/* 이분 탐색 · 정렬 · 힙 — 실행형이 각각 12·28·17문항뿐이던 유형.
   경계 처리(lower/upper bound), 정답에 대한 이분 탐색, 분할 정복 정렬, 힙으로 top-k. */
module.exports = [

/* ───────────── 이분 탐색 ───────────── */
{ track: "algo", k: "처음으로 target 이상 · lowerBound", cat: "internals",
  q: "오름차순 배열에서 <code>target</code> <b>이상인 값이 처음 나오는 자리</b>를 돌려주세요. 그런 값이 없으면 배열 길이를 돌려줍니다.",
  src: "function lowerBound(xs, target) {\n  // TODO: 답이 될 수 있는 구간을 절반씩 줄이세요\n  return 0;\n}",
  sol: "function lowerBound(xs, target) {\n  let lo = 0;\n  let hi = xs.length;\n  while (lo < hi) {\n    const mid = (lo + hi) >> 1;\n    if (xs[mid] < target) lo = mid + 1;\n    else hi = mid;\n  }\n  return lo;\n}",
  tests: [["lowerBound([1,2,4,4,5],4)", "2"],
    ["lowerBound([1,2,4,4,5],3)", "2"],
    ["lowerBound([1,2,3],10)", "3"],
    ["lowerBound([1,2,3],0)", "0"]],
  edge: [["lowerBound([],1)", "0"], ["lowerBound([5,5,5],5)", "0"]],
  ex: "'<b>찾았으면 멈춘다</b>' 가 아니라 '<b>답이 될 수 있는 구간을 좁힌다</b>' 로 쓰는 것이 경계 이분 탐색입니다. 같은 값이 여러 개일 때 <b>첫 자리</b>를 정확히 집어냅니다.\n불변식은 '<code>lo</code> 왼쪽은 전부 target 미만, <code>hi</code> 오른쪽은 전부 target 이상' 입니다. 이 문장이 참인 채로 구간이 줄어들고, <code>lo === hi</code> 가 되면 그 자리가 답입니다.\n<code>hi</code> 를 <code>xs.length - 1</code> 이 아니라 <b><code>xs.length</code></b> 로 두는 것이 핵심입니다. '아무 것도 target 이상이 아님' 이라는 답을 표현할 자리가 필요하기 때문입니다.\n같은 값이 없어도 <b>끼워 넣을 자리</b>를 알려 줍니다. 정렬을 유지하며 삽입하기, 랭킹 매기기, 구간 개수 세기가 모두 이 함수 위에서 만들어집니다." },

{ track: "algo", k: "처음으로 target 초과 · upperBound", cat: "internals",
  q: "오름차순 배열에서 <code>target</code> <b>보다 큰 값이 처음 나오는 자리</b>를 돌려주세요. 앞 문제와 부등호 하나만 다릅니다.",
  src: "function upperBound(xs, target) {\n  // TODO: 같은 값도 왼쪽으로 넘겨야 합니다\n  return 0;\n}",
  sol: "function upperBound(xs, target) {\n  let lo = 0;\n  let hi = xs.length;\n  while (lo < hi) {\n    const mid = (lo + hi) >> 1;\n    if (xs[mid] <= target) lo = mid + 1;\n    else hi = mid;\n  }\n  return lo;\n}",
  tests: [["upperBound([1,2,4,4,5],4)", "4"],
    ["upperBound([1,2,4,4,5],3)", "2"],
    ["upperBound([1,2,3],3)", "3"],
    ["upperBound([1,2,3],0)", "0"]],
  edge: [["upperBound([],1)", "0"], ["upperBound([5,5,5],5)", "3"]],
  ex: "<code>&lt;</code> 를 <code>&lt;=</code> 로 바꾼 것이 전부입니다. 같은 값을 '왼쪽으로 넘겨' 버리므로 마지막 같은 값 <b>다음 자리</b>가 나옵니다.\n두 함수를 함께 두면 <b>같은 값의 개수</b>가 <code>upperBound − lowerBound</code> 로 바로 나옵니다. 정렬된 로그에서 특정 시각대의 건수를 세는 일이 이 뺄셈 하나입니다.\n부등호 하나에 의미가 걸려 있으므로, 이런 함수는 <b>이름으로 규약을 못 박아</b> 두어야 합니다. C++ 의 <code>lower_bound</code>·<code>upper_bound</code>, 파이썬의 <code>bisect_left</code>·<code>bisect_right</code> 가 같은 짝입니다.\n직접 짤 때 가장 흔한 실수는 <code>mid</code> 를 <code>(lo + hi) / 2</code> 로 두고 내림을 잊는 것입니다. 여기서는 <code>&gt;&gt; 1</code> 이 그 역할을 하지만, 값이 2³¹ 을 넘으면 비트 연산이 무너지므로 큰 범위에서는 <code>Math.floor</code> 를 씁니다." },

{ track: "algo", k: "회전된 정렬 배열 탐색 · searchRotated", cat: "internals",
  q: "오름차순 배열을 어느 지점에서 <b>회전시킨</b> 배열에서 <code>target</code> 의 자리를 찾아 주세요. 없으면 <code>-1</code> 입니다. 중복 값은 없습니다.",
  src: "function searchRotated(xs, target) {\n  // TODO: 절반 중 한쪽은 반드시 정렬되어 있습니다\n  return -1;\n}",
  sol: "function searchRotated(xs, target) {\n  let lo = 0;\n  let hi = xs.length - 1;\n  while (lo <= hi) {\n    const mid = (lo + hi) >> 1;\n    if (xs[mid] === target) return mid;\n    if (xs[lo] <= xs[mid]) {\n      if (xs[lo] <= target && target < xs[mid]) hi = mid - 1;\n      else lo = mid + 1;\n    } else if (xs[mid] < target && target <= xs[hi]) lo = mid + 1;\n    else hi = mid - 1;\n  }\n  return -1;\n}",
  tests: [["searchRotated([4,5,6,7,0,1,2],0)", "4"],
    ["searchRotated([4,5,6,7,0,1,2],3)", "-1"],
    ["searchRotated([1],1)", "0"],
    ["searchRotated([5,1,3],3)", "2"]],
  edge: [["searchRotated([],1)", "-1"], ["searchRotated([3,1],1)", "1"]],
  ex: "회전된 배열을 반으로 자르면 <b>둘 중 한쪽은 반드시 완전히 정렬</b>되어 있습니다. 그 한쪽을 찾아 target 이 그 안에 있는지 보면, 여전히 절반씩 줄일 수 있습니다.\n<code>xs[lo] &lt;= xs[mid]</code> 로 왼쪽이 정렬됐는지 판단합니다. 등호가 필요한 이유는 원소가 둘일 때 <code>lo === mid</code> 가 되기 때문입니다 — 등호를 빼면 <code>[3,1]</code> 에서 답을 놓칩니다.\n안쪽 조건의 <b>등호 위치</b>도 정확해야 합니다. 정렬된 쪽의 양 끝은 포함, 반대쪽 끝(<code>xs[mid]</code>)은 이미 비교했으므로 제외입니다.\n<b>중복이 있으면</b> 이 판단이 무너집니다. <code>[1,1,1,0,1]</code> 처럼 양 끝과 가운데가 모두 같으면 어느 쪽이 정렬됐는지 알 수 없어 최악에는 O(n) 이 됩니다 — 문제에서 '중복 없음' 을 못 박는 이유입니다." },

{ track: "algo", k: "정답에 대한 이분 탐색 · minCapacity", cat: "internals",
  q: "짐을 <b>순서를 바꾸지 않고</b> <code>days</code> 일 안에 모두 나르려면 하루 최대 적재량이 얼마여야 하는지, <b>가능한 최솟값</b>을 돌려주세요.",
  src: "function minCapacity(weights, days) {\n  // TODO: 답 자체를 이분 탐색하세요 — '이 용량이면 되는가?' 를 판정합니다\n  return 0;\n}",
  sol: "function minCapacity(weights, days) {\n  const need = (cap) => {\n    let used = 1;\n    let cur = 0;\n    for (const w of weights) {\n      if (w > cap) return Infinity;\n      if (cur + w > cap) { used++; cur = 0; }\n      cur += w;\n    }\n    return used;\n  };\n  let lo = 1;\n  let hi = weights.reduce((s, w) => s + w, 0);\n  while (lo < hi) {\n    const mid = Math.floor((lo + hi) / 2);\n    if (need(mid) <= days) hi = mid;\n    else lo = mid + 1;\n  }\n  return lo;\n}",
  tests: [["minCapacity([1,2,3,4,5,6,7,8,9,10],5)", "15"],
    ["minCapacity([3,2,2,4,1,4],3)", "6"],
    ["minCapacity([1,2,3,1,1],4)", "3"],
    ["minCapacity([1,1,1],3)", "1"]],
  edge: [["minCapacity([1],1)", "1"], ["minCapacity([5,5],1)", "10"]],
  ex: "배열이 아니라 <b>답의 범위</b>를 이분 탐색합니다. '용량 X 로 가능한가?' 라는 판정 함수가 <b>단조</b>이기 때문에 가능합니다 — 어떤 X 로 되면 그보다 큰 값으로도 반드시 됩니다.\n그래서 '되는 것 중 가장 작은 것' 을 찾는 문제가 되고, 이것은 <code>lowerBound</code> 와 같은 모양입니다. 판정 함수만 갈아 끼우면 됩니다.\n탐색 범위를 <b>가장 무거운 짐 ~ 전체 합</b> 으로 잡는 것이 정석입니다. 여기서는 아래를 1로 두고 <code>w &gt; cap</code> 일 때 무한대를 돌려주어 같은 효과를 냈습니다 — 어느 쪽이든 <b>답이 반드시 범위 안에 있음</b>을 보장해야 합니다.\n이 패턴은 '최대를 최소로' 문제 전반에 쓰입니다 — 나무 자르기, 랜선 나누기, 공유기 설치, 그리고 실무의 배치 크기·타임아웃 튜닝까지 같은 틀입니다." },

{ track: "algo", k: "정수 제곱근 · sqrtFloor", cat: "internals",
  q: "<code>n</code> 의 제곱근을 <b>내림한 정수</b>를 돌려주세요. 부동소수 함수를 쓰지 말고 이분 탐색으로 구합니다.",
  src: "function sqrtFloor(n) {\n  // TODO: mid * mid 가 n 이하인 가장 큰 mid 를 찾으세요\n  return 0;\n}",
  sol: "function sqrtFloor(n) {\n  if (n < 2) return n;\n  let lo = 1;\n  let hi = n;\n  while (lo < hi) {\n    const mid = Math.floor((lo + hi + 1) / 2);\n    if (mid * mid <= n) lo = mid;\n    else hi = mid - 1;\n  }\n  return lo;\n}",
  tests: [["sqrtFloor(8)", "2"], ["sqrtFloor(16)", "4"], ["sqrtFloor(1)", "1"], ["sqrtFloor(0)", "0"]],
  edge: [["sqrtFloor(2)", "1"], ["sqrtFloor(9999)", "99"]],
  ex: "'<b>조건을 만족하는 가장 큰 값</b>' 을 찾는 이분 탐색입니다. 앞의 <code>lowerBound</code> 와 방향이 반대라 <code>mid</code> 계산도 달라집니다.\n<code>(lo + hi + 1) / 2</code> 에서 <b>+ 1 을 빠뜨리면 무한 루프</b>입니다. <code>lo = mid</code> 로 갱신하는 쪽에서는 <code>mid</code> 가 내림 때문에 <code>lo</code> 와 같아질 수 있어 구간이 줄지 않습니다 — 이분 탐색에서 가장 흔한 무한 루프입니다.\n짝으로 기억하면 안전합니다. <code>hi = mid</code> 로 줄이면 내림, <code>lo = mid</code> 로 줄이면 <b>올림</b> 입니다.\n부동소수 <code>Math.sqrt</code> 는 큰 수에서 오차가 납니다. 정확한 정수 답이 필요하면 이분 탐색으로 구하거나, 근사값을 얻은 뒤 <b>양옆을 확인</b>해 보정해야 합니다." },

/* ───────────── 정렬 ───────────── */
{ track: "algo", k: "병합 정렬 · mergeSort", cat: "internals",
  q: "배열을 <b>분할 정복</b>으로 정렬해 새 배열로 돌려주세요. 원본은 고치지 않고, 같은 값의 순서는 유지합니다.",
  src: "function mergeSort(xs) {\n  // TODO: 반으로 나눠 각각 정렬한 뒤 합치세요\n  return xs.slice();\n}",
  sol: "function mergeSort(xs) {\n  if (xs.length < 2) return xs.slice();\n  const half = xs.length >> 1;\n  const a = mergeSort(xs.slice(0, half));\n  const b = mergeSort(xs.slice(half));\n  const merged = [];\n  let i = 0;\n  let j = 0;\n  while (i < a.length && j < b.length) {\n    if (a[i] <= b[j]) merged.push(a[i++]);\n    else merged.push(b[j++]);\n  }\n  return merged.concat(a.slice(i), b.slice(j));\n}",
  tests: [["mergeSort([5,2,9,1])", "[1,2,5,9]"],
    ["mergeSort([3,3,1])", "[1,3,3]"],
    ["mergeSort([1])", "[1]"],
    ["mergeSort([2,1])", "[1,2]"]],
  edge: [["mergeSort([])", "[]"], ["mergeSort([4,4,4])", "[4,4,4]"]],
  ex: "분할 정복의 표준형입니다. 반으로 나누는 데 O(log n) 단계, 각 단계에서 합치는 데 O(n) 이므로 <b>언제나</b> O(n log n) 입니다 — 입력이 어떻게 생겼든 흔들리지 않습니다.\n<code>a[i] &lt;= b[j]</code> 의 등호가 <b>안정성</b>을 만듭니다. 같은 값이면 앞쪽(왼쪽 절반)을 먼저 담으므로 원래 순서가 보존되고, 그래서 '이름으로 정렬한 뒤 부서로 정렬' 같은 다단계 정렬이 성립합니다.\n대신 합칠 자리가 따로 필요해 <b>메모리를 O(n)</b> 씁니다. 퀵 정렬은 제자리에서 하지만 최악이 O(n²) 이고 안정하지 않습니다 — 두 정렬은 서로 다른 것을 포기합니다.\n메모리에 안 들어가는 데이터에도 그대로 씁니다. 조각으로 나눠 각각 정렬해 파일로 쓰고, 순차로 읽으며 합치는 것이 <b>외부 병합 정렬</b>입니다." },

{ track: "algo", k: "k번째 작은 수 · quickSelect", cat: "internals",
  q: "정렬하지 않고 <b><code>k</code>번째로 작은 값</b>을 찾아 주세요(<code>k</code> 는 1부터). 범위를 벗어나면 <code>null</code> 이고, 원본은 고치지 않습니다.",
  src: "function quickSelect(xs, k) {\n  // TODO: 분할한 뒤, 답이 있는 쪽만 다시 보세요\n  return null;\n}",
  sol: "function quickSelect(xs, k) {\n  if (k < 1 || k > xs.length) return null;\n  const arr = xs.slice();\n  let lo = 0;\n  let hi = arr.length - 1;\n  for (;;) {\n    const pivot = arr[hi];\n    let store = lo;\n    for (let i = lo; i < hi; i++) {\n      if (arr[i] < pivot) {\n        [arr[i], arr[store]] = [arr[store], arr[i]];\n        store++;\n      }\n    }\n    [arr[hi], arr[store]] = [arr[store], arr[hi]];\n    if (store === k - 1) return arr[store];\n    if (store < k - 1) lo = store + 1;\n    else hi = store - 1;\n  }\n}",
  tests: [["quickSelect([3,1,2],2)", "2"],
    ["quickSelect([7,10,4,3,20,15],3)", "7"],
    ["quickSelect([1],1)", "1"],
    ["quickSelect([5,5,5],2)", "5"]],
  edge: [["quickSelect([1,2],5)", "null"], ["quickSelect([],1)", "null"]],
  ex: "퀵 정렬과 같은 분할을 쓰되, <b>한쪽만</b> 다시 봅니다. 분할 후 기준값의 자리가 확정되므로, 찾는 자리가 그보다 왼쪽인지 오른쪽인지가 바로 정해집니다.\n버리는 절반 덕분에 평균 O(n) 입니다. 전부 정렬해서 <code>k</code> 번째를 꺼내면 O(n log n) 이므로, 하나만 필요할 때는 정렬이 과합니다.\n최악은 O(n²) 입니다. 기준값을 늘 한쪽 끝으로 잡으면 이미 정렬된 입력에서 분할이 1과 n−1 로 갈립니다 — 실무에서는 <b>기준값을 무작위로</b> 고르거나 median-of-three 를 씁니다.\n같은 값이 많을 때도 <code>&lt;</code> 기준 분할은 잘 동작합니다. 다만 값이 전부 같으면 매번 한 칸씩만 줄어드므로, 그런 입력이 예상되면 3분할을 씁니다." },

{ track: "algo", k: "역순 쌍 세기 · countInversions", cat: "internals",
  q: "<code>i &lt; j</code> 인데 <code>xs[i] &gt; xs[j]</code> 인 쌍이 몇 개인지 세세요. 이 값이 클수록 배열이 정렬과 멀다는 뜻입니다.",
  src: "function countInversions(xs) {\n  // TODO: 병합하면서 세면 O(n log n) 입니다\n  return 0;\n}",
  sol: "function countInversions(xs) {\n  let pairs = 0;\n  const walk = (arr) => {\n    if (arr.length < 2) return arr;\n    const half = arr.length >> 1;\n    const a = walk(arr.slice(0, half));\n    const b = walk(arr.slice(half));\n    const merged = [];\n    let i = 0;\n    let j = 0;\n    while (i < a.length && j < b.length) {\n      if (a[i] <= b[j]) merged.push(a[i++]);\n      else { pairs += a.length - i; merged.push(b[j++]); }\n    }\n    return merged.concat(a.slice(i), b.slice(j));\n  };\n  walk(xs);\n  return pairs;\n}",
  tests: [["countInversions([2,4,1,3,5])", "3"],
    ["countInversions([5,4,3,2,1])", "10"],
    ["countInversions([1,2,3])", "0"],
    ["countInversions([2,1])", "1"]],
  edge: [["countInversions([])", "0"], ["countInversions([1])", "0"]],
  ex: "모든 쌍을 보면 O(n²) 입니다. 병합 정렬에 <b>세는 줄 하나</b>를 얹으면 O(n log n) 이 됩니다 — 정렬 알고리즘을 <b>계산 도구로</b> 쓰는 예입니다.\n오른쪽 절반의 값을 먼저 담을 때, <b>왼쪽에 남아 있는 원소 전부</b>가 그 값보다 큽니다. 왼쪽이 이미 정렬되어 있으므로 하나씩 세지 않고 <code>a.length - i</code> 로 한 번에 더할 수 있습니다.\n등호 처리에 주의해야 합니다. <code>a[i] &lt;= b[j]</code> 로 두어 같은 값은 역순으로 세지 않습니다 — <b>정의에 <code>&gt;</code> 만 있고 <code>&gt;=</code> 는 없기</b> 때문입니다.\n이 수치는 '두 순위표가 얼마나 다른가' 를 재는 데 쓰입니다. 켄달 타우 상관계수가 바로 역순 쌍의 개수로 정의되고, 추천 순위 비교나 A/B 결과 비교에서 그대로 나옵니다." },

{ track: "algo", k: "점수·이름 순 정렬 · sortByScoreThenName", cat: "internals",
  q: "<code>[이름, 점수]</code> 목록을 <b>점수 내림차순</b>으로, 점수가 같으면 <b>이름 오름차순</b>으로 정렬해 새 배열로 돌려주세요.",
  src: "function sortByScoreThenName(people) {\n  // TODO: 비교 함수는 음수·0·양수를 돌려주어야 합니다\n  return people.slice();\n}",
  sol: "function sortByScoreThenName(people) {\n  return people.slice().sort((a, b) => {\n    if (a[1] !== b[1]) return b[1] - a[1];\n    if (a[0] < b[0]) return -1;\n    if (a[0] > b[0]) return 1;\n    return 0;\n  });\n}",
  tests: [["sortByScoreThenName([['bob',80],['amy',90],['cid',80]])", "[['amy',90],['bob',80],['cid',80]]"],
    ["sortByScoreThenName([['b',1],['a',1]])", "[['a',1],['b',1]]"],
    ["sortByScoreThenName([['a',1]])", "[['a',1]]"],
    ["sortByScoreThenName([['z',5],['a',9]])", "[['a',9],['z',5]]"]],
  edge: [["sortByScoreThenName([])", "[]"], ["sortByScoreThenName([['a',2],['a',2]])", "[['a',2],['a',2]]"]],
  ex: "다중 키 정렬은 <b>앞 키가 같을 때만</b> 다음 키를 봅니다. 조건을 순서대로 나열하고 결판이 나면 즉시 돌려주는 것이 정석입니다.\n비교 함수는 <b>음수·0·양수</b>를 돌려주어야 합니다. <code>true/false</code> 를 돌려주면 <code>true</code> 가 1로, <code>false</code> 가 0으로 변환되어 '작다' 를 표현할 방법이 없어집니다 — 결과가 브라우저마다 달라지는 고전적인 버그입니다.\n문자열에 <code>b - a</code> 같은 뺄셈은 쓸 수 없습니다. <code>NaN</code> 이 나와 비교가 무너지므로 <b>대소 비교로 −1/1</b> 을 직접 돌려주어야 합니다.\n<code>sort</code> 는 <b>원본을 제자리에서 고칩니다.</b> 모듈에서 공유하는 배열이라면 첫 호출의 흔적이 이후 모든 호출에 남으므로, <code>slice()</code> 로 복사한 뒤 정렬하는 습관이 안전합니다." },

/* ───────────── 힙과 빈도 ───────────── */
{ track: "algo", k: "가장 큰 k 개 · topK", cat: "internals",
  q: "가장 큰 <code>k</code> 개를 <b>내림차순</b>으로 돌려주세요. 전체를 정렬하지 말고 <b>크기 k 짜리 최소 힙</b>을 유지합니다.",
  src: "function topK(xs, k) {\n  // TODO: 힙 크기가 k 를 넘으면 가장 작은 것을 버리세요\n  return [];\n}",
  sol: "function topK(xs, k) {\n  if (k <= 0) return [];\n  const heap = [];\n  const up = (i) => {\n    while (i > 0 && heap[(i - 1) >> 1] > heap[i]) {\n      const p = (i - 1) >> 1;\n      [heap[p], heap[i]] = [heap[i], heap[p]];\n      i = p;\n    }\n  };\n  const down = (i) => {\n    let s = i;\n    if (2 * i + 1 < heap.length && heap[2 * i + 1] < heap[s]) s = 2 * i + 1;\n    if (2 * i + 2 < heap.length && heap[2 * i + 2] < heap[s]) s = 2 * i + 2;\n    if (s === i) return;\n    [heap[s], heap[i]] = [heap[i], heap[s]];\n    down(s);\n  };\n  xs.forEach((x) => {\n    heap.push(x);\n    up(heap.length - 1);\n    if (heap.length > k) { heap[0] = heap[heap.length - 1]; heap.pop(); down(0); }\n  });\n  return heap.slice().sort((a, b) => b - a);\n}",
  tests: [["topK([3,1,5,12,2,11],3)", "[12,11,5]"],
    ["topK([1,2,3],5)", "[3,2,1]"],
    ["topK([4,4,4],2)", "[4,4]"],
    ["topK([7],1)", "[7]"]],
  edge: [["topK([],3)", "[]"], ["topK([1,2],0)", "[]"]],
  ex: "'가장 큰 k 개' 를 <b>최소</b> 힙으로 관리하는 것이 처음에는 거꾸로 느껴집니다. 뿌리에 <b>후보 중 가장 작은 값</b>이 있어야, 새 값이 들어올 때 <b>버릴 것</b>을 O(1) 에 찾을 수 있기 때문입니다.\n전체를 정렬하면 O(n log n), 힙을 쓰면 O(n log k) 입니다. n 이 1억이고 k 가 10이면 차이가 결정적이고, 무엇보다 <b>데이터를 한 번에 들고 있지 않아도</b> 됩니다 — 스트리밍에서 쓸 수 있는 이유입니다.\n힙 연산은 두 줄기입니다. 넣을 때는 <b>위로 올리고</b>(<code>up</code>), 뿌리를 지울 때는 마지막 원소를 뿌리에 놓고 <b>아래로 내립니다</b>(<code>down</code>). 배열 하나로 완전 이진 트리를 표현하므로 자식은 <code>2i+1</code>·<code>2i+2</code> 입니다.\n실무에서는 상위 N 개 인기 검색어, 가장 느린 쿼리 N 개, 로그의 상위 오류 N 종을 이렇게 뽑습니다. 표준 라이브러리에 우선순위 큐가 있으면 그것을 쓰되, <b>왜 최소 힙인지</b>는 알고 써야 합니다." },

{ track: "algo", k: "k 개 정렬 배열 병합 · mergeKSorted", cat: "internals",
  q: "정렬된 배열 여러 개를 <b>하나의 정렬된 배열</b>로 합쳐 돌려주세요. 둘씩 짝지어 합치는 방식으로 구현합니다.",
  src: "function mergeKSorted(lists) {\n  // TODO: 둘씩 합쳐 개수를 절반으로 줄여 나가세요\n  return [];\n}",
  sol: "function mergeKSorted(lists) {\n  const two = (a, b) => {\n    const merged = [];\n    let i = 0;\n    let j = 0;\n    while (i < a.length && j < b.length) merged.push(a[i] <= b[j] ? a[i++] : b[j++]);\n    return merged.concat(a.slice(i), b.slice(j));\n  };\n  let cur = lists.slice();\n  while (cur.length > 1) {\n    const paired = [];\n    for (let i = 0; i < cur.length; i += 2) {\n      paired.push(i + 1 < cur.length ? two(cur[i], cur[i + 1]) : cur[i]);\n    }\n    cur = paired;\n  }\n  return cur[0] || [];\n}",
  tests: [["mergeKSorted([[1,4,5],[1,3,4],[2,6]])", "[1,1,2,3,4,4,5,6]"],
    ["mergeKSorted([[1]])", "[1]"],
    ["mergeKSorted([])", "[]"],
    ["mergeKSorted([[],[1,2]])", "[1,2]"]],
  edge: [["mergeKSorted([[],[]])", "[]"], ["mergeKSorted([[3],[1],[2]])", "[1,2,3]"]],
  ex: "앞에서부터 하나씩 이어 붙이면 <b>같은 원소를 여러 번 옮깁니다.</b> 첫 배열의 값들이 k 번 복사되어 전체가 O(kn) 이 됩니다.\n둘씩 짝지어 합치면 단계 수가 <code>log k</code> 로 줄어 O(n log k) 가 됩니다. 각 단계에서 모든 원소를 한 번씩만 만지므로, 토너먼트를 올라가듯 절반씩 줄어듭니다.\n최소 힙으로도 같은 복잡도를 얻습니다. 각 배열의 앞 원소를 힙에 넣고 가장 작은 것을 꺼내며 진행하는데, <b>스트리밍</b>에 적합하고 메모리를 덜 씁니다.\n홀수 개일 때 마지막 하나를 <b>그대로 올리는</b> 처리를 빠뜨리기 쉽습니다. 이 한 줄이 없으면 배열이 조용히 사라져 결과가 짧아집니다." },

{ track: "algo", k: "빈도 상위 k 개 · topFrequent", cat: "internals",
  q: "가장 자주 나온 수 <code>k</code> 개를 돌려주세요. <b>빈도가 높은 순</b>이고, 빈도가 같으면 <b>값이 작은 순</b>입니다.",
  src: "function topFrequent(xs, k) {\n  // TODO: 세고 나서, 빈도를 자리 번호로 쓰는 통에 담아 보세요\n  return [];\n}",
  sol: "function topFrequent(xs, k) {\n  const cnt = new Map();\n  xs.forEach((x) => cnt.set(x, (cnt.get(x) || 0) + 1));\n  const buckets = [];\n  cnt.forEach((c, v) => {\n    if (!buckets[c]) buckets[c] = [];\n    buckets[c].push(v);\n  });\n  const picked = [];\n  for (let c = buckets.length - 1; c >= 1 && picked.length < k; c--) {\n    if (!buckets[c]) continue;\n    buckets[c].sort((a, b) => a - b);\n    buckets[c].forEach((v) => { if (picked.length < k) picked.push(v); });\n  }\n  return picked;\n}",
  tests: [["topFrequent([1,1,1,2,2,3],2)", "[1,2]"],
    ["topFrequent([1],1)", "[1]"],
    ["topFrequent([1,2],2)", "[1,2]"],
    ["topFrequent([4,4,3,3,2],2)", "[3,4]"]],
  edge: [["topFrequent([],1)", "[]"], ["topFrequent([5,5],5)", "[5]"]],
  ex: "해시로 세고, <b>빈도를 자리 번호로 쓰는 통</b>에 담습니다. 빈도는 0 이상 n 이하이므로 통의 개수가 n + 1 개면 충분하고, 뒤에서부터 훑으면 정렬 없이 빈도 순이 나옵니다.\n이것이 <b>버킷 정렬</b>의 발상입니다. 값의 범위가 좁으면 비교 정렬의 O(n log n) 한계를 우회할 수 있습니다 — 비교를 하지 않기 때문입니다.\n힙으로 상위 k 개를 뽑으면 O(n log k) 이고, 여기서는 O(n + 정렬한 통) 입니다. 동점이 많지 않다면 통 방식이 더 빠릅니다.\n동점 순서를 문제에서 <b>못 박아 주는 것</b>이 중요합니다. 그러지 않으면 해시의 순회 순서에 따라 답이 달라져, 맞는 풀이인데도 채점에서 떨어집니다." },
];
