/* 동적 계획법 — algo 트랙의 실행형을 채우는 마지막 묶음.
   1차원 점화식, 표 채우기, 선택의 DP(배낭·부분집합). */
module.exports = [

/* ───────────── 1차원 DP ───────────── */
{ track: "algo", k: "계단 오르는 방법 수 · climbStairs", cat: "internals",
  q: "한 번에 <b>1칸 또는 2칸</b>을 오를 수 있을 때 <code>n</code> 칸을 오르는 방법의 수를 돌려주세요. <code>n</code> 이 0이면 <code>1</code>(가만히 있는 한 가지)입니다.",
  src: "function climbStairs(n) {\n  // TODO: n번째 답은 바로 앞 두 개만 있으면 나옵니다\n  return n;\n}",
  sol: "function climbStairs(n) {\n  let a = 1;\n  let b = 1;\n  for (let i = 2; i <= n; i++) {\n    const next = a + b;\n    a = b;\n    b = next;\n  }\n  return b;\n}",
  tests: [["climbStairs(2)", "2"],
    ["climbStairs(3)", "3"],
    ["climbStairs(5)", "8"],
    ["climbStairs(10)", "89"]],
  edge: [["climbStairs(0)", "1"], ["climbStairs(1)", "1"]],
  ex: "DP 는 <b>'마지막 한 걸음' 을 묻는 것</b>에서 시작합니다. <code>n</code> 칸에 도착하는 방법은 <code>n-1</code> 에서 한 칸 오르거나 <code>n-2</code> 에서 두 칸 오른 것뿐이므로 <code>f(n) = f(n-1) + f(n-2)</code> 입니다. 점화식이 나오면 코드는 그 문장을 그대로 옮긴 것입니다.\n표 전체를 만들 필요가 없다는 것도 요점입니다. 점화식이 <b>바로 앞 두 개</b>만 보므로 변수 두 개면 충분하고, 메모리가 O(n) 에서 O(1) 로 줄어듭니다. '이 점화식이 몇 칸 뒤까지 보는가' 를 세어 보는 습관이 DP 최적화의 첫 단계입니다.\n초기값 <code>f(0) = 1</code> 이 이상하게 느껴질 수 있습니다. 하지만 <code>f(2) = f(1) + f(0) = 2</code> 가 되려면 반드시 1이어야 합니다. <b>초기값은 감으로 정하는 것이 아니라 점화식이 성립하도록 역산</b>합니다.\n같은 수열이 나오지만 이것을 '피보나치' 로 외우는 것은 도움이 되지 않습니다. 오를 수 있는 칸이 1·2·3이 되면 앞 세 개를 더하는 식으로 바뀌고, 특정 칸이 막혀 있으면 그 칸을 0으로 두면 됩니다. <b>점화식을 세우는 능력</b>이 남는 것입니다." },

{ track: "algo", k: "이웃을 건너뛰는 최대 합 · rob", cat: "internals",
  q: "일렬로 놓인 값에서 <b>이웃한 둘을 함께 고를 수 없을 때</b> 얻을 수 있는 최대 합을 돌려주세요. 값은 0 이상입니다.",
  src: "function rob(xs) {\n  // TODO: 각 자리에서 '고른다 / 안 고른다' 두 상태를 들고 가세요\n  return 0;\n}",
  sol: "function rob(xs) {\n  let skip = 0;\n  let take = 0;\n  xs.forEach((x) => {\n    const nextTake = skip + x;\n    skip = Math.max(skip, take);\n    take = nextTake;\n  });\n  return Math.max(skip, take);\n}",
  tests: [["rob([1,2,3,1])", "4"],
    ["rob([2,7,9,3,1])", "12"],
    ["rob([5])", "5"],
    ["rob([2,1,1,2])", "4"]],
  edge: [["rob([])", "0"], ["rob([0,0])", "0"]],
  ex: "'이웃을 함께 고를 수 없다' 는 제약은 <b>상태를 두 개로 나누면</b> 사라집니다. 각 자리에서 '이 자리를 골랐을 때의 최선' 과 '고르지 않았을 때의 최선' 을 따로 들고 가면, 다음 자리의 답이 이 둘로만 정해집니다.\n갱신 순서가 함정입니다. <code>take</code> 를 먼저 바꾸면 <code>skip</code> 이 <b>이미 갱신된 값</b>을 보게 되어 이웃을 함께 고른 답이 나옵니다. 그래서 새 값을 임시 변수에 담아 두고 <b>동시에 바꾸는 것처럼</b> 만듭니다 — 여러 상태를 한 번에 굴리는 DP 에서 늘 나오는 문제입니다.\n탐욕적으로 '큰 것부터 고른다' 는 틀립니다. 네 번째 테스트의 <code>[2,1,1,2]</code> 에서 가장 큰 값을 먼저 잡는 방식은 양 끝 <code>2 + 2</code> 를 놓칠 수 있습니다. <b>지금의 최선이 나중을 막는</b> 구조에서는 그리디가 아니라 DP 입니다.\n원형으로 이어져 첫 집과 마지막 집이 이웃이 되면, <b>첫 집을 뺀 구간</b>과 <b>마지막 집을 뺀 구간</b>을 각각 풀어 큰 쪽을 답으로 씁니다. 제약이 하나 늘었을 때 문제를 두 번 푸는 이 수법은 자주 쓰입니다." },

{ track: "algo", k: "동전 최소 개수 · coinChange", cat: "internals",
  q: "동전 종류가 주어질 때 <code>amount</code> 를 만드는 <b>최소 동전 개수</b>를 돌려주세요. 만들 수 없으면 <code>-1</code>, 각 동전은 몇 개든 쓸 수 있습니다.",
  src: "function coinChange(coins, amount) {\n  // TODO: 큰 동전부터 쓰는 그리디는 틀립니다. 0원부터 표를 채우세요\n  return -1;\n}",
  sol: "function coinChange(coins, amount) {\n  const best = new Array(amount + 1).fill(Infinity);\n  best[0] = 0;\n  for (let sum = 1; sum <= amount; sum++) {\n    coins.forEach((c) => {\n      if (c <= sum && best[sum - c] + 1 < best[sum]) {\n        best[sum] = best[sum - c] + 1;\n      }\n    });\n  }\n  return best[amount] === Infinity ? -1 : best[amount];\n}",
  tests: [["coinChange([1,2,5],11)", "3"],
    ["coinChange([2],3)", "-1"],
    ["coinChange([1],0)", "0"],
    ["coinChange([1,3,4],6)", "2"]],
  edge: [["coinChange([],5)", "-1"], ["coinChange([5,7],1)", "-1"]],
  ex: "큰 동전부터 쓰는 그리디가 <b>왜 틀리는지</b>를 네 번째 테스트가 보여 줍니다. <code>[1,3,4]</code> 로 6을 만들 때 4를 먼저 쓰면 <code>4+1+1</code> 로 3개지만, 정답은 <code>3+3</code> 으로 2개입니다. 우리가 쓰는 화폐 단위가 우연히 그리디로 풀릴 뿐, <b>일반적으로는 성립하지 않습니다</b>.\n표를 <b>0원부터</b> 채우는 것이 핵심입니다. <code>sum</code> 원을 만드는 최선은 '어떤 동전 <code>c</code> 를 마지막에 썼다' 는 가정 아래 <code>best[sum-c] + 1</code> 이고, 모든 <code>c</code> 중 가장 작은 것이 답입니다. <b>마지막 한 수를 무엇으로 둘지</b>를 전부 시도하는 것이 DP 의 기본형입니다.\n불가능을 <code>Infinity</code> 로 두면 <code>+1</code> 을 해도 여전히 <code>Infinity</code> 라 자연스럽게 전파됩니다. <code>-1</code> 을 표에 그대로 넣으면 <code>-1 + 1 = 0</code> 이 되어 <b>불가능이 최선으로 둔갑</b>합니다. 표 안의 값과 바깥으로 내보내는 값을 다르게 두는 이유입니다.\n'만드는 방법의 가짓수' 를 묻는 문제로 바꾸면 반복 순서가 뒤집힙니다. 동전을 바깥, 금액을 안쪽에 두어야 <b>조합</b>이 세어지고, 지금처럼 두면 순서가 다른 것을 다르게 세는 <b>순열</b>이 됩니다. 같은 표에서 반복 순서 하나가 문제의 정의를 바꿉니다." },

{ track: "algo", k: "최대 부분 합 · maxSubArray", cat: "internals",
  q: "연속한 구간의 합 중 <b>가장 큰 값</b>을 돌려주세요. 구간은 비어 있을 수 없으므로 값이 모두 음수면 그중 가장 큰 값이 답입니다. 빈 배열은 <code>0</code> 입니다.",
  src: "function maxSubArray(xs) {\n  // TODO: 지금까지의 합이 마이너스면 들고 갈 이유가 없습니다\n  return 0;\n}",
  sol: "function maxSubArray(xs) {\n  if (!xs.length) return 0;\n  let cur = xs[0];\n  let best = xs[0];\n  for (let i = 1; i < xs.length; i++) {\n    cur = Math.max(xs[i], cur + xs[i]);\n    if (cur > best) best = cur;\n  }\n  return best;\n}",
  tests: [["maxSubArray([-2,1,-3,4,-1,2,1,-5,4])", "6"],
    ["maxSubArray([1])", "1"],
    ["maxSubArray([-3,-1,-2])", "-1"],
    ["maxSubArray([5,4,-1,7,8])", "23"]],
  edge: [["maxSubArray([])", "0"], ["maxSubArray([-1])", "-1"]],
  ex: "카데인 알고리즘의 한 줄 요약은 <b>'지금까지의 합이 짐이 되면 버린다'</b> 입니다. <code>cur + xs[i]</code> 가 <code>xs[i]</code> 보다 작다는 것은 앞의 합이 음수라는 뜻이고, 음수를 들고 가면 뒤의 어떤 구간도 나빠지기만 합니다.\n<code>cur</code> 과 <code>best</code> 를 나누는 것이 중요합니다. <code>cur</code> 은 <b>이 자리에서 끝나는</b> 구간의 최선, <code>best</code> 는 <b>지금까지 본 전부</b> 중 최선입니다. 하나로 합치려 하면 반드시 틀립니다 — 지금 구간이 나빠져도 과거의 좋았던 답은 남아 있어야 하기 때문입니다.\n초기값을 <code>0</code> 으로 두는 것이 가장 흔한 실수입니다. 세 번째 테스트처럼 값이 모두 음수면 <b>있지도 않은 빈 구간</b>이 답으로 나옵니다. '구간은 비어 있을 수 없다' 는 조건이 곧 <b>첫 원소로 초기화하라</b>는 지시입니다.\n어디서부터 어디까지인지를 알아야 한다면 <code>cur</code> 을 새로 시작할 때의 인덱스를 함께 기록하면 됩니다. 주가의 최대 상승 구간, 로그에서 오류가 몰린 시간대 찾기가 실무에서 만나는 같은 문제입니다." },

/* ───────────── 표를 채우는 DP ───────────── */
{ track: "algo", k: "장애물 격자의 경로 수 · uniquePaths", cat: "internals",
  q: "<code>0</code> 은 빈 칸, <code>1</code> 은 장애물인 격자에서 <b>왼쪽 위에서 오른쪽 아래까지</b> 오른쪽·아래로만 가는 경로의 수를 돌려주세요.",
  src: "function uniquePaths(grid) {\n  // TODO: 각 칸의 경로 수는 위와 왼쪽에서 온 것의 합입니다\n  return 1;\n}",
  sol: "function uniquePaths(grid) {\n  const rows = grid.length;\n  if (!rows) return 0;\n  const cols = grid[0].length;\n  const ways = new Array(cols).fill(0);\n  ways[0] = grid[0][0] === 1 ? 0 : 1;\n  for (let r = 0; r < rows; r++) {\n    for (let c = 0; c < cols; c++) {\n      if (grid[r][c] === 1) ways[c] = 0;\n      else if (c > 0) ways[c] += ways[c - 1];\n    }\n  }\n  return ways[cols - 1];\n}",
  tests: [["uniquePaths([[0,0],[0,0]])", "2"],
    ["uniquePaths([[0,0,0],[0,1,0],[0,0,0]])", "2"],
    ["uniquePaths([[0,1],[0,0]])", "1"],
    ["uniquePaths([[1,0],[0,0]])", "0"]],
  edge: [["uniquePaths([[0]])", "1"], ["uniquePaths([[0,0],[1,0]])", "1"]],
  ex: "한 칸에 도착하는 경로 수는 <b>위에서 온 것 + 왼쪽에서 온 것</b>입니다. 오른쪽·아래로만 가므로 이 둘 말고는 들어올 곳이 없고, 그래서 표를 위에서 아래로·왼쪽에서 오른쪽으로 한 번만 채우면 끝납니다.\n장애물은 <b>0으로 덮어쓰는 것</b>으로 표현합니다. 그 칸을 지나는 경로가 없다는 뜻이라, 아래·오른쪽으로 0이 자연스럽게 번져 나갑니다. 별도 분기를 만들지 않고 <b>값 하나로 상태를 표현</b>하는 것이 표 DP 를 짧게 만드는 요령입니다.\n한 줄짜리 배열만 쓰는 것에 주목하세요. 표의 각 칸은 <b>바로 위</b>와 <b>바로 왼쪽</b>만 보므로, 배열 하나를 덮어쓰며 굴리면 <code>ways[c]</code> 는 아직 갱신 전이라 '위' 이고 <code>ways[c-1]</code> 은 이미 갱신되어 '왼쪽' 입니다. 이 <b>덮어쓰기 순서</b>가 곧 점화식입니다.\n출발 칸이 막혀 있는 경우를 따로 처리한 이유는 초기값을 <b>표 밖에서</b> 정해야 하기 때문입니다. 네 번째 테스트가 그 자리이고, 이런 '시작부터 불가능' 케이스를 빠뜨리면 답이 1로 나옵니다." },

{ track: "algo", k: "최소 비용 경로 · minPathSum", cat: "internals",
  q: "각 칸에 비용이 적힌 격자에서 왼쪽 위부터 오른쪽 아래까지 <b>오른쪽·아래로만</b> 갈 때 지나는 칸 비용의 최소 합을 돌려주세요.",
  src: "function minPathSum(grid) {\n  // TODO: 위와 왼쪽 중 싼 쪽에서 와서 현재 칸 비용을 더합니다\n  return 0;\n}",
  sol: "function minPathSum(grid) {\n  const rows = grid.length;\n  if (!rows) return 0;\n  const cols = grid[0].length;\n  const best = new Array(cols).fill(Infinity);\n  best[0] = 0;\n  for (let r = 0; r < rows; r++) {\n    for (let c = 0; c < cols; c++) {\n      const from = c > 0 ? Math.min(best[c], best[c - 1]) : best[c];\n      best[c] = from + grid[r][c];\n    }\n  }\n  return best[cols - 1];\n}",
  tests: [["minPathSum([[1,3,1],[1,5,1],[4,2,1]])", "7"],
    ["minPathSum([[1,2],[1,1]])", "3"],
    ["minPathSum([[5]])", "5"],
    ["minPathSum([[1,2,3]])", "6"]],
  edge: [["minPathSum([[7]])", "7"], ["minPathSum([[1],[2],[3]])", "6"]],
  ex: "앞 문제와 <b>표의 모양은 같고 합치는 방식만 다릅니다</b>. 경로 수는 더하기, 최소 비용은 <code>Math.min</code> 입니다. 표 DP 를 여러 개 풀다 보면 이 골격이 같고 연산만 바뀐다는 것이 보이는데, 그 지점부터 새 문제가 쉬워집니다.\n첫 행과 첫 열을 따로 채우는 코드가 많지만, 여기서는 <b>초기값을 <code>Infinity</code></b> 로 두어 그 분기를 없앴습니다. 첫 행에서는 왼쪽 값만 유효하고 위쪽은 <code>Infinity</code> 라 <code>min</code> 이 알아서 왼쪽을 고릅니다. <b>불가능을 큰 값으로 표현</b>하면 경계 분기가 사라지는 흔한 수법입니다.\n다만 <code>best[0] = 0</code> 이라는 예외는 남습니다. 출발 칸은 '어디서 온 것' 이 없으므로 0에서 시작해 자기 비용만 더해야 하기 때문입니다. <b>초기값 한 칸</b>이 표 전체의 의미를 결정합니다.\n대각선 이동이나 위로 되돌아가는 이동이 허용되면 이 방식이 무너집니다. 표를 한 번에 채우려면 <b>참조하는 칸이 이미 확정되어 있어야</b> 하는데, 되돌아갈 수 있으면 그 순서가 존재하지 않습니다. 그때는 다익스트라로 바꿉니다." },

{ track: "algo", k: "최장 공통 부분수열 · lcsLength", cat: "internals",
  q: "두 문자열의 <b>최장 공통 부분수열</b> 길이를 돌려주세요. 연속일 필요는 없고 순서만 유지하면 됩니다.",
  src: "function lcsLength(a, b) {\n  // TODO: 두 글자가 같을 때와 다를 때를 나눠 표를 채우세요\n  return 0;\n}",
  sol: "function lcsLength(a, b) {\n  let prev = new Array(b.length + 1).fill(0);\n  for (let i = 1; i <= a.length; i++) {\n    const cur = new Array(b.length + 1).fill(0);\n    for (let j = 1; j <= b.length; j++) {\n      if (a[i - 1] === b[j - 1]) cur[j] = prev[j - 1] + 1;\n      else cur[j] = Math.max(prev[j], cur[j - 1]);\n    }\n    prev = cur;\n  }\n  return prev[b.length];\n}",
  tests: [['lcsLength("abcde","ace")', "3"],
    ['lcsLength("abc","abc")', "3"],
    ['lcsLength("abc","def")', "0"],
    ['lcsLength("AGGTAB","GXTXAYB")', "4"]],
  edge: [['lcsLength("","abc")', "0"], ['lcsLength("a","a")', "1"]],
  ex: "두 수열을 나란히 놓는 문제는 거의 모두 <b>2차원 표</b>입니다. <code>표[i][j]</code> 를 'a 의 앞 i 글자와 b 의 앞 j 글자만 봤을 때의 답' 으로 정의하면, 마지막 글자가 같은지 다른지에 따라 두 갈래로 갈립니다.\n같으면 <b>둘 다 쓰고</b> 대각선에서 1을 더합니다. 다르면 <b>둘 중 하나를 포기</b>하고 위·왼쪽 중 큰 쪽을 가져옵니다. 이 두 줄이 점화식의 전부이고, 나머지는 표를 채우는 반복문입니다.\n표가 <code>(m+1) × (n+1)</code> 인 것에 이유가 있습니다. <b>0번째 행과 열</b>이 '한쪽이 빈 문자열' 을 뜻해 답이 0으로 자연스럽게 정해지고, 덕분에 경계 검사가 필요 없습니다. 대신 문자열을 볼 때 <code>a[i-1]</code> 처럼 <b>한 칸 어긋난 인덱스</b>를 써야 하는데, 여기서 실수가 몰립니다.\n행 두 줄만 들고 굴려 메모리를 O(min(m,n)) 으로 줄일 수 있습니다. 다만 <b>실제 부분수열을 복원</b>하려면 표 전체가 필요합니다 — <code>diff</code> 도구가 이 표를 그대로 씁니다. 무엇이 필요한지에 따라 최적화 여부가 갈립니다." },

{ track: "algo", k: "편집 거리 · editDistance", cat: "internals",
  q: "문자열 <code>a</code> 를 <code>b</code> 로 만들 때 필요한 <b>삽입·삭제·교체</b> 연산의 최소 횟수를 돌려주세요.",
  src: "function editDistance(a, b) {\n  // TODO: 세 가지 연산이 각각 표의 어느 칸에서 오는지 정하세요\n  return Math.abs(a.length - b.length);\n}",
  sol: "function editDistance(a, b) {\n  let prev = Array.from({ length: b.length + 1 }, (unused, j) => j);\n  for (let i = 1; i <= a.length; i++) {\n    const cur = [i];\n    for (let j = 1; j <= b.length; j++) {\n      if (a[i - 1] === b[j - 1]) cur[j] = prev[j - 1];\n      else cur[j] = 1 + Math.min(prev[j - 1], prev[j], cur[j - 1]);\n    }\n    prev = cur;\n  }\n  return prev[b.length];\n}",
  tests: [['editDistance("horse","ros")', "3"],
    ['editDistance("intention","execution")', "5"],
    ['editDistance("abc","abc")', "0"],
    ['editDistance("","abc")', "3"]],
  edge: [['editDistance("a","")', "1"], ['editDistance("","")', "0"]],
  ex: "세 연산이 표의 <b>세 이웃 칸</b>에 하나씩 대응합니다. 대각선은 <b>교체</b>, 위는 <b>삭제</b>, 왼쪽은 <b>삽입</b>입니다. 이 대응을 한 번 그려 보면 점화식을 외울 필요가 없어집니다.\n글자가 같으면 <b>연산 없이 대각선 값을 그대로</b> 가져옵니다. 여기에 실수로 <code>+1</code> 을 붙이면 같은 문자열끼리도 거리가 길이만큼 나옵니다. 세 번째 테스트가 그 자리입니다.\n초기 행과 열이 <code>0,1,2,3,…</code> 인 것도 의미가 있습니다. '빈 문자열에서 <code>j</code> 글자를 만들려면 <code>j</code> 번 삽입' 이라는 뜻이라, 네 번째 테스트가 곧 이 초기값을 확인합니다. <b>초기값이 곧 가장 단순한 경우의 답</b>입니다.\n편집 거리는 맞춤법 교정, <code>diff</code>, DNA 정렬, 검색어 오타 보정에 그대로 쓰입니다. 연산마다 비용을 다르게 주거나(삭제는 비싸고 삽입은 싸게) 인접한 두 글자 뒤바뀜을 한 번으로 세는 변형이 있는데, 전부 <b>이 점화식의 항을 고치는 것</b>으로 끝납니다." },

/* ───────────── 선택의 DP ───────────── */
{ track: "algo", k: "0-1 배낭 · knapsack", cat: "internals",
  q: "<code>[무게, 가치]</code> 목록에서 무게 합이 <code>cap</code> 이하가 되도록 골라 <b>가치 합을 최대</b>로 만들어 주세요. 각 물건은 <b>한 번만</b> 쓸 수 있습니다.",
  src: "function knapsack(items, cap) {\n  // TODO: 물건을 하나씩 추가하며 무게별 최선을 갱신하세요\n  return 0;\n}",
  sol: "function knapsack(items, cap) {\n  const best = new Array(cap + 1).fill(0);\n  items.forEach(([w, value]) => {\n    for (let c = cap; c >= w; c--) {\n      if (best[c - w] + value > best[c]) {\n        best[c] = best[c - w] + value;\n      }\n    }\n  });\n  return best[cap];\n}",
  tests: [["knapsack([[1,1],[2,6],[3,10],[5,16]],7)", "22"],
    ["knapsack([[3,4],[4,5],[2,3]],6)", "8"],
    ["knapsack([[5,10]],3)", "0"],
    ["knapsack([[1,1],[1,2],[1,3]],2)", "5"]],
  edge: [["knapsack([],5)", "0"], ["knapsack([[2,9]],2)", "9"]],
  ex: "무게당 가치가 높은 것부터 담는 그리디는 <b>쪼갤 수 있을 때만</b> 옳습니다. 통째로 담아야 하면 첫 테스트처럼 무게 3·5짜리를 고르는 대신 2·5를 골라야 하는 상황이 생겨, 남는 공간을 못 채운 그리디가 집니다.\n안쪽 반복이 <b>거꾸로</b>인 것이 이 코드의 전부입니다. <code>c</code> 를 작은 쪽부터 돌면 <code>best[c-w]</code> 가 <b>이번 물건을 이미 쓴 값</b>이라 같은 물건을 여러 번 담게 됩니다. 거꾸로 돌면 <code>best[c-w]</code> 는 아직 이전 물건들까지의 값이라 '한 번만' 이 지켜집니다. <b>한 줄의 방향</b>이 문제의 정의를 바꿉니다.\n같은 물건을 여러 번 쓸 수 있는 문제라면 <b>반대로 앞에서부터</b> 돌면 됩니다. 두 문제의 코드가 반복 방향만 다르다는 점을 알아 두면 헷갈릴 때 근거를 되짚을 수 있습니다.\n시간은 <code>물건 수 × cap</code> 입니다. <code>cap</code> 이 값의 크기라 <b>입력 길이의 다항식이 아니고</b>, 그래서 이것을 '유사 다항' 이라 부릅니다. <code>cap</code> 이 10억이면 이 방법은 쓸 수 없다는 뜻이므로, 제약 조건을 먼저 확인해야 합니다." },

{ track: "algo", k: "절반으로 나눌 수 있는가 · canPartition", cat: "internals",
  q: "정수 배열을 <b>합이 같은 두 묶음</b>으로 나눌 수 있는지 판정해 주세요. 값은 0 이상입니다.",
  src: "function canPartition(xs) {\n  // TODO: 전체 합의 절반을 만들 수 있는지 묻는 문제로 바꾸세요\n  return false;\n}",
  sol: "function canPartition(xs) {\n  const total = xs.reduce((s, x) => s + x, 0);\n  if (total % 2 !== 0) return false;\n  const half = total / 2;\n  const ok = new Array(half + 1).fill(false);\n  ok[0] = true;\n  xs.forEach((x) => {\n    for (let sum = half; sum >= x; sum--) {\n      if (ok[sum - x]) ok[sum] = true;\n    }\n  });\n  return ok[half];\n}",
  tests: [["canPartition([1,5,11,5])", "true"],
    ["canPartition([1,2,3,5])", "false"],
    ["canPartition([2,2])", "true"],
    ["canPartition([1,1,1])", "false"]],
  edge: [["canPartition([])", "true"], ["canPartition([7])", "false"]],
  ex: "'둘로 나눈다' 를 그대로 풀려 하면 두 묶음을 동시에 관리해야 해서 복잡합니다. <b>한쪽이 정해지면 나머지는 자동</b>이므로, 문제는 '전체 합의 절반을 만들 수 있는가' 하나로 줄어듭니다. <b>문제를 바꿔 쓰는 것</b>이 실제 풀이의 절반입니다.\n합이 홀수면 즉시 거짓입니다. 이 한 줄은 성능이 아니라 <b>정확성</b>을 위한 것이기도 합니다 — 없으면 <code>half</code> 가 소수가 되어 배열 크기가 이상해집니다.\n배낭과 같은 골격이고, 안쪽 반복을 <b>거꾸로</b> 도는 이유도 같습니다. 각 값을 한 번만 써야 하기 때문입니다. 값을 담는 대신 <b>가능한가만</b> 표시하므로 배열이 <code>boolean</code> 이고 메모리가 훨씬 적습니다.\n빈 배열이 <code>true</code> 인 것은 '둘 다 빈 묶음이고 합이 0으로 같다' 는 뜻입니다. 이런 <b>자명한 경우의 정의</b>는 코드를 짜기 전에 정해야 합니다 — 나중에 정하면 이미 짠 코드에 맞춰 정의를 끼워 맞추게 됩니다." },

{ track: "algo", k: "최장 증가 부분수열 · lisLength", cat: "internals",
  q: "<b>엄격히 증가</b>하는 부분수열의 최대 길이를 돌려주세요. 연속일 필요는 없습니다. O(n log n) 으로 푸세요.",
  src: "function lisLength(xs) {\n  // TODO: '길이 k 인 수열의 가능한 가장 작은 끝값'을 배열로 유지하세요\n  return xs.length;\n}",
  sol: "function lisLength(xs) {\n  const tails = [];\n  xs.forEach((x) => {\n    let lo = 0;\n    let hi = tails.length;\n    while (lo < hi) {\n      const mid = (lo + hi) >> 1;\n      if (tails[mid] < x) lo = mid + 1;\n      else hi = mid;\n    }\n    tails[lo] = x;\n  });\n  return tails.length;\n}",
  tests: [["lisLength([10,9,2,5,3,7,101,18])", "4"],
    ["lisLength([0,1,0,3,2,3])", "4"],
    ["lisLength([7,7,7,7])", "1"],
    ["lisLength([1,2,3,4])", "4"]],
  edge: [["lisLength([])", "0"], ["lisLength([5])", "1"]],
  ex: "<code>tails[k]</code> 는 '길이 <code>k+1</code> 인 증가 수열의 <b>가능한 가장 작은 끝값</b>' 입니다. 끝값이 작을수록 뒤에 붙일 수 있는 값이 많아지므로 언제나 유리하고, 이 배열은 <b>항상 오름차순</b>이라 이분 탐색이 가능합니다.\n<code>tails</code> 는 <b>실제 부분수열이 아닙니다.</b> 두 번째 테스트를 손으로 따라가 보면 중간에 실제로는 존재하지 않는 조합이 담기는 것을 볼 수 있습니다. 그래도 <b>길이</b>는 정확합니다 — 이 구분을 못 하면 '수열을 복원하라' 는 변형에서 틀립니다. 복원하려면 각 값이 어느 자리에 들어갔는지를 따로 기록해야 합니다.\n이분 탐색을 <code>lowerBound</code>(처음으로 <code>x</code> 이상)로 두면 <b>엄격히 증가</b>, <code>upperBound</code> 로 두면 <b>같은 값을 허용</b>하는 문제가 됩니다. 세 번째 테스트가 이 차이를 잡습니다. 부등호 하나로 문제의 정의가 바뀌는 자리입니다.\nO(n²) DP — 각 자리마다 앞을 전부 훑기 — 로도 풀리고 그쪽이 이해하기 쉽습니다. 데이터가 작다면 그 편이 나은 코드일 수 있으므로, <b>제약을 보고</b> 고르세요." },

{ track: "algo", k: "사전으로 문장 쪼개기 · wordBreak", cat: "internals",
  q: "문자열을 사전에 있는 단어들로 <b>빈틈없이 쪼갤 수 있는지</b> 판정해 주세요. 같은 단어를 여러 번 써도 됩니다.",
  src: "function wordBreak(s, words) {\n  // TODO: '앞에서 여기까지 쪼갤 수 있다'를 표로 만드세요\n  return false;\n}",
  sol: "function wordBreak(s, words) {\n  const dict = new Set(words);\n  const ok = new Array(s.length + 1).fill(false);\n  ok[0] = true;\n  for (let end = 1; end <= s.length; end++) {\n    for (let start = 0; start < end; start++) {\n      if (ok[start] && dict.has(s.slice(start, end))) {\n        ok[end] = true;\n        break;\n      }\n    }\n  }\n  return ok[s.length];\n}",
  tests: [['wordBreak("leetcode",["leet","code"])', "true"],
    ['wordBreak("applepenapple",["apple","pen"])', "true"],
    ['wordBreak("catsandog",["cats","dog","sand","and","cat"])', "false"],
    ['wordBreak("aaaa",["a","aa"])', "true"]],
  edge: [['wordBreak("",["a"])', "true"], ['wordBreak("ab",["a"])', "false"]],
  ex: "<code>ok[i]</code> 를 '앞에서 <code>i</code> 글자까지 빈틈없이 쪼갤 수 있다' 로 정의하면, <code>ok[end]</code> 는 '어떤 <code>start</code> 에서 끊었을 때 앞이 되고 뒤가 단어인가' 로 정해집니다. <b>정의를 한 문장으로 쓰는 것</b>이 DP 의 첫 단계이고, 그 문장이 곧 반복문의 모양입니다.\n<code>ok[0] = true</code> 는 '빈 문자열은 쪼갤 수 있다' 는 뜻입니다. 이것이 없으면 어떤 문자열도 시작할 수 없어 전부 거짓이 나옵니다. <b>가장 자명한 경우가 표의 씨앗</b>이 됩니다.\n앞에서부터 가장 긴 단어를 잘라 내는 그리디는 세 번째 테스트에서 무너집니다. <code>cats</code> 를 먼저 자르면 <code>andog</code> 가 남아 실패하는데, <code>cat</code> 으로 잘랐어야 <code>sand</code> 로 이어집니다. 이 입력은 '되돌아가야 하는가' 를 물어보는 자리이고, 그 답이 <b>그리디가 아니라 DP</b>인 이유입니다.\n재귀 + 메모이제이션으로 짜도 같은 표가 나옵니다. 메모를 안 붙이면 네 번째 테스트 같은 입력에서 <b>지수 시간</b>이 되는데, 그것이 DP 가 필요한 이유를 가장 잘 보여 줍니다. 사전 검사를 <code>Set</code> 으로 둔 것도 필수입니다 — 배열 <code>includes</code> 로 두면 사전 크기가 곱해집니다." },

];
