/* 그리디 — 실행형이 4문항뿐이던 유형. 구간 스케줄링·정렬 기준 설계·교환 논증을
   개념 설명이 아니라 <b>테스트를 통과시키는 구현</b>으로 다룬다. */
module.exports = [

{ track: "algo", k: "회의 최대 개수 · activitySelection", cat: "internals",
  q: "<code>[시작, 끝]</code> 목록에서 <b>서로 겹치지 않게</b> 고를 수 있는 최대 개수를 돌려주세요. 앞의 끝과 뒤의 시작이 같은 것은 겹치지 않은 것으로 봅니다.",
  src: "function activitySelection(jobs) {\n  // TODO: 무엇을 기준으로 정렬해야 할지 정하세요\n  return 0;\n}",
  sol: "function activitySelection(jobs) {\n  const sorted = jobs.slice().sort((a, b) => a[1] - b[1]);\n  let taken = 0;\n  let free = -Infinity;\n  sorted.forEach(([s, e]) => {\n    if (s >= free) { taken++; free = e; }\n  });\n  return taken;\n}",
  tests: [["activitySelection([[1,3],[2,5],[4,7],[1,8],[5,9],[8,10]])", "3"],
    ["activitySelection([[1,2],[2,3],[3,4]])", "3"],
    ["activitySelection([[1,10],[2,3],[4,5]])", "2"],
    ["activitySelection([[1,4],[2,3]])", "1"]],
  edge: [["activitySelection([])", "0"], ["activitySelection([[5,5]])", "1"]],
  ex: "그리디가 통하는지 아닌지는 <b>정렬 기준</b>이 정합니다. 여기서는 <b>끝나는 시각이 이른 것부터</b> 고르면 최적입니다 — 빨리 끝날수록 뒤에 남는 시간이 길기 때문입니다.\n시작이 이른 것부터 고르면 틀립니다. <code>[[1,10],[2,3],[4,5]]</code> 에서 <code>[1,10]</code> 을 먼저 집으면 하나로 끝나지만, 끝 기준으로 고르면 <code>[2,3]</code> 과 <code>[4,5]</code> 두 개를 얻습니다.\n짧은 것부터 고르는 기준도 틀립니다. 가운데에 낀 짧은 회의 하나가 양옆의 긴 회의 <b>두 개</b>를 동시에 막을 수 있습니다.\n왜 끝 기준이 옳은지는 <b>교환 논증</b>으로 증명합니다 — 최적해의 첫 회의를 '가장 빨리 끝나는 것' 으로 바꿔도 개수는 줄지 않습니다. 그리디를 쓸 때는 이 논증을 머리로라도 한 번 세워 보고 써야 합니다." },

{ track: "algo", k: "구간 병합 · mergeIntervals", cat: "internals",
  q: "겹치거나 맞닿은 구간을 모두 합쳐 돌려주세요. 결과는 <b>시작 오름차순</b>이며, <code>[1,4]</code> 와 <code>[4,5]</code> 처럼 끝점이 닿는 것도 합칩니다.",
  src: "function mergeIntervals(intervals) {\n  // TODO: 정렬한 뒤 앞의 구간과 겹치는지만 보면 됩니다\n  return [];\n}",
  sol: "function mergeIntervals(intervals) {\n  const sorted = intervals.slice().sort((a, b) => a[0] - b[0]);\n  const merged = [];\n  sorted.forEach(([s, e]) => {\n    const prev = merged[merged.length - 1];\n    if (prev && s <= prev[1]) prev[1] = Math.max(prev[1], e);\n    else merged.push([s, e]);\n  });\n  return merged;\n}",
  tests: [["mergeIntervals([[1,3],[2,6],[8,10],[15,18]])", "[[1,6],[8,10],[15,18]]"],
    ["mergeIntervals([[1,4],[4,5]])", "[[1,5]]"],
    ["mergeIntervals([[1,4],[2,3]])", "[[1,4]]"],
    ["mergeIntervals([[5,6],[1,2]])", "[[1,2],[5,6]]"]],
  edge: [["mergeIntervals([])", "[]"], ["mergeIntervals([[1,1]])", "[[1,1]]"]],
  ex: "시작 기준으로 정렬해 두면 <b>바로 앞 구간 하나</b>만 보면 됩니다. 뒤에 올 구간의 시작은 지금 것보다 크거나 같으므로, 지금 것과 안 겹치면 앞의 것들과도 안 겹칩니다.\n합칠 때 끝점을 <code>Math.max</code> 로 갱신하는 것이 중요합니다. <code>[[1,4],[2,3]]</code> 처럼 <b>뒤 구간이 앞에 완전히 들어가는</b> 경우 그냥 덮어쓰면 <code>[1,3]</code> 이 되어 범위가 줄어듭니다.\n결과에 <code>[s, e]</code> 로 <b>새 배열을 만들어</b> 넣는 것도 습관으로 두세요. 입력 배열을 그대로 담으면 이어지는 갱신이 호출자의 데이터를 조용히 고칩니다.\n이 패턴은 캘린더 병합, 로그 구간 압축, IP 대역 정리처럼 실무에서 자주 나옵니다. '정렬 → 앞의 것 하나와 비교' 라는 골격은 그대로입니다." },

{ track: "algo", k: "회의실 최소 개수 · minMeetingRooms", cat: "internals",
  q: "모든 회의를 열려면 회의실이 <b>최소 몇 개</b> 필요한지 돌려주세요. 앞 회의가 끝나는 시각에 다음 회의를 시작할 수 있습니다.",
  src: "function minMeetingRooms(intervals) {\n  // TODO: 시작과 끝을 따로 정렬해 겹친 수를 세어 보세요\n  return 0;\n}",
  sol: "function minMeetingRooms(intervals) {\n  const starts = intervals.map((x) => x[0]).sort((a, b) => a - b);\n  const ends = intervals.map((x) => x[1]).sort((a, b) => a - b);\n  let open = 0;\n  let peak = 0;\n  let j = 0;\n  starts.forEach((s) => {\n    while (j < ends.length && ends[j] <= s) { open--; j++; }\n    open++;\n    if (open > peak) peak = open;\n  });\n  return peak;\n}",
  tests: [["minMeetingRooms([[0,30],[5,10],[15,20]])", "2"],
    ["minMeetingRooms([[7,10],[2,4]])", "1"],
    ["minMeetingRooms([[1,5],[2,6],[3,7]])", "3"],
    ["minMeetingRooms([[1,2],[2,3],[3,4]])", "1"]],
  edge: [["minMeetingRooms([])", "0"], ["minMeetingRooms([[1,10]])", "1"]],
  ex: "답은 '<b>같은 순간에 겹친 회의의 최대 개수</b>' 입니다. 어느 회의가 어느 방에 들어가는지는 알 필요가 없습니다 — 문제를 <b>세는 문제</b>로 바꾸는 것이 첫 단계입니다.\n시작 시각과 끝 시각을 <b>따로 정렬해</b> 훑는 것이 이 풀이의 요령입니다. 시작을 만나면 방이 하나 늘고, 그 시각까지 끝난 회의만큼 방을 돌려받습니다. 짝을 맞출 필요가 없으므로 정렬 두 번이면 끝납니다.\n<code>ends[j] &lt;= s</code> 에서 등호가 붙는지가 규칙을 정합니다. 등호를 빼면 끝나는 순간에 다음 회의를 못 넣게 되어 <code>[[1,2],[2,3],[3,4]]</code> 의 답이 1이 아니라 3이 됩니다.\n같은 일을 <b>최소 힙</b>으로도 풀 수 있습니다 — 끝나는 시각을 힙에 넣고 가장 이른 것이 지났으면 꺼냅니다. 힙 크기가 곧 방 개수이며, 어느 회의가 어느 방인지까지 알아야 할 때 유용합니다." },

{ track: "algo", k: "점프 게임 · canJump", cat: "internals",
  q: "각 칸의 수는 <b>거기서 최대 몇 칸 뛸 수 있는지</b>입니다. 0번 칸에서 출발해 <b>마지막 칸에 닿을 수 있으면</b> <code>true</code> 를 돌려주세요.",
  src: "function canJump(nums) {\n  // TODO: '지금까지 닿을 수 있는 가장 먼 칸' 하나만 들고 가면 됩니다\n  return false;\n}",
  sol: "function canJump(nums) {\n  let reach = 0;\n  for (let i = 0; i < nums.length; i++) {\n    if (i > reach) return false;\n    if (i + nums[i] > reach) reach = i + nums[i];\n  }\n  return true;\n}",
  tests: [["canJump([2,3,1,1,4])", "true"],
    ["canJump([3,2,1,0,4])", "false"],
    ["canJump([0])", "true"],
    ["canJump([1,0,1])", "false"]],
  edge: [["canJump([])", "true"], ["canJump([0,1])", "false"]],
  ex: "완전탐색으로 풀면 갈래가 지수로 늘지만, <b>상태를 하나로 줄이면</b> 한 번 훑는 것으로 끝납니다. 여기서 그 상태는 '지금까지 닿을 수 있는 가장 먼 칸' 입니다.\n어느 경로로 갔는지는 중요하지 않습니다. i 번 칸에 <b>닿을 수만 있다면</b> 거기서 뻗는 거리는 언제나 <code>i + nums[i]</code> 이므로, 최댓값만 들고 가면 충분합니다.\n<code>i &gt; reach</code> 에서 멈추는 것이 핵심입니다. 이 검사를 빼면 닿지도 못하는 칸의 값으로 <code>reach</code> 를 늘려 버려 <code>[3,2,1,0,4]</code> 에서 잘못된 true 가 나옵니다.\n빈 배열을 true 로 두는 것은 '도착할 곳이 없으니 이미 도착' 이라는 규약입니다. 이런 경계는 문제마다 다르므로 <b>테스트로 못 박아 두는</b> 편이 안전합니다." },

{ track: "algo", k: "여러 번 사고팔기 · maxProfit", cat: "internals",
  q: "하루에 한 번만 사거나 팔 수 있고 <b>거래 횟수에 제한이 없을 때</b> 얻을 수 있는 최대 이익을 돌려주세요. 손해를 보지 않아도 됩니다.",
  src: "function maxProfit(prices) {\n  // TODO: 오르는 구간을 어떻게 셀지 생각해 보세요\n  return 0;\n}",
  sol: "function maxProfit(prices) {\n  let total = 0;\n  for (let i = 1; i < prices.length; i++) {\n    if (prices[i] > prices[i - 1]) total += prices[i] - prices[i - 1];\n  }\n  return total;\n}",
  tests: [["maxProfit([7,1,5,3,6,4])", "7"],
    ["maxProfit([1,2,3,4,5])", "4"],
    ["maxProfit([7,6,4,3,1])", "0"],
    ["maxProfit([1,5,1,5])", "8"]],
  edge: [["maxProfit([])", "0"], ["maxProfit([3])", "0"]],
  ex: "'저점에서 사서 고점에서 판다' 를 그대로 짜면 저점·고점을 찾는 분기가 복잡해집니다. 그런데 <b>오르는 날의 차이를 전부 더한 값</b>이 정확히 같은 답입니다.\n<code>[1,3,7]</code> 을 보면 <code>(3-1) + (7-3) = 7-1</code> 입니다. 연속된 상승 구간을 쪼개서 더하든 통째로 더하든 합이 같으므로, 굳이 구간을 찾을 필요가 없습니다.\n이 변환이 코드를 한 줄로 만듭니다. 분기가 사라지면 경계 버그도 함께 사라집니다 — <b>문제를 다시 쓰는 것</b>이 최적화보다 먼저입니다.\n다만 거래 횟수가 <b>제한되면</b> 이 그리디는 무너집니다. '두 번까지' 같은 조건이 붙으면 어떤 상승 구간을 버릴지 골라야 하므로 DP 로 넘어가야 합니다." },

{ track: "algo", k: "순환 주유소 · gasStation", cat: "internals",
  q: "원형으로 놓인 주유소에서 <code>gas[i]</code> 만큼 넣고 다음 칸까지 <code>cost[i]</code> 만큼 씁니다. <b>한 바퀴를 돌 수 있는 출발점</b>의 번호를 돌려주고, 없으면 <code>-1</code> 입니다. 답은 있으면 하나뿐입니다.",
  src: "function gasStation(gas, cost) {\n  // TODO: 도중에 기름이 떨어지면 출발점을 어디로 옮겨야 할까요\n  return -1;\n}",
  sol: "function gasStation(gas, cost) {\n  let total = 0;\n  let tank = 0;\n  let from = 0;\n  gas.forEach((g, i) => {\n    const diff = g - cost[i];\n    total += diff;\n    tank += diff;\n    if (tank < 0) { from = i + 1; tank = 0; }\n  });\n  return total < 0 ? -1 : from;\n}",
  tests: [["gasStation([1,2,3,4,5],[3,4,5,1,2])", "3"],
    ["gasStation([2,3,4],[3,4,3])", "-1"],
    ["gasStation([5],[4])", "0"],
    ["gasStation([3,1,1],[1,2,2])", "0"]],
  edge: [["gasStation([2],[2])", "0"], ["gasStation([1],[2])", "-1"]],
  ex: "두 가지를 한 번에 봅니다. <b>총합</b>이 음수면 어디서 출발해도 못 돌고, 총합이 0 이상이면 <b>반드시</b> 출발점이 존재합니다 — 이 사실을 알면 후보를 하나씩 시험할 필요가 없습니다.\n출발점을 옮기는 규칙이 그리디입니다. i 까지 오다가 기름이 떨어졌다면 <code>from</code> 부터 i 사이의 <b>어느 칸에서 출발해도</b> 실패합니다. 그 구간의 부분합은 처음부터 잰 합보다 작을 수 없기 때문입니다. 그래서 한 칸씩이 아니라 <b>i + 1 로 건너뜁니다.</b>\n<code>tank</code> 를 0으로 되돌리는 것을 빠뜨리면 새 출발점에서 빚을 지고 시작하게 되어 답이 뒤로 밀립니다.\n한 번만 훑어 O(n) 입니다. 모든 출발점을 시험하는 O(n²) 도 맞는 답을 내지만, n 이 10만이면 100억 번이라 통과하지 못합니다." },

{ track: "algo", k: "분수 배낭 · fractionalKnapsack", cat: "internals",
  q: "물건을 <b>쪼개서 담을 수 있을 때</b> 무게 한도 안에서 얻을 수 있는 최대 가치를 돌려주세요. 물건은 <code>[가치, 무게]</code> 이고, 결과는 <b>소수 둘째 자리까지</b> 반올림합니다.",
  src: "function fractionalKnapsack(items, cap) {\n  // TODO: 무엇이 '이득' 인지부터 정하세요\n  return 0;\n}",
  sol: "function fractionalKnapsack(items, cap) {\n  const sorted = items.slice().sort((a, b) => b[0] / b[1] - a[0] / a[1]);\n  let room = cap;\n  let got = 0;\n  sorted.forEach(([v, w]) => {\n    if (room <= 0) return;\n    const take = Math.min(w, room);\n    got += v * (take / w);\n    room -= take;\n  });\n  return Number(got.toFixed(2));\n}",
  tests: [["fractionalKnapsack([[60,10],[100,20],[120,30]],50)", "240"],
    ["fractionalKnapsack([[10,5]],10)", "10"],
    ["fractionalKnapsack([[10,5]],2)", "4"],
    ["fractionalKnapsack([[60,10],[100,20],[120,30]],5)", "30"]],
  edge: [["fractionalKnapsack([],10)", "0"], ["fractionalKnapsack([[5,1]],0)", "0"]],
  ex: "정렬 기준을 <b>가치</b>도 <b>무게</b>도 아닌 <b>단위 무게당 가치</b>로 잡는 것이 전부입니다. 쪼갤 수 있으니 한도가 남는 한 이득이 큰 것부터 채우면 최적입니다.\n마지막 물건은 <b>일부만</b> 들어갑니다. <code>take / w</code> 비율만큼 가치를 더하는 이 한 줄이 '분수' 배낭을 만듭니다.\n<b>쪼갤 수 없으면 이 그리디는 무너집니다.</b> 0/1 배낭에서는 단위 가치가 가장 높은 것을 넣었다가 한도가 애매하게 남아 더 나쁜 답이 되는 경우가 있고, 그래서 DP 를 씁니다 — 같은 문제처럼 보여도 <b>쪼갤 수 있는가</b> 한 줄이 풀이를 완전히 바꿉니다.\n부동소수 결과를 그대로 비교하면 <code>0.1 + 0.2</code> 문제에 걸립니다. 반올림 자리를 <b>문제에서 못 박아</b> 두는 이유입니다." },

{ track: "algo", k: "최소 화살 · minArrows", cat: "internals",
  q: "수평선 위 풍선들이 <code>[시작, 끝]</code> 로 주어집니다. 수직으로 화살을 쏘면 그 지점을 <b>포함하는 풍선이 모두</b> 터집니다. 전부 터뜨리는 데 필요한 <b>최소 화살 수</b>를 돌려주세요.",
  src: "function minArrows(points) {\n  // TODO: 화살은 어느 지점에 쏘는 것이 이득일까요\n  return 0;\n}",
  sol: "function minArrows(points) {\n  if (!points.length) return 0;\n  const sorted = points.slice().sort((a, b) => a[1] - b[1]);\n  let shots = 1;\n  let at = sorted[0][1];\n  sorted.forEach(([s, e]) => {\n    if (s > at) { shots++; at = e; }\n  });\n  return shots;\n}",
  tests: [["minArrows([[10,16],[2,8],[1,6],[7,12]])", "2"],
    ["minArrows([[1,2],[3,4],[5,6],[7,8]])", "4"],
    ["minArrows([[1,2],[2,3],[3,4],[4,5]])", "2"],
    ["minArrows([[1,10],[2,3],[4,5]])", "2"]],
  edge: [["minArrows([])", "0"], ["minArrows([[1,1]])", "1"]],
  ex: "회의 선택 문제와 <b>같은 골격</b>입니다. 끝점 기준으로 정렬하고, 지금 화살로 안 터지는 풍선을 만나면 그 풍선의 <b>끝점</b>에 새 화살을 쏩니다.\n왜 끝점인가 — 화살을 최대한 <b>오른쪽</b>에 두어야 뒤에 오는 풍선을 함께 맞힐 여지가 커집니다. 시작점에 쏘면 지금 풍선만 터뜨리고 끝납니다.\n두 문제의 답이 뒤집혀 있다는 점이 재미있습니다. 회의는 '겹치지 않게 <b>최대</b>' 를 세고, 화살은 '겹치는 것을 묶어 <b>최소</b>' 를 셉니다. 그런데 정렬 기준과 훑는 방식은 똑같습니다.\n좌표가 크면 <code>a[1] - b[1]</code> 정렬 비교가 오버플로할 수 있는 언어도 있습니다. 자바스크립트에서는 문제없지만, C++·자바로 옮길 때는 뺄셈 대신 <b>대소 비교</b>로 바꾸는 편이 안전합니다." },

{ track: "algo", k: "이어 붙여 가장 큰 수 · largestNumber", cat: "internals",
  q: "수들을 <b>이어 붙여 만들 수 있는 가장 큰 수</b>를 문자열로 돌려주세요. 결과가 <code>0</code> 뿐이면 <code>'0'</code> 하나만 돌려줍니다.",
  src: "function largestNumber(nums) {\n  // TODO: 두 수 a, b 중 어느 쪽을 앞에 둘지 어떻게 정할까요\n  return '';\n}",
  sol: "function largestNumber(nums) {\n  const strs = nums.map(String).sort((a, b) => {\n    const ab = a + b;\n    const ba = b + a;\n    if (ab < ba) return 1;\n    if (ab > ba) return -1;\n    return 0;\n  });\n  if (strs[0] === '0') return '0';\n  return strs.join('');\n}",
  tests: [["largestNumber([10,2])", "'210'"],
    ["largestNumber([3,30,34,5,9])", "'9534330'"],
    ["largestNumber([1])", "'1'"],
    ["largestNumber([0,0])", "'0'"]],
  edge: [["largestNumber([])", "''"], ["largestNumber([0,1])", "'10'"]],
  ex: "정렬 기준을 <b>설계하는</b> 문제입니다. 값이 큰 순도, 자릿수가 많은 순도 아닙니다 — <code>[10, 2]</code> 에서 답은 <code>210</code> 이므로 2가 앞입니다.\n옳은 기준은 '<b>이어 붙여 본다</b>' 입니다. <code>a + b</code> 와 <code>b + a</code> 를 문자열로 비교해서 큰 쪽 순서를 택합니다. 이 비교가 <b>전순서</b>를 이룬다는 것이 이 풀이가 맞는 이유이고, 그렇지 않으면 정렬 자체가 의미를 잃습니다.\n<code>[3, 30]</code> 에서 <code>'330' &gt; '303'</code> 이므로 3이 앞입니다. 사전순 그대로 정렬하면 <code>30</code> 이 앞에 와 틀립니다 — 문자열 비교를 <b>그대로 쓰지 않고</b> 이어 붙인 뒤 비교하는 것이 핵심입니다.\n<code>[0, 0]</code> 을 그냥 이으면 <code>'00'</code> 이 됩니다. 맨 앞이 0이면 전부 0이라는 뜻이므로 <code>'0'</code> 하나로 줄이는 예외 한 줄이 필요합니다." },

{ track: "algo", k: "쿠키 나눠 주기 · assignCookies", cat: "internals",
  q: "아이마다 만족하는 <b>최소 크기</b>가 있고 쿠키마다 크기가 있습니다. 한 아이에게 쿠키 하나씩만 줄 때 <b>만족시킬 수 있는 최대 인원</b>을 돌려주세요.",
  src: "function assignCookies(children, cookies) {\n  // TODO: 둘 다 정렬해 두고 양쪽을 한 칸씩 밀어 보세요\n  return 0;\n}",
  sol: "function assignCookies(children, cookies) {\n  const want = children.slice().sort((a, b) => a - b);\n  const have = cookies.slice().sort((a, b) => a - b);\n  let i = 0;\n  let j = 0;\n  let happy = 0;\n  while (i < want.length && j < have.length) {\n    if (have[j] >= want[i]) { happy++; i++; }\n    j++;\n  }\n  return happy;\n}",
  tests: [["assignCookies([1,2,3],[1,1])", "1"],
    ["assignCookies([1,2],[1,2,3])", "2"],
    ["assignCookies([10,9,8],[5,6,7])", "0"],
    ["assignCookies([1,1,1],[1,1])", "2"]],
  edge: [["assignCookies([],[1])", "0"], ["assignCookies([1],[])", "0"]],
  ex: "'<b>가장 덜 까다로운 아이</b>에게 <b>줄 수 있는 가장 작은 쿠키</b>' 를 주는 것이 최적입니다. 큰 쿠키를 아껴 두면 더 까다로운 아이도 만족시킬 수 있기 때문입니다.\n둘 다 정렬해 두면 포인터 두 개를 앞으로만 밀어 O(n log n) 에 끝납니다. 쿠키가 모자라면 <code>j</code> 만 밀고, 맞으면 <b>둘 다</b> 밉니다.\n큰 쿠키부터 큰 요구에 맞추는 방향으로 짜도 답은 같습니다. 다만 어느 쪽이든 <b>왜 최적인지</b> 를 교환 논증으로 확인하고 써야 합니다 — 큰 쿠키를 덜 까다로운 아이에게 주면 손해라는 논증입니다.\n아이가 없거나 쿠키가 없으면 반복이 한 번도 돌지 않아 0이 나옵니다. 경계 분기를 따로 두지 않아도 되는 구조가 좋은 구조입니다." },

{ track: "algo", k: "글자별로 구간 자르기 · partitionLabels", cat: "internals",
  q: "문자열을 조각으로 자르되 <b>같은 글자는 한 조각 안에만</b> 있어야 합니다. 조각 수가 가장 많아지도록 자르고, 각 조각의 <b>길이 배열</b>을 돌려주세요.",
  src: "function partitionLabels(s) {\n  // TODO: 각 글자가 마지막으로 나오는 자리를 먼저 알아 두세요\n  return [];\n}",
  sol: "function partitionLabels(s) {\n  const lastAt = {};\n  [...s].forEach((ch, i) => { lastAt[ch] = i; });\n  const sizes = [];\n  let from = 0;\n  let far = 0;\n  [...s].forEach((ch, i) => {\n    if (lastAt[ch] > far) far = lastAt[ch];\n    if (i === far) { sizes.push(far - from + 1); from = i + 1; }\n  });\n  return sizes;\n}",
  tests: [["partitionLabels('ababcbacadefegdehijhklij')", "[9,7,8]"],
    ["partitionLabels('abc')", "[1,1,1]"],
    ["partitionLabels('aaa')", "[3]"],
    ["partitionLabels('abab')", "[4]"]],
  edge: [["partitionLabels('')", "[]"], ["partitionLabels('a')", "[1]"]],
  ex: "두 번 훑습니다. 먼저 글자마다 <b>마지막 등장 위치</b>를 적어 두고, 다시 훑으면서 지금까지 본 글자들의 마지막 위치 중 <b>가장 먼 곳</b>까지를 현재 조각의 끝으로 잡습니다.\n그 끝에 <b>도달한 순간</b> 자릅니다. 그 앞에서 자르면 어떤 글자가 두 조각에 걸치고, 더 뒤에서 자르면 조각 수가 줄어듭니다 — 그래서 이 지점이 유일한 최적입니다.\n'가장 먼 곳' 을 계속 늘려 나가는 모양이 점프 게임의 <code>reach</code> 와 똑같습니다. 문제는 달라 보여도 <b>하나의 값으로 상태를 접는</b> 골격은 그대로입니다.\n<code>[...s]</code> 로 펼치는 것은 서로게이트 쌍(이모지 같은 것)을 한 글자로 세기 위해서입니다. <code>s[i]</code> 로 훑으면 코드 유닛 단위라 글자가 반으로 쪼개질 수 있습니다." },

{ track: "algo", k: "동전 그리디 · greedyCoins", cat: "internals",
  q: "동전 종류가 주어질 때 <b>큰 동전부터</b> 최대한 쓰는 방식으로 <code>amount</code> 를 만들고, 쓴 동전 개수를 돌려주세요. 그 방식으로 만들 수 없으면 <code>-1</code> 입니다.",
  src: "function greedyCoins(coins, amount) {\n  // TODO: 큰 것부터 나누고 나머지를 넘기세요\n  return -1;\n}",
  sol: "function greedyCoins(coins, amount) {\n  const sorted = coins.slice().sort((a, b) => b - a);\n  let rest = amount;\n  let used = 0;\n  sorted.forEach((c) => {\n    used += Math.floor(rest / c);\n    rest %= c;\n  });\n  return rest === 0 ? used : -1;\n}",
  tests: [["greedyCoins([1,5,10,25],63)", "6"],
    ["greedyCoins([1,5,10,25],30)", "2"],
    ["greedyCoins([5,10],3)", "-1"],
    ["greedyCoins([1],7)", "7"]],
  edge: [["greedyCoins([1,5],0)", "0"], ["greedyCoins([],5)", "-1"]],
  ex: "구현은 쉽지만 <b>이 그리디는 항상 옳지 않습니다.</b> 동전이 <code>[1, 3, 4]</code> 이고 6을 만들 때 큰 것부터 쓰면 4+1+1 로 세 개지만, 3+3 이면 두 개입니다.\n원화·미국 달러처럼 <b>정준 동전계</b>에서만 그리디가 최적입니다. 각 동전이 그보다 작은 동전들의 배수 구조를 이루기 때문인데, 이것은 <b>동전 목록에 달린 성질</b>이지 알고리즘의 성질이 아닙니다.\n그래서 이 함수의 이름은 <code>minCoins</code> 가 아니라 <code>greedyCoins</code> 입니다. '<b>이 방식으로 만들면</b> 몇 개인가' 를 세는 함수이고, 진짜 최소 개수는 DP 로 풀어야 합니다.\n실무에서도 같은 함정이 있습니다. 그리디는 코드가 짧아 먼저 손이 가지만, <b>반례를 찾아보지 않고</b> 쓰면 대부분의 입력에서 맞고 특정 입력에서만 조용히 틀립니다 — 가장 잡기 어려운 종류의 버그입니다." },
];
