/* 완전탐색과 백트래킹 — 코딩 테스트에서 가장 먼저 나오고 가장 얇게 다뤄지던 두 유형.
   개념을 고르는 문항이 아니라 <b>테스트를 통과시켜야 하는</b> 구현 문항이다.
   앱의 testDoc 품질 규칙(var 금지 · 주석 뺀 28줄 이하 · console.log 금지)을 지킨다. */
module.exports = [

/* ───────────── 완전탐색 ───────────── */
{ track: "algo", k: "부분집합의 합 · subsetSum", cat: "internals",
  q: "음이 아닌 정수 배열에서 <b>몇 개를 골라 합이 <code>target</code></b> 이 되게 할 수 있으면 <code>true</code>, 없으면 <code>false</code> 를 돌려주세요. 아무것도 고르지 않는 것도 하나의 선택입니다.",
  src: "function subsetSum(xs, target) {\n  // TODO: 각 원소를 '고른다 / 안 고른다' 두 갈래로 나눠 보세요\n  return false;\n}",
  sol: "function subsetSum(xs, target) {\n  const go = (i, sum) => {\n    if (sum === target) return true;\n    if (i === xs.length || sum > target) return false;\n    return go(i + 1, sum + xs[i]) || go(i + 1, sum);\n  };\n  return go(0, 0);\n}",
  tests: [["subsetSum([3,34,4,12,5,2],9)", "true"],
    ["subsetSum([3,34,4,12,5,2],30)", "false"],
    ["subsetSum([1,2,3],6)", "true"],
    ["subsetSum([1,2,3],7)", "false"]],
  edge: [["subsetSum([],0)", "true"], ["subsetSum([],5)", "false"]],
  ex: "완전탐색의 기본 꼴입니다. 원소마다 <b>고른다 / 안 고른다</b> 두 갈래로 나누면 2ⁿ 가지가 되고, 재귀 한 줄이 그 갈래를 그대로 그려 냅니다.\n<code>sum &gt; target</code> 에서 멈추는 것이 <b>가지치기</b>입니다. 답이 될 수 없는 갈래를 미리 접어 두면 실제 탐색량이 크게 줄어듭니다 — 다만 이 가지치기는 <b>음수가 없을 때만</b> 옳습니다. 음수가 섞이면 합이 다시 줄어들 수 있으니 조건을 지워야 합니다.\n실패 순서도 중요합니다. <code>sum === target</code> 을 먼저 보지 않고 <code>i === xs.length</code> 를 먼저 보면, 마지막 원소를 고른 순간 답이 맞았는데도 배열 끝이라고 false 를 돌려줍니다.\nn 이 20을 넘어가면 2ⁿ 가 버겁습니다. 그때는 같은 (i, sum) 을 다시 계산하지 않도록 메모이제이션을 붙이는데, 그것이 곧 배낭 문제의 DP 입니다 — 완전탐색은 DP 의 출발점입니다." },

{ track: "algo", k: "비트마스크로 부분집합 만들기 · powerSet", cat: "internals",
  q: "배열의 <b>모든 부분집합</b>을 돌려주세요. 순서는 <b>비트마스크 순서</b>입니다 — <code>m</code> 을 0부터 2ⁿ−1까지 세면서, <code>m</code> 의 <code>i</code>번 비트가 켜져 있으면 <code>xs[i]</code> 를 담습니다.",
  src: "function powerSet(xs) {\n  // TODO: m 을 0..2^n-1 로 세며 켜진 비트의 원소를 모으세요\n  return [];\n}",
  sol: "function powerSet(xs) {\n  const sets = [];\n  for (let m = 0; m < (1 << xs.length); m++) {\n    const cur = [];\n    xs.forEach((x, i) => { if (m & (1 << i)) cur.push(x); });\n    sets.push(cur);\n  }\n  return sets;\n}",
  tests: [["powerSet([1,2])", "[[],[1],[2],[1,2]]"],
    ["powerSet([7])", "[[],[7]]"],
    ["powerSet([1,2,3]).length", "8"],
    ["powerSet([1,2,3])[5]", "[1,3]"]],
  edge: [["powerSet([])", "[[]]"], ["powerSet(['a','b'])", "[[],['a'],['b'],['a','b']]"]],
  ex: "부분집합은 <b>n비트 이진수</b>와 일대일로 대응합니다. 원소 i 를 담았는지 여부가 i번 비트이므로, 0부터 2ⁿ−1까지 세기만 하면 재귀 없이 전부 훑을 수 있습니다.\n비트마스크의 장점은 <b>상태를 정수 하나로 표현</b>한다는 것입니다. 방문 여부를 배열로 들고 다닐 필요가 없어 메모이제이션 키로 쓰기 좋고, 외판원 문제 같은 비트마스크 DP 가 여기서 출발합니다.\n<code>1 &lt;&lt; xs.length</code> 는 n 이 31을 넘으면 무너집니다. 자바스크립트의 비트 연산은 32비트 정수로 잘리기 때문인데, 애초에 2³¹ 개를 훑는 것 자체가 불가능하므로 실무에서는 n ≤ 20 정도가 한계입니다.\n빈 배열에서 <code>1 &lt;&lt; 0 === 1</code> 이라 m 은 0 하나뿐이고 결과는 <code>[[]]</code> 입니다 — 공집합도 부분집합이라는 정의가 코드에 자연스럽게 담깁니다." },

{ track: "algo", k: "조합 만들기 · combinations", cat: "internals",
  q: "1부터 <code>n</code> 까지의 수에서 <b><code>k</code>개를 고르는 모든 조합</b>을 <b>사전순</b>으로 돌려주세요. 조합 안의 수도 오름차순입니다.",
  src: "function combinations(n, k) {\n  // TODO: 시작 수를 하나씩 올려 가며 고르세요\n  return [];\n}",
  sol: "function combinations(n, k) {\n  const picked = [];\n  const cur = [];\n  const go = (start) => {\n    if (cur.length === k) { picked.push(cur.slice()); return; }\n    for (let v = start; v <= n; v++) {\n      cur.push(v);\n      go(v + 1);\n      cur.pop();\n    }\n  };\n  go(1);\n  return picked;\n}",
  tests: [["combinations(4,2)", "[[1,2],[1,3],[1,4],[2,3],[2,4],[3,4]]"],
    ["combinations(3,1)", "[[1],[2],[3]]"],
    ["combinations(3,3)", "[[1,2,3]]"],
    ["combinations(5,2).length", "10"]],
  edge: [["combinations(3,0)", "[[]]"], ["combinations(2,3)", "[]"]],
  ex: "조합과 순열을 가르는 것은 <b>다음 시작점</b> 한 줄입니다. <code>go(v + 1)</code> 처럼 시작점을 올려 두면 이미 지나온 수를 다시 고를 수 없어 순서가 다른 같은 묶음이 생기지 않습니다.\n<code>cur.push</code> 뒤에 <code>cur.pop</code> 을 짝지어 두는 것이 백트래킹의 핵심입니다. 갔던 길을 <b>되돌려 놓아야</b> 형제 갈래가 깨끗한 상태에서 시작합니다 — 이 짝을 빠뜨리면 결과가 점점 길어집니다.\n결과를 담을 때 <code>cur.slice()</code> 로 <b>복사</b>하는 것도 잊기 쉽습니다. <code>cur</code> 를 그대로 넣으면 같은 배열을 여러 번 담게 되고, 되돌리는 순간 이미 담긴 것까지 함께 비워집니다.\nk 가 0이면 아무것도 고르지 않은 조합 하나가 답이고, k 가 n 보다 크면 답이 없습니다. 두 경계는 특별한 분기 없이 위 구조에서 저절로 나옵니다." },

{ track: "algo", k: "순열 만들기 · permutations", cat: "internals",
  q: "배열의 <b>모든 순열</b>을 돌려주세요. 입력이 오름차순이면 결과도 <b>사전순</b>이 됩니다.",
  src: "function permutations(xs) {\n  // TODO: 맨 앞에 올 원소를 하나씩 골라 보세요\n  return [];\n}",
  sol: "function permutations(xs) {\n  if (xs.length === 0) return [[]];\n  const all = [];\n  xs.forEach((x, i) => {\n    const rest = xs.slice(0, i).concat(xs.slice(i + 1));\n    permutations(rest).forEach((p) => all.push([x].concat(p)));\n  });\n  return all;\n}",
  tests: [["permutations([1,2,3])", "[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]"],
    ["permutations([1,2])", "[[1,2],[2,1]]"],
    ["permutations([9])", "[[9]]"],
    ["permutations([1,2,3,4]).length", "24"]],
  edge: [["permutations([])", "[[]]"], ["permutations(['a','b'])", "[['a','b'],['b','a']]"]],
  ex: "순열은 '<b>맨 앞에 무엇이 올까</b>' 를 n 가지로 나누고, 남은 것으로 같은 문제를 다시 푸는 구조입니다. 재귀의 정의가 문제의 정의와 그대로 겹칩니다.\n종료 조건이 <code>[[]]</code> 인 것이 중요합니다. 빈 배열의 순열은 '<b>아무것도 없는 순열 하나</b>' 이지 '순열이 없음' 이 아닙니다. 여기서 <code>[]</code> 를 돌려주면 위쪽 <code>forEach</code> 가 한 번도 돌지 않아 전체가 빈 배열이 됩니다.\n이 구현은 매 단계 <code>slice</code>·<code>concat</code> 으로 새 배열을 만들어 읽기는 쉽지만 복사 비용이 듭니다. 방문 표시 배열과 <code>push</code>/<code>pop</code> 을 쓰면 복사 없이 같은 일을 할 수 있습니다 — 백트래킹 판입니다.\nn! 은 10에서 이미 360만입니다. 순열을 <b>다 만들어서</b> 푸는 접근은 n 이 8~10을 넘으면 쓸 수 없고, 그때부터는 그리디·DP·분기한정으로 갈아타야 합니다." },

{ track: "algo", k: "세 수의 합 세기 · countTriples", cat: "internals",
  q: "서로 다른 세 자리 <code>i &lt; j &lt; k</code> 를 골라 <b>합이 0</b> 이 되는 경우의 <b>개수</b>를 세세요. 값이 같아도 자리가 다르면 다른 경우입니다.",
  src: "function countTriples(xs) {\n  // TODO: 세 겹 반복으로 i < j < k 를 모두 보세요\n  return 0;\n}",
  sol: "function countTriples(xs) {\n  let found = 0;\n  for (let i = 0; i < xs.length; i++) {\n    for (let j = i + 1; j < xs.length; j++) {\n      for (let k = j + 1; k < xs.length; k++) {\n        if (xs[i] + xs[j] + xs[k] === 0) found++;\n      }\n    }\n  }\n  return found;\n}",
  tests: [["countTriples([-1,0,1,2,-1,-4])", "3"],
    ["countTriples([0,0,0])", "1"],
    ["countTriples([1,2,3])", "0"],
    ["countTriples([0,0,0,0])", "4"]],
  edge: [["countTriples([])", "0"], ["countTriples([1,2])", "0"]],
  ex: "가장 단순한 완전탐색입니다. 중요한 것은 <b>안쪽 반복의 시작점</b>을 <code>i + 1</code>, <code>j + 1</code> 로 두어 <code>i &lt; j &lt; k</code> 를 강제하는 것입니다. 0부터 다시 시작하면 같은 자리를 두 번 세거나 순서만 다른 같은 묶음을 여러 번 세게 됩니다.\n이 코드는 O(n³) 입니다. n 이 500이면 1억 번이라 이미 아슬아슬하고, 2,000이면 손댈 수 없습니다.\n줄이는 길은 <b>한 겹을 지우는</b> 것입니다. 배열을 정렬한 뒤 i 를 고정하고 나머지 두 수를 <b>투 포인터</b>로 찾으면 O(n²) 가 되고, 해시로 <code>-(xs[i] + xs[j])</code> 를 찾으면 역시 O(n²) 입니다.\n다만 '자리가 다르면 다른 경우' 라는 이 문제의 규칙에서는 정렬이 자리를 흐트러뜨립니다. 조건을 바꾸기 전에 <b>무엇을 세는 문제인지</b> 부터 다시 읽어야 합니다." },

{ track: "algo", k: "두 수의 최대 곱 · maxProductPair", cat: "internals",
  q: "서로 다른 두 자리를 골라 <b>곱이 가장 큰 값</b>을 돌려주세요. 원소가 둘보다 적으면 <code>null</code> 입니다.",
  src: "function maxProductPair(xs) {\n  // TODO: 모든 쌍을 만들어 가장 큰 곱을 찾으세요\n  return null;\n}",
  sol: "function maxProductPair(xs) {\n  let best = null;\n  for (let i = 0; i < xs.length; i++) {\n    for (let j = i + 1; j < xs.length; j++) {\n      const p = xs[i] * xs[j];\n      if (best === null || p > best) best = p;\n    }\n  }\n  return best;\n}",
  tests: [["maxProductPair([1,5,3,2])", "15"],
    ["maxProductPair([-10,-9,1,2])", "90"],
    ["maxProductPair([0,0])", "0"],
    ["maxProductPair([3,7])", "21"]],
  edge: [["maxProductPair([5])", "null"], ["maxProductPair([])", "null"]],
  ex: "완전탐색이 <b>정답의 기준선</b>이 되는 전형적인 예입니다. 모든 쌍을 보는 O(n²) 는 느리지만 반드시 맞고, 빠른 풀이를 짰을 때 대조할 답을 만들어 줍니다.\n빠른 풀이는 '가장 큰 두 수의 곱' 이지만 그것만으로는 틀립니다. <code>[-10,-9,1,2]</code> 처럼 <b>음수 두 개의 곱</b>이 더 클 수 있어서, 가장 큰 두 수와 가장 작은 두 수를 모두 견줘야 합니다.\n초기값을 0이나 <code>-Infinity</code> 로 두는 실수가 잦습니다. 0으로 두면 곱이 전부 음수인 배열에서 있지도 않은 0을 돌려주고, 원소가 둘 미만일 때 <code>null</code> 을 돌려주어야 한다는 규약도 깨집니다.\n그래서 '아직 아무 쌍도 못 봤다' 를 <code>null</code> 로 표현하고 첫 비교에서만 특별히 다루는 편이 안전합니다 — 값의 범위에 기대지 않는 초기화입니다." },

/* ───────────── 백트래킹 ───────────── */
{ track: "algo", k: "N-퀸 · nQueens", cat: "internals",
  q: "<code>n × n</code> 체스판에 <b>서로 공격하지 못하게</b> 퀸 <code>n</code> 개를 놓는 방법의 <b>가짓수</b>를 돌려주세요. 퀸은 같은 행·열·대각선을 공격합니다.",
  src: "function nQueens(n) {\n  // TODO: 한 행에 하나씩 놓고, 안 되면 되돌아오세요\n  return 0;\n}",
  sol: "function nQueens(n) {\n  const cols = [];\n  let ways = 0;\n  const place = (r) => {\n    if (r === n) { ways++; return; }\n    for (let c = 0; c < n; c++) {\n      const safe = cols.every((cc, rr) => cc !== c && Math.abs(cc - c) !== r - rr);\n      if (!safe) continue;\n      cols.push(c);\n      place(r + 1);\n      cols.pop();\n    }\n  };\n  place(0);\n  return ways;\n}",
  tests: [["nQueens(1)", "1"], ["nQueens(4)", "2"], ["nQueens(5)", "10"], ["nQueens(6)", "4"]],
  edge: [["nQueens(2)", "0"], ["nQueens(3)", "0"]],
  ex: "백트래킹의 교과서 문제입니다. 한 행에 퀸을 하나만 놓기로 정하면 행 충돌은 저절로 사라지고, 남는 것은 <b>열과 두 대각선</b> 뿐입니다.\n대각선 판정이 <code>Math.abs(cc - c) === r - rr</code> 한 줄입니다. 행 차이와 열 차이가 같으면 같은 대각선 위라는 뜻인데, <code>r - rr</code> 은 항상 양수라 절댓값이 필요 없습니다.\n핵심은 <b>안 되는 갈래를 끝까지 가지 않는</b> 것입니다. n! 가지를 모두 만들어 놓고 마지막에 검사하면 n = 8 에서 4만 가지가 되지만, 놓을 때마다 검사하면 실제로 내려가는 갈래가 2천 개 남짓으로 줄어듭니다.\n더 빠르게 하려면 열·대각선 사용 여부를 <b>불리언 배열이나 비트마스크</b>로 들고 다니면 됩니다. 매번 <code>every</code> 로 훑는 O(n) 검사가 O(1) 이 됩니다." },

{ track: "algo", k: "합이 되는 조합 · combinationSum", cat: "internals",
  q: "후보 수를 <b>여러 번 써도 좋을 때</b>, 합이 <code>target</code> 이 되는 모든 조합을 돌려주세요. 순서만 다른 것은 같은 조합으로 보고, 후보 배열의 순서를 따라 오름차순으로 담습니다.",
  src: "function combinationSum(cands, target) {\n  // TODO: 같은 후보를 다시 골라도 되게 시작점을 유지하세요\n  return [];\n}",
  sol: "function combinationSum(cands, target) {\n  const found = [];\n  const cur = [];\n  const go = (start, rest) => {\n    if (rest === 0) { found.push(cur.slice()); return; }\n    for (let i = start; i < cands.length; i++) {\n      if (cands[i] > rest) continue;\n      cur.push(cands[i]);\n      go(i, rest - cands[i]);\n      cur.pop();\n    }\n  };\n  go(0, target);\n  return found;\n}",
  tests: [["combinationSum([2,3,6,7],7)", "[[2,2,3],[7]]"],
    ["combinationSum([2,3,5],8)", "[[2,2,2,2],[2,3,3],[3,5]]"],
    ["combinationSum([2],1)", "[]"],
    ["combinationSum([1],2)", "[[1,1]]"]],
  edge: [["combinationSum([],5)", "[]"], ["combinationSum([3],0)", "[[]]"]],
  ex: "조합 만들기와 딱 한 글자 다릅니다. 다음 단계로 내려갈 때 <code>go(i + 1, ...)</code> 이 아니라 <code>go(i, ...)</code> 를 부르면 <b>같은 수를 다시 고를 수</b> 있습니다.\n그래도 <code>start</code> 아래로는 내려가지 않으므로 <code>[2,3]</code> 과 <code>[3,2]</code> 가 함께 나오지 않습니다. 중복 조합을 막는 것은 방문 표시가 아니라 <b>시작점을 되돌리지 않는 규칙</b>입니다.\n<code>cands[i] &gt; rest</code> 에서 건너뛰는 것이 가지치기입니다. 후보를 미리 정렬해 두었다면 <code>continue</code> 대신 <code>break</code> 로 바꿀 수 있어 더 빨라집니다 — 뒤는 전부 더 큰 수이기 때문입니다.\n<code>target</code> 이 0이면 '아무것도 고르지 않은 조합' 하나가 답입니다. 이 경계를 특별히 다루지 않아도 <code>rest === 0</code> 이 처음부터 참이 되어 자연스럽게 나옵니다." },

{ track: "algo", k: "격자에서 단어 찾기 · wordSearch", cat: "internals",
  q: "문자 격자에서 <b>상하좌우로 이어 붙여</b> 단어를 만들 수 있으면 <code>true</code> 를 돌려주세요. <b>같은 칸을 두 번 쓸 수는 없습니다.</b>",
  src: "function wordSearch(board, word) {\n  // TODO: 칸마다 시작해 보고, 지나온 칸은 잠시 막아 두세요\n  return false;\n}",
  sol: "function wordSearch(board, word) {\n  const h = board.length;\n  const w = h ? board[0].length : 0;\n  const go = (r, c, i) => {\n    if (i === word.length) return true;\n    if (r < 0 || c < 0 || r >= h || c >= w) return false;\n    if (board[r][c] !== word[i]) return false;\n    const save = board[r][c];\n    board[r][c] = null;\n    const ok = go(r + 1, c, i + 1) || go(r - 1, c, i + 1)\n      || go(r, c + 1, i + 1) || go(r, c - 1, i + 1);\n    board[r][c] = save;\n    return ok;\n  };\n  if (!word.length) return true;\n  for (let r = 0; r < h; r++) {\n    for (let c = 0; c < w; c++) if (go(r, c, 0)) return true;\n  }\n  return false;\n}",
  tests: [["wordSearch([['A','B','C','E'],['S','F','C','S'],['A','D','E','E']],'ABCCED')", "true"],
    ["wordSearch([['A','B','C','E'],['S','F','C','S'],['A','D','E','E']],'SEE')", "true"],
    ["wordSearch([['A','B','C','E'],['S','F','C','S'],['A','D','E','E']],'ABCB')", "false"],
    ["wordSearch([['A','B'],['C','D']],'ABDC')", "true"]],
  edge: [["wordSearch([['A']],'A')", "true"], ["wordSearch([],'A')", "false"]],
  ex: "격자 백트래킹의 표준형입니다. 시작 칸을 모를 때는 <b>모든 칸에서 시작해</b> 보고, 각 갈래에서는 지나온 칸을 잠시 막아 두었다가 되돌아올 때 풀어 줍니다.\n방문 표시를 <b>따로 배열로 두지 않고</b> 격자 자체를 잠시 덮어쓰는 것이 이 문제의 요령입니다. 다만 되돌릴 때 원래 값을 반드시 복원해야 하고, 그러지 않으면 다음 시작 칸에서 격자가 이미 망가져 있습니다.\n<code>ABCB</code> 가 false 인 이유가 바로 이 규칙 때문입니다. 두 번째 B 를 쓰려면 첫 번째 B 칸으로 되돌아가야 하는데 그 칸은 이미 쓰였습니다 — 막아 두지 않으면 잘못된 true 가 나옵니다.\n경계 검사를 <b>재귀 안에서</b> 하는 것도 중요합니다. 부르기 전에 검사하면 네 방향마다 같은 조건을 네 번 써야 하지만, 들어와서 검사하면 한 곳에 모입니다." },

{ track: "algo", k: "팰린드롬 분할 세기 · palindromePartitions", cat: "internals",
  q: "문자열을 <b>모든 조각이 팰린드롬</b> 이 되도록 자르는 방법의 <b>가짓수</b>를 돌려주세요. 자르지 않고 통째로 두는 것도 하나입니다.",
  src: "function palindromePartitions(s) {\n  // TODO: 앞에서부터 팰린드롬인 조각을 떼어 내며 세세요\n  return 0;\n}",
  sol: "function palindromePartitions(s) {\n  const isPal = (a, b) => {\n    while (a < b) {\n      if (s[a] !== s[b]) return false;\n      a++; b--;\n    }\n    return true;\n  };\n  const go = (i) => {\n    if (i === s.length) return 1;\n    let ways = 0;\n    for (let j = i; j < s.length; j++) {\n      if (isPal(i, j)) ways += go(j + 1);\n    }\n    return ways;\n  };\n  return go(0);\n}",
  tests: [["palindromePartitions('aab')", "2"],
    ["palindromePartitions('aaa')", "4"],
    ["palindromePartitions('abc')", "1"],
    ["palindromePartitions('aba')", "2"]],
  edge: [["palindromePartitions('')", "1"], ["palindromePartitions('a')", "1"]],
  ex: "문자열을 자르는 문제는 '<b>첫 조각을 어디까지 떼어 낼까</b>' 로 갈래를 나눕니다. 조각이 팰린드롬일 때만 내려가고, 나머지 문자열에 같은 질문을 다시 던집니다.\n빈 문자열이 1을 돌려주는 것이 이 재귀의 바닥입니다. '더 자를 것이 없다 = 방법을 하나 완성했다' 는 뜻이며, 여기서 0을 돌려주면 모든 갈래의 합이 0이 되어 버립니다.\n<code>aaa</code> 가 4인 것을 손으로 확인해 보세요 — <code>a|a|a</code>, <code>a|aa</code>, <code>aa|a</code>, <code>aaa</code> 입니다. 같은 문자가 이어질수록 갈래가 지수로 늘어납니다.\n<code>go(i)</code> 는 시작 위치에만 의존하므로 <b>같은 i 를 여러 번 계산</b>합니다. 배열 하나로 memo 를 붙이면 O(n²) 로 떨어지고, 팰린드롬 여부도 미리 표로 만들어 두면 판정이 O(1) 이 됩니다." },

{ track: "algo", k: "중복 있는 순열 · permuteUnique", cat: "internals",
  q: "같은 값이 섞인 수 배열에서 <b>서로 다른 순열만</b> 사전순으로 돌려주세요. 값이 같은 원소끼리 자리를 바꾼 것은 같은 순열입니다.",
  src: "function permuteUnique(xs) {\n  // TODO: 정렬한 뒤, 같은 값이 이어질 때 앞의 것을 건너뛰지 마세요\n  return [];\n}",
  sol: "function permuteUnique(xs) {\n  const sorted = xs.slice().sort((a, b) => a - b);\n  const used = sorted.map(() => false);\n  const made = [];\n  const cur = [];\n  const go = () => {\n    if (cur.length === sorted.length) { made.push(cur.slice()); return; }\n    sorted.forEach((v, i) => {\n      if (used[i]) return;\n      if (i > 0 && sorted[i] === sorted[i - 1] && !used[i - 1]) return;\n      used[i] = true; cur.push(v);\n      go();\n      cur.pop(); used[i] = false;\n    });\n  };\n  go();\n  return made;\n}",
  tests: [["permuteUnique([1,1,2])", "[[1,1,2],[1,2,1],[2,1,1]]"],
    ["permuteUnique([1,2])", "[[1,2],[2,1]]"],
    ["permuteUnique([2,2])", "[[2,2]]"],
    ["permuteUnique([1,2,3]).length", "6"]],
  edge: [["permuteUnique([])", "[[]]"], ["permuteUnique([5])", "[[5]]"]],
  ex: "중복을 막는 규칙 한 줄이 이 문제의 전부입니다. 정렬해서 같은 값을 붙여 놓은 뒤, <b>바로 앞의 같은 값이 아직 안 쓰였다면 지금 것도 쓰지 않습니다.</b>\n이렇게 하면 값이 같은 원소들은 언제나 <b>왼쪽부터 차례로</b> 쓰이게 되어, 같은 순열을 만드는 여러 경로 중 하나만 남습니다. 조건을 <code>used[i - 1]</code> 로 뒤집어 쓰면 반대로 오른쪽부터 쓰는 경로만 남는데, 그것도 결과는 같습니다.\n만든 순열을 <code>Set</code> 에 넣어 중복을 지우는 방법도 있지만, 그때는 <b>이미 만든 뒤</b> 버리는 것이라 시간이 그대로 듭니다. 중복 순열이 많을수록 손해가 커집니다.\n정렬을 빼먹으면 규칙이 무너집니다. 같은 값이 떨어져 있으면 '<b>바로 앞</b>' 비교가 아무 의미도 갖지 못하기 때문입니다." },

{ track: "algo", k: "IP 주소 복원 · restoreIp", cat: "internals",
  q: "숫자 문자열에 점 세 개를 넣어 만들 수 있는 <b>유효한 IPv4 주소</b>를 모두 돌려주세요. 각 조각은 0~255 이고, <b>0 으로 시작하는 두 자리 이상</b>은 안 됩니다.",
  src: "function restoreIp(s) {\n  // TODO: 조각을 1~3자리씩 떼며 네 조각을 채우세요\n  return [];\n}",
  sol: "function restoreIp(s) {\n  const made = [];\n  const go = (i, parts) => {\n    if (parts.length === 4) {\n      if (i === s.length) made.push(parts.join('.'));\n      return;\n    }\n    for (let len = 1; len <= 3 && i + len <= s.length; len++) {\n      const seg = s.slice(i, i + len);\n      if (seg.length > 1 && seg[0] === '0') break;\n      if (Number(seg) > 255) break;\n      go(i + len, parts.concat(seg));\n    }\n  };\n  go(0, []);\n  return made;\n}",
  tests: [["restoreIp('25525511135')", "['255.255.11.135','255.255.111.35']"],
    ["restoreIp('0000')", "['0.0.0.0']"],
    ["restoreIp('1111')", "['1.1.1.1']"],
    ["restoreIp('101023')", "['1.0.10.23','1.0.102.3','10.1.0.23','10.10.2.3','101.0.2.3']"]],
  edge: [["restoreIp('')", "[]"], ["restoreIp('00')", "[]"]],
  ex: "갈래가 세 개뿐인 백트래킹입니다. 조각을 1·2·3자리로 떼어 보고, 규칙을 어기면 그 자리에서 접습니다.\n<b>두 조건을 모두</b> 봐야 한다는 점이 함정입니다. 값이 255 이하여도 <code>01</code> 처럼 앞이 0이면 안 되고, 앞이 0이 아니어도 <code>256</code> 은 안 됩니다. 둘 중 하나만 검사하면 <code>0000</code> 이나 <code>25525511135</code> 에서 답이 어긋납니다.\n두 검사 모두 <code>continue</code> 가 아니라 <code>break</code> 인 것도 이유가 있습니다. 앞이 0이면 더 긴 조각도 전부 0으로 시작하고, 값이 255를 넘었다면 더 긴 조각은 더 큽니다 — 뒤를 볼 필요가 없습니다.\n마지막으로 네 조각을 채웠을 때 <b>문자열을 다 썼는지</b> 확인해야 합니다. 이 검사를 빠뜨리면 <code>1.1.1.1</code> 뒤에 문자가 남아 있어도 답으로 셉니다." },
];
