/* 그래프 · DFS/BFS · 최단거리 — 실행형이 각각 8·12·5문항뿐이던 유형.
   격자 탐색부터 위상 정렬·유니온 파인드·세 가지 최단거리까지 직접 구현한다. */
module.exports = [

/* ───────────── 탐색 ───────────── */
{ track: "algo", k: "섬의 개수 · numIslands", cat: "internals",
  q: "<code>1</code> 은 땅, <code>0</code> 은 바다입니다. <b>상하좌우로 이어진 땅</b>을 하나의 섬으로 볼 때 섬이 몇 개인지 돌려주세요.",
  src: "function numIslands(grid) {\n  // TODO: 땅을 만나면 이어진 땅을 전부 지우고 하나로 세세요\n  return 0;\n}",
  sol: "function numIslands(grid) {\n  const h = grid.length;\n  const w = h ? grid[0].length : 0;\n  let islands = 0;\n  const sink = (r, c) => {\n    if (r < 0 || c < 0 || r >= h || c >= w || grid[r][c] !== 1) return;\n    grid[r][c] = 0;\n    sink(r + 1, c); sink(r - 1, c); sink(r, c + 1); sink(r, c - 1);\n  };\n  for (let r = 0; r < h; r++) {\n    for (let c = 0; c < w; c++) if (grid[r][c] === 1) { islands++; sink(r, c); }\n  }\n  return islands;\n}",
  tests: [["numIslands([[1,1,0],[0,1,0],[0,0,1]])", "2"],
    ["numIslands([[1,0],[0,1]])", "2"],
    ["numIslands([[1,1],[1,1]])", "1"],
    ["numIslands([[0,0],[0,0]])", "0"]],
  edge: [["numIslands([])", "0"], ["numIslands([[1]])", "1"]],
  ex: "격자는 <b>그래프의 한 모습</b>입니다. 칸이 정점이고 상하좌우가 간선이므로, 인접 리스트를 만들지 않고도 DFS 를 그대로 씁니다.\n방문 표시를 <b>격자 자체에 0으로 덮어써서</b> 합니다. 별도 배열을 만들지 않아 짧지만 입력을 고쳐 버리므로, 호출자가 원본을 다시 쓴다면 복사해서 넘겨야 합니다.\n바깥 반복은 '아직 안 지운 땅' 을 찾는 역할만 합니다. 하나 찾을 때마다 <code>sink</code> 가 그 섬 전체를 지우므로 같은 섬을 두 번 세지 않습니다 — <b>연결 요소를 세는</b> 문제의 표준 골격입니다.\n재귀 깊이는 섬 크기만큼 깊어집니다. 1000×1000 격자에서는 스택이 넘칠 수 있어 실무에서는 스택 배열을 직접 쓰거나 BFS 로 바꿉니다." },

{ track: "algo", k: "DFS 방문 순서 · dfsOrder", cat: "internals",
  q: "무방향 그래프를 <code>start</code> 에서 <b>깊이 우선</b>으로 훑은 방문 순서를 돌려주세요. 갈래가 여럿이면 <b>번호가 작은 쪽</b>으로 먼저 갑니다.",
  src: "function dfsOrder(n, edges, start) {\n  // TODO: 인접 리스트를 만들고 정렬한 뒤 재귀로 내려가세요\n  return [];\n}",
  sol: "function dfsOrder(n, edges, start) {\n  const near = Array.from({ length: n }, () => []);\n  edges.forEach(([a, b]) => { near[a].push(b); near[b].push(a); });\n  near.forEach((list) => list.sort((x, y) => x - y));\n  const seen = new Array(n).fill(false);\n  const order = [];\n  const go = (v) => {\n    seen[v] = true;\n    order.push(v);\n    near[v].forEach((u) => { if (!seen[u]) go(u); });\n  };\n  go(start);\n  return order;\n}",
  tests: [["dfsOrder(5,[[0,1],[0,2],[1,3],[2,4]],0)", "[0,1,3,2,4]"],
    ["dfsOrder(3,[[0,1],[1,2]],0)", "[0,1,2]"],
    ["dfsOrder(4,[[0,1],[2,3]],0)", "[0,1]"],
    ["dfsOrder(3,[[0,2],[0,1]],0)", "[0,1,2]"]],
  edge: [["dfsOrder(1,[],0)", "[0]"], ["dfsOrder(3,[],1)", "[1]"]],
  ex: "간선 목록을 <b>인접 리스트</b>로 바꾸는 것이 그래프 문제의 첫 줄입니다. 무방향이면 양쪽에 모두 넣어야 하는데, 이 한 줄을 빠뜨리면 한쪽으로만 갈 수 있는 그래프가 됩니다.\n방문 표시를 <b>들어갈 때</b> 찍는 것이 중요합니다. 나올 때 찍으면 사이클에서 무한히 돕니다. DFS 에서 <code>seen[v] = true</code> 는 재귀 호출 <b>직전</b>이 아니라 함수에 들어오자마자입니다.\n순서를 못 박으려면 인접 리스트를 <b>정렬</b>해야 합니다. 정렬하지 않으면 간선을 준 순서에 따라 방문 순서가 달라져 테스트가 흔들립니다.\n<code>dfsOrder(4,[[0,1],[2,3]],0)</code> 이 <code>[0,1]</code> 인 것에 주목하세요. 한 번의 DFS 는 <b>시작점이 속한 연결 요소</b>만 훑습니다. 전체를 훑으려면 모든 정점에서 시작을 시도해야 합니다." },

{ track: "algo", k: "격자 최단 거리 · shortestPathGrid", cat: "internals",
  q: "<code>0</code> 은 지날 수 있고 <code>1</code> 은 벽입니다. 왼쪽 위에서 오른쪽 아래까지 <b>지나는 칸의 최소 개수</b>를 돌려주세요(시작 칸 포함). 갈 수 없으면 <code>-1</code> 입니다.",
  src: "function shortestPathGrid(grid) {\n  // TODO: 너비 우선으로 퍼뜨리면 처음 닿은 순간이 최단입니다\n  return -1;\n}",
  sol: "function shortestPathGrid(grid) {\n  const h = grid.length;\n  const w = h ? grid[0].length : 0;\n  if (!h || grid[0][0] === 1 || grid[h - 1][w - 1] === 1) return -1;\n  const dist = grid.map((rw) => rw.map(() => -1));\n  const queue = [[0, 0]];\n  dist[0][0] = 1;\n  while (queue.length) {\n    const [r, c] = queue.shift();\n    if (r === h - 1 && c === w - 1) return dist[r][c];\n    [[1, 0], [-1, 0], [0, 1], [0, -1]].forEach(([dr, dc]) => {\n      const nr = r + dr;\n      const nc = c + dc;\n      if (nr < 0 || nc < 0 || nr >= h || nc >= w) return;\n      if (grid[nr][nc] === 1 || dist[nr][nc] !== -1) return;\n      dist[nr][nc] = dist[r][c] + 1;\n      queue.push([nr, nc]);\n    });\n  }\n  return -1;\n}",
  tests: [["shortestPathGrid([[0,0,0],[1,1,0],[0,0,0]])", "5"],
    ["shortestPathGrid([[0,1],[1,0]])", "-1"],
    ["shortestPathGrid([[0]])", "1"],
    ["shortestPathGrid([[0,0],[0,0]])", "3"]],
  edge: [["shortestPathGrid([[1]])", "-1"], ["shortestPathGrid([])", "-1"]],
  ex: "간선의 <b>비용이 모두 같으면</b> BFS 가 곧 최단거리입니다. 큐에서 꺼내는 순서가 거리 순이므로, 어떤 칸에 <b>처음 닿은 순간</b>이 그 칸까지의 최단입니다.\n그래서 방문 표시를 <b>큐에 넣을 때</b> 찍어야 합니다. 꺼낼 때 찍으면 같은 칸이 큐에 여러 번 들어가 시간이 폭발하고, 심하면 거리가 더 긴 경로로 덮어써집니다.\n여기서는 거리 배열이 방문 표시를 겸합니다. <code>-1</code> 은 '아직 안 닿음' 이라 별도 배열이 필요 없습니다.\n비용이 <b>서로 다르면</b> BFS 는 틀립니다. 그때는 다익스트라로 가야 하고, 비용이 0 아니면 1 뿐인 특수한 경우에는 덱을 쓰는 0-1 BFS 가 더 빠릅니다." },

{ track: "algo", k: "썩는 귤 · orangesRotting", cat: "internals",
  q: "<code>0</code> 은 빈칸, <code>1</code> 은 신선한 귤, <code>2</code> 는 썩은 귤입니다. 1분마다 썩은 귤이 <b>상하좌우</b> 신선한 귤을 썩게 합니다. 모두 썩는 데 걸리는 <b>분</b>을 돌려주고, 끝내 안 썩는 귤이 있으면 <code>-1</code> 입니다.",
  src: "function orangesRotting(grid) {\n  // TODO: 썩은 귤 전부를 동시에 출발점으로 삼으세요\n  return -1;\n}",
  sol: "function orangesRotting(grid) {\n  const h = grid.length;\n  const w = h ? grid[0].length : 0;\n  let fresh = 0;\n  let queue = [];\n  grid.forEach((rw, r) => rw.forEach((v, c) => {\n    if (v === 1) fresh++;\n    if (v === 2) queue.push([r, c]);\n  }));\n  let mins = 0;\n  while (queue.length && fresh) {\n    const nextQ = [];\n    queue.forEach(([r, c]) => [[1, 0], [-1, 0], [0, 1], [0, -1]].forEach(([dr, dc]) => {\n      const nr = r + dr;\n      const nc = c + dc;\n      if (nr < 0 || nc < 0 || nr >= h || nc >= w || grid[nr][nc] !== 1) return;\n      grid[nr][nc] = 2;\n      fresh--;\n      nextQ.push([nr, nc]);\n    }));\n    queue = nextQ;\n    mins++;\n  }\n  return fresh ? -1 : mins;\n}",
  tests: [["orangesRotting([[2,1,1],[1,1,0],[0,1,1]])", "4"],
    ["orangesRotting([[2,1,1],[0,1,1],[1,0,1]])", "-1"],
    ["orangesRotting([[0,2]])", "0"],
    ["orangesRotting([[2,2],[1,1]])", "1"]],
  edge: [["orangesRotting([[0]])", "0"], ["orangesRotting([[1]])", "-1"]],
  ex: "출발점이 여럿인 <b>다중 소스 BFS</b> 입니다. 썩은 귤을 <b>전부 큐에 먼저 넣고</b> 시작하면, 마치 출발점이 하나인 것처럼 한 번의 BFS 로 답이 나옵니다.\n한 번에 한 칸씩이 아니라 <b>한 층씩</b> 처리하는 것이 요령입니다. 지금 큐에 있는 것을 모두 처리한 뒤 시간을 1 늘리면, 층 번호가 곧 경과 시간이 됩니다.\n신선한 귤 수를 따로 세는 것이 <code>-1</code> 판정을 간단하게 만듭니다. 마지막에 격자를 다시 훑지 않아도 <code>fresh</code> 가 0인지만 보면 됩니다.\n신선한 귤이 처음부터 없으면 0을 돌려주어야 합니다. <code>while</code> 조건에 <code>fresh</code> 를 넣어 두면 반복이 한 번도 돌지 않아 이 경계가 저절로 처리됩니다." },

/* ───────────── 순서와 연결 ───────────── */
{ track: "algo", k: "위상 정렬 · topoSort", cat: "internals",
  q: "<code>[a, b]</code> 는 'a 를 끝내야 b 를 할 수 있다' 는 뜻입니다. 가능한 <b>작업 순서</b>를 돌려주세요. 고를 수 있는 것이 여럿이면 <b>번호가 작은 것부터</b>, 순서를 정할 수 없으면 빈 배열입니다.",
  src: "function topoSort(n, edges) {\n  // TODO: 들어오는 간선이 0인 것부터 꺼내세요\n  return [];\n}",
  sol: "function topoSort(n, edges) {\n  const next = Array.from({ length: n }, () => []);\n  const deg = new Array(n).fill(0);\n  edges.forEach(([a, b]) => { next[a].push(b); deg[b]++; });\n  const ready = [];\n  for (let v = 0; v < n; v++) if (deg[v] === 0) ready.push(v);\n  const order = [];\n  while (ready.length) {\n    ready.sort((a, b) => a - b);\n    const v = ready.shift();\n    order.push(v);\n    next[v].forEach((u) => { deg[u]--; if (deg[u] === 0) ready.push(u); });\n  }\n  return order.length === n ? order : [];\n}",
  tests: [["topoSort(4,[[0,1],[0,2],[1,3],[2,3]])", "[0,1,2,3]"],
    ["topoSort(3,[[0,1],[1,2]])", "[0,1,2]"],
    ["topoSort(2,[[0,1],[1,0]])", "[]"],
    ["topoSort(3,[])", "[0,1,2]"]],
  edge: [["topoSort(0,[])", "[]"], ["topoSort(1,[])", "[0]"]],
  ex: "'<b>지금 당장 할 수 있는 것</b>' 은 들어오는 간선이 없는 정점입니다. 하나 꺼낼 때마다 그 정점이 막고 있던 작업들의 차수를 줄이고, 0이 된 것을 새로 후보에 넣습니다.\n사이클 판정이 <b>공짜로</b> 따라옵니다. 사이클 안의 정점들은 서로를 막고 있어 차수가 영원히 0이 되지 않으므로, 꺼낸 개수가 n 보다 적으면 순환이 있다는 뜻입니다.\n후보가 여럿일 때 어느 것을 꺼내도 유효한 답입니다. 순서를 못 박으려면 <b>정렬</b>이 필요한데, 실무에서 '가능한 순서 아무거나' 와 '가장 이른 순서' 는 다른 요구입니다.\n빌드 의존성, 강의 선수 과목, 스프레드시트 수식 재계산이 모두 이 문제입니다. 순환 참조 오류 메시지는 대개 이 알고리즘이 만들어 냅니다." },

{ track: "algo", k: "방향 그래프 사이클 · hasCycleDirected", cat: "internals",
  q: "방향 그래프에 <b>사이클이 있으면</b> <code>true</code> 를 돌려주세요. 자기 자신을 가리키는 간선도 사이클입니다.",
  src: "function hasCycleDirected(n, edges) {\n  // TODO: 지금 내려가는 길에 있는 정점과 이미 끝난 정점을 구분하세요\n  return false;\n}",
  sol: "function hasCycleDirected(n, edges) {\n  const next = Array.from({ length: n }, () => []);\n  edges.forEach(([a, b]) => next[a].push(b));\n  const state = new Array(n).fill(0);\n  const go = (v) => {\n    state[v] = 1;\n    const bad = next[v].some((u) => state[u] === 1 || (state[u] === 0 && go(u)));\n    state[v] = 2;\n    return bad;\n  };\n  for (let v = 0; v < n; v++) if (state[v] === 0 && go(v)) return true;\n  return false;\n}",
  tests: [["hasCycleDirected(2,[[0,1],[1,0]])", "true"],
    ["hasCycleDirected(3,[[0,1],[1,2]])", "false"],
    ["hasCycleDirected(4,[[0,1],[1,2],[2,3],[3,1]])", "true"],
    ["hasCycleDirected(3,[[0,1],[0,2]])", "false"]],
  edge: [["hasCycleDirected(1,[[0,0]])", "true"], ["hasCycleDirected(0,[])", "false"]],
  ex: "방문 표시를 <b>두 단계로</b> 나누는 것이 핵심입니다. <code>1</code> 은 '<b>지금 내려가는 길 위에</b> 있음', <code>2</code> 는 '이미 다 보고 나왔음' 입니다.\n<code>1</code> 인 정점을 다시 만나면 되돌아온 것이니 사이클입니다. 반면 <code>2</code> 인 정점을 만나는 것은 <b>다른 길로 이미 지나간 곳</b>일 뿐이라 사이클이 아닙니다 — 이 구분을 못 하면 <code>[[0,1],[0,2]]</code> 같은 갈림길을 사이클로 잘못 봅니다.\n무방향 그래프에서는 규칙이 다릅니다. 부모로 되돌아가는 것은 사이클이 아니므로 '<b>부모가 아닌</b> 방문한 정점' 을 만났을 때만 사이클입니다.\n나오면서 <code>2</code> 로 바꾸는 것이 이 알고리즘의 이름을 만듭니다 — 회색·검은색으로 칠하는 DFS 이고, 위상 정렬의 재귀 판이기도 합니다." },

{ track: "algo", k: "연결 요소 세기 · countComponents", cat: "internals",
  q: "무방향 그래프에서 <b>서로 이어진 덩어리가 몇 개</b>인지 돌려주세요. 간선이 없는 정점도 하나의 덩어리입니다.",
  src: "function countComponents(n, edges) {\n  // TODO: 간선마다 두 정점을 같은 무리로 합치세요\n  return 0;\n}",
  sol: "function countComponents(n, edges) {\n  const parent = Array.from({ length: n }, (_, i) => i);\n  const find = (x) => {\n    while (parent[x] !== x) { parent[x] = parent[parent[x]]; x = parent[x]; }\n    return x;\n  };\n  let groups = n;\n  edges.forEach(([a, b]) => {\n    const ra = find(a);\n    const rb = find(b);\n    if (ra !== rb) { parent[ra] = rb; groups--; }\n  });\n  return groups;\n}",
  tests: [["countComponents(5,[[0,1],[1,2],[3,4]])", "2"],
    ["countComponents(5,[[0,1],[1,2],[2,3],[3,4]])", "1"],
    ["countComponents(4,[])", "4"],
    ["countComponents(4,[[0,1],[0,1]])", "3"]],
  edge: [["countComponents(0,[])", "0"], ["countComponents(1,[])", "1"]],
  ex: "유니온 파인드는 '<b>같은 무리인가</b>' 만 묻는 문제에 쓰는 자료구조입니다. 각 무리를 대표 하나로 가리키게 해 두고, 합칠 때 대표끼리 잇습니다.\n덩어리 수는 <b>세지 않고 빼면</b> 됩니다. n 개에서 시작해 <b>실제로 합쳐질 때만</b> 1을 줄이므로, 같은 간선이 두 번 들어와도 두 번 줄어들지 않습니다.\n<code>parent[x] = parent[parent[x]]</code> 한 줄이 <b>경로 압축</b>입니다. 찾아 올라가면서 나무를 납작하게 만들어, 반복하면 사실상 O(1) 에 가까워집니다.\nDFS 로도 같은 답을 얻지만, 유니온 파인드는 <b>간선이 하나씩 들어오는 상황</b>에 강합니다. 네트워크가 언제 연결되는지, 어느 두 계정이 같은 사용자인지 같은 문제에서 그대로 씁니다." },

{ track: "algo", k: "이분 그래프 판정 · bipartite", cat: "internals",
  q: "무방향 그래프의 정점을 <b>두 색으로 칠해</b> 간선의 양 끝이 항상 다른 색이 되게 할 수 있으면 <code>true</code> 를 돌려주세요.",
  src: "function bipartite(n, edges) {\n  // TODO: 한 정점을 칠하고 이웃을 반대색으로 칠해 나가세요\n  return false;\n}",
  sol: "function bipartite(n, edges) {\n  const near = Array.from({ length: n }, () => []);\n  edges.forEach(([a, b]) => { near[a].push(b); near[b].push(a); });\n  const color = new Array(n).fill(0);\n  for (let s = 0; s < n; s++) {\n    if (color[s]) continue;\n    color[s] = 1;\n    const queue = [s];\n    while (queue.length) {\n      const v = queue.shift();\n      for (const u of near[v]) {\n        if (color[u] === color[v]) return false;\n        if (!color[u]) { color[u] = -color[v]; queue.push(u); }\n      }\n    }\n  }\n  return true;\n}",
  tests: [["bipartite(4,[[0,1],[1,2],[2,3],[3,0]])", "true"],
    ["bipartite(3,[[0,1],[1,2],[2,0]])", "false"],
    ["bipartite(2,[[0,1]])", "true"],
    ["bipartite(4,[[0,1],[2,3]])", "true"]],
  edge: [["bipartite(1,[])", "true"], ["bipartite(1,[[0,0]])", "false"]],
  ex: "이분 그래프인지 아닌지는 '<b>홀수 길이 사이클이 있는가</b>' 와 같은 말입니다. 삼각형은 안 되고 사각형은 됩니다.\n색을 <code>1</code>·<code>-1</code> 로 두면 반대색이 <code>-color[v]</code> 한 줄이 됩니다. <code>0</code> 은 '아직 안 칠함' 이라 방문 표시를 겸합니다 — 세 상태를 값 하나로 담는 흔한 요령입니다.\n모든 정점에서 시작을 시도해야 합니다. 그래프가 <b>여러 덩어리</b>로 나뉘어 있으면 한 번의 BFS 로는 일부만 칠하게 되고, 다른 덩어리에 있는 홀수 사이클을 놓칩니다.\n실무에서는 두 집단으로 나눌 수 있는지 묻는 문제로 나옵니다 — 서로 싫어하는 사람을 다른 방에 배정하기, 작업을 두 기계에 나누기 같은 것입니다." },

{ track: "algo", k: "최소 신장 트리 · mstWeight", cat: "internals",
  q: "모든 정점을 잇는 데 드는 <b>간선 가중치의 최소 합</b>을 돌려주세요. 전부 이을 수 없으면 <code>-1</code> 입니다. 간선은 <code>[a, b, 가중치]</code> 입니다.",
  src: "function mstWeight(n, edges) {\n  // TODO: 싼 간선부터 보되, 이미 이어진 둘은 건너뛰세요\n  return -1;\n}",
  sol: "function mstWeight(n, edges) {\n  const parent = Array.from({ length: n }, (_, i) => i);\n  const find = (x) => {\n    while (parent[x] !== x) { parent[x] = parent[parent[x]]; x = parent[x]; }\n    return x;\n  };\n  const sorted = edges.slice().sort((a, b) => a[2] - b[2]);\n  let total = 0;\n  let joined = 0;\n  sorted.forEach(([a, b, w]) => {\n    const ra = find(a);\n    const rb = find(b);\n    if (ra === rb) return;\n    parent[ra] = rb;\n    total += w;\n    joined++;\n  });\n  return joined === n - 1 ? total : -1;\n}",
  tests: [["mstWeight(4,[[0,1,1],[1,2,2],[2,3,3],[0,3,10]])", "6"],
    ["mstWeight(3,[[0,1,5],[1,2,5],[0,2,1]])", "6"],
    ["mstWeight(3,[[0,1,1]])", "-1"],
    ["mstWeight(2,[[0,1,7],[0,1,3]])", "3"]],
  edge: [["mstWeight(1,[])", "0"], ["mstWeight(0,[])", "-1"]],
  ex: "크루스칼은 <b>그리디와 유니온 파인드가 만나는</b> 자리입니다. 싼 간선부터 보되, 두 끝이 이미 같은 무리면 <b>사이클이 되므로</b> 버립니다.\n왜 그리디가 옳은지는 절단 성질로 증명됩니다 — 어떤 절단을 가로지르는 가장 싼 간선은 최소 신장 트리에 반드시 들어갑니다. 그리디를 쓸 때는 이런 <b>보장 문장</b>이 있는지부터 확인해야 합니다.\n<code>joined === n - 1</code> 이 연결성 검사를 겸합니다. 신장 트리의 간선 수는 언제나 정점 수보다 하나 적으므로, 그보다 적게 이었다면 그래프가 나뉘어 있다는 뜻입니다.\n정점이 하나면 이을 간선이 없어 답이 0입니다. <code>n - 1 === 0</code> 이라 특별한 분기 없이 맞아떨어집니다." },

/* ───────────── 최단거리 ───────────── */
{ track: "algo", k: "다익스트라 · dijkstra", cat: "internals",
  q: "가중치가 <b>모두 0 이상</b>인 방향 그래프에서 <code>src</code> 로부터 각 정점까지의 <b>최단 거리 배열</b>을 돌려주세요. 닿을 수 없으면 <code>-1</code> 입니다.",
  src: "function dijkstra(n, edges, src) {\n  // TODO: 확정되지 않은 것 중 가장 가까운 정점을 하나씩 확정하세요\n  return [];\n}",
  sol: "function dijkstra(n, edges, src) {\n  const next = Array.from({ length: n }, () => []);\n  edges.forEach(([a, b, w]) => next[a].push([b, w]));\n  const dist = new Array(n).fill(Infinity);\n  const fixed = new Array(n).fill(false);\n  dist[src] = 0;\n  for (let step = 0; step < n; step++) {\n    let v = -1;\n    for (let i = 0; i < n; i++) if (!fixed[i] && (v < 0 || dist[i] < dist[v])) v = i;\n    if (v < 0 || dist[v] === Infinity) break;\n    fixed[v] = true;\n    next[v].forEach(([u, w]) => { if (dist[v] + w < dist[u]) dist[u] = dist[v] + w; });\n  }\n  return dist.map((d) => (d === Infinity ? -1 : d));\n}",
  tests: [["dijkstra(4,[[0,1,1],[1,2,2],[0,2,5],[2,3,1]],0)", "[0,1,3,4]"],
    ["dijkstra(3,[[0,1,4],[0,2,1],[2,1,2]],0)", "[0,3,1]"],
    ["dijkstra(3,[[0,1,1]],0)", "[0,1,-1]"],
    ["dijkstra(2,[],0)", "[0,-1]"]],
  edge: [["dijkstra(1,[],0)", "[0]"], ["dijkstra(3,[[1,2,1]],0)", "[0,-1,-1]"]],
  ex: "다익스트라는 '<b>가장 가까운 것부터 확정</b>' 하는 그리디입니다. 아직 확정 안 된 정점 중 거리가 가장 짧은 것은 더 줄어들 수 없으므로 그 자리에서 확정합니다.\n이 논리는 <b>가중치가 음수가 아닐 때만</b> 성립합니다. 음수 간선이 있으면 '멀리 돌아가서 더 짧아지는' 일이 생겨 확정한 값이 뒤집힙니다 — 그때는 벨만-포드로 가야 합니다.\n이 구현은 매번 전부 훑어 O(n²) 입니다. 정점이 많고 간선이 적으면 <b>최소 힙</b>으로 다음 정점을 골라 O(E log V) 로 줄입니다. 반대로 간선이 촘촘하면 O(n²) 쪽이 오히려 빠릅니다.\n<code>dist[v] === Infinity</code> 에서 멈추는 것은 '남은 정점에 닿을 방법이 없다' 는 뜻입니다. 이 검사를 빼면 무한대에 가중치를 더해 이상한 값이 퍼집니다." },

{ track: "algo", k: "벨만-포드 · bellmanFord", cat: "internals",
  q: "가중치가 <b>음수일 수도 있는</b> 방향 그래프에서 <code>src</code> 로부터의 최단 거리 배열을 돌려주세요. 닿을 수 없으면 <code>-1</code>, <b>음수 사이클</b>이 있으면 <code>null</code> 입니다.",
  src: "function bellmanFord(n, edges, src) {\n  // TODO: 모든 간선을 n-1 번 훑어 거리를 줄여 보세요\n  return null;\n}",
  sol: "function bellmanFord(n, edges, src) {\n  const dist = new Array(n).fill(Infinity);\n  dist[src] = 0;\n  for (let step = 0; step < n - 1; step++) {\n    edges.forEach(([a, b, w]) => {\n      if (dist[a] !== Infinity && dist[a] + w < dist[b]) dist[b] = dist[a] + w;\n    });\n  }\n  const loop = edges.some(([a, b, w]) => dist[a] !== Infinity && dist[a] + w < dist[b]);\n  if (loop) return null;\n  return dist.map((d) => (d === Infinity ? -1 : d));\n}",
  tests: [["bellmanFord(3,[[0,1,4],[0,2,5],[1,2,-3]],0)", "[0,4,1]"],
    ["bellmanFord(3,[[0,1,1],[1,2,-1],[2,1,-1]],0)", "null"],
    ["bellmanFord(2,[[0,1,3]],0)", "[0,3]"],
    ["bellmanFord(3,[[0,1,2]],0)", "[0,2,-1]"]],
  edge: [["bellmanFord(1,[],0)", "[0]"], ["bellmanFord(2,[[1,0,-5]],0)", "[0,-1]"]],
  ex: "간선을 <b>순서 상관없이</b> 계속 훑으며 줄여 나갑니다. 최단 경로는 정점을 최대 n−1 개 지나므로, n−1 번 훑으면 반드시 수렴합니다.\nn−1 번 뒤에도 <b>더 줄어드는 간선이 있다면</b> 음수 사이클입니다. 돌 때마다 값이 작아지니 최단 거리라는 개념 자체가 없어집니다 — 한 번 더 훑어 보는 것이 판정 전부입니다.\n<code>dist[a] !== Infinity</code> 검사를 빼면 안 됩니다. 무한대에 음수를 더하면 여전히 무한대라 자바스크립트에서는 조용히 넘어가지만, 정수로 무한대를 흉내 낸 언어에서는 <b>오버플로해 음수가 되어</b> 엉뚱한 경로가 생깁니다.\n음수 사이클은 환전 차익 거래, 잘못 설정된 할인 규칙처럼 <b>돌수록 이득이 나는 구조</b>를 찾는 데 쓰입니다 — 버그가 아니라 목적일 때도 있습니다." },

{ track: "algo", k: "플로이드-워셜 · floyd", cat: "internals",
  q: "<b>모든 정점 쌍</b> 사이의 최단 거리를 2차원 배열로 돌려주세요. 자기 자신은 0, 닿을 수 없으면 <code>-1</code> 입니다. 같은 두 정점 사이에 간선이 여럿이면 <b>가장 짧은 것</b>을 씁니다.",
  src: "function floyd(n, edges) {\n  // TODO: '거쳐 가는 정점' 을 바깥 반복으로 두세요\n  return [];\n}",
  sol: "function floyd(n, edges) {\n  const big = Infinity;\n  const dist = Array.from({ length: n }, (_, i) =>\n    Array.from({ length: n }, (_, j) => (i === j ? 0 : big)));\n  edges.forEach(([a, b, w]) => { if (w < dist[a][b]) dist[a][b] = w; });\n  for (let k = 0; k < n; k++) {\n    for (let i = 0; i < n; i++) {\n      for (let j = 0; j < n; j++) {\n        if (dist[i][k] + dist[k][j] < dist[i][j]) dist[i][j] = dist[i][k] + dist[k][j];\n      }\n    }\n  }\n  return dist.map((rw) => rw.map((d) => (d === big ? -1 : d)));\n}",
  tests: [["floyd(3,[[0,1,1],[1,2,2]])", "[[0,1,3],[-1,0,2],[-1,-1,0]]"],
    ["floyd(2,[[0,1,5],[1,0,1]])", "[[0,5],[1,0]]"],
    ["floyd(2,[])", "[[0,-1],[-1,0]]"],
    ["floyd(3,[[0,1,4],[0,2,1],[2,1,2]])", "[[0,3,1],[-1,0,-1],[-1,2,0]]"]],
  edge: [["floyd(1,[])", "[[0]]"], ["floyd(0,[])", "[]"]],
  ex: "세 겹 반복의 <b>순서가 전부</b> 입니다. 거쳐 가는 정점 <code>k</code> 가 반드시 <b>바깥</b>에 와야 합니다.\n의미는 '<code>0..k</code> 만 거쳐 갈 수 있을 때의 최단 거리' 입니다. k 를 하나씩 늘려 가며 표를 갱신하므로, k 를 안쪽에 두면 아직 완성되지 않은 값을 참조해 답이 틀립니다 — 코드는 거의 같아 보이는데 결과만 달라지는 무서운 실수입니다.\nO(n³) 이라 정점이 400을 넘으면 버겁습니다. 대신 <b>모든 쌍</b>을 한 번에 주고, 음수 간선도 다룰 수 있으며(음수 사이클만 없으면), 구현이 열 줄입니다.\n대각선이 음수가 되면 그 정점을 지나는 <b>음수 사이클</b>이 있다는 뜻입니다. 판정을 따로 짜지 않아도 표가 알려 줍니다." },
];
