/* 투 포인터 · 슬라이딩 윈도우 · 누적합 — 실행형이 각각 9·15·16문항뿐이던 유형.
   'O(n²) 를 O(n) 으로 접는' 세 가지 기술을 직접 구현으로 익힌다. */
module.exports = [

/* ───────────── 투 포인터 ───────────── */
{ track: "algo", k: "정렬된 배열의 두 수 · twoSumSorted", cat: "internals",
  q: "<b>오름차순으로 정렬된</b> 배열에서 합이 <code>target</code> 인 두 수를 찾아 <b>1부터 세는 자리 번호</b> 두 개를 돌려주세요. 없으면 빈 배열입니다.",
  src: "function twoSumSorted(xs, target) {\n  // TODO: 양 끝에서 하나씩 좁혀 오세요\n  return [];\n}",
  sol: "function twoSumSorted(xs, target) {\n  let lo = 0;\n  let hi = xs.length - 1;\n  while (lo < hi) {\n    const sum = xs[lo] + xs[hi];\n    if (sum === target) return [lo + 1, hi + 1];\n    if (sum < target) lo++;\n    else hi--;\n  }\n  return [];\n}",
  tests: [["twoSumSorted([2,7,11,15],9)", "[1,2]"],
    ["twoSumSorted([2,3,4],6)", "[1,3]"],
    ["twoSumSorted([1,2,3],7)", "[]"],
    ["twoSumSorted([-3,-1,0,4],1)", "[1,4]"]],
  edge: [["twoSumSorted([],5)", "[]"], ["twoSumSorted([3],3)", "[]"]],
  ex: "투 포인터가 성립하는 <b>전제</b>는 '정렬되어 있다' 입니다. 합이 작으면 왼쪽을 올려 키우고, 크면 오른쪽을 내려 줄입니다 — 정렬이 없으면 이 방향 판단 자체가 불가능합니다.\n왜 답을 놓치지 않는가가 중요합니다. 합이 작아서 <code>lo</code> 를 올릴 때, 지금의 <code>lo</code> 는 <b>어떤 오른쪽 짝과도</b> 답이 될 수 없습니다. 가장 큰 <code>hi</code> 와도 모자랐기 때문입니다. 그래서 버려도 안전합니다.\n정렬되지 않은 배열이라면 해시로 <code>target - x</code> 를 찾는 O(n) 풀이를 씁니다. 두 풀이는 <b>전제가 다른 도구</b>이지 우열 관계가 아닙니다.\n<code>lo &lt; hi</code> 로 두어 같은 자리를 두 번 쓰는 것을 막습니다. 등호를 넣으면 <code>[3]</code> 에서 3+3=6 같은 답이 나옵니다." },

{ track: "algo", k: "영숫자만 보는 팰린드롬 · isPalindromeAlnum", cat: "internals",
  q: "영문자와 숫자만 보고, <b>대소문자를 무시</b>했을 때 앞뒤가 같으면 <code>true</code> 를 돌려주세요. 나머지 문자는 없는 셈 칩니다.",
  src: "function isPalindromeAlnum(s) {\n  // TODO: 양 끝에서 좁히되, 볼 필요 없는 문자는 건너뛰세요\n  return false;\n}",
  sol: "function isPalindromeAlnum(s) {\n  const ok = (ch) => /[0-9a-z]/.test(ch || '');\n  const low = s.toLowerCase();\n  let lo = 0;\n  let hi = low.length - 1;\n  while (lo < hi) {\n    while (lo < hi && !ok(low[lo])) lo++;\n    while (lo < hi && !ok(low[hi])) hi--;\n    if (low[lo] !== low[hi]) return false;\n    lo++;\n    hi--;\n  }\n  return true;\n}",
  tests: [["isPalindromeAlnum('A man, a plan, a canal: Panama')", "true"],
    ["isPalindromeAlnum('race a car')", "false"],
    ["isPalindromeAlnum('ab_a')", "true"],
    ["isPalindromeAlnum('0P')", "false"]],
  edge: [["isPalindromeAlnum('')", "true"], ["isPalindromeAlnum(' ,.')", "true"]],
  ex: "걸러 낸 문자열을 <b>따로 만들지 않고</b> 원본 위에서 건너뛰는 것이 이 풀이의 요령입니다. 메모리를 쓰지 않고, 원래 자리 번호도 그대로 남습니다.\n안쪽 <code>while</code> 에도 <code>lo &lt; hi</code> 를 넣어야 합니다. 이 조건을 빼면 <code>' ,.'</code> 처럼 볼 문자가 하나도 없을 때 포인터가 서로를 지나쳐 배열 밖을 읽습니다.\n<code>'0P'</code> 가 false 인 이유가 이 문제의 함정입니다. 대소문자만 무시하고 <b>숫자와 문자를 같은 것으로 보면 안 됩니다</b> — <code>'0'</code> 과 <code>'p'</code> 는 다릅니다.\n대소문자 무시를 <code>toLowerCase</code> 한 번으로 끝내는 것도 요령입니다. 비교할 때마다 변환하면 같은 일을 두 배로 하게 됩니다." },

{ track: "algo", k: "가장 많은 물 · maxWater", cat: "internals",
  q: "높이 배열에서 <b>두 선분과 바닥이 만드는 물통</b>의 최대 넓이를 돌려주세요. 넓이는 <code>두 높이 중 작은 값 × 사이 거리</code> 입니다.",
  src: "function maxWater(heights) {\n  // TODO: 양 끝에서 시작해 낮은 쪽을 옮기세요\n  return 0;\n}",
  sol: "function maxWater(heights) {\n  let lo = 0;\n  let hi = heights.length - 1;\n  let best = 0;\n  while (lo < hi) {\n    const area = Math.min(heights[lo], heights[hi]) * (hi - lo);\n    if (area > best) best = area;\n    if (heights[lo] < heights[hi]) lo++;\n    else hi--;\n  }\n  return best;\n}",
  tests: [["maxWater([1,8,6,2,5,4,8,3,7])", "49"],
    ["maxWater([1,1])", "1"],
    ["maxWater([4,3,2,1,4])", "16"],
    ["maxWater([1,2,1])", "2"]],
  edge: [["maxWater([])", "0"], ["maxWater([5])", "0"]],
  ex: "왜 <b>낮은 쪽</b>을 옮기는지가 이 문제의 전부입니다. 넓이는 작은 높이에 갇혀 있으므로, 높은 쪽을 안으로 옮기면 거리는 줄고 높이는 그대로여서 <b>반드시 손해</b>입니다.\n낮은 쪽을 옮기면 거리는 줄지만 높이가 늘어날 <b>가능성</b>이 생깁니다. 그래서 이 이동만이 더 나은 답을 만들 여지를 남깁니다.\n모든 쌍을 보는 O(n²) 도 맞습니다. 투 포인터는 '<b>지금 버리는 후보가 정말 답이 될 수 없는가</b>' 를 논증할 수 있을 때만 O(n) 으로 줄여 줍니다 — 그 논증이 곧 정당성입니다.\n원소가 둘 미만이면 물통을 만들 수 없어 0입니다. <code>while (lo &lt; hi)</code> 가 한 번도 돌지 않아 초기값 0이 그대로 나갑니다." },

{ track: "algo", k: "세 색 정렬 · sortColors", cat: "internals",
  q: "0·1·2 로만 이루어진 배열을 <b>한 번만 훑어</b> 오름차순으로 정렬해 돌려주세요. 원본은 고치지 않습니다.",
  src: "function sortColors(xs) {\n  // TODO: 0 은 앞으로, 2 는 뒤로 보내는 포인터 세 개를 두세요\n  return xs.slice();\n}",
  sol: "function sortColors(xs) {\n  const arr = xs.slice();\n  let lo = 0;\n  let mid = 0;\n  let hi = arr.length - 1;\n  while (mid <= hi) {\n    if (arr[mid] === 0) {\n      [arr[lo], arr[mid]] = [arr[mid], arr[lo]];\n      lo++;\n      mid++;\n    } else if (arr[mid] === 2) {\n      [arr[mid], arr[hi]] = [arr[hi], arr[mid]];\n      hi--;\n    } else mid++;\n  }\n  return arr;\n}",
  tests: [["sortColors([2,0,2,1,1,0])", "[0,0,1,1,2,2]"],
    ["sortColors([2,0,1])", "[0,1,2]"],
    ["sortColors([0])", "[0]"],
    ["sortColors([1,1,1])", "[1,1,1]"]],
  edge: [["sortColors([])", "[]"], ["sortColors([2,2,0,0])", "[0,0,2,2]"]],
  ex: "네덜란드 국기 문제로 불리는 <b>3분할</b>입니다. 포인터 세 개가 배열을 '<b>0 구역 / 미확인 구역 / 2 구역</b>' 으로 나눠 가며 미확인 구역을 0으로 줄여 갑니다.\n2를 뒤로 보낼 때 <code>mid</code> 를 <b>올리지 않는</b> 것이 핵심입니다. 뒤에서 가져온 값이 무엇인지 아직 모르므로 그 자리를 다시 봐야 합니다. 여기서 <code>mid++</code> 를 하면 검사하지 않은 값이 그대로 남습니다.\n반대로 0을 앞으로 보낼 때는 올려도 됩니다. <code>lo</code> 자리에 있던 값은 이미 지나온 미확인 구역이라 1일 수밖에 없기 때문입니다.\n같은 3분할이 <b>퀵 정렬</b>에도 쓰입니다. 중복 값이 많은 배열에서 3분할 퀵 정렬은 같은 값을 다시 나누지 않아 눈에 띄게 빨라집니다." },

{ track: "algo", k: "정렬된 두 배열 병합 · mergeSortedTwo", cat: "internals",
  q: "오름차순으로 정렬된 두 배열을 <b>정렬을 유지한 채</b> 하나로 합쳐 돌려주세요. 값이 같으면 앞 배열의 것을 먼저 담습니다.",
  src: "function mergeSortedTwo(a, b) {\n  // TODO: 양쪽 앞을 견주며 작은 것부터 담으세요\n  return [];\n}",
  sol: "function mergeSortedTwo(a, b) {\n  const merged = [];\n  let i = 0;\n  let j = 0;\n  while (i < a.length && j < b.length) {\n    if (a[i] <= b[j]) merged.push(a[i++]);\n    else merged.push(b[j++]);\n  }\n  while (i < a.length) merged.push(a[i++]);\n  while (j < b.length) merged.push(b[j++]);\n  return merged;\n}",
  tests: [["mergeSortedTwo([1,3,5],[2,4,6])", "[1,2,3,4,5,6]"],
    ["mergeSortedTwo([],[1,2])", "[1,2]"],
    ["mergeSortedTwo([1,1],[1])", "[1,1,1]"],
    ["mergeSortedTwo([5],[1,2,3])", "[1,2,3,5]"]],
  edge: [["mergeSortedTwo([],[])", "[]"], ["mergeSortedTwo([2],[1])", "[1,2]"]],
  ex: "병합 정렬의 심장입니다. 두 포인터를 앞으로만 밀어 O(n + m) 에 끝나며, 합친 뒤 다시 정렬하는 O((n+m) log(n+m)) 보다 빠릅니다.\n<code>&lt;=</code> 인지 <code>&lt;</code> 인지가 <b>안정성</b>을 정합니다. 같을 때 앞 배열을 먼저 담아야 원래 순서가 보존되고, 이것이 '안정 정렬' 의 정의입니다 — 이름·부서로 두 번 정렬할 때 이 성질이 결과를 바꿉니다.\n남은 꼬리를 처리하는 두 <code>while</code> 을 빠뜨리기 쉽습니다. 한쪽이 먼저 바닥나면 반대쪽이 통째로 남는데, 이미 정렬되어 있으니 그대로 이어 붙이면 됩니다.\n이 골격은 파일이 메모리에 안 들어갈 때도 그대로 씁니다 — 정렬된 조각들을 순차로 읽어 합치는 외부 병합 정렬이 그것입니다." },

/* ───────────── 슬라이딩 윈도우 ───────────── */
{ track: "algo", k: "고정 크기 최대 합 · maxSumWindow", cat: "internals",
  q: "연속한 <code>k</code> 개의 합 중 <b>가장 큰 값</b>을 돌려주세요. 배열이 <code>k</code> 보다 짧거나 <code>k</code> 가 0 이하면 0 입니다.",
  src: "function maxSumWindow(xs, k) {\n  // TODO: 창을 한 칸 밀 때 더하고 빼기만 하세요\n  return 0;\n}",
  sol: "function maxSumWindow(xs, k) {\n  if (k <= 0 || xs.length < k) return 0;\n  let sum = 0;\n  for (let i = 0; i < k; i++) sum += xs[i];\n  let best = sum;\n  for (let i = k; i < xs.length; i++) {\n    sum += xs[i] - xs[i - k];\n    if (sum > best) best = sum;\n  }\n  return best;\n}",
  tests: [["maxSumWindow([1,4,2,10,2,3,1,0,20],4)", "24"],
    ["maxSumWindow([2,3],2)", "5"],
    ["maxSumWindow([1,2,3,4],1)", "4"],
    ["maxSumWindow([-1,-2,-3],2)", "-3"]],
  edge: [["maxSumWindow([1,2],3)", "0"], ["maxSumWindow([1,2],0)", "0"]],
  ex: "창을 한 칸 밀 때 <b>전부 다시 더하지 않는</b> 것이 슬라이딩 윈도우입니다. 들어온 하나를 더하고 나간 하나를 빼면 O(1) 이므로 전체가 O(n) 이 됩니다.\n다시 더하면 O(n·k) 입니다. n 이 10만이고 k 가 1,000이면 1억 번이라 통과하지 못합니다 — <b>겹치는 계산을 버리지 않는 것</b>이 이 기술의 전부입니다.\n최댓값 초기화를 0으로 두면 안 됩니다. <code>[-1,-2,-3]</code> 처럼 전부 음수면 있지도 않은 0이 답이 됩니다. <b>첫 창의 합</b>으로 시작해야 합니다.\n같은 아이디어가 이동 평균, 최근 1분 요청 수, 실시간 이상 탐지에 그대로 쓰입니다. 창이 시간이면 '들어오고 나가는' 것이 이벤트가 됩니다." },

{ track: "algo", k: "합이 목표 이상인 최소 길이 · minSubArrayLen", cat: "internals",
  q: "양수 배열에서 <b>합이 <code>target</code> 이상</b>이 되는 연속 부분배열의 <b>최소 길이</b>를 돌려주세요. 그런 부분배열이 없으면 0 입니다.",
  src: "function minSubArrayLen(target, xs) {\n  // TODO: 오른쪽으로 늘리고, 조건을 만족하면 왼쪽을 줄이세요\n  return 0;\n}",
  sol: "function minSubArrayLen(target, xs) {\n  let lo = 0;\n  let sum = 0;\n  let best = Infinity;\n  for (let hi = 0; hi < xs.length; hi++) {\n    sum += xs[hi];\n    while (sum >= target) {\n      if (hi - lo + 1 < best) best = hi - lo + 1;\n      sum -= xs[lo];\n      lo++;\n    }\n  }\n  return best === Infinity ? 0 : best;\n}",
  tests: [["minSubArrayLen(7,[2,3,1,2,4,3])", "2"],
    ["minSubArrayLen(4,[1,4,4])", "1"],
    ["minSubArrayLen(11,[1,1,1,1,1,1,1,1])", "0"],
    ["minSubArrayLen(3,[1,1,1])", "3"]],
  edge: [["minSubArrayLen(1,[])", "0"], ["minSubArrayLen(15,[1,2,3,4,5])", "5"]],
  ex: "창의 크기가 <b>고정이 아닌</b> 슬라이딩 윈도우입니다. 오른쪽 끝은 한 칸씩 늘리고, 조건을 만족하는 동안 왼쪽 끝을 당겨 창을 최대한 줄입니다.\n두 포인터가 <b>각각 최대 n 번만</b> 앞으로 가므로 전체가 O(n) 입니다. 안쪽에 <code>while</code> 이 있어 O(n²) 처럼 보이지만, <code>lo</code> 는 되돌아가지 않으므로 총 이동 횟수가 n 을 넘지 않습니다.\n이 기법은 <b>양수 배열</b>에서만 성립합니다. 음수가 섞이면 창을 줄였는데 합이 오히려 늘 수 있어 '조건을 만족하는 동안 줄인다' 는 논리가 깨집니다 — 그때는 누적합과 정렬·이분탐색으로 갑니다.\n찾지 못했을 때를 0으로 돌려주려면 <code>Infinity</code> 로 시작해야 합니다. 0으로 시작하면 답이 있어도 0이 최솟값으로 남습니다." },

{ track: "algo", k: "중복 없는 최장 부분 문자열 · longestUnique", cat: "internals",
  q: "같은 문자가 <b>두 번 나오지 않는</b> 가장 긴 연속 부분 문자열의 <b>길이</b>를 돌려주세요.",
  src: "function longestUnique(s) {\n  // TODO: 문자가 마지막으로 나온 자리를 기억해 두세요\n  return 0;\n}",
  sol: "function longestUnique(s) {\n  const at = new Map();\n  let lo = 0;\n  let best = 0;\n  [...s].forEach((ch, hi) => {\n    if (at.has(ch) && at.get(ch) >= lo) lo = at.get(ch) + 1;\n    at.set(ch, hi);\n    if (hi - lo + 1 > best) best = hi - lo + 1;\n  });\n  return best;\n}",
  tests: [["longestUnique('abcabcbb')", "3"],
    ["longestUnique('bbbbb')", "1"],
    ["longestUnique('pwwkew')", "3"],
    ["longestUnique('abba')", "2"]],
  edge: [["longestUnique('')", "0"], ["longestUnique('a')", "1"]],
  ex: "왼쪽 끝을 <b>한 칸씩 당기지 않고 한 번에 건너뜁니다.</b> 지금 문자가 이전에 나온 자리 바로 다음으로 <code>lo</code> 를 옮기면 중복이 사라집니다.\n<code>at.get(ch) &gt;= lo</code> 조건이 이 문제의 함정입니다. <code>'abba'</code> 에서 마지막 <code>a</code> 를 만났을 때 기록된 자리는 0인데, 창은 이미 2부터 시작했습니다. 조건을 빼면 <code>lo</code> 가 <b>뒤로 되돌아가</b> 길이가 잘못 늘어납니다.\n창 안의 문자를 <code>Set</code> 에 담아 하나씩 빼는 풀이도 맞습니다. 다만 이쪽이 '마지막 자리' 하나만 들고 있어 더 간결하고, 되돌아가지 않으므로 O(n) 이 분명합니다.\n<code>[...s]</code> 로 펼치는 것은 서로게이트 쌍을 한 글자로 세기 위해서입니다. 이모지가 섞인 입력에서 <code>s[i]</code> 는 글자를 반으로 쪼갭니다." },

{ track: "algo", k: "아나그램 창 세기 · countAnagramWindows", cat: "internals",
  q: "문자열 <code>s</code> 안에 <code>p</code> 의 <b>아나그램</b>(문자 구성이 같은 것)이 연속으로 나타나는 횟수를 세세요. 자리가 다르면 다른 것으로 셉니다.",
  src: "function countAnagramWindows(s, p) {\n  // TODO: 창을 밀면서 '아직 모자란 문자 종류' 수만 관리하세요\n  return 0;\n}",
  sol: "function countAnagramWindows(s, p) {\n  const k = p.length;\n  if (k === 0 || s.length < k) return 0;\n  const need = new Map();\n  [...p].forEach((ch) => need.set(ch, (need.get(ch) || 0) + 1));\n  let missing = need.size;\n  let hits = 0;\n  const shift = (ch, d) => {\n    if (!need.has(ch)) return;\n    const was = need.get(ch);\n    need.set(ch, was - d);\n    if (was - d === 0) missing--;\n    if (was === 0) missing++;\n  };\n  [...s].forEach((ch, i) => {\n    shift(ch, 1);\n    if (i >= k) shift(s[i - k], -1);\n    if (i >= k - 1 && missing === 0) hits++;\n  });\n  return hits;\n}",
  tests: [["countAnagramWindows('cbaebabacd','abc')", "2"],
    ["countAnagramWindows('abab','ab')", "3"],
    ["countAnagramWindows('aaa','a')", "3"],
    ["countAnagramWindows('abc','abcd')", "0"]],
  edge: [["countAnagramWindows('','a')", "0"], ["countAnagramWindows('ab','')", "0"]],
  ex: "창마다 문자를 세어 비교하면 O(n·k) 입니다. 대신 '<b>아직 개수가 맞지 않는 문자 종류가 몇 가지인가</b>' 하나만 들고 다니면 갱신이 O(1) 이 되어 전체가 O(n) 이 됩니다.\n들어오고 나갈 때마다 그 문자의 부족분을 고치고, <b>0이 되는 순간과 0에서 벗어나는 순간</b>에만 종류 수를 조정합니다. 두 조건을 모두 써야 하며, 하나만 쓰면 창을 밀 때 수가 어긋납니다.\n<code>p</code> 에 없는 문자는 아예 무시해도 됩니다. 창 크기가 <code>k</code> 로 고정이므로, <code>p</code> 의 문자 개수가 전부 맞으면 남는 자리가 없어 자동으로 아나그램입니다.\n정렬해서 비교하는 풀이도 맞지만 창마다 <code>k log k</code> 가 듭니다. 로그 필터링·DNA 서열 검색처럼 창이 수백만 개인 상황에서는 차이가 결정적입니다." },

{ track: "algo", k: "뒤집어 만드는 최장 구간 · longestOnesAfterFlip", cat: "internals",
  q: "0과 1로 된 배열에서 <b>0을 최대 <code>k</code> 개까지 1로 바꿀 수 있을 때</b> 만들 수 있는 가장 긴 연속 1 구간의 길이를 돌려주세요.",
  src: "function longestOnesAfterFlip(xs, k) {\n  // TODO: 창 안의 0 개수가 k 를 넘으면 왼쪽을 당기세요\n  return 0;\n}",
  sol: "function longestOnesAfterFlip(xs, k) {\n  let lo = 0;\n  let zeros = 0;\n  let best = 0;\n  for (let hi = 0; hi < xs.length; hi++) {\n    if (xs[hi] === 0) zeros++;\n    while (zeros > k) {\n      if (xs[lo] === 0) zeros--;\n      lo++;\n    }\n    if (hi - lo + 1 > best) best = hi - lo + 1;\n  }\n  return best;\n}",
  tests: [["longestOnesAfterFlip([1,1,1,0,0,0,1,1,1,1,0],2)", "6"],
    ["longestOnesAfterFlip([0,0,1,1,0],0)", "2"],
    ["longestOnesAfterFlip([1,1],5)", "2"],
    ["longestOnesAfterFlip([0,0,0],2)", "2"]],
  edge: [["longestOnesAfterFlip([],1)", "0"], ["longestOnesAfterFlip([0],0)", "0"]],
  ex: "문제를 다시 쓰면 '<b>0이 k 개 이하인 가장 긴 창</b>' 입니다. 무엇을 뒤집을지 고를 필요가 없어지는 순간 슬라이딩 윈도우가 들어맞습니다.\n창을 줄이는 조건이 <code>zeros &gt; k</code> 입니다. 같을 때는 줄이지 않아야 하며, <code>&gt;=</code> 로 쓰면 정확히 k 개를 뒤집는 최적 구간을 놓칩니다.\n<code>k</code> 가 0이면 '뒤집지 않고 가장 긴 1 구간' 이 되고, <code>k</code> 가 배열 길이보다 크면 전체가 답이 됩니다. 특수 분기 없이 <b>같은 코드가 두 극단을 모두 처리</b>합니다.\n이 골격은 '조건을 어기면 왼쪽을 당긴다' 라는 한 문장으로 요약됩니다. 조건만 바꾸면 '서로 다른 문자 k 종류 이하인 최장 구간' 같은 문제로 그대로 옮겨 갑니다." },

/* ───────────── 누적합 ───────────── */
{ track: "algo", k: "구간 합 질의 · prefixRangeSum", cat: "internals",
  q: "여러 개의 <code>[l, r]</code> 구간에 대해 <b>그 구간의 합</b>을 차례로 돌려주세요. 자리 번호는 0부터 세고 <b>양 끝을 포함</b>합니다.",
  src: "function prefixRangeSum(xs, queries) {\n  // TODO: 앞에서부터의 누적합을 한 번만 만들어 두세요\n  return [];\n}",
  sol: "function prefixRangeSum(xs, queries) {\n  const acc = [0];\n  xs.forEach((x, i) => acc.push(acc[i] + x));\n  return queries.map(([l, r]) => acc[r + 1] - acc[l]);\n}",
  tests: [["prefixRangeSum([1,2,3,4,5],[[0,2],[1,3],[4,4]])", "[6,9,5]"],
    ["prefixRangeSum([5],[[0,0]])", "[5]"],
    ["prefixRangeSum([1,1,1],[[0,2]])", "[3]"],
    ["prefixRangeSum([2,-1,3],[[0,1],[1,2]])", "[1,2]"]],
  edge: [["prefixRangeSum([1,2],[])", "[]"], ["prefixRangeSum([],[])", "[]"]],
  ex: "질의가 많을 때는 <b>미리 계산해 두는</b> 것이 답입니다. 질의마다 훑으면 O(질의 × n) 이지만, 누적합을 한 번 만들어 두면 질의마다 <b>뺄셈 한 번</b>으로 끝납니다.\n누적합 배열을 <b>0으로 시작해 n + 1 칸</b>으로 두는 것이 요령입니다. 그러면 <code>l</code> 이 0일 때도 <code>acc[l]</code> 이 존재해 경계 분기가 사라집니다 — 배열을 한 칸 늘려 <code>if</code> 를 없애는 흔한 기법입니다.\n<code>acc[r + 1] - acc[l]</code> 에서 <code>+ 1</code> 을 빠뜨리면 오른쪽 끝이 빠집니다. 포함·미포함 규약을 <b>주석이 아니라 테스트로</b> 못 박아 두어야 합니다.\n2차원으로 넓히면 직사각형 영역 합이 되고(포함-배제로 네 값을 더하고 뺍니다), 값을 갱신해야 하면 펜윅 트리나 세그먼트 트리로 넘어갑니다." },

{ track: "algo", k: "합이 k 인 부분배열 세기 · subarraySumCount", cat: "internals",
  q: "합이 정확히 <code>k</code> 인 <b>연속 부분배열</b>이 몇 개인지 세세요. 음수가 섞여 있을 수 있습니다.",
  src: "function subarraySumCount(xs, k) {\n  // TODO: 누적합의 차이가 k 인 쌍을 세면 됩니다\n  return 0;\n}",
  sol: "function subarraySumCount(xs, k) {\n  const seen = new Map([[0, 1]]);\n  let acc = 0;\n  let found = 0;\n  xs.forEach((x) => {\n    acc += x;\n    found += seen.get(acc - k) || 0;\n    seen.set(acc, (seen.get(acc) || 0) + 1);\n  });\n  return found;\n}",
  tests: [["subarraySumCount([1,1,1],2)", "2"],
    ["subarraySumCount([1,2,3],3)", "2"],
    ["subarraySumCount([1,-1,0],0)", "3"],
    ["subarraySumCount([3],3)", "1"]],
  edge: [["subarraySumCount([],5)", "0"], ["subarraySumCount([0,0],0)", "3"]],
  ex: "구간 <code>(i, j]</code> 의 합은 <code>acc[j] - acc[i]</code> 입니다. 그러니 '합이 k 인 구간' 을 세는 것은 '<b>차이가 k 인 누적합 쌍</b>' 을 세는 것과 같습니다.\n지금 누적합이 <code>acc</code> 일 때 필요한 짝은 <code>acc - k</code> 입니다. 그 값이 앞에서 몇 번 나왔는지를 해시로 세어 두면 한 번 훑는 것으로 끝납니다.\n<code>seen</code> 을 <code>{0: 1}</code> 로 <b>미리 채워 두는</b> 것이 핵심입니다. 처음부터 시작하는 구간(<code>acc</code> 자체가 k 인 경우)을 세려면 '아무것도 안 더한 상태' 도 후보여야 합니다.\n음수가 섞이면 슬라이딩 윈도우는 쓸 수 없습니다. 창을 줄여도 합이 줄어든다는 보장이 없기 때문인데, 누적합과 해시는 <b>음수가 있어도 그대로 성립</b>합니다 — 도구를 고를 때 이 차이를 먼저 봅니다." },
];
