/* 트리 · 힙 — algo 트랙에 실행형이 15문항뿐이던 유형.
   노드는 { v, l, r } 이고 없는 자식은 null 이다. 재귀로 읽기, 순회, BST 성질, 배열 힙. */
module.exports = [

/* ───────────── 재귀로 읽는 트리 ───────────── */
{ track: "algo", k: "트리의 최대 깊이 · maxDepth", cat: "internals",
  q: "이진 트리의 <b>최대 깊이</b>(뿌리부터 가장 먼 잎까지의 노드 수)를 돌려주세요. 빈 트리는 <code>0</code> 입니다. 노드는 <code>{ v, l, r }</code> 이고 없는 자식은 <code>null</code> 입니다.",
  src: "function maxDepth(root) {\n  // TODO: 빈 트리에서 멈추고, 두 자식 중 깊은 쪽에 1을 더하세요\n  return 1;\n}",
  sol: "function maxDepth(root) {\n  if (!root) return 0;\n  return 1 + Math.max(maxDepth(root.l), maxDepth(root.r));\n}",
  tests: [["maxDepth({v:1,l:null,r:null})", "1"],
    ["maxDepth({v:1,l:{v:2,l:null,r:null},r:null})", "2"],
    ["maxDepth({v:1,l:{v:2,l:{v:4,l:null,r:null},r:null},r:{v:3,l:null,r:null}})", "3"],
    ["maxDepth({v:1,l:null,r:{v:2,l:null,r:{v:3,l:null,r:null}}})", "3"]],
  edge: [["maxDepth(null)", "0"],
    ["maxDepth({v:1,l:{v:2,l:{v:3,l:{v:4,l:null,r:null},r:null},r:null},r:null})", "4"]],
  ex: "트리 재귀는 <b>세 줄로 끝나는 것이 정상</b>입니다. 멈추는 조건 한 줄, 자식에게 같은 질문을 던지는 한 줄, 그 답을 합치는 한 줄입니다. 이 문제에서는 각각 <code>if (!root) return 0</code>, <code>maxDepth(root.l)</code>, <code>1 + Math.max(...)</code> 입니다.\n초보가 가장 많이 틀리는 곳은 <b>멈추는 자리</b>입니다. '잎에서 멈춘다' 로 짜면 <code>if (!root.l &amp;&amp; !root.r) return 1</code> 이 되는데, 이러면 자식이 하나뿐인 노드에서 <code>null</code> 을 파고들다 터집니다. <b><code>null</code> 에서 멈추면</b> 그런 분기가 아예 필요 없습니다.\n깊이를 '간선 수' 로 셀지 '노드 수' 로 셀지는 문제마다 다릅니다. 둘은 항상 1 차이라 정의만 못 박으면 되는데, 그 한 문장을 안 정하고 시작해 <b>off-by-one</b> 을 내는 일이 흔합니다. 여기서는 노드 수라서 잎이 <code>1</code> 입니다.\n재귀 깊이는 트리 높이에 비례합니다. 한쪽으로 치우친 10만 노드짜리 트리라면 스택이 넘칠 수 있으므로, 그때는 명시적 스택을 쓴 반복 버전으로 바꿉니다." },

{ track: "algo", k: "좌우 대칭 판정 · isSymmetric", cat: "internals",
  q: "이진 트리가 <b>거울처럼 좌우 대칭</b>인지 판정해 주세요. 값과 모양이 모두 대칭이어야 합니다.",
  src: "function isSymmetric(root) {\n  // TODO: 한 노드가 아니라 '두 노드'를 함께 내려가야 합니다\n  return true;\n}",
  sol: "function isSymmetric(root) {\n  const same = (a, b) => {\n    if (!a && !b) return true;\n    if (!a || !b) return false;\n    if (a.v !== b.v) return false;\n    return same(a.l, b.r) && same(a.r, b.l);\n  };\n  return !root || same(root.l, root.r);\n}",
  tests: [["isSymmetric({v:1,l:{v:2,l:null,r:null},r:{v:2,l:null,r:null}})", "true"],
    ["isSymmetric({v:1,l:{v:2,l:null,r:null},r:{v:3,l:null,r:null}})", "false"],
    ["isSymmetric({v:1,l:{v:2,l:{v:3,l:null,r:null},r:null},r:{v:2,l:null,r:{v:3,l:null,r:null}}})", "true"],
    ["isSymmetric({v:1,l:{v:2,l:{v:3,l:null,r:null},r:null},r:{v:2,l:{v:3,l:null,r:null},r:null}})", "false"]],
  edge: [["isSymmetric(null)", "true"], ["isSymmetric({v:7,l:null,r:null})", "true"]],
  ex: "혼자 내려가는 재귀로는 풀리지 않습니다. 대칭은 <b>두 노드 사이의 관계</b>라서, 인자를 두 개 받는 도우미 함수를 만들어 <code>a.l</code> 과 <code>b.r</code> 을 짝지어 내려가야 합니다.\n짝을 <b>엇갈리게</b> 거는 것이 핵심입니다. <code>same(a.l, b.l)</code> 로 쓰면 대칭이 아니라 '두 트리가 같은가' 를 묻는 다른 문제가 됩니다. 네 번째 테스트가 정확히 그 실수를 잡으려고 놓은 입력입니다 — 두 자식이 서로 <b>같지만</b> 거울은 아닙니다.\n<code>null</code> 처리를 두 단계로 나눈 것에도 이유가 있습니다. <b>둘 다 없으면</b> 대칭이고, <b>하나만 없으면</b> 모양이 어긋난 것입니다. 이 둘을 한 줄로 합치려다 <code>null.v</code> 를 읽는 오류가 자주 납니다.\n같은 골격으로 '두 트리가 동일한가', '한 트리가 다른 트리의 부분 트리인가' 를 풉니다. <b>두 포인터를 함께 움직이는 재귀</b>라는 형태를 익혀 두면 트리 문제의 절반이 같은 모양으로 보입니다." },

{ track: "algo", k: "트리의 지름 · diameter", cat: "internals",
  q: "트리에서 두 노드를 잇는 <b>가장 긴 경로의 간선 수</b>를 돌려주세요. 그 경로가 뿌리를 지날 필요는 없습니다.",
  src: "function diameter(root) {\n  // TODO: 깊이를 구하면서, 지나가는 김에 답을 갱신하세요\n  return 0;\n}",
  sol: "function diameter(root) {\n  let best = 0;\n  const depth = (node) => {\n    if (!node) return 0;\n    const a = depth(node.l);\n    const b = depth(node.r);\n    if (a + b > best) best = a + b;\n    return 1 + Math.max(a, b);\n  };\n  depth(root);\n  return best;\n}",
  tests: [["diameter({v:1,l:{v:2,l:null,r:null},r:{v:3,l:null,r:null}})", "2"],
    ["diameter({v:1,l:{v:2,l:{v:4,l:null,r:null},r:{v:5,l:null,r:null}},r:{v:3,l:null,r:null}})", "3"],
    ["diameter({v:1,l:null,r:{v:2,l:null,r:{v:3,l:null,r:null}}})", "2"],
    ["diameter({v:1,l:{v:2,l:{v:3,l:{v:4,l:null,r:null},r:null},r:null},r:null})", "3"]],
  edge: [["diameter(null)", "0"], ["diameter({v:1,l:null,r:null})", "0"]],
  ex: "이 문제가 어려운 이유는 <b>돌려주는 값과 구하려는 값이 다르다</b>는 점입니다. 재귀가 돌려주는 것은 '내 아래로의 깊이' 인데, 답은 '나를 꼭짓점으로 하는 경로의 길이' 라서 <b>바깥 변수에 따로 적어 둡니다</b>.\n한 노드에서 만들 수 있는 가장 긴 경로는 <code>왼쪽 깊이 + 오른쪽 깊이</code> 입니다. 모든 노드에서 이 값을 재어 최댓값을 남기면, 답이 되는 경로의 <b>가장 높은 노드</b>에서 반드시 걸립니다. 그래서 뿌리를 지나지 않는 경로도 놓치지 않습니다.\n부모에게는 <code>1 + Math.max(a, b)</code> 만 돌려줘야 합니다. <code>a + b</code> 를 돌려주면 경로가 부모에서 다시 갈라져 <b>트리가 아닌 무언가</b>가 되어 버립니다. 이 두 값을 헷갈리는 것이 오답의 대부분입니다.\n'재귀는 한 가지만 돌려주고, 답은 밖에 적어 둔다' 는 이 형태는 최대 경로 합, 가장 긴 같은 값 경로, 트리 DP 로 그대로 이어집니다. 한 번 훑어 O(n) 이라는 점도 같습니다." },

{ track: "algo", k: "거울 트리의 전위 순회 · mirrorPreorder", cat: "internals",
  q: "트리를 <b>좌우로 뒤집은 뒤</b> 전위 순회한 값 배열을 돌려주세요. 트리를 실제로 고치지 않고도 됩니다.",
  src: "function mirrorPreorder(root) {\n  // TODO: 뒤집는 대신 방문 순서를 바꾸면 됩니다\n  return [];\n}",
  sol: "function mirrorPreorder(root) {\n  if (!root) return [];\n  return [root.v].concat(mirrorPreorder(root.r), mirrorPreorder(root.l));\n}",
  tests: [["mirrorPreorder({v:1,l:{v:2,l:null,r:null},r:{v:3,l:null,r:null}})", "[1,3,2]"],
    ["mirrorPreorder({v:1,l:{v:2,l:{v:4,l:null,r:null},r:null},r:{v:3,l:null,r:null}})", "[1,3,2,4]"],
    ["mirrorPreorder({v:1,l:null,r:{v:2,l:null,r:{v:3,l:null,r:null}}})", "[1,2,3]"],
    ["mirrorPreorder({v:5,l:{v:3,l:{v:1,l:null,r:null},r:{v:4,l:null,r:null}},r:null})", "[5,3,4,1]"]],
  edge: [["mirrorPreorder(null)", "[]"], ["mirrorPreorder({v:9,l:null,r:null})", "[9]"]],
  ex: "'뒤집어라' 는 말을 그대로 따라 <b>노드를 실제로 바꾸는</b> 코드를 짜기 쉽습니다. 하지만 필요한 것이 순회 결과뿐이라면 <b>오른쪽을 먼저 방문</b>하는 것으로 끝납니다. 입력을 건드리지 않으니 원본이 다른 곳에서 그대로 쓰이고 있어도 안전합니다.\n이것은 실무에서 되풀이되는 판단입니다. 자료 구조를 <b>변형할지, 읽는 순서만 바꿀지</b>는 성능이 아니라 <b>누가 그 자료를 또 보는가</b>로 정해집니다. 공유된 객체를 조용히 뒤집어 놓으면 멀리 떨어진 코드가 깨지고, 그 원인을 찾기는 매우 어렵습니다.\n실제로 트리를 뒤집어야 한다면 <code>[node.l, node.r] = [node.r, node.l]</code> 을 각 노드에서 하고 내려가면 됩니다. 다만 <b>돌려주는 값</b>이 새 트리인지 원본을 고친 것인지를 이름에 드러내야 합니다 — <code>invert</code> 와 <code>inverted</code> 는 다른 약속입니다.\n<code>concat</code> 대신 바깥 배열에 <code>push</code> 하는 방식이 더 빠릅니다. 노드가 수만 개라면 매번 새 배열을 만드는 비용이 쌓이므로, 누산 배열을 인자로 넘기는 형태로 바꿉니다." },

/* ───────────── 순회와 이진 탐색 트리 ───────────── */
{ track: "algo", k: "스택으로 중위 순회 · inorderIter", cat: "internals",
  q: "재귀 없이 <b>스택만으로</b> 중위 순회(왼쪽 → 자기 → 오른쪽) 결과 배열을 만들어 주세요.",
  src: "function inorderIter(root) {\n  // TODO: 왼쪽으로 끝까지 내려가며 스택에 쌓고, 꺼낼 때 값을 담으세요\n  return [];\n}",
  sol: "function inorderIter(root) {\n  const out = [];\n  const stack = [];\n  let node = root;\n  while (node || stack.length) {\n    while (node) {\n      stack.push(node);\n      node = node.l;\n    }\n    node = stack.pop();\n    out.push(node.v);\n    node = node.r;\n  }\n  return out;\n}",
  tests: [["inorderIter({v:2,l:{v:1,l:null,r:null},r:{v:3,l:null,r:null}})", "[1,2,3]"],
    ["inorderIter({v:5,l:{v:3,l:{v:1,l:null,r:null},r:{v:4,l:null,r:null}},r:{v:8,l:null,r:null}})", "[1,3,4,5,8]"],
    ["inorderIter({v:1,l:null,r:{v:2,l:null,r:{v:3,l:null,r:null}}})", "[1,2,3]"],
    ["inorderIter({v:3,l:{v:2,l:{v:1,l:null,r:null},r:null},r:null})", "[1,2,3]"]],
  edge: [["inorderIter(null)", "[]"], ["inorderIter({v:7,l:null,r:null})", "[7]"]],
  ex: "재귀를 반복으로 바꾸는 일은 결국 <b>호출 스택을 손으로 만드는</b> 일입니다. 여기서 스택에 담기는 것은 '값을 아직 안 꺼낸, 되돌아와야 할 노드' 들입니다.\n바깥 <code>while</code> 조건이 <code>node || stack.length</code> 인 것이 중요합니다. 스택이 비어 있어도 <b>지금 손에 든 노드</b>가 있으면 아직 끝난 것이 아니고, 손이 비어 있어도 <b>되돌아갈 곳</b>이 남아 있으면 끝이 아닙니다. 둘 중 하나만 보면 결과가 잘립니다.\n중위 순회는 <b>이진 탐색 트리에서 오름차순</b>을 줍니다. 그래서 'BST 인가?' 판정, 'k번째 작은 값', '정렬된 목록으로 내보내기' 가 전부 이 순회 한 번으로 풀립니다.\n한 노드씩 흘려보낼 수 있으므로, 이 형태를 제너레이터로 감싸면 <b>필요한 만큼만</b> 꺼내 쓰는 지연 순회가 됩니다. 트리가 아주 클 때 전체 배열을 만들지 않아도 되는 이유입니다." },

{ track: "algo", k: "층별 순회 · levelOrder", cat: "internals",
  q: "트리를 <b>층별로</b> 묶은 이차원 배열로 돌려주세요. 예를 들어 뿌리만 있으면 <code>[[값]]</code> 입니다.",
  src: "function levelOrder(root) {\n  // TODO: 한 칸씩이 아니라 '한 층씩' 처리하세요\n  return [];\n}",
  sol: "function levelOrder(root) {\n  if (!root) return [];\n  const out = [];\n  let cur = [root];\n  while (cur.length) {\n    out.push(cur.map((x) => x.v));\n    const next = [];\n    cur.forEach((x) => {\n      if (x.l) next.push(x.l);\n      if (x.r) next.push(x.r);\n    });\n    cur = next;\n  }\n  return out;\n}",
  tests: [["levelOrder({v:1,l:{v:2,l:null,r:null},r:{v:3,l:null,r:null}})", "[[1],[2,3]]"],
    ["levelOrder({v:1,l:{v:2,l:{v:4,l:null,r:null},r:null},r:{v:3,l:null,r:null}})", "[[1],[2,3],[4]]"],
    ["levelOrder({v:1,l:null,r:{v:2,l:null,r:{v:3,l:null,r:null}}})", "[[1],[2],[3]]"],
    ["levelOrder({v:5,l:{v:3,l:null,r:null},r:null})", "[[5],[3]]"]],
  edge: [["levelOrder(null)", "[]"], ["levelOrder({v:9,l:null,r:null})", "[[9]]"]],
  ex: "층을 나누려면 <b>지금 층이 어디서 끝나는지</b>를 알아야 합니다. 큐 하나로 풀 때는 반복 시작마다 <code>size = queue.length</code> 를 찍어 두고 그만큼만 꺼내는데, 여기서는 아예 <b>현재 층 배열과 다음 층 배열을 따로</b> 두어 그 경계를 눈에 보이게 했습니다.\n<code>cur</code> 를 순회하는 도중에 <code>cur</code> 에 넣지 않는 것이 요점입니다. 한 배열에 계속 밀어 넣으면서 인덱스로 훑으면 층 경계가 사라져, 결과가 층 구분 없는 한 줄로 뭉갭니다.\n층별 순회는 <b>가장 가까운 것부터</b> 본다는 뜻이라 최단 거리와 같은 성질을 씁니다. 조직도에서 n촌 이내 찾기, 화면 트리에서 보이는 깊이까지만 렌더링하기, 카테고리 2단계까지만 펼치기가 모두 이 형태입니다.\n오른쪽에서 본 실루엣이 필요하면 각 층의 마지막 값만, 지그재그 순회가 필요하면 홀수 층만 뒤집으면 됩니다. <b>층을 손에 쥐고 있으면</b> 변형이 전부 한 줄입니다." },

{ track: "algo", k: "이진 탐색 트리 판정 · isValidBST", cat: "debug",
  q: "이진 트리가 올바른 <b>이진 탐색 트리</b>인지 판정해 주세요. 왼쪽 부분 트리의 <b>모든</b> 값이 자기보다 작고, 오른쪽의 모든 값이 커야 합니다. 같은 값은 없습니다.",
  src: "function isValidBST(root) {\n  // TODO: 부모 하나가 아니라 '허용 범위'를 물려주세요\n  if (!root) return true;\n  if (root.l && root.l.v >= root.v) return false;\n  if (root.r && root.r.v <= root.v) return false;\n  return isValidBST(root.l) && isValidBST(root.r);\n}",
  sol: "function isValidBST(root) {\n  const go = (node, lo, hi) => {\n    if (!node) return true;\n    if (lo !== null && node.v <= lo) return false;\n    if (hi !== null && node.v >= hi) return false;\n    return go(node.l, lo, node.v) && go(node.r, node.v, hi);\n  };\n  return go(root, null, null);\n}",
  tests: [["isValidBST({v:2,l:{v:1,l:null,r:null},r:{v:3,l:null,r:null}})", "true"],
    ["isValidBST({v:5,l:{v:1,l:null,r:{v:6,l:null,r:null}},r:{v:7,l:null,r:null}})", "false"],
    ["isValidBST({v:10,l:{v:5,l:{v:2,l:null,r:null},r:{v:7,l:null,r:null}},r:{v:15,l:null,r:null}})", "true"],
    ["isValidBST({v:10,l:{v:5,l:null,r:{v:12,l:null,r:null}},r:{v:15,l:null,r:null}})", "false"]],
  edge: [["isValidBST(null)", "true"], ["isValidBST({v:1,l:null,r:null})", "true"]],
  ex: "시작 코드는 <b>부모와 자식만</b> 비교합니다. 그래서 두 번째 테스트처럼 <code>5</code> 의 왼쪽 아래에 <code>6</code> 이 숨어 있는 트리를 통과시켜 버립니다. 국소적으로는 모든 부모-자식 관계가 옳지만, 트리 전체로 보면 BST 가 아닙니다.\n올바른 판정은 각 노드에 <b>허용 범위</b>를 물려주는 것입니다. 왼쪽으로 내려갈 때는 상한이 자기 값으로 좁아지고, 오른쪽으로 갈 때는 하한이 자기 값이 됩니다. 범위는 내려갈수록 <b>좁아지기만</b> 하고, 그 범위를 벗어나는 값을 만나면 거짓입니다.\n같은 문제를 <b>중위 순회가 오름차순인가</b>로도 풉니다. 앞 값 하나만 들고 훑으면 되므로 코드가 더 짧지만, 어디서 깨졌는지를 알려 주기에는 범위 방식이 낫습니다.\n경계에 <code>Infinity</code> 대신 <code>null</code> 을 쓴 이유는 '제한 없음' 과 '무한대라는 값' 을 구분하기 위해서입니다. 실무에서도 <b>없음을 큰 수로 흉내내는</b> 습관은 언젠가 그 큰 수가 실제 데이터로 들어오는 날 사고를 냅니다." },

{ track: "algo", k: "BST 의 최소 공통 조상 · lcaBST", cat: "internals",
  q: "이진 탐색 트리에서 두 값 <code>a</code>, <code>b</code> 의 <b>최소 공통 조상</b> 값을 돌려주세요. 두 값은 트리에 반드시 있습니다.",
  src: "function lcaBST(root, a, b) {\n  // TODO: 두 값이 같은 쪽에 있는 동안에만 그쪽으로 내려가세요\n  return root ? root.v : -1;\n}",
  sol: "function lcaBST(root, a, b) {\n  let node = root;\n  while (node) {\n    if (a < node.v && b < node.v) node = node.l;\n    else if (a > node.v && b > node.v) node = node.r;\n    else return node.v;\n  }\n  return -1;\n}",
  tests: [["lcaBST({v:6,l:{v:2,l:{v:0,l:null,r:null},r:{v:4,l:null,r:null}},r:{v:8,l:null,r:null}},0,4)", "2"],
    ["lcaBST({v:6,l:{v:2,l:{v:0,l:null,r:null},r:{v:4,l:null,r:null}},r:{v:8,l:null,r:null}},2,8)", "6"],
    ["lcaBST({v:6,l:{v:2,l:{v:0,l:null,r:null},r:{v:4,l:null,r:null}},r:{v:8,l:null,r:null}},0,2)", "2"],
    ["lcaBST({v:10,l:{v:5,l:null,r:null},r:{v:15,l:{v:12,l:null,r:null},r:null}},12,15)", "15"]],
  edge: [["lcaBST({v:1,l:null,r:null},1,1)", "1"], ["lcaBST(null,1,2)", "-1"]],
  ex: "일반 트리에서는 두 노드까지의 경로를 각각 구해 비교해야 하지만, BST 에서는 <b>값만 비교하면</b> 어느 쪽으로 갈지 알 수 있습니다. 그래서 재귀도 방문 표시도 없이 <b>한 줄기로 내려가는 반복</b>이면 끝나고, 시간은 트리 높이에 비례합니다.\n멈추는 조건이 곧 정답입니다. 두 값이 <b>갈라지는 첫 노드</b>, 또는 <b>둘 중 하나와 같은 노드</b>가 최소 공통 조상입니다. 세 번째 테스트가 이 두 번째 경우입니다 — 조상이 자기 자신일 수 있다는 것을 잊으면 한 칸 더 내려가 틀립니다.\n조건을 <code>&lt;=</code> 로 쓰면 <code>a</code> 가 현재 노드와 같을 때 그냥 지나쳐 버립니다. <b>부등호에 등호를 넣을지</b>는 '자기 자신도 조상인가' 라는 정의에서 나옵니다 — 코드보다 정의를 먼저 정해야 하는 자리입니다.\n이 구조는 실무에서 <b>카테고리 트리의 공통 상위 분류</b>, 조직도의 공통 상급자, 파일 경로의 공통 디렉터리를 찾는 데 그대로 쓰입니다. 값에 순서가 있다는 성질 하나가 탐색을 이만큼 싸게 만듭니다." },

/* ───────────── 경로와 힙 ───────────── */
{ track: "algo", k: "뿌리에서 잎까지의 합 · hasPathSum", cat: "internals",
  q: "뿌리에서 <b>잎</b>까지 내려가는 어떤 경로의 값 합이 <code>target</code> 과 같은지 판정해 주세요. 중간에서 끝나는 경로는 세지 않습니다.",
  src: "function hasPathSum(root, target) {\n  // TODO: 잎에 도착했을 때만 판정해야 합니다\n  return false;\n}",
  sol: "function hasPathSum(root, target) {\n  if (!root) return false;\n  if (!root.l && !root.r) return root.v === target;\n  const rest = target - root.v;\n  return hasPathSum(root.l, rest) || hasPathSum(root.r, rest);\n}",
  tests: [["hasPathSum({v:1,l:{v:2,l:null,r:null},r:{v:3,l:null,r:null}},3)", "true"],
    ["hasPathSum({v:1,l:{v:2,l:null,r:null},r:{v:3,l:null,r:null}},1)", "false"],
    ["hasPathSum({v:5,l:{v:4,l:{v:11,l:null,r:null},r:null},r:{v:8,l:null,r:null}},20)", "true"],
    ["hasPathSum({v:5,l:{v:4,l:{v:11,l:null,r:null},r:null},r:{v:8,l:null,r:null}},9)", "false"]],
  edge: [["hasPathSum(null,0)", "false"], ["hasPathSum({v:0,l:null,r:null},0)", "true"]],
  ex: "이 문제의 함정은 <b>잎의 정의</b>입니다. <code>null</code> 에 닿았을 때 <code>target === 0</code> 인지 보면, 자식이 하나뿐인 노드에서 <b>없는 쪽</b>도 경로로 세어 두 번째 테스트를 통과시켜 버립니다. 잎은 <b>두 자식이 모두 없는 노드</b>이고, 판정은 거기서만 합니다.\n남은 합을 인자로 빼 가며 내려가는 방식이 지나온 값을 배열로 들고 다니는 것보다 낫습니다. 메모리가 상수이고, <b>지금 필요한 정보만</b> 전달한다는 점에서 의도도 분명합니다.\n<code>||</code> 의 <b>단축 평가</b> 덕분에 왼쪽에서 찾으면 오른쪽은 아예 보지 않습니다. 존재 여부만 묻는 문제에서는 이 한 글자가 곧 가지치기입니다. 반대로 <b>모든</b> 경로를 모아야 한다면 두 결과를 이어 붙여야 하고, 그때는 지나온 경로 배열이 필요해집니다.\n값에 음수가 섞이면 '합이 이미 <code>target</code> 을 넘었으니 그만두자' 같은 가지치기가 무너집니다. <b>가지치기의 전제</b>를 말로 못 하면 붙이지 않는 편이 안전합니다." },

{ track: "algo", k: "조상보다 큰 노드 세기 · goodNodes", cat: "internals",
  q: "뿌리에서 그 노드까지 오는 길에 있는 <b>모든 조상보다 작지 않은</b> 노드의 개수를 세어 주세요. 뿌리는 항상 포함됩니다.",
  src: "function goodNodes(root) {\n  // TODO: 내려가면서 '지금까지 본 최댓값'을 물려주세요\n  return 0;\n}",
  sol: "function goodNodes(root) {\n  const go = (node, best) => {\n    if (!node) return 0;\n    const hit = node.v >= best ? 1 : 0;\n    const next = Math.max(best, node.v);\n    return hit + go(node.l, next) + go(node.r, next);\n  };\n  return go(root, -Infinity);\n}",
  tests: [["goodNodes({v:3,l:{v:1,l:{v:3,l:null,r:null},r:null},r:{v:4,l:{v:1,l:null,r:null},r:{v:5,l:null,r:null}}})", "4"],
    ["goodNodes({v:3,l:{v:3,l:{v:4,l:null,r:null},r:{v:2,l:null,r:null}},r:null})", "3"],
    ["goodNodes({v:1,l:null,r:null})", "1"],
    ["goodNodes({v:5,l:{v:4,l:{v:3,l:null,r:null},r:null},r:null})", "1"]],
  edge: [["goodNodes(null)", "0"], ["goodNodes({v:2,l:{v:2,l:null,r:null},r:{v:2,l:null,r:null}})", "3"]],
  ex: "내려가는 길에 <b>지금까지의 최댓값</b>을 인자로 물려주는 것이 전부입니다. 트리 재귀에서 '위에서 아래로 흐르는 정보' 를 다루는 가장 기본적인 형태이고, 앞의 BST 판정에서 범위를 물려준 것과 같은 손놀림입니다.\n바깥 변수에 최댓값을 적어 두면 <b>형제 가지끼리 오염</b>됩니다. 왼쪽 가지에서 커진 값이 오른쪽 가지의 판정에 끼어들기 때문입니다. 가지마다 독립적인 값이 필요하면 <b>인자로 넘겨야</b> 한다는 원칙이 여기서 눈에 보입니다.\n비교를 <code>&gt;=</code> 로 둔 것은 문제의 정의가 '작지 않다' 이기 때문입니다. 마지막 엣지 케이스처럼 값이 모두 같은 트리에서 <code>&gt;</code> 와 <code>&gt;=</code> 는 답이 <code>1</code> 과 <code>3</code> 으로 갈립니다 — <b>동점 규칙</b>을 먼저 못 박아야 하는 이유입니다.\n초기값 <code>-Infinity</code> 는 '아직 아무 조상도 없다' 를 뜻합니다. <code>0</code> 으로 두면 음수 값을 가진 뿌리가 자기 자신에게 밀려 세어지지 않습니다. <b>초기값은 데이터의 범위를 보고</b> 정합니다." },

{ track: "algo", k: "배열 힙으로 정렬 · heapSort", cat: "internals",
  q: "배열을 <b>힙 정렬</b>로 오름차순 정렬해 주세요. <code>sort</code> 를 쓰지 말고, 배열을 최대 힙으로 만든 뒤 꼭대기를 뒤로 보내는 방식으로 직접 구현합니다. 원본은 그대로 두세요.",
  src: "function heapSort(xs) {\n  // TODO: 아래에서부터 내려보내기(siftDown)로 힙을 만드세요\n  return xs.slice();\n}",
  sol: "function heapSort(xs) {\n  const a = xs.slice();\n  const n = a.length;\n  const down = (start, size) => {\n    let i = start;\n    for (;;) {\n      const left = 2 * i + 1;\n      let big = i;\n      if (left < size && a[left] > a[big]) big = left;\n      if (left + 1 < size && a[left + 1] > a[big]) big = left + 1;\n      if (big === i) return;\n      [a[i], a[big]] = [a[big], a[i]];\n      i = big;\n    }\n  };\n  for (let i = (n >> 1) - 1; i >= 0; i--) down(i, n);\n  for (let end = n - 1; end > 0; end--) {\n    [a[0], a[end]] = [a[end], a[0]];\n    down(0, end);\n  }\n  return a;\n}",
  tests: [["heapSort([3,1,2])", "[1,2,3]"],
    ["heapSort([5,4,3,2,1])", "[1,2,3,4,5]"],
    ["heapSort([10,9,10,1,1])", "[1,1,9,10,10]"],
    ["heapSort([-3,0,-7,2])", "[-7,-3,0,2]"]],
  edge: [["heapSort([])", "[]"], ["heapSort([1])", "[1]"]],
  ex: "힙은 <b>배열 하나로 표현되는 트리</b>입니다. <code>i</code> 번 노드의 자식은 <code>2i+1</code>, <code>2i+2</code> 이고 부모는 <code>(i-1)/2</code> 입니다. 포인터도 노드 객체도 없이 인덱스 계산만으로 트리를 다루므로 캐시에도 유리합니다.\n힙을 만드는 방법이 두 가지인데, 여기서는 <b>중간부터 거꾸로 내려보내기</b>를 씁니다. 잎은 이미 힙이므로 <code>(n/2)-1</code> 부터 시작하면 되고, 이 방식은 <b>O(n)</b> 입니다. 하나씩 넣으며 올려보내면 O(n log n) 이라 조금 더 비쌉니다.\n정렬 단계는 '꼭대기를 맨 뒤와 바꾸고, 힙 크기를 하나 줄여 다시 내려보내기' 의 반복입니다. 최대 힙을 쓰면 큰 값이 뒤로 쌓여 <b>오름차순</b>이 되는데, 최소 힙으로 짜면 내림차순이 나옵니다 — 방향을 헷갈리기 쉬운 자리입니다.\n힙 정렬은 <b>추가 메모리가 상수</b>이고 최악에도 O(n log n) 입니다. 다만 안정 정렬이 아니고 실제 속도는 퀵 정렬보다 느린 편이라, 현실에서는 정렬보다 <b>우선순위 큐</b>로 더 많이 쓰입니다. 그래도 한 번 짜 보면 우선순위 큐의 비용이 어디서 나오는지가 손에 잡힙니다." },

{ track: "algo", k: "흐르는 값의 k번째 큰 수 · kthLargestStream", cat: "internals",
  q: "값이 하나씩 들어올 때마다 <b>지금까지 중 k번째로 큰 값</b>을 기록한 배열을 돌려주세요. 아직 값이 <code>k</code> 개가 안 되면 그 자리는 <code>null</code> 입니다. 크기가 <code>k</code> 인 최소 힙을 직접 만드세요.",
  src: "function kthLargestStream(k, xs) {\n  // TODO: 힙에 k 개만 남기면 꼭대기가 곧 답입니다\n  return xs.map(() => null);\n}",
  sol: "function kthLargestStream(k, xs) {\n  const heap = [];\n  const swap = (i, j) => { [heap[i], heap[j]] = [heap[j], heap[i]]; };\n  const down = () => {\n    let i = 0;\n    for (;;) {\n      const left = 2 * i + 1;\n      let small = i;\n      if (left < heap.length && heap[left] < heap[small]) small = left;\n      if (left + 1 < heap.length && heap[left + 1] < heap[small]) small = left + 1;\n      if (small === i) return;\n      swap(i, small);\n      i = small;\n    }\n  };\n  return xs.map((x) => {\n    heap.push(x);\n    let i = heap.length - 1;\n    while (i > 0 && heap[(i - 1) >> 1] > heap[i]) { swap((i - 1) >> 1, i); i = (i - 1) >> 1; }\n    if (heap.length > k) { heap[0] = heap.pop(); down(); }\n    return heap.length === k ? heap[0] : null;\n  });\n}",
  tests: [["kthLargestStream(3,[4,5,8,2])", "[null,null,4,4]"],
    ["kthLargestStream(1,[3,1,5])", "[3,3,5]"],
    ["kthLargestStream(2,[7,7,7])", "[null,7,7]"],
    ["kthLargestStream(3,[1,2,3,4,5])", "[null,null,1,2,3]"]],
  edge: [["kthLargestStream(2,[])", "[]"], ["kthLargestStream(5,[1,2])", "[null,null]"]],
  ex: "'가장 큰 k 개' 를 지키는 데 <b>최소 힙</b>을 쓴다는 것이 처음에는 거꾸로 보입니다. 하지만 꼭대기가 <b>현재 k등</b>이므로, 새 값이 그보다 작으면 볼 것도 없이 버리고 크면 꼭대기를 밀어내면 됩니다 — 답을 바로 읽을 수 있는 자리에 두는 것이 요령입니다.\n메모리가 <code>k</code> 에만 비례한다는 점이 이 구조의 진짜 값어치입니다. 값이 1억 개 흘러도 힙은 <code>k</code> 칸이라, 전부 모아 정렬하는 방법으로는 불가능한 <b>스트림</b>에서도 동작합니다. 실시간 랭킹, 상위 요청 URL, 느린 쿼리 상위 10건이 이 형태입니다.\n힙을 직접 짤 때 실수가 몰리는 곳은 <b>마지막 원소 처리</b>입니다. 꼭대기를 뺄 때 <code>heap[0] = heap.pop()</code> 으로 마지막을 끌어올린 뒤 내려보내야 하는데, 힙에 원소가 하나뿐이면 <code>pop</code> 이 그 원소 자신이라 순서가 어긋나기 쉽습니다. 여기서는 <code>k</code> 를 넘겼을 때만 실행하므로 안전합니다.\n<code>k</code> 개가 차기 전을 <code>null</code> 로 둔 것은 <b>없음을 값으로 흉내내지 않기</b> 위해서입니다. <code>0</code> 이나 <code>-1</code> 로 두면 실제 데이터에 그 값이 등장하는 순간 구분이 불가능해집니다." },

];
