/* 해시 · 문자열 — 실행형이 각각 18·71문항뿐이던 유형.
   한 번 훑어 끝내기, 키를 설계하기, 문자열을 직접 훑고 직접 만들기. */
module.exports = [

/* ───────────── 해시로 한 번에 끝내기 ───────────── */
{ track: "algo", k: "합이 target 인 두 자리 · twoSum", cat: "internals",
  q: "배열에서 두 값의 합이 <code>target</code> 이 되는 <b>두 인덱스</b>를 작은 순서로 돌려주세요. 없으면 빈 배열입니다. 답은 많아야 하나입니다.",
  src: "function twoSum(xs, target) {\n  // TODO: 이중 반복 대신, 지나온 값을 기억해 두세요\n  return [];\n}",
  sol: "function twoSum(xs, target) {\n  const seen = new Map();\n  for (let i = 0; i < xs.length; i++) {\n    const need = target - xs[i];\n    if (seen.has(need)) return [seen.get(need), i];\n    seen.set(xs[i], i);\n  }\n  return [];\n}",
  tests: [["twoSum([2,7,11,15],9)", "[0,1]"],
    ["twoSum([3,2,4],6)", "[1,2]"],
    ["twoSum([3,3],6)", "[0,1]"],
    ["twoSum([1,2,3],7)", "[]"]],
  edge: [["twoSum([],1)", "[]"], ["twoSum([5],5)", "[]"]],
  ex: "이중 반복은 '지금 값과 짝이 될 값' 을 <b>매번 다시 찾습니다</b>. 해시는 그 찾기를 O(1) 로 바꿔 전체를 O(n) 으로 만듭니다. 해시가 하는 일은 언제나 이 하나 — <b>이미 본 것을 다시 찾지 않게</b> 하는 것입니다.\n순서가 중요합니다. <b>먼저 찾고 나중에 넣어야</b> 합니다. 넣고 나서 찾으면 <code>target</code> 이 자기 값의 두 배일 때 자기 자신과 짝을 지어 <code>[0,0]</code> 같은 답이 나옵니다. 세 번째 테스트가 그것을 잡습니다 — 같은 값이 두 개 있어도 <b>서로 다른 자리</b>여야 합니다.\n값이 아니라 <b>인덱스</b>를 담는 것도 요점입니다. 같은 값이 여러 번 나오면 나중 것이 앞 것을 덮어쓰는데, 답이 하나뿐이라는 전제 아래에서는 문제가 되지 않습니다. 전제가 깨지면 값마다 인덱스 목록을 담아야 합니다.\n배열이 정렬되어 있다면 해시 없이 <b>투 포인터</b>로 추가 메모리 없이 풀 수 있습니다. 정렬이 없을 때 해시, 있을 때 투 포인터 — 이 갈림길이 '두 수의 합' 계열 문제의 첫 판단입니다." },

{ track: "algo", k: "처음 한 번만 나온 글자 · firstUnique", cat: "internals",
  q: "문자열에서 <b>딱 한 번만 나오는 첫 글자</b>의 인덱스를 돌려주세요. 그런 글자가 없으면 <code>-1</code> 입니다.",
  src: "function firstUnique(s) {\n  // TODO: 세는 것과 찾는 것을 두 번의 훑기로 나누세요\n  return -1;\n}",
  sol: "function firstUnique(s) {\n  const count = new Map();\n  for (const ch of s) count.set(ch, (count.get(ch) || 0) + 1);\n  for (let i = 0; i < s.length; i++) {\n    if (count.get(s[i]) === 1) return i;\n  }\n  return -1;\n}",
  tests: [['firstUnique("leetcode")', "0"],
    ['firstUnique("loveleetcode")', "2"],
    ['firstUnique("aabb")', "-1"],
    ['firstUnique("abcabd")', "2"]],
  edge: [['firstUnique("")', "-1"], ['firstUnique("z")', "0"]],
  ex: "한 번 훑으면서 동시에 판정하려 하면 막힙니다. 지금 글자가 뒤에 또 나오는지를 <b>아직 모르기</b> 때문입니다. 그래서 <b>세는 훑기</b>와 <b>찾는 훑기</b>를 나눕니다 — 두 번 훑어도 O(n) 이라 손해가 없습니다.\n'한 번에 다 하려다 복잡해지면 단계를 나눈다' 는 것은 실무 코드에서 더 자주 쓰는 판단입니다. 두 번 훑는 코드가 한 번 훑는 코드보다 <b>읽기 쉽고 고치기 쉬우면</b> 그쪽이 더 나은 코드입니다.\n두 번째 훑기를 <b>맵이 아니라 원본 문자열</b> 위에서 도는 것이 중요합니다. 맵을 돌면 '처음' 이라는 조건이 삽입 순서에 기대게 되는데, 자바스크립트 <code>Map</code> 은 삽입 순서를 지키지만 일반 객체나 다른 언어에서는 보장되지 않아 옮길 때 깨집니다.\n<code>count.get(ch) || 0</code> 은 '없으면 0' 을 짧게 쓴 것입니다. 다만 값이 <code>0</code> 일 수 있는 맵에서는 <code>||</code> 가 위험하고, 그때는 <code>??</code> 나 <code>has</code> 검사를 씁니다." },

{ track: "algo", k: "차이가 d 인 쌍 세기 · countPairsWithDiff", cat: "internals",
  q: "배열에서 두 값의 차가 <code>d</code>(0 이상)인 <b>인덱스 쌍</b>의 개수를 세어 주세요. 같은 쌍을 두 번 세면 안 됩니다.",
  src: "function countPairsWithDiff(xs, d) {\n  // TODO: 지나온 값의 개수를 세어 두고, 짝이 몇 개인지 더하세요\n  return 0;\n}",
  sol: "function countPairsWithDiff(xs, d) {\n  const count = new Map();\n  let found = 0;\n  xs.forEach((x) => {\n    found += count.get(x - d) || 0;\n    if (d !== 0) found += count.get(x + d) || 0;\n    count.set(x, (count.get(x) || 0) + 1);\n  });\n  return found;\n}",
  tests: [["countPairsWithDiff([1,5,3,4,2],2)", "3"],
    ["countPairsWithDiff([1,1,1],0)", "3"],
    ["countPairsWithDiff([1,2,3],5)", "0"],
    ["countPairsWithDiff([3,1,4,1,5],2)", "3"]],
  edge: [["countPairsWithDiff([],3)", "0"], ["countPairsWithDiff([2,2],0)", "1"]],
  ex: "'쌍을 센다' 는 문제에서 중복 계산을 막는 가장 깔끔한 방법은 <b>지나온 것만 본다</b>는 규칙입니다. 새 값을 넣기 <b>전에</b> 짝을 세면, 모든 쌍이 <b>나중 원소를 처리할 때 정확히 한 번</b> 세어집니다.\n<code>d === 0</code> 을 따로 막은 이유가 여기 있습니다. 차이가 0이면 <code>x - d</code> 와 <code>x + d</code> 가 같은 값이라, 두 번 더하면 모든 쌍이 두 배로 세어집니다. <b>대칭인 경우를 특수 처리</b>하는 것은 쌍 세기 문제의 단골 함정입니다.\n존재 여부만 묻는다면 <code>Set</code> 이면 되지만, <b>개수</b>를 물으므로 값마다 몇 개인지를 세는 <code>Map</code> 이 필요합니다. 두 번째 테스트처럼 같은 값이 세 개면 쌍은 3개이고, 이것은 개수를 세지 않으면 나오지 않는 답입니다.\n정렬한 뒤 투 포인터로도 O(n log n) 에 풀립니다. 하지만 해시 방식은 정렬이 필요 없고 <b>값이 흘러 들어오는 상황</b>에도 그대로 쓸 수 있어, 로그 스트림에서 특정 간격의 이벤트 쌍을 세는 일 같은 데에 맞습니다." },

{ track: "algo", k: "가장 긴 연속 수열 · longestConsecutive", cat: "internals",
  q: "정렬되지 않은 배열에서 <b>연속된 정수</b>가 가장 길게 이어지는 길이를 돌려주세요. 정렬하지 말고 O(n) 으로 푸세요.",
  src: "function longestConsecutive(xs) {\n  // TODO: 수열의 '시작점'에서만 세면 전체가 O(n) 입니다\n  return xs.length;\n}",
  sol: "function longestConsecutive(xs) {\n  const pool = new Set(xs);\n  let best = 0;\n  pool.forEach((x) => {\n    if (pool.has(x - 1)) return;\n    let len = 1;\n    while (pool.has(x + len)) len++;\n    if (len > best) best = len;\n  });\n  return best;\n}",
  tests: [["longestConsecutive([100,4,200,1,3,2])", "4"],
    ["longestConsecutive([0,3,7,2,5,8,4,6,0,1])", "9"],
    ["longestConsecutive([1,2,0,1])", "3"],
    ["longestConsecutive([9])", "1"]],
  edge: [["longestConsecutive([])", "0"], ["longestConsecutive([5,5,5])", "1"]],
  ex: "겉보기에는 O(n²) 처럼 보이는데 실제로는 O(n) 입니다. 근거는 <code>if (pool.has(x - 1)) return;</code> 한 줄입니다 — <b>수열의 시작점에서만</b> 안쪽 반복이 돌기 때문에, 각 값은 평생 한 번만 세어집니다.\n이 줄을 빼면 답은 여전히 맞지만 시간이 무너집니다. <b>맞는 답과 빠른 답이 한 줄 차이</b>인 대표적인 예이고, 그 한 줄을 왜 붙였는지 설명할 수 있어야 면접에서도 통과합니다.\n<code>Set</code> 으로 감싸는 순간 <b>중복이 사라진다</b>는 점도 답에 관여합니다. 세 번째 테스트에서 <code>1</code> 이 두 번 나오지만 길이는 <code>3</code> 입니다. 중복을 지우고 싶지 않은 문제였다면 <code>Set</code> 은 잘못된 선택이 됩니다.\n정렬하면 O(n log n) 에 훨씬 쉽게 풀립니다. 'O(n) 으로' 라는 제약이 없다면 정렬이 <b>더 나은 코드</b>일 수 있습니다 — 제약을 확인하지 않고 어려운 쪽을 고르는 것도 실수입니다." },

/* ───────────── 키를 설계한다 ───────────── */
{ track: "algo", k: "애너그램 묶기 · groupAnagrams", cat: "internals",
  q: "단어들을 <b>애너그램끼리</b> 묶어 이차원 배열로 돌려주세요. 묶음의 순서와 묶음 안의 순서는 모두 <b>처음 나온 순서</b>를 따릅니다.",
  src: "function groupAnagrams(words) {\n  // TODO: 같은 묶음이면 같아지는 '키'를 만들어야 합니다\n  return words.map((w) => [w]);\n}",
  sol: "function groupAnagrams(words) {\n  const bucket = new Map();\n  words.forEach((w) => {\n    const key = w.split(\"\").sort().join(\"\");\n    if (!bucket.has(key)) bucket.set(key, []);\n    bucket.get(key).push(w);\n  });\n  return [...bucket.values()];\n}",
  tests: [['groupAnagrams(["eat","tea","tan","ate","nat","bat"])', '[["eat","tea","ate"],["tan","nat"],["bat"]]'],
    ['groupAnagrams(["ab","ba","abc"])', '[["ab","ba"],["abc"]]'],
    ['groupAnagrams(["listen","silent","enlist","google"])', '[["listen","silent","enlist"],["google"]]'],
    ['groupAnagrams(["a"])', '[["a"]]']],
  edge: [["groupAnagrams([])", "[]"], ['groupAnagrams(["",""])', '[["",""]]']],
  ex: "해시로 묶는 문제의 전부는 <b>키를 어떻게 만드느냐</b>입니다. 애너그램은 '글자 구성이 같다' 는 뜻이므로, <b>정렬한 글자열</b>이 그대로 같음의 정의가 됩니다. 키가 정해지면 나머지는 기계적입니다.\n글자가 알파벳뿐이라면 <b>26칸 개수 배열</b>을 키로 써서 정렬 비용을 없앨 수 있습니다. 단어 길이가 <code>L</code> 일 때 정렬은 O(L log L), 개수 세기는 O(L) 입니다. 다만 배열은 객체라 그대로는 키가 못 되어 문자열로 이어 붙여야 하고, <b>구분자 없이 이으면</b> <code>[1,11]</code> 과 <code>[11,1]</code> 이 같은 키가 되는 사고가 납니다.\n출력 순서를 <b>처음 나온 순서</b>로 못 박은 것은 테스트를 흔들리지 않게 하기 위해서입니다. 자바스크립트 <code>Map</code> 이 삽입 순서를 지키므로 별도 정렬 없이 성립하는데, 일반 객체나 다른 언어로 옮기면 이 전제가 깨질 수 있습니다.\n같은 골격이 실무의 <b>중복 파일 찾기</b>(내용 해시가 키), <b>동일 요청 묶기</b>(정규화한 URL 이 키), <b>사용자 병합</b>(정규화한 이메일이 키)에 그대로 쓰입니다. 어려운 것은 언제나 키의 정의이지 코드가 아닙니다." },

{ track: "algo", k: "글자 대응 관계 판정 · isIsomorphic", cat: "debug",
  q: "두 문자열이 <b>글자를 일대일로 바꿔</b> 서로 만들 수 있는지 판정해 주세요. 서로 다른 글자가 같은 글자로 가면 안 됩니다.",
  src: "function isIsomorphic(a, b) {\n  // TODO: 한쪽 방향만 검사하면 두 글자가 한 글자로 뭉칩니다\n  if (a.length !== b.length) return false;\n  const fwd = new Map();\n  for (let i = 0; i < a.length; i++) {\n    if (fwd.has(a[i]) && fwd.get(a[i]) !== b[i]) return false;\n    fwd.set(a[i], b[i]);\n  }\n  return true;\n}",
  sol: "function isIsomorphic(a, b) {\n  if (a.length !== b.length) return false;\n  const fwd = new Map();\n  const back = new Map();\n  for (let i = 0; i < a.length; i++) {\n    if (fwd.has(a[i]) && fwd.get(a[i]) !== b[i]) return false;\n    if (back.has(b[i]) && back.get(b[i]) !== a[i]) return false;\n    fwd.set(a[i], b[i]);\n    back.set(b[i], a[i]);\n  }\n  return true;\n}",
  tests: [['isIsomorphic("egg","add")', "true"],
    ['isIsomorphic("foo","bar")', "false"],
    ['isIsomorphic("paper","title")', "true"],
    ['isIsomorphic("badc","baba")', "false"]],
  edge: [['isIsomorphic("","")', "true"], ['isIsomorphic("ab","a")', "false"]],
  ex: "시작 코드는 <b>한 방향만</b> 확인합니다. 그래서 네 번째 테스트에서 <code>d</code> 와 <code>c</code> 가 모두 <code>b</code>·<code>a</code> 로 가는 것을 막지 못합니다 — 각 글자마다 목적지는 하나씩이라 앞쪽 검사는 전부 통과하지만, 되돌아올 수 없으니 <b>일대일이 아닙니다</b>.\n일대일 대응은 <b>양방향 유일성</b>입니다. 그래서 맵을 두 개 두거나, 마지막에 <code>new Set(b).size === new Set(a).size</code> 로 확인합니다. 어느 쪽이든 '반대 방향도 막았는가' 라는 질문에 답할 수 있어야 합니다.\n길이 검사를 <b>맨 앞에</b> 두는 것도 중요합니다. 없으면 짧은 쪽만 훑고 참을 돌려주는데, 이런 종류의 버그는 짧은 입력 테스트에서는 거의 드러나지 않습니다.\n같은 검사가 실무의 <b>필드 매핑</b>에서 그대로 필요합니다. 외부 스키마의 두 컬럼을 내부의 한 컬럼으로 보내면 되돌릴 수 없어, 되돌리는 마이그레이션을 짤 때 데이터가 뭉개집니다. 매핑을 만들 때는 늘 <b>역방향이 성립하는지</b>를 함께 봅니다." },

{ track: "algo", k: "금지어를 뺀 최빈 단어 · mostCommonWord", cat: "internals",
  q: "문장에서 <b>금지어를 뺀</b> 가장 많이 나온 단어를 소문자로 돌려주세요. 알파벳이 아닌 문자는 모두 구분자이고, 동점이면 <b>먼저 그 횟수에 도달한</b> 단어입니다. 없으면 빈 문자열입니다.",
  src: "function mostCommonWord(text, banned) {\n  // TODO: 소문자로 낮추고, 알파벳이 아닌 것으로 쪼개세요\n  return text;\n}",
  sol: "function mostCommonWord(text, banned) {\n  const stop = new Set(banned);\n  const count = new Map();\n  let best = \"\";\n  text.toLowerCase().split(/[^a-z]+/).forEach((w) => {\n    if (!w || stop.has(w)) return;\n    count.set(w, (count.get(w) || 0) + 1);\n    if (count.get(w) > (count.get(best) || 0)) best = w;\n  });\n  return best;\n}",
  tests: [['mostCommonWord("Bob hit a ball, the hit BALL flew", ["hit"])', '"ball"'],
    ['mostCommonWord("a a b", [])', '"a"'],
    ['mostCommonWord("x y z", [])', '"x"'],
    ['mostCommonWord("Hello, hello world", ["world"])', '"hello"']],
  edge: [['mostCommonWord("", [])', '""'], ['mostCommonWord("ban ban", ["ban"])', '""']],
  ex: "문자열 집계 문제는 <b>정규화</b>부터입니다. 대소문자를 낮추고 구두점을 떼어 내지 않으면 <code>BALL</code>·<code>ball</code>·<code>ball,</code> 이 서로 다른 단어가 되어 답이 통째로 달라집니다. 세는 코드보다 <b>무엇을 같은 것으로 볼지</b>가 먼저입니다.\n<code>split(/[^a-z]+/)</code> 은 앞뒤에 <b>빈 문자열</b>을 만들 수 있습니다. 문장이 구두점으로 시작하거나 끝날 때가 그렇습니다. <code>if (!w)</code> 한 줄을 빠뜨리면 빈 문자열이 최빈 단어로 뽑히는 황당한 답이 나옵니다.\n동점 규칙을 <b>먼저 도달한 쪽</b>으로 정하고, 갱신 조건을 <code>&gt;</code> 로 둔 것이 그 규칙의 구현입니다. <code>&gt;=</code> 로 바꾸면 나중 단어가 이깁니다 — 세 번째 테스트가 이 차이를 잡습니다. <b>동점 규칙을 정하지 않은 집계</b>는 실행할 때마다 결과가 흔들립니다.\n금지어를 배열째 <code>includes</code> 로 검사하면 단어 수 × 금지어 수가 됩니다. <code>Set</code> 하나로 바꾸면 O(1) 이 되는데, 금지어가 수천 개인 실제 필터에서는 이 차이가 눈에 보입니다." },

{ track: "algo", k: "공통 접두사 · longestCommonPrefix", cat: "internals",
  q: "문자열 배열의 <b>가장 긴 공통 접두사</b>를 돌려주세요. 없으면 빈 문자열입니다.",
  src: "function longestCommonPrefix(words) {\n  // TODO: 후보를 하나 잡고, 맞지 않을 때마다 뒤에서 깎으세요\n  return words[0] || \"\";\n}",
  sol: "function longestCommonPrefix(words) {\n  if (!words.length) return \"\";\n  let pre = words[0];\n  words.forEach((w) => {\n    while (pre && w.slice(0, pre.length) !== pre) {\n      pre = pre.slice(0, -1);\n    }\n  });\n  return pre;\n}",
  tests: [['longestCommonPrefix(["flower","flow","flight"])', '"fl"'],
    ['longestCommonPrefix(["dog","car"])', '""'],
    ['longestCommonPrefix(["abc","abc"])', '"abc"'],
    ['longestCommonPrefix(["interspecies","interstellar","interstate"])', '"inters"']],
  edge: [["longestCommonPrefix([])", '""'], ['longestCommonPrefix([""])', '""']],
  ex: "'첫 단어를 후보로 잡고 맞을 때까지 깎는다' 는 것은 <b>답의 상한에서 내려오는</b> 방식입니다. 공통 접두사는 어떤 경우에도 첫 단어보다 길 수 없으므로 후보로 시작하기에 안전합니다.\n<code>while</code> 안에 <code>pre &amp;&amp;</code> 가 있어야 합니다. 없으면 공통 접두사가 아예 없을 때 빈 문자열을 계속 깎으며 <b>무한 반복</b>에 빠집니다. 두 번째 테스트가 그 자리를 정확히 밟습니다.\n<code>startsWith</code> 를 쓰면 더 읽기 좋지만, 여기서는 <code>slice</code> 비교로 두어 <b>비교 구간</b>이 눈에 보이게 했습니다. 실무 코드라면 의도가 드러나는 <code>startsWith</code> 쪽이 낫습니다.\n세로로 훑는 방법 — 모든 단어의 0번째 글자를 비교하고, 같으면 1번째로 — 도 있습니다. 이쪽은 <b>다르면 즉시 멈추므로</b> 첫 글자부터 갈리는 입력에서 훨씬 빠릅니다. 어느 쪽이 나은지는 데이터가 정합니다." },

/* ───────────── 문자열을 직접 훑고 직접 만든다 ───────────── */
{ track: "algo", k: "같은 글자 묶어 압축 · compress", cat: "internals",
  q: "연속된 같은 글자를 <b>글자 + 개수</b>로 바꿔 주세요. 한 번만 나온 글자도 <code>1</code> 을 붙입니다. 예를 들어 <code>aabcc</code> 는 <code>a2b1c2</code> 입니다.",
  src: "function compress(s) {\n  // TODO: 같은 글자가 이어지는 구간의 끝을 찾아 한 번에 처리하세요\n  return s;\n}",
  sol: "function compress(s) {\n  let out = \"\";\n  let i = 0;\n  while (i < s.length) {\n    let j = i;\n    while (j < s.length && s[j] === s[i]) j++;\n    out += s[i] + (j - i);\n    i = j;\n  }\n  return out;\n}",
  tests: [['compress("aabcc")', '"a2b1c2"'],
    ['compress("abc")', '"a1b1c1"'],
    ['compress("aaaa")', '"a4"'],
    ['compress("aabbaa")', '"a2b2a2"']],
  edge: [['compress("")', '""'], ['compress("z")', '"z1"']],
  ex: "'같은 것이 이어지는 구간' 을 다루는 표준 형태입니다. <code>i</code> 는 구간의 시작, <code>j</code> 는 구간을 벗어나는 첫 자리이고, 처리한 뒤 <code>i = j</code> 로 건너뜁니다. <b>한 글자씩 보면서 이전 글자와 비교</b>하는 방식보다 마지막 구간을 흘리는 실수가 적습니다.\n한 글자씩 도는 방식에서 가장 흔한 버그가 <b>반복이 끝난 뒤 마지막 묶음을 안 붙이는</b> 것입니다. <code>aaaa</code> 처럼 끝까지 같은 글자인 입력에서만 드러나 테스트를 대충 짜면 놓칩니다. 세 번째 테스트가 그 자리입니다.\n<code>s[i] + (j - i)</code> 에서 숫자가 자동으로 문자열이 됩니다. 편하지만 <b>암묵적 변환</b>은 다른 곳에서는 사고의 원인이므로, 의도가 있을 때만 기대는 편이 좋습니다.\n실제 압축이라면 <code>abc</code> 가 <code>a1b1c1</code> 로 <b>길어진다</b>는 문제가 있습니다. 그래서 현실의 런렝스 부호화는 '원본보다 길어지면 원본을 쓴다' 는 규칙을 함께 두거나, 반복 구간에만 표시를 붙이는 방식을 씁니다. <b>압축이 늘 줄이지는 않는다</b>는 것이 이 문제의 진짜 교훈입니다." },

{ track: "algo", k: "카멜을 스네이크로 · toSnake", cat: "internals",
  q: "<code>userName</code> 같은 카멜 표기를 <code>user_name</code> 같은 스네이크 표기로 바꿔 주세요. 대문자는 소문자로 낮추고 <b>앞에 밑줄</b>을 붙이되, 맨 앞에는 밑줄을 붙이지 않습니다.",
  src: "function toSnake(s) {\n  // TODO: 대문자를 만났을 때 '맨 앞인가'를 함께 보세요\n  return s.toLowerCase();\n}",
  sol: "function toSnake(s) {\n  let out = \"\";\n  for (const ch of s) {\n    if (ch >= \"A\" && ch <= \"Z\") {\n      out += (out ? \"_\" : \"\") + ch.toLowerCase();\n    } else {\n      out += ch;\n    }\n  }\n  return out;\n}",
  tests: [['toSnake("userName")', '"user_name"'],
    ['toSnake("createdAt")', '"created_at"'],
    ['toSnake("a")', '"a"'],
    ['toSnake("URL")', '"u_r_l"']],
  edge: [['toSnake("")', '""'], ['toSnake("Name")', '"name"']],
  ex: "API 응답의 <code>camelCase</code> 와 데이터베이스 컬럼의 <code>snake_case</code> 를 오가는 일은 실무에서 매주 합니다. 규칙 자체는 간단하지만 <b>경계 조건</b>이 답을 가릅니다 — 맨 앞 대문자에 밑줄을 붙이면 <code>_name</code> 이 되어 컬럼 이름이 깨집니다.\n조건을 <code>i === 0</code> 이 아니라 <code>out ?</code> 으로 둔 것에 주의하세요. 결과가 아직 비어 있는지를 보므로, 앞에 무엇이 있었는지와 무관하게 <b>맨 앞에는 밑줄이 없다</b>는 규칙이 그대로 성립합니다.\n네 번째 테스트가 이 구현의 <b>한계</b>를 드러냅니다. <code>URL</code> 은 <code>u_r_l</code> 이 되는데, 사람이 기대하는 것은 대개 <code>url</code> 입니다. 연속된 대문자를 한 덩어리로 볼지, <code>URLPath</code> 를 <code>url_path</code> 로 자를지는 <b>규칙을 더 정해야</b> 답이 나오는 문제입니다.\n그래서 이런 변환은 <b>양방향으로 되돌아오는지</b>를 테스트해 두는 것이 안전합니다. <code>toCamel(toSnake(x)) === x</code> 가 깨지는 입력을 모아 두면, 규칙을 바꿀 때 무엇이 망가지는지 바로 보입니다." },

{ track: "algo", k: "부분 문자열 첫 위치 · strStr", cat: "internals",
  q: "<code>hay</code> 안에서 <code>needle</code> 이 처음 나타나는 인덱스를 돌려주세요. 없으면 <code>-1</code>, <code>needle</code> 이 빈 문자열이면 <code>0</code> 입니다. <code>indexOf</code> 를 쓰지 말고 직접 구현하세요.",
  src: "function strStr(hay, needle) {\n  // TODO: 시작 자리를 하나씩 옮기며 끝까지 맞는지 확인하세요\n  return -1;\n}",
  sol: "function strStr(hay, needle) {\n  if (!needle) return 0;\n  const last = hay.length - needle.length;\n  for (let i = 0; i <= last; i++) {\n    let j = 0;\n    while (j < needle.length && hay[i + j] === needle[j]) j++;\n    if (j === needle.length) return i;\n  }\n  return -1;\n}",
  tests: [['strStr("hello","ll")', "2"],
    ['strStr("aaaaa","bba")', "-1"],
    ['strStr("abcabd","abd")', "3"],
    ['strStr("mississippi","issip")', "4"]],
  edge: [['strStr("","")', "0"], ['strStr("abc","")', "0"]],
  ex: "시작 자리를 하나씩 옮기며 확인하는 <b>단순 탐색</b>입니다. 최악 O(n·m) 이지만 실제 문자열에서는 대개 몇 글자 만에 어긋나 빠르게 끝납니다 — 그래서 많은 표준 라이브러리가 짧은 패턴에는 이 방식을 씁니다.\n반복 범위를 <code>i &lt;= hay.length - needle.length</code> 로 잡는 것이 핵심입니다. 끝까지 돌면 <code>hay[i + j]</code> 가 <code>undefined</code> 가 되어 비교가 그냥 실패하므로 답은 맞지만, <b>범위를 말로 정한 코드</b>가 읽는 사람에게 의도를 알려 줍니다. <code>needle</code> 이 더 길면 이 값이 음수라 반복이 아예 돌지 않는 것도 자연스럽습니다.\n빈 <code>needle</code> 을 <code>0</code> 으로 정한 것은 <b>약속</b>입니다. 수학적으로 자명한 답이 아니라 표준 라이브러리들이 그렇게 정해 둔 것이고, 이런 규약은 <b>테스트로 못 박아</b> 두지 않으면 리팩터링 때 조용히 바뀝니다.\n최악을 O(n + m) 으로 줄이는 KMP 는 '어긋났을 때 얼마나 되돌아갈지' 를 미리 계산해 둡니다. 하지만 대부분의 상황에서 단순 탐색으로 충분하므로, <b>먼저 재고 나서</b> 바꾸는 순서를 지키세요." },

{ track: "algo", k: "괄호 반복 풀기 · decodeString", cat: "internals",
  q: "<code>3[a]2[bc]</code> 처럼 <b>숫자[문자열]</b> 로 접힌 문자열을 펼쳐 주세요. 중첩될 수 있습니다. 숫자는 1 이상이고 두 자리 이상일 수 있습니다.",
  src: "function decodeString(s) {\n  // TODO: 여는 괄호에서 지금까지의 상태를 밀어 넣고, 닫을 때 꺼내세요\n  return s;\n}",
  sol: "function decodeString(s) {\n  const nums = [];\n  const strs = [];\n  let cur = \"\";\n  let num = 0;\n  for (const ch of s) {\n    if (ch >= \"0\" && ch <= \"9\") {\n      num = num * 10 + Number(ch);\n    } else if (ch === \"[\") {\n      nums.push(num);\n      strs.push(cur);\n      num = 0;\n      cur = \"\";\n    } else if (ch === \"]\") {\n      cur = strs.pop() + cur.repeat(nums.pop());\n    } else {\n      cur += ch;\n    }\n  }\n  return cur;\n}",
  tests: [['decodeString("3[a]2[bc]")', '"aaabcbc"'],
    ['decodeString("3[a2[c]]")', '"accaccacc"'],
    ['decodeString("2[abc]3[cd]ef")', '"abcabccdcdcdef"'],
    ['decodeString("abc")', '"abc"']],
  edge: [['decodeString("")', '""'], ['decodeString("10[a]")', '"aaaaaaaaaa"']],
  ex: "중첩이 있으면 스택입니다. 여는 괄호에서 <b>지금까지 만든 것과 반복 횟수를 밀어 넣고</b> 빈 상태로 안쪽을 시작하며, 닫는 괄호에서 <b>꺼내 이어 붙입니다</b>. 재귀로 짜도 같은 구조이고, 스택은 그 호출 스택을 손으로 만든 것입니다.\n숫자를 <code>num = num * 10 + Number(ch)</code> 로 쌓는 것이 중요합니다. 한 글자씩 바로 쓰면 <code>10[a]</code> 이 <code>1</code> 과 <code>0</code> 으로 갈려 답이 완전히 달라집니다. 마지막 엣지 케이스가 그 자리이고, <b>두 자리 수를 테스트하지 않아</b> 놓치는 일이 잦습니다.\n<code>]</code> 를 만났을 때 <b>순서</b>도 함정입니다. <code>strs.pop() + cur.repeat(...)</code> 이어야지 거꾸로 쓰면 바깥에 있던 글자가 뒤로 갑니다. 세 번째 테스트처럼 반복 뒤에 글자가 더 오는 입력에서 드러납니다.\n같은 골격이 수식 계산기, JSON 파서, 템플릿 전개에 그대로 들어갑니다. <b>여는 기호에서 밀고 닫는 기호에서 꺼낸다</b>는 한 문장을 손에 익혀 두면 중첩 구조는 대부분 같은 모양으로 풀립니다." },

];
