/* 설계 문항 2차 — ERD 8 · API 8 · Cloud 8.
   ref 는 검증용 참조 설계다(주입하지 않는다). 검사식은 구조를 직접 확인하고
   자유 서술 정규식은 최소화한다 — 느슨한 검사는 '설계를 안 해도 맞는' 문항을 만든다. */
module.exports = [
/* ─────────── ERD ─────────── */
{ kind:"erd", k:"시계열 데이터와 파티셔닝", lv:3,
  q:"센서 측정값이 하루 수천만 건씩 쌓입니다. <b>최근 7일 조회가 대부분</b>이고 오래된 데이터는 <b>90일 뒤 삭제</b>합니다. 삭제가 서비스를 멈추지 않도록 설계하세요.",
  src:'{\n  "entities": [\n    { "name": "reading", "fields": [\n      { "name": "id", "type": "bigint", "pk": true },\n      { "name": "sensor_id", "type": "bigint" },\n      { "name": "value", "type": "double" },\n      { "name": "at", "type": "timestamptz" }\n    ] }\n  ],\n  "relations": []\n}',
  ref:{entities:[{name:"sensor",fields:[{name:"id",type:"bigint",pk:true},{name:"name",type:"varchar(50)"}]},
        {name:"reading",fields:[{name:"id",type:"bigint",pk:true},{name:"sensor_id",type:"bigint",fk:"sensor.id",index:true},{name:"value",type:"double"},{name:"at",type:"timestamptz",index:true}],
         partitionBy:"RANGE (at)", partitionUnit:"1 day", retention:"90일 지난 파티션을 DROP"}],
       relations:[{from:"sensor",to:"reading",type:"1:N"}]},
  tests:[{d:"측정값 테이블이 시각으로 파티셔닝된다", js:"D.entities.some(e=>/at|time/i.test(String(e.partitionBy||'')))"},
         {d:"파티션 단위가 정해져 있다", js:"D.entities.some(e=>!!String(e.partitionUnit||'').trim())"},
         {d:"보관 정책이 파티션 단위 삭제다", js:"D.entities.some(e=>/DROP|파티션/i.test(String(e.retention||'')))"},
         {d:"조회 기준 컬럼에 인덱스가 있다", js:"D.entities.find(e=>e.partitionBy).fields.some(f=>/at|time/i.test(f.name)&&f.index===true)"},
         {d:"센서 외래키에 인덱스가 있다", js:"D.entities.find(e=>e.partitionBy).fields.filter(f=>f.fk).every(f=>f.index===true)"}],
  ex:"🎯 <code>DELETE FROM reading WHERE at &lt; ...</code> 로 수천만 행을 지우면 트랜잭션이 길어지고 락과 WAL 이 폭발합니다. 삭제가 <b>서비스를 멈추는</b> 전형적인 방식입니다.\n🔧 시각으로 파티셔닝하면 오래된 데이터를 <b>파티션 통째로 DROP</b> 할 수 있습니다 — 메타데이터만 바뀌므로 거의 즉시 끝납니다.\n💡 파티션 프루닝 덕분에 조회도 빨라집니다. '최근 7일' 조건이면 옵티마이저가 7개 파티션만 봅니다.\n⚠️ 파티션 키는 <b>거의 모든 조회 조건에 들어가야</b> 합니다. 센서 id 로만 조회하는 쿼리는 전 파티션을 훑게 되므로, 접근 패턴을 먼저 확인하고 키를 정하세요." },

{ kind:"erd", k:"다형 관계의 함정", lv:3,
  q:"댓글이 <b>게시글·사진·영상</b> 어디에나 달릴 수 있습니다. <code>target_type</code>+<code>target_id</code> 한 쌍으로 가리키는 방식은 <b>외래키를 걸 수 없습니다</b>. 참조 무결성을 지키도록 설계하세요.",
  src:'{\n  "entities": [\n    { "name": "comment", "fields": [\n      { "name": "id", "type": "bigint", "pk": true },\n      { "name": "target_type", "type": "varchar(20)" },\n      { "name": "target_id", "type": "bigint" },\n      { "name": "body", "type": "text" }\n    ] }\n  ],\n  "relations": []\n}',
  ref:{entities:[{name:"commentable",fields:[{name:"id",type:"bigint",pk:true},{name:"kind",type:"varchar(20)"}],note:"모든 댓글 대상의 공통 상위"},
        {name:"post",fields:[{name:"id",type:"bigint",pk:true,fk:"commentable.id"},{name:"title",type:"varchar(200)"}]},
        {name:"photo",fields:[{name:"id",type:"bigint",pk:true,fk:"commentable.id"},{name:"url",type:"text"}]},
        {name:"comment",fields:[{name:"id",type:"bigint",pk:true},{name:"commentable_id",type:"bigint",fk:"commentable.id",index:true},{name:"body",type:"text"}]}],
       relations:[{from:"commentable",to:"comment",type:"1:N"},{from:"commentable",to:"post",type:"1:1"},{from:"commentable",to:"photo",type:"1:1"}]},
  tests:[{d:"댓글이 진짜 외래키를 갖는다", js:"D.entities.find(e=>e.name==='comment').fields.some(f=>!!f.fk)"},
         {d:"target_type 문자열로 분기하지 않는다", js:"!D.entities.find(e=>e.name==='comment').fields.some(f=>/target_type|_type$/i.test(f.name))"},
         {d:"공통 상위 테이블이 있다", js:"D.entities.length>=3"},
         {d:"구체 타입들이 그 상위를 참조한다", js:"D.entities.filter(e=>e.name!=='comment').filter(e=>e.fields.some(f=>!!f.fk)).length>=2"},
         {d:"댓글의 외래키에 인덱스가 있다", js:"D.entities.find(e=>e.name==='comment').fields.filter(f=>f.fk).every(f=>f.index===true)"}],
  ex:"🎯 <code>target_type</code>+<code>target_id</code> 방식은 편해 보이지만 <b>DB 가 무결성을 지켜 줄 수 없습니다</b>. 게시글이 지워져도 댓글은 그대로 남아 어디에도 속하지 않는 고아가 됩니다.\n🔧 공통 상위 테이블(commentable)을 두고 구체 타입들이 그 id 를 공유하면, 댓글은 <b>진짜 외래키 하나</b>만 가지면 됩니다. 이 방식을 클래스 테이블 상속이라고 부릅니다.\n💡 조인도 단순해집니다 — <code>WHERE target_type = 'post'</code> 같은 분기가 사라지고, 인덱스도 컬럼 하나에만 걸면 됩니다.\n⚠️ 대가는 테이블 하나와 조인 한 번입니다. 대상 타입이 둘뿐이고 앞으로도 안 늘어난다면 <b>각각 별도 댓글 테이블</b>(post_comment, photo_comment)이 더 단순할 수도 있습니다." },

{ kind:"erd", k:"감사 로그", lv:2,
  q:"누가 언제 무엇을 바꿨는지 남겨야 합니다. 대상 레코드가 <b>지워져도 기록은 남아야</b> 하고, <b>변경 전후 값</b>을 알 수 있어야 하며, 감사 로그 자체는 <b>수정할 수 없어야</b> 합니다.",
  src:'{\n  "entities": [\n    { "name": "audit_log", "fields": [\n      { "name": "id", "type": "bigint", "pk": true },\n      { "name": "message", "type": "text" }\n    ] }\n  ],\n  "relations": []\n}',
  ref:{entities:[{name:"audit_log",fields:[
      {name:"id",type:"bigint",pk:true},
      {name:"actor_id",type:"bigint",index:true,note:"users 로 FK 를 걸지 않는다 — 사용자가 지워져도 기록은 남아야 한다"},
      {name:"entity",type:"varchar(50)",index:true},
      {name:"entity_id",type:"bigint",index:true},
      {name:"action",type:"varchar(20)"},
      {name:"before",type:"jsonb",nullable:true},
      {name:"after",type:"jsonb",nullable:true},
      {name:"at",type:"timestamptz",index:true}],
      appendOnly:true, note:"UPDATE·DELETE 권한을 주지 않는다"}],
     relations:[]},
  tests:[{d:"행위자·대상·동작·시각이 모두 있다", js:"['actor','entity','action','at'].every(k=>D.entities[0].fields.some(f=>new RegExp(k,'i').test(f.name)))"},
         {d:"변경 전후 값을 담는 자리가 있다", js:"D.entities[0].fields.some(f=>/before|old|prev/i.test(f.name)) && D.entities[0].fields.some(f=>/after|new/i.test(f.name))"},
         {d:"대상 레코드로 외래키를 걸지 않았다", js:"!D.entities[0].fields.some(f=>/entity_id|target_id/i.test(f.name)&&!!f.fk)"},
         {d:"추가 전용임을 명시했다", js:"D.entities[0].appendOnly===true || /append|불변|immutable|수정할 수 없/i.test(String(D.entities[0].note||''))"},
         {d:"조회 기준 컬럼에 인덱스가 있다", js:"D.entities[0].fields.filter(f=>/entity_id|actor|^at$/i.test(f.name)).every(f=>f.index===true)"}],
  ex:"🎯 감사 로그에 <b>외래키를 걸면 안 됩니다</b>. 사용자를 지울 때 감사 기록까지 함께 지워지거나(CASCADE) 삭제 자체가 막힙니다 — 둘 다 감사의 목적에 어긋납니다. id 만 값으로 남기세요.\n💡 '무엇을 바꿨는지' 는 <b>전후 값 전체</b>를 남기는 편이 안전합니다. 스키마가 바뀌어도 과거 기록을 그대로 읽을 수 있도록 JSON 으로 담는 것이 흔한 선택입니다.\n⚠️ 감사 로그가 <b>수정 가능하면 감사가 아닙니다</b>. 애플리케이션 계정에 UPDATE·DELETE 권한을 주지 않고, 필요하면 별도 저장소나 append-only 스토리지로 분리합니다.\n🔧 개인정보가 전후 값에 그대로 들어갈 수 있습니다 — 마스킹 대상 필드를 미리 정해 두세요." },

{ kind:"erd", k:"복합 인덱스의 컬럼 순서", lv:3,
  q:"주문 테이블에서 <b>'특정 회원의 최근 주문 20건'</b> 조회가 가장 잦습니다. <b>복합 인덱스의 컬럼 순서</b>를 정하고, 왜 그 순서인지가 설계에 드러나게 하세요.",
  src:'{\n  "entities": [\n    { "name": "orders", "fields": [\n      { "name": "id", "type": "bigint", "pk": true },\n      { "name": "member_id", "type": "bigint" },\n      { "name": "status", "type": "varchar(20)" },\n      { "name": "created_at", "type": "timestamptz" }\n    ] }\n  ],\n  "relations": []\n}',
  ref:{entities:[{name:"orders",fields:[{name:"id",type:"bigint",pk:true},{name:"member_id",type:"bigint"},{name:"status",type:"varchar(20)"},{name:"created_at",type:"timestamptz"}],
      indexes:[{name:"ix_member_created",columns:["member_id","created_at"],order:["asc","desc"],
                note:"등호 조건(member_id) 먼저, 정렬 조건(created_at) 나중"}]}],
     relations:[]},
  tests:[{d:"복합 인덱스를 선언했다", js:"(D.entities[0].indexes||[]).some(i=>Array.isArray(i.columns)&&i.columns.length>=2)"},
         {d:"등호 조건 컬럼이 앞에 온다", js:"(D.entities[0].indexes||[]).some(i=>i.columns[0]==='member_id')"},
         {d:"정렬 컬럼이 뒤에 온다", js:"(D.entities[0].indexes||[]).some(i=>/created|at$/i.test(String(i.columns[1])))"},
         {d:"정렬 방향을 지정했다", js:"(D.entities[0].indexes||[]).some(i=>Array.isArray(i.order)&&i.order.length===i.columns.length)"},
         {d:"순서를 정한 이유를 적어 두었다", js:"(D.entities[0].indexes||[]).some(i=>/등호|정렬|범위|선행|prefix/i.test(String(i.note||'')))"}],
  ex:"🎯 복합 인덱스는 <b>왼쪽부터 순서대로</b>만 쓸 수 있습니다(leftmost prefix). <code>(member_id, created_at)</code> 인덱스는 member_id 단독 조회에도 쓰이지만, created_at 단독 조회에는 <b>전혀 쓰이지 않습니다</b>.\n🔧 그래서 순서 규칙은 '<b>등호 조건 먼저, 범위·정렬 나중</b>' 입니다. member_id = ? 로 좁힌 뒤 created_at 순서대로 20건만 읽으면 정렬 작업 자체가 사라집니다.\n💡 순서를 반대로 <code>(created_at, member_id)</code> 로 잡으면 특정 회원을 찾으려고 시간 범위 전체를 훑게 됩니다.\n⚠️ 인덱스를 종류별로 다 만들지 마세요. <code>(a, b)</code> 가 있으면 <code>(a)</code> 는 대개 불필요합니다 — 중복 인덱스는 쓰기 비용만 늘립니다." },

{ kind:"erd", k:"태그와 검색", lv:2,
  q:"글에 태그를 여러 개 붙이고 <b>'이 태그가 붙은 글 목록'</b>을 빠르게 조회해야 합니다. 태그 이름은 <b>중복될 수 없고</b>, 같은 글에 같은 태그를 두 번 붙일 수 없습니다.",
  src:'{\n  "entities": [\n    { "name": "post", "fields": [\n      { "name": "id", "type": "bigint", "pk": true },\n      { "name": "tags", "type": "varchar(500)" }\n    ] }\n  ],\n  "relations": []\n}',
  ref:{entities:[{name:"post",fields:[{name:"id",type:"bigint",pk:true},{name:"title",type:"varchar(200)"}]},
        {name:"tag",fields:[{name:"id",type:"bigint",pk:true},{name:"name",type:"varchar(50)"}],unique:[["name"]]},
        {name:"post_tag",fields:[{name:"post_id",type:"bigint",fk:"post.id",index:true},{name:"tag_id",type:"bigint",fk:"tag.id",index:true}],
         unique:[["post_id","tag_id"]]}],
       relations:[{from:"post",to:"post_tag",type:"1:N"},{from:"tag",to:"post_tag",type:"1:N"}]},
  tests:[{d:"태그를 문자열 컬럼에 몰아넣지 않았다", js:"!D.entities.some(e=>e.fields.some(f=>/^tags$/i.test(f.name)))"},
         {d:"태그 테이블과 연결 테이블이 있다", js:"D.entities.length===3"},
         {d:"태그 이름에 유니크가 걸려 있다", js:"(D.entities.find(e=>/^tag$/i.test(e.name)).unique||[]).some(u=>u.length===1&&/name/i.test(u[0]))"},
         {d:"(글, 태그) 조합이 유일하다", js:"D.entities.some(e=>(e.unique||[]).some(u=>u.length===2&&u.some(c=>/post/.test(c))&&u.some(c=>/tag/.test(c))))"},
         {d:"양쪽 외래키에 인덱스가 있다", js:"D.entities.find(e=>e.fields.filter(f=>f.fk).length===2).fields.filter(f=>f.fk).every(f=>f.index===true)"}],
  ex:"🎯 태그를 <code>'a,b,c'</code> 처럼 한 컬럼에 몰아넣으면 '이 태그가 붙은 글' 조회가 <b>LIKE '%tag%'</b> 가 됩니다 — 인덱스를 못 쓰고, 'java' 를 찾는데 'javascript' 가 딸려 옵니다.\n🔧 연결 테이블로 나누면 <code>tag_id = ?</code> 등호 조회가 되어 인덱스가 그대로 듣습니다.\n💡 연결 테이블에는 별도 id 대신 <b>복합 기본키 (post_id, tag_id)</b> 를 쓰는 것이 자연스럽습니다 — 중복 방지와 기본키가 한 번에 해결됩니다.\n⚠️ 인덱스 방향이 둘 다 필요합니다. <code>(post_id, tag_id)</code> 만 있으면 '태그로 글 찾기' 가 느리므로 반대 방향 인덱스도 두세요." },

{ kind:"erd", k:"중복 계정 병합", lv:3,
  q:"같은 사람이 이메일과 소셜 로그인으로 <b>계정을 두 개</b> 만들었습니다. 로그인 수단을 계정에서 분리해 한 사람이 <b>여러 로그인 수단</b>을 가질 수 있게 설계하세요. 같은 수단이 두 계정에 붙으면 안 됩니다.",
  src:'{\n  "entities": [\n    { "name": "users", "fields": [\n      { "name": "id", "type": "bigint", "pk": true },\n      { "name": "email", "type": "varchar(255)" },\n      { "name": "google_id", "type": "varchar(64)" }\n    ], "unique": [["email"]] }\n  ],\n  "relations": []\n}',
  ref:{entities:[{name:"users",fields:[{name:"id",type:"bigint",pk:true},{name:"display_name",type:"varchar(50)"}]},
        {name:"identity",fields:[{name:"id",type:"bigint",pk:true},{name:"user_id",type:"bigint",fk:"users.id",index:true},
          {name:"provider",type:"varchar(20)"},{name:"subject",type:"varchar(255)"}],
         unique:[["provider","subject"]]}],
       relations:[{from:"users",to:"identity",type:"1:N"}]},
  tests:[{d:"로그인 수단이 별도 테이블로 분리됐다", js:"D.entities.length===2"},
         {d:"users 에 제공자별 컬럼이 남아 있지 않다", js:"!D.entities.find(e=>/user/i.test(e.name)).fields.some(f=>/google|kakao|naver|apple/i.test(f.name))"},
         {d:"수단 테이블이 사용자를 참조한다", js:"D.entities.some(e=>e.fields.some(f=>/user/i.test(String(f.fk||''))))"},
         {d:"(provider, subject) 조합이 유일하다", js:"D.entities.some(e=>(e.unique||[]).some(u=>u.length===2&&u.some(c=>/provider/i.test(c))&&u.some(c=>/subject|uid/i.test(c))))"},
         {d:"사용자 외래키에 인덱스가 있다", js:"D.entities.filter(e=>e.fields.some(f=>f.fk)).every(e=>e.fields.filter(f=>f.fk).every(f=>f.index===true))"}],
  ex:"🎯 로그인 수단을 users 컬럼으로 두면 <b>제공자가 늘 때마다 컬럼이 늘어납니다</b>. 그리고 한 사람이 두 수단을 쓰는 순간 계정이 쪼개집니다.\n🔧 identity 테이블로 분리하면 사용자 1명이 여러 수단을 가질 수 있고, 계정 병합은 <b>identity 의 user_id 를 옮기는</b> 것으로 끝납니다.\n💡 유니크는 <code>(provider, subject)</code> 조합에 걸어야 합니다 — 구글의 subject 와 카카오의 subject 가 우연히 같을 수 있기 때문입니다.\n⚠️ 이메일을 신원 확인 수단으로 쓸 때는 <b>검증 여부</b>를 꼭 함께 두세요. 검증되지 않은 이메일로 자동 병합하면 계정 탈취 경로가 됩니다." },

{ kind:"erd", k:"통화와 다국어", lv:2,
  q:"상품을 <b>여러 통화</b>로 팔고 <b>여러 언어</b>로 이름을 보여 줍니다. 통화마다 소수 자릿수가 다르고, 언어가 늘어날 때 스키마를 바꾸지 않아야 합니다.",
  src:'{\n  "entities": [\n    { "name": "product", "fields": [\n      { "name": "id", "type": "bigint", "pk": true },\n      { "name": "name_ko", "type": "varchar(200)" },\n      { "name": "name_en", "type": "varchar(200)" },\n      { "name": "price", "type": "double" }\n    ] }\n  ],\n  "relations": []\n}',
  ref:{entities:[{name:"product",fields:[{name:"id",type:"bigint",pk:true},{name:"sku",type:"varchar(32)"}],unique:[["sku"]]},
        {name:"product_name",fields:[{name:"product_id",type:"bigint",fk:"product.id",index:true},{name:"locale",type:"varchar(10)"},{name:"name",type:"varchar(200)"}],
         unique:[["product_id","locale"]]},
        {name:"product_price",fields:[{name:"product_id",type:"bigint",fk:"product.id",index:true},{name:"currency",type:"char(3)"},{name:"amount_minor",type:"bigint",note:"최소 단위 정수"}],
         unique:[["product_id","currency"]]}],
       relations:[{from:"product",to:"product_name",type:"1:N"},{from:"product",to:"product_price",type:"1:N"}]},
  tests:[{d:"언어별 컬럼(name_ko/name_en)이 사라졌다", js:"!D.entities.some(e=>e.fields.some(f=>/_ko$|_en$|_ja$/i.test(f.name)))"},
         {d:"이름과 가격이 별도 테이블로 분리됐다", js:"D.entities.length>=3"},
         {d:"(상품, 언어) 조합이 유일하다", js:"D.entities.some(e=>(e.unique||[]).some(u=>u.length===2&&u.some(c=>/locale|lang/i.test(c))))"},
         {d:"(상품, 통화) 조합이 유일하다", js:"D.entities.some(e=>(e.unique||[]).some(u=>u.length===2&&u.some(c=>/currency/i.test(c))))"},
         {d:"금액에 부동소수를 쓰지 않았다", js:"D.entities.every(e=>e.fields.filter(f=>/amount|price/i.test(f.name)).every(f=>!/float|double|real/i.test(String(f.type))))"}],
  ex:"🎯 언어마다 컬럼을 만들면 <b>언어를 추가할 때마다 스키마 마이그레이션</b>이 필요합니다. 행으로 두면 데이터만 넣으면 됩니다.\n💡 통화도 마찬가지입니다. '환율로 환산' 은 안 됩니다 — 나라마다 실제 판매가를 따로 정하고(9,900원 vs $9.99), 환율은 그 관계를 설명하지 못합니다.\n🔧 금액은 <b>최소 단위 정수</b>로 저장하세요. 통화마다 소수 자릿수가 다르므로(원 0자리, 달러 2자리, 디나르 3자리) 정수 + 통화 코드가 가장 안전합니다.\n⚠️ 조회할 때 해당 언어가 없으면 어떻게 할지도 정해야 합니다 — 기본 언어로 폴백할지, 빈 값을 보여 줄지." },

{ kind:"erd", k:"읽기를 위한 비정규화", lv:3,
  q:"글 목록에 <b>좋아요 수</b>와 <b>댓글 수</b>를 함께 보여 줍니다. 매번 COUNT 하면 느리므로 집계값을 저장하되, <b>원본과 어긋났을 때의 대책</b>까지 설계에 담으세요.",
  src:'{\n  "entities": [\n    { "name": "post", "fields": [{ "name": "id", "type": "bigint", "pk": true }] },\n    { "name": "post_like", "fields": [\n      { "name": "post_id", "type": "bigint", "fk": "post.id" },\n      { "name": "user_id", "type": "bigint" }\n    ] }\n  ],\n  "relations": []\n}',
  ref:{entities:[{name:"post",fields:[{name:"id",type:"bigint",pk:true},{name:"title",type:"varchar(200)"},
          {name:"like_count",type:"int",denormalized:true,source:"post_like 행 수",maintainedBy:"같은 트랜잭션에서 증감"},
          {name:"comment_count",type:"int",denormalized:true,source:"comment 행 수",maintainedBy:"같은 트랜잭션에서 증감"}]},
        {name:"post_like",fields:[{name:"post_id",type:"bigint",fk:"post.id",index:true},{name:"user_id",type:"bigint",index:true}],
         unique:[["post_id","user_id"]]},
        {name:"comment",fields:[{name:"id",type:"bigint",pk:true},{name:"post_id",type:"bigint",fk:"post.id",index:true}]}],
       relations:[{from:"post",to:"post_like",type:"1:N"},{from:"post",to:"comment",type:"1:N"}],
       reconcile:"주기적으로 원본 COUNT 와 대조해 보정한다"},
  tests:[{d:"집계 컬럼이 두 개 이상 있다", js:"D.entities.find(e=>e.name==='post').fields.filter(f=>/count$/i.test(f.name)).length>=2"},
         {d:"비정규화임을 표시했다", js:"D.entities.find(e=>e.name==='post').fields.filter(f=>/count$/i.test(f.name)).every(f=>f.denormalized===true)"},
         {d:"원본이 무엇인지 적어 두었다", js:"D.entities.find(e=>e.name==='post').fields.filter(f=>/count$/i.test(f.name)).every(f=>!!String(f.source||'').trim())"},
         {d:"갱신 방법을 명시했다", js:"D.entities.find(e=>e.name==='post').fields.filter(f=>/count$/i.test(f.name)).every(f=>/트랜잭션|transaction|트리거|trigger/i.test(String(f.maintainedBy||'')))"},
         {d:"같은 사람이 두 번 좋아요를 누를 수 없다", js:"(D.entities.find(e=>/like/i.test(e.name)).unique||[]).some(u=>u.length===2)"},
         {d:"어긋났을 때의 보정 계획이 있다", js:"/보정|대조|reconcile|재계산/i.test(JSON.stringify(D))"}],
  ex:"🎯 비정규화는 <b>정규화 위반이 아니라 트레이드오프</b>입니다. 읽기가 압도적으로 많으면 집계값을 저장하는 편이 맞고, 중요한 건 그 사실을 <b>스키마에 명시</b>하는 것입니다.\n🔧 갱신은 원본 변경과 <b>같은 트랜잭션</b>에서 해야 합니다. 애플리케이션 두 곳에서 따로 하면 반드시 어긋납니다.\n⚠️ 그래도 어긋납니다 — 버그·수동 수정·마이그레이션 때문에요. 그래서 <b>주기적으로 원본과 대조해 보정하는</b> 배치가 함께 있어야 합니다. '어긋나지 않게 한다' 가 아니라 '어긋나면 고친다' 가 현실적인 목표입니다.\n💡 인기 글에서는 같은 행을 모두가 갱신해 락 경합이 생깁니다. 아주 큰 규모에서는 카운터를 여러 행으로 쪼개는(sharded counter) 기법을 씁니다." },

/* ─────────── API ─────────── */
{ kind:"api", k:"웹훅 보내기", lv:3,
  q:"결제 완료를 가맹점 서버로 <b>웹훅</b>으로 알립니다. 가맹점이 <b>위조를 구분</b>할 수 있어야 하고, 응답이 없으면 <b>재시도</b>하되, 같은 이벤트를 여러 번 받아도 문제없게 만들어야 합니다.",
  src:'{\n  "endpoints": [\n    { "method": "POST", "path": "{가맹점 URL}", "status": 200, "desc": "결제 완료 통보" }\n  ]\n}',
  ref:{endpoints:[{method:"POST",path:"{merchant_webhook_url}",status:200,errors:[],
    headers:[{name:"X-Signature",required:true,desc:"본문 + 타임스탬프의 HMAC-SHA256"},
             {name:"X-Timestamp",required:true,desc:"재전송 공격 방지 — 5분 넘으면 거절"},
             {name:"X-Event-Id",required:true,desc:"이벤트 고유 id — 수신 측 중복 제거용"}],
    retry:{max:8,backoff:"exponential + jitter",note:"2xx 가 아니면 재시도, 소진되면 DLQ"},
    note:"같은 이벤트가 두 번 이상 도착할 수 있다 — 수신 측이 event_id 로 멱등 처리해야 한다",
    desc:"결제 완료 통보"}]},
  tests:[{d:"서명 헤더가 있다", js:"D.endpoints.some(e=>(e.headers||[]).some(h=>/sign|hmac/i.test(h.name)))"},
         {d:"타임스탬프로 재전송 공격을 막는다", js:"D.endpoints.some(e=>(e.headers||[]).some(h=>/timestamp|date/i.test(h.name)))"},
         {d:"이벤트 고유 id 를 보낸다", js:"D.endpoints.some(e=>(e.headers||[]).some(h=>/event.?id|delivery.?id/i.test(h.name)))"},
         {d:"재시도 한도가 정해져 있다", js:"D.endpoints.some(e=>e.retry&&typeof e.retry.max==='number')"},
         {d:"백오프와 지터를 함께 쓴다", js:"D.endpoints.some(e=>/backoff|exponential/i.test(String(e.retry&&e.retry.backoff))&&/jitter|지터/i.test(String(e.retry&&e.retry.backoff)))"},
         {d:"중복 수신 가능성을 문서에 적었다", js:"/여러 번|중복|두 번|멱등/.test(String(D.endpoints.map(e=>e.note||'').join(' ')))"}],
  ex:"🎯 웹훅은 <b>인증되지 않은 공개 엔드포인트로 들어갑니다</b>. 서명이 없으면 누구나 '결제 완료' 를 위조해 보낼 수 있습니다 — 본문 전체의 HMAC 을 보내고 수신 측이 검증해야 합니다.\n⚠️ 서명만으로는 <b>재전송 공격</b>을 막지 못합니다. 진짜 요청을 캡처해 다시 보내면 서명도 그대로 유효하므로, 타임스탬프를 서명에 포함하고 오래된 것은 거절해야 합니다.\n💡 웹훅은 <b>최소 한 번</b> 전달입니다. 응답이 유실되면 다시 보내므로 같은 이벤트가 두 번 도착할 수 있고 순서도 보장되지 않습니다. 이벤트 id 를 주어 수신 측이 멱등하게 처리하게 하세요.\n🔧 재시도가 무한이면 죽은 엔드포인트를 영원히 두들깁니다. 한도와 DLQ, 그리고 가맹점이 놓친 이벤트를 <b>스스로 조회할 API</b> 도 함께 두는 것이 안전합니다." },

{ kind:"api", k:"벌크 처리와 부분 실패", lv:3,
  q:"주소록을 <b>한 번에 1000건</b> 등록하는 API 를 설계하세요. 일부만 실패했을 때 <b>어느 것이 왜 실패했는지</b> 알 수 있어야 하고, 요청 크기에 상한이 있어야 하며, 전체 성공과 부분 성공을 구분해야 합니다.",
  src:'{\n  "endpoints": [\n    { "method": "POST", "path": "/contacts/bulk", "status": 200, "desc": "일괄 등록" }\n  ]\n}',
  ref:{endpoints:[{method:"POST",path:"/contacts:batchCreate",status:201,errors:[400,413,422],
    limits:{maxItems:1000,maxBodyBytes:1048576},
    response:{succeeded:"[{index, id}]",failed:"[{index, code, message}]"},
    partialStatus:207,
    headers:[{name:"Idempotency-Key",required:true,desc:"재시도 시 중복 생성을 막는다"}],
    note:"전부 성공이면 201, 일부 실패면 207 로 구분한다",desc:"주소록 일괄 등록"}]},
  tests:[{d:"항목 수 상한이 있다", js:"D.endpoints.some(e=>e.limits&&typeof e.limits.maxItems==='number')"},
         {d:"본문 크기 상한이 있다", js:"D.endpoints.some(e=>e.limits&&typeof e.limits.maxBodyBytes==='number')"},
         {d:"성공·실패를 index 로 짝지어 돌려준다", js:"/index/i.test(JSON.stringify(D.endpoints.map(e=>e.response||{})))"},
         {d:"실패 항목마다 사유 코드가 있다", js:"/code/i.test(JSON.stringify(D.endpoints.map(e=>(e.response||{}).failed||'')))"},
         {d:"부분 성공을 별도 상태로 구분한다", js:"D.endpoints.some(e=>e.partialStatus===207||(e.errors||[]).indexOf(207)>=0)"},
         {d:"크기 초과에 413 을 낸다", js:"D.endpoints.some(e=>(e.errors||[]).indexOf(413)>=0)"},
         {d:"재시도 대비 멱등 키를 받는다", js:"D.endpoints.some(e=>(e.headers||[]).some(h=>/idempot/i.test(h.name)))"}],
  ex:"🎯 벌크 API 의 핵심 질문은 '<b>일부만 실패하면 어떻게 되는가</b>' 입니다. 전부 되돌릴지 되는 것만 처리할지 먼저 정하고, 그 선택이 응답에 드러나야 합니다.\n🔧 부분 성공을 200 으로 돌려주면 클라이언트가 <b>실패를 놓칩니다</b>. 성공·실패를 요청 순서(index)로 짝지어 돌려주고, 부분 성공은 207 같은 별도 상태로 구분하세요.\n⚠️ 상한이 없으면 <b>100만 건짜리 요청 하나</b>로 서버가 죽습니다. 항목 수와 본문 바이트 수 둘 다 제한하고 초과는 413 으로 거절합니다.\n💡 벌크는 타임아웃이 나기 쉬워 재시도가 잦습니다 — 멱등 키가 없으면 재시도가 곧 중복 생성입니다. 아주 크면 비동기(202 + 작업 조회)로 바꾸는 것이 맞습니다." },

{ kind:"api", k:"검색 API 의 경계", lv:2,
  q:"상품 검색 API 를 설계하세요. <b>키워드·카테고리·정렬</b>을 받고 결과 수를 함께 돌려줍니다. 검색어가 없어도 동작해야 하고, <b>비싼 조건 조합</b>으로 서버가 죽지 않아야 합니다.",
  src:'{\n  "endpoints": [\n    { "method": "GET", "path": "/search?q=keyword", "status": 200, "desc": "상품 검색" }\n  ]\n}',
  ref:{endpoints:[{method:"GET",path:"/products",status:200,errors:[400],
    params:[{name:"q",required:false,maxLength:100,desc:"키워드 — 없으면 전체"},
            {name:"category",required:false,enum:["book","food","tech"]},
            {name:"sort",required:false,enum:["relevance","price_asc","price_desc"],default:"relevance"},
            {name:"limit",required:false,max:50,default:20}],
    response:{items:"[]",total:"number",totalIsExact:"boolean"},
    note:"total 은 1만 건을 넘으면 근사값으로 준다 — 정확한 전체 개수는 비싸다",
    desc:"상품 검색"}]},
  tests:[{d:"검색어가 선택 항목이다", js:"D.endpoints.some(e=>(e.params||[]).some(p=>/^q$|keyword|query/i.test(p.name)&&p.required===false))"},
         {d:"검색어 길이에 상한이 있다", js:"D.endpoints.some(e=>(e.params||[]).some(p=>/^q$|keyword|query/i.test(p.name)&&typeof p.maxLength==='number'))"},
         {d:"정렬은 허용 목록에서만 고른다", js:"D.endpoints.some(e=>(e.params||[]).some(p=>/sort/i.test(p.name)&&Array.isArray(p.enum)))"},
         {d:"개수 파라미터에 상한과 기본값이 있다", js:"D.endpoints.some(e=>(e.params||[]).some(p=>/limit|size/i.test(p.name)&&typeof p.max==='number'&&p.default!=null))"},
         {d:"응답에 전체 건수가 있다", js:"/total/i.test(JSON.stringify(D.endpoints.map(e=>e.response||{})))"},
         {d:"전체 건수가 근사일 수 있음을 알린다", js:"/근사|approx|exact/i.test(JSON.stringify(D.endpoints.map(e=>[e.note,e.response])))"}],
  ex:"🎯 검색 API 는 <b>사용자가 조합을 정하는</b> 유일한 엔드포인트라 비용 예측이 어렵습니다. 그래서 파라미터마다 상한과 허용 목록이 필요합니다.\n⚠️ 정렬 값을 그대로 SQL 에 붙이면 인젝션입니다 — <b>컬럼명은 바인딩할 수 없으므로</b> 허용 목록 대조가 유일한 방어입니다.\n💡 <b>정확한 전체 건수는 비쌉니다.</b> 조건에 맞는 행이 100만 건이면 COUNT 자체가 전체 스캔입니다. 구글이 '약 1,230,000개' 라고 쓰는 이유가 이것이고, 근사값임을 응답에 표시하면 클라이언트도 그렇게 다룰 수 있습니다.\n🔧 경로도 봐 두세요. <code>/search</code> 보다 <code>/products</code> 에 필터를 붙이는 편이 리소스 중심 설계에 맞습니다." },

{ kind:"api", k:"실시간 전송 방식 고르기", lv:3,
  q:"주문 상태 변화를 화면에 <b>실시간</b>으로 반영해야 합니다. 서버→클라이언트 단방향이고, 연결이 끊겼다 붙으면 <b>놓친 것을 받아야</b> 합니다. 방식을 정하고 재연결 규약을 설계하세요.",
  src:'{\n  "endpoints": [\n    { "method": "GET", "path": "/orders/{id}", "status": 200, "desc": "주문 조회 (폴링)" }\n  ]\n}',
  ref:{endpoints:[{method:"GET",path:"/orders/{id}/events",status:200,errors:[404],
    transport:"SSE",
    headers:[{name:"Last-Event-ID",required:false,desc:"재연결 시 마지막으로 받은 이벤트 id — 그 뒤부터 보낸다"}],
    response:{event:"status_changed",id:"단조 증가 id",data:"{status, at}"},
    note:"서버→클라이언트 단방향이라 WebSocket 이 필요 없다. 프록시 타임아웃 대비 주기적 heartbeat 를 보낸다",
    desc:"주문 상태 이벤트 스트림"},
   {method:"GET",path:"/orders/{id}",status:200,errors:[404],desc:"현재 상태 조회 (폴백)"}]},
  tests:[{d:"전송 방식을 명시했다", js:"D.endpoints.some(e=>/sse|websocket|long.?poll/i.test(String(e.transport||'')))"},
         {d:"이벤트에 단조 증가 id 가 있다", js:"/id/i.test(JSON.stringify(D.endpoints.map(e=>e.response||{})))"},
         {d:"재연결 시 놓친 이벤트를 이어받는 수단이 있다", js:"D.endpoints.some(e=>(e.headers||[]).some(h=>/last.?event|resume|cursor/i.test(h.name)))"},
         {d:"연결 유지(heartbeat)를 고려했다", js:"/heartbeat|keep.?alive|ping/i.test(JSON.stringify(D.endpoints.map(e=>e.note||'')))"},
         {d:"스트림이 안 될 때의 폴백 엔드포인트가 있다", js:"D.endpoints.length>=2 && D.endpoints.some(e=>!e.transport)"}],
  ex:"🎯 방식 선택은 <b>방향</b>이 정합니다. 서버→클라이언트 단방향이면 SSE 로 충분하고, 양방향이어야 WebSocket 이 필요합니다. SSE 는 HTTP 그대로라 프록시·인증·재연결이 훨씬 단순합니다.\n🔧 재연결은 <b>반드시 일어납니다</b> — 모바일 네트워크 전환, 프록시 유휴 타임아웃, 배포. 그래서 이벤트에 단조 증가 id 를 붙이고 클라이언트가 마지막 id 를 보내면 그 뒤부터 이어 보내야 <b>놓친 이벤트</b>가 없습니다. SSE 는 <code>Last-Event-ID</code> 로 이걸 표준화해 두었습니다.\n⚠️ 중간 프록시가 유휴 연결을 끊습니다. 주기적으로 주석 줄이나 heartbeat 를 보내야 연결이 유지됩니다.\n💡 폴백을 남겨 두세요. 기업 프록시가 스트리밍을 막는 환경이 여전히 있습니다." },

{ kind:"api", k:"타임존과 시각 표현", lv:2,
  q:"예약 API 를 설계하세요. 사용자는 <b>여러 나라</b>에 있고, 예약 시각은 <b>매장의 현지 시각</b>으로 정해집니다. 응답의 시각 형식과 요청에 필요한 정보를 정하세요.",
  src:'{\n  "endpoints": [\n    { "method": "POST", "path": "/reservations", "status": 201, "desc": "예약 생성" }\n  ]\n}',
  ref:{endpoints:[{method:"POST",path:"/reservations",status:201,errors:[400,409],
    request:{store_id:"string",local_date:"2026-03-01",local_time:"19:30"},
    response:{id:"string",start_utc:"2026-03-01T10:30:00Z",store_timezone:"Asia/Seoul",start_local:"2026-03-01T19:30:00+09:00"},
    note:"저장은 UTC + 매장 타임존 이름. 오프셋만 저장하면 서머타임 규칙이 바뀔 때 과거 예약이 틀어진다",
    desc:"예약 생성"}]},
  tests:[{d:"응답에 UTC 시각이 있다", js:"/utc/i.test(JSON.stringify(D.endpoints.map(e=>e.response||{})))"},
         {d:"타임존을 이름으로 담는다 (오프셋만이 아니라)", js:"/timezone|Asia\\/|America\\//i.test(JSON.stringify(D.endpoints.map(e=>e.response||{})))"},
         {d:"요청은 현지 날짜·시각으로 받는다", js:"/local/i.test(JSON.stringify(D.endpoints.map(e=>e.request||{})))"},
         {d:"현지 표현도 함께 돌려준다", js:"/local/i.test(JSON.stringify(D.endpoints.map(e=>e.response||{})))"},
         {d:"오프셋만으로는 안 되는 이유를 적었다", js:"/서머타임|DST|일광|오프셋/i.test(String(D.endpoints.map(e=>e.note||'').join(' ')))"}],
  ex:"🎯 '<b>시각 하나를 저장한다</b>' 는 생각이 대부분의 버그를 만듭니다. 예약에는 세 가지가 다 필요합니다 — 절대 시각(UTC), 그 시각을 해석할 타임존, 사용자가 입력한 현지 표현.\n⚠️ <b>오프셋만 저장하면 안 됩니다.</b> <code>+09:00</code> 은 그 순간의 오프셋일 뿐이라, 서머타임이 있는 지역에서는 규칙이 바뀌면 과거·미래 예약이 통째로 틀어집니다. <code>Asia/Seoul</code> 같은 <b>IANA 타임존 이름</b>을 저장해야 규칙 변경을 따라갑니다.\n💡 미래의 반복 일정(매주 화요일 19시)은 특히 UTC 로만 저장하면 안 됩니다 — 서머타임 경계를 넘으면 현지 시각이 한 시간 어긋납니다.\n🔧 응답에는 UTC 와 현지 표현을 <b>둘 다</b> 주세요. 클라이언트가 변환 실수를 할 여지를 줄입니다." },

{ kind:"api", k:"API 키와 권한 범위", lv:3,
  q:"서드파티가 쓰는 API 키를 설계하세요. 키마다 <b>할 수 있는 일이 달라야</b> 하고, 유출 시 <b>즉시 무효화</b>할 수 있어야 하며, 키를 <b>저장소에 평문으로 두면 안 됩니다</b>.",
  src:'{\n  "endpoints": [\n    { "method": "POST", "path": "/api-keys", "status": 201, "desc": "키 발급" }\n  ]\n}',
  ref:{endpoints:[{method:"POST",path:"/api-keys",status:201,errors:[400,401,403],
      request:{name:"string",scopes:["orders:read","orders:write"],expires_at:"2026-12-31"},
      response:{id:"string",prefix:"ak_live_abc",secret:"발급 시 한 번만 노출"},
      note:"서버에는 해시만 저장한다 — 평문은 다시 보여 줄 수 없다",desc:"키 발급"},
    {method:"DELETE",path:"/api-keys/{id}",status:204,errors:[401,403,404],
      note:"즉시 무효화 — 캐시된 검증 결과도 함께 만료시킨다",desc:"키 폐기"},
    {method:"GET",path:"/api-keys",status:200,errors:[401],
      response:{items:"[{id, prefix, scopes, last_used_at}]"},
      note:"secret 은 절대 다시 내보내지 않는다",desc:"키 목록"}]},
  tests:[{d:"키마다 권한 범위를 지정한다", js:"/scope|permission/i.test(JSON.stringify(D.endpoints.map(e=>e.request||{})))"},
         {d:"만료 시각을 정할 수 있다", js:"/expire|expires/i.test(JSON.stringify(D.endpoints.map(e=>e.request||{})))"},
         {d:"비밀값은 발급 시 한 번만 노출한다", js:"/한 번만|once|다시 보여|다시 내보내지/i.test(JSON.stringify(D.endpoints.map(e=>[e.note,e.response])))"},
         {d:"서버에는 해시만 저장한다", js:"/해시|hash/i.test(String(D.endpoints.map(e=>e.note||'').join(' ')))"},
         {d:"즉시 폐기하는 엔드포인트가 있다", js:"D.endpoints.some(e=>e.method==='DELETE')"},
         {d:"목록에서는 접두사만 보여 준다", js:"/prefix/i.test(JSON.stringify(D.endpoints.map(e=>e.response||{})))"}],
  ex:"🎯 API 키는 <b>비밀번호와 같은 취급</b>을 받아야 합니다. 평문으로 저장하면 DB 유출이 곧 모든 고객 계정 탈취입니다 — 해시만 저장하고 검증은 해시 비교로 합니다.\n💡 그래서 <b>발급 시 한 번만</b> 보여 줄 수 있습니다. 잃어버리면 재발급뿐입니다. 대신 목록에서 구분할 수 있도록 접두사(<code>ak_live_abc…</code>)를 따로 저장합니다.\n🔧 <b>범위(scope)</b>가 있어야 최소 권한이 가능합니다. 읽기만 필요한 통합에 전체 권한 키를 주면 유출 시 피해가 몇 배가 됩니다.\n⚠️ 폐기는 <b>즉시</b> 반영돼야 합니다. 검증 결과를 캐시했다면 그것도 함께 무효화해야 하고, 아니면 유출된 키가 캐시 TTL 동안 계속 살아 있습니다." },

{ kind:"api", k:"헬스체크의 두 종류", lv:2,
  q:"오케스트레이터가 쓰는 헬스체크를 설계하세요. <b>'프로세스가 살아 있는가'</b> 와 <b>'트래픽을 받을 준비가 됐는가'</b> 는 다릅니다. 두 검사를 나누고, DB 장애가 <b>전체 재시작을 유발하지 않도록</b> 하세요.",
  src:'{\n  "endpoints": [\n    { "method": "GET", "path": "/health", "status": 200, "desc": "헬스체크" }\n  ]\n}',
  ref:{endpoints:[{method:"GET",path:"/livez",status:200,errors:[500],
      checks:[],note:"의존성을 보지 않는다 — 실패하면 재시작된다",desc:"생존 확인"},
    {method:"GET",path:"/readyz",status:200,errors:[503],
      checks:["db","cache","migration"],note:"의존성이 나쁘면 503 — 트래픽만 빠지고 재시작되지는 않는다",desc:"준비 확인"},
    {method:"GET",path:"/startupz",status:200,errors:[503],
      checks:["warmup"],note:"느린 초기화 동안 생존 검사를 미룬다",desc:"기동 확인"}]},
  tests:[{d:"생존과 준비 검사가 분리돼 있다", js:"D.endpoints.length>=2 && D.endpoints.some(e=>/live/i.test(e.path)) && D.endpoints.some(e=>/ready/i.test(e.path))"},
         {d:"생존 검사는 의존성을 보지 않는다", js:"(D.endpoints.find(e=>/live/i.test(e.path)).checks||[]).length===0"},
         {d:"준비 검사는 의존성을 확인한다", js:"(D.endpoints.find(e=>/ready/i.test(e.path)).checks||[]).length>=2"},
         {d:"준비되지 않았을 때 503 을 낸다", js:"(D.endpoints.find(e=>/ready/i.test(e.path)).errors||[]).indexOf(503)>=0"},
         {d:"둘의 차이를 설명으로 남겼다", js:"/재시작|restart/.test(String(D.endpoints.map(e=>e.note||'').join(' ')))"}],
  ex:"🎯 두 검사를 하나로 합치는 것이 가장 흔한 실수입니다. <code>/health</code> 하나가 DB 까지 확인하면, DB 가 잠깐 느려질 때 <b>모든 인스턴스가 동시에 죽고 재시작</b> 됩니다 — DB 는 더 느려지고 상황은 악화됩니다.\n🔧 <b>생존(liveness)</b> 은 '이 프로세스를 재시작해야 하는가' 를 묻습니다. 데드락이나 복구 불가 상태만 봐야 하고 의존성은 보면 안 됩니다.\n💡 <b>준비(readiness)</b> 는 '지금 트래픽을 줘도 되는가' 입니다. DB 가 죽으면 503 을 내어 트래픽에서만 빠지고, 복구되면 다시 받습니다 — 재시작 없이요.\n⚠️ 기동이 느린 앱은 <b>startup probe</b> 가 따로 필요합니다. 없으면 워밍업 중에 생존 검사가 실패해 무한 재시작 루프에 빠집니다." },

{ kind:"api", k:"파일 다운로드", lv:2,
  q:"보고서 파일 다운로드 API 를 설계하세요. 파일은 <b>비공개</b>라 권한 확인이 필요하고, 대용량이라 <b>이어받기</b>가 되어야 하며, 브라우저가 <b>파일 이름을 알아야</b> 합니다.",
  src:'{\n  "endpoints": [\n    { "method": "GET", "path": "/reports/{id}/file", "status": 200, "desc": "파일 다운로드" }\n  ]\n}',
  ref:{endpoints:[{method:"GET",path:"/reports/{id}/file",status:200,errors:[401,403,404,416],
    requestHeaders:[{name:"Range",required:false,desc:"이어받기 — bytes=1000-"},
                    {name:"If-Range",required:false,desc:"이어받는 사이 파일이 바뀌었는지 확인"}],
    responseHeaders:[{name:"Content-Disposition",desc:"attachment; filename*=UTF-8''보고서.pdf"},
                     {name:"Content-Type",desc:"application/pdf"},
                     {name:"Accept-Ranges",desc:"bytes"},
                     {name:"ETag",desc:"파일 버전"}],
    partialStatus:206,
    note:"권한 확인 후 스트리밍한다 — 전체를 메모리에 올리지 않는다",desc:"보고서 파일"}]},
  tests:[{d:"파일 이름을 알리는 헤더가 있다", js:"D.endpoints.some(e=>(e.responseHeaders||[]).some(h=>/content-disposition/i.test(h.name)))"},
         {d:"파일 이름이 UTF-8 로 인코딩된다", js:"/filename\\*|UTF-8/i.test(JSON.stringify(D.endpoints.map(e=>e.responseHeaders||[])))"},
         {d:"이어받기를 위한 Range 를 받는다", js:"D.endpoints.some(e=>(e.requestHeaders||[]).some(h=>/^range$/i.test(h.name)))"},
         {d:"부분 응답 206 을 쓴다", js:"D.endpoints.some(e=>e.partialStatus===206)"},
         {d:"잘못된 범위에 416 을 낸다", js:"D.endpoints.some(e=>(e.errors||[]).indexOf(416)>=0)"},
         {d:"권한 오류 401·403 이 정의돼 있다", js:"D.endpoints.some(e=>(e.errors||[]).indexOf(401)>=0&&(e.errors||[]).indexOf(403)>=0)"}],
  ex:"🎯 비공개 파일을 스토리지 공개 URL 로 내보내면 <b>링크를 아는 누구나</b> 받을 수 있습니다. 권한 확인이 필요한 파일은 서버를 거치거나 <b>짧은 만료의 서명 URL</b> 을 발급해야 합니다.\n💡 한글 파일 이름은 <code>filename=</code> 만으로는 깨집니다. <code>filename*=UTF-8''…</code> 형식(RFC 5987)을 써야 브라우저가 제대로 읽습니다.\n🔧 대용량은 <b>Range 요청</b>으로 이어받게 하세요. 응답은 200 이 아니라 206 이고, 범위가 잘못되면 416 입니다.\n⚠️ 이어받는 사이 파일이 바뀌면 <b>앞뒤가 섞인 파일</b>이 만들어집니다. ETag 를 주고 클라이언트가 <code>If-Range</code> 로 확인하게 하세요.\n📈 파일을 통째로 메모리에 올리지 말고 스트리밍하세요 — 동시 다운로드 몇 건이 서버를 넘어뜨립니다." },

/* ─────────── CLOUD ─────────── */
{ kind:"cloud", k:"CDN 계층과 무효화", lv:3,
  q:"이미지와 정적 파일을 <b>CDN</b>으로 내보냅니다. 배포할 때 <b>옛 파일이 계속 나가면</b> 안 되고, 캐시가 빌 때 원본 서버로 요청이 몰리지 않아야 합니다.",
  src:'{\n  "components": [\n    { "name": "app", "icon": "🖥" },\n    { "name": "storage", "icon": "🪣" }\n  ],\n  "connections": []\n}',
  ref:{components:[{name:"cdn",icon:"🌐",cachePolicy:[{kind:"정적 자산(해시 파일명)",ttl:"1년",immutable:true},
                    {kind:"HTML",ttl:"0",revalidate:"must-revalidate"}],
        originShield:true,note:"오리진 실드로 원본 요청을 한 곳으로 모은다"},
        {name:"storage",icon:"🪣"},{name:"app",icon:"🖥"}],
       connections:[{from:"cdn",to:"storage",via:"오리진 (정적)"},{from:"cdn",to:"app",via:"오리진 (동적)"}],
       deploy:"파일명에 콘텐츠 해시를 넣어 새 URL 로 배포한다 — 무효화가 필요 없다"},
  tests:[{d:"CDN 이 구성 요소로 있다", js:"D.components.some(c=>/cdn|edge/i.test(c.name))"},
         {d:"자산 종류별로 캐시 정책이 다르다", js:"D.components.some(c=>Array.isArray(c.cachePolicy)&&c.cachePolicy.length>=2)"},
         {d:"해시 파일명 배포를 명시했다", js:"/해시|hash|fingerprint/i.test(JSON.stringify(D))"},
         {d:"HTML 은 캐시하지 않거나 재검증한다", js:"D.components.some(c=>(c.cachePolicy||[]).some(p=>/html/i.test(p.kind)&&(String(p.ttl)==='0'||/revalidate/i.test(String(p.revalidate)))))"},
         {d:"오리진 보호 장치가 있다", js:"/shield|실드|오리진 보호/i.test(JSON.stringify(D.components))"},
         {d:"오리진 연결이 정의돼 있다", js:"D.connections.some(e=>/cdn|edge/i.test(String(e.from)))"}],
  ex:"🎯 캐시 무효화는 <b>느리고 불확실합니다</b>. 전 세계 엣지에 전파되는 데 시간이 걸리고 일부 노드가 남아 있기도 합니다.\n🔧 그래서 정답은 무효화하지 않는 것입니다 — 파일명에 <b>콘텐츠 해시</b>를 넣으면(<code>app.a1b2c3.js</code>) 내용이 바뀔 때 URL 자체가 바뀝니다. 옛 URL 은 영원히 캐시해도 안전하고 새 URL 은 캐시가 없으니 바로 받아 갑니다.\n💡 대신 <b>HTML 은 캐시하면 안 됩니다</b>. 새 해시를 가리키는 것이 HTML 이므로, 그것까지 캐시되면 사용자는 영영 옛 버전을 봅니다.\n⚠️ 캐시가 비는 순간 전 세계 엣지가 동시에 원본을 때립니다. <b>오리진 실드</b>(중간 캐시 계층)를 두면 원본으로 가는 요청이 크게 줄어듭니다." },

{ kind:"cloud", k:"블루그린 배포", lv:3,
  q:"배포 중 <b>다운타임이 없어야</b> 하고, 문제가 생기면 <b>즉시 되돌릴 수</b> 있어야 합니다. 두 환경을 나란히 두는 방식으로 설계하고, DB 스키마 변경을 어떻게 다룰지도 명시하세요.",
  src:'{\n  "components": [\n    { "name": "lb", "icon": "⚖" },\n    { "name": "app", "icon": "🖥", "scale": 3 },\n    { "name": "db", "icon": "🗄" }\n  ],\n  "connections": []\n}',
  ref:{components:[{name:"lb",icon:"⚖",router:"blue|green 전환"},
        {name:"app-blue",icon:"🖥",scale:3,version:"v1",active:true},
        {name:"app-green",icon:"🖥",scale:3,version:"v2",active:false},
        {name:"db",icon:"🗄",shared:true,migration:"확장-축소 방식 — 컬럼 추가는 배포 전, 삭제는 롤백 창이 지난 뒤"}],
       connections:[{from:"lb",to:"app-blue",via:"현재 트래픽"},{from:"lb",to:"app-green",via:"전환 대상"},
        {from:"app-blue",to:"db"},{from:"app-green",to:"db"}],
       rollback:"라우팅을 blue 로 되돌리면 끝 — 재배포가 필요 없다"},
  tests:[{d:"두 개의 앱 환경이 있다", js:"D.components.filter(c=>/app|web/i.test(c.name)).length===2"},
         {d:"어느 쪽이 활성인지 표시한다", js:"D.components.filter(c=>/app|web/i.test(c.name)).filter(c=>c.active===true).length===1"},
         {d:"두 환경의 버전이 다르다", js:"(function(){var a=D.components.filter(function(c){return /app|web/i.test(c.name);});return a[0].version!==a[1].version;})()"},
         {d:"DB 는 공유한다", js:"D.components.some(c=>/db|database/i.test(c.name)&&c.shared===true)"},
         {d:"스키마 변경을 확장-축소로 다룬다", js:"D.components.some(c=>/추가|확장|expand|backward/i.test(String(c.migration||'')))"},
         {d:"롤백 방법을 적어 두었다", js:"/되돌리|롤백|switch back/i.test(JSON.stringify(D))"}],
  ex:"🎯 블루그린의 장점은 <b>롤백이 라우팅 전환</b>이라는 점입니다. 재배포·재빌드 없이 초 단위로 되돌아갑니다.\n⚠️ 함정은 <b>DB</b> 입니다. 두 버전이 같은 DB 를 보므로, 새 버전이 컬럼을 지우거나 의미를 바꾸면 <b>롤백한 순간 옛 버전이 깨집니다</b>.\n🔧 그래서 스키마 변경은 <b>확장-축소</b>(expand-contract)로 나눕니다 — ① 컬럼 추가(양쪽 호환) → ② 새 코드 배포 → ③ 롤백 창이 지난 뒤 옛 컬럼 삭제. 각 단계 사이에 언제든 되돌릴 수 있어야 합니다.\n💡 비용도 고려하세요. 두 환경을 동시에 띄우므로 배포 중에는 <b>자원이 두 배</b>입니다. 롤백 속도와 비용 사이의 선택입니다.\n📈 전환 전에 green 을 실제로 검증해야 합니다 — 스모크 테스트 없이 전환하면 블루그린도 그냥 빅뱅 배포입니다." },

{ kind:"cloud", k:"백업과 복구 목표", lv:3,
  q:"DB 백업 전략을 설계하세요. <b>얼마까지 잃어도 되는지(RPO)</b>와 <b>얼마 만에 복구해야 하는지(RTO)</b>를 숫자로 정하고, 백업이 <b>실제로 복구되는지</b> 확인하는 절차까지 포함하세요.",
  src:'{\n  "components": [\n    { "name": "db", "icon": "🗄" },\n    { "name": "backup", "icon": "💾" }\n  ],\n  "connections": []\n}',
  ref:{components:[{name:"db",icon:"🗄"},
        {name:"snapshot",icon:"💾",schedule:"매일 03:00",retention:"30일"},
        {name:"wal-archive",icon:"📜",schedule:"연속",retention:"7일",note:"시점 복구(PITR)용"},
        {name:"restore-drill",icon:"🧪",schedule:"매월",note:"실제로 복구해 보고 소요 시간을 잰다"}],
       connections:[{from:"db",to:"snapshot"},{from:"db",to:"wal-archive"},{from:"snapshot",to:"restore-drill",via:"복구 훈련"}],
       objectives:{rpo:"5분",rto:"1시간"},
       offsite:"다른 리전에 사본을 둔다"},
  tests:[{d:"RPO 와 RTO 를 숫자로 정했다", js:"!!(D.objectives&&D.objectives.rpo&&D.objectives.rto)"},
         {d:"주기 백업과 연속 아카이브가 모두 있다", js:"D.components.filter(c=>!!c.schedule).length>=2 && D.components.some(c=>/연속|continuous|wal/i.test(c.name+String(c.schedule)))"},
         {d:"보관 기간이 정해져 있다", js:"D.components.filter(c=>/snapshot|backup|archive|wal/i.test(c.name)).every(c=>!!String(c.retention||'').trim())"},
         {d:"복구 훈련이 일정에 있다", js:"D.components.some(c=>/drill|훈련|restore/i.test(c.name))"},
         {d:"다른 리전에 사본을 둔다", js:"/리전|region|offsite|원격/i.test(JSON.stringify(D))"}],
  ex:"🎯 <b>RPO</b> 는 '얼마까지 잃어도 되는가'(백업 간격), <b>RTO</b> 는 '얼마 만에 돌아와야 하는가'(복구 시간)입니다. 숫자로 정하지 않으면 백업 설계를 평가할 수 없습니다.\n💡 하루 한 번 스냅샷만으로는 RPO 가 최악 24시간입니다. 5분을 목표로 하려면 WAL/binlog 를 <b>연속으로 보관</b>해 시점 복구(PITR)가 가능해야 합니다.\n⚠️ <b>복구해 보지 않은 백업은 백업이 아닙니다.</b> 파일이 깨져 있거나, 복구 절차가 문서와 다르거나, 실제 RTO 가 목표의 몇 배인 경우가 흔합니다 — 정기 복구 훈련이 유일한 검증입니다.\n🔧 백업을 원본과 같은 계정·리전에 두면 랜섬웨어나 계정 사고에서 함께 사라집니다. 별도 리전, 가능하면 <b>삭제 권한이 분리된</b> 곳에 두세요." },

{ kind:"cloud", k:"배치 작업의 중복 실행", lv:2,
  q:"정산 배치를 매일 새벽에 돌립니다. 서버가 여러 대라 <b>동시에 여러 번 실행될 수</b> 있고, 실패 시 재실행하면 <b>두 번 정산</b>될 수 있습니다. 한 번만 돌게 설계하세요.",
  src:'{\n  "components": [\n    { "name": "app", "icon": "🖥", "scale": 3 },\n    { "name": "db", "icon": "🗄" }\n  ],\n  "connections": []\n}',
  ref:{components:[{name:"scheduler",icon:"⏰",schedule:"매일 03:00"},
        {name:"app",icon:"🖥",scale:3},
        {name:"lock",icon:"🔒",kind:"분산 잠금",ttl:"30분",note:"한 인스턴스만 실행하도록 선점한다"},
        {name:"job_run",icon:"📋",unique:"(job_name, business_date)",note:"같은 날짜는 한 번만 — 재실행해도 중복되지 않는다"},
        {name:"db",icon:"🗄"}],
       connections:[{from:"scheduler",to:"app"},{from:"app",to:"lock",via:"선점"},{from:"app",to:"job_run",via:"실행 기록"},{from:"app",to:"db"}]},
  tests:[{d:"분산 잠금이 있다", js:"D.components.some(c=>/lock|잠금|lease/i.test(c.name))"},
         {d:"잠금에 만료 시간이 있다", js:"D.components.some(c=>/lock|잠금/i.test(c.name)&&!!String(c.ttl||'').trim())"},
         {d:"실행 기록이 남는다", js:"D.components.some(c=>/job|run|실행/i.test(c.name))"},
         {d:"(작업, 기준일) 조합이 유일하다", js:"D.components.some(c=>/date|날짜/i.test(String(c.unique||'')))"},
         {d:"스케줄러가 명시돼 있다", js:"D.components.some(c=>/schedul|cron/i.test(c.name)&&!!String(c.schedule||'').trim())"}],
  ex:"🎯 크론을 <b>여러 인스턴스에 그대로 두면</b> 매일 세 번 정산이 돌아갑니다. 인스턴스 수만큼 실행되는 이 사고는 오토스케일링을 켜는 순간 조용히 생깁니다.\n🔧 분산 잠금으로 <b>한 인스턴스만 선점</b>하게 합니다. 잠금에는 반드시 만료(TTL)가 있어야 합니다 — 잠금을 쥔 채 프로세스가 죽으면 영원히 안 돌아갑니다.\n⚠️ 잠금만으로는 부족합니다. 실패해서 <b>재실행</b>하면 이미 처리한 부분이 다시 처리됩니다. '(작업 이름, 기준일)' 유니크 제약으로 <b>기준일 단위 멱등성</b>을 만들면 몇 번 재실행해도 결과가 같습니다.\n💡 배치는 '어느 날짜분을 처리하는가' 를 인자로 받아야 합니다. <code>오늘</code> 을 코드 안에서 계산하면 재실행 시점에 따라 다른 날짜를 처리해 버립니다." },

{ kind:"cloud", k:"멀티 리전과 지연", lv:3,
  q:"서비스를 <b>한국과 미국</b> 두 리전에서 제공합니다. 읽기는 가까운 리전에서 처리하고 <b>쓰기는 한 곳으로</b> 모읍니다. 리전 간 지연이 사용자 경험을 해치지 않도록 설계하세요.",
  src:'{\n  "components": [\n    { "name": "app-kr", "icon": "🖥" },\n    { "name": "db", "icon": "🗄" }\n  ],\n  "connections": []\n}',
  ref:{components:[{name:"geo-dns",icon:"🧭",region:"global",note:"가까운 리전으로 보낸다"},
        {name:"app-kr",icon:"🖥",region:"kr"},{name:"app-us",icon:"🖥",region:"us"},
        {name:"db-primary",icon:"🗄",region:"kr",role:"write"},
        {name:"db-replica-us",icon:"🗄",region:"us",role:"read",lagAlert:"2s"}],
       connections:[{from:"geo-dns",to:"app-kr"},{from:"geo-dns",to:"app-us"},
        {from:"app-us",to:"db-replica-us",via:"읽기"},
        {from:"app-us",to:"db-primary",via:"쓰기 — 리전 간 왕복을 감수한다"},
        {from:"db-primary",to:"db-replica-us",via:"비동기 복제"},
        {from:"app-us",to:"db-primary",via:"쓴 직후 읽기는 프라이머리로"}]},
  tests:[{d:"모든 구성 요소에 리전이 표시된다", js:"D.components.every(c=>!!c.region)"},
         {d:"쓰기 프라이머리는 한 곳이다", js:"D.components.filter(c=>String(c.role||'')==='write').length===1"},
         {d:"원격 리전에 읽기 복제본이 있다", js:"D.components.some(c=>String(c.role||'')==='read'&&c.region!==D.components.find(x=>x.role==='write').region)"},
         {d:"지리 기반 라우팅이 있다", js:"D.components.some(c=>/geo|dns|route/i.test(c.name))"},
         {d:"쓰기가 프라이머리로 가는 경로가 있다", js:"D.connections.some(e=>/primary/i.test(String(e.to))&&/쓰기|write/i.test(String(e.via||'')))"},
         {d:"복제 지연을 감시한다", js:"/lag|지연/i.test(JSON.stringify(D.components))"}],
  ex:"🎯 멀티 리전의 본질은 '<b>읽기는 가깝게, 쓰기는 한 곳으로</b>' 입니다. 읽기 지연은 복제본으로 해결되지만, 쓰기를 여러 곳에서 받으면 충돌 해결이라는 훨씬 어려운 문제가 생깁니다.\n⚠️ 미국 사용자의 <b>쓰기는 태평양을 건넙니다</b> — 왕복 150ms 이상입니다. 이걸 숨길 수는 없으니 화면을 낙관적으로 먼저 갱신하는 등 UX 로 다뤄야 합니다.\n💡 복제 지연 때문에 '<b>미국에서 글을 썼는데 새로고침하면 사라진다</b>' 는 현상이 나옵니다. 쓴 직후 일정 시간은 그 사용자의 읽기를 프라이머리로 보내야 합니다.\n🔧 진짜 멀티 마스터가 필요하면 CRDT 나 충돌 해결 규칙이 있는 저장소를 써야 합니다 — '나중 쓰기가 이긴다' 는 <b>데이터를 조용히 잃는</b> 규칙입니다." },

{ kind:"cloud", k:"컨테이너 이미지 공급망", lv:3,
  q:"컨테이너 이미지를 안전하게 배포하도록 설계하세요. <b>어떤 코드로 만들어졌는지</b> 추적할 수 있어야 하고, <b>취약점을 배포 전에</b> 걸러야 하며, <code>latest</code> 태그로 배포하면 안 됩니다.",
  src:'{\n  "components": [\n    { "name": "ci", "icon": "⚙" },\n    { "name": "registry", "icon": "📦" },\n    { "name": "cluster", "icon": "☸" }\n  ],\n  "connections": []\n}',
  ref:{components:[{name:"ci",icon:"⚙",produces:"이미지 태그 = 커밋 SHA",sbom:true,note:"빌드 산출물에 SBOM 을 첨부한다"},
        {name:"scanner",icon:"🔎",gate:"HIGH 이상 취약점이면 배포 중단"},
        {name:"signer",icon:"✍",note:"이미지에 서명한다"},
        {name:"registry",icon:"📦",immutableTags:true},
        {name:"cluster",icon:"☸",admission:"서명 검증을 통과한 이미지만 실행",digestPinned:true}],
       connections:[{from:"ci",to:"scanner"},{from:"scanner",to:"signer"},{from:"signer",to:"registry"},
        {from:"registry",to:"cluster",via:"digest 로 고정 배포"}]},
  tests:[{d:"태그가 커밋과 연결된다", js:"D.components.some(c=>/sha|commit|커밋/i.test(String(c.produces||'')))"},
         {d:"취약점 스캔이 배포를 막을 수 있다", js:"D.components.some(c=>/scan/i.test(c.name)&&/중단|block|fail/i.test(String(c.gate||'')))"},
         {d:"이미지에 서명한다", js:"D.components.some(c=>/sign|서명/i.test(c.name+String(c.note||'')))"},
         {d:"클러스터가 서명을 검증한다", js:"D.components.some(c=>/서명|sign/i.test(String(c.admission||'')))"},
         {d:"태그를 덮어쓸 수 없다", js:"D.components.some(c=>c.immutableTags===true)"},
         {d:"digest 로 고정 배포한다", js:"/digest/i.test(JSON.stringify(D))"}],
  ex:"🎯 <code>latest</code> 태그는 <b>무엇이 돌고 있는지 아무도 모르게</b> 만듭니다. 같은 태그가 어제와 오늘 다른 이미지를 가리키므로 롤백도 재현도 불가능합니다. 태그는 커밋 SHA 로, 실제 배포는 <b>digest</b> 로 고정하세요.\n🔧 스캔은 <b>배포를 막을 수 있어야</b> 의미가 있습니다. 리포트만 만들고 아무도 안 보면 없는 것과 같습니다 — 임계 등급을 정해 게이트로 두세요.\n💡 서명과 승인 제어(admission control)가 짝입니다. 서명만 하고 클러스터가 검증하지 않으면, 레지스트리가 뚫렸을 때 위조 이미지가 그대로 실행됩니다.\n⚠️ SBOM(구성 요소 목록)이 있어야 <b>새 취약점이 공개됐을 때</b> 영향 범위를 즉시 알 수 있습니다. Log4Shell 때 '우리가 이걸 쓰고 있나?' 에 며칠씩 걸린 팀과 몇 분 만에 답한 팀을 가른 것이 이것입니다." },

{ kind:"cloud", k:"네트워크 분리", lv:3,
  q:"DB 가 인터넷에서 직접 접근되지 않도록 네트워크를 설계하세요. 애플리케이션은 <b>외부 API 를 호출</b>해야 하고, 운영자는 <b>기록이 남는 경로로</b> DB 에 접속할 수 있어야 합니다.",
  src:'{\n  "components": [\n    { "name": "app", "icon": "🖥" },\n    { "name": "db", "icon": "🗄" }\n  ],\n  "connections": []\n}',
  ref:{components:[{name:"alb",icon:"⚖",subnet:"public"},
        {name:"app",icon:"🖥",subnet:"private",scale:2},
        {name:"db",icon:"🗄",subnet:"private",publicAccess:false},
        {name:"nat",icon:"🔀",subnet:"public",note:"프라이빗 서브넷의 아웃바운드만 허용"},
        {name:"bastion",icon:"🚪",subnet:"public",note:"세션 기록이 남는 관리 접속 경로 — 상시 개방하지 않는다"}],
       connections:[{from:"alb",to:"app"},{from:"app",to:"db"},{from:"app",to:"nat",via:"외부 API 호출"},
        {from:"bastion",to:"db",via:"운영자 접속 (감사 기록)"}],
       rules:"보안 그룹은 출발지를 IP 대역이 아니라 다른 보안 그룹으로 지정한다"},
  tests:[{d:"모든 구성 요소에 서브넷이 지정돼 있다", js:"D.components.every(c=>!!c.subnet)"},
         {d:"DB 는 프라이빗 서브넷에 있다", js:"D.components.some(c=>/db|database/i.test(c.name)&&/private/i.test(String(c.subnet)))"},
         {d:"DB 에 공개 접근이 꺼져 있다", js:"D.components.some(c=>/db|database/i.test(c.name)&&c.publicAccess===false)"},
         {d:"앱은 프라이빗, 로드밸런서만 공개다", js:"D.components.some(c=>/app/i.test(c.name)&&/private/i.test(String(c.subnet))) && D.components.some(c=>/alb|lb|balanc/i.test(c.name)&&/public/i.test(String(c.subnet)))"},
         {d:"아웃바운드 전용 경로(NAT)가 있다", js:"D.components.some(c=>/nat/i.test(c.name))"},
         {d:"관리 접속 경로가 따로 있다", js:"D.components.some(c=>/bastion|jump|관리/i.test(c.name))"}],
  ex:"🎯 <b>DB 에 공개 IP 를 주지 않는 것</b>이 가장 값싼 방어입니다. 비밀번호가 유출돼도 네트워크에서 닿을 수 없으면 피해가 없습니다 — 인터넷에 열린 DB 는 몇 분 안에 스캔됩니다.\n🔧 앱도 프라이빗에 두고 로드밸런서만 공개합니다. 앱이 외부 API 를 불러야 하면 <b>NAT 게이트웨이</b>로 아웃바운드만 허용하세요 — 나가는 건 되지만 들어오는 건 안 됩니다.\n💡 운영자 접속은 없앨 수 없으니 <b>기록이 남는 통로 하나</b>로 좁힙니다. 요즘은 상시 켜 둔 bastion 대신 필요할 때만 여는 세션 관리자 방식이 더 안전합니다.\n⚠️ 보안 그룹 규칙에 <code>0.0.0.0/0</code> 을 쓰지 마세요. 출발지를 <b>다른 보안 그룹</b>으로 지정하면 IP 가 바뀌어도 규칙이 유효하고, 실수로 전 세계를 여는 일이 없습니다." },
];
