/* 설계 문항 3차 — ERD 7 · API 7 · Cloud 7 (arch 129 → 150 목표 달성분).
   ref 는 검증용 참조 설계다(주입하지 않는다). */
module.exports = [
/* ─────────── ERD ─────────── */
{ kind:"erd", k:"아웃박스로 이벤트 보내기", lv:3,
  q:"주문을 저장하고 <b>다른 서비스에 이벤트를 보내야</b> 합니다. DB 커밋은 됐는데 메시지 발행이 실패하면 이벤트가 사라지고, 반대면 없는 주문의 이벤트가 나갑니다. <b>둘이 함께 성립하도록</b> 설계하세요.",
  src:'{\n  "entities": [\n    { "name": "orders", "fields": [\n      { "name": "id", "type": "bigint", "pk": true },\n      { "name": "total", "type": "bigint" }\n    ] }\n  ],\n  "relations": []\n}',
  ref:{entities:[{name:"orders",fields:[{name:"id",type:"bigint",pk:true},{name:"total",type:"bigint"}]},
        {name:"outbox",fields:[{name:"id",type:"bigint",pk:true},
          {name:"aggregate_id",type:"bigint",index:true},
          {name:"event_type",type:"varchar(50)"},
          {name:"payload",type:"jsonb"},
          {name:"created_at",type:"timestamptz"},
          {name:"published_at",type:"timestamptz",nullable:true,index:true}],
         note:"주문 저장과 같은 트랜잭션에서 함께 INSERT 한다. 별도 발행기가 published_at 이 비어 있는 행을 읽어 보낸다"}],
       relations:[{from:"orders",to:"outbox",type:"1:N"}],
       delivery:"최소 한 번 — 수신 측이 event id 로 멱등 처리한다"},
  tests:[{d:"아웃박스 테이블이 있다", js:"D.entities.some(e=>/outbox|event/i.test(e.name))"},
         {d:"이벤트 본문을 담는 자리가 있다", js:"D.entities.some(e=>/outbox|event/i.test(e.name)&&e.fields.some(f=>/payload|body|data/i.test(f.name)))"},
         {d:"발행 여부를 표시하는 컬럼이 있고 NULL 을 허용한다", js:"D.entities.some(e=>e.fields.some(f=>/published|sent|dispatched/i.test(f.name)&&f.nullable===true))"},
         {d:"미발행 행을 찾기 위한 인덱스가 있다", js:"D.entities.some(e=>e.fields.some(f=>/published|sent|dispatched/i.test(f.name)&&f.index===true))"},
         {d:"같은 트랜잭션에서 쓴다는 점을 적었다", js:"/같은 트랜잭션|동일 트랜잭션|한 트랜잭션/.test(JSON.stringify(D))"},
         {d:"중복 전달 가능성을 밝혀 두었다", js:"/최소 한 번|at.least.once|멱등/i.test(JSON.stringify(D))"}],
  ex:"🎯 DB 쓰기와 메시지 발행은 <b>서로 다른 시스템</b>이라 하나의 트랜잭션으로 묶을 수 없습니다. 어느 쪽을 먼저 하든 그 사이에 프로세스가 죽으면 둘이 어긋납니다.\n🔧 <b>아웃박스 패턴</b>은 이벤트를 같은 DB 에 <b>같은 트랜잭션으로</b> 함께 넣습니다. 그러면 '주문은 있는데 이벤트가 없는' 상태가 원천적으로 불가능합니다. 발행은 별도 프로세스가 미발행 행을 읽어 처리합니다.\n💡 대가는 <b>지연과 중복</b>입니다. 이벤트가 즉시 나가지 않고, 발행 후 표시 전에 죽으면 같은 이벤트가 두 번 나갑니다 — 그래서 수신 측 멱등 처리가 전제입니다.\n⚠️ 발행된 행을 지우지 않으면 테이블이 무한히 자랍니다. 보관 기간을 정하거나 파티셔닝하세요." },

{ kind:"erd", k:"샤딩 키 고르기", lv:3,
  q:"메시지 테이블이 한 DB 로 감당이 안 됩니다. <b>샤딩 키</b>를 정하고, '<b>한 대화방의 메시지 목록</b>' 조회가 여러 샤드에 흩어지지 않도록 설계하세요. 전역 유일 id 도 필요합니다.",
  src:'{\n  "entities": [\n    { "name": "message", "fields": [\n      { "name": "id", "type": "bigint", "pk": true },\n      { "name": "room_id", "type": "bigint" },\n      { "name": "sender_id", "type": "bigint" },\n      { "name": "body", "type": "text" }\n    ] }\n  ],\n  "relations": []\n}',
  ref:{entities:[{name:"message",fields:[
      {name:"id",type:"bigint",pk:true,idStrategy:"Snowflake — 시각 + 샤드 + 시퀀스"},
      {name:"room_id",type:"bigint",index:true},
      {name:"sender_id",type:"bigint",index:true},
      {name:"body",type:"text"},
      {name:"created_at",type:"timestamptz",index:true}],
      shardKey:"room_id", note:"같은 방의 메시지는 같은 샤드에 모인다 — 목록 조회가 한 샤드로 끝난다",
      crossShard:"사용자별 전체 메시지 검색은 여러 샤드를 훑어야 한다 — 별도 색인을 둔다"}],
     relations:[]},
  tests:[{d:"샤딩 키를 명시했다", js:"D.entities.some(e=>!!String(e.shardKey||'').trim())"},
         {d:"샤딩 키가 조회 기준(room_id)이다", js:"D.entities.some(e=>/room/i.test(String(e.shardKey||'')))"},
         {d:"자동 증가에 기대지 않는 id 전략이 있다", js:"D.entities[0].fields.some(f=>f.pk&&/snowflake|uuid|ulid|시각|시퀀스/i.test(String(f.idStrategy||'')))"},
         {d:"샤딩 키에 인덱스가 있다", js:"D.entities[0].fields.some(f=>/room/i.test(f.name)&&f.index===true)"},
         {d:"샤드를 넘는 조회의 대책을 적었다", js:"D.entities.some(e=>!!String(e.crossShard||'').trim())"}],
  ex:"🎯 샤딩 키는 '<b>가장 자주 함께 읽는 단위</b>' 로 정합니다. 대화방 기준으로 나누면 목록 조회가 한 샤드에서 끝나지만, 사용자 id 로 나누면 한 방의 메시지가 참여자 수만큼 흩어집니다.\n⚠️ 샤딩하면 <b>자동 증가 id 를 쓸 수 없습니다</b> — 샤드마다 1,2,3 이 생겨 충돌합니다. Snowflake(시각+샤드+시퀀스)나 UUID/ULID 로 전역 유일성을 만들어야 하고, 시각이 앞에 오는 방식이 인덱스 지역성에 유리합니다.\n💡 샤딩을 하면 <b>조인과 트랜잭션이 샤드 안에서만</b> 가능합니다. 샤드를 넘는 조회는 애플리케이션이 흩뿌려 모아야 하므로, 그런 조회가 잦다면 별도 색인(검색 엔진)을 두는 편이 낫습니다.\n🔧 샤딩은 마지막 수단입니다. 인덱스·파티셔닝·읽기 복제본으로 안 될 때 검토하세요 — 운영 복잡도가 크게 오릅니다." },

{ kind:"erd", k:"권한 모델", lv:3,
  q:"사용자에게 <b>역할</b>을 주고 역할에 <b>권한</b>을 붙이는 구조를 설계하세요. 한 사용자가 역할을 여러 개 가질 수 있고, 권한은 <b>조직 단위로</b> 달라야 합니다(같은 사람이 A팀에서는 관리자, B팀에서는 조회자).",
  src:'{\n  "entities": [\n    { "name": "users", "fields": [\n      { "name": "id", "type": "bigint", "pk": true },\n      { "name": "role", "type": "varchar(20)" }\n    ] }\n  ],\n  "relations": []\n}',
  ref:{entities:[{name:"users",fields:[{name:"id",type:"bigint",pk:true},{name:"email",type:"varchar(255)"}],unique:[["email"]]},
        {name:"org",fields:[{name:"id",type:"bigint",pk:true},{name:"name",type:"varchar(50)"}]},
        {name:"role",fields:[{name:"id",type:"bigint",pk:true},{name:"name",type:"varchar(30)"}],unique:[["name"]]},
        {name:"permission",fields:[{name:"id",type:"bigint",pk:true},{name:"code",type:"varchar(50)"}],unique:[["code"]]},
        {name:"role_permission",fields:[{name:"role_id",type:"bigint",fk:"role.id",index:true},{name:"permission_id",type:"bigint",fk:"permission.id",index:true}],unique:[["role_id","permission_id"]]},
        {name:"membership",fields:[{name:"user_id",type:"bigint",fk:"users.id",index:true},{name:"org_id",type:"bigint",fk:"org.id",index:true},{name:"role_id",type:"bigint",fk:"role.id",index:true}],
         unique:[["user_id","org_id","role_id"]]}],
       relations:[{from:"users",to:"membership",type:"1:N"},{from:"org",to:"membership",type:"1:N"},{from:"role",to:"membership",type:"1:N"},{from:"role",to:"role_permission",type:"1:N"}]},
  tests:[{d:"users 에 role 문자열 컬럼이 없다", js:"!D.entities.find(e=>/user/i.test(e.name)).fields.some(f=>/^role$/i.test(f.name))"},
         {d:"역할과 권한이 각각 테이블이다", js:"D.entities.some(e=>/^role$/i.test(e.name)) && D.entities.some(e=>/permission$/i.test(e.name))"},
         {d:"역할-권한 연결 테이블이 있다", js:"D.entities.some(e=>e.fields.filter(f=>/role|permission/i.test(String(f.fk||''))).length===2)"},
         {d:"사용자-조직-역할이 한 행으로 묶인다", js:"D.entities.some(e=>e.fields.filter(f=>!!f.fk).length===3 && e.fields.some(f=>/org/i.test(String(f.fk))))"},
         {d:"같은 조합이 중복되지 않는다", js:"D.entities.some(e=>(e.unique||[]).some(u=>u.length===3))"},
         {d:"모든 외래키에 인덱스가 있다", js:"D.entities.every(e=>e.fields.filter(f=>f.fk).every(f=>f.index===true))"}],
  ex:"🎯 <code>users.role</code> 문자열 하나로는 '<b>어디에서</b> 무슨 역할인가' 를 표현할 수 없습니다. 멀티 테넌트 서비스에서 같은 사람이 조직마다 다른 권한을 갖는 건 기본 요구사항입니다.\n🔧 (사용자, 조직, 역할) 세 쌍을 한 행으로 두는 <b>membership</b> 이 그 자리입니다. 권한 확인은 '이 사용자가 이 조직에서 가진 역할들의 권한 합집합' 이 됩니다.\n💡 역할에 권한을 <b>코드로 하드코딩</b>하지 말고 테이블로 두면, 새 권한이 생겨도 배포 없이 붙일 수 있습니다.\n⚠️ 권한 확인이 매 요청마다 여러 조인을 타면 느려집니다. 로그인 시 권한 집합을 계산해 토큰이나 캐시에 담되, <b>권한이 바뀌었을 때 무효화</b>하는 방법을 함께 정해야 합니다." },

{ kind:"erd", k:"첨부 파일 메타데이터", lv:2,
  q:"사용자가 올린 파일을 다룹니다. 파일 <b>본문은 오브젝트 스토리지</b>에 두고 DB 에는 메타데이터만 둡니다. <b>같은 파일을 두 번 올려도 저장소는 한 번만</b> 쓰이게 하고, 업로드가 중간에 끊긴 것을 정리할 수 있어야 합니다.",
  src:'{\n  "entities": [\n    { "name": "attachment", "fields": [\n      { "name": "id", "type": "bigint", "pk": true },\n      { "name": "data", "type": "bytea" }\n    ] }\n  ],\n  "relations": []\n}',
  ref:{entities:[{name:"blob",fields:[{name:"id",type:"bigint",pk:true},{name:"sha256",type:"char(64)"},
          {name:"size",type:"bigint"},{name:"storage_key",type:"varchar(255)"},{name:"ref_count",type:"int"}],
         unique:[["sha256"]]},
        {name:"attachment",fields:[{name:"id",type:"bigint",pk:true},{name:"blob_id",type:"bigint",fk:"blob.id",index:true},
          {name:"owner_id",type:"bigint",index:true},{name:"filename",type:"varchar(255)"},
          {name:"status",type:"varchar(20)",note:"pending → ready"},{name:"created_at",type:"timestamptz",index:true}]}],
       relations:[{from:"blob",to:"attachment",type:"1:N"}],
       cleanup:"pending 상태로 24시간 넘은 행과 ref_count 가 0인 blob 을 정리한다"},
  tests:[{d:"파일 본문을 DB 에 넣지 않는다", js:"!D.entities.some(e=>e.fields.some(f=>/bytea|blob|binary/i.test(String(f.type))))"},
         {d:"저장소 키를 갖고 있다", js:"D.entities.some(e=>e.fields.some(f=>/storage|key|path|url/i.test(f.name)))"},
         {d:"내용 해시로 중복을 판별한다", js:"D.entities.some(e=>(e.unique||[]).some(u=>u.some(c=>/sha|hash|digest/i.test(c))))"},
         {d:"업로드 상태를 구분한다", js:"D.entities.some(e=>e.fields.some(f=>/status|state/i.test(f.name)))"},
         {d:"정리 정책이 적혀 있다", js:"/정리|cleanup|만료|고아/i.test(JSON.stringify(D))"},
         {d:"외래키에 인덱스가 있다", js:"D.entities.every(e=>e.fields.filter(f=>f.fk).every(f=>f.index===true))"}],
  ex:"🎯 파일 본문을 DB 에 넣으면 백업·복제·캐시가 모두 무거워집니다. 본문은 오브젝트 스토리지에, DB 에는 <b>가리키는 정보만</b> 두는 것이 기본입니다.\n🔧 <b>내용 해시(SHA-256)</b>를 유니크 키로 두면 같은 파일을 여러 명이 올려도 저장소에는 한 번만 씁니다. 대신 참조 수를 세어야 마지막 참조가 사라질 때 지울 수 있습니다.\n⚠️ 업로드는 <b>중간에 끊깁니다</b>. 서명 URL 을 발급한 뒤 완료 통보가 안 오면 DB 행만 남고 파일은 없거나 그 반대가 됩니다 — pending 상태와 정리 배치가 반드시 필요합니다.\n💡 반대 방향의 고아도 생깁니다. 저장소에 있는데 DB 에 없는 파일은 조용히 비용만 쓰므로, 주기적으로 양쪽을 대조하세요." },

{ kind:"erd", k:"재고 예약과 만료", lv:3,
  q:"장바구니에 담으면 재고를 <b>10분간 잡아 둡니다</b>. 결제하면 확정되고, 시간이 지나면 자동으로 풀려야 합니다. 배치가 늦게 돌아도 <b>만료된 예약이 재고를 계속 묶지 않도록</b> 설계하세요.",
  src:'{\n  "entities": [\n    { "name": "stock", "fields": [\n      { "name": "sku", "type": "varchar(32)", "pk": true },\n      { "name": "qty", "type": "int" }\n    ] }\n  ],\n  "relations": []\n}',
  ref:{entities:[{name:"stock",fields:[{name:"sku",type:"varchar(32)",pk:true},{name:"on_hand",type:"int",check:"on_hand >= 0"}]},
        {name:"reservation",fields:[{name:"id",type:"bigint",pk:true},{name:"sku",type:"varchar(32)",fk:"stock.sku",index:true},
          {name:"qty",type:"int",check:"qty > 0"},{name:"status",type:"varchar(20)",note:"held | confirmed | released",index:true},
          {name:"expires_at",type:"timestamptz",index:true}]}],
       relations:[{from:"stock",to:"reservation",type:"1:N"}],
       availability:"가용 재고 = on_hand - SUM(held 이면서 expires_at > now 인 예약의 qty) — 조회 시점에 만료를 반영한다",
       cleanup:"배치가 만료된 held 를 released 로 바꾼다(정리용이지 정확성의 근거가 아니다)"},
  tests:[{d:"예약이 별도 테이블이다", js:"D.entities.length===2"},
         {d:"예약에 만료 시각이 있다", js:"D.entities.some(e=>e.fields.some(f=>/expire|until|valid_to/i.test(f.name)))"},
         {d:"예약 상태를 구분한다", js:"D.entities.some(e=>e.fields.some(f=>/status|state/i.test(f.name)))"},
         {d:"재고가 음수가 되지 않도록 제약을 걸었다", js:"D.entities.some(e=>e.fields.some(f=>/(>=|>)\\s*0/.test(String(f.check||''))))"},
         {d:"가용 재고를 조회 시점에 계산한다", js:"/조회 시점|now|만료를 반영/.test(String(D.availability||''))"},
         {d:"만료·상태 컬럼에 인덱스가 있다", js:"D.entities.some(e=>e.fields.filter(f=>/expire|status/i.test(f.name)).every(f=>f.index===true))"}],
  ex:"🎯 흔한 실수는 재고 컬럼을 <b>직접 깎는</b> 것입니다. 그러면 예약이 만료됐는지 알 수 없고, 배치가 늦으면 팔 수 있는 물건을 못 팝니다.\n🔧 실제 재고(on_hand)는 그대로 두고 <b>가용 재고를 계산</b>하세요 — `on_hand - 유효한 예약 합계`. 만료 여부를 조회 시점에 판단하므로 배치가 늦어도 정확합니다.\n💡 배치는 <b>정리용</b>이지 정확성의 근거가 아닙니다. '배치가 돌아야 맞는 값' 인 설계는 배치가 멈추는 순간 장애가 됩니다.\n⚠️ 동시 예약은 여전히 경합합니다. 가용 재고 확인과 예약 삽입이 <b>같은 트랜잭션</b>에서 원자적으로 일어나야 초과 판매가 없습니다 — `SELECT ... FOR UPDATE` 나 조건부 INSERT 를 씁니다." },

{ kind:"erd", k:"동적 설문 폼", lv:3,
  q:"관리자가 설문 문항을 <b>직접 추가·삭제</b>합니다. 문항 종류는 단답·객관식·척도이고, 응답은 나중에 <b>집계</b>해야 합니다. 문항이 늘 때마다 컬럼을 추가하지 않아도 되게 설계하세요.",
  src:'{\n  "entities": [\n    { "name": "response", "fields": [\n      { "name": "id", "type": "bigint", "pk": true },\n      { "name": "q1", "type": "text" },\n      { "name": "q2", "type": "text" }\n    ] }\n  ],\n  "relations": []\n}',
  ref:{entities:[{name:"survey",fields:[{name:"id",type:"bigint",pk:true},{name:"title",type:"varchar(200)"}]},
        {name:"question",fields:[{name:"id",type:"bigint",pk:true},{name:"survey_id",type:"bigint",fk:"survey.id",index:true},
          {name:"kind",type:"varchar(20)",note:"text | choice | scale"},{name:"position",type:"int"},{name:"label",type:"varchar(300)"}],
         unique:[["survey_id","position"]]},
        {name:"choice_option",fields:[{name:"id",type:"bigint",pk:true},{name:"question_id",type:"bigint",fk:"question.id",index:true},{name:"label",type:"varchar(100)"}]},
        {name:"answer",fields:[{name:"id",type:"bigint",pk:true},{name:"response_id",type:"bigint",index:true},
          {name:"question_id",type:"bigint",fk:"question.id",index:true},
          {name:"text_value",type:"text",nullable:true},
          {name:"option_id",type:"bigint",fk:"choice_option.id",nullable:true,index:true},
          {name:"number_value",type:"int",nullable:true,note:"척도 응답 — 집계 가능하도록 숫자 컬럼을 따로 둔다"}]}],
       relations:[{from:"survey",to:"question",type:"1:N"},{from:"question",to:"choice_option",type:"1:N"},{from:"question",to:"answer",type:"1:N"}]},
  tests:[{d:"문항별 컬럼(q1, q2)이 사라졌다", js:"!D.entities.some(e=>e.fields.some(f=>/^q\\d+$/i.test(f.name)))"},
         {d:"문항과 응답이 각각 테이블이다", js:"D.entities.some(e=>/question/i.test(e.name)) && D.entities.some(e=>/answer|response/i.test(e.name))"},
         {d:"문항 종류를 구분한다", js:"D.entities.some(e=>/question/i.test(e.name)&&e.fields.some(f=>/kind|type/i.test(f.name)))"},
         {d:"객관식 보기가 별도 테이블이다", js:"D.entities.some(e=>/option|choice/i.test(e.name))"},
         {d:"집계 가능한 숫자 컬럼이 따로 있다", js:"D.entities.some(e=>/answer/i.test(e.name)&&e.fields.some(f=>/number|numeric|value/i.test(f.name)&&/int|numeric|decimal/i.test(String(f.type))))"},
         {d:"문항 순서를 유지한다", js:"D.entities.some(e=>e.fields.some(f=>/position|order|seq/i.test(f.name)))"}],
  ex:"🎯 문항마다 컬럼을 만들면 관리자가 설문을 고칠 때마다 <b>마이그레이션</b>이 필요합니다. 문항을 데이터로 두면 그럴 일이 없습니다.\n⚠️ 다만 모든 응답을 <code>text</code> 한 컬럼에 몰아넣는 순수 EAV 는 <b>집계를 못 하게</b> 만듭니다. '만족도 평균' 을 구하려고 매번 문자열을 캐스팅하면 인덱스도 못 쓰고 잘못된 값에서 터집니다.\n🔧 타입별 컬럼을 나눠 두는 절충이 실용적입니다 — 척도는 정수 컬럼에, 객관식은 보기 테이블 외래키로. 그러면 집계가 그대로 되고 무결성도 지켜집니다.\n💡 문항 순서(position)를 반드시 저장하세요. 화면 순서는 데이터의 일부이고, id 순서에 기대면 문항을 중간에 끼울 수 없습니다." },

{ kind:"erd", k:"연락처와 주소", lv:2,
  q:"회원은 <b>여러 개의 주소</b>(집·회사·배송지)를 가질 수 있고 그중 하나가 <b>기본 배송지</b>입니다. 기본 배송지는 <b>회원당 정확히 하나</b>여야 합니다.",
  src:'{\n  "entities": [\n    { "name": "member", "fields": [\n      { "name": "id", "type": "bigint", "pk": true },\n      { "name": "address", "type": "varchar(300)" },\n      { "name": "address2", "type": "varchar(300)" }\n    ] }\n  ],\n  "relations": []\n}',
  ref:{entities:[{name:"member",fields:[{name:"id",type:"bigint",pk:true},{name:"name",type:"varchar(50)"}]},
        {name:"address",fields:[{name:"id",type:"bigint",pk:true},{name:"member_id",type:"bigint",fk:"member.id",index:true},
          {name:"label",type:"varchar(20)"},{name:"postal_code",type:"varchar(10)"},{name:"line1",type:"varchar(200)"},
          {name:"line2",type:"varchar(200)",nullable:true},{name:"is_default",type:"boolean"}],
         partialIndex:"UNIQUE(member_id) WHERE is_default = true"}],
       relations:[{from:"member",to:"address",type:"1:N"}]},
  tests:[{d:"주소가 별도 테이블로 분리됐다", js:"D.entities.length===2 && !D.entities.find(e=>/member/i.test(e.name)).fields.some(f=>/address/i.test(f.name))"},
         {d:"주소가 여러 개 붙을 수 있다", js:"D.relations.some(r=>r.type==='1:N')"},
         {d:"기본 여부를 표시하는 컬럼이 있다", js:"D.entities.some(e=>e.fields.some(f=>/default|primary|main/i.test(f.name)))"},
         {d:"회원당 기본 주소가 하나임을 DB 가 보장한다", js:"D.entities.some(e=>/member_id/i.test(String(e.partialIndex||''))&&/default|primary/i.test(String(e.partialIndex||''))) || D.entities.some(e=>(e.unique||[]).some(u=>u.length>=2&&u.some(c=>/default|primary/i.test(c))))"},
         {d:"우편번호와 상세 주소가 나뉘어 있다", js:"D.entities.some(e=>e.fields.some(f=>/postal|zip/i.test(f.name)) && e.fields.some(f=>/line|street|detail/i.test(f.name)))"},
         {d:"외래키에 인덱스가 있다", js:"D.entities.every(e=>e.fields.filter(f=>f.fk).every(f=>f.index===true))"}],
  ex:"🎯 <code>address</code>, <code>address2</code> 처럼 컬럼을 늘리면 세 번째 주소가 필요할 때 또 늘려야 합니다. 개수가 정해지지 않은 것은 <b>행</b>입니다.\n🔧 '기본 배송지는 하나' 를 애플리케이션 코드로만 지키면 동시 요청에서 두 개가 됩니다. <b>부분 인덱스</b> <code>UNIQUE(member_id) WHERE is_default</code> 로 DB 가 보장하게 하세요.\n💡 주소를 한 문자열로 뭉치면 <b>우편번호로 배송비를 계산</b>하거나 지역별 통계를 낼 수 없습니다. 나중에 쪼개는 마이그레이션은 매우 어렵습니다.\n⚠️ 주소 형식은 나라마다 다릅니다. 국내만이면 우편번호+상세로 충분하지만, 해외가 있으면 국가 코드와 자유 형식 줄을 함께 두는 편이 안전합니다." },

/* ─────────── API ─────────── */
{ kind:"api", k:"긴 작업을 비동기로", lv:3,
  q:"보고서 생성이 <b>몇 분</b> 걸립니다. 요청이 타임아웃되지 않도록 비동기로 바꾸고, 클라이언트가 <b>진행 상태와 결과</b>를 확인할 수 있게 설계하세요. 같은 요청을 두 번 보내도 작업이 두 개 생기면 안 됩니다.",
  src:'{\n  "endpoints": [\n    { "method": "POST", "path": "/reports", "status": 200, "desc": "보고서 생성 (동기)" }\n  ]\n}',
  ref:{endpoints:[{method:"POST",path:"/reports",status:202,errors:[400,409],
      headers:[{name:"Idempotency-Key",required:true}],
      responseHeaders:[{name:"Location",desc:"/jobs/{id} — 상태를 확인할 곳"}],
      response:{job_id:"string",status:"queued"},
      note:"즉시 202 로 접수하고 작업 id 를 준다",desc:"보고서 생성 요청"},
    {method:"GET",path:"/jobs/{id}",status:200,errors:[404],
      response:{status:"queued|running|succeeded|failed",progress:"0~100",result_url:"완료 시에만",error:"실패 시에만"},
      note:"폴링 간격을 Retry-After 로 안내한다",desc:"작업 상태 조회"},
    {method:"DELETE",path:"/jobs/{id}",status:204,errors:[404,409],desc:"작업 취소"}]},
  tests:[{d:"접수는 202 로 응답한다", js:"D.endpoints.some(e=>e.status===202)"},
         {d:"상태를 확인할 위치를 알려 준다", js:"D.endpoints.some(e=>(e.responseHeaders||[]).some(h=>/location/i.test(h.name)))"},
         {d:"작업 상태 조회 엔드포인트가 있다", js:"D.endpoints.some(e=>e.method==='GET'&&/job|task/i.test(String(e.path)))"},
         {d:"상태 값에 성공과 실패가 모두 있다", js:"/succeeded|completed|done/i.test(JSON.stringify(D.endpoints.map(e=>e.response||{}))) && /failed|error/i.test(JSON.stringify(D.endpoints.map(e=>e.response||{})))"},
         {d:"결과를 받을 위치가 응답에 있다", js:"/result|download|url/i.test(JSON.stringify(D.endpoints.map(e=>e.response||{})))"},
         {d:"중복 요청을 막는 멱등 키가 있다", js:"D.endpoints.some(e=>(e.headers||[]).some(h=>/idempot/i.test(h.name)))"},
         {d:"취소할 수 있다", js:"D.endpoints.some(e=>e.method==='DELETE')"}],
  ex:"🎯 몇 분 걸리는 작업을 동기로 두면 <b>프록시·로드밸런서가 먼저 끊습니다</b>. 대개 30~60초에서 끊기고, 클라이언트는 성공했는지 알 수 없습니다.\n🔧 <b>202 Accepted</b> 로 즉시 접수하고 작업 id 를 주면, 클라이언트는 상태를 물어보며 기다릴 수 있습니다. <code>Location</code> 헤더로 어디를 봐야 하는지 알려 주는 것이 규약입니다.\n💡 상태에는 <b>실패</b>도 있어야 합니다. '완료 아니면 진행 중' 만 있으면 실패한 작업을 영원히 폴링합니다. 진행률과 오류 메시지도 함께 주세요.\n⚠️ 사용자가 버튼을 두 번 누르면 작업이 두 개 생깁니다 — 멱등 키로 같은 작업 id 를 돌려주세요. 그리고 취소가 없으면 잘못 시작한 무거운 작업을 멈출 방법이 없습니다." },

{ kind:"api", k:"조건부 GET 과 캐시", lv:2,
  q:"자주 바뀌지 않는 프로필 조회에 <b>캐시</b>를 적용하세요. 내용이 안 바뀌었으면 <b>본문을 보내지 않고</b> 끝내야 하고, 비공개 데이터가 <b>공유 캐시에 남지 않아야</b> 합니다.",
  src:'{\n  "endpoints": [\n    { "method": "GET", "path": "/profiles/{id}", "status": 200, "desc": "프로필 조회" }\n  ]\n}',
  ref:{endpoints:[{method:"GET",path:"/profiles/{id}",status:200,errors:[401,404],
    requestHeaders:[{name:"If-None-Match",required:false,desc:"이전 응답의 ETag"}],
    responseHeaders:[{name:"ETag",desc:"본문의 버전"},
                     {name:"Cache-Control",desc:"private, max-age=60"},
                     {name:"Vary",desc:"Authorization — 사용자마다 다른 응답"}],
    notModifiedStatus:304,
    note:"본인 데이터라 private — 공유 캐시(CDN·프록시)에 저장되면 안 된다",desc:"프로필 조회"}]},
  tests:[{d:"ETag 를 내려준다", js:"D.endpoints.some(e=>(e.responseHeaders||[]).some(h=>/etag/i.test(h.name)))"},
         {d:"If-None-Match 를 받는다", js:"D.endpoints.some(e=>(e.requestHeaders||[]).some(h=>/if-none-match|if-modified/i.test(h.name)))"},
         {d:"바뀌지 않았으면 304 를 낸다", js:"D.endpoints.some(e=>e.notModifiedStatus===304||(e.errors||[]).indexOf(304)>=0)"},
         {d:"Cache-Control 이 private 이다", js:"/private/i.test(JSON.stringify(D.endpoints.map(e=>e.responseHeaders||[])))"},
         {d:"Vary 로 응답이 사용자마다 다름을 알린다", js:"D.endpoints.some(e=>(e.responseHeaders||[]).some(h=>/vary/i.test(h.name)))"}],
  ex:"🎯 <b>조건부 GET</b> 은 '바뀌었으면 주고 아니면 304' 입니다. 본문을 안 보내므로 대역폭이 절약되고, 클라이언트는 캐시된 것을 그대로 씁니다.\n⚠️ 인증이 필요한 응답에 <code>Cache-Control: public</code> 을 두면 <b>CDN 이 남의 프로필을 다른 사람에게 보여 줍니다</b>. 실제로 벌어진 사고 유형이고, <code>private</code> 이 그걸 막습니다.\n🔧 <code>Vary: Authorization</code> 은 '이 응답은 인증 헤더에 따라 다르다' 는 선언입니다. 없으면 캐시가 첫 사용자의 응답을 모두에게 돌려줄 수 있습니다.\n💡 ETag 는 본문의 해시로 만드는 것이 간단하지만, 매번 본문을 만들어야 하므로 계산 비용은 그대로입니다. 갱신 시각이나 버전 컬럼으로 만들면 <b>조회 자체를 건너뛸</b> 수 있습니다." },

{ kind:"api", k:"CORS 와 브라우저 요청", lv:2,
  q:"프론트엔드가 <code>https://app.example.com</code> 에서 API 서버 <code>https://api.example.com</code> 를 호출합니다. 쿠키 인증을 쓰고, <code>Authorization</code>·<code>Content-Type</code> 헤더를 보냅니다. CORS 정책을 설계하세요.",
  src:'{\n  "endpoints": [\n    { "method": "GET", "path": "/orders", "status": 200, "desc": "주문 목록" }\n  ]\n}',
  ref:{endpoints:[{method:"OPTIONS",path:"/*",status:204,errors:[],
      responseHeaders:[{name:"Access-Control-Allow-Origin",desc:"https://app.example.com (와일드카드 아님)"},
                       {name:"Access-Control-Allow-Methods",desc:"GET, POST, PATCH, DELETE"},
                       {name:"Access-Control-Allow-Headers",desc:"Authorization, Content-Type"},
                       {name:"Access-Control-Allow-Credentials",desc:"true"},
                       {name:"Access-Control-Max-Age",desc:"600 — 프리플라이트 결과를 캐시"}],
      note:"자격 증명을 쓰면 Allow-Origin 에 * 를 쓸 수 없다",desc:"프리플라이트"},
    {method:"GET",path:"/orders",status:200,errors:[401],
      responseHeaders:[{name:"Access-Control-Allow-Origin",desc:"https://app.example.com"},
                       {name:"Vary",desc:"Origin"}],desc:"주문 목록"}]},
  tests:[{d:"프리플라이트(OPTIONS)를 처리한다", js:"D.endpoints.some(e=>e.method==='OPTIONS')"},
         {d:"허용 출처를 구체적으로 지정한다", js:"/https:\\/\\//.test(JSON.stringify(D.endpoints.map(e=>e.responseHeaders||[]))) && !/Allow-Origin[^,}]*\\*/.test(JSON.stringify(D.endpoints.map(e=>e.responseHeaders||[])))"},
         {d:"허용 헤더를 명시한다", js:"/Allow-Headers/i.test(JSON.stringify(D.endpoints.map(e=>e.responseHeaders||[])))"},
         {d:"자격 증명 허용을 명시한다", js:"/Allow-Credentials/i.test(JSON.stringify(D.endpoints.map(e=>e.responseHeaders||[])))"},
         {d:"프리플라이트 결과를 캐시한다", js:"/Max-Age/i.test(JSON.stringify(D.endpoints.map(e=>e.responseHeaders||[])))"},
         {d:"Vary: Origin 을 둔다", js:"D.endpoints.some(e=>(e.responseHeaders||[]).some(h=>/^vary$/i.test(h.name)))"}],
  ex:"🎯 CORS 는 <b>서버가 아니라 브라우저가 지키는 규칙</b>입니다. 서버는 '누구에게 허용하는지' 를 헤더로 선언할 뿐이고, 브라우저가 그걸 보고 응답을 스크립트에 넘길지 말지 정합니다.\n⚠️ <code>Allow-Credentials: true</code> 와 <code>Allow-Origin: *</code> 는 <b>함께 쓸 수 없습니다</b>. 브라우저가 거부하고, 허용된다면 아무 사이트나 쿠키를 실은 요청을 보낼 수 있게 되므로 당연한 제약입니다.\n💡 <code>Authorization</code> 같은 헤더나 <code>PATCH</code> 메서드를 쓰면 브라우저가 먼저 <b>프리플라이트(OPTIONS)</b>를 보냅니다. 이걸 처리하지 않으면 본 요청이 아예 나가지 않습니다 — <code>Max-Age</code> 로 결과를 캐시하면 왕복이 줄어듭니다.\n🔧 출처를 동적으로 반사할 때는 반드시 <b>허용 목록과 대조</b>하고 <code>Vary: Origin</code> 을 두세요. 그냥 반사하면 사실상 전면 허용이고, Vary 가 없으면 캐시가 엉뚱한 출처의 응답을 재사용합니다." },

{ kind:"api", k:"필드 선택과 응답 크기", lv:2,
  q:"모바일에서 목록을 부를 때 <b>필요 없는 필드까지</b> 내려와 느립니다. 클라이언트가 원하는 필드만 고를 수 있게 하되, <b>임의의 필드 이름</b>을 그대로 받아들이면 안 됩니다.",
  src:'{\n  "endpoints": [\n    { "method": "GET", "path": "/products", "status": 200, "desc": "상품 목록" }\n  ]\n}',
  ref:{endpoints:[{method:"GET",path:"/products",status:200,errors:[400],
    params:[{name:"fields",required:false,enum:["id","name","price","thumbnail","description"],
             default:"id,name,price",desc:"쉼표로 구분 — 허용 목록에 없으면 400"},
            {name:"limit",required:false,max:50,default:20}],
    response:{items:"선택된 필드만 담은 객체 배열"},
    note:"id 는 항상 포함한다 — 클라이언트가 항목을 구분할 수 없으면 목록이 쓸모없다",
    desc:"상품 목록"}]},
  tests:[{d:"필드 선택 파라미터가 있다", js:"D.endpoints.some(e=>(e.params||[]).some(p=>/field|select|include/i.test(p.name)))"},
         {d:"선택 가능한 필드가 허용 목록으로 정해져 있다", js:"D.endpoints.some(e=>(e.params||[]).some(p=>/field|select/i.test(p.name)&&Array.isArray(p.enum)&&p.enum.length>=3))"},
         {d:"기본값이 있다", js:"D.endpoints.some(e=>(e.params||[]).some(p=>/field|select/i.test(p.name)&&p.default!=null))"},
         {d:"허용 목록 밖이면 400 이다", js:"D.endpoints.every(e=>(e.errors||[]).indexOf(400)>=0)"},
         {d:"항상 포함되는 식별자를 정했다", js:"/id 는 항상|always include|항상 포함/i.test(String(D.endpoints.map(e=>e.note||'').join(' ')))"}],
  ex:"🎯 응답 크기는 모바일에서 <b>체감 속도를 가장 크게</b> 좌우합니다. 목록에 긴 설명과 큰 이미지 URL 이 다 들어가면 파싱 비용까지 함께 늘어납니다.\n⚠️ 필드 이름을 그대로 받아 객체에서 꺼내면 <code>fields=passwordHash</code> 로 <b>노출되면 안 되는 값</b>이 나갑니다. 허용 목록과 대조하는 것이 유일한 안전한 방법입니다.\n💡 <b>기본값</b>을 정해 두면 파라미터를 안 보내는 클라이언트도 가벼운 응답을 받습니다. 그리고 <code>id</code> 는 항상 넣으세요 — 항목을 구분할 수 없는 목록은 쓸모가 없습니다.\n🔧 이 요구가 계속 늘어나면 GraphQL 같은 질의 언어를 검토할 시점입니다. 다만 그쪽은 비용 제어(깊이·복잡도 제한)라는 새로운 숙제를 가져옵니다." },

{ kind:"api", k:"멀티 테넌트 격리", lv:3,
  q:"여러 회사가 같은 서비스를 씁니다. <b>다른 회사의 데이터가 절대 보이면 안 됩니다</b>. 테넌트를 어떻게 식별하고, 실수로 조건을 빠뜨려도 새지 않도록 어떻게 막을지 설계하세요.",
  src:'{\n  "endpoints": [\n    { "method": "GET", "path": "/orders?tenant_id=123", "status": 200, "desc": "주문 목록" }\n  ]\n}',
  ref:{endpoints:[{method:"GET",path:"/orders",status:200,errors:[401,403],
      auth:"Bearer — 토큰의 tenant 클레임에서 읽는다",
      note:"테넌트 id 를 요청 파라미터로 받지 않는다. 받으면 남의 것을 넣어 볼 수 있다",
      defense:["토큰에서만 테넌트를 읽는다","DB 행 수준 보안(RLS)으로 조건 누락을 막는다","테넌트 불일치는 404 로 응답해 존재를 흘리지 않는다"],
      desc:"주문 목록"},
    {method:"GET",path:"/orders/{id}",status:200,errors:[401,403,404],
      note:"다른 테넌트의 주문 id 를 넣으면 403 이 아니라 404 — 있다는 사실도 알리지 않는다",desc:"주문 단건"}]},
  tests:[{d:"테넌트를 요청 파라미터로 받지 않는다", js:"D.endpoints.every(e=>!/tenant_id=|[?&]tenant/i.test(String(e.path)))"},
         {d:"인증 토큰에서 테넌트를 읽는다", js:"/토큰|token|claim/i.test(JSON.stringify(D.endpoints.map(e=>[e.auth,e.note])))"},
         {d:"조건 누락을 DB 계층에서도 막는다", js:"/RLS|행 수준|row level/i.test(JSON.stringify(D.endpoints.map(e=>e.defense||[])))"},
         {d:"남의 리소스는 404 로 응답한다", js:"/404/.test(JSON.stringify(D.endpoints.map(e=>[e.note,e.defense])))"},
         {d:"인증·인가 오류가 정의돼 있다", js:"D.endpoints.every(e=>(e.errors||[]).indexOf(401)>=0)"}],
  ex:"🎯 테넌트 id 를 <b>요청에서 받으면</b> 그 순간 보안이 무너집니다. 사용자가 값을 바꿔 남의 데이터를 요청할 수 있고, 서버가 매번 '이 사람이 이 테넌트 소속인가' 를 검사해야 합니다 — 한 곳만 빠뜨려도 유출입니다.\n🔧 테넌트는 <b>인증된 신원에서만</b> 나와야 합니다. 토큰 클레임에서 읽으면 위조할 수 없고 검사할 곳도 한 곳뿐입니다.\n⚠️ 그래도 사람은 <code>WHERE tenant_id = ?</code> 를 빠뜨립니다. <b>행 수준 보안(RLS)</b> 처럼 DB 가 강제하는 계층을 하나 더 두면, 쿼리가 조건을 잊어도 데이터가 새지 않습니다.\n💡 남의 리소스 id 로 접근했을 때 403 을 주면 '<b>그 id 는 존재한다</b>' 를 알려 주는 셈입니다. 멀티 테넌트에서는 404 로 통일하는 편이 안전합니다." },

{ kind:"api", k:"인가 코드 흐름", lv:3,
  q:"서드파티 앱이 사용자 대신 우리 API 를 부를 수 있게 <b>OAuth 인가 코드</b> 흐름을 설계하세요. 비밀을 보관할 수 없는 <b>모바일·SPA</b> 도 지원해야 하고, 인가 코드가 가로채여도 안전해야 합니다.",
  src:'{\n  "endpoints": [\n    { "method": "POST", "path": "/oauth/token", "status": 200, "desc": "토큰 발급" }\n  ]\n}',
  ref:{endpoints:[{method:"GET",path:"/oauth/authorize",status:302,errors:[400],
      params:[{name:"client_id",required:true},{name:"redirect_uri",required:true,desc:"사전 등록된 것과 정확히 일치해야 한다"},
              {name:"state",required:true,desc:"CSRF 방지 — 콜백에서 그대로 돌려준다"},
              {name:"code_challenge",required:true,desc:"PKCE — code_verifier 의 SHA-256"},
              {name:"code_challenge_method",required:true,desc:"S256"},
              {name:"scope",required:false}],
      note:"동의 화면을 거쳐 redirect_uri 로 code 를 돌려보낸다",desc:"인가 요청"},
    {method:"POST",path:"/oauth/token",status:200,errors:[400,401],
      request:{grant_type:"authorization_code",code:"string",code_verifier:"PKCE 원본",redirect_uri:"string"},
      response:{access_token:"string",expires_in:3600,refresh_token:"string",token_type:"Bearer"},
      note:"code 는 1회용이고 짧은 수명이다 — 재사용되면 발급된 토큰까지 폐기한다",desc:"토큰 발급"},
    {method:"POST",path:"/oauth/revoke",status:200,errors:[400],desc:"토큰 폐기"}]},
  tests:[{d:"인가 요청과 토큰 발급이 분리돼 있다", js:"D.endpoints.some(e=>/authorize/i.test(e.path)) && D.endpoints.some(e=>/token/i.test(e.path))"},
         {d:"PKCE 를 쓴다", js:"/code_challenge/i.test(JSON.stringify(D.endpoints)) && /code_verifier/i.test(JSON.stringify(D.endpoints))"},
         {d:"state 로 CSRF 를 막는다", js:"D.endpoints.some(e=>(e.params||[]).some(p=>/^state$/i.test(p.name)&&p.required===true))"},
         {d:"redirect_uri 를 사전 등록과 대조한다", js:"/사전 등록|등록된|정확히 일치|exact/i.test(JSON.stringify(D.endpoints.map(e=>e.params||[])))"},
         {d:"액세스 토큰에 만료가 있다", js:"/expires_in|expire/i.test(JSON.stringify(D.endpoints.map(e=>e.response||{})))"},
         {d:"인가 코드가 1회용임을 명시했다", js:"/1회용|한 번만|one.?time|재사용/i.test(String(D.endpoints.map(e=>e.note||'').join(' ')))"},
         {d:"토큰을 폐기할 수 있다", js:"D.endpoints.some(e=>/revoke|logout/i.test(e.path))"}],
  ex:"🎯 인가 코드 흐름이 토큰을 <b>바로 주지 않는</b> 이유는, 코드가 브라우저 주소창·로그·리퍼러에 남기 때문입니다. 코드는 그것만으로는 쓸 수 없고 서버 간 교환이 한 번 더 필요합니다.\n🔧 그런데 모바일·SPA 는 <b>클라이언트 시크릿을 숨길 수 없습니다</b>. 그래서 <b>PKCE</b> 가 있습니다 — 요청 때 <code>code_challenge</code>(검증값의 해시)를 보내고 교환 때 원본을 제출하면, 코드를 가로챈 쪽은 원본을 모르므로 쓸 수 없습니다. 이제 PKCE 는 공개 클라이언트뿐 아니라 <b>모든 클라이언트에 권장</b>됩니다.\n⚠️ <code>redirect_uri</code> 를 느슨하게(부분 일치·와일드카드) 검증하면 공격자 URL 로 코드가 배달됩니다. <b>사전 등록된 값과 정확히</b> 비교해야 합니다.\n💡 <code>state</code> 는 CSRF 방지용이고 PKCE 와 목적이 다릅니다 — 둘 다 필요합니다. 그리고 코드는 1회용이어야 하며, 재사용이 감지되면 이미 발급된 토큰까지 폐기하는 것이 권장 동작입니다." },

{ kind:"api", k:"목록 응답의 형태", lv:1,
  q:"목록 API 의 응답 형태를 정하세요. 배열을 그대로 돌려주면 나중에 <b>메타데이터를 붙일 자리</b>가 없습니다. 빈 목록과 오류를 구분할 수 있어야 하고, 단건 조회와 형태가 일관되어야 합니다.",
  src:'{\n  "endpoints": [\n    { "method": "GET", "path": "/posts", "status": 200, "desc": "글 목록 — 배열을 그대로 반환" }\n  ]\n}',
  ref:{endpoints:[{method:"GET",path:"/posts",status:200,errors:[400],
      response:{items:"[]",nextCursor:"string|null",total:"number|null"},
      note:"최상위는 객체다 — 배열로 돌려주면 페이지 정보를 붙일 자리가 없다. 결과가 없으면 items 는 빈 배열이고 200 이다",
      desc:"글 목록"},
    {method:"GET",path:"/posts/{id}",status:200,errors:[404],
      response:{id:"string",title:"string"},
      note:"단건은 리소스를 그대로 — 불필요하게 감싸지 않는다",desc:"글 단건"}]},
  tests:[{d:"목록 응답의 최상위가 객체다", js:"D.endpoints.some(e=>/^\\/posts$/.test(String(e.path))&&e.response&&!Array.isArray(e.response))"},
         {d:"항목이 별도 키에 담긴다", js:"D.endpoints.some(e=>/items|data|results/i.test(Object.keys((D.endpoints.find(x=>/^\\/posts$/.test(String(x.path)))||{}).response||{}).join(',')))"},
         {d:"페이지 정보를 담을 자리가 있다", js:"/cursor|next|total|page/i.test(JSON.stringify((D.endpoints.find(e=>/^\\/posts$/.test(String(e.path)))||{}).response||{}))"},
         {d:"빈 결과도 200 임을 밝혔다", js:"/빈 배열|empty|200/.test(String(D.endpoints.map(e=>e.note||'').join(' ')))"},
         {d:"단건 조회는 404 를 낼 수 있다", js:"D.endpoints.some(e=>/\\{/.test(String(e.path))&&(e.errors||[]).indexOf(404)>=0)"}],
  ex:"🎯 목록을 <b>배열 그대로</b> 돌려주면 나중에 페이지 커서나 전체 건수를 붙일 자리가 없습니다. 그때 형태를 바꾸면 <b>모든 클라이언트가 깨집니다</b> — 처음부터 객체로 감싸 두는 편이 훨씬 쌉니다.\n💡 <b>결과가 없는 것은 오류가 아닙니다.</b> 조건에 맞는 글이 없으면 빈 배열과 200 이지 404 가 아닙니다. 404 는 '이 엔드포인트/리소스가 없다' 는 뜻입니다.\n⚠️ 최상위 배열은 오래된 JSON 하이재킹 취약점의 소재이기도 했습니다. 지금은 대부분 막혔지만, 객체로 감싸는 관행이 남은 이유 중 하나입니다.\n🔧 반대로 <b>단건까지 불필요하게 감쌀</b> 필요는 없습니다. 일관성은 '모두 감싸기' 가 아니라 '같은 상황에서 같은 형태' 입니다." },

/* ─────────── CLOUD ─────────── */
{ kind:"cloud", k:"기능 플래그", lv:2,
  q:"새 기능을 <b>배포와 분리해</b> 켜고 끄고 싶습니다. 일부 사용자에게만 열 수 있어야 하고, 문제가 생기면 <b>재배포 없이</b> 끌 수 있어야 하며, 플래그 서비스가 죽어도 앱이 멈추면 안 됩니다.",
  src:'{\n  "components": [\n    { "name": "app", "icon": "🖥" },\n    { "name": "db", "icon": "🗄" }\n  ],\n  "connections": []\n}',
  ref:{components:[{name:"app",icon:"🖥",flagCache:"메모리 캐시 + 기본값",fallback:"조회 실패 시 코드에 박힌 기본값(off)을 쓴다"},
        {name:"flag-service",icon:"🚩",targeting:"사용자 id 해시 기반 비율 배포",audit:true},
        {name:"db",icon:"🗄"}],
       connections:[{from:"app",to:"flag-service",via:"주기적 갱신 (스트리밍/폴링)"},{from:"app",to:"db"}],
       cleanup:"켜진 지 오래된 플래그는 코드에서 제거한다 — 플래그가 쌓이면 경로 조합이 폭발한다"},
  tests:[{d:"플래그 서비스가 분리돼 있다", js:"D.components.some(c=>/flag|feature|toggle/i.test(c.name))"},
         {d:"일부 사용자에게만 열 수 있다", js:"/비율|percent|해시|targeting|세그먼트/i.test(JSON.stringify(D.components))"},
         {d:"조회 실패 시 기본값으로 동작한다", js:"D.components.some(c=>/기본값|default|fallback/i.test(String(c.fallback||'')))"},
         {d:"앱이 플래그를 캐시한다", js:"D.components.some(c=>/캐시|cache/i.test(String(c.flagCache||'')))"},
         {d:"플래그 변경 이력이 남는다", js:"/audit|이력|기록/i.test(JSON.stringify(D.components))"},
         {d:"오래된 플래그를 정리하는 계획이 있다", js:"/제거|정리|cleanup|삭제/i.test(JSON.stringify(D))"}],
  ex:"🎯 기능 플래그의 핵심 가치는 <b>배포와 공개를 분리</b>하는 것입니다. 코드는 이미 나가 있고 켜는 순간이 공개이므로, 문제가 생기면 롤백 대신 <b>끄기만</b> 하면 됩니다 — 훨씬 빠르고 안전합니다.\n⚠️ 플래그 서비스가 <b>새로운 단일 장애점</b>이 되면 안 됩니다. 조회 실패 시 코드에 박힌 기본값으로 동작하고, 값은 메모리에 캐시해 매 요청마다 외부를 부르지 않아야 합니다.\n💡 비율 배포는 <b>사용자 id 해시</b>로 정해야 합니다. 요청마다 난수를 쓰면 같은 사용자가 새로고침할 때마다 다른 화면을 봅니다.\n🔧 가장 흔한 실패는 <b>플래그를 안 지우는 것</b>입니다. 플래그 10개면 이론상 경로가 1024가지이고, 테스트할 수 없는 코드가 됩니다. 켜고 안정되면 제거하는 것까지가 한 사이클입니다." },

{ kind:"cloud", k:"무중단 스키마 변경", lv:3,
  q:"컬럼 이름을 <code>name</code> 에서 <code>full_name</code> 으로 바꿔야 합니다. 배포 중에는 <b>옛 코드와 새 코드가 동시에</b> 돌아갑니다. 서비스를 멈추지 않고 바꾸는 <b>단계</b>를 설계하세요.",
  src:'{\n  "components": [\n    { "name": "app", "icon": "🖥" },\n    { "name": "db", "icon": "🗄" }\n  ],\n  "connections": []\n}',
  ref:{components:[{name:"app",icon:"🖥",scale:3},{name:"db",icon:"🗄"},
        {name:"migration",icon:"🪜",steps:[
          {n:1,do:"full_name 컬럼 추가 (nullable)",safe:"옛 코드에 영향 없음"},
          {n:2,do:"양쪽에 쓰는 코드 배포",safe:"옛 코드와 공존 가능"},
          {n:3,do:"기존 행 백필",safe:"배치로 나눠 실행"},
          {n:4,do:"새 컬럼만 읽는 코드 배포",safe:"롤백해도 양쪽에 쓰던 코드로 돌아감"},
          {n:5,do:"name 컬럼 삭제",safe:"롤백 창이 지난 뒤에만"}]}],
       connections:[{from:"app",to:"db"}]},
  tests:[{d:"단계가 4개 이상이다", js:"D.components.some(c=>Array.isArray(c.steps)&&c.steps.length>=4)"},
         {d:"컬럼 추가가 삭제보다 먼저다", js:"(function(){var s=D.components.find(c=>Array.isArray(c.steps)).steps;var a=s.findIndex(x=>/추가|add/i.test(x.do));var d=s.findIndex(x=>/삭제|drop/i.test(x.do));return a>=0&&d>=0&&a<d;})()"},
         {d:"양쪽에 쓰는 단계가 있다", js:"D.components.some(c=>(c.steps||[]).some(s=>/양쪽|둘 다|both|dual/i.test(s.do)))"},
         {d:"기존 데이터 백필 단계가 있다", js:"D.components.some(c=>(c.steps||[]).some(s=>/백필|backfill|기존 행/i.test(s.do)))"},
         {d:"삭제는 롤백 창이 지난 뒤다", js:"D.components.some(c=>(c.steps||[]).some(s=>/삭제|drop/i.test(s.do)&&/롤백|rollback/i.test(String(s.safe||''))))"},
         {d:"각 단계가 안전한 이유를 적었다", js:"D.components.some(c=>(c.steps||[]).every(s=>!!String(s.safe||'').trim()))"}],
  ex:"🎯 배포는 순간이 아닙니다. 롤링 배포 중에는 <b>옛 코드와 새 코드가 몇 분간 함께</b> 돌아가므로, 스키마는 그 사이 <b>양쪽 모두와 호환</b>돼야 합니다.\n🔧 그래서 이름 변경은 한 번에 하지 않습니다 — 추가 → 양쪽 쓰기 → 백필 → 새 것만 읽기 → 삭제. 이 <b>확장-축소</b> 절차의 각 단계는 되돌릴 수 있습니다.\n⚠️ <code>ALTER TABLE ... RENAME</code> 한 줄이 가장 위험합니다. 실행되는 순간 옛 코드가 전부 깨지고, 롤백해도 이미 늦습니다.\n💡 백필은 <b>배치로 나눠</b> 돌리세요. 수천만 행을 한 트랜잭션에서 UPDATE 하면 락과 복제 지연이 폭발합니다.\n📈 삭제는 서두를 이유가 없습니다. 컬럼 하나 남아 있는 비용보다 롤백 불가능한 상태의 위험이 훨씬 큽니다." },

{ kind:"cloud", k:"로그 수집 파이프라인", lv:2,
  q:"여러 서비스의 로그를 한곳에서 검색해야 합니다. 로그 폭주가 <b>애플리케이션을 느리게 하면 안 되고</b>, 저장 비용이 무한히 늘지 않아야 하며, 민감정보가 그대로 쌓이면 안 됩니다.",
  src:'{\n  "components": [\n    { "name": "app", "icon": "🖥" },\n    { "name": "logs", "icon": "📜" }\n  ],\n  "connections": []\n}',
  ref:{components:[{name:"app",icon:"🖥",logging:"구조화 JSON · 표준 출력 · 비동기 버퍼",note:"로그 전송 실패가 요청을 막지 않는다"},
        {name:"agent",icon:"🚚",note:"파일/스트림을 읽어 전달 — 앱은 전송을 신경 쓰지 않는다",sampling:"DEBUG 는 1% 표본"},
        {name:"pipeline",icon:"🧹",redaction:["password","token","ssn","card"],note:"수집 단계에서 마스킹한다"},
        {name:"store",icon:"🔎",retention:[{tier:"검색 가능",days:14},{tier:"아카이브",days:365}]}],
       connections:[{from:"app",to:"agent"},{from:"agent",to:"pipeline"},{from:"pipeline",to:"store"}]},
  tests:[{d:"로그가 구조화돼 있다", js:"/json|구조화|structured/i.test(JSON.stringify(D.components))"},
         {d:"앱이 전송을 직접 책임지지 않는다", js:"D.components.some(c=>/agent|collector|forwarder|수집/i.test(c.name))"},
         {d:"로그 전송 실패가 요청을 막지 않는다", js:"/비동기|막지 않|async|non.?block/i.test(JSON.stringify(D.components))"},
         {d:"민감정보 마스킹 대상을 정했다", js:"D.components.some(c=>Array.isArray(c.redaction)&&c.redaction.length>=3)"},
         {d:"보관 계층과 기간이 정해져 있다", js:"D.components.some(c=>Array.isArray(c.retention)&&c.retention.length>=2)"},
         {d:"폭주 대비 표본 추출이 있다", js:"/sampling|표본|샘플/i.test(JSON.stringify(D.components))"}],
  ex:"🎯 로그 전송을 <b>애플리케이션이 동기로</b> 하면, 로그 수집기가 느려질 때 서비스가 함께 느려집니다. 앱은 표준 출력에 쓰기만 하고 <b>수집은 에이전트</b>가 하는 구조가 안전합니다.\n💡 구조화(JSON)하지 않으면 나중에 파싱 규칙을 계속 고쳐야 합니다. 처음부터 필드로 쓰면 검색·집계가 그대로 됩니다.\n⚠️ <b>요청 본문을 통째로 로깅하면</b> 비밀번호와 카드번호가 그대로 쌓입니다. 수집 단계에서 마스킹하고, 마스킹 대상을 목록으로 관리하세요 — 로그는 접근 권한이 넓어 유출 경로가 됩니다.\n🔧 비용은 <b>보관 기간</b>이 결정합니다. 최근 것만 검색 가능한 계층에 두고 나머지는 값싼 아카이브로 내리세요. 그리고 DEBUG 로그는 표본만 남겨야 폭주 때 비용이 터지지 않습니다." },

{ kind:"cloud", k:"서버리스의 콜드 스타트", lv:3,
  q:"함수형(서버리스)으로 API 를 운영하는데 <b>가끔 응답이 몇 초</b> 걸립니다. 원인을 줄이도록 설계하고, DB 커넥션이 <b>인스턴스 수만큼 늘어나는</b> 문제도 다루세요.",
  src:'{\n  "components": [\n    { "name": "function", "icon": "λ" },\n    { "name": "db", "icon": "🗄" }\n  ],\n  "connections": []\n}',
  ref:{components:[{name:"function",icon:"λ",initOutsideHandler:"커넥션·클라이언트는 핸들러 밖에서 만든다",
          packageSize:"의존성 최소화 — 초기화 시간이 곧 콜드 스타트",provisionedConcurrency:"피크 시간대만"},
        {name:"proxy",icon:"🔌",note:"커넥션 풀러 — 함수 인스턴스 수와 무관하게 DB 커넥션을 제한한다"},
        {name:"db",icon:"🗄",maxConnections:200}],
       connections:[{from:"function",to:"proxy"},{from:"proxy",to:"db"}]},
  tests:[{d:"핸들러 밖 초기화를 명시했다", js:"/핸들러 밖|밖에서|outside handler|재사용/i.test(JSON.stringify(D.components))"},
         {d:"패키지 크기·초기화 비용을 줄인다", js:"/의존성|package|번들|초기화/i.test(JSON.stringify(D.components))"},
         {d:"예열(프로비저닝) 수단을 검토했다", js:"/provisioned|예열|warm/i.test(JSON.stringify(D.components))"},
         {d:"커넥션 풀러를 둔다", js:"D.components.some(c=>/proxy|pooler|풀러/i.test(c.name))"},
         {d:"함수가 DB 로 직접 가지 않는다", js:"!D.connections.some(e=>/function|λ/i.test(String(e.from))&&/^db$/i.test(String(e.to)))"},
         {d:"DB 커넥션 상한을 알고 있다", js:"D.components.some(c=>/db/i.test(c.name)&&typeof c.maxConnections==='number')"}],
  ex:"🎯 콜드 스타트는 <b>새 인스턴스를 처음 만들 때</b> 나는 지연입니다. 런타임 기동 + 패키지 로드 + 초기화가 모두 첫 요청에 얹힙니다.\n🔧 가장 큰 절감은 <b>핸들러 밖 초기화</b>입니다. DB 커넥션·SDK 클라이언트를 핸들러 안에서 만들면 매 요청마다 다시 만들고, 밖에 두면 같은 인스턴스가 재사용합니다. 의존성을 줄여 패키지를 가볍게 하는 것도 직접적인 효과가 있습니다.\n⚠️ 더 큰 함정은 <b>커넥션 폭발</b>입니다. 함수는 트래픽에 따라 수백 개로 늘어나는데 각자 DB 커넥션을 열면 DB 의 상한을 순식간에 넘깁니다 — 커넥션 풀러(프록시)를 사이에 두어 총량을 제한해야 합니다.\n💡 예열(provisioned concurrency)은 콜드 스타트를 없애 주지만 <b>상시 비용</b>이 듭니다. 서버리스를 쓰는 이유가 비용이라면 피크 시간대에만 켜는 절충이 현실적입니다." },

{ kind:"cloud", k:"공격 트래픽 막기", lv:3,
  q:"공개 API 가 <b>대량 요청</b>과 <b>봇</b>에 시달립니다. 정상 사용자를 막지 않으면서 방어하도록 계층을 설계하세요. 방어 자체가 <b>비용 폭탄</b>이 되지 않아야 합니다.",
  src:'{\n  "components": [\n    { "name": "app", "icon": "🖥" },\n    { "name": "db", "icon": "🗄" }\n  ],\n  "connections": []\n}',
  ref:{components:[{name:"cdn-waf",icon:"🛡",layer:"edge",rules:["IP 평판","알려진 공격 패턴","지역 차단"],
          note:"엣지에서 버리면 원본 비용이 들지 않는다"},
        {name:"rate-limit",icon:"🚦",layer:"edge",key:"IP + API 키",burst:"토큰 버킷"},
        {name:"app",icon:"🖥",layer:"origin",authRateLimit:"로그인은 계정 단위로 더 엄격하게"},
        {name:"db",icon:"🗄"},
        {name:"budget-alarm",icon:"💰",note:"공격이 곧 청구서다 — 트래픽·비용 경보를 함께 건다"}],
       connections:[{from:"cdn-waf",to:"rate-limit"},{from:"rate-limit",to:"app"},{from:"app",to:"db"}]},
  tests:[{d:"엣지에 방어 계층이 있다", js:"D.components.some(c=>/waf|cdn|edge/i.test(c.name)&&/edge/i.test(String(c.layer)))"},
         {d:"레이트 리밋이 있다", js:"D.components.some(c=>/rate|limit|throttl/i.test(c.name))"},
         {d:"레이트 리밋 기준이 정해져 있다", js:"D.components.some(c=>/rate|limit/i.test(c.name)&&!!String(c.key||'').trim())"},
         {d:"로그인에 더 엄격한 제한을 둔다", js:"/로그인|login|auth/i.test(JSON.stringify(D.components))"},
         {d:"방어를 원본 앞에서 한다", js:"D.connections.some(e=>/waf|cdn|rate/i.test(String(e.from))&&/app|rate/i.test(String(e.to)))"},
         {d:"비용 경보가 있다", js:"D.components.some(c=>/budget|비용|cost/i.test(c.name))"}],
  ex:"🎯 방어는 <b>가장 바깥에서</b> 해야 값쌉니다. 엣지에서 버린 요청은 원본 서버·DB·대역폭을 전혀 쓰지 않지만, 앱까지 들어와 거절하면 이미 비용이 발생한 뒤입니다.\n🔧 계층을 나누세요 — 엣지 WAF(알려진 패턴·평판) → 레이트 리밋(요청량) → 앱(업무 규칙). 각 계층이 다른 종류의 공격을 거릅니다.\n⚠️ 레이트 리밋을 <b>IP 하나로만</b> 걸면 회사·학교처럼 NAT 뒤의 정상 사용자가 함께 막힙니다. API 키·계정·IP 를 조합하고, 로그인처럼 민감한 엔드포인트는 <b>계정 단위</b>로 더 엄격하게 거는 것이 맞습니다.\n💡 자동 확장을 켜 둔 채 공격을 받으면 서비스는 살아 있는데 <b>청구서가 터집니다</b>. 트래픽 경보와 예산 경보를 함께 걸어 두세요 — 그게 유일한 조기 경보입니다." },

{ kind:"cloud", k:"비용을 팀에 귀속시키기", lv:2,
  q:"클라우드 청구서가 한 덩어리로 나와 <b>어느 팀·기능이 얼마를 쓰는지</b> 알 수 없습니다. 비용을 나눌 수 있게 설계하고, 태그가 없는 자원이 생기지 않도록 막으세요.",
  src:'{\n  "components": [\n    { "name": "cluster", "icon": "☸" },\n    { "name": "db", "icon": "🗄" }\n  ],\n  "connections": []\n}',
  ref:{components:[{name:"tagging-policy",icon:"🏷",required:["team","service","env","cost-center"],
          enforcement:"태그 없는 자원은 생성 자체를 거부한다(정책·IaC 검사)"},
        {name:"cluster",icon:"☸",tags:{team:"platform",service:"api",env:"prod"},
          note:"공유 자원은 네임스페이스 사용량으로 안분한다"},
        {name:"db",icon:"🗄",tags:{team:"order",service:"order-db",env:"prod"}},
        {name:"cost-report",icon:"📊",schedule:"주간",note:"팀별·서비스별 추이와 이상 증가 경보"}],
       connections:[{from:"cluster",to:"cost-report"},{from:"db",to:"cost-report"}]},
  tests:[{d:"필수 태그 목록이 정해져 있다", js:"D.components.some(c=>Array.isArray(c.required)&&c.required.length>=3)"},
         {d:"팀과 환경을 구분하는 태그가 있다", js:"D.components.some(c=>(c.required||[]).some(t=>/team|owner/i.test(t))&&(c.required||[]).some(t=>/env/i.test(t)))"},
         {d:"자원에 실제로 태그가 붙어 있다", js:"D.components.filter(c=>/cluster|db|storage/i.test(c.name)).every(c=>c.tags&&Object.keys(c.tags).length>=2)"},
         {d:"태그 없는 자원 생성을 막는다", js:"D.components.some(c=>/거부|막|deny|block|강제/i.test(String(c.enforcement||'')))"},
         {d:"공유 자원의 안분 방법을 정했다", js:"/안분|배분|비율|사용량/i.test(JSON.stringify(D.components))"},
         {d:"정기 리포트와 이상 경보가 있다", js:"D.components.some(c=>/report|리포트/i.test(c.name)&&!!String(c.schedule||'').trim())"}],
  ex:"🎯 비용을 줄이려면 <b>누가 쓰는지</b> 부터 알아야 합니다. 청구서가 한 덩어리면 아무도 자기 몫이라고 느끼지 않고, 최적화도 우선순위를 정할 수 없습니다.\n🔧 태그는 <b>나중에 붙일 수 없습니다</b>. 이미 만들어진 수백 개 자원에 소급 적용하는 건 사실상 불가능하므로, 태그 없는 자원은 <b>생성 자체를 거부</b>하는 정책이 필요합니다(IaC 검사·클라우드 정책).\n💡 쿠버네티스 클러스터나 공유 DB 처럼 여러 팀이 쓰는 자원은 태그만으로 안 나뉩니다 — 네임스페이스·요청량 기준으로 <b>안분 규칙</b>을 미리 정해 두어야 논쟁이 없습니다.\n⚠️ 리포트가 <b>월말에만</b> 나오면 이미 늦습니다. 주간 추이와 이상 증가 경보가 있어야 잘못 켜 둔 자원을 며칠 안에 잡습니다." },

{ kind:"cloud", k:"이벤트 순서와 중복", lv:3,
  q:"주문 상태 변경 이벤트를 여러 소비자가 처리합니다. 메시지는 <b>순서가 뒤바뀌거나 중복</b>될 수 있습니다. 상태가 <b>거꾸로 돌아가지 않도록</b> 설계하세요.",
  src:'{\n  "components": [\n    { "name": "producer", "icon": "📤" },\n    { "name": "consumer", "icon": "📥" }\n  ],\n  "connections": []\n}',
  ref:{components:[{name:"producer",icon:"📤",partitionKey:"order_id",note:"같은 주문은 같은 파티션으로 — 그 안에서는 순서가 보장된다"},
        {name:"broker",icon:"📬",ordering:"파티션 내 순서 보장",delivery:"최소 한 번"},
        {name:"consumer",icon:"📥",scale:3,
          idempotency:"처리한 event_id 를 기록해 중복을 건너뛴다",
          staleGuard:"이벤트의 version 이 현재 상태보다 낮으면 무시한다"},
        {name:"processed",icon:"🗂",unique:"event_id",retention:"7일"}],
       connections:[{from:"producer",to:"broker"},{from:"broker",to:"consumer"},{from:"consumer",to:"processed"}]},
  tests:[{d:"파티션 키가 정해져 있다", js:"D.components.some(c=>/order|entity|aggregate/i.test(String(c.partitionKey||'')))"},
         {d:"순서 보장 범위를 명시했다", js:"/파티션 내|partition/i.test(JSON.stringify(D.components))"},
         {d:"전달이 최소 한 번임을 인정한다", js:"/최소 한 번|at.least.once/i.test(JSON.stringify(D.components))"},
         {d:"중복을 event_id 로 걸러낸다", js:"D.components.some(c=>/event_id/i.test(String(c.idempotency||'')+String(c.unique||'')))"},
         {d:"오래된 이벤트를 무시하는 장치가 있다", js:"D.components.some(c=>/version|시퀀스|낮으면|stale/i.test(String(c.staleGuard||'')))"},
         {d:"처리 기록의 보관 기간이 있다", js:"D.components.some(c=>/processed|기록/i.test(c.name)&&!!String(c.retention||'').trim())"}],
  ex:"🎯 메시지 브로커의 순서 보장은 대개 <b>파티션 안에서만</b> 성립합니다. 같은 주문의 이벤트가 다른 파티션으로 흩어지면 '배송 완료' 가 '결제 완료' 보다 먼저 처리될 수 있습니다 — 파티션 키를 주문 id 로 잡아야 하는 이유입니다.\n⚠️ 그래도 <b>재시도와 재처리</b> 때문에 순서가 뒤집힐 수 있습니다. 이벤트에 버전(또는 시퀀스)을 실어 <b>현재 상태보다 오래된 이벤트는 무시</b>하면 상태가 거꾸로 가지 않습니다.\n💡 전달은 거의 항상 <b>최소 한 번</b>입니다. 처리한 event_id 를 기록해 두고 중복을 건너뛰는 것이 표준 방어이고, 그 기록에도 보관 기간이 필요합니다.\n🔧 파티션 키를 주문 id 로 잡으면 <b>주문 하나가 뜨거운 파티션</b>이 될 수 있습니다. 순서 보장과 병렬성은 맞바꾸는 관계라, 어느 단위까지 순서가 필요한지 먼저 정해야 합니다." },
];
