/* 설계(arch) 문항 — 사용자가 JSON 설계 문서를 쓰고, 검사식이 그 문서를 읽어 판정한다.
   코드를 실행하는 게 아니라 '설계가 요건을 만족하는가' 를 본다.

   ref 는 검증용 참조 설계다(주입하지 않는다). 검증기가 확인하는 것:
     1. src 가 올바른 JSON 이고, 그대로는 통과하지 못한다 (풀 게 남아 있다)
     2. ref 는 모든 검사를 통과한다 (요건이 실제로 만족 가능하다)
   자유 서술 정규식은 최소화하고 구조를 직접 확인한다 — 느슨한 정규식은
   엉뚱한 문자열에도 통과해 '설계를 안 해도 맞는' 문항을 만든다. */
module.exports = [
/* ─────────── ERD ─────────── */
{ kind:"erd", k:"주문 번호의 유일성", lv:2,
  q:"쇼핑몰의 <b>회원과 주문</b>을 설계하세요. 한 회원은 주문을 여러 번 할 수 있고, <b>주문번호(order_no)는 전체에서 중복될 수 없습니다</b>. 회원별 주문 목록 조회가 잦습니다.",
  src:'{\n  "entities": [\n    { "name": "member", "fields": [{ "name": "id", "type": "bigint", "pk": true }] },\n    { "name": "orders", "fields": [{ "name": "id", "type": "bigint", "pk": true }] }\n  ],\n  "relations": []\n}',
  ref:{entities:[{name:"member",fields:[{name:"id",type:"bigint",pk:true},{name:"email",type:"varchar(255)"}],unique:[["email"]]},
                 {name:"orders",fields:[{name:"id",type:"bigint",pk:true},{name:"order_no",type:"varchar(32)"},{name:"member_id",type:"bigint",fk:"member.id",index:true}],unique:[["order_no"]]}],
       relations:[{from:"member",to:"orders",type:"1:N"}]},
  tests:[{d:"member 와 orders 두 테이블이 있다", js:"D.entities.length===2 && ['member','orders'].every(n=>D.entities.some(e=>e.name===n))"},
         {d:"두 테이블 모두 기본키가 정확히 하나다", js:"D.entities.every(e=>e.fields.filter(f=>f.pk).length===1)"},
         {d:"orders 가 member 를 가리키는 외래키를 갖는다", js:"D.entities.find(e=>e.name==='orders').fields.some(f=>f.fk && String(f.fk).indexOf('member')===0)"},
         {d:"그 외래키에 인덱스가 걸려 있다", js:"D.entities.find(e=>e.name==='orders').fields.some(f=>f.fk && f.index===true)"},
         {d:"order_no 에 유니크 제약이 있다", js:"(D.entities.find(e=>e.name==='orders').unique||[]).some(u=>Array.isArray(u)&&u.length===1&&u[0]==='order_no')"},
         {d:"1:N 관계가 선언돼 있다", js:"D.relations.some(r=>r.type==='1:N'&&r.from==='member'&&r.to==='orders')"}],
  ex:"유니크 제약은 <b>애플리케이션 검사로 대신할 수 없습니다</b>. '먼저 조회해서 없으면 넣는다' 는 두 요청이 동시에 오면 둘 다 통과합니다. 중복이 절대 안 되는 값은 DB 제약으로 못 박아야 하고, 애플리케이션 검사는 사용자에게 친절한 메시지를 주기 위한 <b>추가</b> 장치입니다.\n💡 외래키에 인덱스가 필요한 이유는 별개입니다 — 대부분의 DB 는 외래키를 만들어도 인덱스를 자동 생성하지 않아, '회원의 주문 목록' 이 주문 테이블 전체를 훑게 됩니다." },

{ kind:"erd", k:"다대다와 조인 테이블", lv:2,
  q:"<b>학생과 강의</b>를 설계하세요. 한 학생은 여러 강의를 듣고 한 강의에는 여러 학생이 있습니다. 같은 학생이 같은 강의를 <b>두 번 등록할 수는 없습니다</b>. 수강신청 시각도 남겨야 합니다.",
  src:'{\n  "entities": [\n    { "name": "student", "fields": [{ "name": "id", "type": "bigint", "pk": true }] },\n    { "name": "course", "fields": [{ "name": "id", "type": "bigint", "pk": true }] }\n  ],\n  "relations": []\n}',
  ref:{entities:[{name:"student",fields:[{name:"id",type:"bigint",pk:true},{name:"name",type:"varchar(50)"}]},
                 {name:"course",fields:[{name:"id",type:"bigint",pk:true},{name:"title",type:"varchar(100)"}]},
                 {name:"enrollment",fields:[{name:"id",type:"bigint",pk:true},{name:"student_id",type:"bigint",fk:"student.id",index:true},{name:"course_id",type:"bigint",fk:"course.id",index:true},{name:"enrolled_at",type:"timestamptz"}],unique:[["student_id","course_id"]]}],
       relations:[{from:"student",to:"enrollment",type:"1:N"},{from:"course",to:"enrollment",type:"1:N"}]},
  tests:[{d:"조인 테이블을 포함해 세 테이블이다", js:"D.entities.length===3"},
         {d:"조인 테이블이 두 쪽 모두를 가리키는 외래키를 갖는다", js:"D.entities.some(e=>e.fields.filter(f=>f.fk).length===2 && e.fields.some(f=>String(f.fk).indexOf('student')===0) && e.fields.some(f=>String(f.fk).indexOf('course')===0))"},
         {d:"(학생, 강의) 조합에 복합 유니크가 걸려 있다", js:"D.entities.some(e=>(e.unique||[]).some(u=>Array.isArray(u)&&u.length===2&&u.some(c=>/student/.test(c))&&u.some(c=>/course/.test(c))))"},
         {d:"수강신청 시각 필드가 있다", js:"D.entities.some(e=>e.fields.some(f=>/at$|time|date/.test(f.name)))"},
         {d:"조인 테이블의 외래키에 인덱스가 있다", js:"D.entities.filter(e=>e.fields.filter(f=>f.fk).length===2).every(e=>e.fields.filter(f=>f.fk).every(f=>f.index===true))"},
         {d:"두 개의 1:N 관계로 표현했다", js:"D.relations.filter(r=>r.type==='1:N').length===2"}],
  ex:"관계형 DB 에 다대다를 직접 담을 수는 없습니다. <b>조인 테이블</b>로 1:N 두 개로 쪼개는 것이 정석이고, 이때 '같은 조합은 한 번만' 을 <b>복합 유니크</b>로 표현합니다.\n💡 조인 테이블을 단순한 연결로만 보면 나중에 곤란해집니다 — 수강신청 시각·성적·상태처럼 <b>관계 자체가 갖는 속성</b>이 반드시 생깁니다. 처음부터 독립된 엔티티로 이름을 붙여 두면(enrollment) 확장이 자연스럽습니다." },

{ kind:"erd", k:"소프트 삭제와 유니크 충돌", lv:3,
  q:"회원 이메일은 <b>중복될 수 없지만</b>, 탈퇴한 회원의 기록은 남겨야 합니다(소프트 삭제). 탈퇴한 이메일로는 <b>다시 가입할 수 있어야</b> 합니다. 이 요건을 만족하도록 설계하세요.",
  src:'{\n  "entities": [\n    { "name": "member", "fields": [\n      { "name": "id", "type": "bigint", "pk": true },\n      { "name": "email", "type": "varchar(255)" }\n    ], "unique": [["email"]] }\n  ],\n  "relations": []\n}',
  ref:{entities:[{name:"member",fields:[{name:"id",type:"bigint",pk:true},{name:"email",type:"varchar(255)"},{name:"deleted_at",type:"timestamptz",nullable:true}],
        unique:[["email","deleted_at"]], partialIndex:"UNIQUE(email) WHERE deleted_at IS NULL"}],
       relations:[]},
  tests:[{d:"삭제 시각 필드가 있다", js:"D.entities[0].fields.some(f=>/delete|removed|withdraw/.test(f.name))"},
         {d:"삭제 시각은 NULL 을 허용한다 (살아 있는 회원)", js:"D.entities[0].fields.some(f=>/delete|removed|withdraw/.test(f.name) && f.nullable===true)"},
         {d:"email 단독 유니크를 그대로 두지 않았다", js:"!(D.entities[0].unique||[]).some(u=>Array.isArray(u)&&u.length===1&&u[0]==='email')"},
         {d:"이메일 중복을 막는 장치가 남아 있다", js:"(D.entities[0].unique||[]).some(u=>Array.isArray(u)&&u.indexOf('email')>=0) || /email/.test(String(D.entities[0].partialIndex||''))"},
         {d:"부분 인덱스나 복합 유니크로 '살아 있는 회원만' 을 한정했다", js:"/deleted|removed|withdraw/i.test(String(D.entities[0].partialIndex||'')) || (D.entities[0].unique||[]).some(u=>Array.isArray(u)&&u.length>=2&&u.indexOf('email')>=0&&u.some(c=>/delete|removed|withdraw/.test(c)))"}],
  ex:"소프트 삭제를 넣는 순간 <b>모든 유니크 제약이 깨집니다</b>. `UNIQUE(email)` 을 그대로 두면 탈퇴한 사람의 이메일로 재가입이 영영 막힙니다.\n🔧 해법은 둘입니다. PostgreSQL 처럼 <b>부분 인덱스</b>를 지원하면 `UNIQUE(email) WHERE deleted_at IS NULL` 이 가장 깔끔합니다. 지원하지 않으면 `UNIQUE(email, deleted_at)` 로 두되, 살아 있는 행의 deleted_at 을 NULL 이 아닌 고정값(예: 0)으로 채워야 합니다 — NULL 은 서로 같지 않아 유니크가 걸리지 않기 때문입니다.\n⚠️ 소프트 삭제는 공짜가 아닙니다. 모든 조회에 `WHERE deleted_at IS NULL` 을 빠뜨리면 탈퇴 회원이 화면에 나타납니다." },

{ kind:"erd", k:"가격은 바뀌고 주문은 남는다", lv:3,
  q:"상품 가격은 수시로 바뀌지만, <b>이미 결제된 주문의 금액은 절대 변하면 안 됩니다</b>. 상품·주문상세를 설계하세요. 금액 타입도 신중히 고르세요.",
  src:'{\n  "entities": [\n    { "name": "product", "fields": [\n      { "name": "id", "type": "bigint", "pk": true },\n      { "name": "price", "type": "float" }\n    ] },\n    { "name": "order_item", "fields": [\n      { "name": "id", "type": "bigint", "pk": true },\n      { "name": "product_id", "type": "bigint", "fk": "product.id" }\n    ] }\n  ],\n  "relations": []\n}',
  ref:{entities:[{name:"product",fields:[{name:"id",type:"bigint",pk:true},{name:"price",type:"decimal(12,2)"}]},
                 {name:"order_item",fields:[{name:"id",type:"bigint",pk:true},{name:"product_id",type:"bigint",fk:"product.id",index:true},{name:"unit_price",type:"decimal(12,2)"},{name:"qty",type:"int"}]}],
       relations:[{from:"product",to:"order_item",type:"1:N"}]},
  tests:[{d:"주문상세가 자기 시점의 단가를 갖는다", js:"D.entities.find(e=>e.name==='order_item').fields.some(f=>/price|amount/.test(f.name))"},
         {d:"수량 필드가 있다", js:"D.entities.find(e=>e.name==='order_item').fields.some(f=>/qty|quantity|count/.test(f.name))"},
         {d:"금액에 float 을 쓰지 않았다", js:"D.entities.every(e=>e.fields.filter(f=>/price|amount/.test(f.name)).every(f=>!/float|double|real/i.test(String(f.type))))"},
         {d:"금액이 decimal/numeric 이거나 정수 단위다", js:"D.entities.every(e=>e.fields.filter(f=>/price|amount/.test(f.name)).every(f=>/decimal|numeric|bigint|int/i.test(String(f.type))))"},
         {d:"외래키에 인덱스가 있다", js:"D.entities.find(e=>e.name==='order_item').fields.filter(f=>f.fk).every(f=>f.index===true)"}],
  ex:"주문상세가 product 를 <b>참조만</b> 하면, 나중에 상품 가격이 바뀌는 순간 과거 주문 금액까지 바뀝니다. 영수증이 소급 수정되는 셈입니다.\n🔧 그래서 주문 시점의 단가를 <b>복사해서 저장</b>합니다. 정규화 원칙에 어긋나 보이지만, 이건 중복이 아니라 <b>서로 다른 사실</b>입니다 — '지금 팔리는 가격' 과 '그때 팔린 가격' 은 다른 값입니다.\n⚠️ 금액에 float 을 쓰면 0.1+0.2 문제가 회계에 그대로 들어옵니다. decimal/numeric 을 쓰거나 '원' 대신 최소 단위 정수로 저장하세요." },

{ kind:"erd", k:"자기 참조로 만드는 계층", lv:2,
  q:"카테고리는 <b>상위 카테고리를 가질 수 있고</b>, 최상위 카테고리는 상위가 없습니다(깊이 제한 없음). 이 구조를 설계하고, 특정 카테고리의 <b>하위 목록 조회</b>가 빠르도록 하세요.",
  src:'{\n  "entities": [\n    { "name": "category", "fields": [\n      { "name": "id", "type": "bigint", "pk": true },\n      { "name": "name", "type": "varchar(50)" }\n    ] }\n  ],\n  "relations": []\n}',
  ref:{entities:[{name:"category",fields:[{name:"id",type:"bigint",pk:true},{name:"name",type:"varchar(50)"},{name:"parent_id",type:"bigint",fk:"category.id",nullable:true,index:true}]}],
       relations:[{from:"category",to:"category",type:"1:N"}]},
  tests:[{d:"테이블은 하나다", js:"D.entities.length===1"},
         {d:"자기 자신을 가리키는 외래키가 있다", js:"D.entities[0].fields.some(f=>String(f.fk||'').indexOf('category')===0)"},
         {d:"그 외래키는 NULL 을 허용한다 (최상위)", js:"D.entities[0].fields.some(f=>String(f.fk||'').indexOf('category')===0 && f.nullable===true)"},
         {d:"하위 조회를 위해 인덱스가 걸려 있다", js:"D.entities[0].fields.some(f=>String(f.fk||'').indexOf('category')===0 && f.index===true)"},
         {d:"자기 참조 1:N 관계를 선언했다", js:"D.relations.some(r=>r.from==='category'&&r.to==='category'&&r.type==='1:N')"}],
  ex:"인접 리스트(adjacency list)는 자기 참조 외래키 하나로 <b>깊이 제한 없는</b> 트리를 담습니다. 구조가 단순하고 이동·삽입이 싸다는 게 장점입니다.\n⚠️ 대가는 조회입니다. '이 카테고리의 <b>모든</b> 하위' 를 구하려면 재귀가 필요합니다 — 표준 SQL 의 `WITH RECURSIVE` 를 쓰거나, 읽기가 압도적으로 많다면 경로 문자열(`/1/7/23/`)이나 클로저 테이블 같은 다른 표현을 함께 둡니다.\n💡 최상위를 NULL 로 두는 대신 자기 자신을 가리키게 하면 순환이 생겨 재귀 쿼리가 멈추지 않습니다. NULL 이 맞습니다." },

{ kind:"erd", k:"결제 중복을 막는 멱등키", lv:3,
  q:"결제 요청이 네트워크 오류로 재시도될 때 <b>두 번 결제되면 안 됩니다</b>. 클라이언트가 보낸 요청 키로 중복을 막도록 결제 테이블을 설계하세요. 만료된 키는 정리할 수 있어야 합니다.",
  src:'{\n  "entities": [\n    { "name": "payment", "fields": [\n      { "name": "id", "type": "bigint", "pk": true },\n      { "name": "amount", "type": "decimal(12,2)" },\n      { "name": "status", "type": "varchar(20)" }\n    ] }\n  ],\n  "relations": []\n}',
  ref:{entities:[{name:"payment",fields:[{name:"id",type:"bigint",pk:true},{name:"idempotency_key",type:"varchar(64)"},{name:"amount",type:"decimal(12,2)"},{name:"status",type:"varchar(20)"},{name:"created_at",type:"timestamptz"},{name:"expires_at",type:"timestamptz"}],
        unique:[["idempotency_key"]]}],
       relations:[]},
  tests:[{d:"멱등키 필드가 있다", js:"D.entities[0].fields.some(f=>/idempot|request_key|dedup/i.test(f.name))"},
         {d:"멱등키에 유니크 제약이 걸려 있다", js:"(D.entities[0].unique||[]).some(u=>Array.isArray(u)&&u.some(c=>/idempot|request_key|dedup/i.test(c)))"},
         {d:"만료 시각 필드가 있다", js:"D.entities[0].fields.some(f=>/expire|ttl|valid_until/i.test(f.name))"},
         {d:"금액에 float 을 쓰지 않았다", js:"D.entities[0].fields.filter(f=>/amount|price/.test(f.name)).every(f=>!/float|double|real/i.test(String(f.type)))"},
         {d:"상태 필드를 유지했다", js:"D.entities[0].fields.some(f=>/status|state/.test(f.name))"}],
  ex:"재시도는 <b>정상 동작</b>입니다. 타임아웃이 났을 때 클라이언트는 성공했는지 실패했는지 알 수 없으므로 다시 보냅니다. 그래서 서버가 '같은 요청' 을 알아볼 수단이 필요합니다.\n🔧 클라이언트가 요청마다 고유 키를 만들어 보내고, 서버는 그 키에 <b>유니크 제약</b>을 걸어 두 번째 삽입을 DB 가 거절하게 합니다. 거절되면 이미 있는 결과를 그대로 돌려주면 됩니다 — 조회 후 삽입은 동시 요청에서 뚫립니다.\n💡 키를 영원히 보관할 수는 없으니 만료 시각을 함께 두어 오래된 것부터 지웁니다. 보통 24시간이면 충분합니다." },

{ kind:"erd", k:"동시 수정과 낙관적 잠금", lv:3,
  q:"재고 수량을 여러 요청이 동시에 고칠 때 <b>덮어쓰기로 값이 유실되지 않도록</b> 설계하세요. 행 전체를 잠그지 않고(낙관적) 충돌을 감지하는 방식이어야 합니다.",
  src:'{\n  "entities": [\n    { "name": "stock", "fields": [\n      { "name": "id", "type": "bigint", "pk": true },\n      { "name": "sku", "type": "varchar(32)" },\n      { "name": "qty", "type": "int" }\n    ] }\n  ],\n  "relations": []\n}',
  ref:{entities:[{name:"stock",fields:[{name:"id",type:"bigint",pk:true},{name:"sku",type:"varchar(32)"},{name:"qty",type:"int",check:"qty >= 0"},{name:"version",type:"bigint"},{name:"updated_at",type:"timestamptz"}],
        unique:[["sku"]]}],
       relations:[]},
  tests:[{d:"버전(또는 리비전) 필드가 있다", js:"D.entities[0].fields.some(f=>/version|revision|rev$/i.test(f.name))"},
         {d:"sku 에 유니크 제약이 있다", js:"(D.entities[0].unique||[]).some(u=>Array.isArray(u)&&u.length===1&&/sku/i.test(u[0]))"},
         {d:"수량이 음수가 되지 않도록 제약을 걸었다", js:"D.entities[0].fields.some(f=>/qty|quantity/.test(f.name) && /(>=|>)\\s*0/.test(String(f.check||'')))"},
         {d:"마지막 수정 시각을 남긴다", js:"D.entities[0].fields.some(f=>/updated|modified/i.test(f.name))"},
         {d:"수량이 정수 타입이다", js:"D.entities[0].fields.filter(f=>/qty|quantity/.test(f.name)).every(f=>/int/i.test(String(f.type)))"}],
  ex:"낙관적 잠금은 '충돌은 드물다' 고 보고 <b>일단 진행한 뒤 검사</b>합니다. 읽을 때 version 을 같이 읽고, 쓸 때 `WHERE id=? AND version=?` 로 갱신합니다. 그 사이 누가 고쳤다면 version 이 달라 <b>0행이 갱신되고</b>, 그때 재시도하면 됩니다.\n🔧 재고처럼 '절대 음수가 되면 안 되는' 값은 CHECK 제약을 함께 걸어 두세요. 애플리케이션 버그가 있어도 DB 가 마지막으로 막아 줍니다.\n💡 충돌이 잦다면 비관적 잠금(`SELECT ... FOR UPDATE`)이나 원자적 증감(`SET qty = qty - 1 WHERE qty >= 1`)이 더 낫습니다. 어느 쪽이든 '읽고-계산하고-쓰기' 를 그냥 두는 것보다는 낫습니다." },

{ kind:"erd", k:"이력을 남기는 테이블", lv:3,
  q:"직원의 <b>부서 이동 이력</b>을 남겨야 합니다. '현재 부서' 조회도 빨라야 하고, '2023년에 어느 부서였는지' 도 알 수 있어야 합니다. 기간을 다루는 방식에 주의하세요.",
  src:'{\n  "entities": [\n    { "name": "employee", "fields": [\n      { "name": "id", "type": "bigint", "pk": true },\n      { "name": "dept", "type": "varchar(50)" }\n    ] }\n  ],\n  "relations": []\n}',
  ref:{entities:[{name:"employee",fields:[{name:"id",type:"bigint",pk:true},{name:"name",type:"varchar(50)"}]},
                 {name:"department",fields:[{name:"id",type:"bigint",pk:true},{name:"name",type:"varchar(50)"}]},
                 {name:"employee_dept_history",fields:[{name:"id",type:"bigint",pk:true},{name:"employee_id",type:"bigint",fk:"employee.id",index:true},{name:"department_id",type:"bigint",fk:"department.id",index:true},{name:"valid_from",type:"timestamptz"},{name:"valid_to",type:"timestamptz",nullable:true}]}],
       relations:[{from:"employee",to:"employee_dept_history",type:"1:N"},{from:"department",to:"employee_dept_history",type:"1:N"}]},
  tests:[{d:"이력 테이블이 따로 있다", js:"D.entities.length>=3"},
         {d:"이력이 시작 시각을 갖는다", js:"D.entities.some(e=>e.fields.some(f=>/from|start|begin/i.test(f.name)))"},
         {d:"이력이 종료 시각을 갖고 NULL 이면 '현재' 를 뜻한다", js:"D.entities.some(e=>e.fields.some(f=>/to$|_to|end|until/i.test(f.name) && f.nullable===true))"},
         {d:"이력이 직원과 부서 양쪽 외래키를 갖는다", js:"D.entities.some(e=>e.fields.some(f=>/employee/.test(String(f.fk||''))) && e.fields.some(f=>/department|dept/.test(String(f.fk||''))))"},
         {d:"이력의 외래키에 인덱스가 걸려 있다", js:"D.entities.filter(e=>e.fields.filter(f=>f.fk).length>=2).every(e=>e.fields.filter(f=>f.fk).every(f=>f.index===true))"}],
  ex:"부서를 문자열 컬럼 하나로 두면 <b>과거가 사라집니다</b>. 이동하는 순간 이전 값이 덮어써지기 때문입니다.\n🔧 유효 기간(valid_from, valid_to)을 가진 이력 테이블로 분리하면, 종료 시각이 NULL 인 행이 곧 '현재' 이고 특정 시점 조회는 `valid_from <= t AND (valid_to IS NULL OR valid_to > t)` 로 풀립니다.\n⚠️ 기간은 반드시 <b>반열린 구간</b>[from, to)으로 통일하세요. 양끝을 포함하면 경계 시각에 두 행이 동시에 유효해집니다.\n💡 '현재 부서' 조회가 아주 잦다면 employee 에 current_dept_id 를 비정규화해 두고 이력과 함께 갱신하는 것도 정당한 선택입니다 — 대신 둘을 한 트랜잭션에서 바꿔야 합니다." },

/* ─────────── API ─────────── */
{ kind:"api", k:"리소스와 상태 코드", lv:1,
  q:"게시글 API 를 설계하세요. <b>목록 조회 · 단건 조회 · 생성 · 삭제</b> 네 가지가 필요합니다. 각 동작에 맞는 HTTP 메서드와 <b>성공 상태 코드</b>를 정확히 쓰고, 없는 글을 조회할 때의 오류도 명시하세요.",
  src:'{\n  "endpoints": [\n    { "method": "GET", "path": "/getPosts", "status": 200, "desc": "글 목록" }\n  ]\n}',
  ref:{endpoints:[{method:"GET",path:"/posts",status:200,errors:[],desc:"글 목록"},
                  {method:"GET",path:"/posts/{id}",status:200,errors:[404],desc:"글 단건"},
                  {method:"POST",path:"/posts",status:201,errors:[400],desc:"글 생성"},
                  {method:"DELETE",path:"/posts/{id}",status:204,errors:[404],desc:"글 삭제"}]},
  tests:[{d:"엔드포인트가 4개다", js:"D.endpoints.length===4"},
         {d:"경로에 동사를 넣지 않았다", js:"D.endpoints.every(e=>!/\\/(get|create|delete|update|fetch|remove)[A-Za-z]/i.test(String(e.path)))"},
         {d:"목록과 단건이 같은 경로 체계를 쓴다", js:"D.endpoints.some(e=>e.method==='GET'&&/^\\/posts$/.test(e.path)) && D.endpoints.some(e=>e.method==='GET'&&/^\\/posts\\/\\{?\\w+\\}?$/.test(e.path))"},
         {d:"생성은 POST 이고 201 을 준다", js:"D.endpoints.some(e=>e.method==='POST'&&e.status===201)"},
         {d:"삭제는 DELETE 이고 204 를 준다", js:"D.endpoints.some(e=>e.method==='DELETE'&&e.status===204)"},
         {d:"단건 조회와 삭제가 404 를 낼 수 있다", js:"D.endpoints.filter(e=>/\\{/.test(String(e.path))).every(e=>(e.errors||[]).indexOf(404)>=0)"}],
  ex:"REST 에서 <b>동작은 메서드가, 대상은 경로가</b> 나타냅니다. `/getPosts` 처럼 경로에 동사를 넣으면 메서드가 하는 일을 중복해서 말하게 되고, 캐시·프록시가 의미를 읽을 수 없습니다.\n💡 상태 코드는 약속입니다 — 201 은 '만들었고 Location 헤더에 위치가 있다', 204 는 '성공했고 본문이 없다' 는 뜻입니다. 전부 200 으로 두면 클라이언트가 본문을 파싱하려다 빈 응답에서 터집니다.\n⚠️ 삭제를 여러 번 호출해도 결과가 같아야(멱등) 하므로, 이미 없는 리소스를 지울 때 404 를 줄지 204 를 줄지는 팀에서 정해 문서화하세요." },

{ kind:"api", k:"페이지네이션", lv:2,
  q:"글 목록에 <b>페이지네이션</b>을 추가하세요. 데이터가 계속 추가되는 피드라서 <b>중복·누락이 없어야</b> 합니다. 응답에 다음 페이지를 요청할 수단이 포함되어야 하고, 한 번에 가져올 개수에 상한이 있어야 합니다.",
  src:'{\n  "endpoints": [\n    { "method": "GET", "path": "/posts?page=1&size=20", "status": 200, "desc": "글 목록" }\n  ]\n}',
  ref:{endpoints:[{method:"GET",path:"/posts?cursor={cursor}&limit={limit}",status:200,errors:[400],
    params:[{name:"cursor",required:false,desc:"이전 응답의 next_cursor"},{name:"limit",required:false,max:100,default:20}],
    response:{items:"[]",next_cursor:"string|null"},desc:"글 목록 (커서 기반)"}]},
  tests:[{d:"커서 기반이다 (page 번호가 아니다)", js:"D.endpoints.some(e=>/cursor|after|since/i.test(String(e.path)+JSON.stringify(e.params||[])))"},
         {d:"page 파라미터를 쓰지 않는다", js:"D.endpoints.every(e=>!/[?&]page=/.test(String(e.path)))"},
         {d:"응답에 다음 커서가 들어 있다", js:"/cursor|next/i.test(JSON.stringify(D.endpoints.map(e=>e.response||'')))"},
         {d:"개수 파라미터에 상한이 정해져 있다", js:"D.endpoints.some(e=>(e.params||[]).some(p=>/limit|size|per/i.test(p.name)&&typeof p.max==='number'))"},
         {d:"개수 파라미터에 기본값이 있다", js:"D.endpoints.some(e=>(e.params||[]).some(p=>/limit|size|per/i.test(p.name)&&p.default!=null))"},
         {d:"잘못된 파라미터에 400 을 낸다", js:"D.endpoints.every(e=>(e.errors||[]).indexOf(400)>=0)"}],
  ex:"오프셋 방식(`page=2`)은 <b>목록이 고정된 경우에만</b> 맞습니다. 1페이지를 읽는 사이 새 글이 하나 추가되면 모든 항목이 한 칸 밀려, 2페이지에서 <b>이미 본 글이 다시 나오고</b> 어떤 글은 영영 안 보입니다.\n🔧 커서 방식은 '마지막으로 본 지점' 을 기준으로 잡아 그 뒤부터 읽으므로 삽입에 영향받지 않습니다. 성능도 낫습니다 — `OFFSET 100000` 은 앞의 10만 행을 실제로 읽고 버립니다.\n⚠️ limit 에 상한이 없으면 `limit=1000000` 한 방으로 서버가 죽습니다. 기본값과 최대값을 반드시 정하세요.\n💡 커서는 정렬 기준과 짝입니다. 정렬이 유일하지 않으면(같은 시각이 여럿) 타이브레이커로 id 를 함께 넣어야 커서가 정확해집니다." },

{ kind:"api", k:"POST 재시도와 멱등성", lv:3,
  q:"결제 생성 API 를 설계하세요. 타임아웃 후 클라이언트가 <b>같은 요청을 다시 보내도 두 번 결제되면 안 됩니다</b>. 요청 키를 받는 방식과, 처리 중일 때·키가 재사용될 때의 응답을 명시하세요.",
  src:'{\n  "endpoints": [\n    { "method": "POST", "path": "/payments", "status": 201, "desc": "결제 생성" }\n  ]\n}',
  ref:{endpoints:[{method:"POST",path:"/payments",status:201,errors:[400,409,422],
    headers:[{name:"Idempotency-Key",required:true,desc:"클라이언트가 만든 고유 키"}],
    note:"같은 키로 재요청하면 처음 만든 결제를 200 으로 그대로 돌려준다",desc:"결제 생성"},
    {method:"GET",path:"/payments/{id}",status:200,errors:[404],desc:"결제 조회"}]},
  tests:[{d:"멱등 키를 헤더로 받는다", js:"D.endpoints.some(e=>(e.headers||[]).some(h=>/idempot/i.test(h.name)))"},
         {d:"그 헤더가 필수다", js:"D.endpoints.some(e=>(e.headers||[]).some(h=>/idempot/i.test(h.name)&&h.required===true))"},
         {d:"생성은 201 이다", js:"D.endpoints.some(e=>e.method==='POST'&&e.status===201)"},
         {d:"키 충돌·처리중을 409 로 구분한다", js:"D.endpoints.some(e=>e.method==='POST'&&(e.errors||[]).indexOf(409)>=0)"},
         {d:"재요청 시 어떻게 응답할지 적어 두었다", js:"/재요청|다시|같은 키|기존|그대로/.test(String(D.endpoints.map(e=>e.note||'').join(' ')))"},
         {d:"결과를 나중에 확인할 조회 엔드포인트가 있다", js:"D.endpoints.some(e=>e.method==='GET'&&/\\{/.test(String(e.path)))"}],
  ex:"GET·PUT·DELETE 는 본래 멱등하지만 <b>POST 는 아닙니다</b>. 그래서 '만들기' 는 재시도가 위험한 유일한 동작이고, 결제·주문처럼 되돌리기 어려운 곳에서 특히 문제가 됩니다.\n🔧 클라이언트가 요청마다 고유 키를 만들어 `Idempotency-Key` 헤더로 보내고, 서버는 그 키로 이미 처리한 결과를 찾아 <b>같은 응답을 다시</b> 돌려줍니다. Stripe·PayPal 이 쓰는 방식입니다.\n⚠️ 첫 요청이 <b>아직 처리 중</b>일 때 두 번째가 오는 경우가 실제로 가장 흔합니다. 이때 조용히 새로 만들면 안 되고, 409 로 '진행 중' 을 알린 뒤 클라이언트가 조회로 결과를 확인하게 해야 합니다.\n💡 키만 같고 <b>본문이 다른</b> 요청은 명백한 오류입니다(422). 키와 함께 요청 본문의 해시를 저장해 두면 잡을 수 있습니다." },

{ kind:"api", k:"401 과 403 을 구분한다", lv:2,
  q:"관리자 전용 API 를 설계하세요. <b>로그인하지 않은 요청</b>과 <b>로그인했지만 권한이 없는 요청</b>을 서로 다른 상태 코드로 구분하고, 존재를 숨겨야 하는 리소스는 어떻게 다룰지도 명시하세요.",
  src:'{\n  "endpoints": [\n    { "method": "GET", "path": "/admin/users", "status": 200, "errors": [400], "desc": "회원 목록" }\n  ]\n}',
  ref:{endpoints:[{method:"GET",path:"/admin/users",status:200,errors:[401,403],
      auth:"Bearer",note:"미인증은 401, 권한 부족은 403",desc:"회원 목록"},
    {method:"DELETE",path:"/admin/users/{id}",status:204,errors:[401,403,404],
      auth:"Bearer",note:"권한이 없으면 존재 여부를 흘리지 않도록 404 로 통일할 수도 있다",desc:"회원 삭제"}]},
  tests:[{d:"미인증을 401 로 낸다", js:"D.endpoints.every(e=>(e.errors||[]).indexOf(401)>=0)"},
         {d:"권한 부족을 403 으로 낸다", js:"D.endpoints.every(e=>(e.errors||[]).indexOf(403)>=0)"},
         {d:"인증 방식을 명시했다", js:"D.endpoints.every(e=>!!String(e.auth||'').trim())"},
         {d:"401 과 403 의 차이를 설명으로 남겼다", js:"/401[^0-9]*403|인증[^.]*권한|미인증/.test(String(D.endpoints.map(e=>e.note||'').join(' ')))"},
         {d:"단건 리소스에 404 도 정의돼 있다", js:"D.endpoints.filter(e=>/\\{/.test(String(e.path))).every(e=>(e.errors||[]).indexOf(404)>=0)"}],
  ex:"401 은 '<b>당신이 누구인지 모른다</b>' 이고 403 은 '<b>누구인지는 알지만 안 된다</b>' 입니다. 401 을 받은 클라이언트는 로그인 화면으로 보내야 하고, 403 은 로그인해도 소용없으니 안내 문구를 띄워야 합니다 — 섞어 쓰면 로그인 루프에 빠집니다.\n💡 401 응답에는 원래 `WWW-Authenticate` 헤더로 어떤 인증을 원하는지 알려 주게 돼 있습니다.\n⚠️ 다만 <b>존재 자체가 비밀</b>인 리소스는 403 이 정보 누출입니다 — 403 은 '그건 있다' 를 알려 주기 때문입니다. 남의 비공개 문서를 훑어 id 를 수집할 수 있게 됩니다. 이런 곳은 404 로 통일하는 편이 안전하고, 대신 그 정책을 문서에 분명히 적어야 합니다." },

{ kind:"api", k:"부분 수정과 전체 교체", lv:2,
  q:"프로필 수정 API 를 설계하세요. <b>일부 필드만</b> 바꾸는 요청과 <b>전체를 교체</b>하는 요청을 구분하고, 동시 수정으로 남의 변경을 덮어쓰지 않도록 하는 장치도 넣으세요.",
  src:'{\n  "endpoints": [\n    { "method": "POST", "path": "/profile/update", "status": 200, "desc": "프로필 수정" }\n  ]\n}',
  ref:{endpoints:[{method:"PATCH",path:"/profiles/{id}",status:200,errors:[400,404,412],
      headers:[{name:"If-Match",required:true,desc:"이전 응답의 ETag"}],note:"보낸 필드만 바꾼다",desc:"부분 수정"},
    {method:"PUT",path:"/profiles/{id}",status:200,errors:[400,404,412],
      headers:[{name:"If-Match",required:true,desc:"이전 응답의 ETag"}],note:"전체 교체 — 빠진 필드는 비워진다",desc:"전체 교체"}]},
  tests:[{d:"PATCH 와 PUT 을 모두 정의했다", js:"['PATCH','PUT'].every(m=>D.endpoints.some(e=>e.method===m))"},
         {d:"경로에 동사를 넣지 않았다", js:"D.endpoints.every(e=>!/\\/(update|modify|edit|save)/i.test(String(e.path)))"},
         {d:"둘 다 같은 리소스 경로를 쓴다", js:"new Set(D.endpoints.map(e=>String(e.path))).size===1"},
         {d:"동시 수정 감지를 위한 조건부 헤더가 있다", js:"D.endpoints.every(e=>(e.headers||[]).some(h=>/if-match|if-unmodified|version/i.test(h.name)))"},
         {d:"조건이 안 맞으면 412 를 낸다", js:"D.endpoints.every(e=>(e.errors||[]).indexOf(412)>=0)"},
         {d:"PUT 과 PATCH 의 차이를 설명으로 남겼다", js:"D.endpoints.filter(e=>e.method==='PUT').every(e=>/전체|교체|비워|덮어/.test(String(e.note||'')))"}],
  ex:"PUT 은 <b>전체 교체</b>라, 보내지 않은 필드는 '값이 없다' 는 뜻이 되어 지워지는 게 원칙입니다. 일부만 바꾸려고 PUT 을 쓰면 누락된 필드가 조용히 초기화됩니다.\n🔧 부분 수정은 PATCH 입니다. 다만 PATCH 는 <b>멱등하지 않을 수 있다</b>는 점에 주의하세요 — '+1 하기' 같은 연산을 담으면 두 번 보내면 두 번 적용됩니다.\n💡 동시 수정은 별개 문제입니다. A 와 B 가 같은 프로필을 열어 두고 각자 저장하면 나중 저장이 앞 변경을 통째로 덮어씁니다. `ETag` 를 받아 `If-Match` 로 되돌려 보내면, 그 사이 바뀌었을 때 서버가 412 로 거절해 사용자에게 알릴 수 있습니다." },

{ kind:"api", k:"오류 응답의 규격", lv:2,
  q:"오류 응답 형식을 <b>전 API 공통</b>으로 정하세요. 클라이언트가 <b>코드로 분기</b>할 수 있어야 하고, 어떤 필드가 왜 잘못됐는지 알 수 있어야 하며, 지원팀이 로그를 찾을 수 있어야 합니다.",
  src:'{\n  "endpoints": [\n    { "method": "POST", "path": "/orders", "status": 201, "errors": [400], "desc": "주문 생성" }\n  ]\n}',
  ref:{endpoints:[{method:"POST",path:"/orders",status:201,errors:[400,401,409,422,500],
    errorSchema:{code:"string",message:"string",fields:"[{name, reason}]",trace_id:"string"},
    note:"code 는 기계가 읽는 안정된 문자열, message 는 사람이 읽는 설명",desc:"주문 생성"}]},
  tests:[{d:"오류 응답 스키마를 정의했다", js:"D.endpoints.some(e=>e.errorSchema&&typeof e.errorSchema==='object')"},
         {d:"기계가 분기할 코드 필드가 있다", js:"D.endpoints.some(e=>Object.keys(e.errorSchema||{}).some(k=>/^code$|error_code/i.test(k)))"},
         {d:"사람이 읽을 메시지 필드가 있다", js:"D.endpoints.some(e=>Object.keys(e.errorSchema||{}).some(k=>/message|detail/i.test(k)))"},
         {d:"어떤 필드가 틀렸는지 담을 자리가 있다", js:"D.endpoints.some(e=>Object.keys(e.errorSchema||{}).some(k=>/field|errors|violations/i.test(k)))"},
         {d:"추적 ID 가 있다", js:"D.endpoints.some(e=>Object.keys(e.errorSchema||{}).some(k=>/trace|request_id|correlation/i.test(k)))"},
         {d:"서버 오류 500 도 정의돼 있다", js:"D.endpoints.some(e=>(e.errors||[]).indexOf(500)>=0)"}],
  ex:"클라이언트가 <b>메시지 문자열로 분기</b>하기 시작하면 그때부터 문구 하나 못 고칩니다. 오타를 수정했더니 앱이 깨지는 상황이 실제로 벌어집니다.\n🔧 그래서 기계가 읽는 안정된 `code`(예: `ORDER_ALREADY_PAID`)와 사람이 읽는 `message` 를 분리합니다. 다국어도 code 가 있어야 가능합니다.\n💡 검증 오류는 어떤 필드가 왜 틀렸는지 배열로 돌려줘야 폼에 항목별로 표시할 수 있습니다.\n⚠️ `trace_id` 는 지원 업무의 핵심입니다. 사용자가 캡처한 화면의 ID 하나로 서버 로그를 바로 찾을 수 있는지가, 장애 대응 시간을 몇 배로 가릅니다. RFC 9457(Problem Details)이 이런 형식의 표준안입니다." },

{ kind:"api", k:"큰 파일 업로드", lv:3,
  q:"수 GB 짜리 영상 업로드를 설계하세요. 파일 본문이 <b>API 서버를 거치지 않아야</b> 하고, 업로드 완료를 서버가 알 수 있어야 하며, 업로드 권한은 <b>시간 제한</b>이 있어야 합니다.",
  src:'{\n  "endpoints": [\n    { "method": "POST", "path": "/videos", "status": 201, "desc": "영상 업로드" }\n  ]\n}',
  ref:{endpoints:[{method:"POST",path:"/videos",status:201,errors:[400,401],
      response:{video_id:"string",upload_url:"presigned URL",expires_in:900},
      note:"본문은 스토리지로 직접 업로드한다 — API 서버를 거치지 않는다",desc:"업로드 URL 발급"},
    {method:"POST",path:"/videos/{id}/complete",status:202,errors:[404,409],
      note:"업로드 완료 통보 — 인코딩을 비동기로 시작한다",desc:"업로드 완료"},
    {method:"GET",path:"/videos/{id}",status:200,errors:[404],desc:"상태 조회"}]},
  tests:[{d:"엔드포인트가 3개다", js:"D.endpoints.length===3"},
         {d:"서명된 업로드 URL 을 발급한다", js:"/presigned|signed|upload_url/i.test(JSON.stringify(D.endpoints.map(e=>e.response||{})))"},
         {d:"그 URL 에 만료 시간이 있다", js:"/expire|ttl|expires_in/i.test(JSON.stringify(D.endpoints.map(e=>e.response||{})))"},
         {d:"업로드 완료를 알리는 엔드포인트가 있다", js:"D.endpoints.some(e=>/complete|finish|done|callback/i.test(String(e.path)))"},
         {d:"후처리는 비동기다 (202)", js:"D.endpoints.some(e=>e.status===202)"},
         {d:"진행 상태를 조회할 수 있다", js:"D.endpoints.some(e=>e.method==='GET'&&/\\{/.test(String(e.path)))"}],
  ex:"큰 파일을 API 서버로 받으면 <b>서버가 병목이자 단일 장애점</b>이 됩니다. 메모리와 대역폭을 다 먹고, 배포할 때마다 업로드가 끊깁니다.\n🔧 서명된 URL(presigned URL)을 발급해 클라이언트가 <b>스토리지에 직접</b> 올리게 합니다. API 서버는 권한만 판단하고 바이트는 만지지 않습니다.\n⚠️ 서명 URL 에 만료가 없으면 그 링크가 곧 영구 업로드 권한이 됩니다. 짧게(15분 정도) 두세요.\n💡 클라이언트가 완료를 알려 주지 않으면 서버는 언제 인코딩을 시작할지 모릅니다. 다만 완료 통보는 <b>유실될 수 있으므로</b>, 스토리지 이벤트 알림을 함께 걸어 두는 것이 실무에서는 더 안전합니다. 인코딩은 오래 걸리니 202 로 받고 상태 조회를 따로 둡니다." },

{ kind:"api", k:"호환을 깨지 않는 변경", lv:3,
  q:"이미 배포된 API 에 <b>필드를 추가</b>하고 <b>필드를 없애야</b> 합니다. 구버전 클라이언트가 깨지지 않도록 설계하세요. 없앨 필드는 언제 사라지는지 알 수 있어야 합니다.",
  src:'{\n  "endpoints": [\n    { "method": "GET", "path": "/users/{id}", "status": 200, "desc": "회원 조회" }\n  ]\n}',
  ref:{endpoints:[{method:"GET",path:"/v1/users/{id}",status:200,errors:[404],
      response:{id:"string",name:"string",display_name:"string(신규)",full_name:"string(폐기 예정)"},
      deprecated:[{field:"full_name",sunset:"2026-12-31",replacement:"display_name"}],
      headers:[{name:"Deprecation",required:false,desc:"폐기 예정 응답에 표시"}],
      note:"필드 추가는 하위 호환이다 — 제거·의미 변경만 버전을 올린다",desc:"회원 조회"}]},
  tests:[{d:"경로에 버전이 들어 있다", js:"D.endpoints.every(e=>/\\/v\\d+\\//.test(String(e.path)))"},
         {d:"응답 스키마를 적어 두었다", js:"D.endpoints.every(e=>e.response&&typeof e.response==='object')"},
         {d:"폐기 예정 필드를 목록으로 관리한다", js:"D.endpoints.some(e=>Array.isArray(e.deprecated)&&e.deprecated.length>0)"},
         {d:"폐기 필드마다 종료일이 있다", js:"D.endpoints.some(e=>(e.deprecated||[]).every(x=>/\\d{4}-\\d{2}-\\d{2}/.test(String(x.sunset||''))))"},
         {d:"대체 필드를 안내한다", js:"D.endpoints.some(e=>(e.deprecated||[]).every(x=>!!String(x.replacement||'').trim()))"},
         {d:"폐기 예정을 알리는 헤더가 있다", js:"D.endpoints.some(e=>(e.headers||[]).some(h=>/deprecat|sunset/i.test(h.name)))"}],
  ex:"<b>필드를 추가하는 것은 호환을 깨지 않습니다</b> — 모르는 필드는 무시하도록 만들어진 클라이언트라면요. 반면 <b>제거와 의미 변경</b>은 반드시 깹니다. 그래서 버전을 올려야 할 일은 생각보다 적습니다.\n🔧 없앨 필드는 즉시 지우지 말고 폐기 예정으로 표시한 뒤, <b>종료일과 대체 수단</b>을 함께 알립니다. `Deprecation`·`Sunset` 헤더가 이 목적의 표준입니다.\n💡 종료일 없는 '폐기 예정' 은 영원히 남습니다. 날짜를 못 박아야 실제로 정리됩니다.\n⚠️ 정말 지우기 전에 <b>그 필드를 아직 읽는 클라이언트가 있는지</b> 측정하세요. 응답 필드별 접근을 셀 수 없다면, 최소한 구버전 호출량이라도 봐야 합니다." },

/* ─────────── CLOUD ─────────── */
{ kind:"cloud", k:"단일 서버에서 벗어나기", lv:2,
  q:"단일 서버로 돌던 웹 서비스가 트래픽을 못 버팁니다. <b>앞단에 로드밸런서</b>를 두고 앱 서버를 여러 대로 늘리세요. 죽은 서버로 요청이 가지 않아야 하고, 세션 때문에 특정 서버에 묶이면 안 됩니다.",
  src:'{\n  "components": [\n    { "name": "app", "icon": "🖥" },\n    { "name": "db", "icon": "🗄" }\n  ],\n  "connections": []\n}',
  ref:{components:[{name:"lb",icon:"⚖",healthCheck:"/healthz"},{name:"app",icon:"🖥",scale:3,stateless:true},
        {name:"session-store",icon:"⚡",note:"세션을 외부로 빼 앱을 무상태로 만든다"},{name:"db",icon:"🗄"}],
       connections:[{from:"lb",to:"app"},{from:"app",to:"session-store"},{from:"app",to:"db"}]},
  tests:[{d:"로드밸런서가 있다", js:"D.components.some(c=>/lb|balanc|alb|nginx|proxy/i.test(c.name))"},
         {d:"앱 서버가 2대 이상이다", js:"D.components.some(c=>/app|web|api/i.test(c.name)&&Number(c.scale)>=2)"},
         {d:"헬스체크가 정의돼 있다", js:"D.components.some(c=>/health/i.test(JSON.stringify(c)))"},
         {d:"앱이 무상태임을 명시했다", js:"D.components.some(c=>/app|web|api/i.test(c.name)&&(c.stateless===true))"},
         {d:"세션을 외부 저장소로 분리했다", js:"D.components.some(c=>/session|redis|cache/i.test(c.name))"},
         {d:"로드밸런서에서 앱으로 연결이 있다", js:"D.connections.some(e=>/lb|balanc|alb|proxy/i.test(String(e.from))&&/app|web|api/i.test(String(e.to)))"}],
  ex:"수평 확장의 전제는 <b>앱이 무상태</b>라는 것입니다. 세션을 서버 메모리에 들고 있으면 요청이 다른 서버로 가는 순간 로그아웃되고, 그걸 피하려고 sticky session 을 켜면 <b>확장의 이점이 사라집니다</b> — 특정 서버가 죽으면 그 사용자들만 튕기고, 새 서버를 추가해도 기존 사용자는 옮겨가지 않습니다.\n🔧 세션을 Redis 같은 외부 저장소로 빼면 어느 서버가 받아도 같은 결과가 나옵니다.\n💡 헬스체크가 없으면 로드밸런서는 죽은 서버에도 계속 요청을 보냅니다. 다만 헬스체크 경로가 DB 까지 확인하면, DB 가 잠깐 느려질 때 <b>모든 서버가 동시에 빠져</b> 서비스 전체가 죽습니다 — 얕은 체크와 깊은 체크를 나누세요." },

{ kind:"cloud", k:"큐로 느린 작업 떼어내기", lv:2,
  q:"주문 후 이메일 발송·PDF 생성 때문에 응답이 5초씩 걸립니다. <b>큐를 도입</b>해 비동기로 처리하세요. 실패한 작업이 사라지지 않아야 하고, 무한 재시도로 큐가 막히면 안 됩니다.",
  src:'{\n  "components": [\n    { "name": "api", "icon": "🖥" },\n    { "name": "db", "icon": "🗄" }\n  ],\n  "connections": []\n}',
  ref:{components:[{name:"api",icon:"🖥"},{name:"queue",icon:"📬"},{name:"worker",icon:"⚙",scale:2,retry:{max:5,backoff:"exponential"}},
        {name:"dlq",icon:"🪦",note:"재시도 한도를 넘긴 작업을 보관한다"},{name:"db",icon:"🗄"}],
       connections:[{from:"api",to:"queue"},{from:"queue",to:"worker"},{from:"worker",to:"dlq",via:"재시도 소진"},{from:"worker",to:"db"}]},
  tests:[{d:"큐가 있다", js:"D.components.some(c=>/queue|sqs|kafka|rabbit/i.test(c.name))"},
         {d:"워커가 따로 있다", js:"D.components.some(c=>/worker|consumer|job/i.test(c.name))"},
         {d:"재시도 한도가 정해져 있다", js:"D.components.some(c=>c.retry&&typeof c.retry.max==='number')"},
         {d:"재시도에 백오프를 둔다", js:"D.components.some(c=>c.retry&&/backoff|지수|exponential/i.test(String(c.retry.backoff||'')))"},
         {d:"실패 작업을 받는 DLQ 가 있다", js:"D.components.some(c=>/dlq|dead|실패/i.test(c.name+String(c.note||'')))"},
         {d:"api → 큐 → 워커 흐름이 연결돼 있다", js:"D.connections.some(e=>/api/i.test(String(e.from))&&/queue/i.test(String(e.to))) && D.connections.some(e=>/queue/i.test(String(e.from))&&/worker/i.test(String(e.to)))"}],
  ex:"큐를 넣는 순간 시스템은 <b>결과적 일관성</b>으로 바뀝니다. 응답은 빨라지지만 '주문은 됐는데 메일은 아직' 인 시간이 생기므로, 사용자에게 그 상태를 보여 줄 방법이 필요합니다.\n🔧 재시도는 반드시 <b>한도와 백오프</b>가 있어야 합니다. 즉시 무한 재시도는 장애 중인 외부 서비스를 더 두들겨 복구를 늦추고, 그 사이 큐가 실패 작업으로 가득 차 정상 작업까지 밀립니다.\n💡 한도를 넘긴 작업은 DLQ 로 옮겨 <b>사람이 볼 수 있게</b> 남깁니다. 조용히 버리면 '메일이 안 왔다' 는 문의가 들어와도 원인을 찾을 수 없습니다.\n⚠️ 메시지는 대개 <b>최소 한 번</b> 전달됩니다 — 같은 작업이 두 번 올 수 있으므로 워커는 멱등해야 합니다." },

{ kind:"cloud", k:"읽기 복제본과 복제 지연", lv:3,
  q:"읽기 트래픽이 DB 를 압박합니다. <b>읽기 복제본</b>을 도입하되, 방금 쓴 내용을 바로 읽을 때 값이 안 보이는 문제를 다루세요.",
  src:'{\n  "components": [\n    { "name": "app", "icon": "🖥" },\n    { "name": "db-primary", "icon": "🗄" }\n  ],\n  "connections": []\n}',
  ref:{components:[{name:"app",icon:"🖥"},{name:"db-primary",icon:"🗄",role:"write"},
        {name:"db-replica",icon:"🗄",role:"read",scale:2,lagAlert:"1s"},
        {name:"monitoring",icon:"📈",note:"복제 지연을 감시한다"}],
       connections:[{from:"app",to:"db-primary",via:"쓰기"},{from:"app",to:"db-replica",via:"읽기"},
        {from:"db-primary",to:"db-replica",via:"복제"},
        {from:"app",to:"db-primary",via:"쓴 직후 읽기는 프라이머리로"}]},
  tests:[{d:"프라이머리와 복제본이 나뉘어 있다", js:"D.components.filter(c=>/db|database/i.test(c.name)).length>=2"},
         {d:"역할(읽기/쓰기)을 명시했다", js:"D.components.filter(c=>/db|database/i.test(c.name)).every(c=>/read|write|읽기|쓰기/i.test(String(c.role||'')))"},
         {d:"복제 흐름이 연결돼 있다", js:"D.connections.some(e=>/primary|master/i.test(String(e.from))&&/replica|slave/i.test(String(e.to)))"},
         {d:"쓰기는 프라이머리로 간다", js:"D.connections.some(e=>/app/i.test(String(e.from))&&/primary|master/i.test(String(e.to)))"},
         {d:"복제 지연을 감시한다", js:"/lag|지연|delay/i.test(JSON.stringify(D.components))"},
         {d:"쓴 직후 읽기를 어떻게 처리할지 적었다", js:"/직후|방금|read.your|자기가 쓴/i.test(JSON.stringify(D.connections))"}],
  ex:"복제는 <b>비동기</b>입니다. 프라이머리에 쓰고 곧바로 복제본에서 읽으면 아직 안 넘어와 <b>방금 쓴 글이 안 보입니다</b>. 사용자에게는 '저장이 안 됐다' 로 보이고, 다시 저장을 눌러 중복이 생깁니다.\n🔧 가장 단순한 해법은 '쓴 직후 일정 시간 동안 그 사용자의 읽기는 프라이머리로' 보내는 것입니다(read-your-writes). 세션에 마지막 쓰기 시각을 남겨 판단합니다.\n💡 복제 지연은 반드시 <b>지표로 감시</b>하세요. 평소 수십 ms 이던 지연이 배치 작업 중 수십 초로 튀는 일이 흔하고, 그때 서비스 곳곳에서 설명하기 어려운 버그가 동시에 나타납니다.\n⚠️ 복제본을 늘려도 <b>쓰기는 전혀 나아지지 않습니다</b>. 쓰기가 병목이면 샤딩이나 구조 변경이 필요합니다." },

{ kind:"cloud", k:"캐시와 무효화", lv:3,
  q:"상품 상세 조회가 DB 를 압박합니다. <b>캐시 계층</b>을 도입하되, 가격이 바뀌었을 때 옛 값이 계속 나가지 않도록 하고, 캐시가 비었을 때 요청이 한꺼번에 DB 로 몰리지 않도록 하세요.",
  src:'{\n  "components": [\n    { "name": "app", "icon": "🖥" },\n    { "name": "db", "icon": "🗄" }\n  ],\n  "connections": []\n}',
  ref:{components:[{name:"app",icon:"🖥"},{name:"cache",icon:"⚡",ttl:"300s",stampedeGuard:"단일 갱신 잠금 + 지터"},
        {name:"db",icon:"🗄"}],
       connections:[{from:"app",to:"cache",via:"조회"},{from:"app",to:"db",via:"캐시 미스"},
        {from:"app",to:"cache",via:"가격 변경 시 무효화"}]},
  tests:[{d:"캐시 구성 요소가 있다", js:"D.components.some(c=>/cache|redis|memcach|cdn/i.test(c.name))"},
         {d:"TTL 이 정해져 있다", js:"D.components.some(c=>/ttl|만료|expire/i.test(JSON.stringify(c)))"},
         {d:"동시 갱신 폭주(스탬피드) 대책이 있다", js:"D.components.some(c=>/stampede|잠금|lock|single.?flight|지터|jitter/i.test(JSON.stringify(c)))"},
         {d:"캐시 미스 시 DB 로 가는 경로가 있다", js:"D.connections.some(e=>/db/i.test(String(e.to))&&/미스|miss/i.test(String(e.via||'')))"},
         {d:"변경 시 무효화 경로가 있다", js:"D.connections.some(e=>/무효|invalidat|evict|삭제/i.test(String(e.via||'')))"}],
  ex:"캐시의 어려움은 넣는 게 아니라 <b>지우는 것</b>입니다. TTL 만 두면 '가격을 바꿨는데 5분간 옛 가격으로 팔리는' 창이 생깁니다. 변경 시점에 <b>능동적으로 무효화</b>하고 TTL 은 안전망으로 두는 것이 보통입니다.\n⚠️ 인기 키가 만료되는 순간 그 키를 기다리던 요청이 <b>전부 동시에</b> DB 로 갑니다(캐시 스탬피드). 인기 상품 하나가 DB 를 넘어뜨릴 수 있습니다.\n🔧 대책은 두 가지를 함께 씁니다 — 갱신은 한 요청만 하도록 잠그고(single-flight), TTL 에 무작위 지터를 더해 만료 시점을 흩뿌립니다.\n💡 '캐시에 없으면 DB' 는 반대로도 위험합니다. 존재하지 않는 키를 계속 조회하면 매번 DB 로 가므로(캐시 관통), '없음' 도 짧게 캐시해야 합니다." },

{ kind:"cloud", k:"장애 구역을 견디는 이중화", lv:3,
  q:"한 데이터센터(가용 영역)가 통째로 죽어도 서비스가 계속되도록 설계하세요. <b>모든 계층</b>이 두 영역 이상에 걸쳐야 하고, DB 는 자동 승격이 가능해야 합니다.",
  src:'{\n  "components": [\n    { "name": "lb", "icon": "⚖" },\n    { "name": "app", "icon": "🖥", "scale": 2, "az": "a" },\n    { "name": "db-primary", "icon": "🗄", "az": "a" }\n  ],\n  "connections": []\n}',
  ref:{components:[{name:"lb",icon:"⚖",az:["a","b"]},{name:"app",icon:"🖥",scale:4,az:["a","b"]},
        {name:"db-primary",icon:"🗄",az:"a",failover:"자동 승격"},{name:"db-standby",icon:"🗄",az:"b",role:"standby"}],
       connections:[{from:"lb",to:"app"},{from:"app",to:"db-primary"},{from:"db-primary",to:"db-standby",via:"동기 복제"}]},
  tests:[{d:"모든 구성 요소가 영역 정보를 갖는다", js:"D.components.every(c=>!!c.az)"},
         {d:"앱이 두 영역 이상에 걸쳐 있다", js:"D.components.some(c=>/app|web|api/i.test(c.name)&&Array.isArray(c.az)&&c.az.length>=2)"},
         {d:"로드밸런서도 여러 영역에 있다", js:"D.components.some(c=>/lb|balanc/i.test(c.name)&&Array.isArray(c.az)&&c.az.length>=2)"},
         {d:"DB 대기 노드가 다른 영역에 있다", js:"(function(){var p=D.components.find(c=>/primary/i.test(c.name)),s=D.components.find(c=>/standby|replica|secondary/i.test(c.name));return !!p&&!!s&&String(p.az)!==String(s.az);})()"},
         {d:"자동 장애 조치를 명시했다", js:"/failover|승격|promote|자동/i.test(JSON.stringify(D.components))"},
         {d:"DB 복제 연결이 있다", js:"D.connections.some(e=>/primary/i.test(String(e.from))&&/standby|replica|secondary/i.test(String(e.to)))"}],
  ex:"이중화는 <b>가장 약한 계층</b>이 결정합니다. 앱을 두 영역에 두어도 DB 가 한 영역에만 있으면 그 영역이 죽는 순간 전체가 멈춥니다 — 로드밸런서 자체도 마찬가지입니다.\n💡 DB 이중화에는 대가가 있습니다. <b>동기 복제</b>는 데이터를 잃지 않지만 영역 간 왕복만큼 쓰기가 느려지고, <b>비동기</b>는 빠르지만 장애 시 마지막 몇 초가 사라집니다. 어느 쪽을 택할지는 '얼마까지 잃어도 되는가'(RPO)로 정합니다.\n⚠️ 자동 장애 조치는 <b>정기적으로 실제로 시험해야</b> 합니다. 설정만 해 두고 한 번도 안 돌려 본 승격은 정작 필요할 때 실패합니다. 게임데이·카오스 테스트가 그래서 존재합니다." },

{ kind:"cloud", k:"비밀은 코드에 넣지 않는다", lv:2,
  q:"DB 비밀번호와 외부 API 키를 안전하게 다루도록 설계하세요. 저장소·이미지에 비밀이 들어가면 안 되고, <b>주기적 교체</b>가 가능해야 하며, 누가 언제 꺼내 갔는지 남아야 합니다.",
  src:'{\n  "components": [\n    { "name": "app", "icon": "🖥", "env": ["DB_PASSWORD=hunter2"] },\n    { "name": "db", "icon": "🗄" }\n  ],\n  "connections": []\n}',
  ref:{components:[{name:"app",icon:"🖥",secretsFrom:"secret-manager",iamRole:"app-role(최소 권한)"},
        {name:"secret-manager",icon:"🔐",rotation:"90일 자동 교체",audit:true},
        {name:"db",icon:"🗄"},{name:"audit-log",icon:"📜"}],
       connections:[{from:"app",to:"secret-manager",via:"실행 시 조회"},{from:"app",to:"db"},
        {from:"secret-manager",to:"audit-log",via:"접근 기록"}]},
  tests:[{d:"비밀 관리 서비스가 있다", js:"D.components.some(c=>/secret|vault|kms|parameter/i.test(c.name))"},
         {d:"설계 어디에도 비밀 값이 하드코딩돼 있지 않다", js:"!/hunter2|password\\s*=\\s*['\\\"]?[A-Za-z0-9]{4,}/i.test(JSON.stringify(D))"},
         {d:"앱이 실행 시점에 비밀을 가져온다", js:"D.connections.some(e=>/app/i.test(String(e.from))&&/secret|vault|kms/i.test(String(e.to)))"},
         {d:"교체 주기가 정해져 있다", js:"/rotat|교체|갱신/i.test(JSON.stringify(D.components))"},
         {d:"접근이 감사 로그로 남는다", js:"D.components.some(c=>/audit|감사/i.test(c.name)) || /audit/i.test(JSON.stringify(D.components))"},
         {d:"최소 권한 원칙을 명시했다", js:"/최소 권한|least privilege|iam/i.test(JSON.stringify(D.components))"}],
  ex:"저장소에 한 번 들어간 비밀은 <b>지워도 히스토리에 남습니다</b>. 커밋을 되돌려도 이전 커밋에서 그대로 꺼낼 수 있으므로, 유출된 순간 교체 말고는 답이 없습니다.\n🔧 비밀은 실행 시점에 비밀 관리 서비스에서 가져오고, 접근 권한은 사람이 아니라 <b>역할(IAM Role)</b>에 붙입니다. 그래야 서버가 바뀌어도 키를 옮겨 다닐 필요가 없습니다.\n💡 자동 교체는 '유출됐을 때 유효 기간을 짧게' 만드는 장치입니다. 교체가 자동이 아니면 아무도 안 합니다.\n⚠️ 감사 로그가 없으면 유출을 <b>탐지할 수도, 범위를 특정할 수도</b> 없습니다. 사고가 났을 때 '무엇이 노출됐나' 에 답하지 못하면 전부 교체해야 합니다." },

{ kind:"cloud", k:"무엇이 느린지 알 수 있는 구조", lv:3,
  q:"'가끔 느리다' 는 신고가 들어오는데 원인을 못 찾습니다. <b>관측 가능한</b> 구조로 바꾸세요. 요청 하나를 서비스 경계 너머까지 따라갈 수 있어야 하고, 지표에는 평균이 아닌 값이 필요합니다.",
  src:'{\n  "components": [\n    { "name": "api", "icon": "🖥" },\n    { "name": "worker", "icon": "⚙" },\n    { "name": "db", "icon": "🗄" }\n  ],\n  "connections": []\n}',
  ref:{components:[{name:"api",icon:"🖥",traceId:"요청마다 발급·전파"},{name:"worker",icon:"⚙",traceId:"메시지에 실어 전파"},
        {name:"db",icon:"🗄"},{name:"metrics",icon:"📈",percentiles:["p50","p95","p99"],slo:"p99 < 300ms"},
        {name:"tracing",icon:"🧵"},{name:"logs",icon:"📜",structured:true}],
       connections:[{from:"api",to:"tracing",via:"스팬 전송"},{from:"worker",to:"tracing",via:"같은 trace_id"},
        {from:"api",to:"metrics"},{from:"api",to:"logs"}]},
  tests:[{d:"지표·로그·추적이 모두 있다", js:"['metric','log','trac'].every(k=>D.components.some(c=>new RegExp(k,'i').test(c.name)))"},
         {d:"추적 ID 를 발급하고 전파한다", js:"D.components.filter(c=>/api|worker/i.test(c.name)).every(c=>/trace|correlation/i.test(JSON.stringify(c)))"},
         {d:"평균이 아니라 백분위를 본다", js:"D.components.some(c=>Array.isArray(c.percentiles)&&c.percentiles.some(p=>/p9[59]/i.test(p)))"},
         {d:"목표치(SLO)가 숫자로 적혀 있다", js:"/slo|목표/i.test(JSON.stringify(D.components)) && /\\d+\\s*ms|\\d+%/.test(JSON.stringify(D.components))"},
         {d:"로그가 구조화돼 있다", js:"D.components.some(c=>/log/i.test(c.name)&&c.structured===true)"},
         {d:"비동기 경계 너머로도 추적이 이어진다", js:"D.connections.some(e=>/worker/i.test(String(e.from))&&/trac/i.test(String(e.to)))"}],
  ex:"<b>평균 응답 시간은 장애를 숨깁니다.</b> 100건 중 1건이 10초 걸려도 평균은 거의 안 움직입니다. 사용자가 느끼는 것은 p95·p99 이고, '가끔 느리다' 는 신고는 정확히 그 꼬리 구간입니다.\n🔧 지표(무엇이 얼마나)·로그(무슨 일이)·추적(어디서 시간을 썼는지)은 서로를 대체하지 못합니다. 셋을 <b>trace_id 로 엮어야</b> 지표에서 이상을 발견하고 → 해당 추적을 열고 → 그 시점 로그로 내려가는 흐름이 완성됩니다.\n⚠️ 가장 자주 끊기는 곳이 <b>큐 경계</b>입니다. API 는 추적되는데 워커는 별개 세계라, 비동기 처리에 들어간 순간 시간이 어디로 갔는지 사라집니다. 메시지에 trace_id 를 실어 보내야 합니다.\n💡 목표치를 숫자로 못 박지 않으면 '느리다' 는 영원히 주관입니다. p99 < 300ms 처럼 적어 두면 경보를 걸 수 있습니다." },

{ kind:"cloud", k:"쓰지 않는 데이터에 돈을 쓰지 않는다", lv:2,
  q:"스토리지 비용이 매달 늘어납니다. 로그와 업로드 파일에 <b>수명 주기 정책</b>을 적용해 비용을 줄이되, 규정상 보관 기간은 지켜야 합니다. 삭제 전 되돌릴 수 있어야 합니다.",
  src:'{\n  "components": [\n    { "name": "storage", "icon": "🪣" },\n    { "name": "logs", "icon": "📜" }\n  ],\n  "connections": []\n}',
  ref:{components:[{name:"storage",icon:"🪣",lifecycle:[{after:"30일",action:"저빈도 계층으로 이동"},{after:"180일",action:"아카이브"},{after:"2555일",action:"삭제"}],versioning:true},
        {name:"logs",icon:"📜",retention:"90일",lifecycle:[{after:"14일",action:"압축·저빈도"},{after:"90일",action:"삭제"}]},
        {name:"cost-alarm",icon:"💰",threshold:"월 예산 120% 시 경보"}],
       connections:[{from:"storage",to:"cost-alarm"},{from:"logs",to:"cost-alarm"}]},
  tests:[{d:"수명 주기 정책이 있다", js:"D.components.some(c=>Array.isArray(c.lifecycle)&&c.lifecycle.length>=2)"},
         {d:"단계마다 기간과 동작이 적혀 있다", js:"D.components.filter(c=>Array.isArray(c.lifecycle)).every(c=>c.lifecycle.every(s=>!!s.after&&!!s.action))"},
         {d:"바로 지우지 않고 저렴한 계층을 거친다", js:"D.components.some(c=>(c.lifecycle||[]).some(s=>/저빈도|아카이브|archive|infrequent|glacier|cold/i.test(String(s.action))))"},
         {d:"최종 삭제 단계가 있다", js:"D.components.some(c=>(c.lifecycle||[]).some(s=>/삭제|delete|expire/i.test(String(s.action))))"},
         {d:"실수 삭제를 되돌릴 수단이 있다", js:"D.components.some(c=>c.versioning===true) || /버전|versioning|백업|backup/i.test(JSON.stringify(D.components))"},
         {d:"비용 경보가 있다", js:"D.components.some(c=>/cost|비용|budget|예산/i.test(c.name+JSON.stringify(c)))"}],
  ex:"비용은 <b>지우지 않아서</b> 늘어납니다. 대부분의 데이터는 처음 며칠만 읽히고 그 뒤로는 거의 안 읽히는데, 계속 가장 비싼 계층에 놓여 있습니다.\n🔧 수명 주기 정책으로 '30일 뒤 저빈도 → 180일 뒤 아카이브 → N년 뒤 삭제' 를 자동화합니다. 사람이 판단하는 구조로 두면 아무도 안 지웁니다.\n⚠️ 아카이브 계층은 <b>꺼낼 때 비싸고 느립니다</b>. 가끔이라도 조회해야 하는 데이터를 넣으면 오히려 비용이 늘 수 있으니, 접근 패턴을 보고 결정하세요.\n💡 삭제는 되돌릴 수 없으니 버전 관리나 삭제 보호를 켜 두어야 합니다. 그리고 보관 기간은 <b>비용이 아니라 규정</b>이 정합니다 — 세무·개인정보 관련 기록은 법정 기간을 먼저 확인해야 합니다.\n📈 마지막으로 비용 경보가 없으면 다음 달 청구서를 보고서야 알게 됩니다." },
];
