/* mleval 트랙 설계 문항 — 평가·실험 파이프라인을 직접 그린다.
   ref 는 검증용 참조 설계다(주입하지 않는다). */
module.exports = [
{ t: "arch", kind: "cloud", k: "회귀를 잡는 평가 파이프라인", lv: 2, cat: "design", track: "mleval",
  q: "모델을 바꿀 때마다 <b>어디가 나빠졌는지</b>를 배포 뒤에 알게 됩니다. 사람이 표를 보고 판단하는 대신, <b>기준을 넘지 못하면 막히는</b> 평가 파이프라인을 그리세요.",
  src: '{\n  "components": [\n    { "name": "eval-job", "icon": "📏" }\n  ],\n  "connections": []\n}',
  ref: { components: [
      { name: "golden-set", icon: "🥇", note: "버전으로 고정한다 — latest 를 가리키면 어제와 오늘을 견줄 수 없다" },
      { name: "eval-job", icon: "📏", note: "모델 해시·데이터 버전·임계값을 입력으로 받고 실제 추론 건수를 남긴다" },
      { name: "slice-report", icon: "🧩", note: "언어·기기·신규/기존 등 미리 정한 축마다 지표를 따로 낸다" },
      { name: "gate", icon: "🚧", note: "전체 지표와 슬라이스 하한을 모두 만족해야 통과. 하나라도 깨지면 막는다" },
      { name: "baseline-store", icon: "📚", note: "직전 승격 모델의 점수를 보관해 비교 기준으로 쓴다" }],
    connections: [{ from: "golden-set", to: "eval-job" }, { from: "eval-job", to: "slice-report" },
      { from: "baseline-store", to: "gate" }, { from: "slice-report", to: "gate" }],
    versioned: "평가 데이터는 버전 고정 — 자가 바뀌면 어제와 오늘을 견줄 수 없다" },
  tests: [
    { d: "평가 데이터를 버전으로 고정한다고 적었다", js: "/버전|version|고정/i.test(JSON.stringify(D))" },
    { d: "슬라이스별 지표를 내는 자리가 있다", js: "(D.components||[]).some(c=>/slice|슬라이스|세그먼트/i.test(c.name+' '+(c.note||'')))" },
    { d: "기준을 넘지 못하면 막는 관문이 있다", js: "(D.components||[]).some(c=>/gate|관문|게이트/i.test(c.name+' '+(c.note||'')))" },
    { d: "직전 모델과 비교할 기준선을 둔다", js: "(D.components||[]).some(c=>/baseline|기준선|직전/i.test(c.name+' '+(c.note||'')))" },
    { d: "실제 추론을 했는지 기록한다고 적었다", js: "/추론 건수|건수|캐시|실행 여부/i.test(JSON.stringify(D))" }],
  ex: "🎯 평가가 <b>보고서</b>이면 사람이 읽고 넘어가지만, <b>관문</b>이면 통과하지 못한 모델이 배포되지 않습니다. 이 차이가 회귀를 잡느냐 못 잡느냐를 가릅니다.\n🔧 전체 평균만으로는 소수 집단의 붕괴가 보이지 않으므로 <b>슬라이스별 하한</b>을 함께 겁니다. 그리고 비교 대상은 '좋아 보이는 숫자' 가 아니라 <b>직전 승격 모델의 점수</b>입니다.\n💡 평가 데이터가 바뀌면 점수 변화가 모델 때문인지 자 때문인지 알 수 없습니다. <code>latest</code> 대신 버전을 가리키고, 갱신할 때는 한동안 두 버전을 함께 돌립니다.\n⚠️ 캐시가 옛 예측을 돌려주면 무엇을 올려도 같은 점수가 나옵니다. 실행 로그에 <b>실제 추론 건수</b>를 남기고 0 이면 실패로 처리하세요." },

{ t: "arch", kind: "cloud", k: "A/B 실험을 신뢰할 수 있게", lv: 3, cat: "design", track: "mleval",
  q: "A/B 결과가 나올 때마다 '이거 믿어도 되냐' 는 질문이 붙습니다. <b>배정·집계·판정</b>이 어디서 어긋날 수 있는지 드러나도록 실험 시스템을 설계하세요.",
  src: '{\n  "components": [\n    { "name": "assigner", "icon": "🎲" },\n    { "name": "metrics", "icon": "📊" }\n  ],\n  "connections": []\n}',
  ref: { components: [
      { name: "assigner", icon: "🎲", note: "사용자 id 해시로 결정적으로 배정하고 배정 사실을 그 자리에서 기록한다" },
      { name: "exposure-log", icon: "📝", note: "배정된 순간을 남긴다 — 화면이 떴는지와 무관하게 의도 기준으로 집계한다" },
      { name: "srm-check", icon: "⚖️", note: "실제 분배 비율이 설계와 다른지 검정한다. 깨지면 결과를 읽기 전에 파이프라인을 본다" },
      { name: "metrics", icon: "📊", note: "사전 등록한 주 지표 하나와 보조 지표 — 표본 크기와 기간을 미리 정한다" },
      { name: "decision", icon: "🧑‍⚖️", note: "정해진 표본에 도달한 뒤 한 번만 판정한다" }],
    connections: [{ from: "assigner", to: "exposure-log" }, { from: "exposure-log", to: "srm-check" },
      { from: "exposure-log", to: "metrics" }, { from: "srm-check", to: "decision" }, { from: "metrics", to: "decision" }],
    peeking: "중간에 들여다보고 멈추지 않는다 — 사전 등록한 표본과 기간을 지킨다" },
  tests: [
    { d: "배정을 결정적으로 한다고 적었다", js: "/해시|hash|결정적|deterministic/i.test(JSON.stringify(D))" },
    { d: "배정 사실을 남기는 로그가 있다", js: "(D.components||[]).some(c=>/exposure|배정|assign|로그/i.test(c.name+' '+(c.note||'')))" },
    { d: "분배 비율이 설계와 같은지 검정한다", js: "(D.components||[]).some(c=>/srm|분배|비율/i.test(c.name+' '+(c.note||'')))" },
    { d: "표본 크기와 기간을 미리 정한다고 적었다", js: "/사전|미리 정|표본 크기|기간/i.test(JSON.stringify(D))" },
    { d: "중간에 멈추지 않는다는 규칙을 적었다", js: "/peek|들여다|한 번만|조기 종료/i.test(JSON.stringify(D))" },
    { d: "판정 단계가 다른 단계에서 이어진다", js: "(D.connections||[]).filter(e=>/decision|판정/i.test(e.to)).length>=2" }],
  ex: "🎯 A/B 의 신뢰는 통계식이 아니라 <b>파이프라인</b>에서 옵니다. 배정이 치우치거나 집계에서 일부가 빠지면, 어떤 검정을 써도 결론은 틀립니다.\n🔧 배정은 사용자 id 해시로 <b>결정적</b>이어야 같은 사람이 늘 같은 갈래를 봅니다. 집계는 <b>의도 기준</b>으로 — 배정된 순간 포함하고, 화면이 안 떴다고 빼면 생존 편향이 생깁니다.\n💡 <b>SRM 검정</b>은 가장 값싼 안전장치입니다. 50:50 으로 설계했는데 54:46 이 나왔다면 결과를 읽기 전에 파이프라인부터 봐야 합니다.\n⚠️ p 값을 계속 보다가 낮아진 순간 멈추면 1종 오류가 몇 배로 부풀어 오릅니다. 표본과 기간을 <b>먼저 정하고</b>, 중간에 봐야 한다면 순차 검정처럼 보정된 방법을 씁니다." },

{ t: "arch", kind: "cloud", k: "위험 없이 실제 입력으로 재 보기", lv: 3, cat: "design", track: "mleval",
  q: "새 모델을 사용자에게 노출하기 전에 <b>실제 트래픽으로</b> 재 보고 싶습니다. 응답 품질과 지연, 비용까지 보되 <b>사용자에게는 영향이 가지 않아야</b> 합니다.",
  src: '{\n  "components": [\n    { "name": "api", "icon": "🖥️" },\n    { "name": "model-v2", "icon": "🧠" }\n  ],\n  "connections": []\n}',
  ref: { components: [
      { name: "api", icon: "🖥️", note: "사용자 응답은 언제나 현행 모델의 것을 돌려준다" },
      { name: "model-v1", icon: "🧠", note: "현행" },
      { name: "model-v2", icon: "🧠", note: "후보 — 같은 입력을 받지만 응답은 버린다" },
      { name: "mirror", icon: "🪞", note: "요청을 비동기로 복제한다. 실패해도 사용자 경로에 영향을 주지 않는다" },
      { name: "compare", icon: "🔬", note: "두 응답의 차이·지연·비용을 기록하고 차이가 큰 사례를 모아 둔다" }],
    connections: [{ from: "api", to: "model-v1" }, { from: "api", to: "mirror" },
      { from: "mirror", to: "model-v2" }, { from: "model-v1", to: "compare" }, { from: "model-v2", to: "compare" }],
    isolation: "복제는 비동기이고 실패해도 사용자 응답에 영향을 주지 않는다. 부수효과가 있는 호출은 복제하지 않는다" },
  tests: [
    { d: "요청을 복제하는 구성 요소가 있다", js: "(D.components||[]).some(c=>/mirror|shadow|복제|섀도/i.test(c.name+' '+(c.note||'')))" },
    { d: "사용자 응답은 현행 모델의 것이라고 적었다", js: "/현행|기존 모델|응답은 버린|v1/i.test(JSON.stringify(D))" },
    { d: "두 응답을 비교하는 자리가 있다", js: "(D.components||[]).some(c=>/compare|비교|대조/i.test(c.name+' '+(c.note||'')))" },
    { d: "복제가 사용자 경로에 영향을 주지 않는다고 적었다", js: "/비동기|영향을 주지|격리|버린다/i.test(JSON.stringify(D))" },
    { d: "지연이나 비용도 함께 잰다고 적었다", js: "/지연|latency|비용|cost/i.test(JSON.stringify(D))" },
    { d: "부수효과가 있는 호출은 복제하지 않는다고 적었다", js: "/부수효과|쓰기|결제|side.?effect/i.test(JSON.stringify(D))" }],
  ex: "🎯 섀도 트래픽은 <b>실제 분포</b>로 재는 유일한 방법입니다. 오프라인 세트는 아무리 잘 만들어도 지금 들어오는 입력과 다릅니다.\n🔧 핵심은 <b>격리</b>입니다. 복제는 비동기로 하고, 후보 모델이 느리거나 죽어도 사용자 응답은 그대로여야 합니다. 응답은 비교에만 쓰고 버립니다.\n💡 품질뿐 아니라 <b>지연과 비용</b>도 이 단계에서 드러납니다. 점수가 조금 좋아졌는데 비용이 세 배라면 그것은 개선이 아니라 선택의 문제입니다.\n⚠️ 결제나 저장처럼 <b>부수효과가 있는 호출</b>은 절대 복제하면 안 됩니다. 복제 대상 경로를 화이트리스트로 정하는 편이 안전합니다." },

{ t: "arch", kind: "cloud", k: "늦게 오는 정답을 기다리는 감시", lv: 3, cat: "design", track: "mleval",
  q: "정답 라벨이 <b>며칠 뒤에야</b> 도착합니다(환불 여부는 30일 뒤에 확정됩니다). 그때까지 모델이 잘 돌고 있는지 알 수 없습니다. 지연 라벨을 전제로 감시 구조를 설계하세요.",
  src: '{\n  "components": [\n    { "name": "serving", "icon": "🖥️" },\n    { "name": "metrics", "icon": "📊" }\n  ],\n  "connections": []\n}',
  ref: { components: [
      { name: "serving", icon: "🖥️", note: "예측과 입력 특성을 함께 기록한다" },
      { name: "prediction-log", icon: "🧾", note: "예측 id·시각·특성·예측값을 남겨 나중에 라벨과 이어 붙인다" },
      { name: "label-join", icon: "🔗", note: "라벨이 도착하면 예측 id 로 결합한다. 아직 안 온 것은 미확정으로 둔다" },
      { name: "proxy-monitor", icon: "🕒", note: "라벨을 기다리는 동안 입력 분포와 예측 분포 변화를 감시한다" },
      { name: "delayed-metrics", icon: "📊", note: "라벨이 충분히 모인 코호트만 지표를 확정한다" }],
    connections: [{ from: "serving", to: "prediction-log" }, { from: "prediction-log", to: "label-join" },
      { from: "prediction-log", to: "proxy-monitor" }, { from: "label-join", to: "delayed-metrics" }],
    cohort: "코호트별로 라벨 성숙도를 표시한다 — 성숙하지 않은 구간의 지표는 확정하지 않는다" },
  tests: [
    { d: "예측을 나중에 이어 붙일 수 있게 기록한다", js: "(D.components||[]).some(c=>/prediction|예측 로그|log/i.test(c.name+' '+(c.note||'')))" },
    { d: "라벨을 예측과 결합하는 자리가 있다", js: "(D.components||[]).some(c=>/join|결합|이어|match/i.test(c.name+' '+(c.note||'')))" },
    { d: "라벨을 기다리는 동안 볼 대리 지표가 있다", js: "(D.components||[]).some(c=>/proxy|분포|drift|대리/i.test(c.name+' '+(c.note||'')))" },
    { d: "라벨이 덜 모인 구간은 확정하지 않는다고 적었다", js: "/성숙|미확정|충분히 모인|확정하지/i.test(JSON.stringify(D))" },
    { d: "예측을 식별할 id 를 남긴다고 적었다", js: "/예측 id|prediction id|id 로/i.test(JSON.stringify(D))" }],
  ex: "🎯 라벨이 늦게 오는 문제에서 가장 흔한 실수는 <b>덜 모인 구간의 지표를 확정</b>하는 것입니다. 최근 일주일은 라벨이 아직 안 왔을 뿐인데 성능이 떨어진 것처럼 보입니다.\n🔧 예측 시점에 <b>id·특성·예측값</b>을 남겨 두면 라벨이 도착했을 때 이어 붙일 수 있습니다. 코호트마다 '라벨이 몇 % 도착했는가' 를 표시하고, 기준을 넘은 코호트만 지표를 확정합니다.\n💡 기다리는 동안에는 <b>대리 신호</b>를 봅니다 — 입력 분포와 예측 분포의 변화는 라벨 없이도 잴 수 있고, 큰 사고는 대개 여기서 먼저 보입니다.\n⚠️ 라벨이 <b>선택적으로</b> 도착하기도 합니다. 환불한 사람만 기록이 남는다면 그 라벨은 편향돼 있으므로, 도착하지 않은 것을 '음성' 으로 채우면 지표가 통째로 왜곡됩니다." },

{ t: "arch", kind: "cloud", k: "실험 결과를 쌓아 두는 곳", lv: 2, cat: "design", track: "mleval",
  q: "실험 결과가 사람마다 다른 스프레드시트에 있습니다. <b>같은 실험을 두 번 돌리거나</b>, 지난달 결론을 아무도 못 찾습니다. 결과가 남고 비교되는 구조를 설계하세요.",
  src: '{\n  "components": [\n    { "name": "eval-job", "icon": "📏" }\n  ],\n  "connections": []\n}',
  ref: { components: [
      { name: "eval-job", icon: "📏", note: "실행할 때 코드 커밋·데이터 버전·설정을 함께 기록한다" },
      { name: "run-store", icon: "🗂️", note: "실행 하나가 한 행 — 입력·지표·산출물 경로를 남긴다" },
      { name: "artifact-store", icon: "📦", note: "예측 결과와 리포트를 실행 id 로 보관한다" },
      { name: "compare-view", icon: "📈", note: "두 실행을 나란히 두고 슬라이스별 차이와 신뢰구간을 보여 준다" },
      { name: "search", icon: "🔎", note: "설정으로 지난 실행을 찾아 같은 실험을 다시 돌리지 않게 한다" }],
    connections: [{ from: "eval-job", to: "run-store" }, { from: "eval-job", to: "artifact-store" },
      { from: "run-store", to: "compare-view" }, { from: "run-store", to: "search" }],
    interval: "비교 화면은 점 추정만이 아니라 불확실성 구간을 함께 보여 준다" },
  tests: [
    { d: "실행 기록을 남기는 저장소가 있다", js: "(D.components||[]).some(c=>/run|기록|store|tracker/i.test(c.name+' '+(c.note||'')))" },
    { d: "산출물을 실행 id 로 보관한다", js: "(D.components||[]).some(c=>/artifact|산출물|리포트/i.test(c.name+' '+(c.note||'')))" },
    { d: "두 실행을 비교하는 화면이 있다", js: "(D.components||[]).some(c=>/compare|비교/i.test(c.name+' '+(c.note||'')))" },
    { d: "신뢰구간이나 불확실성을 함께 본다고 적었다", js: "/신뢰구간|불확실|부트스트랩|구간/i.test(JSON.stringify(D))" },
    { d: "입력(코드·데이터·설정)을 함께 기록한다고 적었다", js: "/커밋|데이터 버전|설정|하이퍼/i.test(JSON.stringify(D))" }],
  ex: "🎯 실험은 <b>비교</b>가 목적이고, 비교하려면 남아 있어야 합니다. 스프레드시트가 나쁜 이유는 형식이 아니라 <b>입력이 함께 남지 않기</b> 때문입니다.\n🔧 실행 하나를 한 행으로 보고 코드 커밋·데이터 버전·설정·지표·산출물 경로를 함께 남깁니다. 그러면 '이 점수는 어떤 조건에서 나왔나' 에 언제든 답할 수 있고, 같은 조건을 다시 돌릴 일도 없어집니다.\n💡 비교 화면에는 점 추정만 두면 안 됩니다. <b>불확실성 구간</b>이 함께 보여야 0.4%p 차이를 개선이라고 부르지 않게 됩니다.\n⚠️ 기록이 늘면 검색이 문제입니다. 설정으로 지난 실행을 찾을 수 있어야 '누가 이거 해 봤나요' 라는 질문이 사라집니다." },
];
