/* 백엔드 4차 — 실습이 하나도 없던 6개 유닛. JS 로 채점한다.

   서버가 없어도 판단은 연습할 수 있다. 상태 코드 고르기, 토큰 검증,
   N+1 세기, 캐시 무효화, 재시도 판정은 전부 순수 함수다. */
module.exports = [
/* ── REST API 설계 ───────────────────────────────────────── */
{
  unit: "REST API 설계",
  lesson: "직접 짜 보기 — 무엇을 돌려줄지 정하는 일",
  th: {
    sum: "REST 설계의 대부분은 **자원 이름과 상태 코드를 고르는 일**이다. 둘 다 약속이라 지켜야 뜻이 통한다.",
    body: [
      { h: "자원은 명사, 동작은 메서드", t: "`/getUser?id=1` 대신 `GET /users/1` 이다. 동사를 URL 에 넣기 시작하면 `/getUserById`, `/fetchUser`, `/loadUser` 가 함께 자란다 — 메서드가 이미 동사를 맡고 있으니 URL 은 '무엇' 만 가리키면 된다." },
      { h: "상태 코드는 부르는 쪽의 다음 행동을 정한다", t: "400 은 '고쳐서 다시 보내라', 401 은 '로그인하라', 403 은 '로그인해도 안 된다', 404 는 '없다', 409 는 '지금 상태와 충돌한다', 500 은 '우리 잘못이니 재시도해 볼 만하다'. 전부 200 으로 주고 본문에 넣으면 클라이언트가 판단할 근거가 사라진다." },
      { h: "PUT 은 통째로, PATCH 는 일부", t: "PUT 은 보낸 것으로 통째로 바꾸는 것이라, 빠뜨린 필드는 지워지는 게 맞다. 일부만 고칠 거면 PATCH 다 — 이 둘을 섞으면 '수정했더니 다른 값이 사라졌다' 가 된다." },
      { h: "목록은 언제나 페이지로 자른다", t: "지금 백 건이라도 언젠가 백만 건이 된다. 처음부터 상한을 두고 자르면, 나중에 API 를 바꾸느라 클라이언트를 전부 고치는 일이 없다." },
    ],
    code: { c: "GET    /users        목록\nGET    /users/1      하나\nPOST   /users        만들기 → 201\nPUT    /users/1      통째로 바꾸기\nPATCH  /users/1      일부만\nDELETE /users/1      → 204", cap: "이름은 명사, 동작은 메서드" },
    key: ["URL 에 동사를 넣지 않는다", "상태 코드는 다음 행동을 정한다", "목록은 반드시 자른다"],
  },
  q: [
    {
      k: "statusFor · 어떤 코드를 줄 것인가",
      qq: "상황 문자열을 받아 상태 코드를 돌려주세요. <code>'ok'</code>→200, <code>'created'</code>→201, <code>'badInput'</code>→400, <code>'noAuth'</code>→401, <code>'forbidden'</code>→403, <code>'missing'</code>→404, <code>'conflict'</code>→409, 그 밖은 500 입니다.",
      src: "function statusFor(kind) {\n  return kind === 'ok' ? 200 : 400;\n}\n",
      sol: "function statusFor(kind) {\n  const m = { ok: 200, created: 201, badInput: 400, noAuth: 401, forbidden: 403, missing: 404, conflict: 409 };\n  return m[kind] ?? 500;\n}\n",
      tests: [["statusFor('created')", "201"], ["statusFor('noAuth')", "401"], ["statusFor('forbidden')", "403"]],
      edge: [["statusFor('missing')", "404"], ["statusFor('무언가')", "500"], ["statusFor('conflict')", "409"]],
      ex: "401 과 403 을 뭉개면 클라이언트가 '로그인 화면으로 보낼지' 와 '권한이 없다고 알릴지' 를 구별하지 못합니다. 로그인한 사용자를 다시 로그인 화면으로 보내는 무한 루프가 여기서 나와요 — 상태 코드는 장식이 아니라 분기 조건입니다.",
    },
    {
      k: "resourcePath · 동사는 URL 에 넣지 않는다",
      qq: "자원 이름과 id 를 받아 경로를 돌려주세요. id 가 <code>null</code> 이면 목록 경로(<code>/users</code>), 있으면 <code>/users/1</code> 입니다.",
      src: "function resourcePath(name, id) {\n  return id === null ? '/get' + name : '/get' + name + 'ById/' + id;\n}\n",
      sol: "function resourcePath(name, id) {\n  return id === null ? '/' + name : '/' + name + '/' + id;\n}\n",
      tests: [["resourcePath('users', null)", "'/users'"], ["resourcePath('users', 1)", "'/users/1'"], ["resourcePath('orders', 'a1')", "'/orders/a1'"]],
      edge: [["resourcePath('users', 0)", "'/users/0'"], ["resourcePath('items', null)", "'/items'"]],
      ex: "URL 에 동사를 넣으면 같은 자원에 대한 경로가 팀원 수만큼 늘어납니다 — getUser, fetchUser, loadUser 가 다 살아 있는 API 를 실제로 보게 돼요. 메서드가 동작을 맡으니 경로는 '무엇' 만 가리키면 충분합니다.",
    },
    {
      k: "applyPatch · 보낸 것만 바꾼다",
      qq: "기존 객체와 <b>일부 필드</b>를 받아 <b>보낸 필드만</b> 바꾼 새 객체를 돌려주세요. 원본은 그대로입니다.",
      src: "function applyPatch(obj, patch) {\n  return { ...patch };\n}\n",
      sol: "function applyPatch(obj, patch) {\n  return { ...obj, ...patch };\n}\n",
      tests: [["applyPatch({a:1,b:2}, {b:9})", "{a:1,b:9}"], ["applyPatch({a:1}, {})", "{a:1}"], ["applyPatch({a:1,b:2}, {c:3})", "{a:1,b:2,c:3}"]],
      edge: [["(() => { const o = {a:1}; applyPatch(o, {a:2}); return o; })()", "{a:1}"], ["applyPatch({}, {a:1})", "{a:1}"]],
      ex: "보낸 것만 담아 돌려주면 그건 PUT 의 동작입니다 — 이름만 고치려고 보냈는데 이메일과 전화번호가 사라져요. 사용자에게는 '수정했더니 데이터가 날아갔다' 로 보이고, 원인을 찾기까지 오래 걸립니다.",
    },
  ],
},
/* ── OAuth2·SSO ──────────────────────────────────────────── */
{
  unit: "OAuth2·SSO",
  lesson: "직접 짜 보기 — 비밀번호를 넘기지 않고 허락받기",
  th: {
    sum: "OAuth 는 **비밀번호를 남에게 주지 않고 '이만큼만' 허락하는 방법**이다.",
    body: [
      { h: "왜 비밀번호를 안 주는가", t: "앱에 구글 비밀번호를 주면 그 앱은 메일도 읽고 계정도 지울 수 있다. 대신 '연락처 읽기만' 이라고 적힌 토큰을 받으면, 앱이 털려도 피해가 그 범위에 갇힌다." },
      { h: "인가 코드를 한 번 더 바꾼다", t: "토큰을 브라우저 주소창으로 바로 보내면 기록과 로그에 남는다. 대신 짧은 코드를 주고, 서버끼리 조용히 토큰으로 바꾼다 — 코드는 한 번만 쓸 수 있고 금방 만료된다." },
      { h: "state 로 요청을 이어 붙인다", t: "보낼 때 무작위 값을 만들어 두고 돌아온 값과 견준다. 다르면 내가 시작한 흐름이 아니라는 뜻이라 버린다 — CSRF 를 막는 장치다." },
      { h: "리다이렉트 주소는 정확히 일치해야 한다", t: "'앞부분만 같으면 통과' 로 등록해 두면 공격자가 자기 경로를 붙여 코드를 가로챌 수 있다. 전체 문자열이 같아야 한다." },
    ],
    code: { c: "1) 앱 → 인가 서버 (scope, state, redirect_uri)\n2) 사용자 허락\n3) 인가 서버 → 앱 (code, state)\n4) state 확인 → 서버끼리 code ↔ token 교환", cap: "코드를 한 번 더 바꾼다" },
    key: ["비밀번호 대신 범위 있는 토큰", "코드는 서버끼리 교환한다", "state 와 redirect_uri 를 엄격히 본다"],
  },
  q: [
    {
      k: "checkState · 내가 시작한 흐름인가",
      qq: "저장해 둔 state 와 돌아온 state 를 받아, <b>둘 다 비어 있지 않고 같을 때만</b> true 를 돌려주세요.",
      src: "function checkState(saved, got) {\n  return saved === got;\n}\n",
      sol: "function checkState(saved, got) {\n  if (!saved || !got) return false;\n  return saved === got;\n}\n",
      tests: [["checkState('abc', 'abc')", "true"], ["checkState('abc', 'xyz')", "false"], ["checkState('', '')", "false"]],
      edge: [["checkState(null, null)", "false"], ["checkState(undefined, undefined)", "false"], ["checkState('a', '')", "false"]],
      ex: "저장된 state 가 없는 상태(세션이 날아갔거나 아예 시작하지 않은 흐름)에서 빈 값끼리 견주면 통과합니다 — 공격자가 state 없이 보낸 요청이 그대로 받아들여져요. '같다' 앞에 '있다' 를 먼저 물어야 합니다.",
    },
    {
      k: "redirectAllowed · 정확히 등록된 주소만",
      qq: "등록된 주소 목록과 요청된 주소를 받아 <b>정확히 일치</b>할 때만 true 를 돌려주세요.",
      src: "function redirectAllowed(list, uri) {\n  return list.some(u => uri.startsWith(u));\n}\n",
      sol: "function redirectAllowed(list, uri) {\n  return list.includes(uri);\n}\n",
      tests: [["redirectAllowed(['https://a.example/cb'], 'https://a.example/cb')", "true"], ["redirectAllowed(['https://a.example/cb'], 'https://a.example/cb.evil.example')", "false"], ["redirectAllowed([], 'https://a.example/cb')", "false"]],
      edge: [["redirectAllowed(['https://a.example/cb'], 'https://a.example/cb/x')", "false"], ["redirectAllowed(['https://a.example/cb'], 'https://a.example/CB')", "false"]],
      ex: "앞부분만 견주면 `https://a.example/cb.evil.example` 이 통과합니다 — 인가 코드가 공격자 서버로 배달되는 거예요. '등록된 주소로만 보낸다' 는 약속은 전체가 같을 때만 지켜집니다.",
    },
    {
      k: "hasScope · 이만큼만 허락받았다",
      qq: "토큰이 가진 범위 배열과 <b>필요한 범위 배열</b>을 받아, <b>전부 가지고 있으면</b> true 를 돌려주세요.",
      src: "function hasScope(have, need) {\n  return need.some(s => have.includes(s));\n}\n",
      sol: "function hasScope(have, need) {\n  return need.every(s => have.includes(s));\n}\n",
      tests: [["hasScope(['read','write'], ['read'])", "true"], ["hasScope(['read'], ['read','write'])", "false"], ["hasScope(['read'], [])", "true"]],
      edge: [["hasScope([], ['read'])", "false"], ["hasScope(['a','b','c'], ['a','c'])", "true"]],
      ex: "`some` 은 하나만 맞아도 통과시킵니다 — 읽기 권한만 가진 토큰으로 쓰기까지 하게 돼요. 필요한 범위가 여럿이면 **전부** 가지고 있어야 합니다. 범위를 나눠 둔 의미가 이 한 글자에 달려 있습니다.",
    },
  ],
},
/* ── ORM·데이터 접근 ─────────────────────────────────────── */
{
  unit: "ORM·데이터 접근",
  lesson: "직접 짜 보기 — 쿼리가 몇 번 나가는가",
  th: {
    sum: "ORM 의 편리함은 **쿼리가 언제 몇 번 나가는지 안 보이게** 만든다. 그걸 세는 것이 실력이다.",
    body: [
      { h: "N+1 은 조용히 온다", t: "목록을 읽고 각 항목의 관계를 읽으면 1 + N 번이다. 코드는 반복문 한 줄이라 아무 냄새가 안 나는데, 100건이면 101번이고 그 사이 커넥션이 묶인다." },
      { h: "미리 불러오면 두 번으로 끝난다", t: "필요한 id 를 모아 `IN` 으로 한 번에 읽고 메모리에서 붙인다. 쿼리 수가 N 에 무관해지는 것이 핵심이다." },
      { h: "지연 로딩은 트랜잭션 밖에서 터진다", t: "세션이 닫힌 뒤에 관계를 읽으려 하면 예외가 난다. 화면을 그리는 시점에야 터져서, 개발 중에는 멀쩡하다가 배포 후에 보이기도 한다." },
      { h: "커넥션 풀에는 상한이 있다", t: "요청마다 커넥션을 오래 쥐면 풀이 마르고, 그때부터는 모든 요청이 대기한다. 트랜잭션 안에서 외부 API 를 부르는 코드가 대표적인 원인이다." },
    ],
    code: { c: "// N+1\nconst posts = findPosts();            // 1\nposts.map(p => findUser(p.userId));   // N\n\n// 미리 불러오기\nconst ids = [...new Set(posts.map(p => p.userId))];\nconst users = findUsersIn(ids);       // 1", cap: "쿼리 수를 세면서 읽는다" },
    key: ["N+1 은 냄새가 안 난다", "id 를 모아 한 번에 읽는다", "커넥션을 오래 쥐지 않는다"],
  },
  q: [
    {
      k: "queryCount · 몇 번 나가나",
      qq: "목록 길이와 <b>미리 불러오기 여부</b>를 받아 쿼리 횟수를 돌려주세요. 미리 불러오면 <b>2번</b>(비면 1번), 아니면 <b>1 + N</b> 입니다.",
      src: "function queryCount(n, preload) {\n  return preload ? 2 : 2;\n}\n",
      sol: "function queryCount(n, preload) {\n  if (preload) return n === 0 ? 1 : 2;\n  return 1 + n;\n}\n",
      tests: [["queryCount(100, false)", "101"], ["queryCount(100, true)", "2"], ["queryCount(0, false)", "1"]],
      edge: [["queryCount(0, true)", "1"], ["queryCount(1, false)", "2"]],
      ex: "100건에 101번과 2번은 오십 배 차이입니다. 코드로는 반복문 한 줄이라 리뷰에서도 잘 안 걸려요 — 그래서 '이 코드는 쿼리가 몇 번 나가나' 를 세는 습관이 필요합니다.",
    },
    {
      k: "preloadIds · 중복 없이 모으기",
      qq: "행 목록과 키 이름을 받아 <b>중복 없는 id 배열</b>을 <b>처음 나온 순서대로</b> 돌려주세요. <code>null</code>·<code>undefined</code> 는 뺍니다.",
      src: "function preloadIds(rows, key) {\n  return rows.map(r => r[key]);\n}\n",
      sol: "function preloadIds(rows, key) {\n  const out = [];\n  for (const r of rows) {\n    const v = r[key];\n    if (v === null || v === undefined) continue;\n    if (!out.includes(v)) out.push(v);\n  }\n  return out;\n}\n",
      tests: [["preloadIds([{u:1},{u:2},{u:1}], 'u')", "[1,2]"], ["preloadIds([{u:1},{u:null}], 'u')", "[1]"], ["preloadIds([], 'u')", "[]"]],
      edge: [["preloadIds([{u:undefined}], 'u')", "[]"], ["preloadIds([{u:0},{u:0}], 'u')", "[0]"]],
      ex: "중복을 안 지우면 같은 사용자를 백 번 조회하게 됩니다 — `IN` 절이 쓸데없이 길어지고 DB 도 같은 일을 반복해요. 그리고 null 을 그대로 넣으면 `IN (NULL)` 이 되어 아무것도 안 맞습니다.",
    },
    {
      k: "safeInTx · 트랜잭션 안에서 하면 안 되는 일",
      qq: "작업 이름 배열을 받아 <b>트랜잭션 안에서 해도 되는 것만</b> 남겨 돌려주세요. <code>'http'</code>·<code>'email'</code>·<code>'sleep'</code> 은 밖으로 빼야 합니다.",
      src: "function safeInTx(ops) {\n  return ops;\n}\n",
      sol: "function safeInTx(ops) {\n  const bad = new Set(['http', 'email', 'sleep']);\n  return ops.filter(o => !bad.has(o));\n}\n",
      tests: [["safeInTx(['insert','http','update'])", "['insert','update']"], ["safeInTx(['select'])", "['select']"], ["safeInTx(['http','email'])", "[]"]],
      edge: [["safeInTx([])", "[]"], ["safeInTx(['sleep','insert'])", "['insert']"]],
      ex: "트랜잭션 안에서 외부 API 를 부르면, 상대가 느려진 만큼 커넥션과 잠금을 쥐고 있게 됩니다. 남의 장애가 우리 DB 커넥션 풀을 말려 버려요 — 트랜잭션은 짧게, 외부 호출은 밖에서 합니다.",
    },
  ],
},
/* ── 캐싱 전략 ───────────────────────────────────────────── */
{
  unit: "캐싱 전략",
  lesson: "직접 짜 보기 — 언제 버리고 언제 다시 채우나",
  th: {
    sum: "캐시의 어려움은 넣는 게 아니라 **언제 버릴지 정하는 것**이다.",
    body: [
      { h: "무효화는 쓰기 쪽에서", t: "데이터를 바꾼 곳에서 관련 키를 지워야 한다. 읽는 쪽에서 '오래됐으면 다시' 만으로는 방금 바뀐 값을 그 시간만큼 계속 틀리게 보여 준다." },
      { h: "키에 버전을 넣으면 지울 필요가 없다", t: "`user:1:v7` 처럼 버전을 붙이면, 바뀔 때 버전만 올리면 된다. 옛 키는 만료로 알아서 사라지고, 여러 서버에서 동시에 지우는 어려움도 없다." },
      { h: "캐시 스탬피드를 막는다", t: "인기 키가 만료되는 순간 수천 요청이 동시에 DB 로 몰린다. 만료 시각에 약간의 무작위를 섞거나, 한 요청만 다시 채우고 나머지는 기다리게 한다." },
      { h: "없다는 사실도 캐시한다", t: "존재하지 않는 id 를 계속 조회하면 매번 DB 로 간다. '없음' 을 짧게 캐시해 두면 그 공격이 막힌다." },
    ],
    code: { c: "// 버전 키\n`user:${id}:v${version}`\n\n// 스탬피드 방지: 만료에 지터\nttl = base + random(0, base * 0.1)\n\n// 없음도 캐시 (짧게)", cap: "버릴 때를 정하는 일" },
    key: ["무효화는 쓰기 쪽에서", "버전 키는 지울 필요가 없다", "만료에 지터를 섞는다"],
  },
  q: [
    {
      k: "cacheKey · 버전을 넣어 두면",
      qq: "자원 이름·id·버전을 받아 <code>user:1:v7</code> 꼴의 키를 돌려주세요. 버전이 <code>null</code> 이면 <code>:v</code> 부분을 <b>붙이지 않습니다</b>.",
      src: "function cacheKey(name, id, ver) {\n  return name + ':' + id + ':v' + ver;\n}\n",
      sol: "function cacheKey(name, id, ver) {\n  const base = name + ':' + id;\n  return ver === null ? base : base + ':v' + ver;\n}\n",
      tests: [["cacheKey('user', 1, 7)", "'user:1:v7'"], ["cacheKey('user', 1, null)", "'user:1'"], ["cacheKey('post', 'a', 0)", "'post:a:v0'"]],
      edge: [["cacheKey('user', 0, null)", "'user:0'"], ["cacheKey('x', 1, 1)", "'x:1:v1'"]],
      ex: "버전이 없는데 붙이면 `user:1:vnull` 이라는 키가 생깁니다 — 버전이 있을 때와 다른 키라 캐시가 영영 안 맞아요. 적중률 0% 인 캐시는 메모리만 쓰고 아무 일도 안 합니다.",
    },
    {
      k: "ttlWithJitter · 한꺼번에 만료되지 않게",
      qq: "기본 TTL·지터 비율·무작위값(0~1)을 받아 <code>base * (1 + jitter * r)</code> 을 돌려주세요. 결과는 <b>정수로 내림</b>합니다.",
      src: "function ttlWithJitter(base, jitter, r) {\n  return base;\n}\n",
      sol: "function ttlWithJitter(base, jitter, r) {\n  return Math.floor(base * (1 + jitter * r));\n}\n",
      tests: [["ttlWithJitter(100, 0.1, 0)", "100"], ["ttlWithJitter(100, 0.1, 1)", "110"], ["ttlWithJitter(100, 0, 0.5)", "100"]],
      edge: [["ttlWithJitter(100, 0.1, 0.5)", "105"], ["ttlWithJitter(0, 0.5, 1)", "0"]],
      ex: "TTL 이 똑같으면 같이 채워진 키들이 **같은 순간에** 만료됩니다. 인기 페이지의 캐시 수천 개가 동시에 비면 그 요청이 전부 DB 로 몰려 서비스가 멈춰요 — 만료 시각을 조금씩 흩뜨리는 곱셈 하나가 그 파도를 막습니다.",
    },
    {
      k: "invalidate · 바꿨으면 지운다",
      qq: "캐시 객체와 <b>지울 접두사</b>를 받아, 그 접두사로 시작하는 키를 <b>전부 지운 새 객체</b>를 돌려주세요.",
      src: "function invalidate(cache, prefix) {\n  const out = { ...cache };\n  delete out[prefix];\n  return out;\n}\n",
      sol: "function invalidate(cache, prefix) {\n  const out = {};\n  for (const k of Object.keys(cache)) {\n    if (!k.startsWith(prefix)) out[k] = cache[k];\n  }\n  return out;\n}\n",
      tests: [["invalidate({'user:1':'a','user:2':'b','post:1':'c'}, 'user:')", "{'post:1':'c'}"], ["invalidate({'a':1}, 'b')", "{a:1}"], ["invalidate({}, 'x')", "{}"]],
      edge: [["invalidate({'user:1':'a','user:1:profile':'b'}, 'user:1')", "{}"], ["(() => { const c = {'a':1}; invalidate(c, 'a'); return c; })()", "{a:1}"]],
      ex: "키 하나만 지우면 그 사용자에 딸린 다른 캐시(프로필·설정·목록)가 옛 값으로 남습니다. 어떤 화면은 새 값, 어떤 화면은 옛 값이 보이는 거예요 — 사용자는 '가끔 반영이 안 된다' 고 느끼고, 재현이 안 되니 고치기 어렵습니다.",
    },
  ],
},
/* ── 메시지 큐·비동기 처리 ──────────────────────────────── */
{
  unit: "메시지 큐·비동기 처리",
  lesson: "직접 짜 보기 — 한 번만 처리되게",
  th: {
    sum: "큐는 **적어도 한 번은 배달하지만, 두 번 배달할 수도 있다**. 그래서 받는 쪽이 중복을 다뤄야 한다.",
    body: [
      { h: "정확히 한 번은 사실상 없다", t: "네트워크가 끊기면 '보냈는데 확인을 못 받은' 상태가 생긴다. 그래서 대부분의 큐는 '적어도 한 번' 을 보장하고, 중복 제거는 소비자가 맡는다." },
      { h: "멱등하게 만들면 중복이 무해해진다", t: "'잔액을 100 빼라' 는 두 번 하면 틀리지만 '잔액을 900 으로 하라' 는 두 번 해도 같다. 메시지에 처리 id 를 두고 이미 본 것이면 건너뛰는 방법도 있다." },
      { h: "실패한 메시지는 따로 모은다", t: "계속 실패하는 메시지가 큐 맨 앞을 막으면 뒤의 정상 메시지도 못 나간다. 몇 번 재시도한 뒤 별도 큐(DLQ)로 옮기고 사람이 본다." },
      { h: "순서가 필요하면 키로 묶는다", t: "전체 순서를 보장하면 병렬 처리를 못 한다. '같은 주문의 메시지끼리만 순서를 지킨다' 로 좁히면 병렬성과 순서를 함께 얻는다." },
    ],
    code: { c: "if (seen.has(msg.id)) return;   // 멱등\nseen.add(msg.id);\n\nif (msg.attempts >= MAX) toDLQ(msg);\n\npartition = hash(msg.orderId) % N   // 키별 순서", cap: "두 번 와도 괜찮게 만든다" },
    key: ["중복 배달은 정상이다", "멱등하게 만든다", "실패는 DLQ 로 옮긴다"],
  },
  q: [
    {
      k: "processOnce · 두 번 와도 한 번만",
      qq: "이미 처리한 id 집합과 메시지 id 를 받아, <b>처음이면</b> true 를 돌려주고 집합에 넣습니다. 이미 있으면 false 입니다.",
      src: "function processOnce(seen, id) {\n  seen.add(id);\n  return true;\n}\n",
      sol: "function processOnce(seen, id) {\n  if (seen.has(id)) return false;\n  seen.add(id);\n  return true;\n}\n",
      tests: [["processOnce(new Set(), 'a')", "true"], ["processOnce(new Set(['a']), 'a')", "false"], ["(() => { const s = new Set(); processOnce(s, 'a'); return processOnce(s, 'a'); })()", "false"]],
      edge: [["(() => { const s = new Set(); processOnce(s, 'a'); return s.size; })()", "1"], ["processOnce(new Set(['b']), 'a')", "true"]],
      ex: "무조건 true 를 돌려주면 같은 메시지가 두 번 왔을 때 결제도 두 번 되고 메일도 두 번 갑니다. 큐가 중복 배달하는 건 장애가 아니라 정상 동작이에요 — 막는 것은 받는 쪽의 일입니다.",
    },
    {
      k: "route · 몇 번 실패하면 DLQ 로",
      qq: "시도 횟수와 상한을 받아 <code>'retry'</code> 또는 <code>'dlq'</code> 를 돌려주세요. 시도가 상한 <b>이상</b>이면 DLQ 입니다.",
      src: "function route(attempts, max) {\n  return 'retry';\n}\n",
      sol: "function route(attempts, max) {\n  return attempts >= max ? 'dlq' : 'retry';\n}\n",
      tests: [["route(1, 3)", "'retry'"], ["route(3, 3)", "'dlq'"], ["route(5, 3)", "'dlq'"]],
      edge: [["route(0, 0)", "'dlq'"], ["route(2, 3)", "'retry'"]],
      ex: "영원히 재시도하면 그 메시지가 큐 앞을 막고, 뒤의 정상 메시지가 하나도 못 나갑니다 — 큐 하나가 막혀 서비스 전체가 멈추는 흔한 경로예요. 몇 번 해 보고 안 되면 옆으로 치우고 사람이 봅니다.",
    },
    {
      k: "partitionOf · 같은 주문끼리만 순서를 지킨다",
      qq: "키 문자열과 파티션 수를 받아 <b>파티션 번호</b>를 돌려주세요. 같은 키는 <b>언제나 같은 번호</b>여야 하고, 파티션이 1 미만이면 0 입니다.",
      src: "let __n = 0;\nfunction partitionOf(key, n) {\n  return (__n++) % n;\n}\n",
      sol: "function partitionOf(key, n) {\n  if (n < 1) return 0;\n  let h = 0;\n  for (const ch of String(key)) h = (h * 31 + ch.charCodeAt(0)) % 1000003;\n  return h % n;\n}\n",
      tests: [["partitionOf('order-1', 4) === partitionOf('order-1', 4)", "true"], ["partitionOf('x', 1)", "0"], ["partitionOf('y', 0)", "0"]],
      edge: [["(() => { const s = new Set(); for (let i = 0; i < 50; i++) s.add(partitionOf('k' + i, 4)); return s.size; })()", "4"], ["partitionOf('order-1', 4) < 4", "true"]],
      ex: "돌아가며 배정하면 같은 주문의 '생성' 과 '취소' 가 다른 파티션으로 흩어져, 취소가 생성보다 먼저 처리될 수 있습니다. 키를 해시해 고정하면 같은 주문은 언제나 한 줄에 서고, 서로 다른 주문끼리는 마음껏 병렬로 갑니다.",
    },
  ],
},
/* ── 장애 처리·복원력 ───────────────────────────────────── */
{
  unit: "장애 처리·복원력",
  lesson: "직접 짜 보기 — 무너질 때 곱게 무너지기",
  th: {
    sum: "복원력은 **장애를 없애는 것이 아니라, 장애가 번지지 않게 하는 것**이다.",
    body: [
      { h: "회로차단기는 빨리 포기한다", t: "실패가 이어지면 한동안 아예 시도하지 않는다. 죽은 서비스에 계속 요청을 보내 봐야 우리 스레드만 묶이고, 회복도 늦어진다 — 잠시 뒤 한 번만 열어 보고 되면 정상으로 돌아간다." },
      { h: "타임아웃 없는 호출은 시한폭탄", t: "상대가 응답을 안 주면 우리 요청이 무한히 매달린다. 그 스레드와 커넥션은 그동안 아무 일도 못 한다 — 모든 외부 호출에 시간 상한을 둔다." },
      { h: "격벽으로 나눠 둔다", t: "기능마다 쓸 수 있는 자원을 따로 정해 두면, 한 기능이 폭주해도 나머지는 산다. 배의 격벽이 물이 번지는 것을 막는 것과 같다." },
      { h: "무너지되 기능은 줄여서 유지한다", t: "추천 서비스가 죽으면 추천 없이 상품 목록을 보여 준다. 전부 500 을 주는 것보다 훨씬 낫다 — 무엇을 포기할지 미리 정해 둬야 그 순간에 판단이 선다." },
    ],
    code: { c: "// 회로차단기\nCLOSED → (실패 n회) → OPEN\nOPEN   → (시간 경과) → HALF_OPEN\nHALF_OPEN → 성공이면 CLOSED, 실패면 OPEN\n\n모든 외부 호출에 timeout", cap: "번지지 않게 끊는다" },
    key: ["회로차단기는 빨리 포기한다", "타임아웃 없는 호출은 없다", "포기할 기능을 미리 정한다"],
  },
  q: [
    {
      k: "breakerNext · 회로차단기의 다음 상태",
      qq: "현재 상태·연속 실패 수·상한을 받아 다음 상태를 돌려주세요. <code>'CLOSED'</code> 에서 실패가 상한 <b>이상</b>이면 <code>'OPEN'</code>, <code>'HALF_OPEN'</code> 에서 실패가 <b>1 이상</b>이면 <code>'OPEN'</code>, 실패가 0이면 <code>'CLOSED'</code>, 그 밖은 현재 상태입니다.",
      src: "function breakerNext(state, fails, max) {\n  return fails >= max ? 'OPEN' : 'CLOSED';\n}\n",
      sol: "function breakerNext(state, fails, max) {\n  if (fails === 0) return 'CLOSED';\n  if (state === 'HALF_OPEN') return 'OPEN';\n  if (state === 'CLOSED' && fails >= max) return 'OPEN';\n  return state;\n}\n",
      tests: [["breakerNext('CLOSED', 5, 5)", "'OPEN'"], ["breakerNext('CLOSED', 1, 5)", "'CLOSED'"], ["breakerNext('HALF_OPEN', 1, 5)", "'OPEN'"]],
      edge: [["breakerNext('HALF_OPEN', 0, 5)", "'CLOSED'"], ["breakerNext('OPEN', 1, 5)", "'OPEN'"], ["breakerNext('OPEN', 0, 5)", "'CLOSED'"]],
      ex: "HALF_OPEN 은 '한 번만 시험 삼아 보내 보는' 상태라, 그 한 번이 실패하면 곧바로 다시 닫아야 합니다. 상한만큼 실패하기를 기다리면 죽은 서비스에 다섯 번 더 보내게 돼요 — 시험 요청은 한 번이라는 게 이 상태의 요점입니다.",
    },
    {
      k: "withTimeout · 기다림에 상한을 둔다",
      qq: "지금까지 기다린 시간과 상한을 받아 <code>'wait'</code> 또는 <code>'timeout'</code> 을 돌려주세요. 상한이 <code>null</code> 이면 <b>언제나 <code>'timeout'</code></b> — 상한 없는 호출은 허용하지 않습니다.",
      src: "function withTimeout(waited, limit) {\n  if (limit === null) return 'wait';\n  return waited >= limit ? 'timeout' : 'wait';\n}\n",
      sol: "function withTimeout(waited, limit) {\n  if (limit === null) return 'timeout';\n  return waited >= limit ? 'timeout' : 'wait';\n}\n",
      tests: [["withTimeout(10, 100)", "'wait'"], ["withTimeout(100, 100)", "'timeout'"], ["withTimeout(0, null)", "'timeout'"]],
      edge: [["withTimeout(999, null)", "'timeout'"], ["withTimeout(0, 0)", "'timeout'"]],
      ex: "상한이 없으면 영원히 기다리게 두는 코드는, 상대가 조용히 멈췄을 때 우리 스레드를 하나씩 갉아먹습니다. 몇 분 뒤에는 멀쩡한 요청도 받을 자리가 없어져요 — '상한을 안 정했으면 그건 설정 실수' 로 다루는 편이 안전합니다.",
    },
    {
      k: "degrade · 무엇을 포기할 것인가",
      qq: "필수 기능 집합과 <b>죽은 기능 배열</b>을 받아, <b>필수가 하나라도 죽었으면</b> <code>'fail'</code>, 아니면 <code>'degraded'</code>(죽은 게 있을 때) 또는 <code>'ok'</code> 를 돌려주세요.",
      src: "function degrade(required, down) {\n  return down.length ? 'fail' : 'ok';\n}\n",
      sol: "function degrade(required, down) {\n  if (down.some(d => required.has(d))) return 'fail';\n  return down.length ? 'degraded' : 'ok';\n}\n",
      tests: [["degrade(new Set(['db']), ['recommend'])", "'degraded'"], ["degrade(new Set(['db']), ['db'])", "'fail'"], ["degrade(new Set(['db']), [])", "'ok'"]],
      edge: [["degrade(new Set(), ['x'])", "'degraded'"], ["degrade(new Set(['db','auth']), ['auth','recommend'])", "'fail'"]],
      ex: "추천 서비스가 죽었다고 상품 목록까지 500 을 주면, 팔 수 있는 물건을 못 팝니다. 무엇이 없으면 정말 못 하는지(DB·인증)와 없어도 되는지를 미리 갈라 두면, 장애 순간에 판단이 아니라 실행만 하면 돼요.",
    },
  ],
},
];
