/* 백엔드 5차 — 실습이 없던 6개 유닛(2차 묶음). JS 로 채점한다. */
module.exports = [
/* ── API 보안 ───────────────────────────────────────────── */
{
  unit: "API 보안",
  lesson: "직접 짜 보기 — 들어온 것을 믿지 않기",
  th: {
    sum: "API 보안의 대부분은 **누가 무엇에 접근하는지 매 요청마다 다시 확인하는 일**이다.",
    body: [
      { h: "인증과 인가는 다른 질문", t: "인증은 '누구인가', 인가는 '이걸 해도 되는가' 다. 로그인만 확인하고 소유자 확인을 빼먹으면, 남의 주문 번호를 넣어 남의 정보를 보게 된다 — 가장 흔하고 가장 조용한 취약점이다." },
      { h: "id 를 순번으로 두면 훑어진다", t: "`/orders/1001` 이 내 것이면 1002 도 눌러 본다. 소유자 검사가 진짜 방어이고, 추측하기 어려운 id 는 그 위에 얹는 한 겹일 뿐이다." },
      { h: "응답에 필요한 것만 담는다", t: "DB 행을 그대로 내보내면 비밀번호 해시나 내부 플래그가 함께 나간다. 화면에 안 쓰더라도 응답에 들어 있으면 유출이다 — 내보낼 필드를 골라 담는다." },
      { h: "레이트 리밋은 계정과 IP 둘 다", t: "IP 만 막으면 한 계정으로 여러 IP 를 쓰고, 계정만 막으면 계정을 여러 개 만든다. 로그인·비밀번호 재설정처럼 값비싼 경로는 양쪽을 함께 센다." },
    ],
    code: { c: "// 인증만으로는 부족하다\nif (!user) return 401;\nif (order.userId !== user.id) return 404;   // 소유자 확인\n\n// 내보낼 것만 골라 담는다\nreturn { id, name };   // row 를 통째로 보내지 않는다", cap: "매 요청마다 다시 확인한다" },
    key: ["인증과 인가는 다른 질문", "소유자 확인이 진짜 방어", "응답 필드를 골라 담는다"],
  },
  q: [
    {
      k: "canRead · 남의 것을 보지 못하게",
      qq: "사용자와 주문을 받아 <b>로그인했고 소유자일 때만</b> true 를 돌려주세요. <code>role</code> 이 <code>'admin'</code> 이면 남의 것도 볼 수 있습니다.",
      src: "function canRead(user, order) {\n  return !!user;\n}\n",
      sol: "function canRead(user, order) {\n  if (!user || !order) return false;\n  if (user.role === 'admin') return true;\n  return order.userId === user.id;\n}\n",
      tests: [["canRead({id:1,role:'user'}, {userId:1})", "true"], ["canRead({id:1,role:'user'}, {userId:2})", "false"], ["canRead(null, {userId:1})", "false"]],
      edge: [["canRead({id:1,role:'admin'}, {userId:2})", "true"], ["canRead({id:1,role:'user'}, null)", "false"]],
      ex: "로그인만 확인하면 아무나 남의 주문 번호를 넣어 볼 수 있습니다 — 로그인한 사용자니까 401 도 아니고, 오류도 안 나요. 이 취약점은 로그에 아무 흔적을 안 남겨서 유출된 뒤에야 발견됩니다.",
    },
    {
      k: "publicFields · 내보낼 것만 골라 담기",
      qq: "DB 행 객체와 <b>허용 필드 배열</b>을 받아 그 필드만 담은 새 객체를 돌려주세요. 없는 필드는 <b>넣지 않습니다</b>.",
      src: "function publicFields(row, allow) {\n  const out = { ...row };\n  delete out.password;\n  return out;\n}\n",
      sol: "function publicFields(row, allow) {\n  const out = {};\n  for (const k of allow) if (k in row) out[k] = row[k];\n  return out;\n}\n",
      tests: [["publicFields({id:1,name:'가',password:'x'}, ['id','name'])", "{id:1,name:'가'}"], ["publicFields({id:1,secret:'s'}, ['id'])", "{id:1}"], ["publicFields({id:1}, ['id','none'])", "{id:1}"]],
      edge: [["publicFields({}, ['id'])", "{}"], ["publicFields({id:1,name:'가'}, [])", "{}"]],
      ex: "지울 것을 나열하는 방식은 새 컬럼이 생길 때마다 유출됩니다 — `internal_memo` 를 추가한 사람이 이 함수를 고칠 리 없거든요. 허용 목록은 반대로, 적어 두지 않은 것은 절대 안 나갑니다.",
    },
    {
      k: "rateKey · 계정과 IP 를 함께 센다",
      qq: "요청 정보를 받아 <b>레이트 리밋 키 배열</b>을 돌려주세요. 로그인했으면 <code>'u:1'</code> 과 <code>'ip:...'</code> 둘 다, 아니면 IP 만입니다.",
      src: "function rateKey(req) {\n  return ['ip:' + req.ip];\n}\n",
      sol: "function rateKey(req) {\n  const keys = ['ip:' + req.ip];\n  if (req.userId != null) keys.unshift('u:' + req.userId);\n  return keys;\n}\n",
      tests: [["rateKey({ip:'1.1.1.1', userId:1})", "['u:1','ip:1.1.1.1']"], ["rateKey({ip:'1.1.1.1'})", "['ip:1.1.1.1']"], ["rateKey({ip:'2.2.2.2', userId:0})", "['u:0','ip:2.2.2.2']"]],
      edge: [["rateKey({ip:'1.1.1.1', userId:null})", "['ip:1.1.1.1']"], ["rateKey({ip:''})", "['ip:']"]],
      ex: "IP 만 세면 한 계정으로 여러 IP 를 돌려 가며 두드릴 수 있습니다. 반대로 계정만 세면 계정을 여럿 만들면 되고요 — 로그인이나 비밀번호 재설정처럼 값비싼 경로는 두 축을 함께 세야 막힙니다. `userId` 가 0 인 경우까지 살려면 `!= null` 이 필요합니다.",
    },
  ],
},
/* ── 웹의 작동 원리 ─────────────────────────────────────── */
{
  unit: "웹의 작동 원리",
  lesson: "직접 짜 보기 — 요청 하나가 오가는 길",
  th: {
    sum: "웹 요청 하나에는 **주소 찾기 → 연결 → 요청 → 응답 → 캐시 판단**이 전부 들어 있다.",
    body: [
      { h: "URL 은 여러 조각이다", t: "스킴·호스트·포트·경로·질의문자열·프래그먼트로 나뉜다. 프래그먼트(`#`)는 서버로 아예 안 보내진다 — 브라우저만 쓰는 부분이라, 서버 로그에 없다고 놀라지 않아도 된다." },
      { h: "헤더 이름은 대소문자를 안 가린다", t: "`Content-Type` 과 `content-type` 은 같은 헤더다. 직접 파싱할 때 대소문자를 그대로 견주면, 어떤 클라이언트에서만 헤더를 못 찾는 일이 생긴다." },
      { h: "캐시는 신선도와 검증 둘로 돈다", t: "`max-age` 안이면 서버에 안 물어보고 쓴다. 지나면 `ETag` 로 '바뀌었나' 만 물어, 안 바뀌었으면 304 로 본문 없이 끝난다 — 대역폭이 크게 준다." },
      { h: "쿠키는 자동으로 따라간다", t: "그래서 편하고, 그래서 CSRF 가 생긴다. `SameSite` 와 CSRF 토큰이 그 자동 전송을 다시 통제하는 장치다." },
    ],
    code: { c: "https://a.com:443/p?q=1#top\n스킴  호스트 포트 경로 질의  프래그먼트(서버에 안 감)\n\nmax-age 안 → 그냥 쓴다\n지나면 → If-None-Match → 304 (본문 없음)", cap: "조각마다 역할이 있다" },
    key: ["프래그먼트는 서버에 안 간다", "헤더 이름은 대소문자 무시", "304 는 본문이 없다"],
  },
  q: [
    {
      k: "toServer · 서버에 실제로 가는 부분",
      qq: "URL 문자열에서 <b>서버로 가는 부분</b>(경로 + 질의문자열)만 돌려주세요. 프래그먼트는 <b>뗍니다</b>. 경로가 없으면 <code>'/'</code> 입니다.",
      src: "function toServer(url) {\n  const i = url.indexOf('/', url.indexOf('//') + 2);\n  return i < 0 ? '/' : url.slice(i);\n}\n",
      sol: "function toServer(url) {\n  const noHash = url.split('#')[0];\n  const i = noHash.indexOf('/', noHash.indexOf('//') + 2);\n  return i < 0 ? '/' : noHash.slice(i);\n}\n",
      tests: [["toServer('https://a.com/p?q=1#top')", "'/p?q=1'"], ["toServer('https://a.com/p')", "'/p'"], ["toServer('https://a.com')", "'/'"]],
      edge: [["toServer('https://a.com#top')", "'/'"], ["toServer('https://a.com/#x')", "'/'"]],
      ex: "프래그먼트는 브라우저 안에서만 쓰이고 요청에 실리지 않습니다. 그대로 붙여 보내면 서버는 `/p?q=1#top` 이라는 없는 경로를 찾다 404 를 주거나, 질의값에 `#top` 이 섞여 들어가요.",
    },
    {
      k: "headerOf · 대소문자를 가리지 않는다",
      qq: "헤더 객체와 이름을 받아 값을 돌려주세요. <b>대소문자를 무시</b>하고 찾고, 없으면 <code>null</code> 입니다.",
      src: "function headerOf(headers, name) {\n  return headers[name] ?? null;\n}\n",
      sol: "function headerOf(headers, name) {\n  const want = name.toLowerCase();\n  for (const k of Object.keys(headers)) {\n    if (k.toLowerCase() === want) return headers[k];\n  }\n  return null;\n}\n",
      tests: [["headerOf({'Content-Type':'json'}, 'content-type')", "'json'"], ["headerOf({'content-type':'json'}, 'Content-Type')", "'json'"], ["headerOf({}, 'x')", "null"]],
      edge: [["headerOf({'X-Id':'1'}, 'x-id')", "'1'"], ["headerOf({'a':''}, 'A')", "''"]],
      ex: "HTTP 명세상 헤더 이름은 대소문자를 안 가립니다 — 클라이언트마다 `Content-Type`, `content-type`, `CONTENT-TYPE` 을 제각각 보내요. 그대로 견주면 특정 클라이언트에서만 헤더를 못 찾는, 재현하기 까다로운 버그가 됩니다.",
    },
    {
      k: "cacheDecision · 물어볼까 그냥 쓸까",
      qq: "나이(초)·<code>maxAge</code>·<code>etag</code> 유무를 받아 <code>'use'</code>(신선), <code>'revalidate'</code>(etag 있음), <code>'fetch'</code> 를 돌려주세요.",
      src: "function cacheDecision(age, maxAge, hasEtag) {\n  return age <= maxAge ? 'use' : 'fetch';\n}\n",
      sol: "function cacheDecision(age, maxAge, hasEtag) {\n  if (age <= maxAge) return 'use';\n  return hasEtag ? 'revalidate' : 'fetch';\n}\n",
      tests: [["cacheDecision(10, 60, true)", "'use'"], ["cacheDecision(100, 60, true)", "'revalidate'"], ["cacheDecision(100, 60, false)", "'fetch'"]],
      edge: [["cacheDecision(60, 60, false)", "'use'"], ["cacheDecision(61, 60, true)", "'revalidate'"]],
      ex: "신선도가 지났다고 곧바로 다시 받으면, 대부분의 경우 **똑같은 본문**을 다시 내려받습니다. ETag 로 '바뀌었나' 만 물으면 안 바뀐 경우 304 로 본문 없이 끝나요 — 큰 이미지나 번들에서 이 차이가 큽니다.",
    },
  ],
},
/* ── 심화 ───────────────────────────────────────────────── */
{
  unit: "심화 — 시니어/스태프 난이도",
  lesson: "직접 짜 보기 — 규모가 만드는 문제",
  th: {
    sum: "규모가 커지면 **평균은 괜찮은데 꼬리가 나빠지고**, 작은 확률이 매일 일어나는 일이 된다.",
    body: [
      { h: "요청 하나가 여러 곳을 부르면 꼬리가 커진다", t: "각각 99% 확률로 빠르더라도, 열 곳을 부르면 전부 빠를 확률은 0.99¹⁰ ≈ 90% 다. 느린 요청이 열 배로 늘어난 셈이라, 마이크로서비스에서 p99 가 특히 나빠진다." },
      { h: "재시도는 부하를 곱한다", t: "장애가 나면 모두가 재시도해 트래픽이 몇 배가 된다. 이미 힘든 서비스를 더 밀어붙이는 것이라, 재시도에는 상한·백오프·회로차단기가 함께 필요하다." },
      { h: "커넥션 풀은 곱셈으로 는다", t: "서버 20대 × 풀 50개면 DB 커넥션 1000개다. DB 상한이 500이면 그 절반은 연결조차 못 한다 — 풀 크기는 서버 대수와 함께 계산해야 한다." },
      { h: "핫 파티션은 평균에 안 잡힌다", t: "전체 부하가 절반이어도 한 파티션이 포화면 그 사용자들은 전부 느리다. 평균 대신 가장 뜨거운 곳을 본다." },
    ],
    code: { c: "P(전부 빠름) = 0.99¹⁰ ≈ 0.90\n\nDB 커넥션 = 서버수 * 풀크기\n20 * 50 = 1000  > DB 상한 500 ✗\n\n재시도 트래픽 = 원래 * (1 + 실패율 * 재시도수)", cap: "곱셈으로 커진다" },
    key: ["팬아웃은 꼬리를 키운다", "재시도는 부하를 곱한다", "풀 크기는 서버 대수와 곱해진다"],
  },
  q: [
    {
      k: "allFast · 열 곳을 부르면",
      qq: "한 곳이 빠를 확률과 <b>부르는 곳 수</b>를 받아 <b>전부 빠를 확률</b>을 돌려주세요. 0곳이면 1 입니다.",
      src: "function allFast(p, n) {\n  return p;\n}\n",
      sol: "function allFast(p, n) {\n  return Math.pow(p, n);\n}\n",
      tests: [["allFast(0.99, 1)", "0.99"], ["Math.round(allFast(0.99, 10) * 1e4) / 1e4", "0.9044"], ["allFast(0.5, 2)", "0.25"]],
      edge: [["allFast(0.9, 0)", "1"], ["allFast(1, 100)", "1"]],
      ex: "한 곳이 99% 라고 전체가 99% 인 것은 아닙니다 — 열 곳을 부르면 90% 로 떨어져요. 느린 요청이 열 배가 된 셈이라, 서비스를 잘게 쪼갤수록 p99 를 따로 관리해야 합니다.",
    },
    {
      k: "poolTotal · 곱해서 세어 보기",
      qq: "서버 대수·서버당 풀 크기·DB 상한을 받아 <b>실제로 쓸 수 있는 커넥션 수</b>를 돌려주세요. 상한을 넘으면 상한입니다.",
      src: "function poolTotal(servers, perServer, dbMax) {\n  return perServer;\n}\n",
      sol: "function poolTotal(servers, perServer, dbMax) {\n  return Math.min(servers * perServer, dbMax);\n}\n",
      tests: [["poolTotal(20, 50, 500)", "500"], ["poolTotal(2, 10, 500)", "20"], ["poolTotal(1, 5, 500)", "5"]],
      edge: [["poolTotal(0, 50, 500)", "0"], ["poolTotal(10, 50, 500)", "500"]],
      ex: "풀 크기를 서버 하나만 보고 정하면, 오토스케일로 서버가 늘어나는 순간 DB 상한에 부딪힙니다 — 트래픽이 늘어 서버를 늘렸는데 오히려 더 많이 실패하는 거예요. 풀 크기는 언제나 최대 서버 대수와 곱해서 봅니다.",
    },
    {
      k: "retryLoad · 재시도가 부르는 부하",
      qq: "원래 초당 요청 수·실패율·재시도 횟수를 받아 <b>실제 부하</b>를 돌려주세요: <code>rps * (1 + 실패율 * 재시도수)</code>.",
      src: "function retryLoad(rps, failRate, retries) {\n  return rps;\n}\n",
      sol: "function retryLoad(rps, failRate, retries) {\n  return rps * (1 + failRate * retries);\n}\n",
      tests: [["retryLoad(100, 0, 3)", "100"], ["retryLoad(100, 1, 3)", "400"], ["retryLoad(100, 0.5, 2)", "200"]],
      edge: [["retryLoad(100, 0.1, 0)", "100"], ["retryLoad(0, 1, 5)", "0"]],
      ex: "전부 실패하는 중에 세 번씩 재시도하면 부하가 네 배가 됩니다 — 이미 쓰러진 서비스를 네 배로 밀어붙이는 거예요. 재시도가 장애를 길게 만드는 이유가 이 곱셈이고, 그래서 회로차단기로 아예 안 보내는 구간이 필요합니다.",
    },
  ],
},
/* ── 시니어 실전 ────────────────────────────────────────── */
{
  unit: "시니어 실전 — 트랜잭션·동시성·신뢰성",
  lesson: "직접 짜 보기 — 동시에 들어와도 한 번만",
  th: {
    sum: "동시성 문제의 대부분은 **읽고 → 판단하고 → 쓰는 사이에 남이 끼어드는 것**이다.",
    body: [
      { h: "읽고 쓰는 사이가 틈이다", t: "재고를 읽어 '1개 남았네' 하고 파는 코드는, 두 요청이 동시에 읽으면 둘 다 판다. 원자적 갱신(`SET n = n - 1 WHERE n > 0`)으로 읽기와 쓰기를 하나로 묶으면 그 틈이 사라진다." },
      { h: "조건부 갱신이 가장 싸다", t: "잠금을 걸지 않고도 'WHERE 조건' 에 상태를 넣으면, 조건이 안 맞을 때 0행이 갱신된다. 그 0행이 곧 '남이 먼저 했다' 는 신호다." },
      { h: "여러 자원은 순서를 통일한다", t: "두 계좌를 잠글 때 항상 작은 id 부터 잠그면 데드락이 구조적으로 안 생긴다 — 감지해서 재시도하는 것보다 확실하다." },
      { h: "정확히 한 번은 멱등으로 흉내 낸다", t: "네트워크가 있는 한 '정확히 한 번' 은 없다. 처리 키를 두고 두 번째는 이전 결과를 돌려주면, 밖에서 보기에 한 번만 일어난 것과 같아진다." },
    ],
    code: { c: "-- 틈이 있는 코드\nSELECT n FROM stock WHERE id=1;   -- 1\nUPDATE stock SET n=0 WHERE id=1;\n\n-- 틈이 없는 코드\nUPDATE stock SET n=n-1 WHERE id=1 AND n>0;\n-- 0행이면 남이 먼저 가져갔다", cap: "읽기와 쓰기를 하나로 묶는다" },
    key: ["읽고 쓰는 사이가 틈", "조건부 갱신이 가장 싸다", "잠금 순서를 통일한다"],
  },
  q: [
    {
      k: "takeStock · 동시에 들어와도 한 개만",
      qq: "재고 객체와 개수를 받아, <b>충분할 때만</b> 빼고 <code>true</code> 를 돌려주세요. 모자라면 <b>아무것도 바꾸지 않고</b> false 입니다.",
      src: "function takeStock(store, id, n) {\n  const cur = store[id] ?? 0;\n  store[id] = cur - n;\n  return store[id] >= 0;\n}\n",
      sol: "function takeStock(store, id, n) {\n  const cur = store[id] ?? 0;\n  if (n < 0 || cur < n) return false;\n  store[id] = cur - n;\n  return true;\n}\n",
      tests: [["takeStock({a:5}, 'a', 3)", "true"], ["takeStock({a:1}, 'a', 3)", "false"], ["(() => { const s = {a:1}; takeStock(s, 'a', 3); return s.a; })()", "1"]],
      edge: [["(() => { const s = {a:5}; takeStock(s, 'a', 5); return s.a; })()", "0"], ["takeStock({}, 'a', 1)", "false"], ["takeStock({a:5}, 'a', -1)", "false"]],
      ex: "먼저 빼고 나중에 검사하면 실패한 뒤에도 재고가 음수로 남습니다 — 반환값은 false 라 맞아 보여서, 상태를 확인하는 테스트가 없으면 못 잡아요. 그리고 음수 개수를 안 막으면 '−1개 사기' 로 재고를 늘릴 수 있습니다.",
    },
    {
      k: "casUpdate · 남이 먼저 했으면 실패",
      qq: "<code>{값, 버전}</code> 저장소에 <b>기대한 버전일 때만</b> 쓰고 <code>true</code> 를 돌려주세요. 성공하면 버전이 1 오릅니다.",
      src: "function casUpdate(store, key, expected, value) {\n  store[key] = { value, version: expected + 1 };\n  return true;\n}\n",
      sol: "function casUpdate(store, key, expected, value) {\n  const cur = store[key];\n  const ver = cur ? cur.version : 0;\n  if (ver !== expected) return false;\n  store[key] = { value, version: ver + 1 };\n  return true;\n}\n",
      tests: [["casUpdate({a:{value:'x',version:1}}, 'a', 1, 'y')", "true"], ["casUpdate({a:{value:'x',version:2}}, 'a', 1, 'y')", "false"], ["casUpdate({}, 'a', 0, 'y')", "true"]],
      edge: [["(() => { const s = {a:{value:'x',version:1}}; casUpdate(s,'a',9,'y'); return s.a.value; })()", "'x'"], ["(() => { const s = {a:{value:'x',version:1}}; casUpdate(s,'a',1,'y'); return s.a.version; })()", "2"]],
      ex: "버전을 안 보고 쓰면 내가 읽은 뒤 남이 바꾼 값을 덮어씁니다 — 남의 수정이 소리 없이 사라지고(로스트 업데이트), 반환값은 true 라 아무도 모릅니다. 조건을 갱신문 안에 넣는 것이 잠금 없이 이 틈을 없애는 방법이에요.",
    },
    {
      k: "lockOrder · 데드락이 안 생기게",
      qq: "두 계좌 id 를 받아 <b>잠글 순서</b>를 배열로 돌려주세요. 같은 id 면 <b>하나만</b> 잠급니다.",
      src: "function lockOrder(a, b) {\n  return [a, b];\n}\n",
      sol: "function lockOrder(a, b) {\n  if (a === b) return [a];\n  return a < b ? [a, b] : [b, a];\n}\n",
      tests: [["lockOrder(2, 1)", "[1, 2]"], ["lockOrder(1, 2)", "[1, 2]"], ["lockOrder(1, 1)", "[1]"]],
      edge: [["lockOrder('b', 'a')", "['a','b']"], ["lockOrder(0, 5)", "[0, 5]"]],
      ex: "받은 순서대로 잠그면, A→B 로 이체하는 요청과 B→A 로 이체하는 요청이 서로를 기다려 멈춥니다. 항상 작은 id 부터 잠그면 그 순환이 **만들어질 수가 없어요** — 감지해서 한쪽을 죽이는 것보다 훨씬 싸고 확실합니다. 같은 계좌를 두 번 잠그려는 것도 그 자체로 멈춤이라 걸러야 합니다.",
    },
  ],
},
/* ── 코드 리뷰 ──────────────────────────────────────────── */
{
  unit: "코드 리뷰 — 결함 찾기",
  lesson: "직접 고쳐 보기 — 서버 코드의 단골 지적",
  th: {
    sum: "서버 코드 리뷰의 단골은 **경계값·오류 경로·자원 정리** 셋이다. 정상 경로는 대개 맞다.",
    body: [
      { h: "정상 경로는 이미 테스트됐다", t: "리뷰에서 볼 것은 빈 목록, 0, null, 아주 큰 값, 그리고 예외가 났을 때다. 버그는 거의 언제나 그쪽에 있다." },
      { h: "오류를 삼키면 원인이 지워진다", t: "`catch {}` 는 문제가 있었다는 사실 자체를 없앤다. 최소한 로그를 남기거나 다시 던진다 — 조용한 실패가 가장 비싸다." },
      { h: "자원은 실패 경로에서도 정리한다", t: "중간에 `return` 하거나 예외가 나면 `finally` 없이는 커넥션·파일이 남는다. 잘 되는 경로만 보고 리뷰하면 이걸 놓친다." },
      { h: "숫자 변환을 의심한다", t: "외부에서 온 값은 문자열이다. `parseInt` 는 `'12abc'` 를 12 로 읽고, `Number('')` 는 0 이다 — 검증 없이 계산에 넣으면 조용히 틀린다." },
    ],
    code: { c: "// 리뷰 체크리스트\n□ 빈 목록·0·null 에서 어떻게 되나\n□ 예외가 나면 자원이 정리되나\n□ 삼킨 오류가 있나\n□ 외부 값이 검증됐나", cap: "정상 경로 말고 경계를 본다" },
    key: ["경계값부터 본다", "오류를 삼키지 않는다", "실패 경로에서도 정리한다"],
  },
  q: [
    {
      k: "average · 빈 목록에서 터지지 않게",
      qq: "숫자 배열의 평균을 돌려주세요. <b>비어 있으면 <code>null</code></b> 입니다.",
      src: "function average(xs) {\n  return xs.reduce((a, b) => a + b) / xs.length;\n}\n",
      sol: "function average(xs) {\n  if (!xs.length) return null;\n  return xs.reduce((a, b) => a + b, 0) / xs.length;\n}\n",
      tests: [["average([1, 2, 3])", "2"], ["average([])", "null"], ["average([5])", "5"]],
      edge: [["average([0, 0])", "0"], ["average([-1, 1])", "0"]],
      ex: "초기값 없는 `reduce` 는 빈 배열에서 예외를 던지고, `0 / 0` 은 `NaN` 입니다 — 둘 다 정상 경로에서는 절대 안 나타나요. '목록이 빌 수 있나' 는 리뷰에서 가장 먼저 물어야 할 질문입니다.",
    },
    {
      k: "withRelease · 실패해도 커넥션을 돌려준다",
      qq: "작업을 실행하고 <b>성공하든 실패하든</b> 로그에 <code>'released'</code> 를 남기세요. 예외는 <b>그대로 밖으로</b> 나갑니다.",
      src: "function withRelease(work, log) {\n  const r = work();\n  log.push('released');\n  return r;\n}\n",
      sol: "function withRelease(work, log) {\n  try {\n    return work();\n  } finally {\n    log.push('released');\n  }\n}\n",
      tests: [["(() => { const l = []; withRelease(() => 7, l); return l; })()", "['released']"], ["withRelease(() => 7, [])", "7"], ["(() => { const l = []; try { withRelease(() => { throw new Error('펑'); }, l); } catch (e) {} return l; })()", "['released']"]],
      edge: [["(() => { let caught = false; try { withRelease(() => { throw new Error('펑'); }, []); } catch (e) { caught = true; } return caught; })()", "true"]],
      ex: "예외가 나면 그 아래 줄은 실행되지 않습니다 — 커넥션이 풀로 안 돌아가고, 몇 번 반복되면 풀이 말라 모든 요청이 대기해요. `finally` 는 어떤 경로로 빠져나가든 실행되고, 예외를 삼키지도 않습니다.",
    },
    {
      k: "parseQty · 외부 값은 검증하고 쓴다",
      qq: "문자열 수량을 받아 <b>1 이상의 정수</b>면 그 값을, 아니면 <code>null</code> 을 돌려주세요.",
      src: "function parseQty(s) {\n  return parseInt(s, 10);\n}\n",
      sol: "function parseQty(s) {\n  if (typeof s !== 'string' || !/^\\d+$/.test(s.trim())) return null;\n  const n = Number(s.trim());\n  return n >= 1 ? n : null;\n}\n",
      tests: [["parseQty('3')", "3"], ["parseQty('12abc')", "null"], ["parseQty('0')", "null"]],
      edge: [["parseQty('')", "null"], ["parseQty('  5 ')", "5"], ["parseQty('-1')", "null"]],
      ex: "`parseInt('12abc')` 는 12 를 돌려줍니다 — 앞에서 읽히는 만큼만 읽고 나머지를 버려요. 실패가 성공처럼 보이는 겁니다. 그리고 `parseInt('')` 는 `NaN` 이고, 그 `NaN` 이 금액 계산에 들어가면 주문 전체가 `NaN` 이 됩니다.",
    },
  ],
},
/* ── API 설계 실무 심화 ─────────────────────────────────── */
{
  unit: "API 설계 실무 심화 — 자원 모델링·버저닝·에러 규약",
  lesson: "직접 짜 보기 — 바꿔도 안 깨지게",
  th: {
    sum: "API 는 한 번 내보내면 **남의 코드가 기대는 약속**이 된다. 바꾸는 방법을 미리 정해 둔다.",
    body: [
      { h: "더하는 것은 안전, 빼는 것은 위험", t: "필드를 추가하는 것은 대개 안전하다. 이름을 바꾸거나 지우는 것, 타입을 바꾸는 것, 필수 항목을 늘리는 것은 남의 코드를 깨뜨린다." },
      { h: "버전은 필요할 때만 올린다", t: "깨지는 변경이 생기면 새 버전을 내고, 옛 버전은 기한을 정해 함께 굴린다. 사소한 변경마다 버전을 올리면 유지할 것만 늘어난다." },
      { h: "에러 형식을 통일한다", t: "어떤 곳은 문자열, 어떤 곳은 객체를 주면 클라이언트가 매번 다르게 다뤄야 한다. `{code, message, details}` 처럼 모양을 못 박아 두면 공통 처리기 하나로 끝난다." },
      { h: "에러 코드는 사람 말이 아니라 기계용", t: "메시지는 바뀔 수 있지만 코드는 계약이다. 클라이언트가 메시지 문자열을 비교하게 두면, 문구를 다듬는 순간 남의 코드가 깨진다." },
    ],
    code: { c: "// 안전: 필드 추가\n// 위험: 이름 변경 · 삭제 · 타입 변경 · 필수 추가\n\n{ error: { code: 'OUT_OF_STOCK',\n           message: '재고가 없습니다',\n           details: { id: 1 } } }", cap: "바꾸는 방법을 미리 정한다" },
    key: ["더하기는 안전, 빼기는 위험", "에러 형식을 통일한다", "코드가 계약, 메시지는 아니다"],
  },
  q: [
    {
      k: "isBreaking · 이 변경이 깨뜨리나",
      qq: "변경 종류를 받아 <b>깨지는 변경이면</b> true 를 돌려주세요. <code>'addOptional'</code>·<code>'addEndpoint'</code> 만 안전합니다.",
      src: "function isBreaking(kind) {\n  return kind === 'removeField';\n}\n",
      sol: "function isBreaking(kind) {\n  return !(kind === 'addOptional' || kind === 'addEndpoint');\n}\n",
      tests: [["isBreaking('addOptional')", "false"], ["isBreaking('removeField')", "true"], ["isBreaking('renameField')", "true"]],
      edge: [["isBreaking('addRequired')", "true"], ["isBreaking('changeType')", "true"], ["isBreaking('addEndpoint')", "false"]],
      ex: "삭제만 위험하다고 여기면 이름 변경과 타입 변경을 그냥 내보냅니다 — 둘 다 남의 코드에서는 '필드가 사라진 것' 과 똑같아요. 필수 항목을 하나 늘리는 것도, 그것을 안 보내던 모든 클라이언트를 깨뜨립니다. 안전한 것을 나열하는 편이 실수가 적습니다.",
    },
    {
      k: "errorBody · 형식을 못 박아 두기",
      qq: "코드·메시지·상세를 받아 <code>{error:{code, message, details}}</code> 를 돌려주세요. 상세가 없으면 <b><code>details</code> 키를 넣지 않습니다</b>.",
      src: "function errorBody(code, message, details) {\n  return { error: message };\n}\n",
      sol: "function errorBody(code, message, details) {\n  const e = { code, message };\n  if (details !== undefined && details !== null) e.details = details;\n  return { error: e };\n}\n",
      tests: [["errorBody('X', '메시지')", "{error:{code:'X', message:'메시지'}}"], ["errorBody('X', '메시지', {id:1})", "{error:{code:'X', message:'메시지', details:{id:1}}}"], ["errorBody('Y', '')", "{error:{code:'Y', message:''}}"]],
      edge: [["errorBody('X', 'm', null)", "{error:{code:'X', message:'m'}}"], ["errorBody('X', 'm', {})", "{error:{code:'X', message:'m', details:{}}}"]],
      ex: "에러를 문자열로 주면 클라이언트가 문구를 비교하게 됩니다 — 오타 하나를 고치는 순간 남의 분기문이 깨져요. 코드는 계약이고 메시지는 사람이 읽는 것이라, 둘을 나눠 담아야 문구를 자유롭게 다듬을 수 있습니다.",
    },
    {
      k: "pickVersion · 어느 버전으로 처리할까",
      qq: "요청 헤더의 버전과 <b>지원 목록</b>·기본값을 받아 처리할 버전을 돌려주세요. 지원하지 않는 버전이면 <code>null</code>(거절), 헤더가 없으면 기본값입니다.",
      src: "function pickVersion(asked, supported, fallback) {\n  return asked || fallback;\n}\n",
      sol: "function pickVersion(asked, supported, fallback) {\n  if (asked == null || asked === '') return fallback;\n  return supported.includes(asked) ? asked : null;\n}\n",
      tests: [["pickVersion('v2', ['v1','v2'], 'v1')", "'v2'"], ["pickVersion('v9', ['v1','v2'], 'v1')", "null"], ["pickVersion(null, ['v1','v2'], 'v1')", "'v1'"]],
      edge: [["pickVersion('', ['v1'], 'v1')", "'v1'"], ["pickVersion('v1', [], 'v1')", "null"]],
      ex: "지원 목록을 안 보면 `v9` 같은 오타가 그대로 통과해, 어느 코드 경로도 안 타거나 기본 동작으로 조용히 처리됩니다. 클라이언트는 새 버전을 쓰고 있다고 믿는데 실제로는 아닌 거예요 — 모르는 버전은 거절하는 편이 정직합니다.",
    },
  ],
},
];
