/* 백엔드 실습 3차 — 실습이 하나도 없던 6개 유닛을 연다.
   REST 설계 · 캐싱 · 메시지 큐 · 복원력 · 레이트리밋 · 관측성.

   백엔드 주제라고 서버를 띄울 필요는 없다. 실제로 판단이 갈리는 자리는 대개
   순수한 계산이다 — 어떤 상태 코드를 줄지, 캐시 키를 어떻게 만들지, 언제 다시
   시도할지. 그 알맹이만 함수로 떼어 내면 브라우저 안에서 그대로 채점할 수 있고,
   무엇보다 실무에서도 그렇게 떼어 놓아야 시험할 수 있다.

   채점은 앱의 JS 하네스가 한다. 프라미스를 돌려주는 검사식도 기다려 준다. */
module.exports = [
/* ── REST API 설계 ────────────────────────────────────────── */
{
  unit: "REST API 설계",
  lesson: "직접 짜 보기 — 주소와 상태 코드 정하기",
  th: {
    sum: "REST 에서 주소는 **무엇인지**를 가리키고, 무엇을 할지는 **메서드**가 말한다.",
    body: [
      { h: "주소에 동사를 넣지 않는다", t: "`/getUser?id=12` 대신 `/users/12` 다. 무엇을 할지는 `GET`·`DELETE` 같은 메서드가 이미 말해 준다. 동사를 주소에 넣으면 같은 자원에 대한 주소가 여러 개가 되어, 캐시도 권한 검사도 자리를 잡지 못한다." },
      { h: "묶음은 복수형으로", t: "`/users` 는 사람들의 묶음이고 `/users/12` 는 그중 하나다. 단수·복수를 섞어 쓰면 쓰는 쪽이 매번 문서를 다시 봐야 한다. 규칙은 단순한 편이 낫다." },
      { h: "상태 코드가 결과를 말한다", t: "만들었으면 201, 지웠고 돌려줄 내용이 없으면 204, 없는 것을 찾으면 404 다. 전부 200으로 주고 본문에 `success: false` 를 적으면, 중간의 캐시나 모니터링은 그것을 성공으로 센다." },
      { h: "다음 쪽이 없으면 없다고 한다", t: "목록의 마지막 쪽에서도 '다음' 링크를 주면, 쓰는 쪽은 빈 응답을 받고 나서야 끝인 줄 안다. 마지막이면 `null` 을 주는 편이 한 번 덜 부르게 한다." },
    ],
    code: { c: "GET    /users/12   → 200\nPOST   /users      → 201\nDELETE /users/12   → 204\nGET    /users/99   → 404", cap: "주소는 무엇, 메서드는 무엇을" },
    key: ["주소에 동사를 넣지 않는다", "묶음은 복수형", "상태 코드가 결과를 말한다"],
  },
  q: [
    {
      k: "resourcePath · 주소 규칙 지키기",
      qq: "자원 이름과 <code>id</code> 를 받아 REST 주소를 만들어 주세요. <code>id</code> 가 <b>없으면</b> 묶음 주소입니다. 이름은 <b>복수형</b>(끝에 <code>s</code>)으로 씁니다.",
      src: "function resourcePath(name, id) {\n  return '/' + name + '/' + id;\n}",
      sol: "function resourcePath(name, id) {\n  const base = '/' + name + 's';\n  return id === undefined || id === null ? base : base + '/' + id;\n}",
      tests: [["resourcePath('user', 12)", "'/users/12'"],
              ["resourcePath('user')", "'/users'"],
              ["resourcePath('order', 'a1')", "'/orders/a1'"]],
      edge: [["resourcePath('user', 0)", "'/users/0'"],
             ["resourcePath('user', null)", "'/users'"]],
      ex: "id 를 안 넘겼을 때 '/user/undefined' 같은 주소가 만들어지면, 그 주소로 요청이 나가고 나서야 이상한 줄 압니다. 없을 때를 먼저 갈라 두면 그런 주소가 아예 생기지 않아요.",
    },
    {
      k: "statusFor · 결과에 맞는 상태 코드",
      qq: "<code>action</code> 과 <code>found</code> 를 보고 상태 코드를 정하세요. <code>'create'</code>는 201, <code>'delete'</code>는 204, <code>'get'</code>은 찾았으면 200·못 찾았으면 404 입니다.",
      src: "function statusFor(action, found) {\n  return 200;\n}",
      sol: "function statusFor(action, found) {\n  if (action === 'create') return 201;\n  if (action === 'delete') return 204;\n  return found ? 200 : 404;\n}",
      tests: [["statusFor('create', true)", "201"],
              ["statusFor('get', false)", "404"],
              ["statusFor('delete', true)", "204"]],
      edge: [["statusFor('get', true)", "200"]],
      ex: "전부 200으로 주고 본문에 실패라고 적으면, 중간의 캐시나 모니터링 도구는 그것을 성공으로 셉니다. 오류율 그래프가 평평한데 사용자는 안 된다고 하는 상황이 이렇게 생겨요.",
    },
    {
      k: "pageLinks · 마지막 쪽에서는 없다고 하기",
      qq: "전체 개수·현재 쪽·쪽 크기를 받아 <code>{ next, prev }</code> 를 돌려주세요. 없으면 <code>null</code> 입니다. 쪽 번호는 1부터입니다.",
      src: "function pageLinks(total, page, size) {\n  return { next: page + 1, prev: page - 1 };\n}",
      sol: "function pageLinks(total, page, size) {\n  const last = Math.ceil(total / size);\n  return {\n    next: page < last ? page + 1 : null,\n    prev: page > 1 ? page - 1 : null,\n  };\n}",
      tests: [["pageLinks(30, 1, 10)", "({ next: 2, prev: null })"],
              ["pageLinks(30, 3, 10)", "({ next: null, prev: 2 })"],
              ["pageLinks(30, 2, 10)", "({ next: 3, prev: 1 })"]],
      edge: [["pageLinks(0, 1, 10)", "({ next: null, prev: null })"],
             ["pageLinks(5, 1, 10)", "({ next: null, prev: null })"]],
      ex: "마지막 쪽에서도 '다음' 을 주면, 쓰는 쪽은 빈 응답을 한 번 받고 나서야 끝인 줄 압니다. 요청이 한 번 더 나가고, 화면에는 잠깐 빈 목록이 보여요.",
    },
  ],
},
/* ── 캐싱 전략 ────────────────────────────────────────────── */
{
  unit: "캐싱 전략",
  lesson: "직접 짜 보기 — 무엇을 열쇠로 삼을 것인가",
  th: {
    sum: "캐시는 **열쇠가 전부**다. 같은 요청이 같은 열쇠가 되지 않으면 캐시는 없는 것과 같다.",
    body: [
      { h: "순서가 달라도 같은 요청이다", t: "`?a=1&b=2` 와 `?b=2&a=1` 은 같은 요청인데, 글자를 그대로 열쇠로 쓰면 다른 것이 된다. 캐시가 두 벌 생기고 적중률은 절반이 된다. 열쇠를 만들 때 **정렬**해 두면 이 문제가 사라진다." },
      { h: "유효 기간의 경계를 정한다", t: "'10초 동안 쓴다' 고 할 때 정확히 10초가 된 순간은 살아 있는가 죽었는가. 이걸 정해 두지 않으면 사람마다 다르게 구현하고, 경계에서만 이상하게 동작한다. 한쪽으로 못 박아 둔다." },
      { h: "자리가 차면 무엇을 버릴까", t: "가장 오래 **안 쓴** 것을 버리는 방식(LRU)이 흔하다. 들어온 순서대로 버리면, 방금 읽어서 다시 쓸 가능성이 높은 것을 버리게 된다. '읽는 것도 사용' 이라는 점이 핵심이다." },
      { h: "캐시는 없어도 동작해야 한다", t: "캐시가 비었을 때도 결과는 같아야 한다. 캐시에만 있는 값이 생기면 그것은 캐시가 아니라 저장소다. 껐다 켜도 서비스가 멀쩡한지로 확인할 수 있다." },
    ],
    code: { c: "const key = path + '?' + Object.keys(params).sort()\n  .map(k => k + '=' + params[k]).join('&');", cap: "정렬해야 같은 열쇠가 된다" },
    key: ["열쇠는 정렬해서 만든다", "유효 기간 경계를 못 박는다", "안 쓴 지 오래된 것을 버린다"],
  },
  q: [
    {
      k: "cacheKey · 순서가 달라도 같은 열쇠",
      qq: "경로와 조건을 받아 캐시 열쇠를 만들어 주세요. 조건의 <b>순서가 달라도 같은 열쇠</b>여야 합니다. 형식은 <code>경로?a=1&b=2</code> 입니다.",
      src: "function cacheKey(path, params) {\n  return path + '?' + Object.keys(params).map(k => k + '=' + params[k]).join('&');\n}",
      sol: "function cacheKey(path, params) {\n  const q = Object.keys(params).sort().map(k => k + '=' + params[k]).join('&');\n  return q ? path + '?' + q : path;\n}",
      tests: [["cacheKey('/users', { a: 1, b: 2 })", "'/users?a=1&b=2'"],
              ["cacheKey('/users', { b: 2, a: 1 })", "'/users?a=1&b=2'"],
              ["cacheKey('/users', { b: 2, a: 1 }) === cacheKey('/users', { a: 1, b: 2 })", "true"]],
      edge: [["cacheKey('/users', {})", "'/users'"]],
      ex: "같은 요청이 다른 열쇠가 되면 캐시가 두 벌 생기고 적중률이 절반이 됩니다. 게다가 한쪽만 지워지는 일도 생겨요. 열쇠를 만들 때 정렬해 두면 순서가 끼어들 자리가 없습니다.",
    },
    {
      k: "isFresh · 유효 기간의 경계",
      qq: "저장 시각과 유효 기간(ms)을 보고 아직 쓸 수 있는지 판단하세요. <b>정확히 기간이 된 순간은 만료</b>로 봅니다.",
      src: "function isFresh(entry, now) {\n  return now - entry.at <= entry.ttl;\n}",
      sol: "function isFresh(entry, now) {\n  return now - entry.at < entry.ttl;\n}",
      tests: [["isFresh({ at: 0, ttl: 10 }, 5)", "true"],
              ["isFresh({ at: 0, ttl: 10 }, 10)", "false"],
              ["isFresh({ at: 0, ttl: 10 }, 11)", "false"]],
      edge: [["isFresh({ at: 0, ttl: 10 }, 9)", "true"],
             ["isFresh({ at: 0, ttl: 0 }, 0)", "false"]],
      ex: "경계를 정하지 않으면 사람마다 다르게 구현하고, 딱 그 순간에만 이상하게 동작합니다. 재현도 어려워서 찾는 데 오래 걸려요. 한쪽으로 못 박아 두면 모두가 같게 씁니다.",
    },
    {
      k: "LRU · 안 쓴 지 오래된 것부터 버리기",
      qq: "칸이 <code>cap</code>개인 캐시를 만드세요. 자리가 차면 <b>가장 오래 안 쓴</b> 것을 버립니다. <b>읽는 것도 사용</b>으로 칩니다.",
      src: "function makeCache(cap) {\n  const m = new Map();\n  return {\n    get(k) { return m.has(k) ? m.get(k) : null; },\n    put(k, v) {\n      if (m.size >= cap && !m.has(k)) m.delete(m.keys().next().value);\n      m.set(k, v);\n    },\n    keys() { return [...m.keys()]; },\n  };\n}",
      sol: "function makeCache(cap) {\n  const m = new Map();\n  return {\n    get(k) {\n      if (!m.has(k)) return null;\n      const v = m.get(k);\n      m.delete(k);\n      m.set(k, v);\n      return v;\n    },\n    put(k, v) {\n      if (m.has(k)) m.delete(k);\n      else if (m.size >= cap) m.delete(m.keys().next().value);\n      m.set(k, v);\n    },\n    keys() { return [...m.keys()]; },\n  };\n}",
      tests: [["(() => { const c = makeCache(2); c.put('a', 1); c.put('b', 2); c.get('a'); c.put('c', 3); return c.keys(); })()", "['a', 'c']"],
              ["(() => { const c = makeCache(2); c.put('a', 1); c.put('b', 2); c.put('c', 3); return c.keys(); })()", "['b', 'c']"],
              ["(() => { const c = makeCache(2); c.put('a', 1); c.get('a'); return c.get('a'); })()", "1"]],
      edge: [["(() => { const c = makeCache(1); c.put('a', 1); c.put('a', 2); return [c.keys(), c.get('a')]; })()", "[['a'], 2]"],
             ["makeCache(2).get('없음')", "null"]],
      ex: "읽기를 사용으로 치지 않으면, 방금 읽어서 곧 또 쓸 값을 버리게 됩니다. 결국 '자주 쓰는 것' 이 계속 밀려나 캐시가 제 몫을 못 해요. 읽을 때도 맨 뒤로 옮겨야 합니다.",
    },
  ],
},
/* ── 메시지 큐·비동기 처리 ────────────────────────────────── */
{
  unit: "메시지 큐·비동기 처리",
  lesson: "직접 짜 보기 — 같은 것이 두 번 와도",
  th: {
    sum: "큐는 **같은 메시지를 두 번 줄 수 있다.** 그래서 받는 쪽이 두 번 처리해도 괜찮게 만들어야 한다.",
    body: [
      { h: "왜 두 번 오나", t: "보낸 쪽은 '잘 받았다' 는 답을 못 들으면 다시 보낸다. 답이 오는 길에 끊겼을 뿐 실제로는 처리됐을 수도 있다. 그래서 '적어도 한 번' 은 보장해도 '정확히 한 번' 은 어렵다." },
      { h: "번호로 걸러 낸다", t: "메시지마다 고유 번호를 붙이고 이미 처리한 번호는 건너뛴다. 처음 것을 남기는지 나중 것을 남기는지도 정해 둬야 한다 — 대개 먼저 온 것이 정답이다." },
      { h: "다시 시도는 점점 뜸하게", t: "실패했다고 바로 다시 보내면, 이미 힘든 상대를 더 밀어붙인다. 기다리는 시간을 배로 늘리되 상한을 둔다. 상한이 없으면 몇 번 만에 몇 시간짜리 대기가 되어 사실상 멈춘 것이 된다." },
      { h: "같은 열쇠는 같은 곳으로", t: "같은 사용자의 메시지가 여러 칸으로 흩어지면 순서가 뒤섞인다. 열쇠를 숫자로 바꿔 칸 수로 나눈 나머지를 쓰면 같은 열쇠는 언제나 같은 칸으로 간다. 이때 계산이 한쪽으로 몰리면 그 칸만 바빠진다." },
    ],
    code: { c: "const wait = Math.min(base * 2 ** attempt, cap);\n\nconst part = hash(key) % n;   // 같은 열쇠는 같은 칸으로", cap: "두 번 와도 괜찮게" },
    key: ["같은 메시지가 두 번 올 수 있다", "다시 시도는 배로 늘리되 상한", "같은 열쇠는 같은 칸으로"],
  },
  q: [
    {
      k: "dedupe · 먼저 온 것만 남기기",
      qq: "메시지 목록에서 <code>id</code> 가 같은 것은 <b>먼저 온 것</b>만 남기세요. 순서는 그대로입니다.",
      src: "function dedupe(msgs) {\n  const m = new Map();\n  msgs.forEach(x => m.set(x.id, x));\n  return [...m.values()];\n}",
      sol: "function dedupe(msgs) {\n  const seen = new Set();\n  const out = [];\n  for (const x of msgs) {\n    if (seen.has(x.id)) continue;\n    seen.add(x.id);\n    out.push(x);\n  }\n  return out;\n}",
      tests: [["dedupe([{ id: 1, v: 'a' }, { id: 1, v: 'b' }]).map(x => x.v)", "['a']"],
              ["dedupe([{ id: 1, v: 'a' }, { id: 2, v: 'b' }, { id: 1, v: 'c' }]).map(x => x.v)", "['a', 'b']"],
              ["dedupe([]).length", "0"]],
      edge: [["dedupe([{ id: 0, v: 'a' }, { id: 0, v: 'b' }]).length", "1"]],
      ex: "`set` 으로 덮어쓰면 나중에 온 것이 남습니다. 재전송된 옛 메시지가 최신 처리 결과를 덮어쓰는 셈이라, 값이 거꾸로 돌아가는 사고가 생겨요.",
    },
    {
      k: "backoff · 배로 늘리되 상한 두기",
      qq: "몇 번째 시도인지 받아 기다릴 시간을 돌려주세요. <code>base * 2^attempt</code> 이되 <b><code>cap</code>을 넘지 않아야</b> 합니다. <code>attempt</code> 는 0부터입니다.",
      src: "function backoff(attempt, base, cap) {\n  return base * Math.pow(2, attempt);\n}",
      sol: "function backoff(attempt, base, cap) {\n  return Math.min(base * Math.pow(2, attempt), cap);\n}",
      tests: [["backoff(0, 100, 5000)", "100"],
              ["backoff(3, 100, 5000)", "800"],
              ["backoff(10, 100, 5000)", "5000"]],
      edge: [["backoff(0, 100, 50)", "50"],
             ["backoff(20, 100, 5000)", "5000"]],
      ex: "상한이 없으면 열 번째 시도에서 이미 100초를 기다리고, 스무 번째면 한 시간이 넘습니다. 사실상 멈춘 것인데 코드는 '재시도 중' 이라고 말해요.",
    },
    {
      k: "partition · 같은 열쇠는 같은 칸으로",
      qq: "열쇠를 받아 <code>0..n-1</code> 중 하나를 돌려주세요. <b>같은 열쇠는 언제나 같은 칸</b>이고, 글자가 다르면 되도록 흩어져야 합니다.",
      src: "function partition(key, n) {\n  return key.length % n;\n}",
      sol: "function partition(key, n) {\n  let h = 0;\n  for (let i = 0; i < key.length; i++) {\n    h = (h * 31 + key.charCodeAt(i)) % 1000000007;\n  }\n  return h % n;\n}",
      tests: [["partition('user-1', 4) === partition('user-1', 4)", "true"],
              ["partition('user-1', 4) === partition('user-2', 4)", "false"],
              ["[0, 1, 2, 3].includes(partition('아무거나', 4))", "true"]],
      edge: [["partition('', 4)", "0"],
             ["partition('x', 1)", "0"]],
      ex: "길이만 보면 'user-1' 과 'user-2' 가 같은 칸으로 갑니다. 글자가 다른데 같은 칸에 몰리면 한 칸만 바빠지고 나머지는 놀아요. 글자 하나하나를 섞어 넣어야 고르게 흩어집니다.",
    },
  ],
},
/* ── 장애 처리·복원력 ─────────────────────────────────────── */
{
  unit: "장애 처리·복원력",
  lesson: "직접 짜 보기 — 무너질 때 덜 무너지게",
  th: {
    sum: "상대가 아플 때 계속 두드리면 **같이 무너진다.** 잠깐 끊고, 조심스럽게 다시 본다.",
    body: [
      { h: "회로 차단기의 세 상태", t: "평소에는 통과(닫힘), 실패가 쌓이면 아예 막고(열림), 잠시 뒤 딱 한 번만 시험 삼아 보낸다(반열림). 반열림이 없으면 한 번 막힌 뒤 스스로 회복할 방법이 없어, 사람이 손으로 풀어 줘야 한다." },
      { h: "다시 시도는 안전할 때만", t: "같은 요청을 두 번 보내도 결과가 같은 일(조회·삭제)은 다시 시도해도 된다. 하지만 '결제하기' 를 다시 보내면 두 번 결제될 수 있다. 재시도 전에 그 일이 두 번 해도 되는 일인지부터 본다." },
      { h: "기다림에는 반드시 끝을 둔다", t: "응답이 안 오는 상대를 영영 기다리면, 그 요청을 붙들고 있는 자원도 영영 묶인다. 그런 요청이 쌓이면 멀쩡한 요청도 받지 못한다. 제한 시간을 두면 최소한 놓아줄 수는 있다." },
      { h: "실패를 값으로 다룬다", t: "실패했을 때 무엇을 돌려줄지 미리 정해 두면 부르는 쪽이 단순해진다. 예전 값을 그대로 보여 주거나, 빈 목록을 주거나, 명확히 실패라고 알린다 — 정하지 않으면 그때그때 다르게 처리된다." },
    ],
    code: { c: "if (failures >= threshold) {\n  return since >= coolMs ? 'half' : 'open';\n}\nreturn 'closed';", cap: "막고, 잠시 뒤 한 번만 시험" },
    key: ["열림·반열림·닫힘 세 상태", "재시도는 안전한 일에만", "기다림에는 끝을 둔다"],
  },
  q: [
    {
      k: "circuitState · 스스로 회복할 길 만들기",
      qq: "실패 횟수·기준·마지막 실패로부터 지난 시간·식힐 시간을 받아 상태를 돌려주세요. 기준 미만이면 <code>'closed'</code>, 기준 이상이고 아직 덜 식었으면 <code>'open'</code>, 다 식었으면 <code>'half'</code> 입니다.",
      src: "function circuitState(failures, threshold, since, coolMs) {\n  return failures >= threshold ? 'open' : 'closed';\n}",
      sol: "function circuitState(failures, threshold, since, coolMs) {\n  if (failures < threshold) return 'closed';\n  return since >= coolMs ? 'half' : 'open';\n}",
      tests: [["circuitState(1, 3, 0, 1000)", "'closed'"],
              ["circuitState(3, 3, 500, 1000)", "'open'"],
              ["circuitState(3, 3, 1000, 1000)", "'half'"]],
      edge: [["circuitState(0, 3, 9999, 1000)", "'closed'"],
             ["circuitState(9, 3, 5000, 1000)", "'half'"]],
      ex: "반열림이 없으면 한 번 막힌 회로가 스스로 열리지 못합니다. 상대가 다 나았는데도 계속 막혀 있어서, 사람이 손으로 풀어 줄 때까지 장애가 이어져요.",
    },
    {
      k: "withRetry · 될 때까지, 다만 정해진 횟수만",
      qq: "함수를 실행해 실패하면 다시 시도하세요. <b>최대 <code>n</code>번</b>까지이고, 끝까지 실패하면 <b>마지막 오류를 그대로</b> 던집니다.",
      src: "async function withRetry(fn, n) {\n  return await fn();\n}",
      sol: "async function withRetry(fn, n) {\n  let last;\n  for (let i = 0; i < n; i++) {\n    try {\n      return await fn();\n    } catch (e) {\n      last = e;\n    }\n  }\n  throw last;\n}",
      tests: [["withRetry(async () => 7, 3)", "7"],
              ["(() => { let c = 0; return withRetry(async () => { c++; if (c < 3) throw new Error('아직'); return c; }, 5); })()", "3"],
              ["withRetry(async () => { throw new Error('끝내'); }, 2).catch(e => e.message)", "'끝내'"]],
      edge: [["(() => { let c = 0; return withRetry(async () => { c++; throw new Error('x'); }, 3).catch(() => c); })()", "3"]],
      ex: "한 번만 해 보고 끝내면 잠깐 끊긴 것도 그대로 실패가 됩니다. 반대로 횟수를 안 정하면 영영 시도하며 자원을 붙들어요. 그리고 마지막 오류를 그대로 던져야 부르는 쪽이 원인을 압니다.",
    },
    {
      k: "withTimeout · 영영 기다리지 않기",
      qq: "프라미스를 기다리되 <code>ms</code> 안에 안 오면 <code>null</code> 을 돌려주세요. <b>예외를 던지지 말고</b> 값으로 알립니다.",
      src: "async function withTimeout(p, ms) {\n  return await p;\n}",
      sol: "function withTimeout(p, ms) {\n  return Promise.race([\n    p,\n    new Promise(res => setTimeout(() => res(null), ms)),\n  ]);\n}",
      tests: [["withTimeout(Promise.resolve('값'), 100)", "'값'"],
              ["withTimeout(new Promise(r => setTimeout(() => r('늦음'), 400)), 100)", "null"],
              ["withTimeout(new Promise(r => setTimeout(() => r('빠름'), 10)), 200)", "'빠름'"]],
      edge: [["withTimeout(Promise.resolve(0), 100)", "0"]],
      ex: "응답이 안 오는 상대를 영영 기다리면, 그 요청이 붙들고 있는 자원도 영영 묶입니다. 그런 요청이 쌓이면 멀쩡한 요청까지 못 받게 돼요. 제한을 두면 최소한 놓아줄 수는 있습니다.",
    },
  ],
},
/* ── 큐·캐시·레이트리밋 ───────────────────────────────────── */
{
  unit: "큐·캐시·레이트리밋",
  lesson: "직접 짜 보기 — 얼마나 받아 줄 것인가",
  th: {
    sum: "받아 줄 양을 정해 두지 않으면, 바쁜 순간에 **모두가 조금씩 실패한다.**",
    body: [
      { h: "토큰 통은 순간의 몰림을 허용한다", t: "일정 속도로 토큰을 채우고, 요청마다 하나씩 쓴다. 안 쓰고 모아 둔 만큼은 한꺼번에 쓸 수 있어 잠깐의 몰림을 견딘다. 다만 모아 두는 양에 상한이 없으면, 오래 쉬었다가 한 번에 쏟아붓는 것을 막지 못한다." },
      { h: "구간을 미끄러뜨려 센다", t: "'최근 1분에 몇 번' 을 셀 때, 정각마다 세면 59초와 1분 1초에 몰아 쓸 수 있다. 지금부터 1분 전까지를 그때그때 세면 그 빈틈이 없다. 대신 기록을 들고 있어야 한다." },
      { h: "큐에도 상한이 필요하다", t: "처리 속도보다 빨리 쌓이면 큐는 끝없이 자란다. 메모리가 바닥나 통째로 죽는 것보다, 넘칠 때 버리는 편이 낫다. 무엇을 버릴지는 정해야 한다 — 대개 오래된 것부터다." },
      { h: "거절도 응답이다", t: "받아 줄 수 없으면 빨리 거절하는 편이 낫다. 기다리게 해 놓고 나중에 실패하면 그동안의 자원이 전부 낭비된다. 언제 다시 오라고 알려 주면 더 좋다." },
    ],
    code: { c: "tokens = Math.min(cap, tokens + rate * elapsed);\n\nrecent = times.filter(t => now - t < windowMs);", cap: "정해 두고 빨리 거절한다" },
    key: ["모아 두는 양에 상한", "구간은 미끄러뜨려 센다", "큐에도 상한이 필요하다"],
  },
  q: [
    {
      k: "refill · 모아 두는 양에 상한 두기",
      qq: "지난 시간만큼 토큰을 채우되 <b><code>cap</code>을 넘지 않게</b> 하세요. <code>rate</code> 는 1ms 당 채우는 양입니다.",
      src: "function refill(tokens, cap, rate, elapsed) {\n  return tokens + rate * elapsed;\n}",
      sol: "function refill(tokens, cap, rate, elapsed) {\n  return Math.min(cap, tokens + rate * elapsed);\n}",
      tests: [["refill(0, 10, 0.01, 500)", "5"],
              ["refill(8, 10, 0.01, 500)", "10"],
              ["refill(0, 10, 0.01, 100000)", "10"]],
      edge: [["refill(10, 10, 0.01, 0)", "10"],
             ["refill(0, 10, 0.01, 0)", "0"]],
      ex: "상한이 없으면 하루 쉬었다가 한 번에 수만 번을 쏟아부을 수 있습니다. 제한을 걸어 둔 의미가 사라지고, 그 순간 뒤쪽 서비스가 무너져요.",
    },
    {
      k: "allowed · 최근 구간만 세기",
      qq: "지난 요청 시각들과 지금 시각을 받아, <b>최근 <code>windowMs</code> 안</b>의 요청이 <code>limit</code>보다 적으면 <code>true</code> 를 돌려주세요.",
      src: "function allowed(times, now, windowMs, limit) {\n  return times.length < limit;\n}",
      sol: "function allowed(times, now, windowMs, limit) {\n  const recent = times.filter(t => now - t < windowMs);\n  return recent.length < limit;\n}",
      tests: [["allowed([0, 1, 2], 1000, 100, 3)", "true"],
              ["allowed([950, 960, 970], 1000, 100, 3)", "false"],
              ["allowed([950, 960], 1000, 100, 3)", "true"]],
      edge: [["allowed([], 1000, 100, 1)", "true"],
             ["allowed([900], 1000, 100, 1)", "true"]],
      ex: "전체 기록을 세면 어제 보낸 요청까지 세어 오늘 아무것도 못 하게 됩니다. 지금부터 구간만큼만 거슬러 세야, '최근에 얼마나 썼는가' 라는 원래 질문에 답이 돼요.",
    },
    {
      k: "push · 넘치면 오래된 것부터 버리기",
      qq: "큐에 넣되 <code>max</code>를 넘으면 <b>가장 오래된 것</b>을 버리세요. 새 값은 항상 들어갑니다.",
      src: "function push(queue, item, max) {\n  if (queue.length >= max) return queue.slice();\n  return queue.concat([item]);\n}",
      sol: "function push(queue, item, max) {\n  const out = queue.concat([item]);\n  return out.length > max ? out.slice(out.length - max) : out;\n}",
      tests: [["push([1, 2], 3, 3)", "[1, 2, 3]"],
              ["push([1, 2, 3], 4, 3)", "[2, 3, 4]"],
              ["push([], 1, 2)", "[1]"]],
      edge: [["push([1, 2, 3, 4], 5, 2)", "[4, 5]"],
             ["push([1], 2, 1)", "[2]"]],
      ex: "새 값을 버리면 큐는 옛 자료로 굳어 버립니다. 모니터링 기록이라면 화면이 과거에 멈춰 있게 돼요. 넘칠 때는 대개 오래된 것부터 버리는 편이 쓸모 있습니다.",
    },
  ],
},
/* ── 로깅·모니터링·관측성 ─────────────────────────────────── */
{
  unit: "로깅·모니터링·관측성",
  lesson: "직접 짜 보기 — 나중에 읽을 수 있는 기록",
  th: {
    sum: "기록은 **사고가 난 뒤에** 읽는다. 그때 찾을 수 없으면 남긴 의미가 없다.",
    body: [
      { h: "글이 아니라 항목으로 남긴다", t: "`\"사용자 12 로그인 실패\"` 는 사람은 읽지만 기계는 못 센다. `{level, msg, userId}` 처럼 항목으로 남기면 '사용자별 실패 횟수' 같은 것을 바로 뽑을 수 있다. 문장에서 숫자를 다시 뜯어내는 코드는 곧 깨진다." },
      { h: "비밀은 절대 남기지 않는다", t: "비밀번호나 토큰이 기록에 한 번 들어가면, 그 기록을 보는 모든 사람이 볼 수 있게 된다. 지우기도 어렵다. 남기기 전에 가리는 자리를 한 곳 두고 거기서 전부 처리한다." },
      { h: "평균은 사고를 감춘다", t: "응답 시간 평균이 100ms 여도, 100명 중 5명은 3초를 기다리고 있을 수 있다. 상위 몇 퍼센트가 얼마나 걸리는지(p95, p99)를 봐야 그 사람들이 보인다. 평균만 보는 대시보드는 대개 평온하다." },
      { h: "이어 볼 수 있게 표를 붙인다", t: "요청마다 고유 번호를 붙여 모든 기록에 함께 남기면, 서비스 여러 곳을 지나간 하나의 요청을 이어서 볼 수 있다. 없으면 시각으로 짐작해 맞춰야 하고, 바쁜 시간대에는 그게 불가능하다." },
    ],
    code: { c: "log({ level: 'error', msg: '로그인 실패', userId: 12, reqId })\n\np95 = sorted[Math.ceil(0.95 * n) - 1]", cap: "항목으로 남기고 꼬리를 본다" },
    key: ["글 대신 항목으로", "비밀은 가리고 남긴다", "평균이 아니라 꼬리를 본다"],
  },
  q: [
    {
      k: "mask · 비밀을 가리고 남기기",
      qq: "기록할 객체에서 <code>password</code>·<code>token</code> 항목의 값을 <code>'***'</code> 로 바꿔 주세요. <b>중첩된 객체 안까지</b> 가려야 하고, 원본은 그대로 둡니다.",
      src: "function mask(obj) {\n  const out = Object.assign({}, obj);\n  if ('password' in out) out.password = '***';\n  return out;\n}",
      sol: "function mask(obj) {\n  const out = {};\n  for (const k of Object.keys(obj)) {\n    const v = obj[k];\n    if (k === 'password' || k === 'token') out[k] = '***';\n    else if (v && typeof v === 'object' && !Array.isArray(v)) out[k] = mask(v);\n    else out[k] = v;\n  }\n  return out;\n}",
      tests: [["mask({ id: 1, password: 'p' })", "({ id: 1, password: '***' })"],
              ["mask({ user: { token: 't', name: '가' } })", "({ user: { token: '***', name: '가' } })"],
              ["(() => { const o = { password: 'p' }; mask(o); return o.password; })()", "'p'"]],
      edge: [["mask({})", "({})"],
             ["mask({ token: 't', password: 'p' })", "({ token: '***', password: '***' })"]],
      ex: "겉에 있는 것만 가리면 중첩된 객체 안의 토큰이 그대로 남습니다. 기록에 한 번 들어간 비밀은 그 기록을 보는 모두가 볼 수 있고 지우기도 어려워요.",
    },
    {
      k: "logLine · 항목으로 남기기",
      qq: "수준·메시지·부가 항목을 받아 <b>JSON 한 줄</b>로 만들어 주세요. 항목 이름은 <b>가나다순</b>이고, 수준은 <b>대문자</b>입니다.",
      src: "function logLine(level, msg, fields) {\n  return level + ': ' + msg;\n}",
      sol: "function logLine(level, msg, fields) {\n  const o = Object.assign({ level: level.toUpperCase(), msg: msg }, fields || {});\n  const sorted = {};\n  Object.keys(o).sort().forEach(k => { sorted[k] = o[k]; });\n  return JSON.stringify(sorted);\n}",
      tests: [["logLine('error', '실패', { userId: 12 })", "'{\"level\":\"ERROR\",\"msg\":\"실패\",\"userId\":12}'"],
              ["logLine('info', '됨')", "'{\"level\":\"INFO\",\"msg\":\"됨\"}'"],
              ["JSON.parse(logLine('warn', '주의', { a: 1 })).a", "1"]],
      edge: [["logLine('info', '', {})", "'{\"level\":\"INFO\",\"msg\":\"\"}'"]],
      ex: "문장으로 남기면 나중에 '사용자별 실패 횟수' 를 뽑으려고 글자를 다시 뜯어야 합니다. 문장이 조금만 바뀌어도 그 코드는 깨져요. 항목으로 남기면 그대로 셀 수 있습니다.",
    },
    {
      k: "p95 · 평균이 감추는 것 보기",
      qq: "값 목록에서 <b>상위 5% 경계</b>(p95)를 돌려주세요. 정렬한 뒤 <code>ceil(0.95 * n) - 1</code> 번째 값입니다.",
      src: "function p95(xs) {\n  return xs.reduce((a, b) => a + b, 0) / xs.length;\n}",
      sol: "function p95(xs) {\n  if (!xs.length) return 0;\n  const s = xs.slice().sort((a, b) => a - b);\n  return s[Math.ceil(0.95 * s.length) - 1];\n}",
      tests: [["p95([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])", "10"],
              ["p95([1, 1, 1, 1, 100])", "100"],
              ["p95([5])", "5"]],
      edge: [["p95([])", "0"],
             ["(() => { const a = [3, 1, 2]; p95(a); return a; })()", "[3, 1, 2]"]],
      ex: "평균 100ms 인 화면에서도 100명 중 5명은 3초를 기다리고 있을 수 있습니다. 평균만 보는 대시보드는 대개 평온해요. 꼬리를 봐야 그 사람들이 보입니다.",
    },
  ],
},
];
