/* 클라우드 실행형 2 — 저장·큐·배포·관측의 계산을 직접 만들어 본다.
   객체 저장소와 서명, 큐와 재처리, 배포 전략과 롤백, 지표와 경보.
   첫 실행형 유닛과 겹치지 않는 함수만 다룬다. */
module.exports = [

/* ───────────── 객체 저장소와 접근 ───────────── */
{ track: "cloud", k: "열쇠는 폴더가 아니다 · keyPrefix", cat: "internals",
  q: "객체 열쇠 목록에서 지정한 접두사 아래의 <b>바로 다음 한 층</b>만 골라 정렬해 돌려주세요. 더 깊은 것은 그 층의 이름으로 접고 중복은 없앱니다.",
  src: "function keyPrefix(keys, prefix) {\n  // TODO: 접두사를 떼고 첫 조각만 남기세요\n  return [];\n}",
  sol: "function keyPrefix(keys, prefix) {\n  const out = new Set();\n  keys.forEach((k) => {\n    if (String(k).indexOf(prefix) !== 0) return;\n    const rest = String(k).slice(prefix.length);\n    const cut = rest.indexOf(\"/\");\n    out.add(cut < 0 ? rest : rest.slice(0, cut + 1));\n  });\n  return [...out].sort();\n}",
  tests: [['keyPrefix(["a/b.txt","a/c/d.txt","z.txt"], "a/")', '["b.txt","c/"]'],
    ['keyPrefix(["a/b/c","a/b/d"], "a/")', '["b/"]'],
    ['keyPrefix(["x.txt","y.txt"], "")', '["x.txt","y.txt"]'],
    ['keyPrefix(["a/b"], "z/")', '[]']],
  edge: [['keyPrefix([], "a/")', '[]'], ['keyPrefix(["a/"], "a/")', '[""]']],
  ex: "객체 저장소에는 <b>폴더가 없습니다.</b> 열쇠는 그냥 긴 문자열이고, 콘솔에서 폴더처럼 보이는 것은 이 계산으로 <b>그때그때 만들어 낸 착시</b>입니다.\n그래서 '폴더 이름 바꾸기' 같은 것이 없습니다. 안에 든 객체를 전부 새 열쇠로 복사하고 옛것을 지우는 수밖에 없어, 객체가 많으면 아주 비싼 작업이 됩니다.\n같은 이유로 <b>빈 폴더</b>도 없습니다. 마지막 객체를 지우면 폴더가 통째로 사라지는데, 파일 시스템처럼 동작할 것이라 믿고 만든 코드가 여기서 어긋납니다.\n열쇠 이름이 성능에도 영향을 줍니다. 앞부분이 전부 같으면 요청이 한 곳에 몰릴 수 있어, 예전에는 <b>앞자리를 흩뜨리는</b> 설계를 권했습니다. 지금은 많이 나아졌지만 날짜를 앞에 두는 습관은 여전히 조심할 자리입니다." },

{ track: "cloud", k: "언제까지 쓸 수 있나 · presignValid", cat: "security",
  q: "서명 발급 시각과 유효 시간(초), 지금 시각을 받아 <code>\"valid\"</code> 또는 <code>\"expired\"</code> 를 돌려주세요. 발급보다 이른 시각은 <code>\"early\"</code> 입니다. 만료 시각과 같은 순간은 아직 유효합니다.",
  src: "function presignValid(issued, ttlSec, now) {\n  // TODO: 이른 경우와 지난 경우를 나누세요\n  return \"valid\";\n}",
  sol: "function presignValid(issued, ttlSec, now) {\n  if (now < issued) return \"early\";\n  return now <= issued + ttlSec ? \"valid\" : \"expired\";\n}",
  tests: [['presignValid(100, 60, 120)', '"valid"'],
    ['presignValid(100, 60, 200)', '"expired"'],
    ['presignValid(100, 60, 90)', '"early"'],
    ['presignValid(100, 60, 160)', '"valid"']],
  edge: [['presignValid(0, 0, 0)', '"valid"'], ['presignValid(100, 60, 161)', '"expired"']],
  ex: "서명된 URL 은 <b>권한을 시간으로 빌려주는</b> 방법입니다. 서버를 거치지 않고 저장소에 곧바로 올리거나 내려받게 해 주면서, 그 권한이 오래 남지 않게 합니다.\n유효 시간을 짧게 잡는 것이 핵심입니다. 링크가 로그·채팅·브라우저 기록에 남기 때문에 <b>새어도 곧 쓸모없어지는</b> 것이 유일한 방어입니다. 며칠짜리 링크는 사실상 공개와 다르지 않습니다.\n'이른' 경우를 따로 둔 이유는 <b>시계 어긋남</b> 때문입니다. 서버들의 시각이 몇 초 다르면 방금 만든 링크가 아직 유효하지 않다고 거절되는데, 이 상황을 만료와 같이 처리하면 원인을 찾기 어렵습니다.\n서명은 <b>취소할 수 없다</b>는 성질이 있습니다. 이미 나간 링크를 무르려면 열쇠를 바꾸거나 객체를 옮겨야 하므로, 유효 시간이 사실상 유일한 조절 장치입니다." },

{ track: "cloud", k: "옮겨야 하나 남겨야 하나 · lifecycleAction", cat: "ops",
  q: "객체 나이(일)와 규칙 목록 <code>[일수, 동작]</code> 을 받아, <b>조건을 만족하는 것 중 가장 큰 일수</b>의 동작을 돌려주세요. 없으면 <code>\"keep\"</code> 입니다.",
  src: "function lifecycleAction(ageDays, rules) {\n  // TODO: 만족하는 규칙 중 가장 늦은 것을 고르세요\n  return \"keep\";\n}",
  sol: "function lifecycleAction(ageDays, rules) {\n  let best = null;\n  rules.forEach((r) => {\n    if (ageDays >= r[0] && (!best || r[0] > best[0])) best = r;\n  });\n  return best ? best[1] : \"keep\";\n}",
  tests: [['lifecycleAction(40, [[30,"cold"],[365,"delete"]])', '"cold"'],
    ['lifecycleAction(400, [[30,"cold"],[365,"delete"]])', '"delete"'],
    ['lifecycleAction(10, [[30,"cold"]])', '"keep"'],
    ['lifecycleAction(30, [[30,"cold"]])', '"cold"']],
  edge: [['lifecycleAction(0, [])', '"keep"'], ['lifecycleAction(100, [[1,"a"],[50,"b"]])', '"b"']],
  ex: "수명 주기 규칙은 <b>저장 비용을 줄이는 가장 손쉬운 장치</b>입니다. 오래된 로그를 값싼 등급으로 옮기고 더 오래된 것은 지우는 규칙 두 줄이 요금의 큰 부분을 정합니다.\n여러 규칙이 걸릴 때 <b>가장 늦은 것</b>을 고르는 것이 자연스럽습니다. 400일 된 객체는 '30일 넘음' 과 '365일 넘음' 둘 다 만족하지만, 실제로 해야 할 일은 지우는 쪽입니다.\n값싼 등급의 함정은 <b>꺼내는 값</b>입니다. 저장비는 크게 줄지만 읽을 때 요금이 붙고 시간도 걸려, 자주 조회하는 데이터라면 옮겨서 아낀 것보다 더 냅니다.\n최소 보관 기간도 있습니다. 값싼 등급에 넣자마자 지우면 <b>남은 기간만큼 요금이 청구되어</b>, 짧게 살다 갈 데이터를 옮기는 규칙은 오히려 손해입니다." },

{ track: "cloud", k: "덮어쓸까 건너뛸까 · syncPlan", cat: "ops",
  q: "원본과 대상의 <code>[열쇠, 수정시각]</code> 목록을 받아 <b>복사해야 할 열쇠</b>를 정렬해 돌려주세요. 대상에 없거나 원본이 더 새로우면 복사합니다.",
  src: "function syncPlan(source, target) {\n  // TODO: 대상의 시각과 견주세요\n  return [];\n}",
  sol: "function syncPlan(source, target) {\n  const t = new Map(target);\n  return source.filter((s) => !t.has(s[0]) || s[1] > t.get(s[0]))\n    .map((s) => s[0]).sort();\n}",
  tests: [['syncPlan([["a",5],["b",1]], [["a",3]])', '["a","b"]'],
    ['syncPlan([["a",1]], [["a",5]])', '[]'],
    ['syncPlan([["a",5]], [["a",5]])', '[]'],
    ['syncPlan([], [["a",1]])', '[]']],
  edge: [['syncPlan([["z",1],["y",1]], [])', '["y","z"]'], ['syncPlan([["a",2]], [["a",1]])', '["a"]']],
  ex: "<code>aws s3 sync</code> 가 하는 판단입니다. 전부 복사하는 대신 <b>달라진 것만</b> 옮기면 시간과 전송비를 크게 아낍니다.\n시각이 같을 때 건너뛰는 것이 이 방식의 전제입니다. 그런데 <b>시각은 믿을 수 있는 표식이 아닙니다</b> — 내용이 바뀌어도 시각이 같을 수 있고, 시계가 어긋난 기계에서 만든 파일은 미래의 시각을 갖습니다.\n그래서 정확해야 하는 곳에서는 <b>내용 해시</b>로 견줍니다. 계산 비용이 들지만 '같아 보이는데 다른' 상황이 없어집니다. 크기까지 함께 보면 대부분의 어긋남은 잡힙니다.\n대상에만 있는 것을 지울지도 결정해야 합니다. 지우는 옵션은 편하지만 <b>되돌릴 수 없어서</b>, 실수로 원본을 잘못 지정하면 대상이 통째로 비워집니다. 먼저 예행연습으로 목록을 확인합니다." },

{ track: "cloud", k: "여러 조각으로 올린다 · partPlan", cat: "impl",
  q: "전체 크기와 조각 크기를 받아 각 조각의 <b>바이트 수</b>를 배열로 돌려주세요. 마지막 조각은 남은 만큼입니다. 크기가 0 이하면 빈 배열입니다.",
  src: "function partPlan(total, part) {\n  // TODO: 조각 크기로 나누고 나머지를 붙이세요\n  return [];\n}",
  sol: "function partPlan(total, part) {\n  if (!(total > 0) || !(part > 0)) return [];\n  const out = [];\n  let left = total;\n  while (left > 0) { out.push(Math.min(part, left)); left -= part; }\n  return out;\n}",
  tests: [['partPlan(250, 100)', '[100,100,50]'],
    ['partPlan(200, 100)', '[100,100]'],
    ['partPlan(50, 100)', '[50]'],
    ['partPlan(0, 100)', '[]']],
  edge: [['partPlan(100, 0)', '[]'], ['partPlan(1, 1)', '[1]']],
  ex: "큰 파일을 <b>조각으로 나눠 올리는</b> 것은 선택이 아니라 필수입니다. 한 번에 올리다 실패하면 처음부터 다시 해야 하지만, 조각이면 실패한 것만 다시 올립니다.\n조각을 <b>병렬로</b> 올릴 수 있는 것도 큰 이점입니다. 하나의 연결이 낼 수 있는 속도에는 한계가 있어, 여러 조각을 동시에 보내면 전체 시간이 크게 줄어듭니다.\n조심할 것이 있습니다 — 조각을 다 올리고 <b>마무리 요청</b>을 보내야 객체가 생깁니다. 중간에 그만두면 올라간 조각들이 저장소에 남아 요금이 붙는데, 목록에 안 보여서 알아채기 어렵습니다.\n그래서 미완성 업로드를 자동으로 걷어 내는 수명 주기 규칙을 함께 겁니다. '왜 저장 용량이 계산과 안 맞지' 의 흔한 답이 <b>남은 조각</b>입니다." },

/* ───────────── 큐와 비동기 처리 ───────────── */
{ track: "cloud", k: "보이지 않는 동안 · visibilityEnd", cat: "internals",
  q: "받은 시각과 가림 시간(초), 연장 횟수를 받아 <b>다시 보이게 되는 시각</b>을 돌려주세요. 연장은 한 번마다 가림 시간만큼 늘어나고, 음수 연장은 0으로 봅니다.",
  src: "function visibilityEnd(received, timeoutSec, extends_) {\n  // TODO: 연장 횟수만큼 더하세요\n  return received;\n}",
  sol: "function visibilityEnd(received, timeoutSec, extends_) {\n  const n = extends_ > 0 ? extends_ : 0;\n  return received + timeoutSec * (n + 1);\n}",
  tests: [['visibilityEnd(100, 30, 0)', '130'],
    ['visibilityEnd(100, 30, 2)', '190'],
    ['visibilityEnd(0, 60, 1)', '120'],
    ['visibilityEnd(100, 30, -5)', '130']],
  edge: [['visibilityEnd(0, 0, 3)', '0'], ['visibilityEnd(50, 10, 1)', '70']],
  ex: "큐에서 메시지를 받으면 지워지는 것이 아니라 <b>잠깐 안 보이게</b> 됩니다. 처리에 성공해 지우기 전에 시간이 다하면 다시 나타나, 처리하던 프로세스가 죽어도 일이 사라지지 않습니다.\n이 시간을 <b>처리 시간보다 짧게</b> 잡으면 최악의 일이 벌어집니다 — 아직 처리 중인데 메시지가 다시 보여 다른 워커가 같은 일을 시작하고, 그것이 반복되면 같은 작업이 계속 늘어납니다.\n길게 잡는 것도 답이 아닙니다. 워커가 죽었을 때 <b>그만큼 기다려야</b> 다른 워커가 이어받으므로, 처리가 오래 걸리는 일에는 고정 값 대신 <b>연장</b>을 씁니다.\n연장은 처리 중에 '아직 살아 있다' 를 알리는 신호입니다. 그래서 실제 처리 시간을 모르는 작업도 안전하게 다룰 수 있고, 워커가 죽으면 연장이 끊겨 곧 다시 보이게 됩니다." },

{ track: "cloud", k: "더 못 하겠다 · deadLetter", cat: "ops",
  q: "메시지별 시도 횟수 목록과 한계를 받아, <b>한계 이상 시도한</b> 메시지 번호를 오름차순으로 돌려주세요. 입력은 <code>[번호, 시도횟수]</code> 목록입니다.",
  src: "function deadLetter(msgs, limit) {\n  // TODO: 한계 이상인 것을 고르세요\n  return [];\n}",
  sol: "function deadLetter(msgs, limit) {\n  return msgs.filter((m) => m[1] >= limit)\n    .map((m) => m[0]).sort((a, b) => a - b);\n}",
  tests: [['deadLetter([[1,3],[2,1]], 3)', '[1]'],
    ['deadLetter([[1,5],[2,4]], 3)', '[1,2]'],
    ['deadLetter([[1,1]], 3)', '[]'],
    ['deadLetter([], 3)', '[]']],
  edge: [['deadLetter([[9,3],[2,3]], 3)', '[2,9]'], ['deadLetter([[1,0]], 0)', '[1]']],
  ex: "처리에 계속 실패하는 메시지를 <b>따로 모아 두는</b> 장치입니다. 없으면 그 메시지가 큐를 막거나, 무한히 재시도되며 로그와 요금만 쌓입니다.\n한계를 정하는 데 판단이 필요합니다. 너무 작으면 <b>일시적인 장애</b>로도 죽은 편지가 되고, 너무 크면 못 고칠 메시지가 오래 자원을 씁니다. 대개 3~5회가 출발점입니다.\n죽은 편지 큐는 <b>보라고 만든 것</b>입니다. 쌓이는 것을 아무도 안 보면 그냥 조용히 잃어버리는 것과 같으므로, 여기에 메시지가 들어오면 경보가 울리게 합니다.\n원인을 고친 뒤에는 다시 넣어 처리할 수 있어야 합니다. 그래서 죽은 편지에는 <b>원래 메시지 그대로</b>와 실패 이유를 함께 담아 둡니다." },

{ track: "cloud", k: "한 번만 처리한다 · dedupe", cat: "impl",
  q: "메시지 아이디 목록을 받아 <b>처음 나온 것만</b> 순서를 지켜 돌려주세요. 이미 본 아이디는 건너뜁니다.",
  src: "function dedupe(ids) {\n  // TODO: 본 것을 기억하며 훑으세요\n  return [];\n}",
  sol: "function dedupe(ids) {\n  const seenIds = new Set();\n  const out = [];\n  ids.forEach((id) => { if (!seenIds.has(id)) { seenIds.add(id); out.push(id); } });\n  return out;\n}",
  tests: [['dedupe(["a","b","a"])', '["a","b"]'],
    ['dedupe(["x","x","x"])', '["x"]'],
    ['dedupe(["p","q"])', '["p","q"]'],
    ['dedupe([])', '[]']],
  edge: [['dedupe(["z"])', '["z"]'], ['dedupe(["a","b","c","b","a"])', '["a","b","c"]']],
  ex: "대부분의 큐는 <b>적어도 한 번</b>을 약속합니다. 정확히 한 번이 아니라는 뜻이라, 같은 메시지가 두 번 오는 것은 장애가 아니라 <b>정상 동작</b>입니다.\n그래서 처리하는 쪽이 <b>여러 번 실행돼도 안전</b>해야 합니다. 이 함수처럼 아이디로 걸러 내거나, 아예 결과가 같아지도록 만드는 것(같은 값으로 덮어쓰기 같은)이 두 가지 길입니다.\n걸러 내는 방식에는 저장이 필요합니다. 본 아이디를 어딘가 기억해야 하는데, 무한히 쌓을 수 없으므로 <b>기간을 정해</b> 그 안에서만 중복을 막습니다. 그 기간을 넘겨 재전송되면 다시 처리됩니다.\n결제처럼 두 번 하면 안 되는 일에는 <b>업무 수준의 열쇠</b>를 씁니다. 메시지 아이디가 아니라 주문 번호로 걸러야, 다른 경로로 들어온 중복까지 막힙니다." },

{ track: "cloud", k: "얼마나 밀렸나 · queueLag", cat: "ops",
  q: "대기 중인 메시지 수와 초당 처리량을 받아 <b>비우는 데 걸리는 초</b>를 올림해 돌려주세요. 처리량이 0 이하면 <code>-1</code> 입니다.",
  src: "function queueLag(pending, perSec) {\n  // TODO: 나눈 뒤 올리세요\n  return 0;\n}",
  sol: "function queueLag(pending, perSec) {\n  if (!(perSec > 0)) return -1;\n  return Math.ceil(pending / perSec);\n}",
  tests: [['queueLag(100, 10)', '10'],
    ['queueLag(105, 10)', '11'],
    ['queueLag(0, 10)', '0'],
    ['queueLag(50, 0)', '-1']],
  edge: [['queueLag(1, 100)', '1'], ['queueLag(1000, -1)', '-1']],
  ex: "큐의 건강은 <b>길이</b>가 아니라 <b>비우는 데 걸리는 시간</b>으로 봅니다. 1만 개가 밀려도 초당 5천 개를 처리한다면 2초이고, 100개라도 초당 1개면 100초입니다.\n이 값이 경보의 기준이 되어야 합니다. 길이로 경보를 걸면 처리량이 늘어난 뒤에도 옛 기준이 남아, <b>정상인데 울리는 경보</b>가 됩니다.\n처리량이 0인 경우를 <code>-1</code> 로 구분한 이유가 있습니다. 나누면 <code>Infinity</code> 가 나와 비교가 이상해지는데, 이것은 '오래 걸린다' 가 아니라 <b>워커가 죽었다</b>는 완전히 다른 상황입니다.\n추세가 값 자체보다 중요합니다. 늘고 있으면 처리 능력이 모자란 것이고, 일정하면 감당하고 있는 것이며, 갑자기 뛰었으면 <b>어딘가 막힌 것</b>입니다." },

{ track: "cloud", k: "몇 명이 필요한가 · workersNeeded", cat: "design",
  q: "초당 도착 수, 한 건 처리 시간(초), 목표 사용률(0~1)을 받아 필요한 워커 수를 <b>올림</b>해 돌려주세요. 사용률이 0 이하나 1 초과면 <code>-1</code> 입니다.",
  src: "function workersNeeded(rate, serviceSec, util) {\n  // TODO: 필요한 일손을 구한 뒤 사용률로 나누세요\n  return 0;\n}",
  sol: "function workersNeeded(rate, serviceSec, util) {\n  if (!(util > 0) || util > 1) return -1;\n  return Math.ceil((rate * serviceSec) / util);\n}",
  tests: [['workersNeeded(10, 1, 1)', '10'],
    ['workersNeeded(10, 1, 0.5)', '20'],
    ['workersNeeded(10, 0.2, 0.8)', '3'],
    ['workersNeeded(10, 1, 0)', '-1']],
  edge: [['workersNeeded(0, 1, 0.5)', '0'], ['workersNeeded(10, 1, 1.5)', '-1']],
  ex: "'도착 수 × 처리 시간' 이 필요한 <b>동시 일손</b>입니다. 초당 10건이 오고 한 건에 1초가 걸리면 언제나 10건이 처리 중이라는 뜻입니다.\n사용률로 나누는 것이 중요한 대목입니다. 사용률 100% 로 맞추면 <b>여유가 하나도 없어</b> 조금만 몰려도 줄이 무한히 길어집니다. 대기 시간은 사용률이 1에 가까워질수록 급격히 늘어납니다.\n그래서 70~80% 를 목표로 잡는 것이 관행입니다. 놀고 있는 20% 는 낭비가 아니라 <b>변동을 흡수하는 완충</b>입니다.\n처리 시간이 흔들리면 평균만으로는 부족합니다. 가끔 아주 오래 걸리는 건이 섞이면 그동안 일손이 묶이므로, <b>꼬리 쪽 값</b>까지 보고 여유를 더 둡니다." },

/* ───────────── 배포와 되돌리기 ───────────── */
{ track: "cloud", k: "몇 대씩 바꿀까 · rollingBatches", cat: "ops",
  q: "전체 대수와 한 번에 바꿀 최대 비율(0~1)을 받아, 각 회차에 바꾸는 대수를 배열로 돌려주세요. 한 회차 대수는 <b>최소 1</b>이고 내림으로 계산합니다.",
  src: "function rollingBatches(total, pct) {\n  // TODO: 회차 크기를 정하고 남은 만큼 쪼개세요\n  return [];\n}",
  sol: "function rollingBatches(total, pct) {\n  if (!(total > 0)) return [];\n  const size = Math.max(Math.floor(total * pct), 1);\n  const out = [];\n  let left = total;\n  while (left > 0) { out.push(Math.min(size, left)); left -= size; }\n  return out;\n}",
  tests: [['rollingBatches(10, 0.5)', '[5,5]'],
    ['rollingBatches(10, 0.3)', '[3,3,3,1]'],
    ['rollingBatches(3, 0.1)', '[1,1,1]'],
    ['rollingBatches(0, 0.5)', '[]']],
  edge: [['rollingBatches(1, 1)', '[1]'], ['rollingBatches(4, 0.5)', '[2,2]']],
  ex: "순차 배포의 계산입니다. 한 번에 전부 바꾸지 않고 <b>조금씩</b> 바꾸면, 새 버전이 잘못됐을 때 피해가 그 몫으로 제한됩니다.\n회차 크기가 <b>속도와 위험의 맞바꿈</b>입니다. 크게 잡으면 배포가 빠르지만 한 번에 많은 사용자가 영향을 받고, 작게 잡으면 안전하지만 오래 걸려 두 버전이 함께 도는 시간이 길어집니다.\n최소 1을 보장한 것이 중요합니다. 3대에 10% 면 0.3 인데 내림하면 0이 되어 <b>영원히 끝나지 않는 배포</b>가 됩니다. 이런 경계는 작은 환경에서만 드러나 운영에서 늦게 발견됩니다.\n순차 배포에는 전제가 있습니다 — 두 버전이 <b>동시에 돌아도 괜찮아야</b> 합니다. DB 스키마를 함께 바꾼다면 옛 코드도 새 스키마에서 돌 수 있게 먼저 준비해야 합니다." },

{ track: "cloud", k: "얼마씩 흘려보낼까 · canaryStep", cat: "ops",
  q: "지금 비율(%)과 관측된 오류율(%), 허용 오류율을 받아 <code>[\"up\"|\"hold\"|\"rollback\", 다음비율]</code> 을 돌려주세요. 허용 초과면 되돌려 0, 허용의 절반 이하면 두 배(최대 100), 그 사이면 유지합니다.",
  src: "function canaryStep(pct, errPct, limitPct) {\n  // TODO: 세 구간으로 나누세요\n  return [\"hold\", pct];\n}",
  sol: "function canaryStep(pct, errPct, limitPct) {\n  if (errPct > limitPct) return [\"rollback\", 0];\n  if (errPct <= limitPct / 2) return [\"up\", Math.min(pct * 2, 100)];\n  return [\"hold\", pct];\n}",
  tests: [['canaryStep(10, 5, 2)', '["rollback",0]'],
    ['canaryStep(10, 0.5, 2)', '["up",20]'],
    ['canaryStep(10, 1.5, 2)', '["hold",10]'],
    ['canaryStep(60, 0, 2)', '["up",100]']],
  edge: [['canaryStep(10, 2, 2)', '["hold",10]'], ['canaryStep(100, 0, 2)', '["up",100]']],
  ex: "카나리 배포는 <b>새 버전에 조금씩 트래픽을 흘려보내며</b> 지표를 보는 방식입니다. 문제가 있으면 그 비율만큼만 영향을 받습니다.\n세 구간으로 나눈 것이 요점입니다. '나쁘면 되돌린다' 만 있으면 언제 늘릴지를 사람이 매번 판단해야 하는데, <b>충분히 좋을 때 늘린다</b>는 조건까지 있어야 자동으로 굴러갑니다.\n허용의 절반을 기준으로 삼은 것은 <b>여유를 두는</b> 설계입니다. 아슬아슬하게 통과하는 상태에서 비율을 늘리면 곧바로 한계를 넘게 되므로, 확실히 좋을 때만 앞으로 갑니다.\n비율이 작을 때는 <b>표본이 모자란다</b>는 함정이 있습니다. 1% 로 흘려보내는 동안 요청이 100건이면 오류율 0% 는 아무 뜻이 없어, 최소 관측 수를 함께 조건으로 두어야 합니다." },

{ track: "cloud", k: "되돌릴 수 있나 · rollbackSafe", cat: "design",
  q: "스키마 변경 종류와 데이터 이전 여부를 받아 <code>\"safe\"</code>, <code>\"forward-only\"</code>, <code>\"risky\"</code> 중 하나를 돌려주세요. <code>\"add\"</code> 는 안전, <code>\"drop\"</code> 은 언제나 forward-only, 그 밖은 이전이 있었으면 risky·없으면 safe 입니다.",
  src: "function rollbackSafe(change, migrated) {\n  // TODO: 종류를 먼저 보고 이전 여부를 보세요\n  return \"safe\";\n}",
  sol: "function rollbackSafe(change, migrated) {\n  if (change === \"drop\") return \"forward-only\";\n  if (change === \"add\") return \"safe\";\n  return migrated ? \"risky\" : \"safe\";\n}",
  tests: [['rollbackSafe("add", false)', '"safe"'],
    ['rollbackSafe("drop", false)', '"forward-only"'],
    ['rollbackSafe("rename", true)', '"risky"'],
    ['rollbackSafe("rename", false)', '"safe"']],
  edge: [['rollbackSafe("add", true)', '"safe"'], ['rollbackSafe("drop", true)', '"forward-only"']],
  ex: "'되돌리면 된다' 는 코드에만 해당하는 말입니다. <b>데이터는 되돌릴 수 없습니다</b> — 지운 칸을 다시 만들어도 안에 들었던 값은 돌아오지 않습니다.\n그래서 칸을 <b>더하는 것</b>과 <b>빼는 것</b>의 위험이 완전히 다릅니다. 더하는 것은 옛 코드가 무시하면 그만이지만, 빼는 것은 옛 코드가 그 칸을 찾다가 터집니다.\n실무의 해법은 <b>두 단계로 나누는 것</b>입니다. 먼저 새 칸을 더해 양쪽을 다 쓰게 배포하고, 충분히 지난 뒤에 옛 칸을 지웁니다. 각 단계는 되돌릴 수 있고 두 버전이 함께 돌아도 괜찮습니다.\n이전이 있었으면 위험으로 본 것은 <b>값이 바뀌었기</b> 때문입니다. 형식을 바꾸는 이전을 되돌리려면 반대 방향의 이전을 또 만들어야 하는데, 그 과정에서 잃는 정보가 있을 수 있습니다." },

{ track: "cloud", k: "얼마나 오래 두 벌인가 · blueGreenCost", cat: "ops",
  q: "대당 시간 요금과 대수, 두 벌로 두는 시간(시간)을 받아 <b>추가로 드는 비용</b>을 소수 둘째 자리 반올림해 돌려주세요. 음수 입력은 0으로 봅니다.",
  src: "function blueGreenCost(hourly, count, hours) {\n  // TODO: 한 벌치의 추가 비용을 구하세요\n  return 0;\n}",
  sol: "function blueGreenCost(hourly, count, hours) {\n  const h = hourly > 0 ? hourly : 0;\n  const c = count > 0 ? count : 0;\n  const t = hours > 0 ? hours : 0;\n  return Math.round(h * c * t * 100) / 100;\n}",
  tests: [['blueGreenCost(0.1, 10, 2)', '2'],
    ['blueGreenCost(0.5, 4, 1)', '2'],
    ['blueGreenCost(0.1, 10, 0)', '0'],
    ['blueGreenCost(-1, 10, 2)', '0']],
  edge: [['blueGreenCost(0.033, 3, 1)', '0.1'], ['blueGreenCost(1, 0, 5)', '0']],
  ex: "청·녹 배포는 <b>같은 규모를 한 벌 더</b> 띄워 두었다가 트래픽을 통째로 옮기는 방식입니다. 전환이 즉시이고 되돌리기도 즉시라는 것이 가장 큰 장점입니다.\n값은 이 계산입니다. 두 벌을 유지하는 동안 <b>대수만큼의 요금이 그대로 더</b> 나가므로, 전환 뒤 옛 벌을 얼마나 빨리 내리느냐가 비용을 정합니다.\n곧바로 내리지 않는 이유가 있습니다. 문제가 나중에 드러날 수 있어 <b>되돌릴 여지를 남겨 두는</b> 것인데, 그 시간이 곧 보험료입니다.\n순차 배포와 견주면 성격이 분명해집니다 — 순차는 싸지만 두 버전이 섞여 돌고, 청·녹은 비싸지만 <b>한 시점에 한 버전</b>만 돕니다. 스키마를 함께 바꿔야 할 때 후자가 편한 이유입니다." },

{ track: "cloud", k: "누가 먼저 준비되나 · readyOrder", cat: "ops",
  q: "<code>[이름, 의존이름들]</code> 목록을 받아 <b>의존이 없는 것부터</b> 준비할 순서를 돌려주세요. 같은 층에서는 이름 사전순이고, 순환이 있으면 빈 배열입니다.",
  src: "function readyOrder(nodes) {\n  // TODO: 의존이 전부 준비된 것을 층층이 꺼내세요\n  return [];\n}",
  sol: "function readyOrder(nodes) {\n  const need = new Map(nodes.map((n) => [n[0], n[1].slice()]));\n  const done = [], ready = new Set();\n  while (done.length < nodes.length) {\n    const now = [...need.keys()].filter((k) => need.get(k).every((d) => ready.has(d))).sort();\n    if (!now.length) return [];\n    now.forEach((k) => { ready.add(k); done.push(k); need.delete(k); });\n  }\n  return done;\n}",
  tests: [['readyOrder([["app",["db"]],["db",[]]])', '["db","app"]'],
    ['readyOrder([["a",[]],["b",[]]])', '["a","b"]'],
    ['readyOrder([["a",["b"]],["b",["a"]]])', '[]'],
    ['readyOrder([])', '[]']],
  edge: [['readyOrder([["x",[]]])', '["x"]'], ['readyOrder([["c",["b"]],["b",["a"]],["a",[]]])', '["a","b","c"]']],
  ex: "인프라 도구가 자원을 만드는 순서를 정하는 계산입니다. 네트워크가 있어야 서브넷을 만들고, 서브넷이 있어야 인스턴스를 만듭니다.\n<b>같은 층은 동시에</b> 만들 수 있다는 것이 이 방식의 이점입니다. 의존이 없는 것들을 한꺼번에 꺼내므로, 순서를 지키면서도 병렬로 처리할 수 있습니다.\n순환을 빈 배열로 알리는 것이 정직한 처리입니다. A 가 B 를, B 가 A 를 기다리면 <b>영원히 진행되지 않으므로</b>, 조용히 일부만 만들고 끝내는 것보다 못 한다고 말하는 편이 낫습니다.\n실제 도구는 여기에 한 겹을 더합니다 — 의존을 <b>사람이 적지 않아도</b> 참조 관계에서 알아냅니다. 손으로 적은 의존은 늘 낡으므로, 코드에서 뽑아내는 것이 유지되는 유일한 방법입니다." },

/* ───────────── 관측과 경보 ───────────── */
{ track: "cloud", k: "얼마나 자주 울릴까 · alarmFires", cat: "ops",
  q: "지표 값 목록과 임계값, 연속 횟수를 받아 <b>경보가 울린 횟수</b>를 돌려주세요. 임계값을 <b>초과</b>하는 값이 연속으로 그 횟수만큼 나오면 한 번 울리고, 다시 세기 시작합니다.",
  src: "function alarmFires(values, limit, streak) {\n  // TODO: 연속 초과를 세다 횟수에 닿으면 울리고 초기화하세요\n  return 0;\n}",
  sol: "function alarmFires(values, limit, streak) {\n  if (!(streak > 0)) return 0;\n  let run = 0, fired = 0;\n  values.forEach((v) => {\n    run = v > limit ? run + 1 : 0;\n    if (run === streak) { fired++; run = 0; }\n  });\n  return fired;\n}",
  tests: [['alarmFires([5,5,5], 1, 3)', '1'],
    ['alarmFires([5,0,5,5,5], 1, 3)', '1'],
    ['alarmFires([5,5,5,5,5,5], 1, 3)', '2'],
    ['alarmFires([0,0], 1, 3)', '0']],
  edge: [['alarmFires([5], 1, 1)', '1'], ['alarmFires([5,5], 1, 0)', '0']],
  ex: "경보를 <b>연속 횟수</b>로 판정하는 이유는 한 번 튄 값으로 사람을 깨우지 않기 위해서입니다. 지표는 늘 조금씩 흔들립니다.\n횟수를 크게 잡으면 안정적이지만 <b>알아채는 것이 늦어집니다.</b> 주기가 1분이고 3회 연속이면 최소 3분이 지나야 우는데, 몇 초 안에 대응해야 하는 것에는 맞지 않습니다.\n울린 뒤 다시 세기 시작하는 것이 이 구현의 선택입니다. 실제 경보는 대개 <b>상태를 유지</b>해서 정상으로 돌아올 때까지 한 번만 울리는데, 그러면 계속 나쁜 상태에서 조용해져 잊히기도 합니다.\n어느 쪽이든 <b>경보 피로</b>가 진짜 적입니다. 자주 울리고 대개 별일 아니면 사람은 곧 무시하게 되어, 정말 중요한 경보까지 함께 묻힙니다." },

{ track: "cloud", k: "무엇을 표본으로 남길까 · sampleKeep", cat: "perf",
  q: "요청 목록 <code>[아이디, 오류여부, 밀리초]</code> 와 느림 기준을 받아, <b>오류이거나 느린 것</b>의 아이디를 원래 순서대로 돌려주세요.",
  src: "function sampleKeep(reqs, slowMs) {\n  // TODO: 오류이거나 기준 이상인 것을 고르세요\n  return [];\n}",
  sol: "function sampleKeep(reqs, slowMs) {\n  return reqs.filter((r) => r[1] || r[2] >= slowMs).map((r) => r[0]);\n}",
  tests: [['sampleKeep([["a",false,10],["b",true,10]], 100)', '["b"]'],
    ['sampleKeep([["a",false,500]], 100)', '["a"]'],
    ['sampleKeep([["a",false,10]], 100)', '[]'],
    ['sampleKeep([], 100)', '[]']],
  edge: [['sampleKeep([["a",false,100]], 100)', '["a"]'], ['sampleKeep([["a",true,0],["b",true,0]], 1)', '["a","b"]']],
  ex: "추적을 전부 남기면 <b>저장비가 서비스 비용을 넘습니다.</b> 그래서 표본을 뽑는데, 무작위로 뽑으면 정작 보고 싶은 것이 빠집니다.\n<b>흥미로운 것을 남기는</b> 방식이 답입니다. 오류와 느린 요청은 전부 남기고, 평범한 것은 일부만 남깁니다. 문제를 조사할 때 필요한 것은 대개 앞의 둘입니다.\n주의할 점은 이 방식이 <b>통계를 왜곡한다</b>는 것입니다. 남은 표본으로 평균 응답 시간을 계산하면 실제보다 훨씬 나쁘게 나오므로, 지표는 표본이 아니라 <b>전수 집계</b>에서 얻어야 합니다.\n결정을 <b>추적이 끝난 뒤에</b> 하는 것이 좋습니다. 시작할 때는 느릴지 알 수 없어서, 앞에서 판단하면 결국 무작위와 다를 바 없어집니다." },

{ track: "cloud", k: "쓴 만큼 계산한다 · usageBill", cat: "impl",
  q: "구간별 요금 <code>[상한, 단가]</code> 목록과 사용량을 받아 <b>구간마다 다른 단가</b>로 계산한 요금을 소수 둘째 자리 반올림해 돌려주세요. 상한을 넘는 분량은 마지막 단가를 씁니다.",
  src: "function usageBill(tiers, used) {\n  // TODO: 구간별로 잘라 각각의 단가를 곱하세요\n  return 0;\n}",
  sol: "function usageBill(tiers, used) {\n  let left = used, prev = 0, sum = 0;\n  tiers.forEach((tr) => {\n    const span = Math.min(Math.max(tr[0] - prev, 0), left);\n    sum += span * tr[1];\n    left -= span; prev = tr[0];\n  });\n  if (left > 0 && tiers.length) sum += left * tiers[tiers.length - 1][1];\n  return Math.round(sum * 100) / 100;\n}",
  tests: [['usageBill([[10,1],[20,0.5]], 15)', '12.5'],
    ['usageBill([[10,1]], 5)', '5'],
    ['usageBill([[10,1],[20,0.5]], 30)', '20'],
    ['usageBill([[10,1]], 0)', '0']],
  edge: [['usageBill([], 5)', '0'], ['usageBill([[10,1],[20,0.5]], 10)', '10']],
  ex: "클라우드 요금 대부분이 이 모양입니다. 처음 얼마까지는 비싸고 <b>많이 쓸수록 단가가 내려갑니다.</b>\n흔한 오해가 '구간을 넘으면 전부 싼 단가' 라는 것입니다. 실제로는 <b>넘은 분량만</b> 싼 단가라, 소득세 구간과 같은 방식입니다. 이것을 잘못 알면 예측이 크게 어긋납니다.\n무료 제공량도 같은 구조의 첫 구간입니다. 단가가 0인 구간이 앞에 하나 있는 것뿐이라, 계산이 따로 필요하지 않습니다.\n요금 예측에서 진짜 어려운 것은 단가가 아니라 <b>사용량 추정</b>입니다. 여기에 트래픽 증가와 데이터 누적을 곱해야 하므로, 구간 계산이 정확해도 자릿수가 틀릴 수 있습니다." },

{ track: "cloud", k: "잊고 켜 둔 것 · orphanFind", cat: "ops",
  q: "<code>[이름, 종류, 붙은대상]</code> 목록에서 <b>붙은 대상이 빈 문자열인</b> 것의 이름을 정렬해 돌려주세요.",
  src: "function orphanFind(resources) {\n  // TODO: 붙은 곳이 없는 것을 고르세요\n  return [];\n}",
  sol: "function orphanFind(resources) {\n  return resources.filter((r) => !r[2]).map((r) => r[0]).sort();\n}",
  tests: [['orphanFind([["v1","volume",""],["v2","volume","i-1"]])', '["v1"]'],
    ['orphanFind([["a","ip","i-1"]])', '[]'],
    ['orphanFind([["b","ip",""],["a","volume",""]])', '["a","b"]'],
    ['orphanFind([])', '[]']],
  edge: [['orphanFind([["z","snap",""]])', '["z"]'], ['orphanFind([["a","ip","x"],["b","ip","y"]])', '[]']],
  ex: "요금이 예상을 넘는 흔한 이유가 <b>아무도 안 쓰는데 살아 있는 것들</b>입니다. 인스턴스를 지웠는데 붙어 있던 디스크는 남고, 고정 IP 는 붙지 않은 동안에 오히려 요금이 붙습니다.\n이런 것들은 <b>목록에서 눈에 띄지 않습니다.</b> 인스턴스 목록에는 없고 디스크 목록에만 있으니, 따로 찾지 않으면 몇 달씩 조용히 요금을 냅니다.\n스냅샷은 더 어렵습니다. 지우면 안 되는 것과 잊힌 것을 구분하려면 <b>이름과 태그</b>에 의존해야 하는데, 그것이 없으면 아무도 지울 결정을 못 내립니다.\n그래서 만들 때 태그를 강제하는 것이 사실상 유일한 해법입니다. 나중에 붙이려 하면 이미 수천 개가 쌓여 있고, <b>주인을 모르는 자원</b>은 지울 수도 남길 수도 없게 됩니다." },

{ track: "cloud", k: "여러 지표를 한 점수로 · healthScore", cat: "ops",
  q: "<code>[값, 가중치]</code> 목록을 받아 <b>가중 평균</b>을 소수 첫째 자리 반올림해 돌려주세요. 가중치 합이 0 이하면 <code>-1</code> 입니다.",
  src: "function healthScore(items) {\n  // TODO: 가중치를 곱해 더한 뒤 합으로 나누세요\n  return 0;\n}",
  sol: "function healthScore(items) {\n  let sum = 0, wsum = 0;\n  items.forEach((it) => { sum += it[0] * it[1]; wsum += it[1]; });\n  if (!(wsum > 0)) return -1;\n  return Math.round((sum / wsum) * 10) / 10;\n}",
  tests: [['healthScore([[100,1],[0,1]])', '50'],
    ['healthScore([[100,3],[0,1]])', '75'],
    ['healthScore([[80,1]])', '80'],
    ['healthScore([])', '-1']],
  edge: [['healthScore([[50,0]])', '-1'], ['healthScore([[90,2],[60,1]])', '80']],
  ex: "대시보드에 지표가 스무 개 있으면 아무도 안 봅니다. 그래서 <b>하나의 점수</b>로 묶는데, 그 순간 정보를 잃는다는 것을 알고 써야 합니다.\n가중치가 곧 <b>무엇이 중요한가에 대한 선언</b>입니다. 응답 시간과 오류율의 무게를 정하는 일은 기술 결정이 아니라 사업 결정이라, 팀이 합의해 적어 두어야 합니다.\n가장 큰 위험은 <b>평균이 문제를 숨기는 것</b>입니다. 한 지표가 완전히 망가져도 나머지가 좋으면 점수는 그럭저럭 나오므로, 요약 점수와 함께 <b>가장 나쁜 지표</b>를 늘 같이 보여 줍니다.\n가중치 합이 0인 경우를 <code>-1</code> 로 구분한 것도 같은 정신입니다. 0으로 나눠 <code>NaN</code> 을 내보내면 화면에 이상한 값이 뜨는 대신, 설정이 잘못됐다는 사실이 분명히 드러나야 합니다." },

];
