/* 함수형 디버깅 12 — 순수해 보이지만 새는 코드를 고친다.
   전부 결정적이고 순수 JS 다. 검증:  node ver_dbgjs.cjs ./dbg_fp.cjs */
module.exports = [

{ track:"fp", cat:"debug", k:"pipe 인데 순서가 거꾸로다",
  q:"함수들을 <b>왼쪽에서 오른쪽으로</b> 이어 붙이는 <code>pipeAll</code> 입니다. <code>pipeAll([f, g])(x)</code> 는 <code>g(f(x))</code> 여야 합니다. 지금은 변환 순서가 뒤집혀 결과가 엉뚱합니다.",
  src:"function pipeAll(fns) {\n  return x => fns.reduceRight((v, f) => f(v), x);\n}",
  sol:"function pipeAll(fns) {\n  return x => fns.reduce((v, f) => f(v), x);\n}",
  tests:[["pipeAll([n => n + 1, n => n * 2])(3)","8"],
         ["pipeAll([n => n * 2, n => n + 1])(3)","7"],
         ["pipeAll([])(5)","5"],
         ["pipeAll([s => s + 'a', s => s + 'b'])('x')","'xab'"]],
  edge:[["pipeAll([n => n - 1])(1)","0"],
        ["pipeAll([n => [n], a => a.concat(2)])(1)","[1,2]"]],
  ex:"원인: <code>reduceRight</code> 는 <b>오른쪽부터</b> 적용하므로 그건 <code>compose</code> 입니다. <code>pipe</code> 와 <code>compose</code> 는 방향만 다른 쌍이라 함수가 하나거나 두 함수가 교환 가능하면(둘 다 <code>+1</code> 같은) 결과가 같아, <b>순서가 중요한 조합</b>에서만 드러납니다.\n해결: <code>reduce</code> 로 바꿉니다. 초깃값이 <code>x</code> 이고 누적값에 함수를 차례로 먹이는 꼴이 <code>pipe</code> 입니다.\n재발 방지: 두 이름을 코드베이스에서 <b>하나만</b> 쓰는 팀이 많습니다. 섞어 쓰면 읽는 사람이 매번 방향을 다시 생각해야 하기 때문입니다. 테스트는 반드시 <b>교환 불가능한</b> 함수 쌍(<code>+1</code> 과 <code>×2</code>)으로 짜세요 — 대칭인 예제는 방향 버그를 통과시킵니다." },

{ track:"fp", cat:"debug", k:"메모이즈가 첫 인자만 본다",
  q:"인자로 캐시하는 <code>memo</code> 입니다. 인자가 여러 개일 때도 <b>모든 인자</b>가 같아야 캐시 적중입니다. 지금은 두 번째 인자를 바꿔도 <b>옛 결과</b>가 나옵니다.",
  src:"function memo(fn) {\n  const seen = new Map();\n  return (...args) => {\n    const key = args[0];\n    if (!seen.has(key)) seen.set(key, fn(...args));\n    return seen.get(key);\n  };\n}",
  sol:"function memo(fn) {\n  const seen = new Map();\n  return (...args) => {\n    const key = JSON.stringify(args);\n    if (!seen.has(key)) seen.set(key, fn(...args));\n    return seen.get(key);\n  };\n}",
  tests:[["(() => { const f = memo((a, b) => a + b); return [f(1, 2), f(1, 5)]; })()","[3,6]"],
         ["(() => { const f = memo(a => a * 2); return [f(3), f(3), f(4)]; })()","[6,6,8]"],
         ["(() => { let n = 0; const f = memo((a, b) => { n += 1; return a * b; }); f(2, 3); f(2, 3); return n; })()","1"],
         ["(() => { const f = memo((a, b) => `${a}-${b}`); return f('x', 'y'); })()","'x-y'"]],
  edge:[["(() => { const f = memo(() => 7); return [f(), f()]; })()","[7,7]"],
        ["(() => { const f = memo(a => a); return [f(0), f(1)]; })()","[0,1]"]],
  ex:"원인: 캐시 키가 <b>첫 인자뿐</b>이라 나머지 인자가 무시됩니다. 인자가 하나인 함수로만 테스트하면 완벽하게 동작해서, 여러 인자를 받는 함수에 붙이는 순간 <b>조용히 틀린 값</b>을 돌려줍니다 — 오류가 아니라 옛 답이라 더 찾기 어렵습니다.\n해결: 인자 전체로 키를 만듭니다. <code>JSON.stringify(args)</code> 가 간단한 방법이고, 인자가 원시값뿐이면 구분자로 이어 붙여도 됩니다.\n재발 방지: 메모이즈는 <b>순수 함수에만</b> 붙일 수 있고, 키가 인자 전체를 <b>정확히</b> 대표해야 합니다. 객체 인자는 <code>stringify</code> 가 키 순서에 따라 달라지고, 함수·<code>undefined</code> 는 사라집니다. 캐시는 메모리 누수의 흔한 원인이기도 하므로 상한이나 <code>WeakMap</code> 을 함께 생각하세요." },

{ track:"fp", cat:"debug", k:"once 가 두 번째부터 undefined 를 준다",
  q:"함수를 <b>한 번만 실행</b>하고 그 결과를 계속 돌려주는 <code>once</code> 입니다. 초기화 함수에 붙였더니 <b>두 번째 호출부터 <code>undefined</code></b> 가 나옵니다.",
  src:"function once(fn) {\n  let done = false;\n  return (...args) => {\n    if (done) return;\n    done = true;\n    return fn(...args);\n  };\n}",
  sol:"function once(fn) {\n  let done = false, value;\n  return (...args) => {\n    if (!done) { done = true; value = fn(...args); }\n    return value;\n  };\n}",
  tests:[["(() => { const f = once(() => 42); return [f(), f()]; })()","[42,42]"],
         ["(() => { let n = 0; const f = once(() => { n += 1; return n; }); f(); f(); return n; })()","1"],
         ["(() => { const f = once(a => a * 2); return [f(3), f(9)]; })()","[6,6]"],
         ["(() => { const f = once(() => null); return [f(), f()]; })()","[null,null]"]],
  edge:[["(() => { const f = once(() => 0); return [f(), f()]; })()","[0,0]"],
        ["(() => { const f = once(() => undefined); return [f(), f()]; })()","[undefined,undefined]"]],
  ex:"원인: '한 번만 실행' 은 지켰지만 <b>결과를 보관하지 않았습니다</b>. 두 번째부터는 아무것도 돌려주지 않아, 초기화 결과를 받아 쓰던 코드가 <code>undefined</code> 를 만납니다. 첫 호출만 확인하는 테스트로는 절대 안 잡힙니다.\n해결: 첫 결과를 변수에 담아 두고 이후에는 그것을 돌려줍니다. 계약이 '<b>한 번만 실행하고 같은 값을 준다</b>' 라는 점을 테스트 이름에도 적어 두세요.\n재발 방지: <code>once</code>·싱글턴·지연 초기화는 모두 '실행 횟수' 와 '반환값' 두 가지를 약속합니다. 하나만 테스트하면 다른 하나가 조용히 깨집니다. 그리고 첫 호출이 <b>예외를 던졌을 때</b> 다시 시도할지 그대로 실패로 굳힐지도 정해 두어야 합니다 — 초기화 실패가 영구 실패가 되는 사고가 여기서 나옵니다." },

{ track:"fp", cat:"debug", k:"zip 이 짧은 쪽을 넘어간다",
  q:"두 배열을 함수로 짝지어 합치는 <code>zipWith</code> 입니다. 길이가 다르면 <b>짧은 쪽에 맞춰</b> 끝내야 합니다. 지금은 뒤쪽에 <code>NaN</code> 이 섞여 나옵니다.",
  src:"function zipWith(f, a, b) {\n  return a.map((x, i) => f(x, b[i]));\n}",
  sol:"function zipWith(f, a, b) {\n  const n = Math.min(a.length, b.length);\n  return Array.from({ length: n }, (_, i) => f(a[i], b[i]));\n}",
  tests:[["zipWith((x, y) => x + y, [1,2,3], [10,20,30])","[11,22,33]"],
         ["zipWith((x, y) => x + y, [1,2,3], [10])","[11]"],
         ["zipWith((x, y) => x + y, [1], [10,20,30])","[11]"],
         ["zipWith((x, y) => [x, y], [1,2], ['a','b'])","[[1,'a'],[2,'b']]"]],
  edge:[["zipWith((x, y) => x + y, [], [1,2])","[]"],
        ["zipWith((x, y) => x * y, [2,3], [4])","[8]"]],
  ex:"원인: <code>a.map</code> 은 <b>첫 배열의 길이</b>만큼 돕니다. 두 번째 배열이 짧으면 <code>b[i]</code> 가 <code>undefined</code> 가 되어 <code>NaN</code> 이나 <code>'1undefined'</code> 같은 값이 조용히 섞입니다. 길이가 같은 예제로만 테스트하면 통과합니다.\n해결: 두 길이의 <b>최솟값</b>만큼 돕니다. 반대 정책(긴 쪽에 맞추고 빈 자리는 기본값)을 쓰려면 그 기본값을 인자로 받아 <b>계약에 드러내세요</b>.\n재발 방지: 두 자료를 나란히 도는 코드는 언제나 '<b>길이가 다르면 어떻게 하는가</b>' 를 먼저 정해야 합니다. 조용히 <code>undefined</code> 를 흘리는 것은 선택지가 아닙니다 — 짧은 쪽에 맞추거나, 기본값을 채우거나, 오류로 거절하거나 셋 중 하나입니다." },

{ track:"fp", cat:"debug", k:"groupBy 가 프로토타입 키에 걸린다",
  q:"키 함수로 묶는 <code>groupBy</code> 입니다. 사용자 입력에서 나온 문자열이 키가 될 수 있습니다. 지금은 키가 <code>'constructor'</code> 인 자료가 들어오면 <b>이상한 오류</b>가 납니다.",
  src:"function groupBy(xs, keyOf) {\n  const out = {};\n  for (const x of xs) {\n    if (!out[keyOf(x)]) out[keyOf(x)] = [];\n    out[keyOf(x)].push(x);\n  }\n  return out;\n}",
  sol:"function groupBy(xs, keyOf) {\n  const out = Object.create(null);\n  for (const x of xs) {\n    const k = keyOf(x);\n    if (!Object.prototype.hasOwnProperty.call(out, k)) out[k] = [];\n    out[k].push(x);\n  }\n  return out;\n}",
  tests:[["groupBy(['a','bb','c'], s => s.length)","{1:['a','c'], 2:['bb']}"],
         ["groupBy(['constructor'], s => s)","{constructor:['constructor']}"],
         ["groupBy([], s => s)","{}"],
         ["groupBy(['toString','x'], s => s)","{toString:['toString'], x:['x']}"]],
  edge:[["groupBy([1,2,3], n => n % 2)","{0:[2], 1:[1,3]}"],
        ["Object.keys(groupBy(['__proto__','a'], s => s))","['__proto__','a']"]],
  ex:"원인: 보통 객체는 <code>Object.prototype</code> 을 물려받습니다. <code>out['constructor']</code> 는 아직 아무것도 안 넣었는데도 <b>함수를 돌려주므로</b> <code>if (!out[k])</code> 가 거짓이 되어 배열을 만들지 않고 그 함수에 <code>push</code> 를 시도합니다. <code>'__proto__'</code> 는 더 나빠서 대입이 <b>프로토타입 자체</b>를 건드립니다.\n해결: <code>Object.create(null)</code> 로 <b>물려받은 것이 없는</b> 객체를 만들고, 존재 확인은 <code>hasOwnProperty</code> 로 합니다. <code>Map</code> 을 쓰면 이 문제가 아예 없습니다.\n재발 방지: <b>바깥에서 온 문자열이 객체 키가 되는</b> 모든 자리가 이 함정입니다 — 집계·캐시·설정 병합·질의 파라미터. 프로토타입 오염은 여기서 시작해 애플리케이션 전역의 동작을 바꾸는 취약점이 됩니다. 사전이 필요하면 <code>Map</code> 을 기본으로 삼으세요." },

{ track:"fp", cat:"debug", k:"takeWhile 이 필터로 구현됐다",
  q:"조건이 <b>처음 거짓이 되는 순간 멈추는</b> <code>takeWhile</code> 입니다. 지금은 뒤쪽에 있는 조건 만족 원소까지 함께 나와, 정렬된 자료의 앞부분만 자르려던 의도가 깨집니다.",
  src:"function takeWhile(xs, ok) {\n  return xs.filter(ok);\n}",
  sol:"function takeWhile(xs, ok) {\n  const out = [];\n  for (const x of xs) {\n    if (!ok(x)) break;\n    out.push(x);\n  }\n  return out;\n}",
  tests:[["takeWhile([1,2,9,3], n => n < 5)","[1,2]"],
         ["takeWhile([1,2,3], n => n < 5)","[1,2,3]"],
         ["takeWhile([9,1,2], n => n < 5)","[]"],
         ["takeWhile([], n => true)","[]"]],
  edge:[["takeWhile([0,1,2], n => n === 0)","[0]"],
        ["takeWhile([5,5,5], n => n < 5)","[]"]],
  ex:"원인: <code>filter</code> 는 <b>전부 훑어</b> 조건을 만족하는 것을 모읍니다. <code>takeWhile</code> 은 <b>처음 거짓에서 멈춥니다</b>. 조건을 만족하는 원소가 앞에만 몰려 있는 자료로 테스트하면 두 결과가 같아서 그냥 지나갑니다.\n해결: 반복문에서 <code>break</code> 로 멈춥니다. 멈춘다는 것은 <b>뒤를 보지 않는다</b>는 뜻이라, 무한 수열이나 비싼 계산에서는 성능 차이도 큽니다.\n재발 방지: <code>filter</code>·<code>takeWhile</code>·<code>find</code>·<code>some</code> 는 '언제 멈추는가' 가 다릅니다. 테스트는 반드시 <b>조건이 중간에 끊겼다 다시 참이 되는</b> 자료로 짜세요 — 이 한 줄이 네 함수를 구분해 줍니다." },

{ track:"fp", cat:"debug", k:"깊이 지정 평탄화가 한 겹 더 판다",
  q:"<code>depth</code> 겹까지만 펴는 <code>flatten</code> 입니다. <code>depth</code> 가 1 이면 <b>한 겹</b>만 펴야 하는데, 안쪽까지 전부 펴져 구조가 사라집니다.",
  src:"function flatten(xs, depth) {\n  if (depth < 0) return xs;\n  return xs.reduce((out, x) => out.concat(Array.isArray(x) ? flatten(x, depth) : x), []);\n}",
  sol:"function flatten(xs, depth) {\n  if (depth <= 0) return xs.slice();\n  return xs.reduce((out, x) => out.concat(Array.isArray(x) ? flatten(x, depth - 1) : x), []);\n}",
  tests:[["flatten([1,[2,[3,[4]]]], 1)","[1,2,[3,[4]]]"],
         ["flatten([1,[2,[3,[4]]]], 2)","[1,2,3,[4]]"],
         ["flatten([1,[2]], 0)","[1,[2]]"],
         ["flatten([1,2], 5)","[1,2]"]],
  edge:[["flatten([], 3)","[]"],
        ["flatten([[[1]]], 3)","[1]"]],
  ex:"원인: 재귀에 <b><code>depth - 1</code> 을 안 넘겼습니다</b>. 깊이가 줄지 않으니 바닥까지 내려가고, <code>depth &lt; 0</code> 이라는 종료 조건은 영영 참이 되지 않습니다. 두 겹짜리 자료로만 테스트하면 1 과 무한이 같은 답을 내서 통과합니다.\n해결: 재귀 호출에 줄어든 깊이를 넘기고, 종료 조건을 <code>depth &lt;= 0</code> 으로 맞춥니다. 이때 <code>slice()</code> 로 복사해 돌려주면 반환값이 입력과 <b>같은 객체를 공유하지 않습니다</b>.\n재발 방지: 재귀에서 '줄어드는 값' 을 안 넘기는 것은 무한 재귀의 대표 원인입니다. 종료 조건과 <b>줄어드는 인자</b>는 언제나 짝으로 확인하세요. 그리고 깊이 인자를 받는 함수는 <b>0 과 1</b> 을 반드시 테스트에 넣어야 합니다." },

{ track:"fp", cat:"debug", k:"chunk 가 0 에서 멈추지 않는다",
  q:"배열을 <code>n</code> 개씩 자르는 <code>chunk</code> 입니다. <code>n</code> 이 1 보다 작으면 <b>빈 배열</b>을 돌려줘야 합니다. 지금은 설정값이 0 으로 들어오면 화면이 그대로 멈춥니다.",
  src:"function chunk(xs, n) {\n  const out = [];\n  for (let i = 0; i < xs.length; i += n) out.push(xs.slice(i, i + n));\n  return out;\n}",
  sol:"function chunk(xs, n) {\n  if (!(n >= 1)) return [];\n  const out = [];\n  for (let i = 0; i < xs.length; i += n) out.push(xs.slice(i, i + n));\n  return out;\n}",
  tests:[["chunk([1,2,3,4,5], 2)","[[1,2],[3,4],[5]]"],
         ["chunk([1,2,3], 0)","[]"],
         ["chunk([1,2,3], 5)","[[1,2,3]]"],
         ["chunk([], 2)","[]"]],
  edge:[["chunk([1,2,3], -1)","[]"],
        ["chunk([1], 1)","[[1]]"]],
  ex:"원인: <code>i += 0</code> 은 <b>전진하지 않습니다</b>. 반복문이 끝나지 않고 배열에 빈 조각을 무한히 밀어 넣어, 오류가 아니라 <b>메모리를 다 쓰고 탭이 죽는</b> 방식으로 실패합니다. 브라우저에서는 이 실패가 오류 로그조차 남기지 않습니다.\n해결: 전진 폭이 1 이상인지 <b>먼저</b> 확인합니다. <code>!(n &gt;= 1)</code> 로 적으면 <code>NaN</code> 과 <code>undefined</code> 도 함께 걸러집니다 — <code>n &lt; 1</code> 은 <code>NaN</code> 을 통과시킵니다.\n재발 방지: 전진 폭이 <b>변수</b>인 반복문에는 언제나 가드가 필요합니다. 같은 함정이 청킹의 겹침(<code>overlap &gt;= size</code>), 페이지 크기 0, 재시도 간격 0 에도 있습니다. 설정값에서 온 숫자는 <b>범위를 검증한 뒤에</b> 반복문에 넣으세요." },

{ track:"fp", cat:"debug", k:"동결이 한 겹만 걸린다",
  q:"객체를 <b>중첩까지 전부</b> 얼리는 <code>deepFreeze</code> 입니다. 지금은 안쪽 객체가 그대로 수정되어, 공유 설정이 요청 사이에 오염됩니다.",
  src:"function deepFreeze(obj) {\n  return Object.freeze(obj);\n}",
  sol:"function deepFreeze(obj) {\n  if (obj === null || typeof obj !== 'object') return obj;\n  for (const k of Object.keys(obj)) deepFreeze(obj[k]);\n  return Object.freeze(obj);\n}",
  tests:[["(() => { const o = deepFreeze({a:{b:1}}); try { o.a.b = 2; } catch (e) {} return o.a.b; })()","1"],
         ["(() => { const o = deepFreeze({a:1}); try { o.a = 2; } catch (e) {} return o.a; })()","1"],
         ["Object.isFrozen(deepFreeze({a:{b:{c:1}}}).a.b)","true"],
         ["deepFreeze(5)","5"]],
  edge:[["Object.isFrozen(deepFreeze({}))","true"],
        ["(() => { const o = deepFreeze({a:[1,2]}); try { o.a.push(3); } catch (e) {} return o.a.length; })()","2"]],
  ex:"원인: <code>Object.freeze</code> 는 <b>한 겹만</b> 얼립니다. 바깥 객체의 키는 못 바꾸지만 <code>o.a.b = 2</code> 는 그대로 통합니다. 얕은 복사와 똑같은 함정이고, 그래서 '<b>불변이라고 믿었는데 바뀐</b>' 버그가 생깁니다.\n해결: 값이 객체이면 <b>먼저 안쪽을 얼리고</b> 자신을 업니다. 원시값은 그대로 돌려줍니다. 순환 참조가 있으면 무한 재귀가 되므로 실무에서는 방문 집합을 함께 씁니다.\n재발 방지: 비엄격 모드에서 언 객체에 대입하면 <b>조용히 무시</b>되고 오류가 나지 않습니다(모듈과 엄격 모드에서는 예외). 그래서 테스트는 '오류가 나는가' 가 아니라 '<b>값이 그대로인가</b>' 로 확인해야 합니다. 애초에 공유 상태를 만들지 않는 쪽이 더 나은 답일 때가 많습니다." },

{ track:"fp", cat:"debug", k:"partition 이 원본을 함께 바꾼다",
  q:"조건으로 두 묶음으로 가르는 <code>partition</code> 입니다. <b>원본 배열을 바꾸면 안 됩니다</b>. 지금은 한 번 호출하고 나면 원본이 비어 버려 두 번째 호출부터 결과가 이상합니다.",
  src:"function partition(xs, ok) {\n  const yes = [], no = [];\n  while (xs.length) {\n    const x = xs.shift();\n    (ok(x) ? yes : no).push(x);\n  }\n  return [yes, no];\n}",
  sol:"function partition(xs, ok) {\n  const yes = [], no = [];\n  for (const x of xs) (ok(x) ? yes : no).push(x);\n  return [yes, no];\n}",
  tests:[["partition([1,2,3,4], n => n % 2 === 0)","[[2,4],[1,3]]"],
         ["(() => { const a = [1,2,3]; partition(a, n => n > 1); return a; })()","[1,2,3]"],
         ["partition([], n => true)","[[],[]]"],
         ["partition([1,2], n => false)","[[],[1,2]]"]],
  edge:[["partition([5], n => n === 5)","[[5],[]]"],
        ["(() => { const a = [1,2]; const r1 = partition(a, n => n > 0); const r2 = partition(a, n => n > 0); return [r1[0].length, r2[0].length]; })()","[2,2]"]],
  ex:"원인: <code>shift</code> 는 <b>원본에서 원소를 꺼냅니다</b>. 결과는 맞게 나오지만 호출자의 배열이 비어, 같은 배열로 두 번째 작업을 하면 아무것도 없습니다. 반환값만 검사하는 테스트로는 절대 안 잡힙니다.\n해결: 읽기만 하는 <code>for...of</code> 로 돕니다. 굳이 꺼내야 한다면 <code>xs.slice()</code> 로 복사본을 만들어 그것을 소비하세요.\n재발 방지: 자바스크립트의 배열 메서드는 <b>바꾸는 것</b>(<code>sort</code>·<code>reverse</code>·<code>splice</code>·<code>push</code>·<code>shift</code>)과 <b>새로 만드는 것</b>(<code>map</code>·<code>filter</code>·<code>slice</code>·<code>concat</code>)으로 갈립니다. 순수 함수를 쓴다면 앞의 목록은 <b>복사한 뒤에만</b> 씁니다. 그리고 '원본이 그대로인가' 를 테스트로 못 박으세요 — 이 계약은 반환값에 드러나지 않습니다." },

{ track:"fp", cat:"debug", k:"커링이 인자 개수를 안 센다",
  q:"두 자리 함수를 커링하는 <code>curry2</code> 입니다. <code>f(1)(2)</code> 와 <code>f(1, 2)</code> 가 <b>모두</b> 동작해야 합니다. 지금은 두 인자를 한 번에 넘기면 함수가 그대로 나옵니다.",
  src:"function curried(fn) {\n  return a => b => fn(a, b);\n}",
  sol:"function curried(fn) {\n  return function step(...args) {\n    if (args.length >= 2) return fn(args[0], args[1]);\n    return b => fn(args[0], b);\n  };\n}",
  tests:[["curried((a, b) => a + b)(1)(2)","3"],
         ["curried((a, b) => a + b)(1, 2)","3"],
         ["curried((a, b) => a * b)(3)(4)","12"],
         ["curried((a, b) => `${a}${b}`)('x', 'y')","'xy'"]],
  edge:[["typeof curried((a, b) => a + b)(1)","'function'"],
        ["curried((a, b) => (a || 0) + (b || 0))(0, 0)","0"]],
  ex:"원인: 반환한 함수가 <b>인자를 하나만</b> 받습니다. <code>f(1, 2)</code> 로 부르면 두 번째 인자는 그냥 버려지고 '아직 덜 채워진 함수' 가 나옵니다. 오류가 아니라 <b>함수 객체</b>가 돌아오므로, 그 값을 문자열로 이어 붙이거나 비교하는 자리에서야 이상함이 드러납니다.\n해결: 받은 인자 개수를 세어 <b>충분하면 바로 호출</b>하고, 모자라면 나머지를 기다리는 함수를 돌려줍니다. 실무 라이브러리는 <code>fn.length</code> 로 목표 개수를 읽어 임의 자리 수를 지원합니다.\n재발 방지: 커링의 가치는 '<b>부분 적용</b>' 이지 문법이 아닙니다. 두 호출 방식이 같은 답을 내는지 반드시 테스트하고, 인자가 <code>0</code>·<code>undefined</code> 처럼 거짓 같은 값일 때도 '덜 받았다' 로 오해하지 않는지 확인하세요 — 개수는 <b>값이 아니라 <code>args.length</code></b> 로 세야 합니다." },

{ track:"fp", cat:"debug", k:"누산기 없는 재귀가 스택을 넘긴다",
  q:"1 부터 <code>n</code> 까지 더하는 재귀 함수입니다. 작은 값은 맞는데 <code>n</code> 이 커지면 <b>스택 넘침</b>으로 죽습니다. 재귀 형태는 유지하되 큰 <code>n</code> 도 버텨야 합니다.",
  src:"function sumTo(n) {\n  if (n <= 0) return 0;\n  return n + sumTo(n - 1);\n}",
  sol:"function sumTo(n) {\n  let acc = 0;\n  const step = k => { while (k > 0) { acc += k; k -= 1; } return acc; };\n  return step(n);\n}",
  tests:[["sumTo(0)","0"],
         ["sumTo(10)","55"],
         ["sumTo(100000)","5000050000"],
         ["sumTo(1)","1"]],
  edge:[["sumTo(-5)","0"],
        ["sumTo(3)","6"]],
  ex:"원인: <code>n + sumTo(n - 1)</code> 은 <b>꼬리 호출이 아닙니다</b> — 재귀에서 돌아온 뒤에 더해야 하므로 호출마다 스택 프레임이 남습니다. 10만 번이면 스택을 넘겨 <code>RangeError</code> 로 죽습니다. 작은 입력만 테스트하면 완벽해 보입니다.\n해결: 남은 일을 <b>누산기</b>로 옮기면 돌아와서 할 일이 없어집니다. 자바스크립트 엔진은 꼬리 호출 최적화를 대부분 지원하지 않으므로, 누산기 꼴을 <b>반복문으로</b> 펴는 것이 실전의 답입니다.\n재발 방지: 재귀 깊이가 <b>입력 크기에 비례</b>하면 언제든 터질 수 있습니다. 깊이가 <code>log n</code> 인 재귀(이진 탐색·병합 정렬)는 안전하고, 선형인 재귀(리스트 순회)는 반복문으로 펴세요. 테스트에는 <b>10만 단위 입력</b>을 하나 넣어 두면 이 한계가 배포 전에 드러납니다." },

];
