/* 넘파이 디버깅 12 — 모양은 맞는데 값이 틀린 코드를 고친다.
   검증:  node ver_dbgpy.cjs ./dbg_numpy.cjs */
module.exports = [

{ track:"numpy", cat:"debug", fn:"col_mean",
  k:"축을 반대로 잡았다",
  q:"2차원 배열에서 <b>열마다</b> 평균을 구해 1차원 배열로 돌려주는 함수입니다. 지금은 결과의 길이가 <b>행 개수</b>와 같아, 뒤에서 열 이름과 짝지을 때 어긋납니다.",
  pkgs:["numpy"],
  src:"import numpy as np\n\ndef col_mean(a):\n    return np.mean(a, axis=1)\n",
  sol:"import numpy as np\n\ndef col_mean(a):\n    return np.mean(a, axis=0)\n",
  tests:[["col_mean(np.array([[1.0, 2.0], [3.0, 4.0]])).tolist()","[2.0, 3.0]"],
         ["col_mean(np.array([[0.0, 10.0], [0.0, 20.0]])).tolist()","[0.0, 15.0]"],
         ["col_mean(np.array([[1.0, 2.0, 3.0]])).tolist()","[1.0, 2.0, 3.0]"],
         ["col_mean(np.array([[2.0], [4.0]])).tolist()","[3.0]"]],
  edge:[["col_mean(np.zeros((3, 4))).shape","(4,)"],
        ["col_mean(np.array([[5.0, 5.0], [5.0, 5.0]])).tolist()","[5.0, 5.0]"]],
  ex:"원인: <code>axis</code> 는 '<b>없어지는 축</b>' 을 가리킵니다. 열마다 평균을 내려면 <b>행 방향으로 접어야</b> 하므로 <code>axis=0</code> 입니다. <code>axis=1</code> 은 행마다 평균이라 결과 길이가 행 개수가 됩니다. 정사각 배열로 테스트하면 길이가 같아 <b>모양 검사로도 안 잡힙니다</b>.\n해결: <code>axis=0</code> 으로 바꿉니다. 헷갈릴 때는 '결과의 모양이 무엇이어야 하는가' 를 먼저 적어 보세요 — <code>(n, m)</code> 에서 <code>axis=0</code> 은 <code>(m,)</code>, <code>axis=1</code> 은 <code>(n,)</code> 입니다.\n재발 방지: 축을 다루는 코드는 <b>행과 열의 개수가 다른</b> 배열로 테스트해야 합니다. 정사각 예제는 축 실수를 통째로 숨깁니다. 그리고 결과의 <code>shape</code> 를 테스트에 직접 넣어 두면 값이 우연히 맞는 경우까지 걸러집니다." },

{ track:"numpy", cat:"debug", fn:"clip_scale",
  k:"뷰를 고쳐 원본이 함께 바뀐다",
  q:"배열의 앞 절반을 0 으로 만든 <b>새 배열</b>을 돌려줍니다. <b>원본은 그대로여야</b> 합니다. 지금은 이 함수를 부르고 나면 원본 자료가 망가집니다.",
  pkgs:["numpy"],
  src:"import numpy as np\n\ndef clip_scale(a):\n    b = a[:]\n    b[: len(b) // 2] = 0\n    return b\n",
  sol:"import numpy as np\n\ndef clip_scale(a):\n    b = a.copy()\n    b[: len(b) // 2] = 0\n    return b\n",
  tests:[["clip_scale(np.array([1, 2, 3, 4])).tolist()","[0, 0, 3, 4]"],
         ["(lambda a: (clip_scale(a), a.tolist()))(np.array([1, 2, 3, 4]))[1]","[1, 2, 3, 4]"],
         ["clip_scale(np.array([9])).tolist()","[9]"],
         ["(lambda a: (clip_scale(a), a.sum()))(np.array([5, 5]))[1]","10"]],
  edge:[["clip_scale(np.array([])).tolist()","[]"],
        ["clip_scale(np.array([1, 2, 3])).tolist()","[0, 2, 3]"]],
  ex:"원인: 넘파이의 슬라이싱은 <b>복사가 아니라 뷰</b> 입니다. 파이썬 리스트에서 <code>a[:]</code> 가 복사인 것과 정반대라, 리스트 습관을 그대로 옮기면 원본을 고치게 됩니다. 이 차이가 '메모리를 아끼려고' 만든 넘파이의 핵심 설계입니다.\n해결: <code>a.copy()</code> 로 명시적으로 복사합니다. 반대로 큰 배열을 다룰 때는 <b>복사를 피하려고</b> 일부러 뷰를 쓰기도 하므로, 어느 쪽인지 함수 계약에 적어야 합니다.\n재발 방지: 뷰인지 복사인지 헷갈리면 <code>b.base is a</code> 로 확인할 수 있습니다. 그리고 '<b>원본이 그대로인가</b>' 를 반환값 검사와 <b>따로</b> 테스트하세요 — 반환값만 보면 절대 안 잡힙니다. 팬시 인덱싱(<code>a[[0,2]]</code>)은 복사, 기본 슬라이싱은 뷰라는 점도 함께 기억하세요." },

{ track:"numpy", cat:"debug", fn:"safe_div",
  k:"0 으로 나눈 자리를 그대로 둔다",
  q:"두 배열을 나누되 <b>분모가 0 인 자리는 0</b> 으로 둡니다. 지금은 <code>inf</code> 와 <code>nan</code> 이 섞여 뒤쪽 집계가 통째로 망가집니다.",
  pkgs:["numpy"],
  src:"import numpy as np\n\ndef safe_div(a, b):\n    return a / b\n",
  sol:"import numpy as np\n\ndef safe_div(a, b):\n    out = np.zeros(np.broadcast(a, b).shape, dtype=float)\n    np.divide(a, b, out=out, where=(b != 0))\n    return out\n",
  tests:[["safe_div(np.array([4.0, 6.0]), np.array([2.0, 3.0])).tolist()","[2.0, 2.0]"],
         ["safe_div(np.array([1.0, 1.0]), np.array([0.0, 2.0])).tolist()","[0.0, 0.5]"],
         ["safe_div(np.array([0.0]), np.array([0.0])).tolist()","[0.0]"],
         ["bool(np.isfinite(safe_div(np.array([1.0, 2.0]), np.array([0.0, 0.0]))).all())","True"]],
  edge:[["safe_div(np.array([5.0]), np.array([1.0])).tolist()","[5.0]"],
        ["safe_div(np.array([-4.0]), np.array([0.0])).tolist()","[0.0]"]],
  ex:"원인: 넘파이는 0 으로 나눠도 <b>예외를 던지지 않습니다</b> — 경고만 내고 <code>inf</code> 나 <code>nan</code> 을 넣습니다. 경고는 보통 로그에 묻히고, <code>nan</code> 은 이후 <code>sum</code>·<code>mean</code>·비교를 전부 오염시킵니다.\n해결: <code>np.divide</code> 의 <code>where</code> 로 <b>나눌 자리만</b> 계산하고 나머지는 미리 채운 <code>out</code> 값을 그대로 둡니다. <code>where</code> 를 쓸 때 <code>out</code> 을 반드시 함께 주어야 계산하지 않은 자리가 쓰레기값이 되지 않습니다.\n재발 방지: <code>np.errstate</code> 로 경고를 오류로 승격시키면 개발 중에 이 자리를 <b>바로</b> 찾을 수 있습니다. 그리고 파이프라인 끝에서 <code>np.isfinite(x).all()</code> 을 확인하는 습관이 <code>nan</code> 이 멀리 퍼지기 전에 잡아 줍니다." },

{ track:"numpy", cat:"debug", fn:"row_norm",
  k:"브로드캐스트 모양이 어긋난다",
  q:"각 <b>행</b>을 그 행의 합으로 나눠 정규화합니다(합은 0 이 아니라고 가정). 지금은 값이 이상하거나 오류가 납니다.",
  pkgs:["numpy"],
  src:"import numpy as np\n\ndef row_norm(a):\n    return a / a.sum(axis=1)\n",
  sol:"import numpy as np\n\ndef row_norm(a):\n    return a / a.sum(axis=1, keepdims=True)\n",
  tests:[["row_norm(np.array([[1.0, 1.0], [1.0, 3.0]])).tolist()","[[0.5, 0.5], [0.25, 0.75]]"],
         ["row_norm(np.array([[2.0, 2.0, 4.0]])).tolist()","[[0.25, 0.25, 0.5]]"],
         ["row_norm(np.array([[1.0], [2.0]])).tolist()","[[1.0], [1.0]]"],
         ["row_norm(np.array([[3.0, 1.0], [1.0, 1.0]])).tolist()","[[0.75, 0.25], [0.5, 0.5]]"]],
  edge:[["row_norm(np.array([[1.0, 1.0, 2.0], [2.0, 1.0, 1.0]])).shape","(2, 3)"],
        ["row_norm(np.array([[5.0, 5.0]])).tolist()","[[0.5, 0.5]]"]],
  ex:"원인: <code>a.sum(axis=1)</code> 은 축이 <b>사라져</b> <code>(n,)</code> 모양이 됩니다. 이것을 <code>(n, m)</code> 과 나누면 브로드캐스트 규칙이 <b>마지막 축끼리</b> 맞추려 해서, 정사각 배열에서는 조용히 <b>열 방향으로</b> 나눠지고 아니면 오류가 납니다.\n해결: <code>keepdims=True</code> 로 축을 <code>(n, 1)</code> 로 남기면 의도대로 행마다 나눠집니다. <code>a.sum(axis=1)[:, None]</code> 도 같은 뜻입니다.\n재발 방지: 브로드캐스트는 <b>뒤쪽 축부터</b> 맞춥니다. 집계 후 다시 나누는 코드에서는 거의 언제나 <code>keepdims=True</code> 가 정답입니다. 그리고 정사각 배열은 이 실수를 오류 없이 숨기므로 <b>행과 열의 수가 다른</b> 배열로 테스트하세요." },

{ track:"numpy", cat:"debug", fn:"count_pos",
  k:"배열을 파이썬 참거짓으로 본다",
  q:"배열에서 <b>양수의 개수</b>를 세어 파이썬 정수로 돌려줍니다. 지금은 원소가 둘 이상이면 예외가 납니다.",
  pkgs:["numpy"],
  src:"import numpy as np\n\ndef count_pos(a):\n    n = 0\n    for x in a:\n        if a > 0:\n            n += 1\n    return n\n",
  sol:"import numpy as np\n\ndef count_pos(a):\n    return int(np.count_nonzero(a > 0))\n",
  tests:[["count_pos(np.array([1, -2, 3]))","2"],
         ["count_pos(np.array([-1, -2]))","0"],
         ["count_pos(np.array([0, 0, 1]))","1"],
         ["count_pos(np.array([5]))","1"]],
  edge:[["count_pos(np.array([]))","0"],
        ["count_pos(np.array([0]))","0"]],
  ex:"원인: <code>a &gt; 0</code> 은 <b>불리언 배열</b>이지 참거짓 하나가 아닙니다. <code>if</code> 에 넣으면 넘파이가 '<b>모호하다</b>' 며 <code>ValueError</code> 를 던집니다 — 전부 참인지 하나라도 참인지 알 수 없기 때문입니다. 원소가 하나면 예외 없이 통과해서 더 헷갈립니다.\n해결: 개수는 <code>np.count_nonzero(a &gt; 0)</code> 한 줄입니다. 반복문 자체가 필요 없고 훨씬 빠릅니다. 파이썬 <code>int</code> 로 감싸면 JSON 직렬화나 비교에서 넘파이 정수 타입 때문에 생기는 잔문제도 없습니다.\n재발 방지: '<b>배열을 조건문에 넣었다</b>' 면 대개 <b>벡터화</b>로 바꿀 자리입니다. 정말 하나의 참거짓이 필요하면 <code>.any()</code>·<code>.all()</code> 로 <b>무엇을 묻는지</b> 명시하세요. 그리고 넘파이 코드에 파이썬 <code>for</code> 가 보이면 성능도 함께 의심할 신호입니다." },

{ track:"numpy", cat:"debug", fn:"to_int",
  k:"정수 배열이 조용히 넘친다",
  q:"값들을 <b>2배</b>한 뒤 파이썬 리스트로 돌려줍니다. 큰 값이 들어오면 <b>음수</b>가 나옵니다.",
  pkgs:["numpy"],
  src:"import numpy as np\n\ndef to_int(xs):\n    a = np.array(xs, dtype=np.int8)\n    return (a * 2).tolist()\n",
  sol:"import numpy as np\n\ndef to_int(xs):\n    a = np.array(xs, dtype=np.int64)\n    return (a * 2).tolist()\n",
  tests:[["to_int([1, 2, 3])","[2, 4, 6]"],
         ["to_int([100])","[200]"],
         ["to_int([1000, 2000])","[2000, 4000]"],
         ["to_int([-100])","[-200]"]],
  edge:[["to_int([])","[]"],
        ["to_int([0])","[0]"]],
  ex:"원인: <code>int8</code> 은 −128~127 만 담습니다. 넘파이는 <b>넘쳐도 예외를 던지지 않고</b> 조용히 감아 버려 200 이 −56 이 됩니다. 작은 값으로만 테스트하면 완벽하게 동작하고, 실제 데이터가 들어오는 순간 음수가 튀어나옵니다.\n해결: 값의 범위에 맞는 <code>dtype</code> 을 고릅니다. 메모리를 아끼려고 좁은 타입을 쓸 때는 <b>최댓값이 얼마까지 가능한지</b>를 먼저 계산해야 합니다.\n재발 방지: <code>np.iinfo(np.int8).max</code> 로 한계를 확인할 수 있습니다. 그리고 이미지·오디오처럼 좁은 타입이 흔한 자료에서는 <b>계산 전에</b> 넓은 타입으로 올리세요 — <code>uint8</code> 픽셀을 더하다가 감기는 것이 같은 사고입니다." },

{ track:"numpy", cat:"debug", fn:"where_pick",
  k:"불리언 인덱싱 대신 인덱스를 쓴다",
  q:"조건을 만족하는 <b>값들</b>을 골라 리스트로 돌려줍니다. 지금은 값이 아니라 <b>자리 번호</b>가 나옵니다.",
  pkgs:["numpy"],
  src:"import numpy as np\n\ndef where_pick(a, t):\n    return np.where(a > t)[0].tolist()\n",
  sol:"import numpy as np\n\ndef where_pick(a, t):\n    return a[a > t].tolist()\n",
  tests:[["where_pick(np.array([1, 5, 3, 9]), 2)","[5, 3, 9]"],
         ["where_pick(np.array([10, 20]), 15)","[20]"],
         ["where_pick(np.array([1, 2, 3]), 5)","[]"],
         ["where_pick(np.array([7]), 0)","[7]"]],
  edge:[["where_pick(np.array([]), 0)","[]"],
        ["where_pick(np.array([0, 1, 2]), -1)","[0, 1, 2]"]],
  ex:"원인: 인자가 하나뿐인 <code>np.where(cond)</code> 는 <b>조건이 참인 자리</b>를 돌려줍니다. 값이 아니라 인덱스라, 배열이 <code>[0, 1, 2, …]</code> 같은 모양이면 <b>우연히 같아</b> 테스트가 통과하기도 합니다.\n해결: 값이 필요하면 <b>불리언 인덱싱</b> <code>a[a &gt; t]</code> 를 씁니다. 자리가 필요할 때만 <code>np.where</code> 를 쓰고, 값을 고르는 두 갈래가 필요하면 <code>np.where(cond, x, y)</code> 처럼 인자 세 개짜리를 씁니다.\n재발 방지: <code>np.where</code> 는 인자 개수에 따라 <b>완전히 다른 일</b>을 하는 함수입니다. 이런 함수는 무엇을 돌려주는지 테스트로 못 박아 두세요. 그리고 값과 자리를 헷갈리지 않게 <b>테스트 자료를 인덱스와 다르게</b> 만드는 것이 요령입니다." },

{ track:"numpy", cat:"debug", fn:"nan_mean",
  k:"결측이 섞이면 평균이 nan 이 된다",
  q:"<code>nan</code> 이 섞인 배열의 평균을 구합니다. 유효한 값이 하나도 없으면 <code>None</code> 입니다. 지금은 결측이 하나만 있어도 결과가 <code>nan</code> 입니다.",
  pkgs:["numpy"],
  src:"import numpy as np\n\ndef nan_mean(a):\n    return float(np.mean(a))\n",
  sol:"import numpy as np\n\ndef nan_mean(a):\n    ok = a[~np.isnan(a)]\n    if ok.size == 0:\n        return None\n    return float(np.mean(ok))\n",
  tests:[["nan_mean(np.array([1.0, np.nan, 3.0]))","2.0"],
         ["nan_mean(np.array([2.0, 4.0]))","3.0"],
         ["nan_mean(np.array([np.nan, np.nan])) is None","True"],
         ["nan_mean(np.array([5.0, np.nan]))","5.0"]],
  edge:[["nan_mean(np.array([])) is None","True"],
        ["nan_mean(np.array([0.0, np.nan, 0.0]))","0.0"]],
  ex:"원인: <code>nan</code> 은 <b>어떤 연산에도 번집니다</b> — 하나만 섞여도 합계와 평균이 전부 <code>nan</code> 이 됩니다. 그리고 <code>nan == nan</code> 이 거짓이라 일반 비교로는 찾을 수도 없습니다.\n해결: <code>np.isnan</code> 으로 걸러 낸 뒤 평균을 냅니다. 넘파이의 <code>np.nanmean</code> 도 같은 일을 하지만, 전부 <code>nan</code> 이면 경고와 함께 <code>nan</code> 을 돌려주므로 <b>빈 경우를 따로</b> 다뤄야 하는 것은 같습니다.\n재발 방지: 결측이 있을 수 있는 자료는 <b>파이프라인 입구에서</b> 개수를 세어 로그에 남기세요. 그리고 '결측을 뺀 평균' 은 결측이 무작위일 때만 뜻이 있습니다 — 결측 자체에 패턴이 있으면(측정 실패가 특정 조건에서만 발생) 평균이 편향됩니다." },

{ track:"numpy", cat:"debug", fn:"argmax_row",
  k:"평탄화된 argmax 를 행 번호로 쓴다",
  q:"2차원 배열에서 <b>행마다</b> 최댓값의 열 번호를 구해 리스트로 돌려줍니다. 지금은 값이 하나만 나오거나 범위를 벗어납니다.",
  pkgs:["numpy"],
  src:"import numpy as np\n\ndef argmax_row(a):\n    return [int(np.argmax(a))]\n",
  sol:"import numpy as np\n\ndef argmax_row(a):\n    return np.argmax(a, axis=1).tolist()\n",
  tests:[["argmax_row(np.array([[1, 9], [7, 2]]))","[1, 0]"],
         ["argmax_row(np.array([[3, 1, 2]]))","[0]"],
         ["argmax_row(np.array([[0, 0], [0, 1]]))","[0, 1]"],
         ["argmax_row(np.array([[5], [6]]))","[0, 0]"]],
  edge:[["argmax_row(np.array([[1, 2], [3, 4], [6, 5]]))","[1, 1, 0]"],
        ["argmax_row(np.array([[2, 2]]))","[0]"]],
  ex:"원인: <code>axis</code> 없는 <code>np.argmax</code> 는 배열을 <b>한 줄로 편 뒤</b> 전체 최댓값의 자리를 돌려줍니다. 그 값은 행 번호도 열 번호도 아닌 <b>평탄화된 인덱스</b>라, 열 번호로 쓰면 범위를 벗어나거나 엉뚱한 자리를 가리킵니다.\n해결: <code>axis=1</code> 을 주면 행마다 열 번호가 나옵니다. 평탄화된 인덱스를 행·열로 되돌리려면 <code>np.unravel_index</code> 를 씁니다.\n재발 방지: <code>argmax</code>·<code>argmin</code>·<code>argsort</code> 는 <b>axis 기본값이 '전체'</b>인 것과 '마지막 축' 인 것이 함수마다 달라 특히 헷갈립니다. 축을 <b>언제나 명시</b>하는 습관이 가장 안전하고, 결과의 모양을 테스트에 함께 적어 두세요." },

{ track:"numpy", cat:"debug", fn:"add_bias",
  k:"제자리 연산이 dtype 을 강요한다",
  q:"정수 배열에 소수 <code>b</code> 를 더해 <b>실수 배열</b>로 돌려줍니다. 지금은 소수 부분이 사라집니다.",
  pkgs:["numpy"],
  src:"import numpy as np\n\ndef add_bias(a, b):\n    a += b\n    return a.tolist()\n",
  sol:"import numpy as np\n\ndef add_bias(a, b):\n    return (a + b).tolist()\n",
  tests:[["add_bias(np.array([1, 2]), 0.5)","[1.5, 2.5]"],
         ["add_bias(np.array([0]), 0.25)","[0.25]"],
         ["add_bias(np.array([10, 20]), 1.5)","[11.5, 21.5]"],
         ["add_bias(np.array([1]), 1.0)","[2.0]"]],
  edge:[["add_bias(np.array([]), 0.5)","[]"],
        ["add_bias(np.array([-1, 1]), 0.5)","[-0.5, 1.5]"]],
  ex:"원인: <code>a += b</code> 는 <b>제자리 연산</b>이라 결과를 원래 배열에 그대로 써야 합니다. 정수 배열에 소수를 더하면 소수 부분이 잘려 나가고, 넘파이 버전에 따라 아예 오류가 나기도 합니다. 게다가 <b>호출자의 배열까지</b> 바뀝니다.\n해결: <code>a + b</code> 로 <b>새 배열</b>을 만들면 타입이 자동으로 실수로 올라갑니다(타입 승격). 제자리 연산은 메모리를 아끼려는 최적화이지 기본이 아닙니다.\n재발 방지: <code>+=</code>·<code>*=</code> 는 넘파이에서 파이썬과 뜻이 다릅니다 — 파이썬 정수는 새 객체를 만들지만 넘파이 배열은 제자리를 고칩니다. '<b>원본이 그대로인가</b>' 와 '<b>dtype 이 무엇인가</b>' 를 함께 테스트하면 두 문제가 한 번에 잡힙니다." },

{ track:"numpy", cat:"debug", fn:"softmax_np",
  k:"넘파이 소프트맥스가 넘친다",
  q:"1차원 로짓 배열을 확률로 바꿉니다. 실제 로짓은 수백까지 커집니다. 결과는 소수 여섯째 자리까지 반올림한 리스트입니다. 지금은 큰 값에서 <code>nan</code> 이 됩니다.",
  pkgs:["numpy"],
  src:"import numpy as np\n\ndef softmax_np(x):\n    e = np.exp(x)\n    return np.round(e / e.sum(), 6).tolist()\n",
  sol:"import numpy as np\n\ndef softmax_np(x):\n    e = np.exp(x - np.max(x))\n    return np.round(e / e.sum(), 6).tolist()\n",
  tests:[["softmax_np(np.array([0.0, 0.0]))","[0.5, 0.5]"],
         ["softmax_np(np.array([1000.0, 1000.0]))","[0.5, 0.5]"],
         ["softmax_np(np.array([1000.0, 999.0]))","[0.731059, 0.268941]"],
         ["softmax_np(np.array([0.0, 1.0]))","[0.268941, 0.731059]"]],
  edge:[["softmax_np(np.array([-1000.0, -1000.0]))","[0.5, 0.5]"],
        ["softmax_np(np.array([5.0]))","[1.0]"]],
  ex:"원인: <code>np.exp(1000)</code> 은 <code>inf</code> 이고 <code>inf/inf</code> 는 <code>nan</code> 입니다. 넘파이는 경고만 내고 계속 진행하므로 <code>nan</code> 이 조용히 흘러갑니다. 반대로 로짓이 아주 작으면 <code>exp</code> 가 전부 0 이 되어 0 으로 나누기가 됩니다.\n해결: 소프트맥스는 <b>모든 입력에 같은 수를 더하거나 빼도 결과가 같습니다</b>. 최댓값을 빼면 지수의 인자가 0 이하가 되어 넘치지 않고, 최댓값 항이 <code>exp(0)=1</code> 이라 아래로도 무너지지 않습니다.\n재발 방지: 수치 안정성 문제는 <b>실전 크기의 값</b>을 테스트에 넣어야 드러납니다. 그리고 2차원 배치라면 <code>np.max(x, axis=-1, keepdims=True)</code> 로 <b>행마다</b> 빼야 한다는 점도 함께 기억하세요." },

{ track:"numpy", cat:"debug", fn:"pearson",
  k:"상관행렬에서 값 하나를 잘못 꺼낸다",
  q:"두 1차원 배열의 <b>피어슨 상관계수</b> 하나를 실수로 돌려줍니다. 결과는 소수 여섯째 자리까지 반올림합니다. 지금은 언제나 1.0 이 나옵니다.",
  pkgs:["numpy"],
  src:"import numpy as np\n\ndef pearson(x, y):\n    return float(np.round(np.corrcoef(x, y)[0][0], 6))\n",
  sol:"import numpy as np\n\ndef pearson(x, y):\n    return float(np.round(np.corrcoef(x, y)[0][1], 6))\n",
  tests:[["pearson(np.array([1.0, 2.0, 3.0]), np.array([2.0, 4.0, 6.0]))","1.0"],
         ["pearson(np.array([1.0, 2.0, 3.0]), np.array([3.0, 2.0, 1.0]))","-1.0"],
         ["pearson(np.array([1.0, 2.0, 3.0, 4.0]), np.array([1.0, 3.0, 2.0, 4.0]))","0.8"],
         ["pearson(np.array([1.0, 2.0]), np.array([5.0, 1.0]))","-1.0"]],
  edge:[["pearson(np.array([0.0, 1.0, 2.0]), np.array([0.0, 1.0, 2.0]))","1.0"],
        ["pearson(np.array([1.0, 2.0, 3.0]), np.array([1.0, 3.0, 2.0]))","0.5"]],
  ex:"원인: <code>np.corrcoef</code> 는 <b>상관행렬</b>을 돌려줍니다. <code>[0][0]</code> 은 자기 자신과의 상관이라 <b>언제나 1.0</b> 입니다. 첫 테스트가 마침 완전 상관이면 통과해 버려서, 이 실수가 살아남기 딱 좋습니다.\n해결: 두 변수 사이의 값은 <code>[0][1]</code>(또는 <code>[1][0]</code>)입니다. 대각선이 전부 1 인 행렬이라는 점을 알면 실수를 바로 알아챌 수 있습니다.\n재발 방지: 행렬을 돌려주는 함수에서 값 하나를 꺼낼 때는 <b>완전 상관이 아닌 자료</b>로 테스트하세요 — 정답이 1 이 아닌 예제가 있어야 자리 실수가 드러납니다. 그리고 결과가 '언제나 같은 값' 이면 계산이 아니라 <b>꺼내는 자리</b>를 먼저 의심하세요." },

];
