/* 머신러닝 디버깅 12 — 학습은 도는데 결론이 틀린 코드를 고친다.
   전부 결정적이고 순수 JS 다. 검증:  node ver_dbgjs.cjs ./dbg_ml.cjs */
module.exports = [

{ track:"ml", cat:"debug", k:"시계열을 앞에서 잘라 미래를 학습한다",
  q:"시각순으로 정렬된 자료를 <b>뒤쪽 <code>frac</code> 비율</b>을 검증용으로 떼어 <code>[학습, 검증]</code> 으로 나눕니다. 지금은 검증 점수가 아주 좋은데 <b>실서비스 성능은 형편없습니다</b>.",
  src:"function splitByTime(rows, frac) {\n  const cut = Math.floor(rows.length * frac);\n  return [rows.slice(cut), rows.slice(0, cut)];\n}",
  sol:"function splitByTime(rows, frac) {\n  const cut = rows.length - Math.floor(rows.length * frac);\n  return [rows.slice(0, cut), rows.slice(cut)];\n}",
  tests:[["splitByTime([1,2,3,4,5,6,7,8,9,10], 0.2)","[[1,2,3,4,5,6,7,8],[9,10]]"],
         ["splitByTime([1,2,3,4], 0.5)","[[1,2],[3,4]]"],
         ["splitByTime([1,2,3], 0)","[[1,2,3],[]]"],
         ["splitByTime([1,2,3,4,5], 0.4)","[[1,2,3],[4,5]]"]],
  edge:[["splitByTime([], 0.2)","[[],[]]"],
        ["splitByTime([1], 0.9)","[[1],[]]"]],
  ex:"원인: 검증 집합을 <b>앞쪽</b>에서 떼면 모델이 <b>미래를 보고 과거를 맞히게</b> 됩니다. 시계열에는 추세와 계절성이 있어 이렇게 하면 점수가 비현실적으로 좋아지고, 실제 배포에서는 전혀 재현되지 않습니다 — 가장 비싸고 흔한 실수입니다.\n해결: 검증은 언제나 <b>가장 최근</b> 구간입니다. 학습은 그 앞까지만 봅니다.\n재발 방지: 시계열에는 무작위 K-폴드도 쓰면 안 됩니다 — <b>앞으로 걸어가는 검증</b>(walk-forward)이 정석입니다. 그리고 '검증 점수가 놀랍도록 좋다' 는 것은 축하가 아니라 <b>누수를 의심할 신호</b>입니다. 사용자 단위·시간 단위 경계가 학습과 검증 사이에서 새지 않았는지 먼저 확인하세요." },

{ track:"ml", cat:"debug", k:"불균형 자료에 정확도를 쓴다",
  q:"양성·음성 각각의 재현율을 평균한 <b>균형 정확도</b>를 소수 넷째 자리까지 구합니다. 지금은 99% 가 음성인 자료에서 <b>전부 음성이라고 답하는 모델</b>이 최고점을 받습니다.",
  src:"function balancedAcc(tp, tn, fp, fn) {\n  return Math.round((tp + tn) / (tp + tn + fp + fn) * 10000) / 10000;\n}",
  sol:"function balancedAcc(tp, tn, fp, fn) {\n  const pos = tp + fn, neg = tn + fp;\n  if (!pos || !neg) return null;\n  return Math.round((tp / pos + tn / neg) / 2 * 10000) / 10000;\n}",
  tests:[["balancedAcc(0, 99, 0, 1)","0.5"],
         ["balancedAcc(1, 99, 0, 0)","1"],
         ["balancedAcc(5, 5, 5, 5)","0.5"],
         ["balancedAcc(8, 90, 10, 2)","0.85"]],
  edge:[["balancedAcc(0, 10, 0, 0) === null","true"],
        ["balancedAcc(3, 0, 0, 1)","null"]],
  ex:"원인: 정확도는 <b>다수 클래스에 지배</b>됩니다. 양성이 1% 인 자료에서 '전부 음성' 이라고 답하면 정확도 99% 인데, 정작 찾으려던 것을 <b>하나도 못 찾습니다</b>. 균형 정확도는 클래스별 재현율을 평균해 이 착시를 없앱니다.\n해결: 양성 재현율 <code>tp/(tp+fn)</code> 과 음성 재현율 <code>tn/(tn+fp)</code> 을 각각 구해 평균합니다. 한쪽 클래스가 아예 없으면 정의되지 않으므로 거절합니다.\n재발 방지: 지표는 <b>클래스 비율을 알고 나서</b> 고릅니다. 불균형에서는 균형 정확도·PR 곡선·F1 이 정확도보다 훨씬 많은 것을 말해 줍니다. 그리고 '아무것도 안 하는 모델' 의 점수를 <b>기준선으로 먼저 재 보세요</b> — 그보다 못하면 지표가 잘못된 것입니다." },

{ track:"ml", cat:"debug", k:"정밀도가 예측이 없을 때 무너진다",
  q:"정밀도 <code>tp / (tp + fp)</code> 를 구합니다. 양성 예측이 하나도 없으면 정의되지 않으므로 <code>null</code> 입니다. 지금은 문턱을 높게 잡은 실험에서 <code>NaN</code> 이 나와 리더보드 정렬이 깨집니다.",
  src:"function precisionOf(tp, fp) {\n  return Math.round(tp / (tp + fp) * 10000) / 10000;\n}",
  sol:"function precisionOf(tp, fp) {\n  const pred = tp + fp;\n  if (!pred) return null;\n  return Math.round(tp / pred * 10000) / 10000;\n}",
  tests:[["precisionOf(8, 2)","0.8"],
         ["precisionOf(0, 0) === null","true"],
         ["precisionOf(0, 5)","0"],
         ["precisionOf(3, 0)","1"]],
  edge:[["precisionOf(1, 2)","0.3333"],
        ["precisionOf(0, 1)","0"]],
  ex:"원인: 문턱을 아주 높이면 <b>양성 예측이 0 개</b>가 되고 분모도 0 이 됩니다. <code>0/0</code> 은 <code>NaN</code> 이라 비교가 전부 거짓이 되고, 정렬·최댓값 찾기가 조용히 이상해집니다.\n해결: 분모를 먼저 확인합니다. '<b>예측을 안 했다</b>' 와 '<b>예측이 전부 틀렸다</b>'(<code>precisionOf(0, 5) = 0</code>)는 다른 상태이므로 서로 다른 값으로 표현해야 합니다.\n재발 방지: PR 곡선을 그릴 때 문턱 양 끝에서 이 경우가 반드시 나옵니다. 관례상 정밀도를 1 로 두기도 하는데, 그러면 곡선 아래 면적이 부풀 수 있어 <b>어떤 관례를 쓰는지</b> 적어 두어야 합니다. 지표 함수는 언제나 '분모가 0 인 순간' 을 계약에 포함하세요." },

{ track:"ml", cat:"debug", k:"F1 을 산술평균으로 낸다",
  q:"정밀도와 재현율의 <b>조화평균</b>인 F1 을 소수 넷째 자리까지 구합니다. 둘 다 0 이면 0 입니다. 지금은 한쪽이 0 에 가까운 모델이 <b>괜찮은 점수</b>를 받습니다.",
  src:"function f1Of(p, r) {\n  return Math.round((p + r) / 2 * 10000) / 10000;\n}",
  sol:"function f1Of(p, r) {\n  if (p + r === 0) return 0;\n  return Math.round(2 * p * r / (p + r) * 10000) / 10000;\n}",
  tests:[["f1Of(1, 0)","0"],
         ["f1Of(0.5, 0.5)","0.5"],
         ["f1Of(1, 1)","1"],
         ["f1Of(0.9, 0.1)","0.18"]],
  edge:[["f1Of(0, 0)","0"],
        ["f1Of(0.6, 0.4)","0.48"]],
  ex:"원인: 산술평균은 <b>한쪽이 0 이어도 절반</b>을 줍니다. 재현율 0 인 모델(아무것도 못 찾음)이 0.5 점을 받으면 순위가 통째로 뒤집힙니다. F1 이 조화평균인 이유가 정확히 이것 — <b>둘 다 높아야</b> 높은 점수가 나옵니다.\n해결: <code>2pr/(p+r)</code> 을 쓰고, 두 값이 모두 0 인 경우를 따로 0 으로 둡니다.\n재발 방지: 두 지표를 하나로 합칠 때는 '<b>한쪽이 0 이면 어떻게 되어야 하는가</b>' 를 먼저 물으세요. 조화평균은 작은 쪽에 끌려가고 산술평균은 큰 쪽에 관대합니다. 그리고 F1 은 정밀도와 재현율에 <b>같은 무게</b>를 주므로, 도메인에서 한쪽이 더 중요하면 F<sub>β</sub> 로 무게를 바꿔야 합니다." },

{ track:"ml", cat:"debug", k:"본 적 없는 범주에서 원핫이 깨진다",
  q:"범주를 원핫 벡터로 바꿉니다. 학습 때 본 적 없는 값은 <b>전부 0 인 벡터</b>여야 합니다. 지금은 배포 뒤 새 범주가 들어오면 <b>마지막 자리가 1</b> 이 되어 엉뚱한 예측이 나옵니다.",
  src:"function oneHot(cats, v) {\n  const i = cats.indexOf(v);\n  return cats.map((_, k) => (k === i ? 1 : 0)).map((x, k) => (i < 0 && k === cats.length - 1 ? 1 : x));\n}",
  sol:"function oneHot(cats, v) {\n  const i = cats.indexOf(v);\n  return cats.map((_, k) => (k === i ? 1 : 0));\n}",
  tests:[["oneHot(['a','b','c'], 'b')","[0,1,0]"],
         ["oneHot(['a','b','c'], 'z')","[0,0,0]"],
         ["oneHot(['a','b','c'], 'a')","[1,0,0]"],
         ["oneHot(['a','b','c'], 'c')","[0,0,1]"]],
  edge:[["oneHot([], 'a')","[]"],
        ["oneHot(['x'], 'y')","[0]"]],
  ex:"원인: <code>indexOf</code> 가 −1 을 돌려주는 경우를 '마지막 범주' 로 <b>떠넘겼습니다</b>. 그러면 새 범주가 전부 특정 범주로 둔갑해, 배포 뒤 조용히 예측이 치우칩니다. 학습 데이터로 테스트하면 모든 값이 목록에 있어 절대 안 드러납니다.\n해결: 못 찾으면 <b>전부 0</b> 인 벡터입니다. '모르는 값' 을 명시적으로 다루고 싶다면 <code>&lt;UNK&gt;</code> 자리를 <b>학습 때부터</b> 만들어 두어야 합니다 — 배포 뒤에 끼워 넣으면 차원이 달라집니다.\n재발 방지: 전처리는 '<b>학습에 없던 값이 오면</b>' 을 반드시 정의해야 합니다. 범주형 인코딩·어휘 사전·정규화 파라미터가 모두 같습니다. 그리고 위 마지막 경계 테스트처럼 <b>벡터 길이가 갑자기 달라지지 않는지</b>도 확인하세요." },

{ track:"ml", cat:"debug", k:"K-폴드가 나머지 자료를 버린다",
  q:"<code>n</code> 개를 <code>k</code> 겹으로 나눌 때 <code>i</code> 번째 겹의 <code>[시작, 끝)</code> 을 구합니다. 나누어떨어지지 않아도 <b>모든 자료가 정확히 한 번씩</b> 검증에 쓰여야 합니다. 지금은 뒤쪽 몇 개가 어느 겹에도 안 들어갑니다.",
  src:"function foldRange(n, k, i) {\n  const size = Math.floor(n / k);\n  return [i * size, (i + 1) * size];\n}",
  sol:"function foldRange(n, k, i) {\n  const size = Math.floor(n / k), rest = n % k;\n  const start = i * size + Math.min(i, rest);\n  const end = start + size + (i < rest ? 1 : 0);\n  return [start, end];\n}",
  tests:[["foldRange(10, 3, 0)","[0,4]"],
         ["foldRange(10, 3, 1)","[4,7]"],
         ["foldRange(10, 3, 2)","[7,10]"],
         ["foldRange(9, 3, 2)","[6,9]"]],
  edge:[["foldRange(5, 5, 4)","[4,5]"],
        ["foldRange(4, 3, 0)","[0,2]"]],
  ex:"원인: <code>floor(n/k)</code> 로 균등하게 자르면 <b>나머지가 버려집니다</b>. 10 을 3 으로 나누면 3·3·3 이라 마지막 한 개가 어느 겹에도 안 들어가고, 교차검증 점수가 전체 자료를 대표하지 못합니다. 나누어떨어지는 예제만 테스트하면 통과합니다.\n해결: 나머지를 <b>앞쪽 겹부터 하나씩</b> 더 줍니다. 마지막 겹의 끝이 정확히 <code>n</code> 인지로 검산하세요.\n재발 방지: 나눠 쓰는 코드는 '<b>합치면 전체가 되는가</b>' 를 성질 테스트로 걸어 두세요 — 겹들의 길이 합이 <code>n</code> 이고 서로 겹치지 않아야 합니다. 그리고 분류 문제라면 겹마다 클래스 비율이 유지되는 <b>층화</b> K-폴드가 필요합니다." },

{ track:"ml", cat:"debug", k:"상수 특성에서 최소최대 정규화가 NaN 을 낸다",
  q:"특성을 0~1 로 정규화합니다. 모든 값이 같으면 <b>전부 0</b> 으로 둡니다. 지금은 상수 열 하나 때문에 학습 손실이 첫 스텝부터 <code>NaN</code> 이 됩니다.",
  src:"function minMax(xs) {\n  const lo = Math.min(...xs), hi = Math.max(...xs);\n  return xs.map(x => (x - lo) / (hi - lo));\n}",
  sol:"function minMax(xs) {\n  if (!xs.length) return [];\n  const lo = Math.min(...xs), hi = Math.max(...xs);\n  if (hi === lo) return xs.map(() => 0);\n  return xs.map(x => (x - lo) / (hi - lo));\n}",
  tests:[["minMax([0, 5, 10])","[0,0.5,1]"],
         ["minMax([5, 5, 5])","[0,0,0]"],
         ["minMax([2, 4])","[0,1]"],
         ["minMax([-1, 0, 1])","[0,0.5,1]"]],
  edge:[["minMax([])","[]"],
        ["minMax([7])","[0]"]],
  ex:"원인: 최댓값과 최솟값이 같으면 <b>0 으로 나누기</b>가 됩니다. 상수 특성은 실전에서 흔합니다 — 아직 값이 하나뿐인 신규 필드, 상수로 채운 결측, 필터링 뒤 남은 한 종류. <code>NaN</code> 이 하나 섞이면 역전파를 타고 <b>가중치 전체</b>가 <code>NaN</code> 이 됩니다.\n해결: 범위가 0 이면 전부 0 으로 둡니다. 정보가 없는 열이므로 아예 <b>제거하는</b> 것도 좋은 선택입니다.\n재발 방지: 정규화 파라미터(<code>lo</code>·<code>hi</code>)는 반드시 <b>학습 데이터에서만</b> 구해 검증·배포에 그대로 적용해야 합니다. 전체 데이터로 구하면 그것 자체가 누수입니다. 그리고 배포 뒤 <code>hi</code> 를 넘는 값이 오면 1 을 넘는다는 점도 계약에 적어 두세요." },

{ track:"ml", cat:"debug", k:"조기 종료가 최고 기록을 안 본다",
  q:"검증 손실 목록에서 <b>조기 종료</b> 지점을 찾습니다. <b>최고 기록</b>이 <code>patience</code> 번 갱신되지 않으면 그 자리에서 멈추고, 멈춘 에폭 번호(0부터)를 돌려줍니다. 끝까지 좋아지면 마지막 번호입니다. 지금은 손실이 한 번만 튀어도 학습을 멈춥니다.",
  src:"function stopAt(losses, patience) {\n  for (let i = 1; i < losses.length; i += 1) {\n    let bad = 0;\n    for (let j = i; j < losses.length && j < i + patience; j += 1) {\n      if (losses[j] >= losses[j - 1]) bad += 1;\n    }\n    if (bad >= patience) return i + patience - 1;\n  }\n  return losses.length - 1;\n}",
  sol:"function stopAt(losses, patience) {\n  let best = Infinity, bad = 0;\n  for (let i = 0; i < losses.length; i += 1) {\n    if (losses[i] < best) { best = losses[i]; bad = 0; }\n    else { bad += 1; if (bad >= patience) return i; }\n  }\n  return losses.length - 1;\n}",
  tests:[["stopAt([5,3,4,3.5,3.2], 2)","3"],
         ["stopAt([10,9,9.5,9.2,9.1], 2)","3"],
         ["stopAt([5,4,5,6,7], 2)","3"],
         ["stopAt([5,4,3,2,1], 2)","4"]],
  edge:[["stopAt([1], 2)","0"],
        ["stopAt([3,3,3], 2)","2"]],
  ex:"원인: <b>직전 에폭</b>과만 견주면 손실이 한 번 튀었다가 더 좋아지는 정상적인 학습에서도 멈춥니다. 조기 종료의 기준은 '<b>지금까지의 최고 기록</b>' 이고, 그 기록이 갱신되지 않은 횟수를 세야 합니다.\n해결: 최고 기록과 '갱신 없이 지난 횟수' 두 값만 들고 돕니다. 갱신되면 카운터를 0 으로 되돌립니다.\n재발 방지: 조기 종료는 <b>가중치도 되돌려야</b> 의미가 있습니다 — 멈춘 시점이 아니라 최고 기록 시점의 가중치를 복원하세요. 그리고 <code>patience</code> 를 정할 때는 검증 손실의 자연스러운 흔들림 폭을 먼저 보고, 최소 개선 폭(<code>min_delta</code>)도 함께 두는 것이 좋습니다." },

{ track:"ml", cat:"debug", k:"클래스 가중치가 거꾸로 걸렸다",
  q:"클래스별 표본 수로 <b>가중치</b>를 정합니다. 드문 클래스일수록 <b>커야</b> 하고, 가중치의 합은 클래스 수와 같도록 맞춥니다. 지금은 다수 클래스에 더 큰 가중치가 걸려 불균형이 오히려 심해집니다.",
  src:"function classWeights(counts) {\n  const total = counts.reduce((s, c) => s + c, 0);\n  if (!total) return counts.map(() => 0);\n  return counts.map(c => Math.round(c / total * counts.length * 10000) / 10000);\n}",
  sol:"function classWeights(counts) {\n  const total = counts.reduce((s, c) => s + c, 0);\n  if (!total || counts.some(c => c <= 0)) return null;\n  const raw = counts.map(c => total / c);\n  const sum = raw.reduce((s, w) => s + w, 0);\n  return raw.map(w => Math.round(w / sum * counts.length * 10000) / 10000);\n}",
  tests:[["classWeights([50, 50])","[1,1]"],
         ["classWeights([90, 10])","[0.2,1.8]"],
         ["classWeights([1, 1, 2])","[1.2,1.2,0.6]"],
         ["classWeights([10, 10, 10])","[1,1,1]"]],
  edge:[["classWeights([0, 5]) === null","true"],
        ["classWeights([25, 75])","[1.5,0.5]"]],
  ex:"원인: 빈도를 <b>그대로</b> 가중치로 쓰면 흔한 클래스가 더 큰 목소리를 갖습니다. 목적이 정확히 반대라서, 모델은 다수 클래스만 더 잘 맞히게 되고 소수 클래스 재현율이 0 으로 수렴합니다.\n해결: <b>빈도의 역수</b>를 쓰고, 합이 클래스 수가 되도록 정규화해 전체 손실 크기를 유지합니다. 표본이 0 인 클래스는 가중치가 무한이므로 거절합니다.\n재발 방지: 가중치를 넣었으면 <b>방향이 맞는지</b> 반드시 검산하세요 — 균등한 입력에서 전부 1 이 나오고, 소수 클래스 쪽이 더 큰지. 그리고 가중치는 손실만 바꿀 뿐 <b>결정 문턱은 그대로</b>이므로, 문턱도 함께 조정해야 실제 성능이 따라옵니다." },

{ track:"ml", cat:"debug", k:"로그 손실이 무한대로 튄다",
  q:"이진 <b>로그 손실</b>을 소수 넷째 자리까지 구합니다. 확률이 정확히 0 이나 1 이면 로그가 발산하므로 <code>1e-15</code> 만큼 안쪽으로 <b>잘라</b> 계산합니다. 지금은 손실이 <code>Infinity</code> 가 되어 학습 곡선이 끊깁니다.",
  src:"function logLoss(ys, ps) {\n  const n = ys.length;\n  let s = 0;\n  for (let i = 0; i < n; i += 1) {\n    s += ys[i] ? -Math.log(ps[i]) : -Math.log(1 - ps[i]);\n  }\n  return Math.round(s / n * 10000) / 10000;\n}",
  sol:"function logLoss(ys, ps) {\n  const n = ys.length;\n  if (!n) return null;\n  const eps = 1e-15;\n  let s = 0;\n  for (let i = 0; i < n; i += 1) {\n    const p = Math.min(1 - eps, Math.max(eps, ps[i]));\n    s += ys[i] ? -Math.log(p) : -Math.log(1 - p);\n  }\n  return Math.round(s / n * 10000) / 10000;\n}",
  tests:[["logLoss([1], [1])","0"],
         ["logLoss([1], [0])","34.5388"],
         ["logLoss([1, 0], [0.5, 0.5])","0.6931"],
         ["logLoss([0], [0])","0"]],
  edge:[["logLoss([], []) === null","true"],
        ["logLoss([1, 1], [0.9, 0.9])","0.1054"]],
  ex:"원인: <code>log(0)</code> 은 <code>-Infinity</code> 입니다. 모델이 자신 있게 틀리면(확률 0 인데 정답이 1) 손실이 무한이 되고, 그 뒤 모든 평균과 기울기가 <code>NaN</code>·<code>Infinity</code> 로 오염됩니다. 확률을 <code>sigmoid</code> 로 만들면 정확히 0 이 나오기 어렵지만, 반올림·<code>float16</code>·클리핑을 거치면 실제로 나옵니다.\n해결: 확률을 <code>[eps, 1-eps]</code> 로 자릅니다. 그러면 최악의 손실이 <code>-log(eps) ≈ 34.5</code> 로 유한하게 묶입니다.\n재발 방지: 로그·나눗셈·역수처럼 <b>정의역이 있는 연산</b> 앞에는 언제나 클리핑을 둡니다. 그리고 손실 곡선에 <code>NaN</code> 이 한 번 나오면 그 뒤는 전부 <code>NaN</code> 이므로, 학습 루프에 '<b>유한한 값인가</b>' 검사를 넣어 그 자리에서 멈추게 하세요." },

{ track:"ml", cat:"debug", k:"결측을 0 으로 세어 평균이 내려간다",
  q:"결측(<code>null</code>)이 섞인 배열의 평균을 구합니다. 결측은 <b>계산에서 빼야</b> 하고, 값이 하나도 없으면 <code>null</code> 입니다. 지금은 결측이 많은 열의 평균이 실제보다 <b>크게 낮아집니다</b>.",
  src:"function meanSkipNull(xs) {\n  const s = xs.reduce((a, x) => a + (x === null ? 0 : x), 0);\n  return Math.round(s / xs.length * 10000) / 10000;\n}",
  sol:"function meanSkipNull(xs) {\n  const ok = xs.filter(x => x !== null && x !== undefined && !Number.isNaN(x));\n  if (!ok.length) return null;\n  const s = ok.reduce((a, x) => a + x, 0);\n  return Math.round(s / ok.length * 10000) / 10000;\n}",
  tests:[["meanSkipNull([10, null, 20])","15"],
         ["meanSkipNull([10, 20])","15"],
         ["meanSkipNull([null, null]) === null","true"],
         ["meanSkipNull([4, null, null, 4])","4"]],
  edge:[["meanSkipNull([]) === null","true"],
        ["meanSkipNull([0, null])","0"]],
  ex:"원인: 결측을 0 으로 바꾸면 <b>'모른다' 가 '0 이다' 로 둔갑</b>합니다. 분모도 전체 개수를 그대로 써서, 결측 비율만큼 평균이 아래로 끌려갑니다. 결측이 적은 개발용 표본에서는 차이가 작아 눈에 안 띕니다.\n해결: 결측을 <b>걸러 낸 뒤</b> 남은 개수로 나눕니다. <code>NaN</code> 도 함께 거르는 이유는 <code>NaN</code> 하나가 합계 전체를 <code>NaN</code> 으로 만들기 때문입니다.\n재발 방지: 결측 처리는 '<b>왜 비었는가</b>' 를 알아야 정할 수 있습니다 — 측정 실패라면 빼고, '해당 없음' 이라면 0 이 맞을 수도 있습니다. 그리고 결측 여부 자체가 정보일 때가 많으므로, 채우기 전에 <b>결측 표시 열</b>을 하나 만들어 두는 것이 흔한 요령입니다." },

{ track:"ml", cat:"debug", k:"학습률 감쇠가 매 에폭 떨어진다",
  q:"<b>계단식</b> 학습률 감쇠입니다 — <code>step</code> 에폭마다 <code>gamma</code> 를 곱합니다. 지금은 매 에폭 곱해져 <b>몇 에폭 만에 학습이 멈춥니다</b>.",
  src:"function lrAt(lr0, epoch, step, gamma) {\n  return lr0 * gamma ** epoch;\n}",
  sol:"function lrAt(lr0, epoch, step, gamma) {\n  if (!(step >= 1)) return lr0;\n  return lr0 * gamma ** Math.floor(epoch / step);\n}",
  tests:[["lrAt(0.1, 0, 10, 0.1)","0.1"],
         ["lrAt(0.1, 9, 10, 0.1)","0.1"],
         ["lrAt(0.1, 10, 10, 0.1)","0.010000000000000002"],
         ["lrAt(0.1, 25, 10, 0.5)","0.025"]],
  edge:[["lrAt(0.1, 5, 0, 0.5)","0.1"],
        ["lrAt(1, 3, 1, 0.5)","0.125"]],
  ex:"원인: <code>step</code> 을 안 쓰고 에폭을 그대로 지수로 썼습니다. 감마가 0.1 이면 10 에폭 만에 학습률이 <b>100억분의 1</b> 이 되어, 손실이 어느 순간부터 전혀 움직이지 않습니다. 오류가 아니라 '학습이 수렴한 것처럼 보이는' 증상이라 원인을 찾기 어렵습니다.\n해결: 지수를 <code>floor(epoch / step)</code> 으로 바꿉니다. 첫 <code>step</code> 에폭 동안은 초기 학습률이 그대로 유지되는지로 검산하세요.\n재발 방지: 스케줄러는 <b>몇 개 에폭치를 미리 뽑아 그려 보는</b> 것이 가장 빠른 검증입니다. 그리고 학습이 멈춘 것 같을 때는 손실뿐 아니라 <b>학습률과 기울기 노름</b>을 함께 로그로 남기세요 — 셋을 나란히 보면 원인이 바로 드러납니다." },

];
