/* 컴퓨터 구조 디버깅 12 — 비트와 성능 계산이 어긋난 코드를 고친다.
   전부 결정적이고 순수 JS 다. 검증:  node ver_dbgjs.cjs ./dbg_arch.cjs */
module.exports = [

{ track:"arch", cat:"debug", k:"부호 확장을 안 한다",
  q:"<code>bits</code> 비트 2의 보수 값을 자바스크립트 수로 되살리는 함수입니다. 8비트 <code>0xFF</code> 는 <b>−1</b> 이어야 하는데 255 로 읽혀, 센서 값이 음수 구간에서 통째로 뒤집힙니다.",
  src:"function signExtend(value, bits) {\n  return value;\n}",
  sol:"function signExtend(value, bits) {\n  const top = 1 << (bits - 1);\n  return (value & (top - 1)) - (value & top);\n}",
  tests:[["signExtend(0xFF, 8)","-1"],
         ["signExtend(0x7F, 8)","127"],
         ["signExtend(0x80, 8)","-128"],
         ["signExtend(0x01, 8)","1"]],
  edge:[["signExtend(0xFFFF, 16)","-1"],
        ["signExtend(0, 8)","0"]],
  ex:"원인: 좁은 비트 폭의 값을 넓은 자리에 옮길 때는 <b>맨 위 비트(부호)를 위쪽 전체에 복사</b>해야 합니다. 그냥 옮기면 음수가 큰 양수가 됩니다. 값이 양수 구간에만 있으면 정확히 맞아서, <b>0x80 을 넘는 순간</b> 처음 드러납니다.\n해결: 부호 비트를 뺀 나머지에서 부호 비트의 가중치를 <b>빼면</b> 2의 보수가 됩니다 — <code>(v &amp; (top-1)) - (v &amp; top)</code>. 32비트라면 <code>(v &lt;&lt; 0) &gt;&gt; 0</code> 처럼 시프트로도 됩니다.\n재발 방지: 바이트 배열에서 값을 꺼낼 때 <code>Int8Array</code>·<code>DataView.getInt16</code> 처럼 <b>부호를 아는 뷰</b>를 쓰면 이 계산 자체가 필요 없습니다. 직접 계산해야 한다면 <b>가장 큰 음수</b>(0x80·0x8000)를 테스트에 반드시 넣으세요 — 경계에서만 틀리는 구현이 흔합니다." },

{ track:"arch", cat:"debug", k:"캐시 세트 번호를 주소로 바로 나눈다",
  q:"직접 사상 캐시에서 주소가 들어갈 <b>세트 번호</b>를 구합니다. 세트 번호는 <b>블록 번호</b>를 세트 수로 나눈 나머지입니다. 지금은 인접한 주소들이 서로 다른 세트로 흩어져 지역성이 사라집니다.",
  src:"function setIndexOf(addr, lineSize, sets) {\n  return addr % sets;\n}",
  sol:"function setIndexOf(addr, lineSize, sets) {\n  return Math.floor(addr / lineSize) % sets;\n}",
  tests:[["setIndexOf(0, 64, 8)","0"],
         ["setIndexOf(64, 64, 8)","1"],
         ["setIndexOf(63, 64, 8)","0"],
         ["setIndexOf(640, 64, 8)","2"]],
  edge:[["setIndexOf(4096, 64, 8)","0"],
        ["setIndexOf(65, 64, 8)","1"]],
  ex:"원인: 캐시는 바이트가 아니라 <b>블록(라인) 단위</b>로 움직입니다. 주소를 그대로 나누면 같은 라인 안의 바이트들이 서로 다른 세트로 배정되어, 캐시가 하는 일 자체가 무너집니다.\n해결: 먼저 <code>addr / lineSize</code> 로 블록 번호를 구하고, 그 번호를 세트 수로 나눕니다. 주소 비트로 보면 <b>[태그 | 세트 | 블록 안 오프셋]</b> 세 토막이고, 오프셋 비트를 먼저 잘라 내는 것과 같습니다.\n재발 방지: 2의 거듭제곱이면 <code>(addr &gt;&gt;&gt; log2(lineSize)) &amp; (sets - 1)</code> 로 적을 수 있고, 이 꼴이 주소의 세 토막 구조를 더 잘 드러냅니다. 인접한 주소가 같은 세트에 들어가는지(<code>0</code> 과 <code>63</code>)를 테스트에 넣으면 이 실수는 첫 실행에서 잡힙니다." },

{ track:"arch", cat:"debug", k:"암달의 법칙에서 직렬 구간을 뺐다",
  q:"병렬 비율 <code>p</code>, 코어 <code>n</code> 개일 때의 속도 향상을 소수 둘째 자리까지 구합니다. 지금은 코어를 늘리면 <b>끝없이 빨라진다</b>고 나와 용량 산정이 크게 빗나갑니다.",
  src:"function amdahl(p, n) {\n  return Math.round(1 / (p / n) * 100) / 100;\n}",
  sol:"function amdahl(p, n) {\n  return Math.round(1 / ((1 - p) + p / n) * 100) / 100;\n}",
  tests:[["amdahl(0.5, 2)","1.33"],
         ["amdahl(0.9, 10)","5.26"],
         ["amdahl(1, 4)","4"],
         ["amdahl(0, 8)","1"]],
  edge:[["amdahl(0.95, 1000)","19.63"],
        ["amdahl(0.5, 1)","1"]],
  ex:"원인: 분모에서 <b>직렬 구간 <code>(1 - p)</code></b> 가 빠졌습니다. 그러면 코어 수에 비례해 무한히 빨라진다는 결론이 나오는데, 암달의 법칙이 말하려는 바가 정확히 그 반대입니다 — 병렬화가 안 되는 5% 가 있으면 코어를 무한히 늘려도 <b>20배가 상한</b>입니다.\n해결: 분모를 <code>(1 - p) + p / n</code> 으로 적습니다. <code>p = 0</code>(전부 직렬)이면 1, <code>p = 1</code>(전부 병렬)이면 n 이 나오는지로 식을 검산할 수 있습니다.\n재발 방지: 성능 공식은 <b>극단값으로 검산</b>하는 습관이 가장 빠릅니다. 여기서는 <code>n = 1</code> 이면 언제나 1, <code>p = 0</code> 이면 언제나 1 이어야 합니다. 그리고 이 상한을 알면 '<b>어디를 병렬화할 것인가</b>' 보다 '<b>직렬 구간을 줄일 수 있는가</b>' 를 먼저 묻게 됩니다." },

{ track:"arch", cat:"debug", k:"바이트 뒤집기가 음수를 낸다",
  q:"32비트 값의 <b>바이트 순서를 뒤집는</b> 함수입니다. 결과는 <b>부호 없는</b> 수여야 하는데, 최상위 바이트가 0x80 이상이면 음수가 나와 파일 오프셋 계산이 깨집니다.",
  src:"function swap32(x) {\n  return ((x & 0xff) << 24) | ((x & 0xff00) << 8) | ((x >> 8) & 0xff00) | ((x >> 24) & 0xff);\n}",
  sol:"function swap32(x) {\n  const v = ((x & 0xff) << 24) | ((x & 0xff00) << 8) | ((x >>> 8) & 0xff00) | ((x >>> 24) & 0xff);\n  return v >>> 0;\n}",
  tests:[["swap32(0x12345678)","2018915346"],
         ["swap32(0x000000FF)","4278190080"],
         ["swap32(0)","0"],
         ["swap32(0xFFFFFFFF)","4294967295"]],
  edge:[["swap32(0x00FF0000)","65280"],
        ["swap32(0x01000000)","1"]],
  ex:"원인: 자바스크립트의 비트 연산은 값을 <b>부호 있는 32비트</b>로 다룹니다. 결과의 최상위 비트가 켜지면 음수가 되고, <code>&gt;&gt;</code> 는 부호 비트를 채우며 내려가 위쪽 바이트까지 오염시킵니다.\n해결: 오른쪽 시프트는 <b>부호 없는</b> <code>&gt;&gt;&gt;</code> 를 쓰고, 마지막에 <code>&gt;&gt;&gt; 0</code> 으로 부호 없는 수로 되돌립니다. <code>&gt;&gt;&gt; 0</code> 은 값을 바꾸지 않으면서 타입만 바로잡는 관용구입니다.\n재발 방지: 바이트 순서를 다룰 일이 있으면 <code>DataView</code> 의 <code>getUint32(off, littleEndian)</code> 를 쓰는 편이 안전합니다. 직접 계산한다면 <b>최상위 비트가 켜지는 값</b>을 반드시 테스트에 넣으세요 — 0x12345678 하나로는 절대 안 잡힙니다." },

{ track:"arch", cat:"debug", k:"파이프라인 총 사이클이 한 칸 많다",
  q:"<code>stages</code> 단계 파이프라인에서 <code>instrs</code> 개 명령을 흘릴 때의 <b>이상적인 총 사이클</b>을 구합니다(해저드 없음). 명령이 없으면 0 입니다. 지금 값이 교재보다 <b>1 씩 큽니다</b>.",
  src:"function pipeCycles(stages, instrs) {\n  return stages + instrs;\n}",
  sol:"function pipeCycles(stages, instrs) {\n  return instrs <= 0 ? 0 : stages + instrs - 1;\n}",
  tests:[["pipeCycles(5, 1)","5"],
         ["pipeCycles(5, 2)","6"],
         ["pipeCycles(5, 100)","104"],
         ["pipeCycles(1, 10)","10"]],
  edge:[["pipeCycles(5, 0)","0"],
        ["pipeCycles(3, 3)","5"]],
  ex:"원인: 첫 명령이 <b>파이프를 채우는 데 <code>stages</code> 사이클</b>이 걸리고, 그 뒤로는 <b>한 사이클에 하나씩</b> 나옵니다. 그래서 <code>stages + (instrs - 1)</code> 이지 <code>stages + instrs</code> 가 아닙니다. 명령이 1 개일 때 <code>stages</code> 가 나오는지로 바로 검산됩니다.\n해결: <code>-1</code> 을 넣고, 명령이 0 개인 경우를 따로 갈라 음수가 나오지 않게 합니다.\n재발 방지: '<b>채우는 구간 + 흘러나오는 구간</b>' 구조는 파이프라인·스트리밍·배치 처리에 공통입니다. 경계는 언제나 '첫 하나' 와 '없음' 입니다. 그리고 이 식이 말하는 바 — 명령이 많아질수록 단계 수는 무시할 수 있고 <b>처리량이 사이클당 1 로 수렴</b>한다 — 가 파이프라인을 쓰는 이유입니다." },

{ track:"arch", cat:"debug", k:"미스 페널티를 모든 명령에 매긴다",
  q:"캐시 미스를 포함한 <b>실효 CPI</b> 를 소수 둘째 자리까지 구합니다. 식은 <code>base + 미스율 × 페널티</code> 입니다. 지금은 미스율이 0 이어도 페널티가 그대로 더해져, 최적화 효과가 보이지 않습니다.",
  src:"function cpiWithMiss(base, rate, penalty) {\n  return Math.round((base + penalty) * 100) / 100;\n}",
  sol:"function cpiWithMiss(base, rate, penalty) {\n  return Math.round((base + rate * penalty) * 100) / 100;\n}",
  tests:[["cpiWithMiss(1, 0.02, 100)","3"],
         ["cpiWithMiss(1, 0, 100)","1"],
         ["cpiWithMiss(2, 0.1, 20)","4"],
         ["cpiWithMiss(1, 1, 5)","6"]],
  edge:[["cpiWithMiss(1.5, 0.05, 40)","3.5"],
        ["cpiWithMiss(1, 0.001, 1000)","2"]],
  ex:"원인: 페널티는 <b>미스가 났을 때만</b> 냅니다. 곱하기를 빼먹으면 모든 명령이 매번 메모리를 다녀오는 셈이 되어, 실제로는 2 인 CPI 가 101 로 나옵니다. 그 숫자로 최적화를 판단하면 엉뚱한 곳을 고칩니다.\n해결: <code>rate * penalty</code> 로 <b>기댓값</b>을 더합니다. 미스율 0 이면 base 가 그대로 나오는지로 검산하세요.\n재발 방지: 성능 식에서 '확률 × 비용' 은 거의 언제나 나옵니다 — 미스율·분기 예측 실패율·재시도율·타임아웃 비율. 곱해야 할 것을 더하면 값이 <b>수십 배</b> 어긋나므로, 극단값(0 과 1)으로 검산하는 습관이 이 실수를 즉시 잡아 줍니다." },

{ track:"arch", cat:"debug", k:"사이클을 나노초로 바꾸며 곱한다",
  q:"클록 <code>ghz</code> 인 CPU 에서 <code>cycles</code> 사이클이 걸리는 시간을 <b>나노초</b>로 구합니다. 3GHz 에서 3 사이클이면 1ns 입니다. 지금은 클록이 빠를수록 시간이 <b>늘어난다</b>고 나옵니다.",
  src:"function nsFor(cycles, ghz) {\n  return cycles * ghz;\n}",
  sol:"function nsFor(cycles, ghz) {\n  return cycles / ghz;\n}",
  tests:[["nsFor(3, 3)","1"],
         ["nsFor(10, 2)","5"],
         ["nsFor(0, 2)","0"],
         ["nsFor(9, 3)","3"]],
  edge:[["nsFor(1, 4)","0.25"],
        ["nsFor(100, 2.5)","40"]],
  ex:"원인: 단위가 뒤집혔습니다. GHz 는 <b>초당 10억 사이클</b>이므로 사이클당 시간은 <code>1 / ghz</code> 나노초입니다. 시간을 구하려면 <b>나눠야</b> 합니다. 3GHz·3사이클처럼 두 값이 같으면 곱해도 나눠도… 는 아니고 9 와 1 로 갈리니 첫 테스트에서 바로 드러납니다.\n해결: <code>cycles / ghz</code>. 단위를 적어 보면 확인됩니다 — <code>사이클 ÷ (사이클/ns) = ns</code>.\n재발 방지: 단위 변환은 <b>차원 분석</b>으로 검산하세요. 곱할지 나눌지 헷갈릴 때는 극단값을 넣어 방향을 봅니다 — '클록이 빨라지면 시간이 줄어야 한다' 는 상식 하나로 충분합니다. 성능 계산에서 이 방향 실수는 결론을 정반대로 뒤집습니다." },

{ track:"arch", cat:"debug", k:"구조체 크기에 패딩이 없다",
  q:"필드 목록(<code>{size, align}</code>)으로 구조체의 <b>실제 크기</b>를 구합니다. 각 필드는 자기 정렬 경계에서 시작하고, 전체 크기는 <b>가장 큰 정렬의 배수</b>로 올림합니다. 지금 값이 <code>sizeof</code> 와 달라 파일 형식이 어긋납니다.",
  src:"function structSize(fields) {\n  return fields.reduce((s, f) => s + f.size, 0);\n}",
  sol:"function structSize(fields) {\n  let off = 0, max = 1;\n  for (const f of fields) {\n    off = Math.ceil(off / f.align) * f.align;\n    off += f.size;\n    if (f.align > max) max = f.align;\n  }\n  return Math.ceil(off / max) * max;\n}",
  tests:[["structSize([{size:1,align:1},{size:4,align:4}])","8"],
         ["structSize([{size:4,align:4},{size:1,align:1}])","8"],
         ["structSize([{size:1,align:1}])","1"],
         ["structSize([])","0"]],
  edge:[["structSize([{size:8,align:8},{size:1,align:1},{size:2,align:2}])","16"],
        ["structSize([{size:2,align:2},{size:2,align:2}])","4"]],
  ex:"원인: 필드 크기를 더하기만 하면 <b>정렬 패딩</b>이 빠집니다. <code>char</code> 뒤에 <code>int</code> 가 오면 3바이트가 비고, 구조체 전체도 배열로 늘어놓을 수 있게 <b>끝에 패딩</b>이 붙습니다. 5 와 8 의 차이는 파일에 쓰거나 네트워크로 보낼 때 그대로 형식 불일치가 됩니다.\n해결: 필드마다 자기 정렬로 올림한 뒤 크기를 더하고, 마지막에 <b>최대 정렬</b>로 한 번 더 올립니다.\n재발 방지: 필드를 <b>큰 것부터</b> 늘어놓으면 패딩이 줄어듭니다(위 두 예가 같은 8 인 것도 우연이 아닙니다 — 더 복잡한 구조체에서는 차이가 커집니다). 그리고 디스크·네트워크로 나가는 구조체는 컴파일러 정렬에 기대지 말고 <b>바이트 단위로 직렬화</b>하세요 — 컴파일러·아키텍처마다 답이 다릅니다." },

{ track:"arch", cat:"debug", k:"속도 향상을 산술평균으로 낸다",
  q:"여러 벤치마크의 속도 향상 배수를 <b>하나의 대표값</b>으로 요약합니다. 비율의 평균은 <b>기하평균</b>이어야 합니다. 지금 값이 실제보다 후하게 나와 최적화 효과가 과장됩니다. 빈 목록은 1 입니다.",
  src:"function geoSpeedup(list) {\n  if (!list.length) return 1;\n  const sum = list.reduce((s, x) => s + x, 0);\n  return Math.round(sum / list.length * 100) / 100;\n}",
  sol:"function geoSpeedup(list) {\n  if (!list.length) return 1;\n  const prod = list.reduce((s, x) => s * x, 1);\n  return Math.round(prod ** (1 / list.length) * 100) / 100;\n}",
  tests:[["geoSpeedup([2, 8])","4"],
         ["geoSpeedup([1, 1])","1"],
         ["geoSpeedup([4])","4"],
         ["geoSpeedup([1, 2, 4])","2"]],
  edge:[["geoSpeedup([])","1"],
        ["geoSpeedup([0.5, 2])","1"]],
  ex:"원인: 비율을 산술평균하면 <b>기준이 무엇이냐에 따라 답이 달라집니다</b>. 2배와 8배의 산술평균은 5 지만, 두 벤치마크의 기준을 뒤집어 계산하면(0.5배와 0.125배) 역수의 평균이 4 와 맞지 않습니다. 기하평균은 <b>기준을 뒤집어도 같은 답</b>을 줍니다.\n해결: 곱한 뒤 개수제곱근을 취합니다. 절반으로 느려진 것(0.5)과 두 배 빨라진 것(2)을 함께 요약하면 <b>1</b> 이 나오는지로 검산할 수 있습니다 — 산술평균은 1.25 라는 이상한 답을 냅니다.\n재발 방지: 평균에는 쓸 자리가 정해져 있습니다 — <b>더해서 뜻이 있는 값</b>은 산술, <b>곱해서 뜻이 있는 비율</b>은 기하, <b>속도·처리율</b>은 조화평균. SPEC 벤치마크가 기하평균을 쓰는 이유이고, 값이 많을 때는 곱이 넘칠 수 있어 <b>로그 평균</b>으로 계산합니다." },

{ track:"arch", cat:"debug", k:"AMAT 의 괄호가 빠졌다",
  q:"2단 캐시의 <b>평균 메모리 접근 시간</b>을 소수 둘째 자리까지 구합니다. 식은 <code>l1 + r1 × (l2 + r2 × mem)</code> 입니다. 지금은 L2 를 개선해도 값이 거의 안 움직입니다.",
  src:"function amat(l1, l2, mem, r1, r2) {\n  return Math.round((l1 + r1 * l2 + r2 * mem) * 100) / 100;\n}",
  sol:"function amat(l1, l2, mem, r1, r2) {\n  return Math.round((l1 + r1 * (l2 + r2 * mem)) * 100) / 100;\n}",
  tests:[["amat(1, 10, 100, 0.1, 0.02)","2.2"],
         ["amat(1, 10, 100, 0, 0.5)","1"],
         ["amat(2, 20, 200, 0.5, 0.5)","62"],
         ["amat(1, 10, 100, 1, 1)","111"]],
  edge:[["amat(1, 10, 100, 0.1, 0)","2"],
        ["amat(4, 12, 120, 0.25, 0.1)","10"]],
  ex:"원인: 메모리까지 가는 비용은 <b>L1 도 미스하고 L2 도 미스했을 때만</b> 냅니다. 괄호가 없으면 L2 미스율이 L1 미스율과 무관하게 곱해져, 전체 미스 경로가 실제보다 훨씬 무겁게 잡힙니다. 그러면 L1 미스율이 0 이어도 값이 1 로 떨어지지 않습니다 — 그 검산으로 바로 드러납니다.\n해결: 계층은 <b>중첩된 조건부 확률</b>입니다. 안쪽부터 <code>(l2 + r2 * mem)</code> 을 묶고 그 전체에 <code>r1</code> 을 곱합니다.\n재발 방지: 캐시 계층의 미스율은 대개 <b>지역 미스율</b>(그 계층에 온 요청 중)로 보고됩니다. 전역 미스율로 착각하면 이 식이 통째로 달라집니다. 어떤 미스율인지 <b>이름과 단위를 함께</b> 적어 두세요 — 성능 모델의 버그는 대부분 수식이 아니라 정의에서 옵니다." },

{ track:"arch", cat:"debug", k:"일감이 나누어떨어진다고 가정한다",
  q:"작업 <code>work</code> 를 <code>workers</code> 명이 최대한 고르게 나눠 할 때 <b>걸리는 시간</b>을 구합니다(준비 시간 <code>setup</code> 포함). 가장 많이 맡은 사람이 끝나야 끝입니다. 지금 예측이 실제보다 짧아 마감을 계속 놓칩니다.",
  src:"function parallelTime(work, workers, setup) {\n  return setup + work / workers;\n}",
  sol:"function parallelTime(work, workers, setup) {\n  return setup + Math.ceil(work / workers);\n}",
  tests:[["parallelTime(10, 3, 1)","5"],
         ["parallelTime(9, 3, 1)","4"],
         ["parallelTime(1, 4, 0)","1"],
         ["parallelTime(0, 4, 2)","2"]],
  edge:[["parallelTime(100, 7, 0)","15"],
        ["parallelTime(5, 5, 1)","2"]],
  ex:"원인: 나누어떨어지지 않으면 <b>누군가는 한 개를 더</b> 맡습니다. 전체가 끝나는 시각은 평균이 아니라 <b>가장 오래 걸리는 사람</b>이 정합니다. 10 을 3 명이 나누면 4·3·3 이라 4 인데, 3.33 으로 계산하면 매번 조금씩 낙관적인 예측이 됩니다.\n해결: <code>Math.ceil</code> 로 최대 몫을 구합니다. 작업이 0 이면 준비 시간만 남는지도 함께 확인하세요.\n재발 방지: 병렬 처리 예측은 <b>평균이 아니라 최댓값</b>이 지배합니다(꼬리 지연도 같은 이야기). 그리고 일감의 크기가 제각각이면 개수만 나눠서는 안 되고 <b>크기 기준</b>으로 나눠야 합니다 — 균등 분할이 아니라 부하 분할입니다." },

{ track:"arch", cat:"debug", k:"루프라인에서 큰 쪽을 고른다",
  q:"루프라인 모델로 <b>도달 가능한 성능</b>(GFLOPS)을 구합니다. 연산 강도는 <code>flops / bytes</code> 이고, 성능은 <b>연산 상한과 대역폭 상한 중 작은 쪽</b>입니다. 지금은 메모리에 묶인 커널도 최대 성능이 난다고 나옵니다.",
  src:"function roofline(flops, bytes, peakFlops, bw) {\n  if (bytes <= 0) return peakFlops;\n  return Math.max(peakFlops, bw * (flops / bytes));\n}",
  sol:"function roofline(flops, bytes, peakFlops, bw) {\n  if (bytes <= 0) return peakFlops;\n  return Math.min(peakFlops, bw * (flops / bytes));\n}",
  tests:[["roofline(100, 10, 1000, 50)","500"],
         ["roofline(100, 1, 1000, 50)","1000"],
         ["roofline(10, 10, 1000, 50)","50"],
         ["roofline(0, 10, 1000, 50)","0"]],
  edge:[["roofline(100, 0, 1000, 50)","1000"],
        ["roofline(40, 10, 1000, 50)","200"]],
  ex:"원인: 두 상한 중 <b>큰 쪽</b>을 고르면 상한이라는 개념 자체가 뒤집힙니다. 성능은 두 제약을 <b>동시에</b> 만족해야 하므로 작은 쪽이 답입니다. 연산 강도가 높은 커널만 테스트하면 두 값이 같은 쪽에 몰려 우연히 통과합니다.\n해결: <code>Math.min</code> 입니다. 연산 강도가 낮으면 대역폭이, 높으면 연산 능력이 병목이라는 것이 루프라인이 보여 주려는 그림입니다.\n재발 방지: 여러 제약이 있는 계산에서 <b>상한은 min, 하한은 max</b> 입니다. 헷갈리면 극단값으로 검산하세요 — 대역폭이 0 이면 성능도 0 이어야 합니다. 그리고 이 모델의 값어치는 정확한 숫자가 아니라 '<b>지금 무엇에 묶여 있는가</b>' 를 알려 주는 데 있습니다." },

];
