/* 파이썬 실행형 디버깅 문항 — 고장난 코드를 받아 직접 고친다.
   'cat:debug' 는 지금 가장 비어 있는 칸이고(378/1000), 선택형이 아니라
   실제로 파이썬을 돌려 채점하므로 code 칸도 같이 채운다.

   검증 규칙 (하나라도 어기면 주입하지 않는다)
     1. sol 은 tests + edge 를 전부 통과해야 한다
     2. src 는 최소 하나의 tests 를 실패해야 한다 — 통과하면 '고칠 게 없는' 가짜 디버깅이다
     3. src 는 문법 오류가 아니어야 한다 — 문법 오류 찾기는 디버깅이 아니다
     4. 트랙 안에서 함수 이름과 문제 줄기가 겹치지 않아야 한다 */
module.exports = [
{ k:"strip은 부분 문자열이 아니라 문자 집합", fn:"drop_ext",
  q:"파일 이름에서 확장자 '.log' 를 떼어내는 함수인데, 'catalog.log' 를 넣으면 'cata' 가 나옵니다. 'catalog' 가 나오도록 고치세요.",
  src:"def drop_ext(name):\n    return name.strip('.log')",
  sol:"def drop_ext(name):\n    if name.endswith('.log'):\n        return name[:-4]\n    return name",
  tests:[["drop_ext('catalog.log')","'catalog'"],["drop_ext('app.log')","'app'"],["drop_ext('server.log')","'server'"],["drop_ext('goal.log')","'goal'"]],
  edge:[["drop_ext('data.txt')","'data.txt'"],["drop_ext('log')","'log'"]],
  ex:"🐛 원인: strip('.log') 는 '.log' 라는 문자열을 떼는 게 아니라 '.', 'l', 'o', 'g' 라는 문자 집합을 양쪽 끝에서 계속 깎아냅니다. 'catalog.log' 는 뒤에서 '.log' 를 깎고도 'catalog' 의 'g','o','l' 이 집합에 있어 'cata' 까지 갑니다.\n🔧 해결: endswith 로 확인한 뒤 슬라이싱으로 길이만큼 잘라냅니다. 파이썬 3.9+ 라면 removesuffix('.log') 가 더 명확합니다.\n🛡 재발 방지: strip/lstrip/rstrip 의 인자는 '문자 집합' 입니다. 접두·접미사를 떼려면 removeprefix/removesuffix 나 슬라이싱을 쓰세요." },

{ k:"반복 중 삭제", fn:"drop_negatives",
  q:"리스트에서 음수를 모두 제거해야 하는데, 음수가 연달아 있으면 일부가 남습니다. 원본을 바꾸지 말고 새 리스트를 반환하도록 고치세요.",
  src:"def drop_negatives(xs):\n    out = list(xs)\n    for v in out:\n        if v < 0:\n            out.remove(v)\n    return out",
  sol:"def drop_negatives(xs):\n    return [v for v in xs if v >= 0]",
  tests:[["drop_negatives([1,-1,-2,3])","[1,3]"],["drop_negatives([-1,-2,-3])","[]"],["drop_negatives([0,-5,2,-7,-8,4])","[0,2,4]"],["drop_negatives([5,6])","[5,6]"]],
  edge:[["drop_negatives([])","[]"],["drop_negatives([-1])","[]"]],
  ex:"🐛 원인: 반복 중인 리스트에서 원소를 지우면 내부 인덱스가 한 칸 밀려 바로 다음 원소를 건너뜁니다. 음수가 연달아 있으면 두 번째가 통째로 살아남습니다.\n🔧 해결: 지우는 대신 조건에 맞는 것만 골라 새 리스트를 만듭니다.\n🛡 재발 방지: 순회 중인 컬렉션은 절대 크기를 바꾸지 마세요. 필터링은 컴프리헨션이나 filter 로 새로 만드는 게 원칙입니다." },

{ k:"2차원 리스트의 별칭", fn:"make_grid",
  q:"n×n 격자를 0으로 만들고 대각선만 1로 채우는 함수입니다. 그런데 한 칸만 바꿔도 같은 열 전체가 1이 됩니다.",
  src:"def make_grid(n):\n    g = [[0] * n] * n\n    for i in range(n):\n        g[i][i] = 1\n    return g",
  sol:"def make_grid(n):\n    g = [[0] * n for _ in range(n)]\n    for i in range(n):\n        g[i][i] = 1\n    return g",
  tests:[["make_grid(2)","[[1,0],[0,1]]"],["make_grid(3)","[[1,0,0],[0,1,0],[0,0,1]]"],["make_grid(1)","[[1]]"],["make_grid(4)","[[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]]"]],
  edge:[["make_grid(0)","[]"],["len(set(id(r) for r in make_grid(3)))","3"]],
  ex:"🐛 원인: [[0]*n]*n 은 안쪽 리스트 '하나' 를 만들고 그 참조를 n 번 복사합니다. 모든 행이 같은 객체라 한 행을 고치면 전부 바뀝니다.\n🔧 해결: 컴프리헨션으로 매 행마다 새 리스트를 생성합니다.\n🛡 재발 방지: 가변 객체에 * 를 쓰면 복제가 아니라 참조 복사입니다. 중첩 구조는 항상 컴프리헨션으로 만드세요." },

{ k:"sort는 None을 반환한다", fn:"top_two",
  q:"점수 리스트에서 가장 큰 두 개를 내림차순으로 반환해야 하는데 항상 에러가 납니다.",
  src:"def top_two(scores):\n    s = sorted(scores).reverse()\n    return s[:2]",
  sol:"def top_two(scores):\n    return sorted(scores, reverse=True)[:2]",
  tests:[["top_two([3,9,1,7])","[9,7]"],["top_two([5,5,2])","[5,5]"],["top_two([-1,-9,-3])","[-1,-3]"],["top_two([10,20,30,40])","[40,30]"]],
  edge:[["top_two([4])","[4]"],["top_two([])","[]"]],
  ex:"🐛 원인: list.reverse() 는 제자리에서 뒤집고 None 을 반환합니다. sorted(...).reverse() 의 결과는 None 이라 슬라이싱에서 터집니다.\n🔧 해결: sorted(..., reverse=True) 로 정렬과 방향을 한 번에 지정합니다.\n🛡 재발 방지: 제자리 변경 메서드(sort·reverse·append)는 None 을 반환합니다. 값을 이어 쓰려면 sorted·reversed 같은 '새 객체를 주는' 함수를 쓰세요." },

{ k:"정수 나눗셈과 음수 내림", fn:"pages",
  q:"항목 n 개를 한 쪽에 size 개씩 담을 때 필요한 페이지 수를 구합니다. 나머지가 있으면 한 쪽이 더 필요합니다.",
  src:"def pages(n, size):\n    return n // size",
  sol:"def pages(n, size):\n    return -(-n // size)",
  tests:[["pages(10,3)","4"],["pages(9,3)","3"],["pages(1,10)","1"],["pages(100,7)","15"]],
  edge:[["pages(0,5)","0"],["pages(7,1)","7"]],
  ex:"🐛 원인: // 는 내림 나눗셈이라 나머지를 버립니다. 10개를 3개씩 담으면 4쪽이 필요한데 3을 반환합니다.\n🔧 해결: -(-n // size) 는 올림 나눗셈입니다. 부호를 뒤집어 내림시키면 결과적으로 올림이 됩니다. math.ceil(n/size) 는 큰 정수에서 부동소수 오차가 생길 수 있어 정수 연산이 안전합니다.\n🛡 재발 방지: 페이지·배치·청크 계산은 거의 언제나 올림입니다. // 를 쓰기 전에 나머지를 어떻게 할지 먼저 정하세요." },

{ k:"얕은 복사와 중첩 딕셔너리", fn:"with_role",
  q:"사용자 설정을 복사해 role 만 바꿔 돌려주는 함수인데, 반환값을 수정하면 원본의 권한 목록도 함께 바뀝니다.",
  src:"def with_role(user, role):\n    c = dict(user)\n    c['role'] = role\n    return c",
  sol:"import copy\n\ndef with_role(user, role):\n    c = copy.deepcopy(user)\n    c['role'] = role\n    return c",
  tests:[["with_role({'role':'a','perms':['r']},'b')['role']","'b'"],
         ["(lambda u: (with_role(u,'b')['perms'].append('w'), u['perms'])[1])({'role':'a','perms':['r']})","['r']"],
         ["with_role({'role':'a','perms':[]},'admin')['perms']","[]"],
         ["(lambda u: (with_role(u,'x')['perms'].append('z'), len(u['perms']))[1])({'role':'a','perms':['r','w']})","2"]],
  edge:[["with_role({'role':'a'},'b')","{'role':'b'}"],
        ["(lambda u: (with_role(u,'b'), u['role'])[1])({'role':'a','perms':['r']})","'a'"]],
  ex:"🐛 원인: dict(user) 는 얕은 복사입니다. 최상위 키만 새로 만들고 값이 리스트·딕셔너리면 같은 객체를 그대로 가리킵니다.\n🔧 해결: copy.deepcopy 로 중첩된 값까지 새로 만듭니다.\n🛡 재발 방지: 복사가 '어디까지' 필요한지 먼저 정하세요. 중첩 구조를 넘겨받아 수정하는 함수라면 얕은 복사는 거의 항상 버그입니다." },

{ k:"실수 비교", fn:"is_full",
  q:"채워진 비율이 1.0 에 도달했는지 판정합니다. 0.1 을 열 번 더한 값이 들어오면 False 가 나옵니다.",
  src:"def is_full(ratio):\n    return ratio == 1.0",
  sol:"def is_full(ratio):\n    return abs(ratio - 1.0) < 1e-9",
  tests:[["is_full(sum([0.1]*10))","True"],["is_full(1.0)","True"],["is_full(0.5)","False"],["is_full(0.9999)","False"]],
  edge:[["is_full(0.1+0.2+0.7)","True"],["is_full(1.5)","False"]],
  ex:"🐛 원인: 0.1 은 2진 부동소수로 정확히 표현되지 않습니다. 열 번 더하면 0.9999999999999999 가 되어 == 1.0 이 거짓입니다.\n🔧 해결: 허용 오차를 두고 비교합니다. math.isclose(ratio, 1.0) 도 같은 일을 합니다.\n🛡 재발 방지: 부동소수는 == 로 비교하지 않습니다. 금액처럼 정확해야 하는 값은 Decimal 이나 정수 단위(원 대신 전)로 다루세요." },

{ k:"UnboundLocalError", fn:"count_up",
  q:"모듈 수준 카운터를 올리는 함수인데 호출하면 예외가 납니다. 호출할 때마다 1씩 늘어난 값을 반환하도록 고치세요.",
  src:"total = 0\n\ndef count_up():\n    total = total + 1\n    return total",
  sol:"total = 0\n\ndef count_up():\n    global total\n    total = total + 1\n    return total",
  tests:[["count_up()","1"],["count_up()","2"],["count_up()","3"],["count_up()","4"]],
  edge:[["(count_up(), count_up())[1]","2"],["type(count_up())","int"]],
  ex:"🐛 원인: 함수 안에서 이름에 대입하면 파이썬은 그 이름을 지역 변수로 확정합니다. total = total + 1 의 오른쪽은 아직 값이 없는 지역 total 을 읽으므로 UnboundLocalError 가 납니다.\n🔧 해결: global 선언으로 모듈 변수를 가리키게 합니다.\n🛡 재발 방지: 전역 상태를 함수가 직접 고치는 구조 자체가 위험합니다. 가능하면 값을 인자로 받고 새 값을 반환하도록 바꾸세요." },

{ k:"딕셔너리의 in 은 키를 본다", fn:"has_owner",
  q:"팀 배정표에서 특정 사람이 어느 팀이든 담당자로 들어가 있는지 확인합니다. 지금은 항상 False 가 나옵니다.",
  src:"def has_owner(teams, person):\n    return person in teams",
  sol:"def has_owner(teams, person):\n    return person in teams.values()",
  tests:[["has_owner({'a':'kim','b':'lee'},'kim')","True"],["has_owner({'a':'kim'},'park')","False"],["has_owner({'x':'lee','y':'lee'},'lee')","True"],["has_owner({'a':'kim','b':'lee'},'lee')","True"]],
  edge:[["has_owner({},'kim')","False"],["has_owner({'kim':'lee'},'kim')","False"]],
  ex:"🐛 원인: 딕셔너리에 in 을 쓰면 키만 검사합니다. 담당자 이름은 값 쪽에 있으므로 항상 False 입니다.\n🔧 해결: .values() 로 값 목록을 검사합니다.\n🛡 재발 방지: 값으로 찾는 일이 잦다면 자료구조가 뒤집혀 있다는 신호입니다. 담당자→팀 역방향 인덱스를 함께 두는 것도 방법입니다." },

{ k:"이진 탐색 경계 off-by-one", fn:"lower_bound",
  q:"정렬된 배열에서 target 이상인 첫 위치를 반환해야 합니다. 배열 안에 있는 값은 잘 찾는데, 모든 값보다 큰 값을 넣으면 마지막 인덱스가 나옵니다(배열 길이가 나와야 합니다).",
  src:"def lower_bound(a, target):\n    lo, hi = 0, len(a) - 1\n    while lo < hi:\n        mid = (lo + hi) // 2\n        if a[mid] < target:\n            lo = mid + 1\n        else:\n            hi = mid\n    return lo",
  sol:"def lower_bound(a, target):\n    lo, hi = 0, len(a)\n    while lo < hi:\n        mid = (lo + hi) // 2\n        if a[mid] < target:\n            lo = mid + 1\n        else:\n            hi = mid\n    return lo",
  tests:[["lower_bound([1,3,5,7],9)","4"],["lower_bound([1,3,5,7],5)","2"],["lower_bound([1,3,5,7],4)","2"],["lower_bound([1,3,5,7],0)","0"]],
  edge:[["lower_bound([],1)","0"],["lower_bound([2,2,2],2)","0"]],
  ex:"🐛 원인: 탐색 구간을 [lo, hi] 로 잡고 hi 를 len(a)-1 로 두면 '모든 원소보다 크다' 는 답(len(a))을 표현할 자리가 없습니다. 그래서 마지막 인덱스로 잘립니다.\n🔧 해결: 구간을 [lo, hi) 반열린 구간으로 잡고 hi = len(a) 에서 시작합니다. 삽입 위치는 0부터 len(a) 까지 len(a)+1 가지이므로 이 표현이 맞습니다.\n🛡 재발 방지: 이진 탐색은 구간 표기를 먼저 고정하세요. [lo, hi) 로 통일하면 종료 조건 lo < hi, 축소 lo = mid+1 / hi = mid 가 자동으로 따라옵니다." },

{ k:"누적 변수 초기화 위치", fn:"row_sums",
  q:"2차원 리스트의 행별 합계를 구하는데, 결과가 계속 누적되어 뒤로 갈수록 커집니다.",
  src:"def row_sums(rows):\n    out = []\n    s = 0\n    for r in rows:\n        for v in r:\n            s += v\n        out.append(s)\n    return out",
  sol:"def row_sums(rows):\n    out = []\n    for r in rows:\n        s = 0\n        for v in r:\n            s += v\n        out.append(s)\n    return out",
  tests:[["row_sums([[1,2],[3,4]])","[3,7]"],["row_sums([[5],[5],[5]])","[5,5,5]"],["row_sums([[1,1,1],[2,2,2]])","[3,6]"],["row_sums([[0],[1],[2]])","[0,1,2]"]],
  edge:[["row_sums([])","[]"],["row_sums([[]])","[0]"]],
  ex:"🐛 원인: 누적 변수 s 를 바깥 루프 밖에서 한 번만 0 으로 두어 이전 행의 합이 그대로 남습니다.\n🔧 해결: 행마다 s 를 다시 0 으로 초기화합니다.\n🛡 재발 방지: 누적 변수는 '어느 단위로 다시 시작하는가' 를 기준으로 선언 위치를 정하세요. 행 단위 합계면 초기화도 행 안에 있어야 합니다." },

{ k:"zip 은 짧은 쪽에서 멈춘다", fn:"pair_up",
  q:"이름과 점수를 짝지어 딕셔너리로 만듭니다. 점수가 모자라면 그 사람이 결과에서 통째로 사라집니다. 점수가 없는 사람은 None 으로 채워 모두 남기도록 고치세요.",
  src:"def pair_up(names, scores):\n    return dict(zip(names, scores))",
  sol:"def pair_up(names, scores):\n    return {n: (scores[i] if i < len(scores) else None) for i, n in enumerate(names)}",
  tests:[["pair_up(['a','b'],[1])","{'a':1,'b':None}"],["pair_up(['a','b'],[1,2])","{'a':1,'b':2}"],["pair_up(['x','y','z'],[9])","{'x':9,'y':None,'z':None}"],["len(pair_up(['a','b','c'],[1,2]))","3"]],
  edge:[["pair_up([],[])","{}"],["pair_up(['solo'],[])","{'solo':None}"]],
  ex:"🐛 원인: zip 은 가장 짧은 입력에서 멈추고 아무 경고도 내지 않습니다. 점수가 하나 빠지면 그 사람은 결과에서 조용히 사라집니다.\n🔧 해결: 이름을 기준으로 돌면서 점수가 없으면 None 을 넣습니다. 길이가 같아야만 한다면 파이썬 3.10+ 의 zip(..., strict=True) 로 어긋남을 예외로 만들 수도 있습니다.\n🛡 재발 방지: 조용한 절삭은 가장 찾기 어려운 종류의 버그입니다. 두 시퀀스를 짝지을 때는 길이가 다를 때 무엇을 할지 코드에 못 박으세요." },

{ k:"remove는 첫 번째만 지운다", fn:"purge",
  q:"목록에서 특정 값을 모두 없애야 하는데 하나만 사라집니다. 원본은 건드리지 마세요.",
  src:"def purge(xs, v):\n    out = list(xs)\n    out.remove(v)\n    return out",
  sol:"def purge(xs, v):\n    return [x for x in xs if x != v]",
  tests:[["purge([1,2,1,3],1)","[2,3]"],["purge(['a','b','a'],'a')","['b']"],["purge([0,0,0],0)","[]"],["purge([1,2,3],2)","[1,3]"]],
  edge:[["purge([1,2],9)","[1,2]"],["purge([],1)","[]"]],
  ex:"🐛 원인: list.remove 는 처음 만나는 하나만 지우고, 값이 없으면 ValueError 까지 냅니다.\n🔧 해결: 조건에 맞지 않는 것만 남기는 컴프리헨션으로 한 번에 처리합니다.\n🛡 재발 방지: '모두 제거' 와 '하나 제거' 는 다른 연산입니다. remove 를 쓰기 전에 중복 가능성과 없을 때의 동작을 확인하세요." },

{ k:"빈 입력에서 터지는 평균", fn:"mean",
  q:"점수 평균을 구하는 함수입니다. 아직 아무도 응시하지 않은 과목에서 호출하면 ZeroDivisionError 로 페이지 전체가 죽습니다. 빈 목록이면 0.0 을 반환하도록 고치세요.",
  src:"def mean(xs):\n    return sum(xs) / len(xs)",
  sol:"def mean(xs):\n    if not xs:\n        return 0.0\n    return sum(xs) / len(xs)",
  tests:[["mean([])","0.0"],["mean([2,4])","3.0"],["mean([5])","5.0"],["mean([1,2,3,4])","2.5"]],
  edge:[["mean([0,0])","0.0"],["mean([-2,2])","0.0"]],
  ex:"🐛 원인: len(xs) 가 0이면 나눗셈에서 ZeroDivisionError 가 납니다. '데이터가 아직 없다' 는 정상적인 상태인데 예외로 처리돼 호출 스택 전체가 무너집니다.\n🔧 해결: 빈 입력을 먼저 걸러 0.0 을 반환합니다. 도메인상 '평균 없음' 이 맞다면 None 을 반환하고 호출부에서 표시를 다르게 하는 것도 방법입니다.\n🛡 재발 방지: 집계 함수는 빈 입력이 첫 번째 테스트 케이스여야 합니다. 서비스 초기·신규 사용자·필터 결과 0건에서 반드시 마주칩니다." },

{ k:"기본 인자는 정의 시점에 한 번 평가된다", fn:"append_id",
  q:"호출할 때마다 새 목록에 id 를 담아 돌려줘야 하는데, 두 번째 호출부터 이전 결과가 섞여 나옵니다.",
  src:"def append_id(x, bucket=[]):\n    bucket.append(x)\n    return bucket",
  sol:"def append_id(x, bucket=None):\n    if bucket is None:\n        bucket = []\n    bucket.append(x)\n    return bucket",
  tests:[["append_id(1)","[1]"],["append_id(2)","[2]"],["append_id(3)","[3]"],["append_id(1,[9])","[9,1]"]],
  edge:[["append_id('a')","['a']"],["len(append_id(0))","1"]],
  ex:"🐛 원인: 기본값 [] 는 def 를 실행할 때 딱 한 번 만들어져 함수 객체에 붙습니다. 모든 호출이 같은 리스트를 나눠 쓰게 됩니다.\n🔧 해결: 기본값을 None 으로 두고 함수 안에서 새 리스트를 만듭니다.\n🛡 재발 방지: 기본 인자에 리스트·딕셔너리·집합 같은 가변 객체를 두지 마세요. None 센티넬이 표준 패턴입니다." },

{ k:"늦은 바인딩 클로저", fn:"make_adders",
  q:"0,1,2 를 각각 더하는 함수 3개를 만들어야 하는데, 어느 것을 호출해도 2를 더합니다.",
  src:"def make_adders():\n    fns = []\n    for i in range(3):\n        fns.append(lambda x: x + i)\n    return fns",
  sol:"def make_adders():\n    fns = []\n    for i in range(3):\n        fns.append(lambda x, i=i: x + i)\n    return fns",
  tests:[["[f(10) for f in make_adders()]","[10,11,12]"],["make_adders()[0](0)","0"],["make_adders()[2](5)","7"],["[f(0) for f in make_adders()]","[0,1,2]"]],
  edge:[["len(make_adders())","3"],["make_adders()[1](-1)","0"]],
  ex:"🐛 원인: 람다는 i 의 '값' 이 아니라 '변수' 를 캡처합니다. 호출 시점에 i 를 읽으므로 루프가 끝난 뒤의 2 를 씁니다.\n🔧 해결: 기본 인자 i=i 로 만들 때의 값을 즉시 고정합니다. functools.partial 도 같은 효과입니다.\n🛡 재발 방지: 반복문 안에서 함수를 만들 때는 캡처가 값인지 변수인지 항상 확인하세요." },

{ k:"집합은 순서를 잃는다", fn:"dedupe",
  q:"중복을 없애되 처음 나온 순서를 유지해야 합니다. 지금은 순서가 뒤죽박죽입니다.",
  src:"def dedupe(xs):\n    return sorted(set(xs))",
  sol:"def dedupe(xs):\n    seen = set()\n    out = []\n    for x in xs:\n        if x not in seen:\n            seen.add(x)\n            out.append(x)\n    return out",
  tests:[["dedupe([3,1,3,2,1])","[3,1,2]"],["dedupe(['b','a','b'])","['b','a']"],["dedupe([5,4,3])","[5,4,3]"],["dedupe([1,1,1,2])","[1,2]"]],
  edge:[["dedupe([])","[]"],["dedupe([2])","[2]"]],
  ex:"🐛 원인: set 은 순서를 보장하지 않고, sorted 를 씌우면 '입력 순서' 가 아니라 '값 순서' 가 됩니다.\n🔧 해결: 본 적 있는 값을 집합으로 기억하면서 리스트에는 처음 순서대로 담습니다. list(dict.fromkeys(xs)) 도 같은 결과를 줍니다.\n🛡 재발 방지: 중복 제거를 요구받으면 '순서를 지켜야 하는가' 를 먼저 물으세요. 답에 따라 자료구조가 달라집니다." },

{ k:"enumerate 의 시작값", fn:"numbered",
  q:"항목마다 1부터 시작하는 번호를 붙여 '1. 사과' 형태로 만듭니다. 지금은 0번부터 시작합니다.",
  src:"def numbered(items):\n    return ['%d. %s' % (i, x) for i, x in enumerate(items)]",
  sol:"def numbered(items):\n    return ['%d. %s' % (i, x) for i, x in enumerate(items, 1)]",
  tests:[["numbered(['a'])","['1. a']"],["numbered(['a','b'])","['1. a','2. b']"],["numbered(['x','y','z'])","['1. x','2. y','3. z']"],["numbered(['q','w'])[1]","'2. w'"]],
  edge:[["numbered([])","[]"],["numbered(['only'])[0]","'1. only'"]],
  ex:"🐛 원인: enumerate 의 기본 시작값은 0 입니다. 사람이 읽는 번호는 보통 1부터입니다.\n🔧 해결: enumerate(items, 1) 로 시작값을 넘깁니다.\n🛡 재발 방지: 인덱스(0부터)와 순번(1부터)을 구분해서 부르세요. 이름만 나눠도 실수가 줄어듭니다." },

{ k:"is 로 값을 비교", fn:"is_limit",
  q:"요청 수가 상한 1000에 정확히 도달했는지 확인합니다. 테스트에서는 통과하는데, 실제 요청 카운터를 넣으면 도달해도 False 가 나옵니다.",
  src:"def is_limit(n):\n    return n is 1000",
  sol:"def is_limit(n):\n    return n == 1000",
  tests:[["is_limit(int('1000'))","True"],["is_limit(sum([500,500]))","True"],["is_limit(999)","False"],["is_limit(1001)","False"]],
  edge:[["is_limit(len([0]*1000))","True"],["is_limit(0)","False"]],
  ex:"🐛 원인: is 는 '같은 객체인가' 를 묻습니다. CPython 은 -5~256 의 작은 정수만 캐시하므로 1000 은 계산해서 만들 때마다 다른 객체입니다. 소스에 리터럴 1000 을 직접 쓴 테스트만 우연히 통과합니다.\n🔧 해결: 값이 같은지 물으려면 == 를 씁니다.\n🛡 재발 방지: is 는 None·True·False 같은 싱글턴 비교에만 쓰세요. 숫자·문자열에 쓰면 인터프리터 구현 세부에 기대는 코드가 됩니다." },

{ k:"슬라이스 복사 없이 정렬", fn:"sorted_view",
  q:"원본을 유지한 채 정렬된 사본을 돌려줘야 하는데, 호출하고 나면 원본까지 정렬되어 있습니다.",
  src:"def sorted_view(xs):\n    xs.sort()\n    return xs",
  sol:"def sorted_view(xs):\n    return sorted(xs)",
  tests:[["sorted_view([3,1,2])","[1,2,3]"],
         ["(lambda a: (sorted_view(a), a)[1])([3,1,2])","[3,1,2]"],
         ["sorted_view(['b','a'])","['a','b']"],
         ["(lambda a: (sorted_view(a), a[0])[1])([9,8])","9"]],
  edge:[["sorted_view([])","[]"],["sorted_view([1])","[1]"]],
  ex:"🐛 원인: list.sort() 는 인자로 받은 원본을 제자리에서 바꿉니다. 호출자가 넘긴 리스트가 함수 밖에서도 정렬돼 버립니다.\n🔧 해결: sorted 는 새 리스트를 만들어 반환하므로 원본이 그대로 남습니다.\n🛡 재발 방지: 인자로 받은 가변 객체를 함수가 바꾸면 '숨은 부작용' 입니다. 바꿔야 한다면 함수 이름과 문서에 분명히 드러내세요." },

{ k:"딕셔너리 순회 중 변경", fn:"drop_empty",
  q:"값이 비어 있는 항목을 지우는 함수인데 RuntimeError 가 납니다. 원본은 건드리지 말고 새 딕셔너리를 반환하세요.",
  src:"def drop_empty(d):\n    out = dict(d)\n    for k in out:\n        if not out[k]:\n            del out[k]\n    return out",
  sol:"def drop_empty(d):\n    return {k: v for k, v in d.items() if v}",
  tests:[["drop_empty({'a':1,'b':0})","{'a':1}"],["drop_empty({'a':'','b':'x'})","{'b':'x'}"],["drop_empty({'a':[],'b':[1]})","{'b':[1]}"],["drop_empty({'a':1,'b':2})","{'a':1,'b':2}"]],
  edge:[["drop_empty({})","{}"],["drop_empty({'a':None})","{}"]],
  ex:"🐛 원인: 순회 중에 딕셔너리 크기를 바꾸면 파이썬이 RuntimeError 를 냅니다. 반복자가 무엇을 가리켜야 할지 알 수 없기 때문입니다.\n🔧 해결: 지우는 대신 남길 항목만 골라 새 딕셔너리를 만듭니다.\n🛡 재발 방지: 순회 대상과 수정 대상은 반드시 분리하세요. 굳이 제자리에서 지워야 한다면 list(d.keys()) 로 키 스냅샷을 먼저 뜹니다." },

{ k:"조건 연산자 우선순위", fn:"in_range",
  q:"값이 lo 이상 hi 이하인지 판정합니다. lo=0, hi=10 에 -5 를 넣으면 True 가 나옵니다.",
  src:"def in_range(v, lo, hi):\n    return lo <= v or v <= hi",
  sol:"def in_range(v, lo, hi):\n    return lo <= v <= hi",
  tests:[["in_range(5,0,10)","True"],["in_range(-5,0,10)","False"],["in_range(11,0,10)","False"],["in_range(0,0,10)","True"]],
  edge:[["in_range(10,0,10)","True"],["in_range(3,5,1)","False"]],
  ex:"🐛 원인: or 는 둘 중 하나만 참이어도 참입니다. -5 는 v <= hi 를 만족하므로 전체가 참이 됩니다.\n🔧 해결: 두 조건이 모두 참이어야 하므로 and 를, 파이썬에서는 lo <= v <= hi 연쇄 비교를 씁니다.\n🛡 재발 방지: '범위 안' 은 항상 두 조건의 교집합입니다. and/or 를 쓸 때는 경계값 두 개로 반드시 확인하세요." },

{ k:"문자열 누적을 대입하지 않음", fn:"shout",
  q:"단어들을 대문자로 바꿔 '-' 로 이어붙입니다. 결과가 항상 빈 문자열입니다.",
  src:"def shout(words):\n    s = ''\n    for w in words:\n        s + w.upper() + '-'\n    return s[:-1]",
  sol:"def shout(words):\n    return '-'.join(w.upper() for w in words)",
  tests:[["shout(['a','b'])","'A-B'"],["shout(['hi'])","'HI'"],["shout(['x','y','z'])","'X-Y-Z'"],["shout(['ab','cd'])","'AB-CD'"]],
  edge:[["shout([])","''"],["shout(['a','','b'])","'A--B'"]],
  ex:"🐛 원인: 문자열은 불변이라 s + ... 는 새 문자열을 만들 뿐 s 를 바꾸지 않습니다. 대입이 없으니 결과가 버려집니다.\n🔧 해결: join 으로 한 번에 이어붙입니다. 구분자 처리도 자동이라 s[:-1] 같은 잔재주가 필요 없습니다.\n🛡 재발 방지: 반환값을 쓰지 않는 식은 대부분 버그입니다. 문자열 이어붙이기는 join 이 기본이라고 외워 두세요." },

{ k:"any 와 all 의 빈 입력", fn:"all_passed",
  q:"모든 검사가 통과했는지 확인합니다. 검사 목록이 비어 있으면 '통과할 검사가 없다' 는 뜻이므로 False 여야 하는데 True 가 나옵니다.",
  src:"def all_passed(results):\n    return all(results)",
  sol:"def all_passed(results):\n    return len(results) > 0 and all(results)",
  tests:[["all_passed([True,True])","True"],["all_passed([True,False])","False"],["all_passed([])","False"],["all_passed([False])","False"]],
  edge:[["all_passed([1,1,1])","True"],["all_passed([1,0])","False"]],
  ex:"🐛 원인: all([]) 은 정의상 True 입니다(반증이 없으므로). 검사가 하나도 돌지 않았는데 '전부 통과' 로 보고됩니다.\n🔧 해결: 빈 입력을 명시적으로 거부합니다.\n🛡 재발 방지: 품질 게이트에서 '검사 0건 = 통과' 는 가장 위험한 기본값입니다. CI 에서도 테스트 수집이 0건이면 실패로 처리하세요." },
];
