/* 모델 평가 디버깅 12 — 점수는 나오는데 비교를 망치는 코드를 고친다.
   전부 결정적이고 순수 JS 다. 검증:  node ver_dbgjs.cjs ./dbg_mleval.cjs */
module.exports = [

{ track:"mleval", cat:"debug", k:"FPR 의 분모가 틀렸다",
  q:"혼동행렬에서 <code>[TPR, FPR]</code> 을 소수 넷째 자리까지 구합니다. TPR 은 실제 양성 중 맞힌 비율, FPR 은 <b>실제 음성 중</b> 잘못 양성이라 한 비율입니다. 지금 ROC 곡선의 모양이 이상합니다.",
  src:"function tprFpr(tp, fn, fp, tn) {\n  const r = x => Math.round(x * 10000) / 10000;\n  return [r(tp / (tp + fn)), r(fp / (fp + fn))];\n}",
  sol:"function tprFpr(tp, fn, fp, tn) {\n  const pos = tp + fn, neg = fp + tn;\n  if (!pos || !neg) return null;\n  const r = x => Math.round(x * 10000) / 10000;\n  return [r(tp / pos), r(fp / neg)];\n}",
  tests:[["tprFpr(8, 2, 1, 9)","[0.8,0.1]"],
         ["tprFpr(5, 5, 5, 5)","[0.5,0.5]"],
         ["tprFpr(10, 0, 0, 10)","[1,0]"],
         ["tprFpr(0, 10, 10, 0)","[0,1]"]],
  edge:[["tprFpr(1, 0, 0, 0) === null","true"],
        ["tprFpr(2, 2, 1, 3)","[0.5,0.25]"]],
  ex:"🐛 원인: FPR 의 분모는 <b>실제 음성의 수</b>(<code>fp + tn</code>)인데 <code>fp + fn</code> 을 썼습니다. 두 값은 완전히 다른 묶음을 세는데, 균형 잡힌 자료에서는 우연히 비슷해 눈에 잘 안 띕니다. ROC 곡선이 대각선 아래로 처지거나 계단이 뒤집혀 보이는 것이 증상입니다.\n🔧 해결: 분모를 <b>실제 라벨 기준</b>으로 잡습니다 — TPR 은 실제 양성, FPR 은 실제 음성. 한쪽 클래스가 없으면 정의되지 않으므로 거절합니다.\n🛡 재발 방지: 혼동행렬 지표는 '<b>무엇으로 나누는가</b>' 가 이름의 절반입니다 — 정밀도는 예측 양성으로, 재현율(TPR)은 실제 양성으로. 표를 그려 행·열 합을 적어 두고 코드와 대조하면 이 실수가 즉시 드러납니다." },

{ track:"mleval", cat:"debug", k:"AUC 를 정렬 없이 사다리꼴로 잰다",
  q:"<code>[fpr, tpr]</code> 점들로 <b>사다리꼴 적분</b> AUC 를 소수 넷째 자리까지 구합니다. 점의 순서는 보장되지 않습니다. 지금은 문턱을 훑는 순서가 바뀌면 AUC 가 <b>음수</b>로 나옵니다.",
  src:"function aucOf(points) {\n  let a = 0;\n  for (let i = 1; i < points.length; i += 1) {\n    const [x0, y0] = points[i - 1], [x1, y1] = points[i];\n    a += (x1 - x0) * (y0 + y1) / 2;\n  }\n  return Math.round(a * 10000) / 10000;\n}",
  sol:"function aucOf(points) {\n  const ps = points.slice().sort((p, q) => p[0] - q[0] || p[1] - q[1]);\n  let a = 0;\n  for (let i = 1; i < ps.length; i += 1) {\n    const [x0, y0] = ps[i - 1], [x1, y1] = ps[i];\n    a += (x1 - x0) * (y0 + y1) / 2;\n  }\n  return Math.round(a * 10000) / 10000;\n}",
  tests:[["aucOf([[0,0],[1,1]])","0.5"],
         ["aucOf([[1,1],[0,0]])","0.5"],
         ["aucOf([[0,0],[0,1],[1,1]])","1"],
         ["aucOf([[1,1],[0,1],[0,0]])","1"]],
  edge:[["aucOf([[0,0]])","0"],
        ["aucOf([[0,0],[0.5,0.8],[1,1]])","0.65"]],
  ex:"🐛 원인: 사다리꼴 적분은 <b>x 가 오름차순</b>이라는 전제 위에 섭니다. 점이 거꾸로 오면 <code>x1 - x0</code> 이 음수라 넓이가 음수로 쌓입니다. 문턱을 내림차순으로 훑으면 정확히 이 순서가 나옵니다.\n🔧 해결: <b>fpr 기준으로 정렬</b>한 뒤 적분합니다. 같은 fpr 이 여러 개면 tpr 로 2차 정렬해야 수직 구간이 올바르게 처리됩니다.\n🛡 재발 방지: 적분·누적합·구간 계산은 정렬을 전제로 합니다. 그 전제를 <b>함수 안에서 보장</b>하는 편이, 호출자마다 기억하기를 바라는 것보다 안전합니다. 그리고 AUC 는 0.5 가 무작위 기준선이므로 <b>0.5 미만이면 부호나 라벨이 뒤집혔는지</b> 먼저 의심하세요." },

{ track:"mleval", cat:"debug", k:"보정 구간이 확률 1 에서 넘친다",
  q:"확률 <code>p</code> 가 들어갈 <b>보정 구간</b> 번호(0부터 <code>bins-1</code>)를 구합니다. <code>p = 1</code> 은 <b>마지막 구간</b>에 들어갑니다. 지금은 확신에 찬 예측에서 배열 밖을 건드려 집계가 <code>undefined</code> 가 됩니다.",
  src:"function binOf(p, bins) {\n  return Math.floor(p * bins);\n}",
  sol:"function binOf(p, bins) {\n  if (!(bins >= 1)) return null;\n  const q = Math.min(1, Math.max(0, p));\n  return Math.min(bins - 1, Math.floor(q * bins));\n}",
  tests:[["binOf(0, 10)","0"],
         ["binOf(0.55, 10)","5"],
         ["binOf(1, 10)","9"],
         ["binOf(0.999, 10)","9"]],
  edge:[["binOf(1.5, 10)","9"],
        ["binOf(-0.1, 10)","0"]],
  ex:"🐛 원인: <code>floor(1 × 10)</code> 은 <b>10</b> 인데 구간 번호는 0~9 입니다. 배열 밖을 쓰면 자바스크립트에서는 오류가 아니라 <code>undefined</code> 가 되어, 보정 곡선의 마지막 점만 조용히 비어 버립니다.\n🔧 해결: 위쪽을 <code>bins - 1</code> 로 <b>자르고</b>, 들어온 값이 범위를 벗어날 수 있다는 전제로 아래쪽도 함께 막습니다.\n🛡 재발 방지: 연속값을 <b>구간으로 나누는</b> 코드는 언제나 위쪽 끝이 문제입니다 — 히스토그램, 점수 등급, 나이대. '마지막 구간은 닫혀 있다' 는 규칙을 코드와 문서에 함께 적으세요. 그리고 반올림 오차로 <code>p</code> 가 1 을 아주 조금 넘는 경우도 실제로 생깁니다." },

{ track:"mleval", cat:"debug", k:"맥니마 검정에 일치 쌍을 넣는다",
  q:"두 모델을 같은 표본에서 견주는 <b>맥니마 검정</b> 통계량을 구합니다. 식은 <code>(|b − c| − 1)² / (b + c)</code> 이고 <code>b</code>·<code>c</code> 는 <b>서로 엇갈린 쌍</b>의 수입니다. 지금 값이 실제보다 작아 유의한 차이를 놓칩니다.",
  src:"function mcNemar(b, c, n) {\n  return Math.round((b - c) ** 2 / n * 10000) / 10000;\n}",
  sol:"function mcNemar(b, c, n) {\n  const d = b + c;\n  if (!d) return null;\n  return Math.round((Math.abs(b - c) - 1) ** 2 / d * 10000) / 10000;\n}",
  tests:[["mcNemar(10, 2, 100)","4.0833"],
         ["mcNemar(5, 5, 100)","0.1"],
         ["mcNemar(20, 5, 100)","7.84"],
         ["mcNemar(3, 1, 50)","0.25"]],
  edge:[["mcNemar(0, 0, 10) === null","true"],
        ["mcNemar(1, 0, 10)","0"]],
  ex:"🐛 원인: 맥니마 검정은 <b>두 모델의 답이 엇갈린 쌍만</b> 봅니다. 둘 다 맞히거나 둘 다 틀린 쌍은 정보가 없어 분모에 들어가지 않는데, 전체 표본 수로 나누면 통계량이 크게 작아져 <b>실제로 있는 차이를 못 봅니다</b>. 연속성 보정(<code>−1</code>)도 빠져 있습니다.\n🔧 해결: 분모를 <code>b + c</code> 로 바꾸고 보정을 넣습니다. 엇갈린 쌍이 하나도 없으면 두 모델이 완전히 같으므로 판정할 것이 없습니다.\n🛡 재발 방지: <b>짝지어진 비교</b>는 짝의 차이만 봐야 검정력이 살아납니다 — 같은 표본에 두 모델을 돌렸다면 독립 표본 검정을 쓰면 안 됩니다. 어떤 설계인지 먼저 정하고 그에 맞는 검정을 고르세요." },

{ track:"mleval", cat:"debug", k:"부트스트랩 구간의 자리가 밀린다",
  q:"정렬된 부트스트랩 표본에서 <b>백분위 신뢰구간</b> <code>[lo, hi]</code> 를 구합니다. 양쪽 꼬리 각각 <code>alpha/2</code> 씩 자릅니다. 지금은 표본이 적을 때 <code>undefined</code> 가 섞여 구간이 깨집니다.",
  src:"function bootCI(sorted, alpha) {\n  const n = sorted.length;\n  return [sorted[Math.round(alpha / 2 * n)], sorted[Math.round((1 - alpha / 2) * n)]];\n}",
  sol:"function bootCI(sorted, alpha) {\n  const n = sorted.length;\n  if (!n) return null;\n  const at = q => sorted[Math.min(n - 1, Math.max(0, Math.floor(q * n)))];\n  return [at(alpha / 2), at(1 - alpha / 2)];\n}",
  tests:[["bootCI([1,2,3,4,5,6,7,8,9,10], 0.2)","[2,10]"],
         ["bootCI([1,2,3,4], 0.5)","[2,4]"],
         ["bootCI([5], 0.05)","[5,5]"],
         ["bootCI([1,2,3,4,5,6,7,8,9,10], 0.05)","[1,10]"]],
  edge:[["bootCI([], 0.05) === null","true"],
        ["bootCI([1,2], 0.5)","[1,2]"]],
  ex:"🐛 원인: <code>(1 - alpha/2) × n</code> 은 표본이 적으면 <b><code>n</code> 그 자체</b>가 되어 배열 밖을 가리킵니다. 그리고 <code>round</code> 는 자리를 위아래로 흔들어, 같은 자료에서 실행마다 다른 구간이 나올 수 있습니다.\n🔧 해결: <b>내림</b>으로 자리를 정하고 <code>[0, n-1]</code> 로 자릅니다. 부트스트랩 표본이 적을 때 구간이 전체 범위로 넓어지는 것은 <b>정직한 결과</b>입니다.\n🛡 재발 방지: 백분위 구간은 표본 수가 적으면 애초에 믿을 수 없습니다 — 95% 구간을 보려면 보통 1,000회 이상 재표본해야 합니다. 그리고 배열 자리를 계산해 접근하는 코드는 <b>항상 범위로 자르는</b> 헬퍼를 하나 두세요." },

{ track:"mleval", cat:"debug", k:"top-k 판정이 순위 기준을 헷갈린다",
  q:"정답의 <b>순위</b>(1등이 1)가 상위 <code>k</code> 안에 들었는지 봅니다. 지금 top-1 정확도가 항상 0 으로 나옵니다.",
  src:"function topKHit(rank, k) {\n  return rank < k;\n}",
  sol:"function topKHit(rank, k) {\n  return rank >= 1 && rank <= k;\n}",
  tests:[["topKHit(1, 1)","true"],
         ["topKHit(2, 1)","false"],
         ["topKHit(5, 5)","true"],
         ["topKHit(6, 5)","false"]],
  edge:[["topKHit(1, 0)","false"],
        ["topKHit(0, 3)","false"]],
  ex:"🐛 원인: 순위는 <b>1 부터</b> 세는데 <code>&lt;</code> 로 견주면 경계가 한 칸 안쪽으로 들어갑니다. top-1 은 <code>rank &lt; 1</code> 이 되어 <b>영원히 거짓</b>이고, top-5 는 사실상 top-4 가 됩니다. 두 지표가 나란히 보고되면 top-1 만 0 이라 이상함이 드러납니다.\n🔧 해결: <code>rank &lt;= k</code> 입니다. 순위가 0 이나 음수로 들어오는 것은 상류 버그이므로 함께 막습니다.\n🛡 재발 방지: 1 부터 세는 값(순위·페이지·행 번호)과 0 부터 세는 값(배열 자리)이 한 함수 안에서 섞이면 반드시 어딘가 어긋납니다. 이름에 드러내거나(<code>rank1</code>·<code>idx0</code>) 경계에서 <b>가장 작은 값</b>을 첫 테스트로 두세요." },

{ track:"mleval", cat:"debug", k:"MAPE 가 실제값 0 에서 폭발한다",
  q:"<b>평균 절대 백분율 오차</b>(%)를 소수 넷째 자리까지 구합니다. 실제값이 0 인 항목은 백분율이 정의되지 않으므로 <b>빼고</b> 계산하고, 남는 항목이 없으면 <code>null</code> 입니다. 지금은 값이 <code>Infinity</code> 로 나옵니다.",
  src:"function mape(ys, ps) {\n  const n = ys.length;\n  let s = 0;\n  for (let i = 0; i < n; i += 1) s += Math.abs((ys[i] - ps[i]) / ys[i]);\n  return Math.round(s / n * 1000000) / 10000;\n}",
  sol:"function mape(ys, ps) {\n  let s = 0, m = 0;\n  for (let i = 0; i < ys.length; i += 1) {\n    if (ys[i] === 0) continue;\n    s += Math.abs((ys[i] - ps[i]) / ys[i]);\n    m += 1;\n  }\n  if (!m) return null;\n  return Math.round(s / m * 1000000) / 10000;\n}",
  tests:[["mape([100], [110])","10"],
         ["mape([100, 0], [110, 5])","10"],
         ["mape([0], [5]) === null","true"],
         ["mape([50, 100], [45, 90])","10"]],
  edge:[["mape([], []) === null","true"],
        ["mape([10, 0, 20], [11, 3, 18])","10"]],
  ex:"🐛 원인: MAPE 의 분모는 <b>실제값</b>이라 0 이 하나만 있어도 전체가 <code>Infinity</code> 가 됩니다. 수요 예측·트래픽 예측에는 0 이 흔하고(휴일, 신규 상품), 그때 지표가 통째로 무의미해집니다.\n🔧 해결: 0 인 항목을 <b>빼고</b> 남은 개수로 나눕니다. 몇 개를 뺐는지도 함께 보고해야 사람이 지표를 믿을 수 있습니다.\n🛡 재발 방지: MAPE 는 0 근처에서 불안정하고 <b>과소 예측에 관대</b>한 비대칭 지표입니다. 0 이 많은 자료에는 sMAPE·MASE·절대 오차 같은 대안이 낫습니다. 지표를 고르는 일이 모델을 고르는 일보다 결과를 더 크게 좌우할 때가 많습니다." },

{ track:"mleval", cat:"debug", k:"결정계수의 기준선이 0 이다",
  q:"결정계수 <code>R²</code> 를 소수 넷째 자리까지 구합니다. 기준선은 <b>실제값의 평균</b>으로 예측한 모델입니다. 지금은 값이 언제나 1 에 가깝게 나와 모델이 좋아 보입니다.",
  src:"function r2Of(ys, ps) {\n  const ssRes = ys.reduce((s, y, i) => s + (y - ps[i]) ** 2, 0);\n  const ssTot = ys.reduce((s, y) => s + y ** 2, 0);\n  return Math.round((1 - ssRes / ssTot) * 10000) / 10000;\n}",
  sol:"function r2Of(ys, ps) {\n  const n = ys.length;\n  if (n < 2) return null;\n  const m = ys.reduce((s, y) => s + y, 0) / n;\n  const ssRes = ys.reduce((s, y, i) => s + (y - ps[i]) ** 2, 0);\n  const ssTot = ys.reduce((s, y) => s + (y - m) ** 2, 0);\n  if (ssTot === 0) return null;\n  return Math.round((1 - ssRes / ssTot) * 10000) / 10000;\n}",
  tests:[["r2Of([1,2,3], [1,2,3])","1"],
         ["r2Of([100,101,102], [101,101,101])","0"],
         ["r2Of([1,2,3], [2,2,2])","0"],
         ["r2Of([0,10], [0,10])","1"]],
  edge:[["r2Of([5,5], [5,5]) === null","true"],
        ["r2Of([1], [1]) === null","true"]],
  ex:"🐛 원인: 기준선을 <b>0 으로 예측하는 모델</b>로 잡았습니다. 값이 100 근처인 자료라면 0 예측은 형편없으므로, 어떤 모델이든 그것보다는 나아 R² 가 1 에 가깝게 나옵니다. 정말 알고 싶은 것은 '<b>평균보다 나은가</b>' 입니다.\n🔧 해결: <code>ssTot</code> 를 <b>평균 둘레의 제곱합</b>으로 바꿉니다. 평균으로 예측한 모델의 R² 가 정확히 0 이 되는지로 검산하세요.\n🛡 재발 방지: 상대 지표는 <b>기준선이 무엇인가</b>가 전부입니다. R² 는 음수도 될 수 있고(평균보다 나쁨), 실제값이 모두 같으면 정의되지 않습니다. 절대 오차와 함께 보고해야 '좋다' 는 말의 크기를 알 수 있습니다." },

{ track:"mleval", cat:"debug", k:"비용 최적 문턱에서 최댓값을 고른다",
  q:"문턱별 오분류 비용 목록에서 <b>비용이 가장 작은</b> 문턱을 고릅니다. 동점이면 <b>작은 문턱</b>입니다. 지금 배포된 문턱이 가장 나쁜 값입니다.",
  src:"function bestThreshold(rows) {\n  if (!rows.length) return null;\n  let best = rows[0];\n  for (const r of rows) if (r.cost > best.cost) best = r;\n  return best.thr;\n}",
  sol:"function bestThreshold(rows) {\n  if (!rows.length) return null;\n  let best = rows[0];\n  for (const r of rows) {\n    if (r.cost < best.cost || (r.cost === best.cost && r.thr < best.thr)) best = r;\n  }\n  return best.thr;\n}",
  tests:[["bestThreshold([{thr:0.3, cost:10}, {thr:0.5, cost:4}, {thr:0.7, cost:9}])","0.5"],
         ["bestThreshold([{thr:0.2, cost:5}, {thr:0.8, cost:5}])","0.2"],
         ["bestThreshold([{thr:0.9, cost:1}])","0.9"],
         ["bestThreshold([{thr:0.1, cost:7}, {thr:0.4, cost:3}])","0.4"]],
  edge:[["bestThreshold([]) === null","true"],
        ["bestThreshold([{thr:0.6, cost:2}, {thr:0.2, cost:2}])","0.2"]],
  ex:"🐛 원인: 부등호 방향이 뒤집혀 <b>가장 비싼</b> 문턱을 고릅니다. 비용이 목적함수일 때는 최소화, 점수가 목적함수일 때는 최대화라 두 코드가 한 글자만 다릅니다 — 리뷰에서도 잘 안 보입니다.\n🔧 해결: <code>&lt;</code> 로 바꾸고 동점 규칙을 더합니다. 동점 기준이 없으면 입력 순서에 따라 답이 달라져 배포마다 문턱이 바뀝니다.\n🛡 재발 방지: 목적함수를 다루는 코드는 <b>방향을 이름에 드러내세요</b>(<code>minCost</code>·<code>maxScore</code>). 그리고 최적값이 '가장자리' 에서 나오면 대개 탐색 범위가 좁은 것이니, 문턱 격자의 양 끝을 함께 확인하세요." },

{ track:"mleval", cat:"debug", k:"nDCG 의 로그 자리가 하나 어긋난다",
  q:"상위 <code>k</code> 개의 관련도로 <b>DCG</b> 를 소수 넷째 자리까지 구합니다. <code>i</code> 번째(0부터) 항목의 할인은 <code>log2(i + 2)</code> 입니다. 지금은 첫 항목에서 <code>Infinity</code> 가 나옵니다.",
  src:"function dcgAt(rels, k) {\n  let s = 0;\n  for (let i = 0; i < Math.min(k, rels.length); i += 1) {\n    s += rels[i] / Math.log2(i + 1);\n  }\n  return Math.round(s * 10000) / 10000;\n}",
  sol:"function dcgAt(rels, k) {\n  let s = 0;\n  for (let i = 0; i < Math.min(k, rels.length); i += 1) {\n    s += rels[i] / Math.log2(i + 2);\n  }\n  return Math.round(s * 10000) / 10000;\n}",
  tests:[["dcgAt([1], 1)","1"],
         ["dcgAt([1,1], 2)","1.6309"],
         ["dcgAt([3,2,1], 3)","4.7619"],
         ["dcgAt([0,0,5], 3)","2.5"]],
  edge:[["dcgAt([], 3)","0"],
        ["dcgAt([2,2], 1)","2"]],
  ex:"🐛 원인: <code>log2(1)</code> 은 <b>0</b> 이라 첫 항목에서 0 으로 나눕니다. 관련도가 0 이면 <code>0/0 = NaN</code>, 아니면 <code>Infinity</code> 가 되어 순위 지표 전체가 무의미해집니다. 첫 항목의 할인은 1 이어야 하므로 <code>log2(i + 2)</code> 가 맞습니다.\n🔧 해결: 자리 인덱스를 0 부터 셀 때는 <code>i + 2</code>, 1 부터 셀 때는 <code>i + 1</code> 입니다. 첫 항목의 할인이 정확히 1 인지로 검산하세요 — 위 첫 테스트가 그 확인입니다.\n🛡 재발 방지: 순위 지표는 <b>1 부터 세는 관례</b>로 정의된 식을 0 부터 세는 코드로 옮기면서 어긋나기 쉽습니다. 논문 식을 옮길 때는 <b>첫 항</b>을 손으로 계산해 테스트에 박아 두세요. 그리고 DCG 는 이상적 순서의 DCG 로 나눠 <b>nDCG</b> 로 만들어야 질의끼리 비교할 수 있습니다." },

{ track:"mleval", cat:"debug", k:"매크로 F1 을 표본 수로 가중한다",
  q:"클래스별 F1 과 표본 수로 <b>매크로 F1</b>(단순 평균)을 소수 넷째 자리까지 구합니다. 지금 값이 소수 클래스를 무시해, 불균형에서 성능이 좋아 보입니다.",
  src:"function macroF1(rows) {\n  if (!rows.length) return null;\n  const n = rows.reduce((s, r) => s + r.n, 0);\n  if (!n) return null;\n  return Math.round(rows.reduce((s, r) => s + r.f1 * r.n, 0) / n * 10000) / 10000;\n}",
  sol:"function macroF1(rows) {\n  if (!rows.length) return null;\n  return Math.round(rows.reduce((s, r) => s + r.f1, 0) / rows.length * 10000) / 10000;\n}",
  tests:[["macroF1([{f1:0.9, n:990}, {f1:0.1, n:10}])","0.5"],
         ["macroF1([{f1:0.5, n:1}, {f1:0.5, n:100}])","0.5"],
         ["macroF1([{f1:1, n:1}])","1"],
         ["macroF1([{f1:0.8, n:50}, {f1:0.4, n:50}])","0.6"]],
  edge:[["macroF1([]) === null","true"],
        ["macroF1([{f1:0, n:5}, {f1:1, n:5}])","0.5"]],
  ex:"🐛 원인: 표본 수로 가중하면 그것은 <b>가중 평균 F1</b> 이지 매크로가 아닙니다. 매크로의 존재 이유가 '<b>모든 클래스를 같은 무게로</b>' 보는 것이라, 가중하면 다수 클래스의 점수가 전체를 덮어 소수 클래스 실패가 보이지 않습니다.\n🔧 해결: 클래스 수로 <b>단순 평균</b>합니다. 위 첫 테스트가 정확히 그 차이를 드러냅니다 — 가중은 0.892, 매크로는 0.5.\n🛡 재발 방지: 마이크로·매크로·가중 평균은 <b>서로 다른 질문에 답합니다</b> — 마이크로는 '전체 예측 중', 매크로는 '클래스마다 공평하게', 가중은 '실제 분포대로'. 보고서에는 어느 것인지 반드시 이름을 붙이고, 가능하면 <b>세 개를 함께</b> 적으세요." },

{ track:"mleval", cat:"debug", k:"짝지은 비교에 표준편차를 그대로 쓴다",
  q:"짝지은 차이 목록으로 <b>t 통계량</b>을 소수 넷째 자리까지 구합니다. 식은 <code>평균 / (표본표준편차 / √n)</code> 입니다. 지금은 표본을 늘려도 통계량이 커지지 않아 차이를 계속 놓칩니다.",
  src:"function pairedT(diffs) {\n  const n = diffs.length;\n  if (n < 2) return null;\n  const m = diffs.reduce((s, d) => s + d, 0) / n;\n  const sd = Math.sqrt(diffs.reduce((s, d) => s + (d - m) ** 2, 0) / (n - 1));\n  if (sd === 0) return null;\n  return Math.round(m / sd * 10000) / 10000;\n}",
  sol:"function pairedT(diffs) {\n  const n = diffs.length;\n  if (n < 2) return null;\n  const m = diffs.reduce((s, d) => s + d, 0) / n;\n  const sd = Math.sqrt(diffs.reduce((s, d) => s + (d - m) ** 2, 0) / (n - 1));\n  if (sd === 0) return null;\n  return Math.round(m / (sd / Math.sqrt(n)) * 10000) / 10000;\n}",
  tests:[["pairedT([1,1,1,3])","3"],
         ["pairedT([2,2,2,2]) === null","true"],
         ["pairedT([-1,-1,-1,-3])","-3"],
         ["pairedT([0,2])","1"]],
  edge:[["pairedT([5]) === null","true"],
        ["pairedT([1,3,1,3])","3.4641"]],
  ex:"🐛 원인: 분모가 <b>표준편차</b>이면 그것은 효과 크기(코헨의 d 에 가까움)이지 t 통계량이 아닙니다. t 는 <b>표준오차</b>로 나누므로 표본이 늘수록 커지고, 그래서 '차이가 있다' 를 판정할 수 있습니다. 이 나눗셈이 빠지면 표본을 아무리 모아도 검정이 반응하지 않습니다.\n🔧 해결: <code>sd / √n</code> 으로 나눕니다. 표본이 4배가 되면 통계량이 2배가 되는지로 검산하세요.\n🛡 재발 방지: 효과 크기와 검정 통계량은 <b>다른 질문</b>에 답합니다 — 전자는 '얼마나 큰 차이인가', 후자는 '우연으로 보기 어려운가'. 둘을 함께 보고해야 '통계적으로 유의하지만 실무적으로 무의미한' 결과를 걸러 낼 수 있습니다." },

];
