/* 통계 디버깅 12 — 숫자는 나오는데 뜻이 틀린 코드를 고친다.
   전부 결정적이고 순수 JS 다. 검증:  node ver_dbgjs.cjs ./dbg_stat.cjs */
module.exports = [

{ track:"stat", cat:"debug", k:"표준편차가 0 인데 나눈다",
  q:"표준점수를 구합니다. 표준편차가 0 이면 <b>모든 값이 같다</b>는 뜻이라 표준점수가 정의되지 않으므로 <code>null</code> 입니다. 지금은 상수 열이 들어오면 <code>Infinity</code> 나 <code>NaN</code> 이 모델 입력으로 흘러갑니다.",
  src:"function zScore(x, mean, sd) {\n  return Math.round((x - mean) / sd * 100) / 100;\n}",
  sol:"function zScore(x, mean, sd) {\n  if (!(sd > 0)) return null;\n  return Math.round((x - mean) / sd * 100) / 100;\n}",
  tests:[["zScore(10, 5, 2)","2.5"],
         ["zScore(5, 5, 0) === null","true"],
         ["zScore(3, 5, 2)","-1"],
         ["zScore(5, 5, 2)","0"]],
  edge:[["zScore(7, 5, 0) === null","true"],
        ["zScore(1, 0, 0.5)","2"]],
  ex:"원인: 상수 열(모든 값이 같은 특성)은 실전 데이터에 <b>흔합니다</b> — 아직 값이 하나뿐인 신규 카테고리, 상수로 채운 결측 보정. 그때 표준편차가 0 이라 나눗셈이 <code>Infinity</code> 나 <code>0/0 = NaN</code> 이 되고, 그 값이 모델에 들어가면 <b>학습 전체가 <code>NaN</code></b> 이 됩니다.\n해결: <code>sd &gt; 0</code> 을 먼저 확인합니다. <code>!(sd &gt; 0)</code> 으로 적으면 <code>NaN</code> 인 표준편차도 함께 걸러집니다.\n재발 방지: 전처리 코드는 '<b>이 열이 상수면 어떻게 하는가</b>' 를 정해야 합니다 — 제거하거나, 0 으로 채우거나, 거절하거나. 조용히 <code>NaN</code> 을 흘리면 원인 지점에서 아주 멀리 떨어진 곳에서 증상이 나타나 디버깅이 가장 어려워집니다." },

{ track:"stat", cat:"debug", k:"백분위수 자리를 하나 넘긴다",
  q:"정렬된 값에서 <b>가장 가까운 순위</b> 방식의 백분위수를 구합니다. 자리는 <code>ceil(p/100 × n)</code> 번째(1부터)이고, <code>p</code> 가 0 이면 최솟값입니다. 지금은 중앙값 근처가 한 칸씩 밀립니다.",
  src:"function pctile(xs, p) {\n  if (!xs.length) return null;\n  const s = xs.slice().sort((a, b) => a - b);\n  return s[Math.ceil(p / 100 * s.length)];\n}",
  sol:"function pctile(xs, p) {\n  if (!xs.length) return null;\n  const s = xs.slice().sort((a, b) => a - b);\n  const rank = Math.max(1, Math.ceil(p / 100 * s.length));\n  return s[rank - 1];\n}",
  tests:[["pctile([1,2,3,4], 50)","2"],
         ["pctile([1,2,3,4], 100)","4"],
         ["pctile([1,2,3,4], 0)","1"],
         ["pctile([10,20,30], 75)","30"]],
  edge:[["pctile([], 50) === null","true"],
        ["pctile([5], 99)","5"]],
  ex:"원인: 순위는 <b>1 부터</b> 세고 배열 자리는 <b>0 부터</b> 셉니다. <code>-1</code> 을 안 빼면 한 칸씩 밀리고, <code>p = 100</code> 에서는 배열 밖이라 <code>undefined</code> 가 나옵니다. <code>p = 0</code> 이면 순위가 0 이 되므로 최소 1 로 올려야 합니다.\n해결: 순위를 구한 뒤 <b>1 을 빼서</b> 자리로 바꿉니다. p50 이 정확히 어느 값이어야 하는지를 테스트로 못 박으세요.\n재발 방지: 백분위수는 <b>정의가 여러 가지</b>입니다 — 가장 가까운 순위, 선형 보간, 배타적/포함적. 라이브러리마다 기본값이 달라 같은 데이터에서 다른 p95 가 나옵니다. 어느 정의인지 <b>함수 이름과 문서에 적고</b>, 대시보드와 경보가 같은 정의를 쓰는지 확인하세요." },

{ track:"stat", cat:"debug", k:"이동평균이 채워지기 전부터 값을 낸다",
  q:"창 크기 <code>w</code> 의 <b>단순 이동평균</b>입니다. 창이 다 차기 전 구간은 값을 내지 않으므로 결과 길이는 <code>n − w + 1</code> 입니다. 지금은 앞쪽에 <b>덜 채워진 평균</b>이 섞여 그래프 초반이 튑니다.",
  src:"function movingAvg(xs, w) {\n  return xs.map((_, i) => {\n    const win = xs.slice(Math.max(0, i - w + 1), i + 1);\n    return win.reduce((s, x) => s + x, 0) / win.length;\n  });\n}",
  sol:"function movingAvg(xs, w) {\n  if (w <= 0 || xs.length < w) return [];\n  const out = [];\n  for (let i = w - 1; i < xs.length; i += 1) {\n    const win = xs.slice(i - w + 1, i + 1);\n    out.push(win.reduce((s, x) => s + x, 0) / w);\n  }\n  return out;\n}",
  tests:[["movingAvg([1,2,3,4], 2)","[1.5,2.5,3.5]"],
         ["movingAvg([1,2,3], 3)","[2]"],
         ["movingAvg([1,2], 3)","[]"],
         ["movingAvg([2,4,6,8], 2)","[3,5,7]"]],
  edge:[["movingAvg([], 2)","[]"],
        ["movingAvg([5,5,5], 1)","[5,5,5]"]],
  ex:"원인: 창이 채워지기 전에도 값을 내면 <b>앞쪽 몇 개는 표본 수가 다른 평균</b>입니다. 7일 이동평균의 첫날은 사실 1일 평균이라 훨씬 크게 흔들리고, 그 튐을 보고 '이상 징후' 로 판단하게 됩니다.\n해결: <code>w − 1</code> 번째부터 시작해 결과 길이를 <code>n − w + 1</code> 로 맞춥니다. 앞을 <code>null</code> 로 채워 길이를 유지하는 방식도 있는데, 어느 쪽이든 <b>계약으로 적어야</b> 그래프 축이 어긋나지 않습니다.\n재발 방지: 이동 통계는 '<b>가장자리를 어떻게 하는가</b>' 가 절반입니다. 그리고 자료가 창보다 짧을 때 빈 배열인지 오류인지도 정해 두세요 — 새 지표를 붙인 첫날이 정확히 그 경우입니다." },

{ track:"stat", cat:"debug", k:"다중 비교 보정이 너무 세다",
  q:"여러 개의 p 값에 <b>벤저미니-호크버그</b>(FDR) 보정을 걸어, 기각할 가설의 개수를 셉니다. 지금은 본페로니처럼 동작해 <b>진짜 효과까지 전부 놓칩니다</b>.",
  src:"function bhReject(ps, q) {\n  return ps.filter(p => p <= q / ps.length).length;\n}",
  sol:"function bhReject(ps, q) {\n  const s = ps.slice().sort((a, b) => a - b);\n  let k = 0;\n  for (let i = 0; i < s.length; i += 1) {\n    if (s[i] <= q * (i + 1) / s.length) k = i + 1;\n  }\n  return k;\n}",
  tests:[["bhReject([0.001, 0.02, 0.03, 0.9], 0.05)","3"],
         ["bhReject([0.9, 0.8], 0.05)","0"],
         ["bhReject([0.001], 0.05)","1"],
         ["bhReject([0.01, 0.02, 0.03], 0.05)","3"]],
  edge:[["bhReject([], 0.05)","0"],
        ["bhReject([0.05], 0.05)","1"]],
  ex:"원인: 본페로니는 모든 p 값에 <b>같은 문턱</b> <code>q/m</code> 을 씌웁니다. BH 는 정렬한 뒤 순위에 비례한 문턱 <code>q × i / m</code> 을 씌우고, <b>조건을 만족하는 가장 큰 순위까지 전부</b> 기각합니다. 그래서 BH 가 훨씬 덜 보수적이고 검정 수가 많을수록 차이가 큽니다.\n해결: 오름차순 정렬 → 순위별 문턱과 견주기 → <b>마지막으로 만족한 순위</b>를 기억합니다. 중간에 만족하지 않는 p 값이 있어도 그보다 작은 것들은 함께 기각한다는 점이 핵심입니다.\n재발 방지: 보정을 안 하면 거짓 양성이 넘치고, 너무 세게 하면 <b>진짜 효과를 놓칩니다</b>. 무엇을 통제하는지(FWER 대 FDR)를 먼저 정하세요 — 탐색적 분석에는 FDR 이, 하나만 틀려도 안 되는 판단에는 FWER 이 맞습니다." },

{ track:"stat", cat:"debug", k:"신뢰구간에 표준오차를 안 쓴다",
  q:"평균의 <b>신뢰구간 반폭</b>을 소수 넷째 자리까지 구합니다. 반폭은 <code>z × 표준편차 / √n</code> 입니다. 지금은 표본을 아무리 늘려도 구간이 <b>좁아지지 않습니다</b>.",
  src:"function ciHalf(sd, n, z) {\n  return Math.round(z * sd * 10000) / 10000;\n}",
  sol:"function ciHalf(sd, n, z) {\n  if (!(n > 0)) return null;\n  return Math.round(z * sd / Math.sqrt(n) * 10000) / 10000;\n}",
  tests:[["ciHalf(10, 100, 1.96)","1.96"],
         ["ciHalf(10, 400, 1.96)","0.98"],
         ["ciHalf(2, 4, 2)","2"],
         ["ciHalf(0, 100, 1.96)","0"]],
  edge:[["ciHalf(10, 0, 1.96) === null","true"],
        ["ciHalf(5, 25, 1.96)","1.96"]],
  ex:"원인: 표준편차는 <b>개별 값의 흩어짐</b>이고, 평균의 흩어짐은 <b>표준오차</b> <code>sd/√n</code> 입니다. 이 나눗셈이 빠지면 표본을 4배로 늘려도 구간이 그대로라, '데이터를 더 모아도 확신이 안 는다' 는 이상한 결론이 나옵니다.\n해결: <code>√n</code> 으로 나눕니다. 표본이 4배가 되면 구간이 절반이 되는지로 검산하세요 — 위 첫 두 테스트가 정확히 그 확인입니다.\n재발 방지: '<b>무엇의 흩어짐인가</b>' 를 늘 물으세요 — 개별 값인지, 평균인지, 차이인지. 그리고 <code>√n</code> 규칙은 표본 크기를 정할 때도 그대로 쓰입니다: 구간을 절반으로 줄이려면 표본이 <b>4배</b> 필요합니다." },

{ track:"stat", cat:"debug", k:"가중평균을 개수로 나눈다",
  q:"값과 가중치로 <b>가중평균</b>을 구합니다. 가중치 합이 0 이면 <code>null</code> 입니다. 지금은 큰 매장과 작은 매장의 평균 단가가 <b>똑같이 반영</b>됩니다.",
  src:"function weightedMean(xs, ws) {\n  const num = xs.reduce((s, x, i) => s + x * ws[i], 0);\n  return num / xs.length;\n}",
  sol:"function weightedMean(xs, ws) {\n  if (xs.length !== ws.length) return null;\n  const den = ws.reduce((s, w) => s + w, 0);\n  if (den === 0) return null;\n  const num = xs.reduce((s, x, i) => s + x * ws[i], 0);\n  return num / den;\n}",
  tests:[["weightedMean([10, 20], [1, 3])","17.5"],
         ["weightedMean([10, 20], [1, 1])","15"],
         ["weightedMean([5], [7])","5"],
         ["weightedMean([1, 2], [0, 4])","2"]],
  edge:[["weightedMean([1, 2], [0, 0]) === null","true"],
        ["weightedMean([1, 2], [1]) === null","true"]],
  ex:"원인: 가중평균의 분모는 <b>가중치의 합</b>이지 항목 개수가 아닙니다. 개수로 나누면 가중치를 곱한 만큼 값이 부풀고, 가중치가 1 일 때만 우연히 맞습니다 — 그래서 균등 가중 테스트는 통과합니다.\n해결: 분모를 <code>Σw</code> 로 바꾸고, 0 일 때를 먼저 거릅니다. 길이 불일치도 조용히 <code>NaN</code> 을 만드므로 함께 막습니다.\n재발 방지: 가중치를 쓰는 계산은 '<b>가중치의 합이 1 인가</b>' 를 먼저 물으세요. 정규화된 가중치라면 나누지 않아도 되지만, 그 전제가 깨지는 순간 조용히 틀립니다. 트래픽 가중 지연·매출 가중 만족도가 전부 같은 함정입니다." },

{ track:"stat", cat:"debug", k:"지수이동평균이 0 에서 시작한다",
  q:"평활 계수 <code>a</code> 의 <b>지수이동평균</b>입니다. 첫 값은 자료의 첫 값 그대로여야 합니다. 지금은 그래프가 <b>0 에서 솟아오르며</b> 시작해 초반 경보가 계속 울립니다.",
  src:"function ewmaOf(xs, a) {\n  let prev = 0;\n  return xs.map(x => { prev = a * x + (1 - a) * prev; return prev; });\n}",
  sol:"function ewmaOf(xs, a) {\n  if (!xs.length) return [];\n  let prev = xs[0];\n  return xs.map((x, i) => {\n    if (i === 0) return prev;\n    prev = a * x + (1 - a) * prev;\n    return prev;\n  });\n}",
  tests:[["ewmaOf([10, 10, 10], 0.5)","[10,10,10]"],
         ["ewmaOf([100], 0.5)","[100]"],
         ["ewmaOf([10, 20], 0.5)","[10,15]"],
         ["ewmaOf([4, 4, 8], 0.5)","[4,4,6]"]],
  edge:[["ewmaOf([], 0.5)","[]"],
        ["ewmaOf([7, 7], 1)","[7,7]"]],
  ex:"원인: 초깃값 0 은 '<b>지금까지 값이 0 이었다</b>' 는 강한 가정입니다. 실제 값이 100 근처라면 평활값이 0 에서 서서히 올라오는 <b>가짜 상승 구간</b>이 생기고, 그동안의 편차는 전부 잘못된 신호입니다.\n해결: 첫 값으로 초기화합니다. 더 정교하게는 <b>편향 보정</b>(<code>1 - (1-a)^t</code> 로 나누기)을 쓰는데, 아담 옵티마이저가 하는 일이 정확히 이것입니다.\n재발 방지: 상태를 들고 도는 계산은 <b>초기 상태가 결과의 일부</b>입니다. 0·null·첫 값 중 무엇으로 시작할지 정하고 테스트로 못 박으세요. 그리고 '워밍업 구간' 을 지표에서 제외할지도 함께 정해야 합니다." },

{ track:"stat", cat:"debug", k:"이상치 판정이 평균과 표준편차를 쓴다",
  q:"<b>IQR 방식</b>으로 이상치를 셉니다 — 사분위수 <code>q1</code>·<code>q3</code> 를 구해 <code>[q1 − 1.5·IQR, q3 + 1.5·IQR]</code> 밖의 값을 셉니다. 지금은 이상치가 <b>자기 자신 때문에</b> 안 잡힙니다.",
  src:"function iqrOutliers(xs) {\n  if (xs.length < 4) return 0;\n  const m = xs.reduce((s, x) => s + x, 0) / xs.length;\n  const sd = Math.sqrt(xs.reduce((s, x) => s + (x - m) ** 2, 0) / xs.length);\n  return xs.filter(x => Math.abs(x - m) > 3 * sd).length;\n}",
  sol:"function iqrOutliers(xs) {\n  if (xs.length < 4) return 0;\n  const s = xs.slice().sort((a, b) => a - b);\n  const at = p => s[Math.max(0, Math.ceil(p * s.length) - 1)];\n  const q1 = at(0.25), q3 = at(0.75), iqr = q3 - q1;\n  return xs.filter(x => x < q1 - 1.5 * iqr || x > q3 + 1.5 * iqr).length;\n}",
  tests:[["iqrOutliers([1,2,3,4,100])","1"],
         ["iqrOutliers([1,2,3,4])","0"],
         ["iqrOutliers([1,2,3,4,5,6,7,8,1000])","1"],
         ["iqrOutliers([5,5,5,5])","0"]],
  edge:[["iqrOutliers([1,2])","0"],
        ["iqrOutliers([1,1,1,1,50])","1"]],
  ex:"원인: 평균과 표준편차는 <b>이상치 자신에게 끌려갑니다</b>. 값 하나가 크게 튀면 평균이 그쪽으로 밀리고 표준편차가 크게 늘어, '평균 ± 3σ' 문턱이 그 값을 품어 버립니다 — 찾으려던 것 때문에 못 찾는 구조입니다.\n해결: <b>순위 기반</b> 통계인 사분위수를 씁니다. 중앙값·사분위수는 극단값 몇 개가 바뀌어도 거의 움직이지 않아(<b>강건</b>) 이런 판정에 알맞습니다.\n재발 방지: '평균 기반' 과 '순위 기반' 은 쓰임이 다릅니다 — 분포가 대칭이고 꼬리가 얇으면 평균이, 치우쳤거나 극단값이 있으면 중앙값·사분위수가 맞습니다. 지연 시간처럼 오른쪽으로 긴 꼬리를 가진 자료에 평균을 쓰면 거의 언제나 잘못된 결론이 나옵니다." },

{ track:"stat", cat:"debug", k:"상관계수가 상수 열에서 NaN 을 낸다",
  q:"피어슨 상관계수를 소수 넷째 자리까지 구합니다. 한쪽이 <b>상수</b>면 정의되지 않으므로 <code>null</code> 입니다. 지금은 상관 행렬에 <code>NaN</code> 이 섞여 히트맵이 통째로 비어 보입니다.",
  src:"function corrOf(xs, ys) {\n  const n = xs.length;\n  const mx = xs.reduce((s, x) => s + x, 0) / n;\n  const my = ys.reduce((s, y) => s + y, 0) / n;\n  let sxy = 0, sxx = 0, syy = 0;\n  for (let i = 0; i < n; i += 1) {\n    sxy += (xs[i] - mx) * (ys[i] - my);\n    sxx += (xs[i] - mx) ** 2;\n    syy += (ys[i] - my) ** 2;\n  }\n  return Math.round(sxy / Math.sqrt(sxx * syy) * 10000) / 10000;\n}",
  sol:"function corrOf(xs, ys) {\n  const n = xs.length;\n  if (n < 2 || ys.length !== n) return null;\n  const mx = xs.reduce((s, x) => s + x, 0) / n;\n  const my = ys.reduce((s, y) => s + y, 0) / n;\n  let sxy = 0, sxx = 0, syy = 0;\n  for (let i = 0; i < n; i += 1) {\n    sxy += (xs[i] - mx) * (ys[i] - my);\n    sxx += (xs[i] - mx) ** 2;\n    syy += (ys[i] - my) ** 2;\n  }\n  if (sxx === 0 || syy === 0) return null;\n  return Math.round(sxy / Math.sqrt(sxx * syy) * 10000) / 10000;\n}",
  tests:[["corrOf([1,2,3], [2,4,6])","1"],
         ["corrOf([1,2,3], [3,2,1])","-1"],
         ["corrOf([1,2,3], [5,5,5]) === null","true"],
         ["corrOf([1,2,3,4], [1,3,2,4])","0.8"]],
  edge:[["corrOf([1], [1]) === null","true"],
        ["corrOf([1,2], [1]) === null","true"]],
  ex:"원인: 한쪽이 상수면 그 쪽의 편차 제곱합이 0 이라 <b>0 으로 나누기</b>가 됩니다. 상관 행렬을 만들 때 상수 열 하나가 <code>NaN</code> 을 만들고, 그 행렬로 계산한 모든 것이 <code>NaN</code> 이 됩니다.\n해결: 분모의 두 항이 0 인지 <b>먼저</b> 봅니다. 관측이 2 개 미만이거나 길이가 다른 경우도 함께 막습니다.\n재발 방지: 상관은 <b>선형</b> 관계만 잽니다 — 0 이 '관계 없음' 을 뜻하지 않습니다(U 자 관계의 상관은 0 입니다). 그리고 이상치 하나가 상관을 크게 바꾸므로, 숫자만 보지 말고 <b>산점도를 함께</b> 보세요. 앤스컴의 네 자료가 그 교훈입니다." },

{ track:"stat", cat:"debug", k:"MAD 가 평균을 기준으로 잰다",
  q:"<b>중앙값 절대 편차</b>(MAD)를 구합니다 — 각 값과 <b>중앙값</b>의 거리의 중앙값입니다. 지금 값이 평균 기반 지표와 똑같이 극단값에 흔들립니다.",
  src:"function madOf(xs) {\n  if (!xs.length) return null;\n  const m = xs.reduce((s, x) => s + x, 0) / xs.length;\n  const d = xs.map(x => Math.abs(x - m)).sort((a, b) => a - b);\n  return d[Math.floor(d.length / 2)];\n}",
  sol:"function madOf(xs) {\n  if (!xs.length) return null;\n  const mid = ys => {\n    const s = ys.slice().sort((a, b) => a - b);\n    const k = Math.floor(s.length / 2);\n    return s.length % 2 ? s[k] : (s[k - 1] + s[k]) / 2;\n  };\n  const m = mid(xs);\n  return mid(xs.map(x => Math.abs(x - m)));\n}",
  tests:[["madOf([1,2,3,4,5])","1"],
         ["madOf([1,2,3,4,1000])","1"],
         ["madOf([5,5,5])","0"],
         ["madOf([1,2,3,4])","1"]],
  edge:[["madOf([]) === null","true"],
        ["madOf([7])","0"]],
  ex:"원인: 기준을 <b>평균</b>으로 잡으면 극단값이 기준 자체를 끌고 갑니다. MAD 의 존재 이유가 '기준도 흩어짐도 <b>모두 순위 기반</b>' 이라는 데 있는데, 절반만 순위 기반이면 강건함이 사라집니다. 짝수 개일 때 중앙값을 평균 내지 않은 것도 함께 틀렸습니다.\n해결: 중앙값을 구하는 헬퍼를 하나 만들어 <b>두 번 다</b> 씁니다 — 기준을 구할 때와 거리의 대표값을 구할 때.\n재발 방지: 강건 통계는 '어디에도 평균이 없어야' 성립합니다. 정규분포와 견주려면 MAD 에 <b>1.4826</b> 을 곱해 표준편차 척도로 맞추는 관례도 함께 기억하세요 — 그 상수 없이 두 지표를 나란히 놓으면 크기가 안 맞습니다." },

{ track:"stat", cat:"debug", k:"반올림한 비율의 합이 100 이 아니다",
  q:"부분 값들을 <b>정수 백분율</b>로 바꿉니다. 합은 반드시 100 이어야 합니다. 지금은 원그래프 옆 숫자가 <b>99% 나 101%</b> 로 나옵니다.",
  src:"function pctBreakdown(parts) {\n  const total = parts.reduce((s, x) => s + x, 0);\n  if (!total) return parts.map(() => 0);\n  return parts.map(x => Math.round(x / total * 100));\n}",
  sol:"function pctBreakdown(parts) {\n  const total = parts.reduce((s, x) => s + x, 0);\n  if (!total) return parts.map(() => 0);\n  const raw = parts.map(x => x / total * 100);\n  const out = raw.map(v => Math.floor(v));\n  let left = 100 - out.reduce((s, v) => s + v, 0);\n  const order = raw.map((v, i) => [v - Math.floor(v), i]).sort((a, b) => b[0] - a[0]);\n  for (const [, i] of order) { if (left <= 0) break; out[i] += 1; left -= 1; }\n  return out;\n}",
  tests:[["pctBreakdown([1,1,1])","[34,33,33]"],
         ["pctBreakdown([1,1])","[50,50]"],
         ["pctBreakdown([1,1,1,1,1,1])","[17,17,17,17,16,16]"],
         ["pctBreakdown([5])","[100]"]],
  edge:[["pctBreakdown([0,0])","[0,0]"],
        ["pctBreakdown([2,1,1])","[50,25,25]"]],
  ex:"원인: 각자 따로 반올림하면 <b>합이 보존되지 않습니다</b>. 3등분은 33·33·33 으로 99% 가 되고, 6등분은 17씩 여섯이면 102% 가 됩니다. 화면에 숫자와 그림이 함께 있으면 사람이 바로 알아챕니다.\n해결: 먼저 <b>내림</b>하고 남은 몫을 <b>소수부가 큰 순서</b>로 1씩 나눠 줍니다(최대 잉여 방식). 합이 100 임이 계산으로 보장됩니다.\n재발 방지: '개별 값을 각자 반올림한 뒤 합계' 는 언제나 어긋납니다 — 금액 분할·투표 의석·자원 배분이 같은 문제입니다. <b>합계 보존</b>을 성질 테스트로 걸어 두면 구현을 바꿔도 이 계약이 유지됩니다." },

{ track:"stat", cat:"debug", k:"비율의 평균으로 전체 비율을 낸다",
  q:"여러 집단의 성공/시도 수로 <b>전체 성공률</b>을 소수 넷째 자리까지 구합니다. 지금은 표본이 아주 작은 집단이 전체 값을 흔들어, 실제와 크게 다른 수치가 보고됩니다.",
  src:"function pooledRate(groups) {\n  if (!groups.length) return null;\n  const rates = groups.map(g => (g.n ? g.ok / g.n : 0));\n  return Math.round(rates.reduce((s, r) => s + r, 0) / rates.length * 10000) / 10000;\n}",
  sol:"function pooledRate(groups) {\n  const ok = groups.reduce((s, g) => s + g.ok, 0);\n  const n = groups.reduce((s, g) => s + g.n, 0);\n  if (!n) return null;\n  return Math.round(ok / n * 10000) / 10000;\n}",
  tests:[["pooledRate([{ok:1, n:1}, {ok:50, n:100}])","0.505"],
         ["pooledRate([{ok:5, n:10}, {ok:5, n:10}])","0.5"],
         ["pooledRate([{ok:0, n:10}, {ok:10, n:10}])","0.5"],
         ["pooledRate([{ok:3, n:4}])","0.75"]],
  edge:[["pooledRate([{ok:0, n:0}]) === null","true"],
        ["pooledRate([{ok:1, n:2}, {ok:0, n:0}])","0.5"]],
  ex:"원인: <b>비율의 평균</b>과 <b>전체의 비율</b>은 다릅니다. 시도가 1 번뿐인 집단의 100% 가 100번 시도한 집단의 50% 와 <b>같은 무게</b>를 갖게 되어, 표본이 작을수록 결과를 크게 흔듭니다.\n해결: 분자끼리 더하고 분모끼리 더해 <b>한 번만</b> 나눕니다(풀링). 집단별 비율이 필요하다면 표본 수와 <b>함께</b> 보여 주세요.\n재발 방지: 이 실수는 심슨의 역설과 이웃입니다 — 집단을 나누느냐 합치느냐로 결론이 뒤집힐 수 있습니다. 지표를 만들 때 '<b>이 비율의 분모는 무엇인가</b>' 를 한 문장으로 적어 두면, 나중에 누가 봐도 같은 수를 계산합니다." },

];
