/* 분산 시스템 디버깅 12 — 한 대에서는 맞고 여러 대에서 갈라지는 코드를 고친다.
   전부 결정적이고 순수 JS 다. 검증:  node ver_dbgjs.cjs ./dbg_sysd.cjs */
module.exports = [

{ track:"sysd", cat:"debug", k:"해시 링이 한 바퀴를 못 돈다",
  q:"일관 해싱 링에서 키를 맡을 노드를 찾는 함수입니다. <code>ring</code> 은 위치(<code>pos</code>) 오름차순이고, 해시 <code>h</code> <b>이상</b>인 첫 노드가 담당입니다. 그런데 일부 키에서 <code>undefined</code> 가 나와 요청이 통째로 실패합니다.",
  src:"function ringPick(ring, h) {\n  for (const node of ring) {\n    if (node.pos >= h) return node.id;\n  }\n  return undefined;\n}",
  sol:"function ringPick(ring, h) {\n  for (const node of ring) {\n    if (node.pos >= h) return node.id;\n  }\n  return ring.length ? ring[0].id : undefined;\n}",
  tests:[["ringPick([{pos:10,id:'a'},{pos:20,id:'b'}], 5)","'a'"],
         ["ringPick([{pos:10,id:'a'},{pos:20,id:'b'}], 15)","'b'"],
         ["ringPick([{pos:10,id:'a'},{pos:20,id:'b'}], 25)","'a'"],
         ["ringPick([{pos:10,id:'a'},{pos:20,id:'b'}], 20)","'b'"]],
  edge:[["ringPick([{pos:10,id:'a'}], 99)","'a'"],
        ["ringPick([], 1)","undefined"]],
  ex:"🐛 원인: 링은 <b>원</b>인데 코드는 직선으로 훑었습니다. 가장 큰 노드 위치보다 큰 해시는 <b>처음으로 감겨</b> 첫 노드가 맡아야 하는데, 그 처리가 없어 담당 노드가 없다고 나옵니다. 노드가 해시 공간 위쪽에 몰려 있으면 잘 안 드러나다가, 노드를 하나 빼는 순간 대량으로 터집니다.\n🔧 해결: 끝까지 못 찾으면 <code>ring[0]</code> 으로 감습니다. 링이 비어 있을 때만 <code>undefined</code> 입니다.\n🛡 재발 방지: 원형 자료구조(해시 링·링 버퍼·시계 알고리즘)는 <b>감기는 경우</b>를 반드시 테스트에 넣으세요. 실제 구현은 이진 탐색으로 찾는데, 그때도 '삽입 지점이 길이와 같으면 0' 이라는 같은 처리가 필요합니다. 가상 노드를 쓰면 링이 촘촘해져 이 버그가 더 늦게 드러납니다." },

{ track:"sysd", cat:"debug", k:"쿼럼 부등식의 등호",
  q:"정족수 설정이 <b>강한 일관성</b>을 보장하는지 보는 함수입니다. 읽기 집합과 쓰기 집합이 <b>반드시 겹쳐야</b> 합니다. 지금은 겹치지 않는 설정을 '안전하다' 고 통과시켜, 방금 쓴 값을 못 읽는 일이 생깁니다.",
  src:"function quorumOk(n, r, w) {\n  return r + w >= n;\n}",
  sol:"function quorumOk(n, r, w) {\n  return r + w > n;\n}",
  tests:[["quorumOk(3, 2, 2)","true"],
         ["quorumOk(3, 1, 2)","false"],
         ["quorumOk(3, 2, 1)","false"],
         ["quorumOk(5, 3, 3)","true"]],
  edge:[["quorumOk(1, 1, 1)","true"],
        ["quorumOk(3, 3, 1)","true"]],
  ex:"🐛 원인: 등호 하나가 안전과 위험을 가릅니다. N=3, R=1, W=2 면 <code>R + W = 3</code> 이라 <b>겹치지 않는 조합이 존재</b>합니다 — 쓰기가 1·2번 노드에, 읽기가 3번 노드에 가면 방금 쓴 값을 못 봅니다. 겹침을 보장하려면 합이 N 을 <b>넘어야</b> 합니다(비둘기집 원리).\n🔧 해결: <code>r + w &gt; n</code> 으로 고칩니다. 같은 이유로 쓰기끼리 충돌하지 않게 하려면 <code>W &gt; N / 2</code> 도 함께 봅니다.\n🛡 재발 방지: 부등식이 계약인 코드는 <b>경계값을 반드시 테스트</b>하세요 — 여기서는 <code>r + w === n</code> 이 그 자리입니다. 그리고 N=3·W=2·R=2 가 흔한 기본값인 이유가 이 부등식과 '한 대 장애를 견딘다' 를 동시에 만족하는 가장 작은 조합이기 때문이라는 점도 함께 기억하세요." },

{ track:"sysd", cat:"debug", k:"동점일 때 복제본마다 다른 값을 고른다",
  q:"마지막 쓰기 우선(LWW) 병합입니다. 타임스탬프가 <b>같으면</b> 노드 이름이 <b>사전순으로 큰</b> 쪽을 고릅니다. 지금은 어느 복제본에서 먼저 병합했느냐에 따라 <b>결과가 갈라집니다</b>.",
  src:"function lwwMerge(a, b) {\n  return a.ts >= b.ts ? a : b;\n}",
  sol:"function lwwMerge(a, b) {\n  if (a.ts !== b.ts) return a.ts > b.ts ? a : b;\n  return a.node > b.node ? a : b;\n}",
  tests:[["lwwMerge({ts:2,node:'a',v:1}, {ts:1,node:'b',v:2}).v","1"],
         ["lwwMerge({ts:1,node:'a',v:1}, {ts:1,node:'b',v:2}).v","2"],
         ["lwwMerge({ts:1,node:'b',v:2}, {ts:1,node:'a',v:1}).v","2"],
         ["lwwMerge({ts:1,node:'a',v:1}, {ts:3,node:'b',v:9}).v","9"]],
  edge:[["lwwMerge({ts:5,node:'z',v:7}, {ts:5,node:'z',v:7}).v","7"],
        ["lwwMerge({ts:0,node:'a',v:0}, {ts:0,node:'b',v:1}).v","1"]],
  ex:"🐛 원인: 동점을 '먼저 온 쪽' 으로 풀면 병합이 <b>교환법칙을 잃습니다</b>. 복제본 1 은 <code>merge(a, b)</code>, 복제본 2 는 <code>merge(b, a)</code> 를 하게 되는데 결과가 다르면 두 복제본은 <b>영원히 수렴하지 않습니다</b>.\n🔧 해결: 동점일 때 <b>값 자체에서 결정되는 기준</b>(노드 이름·해시)으로 풉니다. 그러면 어느 순서로 병합해도 같은 답이 나옵니다.\n🛡 재발 방지: 병합 함수는 <b>교환·결합·멱등</b> 세 성질을 가져야 수렴이 보장됩니다. 세 성질을 성질 테스트로 걸어 두면 '어느 순서로 합쳐도 같은가' 를 값 하나하나 확인하지 않아도 됩니다. 그리고 LWW 는 수렴하는 대신 <b>진 쪽 쓰기를 버린다</b>는 점을 도메인에서 받아들일 수 있는지가 먼저입니다." },

{ track:"sysd", cat:"debug", k:"슬라이딩 윈도가 한 칸 넓다",
  q:"최근 <code>span</code> 안에 든 요청 수를 세는 함수입니다. 윈도는 <b>반열린 구간</b>이라 정확히 <code>span</code> 만큼 지난 것은 이미 빠져야 합니다. 지금은 한도 10 으로 잡아도 <b>11개가 통과</b>합니다.",
  src:"function inWindow(times, now, span) {\n  return times.filter(t => now - t <= span).length;\n}",
  sol:"function inWindow(times, now, span) {\n  return times.filter(t => now - t < span).length;\n}",
  tests:[["inWindow([0,5,10], 10, 10)","2"],
         ["inWindow([0,5,10], 11, 10)","2"],
         ["inWindow([], 5, 10)","0"],
         ["inWindow([9,10], 10, 1)","1"]],
  edge:[["inWindow([0], 0, 1)","1"],
        ["inWindow([0], 10, 10)","0"]],
  ex:"🐛 원인: <code>&lt;=</code> 는 <b>정확히 경계에 걸린 항목</b>까지 포함합니다. 초당 10개 제한이라면 1초 전 요청은 이미 지난 것인데 그것까지 세어, 한도가 조용히 하나 넓어집니다. 트래픽이 몰릴 때만 한 건씩 새기 때문에 눈에 잘 안 띕니다.\n🔧 해결: 윈도를 <b>반열린 구간</b> <code>[now - span, now)</code> 으로 못 박고 <code>&lt;</code> 를 씁니다. 어느 쪽을 닫을지는 취향이 아니라 <b>계약</b>이라 문서와 테스트에 적어야 합니다.\n🛡 재발 방지: 시간 구간·페이지 범위·버전 범위처럼 경계가 있는 값은 '<b>어느 쪽이 열려 있는가</b>' 를 이름에 드러내세요(<code>from</code>·<code>untilExclusive</code>). 그리고 경계에 정확히 걸린 값을 테스트에 반드시 넣으세요 — 이 버그는 그 한 줄로만 잡힙니다." },

{ track:"sysd", cat:"debug", k:"큐가 가득 차면 새 것을 버린다",
  q:"최근 <code>cap</code> 개만 남기는 유한 큐입니다. 오래된 것부터 버려야 하는데, 지금은 <b>새로 들어온 것</b>이 버려져 최신 상태가 반영되지 않습니다. <code>cap</code> 이 0 이면 빈 배열입니다.",
  src:"function dropOldest(queue, cap) {\n  return queue.slice(0, cap);\n}",
  sol:"function dropOldest(queue, cap) {\n  return cap <= 0 ? [] : queue.slice(-cap);\n}",
  tests:[["dropOldest([1,2,3,4], 2)","[3,4]"],
         ["dropOldest([1], 3)","[1]"],
         ["dropOldest([], 2)","[]"],
         ["dropOldest([1,2,3], 0)","[]"]],
  edge:[["dropOldest([1,2,3], 3)","[1,2,3]"],
        ["dropOldest([1,2,3,4,5], 1)","[5]"]],
  ex:"🐛 원인: <code>slice(0, cap)</code> 은 <b>앞</b>에서 cap 개를 남기므로 오래된 것을 남기고 새 것을 버립니다. 이름은 <code>dropOldest</code> 인데 동작은 정반대라 코드 리뷰에서도 그냥 지나치기 쉽습니다.\n🔧 해결: <code>slice(-cap)</code> 으로 <b>뒤</b>에서 cap 개를 남깁니다. 다만 <code>cap</code> 이 0 이면 <code>slice(-0)</code> 은 <code>slice(0)</code> 과 같아 <b>배열 전체</b>가 나오므로 0 을 따로 갈라야 합니다 — 자바스크립트에서 <code>-0 === 0</code> 이기 때문입니다.\n🛡 재발 방지: 어느 쪽을 버릴지는 도메인 결정입니다. 지표라면 최신이 중요하고(뒤를 남긴다), 감사 로그라면 처음이 중요할 수 있습니다(앞을 남긴다). 이름과 동작이 어긋나지 않게 <b>이름 그대로의 테스트</b>를 먼저 적으세요." },

{ track:"sysd", cat:"debug", k:"벡터 클록을 합으로 견준다",
  q:"두 벡터 클록의 관계를 <code>'before'</code>·<code>'after'</code>·<code>'same'</code>·<code>'concurrent'</code> 로 판정하는 함수입니다. 지금은 <b>동시(concurrent)</b> 를 한 번도 돌려주지 않아, 충돌을 조용히 덮어씁니다.",
  src:"function clockCmp(a, b) {\n  const sum = m => Object.keys(m).reduce((s, k) => s + m[k], 0);\n  const x = sum(a), y = sum(b);\n  if (x === y) return 'same';\n  return x < y ? 'before' : 'after';\n}",
  sol:"function clockCmp(a, b) {\n  const keys = new Set([...Object.keys(a), ...Object.keys(b)]);\n  let less = false, more = false;\n  for (const k of keys) {\n    const x = a[k] || 0, y = b[k] || 0;\n    if (x < y) less = true;\n    if (x > y) more = true;\n  }\n  if (less && more) return 'concurrent';\n  if (less) return 'before';\n  if (more) return 'after';\n  return 'same';\n}",
  tests:[["clockCmp({a:1}, {a:2})","'before'"],
         ["clockCmp({a:2,b:1}, {a:1,b:2})","'concurrent'"],
         ["clockCmp({a:1}, {a:1})","'same'"],
         ["clockCmp({a:2}, {a:1})","'after'"]],
  edge:[["clockCmp({}, {a:1})","'before'"],
        ["clockCmp({}, {})","'same'"]],
  ex:"🐛 원인: 합으로 견주면 <code>{a:2,b:1}</code> 과 <code>{a:1,b:2}</code> 가 <b>같다</b>고 나옵니다. 실제로는 서로가 서로를 보지 못한 <b>동시 갱신</b>이라 자동으로 고를 수 없는 관계인데, 합계라는 한 숫자로 뭉개면 그 정보가 사라집니다.\n🔧 해결: 두 클록의 모든 키를 훑어 '어느 쪽이 더 작은 항목이 있는가' 와 '더 큰 항목이 있는가' 를 <b>따로</b> 봅니다. 둘 다 참이면 동시입니다.\n🛡 재발 방지: 부분 순서를 전순서로 억지로 바꾸면 <b>충돌이 조용히 사라집니다</b>. 벡터 클록의 존재 이유가 바로 '자동으로 못 고르는 경우가 있다' 를 드러내는 것이므로, 네 번째 답을 없애면 자료구조를 쓰는 의미가 없습니다. 동시일 때 무엇을 할지(양쪽 보존·사용자에게 묻기·도메인 병합)는 코드가 아니라 제품이 정합니다." },

{ track:"sysd", cat:"debug", k:"재시도 예산이 0으로 나눈다",
  q:"재시도 예산 판정입니다. 재시도를 한 번 더 해도 전체 요청의 <code>ratio</code> 비율을 넘지 않으면 허용합니다. 트래픽이 아직 없을 때(<code>total = 0</code>)는 허용합니다. 지금은 서비스 시작 직후 재시도가 <b>전부 막힙니다</b>.",
  src:"function retryBudget(total, retries, ratio) {\n  return retries / total < ratio;\n}",
  sol:"function retryBudget(total, retries, ratio) {\n  if (total <= 0) return true;\n  return retries + 1 <= total * ratio;\n}",
  tests:[["retryBudget(100, 5, 0.1)","true"],
         ["retryBudget(100, 10, 0.1)","false"],
         ["retryBudget(0, 0, 0.1)","true"],
         ["retryBudget(10, 0, 0.1)","true"]],
  edge:[["retryBudget(100, 9, 0.1)","true"],
        ["retryBudget(1, 1, 0.1)","false"]],
  ex:"🐛 원인: <code>0 / 0</code> 은 <code>NaN</code> 이고 <code>NaN &lt; 0.1</code> 은 <b>거짓</b>입니다. 그래서 트래픽이 없는 시작 직후에는 재시도가 전부 막히고, 이 상태가 정확히 '첫 요청이 실패했을 때' 와 겹쳐 서비스가 스스로 회복하지 못합니다.\n🔧 해결: 분모가 0 인 경우를 먼저 갈라 냅니다. 그리고 '<b>이번 재시도를 포함해</b>' 예산 안인지 보도록 <code>retries + 1</code> 로 세면 한도가 정확히 지켜집니다.\n🛡 재발 방지: 비율·평균·성공률처럼 <b>나눗셈이 들어간 판정</b>은 분모가 0 인 순간이 반드시 옵니다 — 배포 직후, 새 샤드, 새 고객. <code>NaN</code> 은 어떤 비교에서도 거짓이라 '조용히 막는' 쪽으로 기울고, 그게 장애 상황과 겹치면 최악입니다. 나눗셈 대신 <b>곱셈으로 옮겨 적으면</b> 분모 문제 자체가 사라집니다." },

{ track:"sysd", cat:"debug", k:"G-Counter 병합이 두 번 센다",
  q:"노드별 카운터를 합치는 CRDT 병합입니다. 같은 상태를 <b>여러 번 병합해도 결과가 같아야</b> 하는데, 지금은 동기화를 돌릴 때마다 숫자가 불어납니다.",
  src:"function mergeCounter(a, b) {\n  const out = {};\n  for (const k of new Set([...Object.keys(a), ...Object.keys(b)])) {\n    out[k] = (a[k] || 0) + (b[k] || 0);\n  }\n  return out;\n}",
  sol:"function mergeCounter(a, b) {\n  const out = {};\n  for (const k of new Set([...Object.keys(a), ...Object.keys(b)])) {\n    out[k] = Math.max(a[k] || 0, b[k] || 0);\n  }\n  return out;\n}",
  tests:[["mergeCounter({a:1}, {a:1})","{a:1}"],
         ["mergeCounter({a:2,b:1}, {b:3})","{a:2,b:3}"],
         ["mergeCounter({}, {a:5})","{a:5}"],
         ["mergeCounter(mergeCounter({a:1},{a:1}), {a:1})","{a:1}"]],
  edge:[["mergeCounter({}, {})","{}"],
        ["mergeCounter({a:0}, {a:0})","{a:0}"]],
  ex:"🐛 원인: G-Counter 는 '노드마다 자기 칸만 올리고, 병합은 <b>칸별 최댓값</b>' 이라는 규칙 위에 섭니다. 합을 쓰면 <b>멱등하지 않아</b> 같은 상태를 두 번 받을 때마다 값이 커집니다. 네트워크가 재전송하거나 동기화가 겹치면 반드시 일어납니다.\n🔧 해결: 칸별로 <code>Math.max</code> 를 씁니다. 전체 카운트는 병합한 뒤 <b>칸들의 합</b>으로 읽습니다 — 올리는 곳과 읽는 곳의 연산이 다른 것이 이 자료구조의 요령입니다.\n🛡 재발 방지: 분산 병합에 필요한 성질은 <b>교환·결합·멱등</b>입니다. <code>max</code> 는 셋을 모두 만족하고 <code>+</code> 는 멱등이 아닙니다. '같은 메시지를 두 번 받아도 같은가' 를 테스트로 못 박으면, 정확히 한 번 전달을 보장하지 않는 큐 위에서도 안전해집니다." },

{ track:"sysd", cat:"debug", k:"리스가 시계 오차만큼 겹친다",
  q:"리스(임대) 가 아직 유효한지 보는 함수입니다. 서버 간 시계 오차 <code>skew</code> 를 감안해 <b>보수적으로</b>, 즉 명목 만료보다 <code>skew</code> 만큼 <b>일찍</b> 만료로 봐야 합니다. 지금은 아주 가끔 <b>두 노드가 동시에 리더</b>가 됩니다.",
  src:"function leaseValid(lease, now, skew) {\n  return now < lease.until;\n}",
  sol:"function leaseValid(lease, now, skew) {\n  return now < lease.until - skew;\n}",
  tests:[["leaseValid({until:100}, 50, 5)","true"],
         ["leaseValid({until:100}, 96, 5)","false"],
         ["leaseValid({until:100}, 94, 5)","true"],
         ["leaseValid({until:100}, 100, 5)","false"]],
  edge:[["leaseValid({until:100}, 95, 5)","false"],
        ["leaseValid({until:0}, -1, 0)","true"]],
  ex:"🐛 원인: 리스를 <b>주는 쪽과 쥔 쪽의 시계가 다릅니다</b>. 쥔 쪽 시계가 조금 느리면 이미 만료된 리스를 아직 유효하다고 믿고, 그 사이 다른 노드가 새 리스를 받아 <b>둘 다 리더</b>가 됩니다. 평소에는 안 보이다가 시계가 튈 때 데이터가 깨집니다.\n🔧 해결: 쥔 쪽은 <b>일찍 포기</b>합니다(<code>until - skew</code>). 주는 쪽은 반대로 <b>늦게 회수</b>해야 안전 구간이 생깁니다 — 양쪽이 같은 식을 쓰면 안 됩니다.\n🛡 재발 방지: 분산 잠금에서 시계는 <b>믿을 수 없는 입력</b>입니다. 가능하면 시각 대신 <b>단조 증가 토큰</b>(fencing token)을 함께 넘겨, 늦게 도착한 옛 리더의 쓰기를 저장소가 거부하게 만드세요. 시간 기반 안전은 언제나 '오차보다 크게 잡았기를' 바라는 가정 위에 있습니다." },

{ track:"sysd", cat:"debug", k:"해시 버킷이 음수로 나온다",
  q:"키를 <code>n</code> 개의 버킷 중 하나에 배정하는 함수입니다. 결과는 <code>0</code> 이상 <code>n</code> 미만이어야 하는데, 일부 키에서 <b>음수 인덱스</b>가 나와 배열 접근이 <code>undefined</code> 가 됩니다.",
  src:"function bucketOf(key, n) {\n  let acc = 0;\n  for (const ch of String(key)) acc = (acc * 31 + ch.charCodeAt(0)) | 0;\n  return acc % n;\n}",
  sol:"function bucketOf(key, n) {\n  let acc = 0;\n  for (const ch of String(key)) acc = (acc * 31 + ch.charCodeAt(0)) | 0;\n  return ((acc % n) + n) % n;\n}",
  tests:[["bucketOf('a', 4)","1"],
         ["bucketOf('user-1234567890', 8)","5"],
         ["bucketOf('zzzzzzzzzzzzzzzz', 16)","0"],
         ["bucketOf('session-abcdefghijklmnop', 4)","3"]],
  edge:[["bucketOf('', 8)","0"],
        ["bucketOf('order:998877', 8)","4"]],
  ex:"🐛 원인: <code>| 0</code> 은 값을 <b>부호 있는 32비트</b>로 자릅니다. 문자열이 조금만 길어도 누적값이 넘쳐 음수가 되고, 자바스크립트의 <code>%</code> 는 <b>피제수의 부호를 따라가</b> 음수 나머지를 돌려줍니다. 짧은 키로만 테스트하면 끝까지 안 보입니다.\n🔧 해결: <code>((acc % n) + n) % n</code> 으로 항상 0 이상으로 접습니다. 또는 <code>acc &gt;&gt;&gt; 0</code> 으로 부호 없는 수로 바꾼 뒤 나눠도 됩니다.\n🛡 재발 방지: 자바스크립트·자바·C 의 <code>%</code> 는 <b>나머지</b>이지 수학의 모듈로가 아닙니다(파이썬은 다릅니다). 해시·순환 인덱스·각도 계산처럼 '언제나 0 이상' 이 필요한 자리에서는 감싸는 헬퍼를 하나 두고 그것만 쓰세요. 그리고 해시 테스트에는 <b>긴 키</b>를 반드시 넣으세요." },

{ track:"sysd", cat:"debug", k:"과반은 절반 이상이 아니다",
  q:"리더 선출에서 표가 <b>과반</b>인지 보는 함수입니다. 지금은 4대 클러스터가 2대씩 갈렸을 때 <b>양쪽 모두 리더</b>가 됩니다.",
  src:"function hasMajority(nodes, votes) {\n  return votes >= nodes / 2;\n}",
  sol:"function hasMajority(nodes, votes) {\n  return votes * 2 > nodes;\n}",
  tests:[["hasMajority(4, 2)","false"],
         ["hasMajority(4, 3)","true"],
         ["hasMajority(3, 2)","true"],
         ["hasMajority(5, 2)","false"]],
  edge:[["hasMajority(1, 1)","true"],
        ["hasMajority(2, 1)","false"]],
  ex:"🐛 원인: '절반 이상' 과 '<b>절반 초과</b>' 는 다릅니다. 짝수 대 클러스터에서 정확히 반씩 갈리면 두 진영이 모두 조건을 만족해 <b>분할 뇌</b>가 됩니다. 홀수 대에서는 이 차이가 드러나지 않아 3대 테스트만으로는 통과합니다.\n🔧 해결: <code>votes * 2 &gt; nodes</code> 로 적습니다. 나눗셈을 곱셈으로 옮기면 소수점 오차와 등호 실수를 동시에 없앨 수 있습니다.\n🛡 재발 방지: 클러스터를 <b>홀수 대</b>로 두는 관행이 여기서 나옵니다 — 4대는 3대와 견딜 수 있는 장애 수가 같으면서(1대) 분할될 때만 위험합니다. 정족수 로직은 짝수·홀수·정확히 반 세 경우를 모두 테스트하세요." },

{ track:"sysd", cat:"debug", k:"마지막 구간이 범위를 넘는다",
  q:"작업 범위 <code>[0, total)</code> 을 <code>size</code> 씩 잘라 <code>[시작, 끝)</code> 목록으로 만드는 함수입니다. 마지막 구간이 <b>범위를 넘어</b>, 이 값을 그대로 쓰는 워커가 없는 자료를 읽으려다 실패합니다.",
  src:"function chunkRanges(total, size) {\n  const out = [];\n  for (let i = 0; i < total; i += size) out.push([i, i + size]);\n  return out;\n}",
  sol:"function chunkRanges(total, size) {\n  const out = [];\n  for (let i = 0; i < total; i += size) out.push([i, Math.min(i + size, total)]);\n  return out;\n}",
  tests:[["chunkRanges(10, 4)","[[0,4],[4,8],[8,10]]"],
         ["chunkRanges(8, 4)","[[0,4],[4,8]]"],
         ["chunkRanges(3, 5)","[[0,3]]"],
         ["chunkRanges(0, 4)","[]"]],
  edge:[["chunkRanges(1, 1)","[[0,1]]"],
        ["chunkRanges(5, 10)","[[0,5]]"]],
  ex:"🐛 원인: 마지막 구간의 끝을 <b>자르지 않았습니다</b>. 딱 나누어떨어지는 크기로만 테스트하면(8 을 4 씩) 통과해서, 운영 데이터가 들어오는 순간 드러납니다. 배열 <code>slice</code> 는 넘겨도 알아서 잘라 주지만, 파일 오프셋·DB 범위 질의·외부 API 는 그렇지 않습니다.\n🔧 해결: 끝을 <code>Math.min(i + size, total)</code> 로 씌웁니다. 반환값이 <b>반열린 구간</b>이라는 점도 계약에 적어 두면 호출자가 겹치게 쓰지 않습니다.\n🛡 재발 방지: 잘라 나누는 코드는 '<b>나누어떨어지지 않는</b> 크기' 와 '<b>한 구간보다 작은</b> 전체' 두 가지를 반드시 테스트하세요. 그리고 이 함수를 그대로 병렬 처리에 쓰면 각 구간이 겹치지 않는지도 성질 테스트로 확인할 수 있습니다 — 구간 끝의 합이 total 과 같아야 합니다." },

];
