/* 보안 디버깅 12 — 검사를 하긴 했는데 우회되는 코드를 고친다.
   전부 결정적이고 순수 JS 다. 검증:  node ver_dbgjs.cjs ./dbg_security.cjs */
module.exports = [

{ track:"security", cat:"debug", k:"이스케이프 순서가 거꾸로다",
  q:"HTML 특수문자를 이스케이프합니다. <code>&amp;</code>·<code>&lt;</code>·<code>&gt;</code>·큰따옴표·작은따옴표를 각각 <code>&amp;amp;</code>·<code>&amp;lt;</code>·<code>&amp;gt;</code>·<code>&amp;quot;</code>·<code>&amp;#39;</code> 로 바꿉니다. 지금은 화면에 <code>&amp;amp;lt;</code> 같은 글자가 그대로 보입니다.",
  src:"function escapeHtml(s) {\n  return String(s)\n    .replace(/</g, '&lt;')\n    .replace(/>/g, '&gt;')\n    .replace(/\"/g, '&quot;')\n    .replace(/'/g, '&#39;')\n    .replace(/&/g, '&amp;');\n}",
  sol:"function escapeHtml(s) {\n  return String(s)\n    .replace(/&/g, '&amp;')\n    .replace(/</g, '&lt;')\n    .replace(/>/g, '&gt;')\n    .replace(/\"/g, '&quot;')\n    .replace(/'/g, '&#39;');\n}",
  tests:[["escapeHtml('<b>')","'&lt;b&gt;'"],
         ["escapeHtml('a & b')","'a &amp; b'"],
         ["escapeHtml('\"x\"')","'&quot;x&quot;'"],
         ["escapeHtml(\"it's\")","'it&#39;s'"]],
  edge:[["escapeHtml('')","''"],
        ["escapeHtml('&amp;')","'&amp;amp;'"]],
  ex:"🐛 원인: <code>&amp;</code> 를 <b>마지막에</b> 바꾸면, 앞에서 만들어 둔 <code>&amp;lt;</code> 의 <code>&amp;</code> 까지 다시 이스케이프되어 <code>&amp;amp;lt;</code> 가 됩니다. 화면에 <code>&lt;b&gt;</code> 라는 <b>글자</b>가 그대로 보이는 증상입니다.\n🔧 해결: <code>&amp;</code> 를 <b>가장 먼저</b> 바꿉니다. 그래야 이후 치환이 만든 <code>&amp;</code> 는 건드리지 않습니다.\n🛡 재발 방지: 치환이 <b>자기 결과를 다시 입력으로 삼는</b> 구조는 순서가 계약입니다. 더 안전한 길은 한 번의 <code>replace</code> 로 문자 하나하나를 표에서 찾아 바꾸는 것입니다 — <code>s.replace(/[&amp;&lt;&gt;\"']/g, c =&gt; MAP[c])</code>. 그리고 이스케이프는 <b>넣는 자리마다</b>(HTML 본문·속성·URL·JS 문자열) 규칙이 다르다는 점을 기억하세요." },

{ track:"security", cat:"debug", k:"슬래시 두 개로 열린 리다이렉트",
  q:"로그인 뒤 돌아갈 주소가 <b>우리 사이트 안</b>인지 보는 함수입니다. 상대 경로이거나 우리 호스트의 절대 주소만 허용합니다. 지금은 <code>//evil.com</code> 이 통과해 <b>외부로 튕겨 나갑니다</b>.",
  src:"function safeRedirect(url, host) {\n  const s = String(url);\n  if (s.startsWith('/')) return true;\n  return s.startsWith('https://' + host + '/') || s === 'https://' + host;\n}",
  sol:"function safeRedirect(url, host) {\n  const s = String(url);\n  if (s.startsWith('/') && !s.startsWith('//') && !s.startsWith('/\\\\')) return true;\n  return s.startsWith('https://' + host + '/') || s === 'https://' + host;\n}",
  tests:[["safeRedirect('/home', 'a.com')","true"],
         ["safeRedirect('//evil.com', 'a.com')","false"],
         ["safeRedirect('https://a.com/x', 'a.com')","true"],
         ["safeRedirect('https://evil.com', 'a.com')","false"]],
  edge:[["safeRedirect('/\\\\evil.com', 'a.com')","false"],
        ["safeRedirect('', 'a.com')","false"]],
  ex:"🐛 원인: <code>//evil.com</code> 은 <b>프로토콜 상대 URL</b> 이라 브라우저가 <code>https://evil.com</code> 으로 읽습니다. '슬래시로 시작하면 내부' 라는 규칙이 정확히 여기서 뚫립니다. 일부 브라우저는 <code>/\\evil.com</code> 도 같은 뜻으로 읽습니다.\n🔧 해결: 슬래시로 시작하되 <b>두 번째 글자가 슬래시나 역슬래시가 아닐 때만</b> 내부로 봅니다. 더 튼튼한 길은 <code>new URL(url, base)</code> 로 실제 해석한 뒤 <code>origin</code> 을 견주는 것입니다.\n🛡 재발 방지: 열린 리다이렉트는 그 자체로도 피싱에 쓰이고, OAuth 흐름과 만나면 <b>토큰 탈취</b>로 이어집니다. 돌아갈 주소는 가능하면 <b>허용 목록의 키</b>로 받으세요(<code>?next=cart</code>) — 임의 URL 을 받지 않으면 검증할 것도 없습니다." },

{ track:"security", cat:"debug", k:"CORS 오리진을 부분 문자열로 본다",
  q:"요청 오리진이 허용 목록에 있는지 보는 함수입니다. <b>정확히 같은</b> 오리진만 허용해야 합니다. 지금은 공격자가 만든 도메인이 통과해 브라우저가 응답을 읽게 됩니다.",
  src:"function corsAllow(origin, allow) {\n  return allow.some(a => String(origin).includes(a));\n}",
  sol:"function corsAllow(origin, allow) {\n  return allow.indexOf(String(origin)) >= 0;\n}",
  tests:[["corsAllow('https://a.com', ['https://a.com'])","true"],
         ["corsAllow('https://a.com.evil.net', ['https://a.com'])","false"],
         ["corsAllow('https://b.com', ['https://a.com'])","false"],
         ["corsAllow('https://a.com', ['https://b.com','https://a.com'])","true"]],
  edge:[["corsAllow('', ['https://a.com'])","false"],
        ["corsAllow('https://a.com:8443', ['https://a.com'])","false"]],
  ex:"🐛 원인: <code>includes</code> 는 <b>어딘가에 들어 있기만</b> 하면 참입니다. <code>https://a.com.evil.net</code> 은 <code>https://a.com</code> 을 포함하므로 통과하고, 그러면 그 사이트의 스크립트가 우리 API 응답을 읽습니다.\n🔧 해결: 오리진은 <b>정확히 일치</b>로만 판정합니다. 오리진은 스킴·호스트·포트 셋이 모두 같아야 같은 것이고, 포트가 다르면 다른 오리진입니다.\n🛡 재발 방지: 접근 제어에서 <code>includes</code>·<code>startsWith</code>·<code>endsWith</code> 는 거의 언제나 잘못된 도구입니다. 하위 도메인을 허용해야 한다면 <b>점 경계</b>를 명시적으로 검사하세요. 그리고 <code>Access-Control-Allow-Origin</code> 을 요청 오리진으로 <b>그대로 되돌려 주는</b> 구현은 허용 목록 검사를 반드시 먼저 통과시켜야 합니다." },

{ track:"security", cat:"debug", k:"권한 범위를 부분 문자열로 본다",
  q:"토큰의 권한 목록에 필요한 범위가 있는지 보는 함수입니다. 범위는 빈칸으로 구분된 문자열입니다. 지금은 <code>read</code> 만 가진 토큰이 <code>readwrite</code> 검사를 통과합니다.",
  src:"function scopeOk(granted, need) {\n  return String(granted).includes(need);\n}",
  sol:"function scopeOk(granted, need) {\n  return String(granted).split(/\\s+/).indexOf(need) >= 0;\n}",
  tests:[["scopeOk('read write', 'read')","true"],
         ["scopeOk('reading', 'read')","false"],
         ["scopeOk('orders:readonly', 'orders:read')","false"],
         ["scopeOk('a b c', 'c')","true"]],
  edge:[["scopeOk('', 'read')","false"],
        ["scopeOk('read', 'readwrite')","false"]],
  ex:"🐛 원인: 범위는 <b>목록</b>인데 문자열로 다뤘습니다. <code>'read'.includes('readwrite')</code> 는 거짓이지만 반대로 <code>'readwrite'.includes('read')</code> 는 참이라, 방향에 따라 <b>권한이 늘어나기도 줄어들기도</b> 합니다. <code>'reading'</code> 이 <code>'read'</code> 를 통과시키는 것도 같은 이유입니다.\n🔧 해결: 빈칸으로 나눠 <b>목록의 원소로</b> 견줍니다. 계층 범위(<code>orders:read</code>)를 쓴다면 접두사 규칙을 <b>따로 명시</b>하고, 그때도 구분자 경계를 확인하세요.\n🛡 재발 방지: 권한 검사는 '<b>가진 것 중에 정확히 이것이 있는가</b>' 입니다. 문자열 포함으로 적힌 권한 검사를 보면 그 자리에서 의심하세요. 그리고 검사에 실패했을 때 <b>기본이 거부</b>인지 확인하세요 — 예외가 나면 통과하는 구조가 의외로 흔합니다." },

{ track:"security", cat:"debug", k:"alg 가 none 인 토큰을 받는다",
  q:"JWT 헤더의 서명 알고리즘이 우리가 받아들이는 것인지 봅니다. <code>HS256</code> 과 <code>RS256</code> 만 허용합니다. 지금은 서명이 없는 토큰도 통과해 <b>아무나 관리자가 됩니다</b>.",
  src:"function jwtAlgOk(header) {\n  return header.alg !== undefined;\n}",
  sol:"function jwtAlgOk(header) {\n  return header.alg === 'HS256' || header.alg === 'RS256';\n}",
  tests:[["jwtAlgOk({alg:'HS256'})","true"],
         ["jwtAlgOk({alg:'none'})","false"],
         ["jwtAlgOk({alg:'RS256'})","true"],
         ["jwtAlgOk({})","false"]],
  edge:[["jwtAlgOk({alg:'NONE'})","false"],
        ["jwtAlgOk({alg:'HS512'})","false"]],
  ex:"🐛 원인: '<b>값이 있는가</b>' 만 봤습니다. <code>alg: 'none'</code> 은 규격에 있는 값이라 헤더로서는 멀쩡하고, 이를 받아들이면 <b>서명 없는 토큰</b>이 유효해집니다. 라이브러리를 쓰더라도 허용 알고리즘을 안 지정하면 같은 구멍이 열립니다.\n🔧 해결: <b>허용 목록</b>으로 정확히 견줍니다. 대소문자 변형(<code>NONE</code>)도 통과하지 않도록 정확히 일치로 봅니다.\n🛡 재발 방지: 토큰을 검증할 때 알고리즘을 <b>토큰이 정하게 두면 안 됩니다</b> — 검증하는 쪽이 정합니다. 대칭키(HS256)와 비대칭키(RS256)를 함께 허용하면 공개키를 HMAC 키로 쓰는 혼동 공격도 가능하므로, 실무에서는 <b>하나만</b> 고르는 편이 안전합니다." },

{ track:"security", cat:"debug", k:"경로 조각을 한 번만 지운다",
  q:"업로드 파일 이름을 안전하게 만듭니다. 경로 구분자와 <code>..</code> 를 <b>모두</b> 없애 순수한 파일 이름만 남겨야 합니다. 지금은 겹쳐 적은 입력이 그대로 상위 경로를 가리킵니다.",
  src:"function safeName(name) {\n  return String(name).replace('../', '').replace('/', '');\n}",
  sol:"function safeName(name) {\n  return String(name).replace(/[/\\\\]/g, '').replace(/\\.{2,}/g, '');\n}",
  tests:[["safeName('a.txt')","'a.txt'"],
         ["safeName('../a.txt')","'a.txt'"],
         ["safeName('....//a.txt')","'a.txt'"],
         ["safeName('x/../../y.txt')","'xy.txt'"]],
  edge:[["safeName('..\\\\..\\\\z.txt')","'z.txt'"],
        ["safeName('')","''"]],
  ex:"🐛 원인: <code>replace</code> 에 문자열을 주면 <b>첫 자리 하나만</b> 바꿉니다. <code>....//</code> 는 한 번 지우고 나면 다시 <code>../</code> 가 되어 살아납니다 — '한 번 지우면 안전하다' 는 가정이 정확히 이 방식으로 뚫립니다.\n🔧 해결: 정규식에 <code>g</code> 를 붙여 <b>남지 않을 때까지</b> 지우거나, 아예 <b>허용 문자만 남기는</b> 방식으로 바꿉니다. 역슬래시도 윈도에서는 구분자입니다.\n🛡 재발 방지: 위험한 것을 <b>지우는</b> 방식(블랙리스트)은 겹쳐 쓰기·인코딩 변형으로 계속 뚫립니다. <b>허용 목록</b>이 원칙입니다 — 파일 이름은 영숫자와 몇 글자만 남기고, 저장 이름은 서버가 새로 만들어 원본 이름은 표시용으로만 쓰세요." },

{ track:"security", cat:"debug", k:"빈 CSRF 토큰끼리 맞다고 본다",
  q:"CSRF 토큰이 쿠키의 값과 같은지 봅니다. <b>둘 다 비어 있지 않고</b> 같아야 통과입니다. 지금은 토큰을 아예 안 보낸 요청이 통과합니다.",
  src:"function csrfOk(sent, cookie) {\n  return sent === cookie;\n}",
  sol:"function csrfOk(sent, cookie) {\n  if (typeof sent !== 'string' || typeof cookie !== 'string') return false;\n  if (!sent || !cookie) return false;\n  return sent === cookie;\n}",
  tests:[["csrfOk('a1', 'a1')","true"],
         ["csrfOk('a1', 'b2')","false"],
         ["csrfOk('', '')","false"],
         ["csrfOk(undefined, undefined)","false"]],
  edge:[["csrfOk(null, null)","false"],
        ["csrfOk('a1', '')","false"]],
  ex:"🐛 원인: '<b>없음 == 없음</b>' 이 참이 되어 버립니다. 공격자는 토큰을 알 필요 없이 <b>아예 보내지 않으면</b> 됩니다. 헤더도 쿠키도 없으면 둘 다 <code>undefined</code> 라 검사가 통과합니다.\n🔧 해결: 비교 전에 <b>둘 다 실제 값인지</b> 확인합니다. 타입까지 보는 이유는 <code>null</code>·객체가 들어와도 조용히 통과하지 않게 하기 위함입니다.\n🛡 재발 방지: 동등 비교로 하는 보안 검사는 '<b>양쪽이 비어 있을 때</b>' 를 반드시 테스트하세요 — 서명 검증·API 키·HMAC 비교가 전부 같은 함정입니다. 그리고 값이 있는 경우에도 <b>일정 시간 비교</b>(timing-safe)를 쓰는 것이 원칙입니다." },

{ track:"security", cat:"debug", k:"쿠키 속성을 대소문자 그대로 본다",
  q:"<code>Set-Cookie</code> 문자열이 <code>HttpOnly</code>·<code>Secure</code>·<code>SameSite</code> 를 <b>모두</b> 갖췄는지 봅니다. 쿠키 속성 이름은 <b>대소문자를 가리지 않습니다</b>. 지금은 소문자로 적힌 설정이 '취약' 으로 잘못 보고됩니다.",
  src:"function cookieHardened(setCookie) {\n  const s = String(setCookie);\n  return s.includes('HttpOnly') && s.includes('Secure') && s.includes('SameSite');\n}",
  sol:"function cookieHardened(setCookie) {\n  const s = String(setCookie).toLowerCase();\n  return s.includes('httponly') && s.includes('secure') && s.includes('samesite');\n}",
  tests:[["cookieHardened('a=1; HttpOnly; Secure; SameSite=Lax')","true"],
         ["cookieHardened('a=1; httponly; secure; samesite=lax')","true"],
         ["cookieHardened('a=1; HttpOnly')","false"],
         ["cookieHardened('a=1')","false"]],
  edge:[["cookieHardened('a=1; HTTPONLY; SECURE; SAMESITE=Strict')","true"],
        ["cookieHardened('')","false"]],
  ex:"🐛 원인: 쿠키 속성 이름은 <b>대소문자를 가리지 않습니다</b>. 프레임워크마다 표기가 달라서(<code>httponly</code>·<code>HttpOnly</code>·<code>HTTPONLY</code>) 정확히 한 표기만 보는 검사는 <b>거짓 경보</b>를 냅니다. 거짓 경보가 잦으면 사람이 검사 결과를 무시하게 되고, 그때 진짜 문제도 함께 묻힙니다.\n🔧 해결: 양쪽을 소문자로 맞춰 견줍니다. 값까지 봐야 한다면(<code>SameSite=None</code> 은 <code>Secure</code> 가 필수) 속성을 파싱해 표로 만든 뒤 판정하세요.\n🛡 재발 방지: 규약에서 <b>대소문자를 가리지 않는</b> 자리(HTTP 헤더 이름, 쿠키 속성, 도메인, 스킴)는 정해져 있습니다. 그런 값은 <b>받는 즉시 정규화</b>해 두면 이후 코드가 전부 단순해집니다." },

{ track:"security", cat:"debug", k:"루트 밑인지 접두사만 본다",
  q:"열려는 경로가 <b>허용된 루트 아래</b>인지 봅니다. 두 값은 이미 정규화된 절대 경로입니다. 지금은 이름이 비슷한 <b>옆 디렉터리</b>가 통과합니다.",
  src:"function underRoot(root, target) {\n  return String(target).startsWith(String(root));\n}",
  sol:"function underRoot(root, target) {\n  const r = String(root).replace(/\\/+$/, '');\n  const t = String(target);\n  return t === r || t.startsWith(r + '/');\n}",
  tests:[["underRoot('/var/www', '/var/www/index.html')","true"],
         ["underRoot('/var/www', '/var/www2/secret')","false"],
         ["underRoot('/var/www', '/var/www')","true"],
         ["underRoot('/var/www', '/etc/passwd')","false"]],
  edge:[["underRoot('/var/www/', '/var/www/a')","true"],
        ["underRoot('/var/www', '/var/wwwx')","false"]],
  ex:"🐛 원인: 문자열 접두사에는 <b>경로 경계</b>가 없습니다. <code>/var/www2</code> 는 <code>/var/www</code> 로 시작하므로 통과하고, 그러면 허용 범위 밖의 디렉터리가 열립니다. 쿠키 도메인·오리진 검사와 정확히 같은 실수입니다.\n🔧 해결: 루트와 <b>정확히 같거나</b>, 루트 뒤에 <b>구분자가 오는</b> 경우만 참으로 봅니다. 루트에 붙은 꼬리 슬래시는 미리 정리해 두어야 두 규칙이 어긋나지 않습니다.\n🛡 재발 방지: 경로 검사는 정규화 → 경계 있는 접두사 비교 → <b>심볼릭 링크 확인</b> 순서로 갑니다. 세 번째를 빠뜨리면 링크 하나로 뚫리므로, 사용자 입력이 파일 경로가 되는 기능에서는 <code>realpath</code> 로 확인하거나 아예 <b>식별자로만</b> 받는 설계를 고르세요." },

{ track:"security", cat:"debug", k:"LIKE 이스케이프가 자기 자신을 안 막는다",
  q:"사용자 검색어를 SQL <code>LIKE</code> 패턴에 넣기 전에 와일드카드를 막습니다. <code>%</code>·<code>_</code>·이스케이프 문자 <code>\\\\</code> 를 모두 <code>\\\\</code> 로 막아야 합니다. 지금은 역슬래시가 든 검색어에서 막이 풀립니다.",
  src:"function escapeLike(s) {\n  return String(s).replace(/[%_]/g, c => '\\\\' + c);\n}",
  sol:"function escapeLike(s) {\n  return String(s).replace(/[\\\\%_]/g, c => '\\\\' + c);\n}",
  tests:[["escapeLike('50%')","'50\\\\%'"],
         ["escapeLike('a_b')","'a\\\\_b'"],
         ["escapeLike('c\\\\d')","'c\\\\\\\\d'"],
         ["escapeLike('plain')","'plain'"]],
  edge:[["escapeLike('')","''"],
        ["escapeLike('\\\\%')","'\\\\\\\\\\\\%'"]],
  ex:"🐛 원인: 이스케이프 문자 자신을 안 막으면 <b>막이 풀립니다</b>. 검색어에 <code>\\</code> 가 있으면 그 뒤 글자가 이스케이프된 것으로 읽혀, 우리가 붙인 <code>\\</code> 의 뜻이 뒤바뀝니다. 특수문자 두 개만 테스트하면 절대 안 보입니다.\n🔧 해결: <b>이스케이프 문자를 목록의 첫 자리에</b> 넣습니다. 그러면 한 번의 치환으로 셋이 모두 안전해집니다.\n🛡 재발 방지: 이스케이프 규칙을 만들 때 첫 질문은 언제나 '<b>이스케이프 문자 자신은 어떻게 되는가</b>' 입니다. JSON·CSV·정규식·셸 인용이 모두 같습니다. 그리고 <code>LIKE</code> 는 <b>파라미터 바인딩과 별개</b>입니다 — 바인딩은 SQL 주입을 막지만 와일드카드 뜻까지 막아 주지는 않습니다." },

{ track:"security", cat:"debug", k:"길이로 비밀번호 해시를 판정한다",
  q:"저장된 비밀번호 해시가 <b>안전한 방식</b>인지 봅니다. bcrypt·argon2·scrypt 만 <code>'strong'</code> 이고 나머지는 <code>'weak'</code> 입니다. 지금은 솔트 없는 옛 해시가 안전하다고 보고됩니다.",
  src:"function hashScheme(hash) {\n  return String(hash).length >= 32 ? 'strong' : 'weak';\n}",
  sol:"function hashScheme(hash) {\n  const s = String(hash);\n  const ok = ['$2a$', '$2b$', '$2y$', '$argon2', '$scrypt$'];\n  return ok.some(p => s.startsWith(p)) ? 'strong' : 'weak';\n}",
  tests:[["hashScheme('$2b$12$abcdefghijklmnopqrstuv')","'strong'"],
         ["hashScheme('5f4dcc3b5aa765d61d8327deb882cf99')","'weak'"],
         ["hashScheme('$argon2id$v=19$m=65536,t=3,p=4$abc')","'strong'"],
         ["hashScheme('plain')","'weak'"]],
  edge:[["hashScheme('$scrypt$ln=15,r=8,p=1$abc')","'strong'"],
        ["hashScheme('')","'weak'"]],
  ex:"🐛 원인: 길이는 <b>알고리즘을 말해 주지 않습니다</b>. MD5 는 32글자라 이 검사를 통과하지만 초당 수십억 번 계산할 수 있어 사실상 평문에 가깝습니다. '길어 보이면 안전하다' 는 직관이 정확히 반대인 영역입니다.\n🔧 해결: 해시 문자열의 <b>접두사</b>로 알고리즘을 읽습니다. 현대 해시 형식은 <code>$알고리즘$파라미터$값</code> 꼴로 자신을 밝히도록 설계돼 있습니다.\n🛡 재발 방지: 비밀번호 해시에 필요한 성질은 길이가 아니라 <b>느리고 조절 가능한 비용</b>입니다. 그리고 이 판정 함수의 진짜 값어치는 <b>옛 해시를 찾아 옮기는</b> 데 있습니다 — 로그인 성공 시점에 새 방식으로 다시 해싱해 두면 사용자를 방해하지 않고 이전할 수 있습니다." },

{ track:"security", cat:"debug", k:"토큰 모양을 확인하지 않는다",
  q:"난수 토큰이 <b><code>bytes</code> 바이트를 16진수로 적은 꼴</b>인지 봅니다. 즉 길이가 <code>bytes × 2</code> 이고 <b>소문자 16진수</b>만 들어 있어야 합니다. 지금은 짧거나 이상한 토큰이 통과합니다.",
  src:"function tokenLooksRandom(s, bytes) {\n  return typeof s === 'string' && s.length > 0;\n}",
  sol:"function tokenLooksRandom(s, bytes) {\n  if (typeof s !== 'string') return false;\n  if (s.length !== bytes * 2) return false;\n  return /^[0-9a-f]+$/.test(s);\n}",
  tests:[["tokenLooksRandom('deadbeef', 4)","true"],
         ["tokenLooksRandom('dead', 4)","false"],
         ["tokenLooksRandom('DEADBEEF', 4)","false"],
         ["tokenLooksRandom('zzzzzzzz', 4)","false"]],
  edge:[["tokenLooksRandom('', 0)","false"],
        ["tokenLooksRandom('00000000', 4)","true"]],
  ex:"🐛 원인: '문자열이고 비어 있지 않다' 는 <b>아무것도 검증하지 않는 것</b>과 같습니다. 길이가 짧은 토큰은 무차별 대입이 가능하고, 예상 밖의 글자가 든 값은 뒤쪽 코드(SQL·경로·로그)에서 다른 사고를 만듭니다.\n🔧 해결: <b>길이와 글자 집합</b>을 정확히 못 박습니다. 이 함수는 '무작위성' 을 증명하지 못하지만, <b>우리가 발급한 모양인가</b>는 확인해 줍니다.\n🛡 재발 방지: 형식 검증은 보안의 첫 관문이고 <b>가장 싼 방어</b>입니다. 값이 우리 시스템에서 나온 것이어야 한다면 모양·길이·글자 집합을 계약으로 적고 입구에서 거절하세요. 물론 모양 검사는 <b>서명·조회 검증을 대신하지 않습니다</b> — 순서상 먼저일 뿐입니다." },

];
