/* 수학·수치 디버깅 12 — 식은 맞는데 수가 어긋나는 코드를 고친다.
   전부 결정적이고 순수 JS 다. 검증:  node ver_dbgjs.cjs ./dbg_math.cjs */
module.exports = [

{ track:"math", cat:"debug", k:"반올림이 음수에서 방향을 바꾼다",
  q:"<b>0 에서 먼 쪽</b>으로 반올림합니다(−2.5 는 −3). 지금은 음수에서 −2 가 나와, 정산 반올림이 한쪽으로만 치우칩니다.",
  src:"function roundHalfAway(x) {\n  return Math.round(x);\n}",
  sol:"function roundHalfAway(x) {\n  const sign = x < 0 ? -1 : 1;\n  return sign * Math.round(Math.abs(x));\n}",
  tests:[["roundHalfAway(2.5)","3"],
         ["roundHalfAway(-2.5)","-3"],
         ["roundHalfAway(2.4)","2"],
         ["roundHalfAway(-2.6)","-3"]],
  edge:[["roundHalfAway(0)","0"],
        ["roundHalfAway(-0.5)","-1"]],
  ex:"🐛 원인: <code>Math.round</code> 는 <b>언제나 위쪽(+∞ 방향)</b>으로 반올림합니다. 그래서 2.5 는 3 이지만 −2.5 는 −2 가 됩니다. 양수만 다루는 동안에는 완벽하고, 환불·차감처럼 음수가 들어오는 순간 <b>한쪽으로 치우친 오차</b>가 쌓입니다.\n🔧 해결: 부호를 떼어 절댓값으로 반올림한 뒤 부호를 되돌립니다. 그러면 0 을 기준으로 대칭이 됩니다.\n🛡 재발 방지: 반올림 규칙은 <b>여러 가지</b>이고 도메인이 정합니다 — 위로, 0에서 멀리, 짝수로(은행가 반올림). 금액을 다루는 코드는 어느 규칙인지 <b>문서와 테스트에 적어</b> 두세요. 그리고 반올림은 <b>마지막에 한 번만</b> 하는 것이 원칙입니다 — 중간마다 반올림하면 오차가 누적됩니다." },

{ track:"math", cat:"debug", k:"변화율이 0 에서 무한대가 된다",
  q:"<code>from</code> 에서 <code>to</code> 로의 <b>변화율</b>(%)을 소수 첫째 자리까지 구합니다. 기준이 0 이면 변화율이 정의되지 않으므로 <code>null</code> 입니다. 지금은 <code>Infinity</code> 가 지표 대시보드에 그대로 찍힙니다.",
  src:"function pctChange(from, to) {\n  return Math.round((to - from) / from * 1000) / 10;\n}",
  sol:"function pctChange(from, to) {\n  if (from === 0) return null;\n  return Math.round((to - from) / from * 1000) / 10;\n}",
  tests:[["pctChange(100, 150)","50"],
         ["pctChange(0, 5) === null","true"],
         ["pctChange(200, 100)","-50"],
         ["pctChange(100, 100)","0"]],
  edge:[["pctChange(0, 0) === null","true"],
        ["pctChange(50, 55)","10"]],
  ex:"🐛 원인: 기준이 0 이면 '몇 % 늘었나' 라는 질문 자체가 성립하지 않습니다. 코드는 <code>Infinity</code>(또는 <code>0/0</code> 이면 <code>NaN</code>)를 돌려주고, 그 값이 그래프·경보·정렬로 흘러가 <b>모든 것을 망가뜨립니다</b>.\n🔧 해결: 분모가 0 인 경우를 <b>먼저 갈라</b> '알 수 없음' 을 명시적으로 돌려줍니다. 화면에서는 '−' 나 '신규' 로 표시하면 사람이 바로 이해합니다.\n🛡 재발 방지: 신규 지표·새 고객·첫 배포는 <b>언제나 분모 0 으로 시작</b>합니다. 비율을 계산하는 함수는 예외 없이 이 경우를 다뤄야 하고, '알 수 없음' 을 0 으로 뭉개면 '변화 없음' 과 구분되지 않아 더 나쁜 거짓말이 됩니다." },

{ track:"math", cat:"debug", k:"범위 제한이 뒤집힌 경계에서 무너진다",
  q:"값을 <code>[lo, hi]</code> 안으로 자릅니다. 두 경계가 <b>뒤집혀 들어와도</b> 알아서 바로잡아야 합니다. 지금은 설정 파일에서 순서가 바뀐 값이 들어오면 결과가 언제나 한쪽 끝에 붙습니다.",
  src:"function clampVal(x, lo, hi) {\n  return Math.min(hi, Math.max(lo, x));\n}",
  sol:"function clampVal(x, lo, hi) {\n  const a = Math.min(lo, hi), b = Math.max(lo, hi);\n  return Math.min(b, Math.max(a, x));\n}",
  tests:[["clampVal(5, 0, 10)","5"],
         ["clampVal(-1, 0, 10)","0"],
         ["clampVal(11, 0, 10)","10"],
         ["clampVal(5, 10, 0)","5"]],
  edge:[["clampVal(5, 5, 5)","5"],
        ["clampVal(0, -1, 1)","0"]],
  ex:"🐛 원인: <code>lo</code> 와 <code>hi</code> 가 뒤집히면 <code>max</code> 가 올린 값을 <code>min</code> 이 다시 <b>더 아래로</b> 끌어내려, 입력과 무관하게 언제나 같은 값이 나옵니다. 오류가 아니라 '항상 최솟값' 이라는 그럴듯한 동작이라 한참 뒤에 발견됩니다.\n🔧 해결: 두 경계를 <b>먼저 정렬</b>합니다. 또는 뒤집힌 경계를 <b>오류로 거절</b>해도 됩니다 — 어느 쪽이든 계약에 적어야 합니다.\n🛡 재발 방지: 경계를 인자로 받는 함수는 '<b>뒤집혀 들어오면 어떻게 하는가</b>' 를 반드시 정하세요. 설정 파일·사용자 입력·계산 결과에서 온 경계는 순서가 보장되지 않습니다. 조용히 이상하게 동작하는 것보다 <b>거절하는</b> 편이 나을 때가 많습니다." },

{ track:"math", cat:"debug", k:"등간격 나누기가 끝점을 놓친다",
  q:"<code>a</code> 부터 <code>b</code> 까지 <b>양끝을 포함해</b> <code>n</code> 개의 점을 고르게 만듭니다. 지금은 마지막 값이 <code>b</code> 에 닿지 않아 그래프의 오른쪽 끝이 잘립니다.",
  src:"function linspace(a, b, n) {\n  const step = (b - a) / n;\n  return Array.from({ length: n }, (_, i) => a + step * i);\n}",
  sol:"function linspace(a, b, n) {\n  if (n <= 1) return n === 1 ? [a] : [];\n  const step = (b - a) / (n - 1);\n  return Array.from({ length: n }, (_, i) => a + step * i);\n}",
  tests:[["linspace(0, 1, 3)","[0,0.5,1]"],
         ["linspace(0, 10, 5)","[0,2.5,5,7.5,10]"],
         ["linspace(0, 1, 2)","[0,1]"],
         ["linspace(0, 1, 1)","[0]"]],
  edge:[["linspace(-1, 1, 3)","[-1,0,1]"],
        ["linspace(0, 1, 0)","[]"]],
  ex:"🐛 원인: <b>점이 n 개면 간격은 n−1 개</b> 입니다. <code>n</code> 으로 나누면 마지막 점이 <code>b</code> 에 못 미치고, 나눈 조각 하나만큼 모자랍니다. 울타리 기둥과 칸의 관계와 같은 고전적인 한 칸 오차입니다.\n🔧 해결: <code>(b - a) / (n - 1)</code> 로 나눕니다. <code>n</code> 이 1 이면 나눗셈이 0 으로 나누기가 되므로 <b>따로 갈라</b> 시작점만 돌려줍니다.\n🛡 재발 방지: '<b>점의 수와 간격의 수</b>' 는 언제나 1 차이입니다 — 축 눈금, 히스토그램 경계, 페이지 구분선이 모두 같습니다. 마지막 값이 정확히 <code>b</code> 인지를 테스트로 못 박으면 이 실수는 첫 실행에서 잡힙니다." },

{ track:"math", cat:"debug", k:"근사 비교가 큰 수에서 무너진다",
  q:"두 실수가 <b>상대 오차</b> 안에서 같은지 봅니다. 값이 커지면 표현할 수 있는 간격도 커지므로, 절대 오차로 견주면 안 됩니다. 지금은 억 단위 값에서 <b>같은 값도 다르다</b>고 나옵니다.",
  src:"function isClose(a, b, rel) {\n  return Math.abs(a - b) < rel;\n}",
  sol:"function isClose(a, b, rel) {\n  const scale = Math.max(1, Math.abs(a), Math.abs(b));\n  return Math.abs(a - b) <= rel * scale;\n}",
  tests:[["isClose(1e9, 1e9 + 1, 1e-6)","true"],
         ["isClose(1, 1.5, 1e-6)","false"],
         ["isClose(0, 0, 1e-6)","true"],
         ["isClose(1, 1 + 1e-9, 1e-6)","true"]],
  edge:[["isClose(0, 1e-9, 1e-6)","true"],
        ["isClose(-5, -5, 1e-6)","true"]],
  ex:"🐛 원인: 부동소수점은 <b>값이 클수록 간격이 넓습니다</b>. 10억 근처에서 표현 가능한 두 수의 최소 간격은 이미 1e−7 보다 큽니다. 절대 오차 1e−6 으로 견주면 '계산 오차로 어긋난 같은 값' 을 다르다고 판정합니다.\n🔧 해결: <b>크기에 비례한</b> 허용 오차를 씁니다. 0 근처에서는 상대 오차가 뜻이 없으므로 최소 배율 1 을 함께 둡니다 — 절대와 상대를 섞는 것이 실무의 표준(파이썬 <code>math.isclose</code>)입니다.\n🛡 재발 방지: 실수를 <code>===</code> 로 견주는 코드는 대부분 버그이고, <b>절대 오차만</b> 쓰는 코드는 절반이 버그입니다. 비교 함수 하나를 만들어 프로젝트 전체가 그것만 쓰게 하세요. 그리고 테스트의 기대값도 같은 방식으로 견주어야 합니다." },

{ track:"math", cat:"debug", k:"조합 계산이 팩토리얼에서 넘친다",
  q:"이항계수 <code>nCr</code> 을 정확히 구합니다. <code>n</code> 이 30 을 넘어도 <b>정수로 정확</b>해야 합니다. 지금은 큰 값에서 끝자리가 어긋납니다.",
  src:"function nCr(n, k) {\n  const f = m => { let r = 1; for (let i = 2; i <= m; i += 1) r *= i; return r; };\n  return f(n) / (f(k) * f(n - k));\n}",
  sol:"function nCr(n, k) {\n  const t = Math.min(k, n - k);\n  let r = 1;\n  for (let i = 1; i <= t; i += 1) r = r * (n - t + i) / i;\n  return Math.round(r);\n}",
  tests:[["nCr(5, 2)","10"],
         ["nCr(30, 15)","155117520"],
         ["nCr(0, 0)","1"],
         ["nCr(5, 0)","1"]],
  edge:[["nCr(52, 5)","2598960"],
        ["nCr(10, 10)","1"]],
  ex:"🐛 원인: 30! 은 약 2.65×10³² 이라 자바스크립트 수가 <b>정확히 담을 수 있는 한계</b>(2⁵³)를 훌쩍 넘습니다. 큰 수 세 개를 만들어 나누면 각각이 이미 반올림된 값이라 결과의 끝자리가 틀립니다 — 답이 정수처럼 보여서 더 속기 쉽습니다.\n🔧 해결: 팩토리얼을 만들지 말고 <b>곱하며 바로 나눕니다</b>. <code>r * (n-t+i) / i</code> 는 각 단계의 값이 언제나 정수라서 정확도를 잃지 않고, 중간값도 훨씬 작습니다. 대칭성(<code>nCr(n,k) = nCr(n,n-k)</code>)으로 반복 횟수도 줄입니다.\n🛡 재발 방지: '<b>큰 수를 만든 뒤 줄이기</b>' 대신 '작게 유지하며 계산하기' 는 수치 코드의 일반 원칙입니다. 팩토리얼·거듭제곱·확률의 곱이 모두 같습니다. 정말 큰 정수가 필요하면 <code>BigInt</code> 를 쓰세요." },

{ track:"math", cat:"debug", k:"속도의 평균을 산술평균으로 낸다",
  q:"같은 거리를 서로 다른 속도로 갈 때의 <b>평균 속도</b>를 구합니다. 값이 0 이거나 목록이 비면 <code>null</code> 입니다. 지금 값이 실제보다 높게 나와 예상 도착 시각이 계속 빗나갑니다.",
  src:"function avgSpeed(list) {\n  if (!list.length) return null;\n  return list.reduce((s, x) => s + x, 0) / list.length;\n}",
  sol:"function avgSpeed(list) {\n  if (!list.length) return null;\n  if (list.some(x => x <= 0)) return null;\n  const inv = list.reduce((s, x) => s + 1 / x, 0);\n  return list.length / inv;\n}",
  tests:[["avgSpeed([60, 30])","40"],
         ["avgSpeed([10])","10"],
         ["avgSpeed([2, 4, 4])","3"],
         ["avgSpeed([1, 1])","1"]],
  edge:[["avgSpeed([]) === null","true"],
        ["avgSpeed([5, 0]) === null","true"]],
  ex:"🐛 원인: 같은 <b>거리</b>를 다른 속도로 가면 느린 구간에 <b>시간이 더 많이</b> 듭니다. 그래서 시간으로 가중된 평균, 곧 <b>조화평균</b>이 맞습니다. 갈 때 60, 올 때 30 이면 평균은 45 가 아니라 40 입니다.\n🔧 해결: 역수의 평균을 낸 뒤 다시 뒤집습니다. 속도가 0 이면 시간이 무한이라 평균이 정의되지 않으므로 먼저 거절합니다.\n🛡 재발 방지: 평균은 <b>무엇이 고정되어 있는가</b>로 고릅니다 — 거리가 같으면 조화, 비율의 누적이면 기하, 그냥 더해서 뜻이 있으면 산술. 처리율(req/s)·연비·환율 변동이 전부 이 함정입니다. 헷갈리면 '<b>총량 ÷ 총시간</b>' 으로 직접 계산해 검산하세요." },

{ track:"math", cat:"debug", k:"에라토스테네스가 1 을 소수로 센다",
  q:"<code>n</code> 이하의 소수를 오름차순으로 구합니다. 지금 결과의 맨 앞에 <b>1</b> 이 들어 있어, 소인수분해가 무한 루프에 빠집니다.",
  src:"function primesTo(n) {\n  const sieve = new Array(n + 1).fill(true);\n  for (let i = 2; i * i <= n; i += 1) {\n    if (!sieve[i]) continue;\n    for (let j = i * i; j <= n; j += i) sieve[j] = false;\n  }\n  const out = [];\n  for (let i = 1; i <= n; i += 1) if (sieve[i]) out.push(i);\n  return out;\n}",
  sol:"function primesTo(n) {\n  const sieve = new Array(n + 1).fill(true);\n  for (let i = 2; i * i <= n; i += 1) {\n    if (!sieve[i]) continue;\n    for (let j = i * i; j <= n; j += i) sieve[j] = false;\n  }\n  const out = [];\n  for (let i = 2; i <= n; i += 1) if (sieve[i]) out.push(i);\n  return out;\n}",
  tests:[["primesTo(10)","[2,3,5,7]"],
         ["primesTo(2)","[2]"],
         ["primesTo(1)","[]"],
         ["primesTo(0)","[]"]],
  edge:[["primesTo(20)","[2,3,5,7,11,13,17,19]"],
        ["primesTo(3)","[2,3]"]],
  ex:"🐛 원인: 체는 2 부터 지우는데 <b>결과를 모을 때는 1 부터</b> 훑었습니다. 1 은 지워진 적이 없으니 그대로 남아 소수 목록에 끼어듭니다. 1 을 소수로 보면 소인수분해의 유일성이 깨지고, <code>n /= p</code> 를 도는 코드는 <b>영영 끝나지 않습니다</b>.\n🔧 해결: 모으는 반복문도 2 부터 시작합니다. 0 과 1 을 처음부터 <code>false</code> 로 표시해 두면 의도가 더 잘 드러납니다.\n🛡 재발 방지: 체 알고리즘은 '지우는 범위' 와 '모으는 범위' 가 <b>따로</b> 있어 둘이 어긋나기 쉽습니다. 그리고 <code>n</code> 이 0·1·2 인 아주 작은 입력을 반드시 테스트하세요 — 반복문 조건이 한 번도 안 도는 경우에서 이런 실수가 드러납니다." },

{ track:"math", cat:"debug", k:"보간이 구간 밖으로 나간다",
  q:"<code>a</code> 와 <code>b</code> 사이를 <code>t</code> 비율로 보간하되 <b><code>t</code> 를 0~1 로 잘라</b> 결과가 구간 밖으로 나가지 않게 합니다. 지금은 애니메이션이 목표를 지나쳐 튕깁니다.",
  src:"function lerpClamped(a, b, t) {\n  return a + (b - a) * t;\n}",
  sol:"function lerpClamped(a, b, t) {\n  const u = Math.min(1, Math.max(0, t));\n  return a + (b - a) * u;\n}",
  tests:[["lerpClamped(0, 10, 0.5)","5"],
         ["lerpClamped(0, 10, 1.5)","10"],
         ["lerpClamped(0, 10, -1)","0"],
         ["lerpClamped(0, 10, 1)","10"]],
  edge:[["lerpClamped(5, 5, 0.3)","5"],
        ["lerpClamped(0, 10, 0)","0"]],
  ex:"🐛 원인: 계약에 '자른다' 가 적혀 있는데 자르는 코드가 없습니다. 시간을 <code>(now - start) / duration</code> 으로 계산하면 프레임이 늦게 들어올 때 <code>t</code> 가 1 을 넘어, 애니메이션이 목표를 지나쳤다가 돌아옵니다.\n🔧 해결: <code>t</code> 를 먼저 0~1 로 자릅니다. 자르지 않는 보간이 필요할 때도 있으므로 <b>두 함수를 따로</b> 두고 이름으로 구분하는 편이 좋습니다.\n🛡 재발 방지: 진행률은 거의 언제나 <b>바깥에서 계산되어</b> 들어옵니다 — 시간, 스크롤 위치, 드래그 거리. 그 값이 범위를 벗어날 수 있다는 전제로 함수를 만드세요. 그리고 <code>a + (b - a) * t</code> 는 <code>t = 1</code> 에서 정확히 <code>b</code> 가 되는 좋은 성질이 있습니다 — <code>a * (1 - t) + b * t</code> 는 그렇지 않을 수 있습니다." },

{ track:"math", cat:"debug", k:"표본분산을 n 으로 나눈다",
  q:"<b>표본분산</b>을 소수 넷째 자리까지 구합니다(자유도 <code>n − 1</code>). 값이 두 개보다 적으면 <code>null</code> 입니다. 지금 값이 통계 패키지보다 <b>조금씩 작습니다</b>.",
  src:"function sampleVar(xs) {\n  if (xs.length < 2) return null;\n  const m = xs.reduce((s, x) => s + x, 0) / xs.length;\n  const ss = xs.reduce((s, x) => s + (x - m) ** 2, 0);\n  return Math.round(ss / xs.length * 10000) / 10000;\n}",
  sol:"function sampleVar(xs) {\n  if (xs.length < 2) return null;\n  const m = xs.reduce((s, x) => s + x, 0) / xs.length;\n  const ss = xs.reduce((s, x) => s + (x - m) ** 2, 0);\n  return Math.round(ss / (xs.length - 1) * 10000) / 10000;\n}",
  tests:[["sampleVar([2,4,4,4,5,5,7,9])","4.5714"],
         ["sampleVar([1,2])","0.5"],
         ["sampleVar([3,3,3])","0"],
         ["sampleVar([1,2,3,4])","1.6667"]],
  edge:[["sampleVar([5]) === null","true"],
        ["sampleVar([]) === null","true"]],
  ex:"🐛 원인: <code>n</code> 으로 나누면 <b>모분산</b>입니다. 표본에서 계산한 평균을 쓰면 편차가 실제보다 작게 나오므로, 나누는 수를 하나 줄여(<code>n − 1</code>) 보정합니다. 표본이 크면 차이가 작아 눈에 안 띄다가, 표본이 작은 A/B 테스트에서 <b>신뢰구간이 좁게</b> 나옵니다.\n🔧 해결: 자유도로 나눕니다. 모집단 전체를 다 가진 경우에만 <code>n</code> 이 맞습니다 — 어느 쪽인지 <b>함수 이름에 드러내세요</b>.\n🛡 재발 방지: 통계 함수는 라이브러리마다 기본값이 다릅니다(넘파이 <code>ddof=0</code>, 판다스 <code>ddof=1</code>). 값을 옮길 때 <b>같은 자유도인지</b> 먼저 확인하세요. 손으로 계산한 값 하나를 테스트에 박아 두면 이 차이가 즉시 드러납니다." },

{ track:"math", cat:"debug", k:"각도 차이가 0도 근처에서 튄다",
  q:"두 각도(도 단위)의 <b>최소 부호 있는 차이</b>를 구합니다. 결과는 −180 초과 180 이하입니다. 지금은 359도와 1도의 차이가 <b>358도</b> 로 나와 회전 방향이 반대가 됩니다.",
  src:"function angleDiff(a, b) {\n  return a - b;\n}",
  sol:"function angleDiff(a, b) {\n  const d = ((a - b) % 360 + 540) % 360 - 180;\n  return d === -180 ? 180 : d;\n}",
  tests:[["angleDiff(10, 350)","20"],
         ["angleDiff(350, 10)","-20"],
         ["angleDiff(0, 0)","0"],
         ["angleDiff(180, 0)","180"]],
  edge:[["angleDiff(370, 10)","0"],
        ["angleDiff(-10, 10)","-20"]],
  ex:"🐛 원인: 각도는 <b>원 위의 값</b>이라 360 을 더하거나 빼도 같은 방향입니다. 그냥 빼면 0도 경계를 넘을 때 거의 한 바퀴에 해당하는 값이 나오고, 그 값으로 회전시키면 <b>먼 쪽으로 돌아갑니다</b>.\n🔧 해결: 차이를 <code>%</code> 로 접은 뒤 <code>+540 … −180</code> 으로 −180~180 구간에 넣습니다. 자바스크립트의 <code>%</code> 가 음수를 낼 수 있어 540 을 더해 양수로 만든 것이 요령입니다.\n🛡 재발 방지: <b>둥근 값</b>(각도·시각·요일·경도)에는 언제나 '접기' 가 필요하고, 경계를 넘는 입력을 테스트에 넣어야 합니다. 그리고 −180 과 180 중 어느 쪽을 포함할지는 계약이므로 <b>한쪽을 골라 적어</b> 두세요 — 안 정하면 구현마다 답이 갈립니다." },

{ track:"math", cat:"debug", k:"내적이 길이를 확인하지 않는다",
  q:"두 벡터의 <b>내적</b>을 구합니다. 길이가 다르면 정의되지 않으므로 <code>null</code> 입니다. 지금은 길이가 다른 벡터에서 <code>NaN</code> 이 나와 유사도 정렬이 통째로 깨집니다.",
  src:"function dotOf(a, b) {\n  return a.reduce((s, x, i) => s + x * b[i], 0);\n}",
  sol:"function dotOf(a, b) {\n  if (a.length !== b.length) return null;\n  return a.reduce((s, x, i) => s + x * b[i], 0);\n}",
  tests:[["dotOf([1,2], [3,4])","11"],
         ["dotOf([1,2], [3]) === null","true"],
         ["dotOf([], [])","0"],
         ["dotOf([1], [2])","2"]],
  edge:[["dotOf([0,0], [1,1])","0"],
        ["dotOf([1,2,3], [1,2]) === null","true"]],
  ex:"🐛 원인: 짧은 쪽을 넘어가면 <code>undefined</code> 와 곱해져 <code>NaN</code> 이 됩니다. <code>NaN</code> 은 어떤 비교에서도 거짓이라 정렬에 넣으면 <b>순서가 구현마다 달라지고</b>, 원인 지점에서 아주 멀리 떨어진 곳에서 증상이 나타납니다.\n🔧 해결: 길이를 먼저 확인하고 다르면 <code>null</code> 로 거절합니다. 임베딩 차원이 다른 벡터를 비교하려는 것은 <b>거의 언제나 상류의 버그</b>이므로, 여기서 멈추는 편이 낫습니다.\n🛡 재발 방지: <code>NaN</code> 은 <b>조용히 번지는</b> 값입니다. 만들어질 수 있는 자리(길이 불일치·0으로 나누기·문자열 변환 실패)를 입구에서 막고, 지표 파이프라인에서는 <code>NaN</code> 이 나오면 <b>경보를 울리게</b> 해 두세요 — 평균 한 개가 <code>NaN</code> 이면 그 위의 모든 집계가 <code>NaN</code> 이 됩니다." },

];
