/* 데브옵스 디버깅 12 — 배포·운영 계산이 조용히 어긋난 코드를 고친다.
   전부 결정적이고 순수 JS 다. 검증:  node ver_dbgjs.cjs ./dbg_devops.cjs */
module.exports = [

{ track:"devops", cat:"debug", k:"버전을 문자열로 견준다",
  q:"두 시맨틱 버전 중 앞이 더 큰지 보는 함수입니다. 그런데 <code>1.10.0</code> 이 <code>1.9.0</code> 보다 <b>작다</b>고 나와, 배포 파이프라인이 최신 버전을 건너뜁니다.",
  src:"function semverGt(a, b) {\n  return a > b;\n}",
  sol:"function semverGt(a, b) {\n  const p = s => String(s).split('.').map(Number);\n  const x = p(a), y = p(b);\n  for (let i = 0; i < 3; i += 1) {\n    if ((x[i] || 0) !== (y[i] || 0)) return (x[i] || 0) > (y[i] || 0);\n  }\n  return false;\n}",
  tests:[["semverGt('1.10.0', '1.9.0')","true"],
         ["semverGt('1.0.0', '1.0.0')","false"],
         ["semverGt('2.0.0', '10.0.0')","false"],
         ["semverGt('1.0.10', '1.0.9')","true"]],
  edge:[["semverGt('0.0.1', '0.0.0')","true"],
        ["semverGt('1.2', '1.2.0')","false"]],
  ex:"원인: 문자열 비교는 <b>한 글자씩</b> 견줍니다. <code>'1.10.0'</code> 과 <code>'1.9.0'</code> 은 세 번째 글자에서 <code>'1' &lt; '9'</code> 라 순서가 뒤집힙니다. 9 를 넘기 전까지는 우연히 맞아서 <b>버전이 두 자리가 되는 날</b> 처음 드러납니다.\n해결: 점으로 나눠 <b>숫자로</b> 자리마다 견줍니다. 자리가 모자라면 0 으로 채워 <code>1.2</code> 와 <code>1.2.0</code> 을 같게 봅니다.\n재발 방지: 정렬해야 하는 값을 문자열로 저장할 때는 <b>자릿수를 채우거나</b>(<code>001.010.000</code>) 애초에 숫자 세 칸으로 나눠 두세요. 같은 함정이 로그 파일 이름(<code>app.log.10</code>)·태그·날짜 문자열에도 있습니다. 사전순과 숫자순이 갈리는 첫 지점은 대개 <b>10</b> 입니다." },

{ track:"devops", cat:"debug", k:"크론의 */k 를 글자 그대로 읽는다",
  q:"크론 필드 하나가 주어진 값과 맞는지 보는 함수입니다. <code>*</code>·정확한 수·<code>a-b</code> 범위·<code>*/k</code> 간격·쉼표 목록을 지원해야 합니다. 지금은 <code>*/15</code> 로 적은 잡이 <b>한 번도 돌지 않습니다</b>.",
  src:"function cronMatch(spec, value) {\n  if (spec === '*') return true;\n  return String(spec).split(',').some(part => Number(part) === value);\n}",
  sol:"function cronMatch(spec, value) {\n  return String(spec).split(',').some(part => {\n    if (part === '*') return true;\n    if (part.startsWith('*/')) return value % Number(part.slice(2)) === 0;\n    if (part.includes('-')) {\n      const [lo, hi] = part.split('-').map(Number);\n      return value >= lo && value <= hi;\n    }\n    return Number(part) === value;\n  });\n}",
  tests:[["cronMatch('*/15', 30)","true"],
         ["cronMatch('*/15', 7)","false"],
         ["cronMatch('1,2,3', 2)","true"],
         ["cronMatch('10-20', 15)","true"]],
  edge:[["cronMatch('*', 0)","true"],
        ["cronMatch('5', 5)","true"]],
  ex:"원인: <code>Number('*/15')</code> 는 <code>NaN</code> 이라 어떤 값과도 같지 않습니다. 그래서 잡이 <b>조용히 한 번도 안 돕니다</b> — 오류도 로그도 없이 그냥 아무 일이 없어서, 며칠 뒤 '보고서가 안 왔다' 로 알게 됩니다.\n해결: 필드 문법을 갈래로 나눠 각각 처리합니다. 목록은 바깥에서 한 번 나누고, 각 조각을 <code>*</code>·<code>*/k</code>·범위·정확한 수로 판정합니다.\n재발 방지: '<b>아무 일도 안 일어나는</b>' 실패는 예외보다 늦게 발견됩니다. 스케줄러에는 '마지막 실행 시각' 지표를 두고 예상 주기를 넘으면 경보하세요. 그리고 크론 표현식은 파싱 결과를 <b>다음 실행 시각 목록</b>으로 보여 주면 설정 실수를 배포 전에 잡을 수 있습니다." },

{ track:"devops", cat:"debug", k:"조건 하나만 참이면 준비 완료로 본다",
  q:"파드의 준비 상태 조건들을 보고 트래픽을 보내도 되는지 판정합니다. <b>모든</b> 조건이 <code>'True'</code> 여야 하고, 조건이 하나도 없으면 준비되지 않은 것입니다. 지금은 아직 준비 안 된 파드로 요청이 흘러 502 가 납니다.",
  src:"function podReady(conds) {\n  return conds.some(c => c.status === 'True');\n}",
  sol:"function podReady(conds) {\n  return conds.length > 0 && conds.every(c => c.status === 'True');\n}",
  tests:[["podReady([{status:'True'},{status:'True'}])","true"],
         ["podReady([{status:'True'},{status:'False'}])","false"],
         ["podReady([])","false"],
         ["podReady([{status:'False'}])","false"]],
  edge:[["podReady([{status:'True'}])","true"],
        ["podReady([{status:'Unknown'},{status:'True'}])","false"]],
  ex:"원인: <code>some</code> 은 '<b>하나라도</b>' 이고 <code>every</code> 는 '<b>모두</b>' 입니다. 준비 판정은 모든 게이트를 통과해야 하는데 하나만 봐서, 컨테이너는 떴지만 의존 서비스 연결이 아직인 파드에도 트래픽이 갑니다.\n해결: <code>every</code> 로 바꾸고, <b>빈 배열</b>을 따로 막습니다. <code>[].every(...)</code> 는 <code>true</code> 라서(공허 참) 조건이 아직 보고되지 않은 파드가 준비 완료로 보이는 두 번째 함정이 있습니다.\n재발 방지: <code>every</code> 를 쓸 때는 <b>빈 배열이 참</b>이라는 점을 언제나 함께 생각하세요. '검사를 하나도 안 했다' 와 '검사를 다 통과했다' 는 완전히 다른 상태입니다. 권한 검사·정책 검사에서 이 차이가 보안 구멍이 됩니다." },

{ track:"devops", cat:"debug", k:"오류율의 분모가 틀렸다",
  q:"성공·실패 수로 오류율(%)을 소수 첫째 자리까지 구합니다. 요청이 하나도 없으면 0 입니다. 지금 대시보드의 오류율이 <b>실제보다 크게</b> 나와 경보가 계속 울립니다.",
  src:"function errPct(ok, fail) {\n  return Math.round(fail / ok * 1000) / 10;\n}",
  sol:"function errPct(ok, fail) {\n  const total = ok + fail;\n  if (total <= 0) return 0;\n  return Math.round(fail / total * 1000) / 10;\n}",
  tests:[["errPct(99, 1)","1"],
         ["errPct(0, 0)","0"],
         ["errPct(0, 5)","100"],
         ["errPct(900, 100)","10"]],
  edge:[["errPct(1, 1)","50"],
        ["errPct(999, 1)","0.1"]],
  ex:"원인: 오류율의 분모는 <b>전체 요청</b>이지 성공 수가 아닙니다. 성공 99·실패 1 이면 1% 인데 <code>1/99</code> 는 1.01% 로, 값이 작을 때는 차이가 안 보이다가 실패가 늘수록 크게 벌어집니다. 성공이 0 이면 <code>Infinity</code> 가 됩니다.\n해결: 분모를 <code>ok + fail</code> 로 바로잡고, 전체가 0 인 경우를 먼저 갈라 <code>NaN</code> 을 막습니다.\n재발 방지: 비율 지표는 <b>분모의 정의</b>를 이름과 문서에 적으세요 — '전체 요청 대비' 인지 '성공 대비' 인지, 4xx 를 실패로 세는지. 경보 임계값은 이 정의 위에 서 있어서, 정의가 흔들리면 임계값도 함께 무의미해집니다." },

{ track:"devops", cat:"debug", k:"태그를 고정으로 착각한다",
  q:"컨테이너 이미지 참조가 <b>다이제스트로 고정</b>되어 있는지 보는 함수입니다. 재현 가능한 배포에는 다이제스트가 필요합니다. 지금은 태그만 붙은 이미지도 고정으로 통과해, 같은 파이프라인이 <b>다른 이미지를 배포</b>합니다.",
  src:"function pinnedByDigest(ref) {\n  return String(ref).includes(':');\n}",
  sol:"function pinnedByDigest(ref) {\n  return String(ref).includes('@sha256:');\n}",
  tests:[["pinnedByDigest('app:1.2.3')","false"],
         ["pinnedByDigest('app@sha256:abc')","true"],
         ["pinnedByDigest('app')","false"],
         ["pinnedByDigest('reg.io:5000/app:1.0')","false"]],
  edge:[["pinnedByDigest('reg.io:5000/app@sha256:dead')","true"],
        ["pinnedByDigest('')","false"]],
  ex:"원인: 콜론은 태그에도, <b>레지스트리 포트</b>에도 들어갑니다(<code>reg.io:5000/app</code>). 콜론만 보면 거의 모든 참조가 '고정' 으로 통과합니다. 태그는 <b>언제든 다른 이미지를 가리키도록 다시 붙일 수 있어</b> 고정이 아닙니다.\n해결: 다이제스트 참조의 표식인 <code>@sha256:</code> 를 봅니다. 같은 다이제스트는 같은 바이트라는 것이 레지스트리의 보장입니다.\n재발 방지: '들어 있는가' 로 형식을 판정하면 우연히 맞는 경우가 반드시 생깁니다. 참조 문자열은 <b>제대로 파싱</b>하거나(레지스트리·이름·태그·다이제스트), 최소한 <b>위치를 특정한</b> 검사를 쓰세요. 운영에서는 배포 시점에 태그를 다이제스트로 <b>풀어서 기록</b>해 두면 나중에 무엇이 돌았는지 되짚을 수 있습니다." },

{ track:"devops", cat:"debug", k:"빈 문자열 환경변수가 사라진다",
  q:"기본 환경변수 위에 덮어쓰는 함수입니다. 덮어쓰는 값이 <b>빈 문자열이어도</b> 반영되어야 하고, <code>null</code> 인 키는 <b>삭제</b>입니다. 지금은 <code>LOG_PREFIX=\"\"</code> 로 비우려 해도 기본값이 그대로 남습니다.",
  src:"function mergeEnv(base, over) {\n  const out = Object.assign({}, base);\n  for (const k of Object.keys(over)) {\n    if (over[k]) out[k] = over[k];\n  }\n  return out;\n}",
  sol:"function mergeEnv(base, over) {\n  const out = Object.assign({}, base);\n  for (const k of Object.keys(over)) {\n    if (over[k] === null) delete out[k];\n    else out[k] = over[k];\n  }\n  return out;\n}",
  tests:[["mergeEnv({A:'1'}, {A:''})","{A:''}"],
         ["mergeEnv({A:'1'}, {A:null})","{}"],
         ["mergeEnv({A:'1'}, {B:'2'})","{A:'1', B:'2'}"],
         ["mergeEnv({}, {A:'0'})","{A:'0'}"]],
  edge:[["mergeEnv({A:'1'}, {})","{A:'1'}"],
        ["mergeEnv({A:'x'}, {A:'0'})","{A:'0'}"]],
  ex:"원인: <code>if (over[k])</code> 는 <b>거짓 같은 값</b>을 전부 걸러 냅니다 — 빈 문자열, <code>'0'</code> 은 아니지만 숫자 <code>0</code>, <code>false</code>. 그래서 '비우기' 라는 정당한 설정이 '설정 안 함' 으로 뭉개집니다. 환경변수에서 빈 값과 없는 값은 <b>서로 다른 뜻</b>입니다.\n해결: '있는가' 는 <code>Object.keys</code> 로 판정하고, 값의 참·거짓은 보지 않습니다. 삭제는 <code>null</code> 이라는 <b>명시적 표식</b>으로 따로 표현합니다.\n재발 방지: 설정 병합·기본값 채우기(<code>a || b</code>)에서 이 함정이 가장 자주 나옵니다. 기본값이 필요하면 <code>??</code>(널 병합)를 쓰세요 — <code>0</code> 과 <code>''</code> 를 살려 줍니다. 그리고 '없음' 을 표현하는 값을 <b>하나만</b> 정해 두세요." },

{ track:"devops", cat:"debug", k:"로그 파일이 사전순으로 정렬된다",
  q:"회전된 로그 파일을 <b>오래된 순</b>(번호가 큰 쪽이 오래됨은 아님 — 여기서는 번호가 작을수록 최신이라 오름차순이 최신순)으로 정렬합니다. 계약은 <b>접미 번호의 숫자 오름차순</b>입니다. 지금은 <code>a.log.10</code> 이 <code>a.log.2</code> 보다 앞에 옵니다.",
  src:"function sortRotated(files) {\n  return files.slice().sort();\n}",
  sol:"function sortRotated(files) {\n  const n = f => Number(String(f).split('.').pop());\n  return files.slice().sort((a, b) => n(a) - n(b));\n}",
  tests:[["sortRotated(['a.log.2','a.log.10','a.log.1'])","['a.log.1','a.log.2','a.log.10']"],
         ["sortRotated(['x.1','x.3','x.2'])","['x.1','x.2','x.3']"],
         ["sortRotated(['b.log.20','b.log.3'])","['b.log.3','b.log.20']"],
         ["sortRotated([])","[]"]],
  edge:[["sortRotated(['c.log.1'])","['c.log.1']"],
        ["sortRotated(['d.9','d.10','d.11'])","['d.9','d.10','d.11']"]],
  ex:"원인: 인자 없는 <code>sort()</code> 는 원소를 <b>문자열로 바꿔</b> 사전순으로 정렬합니다. <code>'10' &lt; '2'</code> 이므로 열 번째 회전 파일이 두 번째보다 앞에 옵니다. 파일이 아홉 개를 넘기 전까지는 정확히 맞아서 오래 숨습니다.\n해결: 접미 번호를 뽑아 <b>숫자로</b> 견주는 비교 함수를 넘깁니다. 같은 이유로 숫자 배열도 <code>[1,2,10].sort()</code> 가 <code>[1,10,2]</code> 가 됩니다.\n재발 방지: 이름에 번호를 넣을 때는 <b>자릿수를 채우면</b>(<code>a.log.010</code>) 사전순과 숫자순이 같아집니다. 로그 회전·백업·마이그레이션 파일 이름을 지을 때 이 관행 하나로 도구 전체가 편해집니다. 사람이 읽는 순서가 필요하면 <code>Intl.Collator(undefined, {numeric:true})</code> 도 답입니다." },

{ track:"devops", cat:"debug", k:"오토스케일 목표를 내림한다",
  q:"현재 사용률로 필요한 레플리카 수를 계산합니다. 계산식은 <code>current × curUtil / targetUtil</code> 이고 <b>올림</b>하며 최소 1 입니다. 지금은 부하가 올라도 <b>한 대씩 모자라게</b> 늘어 목표 사용률을 계속 넘깁니다.",
  src:"function replicasFor(current, targetUtil, curUtil) {\n  return Math.max(1, Math.round(current * curUtil / targetUtil));\n}",
  sol:"function replicasFor(current, targetUtil, curUtil) {\n  return Math.max(1, Math.ceil(current * curUtil / targetUtil));\n}",
  tests:[["replicasFor(3, 50, 90)","6"],
         ["replicasFor(2, 50, 50)","2"],
         ["replicasFor(1, 80, 10)","1"],
         ["replicasFor(4, 60, 61)","5"]],
  edge:[["replicasFor(10, 50, 0)","1"],
        ["replicasFor(3, 50, 100)","6"]],
  ex:"원인: <code>Math.round</code> 는 <b>내려갈 수도</b> 있습니다. 5.4 대가 필요한데 5 대로 잡으면 목표 사용률을 계속 넘고, 다음 주기에 또 조금 늘리는 <b>느린 추격</b>이 됩니다. 부하가 계단으로 오르면 이 지연이 그대로 지연 시간 증가가 됩니다.\n해결: 필요한 대수는 언제나 <b>올림</b>입니다. 사람 수·서버 수·요청 처리 슬롯처럼 <b>쪼갤 수 없는 자원</b>은 예외 없이 <code>Math.ceil</code> 입니다.\n재발 방지: 반대로 줄일 때는 급격한 축소가 부하 급증을 만드므로 <b>안정화 창</b>을 둡니다. 그리고 <code>curUtil</code> 이 0 이면 계산이 0 이 되어 최소값에 걸리는데, 그 최소값이 실제로 안전한 하한인지 따로 정해야 합니다 — 수식이 아니라 용량 산정의 문제입니다." },

{ track:"devops", cat:"debug", k:"Mi 와 M 을 같게 센다",
  q:"쿠버네티스 자원 수량 문자열을 바이트로 바꿉니다. <code>Ki·Mi·Gi</code> 는 <b>1024 진법</b>, <code>K·M·G</code> 는 <b>1000 진법</b>입니다. 지금은 메모리 한도가 실제보다 작게 잡혀 컨테이너가 OOM 으로 죽습니다.",
  src:"function parseQty(s) {\n  const m = String(s).match(/^(\\d+)(Ki|Mi|Gi|K|M|G)?$/);\n  if (!m) return null;\n  const unit = { K: 1e3, M: 1e6, G: 1e9, Ki: 1e3, Mi: 1e6, Gi: 1e9 };\n  return Number(m[1]) * (m[2] ? unit[m[2]] : 1);\n}",
  sol:"function parseQty(s) {\n  const m = String(s).match(/^(\\d+)(Ki|Mi|Gi|K|M|G)?$/);\n  if (!m) return null;\n  const unit = { K: 1e3, M: 1e6, G: 1e9, Ki: 1024, Mi: 1048576, Gi: 1073741824 };\n  return Number(m[1]) * (m[2] ? unit[m[2]] : 1);\n}",
  tests:[["parseQty('1Mi')","1048576"],
         ["parseQty('1M')","1000000"],
         ["parseQty('512Ki')","524288"],
         ["parseQty('2Gi')","2147483648"]],
  edge:[["parseQty('100')","100"],
        ["parseQty('1x')","null"]],
  ex:"원인: 접미사 표를 만들면서 <code>Ki·Mi·Gi</code> 에 10진 배수를 넣었습니다. <code>1Gi</code> 와 <code>1G</code> 는 약 7% 차이라 작은 값에서는 넘어가고, 기가 단위에서 <b>7천만 바이트</b>가 사라져 한도가 모자랍니다.\n해결: 2진 접두사는 1024 의 거듭제곱입니다(<code>Ki=1024</code>·<code>Mi=1024²</code>·<code>Gi=1024³</code>). 표를 만들 때 값 하나하나를 테스트로 못 박으세요.\n재발 방지: 같은 혼동이 디스크 광고 용량(1TB = 10¹²)과 운영체제 표시(1TiB = 2⁴⁰), <code>df</code> 의 <code>-h</code> 와 <code>-H</code> 옵션에도 있습니다. 단위를 다루는 코드는 <b>변환표 자체를 테스트</b>하는 것이 가장 확실합니다 — 로직은 맞는데 표가 틀린 버그는 로직만 봐서는 안 보입니다." },

{ track:"devops", cat:"debug", k:"표본 두 개로 카나리를 통과시킨다",
  q:"카나리 배포 판정입니다. 카나리 요청이 <b><code>minN</code> 건 이상</b> 쌓였고, 카나리 오류율이 기준의 <b>1.5배 이하</b>일 때만 통과입니다. 지금은 배포 직후 요청 두어 건만 성공해도 전체 전환이 시작됩니다.",
  src:"function canaryPass(base, canary, minN) {\n  const rate = g => (g.total ? g.fail / g.total : 0);\n  return rate(canary) <= rate(base) * 1.5;\n}",
  sol:"function canaryPass(base, canary, minN) {\n  const rate = g => (g.total ? g.fail / g.total : 0);\n  if (canary.total < minN) return false;\n  return rate(canary) <= rate(base) * 1.5;\n}",
  tests:[["canaryPass({total:1000,fail:10}, {total:2,fail:0}, 100)","false"],
         ["canaryPass({total:1000,fail:10}, {total:200,fail:2}, 100)","true"],
         ["canaryPass({total:1000,fail:10}, {total:200,fail:40}, 100)","false"],
         ["canaryPass({total:1000,fail:10}, {total:100,fail:1}, 100)","true"]],
  edge:[["canaryPass({total:0,fail:0}, {total:100,fail:0}, 100)","true"],
        ["canaryPass({total:1000,fail:10}, {total:99,fail:0}, 100)","false"]],
  ex:"원인: 표본 수를 안 봤습니다. 요청 두 건이 성공하면 오류율 0% 라 어떤 기준도 통과하지만, 그 0% 는 <b>아무것도 말해 주지 않습니다</b>. 배포 직후는 트래픽이 가장 적은 시점이라 이 구멍에 반드시 걸립니다.\n해결: 최소 표본 수를 게이트로 먼저 겁니다. 통계적으로는 신뢰구간을 보는 것이 정석이지만, 실무에서는 '<b>최소 건수 + 배수 비교</b>' 만으로도 대부분의 오판을 막습니다.\n재발 방지: 비율로 판단하는 자동화(카나리·A/B·이상 탐지)에는 언제나 <b>최소 표본</b>과 <b>최소 관찰 시간</b>을 함께 두세요. 그리고 '아직 판단할 수 없음' 을 '통과' 가 아니라 <b>보류</b>로 표현하는 편이 안전합니다 — 자동 배포에서 기본값은 멈춤이어야 합니다." },

{ track:"devops", cat:"debug", k:"순환 의존을 못 보고 부분 배포한다",
  q:"의존 그래프로 배포 순서를 정합니다. 순환이 있으면 <code>null</code> 을 돌려줘야 하고, 준비된 노드가 여럿이면 <b>이름이 작은</b> 것부터입니다. 지금은 순환이 있어도 <b>일부만 담긴 순서</b>를 내놓아 절반만 배포됩니다.",
  src:"function deployOrder(deps) {\n  const names = Object.keys(deps).sort();\n  const done = [];\n  for (let pass = 0; pass < names.length; pass += 1) {\n    for (const n of names) {\n      if (done.includes(n)) continue;\n      if (deps[n].every(d => done.includes(d))) { done.push(n); break; }\n    }\n  }\n  return done;\n}",
  sol:"function deployOrder(deps) {\n  const names = Object.keys(deps).sort();\n  const done = [];\n  for (let pass = 0; pass < names.length; pass += 1) {\n    const next = names.find(n => !done.includes(n) && deps[n].every(d => done.includes(d)));\n    if (next === undefined) return null;\n    done.push(next);\n  }\n  return done.length === names.length ? done : null;\n}",
  tests:[["deployOrder({a:[], b:['a']})","['a','b']"],
         ["deployOrder({a:['b'], b:['a']})","null"],
         ["deployOrder({c:['a','b'], a:[], b:['a']})","['a','b','c']"],
         ["deployOrder({a:[]})","['a']"]],
  edge:[["deployOrder({})","[]"],
        ["deployOrder({a:['a']})","null"]],
  ex:"원인: 더 진행할 수 없을 때 <b>조용히 멈추고</b> 지금까지 담은 것을 돌려줍니다. 호출하는 쪽은 그것이 완전한 순서인 줄 알고 절반만 배포하는데, 그 상태가 가장 나쁩니다 — 새 버전과 옛 버전이 섞여 돕니다.\n해결: 한 바퀴에서 <b>배치할 노드를 못 찾으면</b> 그 자리에서 <code>null</code> 로 실패를 알립니다. 마지막에 개수까지 확인해 두면 이중으로 안전합니다.\n재발 방지: 위상 정렬의 실패는 '<b>순환이 있다</b>' 는 값진 정보입니다. 그냥 실패로 뭉개지 말고 어떤 노드들이 남았는지 함께 돌려주면 사람이 바로 고칠 수 있습니다. '부분 성공' 을 성공처럼 돌려주는 함수는 배포·마이그레이션·정산에서 특히 위험합니다." },

{ track:"devops", cat:"debug", k:"오류 예산을 가용률로 착각한다",
  q:"남은 <b>오류 예산</b>을 백분율로 구합니다. 예산은 <code>total × (1 − slo)</code> 건이고, 남은 비율은 그 예산 대비입니다. 0 아래로는 내려가지 않습니다. 지금은 예산을 절반 태웠는데도 <b>99% 남았다</b>고 나옵니다.",
  src:"function budgetLeftPct(slo, total, bad) {\n  return Math.round((1 - bad / total) * 1000) / 10;\n}",
  sol:"function budgetLeftPct(slo, total, bad) {\n  const budget = total * (1 - slo);\n  if (budget <= 0) return 0;\n  const left = (budget - bad) / budget * 100;\n  return Math.round(Math.max(0, left) * 10) / 10;\n}",
  tests:[["budgetLeftPct(0.99, 10000, 50)","50"],
         ["budgetLeftPct(0.99, 10000, 0)","100"],
         ["budgetLeftPct(0.99, 10000, 100)","0"],
         ["budgetLeftPct(0.99, 10000, 200)","0"]],
  edge:[["budgetLeftPct(0.999, 1000, 0)","100"],
        ["budgetLeftPct(1, 1000, 0)","0"]],
  ex:"원인: <code>1 - bad/total</code> 은 <b>가용률</b>이지 남은 예산이 아닙니다. SLO 99% 에 1만 건이면 예산은 100건인데, 50건을 태우면 가용률은 여전히 99.5% 라 '거의 안 썼다' 로 보입니다. 실제로는 <b>예산의 절반</b>을 쓴 것입니다.\n해결: 분모를 <b>예산</b>으로 바꿉니다. 예산이 0(SLO 100%)이면 남은 비율이 정의되지 않으므로 0 으로 두어 '여유 없음' 을 표현합니다.\n재발 방지: 오류 예산의 요점은 <b>작은 숫자를 크게 보이게</b> 만드는 것입니다. 99.9% 가용률은 안심되는 숫자지만 '이번 달 예산의 90% 소진' 은 행동을 부릅니다. 지표를 고를 때 '<b>어떤 행동을 유발하는가</b>' 를 기준으로 삼으세요 — 같은 사실을 다르게 표현한 두 숫자가 전혀 다른 결정을 만듭니다." },

];
