/* 운영체제 디버깅 12 — 커널이 하는 계산을 흉내 낸 코드의 어긋남을 고친다.
   전부 결정적이고 순수 JS 다. 검증:  node ver_dbgjs.cjs ./dbg_os.cjs */
module.exports = [

{ track:"os", cat:"debug", k:"FIFO 인데 최근 사용으로 옮긴다",
  q:"<b>FIFO</b> 페이지 교체의 페이지 폴트 수를 세는 함수입니다. FIFO 는 <b>들어온 순서</b>로만 내보내며, 적중해도 순서를 바꾸지 않습니다. 지금 값이 교재의 FIFO 결과와 다릅니다.",
  src:"function pageFaults(pages, frames) {\n  const mem = [];\n  let n = 0;\n  for (const p of pages) {\n    const at = mem.indexOf(p);\n    if (at >= 0) { mem.splice(at, 1); mem.push(p); continue; }\n    n += 1;\n    mem.push(p);\n    if (mem.length > frames) mem.shift();\n  }\n  return n;\n}",
  sol:"function pageFaults(pages, frames) {\n  const mem = [];\n  let n = 0;\n  for (const p of pages) {\n    if (mem.indexOf(p) >= 0) continue;\n    n += 1;\n    mem.push(p);\n    if (mem.length > frames) mem.shift();\n  }\n  return n;\n}",
  tests:[["pageFaults([1,2,3,4,1,2,5,1,2,3,4,5], 3)","9"],
         ["pageFaults([1,2,3,1,2,3], 3)","3"],
         ["pageFaults([1,1,1], 1)","1"],
         ["pageFaults([1,2,1,2], 1)","4"]],
  edge:[["pageFaults([], 3)","0"],
        ["pageFaults([1,2,3], 5)","3"]],
  ex:"🐛 원인: 적중했을 때 그 페이지를 <b>맨 뒤로 옮기는</b> 코드가 들어 있습니다. 그건 LRU 의 동작입니다. FIFO 는 '언제 들어왔는가' 만 보므로 적중은 <b>순서를 바꾸지 않습니다</b>. 짧은 참조열에서는 두 정책의 결과가 같아 잘 드러나지 않습니다.\n🔧 해결: 적중이면 아무것도 하지 않고 넘어갑니다. 프레임을 넘칠 때 <code>shift</code> 로 가장 먼저 들어온 것을 내보내는 부분은 그대로입니다.\n🛡 재발 방지: 교체 정책은 '<b>무엇을 기준으로 내보내는가</b>' 한 줄로 갈립니다 — FIFO 는 도착 시각, LRU 는 마지막 사용 시각, LFU 는 사용 횟수. 두 정책이 다른 답을 내는 참조열(위 첫 테스트)을 골라 두면 구현을 바꿔도 정책이 뒤바뀌지 않습니다. FIFO 는 프레임을 늘렸는데 폴트가 늘어나는 <b>벨레이디 이상</b>이 나타나는 정책이기도 합니다." },

{ track:"os", cat:"debug", k:"SJF 인데 도착 순서로 처리한다",
  q:"모든 작업이 0 시각에 도착했을 때 <b>최단 작업 우선</b>의 총 대기 시간을 구합니다. 지금 값이 항상 FCFS 와 같게 나옵니다.",
  src:"function sjfTotalWait(bursts) {\n  let clock = 0, wait = 0;\n  for (const b of bursts) {\n    wait += clock;\n    clock += b;\n  }\n  return wait;\n}",
  sol:"function sjfTotalWait(bursts) {\n  let clock = 0, wait = 0;\n  for (const b of bursts.slice().sort((x, y) => x - y)) {\n    wait += clock;\n    clock += b;\n  }\n  return wait;\n}",
  tests:[["sjfTotalWait([3,1,2])","4"],
         ["sjfTotalWait([1,2,3])","4"],
         ["sjfTotalWait([5,5])","5"],
         ["sjfTotalWait([10,1,1])","3"]],
  edge:[["sjfTotalWait([])","0"],
        ["sjfTotalWait([7])","0"]],
  ex:"🐛 원인: 정렬이 빠졌습니다. SJF 의 전부가 '<b>짧은 것부터</b>' 인데 그 한 줄이 없으면 FCFS 와 같아집니다. 입력이 우연히 오름차순이면 결과도 같아 테스트가 통과합니다 — 위 두 번째 테스트가 정확히 그 함정입니다.\n🔧 해결: 처리 시간 오름차순으로 정렬한 뒤 누적합을 셉니다. <code>slice()</code> 로 복사해 <b>호출자의 배열을 바꾸지 않는</b> 것도 함께 지킵니다.\n🛡 재발 방지: SJF 가 평균 대기 시간을 최소로 만든다는 것은 <b>증명된 성질</b>입니다(교환 논법). 그래서 '어떤 순서로 바꿔도 이보다 작아지지 않는다' 를 성질 테스트로 걸 수 있습니다. 대신 긴 작업이 계속 밀리는 <b>기아</b>가 생기므로 실제 스케줄러는 대기 시간에 따라 우선순위를 올립니다(에이징)." },

{ track:"os", cat:"debug", k:"이미 정렬된 주소를 또 올린다",
  q:"주소를 <code>align</code> 의 배수로 <b>올림</b>하는 함수입니다. 이미 정렬된 주소는 그대로여야 하는데, 한 칸 더 올라가 <b>매핑마다 한 페이지씩</b> 낭비됩니다.",
  src:"function alignUp(addr, align) {\n  return addr + (align - addr % align);\n}",
  sol:"function alignUp(addr, align) {\n  return Math.ceil(addr / align) * align;\n}",
  tests:[["alignUp(0, 8)","0"],
         ["alignUp(1, 8)","8"],
         ["alignUp(8, 8)","8"],
         ["alignUp(9, 8)","16"]],
  edge:[["alignUp(4096, 4096)","4096"],
        ["alignUp(1, 1)","1"]],
  ex:"🐛 원인: 이미 배수인 주소는 <code>addr % align</code> 이 0 이라 <code>align</code> 을 통째로 더해 버립니다. 대부분의 주소는 정렬돼 있지 않아 잘 맞는 것처럼 보이고, <b>정확히 경계에 놓인</b> 주소에서만 틀립니다 — 그리고 그 경우가 실전에서 가장 흔합니다.\n🔧 해결: <code>Math.ceil(addr / align) * align</code> 로 적으면 경계가 저절로 처리됩니다. 2의 거듭제곱 정렬이라면 <code>(addr + align - 1) &amp; ~(align - 1)</code> 이 관용구입니다.\n🛡 재발 방지: '올림' 을 직접 계산할 때는 <b>이미 맞아떨어지는 값</b>을 첫 테스트로 두세요. 같은 함정이 페이지 수 계산·버퍼 크기 산정·다음 정각 시각 계산에도 있습니다. 한 칸씩 낭비되는 버그는 기능이 멀쩡해 보여서 메모리 사용량 그래프로만 드러납니다." },

{ track:"os", cat:"debug", k:"필요한 페이지 수를 내림한다",
  q:"바이트 수를 담는 데 필요한 <b>페이지 수</b>를 구합니다. 0 바이트는 0 페이지입니다. 지금은 매핑이 마지막 몇 바이트를 담지 못해 세그멘테이션 폴트가 납니다.",
  src:"function pagesFor(bytes, pageSize) {\n  return Math.floor(bytes / pageSize);\n}",
  sol:"function pagesFor(bytes, pageSize) {\n  return Math.ceil(bytes / pageSize);\n}",
  tests:[["pagesFor(1, 4096)","1"],
         ["pagesFor(4096, 4096)","1"],
         ["pagesFor(4097, 4096)","2"],
         ["pagesFor(0, 4096)","0"]],
  edge:[["pagesFor(8192, 4096)","2"],
        ["pagesFor(4095, 4096)","1"]],
  ex:"🐛 원인: 자원을 <b>쪼갤 수 없을 때</b>는 언제나 올림입니다. 내림하면 1 바이트를 담는 데 0 페이지가 나오고, 그 매핑을 그대로 쓰면 마지막 조각이 매핑되지 않은 영역을 가리킵니다.\n🔧 해결: <code>Math.ceil</code> 한 글자입니다. 0 바이트가 0 페이지인 것은 올림에서 저절로 나옵니다.\n🛡 재발 방지: '<b>몇 개가 필요한가</b>' 를 묻는 계산은 페이지·블록·버퍼·컨테이너·배치 크기까지 모두 같은 꼴입니다. 반대로 '<b>몇 개가 들어가는가</b>' 는 내림입니다. 두 질문을 함수 이름에 드러내면(<code>pagesFor</code> 와 <code>itemsPerPage</code>) 헷갈리지 않습니다." },

{ track:"os", cat:"debug", k:"라운드로빈 마지막 조각을 안 센다",
  q:"양자 <code>q</code> 로 라운드로빈을 돌 때 각 작업이 <b>몇 번 스케줄되는지</b>의 총합을 구합니다. 지금은 컨텍스트 스위치 예상치가 실제보다 적게 나옵니다.",
  src:"function rrTurns(bursts, q) {\n  return bursts.reduce((s, b) => s + Math.floor(b / q), 0);\n}",
  sol:"function rrTurns(bursts, q) {\n  return bursts.reduce((s, b) => s + Math.ceil(b / q), 0);\n}",
  tests:[["rrTurns([5], 2)","3"],
         ["rrTurns([4], 2)","2"],
         ["rrTurns([1,1], 2)","2"],
         ["rrTurns([], 2)","0"]],
  edge:[["rrTurns([3,3], 3)","2"],
        ["rrTurns([1], 10)","1"]],
  ex:"🐛 원인: 내림하면 <b>양자보다 짧은 마지막 조각</b>이 빠집니다. 5 를 양자 2 로 돌면 2+2+1 로 세 번 스케줄되는데 내림은 2 로 셉니다. 작업이 양자의 배수일 때만 맞아서, 딱 떨어지는 예제로 만든 테스트는 통과합니다.\n🔧 해결: <code>Math.ceil</code> 입니다. 양자보다 짧은 작업도 <b>한 번은</b> 스케줄된다는 점이 올림에서 자연스럽게 나옵니다.\n🛡 재발 방지: 라운드로빈에서 양자를 정하는 감각이 이 계산에 있습니다 — 양자가 작으면 응답은 빨라지지만 스위치 횟수가 늘어 오버헤드가 커지고, 크면 FCFS 에 가까워집니다. 스위치 한 번의 비용(수 마이크로초)과 곱해 보면 어느 쪽이 이득인지 <b>숫자로</b> 답할 수 있습니다." },

{ track:"os", cat:"debug", k:"파일 디스크립터 수가 음수가 된다",
  q:"<code>'open:3'</code>·<code>'close:3'</code> 형태의 이벤트 목록에서 <b>아직 열려 있는</b> 디스크립터 수를 셉니다. 모르는 fd 를 닫는 이벤트는 무시하고, 같은 fd 를 두 번 열어도 하나입니다. 지금은 음수가 나와 누수 경보가 무의미해졌습니다.",
  src:"function openCount(events) {\n  let n = 0;\n  for (const e of events) n += e.startsWith('open') ? 1 : -1;\n  return n;\n}",
  sol:"function openCount(events) {\n  const live = new Set();\n  for (const e of events) {\n    const [kind, fd] = e.split(':');\n    if (kind === 'open') live.add(fd);\n    else live.delete(fd);\n  }\n  return live.size;\n}",
  tests:[["openCount(['open:1','close:1'])","0"],
         ["openCount(['open:1','open:2','close:1'])","1"],
         ["openCount(['close:9'])","0"],
         ["openCount(['open:1','open:1'])","1"]],
  edge:[["openCount([])","0"],
        ["openCount(['open:1','close:1','close:1'])","0"]],
  ex:"🐛 원인: 숫자 하나로 세면 <b>무엇이 열려 있는지</b>는 모른 채 개수만 셉니다. 중복 열기·모르는 fd 닫기·이중 닫기가 섞이면 값이 실제와 어긋나고, 심지어 음수가 됩니다. 음수 누수 카운터는 경보를 영영 울리지 않게 만듭니다.\n🔧 해결: <b>집합</b>으로 실제 열린 fd 를 들고 있습니다. 개수는 그 집합의 크기입니다 — 중복과 잘못된 닫기가 저절로 처리됩니다.\n🛡 재발 방지: '개수만 세는' 최적화는 이벤트가 <b>정확히 한 번씩 짝을 이룰 때만</b> 맞습니다. 재시도·중복 전달이 있는 곳에서는 언제나 식별자를 들고 있어야 합니다. 그리고 누수를 볼 때는 개수보다 '<b>가장 오래 열려 있는 fd</b>' 가 원인을 훨씬 빨리 알려 줍니다." },

{ track:"os", cat:"debug", k:"줄이 청크 경계에서 잘린다",
  q:"스트림에서 읽은 조각들을 이어 <b>완성된 줄</b>만 돌려주는 함수입니다. 마지막에 남은 미완성 줄은 버립니다. 지금은 로그 한 줄이 <b>두 줄로 쪼개져</b> 파서가 깨집니다.",
  src:"function completeLines(chunks) {\n  return chunks.flatMap(c => c.split('\\n')).filter(Boolean);\n}",
  sol:"function completeLines(chunks) {\n  const all = chunks.join('');\n  const lines = all.split('\\n');\n  lines.pop();\n  return lines.filter(Boolean);\n}",
  tests:[["completeLines(['a\\nb','c\\nd\\n'])","['a','bc','d']"],
         ["completeLines(['hello\\n'])","['hello']"],
         ["completeLines(['no newline'])","[]"],
         ["completeLines(['x\\ny','z'])","['x']"]],
  edge:[["completeLines([])","[]"],
        ["completeLines(['\\n\\n'])","[]"]],
  ex:"🐛 원인: 조각은 <b>줄 경계에서 잘리지 않습니다</b>. 조각마다 따로 나누면 경계를 걸친 <code>'b' + 'c'</code> 가 두 줄이 되고, 아직 끝나지 않은 마지막 줄도 완성된 줄처럼 흘러나갑니다. 작은 로그로 테스트하면 조각이 하나뿐이라 통과합니다.\n🔧 해결: <b>먼저 이어 붙이고</b> 나서 나눕니다. 마지막 조각은 개행으로 끝나지 않았다면 미완성이므로 <code>pop</code> 으로 떼어 냅니다 — 개행으로 끝났다면 그 자리는 빈 문자열이라 버려도 맞습니다.\n🛡 재발 방지: 스트림 파서는 <b>남은 조각(buffer)</b>을 다음 호출로 넘기는 구조가 정석입니다. TCP 도 같은 이유로 '메시지 경계를 보장하지 않는다' 고 말합니다 — 길이 접두사나 구분자로 <b>스스로 경계를 만들어야</b> 합니다." },

{ track:"os", cat:"debug", k:"SCAN 이 헤드 방향을 무시한다",
  q:"디스크 <b>SCAN(엘리베이터)</b> 스케줄링입니다. 헤드는 위쪽으로 먼저 움직이며 <code>head</code> 이상 요청을 <b>오름차순</b>으로 처리하고, 끝까지 간 뒤 남은 요청을 <b>내림차순</b>으로 처리합니다. 지금은 그냥 번호순이라 헤드가 위아래로 튑니다.",
  src:"function scanOrder(head, queue, up) {\n  return queue.slice().sort((a, b) => a - b);\n}",
  sol:"function scanOrder(head, queue, up) {\n  const hi = queue.filter(x => x >= head).sort((a, b) => a - b);\n  const lo = queue.filter(x => x < head).sort((a, b) => b - a);\n  return up ? hi.concat(lo) : lo.concat(hi);\n}",
  tests:[["scanOrder(50, [10,20,60,80], true)","[60,80,20,10]"],
         ["scanOrder(50, [10,20,60,80], false)","[20,10,60,80]"],
         ["scanOrder(50, [50,60], true)","[50,60]"],
         ["scanOrder(0, [5,1,3], true)","[1,3,5]"]],
  edge:[["scanOrder(50, [], true)","[]"],
        ["scanOrder(100, [10,20], true)","[20,10]"]],
  ex:"🐛 원인: SCAN 의 핵심은 <b>현재 위치와 진행 방향</b>인데 둘 다 안 봤습니다. 번호순으로만 처리하면 헤드가 매번 처음으로 되돌아가 탐색 거리가 크게 늘어납니다. 요청이 전부 헤드 위쪽에 있으면 우연히 같은 답이 나옵니다 — 위 네 번째 테스트가 그 경우입니다.\n🔧 해결: 헤드 기준으로 위·아래를 갈라 각각 정렬하고, 진행 방향에 따라 이어 붙입니다. 헤드와 같은 위치의 요청은 위쪽 묶음에 넣습니다.\n🛡 재발 방지: 상태(위치)와 방향에 따라 결과가 달라지는 알고리즘은 <b>상태를 인자로 받아</b> 순수 함수로 만들면 테스트가 쉬워집니다. SCAN 이 SSTF 보다 나은 이유가 '가까운 것만 먼저' 하면 먼 요청이 굶기 때문이라는 점도 함께 기억하세요 — 평균과 최악은 다른 목표입니다." },

{ track:"os", cat:"debug", k:"CPU 사용률을 누적값으로 잰다",
  q:"<code>/proc/stat</code> 스타일의 누적 카운터 두 스냅숏으로 <b>구간 CPU 사용률</b>(%)을 소수 첫째 자리까지 구합니다. 전체 증가분이 0 이면 0 입니다. 지금은 부팅 이후 평균이 나와 <b>변화가 보이지 않습니다</b>.",
  src:"function cpuPct(prev, cur) {\n  return Math.round((1 - cur.idle / cur.total) * 1000) / 10;\n}",
  sol:"function cpuPct(prev, cur) {\n  const dt = cur.total - prev.total;\n  if (dt <= 0) return 0;\n  const di = cur.idle - prev.idle;\n  return Math.round((1 - di / dt) * 1000) / 10;\n}",
  tests:[["cpuPct({idle:100, total:200}, {idle:150, total:300})","50"],
         ["cpuPct({idle:100, total:200}, {idle:100, total:300})","100"],
         ["cpuPct({idle:100, total:200}, {idle:200, total:300})","0"],
         ["cpuPct({idle:100, total:200}, {idle:100, total:200})","0"]],
  edge:[["cpuPct({idle:0, total:0}, {idle:25, total:100})","75"],
        ["cpuPct({idle:10, total:20}, {idle:10, total:21})","100"]],
  ex:"🐛 원인: <code>/proc/stat</code> 의 값은 <b>부팅 이후 누적</b>입니다. 한 스냅숏만 보면 '지금까지의 평균' 이라 며칠 돌아간 서버에서는 사실상 상수가 되어, 갑자기 100% 로 튀어도 그래프가 꿈쩍하지 않습니다.\n🔧 해결: 두 스냅숏의 <b>증가분끼리</b> 나눕니다. 두 시점이 같으면 증가분이 0 이라 나눗셈이 <code>NaN</code> 이 되므로 먼저 막습니다.\n🛡 재발 방지: 누적 카운터(<code>counter</code>)와 현재값(<code>gauge</code>)은 다루는 법이 다릅니다 — 카운터는 <b>반드시 증가분</b>으로, 게이지는 값 그대로. 그리고 카운터는 재시작하면 0 으로 돌아가므로 증가분이 음수면 <b>리셋</b>으로 보고 그 구간을 버려야 합니다. 지표 파이프라인의 <code>rate()</code> 가 하는 일이 정확히 이것입니다." },

{ track:"os", cat:"debug", k:"루트를 넘는 .. 를 조용히 삼킨다",
  q:"절대 경로를 정규화합니다. <code>.</code> 은 없애고 <code>..</code> 은 한 단계 올라가되, <b>루트 위로 올라가려는 경로는 <code>null</code> 로 거절</b>해야 합니다. 지금은 그런 경로도 그럴듯한 값으로 바뀌어, 이 함수를 믿고 만든 접근 검사가 뚫립니다.",
  src:"function normPath(p) {\n  const out = [];\n  for (const seg of String(p).split('/')) {\n    if (seg === '' || seg === '.') continue;\n    if (seg === '..') { out.pop(); continue; }\n    out.push(seg);\n  }\n  return '/' + out.join('/');\n}",
  sol:"function normPath(p) {\n  const out = [];\n  for (const seg of String(p).split('/')) {\n    if (seg === '' || seg === '.') continue;\n    if (seg === '..') {\n      if (!out.length) return null;\n      out.pop();\n      continue;\n    }\n    out.push(seg);\n  }\n  return '/' + out.join('/');\n}",
  tests:[["normPath('/a/b/../c')","'/a/c'"],
         ["normPath('/../x')","null"],
         ["normPath('/a/./b')","'/a/b'"],
         ["normPath('/a/b/../..')","'/'"]],
  edge:[["normPath('/')","'/'"],
        ["normPath('/a/../..')","null"]],
  ex:"🐛 원인: 빈 배열에서 <code>pop</code> 은 <b>조용히 아무 일도 하지 않습니다</b>. 그래서 <code>/../x</code> 가 <code>/x</code> 라는 멀쩡해 보이는 값이 되고, '루트를 넘으려 했다' 는 사실이 <b>사라집니다</b>. 결과 문자열만 보면 정상이라 리뷰에서도 지나칩니다.\n🔧 해결: 올라갈 곳이 없는데 <code>..</code> 를 만나면 <b>거절</b>합니다. 정규화 함수가 '조용히 고쳐 주는' 대신 '이상하다고 말하는' 쪽으로 계약을 바꾸는 것이 요점입니다.\n🛡 재발 방지: 보안 검사에서 <b>조용한 보정</b>은 우회의 발판이 됩니다. 잘못된 입력은 고쳐 주지 말고 거절하세요. 그리고 경로 검사는 정규화만으로 끝나지 않습니다 — 심볼릭 링크까지 푸는 <code>realpath</code> 로 확인하거나, 사용자 문자열에 구분자와 <code>..</code> 가 있으면 <b>아예 받지 않는</b> 편이 더 안전합니다." },

{ track:"os", cat:"debug", k:"세마포어가 음수로 내려간다",
  q:"카운팅 세마포어에서 <code>n</code> 개를 가져간 뒤 남은 수를 돌려줍니다. 남은 수가 모자라면 <code>null</code> 로 <b>거절</b>해야 합니다. 지금은 한도를 넘겨 자원이 배정되어 커넥션 풀이 터집니다.",
  src:"function semTake(count, n) {\n  return count - n;\n}",
  sol:"function semTake(count, n) {\n  return n <= count ? count - n : null;\n}",
  tests:[["semTake(5, 2)","3"],
         ["semTake(5, 5)","0"],
         ["semTake(5, 6)","null"],
         ["semTake(0, 1)","null"]],
  edge:[["semTake(0, 0)","0"],
        ["semTake(3, 0)","3"]],
  ex:"🐛 원인: 계약에 '<b>모자라면 거절</b>' 이 적혀 있는데 코드는 그냥 뺍니다. 음수 카운트는 이후 모든 판정을 망가뜨립니다 — 반납할 때마다 0 으로 돌아오지 못해 한도가 영구히 늘어난 것처럼 동작합니다.\n🔧 해결: 가져가기 전에 <b>충분한지 먼저 봅니다</b>. 성공과 실패를 서로 다른 타입(<code>number</code> 와 <code>null</code>)으로 돌려주면 호출자가 확인을 빠뜨리기 어렵습니다.\n🛡 재발 방지: 실제 세마포어에서는 '<b>검사와 감소가 하나의 원자적 연산</b>' 이라는 점이 핵심입니다. 두 단계로 나뉘면 그 사이에 다른 스레드가 끼어들어 한도를 넘깁니다. 이 함수는 순수 계산이지만, 같은 로직을 공유 상태 위에 올릴 때는 반드시 원자적 연산(CAS·Redis 스크립트)으로 감싸세요." },

{ track:"os", cat:"debug", k:"매핑이 걸치는 페이지 수를 길이로만 센다",
  q:"<code>offset</code> 에서 <code>length</code> 바이트를 매핑할 때 <b>실제로 걸치는 페이지 수</b>를 구합니다. 길이가 0 이면 0 입니다. 지금은 페이지 경계를 걸치는 매핑에서 <b>한 페이지가 모자랍니다</b>.",
  src:"function mappedPages(offset, length, pageSize) {\n  return Math.ceil(length / pageSize);\n}",
  sol:"function mappedPages(offset, length, pageSize) {\n  if (length <= 0) return 0;\n  const first = Math.floor(offset / pageSize);\n  const last = Math.floor((offset + length - 1) / pageSize);\n  return last - first + 1;\n}",
  tests:[["mappedPages(0, 4096, 4096)","1"],
         ["mappedPages(1, 4096, 4096)","2"],
         ["mappedPages(4095, 2, 4096)","2"],
         ["mappedPages(0, 0, 4096)","0"]],
  edge:[["mappedPages(8192, 4096, 4096)","1"],
        ["mappedPages(100, 10, 4096)","1"]],
  ex:"🐛 원인: 길이만 보면 <b>시작 위치가 페이지 안 어디인지</b>를 놓칩니다. 4096 바이트라도 1 번지에서 시작하면 두 페이지에 걸칩니다. 매핑이 페이지 경계에 맞춰진 예제만 테스트하면 끝까지 안 보입니다.\n🔧 해결: 첫 페이지 번호와 <b>마지막 바이트</b>의 페이지 번호를 구해 차이에 1 을 더합니다. <code>offset + length</code> 가 아니라 <code>offset + length - 1</code> 인 것이 핵심입니다 — 딱 경계에서 끝나는 매핑이 한 페이지를 더 세지 않습니다.\n🛡 재발 방지: '<b>걸치는 개수</b>' 는 캐시 라인, 디스크 블록, 시간 버킷, 달력 주 계산까지 같은 꼴입니다. 언제나 '마지막 요소' 기준으로 세고, 길이 0 은 따로 갈라 두세요. 이 계산이 틀리면 성능만 나빠지는 것이 아니라 <b>버퍼 경계를 넘어 읽는</b> 버그가 됩니다." },

];
