/* 아두이노 디버깅 12 — 책상에서는 되는데 며칠 돌리면 어긋나는 자리.
   계약
     1. src 는 문법 오류가 아니고 TODO 도 없다. 작은 입력에서는 통과하기도 한다.
     2. src 는 tests 중 최소 하나를 실패한다.
     3. sol 은 tests + edge 를 전부 통과한다.
     4. 전부 결정적 — 현재 시각·난수는 쓰지 않는다(시각은 인자로 받는다).
   검증:  node ver_dbgjs.cjs ./dbg_arduino.cjs */
module.exports = [

/* ── 1교시 · 값을 읽고 셈하는 곳 ───────────────────────────────────── */

{ track:"arduino", cat:"debug", k:"ADC 최댓값을 1024 로 나눈다",
  q:"10비트 ADC 값(<code>0~1023</code>)을 <b>밀리볼트</b>로 바꿉니다(기준 전압 5V). <code>1023</code> 은 <b>정확히 5000</b> 이어야 하고 <b>반올림</b>합니다. 그런데 전압이 늘 조금씩 낮게 나오고, 최대로 올려도 5V 에 못 미칩니다.",
  src:"function toMilliVolts(raw) {\n  return Math.floor(raw * 5000 / 1024);\n}",
  sol:"function toMilliVolts(raw) {\n  return Math.round(raw * 5000 / 1023);\n}",
  tests:[["toMilliVolts(1023)","5000"],
         ["toMilliVolts(512)","2502"],
         ["toMilliVolts(1)","5"],
         ["toMilliVolts(0)","0"]],
  edge:[["toMilliVolts(2)","10"],
        ["toMilliVolts(1022)","4995"]],
  ex:"🐛 원인: 두 가지가 겹쳤습니다. ① ADC 가 낼 수 있는 <b>가장 큰 값이 1023</b> 이므로 그 값이 기준 전압에 대응합니다 — 1024 로 나누면 최댓값이 4995mV 에서 멈춥니다. ② <code>floor</code> 는 언제나 <b>아래로</b> 버리므로 오차가 한쪽으로만 쌓입니다. 둘 다 한 눈금(5mV) 안쪽이라 멀티미터로 대충 보면 안 보입니다.\n🔧 해결: <code>1023</code> 으로 나누고 <b>반올림</b>합니다. 그러면 양 끝(0 과 최대)이 정확히 맞고 오차도 좌우로 고르게 퍼집니다.\n🛡 재발 방지: '<b>몇 단계인가</b>' 와 '<b>가장 큰 값이 얼마인가</b>' 는 하나 차이입니다 — 10비트는 1024 <b>단계</b>이고 최댓값은 1023 입니다. 변환 함수는 언제나 <b>양 끝값</b>을 테스트에 넣으세요. 그리고 정수 나눗셈을 쓸 수밖에 없다면 <code>(raw * 5000 + 511) / 1023</code> 처럼 <b>반올림을 손으로</b> 넣습니다." },

{ track:"arduino", cat:"debug", k:"범위를 벗어난 값이 그대로 흘러간다",
  q:"입력 범위의 값을 출력 범위로 <b>비례 변환</b>하고 <b>반올림</b>합니다. 입력이 범위를 벗어나면 <b>가까운 끝값으로 자릅니다</b>. 그런데 센서가 튀면 PWM 에 <code>255</code> 를 넘는 값이나 <b>음수</b>가 들어가 LED 가 꺼지거나 모터가 역회전합니다.",
  src:"function mapRange(x, inMin, inMax, outMin, outMax) {\n  return Math.round((x - inMin) * (outMax - outMin) / (inMax - inMin) + outMin);\n}",
  sol:"function mapRange(x, inMin, inMax, outMin, outMax) {\n  const v = Math.round((x - inMin) * (outMax - outMin) / (inMax - inMin) + outMin);\n  const lo = Math.min(outMin, outMax), hi = Math.max(outMin, outMax);\n  return Math.min(hi, Math.max(lo, v));\n}",
  tests:[["mapRange(1200, 0, 1023, 0, 255)","255"],
         ["mapRange(-10, 0, 1023, 0, 255)","0"],
         ["mapRange(0, 0, 1023, 0, 255)","0"],
         ["mapRange(1023, 0, 1023, 0, 255)","255"]],
  edge:[["mapRange(512, 0, 1023, 0, 255)","128"],
        ["mapRange(500, 0, 1000, 100, 0)","50"]],
  ex:"🐛 원인: 비례식은 <b>범위 밖에서도 그대로 계산됩니다</b>. 입력이 범위를 넘으면 출력도 그만큼 넘고, 그 값이 <code>analogWrite</code> 로 가면 하위 8비트만 남아 <b>엉뚱한 밝기</b>가 됩니다. 음수는 부호가 뒤집혀 모터 방향까지 바꿉니다. 센서를 손으로 천천히 돌려 보는 시험에서는 절대 범위를 안 넘습니다.\n🔧 해결: 계산한 뒤 <b>출력 범위로 자릅니다</b>. 출력 범위가 거꾸로(<code>100 → 0</code>) 주어질 수 있으므로 <b>최소·최대를 따로 구해</b> 자릅니다.\n🛡 재발 방지: 하드웨어로 나가는 값은 <b>나가기 직전에 자르는</b> 것을 규칙으로 두세요 — 핀에 쓰는 함수를 한 겹 감싸 그 안에서 자르면 호출하는 쪽이 실수해도 안전합니다. 테스트에는 <b>범위 밖 입력</b>과 <b>거꾸로 된 출력 범위</b>를 반드시 넣습니다." },

{ track:"arduino", cat:"debug", k:"창이 차기 전에도 창 크기로 나눈다",
  q:"센서 값의 <b>이동 평균</b>을 냅니다(반올림). 아직 표본이 <code>n</code> 개가 안 됐으면 <b>지금까지 받은 개수</b>로 나눠야 합니다. 그런데 전원을 켠 직후 값이 <b>0 에서 서서히 올라오는</b> 것처럼 보입니다.",
  src:"function movingAvg(samples, n) {\n  const out = [];\n  let sum = 0;\n  for (let i = 0; i < samples.length; i += 1) {\n    sum += samples[i];\n    if (i >= n) sum -= samples[i - n];\n    out.push(Math.round(sum / n));\n  }\n  return out;\n}",
  sol:"function movingAvg(samples, n) {\n  const out = [];\n  let sum = 0;\n  for (let i = 0; i < samples.length; i += 1) {\n    sum += samples[i];\n    if (i >= n) sum -= samples[i - n];\n    const k = Math.min(i + 1, n);\n    out.push(Math.round(sum / k));\n  }\n  return out;\n}",
  tests:[["movingAvg([10,20], 3)","[10,15]"],
         ["movingAvg([3,3,3], 3)","[3,3,3]"],
         ["movingAvg([100], 4)","[100]"],
         ["movingAvg([1,2,3,4], 2)","[1,2,3,4]"]],
  edge:[["movingAvg([], 3)","[]"],
        ["movingAvg([5,5,5,5], 2)","[5,5,5,5]"]],
  ex:"🐛 원인: 창이 아직 <b>다 차지 않았는데</b> 창 크기로 나눕니다. 처음 <code>n-1</code> 개의 평균은 실제보다 작게 나오고, 그 구간이 마치 '<b>천천히 안정되는 센서</b>' 처럼 보여 원인을 하드웨어에서 찾게 됩니다. 표본이 충분히 쌓인 뒤부터는 완벽히 맞습니다.\n🔧 해결: 나눌 개수를 <code>Math.min(i + 1, n)</code> 으로 잡습니다. 창이 차기 전에는 <b>받은 만큼</b>으로 나눕니다.\n🛡 재발 방지: 다른 방법도 있습니다 — 첫 표본으로 창을 <b>미리 채워 두면</b>(prime) 처음부터 정상값이 나옵니다. 어느 쪽이든 '<b>켜자마자 첫 몇 개</b>' 를 테스트에 넣으세요. 필터의 과도 구간은 실제로 존재하지만, <b>버그로 생긴 과도 구간</b>과는 구분해야 합니다." },

{ track:"arduino", cat:"debug", k:"16비트 누산기가 조용히 넘친다",
  q:"ADC 표본들을 <b>모두 더합니다</b>(평균을 내기 전 단계). 표본이 몇 개일 때는 맞는데, <b>수십 개 이상</b> 모으면 합계가 갑자기 작아지고 평균이 튑니다.",
  src:"function sumAdc(samples) {\n  let sum = 0;\n  for (const v of samples) sum = (sum + v) & 0xFFFF;\n  return sum;\n}",
  sol:"function sumAdc(samples) {\n  let sum = 0;\n  for (const v of samples) sum += v;\n  return sum;\n}",
  tests:[["sumAdc(new Array(100).fill(1023))","102300"],
         ["sumAdc(new Array(65).fill(1023))","66495"],
         ["sumAdc(new Array(200).fill(500))","100000"],
         ["sumAdc([1,2,3])","6"]],
  edge:[["sumAdc([])","0"],
        ["sumAdc(new Array(64).fill(1023))","65472"]],
  ex:"🐛 원인: 누산기가 <b>16비트</b>(<code>uint16_t</code>)입니다. 표본 하나가 최대 1023 이므로 <b>64 개까지</b>(65,472)는 담기지만 <b>65 개째</b>에 65,536 을 넘어 0 부터 다시 셉니다. 경고도 예외도 없이 값만 작아지므로, 평균이 갑자기 뛰는 현상만 보입니다. 8비트 마이크로컨트롤러에서 <code>int</code> 는 <b>16비트</b>라는 점이 함정입니다.\n🔧 해결: 누산기를 <b>32비트</b>(<code>uint32_t</code>·<code>long</code>)로 잡습니다. 1023 × 65,536 표본까지 견딥니다.\n🛡 재발 방지: 곱하거나 누적하는 자리마다 '<b>가장 큰 값이 몇인가</b>' 를 손으로 계산해 주석에 적어 두세요. AVR 에서 <code>1000L * x</code> 처럼 <b>상수에 <code>L</code> 을 붙여</b> 계산 폭을 올리는 것도 같은 이유입니다. 테스트에는 <b>넘치는 개수</b>의 표본을 반드시 하나 넣습니다." },

{ track:"arduino", cat:"debug", k:"임계값을 같은지로 판정한다",
  q:"센서 값이 임계값을 <b>아래에서 위로 넘어선 순간</b>에만 <code>true</code> 를 냅니다(이전 값 &lt; 임계, 현재 값 ≥ 임계). 그런데 값이 임계를 지나가도 <b>거의 반응하지 않고</b>, 어쩌다 한 번만 걸립니다.",
  src:"function crossed(prev, cur, th) {\n  return cur === th;\n}",
  sol:"function crossed(prev, cur, th) {\n  return prev < th && cur >= th;\n}",
  tests:[["crossed(0.1, 0.3, 0.2)","true"],
         ["crossed(0.2, 0.2, 0.2)","false"],
         ["crossed(0.05, 0.1 + 0.1, 0.2)","true"],
         ["crossed(0.3, 0.4, 0.2)","false"]],
  edge:[["crossed(0.5, 0.1, 0.2)","false"],
        ["crossed(0.1, 0.2, 0.2)","true"]],
  ex:"🐛 원인: 아날로그 값이 임계값과 <b>정확히 같아지는 일</b>은 거의 없습니다. 게다가 부동소수로는 <code>0.1 + 0.1</code> 조차 <code>0.2</code> 와 <b>같지 않습니다</b>(0.20000000000000004). 그래서 <code>===</code> 검사는 사실상 영원히 거짓이고, 어쩌다 걸리면 그것도 우연입니다. 또한 '넘어선 <b>순간</b>' 이라는 뜻이 코드에 없어 임계 위에 머무는 동안 계속 참이 될 수도 있습니다.\n🔧 해결: <b>이전 값과 현재 값</b>을 함께 보고 <code>prev &lt; th &amp;&amp; cur &gt;= th</code> 로 적습니다. 경계를 <b>구간으로</b> 다루므로 부동소수 오차에도 흔들리지 않습니다.\n🛡 재발 방지: 실수 비교에 <code>==</code> 를 쓰지 마세요 — 크기 비교(<code>&lt;</code>·<code>&gt;=</code>)나 오차 허용(<code>Math.abs(a-b) &lt; eps</code>)으로 바꿉니다. 그리고 센서 잡음으로 임계 근처에서 값이 떨릴 수 있으니, 올라갈 때와 내려갈 때 임계를 다르게 두는 <b>히스테리시스</b>를 함께 고려하세요." },

{ track:"arduino", cat:"debug", k:"풀업 입력은 눌렀을 때 0 이다",
  q:"버튼이 눌렸는지 판정합니다. <code>pullup</code> 회로는 <b>눌렸을 때 0</b>, <code>pulldown</code> 회로는 <b>눌렸을 때 1</b> 입니다. 모르는 회로면 <code>false</code> 입니다. 그런데 내부 풀업을 켠 보드에서 <b>손을 안 댔는데 계속 눌린 것</b>으로 나옵니다.",
  src:"function pressed(raw, mode) {\n  return raw === 1;\n}",
  sol:"function pressed(raw, mode) {\n  if (mode === 'pullup') return raw === 0;\n  if (mode === 'pulldown') return raw === 1;\n  return false;\n}",
  tests:[["pressed(0, 'pullup')","true"],
         ["pressed(1, 'pullup')","false"],
         ["pressed(1, 'floating')","false"],
         ["pressed(1, 'pulldown')","true"]],
  edge:[["pressed(0, 'pulldown')","false"],
        ["pressed(0, 'floating')","false"]],
  ex:"🐛 원인: '<b>1 이면 눌림</b>' 은 풀다운 회로에서만 맞습니다. <code>INPUT_PULLUP</code> 은 평소에 핀을 <b>HIGH 로 끌어올려</b> 두고, 버튼이 그 핀을 GND 에 붙여 <b>LOW 로 떨어뜨립니다</b> — 논리가 정확히 반대입니다. 배선을 바꾸면 코드도 바뀌어야 하는데 코드에는 그 전제가 안 적혀 있습니다.\n🔧 해결: 회로 방식을 <b>인자로 받아</b> 그에 맞게 판정합니다. 모르는 값은 <b>눌리지 않음</b>으로 두어, 새 방식이 늘어도 안전한 쪽으로 떨어집니다.\n🛡 재발 방지: 외부 풀업/풀다운 저항이 없는 <b>부유 입력</b>은 주변 잡음에 따라 값이 제멋대로 바뀝니다 — 입력 핀은 <b>언제나</b> 풀업이나 풀다운이 있어야 합니다. 논리 극성은 <code>#define PRESSED LOW</code> 처럼 <b>이름으로</b> 적어 두면 배선을 바꿀 때 고칠 자리가 한 곳뿐입니다." },

/* ── 2교시 · 시간·인터럽트·주변장치 ────────────────────────────────── */

{ track:"arduino", cat:"debug", k:"49일마다 타이머가 멈춘다",
  q:"<code>millis()</code> 값으로 주기가 지났는지 봅니다. 값은 <b>32비트 부호 없는 정수</b>라 최댓값 뒤에 0 으로 되돌아옵니다. 평소에는 잘 도는데, 되돌아오는 순간부터 <b>주기가 영원히 안 옵니다</b>.",
  src:"function due(now, last, interval) {\n  return now > last + interval;\n}",
  sol:"function due(now, last, interval) {\n  return ((now - last) >>> 0) >= interval;\n}",
  tests:[["due(4, 4294967290, 10)","true"],
         ["due(100, 90, 10)","true"],
         ["due(0, 0, 0)","true"],
         ["due(100, 90, 20)","false"]],
  edge:[["due(4294967290, 4294967280, 5)","true"],
        ["due(4294967295, 4294967295, 1)","false"]],
  ex:"🐛 원인: <code>last + interval</code> 은 <b>넘칠 수 있습니다</b>. 32비트 최댓값 근처에서 이 덧셈이 되돌아오면 비교가 뒤집혀 조건이 영영 참이 되지 않습니다. <code>millis()</code> 는 약 <b>49.7 일</b>마다 한 바퀴 도는데, 책상에서 몇 시간 돌려 보는 시험으로는 절대 만날 수 없습니다.\n🔧 해결: <b>뺄셈</b>으로 적습니다 — <code>now - last &gt;= interval</code>. 부호 없는 뺄셈은 되돌아온 뒤에도 <b>지난 시간</b>을 정확히 냅니다(자바스크립트에서는 <code>&gt;&gt;&gt; 0</code> 으로 32비트 부호 없는 값으로 만듭니다).\n🛡 재발 방지: 시각 비교는 <b>언제나 차이로</b> 적으세요 — <code>now - last</code> 는 되돌아옴에 안전하고 <code>last + interval</code> 은 안전하지 않습니다. 같은 규칙이 순번·시퀀스 번호에도 적용됩니다. 되돌아오는 순간을 <b>테스트로 만들어</b> 두면 49 일을 기다리지 않아도 됩니다." },

{ track:"arduino", cat:"debug", k:"접점 튐을 그대로 눌림으로 센다",
  q:"버튼 표본에서 <b>눌린 횟수</b>를 셉니다. <code>1</code> 이 <b>연속 <code>n</code> 번</b> 이어진 순간 한 번 세고, 그 뒤 <code>0</code> 이 한 번이라도 나와야 다시 셀 수 있습니다. 그런데 한 번 눌렀는데 <b>두세 번</b> 눌린 것으로 셉니다.",
  src:"function presses(samples, n) {\n  let c = 0;\n  for (let i = 1; i < samples.length; i += 1) {\n    if (samples[i] === 1 && samples[i - 1] === 0) c += 1;\n  }\n  return c;\n}",
  sol:"function presses(samples, n) {\n  let c = 0, run = 0, armed = true;\n  for (const v of samples) {\n    if (v === 1) {\n      run += 1;\n      if (armed && run >= n) { c += 1; armed = false; }\n    } else {\n      run = 0;\n      armed = true;\n    }\n  }\n  return c;\n}",
  tests:[["presses([0,1,0,1,1,1,1,0], 3)","1"],
         ["presses([1,1,1], 3)","1"],
         ["presses([1,1,1,0,1,1,1], 3)","2"],
         ["presses([0,1,0,1,0], 3)","0"]],
  edge:[["presses([], 3)","0"],
        ["presses([1,1], 3)","0"]],
  ex:"🐛 원인: 기계 접점은 붙는 순간 수 밀리초 동안 <b>수십 번 튑니다</b>(chatter). 코드가 <code>0 → 1</code> 변화를 그대로 세고 있으니 한 번 누른 것이 여러 번으로 잡힙니다. 게다가 <b>처음부터 눌려 있는</b> 경우는 앞 표본이 없어 아예 못 셉니다.\n🔧 해결: '<b>연속으로 <code>n</code> 번 같은 값</b>' 을 조건으로 둡니다. 세고 나면 잠금(<code>armed = false</code>)을 걸어, <b>떨어졌다가 다시 붙어야</b> 다음 눌림을 셉니다.\n🛡 재발 방지: 디바운스는 <b>시간</b>(마지막 변화로부터 20~50ms)이나 <b>표본 수</b> 중 하나로 하고, <code>delay()</code> 로 기다리지 마세요 — 그 사이 다른 일이 전부 멈춥니다. 하드웨어로 푸는 방법(RC 필터·슈미트 트리거)도 있습니다. 테스트에는 <b>튀는 표본</b>과 <b>처음부터 눌린</b> 표본을 함께 넣습니다." },

{ track:"arduino", cat:"debug", k:"인터럽트 카운터를 0 으로 덮는다",
  q:"인터럽트가 올려 놓은 카운터를 본문에서 가져갑니다. <b>읽는 사이에 들어온 인터럽트</b>(<code>arrivals</code>)는 다음에 처리하도록 남겨야 합니다. 함수는 <code>[가져간 수, 남은 수]</code> 를 돌려줍니다. 그런데 회전이 빠를 때 <b>펄스를 조금씩 잃습니다</b>.",
  src:"function drain(state, arrivals) {\n  const n = state.count;\n  state.count += arrivals;\n  state.count = 0;\n  return [n, state.count];\n}",
  sol:"function drain(state, arrivals) {\n  const n = state.count;\n  state.count += arrivals;\n  state.count -= n;\n  return [n, state.count];\n}",
  tests:[["(function(){ const s = {count:3}; return drain(s, 2); })()","[3,2]"],
         ["(function(){ const s = {count:0}; return drain(s, 1); })()","[0,1]"],
         ["(function(){ const s = {count:5}; return drain(s, 5); })()","[5,5]"],
         ["(function(){ const s = {count:3}; return drain(s, 0); })()","[3,0]"]],
  edge:[["(function(){ const s = {count:0}; return drain(s, 0); })()","[0,0]"],
        ["(function(){ const s = {count:1}; drain(s, 3); return s.count; })()","3"]],
  ex:"🐛 원인: 값을 읽은 뒤 <b>0 으로 덮었습니다</b>. 읽기와 덮기 사이에 인터럽트가 들어오면 그 펄스는 <b>세지도 못한 채 사라집니다</b>. 신호가 느릴 때는 그 틈에 아무 일도 안 일어나 완벽히 동작하고, 회전이 빨라질수록 조용히 어긋납니다.\n🔧 해결: 0 으로 덮지 말고 <b>가져간 만큼만 뺍니다</b>. 그 사이 늘어난 값은 그대로 남습니다.\n🛡 재발 방지: 인터럽트와 공유하는 변수는 <code>volatile</code> 로 선언하고, <b>여러 바이트짜리 값</b>은 읽는 동안 인터럽트를 잠깐 끄거나(<code>ATOMIC_BLOCK</code>) 스냅숏을 뜬 뒤 다뤄야 합니다. 규칙은 하나입니다 — <b>읽고 쓰는 사이에 끼어들 수 있다고 가정</b>하고, 상태를 덮어쓰는 대신 <b>차이로</b> 갱신하세요." },

{ track:"arduino", cat:"debug", k:"시리얼은 줄 단위로 도착하지 않는다",
  q:"시리얼로 들어온 조각을 모아 <b>완성된 줄</b>만 꺼냅니다. <code>buf</code> 는 지난번에 남은 부분이고, 결과는 <code>{lines, rest}</code> 입니다. 그런데 명령이 <b>중간에서 잘리거나</b> 빈 줄이 섞여 들어옵니다.",
  src:"function feed(buf, chunk) {\n  return { lines: chunk.split('\\n'), rest: '' };\n}",
  sol:"function feed(buf, chunk) {\n  const all = buf + chunk;\n  const pieces = all.split('\\n');\n  const rest = pieces.pop();\n  return { lines: pieces, rest };\n}",
  tests:[["feed('', 'ab')","{lines:[], rest:'ab'}"],
         ["feed('ab', 'c\\nd')","{lines:['abc'], rest:'d'}"],
         ["feed('', 'a\\n')","{lines:['a'], rest:''}"],
         ["feed('', '')","{lines:[], rest:''}"]],
  edge:[["feed('x', '\\n')","{lines:['x'], rest:''}"],
        ["feed('', 'a\\nb\\n')","{lines:['a','b'], rest:''}"]],
  ex:"🐛 원인: 시리얼은 <b>바이트 흐름</b>입니다. 한 번에 읽어 오는 조각이 줄 하나와 일치한다는 보장이 전혀 없어서, 명령이 두 조각으로 잘려 오거나 두 명령이 한 조각에 붙어 옵니다. 지난번 <b>남은 조각(<code>buf</code>)을 무시</b>했으니 앞부분이 통째로 사라지고, 마지막 <b>미완성 조각</b>까지 완성된 줄로 내보냅니다.\n🔧 해결: 남은 것과 새로 온 것을 <b>먼저 이어 붙인</b> 뒤 줄바꿈으로 나눕니다. <b>마지막 조각은 아직 미완성</b>이므로 떼어 다음 번을 위해 남깁니다.\n🛡 재발 방지: 흐름을 다루는 코드는 '<b>조각의 경계는 의미의 경계가 아니다</b>' 를 전제로 짭니다 — 시리얼·TCP·파일 읽기 모두 같습니다. 그리고 <code>\\r\\n</code> 으로 끝나는 터미널도 있으니 <code>\\r</code> 을 함께 다듬고, 남은 조각이 <b>끝없이 길어지지 않도록</b> 최대 길이를 두세요." },

{ track:"arduino", cat:"debug", k:"데이터시트의 주소를 그대로 넘긴다",
  q:"데이터시트에 적힌 <b>8비트 쓰기 주소</b>를 라이브러리가 요구하는 <b>7비트 주소</b>로 바꿉니다. 홀수(읽기 주소)이거나 0~255 밖이거나, 바꾼 결과가 <b>예약 구간</b>(<code>0x08</code>~<code>0x77</code> 밖)이면 <code>-1</code> 입니다. 그런데 장치가 응답하지 않거나 소수점이 붙은 주소가 넘어갑니다.",
  src:"function wireAddr(addr8) {\n  return addr8 / 2;\n}",
  sol:"function wireAddr(addr8) {\n  if (!Number.isInteger(addr8) || addr8 < 0 || addr8 > 255) return -1;\n  if (addr8 % 2 !== 0) return -1;\n  const a = addr8 >> 1;\n  return a >= 0x08 && a <= 0x77 ? a : -1;\n}",
  tests:[["wireAddr(0x79)","-1"],
         ["wireAddr(0x02)","-1"],
         ["wireAddr(0x100)","-1"],
         ["wireAddr(0x78)","60"]],
  edge:[["wireAddr(0x10)","8"],
        ["wireAddr(0xF0)","-1"]],
  ex:"🐛 원인: I²C 주소는 <b>7비트</b>인데 데이터시트는 흔히 <b>읽기·쓰기 비트가 붙은 8비트</b>로 적습니다. 아두이노의 <code>Wire</code> 는 7비트를 요구하므로 그대로 넘기면 <b>전혀 다른 장치</b>를 부릅니다. 게다가 <code>/ 2</code> 는 홀수에서 <b>소수</b>를 만들고, 그런 값이 넘어가면 라이브러리가 조용히 잘라 쓰거나 무시합니다.\n🔧 해결: <b>정수 나눗셈</b>(<code>&gt;&gt; 1</code>)으로 비트를 밀고, 그 전에 <b>홀수·범위</b>를 걸러 냅니다. 결과가 예약 구간에 들면 유효한 장치 주소가 아니므로 거부합니다.\n🛡 재발 방지: 주소가 의심스러우면 <b>I²C 스캐너</b>를 먼저 돌려 실제로 응답하는 7비트 주소를 확인하세요. 코드에는 <code>0x3C</code> 같은 <b>7비트 상수</b>만 두고 8비트 표기는 주석으로 남기면, 나중에 데이터시트를 다시 볼 때 헷갈리지 않습니다." },

{ track:"arduino", cat:"debug", k:"값이 안 바뀌어도 EEPROM 에 쓴다",
  q:"설정값을 EEPROM 에 저장합니다. <b>직전에 저장한 값과 같으면 쓰지 않아야</b> 하고, 처음 값은 언제나 씁니다. 함수는 <b>실제로 쓴 횟수</b>를 돌려줍니다. 그런데 몇 달 만에 특정 주소가 <b>못 쓰게</b> 됩니다.",
  src:"function writes(values) {\n  return values.length;\n}",
  sol:"function writes(values) {\n  let n = 0, last;\n  for (const v of values) {\n    if (n === 0 || v !== last) { n += 1; last = v; }\n  }\n  return n;\n}",
  tests:[["writes([1,1,1])","1"],
         ["writes([5,5,6,6,6])","2"],
         ["writes([1,2,1])","3"],
         ["writes([])","0"]],
  edge:[["writes([0,0])","1"],
        ["writes([7])","1"]],
  ex:"🐛 원인: 루프 안에서 <b>매번</b> 저장하고 있습니다. EEPROM 셀의 쓰기 수명은 대략 <b>10만 회</b>라, 1 초에 한 번만 써도 <b>하루 남짓</b>이면 8만 6천 회입니다. 읽을 때는 멀쩡해 보이므로 며칠 뒤 값이 이상해지고 나서야 알게 됩니다.\n🔧 해결: <b>값이 바뀔 때만</b> 씁니다. 아두이노의 <code>EEPROM.update()</code> 가 바로 이 일을 해 주며, 직접 짤 때는 직전 값을 들고 다니면 됩니다.\n🛡 재발 방지: 쓰기 횟수는 <b>설계 수치</b>로 다루세요 — '몇 초마다 몇 번 × 몇 년' 을 계산해 수명 안에 드는지 확인합니다. 자주 바뀌는 값은 RAM 에 두고 <b>전원이 꺼지기 직전</b>이나 <b>일정 간격</b>으로만 내려쓰고, 꼭 필요하면 여러 주소를 돌려 쓰는 <b>웨어 레벨링</b>을 씁니다." },

];
