/* 백엔드 디버깅 12 — 돌아가는 것처럼 보이는 고장난 코드를 받아 고친다.
   계약
     1. src 는 문법 오류가 아니고 TODO 도 없다. 작은 입력에서는 통과하기도 한다.
     2. src 는 tests 중 최소 하나를 실패한다.
     3. sol 은 tests + edge 를 전부 통과한다.
     4. 전부 결정적 — 시각·난수는 인자로 받는다. 러너 없이 순수 JS 로 돈다.
   검증:  node ver_dbgjs.cjs ./dbg_be.cjs */
module.exports = [

{ track:"backend", cat:"debug", k:"페이지 번호는 1부터 센다",
  q:"목록을 페이지로 잘라 주는 함수입니다. 페이지 번호는 <b>1부터</b> 셉니다. 그런데 1페이지를 요청하면 <b>첫 묶음이 통째로 빠지고</b> 두 번째 묶음이 나옵니다.",
  src:"function pageSlice(items, page, size) {\n  return items.slice(page * size, page * size + size);\n}",
  sol:"function pageSlice(items, page, size) {\n  const from = (page - 1) * size;\n  return items.slice(from, from + size);\n}",
  tests:[["pageSlice([1,2,3,4,5], 1, 2)","[1,2]"],
         ["pageSlice([1,2,3,4,5], 2, 2)","[3,4]"],
         ["pageSlice([1,2,3,4,5], 3, 2)","[5]"],
         ["pageSlice([1,2,3,4,5], 4, 2)","[]"]],
  edge:[["pageSlice([], 1, 10)","[]"],
        ["pageSlice([1,2,3], 1, 0)","[]"]],
  ex:"🐛 원인: 페이지 번호는 1부터 세는데 <code>slice</code> 의 시작 자리는 0부터 셉니다. <code>page * size</code> 는 1페이지에서 <b>이미 한 묶음을 건너뛴</b> 자리를 가리켜 첫 화면이 통째로 사라집니다.\n🔧 해결: 건너뛸 개수는 <code>(page - 1) * size</code> 입니다. '몇 번째 페이지' 를 '몇 개를 건너뛰는가' 로 한 번 바꿔 주는 것이 전부입니다.\n🛡 재발 방지: 1부터 세는 값과 0부터 세는 값이 <b>한 함수 안에서 섞이면</b> 반드시 어딘가에서 한 칸이 어긋납니다. 경계는 <code>page=1</code>·마지막 페이지·범위 밖 페이지 세 가지를 항상 테스트에 넣으세요. API 를 새로 설계한다면 <b>커서</b>를 주는 편이 이 계산 자체를 없앱니다." },

{ track:"backend", cat:"debug", k:"헤더 이름은 대소문자를 가리지 않는다",
  q:"요청 헤더에서 값을 꺼내는 함수입니다. 개발 서버에서는 잘 되는데, 프록시를 거친 뒤로는 <code>Content-Type</code> 을 못 찾고 <code>null</code> 이 나옵니다. 없으면 <code>null</code> 을 돌려줘야 합니다.",
  src:"function headerValue(headers, name) {\n  const v = headers[name];\n  return v === undefined ? null : v;\n}",
  sol:"function headerValue(headers, name) {\n  const want = String(name).toLowerCase();\n  for (const k of Object.keys(headers)) {\n    if (k.toLowerCase() === want) return headers[k];\n  }\n  return null;\n}",
  tests:[["headerValue({'Content-Type':'application/json'}, 'content-type')","'application/json'"],
         ["headerValue({'content-type':'text/html'}, 'Content-Type')","'text/html'"],
         ["headerValue({'X-Request-Id':'r1'}, 'x-request-id')","'r1'"],
         ["headerValue({'Accept':'*/*'}, 'authorization')","null"]],
  edge:[["headerValue({}, 'accept')","null"],
        ["headerValue({'ETag':''}, 'etag')","''"]],
  ex:"🐛 원인: HTTP 헤더 이름은 <b>대소문자를 가리지 않습니다</b>(RFC 9110). 객체 키 조회는 대소문자를 그대로 따지므로, 보내는 쪽이 <code>content-type</code> 으로 적는 순간 못 찾습니다. HTTP/2 는 아예 <b>소문자로만</b> 보내기 때문에 프록시를 거치면서 이름이 바뀝니다.\n🔧 해결: 양쪽을 소문자로 맞춰 견줍니다. 헤더를 받는 즉시 키를 소문자로 정규화해 두면 이후 코드가 전부 단순해집니다.\n🛡 재발 방지: <code>headers['ETag']</code> 처럼 <b>이름을 직접 적어 꺼내는 코드</b>가 이 버그의 씨앗입니다. 프레임워크가 주는 <code>get()</code> 을 쓰거나, 값이 <code>''</code> 인 경우와 없는 경우를 구분하려면 <code>undefined</code> 검사를 <code>falsy</code> 검사로 바꾸지 마세요 — 빈 문자열도 정당한 헤더 값입니다." },

{ track:"backend", cat:"debug", k:"커서는 다음 쪽이 있을 때만 준다",
  q:"커서 페이지네이션입니다. <code>rows</code> 는 <code>size + 1</code> 개까지 넉넉히 읽어 온 결과이고, 돌려줄 것은 <code>size</code> 개와 <b>다음 커서</b>입니다. 그런데 클라이언트가 마지막 쪽에서 <b>같은 요청을 끝없이 반복</b>합니다.",
  src:"function nextPage(rows, size) {\n  const items = rows.slice(0, size);\n  const last = items[items.length - 1];\n  return { items, cursor: last ? last.id : null };\n}",
  sol:"function nextPage(rows, size) {\n  const items = rows.slice(0, size);\n  const more = rows.length > size;\n  const last = items[items.length - 1];\n  return { items, cursor: more && last ? last.id : null };\n}",
  tests:[["nextPage([{id:1},{id:2},{id:3}], 2)","{items:[{id:1},{id:2}], cursor:2}"],
         ["nextPage([{id:1},{id:2}], 2)","{items:[{id:1},{id:2}], cursor:null}"],
         ["nextPage([{id:9}], 2)","{items:[{id:9}], cursor:null}"],
         ["nextPage([{id:1},{id:2},{id:3},{id:4}], 3)","{items:[{id:1},{id:2},{id:3}], cursor:3}"]],
  edge:[["nextPage([], 5)","{items:[], cursor:null}"],
        ["nextPage([{id:7},{id:8}], 1)","{items:[{id:7}], cursor:7}"]],
  ex:"🐛 원인: 마지막 쪽에서도 커서를 돌려주니, 클라이언트는 '아직 남았다' 로 읽고 같은 커서로 다시 묻습니다. 서버는 다시 빈 목록과 같은 커서를 주고 — <b>끝나지 않는 순환</b>입니다.\n🔧 해결: <code>size + 1</code> 개를 읽어 온 이유가 여기 있습니다. <b>실제로 한 개가 더 있었는지</b>로 다음 쪽 여부를 판정하고, 없으면 커서를 <code>null</code> 로 닫습니다.\n🛡 재발 방지: '남았는가' 를 <b>돌려주는 개수</b>로 추측하지 마세요 — 마지막 쪽이 정확히 <code>size</code> 개로 딱 떨어지면 그 추측이 틀립니다. 여분 한 건을 더 읽는 <b>+1 조회</b>가 총 개수를 세는 <code>COUNT(*)</code> 보다 훨씬 싸고 정확합니다." },

{ track:"backend", cat:"debug", k:"If-None-Match 는 목록이고 약한 비교다",
  q:"조건부 요청에서 304 를 줄지 판정하는 함수입니다. 브라우저가 보낸 <code>If-None-Match</code> 와 현재 <code>etag</code> 를 견줍니다. 그런데 캐시가 <b>거의 맞지 않아</b> 매번 본문을 다시 보냅니다. <code>*</code> 는 아무 etag 나 맞는 것으로 봅니다.",
  src:"function etagMatch(ifNoneMatch, etag) {\n  if (!ifNoneMatch || !etag) return false;\n  return ifNoneMatch === etag;\n}",
  sol:"function etagMatch(ifNoneMatch, etag) {\n  if (!ifNoneMatch || !etag) return false;\n  if (ifNoneMatch.trim() === '*') return true;\n  const weak = t => t.trim().replace(/^W\\//, '');\n  const want = weak(etag);\n  return ifNoneMatch.split(',').some(t => weak(t) === want);\n}",
  tests:[["etagMatch('\"a\"', '\"a\"')","true"],
         ["etagMatch('W/\"a\"', '\"a\"')","true"],
         ["etagMatch('\"a\", \"b\"', '\"b\"')","true"],
         ["etagMatch('\"a\"', '\"b\"')","false"]],
  edge:[["etagMatch('*', '\"z\"')","true"],
        ["etagMatch('', '\"a\"')","false"]],
  ex:"🐛 원인: <code>If-None-Match</code> 는 <b>하나가 아니라 목록</b>이고, 각 항목에 <code>W/</code> 가 붙을 수 있습니다. 문자열을 통째로 견주면 목록이 오거나 약한 태그가 오는 순간 전부 어긋나 캐시가 무용지물이 됩니다.\n🔧 해결: 쉼표로 나누고, 각 항목의 <code>W/</code> 접두사를 떼고(<b>약한 비교</b>), 하나라도 맞으면 304 입니다. <code>*</code> 는 '무엇이든 있으면' 이라는 뜻입니다.\n🛡 재발 방지: 이 버그는 <b>기능이 안 되는 게 아니라 느려지는</b> 쪽으로 나타나서 늦게 발견됩니다. 캐시 적중률을 지표로 두면 배포 직후 바로 보입니다. 반대로 <code>If-Match</code>(낙관적 잠금)에서는 <b>강한 비교</b>를 써야 합니다 — 같은 형식이지만 규칙이 다릅니다." },

{ track:"backend", cat:"debug", k:"질의 문자열은 반드시 인코딩한다",
  q:"객체를 질의 문자열로 바꾸는 함수입니다. 키는 <b>사전순</b>으로 정렬하고, 배열 값은 <b>같은 키를 되풀이</b>하며, <code>null</code>·<code>undefined</code> 는 뺍니다. 그런데 검색어에 빈칸이나 <code>&amp;</code> 가 들어가면 <b>파라미터가 쪼개져</b> 엉뚱한 값이 서버에 도착합니다.",
  src:"function toQuery(params) {\n  return Object.keys(params)\n    .map(k => k + '=' + params[k])\n    .join('&');\n}",
  sol:"function toQuery(params) {\n  const out = [];\n  for (const k of Object.keys(params).sort()) {\n    const v = params[k];\n    if (v === null || v === undefined) continue;\n    const list = Array.isArray(v) ? v : [v];\n    for (const one of list) {\n      out.push(encodeURIComponent(k) + '=' + encodeURIComponent(one));\n    }\n  }\n  return out.join('&');\n}",
  tests:[["toQuery({b:1, a:2})","'a=2&b=1'"],
         ["toQuery({q:'a b'})","'q=a%20b'"],
         ["toQuery({t:['x','y']})","'t=x&t=y'"],
         ["toQuery({a:1, b:null})","'a=1'"]],
  edge:[["toQuery({})","''"],
        ["toQuery({k:'a&b=c'})","'k=a%26b%3Dc'"]],
  ex:"🐛 원인: 값을 그대로 이어 붙이면 값 안의 <code>&amp;</code> 와 <code>=</code> 가 <b>구분자로 읽힙니다</b>. <code>k=a&amp;b=c</code> 는 서버에서 두 개의 파라미터가 되고, 검색어의 빈칸은 조용히 <code>+</code> 나 잘림으로 바뀝니다. 배열을 그대로 이어 붙이면 <code>t=x,y</code> 라는 <b>한 개의 값</b>이 됩니다.\n🔧 해결: 키와 값 모두 <code>encodeURIComponent</code> 를 거칩니다. 배열은 규약대로 같은 키를 되풀이하고, 없는 값은 <code>key=undefined</code> 라는 문자열이 되지 않도록 아예 뺍니다.\n🛡 재발 방지: 손으로 만들지 말고 <code>URLSearchParams</code> 를 쓰는 것이 가장 안전합니다. 직접 만들어야 한다면 <b>키 정렬</b>을 규칙으로 두세요 — 같은 뜻의 요청이 늘 같은 문자열이 되어 캐시 키와 요청 서명이 안정됩니다." },

{ track:"backend", cat:"debug", k:"쿠키 값 안에도 등호가 들어간다",
  q:"쿠키 헤더를 객체로 바꾸는 함수입니다. 평소에는 잘 되는데, base64 로 인코딩한 세션 값이 들어오면 <b>끝의 <code>=</code> 뒤가 잘려</b> 로그인이 풀립니다.",
  src:"function parseCookie(s) {\n  const out = {};\n  if (!s) return out;\n  for (const part of s.split(';')) {\n    const [k, v] = part.split('=');\n    if (v === undefined) continue;\n    out[k.trim()] = v;\n  }\n  return out;\n}",
  sol:"function parseCookie(s) {\n  const out = {};\n  if (!s) return out;\n  for (const part of s.split(';')) {\n    const i = part.indexOf('=');\n    if (i < 0) continue;\n    out[part.slice(0, i).trim()] = part.slice(i + 1).trim();\n  }\n  return out;\n}",
  tests:[["parseCookie('a=1; b=2')","{a:'1', b:'2'}"],
         ["parseCookie('sid=YWJj==')","{sid:'YWJj=='}"],
         ["parseCookie('x=')","{x:''}"],
         ["parseCookie('a=1;b=2')","{a:'1', b:'2'}"]],
  edge:[["parseCookie('')","{}"],
        ["parseCookie('flag; a=1')","{a:'1'}"]],
  ex:"🐛 원인: <code>split('=')</code> 는 <b>모든</b> 등호에서 자르므로, 값 안에 등호가 있으면 첫 조각만 남습니다. base64 의 채움 문자가 정확히 <code>=</code> 라서 세션 쿠키에서 자주 터집니다. 짧은 값으로 테스트하면 끝까지 안 드러납니다.\n🔧 해결: <code>indexOf('=')</code> 로 <b>첫 등호 자리만</b> 찾아 앞뒤로 한 번 자릅니다. <code>split('=', 2)</code> 는 자바스크립트에서는 뒤를 버리므로 답이 되지 않습니다 — 이 점이 다른 언어와 다릅니다.\n🛡 재발 방지: '구분자로 자른다' 는 코드를 볼 때마다 <b>값 안에 그 구분자가 들어갈 수 있는가</b>를 먼저 물으세요. 쿠키·헤더·CSV·로그가 전부 같은 함정입니다. 값에 등호를 허용하지 않으려면 잘라 버리지 말고 <b>거부</b>해야 합니다." },

{ track:"backend", cat:"debug", k:"재시도 대기는 지수로 늘고 상한이 있다",
  q:"재시도 대기 시간을 계산하는 함수입니다. <code>base</code> 밀리초에서 시작해 시도마다 <b>두 배</b>로 늘리되 <code>cap</code> 을 넘지 않아야 합니다. 지금은 장애가 길어져도 <b>대기가 거의 늘지 않아</b> 죽은 서버를 계속 두드립니다.",
  src:"function waitMs(attempt, base, cap) {\n  return base * (attempt + 1);\n}",
  sol:"function waitMs(attempt, base, cap) {\n  return Math.min(base * 2 ** attempt, cap);\n}",
  tests:[["waitMs(0, 100, 3000)","100"],
         ["waitMs(1, 100, 3000)","200"],
         ["waitMs(3, 100, 3000)","800"],
         ["waitMs(9, 100, 3000)","3000"]],
  edge:[["waitMs(0, 0, 100)","0"],
        ["waitMs(3, 100, 150)","150"]],
  ex:"🐛 원인: <code>base * (attempt + 1)</code> 은 <b>선형</b>이라 100·200·300… 으로 늘어납니다. 장애가 10초만 이어져도 재시도가 수십 번 쌓여, 회복하려던 서버를 도리어 밀어 넘깁니다. 상한도 없어 반대로 아주 오래 기다리게 될 수도 있습니다.\n🔧 해결: <code>base * 2 ** attempt</code> 로 <b>지수</b>로 늘리고 <code>Math.min</code> 으로 상한을 씌웁니다. 상한이 곧 '최악의 경우 이만큼은 기다린다' 는 약속입니다.\n🛡 재발 방지: 실전에서는 여기에 <b>지터</b>를 더합니다 — 같은 시각에 실패한 클라이언트들이 같은 시각에 재시도하면 회복하는 순간 다시 무너집니다(thundering herd). 지터는 난수를 쓰므로 <b>난수를 인자로 받게</b> 만들어야 테스트가 결정적으로 남습니다." },

{ track:"backend", cat:"debug", k:"돈을 나눌 때는 한 푼도 새지 않아야 한다",
  q:"금액(원 단위 정수)을 <code>n</code> 명에게 나누는 함수입니다. 나머지는 <b>앞사람부터</b> 1원씩 더 받고, 합계는 반드시 원래 금액과 같아야 합니다. 지금은 정산 합계가 <b>원금과 몇 원씩 어긋납니다</b>.",
  src:"function splitAmount(total, n) {\n  const each = Math.round(total / n);\n  return Array.from({ length: n }, () => each);\n}",
  sol:"function splitAmount(total, n) {\n  const base = Math.floor(total / n);\n  const rest = total - base * n;\n  return Array.from({ length: n }, (_, i) => base + (i < rest ? 1 : 0));\n}",
  tests:[["splitAmount(100, 3)","[34,33,33]"],
         ["splitAmount(10, 2)","[5,5]"],
         ["splitAmount(1, 3)","[1,0,0]"],
         ["splitAmount(0, 2)","[0,0]"]],
  edge:[["splitAmount(7, 7)","[1,1,1,1,1,1,1]"],
        ["splitAmount(5, 1)","[5]"]],
  ex:"🐛 원인: 각자에게 <b>반올림한 같은 값</b>을 주면 합계가 원금과 달라집니다. 100 을 3 으로 나누면 33.33… 이 33 으로 반올림되어 합이 99 가 되고, 1원이 사라집니다. 반대 방향으로 어긋나면 없는 돈이 생깁니다.\n🔧 해결: 몫을 <b>내림</b>으로 잡고 남은 나머지를 앞에서부터 1원씩 나눠 줍니다. 이러면 합계가 항상 원금과 같다는 것이 계산으로 보장됩니다.\n🛡 재발 방지: 돈은 <b>정수 최소 단위</b>(원·센트)로만 다루세요 — 부동소수점으로 두면 <code>0.1 + 0.2 !== 0.3</code> 이 그대로 회계 오차가 됩니다. 그리고 나눗셈이 들어간 정산 코드에는 <b>합계가 보존되는가</b>를 성질 테스트로 걸어 두는 것이 개별 값 검사보다 강력합니다." },

{ track:"backend", cat:"debug", k:"정규식에 g 를 빠뜨렸다",
  q:"제목을 URL 조각(slug)으로 바꾸는 함수입니다. 영문 소문자와 숫자만 남기고 나머지 연속 구간은 <code>-</code> 하나로 바꾸며, 앞뒤의 <code>-</code> 는 없앱니다. 그런데 <b>첫 빈칸만 바뀌고</b> 뒤쪽은 그대로 남습니다.",
  src:"function slugOf(s) {\n  return s.toLowerCase().trim().replace(/[^a-z0-9]+/, '-');\n}",
  sol:"function slugOf(s) {\n  return s.toLowerCase().trim()\n    .replace(/[^a-z0-9]+/g, '-')\n    .replace(/^-+|-+$/g, '');\n}",
  tests:[["slugOf('Hello World Now')","'hello-world-now'"],
         ["slugOf('  A  B  ')","'a-b'"],
         ["slugOf('a--b')","'a-b'"],
         ["slugOf('Go!')","'go'"]],
  edge:[["slugOf('')","''"],
        ["slugOf('---')","''"]],
  ex:"🐛 원인: <code>String.replace</code> 는 정규식에 <code>g</code> 가 없으면 <b>첫 자리 하나만</b> 바꿉니다. 두 낱말짜리 제목으로 테스트하면 통과해 버려서, 긴 제목이 들어오는 운영에서야 드러납니다.\n🔧 해결: <code>g</code> 를 붙이고, 특수문자가 끝에 붙어 생기는 꼬리 <code>-</code> 도 한 번 더 정리합니다. <code>replaceAll</code> 을 쓰면 정규식에 <code>g</code> 가 없을 때 아예 오류를 내 주므로 실수를 더 빨리 잡습니다.\n🛡 재발 방지: <code>g</code> 를 붙인 정규식을 <b>변수에 담아 재사용</b>하면 이번에는 <code>lastIndex</code> 가 남아 <code>test</code> 결과가 호출마다 달라집니다. 상태를 가진 정규식은 쓰는 자리에서 새로 만들거나 <code>match</code>·<code>replace</code> 처럼 상태를 안 쓰는 메서드로 다루세요." },

{ track:"backend", cat:"debug", k:"카드 번호는 뒤 네 자리만 남긴다",
  q:"카드 번호를 가리는 함수입니다. <b>마지막 숫자 네 개</b>만 남기고 나머지 숫자는 <code>*</code> 로 바꾸며, 하이픈 같은 글자는 그대로 둡니다. 지금은 <b>전부 가려져</b> 고객센터에서 카드를 구분하지 못합니다.",
  src:"function maskPan(s) {\n  return s.replace(/\\d/g, '*');\n}",
  sol:"function maskPan(s) {\n  const digits = (s.match(/\\d/g) || []).length;\n  let seen = 0;\n  return s.replace(/\\d/g, d => {\n    seen += 1;\n    return seen > digits - 4 ? d : '*';\n  });\n}",
  tests:[["maskPan('4111111111111111')","'************1111'"],
         ["maskPan('4111-1111-1111-1111')","'****-****-****-1111'"],
         ["maskPan('12345')","'*2345'"],
         ["maskPan('123')","'123'"]],
  edge:[["maskPan('')","''"],
        ["maskPan('abcd')","'abcd'"]],
  ex:"🐛 원인: 숫자를 전부 <code>*</code> 로 바꾸면 개인정보는 확실히 지워지지만 <b>업무가 안 됩니다</b>. 가림은 '지우기' 가 아니라 '<b>식별에 필요한 최소만 남기기</b>' 입니다.\n🔧 해결: 먼저 숫자 개수를 세고, 바꾸는 동안 <b>몇 번째 숫자인지</b>를 세어 뒤 네 개만 살립니다. 하이픈 위치가 제각각이라 <code>slice</code> 로 자리를 세면 형식마다 틀어집니다.\n🛡 재발 방지: 네 자리 미만이면 남길 것이 없다는 점을 계약에 적어 두세요(위 <code>maskPan('123')</code>). 그리고 가리는 일은 <b>로그를 쓰는 자리마다</b> 하지 말고 직렬화 계층 한 곳에서 하세요 — 한 곳을 빠뜨리면 그 한 줄로 전부 샙니다." },

{ track:"backend", cat:"debug", k:"설정 병합이 원본을 망가뜨린다",
  q:"기본 설정 위에 사용자 설정을 덮어 주는 함수입니다. 중첩된 객체는 <b>깊이 병합</b>하고, 배열은 통째로 교체하며, <b>두 인자 모두 바뀌면 안 됩니다</b>. 지금은 요청을 한 번 처리하고 나면 <b>다음 요청의 기본값이 오염됩니다</b>.",
  src:"function mergeConfig(base, over) {\n  return Object.assign(base, over);\n}",
  sol:"function mergeConfig(base, over) {\n  const plain = v => v !== null && typeof v === 'object' && !Array.isArray(v);\n  const out = {};\n  for (const k of Object.keys(base)) out[k] = base[k];\n  for (const k of Object.keys(over)) {\n    out[k] = plain(base[k]) && plain(over[k]) ? mergeConfig(base[k], over[k]) : over[k];\n  }\n  return out;\n}",
  tests:[["mergeConfig({a:{x:1,y:2}}, {a:{y:3}})","{a:{x:1,y:3}}"],
         ["(() => { const b={a:{x:1}}; mergeConfig(b, {a:{x:2}}); return b; })()","{a:{x:1}}"],
         ["mergeConfig({a:1}, {b:2})","{a:1, b:2}"],
         ["mergeConfig({a:[1,2]}, {a:[3]})","{a:[3]}"]],
  edge:[["mergeConfig({}, {})","{}"],
        ["mergeConfig({a:{b:{c:1}}}, {a:{b:{d:2}}})","{a:{b:{c:1,d:2}}}"]],
  ex:"🐛 원인: <code>Object.assign(base, over)</code> 는 <b>첫 인자를 제자리에서 고칩니다</b>. 기본 설정 객체를 모듈에서 한 번 만들어 공유한다면, 첫 요청의 사용자 설정이 기본값에 눌러 붙어 이후 모든 요청에 새어 나갑니다. 게다가 얕은 병합이라 <code>{a:{y:3}}</code> 이 <code>a</code> 전체를 갈아 치웁니다.\n🔧 해결: 새 객체에 담고, 양쪽이 모두 <b>평범한 객체</b>일 때만 재귀로 내려갑니다. 배열은 '합칠지 갈아 치울지' 가 도메인 결정이라 계약에 적어 두어야 합니다 — 여기서는 교체입니다.\n🛡 재발 방지: 공유 상태를 <b>동결</b>(<code>Object.freeze</code>)해 두면 이런 오염이 조용히 지나가지 않고 그 자리에서 드러납니다. 그리고 '원본을 바꾸지 않는다' 는 테스트로 못 박으세요 — 반환값만 검사하면 절대 안 잡힙니다." },

{ track:"backend", cat:"debug", k:"정렬이 입력을 뒤엎고 동점 순서가 흔들린다",
  q:"점수 상위 <code>k</code> 명의 이름을 뽑는 함수입니다. 점수가 같으면 <b>이름 오름차순</b>이고, <b>받은 배열을 바꾸면 안 됩니다</b>. 지금은 같은 목록으로 두 번 호출하면 <b>두 번째 결과가 달라집니다</b>.",
  src:"function topNames(rows, k) {\n  return rows.sort((a, b) => b.score - a.score)\n    .slice(0, k)\n    .map(r => r.name);\n}",
  sol:"function topNames(rows, k) {\n  return [...rows]\n    .sort((a, b) => b.score - a.score || (a.name < b.name ? -1 : a.name > b.name ? 1 : 0))\n    .slice(0, k)\n    .map(r => r.name);\n}",
  tests:[["topNames([{name:'b',score:1},{name:'a',score:3}], 2)","['a','b']"],
         ["topNames([{name:'b',score:2},{name:'a',score:2}], 2)","['a','b']"],
         ["topNames([{name:'c',score:5},{name:'a',score:5},{name:'b',score:9}], 2)","['b','a']"],
         ["(() => { const r=[{name:'b',score:1},{name:'a',score:3}]; topNames(r,1); return r[0].name; })()","'b'"]],
  edge:[["topNames([], 3)","[]"],
        ["topNames([{name:'z',score:0}], 5)","['z']"]],
  ex:"🐛 원인: <code>Array.prototype.sort</code> 는 <b>제자리 정렬</b>이라 호출자의 배열을 그대로 뒤엎습니다. 캐시해 둔 목록이나 다른 곳에서 쓰는 배열이면 그 순간부터 순서가 달라져, '두 번째 호출부터 결과가 이상하다' 는 재현하기 어려운 버그가 됩니다. 동점 처리도 빠져 있어 순서가 입력 순서에 딸려 갑니다.\n🔧 해결: <code>[...rows]</code> 로 얕게 복사한 뒤 정렬하고, 비교 함수에 <b>2차 기준</b>을 이어 붙입니다. <code>||</code> 로 잇는 것이 관용구입니다 — 앞 기준이 0(동점)일 때만 뒤가 쓰입니다.\n🛡 재발 방지: 요즘 런타임의 <code>sort</code> 는 <b>안정 정렬</b>이라 동점의 입력 순서가 유지되지만, 그 '입력 순서' 자체가 DB 질의나 해시 순회에 따라 달라집니다. 결과를 눈으로 견주는 테스트나 페이지네이션이 있다면 <b>전순서를 정하는 마지막 기준</b>(보통 고유 키)을 반드시 넣으세요." },

];
