/* 컴파일 언어 실행형 디버깅 2차 — 로컬 러너의 실제 컴파일러·테스트 러너가 판정한다.
   가짜 인터프리터로 의미를 흉내내지 않는다.
     go   : go test          rust : cargo test
     c    : gcc 로 sol.c + test.c 빌드, main 이 0 이면 통과
     cpp  : catch2            java : JUnit 5
   검증: sol 은 통과, src 는 반드시 실패해야 한다. */
module.exports = [
/* ───────────────── Java ───────────────── */
{ lang:"java", k:"정수 나눗셈으로 평균이 잘린다",
  q:"점수 배열의 평균을 구하는데 [1, 2] 의 평균이 1.0 으로 나옵니다. 1.5 가 나오도록 고치세요.",
  src:"public class Sol {\n    public static double average(int[] xs) {\n        int sum = 0;\n        for (int v : xs) sum += v;\n        return sum / xs.length;\n    }\n}",
  sol:"public class Sol {\n    public static double average(int[] xs) {\n        int sum = 0;\n        for (int v : xs) sum += v;\n        return (double) sum / xs.length;\n    }\n}",
  test:{"SolTest.java":"import org.junit.jupiter.api.Test;\nimport static org.junit.jupiter.api.Assertions.*;\n\nclass SolTest {\n    @Test void half() { assertEquals(1.5, Sol.average(new int[]{1, 2}), 1e-9); }\n    @Test void thirds() { assertEquals(2.0 / 3, Sol.average(new int[]{0, 1, 1}), 1e-9); }\n    @Test void whole() { assertEquals(3.0, Sol.average(new int[]{2, 3, 4}), 1e-9); }\n    @Test void negative() { assertEquals(-0.5, Sol.average(new int[]{-1, 0}), 1e-9); }\n}\n"},
  ex:"🐛 원인: <code>sum</code> 과 <code>xs.length</code> 가 둘 다 int 라 <b>나눗셈이 먼저 정수로 계산</b>되고, 그 결과(1)가 나중에 double 로 넓혀집니다. 반환 타입이 double 이라고 계산까지 double 이 되지는 않습니다.\n🔧 해결: 나누기 <b>전에</b> 한쪽을 double 로 캐스팅합니다 — <code>(double) sum / xs.length</code>. 캐스팅이 나눗셈보다 우선순위가 높아 괄호 없이도 의도대로 됩니다.\n🛡 재발 방지: 정수 나눗셈은 조용히 버림하며 예외가 없습니다. 비율·평균·퍼센트를 다룰 때는 '<b>이 식의 피연산자가 모두 정수인가</b>' 를 먼저 보세요. <code>(a + b) / 2</code> 같은 중간값 계산도 같은 함정입니다." },

{ lang:"java", k:"Integer 캐시 밖의 == 비교",
  q:"두 정수 객체가 같은 값인지 확인하는 함수인데, 값이 128 이상이면 같은 값인데도 false 가 나옵니다.",
  src:"public class Sol {\n    public static boolean sameValue(Integer a, Integer b) {\n        return a == b;\n    }\n}",
  sol:"public class Sol {\n    public static boolean sameValue(Integer a, Integer b) {\n        return a.equals(b);\n    }\n}",
  test:{"SolTest.java":"import org.junit.jupiter.api.Test;\nimport static org.junit.jupiter.api.Assertions.*;\n\nclass SolTest {\n    @Test void big() { assertTrue(Sol.sameValue(1000, 1000)); }\n    @Test void small() { assertTrue(Sol.sameValue(7, 7)); }\n    @Test void differ() { assertFalse(Sol.sameValue(1000, 1001)); }\n    @Test void boundary() { assertTrue(Sol.sameValue(128, 128)); }\n}\n"},
  ex:"🐛 원인: <code>Integer</code> 는 객체이고 <code>==</code> 는 <b>참조 비교</b>입니다. JVM 은 −128~127 범위의 Integer 를 캐시해 재사용하므로 작은 값은 우연히 같은 객체라 true 가 나오고, 128부터는 새 객체라 false 가 됩니다 — <b>작은 값으로만 테스트하면 통과</b>하는 최악의 버그입니다.\n🔧 해결: 값 비교는 <code>equals</code> 로 합니다. 한쪽이 <code>int</code> 라면 언박싱이 일어나 <code>==</code> 도 값 비교가 되지만, 양쪽 다 <code>Integer</code> 면 참조 비교입니다.\n🛡 재발 방지: 박싱 타입(<code>Integer</code>·<code>Long</code>·<code>Double</code>)에는 <code>==</code> 를 쓰지 마세요. 캐시 경계 128 은 우연이며 언어 명세가 보장하는 것은 −128~127 뿐입니다." },

{ lang:"java", k:"HashMap 키로 쓰려면 hashCode 도",
  q:"좌표를 키로 방문 횟수를 세는데, 같은 좌표를 다시 넣어도 새 항목이 생깁니다. equals 는 이미 구현했습니다.",
  src:"import java.util.*;\n\npublic class Sol {\n    static class Point {\n        final int x, y;\n        Point(int x, int y) { this.x = x; this.y = y; }\n        @Override public boolean equals(Object o) {\n            if (!(o instanceof Point)) return false;\n            Point p = (Point) o;\n            return x == p.x && y == p.y;\n        }\n    }\n\n    public static int distinct(int[][] pts) {\n        Set<Point> seen = new HashSet<>();\n        for (int[] p : pts) seen.add(new Point(p[0], p[1]));\n        return seen.size();\n    }\n}",
  sol:"import java.util.*;\n\npublic class Sol {\n    static class Point {\n        final int x, y;\n        Point(int x, int y) { this.x = x; this.y = y; }\n        @Override public boolean equals(Object o) {\n            if (!(o instanceof Point)) return false;\n            Point p = (Point) o;\n            return x == p.x && y == p.y;\n        }\n        @Override public int hashCode() { return Objects.hash(x, y); }\n    }\n\n    public static int distinct(int[][] pts) {\n        Set<Point> seen = new HashSet<>();\n        for (int[] p : pts) seen.add(new Point(p[0], p[1]));\n        return seen.size();\n    }\n}",
  test:{"SolTest.java":"import org.junit.jupiter.api.Test;\nimport static org.junit.jupiter.api.Assertions.*;\n\nclass SolTest {\n    @Test void dedup() { assertEquals(2, Sol.distinct(new int[][]{{1,2},{1,2},{3,4}})); }\n    @Test void allSame() { assertEquals(1, Sol.distinct(new int[][]{{0,0},{0,0},{0,0}})); }\n    @Test void allDiff() { assertEquals(3, Sol.distinct(new int[][]{{1,1},{1,2},{2,1}})); }\n    @Test void empty() { assertEquals(0, Sol.distinct(new int[][]{})); }\n}\n"},
  ex:"🐛 원인: 해시 기반 컬렉션은 <b>먼저 <code>hashCode</code> 로 버킷을 찾고</b> 그 안에서만 <code>equals</code> 를 부릅니다. hashCode 를 재정의하지 않으면 객체마다 다른 기본값(대개 주소 기반)이 나와 <b>서로 다른 버킷</b>으로 흩어지고, equals 는 비교조차 되지 않습니다.\n🔧 해결: <code>equals</code> 를 재정의하면 <b>반드시 <code>hashCode</code> 도</b> 함께 재정의합니다 — <code>Objects.hash(x, y)</code> 면 충분합니다.\n🛡 재발 방지: '같은 객체면 같은 해시' 는 계약입니다(역은 아님). 자바 16+ 의 <code>record</code> 는 둘을 자동 생성하므로 값 객체에는 record 가 안전합니다. IDE 의 generate 도 항상 둘을 함께 만듭니다." },

{ lang:"java", k:"순회 중 컬렉션 수정",
  q:"목록에서 특정 접두사로 시작하는 항목을 제거하는데 ConcurrentModificationException 이 납니다.",
  src:"import java.util.*;\n\npublic class Sol {\n    public static List<String> without(List<String> items, String prefix) {\n        List<String> out = new ArrayList<>(items);\n        for (String s : out) {\n            if (s.startsWith(prefix)) out.remove(s);\n        }\n        return out;\n    }\n}",
  sol:"import java.util.*;\n\npublic class Sol {\n    public static List<String> without(List<String> items, String prefix) {\n        List<String> out = new ArrayList<>();\n        for (String s : items) {\n            if (!s.startsWith(prefix)) out.add(s);\n        }\n        return out;\n    }\n}",
  test:{"SolTest.java":"import org.junit.jupiter.api.Test;\nimport java.util.*;\nimport static org.junit.jupiter.api.Assertions.*;\n\nclass SolTest {\n    @Test void drops() {\n        assertEquals(List.of(\"b1\"), Sol.without(new ArrayList<>(List.of(\"a1\", \"b1\", \"a2\")), \"a\"));\n    }\n    @Test void consecutive() {\n        assertEquals(List.of(\"c\"), Sol.without(new ArrayList<>(List.of(\"a1\", \"a2\", \"a3\", \"c\")), \"a\"));\n    }\n    @Test void none() {\n        assertEquals(List.of(\"x\", \"y\"), Sol.without(new ArrayList<>(List.of(\"x\", \"y\")), \"z\"));\n    }\n    @Test void keepsInput() {\n        List<String> src = new ArrayList<>(List.of(\"a1\", \"b\"));\n        Sol.without(src, \"a\");\n        assertEquals(2, src.size());\n    }\n}\n"},
  ex:"🐛 원인: for-each 는 내부적으로 <code>Iterator</code> 를 쓰고, 이터레이터는 생성 시점의 수정 횟수(modCount)를 기억합니다. 순회 도중 컬렉션이 바뀌면 다음 <code>next()</code> 에서 <b>즉시 예외</b>를 던집니다 — 조용히 원소를 건너뛰는 것보다 낫다는 판단(fail-fast)입니다.\n🔧 해결: 지우는 대신 <b>남길 것만 새 리스트에</b> 담습니다. 제자리 삭제가 꼭 필요하면 <code>iterator.remove()</code> 나 <code>removeIf</code> 를 씁니다.\n🛡 재발 방지: '순회 중인 컬렉션은 건드리지 않는다' 가 원칙입니다. 참고로 마지막에서 두 번째 원소를 지우면 <b>예외 없이 조용히 끝나는</b> 경우도 있어, 예외가 안 났다고 안전한 것은 아닙니다." },

{ lang:"java", k:"double 로 돈을 더한다",
  q:"금액을 합산해 원 단위로 반올림하는데, 0.1 을 세 번 더한 결과가 기대와 다릅니다. 정확한 십진 계산이 되도록 고치세요.",
  src:"import java.math.*;\n\npublic class Sol {\n    public static String total(String[] amounts) {\n        double sum = 0;\n        for (String a : amounts) sum += Double.parseDouble(a);\n        return String.valueOf(sum);\n    }\n}",
  sol:"import java.math.*;\n\npublic class Sol {\n    public static String total(String[] amounts) {\n        BigDecimal sum = BigDecimal.ZERO;\n        for (String a : amounts) sum = sum.add(new BigDecimal(a));\n        return sum.toPlainString();\n    }\n}",
  test:{"SolTest.java":"import org.junit.jupiter.api.Test;\nimport static org.junit.jupiter.api.Assertions.*;\n\nclass SolTest {\n    @Test void tenths() { assertEquals(\"0.3\", Sol.total(new String[]{\"0.1\", \"0.1\", \"0.1\"})); }\n    @Test void cents() { assertEquals(\"0.30\", Sol.total(new String[]{\"0.10\", \"0.20\"})); }\n    @Test void whole() { assertEquals(\"3\", Sol.total(new String[]{\"1\", \"2\"})); }\n    @Test void none() { assertEquals(\"0\", Sol.total(new String[]{})); }\n}\n"},
  ex:"🐛 원인: <code>double</code> 은 <b>2진 부동소수점</b>이라 0.1 을 정확히 표현하지 못합니다. 세 번 더하면 0.30000000000000004 가 되고, 이 오차는 금액 합산이 쌓일수록 커집니다 — 회계에서는 1원 차이도 사고입니다.\n🔧 해결: <code>BigDecimal</code> 로 <b>십진 그대로</b> 계산합니다. 반드시 <b>문자열 생성자</b>를 쓰세요 — <code>new BigDecimal(0.1)</code> 은 이미 오차가 낀 double 을 받아 0.1000000000000000055... 가 됩니다.\n🛡 재발 방지: 돈은 <code>BigDecimal</code> 이나 <b>정수 최소 단위</b>(센트·원)로 다룹니다. BigDecimal 은 <code>0.10</code> 과 <code>0.1</code> 을 <code>equals</code> 로는 다르게(스케일까지 비교) 보므로 값 비교에는 <code>compareTo</code> 를 씁니다." },

{ lang:"java", k:"try 안에서 닫으면 새는 경로가 생긴다",
  q:"자원을 열어 읽고 닫는 코드인데, 읽는 도중 예외가 나면 close 가 호출되지 않습니다. 예외가 나도 항상 닫히도록 고치세요.",
  src:"public class Sol {\n    public static class Res implements AutoCloseable {\n        boolean closed = false;\n        final boolean broken;\n        Res(boolean broken) { this.broken = broken; }\n        String read() { if (broken) throw new IllegalStateException(\"boom\"); return \"ok\"; }\n        @Override public void close() { closed = true; }\n    }\n\n    public static boolean readAndCheck(Res r) {\n        try {\n            r.read();\n            r.close();\n        } catch (RuntimeException e) {\n            return r.closed;\n        }\n        return r.closed;\n    }\n}",
  sol:"public class Sol {\n    public static class Res implements AutoCloseable {\n        boolean closed = false;\n        final boolean broken;\n        Res(boolean broken) { this.broken = broken; }\n        String read() { if (broken) throw new IllegalStateException(\"boom\"); return \"ok\"; }\n        @Override public void close() { closed = true; }\n    }\n\n    public static boolean readAndCheck(Res r) {\n        try (Res held = r) {\n            held.read();\n        } catch (RuntimeException e) {\n            return r.closed;\n        }\n        return r.closed;\n    }\n}",
  test:{"SolTest.java":"import org.junit.jupiter.api.Test;\nimport static org.junit.jupiter.api.Assertions.*;\n\nclass SolTest {\n    @Test void normal() { assertTrue(Sol.readAndCheck(new Sol.Res(false))); }\n    @Test void onError() { assertTrue(Sol.readAndCheck(new Sol.Res(true))); }\n    @Test void closedFlagNormal() {\n        Sol.Res r = new Sol.Res(false); Sol.readAndCheck(r); assertTrue(r.closed);\n    }\n    @Test void closedFlagError() {\n        Sol.Res r = new Sol.Res(true); Sol.readAndCheck(r); assertTrue(r.closed);\n    }\n}\n"},
  ex:"🐛 원인: <code>close()</code> 가 <b>try 블록 안 마지막 줄</b>에 있으면, 그 앞에서 예외가 나는 순간 건너뛰어집니다. 정상 경로만 테스트하면 절대 안 잡히고, 운영에서 <b>파일 핸들·커넥션이 서서히 말라</b> 몇 시간 뒤 장애로 나타납니다.\n🔧 해결: <b>try-with-resources</b> 를 씁니다 — <code>AutoCloseable</code> 이면 정상·예외 어느 경로로 나가든 컴파일러가 close 를 보장합니다. 자바 7 이전 방식이라면 <code>finally</code> 에 넣습니다.\n🛡 재발 방지: 자원의 수명은 <b>블록 구조로</b> 표현하세요. '언제 닫을지' 를 사람이 기억하는 코드는 예외 경로가 늘어날수록 반드시 새어 나갑니다." },

{ lang:"java", k:"가변 객체를 그대로 돌려준다",
  q:"내부 목록을 조회하는 게터인데, 호출자가 반환값에 add 를 하면 내부 상태까지 바뀝니다. 방어적으로 고치세요.",
  src:"import java.util.*;\n\npublic class Sol {\n    private final List<String> tags = new ArrayList<>();\n\n    public void add(String t) { tags.add(t); }\n\n    public List<String> getTags() {\n        return tags;\n    }\n}",
  sol:"import java.util.*;\n\npublic class Sol {\n    private final List<String> tags = new ArrayList<>();\n\n    public void add(String t) { tags.add(t); }\n\n    public List<String> getTags() {\n        return List.copyOf(tags);\n    }\n}",
  test:{"SolTest.java":"import org.junit.jupiter.api.Test;\nimport java.util.*;\nimport static org.junit.jupiter.api.Assertions.*;\n\nclass SolTest {\n    @Test void readable() {\n        Sol s = new Sol(); s.add(\"a\");\n        assertEquals(List.of(\"a\"), s.getTags());\n    }\n    @Test void notLeaking() {\n        Sol s = new Sol(); s.add(\"a\");\n        try { s.getTags().add(\"hack\"); } catch (UnsupportedOperationException ignored) { }\n        assertEquals(1, s.getTags().size());\n    }\n    @Test void stillGrows() {\n        Sol s = new Sol(); s.add(\"a\"); s.add(\"b\");\n        assertEquals(2, s.getTags().size());\n    }\n    @Test void emptyStart() { assertTrue(new Sol().getTags().isEmpty()); }\n}\n"},
  ex:"🐛 원인: <code>final</code> 은 <b>참조가 바뀌지 않는다</b>는 뜻이지 <b>내용이 안 바뀐다</b>는 뜻이 아닙니다. 내부 리스트를 그대로 돌려주면 호출자가 캡슐화를 우회해 내부 상태를 바꿉니다 — 게터를 통한 <b>참조 유출</b>입니다.\n🔧 해결: <code>List.copyOf</code>(불변 복사)나 <code>Collections.unmodifiableList</code>(불변 뷰)로 감쌉니다. 둘의 차이는 원본 변경이 비치는지 여부입니다.\n🛡 재발 방지: 생성자로 <b>받을 때도</b> 같은 문제가 있습니다 — 밖에서 준 리스트를 그대로 필드에 두면 호출자가 나중에 바꿀 수 있습니다. 경계에서 들어올 때와 나갈 때 모두 복사하는 것이 방어적 복사입니다." },

/* ───────────────── C ───────────────── */
{ lang:"c", k:"지역 배열의 주소를 돌려준다",
  q:"숫자를 문자열로 바꿔 돌려주는 함수인데, 결과가 쓰레기 값이거나 다음 호출에 덮어써집니다. 호출자가 안전하게 쓸 수 있도록 고치세요.",
  src:"#include <stdio.h>\n#include <stdlib.h>\n\nchar *to_str(int n) {\n    char buf[32];\n    snprintf(buf, sizeof buf, \"%d\", n);\n    return buf;\n}",
  sol:"#include <stdio.h>\n#include <stdlib.h>\n\nchar *to_str(int n) {\n    char *buf = malloc(32);\n    if (!buf) return NULL;\n    snprintf(buf, 32, \"%d\", n);\n    return buf;\n}",
  test:{"test.c":"#include <stdio.h>\n#include <string.h>\n#include <stdlib.h>\n\nchar *to_str(int n);\n\nint main(void) {\n    char *a = to_str(42);\n    char *b = to_str(-7);\n    if (strcmp(a, \"42\") != 0) { printf(\"a=%s, 기대 42\\n\", a); return 1; }\n    if (strcmp(b, \"-7\") != 0) { printf(\"b=%s, 기대 -7\\n\", b); return 1; }\n    char *c = to_str(0);\n    if (strcmp(c, \"0\") != 0) { printf(\"c=%s, 기대 0\\n\", c); return 1; }\n    if (strcmp(a, \"42\") != 0) { printf(\"첫 결과가 덮어써졌다: %s\\n\", a); return 1; }\n    free(a); free(b); free(c);\n    printf(\"ok\\n\");\n    return 0;\n}\n"},
  ex:"🐛 원인: <code>buf</code> 는 <b>스택에 있는 지역 배열</b>이라 함수가 끝나는 순간 사라집니다. 그 주소를 돌려주면 이미 해제된 메모리를 가리키는 <b>댕글링 포인터</b>가 됩니다 — 다음 함수 호출이 그 자리를 덮어쓰면서 값이 변합니다.\n🔧 해결: <code>malloc</code> 으로 <b>힙</b>에 할당하면 함수가 끝나도 살아 있습니다. 대신 <b>해제 책임이 호출자에게</b> 넘어가므로 문서에 명시해야 합니다.\n🛡 재발 방지: 흔한 대안은 <b>호출자가 버퍼를 주는</b> 설계입니다 — <code>to_str(int n, char *out, size_t cap)</code>. 표준 라이브러리(<code>snprintf</code>·<code>strncpy</code>)가 이 형태인 이유이고, 할당 책임이 한쪽으로 명확해집니다.\n⚠️ 운 나쁘게 '되는 것처럼 보이는' 것이 이 버그의 가장 위험한 점입니다 — 최적화 수준이나 컴파일러가 바뀌면 갑자기 깨집니다." },

{ lang:"c", k:"sizeof 는 포인터 크기를 준다",
  q:"배열의 원소 개수를 세어 합계를 구하는데, 배열을 함수에 넘기면 앞의 몇 개만 더해집니다.",
  src:"#include <stddef.h>\n\nint sum_all(int *xs) {\n    int n = sizeof(xs) / sizeof(xs[0]);\n    int s = 0;\n    for (int i = 0; i < n; i++) s += xs[i];\n    return s;\n}",
  sol:"#include <stddef.h>\n\nint sum_all(int *xs, size_t n) {\n    int s = 0;\n    for (size_t i = 0; i < n; i++) s += xs[i];\n    return s;\n}",
  test:{"test.c":"#include <stdio.h>\n#include <stddef.h>\n\nint sum_all(int *xs, size_t n);\n\nint main(void) {\n    int a[] = {1, 2, 3, 4, 5};\n    if (sum_all(a, 5) != 15) { printf(\"got %d, want 15\\n\", sum_all(a, 5)); return 1; }\n    int b[] = {10};\n    if (sum_all(b, 1) != 10) { printf(\"단일 원소 실패\\n\"); return 1; }\n    if (sum_all(a, 0) != 0) { printf(\"빈 범위 실패\\n\"); return 1; }\n    int c[] = {-1, 1, -2, 2};\n    if (sum_all(c, 4) != 0) { printf(\"음수 혼합 실패\\n\"); return 1; }\n    printf(\"ok\\n\");\n    return 0;\n}\n"},
  ex:"🐛 원인: 배열을 함수 인자로 넘기면 <b>포인터로 붕괴(decay)</b>합니다. 함수 안의 <code>sizeof(xs)</code> 는 배열 전체 크기가 아니라 <b>포인터 크기</b>(64비트에서 8)라, <code>8/4 = 2</code> — 항상 앞의 2개만 더합니다.\n🔧 해결: 길이를 <b>별도 인자로 함께</b> 넘깁니다. C 에서 '포인터와 길이는 한 쌍' 이 기본 관용구입니다.\n🛡 재발 방지: <code>sizeof(arr)/sizeof(arr[0])</code> 관용구는 <b>배열이 선언된 그 스코프에서만</b> 유효합니다. 함수 시그니처의 <code>int xs[]</code> 도 실제로는 <code>int *xs</code> 라 똑같이 속습니다 — 그래서 C23 이전에는 컴파일러 경고도 잘 안 나옵니다." },

{ lang:"c", k:"strcpy 가 널 종료 자리를 넘긴다",
  q:"문자열을 고정 버퍼에 안전하게 복사하는 함수인데, 버퍼 크기와 딱 맞는 문자열을 넣으면 널 종료가 사라져 뒤쪽 쓰레기까지 읽힙니다.",
  src:"#include <string.h>\n\nvoid copy_into(char *dst, size_t cap, const char *src) {\n    strncpy(dst, src, cap);\n}",
  sol:"#include <string.h>\n\nvoid copy_into(char *dst, size_t cap, const char *src) {\n    if (cap == 0) return;\n    strncpy(dst, src, cap - 1);\n    dst[cap - 1] = '\\0';\n}",
  test:{"test.c":"#include <stdio.h>\n#include <string.h>\n\nvoid copy_into(char *dst, size_t cap, const char *src);\n\nint main(void) {\n    char buf[6];\n    memset(buf, 'X', sizeof buf);\n    copy_into(buf, 6, \"abcde\");\n    if (strlen(buf) != 5 || strcmp(buf, \"abcde\") != 0) { printf(\"딱 맞는 경우: %.*s\\n\", 6, buf); return 1; }\n    char b2[6];\n    memset(b2, 'X', sizeof b2);\n    copy_into(b2, 6, \"abcdefgh\");\n    if (strlen(b2) != 5) { printf(\"긴 입력 잘림 실패: len=%zu\\n\", strlen(b2)); return 1; }\n    char b3[6];\n    memset(b3, 'X', sizeof b3);\n    copy_into(b3, 6, \"ab\");\n    if (strcmp(b3, \"ab\") != 0) { printf(\"짧은 입력 실패\\n\"); return 1; }\n    printf(\"ok\\n\");\n    return 0;\n}\n"},
  ex:"🐛 원인: <code>strncpy</code> 는 '안전한 strcpy' 가 아닙니다. 소스 길이가 n <b>이상</b>이면 널 종료 문자를 <b>붙이지 않습니다</b>. 그래서 <code>strlen</code> 이 버퍼 끝을 넘어 달리고, 인접 메모리를 읽어 정보가 새거나 크래시가 납니다.\n🔧 해결: <code>cap - 1</code> 까지만 복사하고 <b>마지막 바이트를 직접 <code>'\\0'</code> 로</b> 채웁니다. cap 이 0인 경우도 먼저 막아야 <code>cap - 1</code> 이 거대한 값으로 감기지 않습니다.\n🛡 재발 방지: strncpy 는 원래 <b>고정 길이 레코드용</b>이라 남는 자리를 0으로 채우는(느린) 함수입니다 — 문자열 복사용이 아닙니다. <code>snprintf(dst, cap, \"%s\", src)</code> 나 BSD 의 <code>strlcpy</code> 가 의도에 맞습니다." },

{ lang:"c", k:"free 후 포인터가 살아 있다",
  q:"노드 하나를 지우고 다음 노드로 넘어가는 반복인데, 해제한 뒤에 그 노드를 다시 읽고 있습니다. 링크드 리스트를 안전하게 모두 해제하도록 고치세요.",
  src:"#include <stdlib.h>\n\ntypedef struct Node { int v; struct Node *next; } Node;\n\nint free_all(Node *head) {\n    int n = 0;\n    Node *p = head;\n    while (p) {\n        free(p);\n        p = p->next;\n        n++;\n    }\n    return n;\n}",
  sol:"#include <stdlib.h>\n\ntypedef struct Node { int v; struct Node *next; } Node;\n\nint free_all(Node *head) {\n    int n = 0;\n    Node *p = head;\n    while (p) {\n        Node *nx = p->next;\n        free(p);\n        p = nx;\n        n++;\n    }\n    return n;\n}",
  test:{"test.c":"#include <stdio.h>\n#include <stdlib.h>\n\ntypedef struct Node { int v; struct Node *next; } Node;\nint free_all(Node *head);\n\nstatic Node *build(int n) {\n    Node *head = NULL;\n    for (int i = n; i >= 1; i--) {\n        Node *p = malloc(sizeof(Node));\n        p->v = i; p->next = head; head = p;\n    }\n    return head;\n}\n\nint main(void) {\n    if (free_all(build(3)) != 3) { printf(\"3개 리스트 개수 불일치\\n\"); return 1; }\n    if (free_all(build(1)) != 1) { printf(\"1개 리스트 개수 불일치\\n\"); return 1; }\n    if (free_all(NULL) != 0) { printf(\"빈 리스트는 0이어야 한다\\n\"); return 1; }\n    if (free_all(build(100)) != 100) { printf(\"긴 리스트 개수 불일치\\n\"); return 1; }\n    printf(\"ok\\n\");\n    return 0;\n}\n"},
  ex:"🐛 원인: <code>free(p)</code> 뒤에 <code>p->next</code> 를 읽는 것은 <b>해제된 메모리 사용(use-after-free)</b>입니다. 할당자는 해제된 블록의 앞부분을 자기 관리 정보로 덮어쓰는 경우가 많아, next 가 쓰레기 주소로 변해 크래시나 무한 루프가 됩니다.\n🔧 해결: <b>해제 전에 next 를 지역 변수에 저장</b>합니다. 순서 한 줄이 전부입니다.\n🛡 재발 방지: use-after-free 는 <b>즉시 안 죽는 것</b>이 가장 무섭습니다 — 작은 리스트에서는 우연히 동작하다가 부하가 걸리면 터집니다. 해제 직후 <code>p = NULL</code> 습관과 ASan(<code>-fsanitize=address</code>) 으로 테스트하면 이 계열 버그가 개발 중에 잡힙니다." },

{ lang:"c", k:"int 오버플로는 정의되지 않은 동작",
  q:"두 int 의 평균을 구하는 함수인데, 큰 값 두 개를 넣으면 음수가 나옵니다.",
  src:"int avg(int a, int b) {\n    return (a + b) / 2;\n}",
  sol:"int avg(int a, int b) {\n    return a + (b - a) / 2;\n}",
  test:{"test.c":"#include <stdio.h>\n#include <limits.h>\n\nint avg(int a, int b);\n\nint main(void) {\n    if (avg(2, 4) != 3) { printf(\"기본: %d\\n\", avg(2, 4)); return 1; }\n    int big = INT_MAX;\n    if (avg(big, big) != big) { printf(\"오버플로: %d, 기대 %d\\n\", avg(big, big), big); return 1; }\n    if (avg(big - 2, big) != big - 1) { printf(\"큰 값: %d\\n\", avg(big - 2, big)); return 1; }\n    if (avg(0, 0) != 0) { printf(\"0 실패\\n\"); return 1; }\n    printf(\"ok\\n\");\n    return 0;\n}\n"},
  ex:"🐛 원인: <code>a + b</code> 가 <b>먼저 계산</b>되므로 두 값이 크면 int 범위를 넘어 오버플로합니다. C 에서 부호 있는 정수 오버플로는 '음수가 된다' 가 아니라 <b>정의되지 않은 동작(UB)</b> — 컴파일러가 '오버플로는 일어나지 않는다' 고 가정해 검사 코드를 통째로 지워 버리기도 합니다.\n🔧 해결: <code>a + (b - a) / 2</code> 는 중간값이 범위를 넘지 않습니다. 부호 없는 정수라면 <code>(a &amp; b) + ((a ^ b) &gt;&gt; 1)</code> 도 씁니다.\n🛡 재발 방지: 이진 탐색의 <code>(lo + hi) / 2</code> 가 같은 버그로 <b>자바 표준 라이브러리에서 9년간</b> 살아 있었습니다. '입력이 그렇게 크지 않다' 는 가정은 문서에 적히지 않으면 반드시 깨집니다 — 경계값 테스트(<code>INT_MAX</code>)가 유일한 방어선입니다." },

/* ───────────────── C++ ───────────────── */
{ lang:"cpp", k:"vector 를 값으로 받아 복사한다",
  q:"큰 벡터의 최댓값을 찾는 함수인데, 호출할 때마다 전체가 복사되어 느립니다. 원본을 바꾸지 않으면서 복사도 없애세요. (테스트가 복사 횟수를 셉니다)",
  src:"#include <vector>\n#include <stdexcept>\n\nint max_of(std::vector<int> xs) {\n    if (xs.empty()) throw std::invalid_argument(\"empty\");\n    int m = xs[0];\n    for (int v : xs) if (v > m) m = v;\n    return m;\n}",
  sol:"#include <vector>\n#include <stdexcept>\n\nint max_of(const std::vector<int> &xs) {\n    if (xs.empty()) throw std::invalid_argument(\"empty\");\n    int m = xs[0];\n    for (int v : xs) if (v > m) m = v;\n    return m;\n}",
  test:{"test.cpp":"#include \"catch.hpp\"\n#include <vector>\n#include <stdexcept>\n\nint max_of(const std::vector<int> &xs);\n\nTEST_CASE(\"기본 최댓값\") {\n    std::vector<int> v{3, 9, 2};\n    REQUIRE(max_of(v) == 9);\n}\n\nTEST_CASE(\"음수만\") {\n    std::vector<int> v{-5, -2, -9};\n    REQUIRE(max_of(v) == -2);\n}\n\nTEST_CASE(\"빈 벡터는 예외\") {\n    std::vector<int> v;\n    REQUIRE_THROWS_AS(max_of(v), std::invalid_argument);\n}\n\nTEST_CASE(\"const 벡터도 받는다\") {\n    const std::vector<int> v{1, 7, 4};\n    REQUIRE(max_of(v) == 7);\n}\n"},
  ex:"🐛 원인: <code>std::vector&lt;int&gt; xs</code> 는 <b>값 전달</b>이라 호출마다 전체 원소가 복사됩니다. 원소 100만 개면 매 호출이 수 MB 복사 + 힙 할당입니다 — 읽기만 하는 함수인데 비용은 쓰기만큼 듭니다.\n🔧 해결: <code>const std::vector&lt;int&gt; &amp;</code> — <b>const 참조</b>로 받으면 복사도 없고 원본 수정도 막힙니다. <code>const</code> 를 붙여야 임시 객체와 const 객체도 받을 수 있습니다.\n🛡 재발 방지: 관례는 '작고 복사 저렴한 타입(int·포인터)은 값으로, 그 외에는 const 참조로' 입니다. 함수가 <b>사본을 소유해야 한다면</b> 오히려 값 전달 + <code>std::move</code> 가 더 나은 선택입니다 — '무조건 참조' 도 정답은 아닙니다." },

{ lang:"cpp", k:"참조를 무효화하는 push_back",
  q:"벡터의 첫 원소를 참조로 잡아 두고 값을 추가한 뒤 그 참조를 쓰는 코드입니다. 값이 이상하게 나오거나 크래시가 납니다.",
  src:"#include <vector>\n\nint grow_and_read(std::vector<int> &xs, int add) {\n    int &first = xs[0];\n    for (int i = 0; i < add; i++) xs.push_back(i);\n    return first;\n}",
  sol:"#include <vector>\n\nint grow_and_read(std::vector<int> &xs, int add) {\n    int saved = xs[0];\n    for (int i = 0; i < add; i++) xs.push_back(i);\n    return saved;\n}",
  test:{"test.cpp":"#include \"catch.hpp\"\n#include <vector>\n\nint grow_and_read(std::vector<int> &xs, int add);\n\nTEST_CASE(\"재할당 후에도 첫 값\") {\n    std::vector<int> v{42};\n    REQUIRE(grow_and_read(v, 1000) == 42);\n}\n\nTEST_CASE(\"추가 없이\") {\n    std::vector<int> v{7, 8};\n    REQUIRE(grow_and_read(v, 0) == 7);\n}\n\nTEST_CASE(\"크기도 늘어난다\") {\n    std::vector<int> v{1};\n    grow_and_read(v, 5);\n    REQUIRE(v.size() == 6);\n}\n\nTEST_CASE(\"음수 첫 값\") {\n    std::vector<int> v{-3};\n    REQUIRE(grow_and_read(v, 500) == -3);\n}\n"},
  ex:"🐛 원인: <code>push_back</code> 으로 용량이 넘치면 벡터는 <b>더 큰 메모리를 새로 잡아 원소를 옮기고 기존 블록을 해제</b>합니다. 그 순간 이전 메모리를 가리키던 참조·포인터·이터레이터는 전부 <b>무효</b>가 됩니다.\n🔧 해결: 참조 대신 <b>값을 복사해</b> 보관하거나, 참조가 꼭 필요하면 인덱스로 잡고 나중에 <code>xs[0]</code> 로 다시 접근합니다.\n🛡 재발 방지: 용량이 넉넉하면 <b>재할당이 안 일어나 우연히 통과</b>합니다 — 그래서 이 버그는 데이터가 커진 운영 환경에서야 터집니다. <code>reserve</code> 로 미리 잡아도 '재할당하지 않는다' 는 보장은 그 용량까지뿐입니다. 컨테이너별 무효화 규칙(list·deque 는 다릅니다)은 외워 둘 값어치가 있습니다." },

{ lang:"cpp", k:"가상 소멸자가 없다",
  q:"기반 클래스 포인터로 파생 객체를 지우는데, 파생 클래스의 정리 코드가 실행되지 않습니다. (테스트가 소멸 카운터를 확인합니다)",
  src:"#include <memory>\n\nstruct Base {\n    ~Base() {}\n    virtual int id() const { return 0; }\n};\n\nstruct Derived : Base {\n    int *counter;\n    explicit Derived(int *c) : counter(c) {}\n    ~Derived() { (*counter)++; }\n    int id() const override { return 1; }\n};\n\nvoid destroy_via_base(int *counter) {\n    Base *p = new Derived(counter);\n    delete p;\n}",
  sol:"#include <memory>\n\nstruct Base {\n    virtual ~Base() {}\n    virtual int id() const { return 0; }\n};\n\nstruct Derived : Base {\n    int *counter;\n    explicit Derived(int *c) : counter(c) {}\n    ~Derived() override { (*counter)++; }\n    int id() const override { return 1; }\n};\n\nvoid destroy_via_base(int *counter) {\n    Base *p = new Derived(counter);\n    delete p;\n}",
  test:{"test.cpp":"#include \"catch.hpp\"\n\nvoid destroy_via_base(int *counter);\n\nTEST_CASE(\"파생 소멸자가 불린다\") {\n    int c = 0;\n    destroy_via_base(&c);\n    REQUIRE(c == 1);\n}\n\nTEST_CASE(\"여러 번\") {\n    int c = 0;\n    destroy_via_base(&c);\n    destroy_via_base(&c);\n    destroy_via_base(&c);\n    REQUIRE(c == 3);\n}\n\nTEST_CASE(\"독립 카운터\") {\n    int a = 0, b = 0;\n    destroy_via_base(&a);\n    REQUIRE(a == 1);\n    REQUIRE(b == 0);\n}\n"},
  ex:"🐛 원인: 기반 클래스 포인터로 <code>delete</code> 할 때 소멸자가 <b>가상이 아니면</b> 기반 클래스 소멸자만 호출됩니다 — 파생 클래스가 잡은 자원은 그대로 샙니다. 표준상 이것은 <b>정의되지 않은 동작</b>입니다.\n🔧 해결: 다형적으로 삭제될 기반 클래스에는 <code>virtual ~Base()</code> 를 둡니다. 가상 함수가 이미 하나라도 있다면(여기선 <code>id()</code>) vtable 비용은 이미 지불된 상태라 추가 부담도 없습니다.\n🛡 재발 방지: 규칙은 간단합니다 — '<b>가상 함수가 있으면 소멸자도 가상으로</b>'. 반대로 상속을 의도하지 않은 클래스는 <code>final</code> 을 붙여 의도를 못 박습니다. <code>std::shared_ptr</code> 은 삭제자를 타입 소거로 기억해 이 함정을 피해 가지만 <code>unique_ptr</code> 은 그렇지 않습니다." },

{ lang:"cpp", k:"이터레이터 무효화 — erase 반복",
  q:"벡터에서 짝수를 모두 지우는데, 짝수가 연달아 있으면 일부가 남습니다.",
  src:"#include <vector>\n\nvoid drop_even(std::vector<int> &xs) {\n    for (auto it = xs.begin(); it != xs.end(); ++it) {\n        if (*it % 2 == 0) xs.erase(it);\n    }\n}",
  sol:"#include <vector>\n#include <algorithm>\n\nvoid drop_even(std::vector<int> &xs) {\n    xs.erase(std::remove_if(xs.begin(), xs.end(),\n                            [](int v) { return v % 2 == 0; }),\n             xs.end());\n}",
  test:{"test.cpp":"#include \"catch.hpp\"\n#include <vector>\n\nvoid drop_even(std::vector<int> &xs);\n\nTEST_CASE(\"연속된 짝수\") {\n    std::vector<int> v{1, 2, 4, 5};\n    drop_even(v);\n    REQUIRE(v == std::vector<int>{1, 5});\n}\n\nTEST_CASE(\"전부 짝수\") {\n    std::vector<int> v{2, 4, 6};\n    drop_even(v);\n    REQUIRE(v.empty());\n}\n\nTEST_CASE(\"짝수 없음\") {\n    std::vector<int> v{1, 3, 5};\n    drop_even(v);\n    REQUIRE(v == std::vector<int>{1, 3, 5});\n}\n\nTEST_CASE(\"빈 벡터\") {\n    std::vector<int> v;\n    drop_even(v);\n    REQUIRE(v.empty());\n}\n"},
  ex:"🐛 원인: <code>erase</code> 는 지운 위치 <b>이후의 모든 이터레이터를 무효화</b>하고, 뒤 원소들이 한 칸씩 앞으로 당겨집니다. 그런데 루프는 <code>++it</code> 로 한 칸 더 나아가므로 <b>당겨진 원소를 건너뜁니다</b> — 짝수가 연달아 있으면 두 번째가 살아남습니다.\n🔧 해결: <b>erase-remove 관용구</b>가 정석입니다 — <code>remove_if</code> 가 남길 원소를 앞으로 모아 새 끝을 돌려주고, <code>erase</code> 가 꼬리를 한 번에 자릅니다. 원소 이동이 O(n) 한 번이라 반복 erase 의 O(n²) 보다 빠르기도 합니다.\n🛡 재발 방지: 제자리 순회 삭제가 꼭 필요하면 <code>it = xs.erase(it);</code> 로 <b>반환값을 받고</b> 그 경우엔 <code>++it</code> 를 하지 않습니다. C++20 이후로는 <code>std::erase_if(xs, pred)</code> 한 줄이면 됩니다." },

{ lang:"cpp", k:"map 의 operator[] 가 원소를 만든다",
  q:"맵에서 값을 조회하는 함수인데, 없는 키를 조회하면 맵의 크기가 늘어납니다. 조회만으로 맵이 변하지 않게 고치세요.",
  src:"#include <map>\n#include <string>\n\nint lookup(std::map<std::string, int> &m, const std::string &k) {\n    return m[k];\n}",
  sol:"#include <map>\n#include <string>\n\nint lookup(std::map<std::string, int> &m, const std::string &k) {\n    auto it = m.find(k);\n    return it == m.end() ? 0 : it->second;\n}",
  test:{"test.cpp":"#include \"catch.hpp\"\n#include <map>\n#include <string>\n\nint lookup(std::map<std::string, int> &m, const std::string &k);\n\nTEST_CASE(\"있는 키\") {\n    std::map<std::string, int> m{{\"a\", 3}};\n    REQUIRE(lookup(m, \"a\") == 3);\n}\n\nTEST_CASE(\"없는 키는 0이고 맵은 그대로\") {\n    std::map<std::string, int> m{{\"a\", 3}};\n    REQUIRE(lookup(m, \"zz\") == 0);\n    REQUIRE(m.size() == 1);\n}\n\nTEST_CASE(\"빈 맵도 커지지 않는다\") {\n    std::map<std::string, int> m;\n    lookup(m, \"x\");\n    REQUIRE(m.empty());\n}\n\nTEST_CASE(\"0 이 저장된 키\") {\n    std::map<std::string, int> m{{\"z\", 0}};\n    REQUIRE(lookup(m, \"z\") == 0);\n    REQUIRE(m.size() == 1);\n}\n"},
  ex:"🐛 원인: <code>std::map</code> 의 <code>operator[]</code> 는 <b>키가 없으면 값을 기본 생성해 삽입</b>합니다 — 읽기처럼 보이지만 쓰기입니다. 조회만 하는 루프가 맵을 무한정 키우고, 메모리가 새는 것처럼 보입니다.\n🔧 해결: 조회에는 <code>find</code>(또는 <code>at</code>, <code>contains</code>)를 씁니다. <code>at</code> 은 없으면 예외를 던지므로 '없을 수 있다' 를 코드로 표현하려면 find 가 낫습니다.\n🛡 재발 방지: <code>operator[]</code> 가 <b>const 맵에서는 아예 쓸 수 없다</b>는 사실이 힌트입니다 — 수정 연산이기 때문입니다. 반대로 카운팅(<code>m[k]++</code>)에는 이 성질이 오히려 편리하니, '지금 삽입을 원하는가' 로 갈라 쓰면 됩니다." },

/* ───────────────── Go ───────────────── */
{ lang:"go", k:"루프 변수 캡처",
  q:"각 인덱스를 돌려주는 클로저들을 만드는데, 전부 같은 값(마지막 값)을 돌려줍니다. Go 1.21 이하에서도 안전하도록 고치세요.",
  src:"package ex\n\nfunc Makers(n int) []func() int {\n\tout := []func() int{}\n\tfor i := 0; i < n; i++ {\n\t\tout = append(out, func() int { return i })\n\t}\n\treturn out\n}",
  sol:"package ex\n\nfunc Makers(n int) []func() int {\n\tout := []func() int{}\n\tfor i := 0; i < n; i++ {\n\t\ti := i\n\t\tout = append(out, func() int { return i })\n\t}\n\treturn out\n}",
  test:{"go.mod":"module ex\n\ngo 1.21\n","sol_test.go":"package ex\n\nimport \"testing\"\n\nfunc TestEach(t *testing.T) {\n\tfs := Makers(3)\n\tfor i, f := range fs {\n\t\tif got := f(); got != i {\n\t\t\tt.Fatalf(\"%d번째 클로저가 %d 를 돌려줬다\", i, got)\n\t\t}\n\t}\n}\n\nfunc TestCount(t *testing.T) {\n\tif len(Makers(5)) != 5 {\n\t\tt.Fatal(\"개수가 맞지 않는다\")\n\t}\n}\n\nfunc TestZero(t *testing.T) {\n\tif len(Makers(0)) != 0 {\n\t\tt.Fatal(\"빈 입력\")\n\t}\n}\n"},
  ex:"🐛 원인: Go 1.21 까지 <code>for</code> 의 루프 변수는 <b>반복마다 새로 만들어지지 않고 하나를 재사용</b>합니다. 클로저는 값이 아니라 <b>그 변수</b>를 캡처하므로, 루프가 끝난 뒤 전부 마지막 값을 봅니다.\n🔧 해결: 루프 안에서 <code>i := i</code> 로 <b>반복마다 새 변수</b>를 만들어 캡처합니다. 어색해 보이지만 Go 커뮤니티의 오랜 관용구입니다.\n🛡 재발 방지: <b>Go 1.22 부터는 루프 변수가 반복마다 새로 생성</b>되어 이 버그가 사라졌습니다 — 다만 <code>go.mod</code> 의 언어 버전이 기준이라, 오래된 모듈은 최신 툴체인으로 빌드해도 옛 동작입니다. 고루틴을 루프에서 띄울 때 특히 자주 터집니다." },

{ lang:"go", k:"defer 는 함수 끝에 실행된다",
  q:"여러 항목을 처리하며 매번 정리 함수를 호출해야 하는데, 정리가 전부 마지막에 몰려 실행됩니다. 항목마다 즉시 정리되도록 고치세요.",
  src:"package ex\n\nfunc Process(items []string) []string {\n\tlog := []string{}\n\tfor _, it := range items {\n\t\tdefer func(name string) { log = append(log, \"close:\"+name) }(it)\n\t\tlog = append(log, \"open:\"+it)\n\t}\n\treturn log\n}",
  sol:"package ex\n\nfunc Process(items []string) []string {\n\tlog := []string{}\n\tfor _, it := range items {\n\t\tfunc(name string) {\n\t\t\tdefer func() { log = append(log, \"close:\"+name) }()\n\t\t\tlog = append(log, \"open:\"+name)\n\t\t}(it)\n\t}\n\treturn log\n}",
  test:{"go.mod":"module ex\n\ngo 1.21\n","sol_test.go":"package ex\n\nimport (\n\t\"reflect\"\n\t\"testing\"\n)\n\nfunc TestOrder(t *testing.T) {\n\tgot := Process([]string{\"a\", \"b\"})\n\twant := []string{\"open:a\", \"close:a\", \"open:b\", \"close:b\"}\n\tif !reflect.DeepEqual(got, want) {\n\t\tt.Fatalf(\"got %v, want %v\", got, want)\n\t}\n}\n\nfunc TestSingle(t *testing.T) {\n\tgot := Process([]string{\"x\"})\n\twant := []string{\"open:x\", \"close:x\"}\n\tif !reflect.DeepEqual(got, want) {\n\t\tt.Fatalf(\"got %v, want %v\", got, want)\n\t}\n}\n\nfunc TestEmpty(t *testing.T) {\n\tif len(Process(nil)) != 0 {\n\t\tt.Fatal(\"빈 입력\")\n\t}\n}\n"},
  ex:"🐛 원인: <code>defer</code> 는 <b>블록이 아니라 함수</b>가 끝날 때 실행됩니다. 루프 안에서 defer 하면 정리가 하나도 실행되지 않은 채 쌓이다가 마지막에 <b>역순으로 몰려</b> 실행됩니다 — 파일 1만 개를 처리하면 핸들 1만 개를 동시에 들고 있게 됩니다.\n🔧 해결: 루프 본문을 <b>익명 함수로 감싸</b> 반복마다 함수 경계를 만듭니다. 그 안의 defer 는 반복 끝에 실행됩니다. 별도의 이름 있는 함수로 빼는 것이 더 읽기 좋을 때도 많습니다.\n🛡 재발 방지: 실전 증상은 'too many open files' 나 커넥션 풀 고갈입니다. 정리 순서도 기억하세요 — defer 는 <b>LIFO</b>라 마지막에 defer 한 것이 먼저 실행됩니다." },

{ lang:"go", k:"errors.Is 로 감싼 에러를 본다",
  q:"에러가 특정 센티넬 에러인지 판별하는데, 상위에서 %w 로 감싼 에러는 false 가 나옵니다.",
  src:"package ex\n\nimport (\n\t\"errors\"\n\t\"fmt\"\n)\n\nvar ErrNotFound = errors.New(\"not found\")\n\nfunc Wrap(msg string) error {\n\treturn fmt.Errorf(\"%s: %w\", msg, ErrNotFound)\n}\n\nfunc IsMissing(err error) bool {\n\treturn err == ErrNotFound\n}",
  sol:"package ex\n\nimport (\n\t\"errors\"\n\t\"fmt\"\n)\n\nvar ErrNotFound = errors.New(\"not found\")\n\nfunc Wrap(msg string) error {\n\treturn fmt.Errorf(\"%s: %w\", msg, ErrNotFound)\n}\n\nfunc IsMissing(err error) bool {\n\treturn errors.Is(err, ErrNotFound)\n}",
  test:{"go.mod":"module ex\n\ngo 1.21\n","sol_test.go":"package ex\n\nimport (\n\t\"errors\"\n\t\"fmt\"\n\t\"testing\"\n)\n\nfunc TestWrapped(t *testing.T) {\n\tif !IsMissing(Wrap(\"user 42\")) {\n\t\tt.Fatal(\"감싼 에러를 못 알아본다\")\n\t}\n}\n\nfunc TestDirect(t *testing.T) {\n\tif !IsMissing(ErrNotFound) {\n\t\tt.Fatal(\"직접 비교도 되어야 한다\")\n\t}\n}\n\nfunc TestTwice(t *testing.T) {\n\tif !IsMissing(fmt.Errorf(\"outer: %w\", Wrap(\"inner\"))) {\n\t\tt.Fatal(\"두 겹으로 감싸도 찾아야 한다\")\n\t}\n}\n\nfunc TestOther(t *testing.T) {\n\tif IsMissing(errors.New(\"other\")) {\n\t\tt.Fatal(\"다른 에러를 참으로 판정했다\")\n\t}\n}\n"},
  ex:"🐛 원인: <code>%w</code> 로 감싼 에러는 <b>원본을 안에 품은 새 에러 값</b>입니다. <code>==</code> 는 바깥 값만 비교하므로 항상 false 입니다 — 그런데 감싸지 않은 경로에서는 통과하기 때문에, 나중에 누군가 컨텍스트를 덧붙이는 순간 조용히 깨집니다.\n🔧 해결: <code>errors.Is</code> 는 <b>Unwrap 체인을 따라가며</b> 비교합니다. 타입으로 판별할 때는 <code>errors.As</code> 를 씁니다.\n🛡 재발 방지: 에러를 감쌀 때는 <code>%w</code>(체인 유지), 그냥 메시지로만 쓸 때는 <code>%v</code>(체인 끊김)입니다. 라이브러리 경계에서 <b>무엇을 노출할지</b> 정하는 것이 곧 API 계약이라, 센티넬 에러는 문서화된 공개 약속으로 다뤄야 합니다." },

{ lang:"go", k:"채널을 닫지 않아 range 가 멈추지 않는다",
  q:"고루틴이 값을 보내고 range 로 받아 모으는 코드인데, 모든 값을 받은 뒤에도 끝나지 않고 데드락이 납니다.",
  src:"package ex\n\nfunc Collect(n int) []int {\n\tch := make(chan int)\n\tgo func() {\n\t\tfor i := 0; i < n; i++ {\n\t\t\tch <- i\n\t\t}\n\t}()\n\tout := []int{}\n\tfor v := range ch {\n\t\tout = append(out, v)\n\t}\n\treturn out\n}",
  sol:"package ex\n\nfunc Collect(n int) []int {\n\tch := make(chan int)\n\tgo func() {\n\t\tfor i := 0; i < n; i++ {\n\t\t\tch <- i\n\t\t}\n\t\tclose(ch)\n\t}()\n\tout := []int{}\n\tfor v := range ch {\n\t\tout = append(out, v)\n\t}\n\treturn out\n}",
  test:{"go.mod":"module ex\n\ngo 1.21\n","sol_test.go":"package ex\n\nimport (\n\t\"reflect\"\n\t\"testing\"\n)\n\nfunc TestThree(t *testing.T) {\n\tif got := Collect(3); !reflect.DeepEqual(got, []int{0, 1, 2}) {\n\t\tt.Fatalf(\"got %v\", got)\n\t}\n}\n\nfunc TestOne(t *testing.T) {\n\tif got := Collect(1); !reflect.DeepEqual(got, []int{0}) {\n\t\tt.Fatalf(\"got %v\", got)\n\t}\n}\n\nfunc TestZero(t *testing.T) {\n\tif got := Collect(0); len(got) != 0 {\n\t\tt.Fatalf(\"got %v\", got)\n\t}\n}\n"},
  ex:"🐛 원인: <code>for v := range ch</code> 는 <b>채널이 닫힐 때까지</b> 계속 기다립니다. 보내는 쪽이 닫지 않으면 수신자는 영원히 대기하고, 다른 고루틴이 없으면 런타임이 <b>데드락으로 프로그램을 종료</b>시킵니다.\n🔧 해결: 보내기가 끝나면 <code>close(ch)</code> — 닫는 책임은 <b>보내는 쪽</b>에 있습니다. 받는 쪽이 닫으면 다른 송신자가 닫힌 채널에 보내다 패닉이 납니다.\n🛡 재발 방지: 송신자가 여럿이면 <code>sync.WaitGroup</code> 으로 전부 끝난 뒤 별도 고루틴에서 한 번만 닫습니다. 취소가 필요하면 <code>context</code> 와 <code>select</code> 를 함께 써서 <b>수신자가 사라져도 송신자가 영원히 막히지 않게</b> 해야 합니다 — 고루틴 누수의 대표 원인입니다." },

/* ───────────────── Rust ───────────────── */
{ lang:"rust", k:"인덱싱은 바이트 경계를 요구한다",
  q:"문자열의 첫 글자를 돌려주는 함수인데, 한글이 들어오면 패닉이 납니다.",
  src:"pub fn first_char(s: &str) -> Option<String> {\n    if s.is_empty() {\n        return None;\n    }\n    Some(s[0..1].to_string())\n}",
  sol:"pub fn first_char(s: &str) -> Option<String> {\n    s.chars().next().map(|c| c.to_string())\n}",
  test:{"sol.rs":"use ex::first_char;\n\n#[test]\nfn ascii() {\n    assert_eq!(first_char(\"abc\"), Some(\"a\".to_string()));\n}\n\n#[test]\nfn hangul() {\n    assert_eq!(first_char(\"한글\"), Some(\"한\".to_string()));\n}\n\n#[test]\nfn empty() {\n    assert_eq!(first_char(\"\"), None);\n}\n\n#[test]\nfn emoji() {\n    assert_eq!(first_char(\"🦀x\"), Some(\"🦀\".to_string()));\n}\n"},
  ex:"🐛 원인: 러스트의 <code>&amp;str</code> 은 UTF-8 바이트열이고, 범위 인덱싱은 <b>문자 경계에 정확히 맞아야</b> 합니다. 한글 한 글자는 3바이트라 <code>s[0..1]</code> 은 글자 중간을 자르게 되어 <b>런타임 패닉</b>입니다.\n🔧 해결: <code>chars()</code> 로 <b>문자 단위 이터레이터</b>를 얻어 첫 항목을 취합니다. 바이트가 아니라 의미 단위로 다루는 것이 의도에 맞습니다.\n🛡 재발 방지: 러스트가 <code>s[0]</code>(단일 인덱싱)을 <b>아예 금지</b>하는 것은 '문자열의 i번째' 가 O(1) 이 아니고 의미도 모호하기 때문입니다. 자소 클러스터(결합 이모지·한글 조합형)까지 정확히 다루려면 <code>unicode-segmentation</code> 크레이트가 필요합니다 — <code>chars()</code> 도 만능은 아닙니다." },

{ lang:"rust", k:"정수 나눗셈과 오버플로",
  q:"두 값의 중간값을 구하는 함수인데, 큰 값에서 릴리스 빌드는 값이 감기고 디버그 빌드는 패닉이 납니다. 어떤 입력에도 안전하도록 고치세요.",
  src:"pub fn midpoint(a: u32, b: u32) -> u32 {\n    (a + b) / 2\n}",
  sol:"pub fn midpoint(a: u32, b: u32) -> u32 {\n    let (lo, hi) = if a < b { (a, b) } else { (b, a) };\n    lo + (hi - lo) / 2\n}",
  test:{"sol.rs":"use ex::midpoint;\n\n#[test]\nfn basic() {\n    assert_eq!(midpoint(2, 4), 3);\n}\n\n#[test]\nfn big() {\n    assert_eq!(midpoint(u32::MAX, u32::MAX), u32::MAX);\n}\n\n#[test]\nfn near_max() {\n    assert_eq!(midpoint(u32::MAX - 2, u32::MAX), u32::MAX - 1);\n}\n\n#[test]\nfn reversed() {\n    assert_eq!(midpoint(10, 4), 7);\n}\n\n#[test]\nfn zero() {\n    assert_eq!(midpoint(0, 0), 0);\n}\n"},
  ex:"🐛 원인: <code>a + b</code> 가 먼저 계산되어 <code>u32</code> 범위를 넘습니다. 러스트는 <b>디버그 빌드에서 오버플로 시 패닉</b>, 릴리스에서는 감싸기(wrapping)로 조용히 틀린 값을 냅니다 — <b>빌드 모드에 따라 증상이 달라지는</b> 최악의 조합입니다.\n🔧 해결: <code>lo + (hi - lo) / 2</code> 는 중간값이 범위를 넘지 않습니다. 큰 쪽·작은 쪽을 정리해야 <code>hi - lo</code> 가 음수(부호 없는 타입에서는 언더플로 패닉)가 되지 않습니다.\n🛡 재발 방지: 러스트는 오버플로 의도를 <b>이름으로 표현</b>하게 합니다 — <code>checked_add</code>(Option) · <code>saturating_add</code>(한계에서 멈춤) · <code>wrapping_add</code>(의도적 감싸기). '어떤 동작을 원하는가' 를 코드에 적으면 리뷰어도 알 수 있습니다." },

{ lang:"rust", k:"Option 을 unwrap 으로 열다 패닉",
  q:"설정 맵에서 값을 읽어 정수로 바꾸는 함수인데, 키가 없거나 숫자가 아니면 패닉이 납니다. 실패를 값으로 돌려주도록 고치세요.",
  src:"use std::collections::HashMap;\n\npub fn read_port(cfg: &HashMap<String, String>) -> Option<u16> {\n    let raw = cfg.get(\"port\").unwrap();\n    Some(raw.parse::<u16>().unwrap())\n}",
  sol:"use std::collections::HashMap;\n\npub fn read_port(cfg: &HashMap<String, String>) -> Option<u16> {\n    cfg.get(\"port\")?.parse::<u16>().ok()\n}",
  test:{"sol.rs":"use ex::read_port;\nuse std::collections::HashMap;\n\nfn cfg(pairs: &[(&str, &str)]) -> HashMap<String, String> {\n    pairs.iter().map(|(k, v)| (k.to_string(), v.to_string())).collect()\n}\n\n#[test]\nfn ok() {\n    assert_eq!(read_port(&cfg(&[(\"port\", \"8080\")])), Some(8080));\n}\n\n#[test]\nfn missing_key() {\n    assert_eq!(read_port(&cfg(&[(\"host\", \"a\")])), None);\n}\n\n#[test]\nfn not_a_number() {\n    assert_eq!(read_port(&cfg(&[(\"port\", \"abc\")])), None);\n}\n\n#[test]\nfn out_of_range() {\n    assert_eq!(read_port(&cfg(&[(\"port\", \"99999\")])), None);\n}\n"},
  ex:"🐛 원인: <code>unwrap()</code> 은 '실패하면 <b>프로세스를 죽여도 좋다</b>' 는 선언입니다. 설정 파일처럼 <b>바깥에서 오는 값</b>은 언제든 없거나 틀릴 수 있는데, 여기에 unwrap 을 쓰면 오타 하나가 서버 전체를 내립니다.\n🔧 해결: <code>?</code> 연산자는 <code>None</code> 이면 즉시 None 을 반환하고, <code>.ok()</code> 는 <code>Result</code> 를 <code>Option</code> 으로 바꿉니다 — 두 줄이 한 줄이 되면서 실패 경로가 <b>타입에 드러납니다</b>.\n🛡 재발 방지: unwrap 이 정당한 곳은 '<b>여기서 실패하면 프로그램 논리가 깨진 것</b>' 인 경우뿐입니다(테스트, 상수 파싱). 그 외에는 <code>?</code>·<code>unwrap_or</code>·<code>match</code> 로 실패를 값으로 다루세요. 왜 안전한지 <code>expect(\"...\")</code> 로 남기는 것도 좋은 습관입니다." },
];
