/* 컴파일러 디버깅 13 — 작은 예제는 통과하는 앞단·뒷단 코드를 고친다.
   계약
     1. src 는 문법 오류가 아니고 TODO 도 없다. 작은 입력에서는 통과하기도 한다.
     2. src 는 tests 중 최소 하나를 실패한다.
     3. sol 은 tests + edge 를 전부 통과한다.
     4. 전부 결정적 — 시각·난수는 쓰지 않는다.
   검증:  node ver_dbgjs.cjs ./dbg_compiler.cjs */
module.exports = [

/* ── 1교시 · 앞단 — 읽고 나누고 세는 곳 ────────────────────────────── */

{ track:"compiler", cat:"debug", k:"두 글자 연산자가 한 글자씩 쪼개진다",
  q:"아주 작은 렉서입니다. 소문자 식별자와 기호를 토큰으로 나누고 공백은 버립니다. <code>==</code>·<code>!=</code>·<code>&lt;=</code>·<code>&gt;=</code> 는 <b>한 토큰</b>이어야 하는데, 파서가 <code>=</code> 를 두 개 받았다며 오류를 냅니다.",
  src:"function tokenize(s) {\n  const out = [];\n  let i = 0;\n  while (i < s.length) {\n    if (s[i] === ' ') { i += 1; continue; }\n    if (/[a-z]/.test(s[i])) {\n      let j = i;\n      while (j < s.length && /[a-z]/.test(s[j])) j += 1;\n      out.push(s.slice(i, j));\n      i = j;\n      continue;\n    }\n    out.push(s[i]);\n    i += 1;\n  }\n  return out;\n}",
  sol:"const TWO = ['==', '!=', '<=', '>='];\nfunction tokenize(s) {\n  const out = [];\n  let i = 0;\n  while (i < s.length) {\n    if (s[i] === ' ') { i += 1; continue; }\n    if (TWO.includes(s.slice(i, i + 2))) { out.push(s.slice(i, i + 2)); i += 2; continue; }\n    if (/[a-z]/.test(s[i])) {\n      let j = i;\n      while (j < s.length && /[a-z]/.test(s[j])) j += 1;\n      out.push(s.slice(i, j));\n      i = j;\n      continue;\n    }\n    out.push(s[i]);\n    i += 1;\n  }\n  return out;\n}",
  tests:[["tokenize('a==b')","['a','==','b']"],
         ["tokenize('a<=b')","['a','<=','b']"],
         ["tokenize('a+b')","['a','+','b']"],
         ["tokenize('x = y')","['x','=','y']"]],
  edge:[["tokenize('')","[]"],
        ["tokenize('a!=b')","['a','!=','b']"]],
  ex:"🐛 원인: 기호를 <b>한 글자씩</b> 집어 내보내고 있습니다. 렉서는 '<b>가장 긴 것부터 맞춰 본다</b>'(최장 일치)가 원칙인데, 그 규칙이 없으니 <code>==</code> 가 <code>=</code> 둘로 쪼개집니다. 단일 문자 연산자만 쓴 예제에서는 전부 통과합니다.\n🔧 해결: 기호를 집기 전에 <b>두 글자짜리 목록</b>을 먼저 맞춰 봅니다. 맞으면 두 칸을 함께 소비합니다.\n🛡 재발 방지: 연산자 표는 <b>긴 것부터 짧은 것 순서</b>로 정렬해 두고 그 순서대로 시도하세요. 세 글자짜리(<code>===</code>·<code>&lt;&lt;=</code>)가 늘어나도 규칙이 그대로 통합니다. 그리고 테스트에는 <b>접두사가 겹치는 연산자 쌍</b>(<code>=</code> 와 <code>==</code>, <code>&lt;</code> 와 <code>&lt;=</code>)을 반드시 함께 넣으세요." },

{ track:"compiler", cat:"debug", k:"키워드가 식별자의 앞부분을 잘라먹는다",
  q:"토큰에 <code>KW:</code>(키워드)와 <code>ID:</code>(식별자) 딱지를 붙입니다. 키워드는 <code>if</code>·<code>in</code>·<code>int</code> 셋입니다. 그런데 <code>iffy</code> 같은 변수 이름이 <b>키워드와 식별자로 쪼개지고</b>, <code>int</code> 는 <code>in</code> 으로 읽힙니다.",
  src:"const KW = ['if', 'in', 'int'];\nfunction classify(s) {\n  const out = [];\n  let i = 0;\n  while (i < s.length) {\n    const kw = KW.find(k => s.startsWith(k, i));\n    if (kw) { out.push('KW:' + kw); i += kw.length; continue; }\n    let j = i;\n    while (j < s.length && /[a-z]/.test(s[j])) j += 1;\n    if (j === i) { i += 1; continue; }\n    out.push('ID:' + s.slice(i, j));\n    i = j;\n  }\n  return out;\n}",
  sol:"const KW = ['if', 'in', 'int'];\nfunction classify(s) {\n  const out = [];\n  let i = 0;\n  while (i < s.length) {\n    let j = i;\n    while (j < s.length && /[a-z]/.test(s[j])) j += 1;\n    if (j === i) { i += 1; continue; }\n    const w = s.slice(i, j);\n    out.push((KW.includes(w) ? 'KW:' : 'ID:') + w);\n    i = j;\n  }\n  return out;\n}",
  tests:[["classify('iffy')","['ID:iffy']"],
         ["classify('int')","['KW:int']"],
         ["classify('int x')","['KW:int','ID:x']"],
         ["classify('if')","['KW:if']"]],
  edge:[["classify('')","[]"],
        ["classify('foo')","['ID:foo']"]],
  ex:"🐛 원인: <b>키워드를 먼저 맞춰 본</b> 것이 잘못입니다. 키워드는 식별자의 <b>앞부분</b>일 수 있으므로, <code>iffy</code> 를 만나면 <code>if</code> 가 먼저 걸립니다. <code>KW.find</code> 는 목록의 앞에서부터 찾으므로 <code>int</code> 도 <code>in</code> 으로 읽힙니다 — 목록 순서에 답이 딸려 가는 것 자체가 위험 신호입니다.\n🔧 해결: <b>식별자를 끝까지 읽은 다음</b> 그 낱말이 키워드 목록에 있는지 봅니다. 렉서의 표준 방식이며 목록 순서와 무관해집니다.\n🛡 재발 방지: '키워드는 <b>예약된 식별자</b>' 라는 정의를 코드 구조가 그대로 담아야 합니다. 테스트에는 <b>키워드로 시작하는 식별자</b>(<code>iffy</code>·<code>inner</code>)와 <b>다른 키워드의 접두사인 키워드</b>(<code>in</code> 과 <code>int</code>)를 반드시 넣으세요." },

{ track:"compiler", cat:"debug", k:"문자열과 주석 안의 기호까지 센다",
  q:"소스에서 <b>문장 구분자 <code>;</code> 의 개수</b>를 셉니다. 작은따옴표 문자열 안이나 <code>//</code> 주석 뒤의 <code>;</code> 는 <b>세지 않아야</b> 합니다. 그런데 문자열이나 주석이 들어간 파일에서 개수가 부풀려집니다.",
  src:"function countSemis(src) {\n  return (src.match(/;/g) || []).length;\n}",
  sol:"function countSemis(src) {\n  let n = 0, i = 0, inStr = false;\n  while (i < src.length) {\n    const c = src[i];\n    if (inStr) {\n      if (c === '\\\\') i += 1;\n      else if (c === \"'\") inStr = false;\n    } else if (c === \"'\") inStr = true;\n    else if (c === '/' && src[i + 1] === '/') {\n      while (i < src.length && src[i] !== '\\n') i += 1;\n      continue;\n    } else if (c === ';') n += 1;\n    i += 1;\n  }\n  return n;\n}",
  tests:[["countSemis(\"x = ';';\")","1"],
         ["countSemis('a; // b;')","1"],
         ["countSemis(\"a;\\n// c;\\nb;\")","2"],
         ["countSemis('a; b;')","2"]],
  edge:[["countSemis('')","0"],
        ["countSemis(\"';;;'\")","0"]],
  ex:"🐛 원인: 정규식은 소스를 <b>글자의 나열</b>로만 봅니다. 문자열 리터럴 안인지 주석 안인지는 <b>지금까지 읽은 것</b>에 따라 달라지는 <b>상태</b>인데, 정규식 하나에는 그 상태가 없습니다. 주석도 문자열도 없는 예제 파일에서는 언제나 통과합니다.\n🔧 해결: 앞에서부터 한 글자씩 읽으며 <b>'지금 문자열 안인가'</b> 를 들고 다닙니다. 이스케이프(<code>\\\\</code>)는 다음 글자를 통째로 건너뛰고, 줄 주석은 줄 끝까지 건너뜁니다. 이것이 곧 <b>렉서를 상태 기계로 쓰는</b> 이유입니다.\n🛡 재발 방지: '소스 코드를 정규식으로 훑는다' 는 아이디어는 <b>중첩과 상태가 없는 문법</b>에서만 통합니다. 세거나 바꿔야 할 대상이 문자열·주석·정규식 리터럴 안에 나타날 수 있다면 반드시 <b>렉서를 거치세요</b> — 테스트에는 그 셋을 각각 하나씩 넣습니다." },

{ track:"compiler", cat:"debug", k:"뺄셈이 오른쪽부터 묶인다",
  q:"한 자리 숫자와 <code>+</code>·<code>-</code> 만 있는 식을 계산하는 재귀 하강 파서입니다. 연산자가 하나면 맞는데, <code>1-2-3</code> 처럼 <b>두 개 이상 이어지면</b> 답이 다릅니다.",
  src:"function evalExpr(s) {\n  const t = s.split('').filter(c => c !== ' ');\n  let i = 0;\n  const expr = () => {\n    const left = Number(t[i]);\n    i += 1;\n    if (t[i] === '-' || t[i] === '+') {\n      const op = t[i];\n      i += 1;\n      const right = expr();\n      return op === '-' ? left - right : left + right;\n    }\n    return left;\n  };\n  return expr();\n}",
  sol:"function evalExpr(s) {\n  const t = s.split('').filter(c => c !== ' ');\n  let i = 0;\n  let acc = Number(t[i]);\n  i += 1;\n  while (t[i] === '-' || t[i] === '+') {\n    const op = t[i];\n    i += 1;\n    const right = Number(t[i]);\n    i += 1;\n    acc = op === '-' ? acc - right : acc + right;\n  }\n  return acc;\n}",
  tests:[["evalExpr('1-2-3')","-4"],
         ["evalExpr('9-1-1-1')","6"],
         ["evalExpr('1-2')","-1"],
         ["evalExpr('5')","5"]],
  edge:[["evalExpr('8-3+2')","7"],
        ["evalExpr('0')","0"]],
  ex:"🐛 원인: 오른쪽 항을 <b>다시 <code>expr()</code> 로</b> 읽으면 <code>1-(2-3)</code> 처럼 <b>오른쪽부터 묶입니다</b>(우결합). 그런데 <code>-</code> 와 <code>+</code> 는 <b>왼쪽부터 묶이는</b>(좌결합) 연산자입니다. 연산자가 하나뿐이면 결합 방향이 결과를 바꾸지 않아 통과합니다.\n🔧 해결: 재귀 대신 <b>반복</b>으로 왼쪽부터 접습니다. 누적값에 오른쪽 항을 차례로 적용하면 그것이 곧 좌결합입니다.\n🛡 재발 방지: 재귀 하강에서 <b>좌결합은 반복으로, 우결합은 재귀로</b> 적습니다(<code>**</code>·<code>=</code> 가 우결합입니다). 문법을 적을 때부터 <code>expr := term (('+'|'-') term)*</code> 처럼 <b>반복 형태</b>로 쓰면 코드가 저절로 맞고, 테스트에는 <b>같은 연산자를 세 개 이상</b> 이은 식을 두세요." },

{ track:"compiler", cat:"debug", k:"스택에 남은 연산자를 안 비운다",
  q:"션팅 야드 알고리즘으로 중위식을 <b>후위식(RPN)</b>으로 바꿉니다. 피연산자와 연산자는 한 글자이고 괄호는 없습니다. 그런데 결과에 <b>연산자가 통째로 빠져</b> 있습니다.",
  src:"function toRpn(s) {\n  const prec = { '+': 1, '-': 1, '*': 2 };\n  const out = [], ops = [];\n  for (const c of s.split('').filter(x => x !== ' ')) {\n    if (prec[c]) {\n      while (ops.length && prec[ops[ops.length - 1]] >= prec[c]) out.push(ops.pop());\n      ops.push(c);\n    } else out.push(c);\n  }\n  return out;\n}",
  sol:"function toRpn(s) {\n  const prec = { '+': 1, '-': 1, '*': 2 };\n  const out = [], ops = [];\n  for (const c of s.split('').filter(x => x !== ' ')) {\n    if (prec[c]) {\n      while (ops.length && prec[ops[ops.length - 1]] >= prec[c]) out.push(ops.pop());\n      ops.push(c);\n    } else out.push(c);\n  }\n  while (ops.length) out.push(ops.pop());\n  return out;\n}",
  tests:[["toRpn('1+2')","['1','2','+']"],
         ["toRpn('1+2*3')","['1','2','3','*','+']"],
         ["toRpn('1*2+3')","['1','2','*','3','+']"],
         ["toRpn('5')","['5']"]],
  edge:[["toRpn('')","[]"],
        ["toRpn('1-2-3')","['1','2','-','3','-']"]],
  ex:"🐛 원인: 연산자는 <b>더 낮거나 같은 우선순위를 만날 때</b>만 스택에서 나옵니다. 입력이 끝나면 그런 기회가 더 없으므로, 스택에 남아 있던 연산자들이 <b>결과에 실리지 않습니다</b>. 피연산자만 있는 입력(<code>'5'</code>)에서는 스택이 비어 있어 통과합니다.\n🔧 해결: 입력을 다 읽은 뒤 <b>스택을 위에서부터 전부 비워</b> 출력에 붙입니다. 알고리즘 명세의 마지막 줄이 바로 이 '드레인' 단계입니다.\n🛡 재발 방지: 스택을 쓰는 변환은 대부분 <b>본문 반복 + 마무리 드레인</b> 두 부분입니다. 어느 한쪽만 적으면 짧은 입력에서만 맞습니다. 결과 길이를 세는 성질 테스트(<b>토큰 수는 보존된다</b>)를 두면 이 누락이 즉시 드러납니다." },

{ track:"compiler", cat:"debug", k:"오류 줄 번호가 하나씩 앞선다",
  q:"오프셋을 <b>줄·칸 번호</b>로 바꿉니다. 둘 다 <b>1 부터</b> 셉니다. 칸은 맞는데 <b>줄 번호가 언제나 하나씩 작아</b>, 편집기가 엉뚱한 줄에 밑줄을 긋습니다.",
  src:"function posOf(src, pos) {\n  const before = src.slice(0, pos);\n  const line = before.split('\\n').length - 1;\n  const col = pos - before.lastIndexOf('\\n');\n  return [line, col];\n}",
  sol:"function posOf(src, pos) {\n  const before = src.slice(0, pos);\n  const line = before.split('\\n').length;\n  const col = pos - before.lastIndexOf('\\n');\n  return [line, col];\n}",
  tests:[["posOf('a\\nb', 0)","[1,1]"],
         ["posOf('a\\nb', 2)","[2,1]"],
         ["posOf('abc', 3)","[1,4]"],
         ["posOf('a\\n\\nb', 3)","[3,1]"]],
  edge:[["posOf('', 0)","[1,1]"],
        ["posOf('a\\nbcd', 4)","[2,3]"]],
  ex:"🐛 원인: <code>split('\\n')</code> 이 돌려주는 조각 수가 곧 <b>줄 수</b>입니다 — 줄바꿈이 하나도 없으면 조각 하나, 즉 1 번째 줄입니다. 거기서 1 을 더 빼면 <b>0 부터 세는 번호</b>가 되어 편집기가 쓰는 1 기반 번호와 어긋납니다. 칸 번호는 <code>lastIndexOf</code> 가 없을 때 <code>-1</code> 을 주는 덕에 우연히 1 기반으로 맞았습니다.\n🔧 해결: 빼기를 없앱니다. '조각 수 = 줄 번호' 라는 관계를 그대로 씁니다.\n🛡 재발 방지: 진단 메시지의 자리 정보는 <b>0 기반과 1 기반이 만나는 대표적인 자리</b>입니다. 내부는 0 기반 오프셋으로만 다루고 <b>사람에게 보여 줄 때 한 번만</b> 1 을 더하도록 층을 나누세요. 테스트에는 <b>첫 글자</b>·<b>줄바꿈 직후</b>·<b>빈 줄</b> 세 가지를 넣습니다." },

{ track:"compiler", cat:"debug", k:"매크로 인자가 낱말 안까지 치환된다",
  q:"아주 단순한 매크로 확장기입니다. 인자 이름이 <b>낱말 하나로 나올 때만</b> 값으로 바꿔야 합니다. 그런데 <code>x</code> 를 바꾸면 <code>xy</code> 의 앞글자까지 바뀌고, 이름이 서로의 앞부분이면 순서에 따라 결과가 달라집니다.",
  src:"function expand(tmpl, args) {\n  let out = tmpl;\n  for (const k of Object.keys(args)) out = out.split(k).join(String(args[k]));\n  return out;\n}",
  sol:"function expand(tmpl, args) {\n  return tmpl.replace(/[A-Za-z_][A-Za-z0-9_]*/g,\n    w => (Object.prototype.hasOwnProperty.call(args, w) ? String(args[w]) : w));\n}",
  tests:[["expand('x + xy', { x: 1 })","'1 + xy'"],
         ["expand('ab + a', { a: 1, ab: 2 })","'2 + 1'"],
         ["expand('aa', { a: 1 })","'aa'"],
         ["expand('a', { a: 2 })","'2'"]],
  edge:[["expand('', { a: 1 })","''"],
        ["expand('z', { a: 1 })","'z'"]],
  ex:"🐛 원인: <code>split</code>/<code>join</code> 은 <b>글자 나열</b>을 바꿉니다. 매크로 인자는 <b>낱말(토큰)</b> 단위인데 그 경계를 모르니 <code>xy</code> 의 앞글자까지 먹습니다. 게다가 이름을 <b>하나씩 차례로</b> 바꾸므로, 짧은 이름을 먼저 바꾸면 긴 이름이 이미 사라져 결과가 <code>Object.keys</code> 순서에 딸려 갑니다.\n🔧 해결: 소스를 <b>낱말 단위로 훑으면서</b> 그 낱말이 인자 목록에 있을 때만 바꿉니다. 한 번의 훑기로 끝나므로 순서 의존성도 함께 사라집니다.\n🛡 재발 방지: 치환은 <b>파싱한 단위</b> 위에서 해야 합니다. 낱말·경로 조각·SQL 자리표 모두 같습니다. 그리고 '<b>여러 번 치환</b>' 은 앞선 치환의 결과를 다시 치환할 위험이 있으므로 <b>한 번의 훑기</b>로 끝내세요 — 테스트에는 <b>이름이 서로의 앞부분인 경우</b>를 반드시 넣습니다." },

/* ── 2교시 · 뒷단 — 이름·순서·부수효과 ─────────────────────────────── */

{ track:"compiler", cat:"debug", k:"블록을 빠져나가도 이름이 살아 있다",
  q:"아주 작은 이름 해석기입니다. <code>push</code>·<code>pop</code> 은 블록의 시작과 끝, <code>let</code> 은 선언, <code>use</code> 는 조회이며 없으면 <code>null</code> 입니다. 그런데 <b>블록 안에서 선언한 이름이 블록 밖에서도</b> 보이고, 바깥 이름은 <b>안쪽 값으로 덮인 채</b> 돌아옵니다.",
  src:"function resolve(prog) {\n  const scope = new Map();\n  const out = [];\n  for (const st of prog) {\n    if (st[0] === 'let') scope.set(st[1], st[2]);\n    if (st[0] === 'use') out.push(scope.has(st[1]) ? scope.get(st[1]) : null);\n  }\n  return out;\n}",
  sol:"function resolve(prog) {\n  const stack = [new Map()];\n  const out = [];\n  for (const st of prog) {\n    if (st[0] === 'push') stack.push(new Map());\n    else if (st[0] === 'pop') stack.pop();\n    else if (st[0] === 'let') stack[stack.length - 1].set(st[1], st[2]);\n    else if (st[0] === 'use') {\n      let v = null;\n      for (let i = stack.length - 1; i >= 0; i -= 1) {\n        if (stack[i].has(st[1])) { v = stack[i].get(st[1]); break; }\n      }\n      out.push(v);\n    }\n  }\n  return out;\n}",
  tests:[["resolve([['let','x',1],['push'],['let','x',2],['use','x'],['pop'],['use','x']])","[2,1]"],
         ["resolve([['push'],['let','y',5],['pop'],['use','y']])","[null]"],
         ["resolve([['let','x',1],['use','x']])","[1]"],
         ["resolve([['use','z']])","[null]"]],
  edge:[["resolve([])","[]"],
        ["resolve([['push'],['use','q'],['pop']])","[null]"]],
  ex:"🐛 원인: 심볼 테이블이 <b>맵 하나</b>뿐이라 블록 개념이 없습니다. 안쪽 선언이 바깥 이름을 <b>영구히 덮어쓰고</b>, 블록을 나가도 지워지지 않습니다. 블록이 없거나 이름이 겹치지 않는 예제에서는 완벽히 동작합니다.\n🔧 해결: 맵을 <b>스택</b>으로 쌓습니다. <code>push</code> 는 새 맵을 얹고 <code>pop</code> 은 벗기며, 조회는 <b>안쪽부터 바깥으로</b> 훑습니다. 이것이 렉시컬 스코프의 정의 그대로입니다.\n🛡 재발 방지: 이름 해석 테스트의 핵심은 <b>가림(shadowing)</b>과 <b>수명</b>입니다 — 안쪽에서 같은 이름을 선언하고 나간 뒤 바깥 값이 <b>원래대로</b>인지, 안쪽 이름이 밖에서 <b>안 보이는지</b> 두 가지를 항상 확인하세요. 나중에 클로저를 붙이려면 <code>pop</code> 대신 <b>스코프를 노드에 매다는</b> 설계로 바꿔야 합니다." },

{ track:"compiler", cat:"debug", k:"클로저가 반복 변수를 함께 쓴다",
  q:"목록의 각 원소를 돌려주는 <b>함수들</b>을 만들고, 만든 순서대로 불러 결과를 모읍니다. 원소가 없으면 빈 배열입니다. 그런데 결과가 전부 <code>null</code> 로 나옵니다.",
  src:"function makeGetters(ns) {\n  const out = [];\n  for (var i = 0; i < ns.length; i += 1) out.push(() => ns[i]);\n  return out.map(f => f());\n}",
  sol:"function makeGetters(ns) {\n  const out = [];\n  for (let i = 0; i < ns.length; i += 1) out.push(() => ns[i]);\n  return out.map(f => f());\n}",
  tests:[["makeGetters([1,2,3])","[1,2,3]"],
         ["makeGetters([9])","[9]"],
         ["makeGetters([1,2])","[1,2]"],
         ["makeGetters([])","[]"]],
  edge:[["makeGetters([0])","[0]"],
        ["makeGetters([5,6,7])","[5,6,7]"]],
  ex:"🐛 원인: <code>var</code> 는 <b>함수 하나를 통째로</b> 스코프로 삼습니다. 그래서 반복문이 만든 모든 화살표 함수가 <b>같은 변수 <code>i</code> 하나</b>를 붙듭니다. 반복이 끝나면 <code>i</code> 는 <code>ns.length</code> 이므로 전부 범위 밖을 읽어 <code>undefined</code> 가 나옵니다.\n🔧 해결: <code>let</code> 은 <b>반복마다 새 바인딩</b>을 만듭니다. 각 함수가 자기 몫의 <code>i</code> 를 잡으므로 만든 시점의 값이 그대로 남습니다.\n🛡 재발 방지: 컴파일러 눈으로 보면 이것은 '<b>바인딩을 언제 새로 만드는가</b>' 의 문제입니다. 클로저를 만드는 반복문에서는 잡히는 변수의 <b>수명과 개수</b>를 먼저 세어 보세요. 함수를 만들어 모아 두었다가 <b>나중에 부르는</b> 코드(콜백 등록·지연 평가·태스크 큐)가 이 버그의 단골 자리입니다." },

{ track:"compiler", cat:"debug", k:"상수 접기가 한 겹만 내려간다",
  q:"덧셈 트리에서 <b>상수끼리의 덧셈</b>을 미리 계산해 접습니다. 노드는 <code>num</code>·<code>var</code>·<code>add</code> 셋입니다. 한 겹짜리 식은 접히는데, <b>중첩된 식</b>은 그대로 남습니다.",
  src:"function fold(n) {\n  if (n.k === 'num') return n;\n  if (n.l.k === 'num' && n.r.k === 'num') return { k: 'num', v: n.l.v + n.r.v };\n  return n;\n}",
  sol:"function fold(n) {\n  if (n.k === 'num' || n.k === 'var') return n;\n  const l = fold(n.l), r = fold(n.r);\n  if (l.k === 'num' && r.k === 'num') return { k: 'num', v: l.v + r.v };\n  return { k: n.k, l, r };\n}",
  tests:[["fold({k:'add', l:{k:'add', l:{k:'num',v:1}, r:{k:'num',v:2}}, r:{k:'num',v:3}})","{k:'num', v:6}"],
         ["fold({k:'add', l:{k:'num',v:1}, r:{k:'add', l:{k:'num',v:2}, r:{k:'num',v:3}}})","{k:'num', v:6}"],
         ["fold({k:'add', l:{k:'num',v:1}, r:{k:'num',v:2}})","{k:'num', v:3}"],
         ["fold({k:'add', l:{k:'var',n:'x'}, r:{k:'num',v:2}})","{k:'add', l:{k:'var',n:'x'}, r:{k:'num',v:2}}"]],
  edge:[["fold({k:'num', v:0})","{k:'num', v:0}"],
        ["fold({k:'add', l:{k:'add', l:{k:'var',n:'x'}, r:{k:'num',v:1}}, r:{k:'num',v:2}})","{k:'add', l:{k:'add', l:{k:'var',n:'x'}, r:{k:'num',v:1}}, r:{k:'num',v:2}}"]],
  ex:"🐛 원인: 자식을 <b>먼저 접지 않고</b> 지금 노드만 봅니다. <code>(1+2)+3</code> 의 왼쪽 자식은 아직 <code>add</code> 이므로 '상수 둘' 조건에 걸리지 않아 통째로 남습니다. 깊이 1 짜리 예제에서는 완벽히 동작합니다.\n🔧 해결: <b>후위 순회</b>로 만듭니다 — 자식을 먼저 접고, 그 결과가 둘 다 상수일 때 지금 노드를 접습니다. 접히지 않으면 <b>접힌 자식으로 새 노드</b>를 만들어 돌려줍니다.\n🛡 재발 방지: 트리를 바꾸는 패스는 '<b>어느 순서로 방문하는가</b>' 가 곧 알고리즘입니다. 상수 접기·타입 추론·크기 계산은 <b>아래에서 위로</b>(후위), 스코프 주입·상수 전파는 <b>위에서 아래로</b>(전위)입니다. 테스트에는 <b>깊이 2 이상</b>의 트리와 <b>일부만 접히는</b> 트리를 넣으세요." },

{ track:"compiler", cat:"debug", k:"부수효과가 있는 명령까지 지운다",
  q:"결과를 <b>아무도 쓰지 않는</b> 명령을 한 번의 훑기로 지웁니다. 다만 <code>eff:true</code> 인 명령은 <b>부수효과</b>가 있으므로 남겨야 합니다. 그런데 반환값을 안 쓰는 함수 호출이 통째로 사라져 <b>로그도 저장도 안 됩니다</b>.",
  src:"function dce(instrs) {\n  const used = new Set();\n  for (const it of instrs) (it.args || []).forEach(a => used.add(a));\n  return instrs.filter(it => used.has(it.dst)).map(it => it.id);\n}",
  sol:"function dce(instrs) {\n  const used = new Set();\n  for (const it of instrs) (it.args || []).forEach(a => used.add(a));\n  return instrs.filter(it => it.eff || used.has(it.dst)).map(it => it.id);\n}",
  tests:[["dce([{id:1,dst:'r',args:[],eff:true}])","[1]"],
         ["dce([{id:1,dst:'x',args:[]},{id:2,dst:'y',args:['x'],eff:true}])","[1,2]"],
         ["dce([{id:1,dst:'a',args:[]},{id:2,dst:'b',args:['a']}])","[1]"],
         ["dce([])","[]"]],
  edge:[["dce([{id:1,dst:'a',args:['a']}])","[1]"],
        ["dce([{id:1,dst:'a',args:[]}])","[]"]],
  ex:"🐛 원인: '쓰이지 않는 값' 과 '<b>하는 일이 없는 명령</b>' 을 같은 것으로 봤습니다. 파일 쓰기·네트워크 호출·전역 변경은 <b>결과를 안 써도 반드시 실행돼야</b> 합니다. 모든 명령이 순수한 예제에서는 최적화가 완벽해 보입니다.\n🔧 해결: 부수효과 표시를 살아 있음의 <b>또 다른 근거</b>로 넣습니다 — <code>it.eff || used.has(it.dst)</code>.\n🛡 재발 방지: 최적화 패스는 '<b>관찰 가능한 동작을 바꾸지 않는다</b>' 는 약속 위에서만 정당합니다. 그래서 IR 은 명령마다 <b>순수한가</b>를 들고 다녀야 하고, 모르면 <b>보수적으로 부수효과 있음</b>으로 둬야 합니다. 최적화 테스트에는 언제나 <b>부수효과가 있는 명령</b>을 하나 섞어 두세요." },

{ track:"compiler", cat:"debug", k:"나중에 정의된 심볼을 미정의로 본다",
  q:"오브젝트 파일들을 링크해 <b>정의를 못 찾은 심볼</b>을 사전순으로 모읍니다. 정의가 <b>먼저</b> 나오면 맞는데, 쓰는 쪽이 앞에 있고 정의가 <b>뒤 파일</b>에 있으면 미정의로 잘못 보고합니다.",
  src:"function link(objs) {\n  const def = new Set();\n  const missing = [];\n  for (const o of objs) {\n    (o.use || []).forEach(s => { if (!def.has(s)) missing.push(s); });\n    (o.def || []).forEach(s => def.add(s));\n  }\n  return [...new Set(missing)].sort();\n}",
  sol:"function link(objs) {\n  const def = new Set(), need = new Set();\n  for (const o of objs) {\n    (o.def || []).forEach(s => def.add(s));\n    (o.use || []).forEach(s => need.add(s));\n  }\n  return [...need].filter(s => !def.has(s)).sort();\n}",
  tests:[["link([{use:['f']},{def:['f']}])","[]"],
         ["link([{use:['z']},{use:['z']},{def:['z']}])","[]"],
         ["link([{def:['f']},{use:['f']}])","[]"],
         ["link([{use:['g']}])","['g']"]],
  edge:[["link([])","[]"],
        ["link([{def:['a']},{use:['a','b']}])","['b']"]],
  ex:"🐛 원인: 정의 집합을 <b>훑는 도중에 채우면서</b> 그때그때 판정했습니다. 그래서 판정 시점에 아직 안 읽은 파일의 정의는 없는 것으로 보입니다. 컴파일 순서를 바꾸면 결과가 달라지는데, 링커의 심볼 해석은 <b>파일 순서와 무관</b>해야 합니다.\n🔧 해결: <b>두 번 훑습니다</b> — 먼저 모든 정의와 모든 참조를 모으고, 그다음 차집합을 냅니다. 판정이 <b>전체를 다 본 뒤</b>에 일어나므로 순서에 흔들리지 않습니다.\n🛡 재발 방지: '모으고 나서 판정한다' 는 이름 해석·의존성 검사·미사용 탐지에 공통으로 필요한 구조입니다. 한 번의 훑기로 답하려면 <b>전방 참조가 없다</b>는 근거가 있어야 합니다. 테스트에는 같은 입력을 <b>순서만 바꿔</b> 두 벌 넣으면 이 부류가 전부 잡힙니다." },

{ track:"compiler", cat:"debug", k:"스택에서 꺼낸 두 값의 순서가 뒤집혔다",
  q:"아주 작은 스택 머신입니다. <code>push</code> 로 값을 얹고 <code>sub</code>·<code>div</code> 는 <b>먼저 얹은 값에서 나중 값을</b> 빼거나 나눕니다. 마지막에 스택 맨 위를 돌려줍니다. 그런데 뺄셈의 부호가 뒤집히고 나눗셈이 역수로 나옵니다.",
  src:"function run(code) {\n  const st = [];\n  for (const ins of code) {\n    if (ins[0] === 'push') st.push(ins[1]);\n    else {\n      const a = st.pop(), b = st.pop();\n      st.push(ins[0] === 'sub' ? a - b : a / b);\n    }\n  }\n  return st[st.length - 1];\n}",
  sol:"function run(code) {\n  const st = [];\n  for (const ins of code) {\n    if (ins[0] === 'push') st.push(ins[1]);\n    else {\n      const a = st.pop(), b = st.pop();\n      st.push(ins[0] === 'sub' ? b - a : b / a);\n    }\n  }\n  return st[st.length - 1];\n}",
  tests:[["run([['push',10],['push',3],['sub']])","7"],
         ["run([['push',12],['push',4],['div']])","3"],
         ["run([['push',1],['push',1],['sub']])","0"],
         ["run([['push',5]])","5"]],
  edge:[["run([['push',8],['push',2],['div'],['push',1],['sub']])","3"],
        ["run([['push',0],['push',5],['sub']])","-5"]],
  ex:"🐛 원인: 스택은 <b>나중에 넣은 것이 먼저 나옵니다</b>. 그래서 첫 <code>pop</code> 이 <b>오른쪽 피연산자</b>이고 두 번째 <code>pop</code> 이 왼쪽입니다. 이름을 <code>a</code>·<code>b</code> 로 붙이고 <code>a - b</code> 라고 적는 순간 순서가 뒤집힙니다. 덧셈·곱셈만으로 시험하면 <b>교환법칙 덕분에</b> 전부 통과합니다.\n🔧 해결: 꺼낸 순서를 그대로 뜻으로 옮깁니다 — 나중에 꺼낸 것이 왼쪽이므로 <code>b - a</code>·<code>b / a</code> 입니다. 이름을 <code>rhs</code>·<code>lhs</code> 로 두면 실수가 줄어듭니다.\n🛡 재발 방지: 스택 머신·RPN·후위 순회 코드 생성은 전부 이 함정을 공유합니다. 테스트를 <b>교환법칙이 없는 연산</b>(<code>-</code>·<code>/</code>·<code>%</code>·비교)으로 만들고, 같은 값 두 개(<code>1-1</code>)로만 시험하지 마세요 — 그런 입력은 뒤집혀도 통과합니다." },

];
