/* 네트워크 디버깅 12 — 규약을 반쯤만 지킨 코드를 고친다.
   전부 결정적이고 순수 JS 다. 검증:  node ver_dbgjs.cjs ./dbg_net.cjs */
module.exports = [

{ track:"net", cat:"debug", k:"프리픽스 길이 0 에서 무너지는 CIDR",
  q:"IP 가 CIDR 대역에 드는지 보는 함수입니다. 사내 대역 판정은 잘 되는데, <b>기본 경로</b>를 뜻하는 <code>0.0.0.0/0</code> 을 넣으면 자기 자신 말고는 아무것도 맞지 않습니다.",
  src:"function matchCidr(cidr, ip) {\n  const [net, bitsText] = cidr.split('/');\n  const bits = Number(bitsText);\n  const toN = s => s.split('.').reduce((a, o) => a * 256 + Number(o), 0);\n  const mask = -1 << (32 - bits);\n  return (toN(net) & mask) === (toN(ip) & mask);\n}",
  sol:"function matchCidr(cidr, ip) {\n  const [net, bitsText] = cidr.split('/');\n  const bits = Number(bitsText);\n  const toN = s => s.split('.').reduce((a, o) => a * 256 + Number(o), 0) >>> 0;\n  const mask = bits === 0 ? 0 : (-1 << (32 - bits)) >>> 0;\n  return ((toN(net) & mask) >>> 0) === ((toN(ip) & mask) >>> 0);\n}",
  tests:[["matchCidr('10.0.0.0/8', '10.1.2.3')","true"],
         ["matchCidr('10.0.0.0/8', '11.1.2.3')","false"],
         ["matchCidr('0.0.0.0/0', '8.8.8.8')","true"],
         ["matchCidr('192.168.1.1/32', '192.168.1.1')","true"]],
  edge:[["matchCidr('255.255.255.0/24', '255.255.255.9')","true"],
        ["matchCidr('0.0.0.0/0', '0.0.0.0')","true"]],
  ex:"🐛 원인: 자바스크립트의 시프트 연산은 <b>자릿수를 32 로 나눈 나머지</b>만 씁니다. <code>bits = 0</code> 이면 <code>-1 &lt;&lt; 32</code> 가 되는데 이는 <code>-1 &lt;&lt; 0</code> 과 같아 마스크가 <code>0</code> 이 아니라 <b>전부 1</b> 이 됩니다. 그래서 '모든 주소' 를 뜻하는 <code>/0</code> 이 '완전히 같은 주소' 로 뒤집힙니다.\n🔧 해결: <code>bits === 0</code> 을 따로 갈라 마스크를 <code>0</code> 으로 둡니다. 그리고 비트 연산의 결과는 <b>부호 있는 32비트</b>라 <code>&gt;&gt;&gt; 0</code> 으로 부호 없는 수로 되돌려 두는 편이 안전합니다.\n🛡 재발 방지: 시프트 자릿수가 <b>변수</b>일 때는 0 과 32 를 반드시 테스트에 넣으세요. 같은 함정이 <code>1 &lt;&lt; 32</code>(= 1), 해시의 <code>&gt;&gt;</code> 와 <code>&gt;&gt;&gt;</code> 혼용에서도 나옵니다. 마스크를 만들 때는 <code>2 ** (32 - bits)</code> 처럼 산술로 적으면 이 함정을 피할 수 있습니다." },

{ track:"net", cat:"debug", k:"IPv4 를 검사 없이 받아들인다",
  q:"IPv4 문자열을 32비트 정수로 바꾸는 함수입니다. 잘못된 주소는 <code>null</code> 을 돌려줘야 하는데, <code>256.0.0.1</code> 같은 값이 그대로 통과해 <b>엉뚱한 대역</b>으로 계산됩니다.",
  src:"function parseIpv4(s) {\n  const octets = String(s).split('.');\n  if (octets.length !== 4) return null;\n  return octets.reduce((a, o) => a * 256 + Number(o), 0);\n}",
  sol:"function parseIpv4(s) {\n  const octets = String(s).split('.');\n  if (octets.length !== 4) return null;\n  let out = 0;\n  for (const one of octets) {\n    if (!/^(0|[1-9][0-9]{0,2})$/.test(one)) return null;\n    const n = Number(one);\n    if (n > 255) return null;\n    out = out * 256 + n;\n  }\n  return out;\n}",
  tests:[["parseIpv4('1.2.3.4')","16909060"],
         ["parseIpv4('256.0.0.1')","null"],
         ["parseIpv4('1.2.3')","null"],
         ["parseIpv4('1.2.3.x')","null"]],
  edge:[["parseIpv4('0.0.0.0')","0"],
        ["parseIpv4('01.2.3.4')","null"]],
  ex:"🐛 원인: 마디 개수만 세고 <b>값의 범위와 모양</b>은 보지 않았습니다. <code>Number('x')</code> 는 <code>NaN</code> 이라 결과가 조용히 <code>NaN</code> 이 되고, <code>256</code> 은 다음 마디로 자리올림되어 <b>전혀 다른 주소</b>가 됩니다.\n🔧 해결: 마디마다 '숫자 1~3자리' 와 '255 이하' 를 확인합니다. <code>01</code> 처럼 앞에 0 이 붙은 표기도 막아야 합니다 — 일부 라이브러리는 이를 <b>8진수</b>로 읽어 같은 문자열이 서로 다른 주소가 됩니다.\n🛡 재발 방지: 주소·포트·경로처럼 <b>바깥에서 들어오는 문자열</b>은 '파싱하면서 검증' 해야 합니다. 파싱 결과가 <code>NaN</code> 인지 나중에 확인하는 방식은 <code>NaN</code> 이 산술을 타고 번져 원인 지점에서 멀어집니다. SSRF 우회는 대부분 이 느슨한 파서에서 시작합니다." },

{ track:"net", cat:"debug", k:"체크섬에서 자리올림을 접지 않았다",
  q:"16비트 낱말들의 <b>1의 보수 합</b> 체크섬입니다. 넘친 자리올림은 다시 하위 16비트에 <b>더해 접어야</b> 합니다. 지금은 값이 큰 패킷에서 상대가 계산한 값과 어긋납니다.",
  src:"function onesComplement(words) {\n  let sum = 0;\n  for (const w of words) sum += w;\n  return (~sum) & 0xffff;\n}",
  sol:"function onesComplement(words) {\n  let sum = 0;\n  for (const w of words) sum += w;\n  while (sum > 0xffff) sum = (sum & 0xffff) + (sum >>> 16);\n  return (~sum) & 0xffff;\n}",
  tests:[["onesComplement([0, 0])","65535"],
         ["onesComplement([1, 2])","65532"],
         ["onesComplement([0xffff, 1])","65534"],
         ["onesComplement([0xffff, 0xffff])","0"]],
  edge:[["onesComplement([])","65535"],
        ["onesComplement([0x8000, 0x8000])","65534"]],
  ex:"🐛 원인: 16비트끼리 더하면 <b>17비트가 되는 순간</b>이 옵니다. 1의 보수 산술에서는 넘친 자리를 버리는 것이 아니라 <b>하위로 되돌려 더합니다</b>(end-around carry). 그 접기를 빼먹으면 넘치기 전에는 맞고 넘친 뒤부터 틀립니다 — 짧은 패킷 테스트로는 안 잡힙니다.\n🔧 해결: <code>sum &gt; 0xffff</code> 인 동안 <code>(sum &amp; 0xffff) + (sum &gt;&gt;&gt; 16)</code> 으로 접습니다. 한 번으로 끝나지 않을 수 있어 <b>반복</b>해야 합니다.\n🛡 재발 방지: 이 체크섬의 좋은 성질은 <b>순서와 무관</b>하고, 검증 시 체크섬까지 포함해 더하면 결과가 0xffff 가 된다는 것입니다. 그 성질을 테스트로 걸면 개별 값 하나하나를 손으로 계산하지 않아도 됩니다. TCP·UDP 는 여기에 의사 헤더까지 더한다는 점도 함께 기억하세요." },

{ track:"net", cat:"debug", k:"조각 크기는 8의 배수여야 한다",
  q:"IPv4 조각내기입니다. 각 조각의 페이로드는 링크 MTU 에서 헤더를 뺀 크기를 넘을 수 없고, <b>마지막 조각을 뺀 나머지는 8의 배수</b>여야 합니다(오프셋을 8바이트 단위로 세기 때문). 지금 계산한 조각을 상대가 <b>재조립하지 못합니다</b>.",
  src:"function fragments(total, mtu, hdr) {\n  const per = mtu - hdr;\n  const out = [];\n  let left = total;\n  while (left > 0) {\n    const n = Math.min(per, left);\n    out.push(n);\n    left -= n;\n  }\n  return out;\n}",
  sol:"function fragments(total, mtu, hdr) {\n  const per = Math.floor((mtu - hdr) / 8) * 8;\n  const out = [];\n  let left = total;\n  while (left > 0) {\n    const n = Math.min(per, left);\n    out.push(n);\n    left -= n;\n  }\n  return out;\n}",
  tests:[["fragments(3000, 1500, 24)","[1472,1472,56]"],
         ["fragments(2960, 1500, 20)","[1480,1480]"],
         ["fragments(100, 1500, 20)","[100]"],
         ["fragments(0, 1500, 20)","[]"]],
  edge:[["fragments(1480, 1500, 20)","[1480]"],
        ["fragments(10, 68, 20)","[10]"]],
  ex:"🐛 원인: IPv4 헤더의 조각 오프셋은 <b>8바이트 단위</b>로 셉니다. 그래서 마지막이 아닌 조각의 페이로드는 반드시 8의 배수여야 하고, 그렇지 않으면 오프셋으로 표현할 수 없어 재조립이 어긋납니다. 헤더가 20바이트(1480, 8의 배수)일 때는 우연히 맞아서 <b>옵션이 붙은 헤더</b>에서만 드러납니다.\n🔧 해결: 조각 크기를 <code>Math.floor((mtu - hdr) / 8) * 8</code> 로 내림합니다. 마지막 조각만 아무 크기나 될 수 있습니다.\n🛡 재발 방지: '우연히 맞는 상수' 가 테스트를 통과시키는 전형적인 예입니다. 헤더 길이를 20 이 아닌 값으로 한 번만 넣어 보면 바로 드러납니다. 실무에서는 애초에 <b>Path MTU Discovery</b> 로 조각내기를 피하고, 조각이 생기면 방화벽이 뒷조각을 버려 '가끔 큰 응답만 실패' 하는 증상이 됩니다." },

{ track:"net", cat:"debug", k:"만료된 캐시가 음수 TTL 을 돌려준다",
  q:"DNS 캐시 항목의 남은 수명을 초 단위로 돌려주는 함수입니다. 이미 만료됐으면 <b>0</b> 이어야 하는데, 오래 지난 항목에서 <b>음수</b>가 나와 재조회 스케줄러가 과거 시각에 예약을 겁니다.",
  src:"function ttlLeft(entry, now) {\n  return entry.ttl - (now - entry.at);\n}",
  sol:"function ttlLeft(entry, now) {\n  return Math.max(0, entry.ttl - (now - entry.at));\n}",
  tests:[["ttlLeft({at:0, ttl:60}, 10)","50"],
         ["ttlLeft({at:0, ttl:60}, 60)","0"],
         ["ttlLeft({at:0, ttl:60}, 90)","0"],
         ["ttlLeft({at:100, ttl:5}, 101)","4"]],
  edge:[["ttlLeft({at:0, ttl:0}, 0)","0"],
        ["ttlLeft({at:0, ttl:60}, 0)","60"]],
  ex:"🐛 원인: 뺄셈 결과를 그대로 돌려주니 만료 뒤에는 <b>음수</b>가 됩니다. 호출하는 쪽이 이 값을 <code>setTimeout</code> 이나 <code>Cache-Control: max-age</code> 에 그대로 넣으면 '즉시' 가 아니라 <b>정의되지 않은 동작</b>이 됩니다.\n🔧 해결: <code>Math.max(0, …)</code> 한 줄로 값의 범위를 계약에 맞춥니다. 정확히 만료된 순간(<code>now - at === ttl</code>)이 0 이라는 것도 함께 못 박습니다.\n🛡 재발 방지: '남은 시간' 처럼 <b>음수가 뜻을 갖지 않는 값</b>은 만드는 자리에서 잘라 두세요. 받는 쪽마다 방어하면 한 곳을 빠뜨립니다. 그리고 시각을 인자로 받게 만들면(<code>now</code>) 만료 경계를 테스트로 고정할 수 있습니다 — <code>Date.now()</code> 를 함수 안에서 부르면 이 테스트 자체를 쓸 수 없습니다." },

{ track:"net", cat:"debug", k:"q=0 은 '싫다' 는 뜻이다",
  q:"<code>Accept</code> 헤더를 보고 응답 형식을 고르는 함수입니다. 품질값(<code>q</code>)이 가장 높은 형식을 고르고, 생산할 수 없으면 <code>null</code> 입니다. 그런데 클라이언트가 <b>명시적으로 거부한</b> 형식을 골라 406 을 받습니다.",
  src:"function pickType(header, have) {\n  const wants = String(header).split(',').map(p => {\n    const bits = p.trim().split(';');\n    const q = bits.slice(1).map(r => r.trim()).find(r => r.startsWith('q='));\n    return { type: bits[0].trim(), q: q ? Number(q.slice(2)) : 1 };\n  });\n  let best = null;\n  for (const w of wants) {\n    if (have.indexOf(w.type) < 0) continue;\n    if (!best || w.q > best.q) best = w;\n  }\n  return best ? best.type : null;\n}",
  sol:"function pickType(header, have) {\n  const wants = String(header).split(',').map(p => {\n    const bits = p.trim().split(';');\n    const q = bits.slice(1).map(r => r.trim()).find(r => r.startsWith('q='));\n    return { type: bits[0].trim(), q: q ? Number(q.slice(2)) : 1 };\n  });\n  let best = null;\n  for (const w of wants) {\n    if (have.indexOf(w.type) < 0) continue;\n    if (!(w.q > 0)) continue;\n    if (!best || w.q > best.q) best = w;\n  }\n  return best ? best.type : null;\n}",
  tests:[["pickType('text/html;q=0.8, application/json', ['application/json','text/html'])","'application/json'"],
         ["pickType('application/json;q=0', ['application/json'])","null"],
         ["pickType('text/html', ['application/json'])","null"],
         ["pickType('a/b;q=0.5, c/d;q=0.9', ['a/b','c/d'])","'c/d'"]],
  edge:[["pickType('', ['a/b'])","null"],
        ["pickType('a/b;q=0, c/d;q=0.1', ['a/b','c/d'])","'c/d'"]],
  ex:"🐛 원인: <code>q</code> 는 단순한 우선순위 점수가 아닙니다. <b><code>q=0</code> 은 '이 형식은 받지 않겠다'</b> 는 명시적 거부입니다(RFC 9110). 점수만 견주면 후보가 그것뿐일 때 거부된 형식을 골라 버립니다.\n🔧 해결: <code>q</code> 가 0 이하인 항목은 후보에서 아예 뺍니다. <code>NaN</code> 도 함께 걸러지도록 <code>!(w.q &gt; 0)</code> 로 적은 것이 요령입니다 — <code>w.q &lt;= 0</code> 은 <code>NaN</code> 을 통과시킵니다.\n🛡 재발 방지: 규약의 특수값(<code>q=0</code>, <code>max-age=0</code>, <code>*</code>, <code>identity;q=0</code>)은 <b>일반 규칙의 예외</b>라서 구현에서 가장 자주 빠집니다. 헤더를 다루는 함수를 쓸 때는 규약 문서에서 그 필드의 '0 과 * 의 뜻' 을 먼저 찾아 테스트로 옮겨 두세요." },

{ track:"net", cat:"debug", k:"Retry-After 는 초일 수도 날짜일 수도 있다",
  q:"<code>Retry-After</code> 값을 밀리초 대기 시간으로 바꾸는 함수입니다. 값은 <b>초</b>이거나 <b>HTTP 날짜</b>입니다. 해석할 수 없으면 <code>null</code> 입니다. 지금은 날짜 형식이 오면 <code>NaN</code> 이 되어 재시도 스케줄이 통째로 깨집니다.",
  src:"function retryAfterMs(value, now) {\n  return Number(value) * 1000;\n}",
  sol:"function retryAfterMs(value, now) {\n  const s = String(value).trim();\n  if (/^\\d+$/.test(s)) return Number(s) * 1000;\n  const at = Date.parse(s);\n  if (Number.isNaN(at)) return null;\n  return Math.max(0, at - now);\n}",
  tests:[["retryAfterMs('120', 0)","120000"],
         ["retryAfterMs('Wed, 21 Oct 2015 07:28:00 GMT', Date.parse('Wed, 21 Oct 2015 07:28:00 GMT') - 5000)","5000"],
         ["retryAfterMs('soon', 0)","null"],
         ["retryAfterMs('', 0)","null"]],
  edge:[["retryAfterMs('0', 0)","0"],
        ["retryAfterMs('Wed, 21 Oct 2015 07:28:00 GMT', Date.parse('Wed, 21 Oct 2015 07:28:00 GMT') + 1000)","0"]],
  ex:"🐛 원인: 한 헤더가 <b>두 가지 형식</b>을 갖는데 한쪽만 다뤘습니다. <code>Number('Wed, 21 …')</code> 는 <code>NaN</code> 이고, <code>NaN</code> 은 비교에서 언제나 거짓이라 '대기 없음' 처럼 흘러가 <b>즉시 재시도 폭주</b>가 됩니다. <code>Number('')</code> 가 0 인 것도 함정입니다.\n🔧 해결: 숫자 모양인지 먼저 보고, 아니면 날짜로 해석합니다. 과거 시각이면 0 으로 깎아 음수 대기가 나오지 않게 합니다.\n🛡 재발 방지: <code>Number()</code> 는 빈 문자열·공백·<code>null</code> 을 전부 0 으로 만듭니다. 바깥에서 온 값에는 <b>모양 검사를 먼저</b> 하고 변환하세요. 그리고 상대가 준 대기 시간을 그대로 믿기보다 <b>상한</b>을 씌우는 편이 안전합니다 — 악의적이거나 잘못된 서버가 하루를 기다리게 만들 수 있습니다." },

{ track:"net", cat:"debug", k:"질의 문자열에서 + 는 빈칸이다",
  q:"질의 문자열의 값 하나를 디코딩하는 함수입니다. 잘못된 퍼센트 열이면 <code>null</code> 입니다. 검색어 <code>a+b</code> 가 <b>그대로 <code>a+b</code></b> 로 들어와 검색이 되지 않습니다.",
  src:"function decodeQuery(s) {\n  return decodeURIComponent(s);\n}",
  sol:"function decodeQuery(s) {\n  try {\n    return decodeURIComponent(String(s).replace(/\\+/g, ' '));\n  } catch (e) {\n    return null;\n  }\n}",
  tests:[["decodeQuery('a+b')","'a b'"],
         ["decodeQuery('a%20b')","'a b'"],
         ["decodeQuery('%ED%95%9C')","'한'"],
         ["decodeQuery('%zz')","null"]],
  edge:[["decodeQuery('')","''"],
        ["decodeQuery('1%2B1')","'1+1'"]],
  ex:"🐛 원인: <code>decodeURIComponent</code> 는 URI 규약만 압니다. 질의 문자열의 <code>+</code> 를 빈칸으로 읽는 것은 <b>HTML 폼 인코딩</b>(<code>application/x-www-form-urlencoded</code>)의 규칙이라 따로 처리해야 합니다. 게다가 <code>%zz</code> 같은 값이 오면 <b>예외를 던져</b> 요청 전체가 500 이 됩니다.\n🔧 해결: <code>+</code> 를 빈칸으로 먼저 바꾸고 디코딩하며, 예외는 <code>null</code> 로 바꿔 호출자가 400 을 돌려줄 수 있게 합니다. 순서가 중요합니다 — 디코딩 후에 <code>+</code> 를 바꾸면 <code>%2B</code> 로 보낸 진짜 <code>+</code> 까지 빈칸이 됩니다.\n🛡 재발 방지: <code>URLSearchParams</code> 는 이 규칙을 이미 지킵니다. 직접 다룰 때는 '<b>경로</b>의 + 는 그냥 +, <b>질의</b>의 + 는 빈칸' 이라는 차이를 기억하세요. 바깥 입력을 다루는 함수가 <b>예외를 던질 수 있는지</b>도 계약의 일부입니다." },

{ track:"net", cat:"debug", k:"쿠키 도메인 검사가 점 경계를 안 본다",
  q:"쿠키의 <code>Domain</code> 속성으로 이 호스트에 보내도 되는지 보는 함수입니다. <code>example.com</code> 쿠키는 <code>example.com</code> 과 그 하위 도메인에만 보내야 합니다. 그런데 <b>남의 도메인</b>에도 쿠키가 나갑니다.",
  src:"function cookieDomainOk(cookieDomain, host) {\n  return host === cookieDomain || host.endsWith(cookieDomain);\n}",
  sol:"function cookieDomainOk(cookieDomain, host) {\n  return host === cookieDomain || host.endsWith('.' + cookieDomain);\n}",
  tests:[["cookieDomainOk('example.com', 'example.com')","true"],
         ["cookieDomainOk('example.com', 'a.example.com')","true"],
         ["cookieDomainOk('example.com', 'notexample.com')","false"],
         ["cookieDomainOk('a.example.com', 'example.com')","false"]],
  edge:[["cookieDomainOk('example.com', '')","false"],
        ["cookieDomainOk('example.com', 'x.y.example.com')","true"]],
  ex:"🐛 원인: 문자열 끝만 견주면 <code>notexample.com</code> 도 <code>example.com</code> 으로 끝납니다. 도메인은 <b>점으로 끊긴 라벨의 계층</b>이므로, 접미사 검사에는 반드시 <b>점 경계</b>가 있어야 합니다. 이 한 글자가 세션 쿠키를 남의 서버로 보내는 구멍이 됩니다.\n🔧 해결: 정확히 같거나 <code>'.' + 도메인</code> 으로 끝날 때만 참입니다. 같은 함정이 오리진 검사(<code>origin.endsWith('mysite.com')</code>)와 리다이렉트 화이트리스트에도 그대로 있습니다.\n🛡 재발 방지: 접미사·접두사 검사를 쓸 때마다 <b>경계 문자</b>가 필요한지 물으세요. 그리고 실제 브라우저는 여기에 <b>공개 접미사 목록</b>(<code>.com</code>·<code>.co.kr</code> 같은 곳에는 쿠키를 걸 수 없다)까지 더해 검사합니다 — 직접 구현하기보다 라이브러리를 쓰는 편이 안전한 영역입니다." },

{ track:"net", cat:"debug", k:"혼잡 윈도는 임계점에서 성장 방식이 바뀐다",
  q:"TCP 혼잡 윈도를 갱신하는 함수입니다(단위는 MSS). <code>cwnd &lt; ssthresh</code> 면 <b>느린 시작</b>이라 받은 만큼 더하고, 그 이상이면 <b>혼잡 회피</b>라 <code>floor(acked / cwnd)</code> 만큼만 더합니다. 지금은 윈도가 <b>끝없이 두 배로</b> 늘어 곧 손실이 납니다.",
  src:"function cwndNext(cwnd, ssthresh, acked) {\n  return cwnd + acked;\n}",
  sol:"function cwndNext(cwnd, ssthresh, acked) {\n  return cwnd < ssthresh ? cwnd + acked : cwnd + Math.floor(acked / cwnd);\n}",
  tests:[["cwndNext(4, 16, 4)","8"],
         ["cwndNext(16, 16, 4)","16"],
         ["cwndNext(20, 16, 20)","21"],
         ["cwndNext(1, 2, 1)","2"]],
  edge:[["cwndNext(10, 10, 0)","10"],
        ["cwndNext(100, 16, 50)","100"]],
  ex:"🐛 원인: 느린 시작만 구현했습니다. 이름과 달리 느린 시작은 <b>가장 빠른</b> 국면이라(왕복마다 두 배) 임계점을 넘어서도 계속 두 배로 늘리면 반드시 손실을 만들고, 손실 → 임계점 하향 → 다시 폭주의 톱니가 됩니다.\n🔧 해결: <code>ssthresh</code> 를 기준으로 두 국면을 가릅니다. 혼잡 회피에서는 <b>왕복당 1 MSS</b> 만 늘어나도록 <code>acked / cwnd</code> 로 나눠 더합니다 — 윈도가 클수록 천천히 늘어나는 것이 핵심입니다.\n🛡 재발 방지: '지수로 늘리다 어느 지점부터 선형으로' 는 혼잡 제어뿐 아니라 재시도·자동 확장에도 같은 꼴로 나옵니다. 국면이 바뀌는 코드는 <b>경계값 그 자체</b>(<code>cwnd === ssthresh</code>)를 테스트에 꼭 넣으세요 — 부등호 방향 하나로 동작이 갈립니다." },

{ track:"net", cat:"debug", k:"청크 길이는 16진수다",
  q:"청크 전송 인코딩 본문의 전체 길이를 세는 함수입니다. 작은 응답은 맞는데, <b>10바이트가 넘는 청크</b>가 있으면 길이가 0 이나 엉뚱한 값이 나옵니다.",
  src:"function chunkedSize(body) {\n  let i = 0, total = 0;\n  for (;;) {\n    const nl = body.indexOf('\\r\\n', i);\n    if (nl < 0) return total;\n    const n = Number(body.slice(i, nl).split(';')[0]);\n    if (!n) return total;\n    total += n;\n    i = nl + 2 + n + 2;\n  }\n}",
  sol:"function chunkedSize(body) {\n  let i = 0, total = 0;\n  for (;;) {\n    const nl = body.indexOf('\\r\\n', i);\n    if (nl < 0) return total;\n    const n = parseInt(body.slice(i, nl).split(';')[0], 16);\n    if (!n) return total;\n    total += n;\n    i = nl + 2 + n + 2;\n  }\n}",
  tests:[["chunkedSize('4\\r\\nWiki\\r\\n5\\r\\npedia\\r\\n0\\r\\n\\r\\n')","9"],
         ["chunkedSize('a\\r\\n0123456789\\r\\n0\\r\\n\\r\\n')","10"],
         ["chunkedSize('0\\r\\n\\r\\n')","0"],
         ["chunkedSize('1\\r\\nx\\r\\n0\\r\\n\\r\\n')","1"]],
  edge:[["chunkedSize('10\\r\\n0123456789abcdef\\r\\n0\\r\\n\\r\\n')","16"],
        ["chunkedSize('')","0"]],
  ex:"🐛 원인: 청크 길이 줄은 <b>16진수</b>입니다(RFC 9112). <code>Number('a')</code> 는 <code>NaN</code> 이고 <code>NaN</code> 은 거짓이라 '마지막 청크' 로 오해해 그 자리에서 멈춥니다. 9바이트 이하 청크만 있는 테스트에서는 10진수와 16진수가 같아 <b>통과해 버립니다</b>.\n🔧 해결: <code>parseInt(…, 16)</code> 으로 진법을 못 박습니다. 길이 줄 뒤에 <code>;</code> 로 확장 정보가 붙을 수 있어 잘라 내는 처리도 함께 필요합니다.\n🛡 재발 방지: '작은 값에서는 두 진법이 같다' 는 것이 이 버그를 오래 숨깁니다. 16진수를 쓰는 자리(청크 길이·색상·유니코드 이스케이프·권한 비트)에서는 <b>a~f 가 들어간 값</b>을 반드시 테스트에 넣으세요. <code>parseInt</code> 는 진법을 생략하면 문자열에 따라 진법을 추측하므로 <b>언제나 두 번째 인자를 적는</b> 습관이 안전합니다." },

{ track:"net", cat:"debug", k:"포트가 비어 있으면 기본 포트다",
  q:"URL 에서 실제 접속 포트를 구하는 함수입니다. 포트가 적혀 있지 않으면 스킴의 <b>기본 포트</b>(http 80 · https 443 · ws 80 · wss 443)를 쓰고, 모르는 스킴이면 <code>null</code> 입니다. 지금은 포트를 안 적은 주소에서 <b>0</b> 이 나와 접속이 실패합니다.",
  src:"function portOf(url) {\n  const u = new URL(url);\n  return Number(u.port);\n}",
  sol:"function portOf(url) {\n  const u = new URL(url);\n  if (u.port) return Number(u.port);\n  const std = { 'http:': 80, 'https:': 443, 'ws:': 80, 'wss:': 443 };\n  return std[u.protocol] === undefined ? null : std[u.protocol];\n}",
  tests:[["portOf('http://a.com/x')","80"],
         ["portOf('https://a.com')","443"],
         ["portOf('http://a.com:8080/')","8080"],
         ["portOf('ftp://a.com/f')","null"]],
  edge:[["portOf('wss://a.com')","443"],
        ["portOf('https://a.com:443/')","443"]],
  ex:"🐛 원인: <code>URL</code> 은 포트를 안 적었거나 <b>기본 포트를 적었을 때</b> <code>port</code> 를 빈 문자열로 정규화합니다. <code>Number('')</code> 는 0 이라 '포트 0' 이라는 없는 값이 만들어집니다. <code>https://a.com:443/</code> 도 같은 자리에 걸린다는 점이 특히 헷갈립니다.\n🔧 해결: 빈 문자열을 먼저 갈라 스킴별 기본 포트를 찾습니다. 모르는 스킴은 0 이 아니라 <code>null</code> 로 '알 수 없음' 을 표현합니다.\n🛡 재발 방지: <code>Number()</code>·<code>parseInt()</code> 는 '없음' 을 0 이나 <code>NaN</code> 으로 뭉갭니다. <b>없음과 0 이 서로 다른 뜻</b>인 자리에서는 변환 전에 존재 여부를 먼저 보세요. 이 구분이 무너지면 타임아웃 0(무한 대기)·재시도 0(안 함)·가중치 0(제외) 같은 사고로 이어집니다." },

];
