/* 기초 알고리즘 디버깅 12 — 교과서 코드를 반쯤만 옮긴 자리를 고친다.
   전부 결정적이고 순수 JS 다. 검증:  node ver_dbgjs.cjs ./dbg_cs.cjs */
module.exports = [

{ track:"cs", cat:"debug", k:"이진 탐색이 첫 자리를 안 준다",
  q:"정렬된 배열에서 <code>t</code> 가 <b>처음 나오는 자리</b>를 찾습니다. 없으면 −1 입니다. 지금은 같은 값이 여러 개일 때 <b>가운데 아무 자리</b>가 나와, 구간을 세는 코드가 어긋납니다.",
  src:"function firstIndex(xs, t) {\n  let lo = 0, hi = xs.length - 1;\n  while (lo <= hi) {\n    const mid = (lo + hi) >> 1;\n    if (xs[mid] === t) return mid;\n    if (xs[mid] < t) lo = mid + 1;\n    else hi = mid - 1;\n  }\n  return -1;\n}",
  sol:"function firstIndex(xs, t) {\n  let lo = 0, hi = xs.length;\n  while (lo < hi) {\n    const mid = (lo + hi) >> 1;\n    if (xs[mid] < t) lo = mid + 1;\n    else hi = mid;\n  }\n  return xs[lo] === t ? lo : -1;\n}",
  tests:[["firstIndex([1,2,2,2,3], 2)","1"],
         ["firstIndex([1,2,3], 3)","2"],
         ["firstIndex([1,2,3], 9)","-1"],
         ["firstIndex([5,5,5,5], 5)","0"]],
  edge:[["firstIndex([], 1)","-1"],
        ["firstIndex([7], 7)","0"]],
  ex:"🐛 원인: '찾으면 바로 반환' 은 <b>아무 자리</b>를 줍니다. 값이 유일하면 정답이라 대부분의 테스트를 통과하지만, 중복이 있으면 어느 자리가 나올지 배열 크기에 따라 달라집니다.\n🔧 해결: 같은 값을 만나도 <b>왼쪽으로 계속 좁히는</b> 하한 탐색으로 바꿉니다. 구간을 반열린 <code>[lo, hi)</code> 로 두고 <code>xs[mid] &lt; t</code> 일 때만 <code>lo</code> 를 올리면, 끝났을 때 <code>lo</code> 가 '<b>t 가 들어갈 첫 자리</b>' 입니다.\n🛡 재발 방지: 이진 탐색은 '찾기' 보다 <b>하한·상한</b> 두 함수로 두는 편이 쓰임새가 넓습니다 — 개수 세기, 구간 질의, 삽입 위치가 전부 그 위에서 나옵니다. 그리고 중복이 있는 입력을 테스트에 반드시 넣으세요." },

{ track:"cs", cat:"debug", k:"구간 병합이 정렬을 건너뛴다",
  q:"겹치거나 맞닿은 구간을 합칩니다. 결과는 <b>시작점 오름차순</b>입니다. 입력 순서는 보장되지 않습니다. 지금은 입력이 섞여 들어오면 합쳐지지 않고 그대로 나옵니다.",
  src:"function mergeSpans(list) {\n  const out = [];\n  for (const [s, e] of list) {\n    const last = out[out.length - 1];\n    if (last && s <= last[1]) last[1] = e;\n    else out.push([s, e]);\n  }\n  return out;\n}",
  sol:"function mergeSpans(list) {\n  const out = [];\n  for (const [s, e] of list.slice().sort((a, b) => a[0] - b[0])) {\n    const last = out[out.length - 1];\n    if (last && s <= last[1]) last[1] = Math.max(last[1], e);\n    else out.push([s, e]);\n  }\n  return out;\n}",
  tests:[["mergeSpans([[1,3],[2,6],[8,10]])","[[1,6],[8,10]]"],
         ["mergeSpans([[8,10],[1,3],[2,6]])","[[1,6],[8,10]]"],
         ["mergeSpans([[1,10],[3,4]])","[[1,10]]"],
         ["mergeSpans([[1,2],[3,4]])","[[1,2],[3,4]]"]],
  edge:[["mergeSpans([])","[]"],
        ["mergeSpans([[1,4],[4,5]])","[[1,5]]"]],
  ex:"🐛 원인: 두 가지가 빠졌습니다. <b>정렬</b>이 없어 뒤에 온 작은 구간이 합쳐지지 않고, 겹칠 때 끝을 <code>e</code> 로 <b>덮어써서</b> 큰 구간 안에 작은 구간이 들어오면 끝이 오히려 줄어듭니다(<code>[1,10]</code> 과 <code>[3,4]</code>).\n🔧 해결: 시작점으로 정렬한 뒤 겹치면 <code>Math.max</code> 로 끝을 늘립니다. <code>slice()</code> 로 복사해 <b>호출자의 배열을 바꾸지 않는</b> 것도 함께 지킵니다.\n🛡 재발 방지: 구간 알고리즘은 거의 언제나 <b>정렬이 전제</b>입니다. 그 전제를 함수 안에서 보장하든 계약으로 요구하든 <b>둘 중 하나는 명시</b>해야 합니다. 테스트에는 '<b>포함 관계</b>' 와 '<b>딱 맞닿은</b>' 두 경우를 반드시 넣으세요 — 이 둘이 구현을 가릅니다." },

{ track:"cs", cat:"debug", k:"회문 검사가 글자를 고르지 않는다",
  q:"문장이 회문인지 봅니다. <b>대소문자를 무시</b>하고 <b>영숫자만</b> 견줍니다. 지금은 빈칸과 문장부호 때문에 대부분 거짓이 나옵니다.",
  src:"function isPalin(s) {\n  const t = String(s);\n  return t === t.split('').reverse().join('');\n}",
  sol:"function isPalin(s) {\n  const t = String(s).toLowerCase().replace(/[^a-z0-9]/g, '');\n  return t === t.split('').reverse().join('');\n}",
  tests:[["isPalin('A man, a plan, a canal: Panama')","true"],
         ["isPalin('race a car')","false"],
         ["isPalin('Aa')","true"],
         ["isPalin('ab')","false"]],
  edge:[["isPalin('')","true"],
        ["isPalin('.,')","true"]],
  ex:"🐛 원인: 계약에 '대소문자 무시' 와 '영숫자만' 이 적혀 있는데 코드는 <b>문자열을 그대로</b> 뒤집어 견줍니다. <code>'aba'</code> 같은 깨끗한 입력만 테스트하면 통과합니다.\n🔧 해결: 견주기 전에 <b>정규화</b>합니다 — 소문자로 바꾸고 영숫자만 남깁니다. 정규화와 비교를 나누면 규칙이 바뀌어도 한 줄만 고치면 됩니다.\n🛡 재발 방지: 문자열 비교는 거의 언제나 '<b>무엇을 같다고 볼 것인가</b>' 를 먼저 정해야 합니다 — 대소문자·공백·유니코드 정규화(NFC/NFD)·악센트. 한국어와 이모지가 섞이면 <code>split('')</code> 이 코드 단위로 쪼개 서러게이트 쌍을 깨뜨리므로 <code>[...s]</code> 를 쓰는 편이 안전합니다." },

{ track:"cs", cat:"debug", k:"최대공약수가 음수를 낸다",
  q:"두 정수의 <b>최대공약수</b>를 구합니다. 결과는 언제나 0 이상입니다. 지금은 음수 입력에서 음수가 나와, 이 값으로 나누는 분수 약분이 뒤집힙니다.",
  src:"function gcd(a, b) {\n  while (b !== 0) {\n    const t = b;\n    b = a % b;\n    a = t;\n  }\n  return a;\n}",
  sol:"function gcd(a, b) {\n  let x = Math.abs(a), y = Math.abs(b);\n  while (y !== 0) {\n    const t = y;\n    y = x % y;\n    x = t;\n  }\n  return x;\n}",
  tests:[["gcd(12, 18)","6"],
         ["gcd(4, -6)","2"],
         ["gcd(-4, -6)","2"],
         ["gcd(7, 13)","1"]],
  edge:[["gcd(0, 5)","5"],
        ["gcd(0, 0)","0"]],
  ex:"🐛 원인: 자바스크립트의 <code>%</code> 는 <b>피제수의 부호</b>를 따릅니다. 음수가 섞이면 중간값이 음수가 되고 결과도 음수로 나옵니다. 양수만 테스트하면 완벽하게 동작합니다.\n🔧 해결: 시작할 때 <b>절댓값</b>을 취합니다. 최대공약수는 정의상 음이 아닌 값이고, <code>gcd(0, 0)</code> 은 0 으로 두는 것이 관례입니다.\n🛡 재발 방지: 수론 함수는 <b>음수·0</b> 입력을 반드시 테스트하세요. 그리고 <code>%</code> 가 나머지이지 모듈로가 아니라는 점은 해시·순환 인덱스·각도 계산에서도 같은 함정으로 나타납니다 — 언제나 0 이상이 필요하면 감싸는 헬퍼를 하나 두세요." },

{ track:"cs", cat:"debug", k:"BFS 거리가 하나 더 세어진다",
  q:"인접 목록 그래프에서 <code>from</code> 에서 <code>to</code> 까지의 <b>간선 수</b>를 셉니다. 못 가면 −1 입니다. 지금 값이 교과서보다 <b>1 큽니다</b>.",
  src:"function bfsDist(adj, from, to) {\n  const seen = new Set([from]);\n  let level = 1, frontier = [from];\n  while (frontier.length) {\n    if (frontier.includes(to)) return level;\n    const next = [];\n    for (const n of frontier) {\n      for (const m of adj[n] || []) {\n        if (!seen.has(m)) { seen.add(m); next.push(m); }\n      }\n    }\n    frontier = next;\n    level += 1;\n  }\n  return -1;\n}",
  sol:"function bfsDist(adj, from, to) {\n  const seen = new Set([from]);\n  let level = 0, frontier = [from];\n  while (frontier.length) {\n    if (frontier.includes(to)) return level;\n    const next = [];\n    for (const n of frontier) {\n      for (const m of adj[n] || []) {\n        if (!seen.has(m)) { seen.add(m); next.push(m); }\n      }\n    }\n    frontier = next;\n    level += 1;\n  }\n  return -1;\n}",
  tests:[["bfsDist({a:['b'], b:['c'], c:[]}, 'a', 'c')","2"],
         ["bfsDist({a:['b'], b:['c'], c:[]}, 'a', 'a')","0"],
         ["bfsDist({a:['b'], b:[], c:[]}, 'a', 'c')","-1"],
         ["bfsDist({a:['b','c'], b:[], c:[]}, 'a', 'b')","1"]],
  edge:[["bfsDist({a:['a']}, 'a', 'a')","0"],
        ["bfsDist({}, 'a', 'a')","0"]],
  ex:"🐛 원인: 시작 노드의 거리는 <b>0</b> 입니다. 레벨을 1 에서 시작하면 모든 답이 1 씩 커지고, '자기 자신까지의 거리' 라는 가장 기본적인 경우부터 틀립니다.\n🔧 해결: <code>level = 0</code> 으로 시작합니다. 노드 수가 아니라 <b>간선 수</b>를 세는 것이라는 계약을 함수 이름과 테스트에 함께 못 박으세요.\n🛡 재발 방지: 거리 계산에서 '<b>자기 자신까지 0</b>' 은 언제나 첫 테스트여야 합니다. 그리고 '몇 개의 노드를 지나는가' 와 '몇 개의 간선을 지나는가' 는 언제나 1 차이라, 두 표현이 문서와 코드에서 섞이면 이 버그가 반복해서 돌아옵니다." },

{ track:"cs", cat:"debug", k:"괄호 검사가 종류를 안 본다",
  q:"<code>()</code>·<code>[]</code>·<code>{}</code> 가 올바르게 짝지어졌는지 봅니다. 지금은 <code>(]</code> 처럼 <b>종류가 어긋난</b> 짝도 통과합니다.",
  src:"function bracketsOk(s) {\n  let depth = 0;\n  for (const c of String(s)) {\n    if ('([{'.includes(c)) depth += 1;\n    else if (')]}'.includes(c)) { depth -= 1; if (depth < 0) return false; }\n  }\n  return depth === 0;\n}",
  sol:"function bracketsOk(s) {\n  const pair = { ')': '(', ']': '[', '}': '{' };\n  const st = [];\n  for (const c of String(s)) {\n    if ('([{'.includes(c)) st.push(c);\n    else if (pair[c]) { if (st.pop() !== pair[c]) return false; }\n  }\n  return st.length === 0;\n}",
  tests:[["bracketsOk('([]{})')","true"],
         ["bracketsOk('(]')","false"],
         ["bracketsOk('([)]')","false"],
         ["bracketsOk('(()')","false"]],
  edge:[["bracketsOk('')","true"],
        ["bracketsOk('a(b)c')","true"]],
  ex:"🐛 원인: 개수만 세면 <b>어떤 괄호가 열렸는지</b>를 모릅니다. <code>([)]</code> 는 깊이가 정확히 맞아떨어져 통과하지만 실제로는 교차한 잘못된 짝입니다. 한 종류만 쓰는 테스트로는 절대 안 잡힙니다.\n🔧 해결: <b>스택</b>에 열린 괄호를 쌓고, 닫을 때 <b>맨 위와 같은 종류인지</b> 봅니다. 이 문제가 스택의 교과서 예제인 이유가 바로 '가장 최근에 열린 것' 을 알아야 하기 때문입니다.\n🛡 재발 방지: 중첩 구조(괄호·태그·블록)를 다룰 때 <b>깊이 카운터로 충분한지</b> 먼저 물으세요 — 종류가 하나뿐이면 충분하고, 둘 이상이면 반드시 스택이 필요합니다. 같은 이유로 HTML 태그 짝 검사도 카운터로는 안 됩니다." },

{ track:"cs", cat:"debug", k:"편집 거리의 첫 줄이 비어 있다",
  q:"두 문자열의 <b>편집 거리</b>(삽입·삭제·교체 각 1)를 구합니다. 한쪽이 빈 문자열이면 다른 쪽의 길이입니다. 지금은 빈 문자열이 섞이면 0 이 나옵니다.",
  src:"function editDistance(a, b) {\n  const n = a.length, m = b.length;\n  const d = Array.from({ length: n + 1 }, () => new Array(m + 1).fill(0));\n  for (let i = 1; i <= n; i += 1) {\n    for (let j = 1; j <= m; j += 1) {\n      const cost = a[i - 1] === b[j - 1] ? 0 : 1;\n      d[i][j] = Math.min(d[i - 1][j] + 1, d[i][j - 1] + 1, d[i - 1][j - 1] + cost);\n    }\n  }\n  return d[n][m];\n}",
  sol:"function editDistance(a, b) {\n  const n = a.length, m = b.length;\n  const d = Array.from({ length: n + 1 }, () => new Array(m + 1).fill(0));\n  for (let i = 0; i <= n; i += 1) d[i][0] = i;\n  for (let j = 0; j <= m; j += 1) d[0][j] = j;\n  for (let i = 1; i <= n; i += 1) {\n    for (let j = 1; j <= m; j += 1) {\n      const cost = a[i - 1] === b[j - 1] ? 0 : 1;\n      d[i][j] = Math.min(d[i - 1][j] + 1, d[i][j - 1] + 1, d[i - 1][j - 1] + cost);\n    }\n  }\n  return d[n][m];\n}",
  tests:[["editDistance('kitten', 'sitting')","3"],
         ["editDistance('', 'abc')","3"],
         ["editDistance('abc', '')","3"],
         ["editDistance('abc', 'abc')","0"]],
  edge:[["editDistance('', '')","0"],
        ["editDistance('a', 'b')","1"]],
  ex:"🐛 원인: DP 표의 <b>첫 행과 첫 열</b>을 초기화하지 않았습니다. <code>d[i][0]</code> 은 '<code>a</code> 의 앞 i 글자를 빈 문자열로 만드는 비용' 이라 <b>i</b> 여야 하는데 0 으로 남아, 삭제·삽입 비용이 통째로 사라집니다. 길이가 같은 문자열끼리는 우연히 맞을 때도 있어 더 헷갈립니다.\n🔧 해결: 표를 채우기 전에 첫 행을 <code>0..m</code>, 첫 열을 <code>0..n</code> 으로 놓습니다. <b>기저 조건이 곧 정답의 절반</b>입니다.\n🛡 재발 방지: DP 버그의 대부분은 점화식이 아니라 <b>기저 조건</b>에 있습니다. 표의 첫 줄이 뜻하는 바를 한 문장으로 적어 보면 초기화 값이 저절로 나옵니다. 그리고 '한쪽이 비었을 때' 를 첫 테스트로 두면 이 실수는 즉시 잡힙니다." },

{ track:"cs", cat:"debug", k:"2진 문자열을 10진수로 읽는다",
  q:"<b>2진수 문자열</b>을 수로 바꿉니다. 지금은 <code>'101'</code> 이 5 가 아니라 101 로 읽혀, 비트 마스크 계산이 통째로 틀립니다.",
  src:"function binToInt(s) {\n  return parseInt(s);\n}",
  sol:"function binToInt(s) {\n  return parseInt(s, 2);\n}",
  tests:[["binToInt('101')","5"],
         ["binToInt('0')","0"],
         ["binToInt('1111')","15"],
         ["binToInt('10000000')","128"]],
  edge:[["binToInt('1')","1"],
        ["binToInt('000101')","5"]],
  ex:"🐛 원인: <code>parseInt</code> 는 <b>진법을 생략하면 10진수</b>로 읽습니다(옛 브라우저는 <code>0x</code>·<code>0</code> 접두사를 보고 추측하기도 했습니다). 2진수 문자열은 숫자로만 이뤄져 있어 오류 없이 그럴듯한 값이 나오고, 그 값으로 마스크를 만들면 아주 먼 곳에서 이상해집니다.\n🔧 해결: <b>언제나 두 번째 인자를 적습니다</b> — <code>parseInt(s, 2)</code>. 반대 방향은 <code>n.toString(2)</code> 입니다.\n🛡 재발 방지: <code>parseInt</code> 를 진법 없이 쓰는 코드는 리뷰에서 바로 지적할 만한 자리입니다. 그리고 <code>['1','2','3'].map(parseInt)</code> 가 <code>[1, NaN, NaN]</code> 이 되는 유명한 함정도 같은 뿌리입니다 — <code>map</code> 이 넘기는 <b>인덱스가 진법 인자로</b> 들어갑니다." },

{ track:"cs", cat:"debug", k:"회전이 배열 길이를 넘는 k 에서 깨진다",
  q:"배열을 오른쪽으로 <code>k</code> 칸 회전합니다. <code>k</code> 는 배열 길이보다 클 수도, <b>음수</b>(왼쪽 회전)일 수도 있습니다. 지금은 그런 <code>k</code> 에서 빈 배열이나 이상한 결과가 나옵니다.",
  src:"function rotate(xs, k) {\n  return xs.slice(-k).concat(xs.slice(0, -k));\n}",
  sol:"function rotate(xs, k) {\n  const n = xs.length;\n  if (n === 0) return [];\n  const s = ((k % n) + n) % n;\n  return xs.slice(n - s).concat(xs.slice(0, n - s));\n}",
  tests:[["rotate([1,2,3,4,5], 2)","[4,5,1,2,3]"],
         ["rotate([1,2,3], 3)","[1,2,3]"],
         ["rotate([1,2,3], 4)","[3,1,2]"],
         ["rotate([1,2,3], -1)","[2,3,1]"]],
  edge:[["rotate([], 3)","[]"],
        ["rotate([1,2,3], 0)","[1,2,3]"]],
  ex:"🐛 원인: <code>slice(-k)</code> 는 <code>k</code> 가 길이 이상이거나 0 이하일 때 뜻이 달라집니다. <code>k = 0</code> 이면 <code>slice(-0)</code> 이 <b>배열 전체</b>가 되고, <code>k = 3</code>(길이 3)이면 <code>slice(0, -3)</code> 이 빈 배열이 됩니다. 작은 <code>k</code> 만 테스트하면 통과합니다.\n🔧 해결: <b>먼저 <code>k</code> 를 길이로 접습니다</b> — <code>((k % n) + n) % n</code> 이면 음수와 큰 값이 한 번에 정리되어, 그 뒤 계산은 언제나 <code>0 ≤ s &lt; n</code> 인 안전한 범위에서 이뤄집니다.\n🛡 재발 방지: 순환하는 인덱스는 <b>쓰기 전에 정규화</b>하세요 — 링 버퍼·원형 큐·요일 계산이 같습니다. 그리고 음수 인덱스를 받는 <code>slice</code> 는 편하지만 경계에서 뜻이 미묘하므로, 계산으로 얻은 값을 넣을 때는 특히 조심해야 합니다." },

{ track:"cs", cat:"debug", k:"중앙값이 원본을 흔들고 짝수를 놓친다",
  q:"수 배열의 <b>중앙값</b>을 구합니다. 개수가 짝수면 <b>가운데 두 값의 평균</b>이고, <b>원본을 바꾸면 안 됩니다</b>. 지금은 짝수 개에서 값이 어긋나고, 같은 배열로 두 번 부르면 결과가 달라집니다.",
  src:"function median(xs) {\n  const s = xs.sort((a, b) => a - b);\n  return s[Math.floor(s.length / 2)];\n}",
  sol:"function median(xs) {\n  if (!xs.length) return null;\n  const s = xs.slice().sort((a, b) => a - b);\n  const mid = Math.floor(s.length / 2);\n  return s.length % 2 ? s[mid] : (s[mid - 1] + s[mid]) / 2;\n}",
  tests:[["median([3,1,2])","2"],
         ["median([4,1,3,2])","2.5"],
         ["(() => { const a = [3,1,2]; median(a); return a; })()","[3,1,2]"],
         ["median([5])","5"]],
  edge:[["median([])","null"],
        ["median([2,2,2,2])","2"]],
  ex:"🐛 원인: 두 가지가 빠졌습니다. <b>짝수 개</b>일 때 가운데 두 값의 평균을 내지 않아 위쪽 값이 그대로 나오고, <code>sort</code> 가 <b>원본을 제자리에서</b> 정렬해 호출자의 배열 순서를 바꿉니다. 홀수 개 예제만 테스트하면 둘 다 안 보입니다.\n🔧 해결: <code>slice()</code> 로 복사한 뒤 정렬하고, 개수의 홀짝을 갈라 처리합니다. 빈 배열의 답이 무엇인지도 계약에 적어야 합니다.\n🛡 재발 방지: 통계량 함수는 <b>빈 입력·짝수 개·모두 같은 값</b> 세 가지를 기본 테스트로 두세요. 그리고 자바스크립트의 기본 <code>sort</code> 는 문자열 비교라 <code>[1,2,10]</code> 이 <code>[1,10,2]</code> 가 되므로, 숫자 배열에는 <b>언제나 비교 함수</b>를 넘겨야 합니다." },

{ track:"cs", cat:"debug", k:"최빈값이 동점을 순서로 푼다",
  q:"가장 많이 나온 값을 돌려줍니다. 동점이면 <b>작은 값</b>을 고릅니다. 지금은 자료가 들어온 순서에 따라 답이 달라져 재현이 되지 않습니다.",
  src:"function modeOf(xs) {\n  const cnt = new Map();\n  for (const x of xs) cnt.set(x, (cnt.get(x) || 0) + 1);\n  let best = null, bestN = -1;\n  for (const [v, n] of cnt) {\n    if (n > bestN) { best = v; bestN = n; }\n  }\n  return best;\n}",
  sol:"function modeOf(xs) {\n  const cnt = new Map();\n  for (const x of xs) cnt.set(x, (cnt.get(x) || 0) + 1);\n  let best = null, bestN = -1;\n  for (const [v, n] of cnt) {\n    if (n > bestN || (n === bestN && v < best)) { best = v; bestN = n; }\n  }\n  return best;\n}",
  tests:[["modeOf([3,1,3,1,2])","1"],
         ["modeOf([1,3,1,3,2])","1"],
         ["modeOf([5,5,5,1])","5"],
         ["modeOf([2])","2"]],
  edge:[["modeOf([])","null"],
        ["modeOf([9,8,7])","7"]],
  ex:"🐛 원인: 동점을 <b>먼저 만난 쪽</b>으로 풀면 답이 입력 순서에 딸려 갑니다. 같은 자료를 다른 순서로 넣으면 다른 답이 나와, 캐시·페이지네이션·테스트가 모두 불안정해집니다.\n🔧 해결: 동점일 때 <b>값 자체에서 결정되는 기준</b>을 하나 더 겁니다. 여기서는 '작은 값' 이고, 그러면 순서와 무관하게 언제나 같은 답이 나옵니다.\n🛡 재발 방지: 최댓값·정렬·순위 매기기에는 언제나 <b>전순서를 정하는 마지막 기준</b>이 필요합니다. 그 기준이 없으면 '대부분 맞지만 가끔 다른' 결과가 나오고, 그런 버그는 재현이 어려워 가장 오래 삽니다." },

{ track:"cs", cat:"debug", k:"거듭제곱을 먼저 다 계산한 뒤 나눈다",
  q:"<code>(base ** exp) % mod</code> 를 구합니다. <code>exp</code> 가 아주 클 수 있습니다. 지금은 지수가 조금만 커져도 <b>0 이나 부정확한 값</b>이 나옵니다.",
  src:"function powMod(base, exp, mod) {\n  return (base ** exp) % mod;\n}",
  sol:"function powMod(base, exp, mod) {\n  let r = 1, b = base % mod, e = exp;\n  while (e > 0) {\n    if (e % 2 === 1) r = (r * b) % mod;\n    b = (b * b) % mod;\n    e = Math.floor(e / 2);\n  }\n  return r;\n}",
  tests:[["powMod(2, 10, 1000)","24"],
         ["powMod(3, 200, 50)","1"],
         ["powMod(7, 0, 13)","1"],
         ["powMod(2, 62, 1000)","904"]],
  edge:[["powMod(5, 3, 1)","0"],
        ["powMod(10, 1, 7)","3"]],
  ex:"🐛 원인: 먼저 다 곱하면 <b>수가 표현 범위를 넘습니다</b>. 자바스크립트 수는 정수를 2⁵³ 까지만 정확히 담으므로, 그 위로는 조용히 반올림된 값이 되고 나머지 연산의 결과도 틀립니다. 오류가 아니라 <b>그럴듯한 숫자</b>가 나오는 것이 가장 나쁩니다.\n🔧 해결: <b>제곱하며 접는</b> 방식으로 곱할 때마다 나머지를 취합니다. 값이 언제나 <code>mod</code> 보다 작게 유지되고, 계산 횟수도 <code>log exp</code> 로 줄어듭니다.\n🛡 재발 방지: '큰 수를 만든 뒤 줄이기' 대신 '<b>작게 유지하며 계산하기</b>' 가 수치 코드의 원칙입니다. 확률의 곱은 로그로, 나머지 연산은 매 단계 접기로 다룹니다. 자바스크립트에서 정말 큰 정수가 필요하면 <code>BigInt</code> 를 쓰되, 성능과 형변환 규칙이 다르다는 점을 함께 고려하세요." },

];
