/* 알고리즘 디버깅 13 — 예제 입력에서는 통과하는 고장난 구현을 받아 고친다.
   계약
     1. src 는 문법 오류가 아니고 TODO 도 없다. 작은 입력에서는 통과하기도 한다.
     2. src 는 tests 중 최소 하나를 실패한다.
     3. sol 은 tests + edge 를 전부 통과한다.
     4. 전부 결정적 — 시각·난수는 쓰지 않는다. 러너 없이 순수 JS 로 돈다.
   검증:  node ver_dbgjs.cjs ./dbg_algo.cjs */
module.exports = [

/* ── 1교시 · 경계와 초기값이 어긋난 곳 ─────────────────────────────── */

{ track:"algo", cat:"debug", k:"같은 값이 여럿이면 첫 자리를 준다",
  q:"정렬된 배열에서 <code>x</code> <b>이상인 첫 자리</b>를 찾는 함수입니다. 없으면 배열 길이를 돌려줍니다. 중복이 없는 입력에서는 잘 맞는데, 같은 값이 여러 개면 <b>가운데 자리</b>가 나옵니다.",
  src:"function lowerBound(a, x) {\n  let lo = 0, hi = a.length;\n  while (lo < hi) {\n    const mid = (lo + hi) >> 1;\n    if (a[mid] === x) return mid;\n    if (a[mid] < x) lo = mid + 1; else hi = mid;\n  }\n  return lo;\n}",
  sol:"function lowerBound(a, x) {\n  let lo = 0, hi = a.length;\n  while (lo < hi) {\n    const mid = (lo + hi) >> 1;\n    if (a[mid] < x) lo = mid + 1; else hi = mid;\n  }\n  return lo;\n}",
  tests:[["lowerBound([1,2,2,2,3], 2)","1"],
         ["lowerBound([1,3,5], 4)","2"],
         ["lowerBound([1,3,5], 0)","0"],
         ["lowerBound([1,3,5], 6)","3"]],
  edge:[["lowerBound([], 1)","0"],
        ["lowerBound([2,2,2], 2)","0"]],
  ex:"원인: <code>a[mid] === x</code> 를 만나자마자 돌려주면 <b>중복 구간 어딘가</b>를 주게 됩니다. 이진 탐색이 주는 자리는 '만난 순서' 에 딸려 가므로, 중복이 있으면 답이 하나로 정해지지 않습니다.\n해결: 값이 같은지 따로 묻지 말고 <code>&lt;</code> 하나로만 나눕니다. <code>a[mid] &lt; x</code> 면 왼쪽 절반을 버리고, 아니면 <code>hi = mid</code> 로 <b>mid 자신을 후보로 남깁니다</b>. 반복이 끝나면 <code>lo</code> 가 곧 첫 자리입니다.\n재발 방지: 이진 탐색은 '찾는다' 가 아니라 '<b>어느 경계를 돌려줄 것인가</b>' 를 먼저 정해야 합니다. 이상인 첫 자리(lower bound)와 초과인 첫 자리(upper bound)를 각각 한 줄 차이로 적어 두고, 테스트에는 반드시 <b>중복이 있는 입력</b>과 <b>범위를 벗어나는 값</b> 두 가지를 넣으세요." },

{ track:"algo", cat:"debug", k:"전부 음수인 구간이 0으로 접힌다",
  q:"연속 부분 배열의 <b>최대 합</b>을 구합니다(빈 배열은 0). 양수가 섞인 입력은 잘 맞는데, <b>전부 음수</b>이면 언제나 0 이 나옵니다.",
  src:"function maxSubArray(a) {\n  let best = 0, cur = 0;\n  for (const v of a) {\n    cur = Math.max(v, cur + v);\n    best = Math.max(best, cur);\n  }\n  return best;\n}",
  sol:"function maxSubArray(a) {\n  if (a.length === 0) return 0;\n  let best = a[0], cur = a[0];\n  for (let i = 1; i < a.length; i += 1) {\n    cur = Math.max(a[i], cur + a[i]);\n    best = Math.max(best, cur);\n  }\n  return best;\n}",
  tests:[["maxSubArray([-2,1,-3,4,-1,2,1,-5,4])","6"],
         ["maxSubArray([-3,-1,-2])","-1"],
         ["maxSubArray([5])","5"],
         ["maxSubArray([-1])","-1"]],
  edge:[["maxSubArray([])","0"],
        ["maxSubArray([0,-1])","0"]],
  ex:"원인: <code>best</code> 를 0 으로 시작한 것은 '<b>아무것도 고르지 않는 선택</b>' 을 후보에 넣은 것과 같습니다. 문제는 '연속 부분 배열' 이므로 적어도 한 칸은 골라야 하는데, 0 이 언제나 이겨 버립니다.\n해결: 초기값을 첫 원소로 두고 나머지를 훑습니다. 빈 배열이라는 별도의 계약은 <b>맨 앞에서 한 번</b> 처리하면 본문이 깨끗해집니다.\n재발 방지: 누적 최댓값·최솟값의 초기값은 0 이나 <code>Infinity</code> 가 아니라 <b>실제 후보 하나</b>여야 합니다. '전부 음수', '길이 1', '빈 입력' 이 세 가지는 집계 함수의 고정 테스트로 박아 두세요 — 세 개 모두 예제에서는 절대 나오지 않습니다." },

{ track:"algo", cat:"debug", k:"창의 왼쪽 끝이 뒤로 되감긴다",
  q:"문자가 겹치지 않는 <b>가장 긴 구간</b>의 길이를 셉니다. 마지막으로 본 자리를 기억해 창을 옮기는데, <code>\"abba\"</code> 처럼 <b>이미 지나온 글자가 다시 나오면</b> 답이 실제보다 커집니다.",
  src:"function longestUnique(s) {\n  const last = new Map();\n  let left = 0, best = 0;\n  for (let i = 0; i < s.length; i += 1) {\n    const ch = s[i];\n    if (last.has(ch)) left = last.get(ch) + 1;\n    last.set(ch, i);\n    best = Math.max(best, i - left + 1);\n  }\n  return best;\n}",
  sol:"function longestUnique(s) {\n  const last = new Map();\n  let left = 0, best = 0;\n  for (let i = 0; i < s.length; i += 1) {\n    const ch = s[i];\n    if (last.has(ch)) left = Math.max(left, last.get(ch) + 1);\n    last.set(ch, i);\n    best = Math.max(best, i - left + 1);\n  }\n  return best;\n}",
  tests:[["longestUnique('abba')","2"],
         ["longestUnique('abcabcbb')","3"],
         ["longestUnique('bbbbb')","1"],
         ["longestUnique('pwwkew')","3"]],
  edge:[["longestUnique('')","0"],
        ["longestUnique('aab')","2"]],
  ex:"원인: <code>last</code> 에는 <b>창 밖으로 이미 밀려난 글자</b>의 자리도 남아 있습니다. <code>'abba'</code> 의 마지막 <code>a</code> 를 만나면 0 번 자리를 보고 <code>left</code> 를 1 로 <b>되돌려</b>, 이미 버린 <code>b</code> 를 다시 창에 넣어 버립니다.\n해결: 왼쪽 끝은 <b>절대 되감기지 않는다</b>는 성질을 코드로 못 박습니다 — <code>Math.max(left, ...)</code> 한 번이면 됩니다.\n재발 방지: 투 포인터의 두 지표는 <b>단조롭게만 움직인다</b>는 것이 전체 O(n) 보장의 근거입니다. 되감기는 순간 복잡도 근거와 정답이 동시에 무너지므로, 지표를 대입할 때마다 '이 값이 줄어들 수 있는가' 를 묻고 <code>max</code>·<code>min</code> 으로 막으세요." },

{ track:"algo", cat:"debug", k:"같은 값은 '더 큰 값' 이 아니다",
  q:"각 자리에서 <b>오른쪽에 처음 나오는 더 큰 값</b>을 찾습니다. 없으면 <code>-1</code> 입니다. 서로 다른 값만 있는 입력은 맞는데, <b>같은 값이 이웃하면</b> 자기 자신과 같은 값을 답으로 적습니다.",
  src:"function nextGreater(a) {\n  const res = new Array(a.length).fill(-1);\n  const st = [];\n  for (let i = 0; i < a.length; i += 1) {\n    while (st.length && a[st[st.length - 1]] <= a[i]) res[st.pop()] = a[i];\n    st.push(i);\n  }\n  return res;\n}",
  sol:"function nextGreater(a) {\n  const res = new Array(a.length).fill(-1);\n  const st = [];\n  for (let i = 0; i < a.length; i += 1) {\n    while (st.length && a[st[st.length - 1]] < a[i]) res[st.pop()] = a[i];\n    st.push(i);\n  }\n  return res;\n}",
  tests:[["nextGreater([2,1,2,4,3])","[4,2,4,-1,-1]"],
         ["nextGreater([2,2,3])","[3,3,-1]"],
         ["nextGreater([1,2,3])","[2,3,-1]"],
         ["nextGreater([3,2,1])","[-1,-1,-1]"]],
  edge:[["nextGreater([])","[]"],
        ["nextGreater([5])","[-1]"]],
  ex:"원인: <code>&lt;=</code> 는 '같으면 답이 정해졌다' 고 선언합니다. 그런데 문제가 요구한 것은 <b>더 큰 값</b>이므로, 같은 값을 만난 자리는 아직 답이 없는 상태로 스택에 남아 있어야 합니다. <code>[2,2,3]</code> 에서 앞 <code>2</code> 가 뒤 <code>2</code> 를 답으로 받아 3 을 놓칩니다.\n해결: 비교를 <code>&lt;</code> 로 바꿉니다. 같은 값은 팝하지 않고 <b>스택에 쌓아 둔 채</b> 넘어가므로, 나중에 진짜 큰 값이 오면 둘 다 한꺼번에 처리됩니다.\n재발 방지: 모노토닉 스택에서 <code>&lt;</code> 와 <code>&lt;=</code> 는 '<b>같은 값을 하나로 볼 것인가</b>' 라는 서로 다른 문제를 풉니다. 다음 큰 값이면 <code>&lt;</code>, 다음 크거나 같은 값이면 <code>&lt;=</code> — 문제 문장의 '더', '이상' 을 그대로 부등호로 옮기고 <b>중복이 있는 입력</b>을 테스트에 넣으세요." },

{ track:"algo", cat:"debug", k:"누적합에서 오른쪽 끝이 빠진다",
  q:"배열을 한 번 훑어 <b>누적합</b>을 만들어 두고, 구간 합을 여러 번 묻는 함수를 돌려줍니다. 구간은 <code>i</code>·<code>j</code> 를 <b>모두 포함</b>하고 <code>i &gt; j</code> 면 0 입니다. 그런데 어떤 구간을 물어도 <b>마지막 한 칸이 빠진</b> 값이 나옵니다.",
  src:"function makeRange(a) {\n  const pre = [0];\n  for (const v of a) pre.push(pre[pre.length - 1] + v);\n  return (i, j) => pre[j] - pre[i];\n}",
  sol:"function makeRange(a) {\n  const pre = [0];\n  for (const v of a) pre.push(pre[pre.length - 1] + v);\n  return (i, j) => (i > j ? 0 : pre[j + 1] - pre[i]);\n}",
  tests:[["makeRange([1,2,3,4])(1, 2)","5"],
         ["makeRange([1,2,3,4])(0, 3)","10"],
         ["makeRange([5])(0, 0)","5"],
         ["makeRange([1,2,3])(2, 2)","3"]],
  edge:[["makeRange([])(0, -1)","0"],
        ["makeRange([1,2,3])(1, 1)","2"]],
  ex:"원인: <code>pre[k]</code> 는 '<b>앞에서 k 개의 합</b>' 이지 'k 번 자리까지의 합' 이 아닙니다. 포함 구간 <code>[i, j]</code> 는 앞에서 <code>j+1</code> 개에서 앞에서 <code>i</code> 개를 뺀 값이므로, <code>pre[j] - pre[i]</code> 는 언제나 <b>j 번 자리 한 칸을 놓칩니다</b>.\n해결: <code>pre[j + 1] - pre[i]</code> 로 고치고, 빈 구간(<code>i &gt; j</code>)은 앞에서 잘라 냅니다. 그러면 <code>pre[-1]</code> 같은 <b>범위 밖 접근</b>도 함께 막힙니다.\n재발 방지: 누적합 배열의 길이는 원본보다 <b>하나 길다</b>는 것을 이름이나 주석으로 남기세요. 그리고 '한 칸짜리 구간' 을 첫 테스트로 두면 이 오프바이원은 언제나 첫 실행에서 잡힙니다 — <code>f(k, k)</code> 는 <code>a[k]</code> 와 같아야 합니다." },

{ track:"algo", cat:"debug", k:"창을 벗어난 후보가 덱에 남는다",
  q:"크기 <code>k</code> 짜리 창을 옮기며 <b>각 창의 최댓값</b>을 모읍니다. 창보다 배열이 짧으면 빈 배열입니다. 값이 뒤로 갈수록 커지는 입력은 맞는데, <b>맨 앞의 큰 값</b>이 있으면 그 값이 끝까지 따라옵니다.",
  src:"function windowMax(a, k) {\n  const out = [], dq = [];\n  for (let i = 0; i < a.length; i += 1) {\n    while (dq.length && a[dq[dq.length - 1]] <= a[i]) dq.pop();\n    dq.push(i);\n    if (i >= k - 1) out.push(a[dq[0]]);\n  }\n  return out;\n}",
  sol:"function windowMax(a, k) {\n  const out = [], dq = [];\n  for (let i = 0; i < a.length; i += 1) {\n    while (dq.length && dq[0] <= i - k) dq.shift();\n    while (dq.length && a[dq[dq.length - 1]] <= a[i]) dq.pop();\n    dq.push(i);\n    if (i >= k - 1) out.push(a[dq[0]]);\n  }\n  return out;\n}",
  tests:[["windowMax([9,1,2,3], 2)","[9,2,3]"],
         ["windowMax([5,4,3,2,1], 3)","[5,4,3]"],
         ["windowMax([1,3,-1,-3,5,3,6,7], 3)","[3,3,5,5,6,7]"],
         ["windowMax([4,4,4], 2)","[4,4]"]],
  edge:[["windowMax([1,2], 5)","[]"],
        ["windowMax([7], 1)","[7]"]],
  ex:"원인: 덱은 '<b>아직 최댓값이 될 수 있는 후보</b>' 만 담아야 합니다. 뒤에서 작은 값을 걷어내는 코드는 있는데 <b>앞에서 창을 벗어난 자리를 버리는 코드</b>가 없어서, 맨 앞의 큰 값이 창을 빠져나간 뒤에도 <code>dq[0]</code> 자리를 계속 차지합니다.\n해결: 답을 읽기 전에 <code>dq[0] &lt;= i - k</code> 인 동안 앞에서 버립니다. 순서가 중요합니다 — <b>버리고 → 밀어내고 → 넣고 → 읽는다</b>.\n재발 방지: 덱을 쓰는 슬라이딩 윈도우는 앞·뒤 두 가지 정리를 <b>모두</b> 해야 하고, 하나만 빠뜨려도 뒤로 갈수록 커지는 예제에서는 조용히 통과합니다. '<b>최댓값이 창 앞쪽에 있는</b>' 입력을 반드시 테스트에 넣으세요." },

{ track:"algo", cat:"debug", k:"회의는 일찍 끝나는 순서로 고른다",
  q:"겹치지 않게 고를 수 있는 <b>회의의 최대 개수</b>를 셉니다. 구간은 <code>[시작, 끝]</code> 이고 앞 회의의 끝과 다음 회의의 시작이 같은 것은 <b>괜찮습니다</b>. 짧은 회의가 고르게 흩어진 입력은 맞는데, <b>아주 긴 회의</b>가 하나 섞이면 답이 1 로 줄어듭니다.",
  src:"function maxMeetings(iv) {\n  const s = iv.slice().sort((a, b) => a[0] - b[0]);\n  let end = -Infinity, n = 0;\n  for (const [a, b] of s) {\n    if (a >= end) { n += 1; end = b; }\n  }\n  return n;\n}",
  sol:"function maxMeetings(iv) {\n  const s = iv.slice().sort((a, b) => a[1] - b[1]);\n  let end = -Infinity, n = 0;\n  for (const [a, b] of s) {\n    if (a >= end) { n += 1; end = b; }\n  }\n  return n;\n}",
  tests:[["maxMeetings([[1,10],[2,3],[4,5]])","2"],
         ["maxMeetings([[1,2],[2,3],[3,4]])","3"],
         ["maxMeetings([[1,3],[2,4],[3,5]])","2"],
         ["maxMeetings([[5,6],[1,4],[2,3]])","2"]],
  edge:[["maxMeetings([])","0"],
        ["maxMeetings([[1,1]])","1"]],
  ex:"원인: 정렬 기준이 <b>시작 시각</b>이라 가장 먼저 시작하는 회의를 무조건 집습니다. 그 회의가 <code>[1,10]</code> 처럼 길면 하루를 통째로 잡아먹고, 뒤의 짧은 회의 두 개를 모두 잃습니다. 탐욕 알고리즘이 틀리는 것이 아니라 <b>고르는 기준</b>이 틀렸습니다.\n해결: <b>끝나는 시각</b>이 이른 순서로 정렬합니다. 가장 일찍 끝나는 회의를 집으면 <b>남는 시간이 언제나 최대</b>가 되므로, 교환 논증으로 최적임이 증명됩니다.\n재발 방지: 탐욕은 '무엇을 먼저 고르는가' 가 알고리즘 전부입니다. 기준을 정할 때는 <b>어떤 자원을 아끼려는가</b>를 한 줄로 적어 보세요 — 여기서는 '남은 시간' 입니다. 그리고 '긴 것 하나 + 짧은 것 여럿' 을 반례 테스트로 고정하세요." },

/* ── 2교시 · 아껴 둔 상태를 잘못 되쓴 곳 ───────────────────────────── */

{ track:"algo", cat:"debug", k:"한 번만 담을 물건이 여러 번 담긴다",
  q:"무게 한도 <code>cap</code> 안에서 <b>물건을 하나씩만</b> 골라 값을 최대로 만듭니다(0/1 배낭). 1차원 표로 줄여 놓았는데, 값이 좋은 가벼운 물건이 있으면 답이 <b>실제보다 큽니다</b>.",
  src:"function knap(items, cap) {\n  const dp = new Array(cap + 1).fill(0);\n  for (const [w, v] of items) {\n    for (let c = w; c <= cap; c += 1) dp[c] = Math.max(dp[c], dp[c - w] + v);\n  }\n  return dp[cap];\n}",
  sol:"function knap(items, cap) {\n  const dp = new Array(cap + 1).fill(0);\n  for (const [w, v] of items) {\n    for (let c = cap; c >= w; c -= 1) dp[c] = Math.max(dp[c], dp[c - w] + v);\n  }\n  return dp[cap];\n}",
  tests:[["knap([[3,4],[4,5],[2,3]], 6)","8"],
         ["knap([[1,5]], 3)","5"],
         ["knap([[5,10]], 4)","0"],
         ["knap([[2,3],[3,4]], 5)","7"]],
  edge:[["knap([], 5)","0"],
        ["knap([[2,3]], 0)","0"]],
  ex:"원인: 용량을 <b>작은 쪽부터</b> 훑으면 <code>dp[c - w]</code> 가 <b>같은 물건을 이미 넣은 뒤의 값</b>입니다. 그래서 한 물건이 몇 번이고 다시 담기고, 이는 0/1 배낭이 아니라 <b>무한 배낭</b>을 푼 결과입니다.\n해결: 안쪽 반복을 <code>cap</code> 에서 <code>w</code> 까지 <b>거꾸로</b> 돌립니다. 그러면 <code>dp[c - w]</code> 는 언제나 <b>이번 물건을 아직 안 본 상태</b>의 값이라 한 번만 담깁니다.\n재발 방지: 2차원 표를 1차원으로 접을 때는 '<b>내가 읽는 칸이 이전 줄인가 이번 줄인가</b>' 를 반드시 확인하세요. 방향 하나로 0/1 과 무한이 갈리므로, <code>[[1, 5]]</code> 처럼 <b>물건 하나에 여유 용량</b>인 입력을 테스트로 두면 즉시 드러납니다." },

{ track:"algo", cat:"debug", k:"메모 열쇠가 서로 다른 칸을 뭉갠다",
  q:"<code>m × n</code> 격자에서 오른쪽·아래로만 움직여 오른쪽 끝 아래까지 가는 <b>경로의 수</b>를 셉니다. <code>blocked</code> 에는 <code>\"행-열\"</code> 꼴로 막힌 칸이 들어옵니다. 정사각 격자에서는 맞는데, <b>가로세로가 다르거나</b> 막힌 칸이 있으면 답이 작게 나옵니다.",
  src:"function paths(m, n, blocked) {\n  const memo = new Map();\n  const walk = (r, c) => {\n    if (r >= m || c >= n) return 0;\n    if (blocked.includes(r + '-' + c)) return 0;\n    if (r === m - 1 && c === n - 1) return 1;\n    const key = r + c;\n    if (memo.has(key)) return memo.get(key);\n    const v = walk(r + 1, c) + walk(r, c + 1);\n    memo.set(key, v);\n    return v;\n  };\n  return walk(0, 0);\n}",
  sol:"function paths(m, n, blocked) {\n  const memo = new Map();\n  const walk = (r, c) => {\n    if (r >= m || c >= n) return 0;\n    if (blocked.includes(r + '-' + c)) return 0;\n    if (r === m - 1 && c === n - 1) return 1;\n    const key = r + '-' + c;\n    if (memo.has(key)) return memo.get(key);\n    const v = walk(r + 1, c) + walk(r, c + 1);\n    memo.set(key, v);\n    return v;\n  };\n  return walk(0, 0);\n}",
  tests:[["paths(2, 4, [])","4"],
         ["paths(3, 3, ['0-1'])","3"],
         ["paths(3, 3, [])","6"],
         ["paths(1, 1, [])","1"]],
  edge:[["paths(2, 2, ['1-1'])","0"],
        ["paths(1, 3, [])","1"]],
  ex:"원인: <code>r + c</code> 는 <b>숫자 덧셈</b>이라 <code>(0,1)</code> 과 <code>(1,0)</code> 이 같은 열쇠 <code>1</code> 을 씁니다. 대각선으로 마주 보는 칸들이 하나로 뭉개져, 먼저 계산된 칸의 답이 <b>다른 칸의 답으로 그대로 재활용</b>됩니다. 정사각 격자에서는 두 값이 우연히 같아 통과합니다.\n해결: 열쇠를 <code>r + '-' + c</code> 처럼 <b>두 값을 구분할 수 있는 문자열</b>로 만듭니다. 이미 <code>blocked</code> 가 같은 규칙을 쓰고 있으니 형식도 맞춰집니다.\n재발 방지: 메모이제이션의 열쇠는 '<b>상태를 유일하게 결정하는 값 전부</b>' 여야 합니다. 두 값을 이어 붙일 때는 구분자를 넣고(<code>1-23</code> 과 <code>12-3</code> 이 갈리도록), 대칭인 입력만으로 테스트하지 마세요 — 열쇠 충돌은 <b>비대칭 입력에서만</b> 드러납니다." },

{ track:"algo", cat:"debug", k:"루트가 아닌 노드에 부모를 붙인다",
  q:"노드 <code>0..n-1</code> 과 간선 목록을 받아 <b>연결 요소의 개수</b>를 셉니다. 간선이 서로 겹치지 않으면 맞는데, <b>한 노드에 여러 간선</b>이 붙으면 개수가 많게 나옵니다.",
  src:"function components(n, edges) {\n  const p = Array.from({ length: n }, (_, i) => i);\n  const find = x => (p[x] === x ? x : (p[x] = find(p[x])));\n  for (const [a, b] of edges) p[a] = find(b);\n  let c = 0;\n  for (let i = 0; i < n; i += 1) if (find(i) === i) c += 1;\n  return c;\n}",
  sol:"function components(n, edges) {\n  const p = Array.from({ length: n }, (_, i) => i);\n  const find = x => (p[x] === x ? x : (p[x] = find(p[x])));\n  for (const [a, b] of edges) {\n    const ra = find(a), rb = find(b);\n    if (ra !== rb) p[ra] = rb;\n  }\n  let c = 0;\n  for (let i = 0; i < n; i += 1) if (find(i) === i) c += 1;\n  return c;\n}",
  tests:[["components(4, [[0,1],[2,3]])","2"],
         ["components(3, [[0,1],[0,2]])","1"],
         ["components(4, [[0,1],[0,2],[0,3]])","1"],
         ["components(5, [])","5"]],
  edge:[["components(0, [])","0"],
        ["components(2, [[0,0]])","2"]],
  ex:"원인: <code>p[a] = find(b)</code> 는 <b>a 의 부모를 통째로 갈아치웁니다</b>. a 가 이미 어떤 묶음의 중간 노드였다면 그 아래 매달린 노드들이 <b>통째로 떨어져 나가</b> 별개의 묶음으로 남습니다. 한 노드에 간선이 하나뿐이면 우연히 맞습니다.\n해결: 합칠 것은 노드가 아니라 <b>두 묶음의 뿌리</b>입니다. <code>find(a)</code> 와 <code>find(b)</code> 를 먼저 구해 서로 다를 때만 한쪽 뿌리를 다른 뿌리에 붙입니다.\n재발 방지: 유니온-파인드에서 <code>p[...]</code> 에 대입하는 왼쪽 자리는 <b>언제나 find 를 거친 값</b>이어야 합니다. 이 규칙 하나를 코드 리뷰 항목으로 두고, '한 노드에 간선 여러 개' 와 '자기 자신으로 가는 간선' 을 테스트에 고정하세요." },

{ track:"algo", cat:"debug", k:"큐가 아니라 스택으로 퍼진다",
  q:"가중치 없는 그래프에서 <code>start</code> 에서 <code>goal</code> 까지의 <b>최소 이동 횟수</b>를 셉니다. 못 가면 <code>-1</code> 입니다. 길이 하나뿐인 그래프는 맞는데, <b>지름길과 우회로가 갈리면</b> 우회로의 길이가 나옵니다.",
  src:"function hops(adj, start, goal) {\n  const seen = new Set([start]);\n  const q = [[start, 0]];\n  while (q.length) {\n    const [n, d] = q.pop();\n    if (n === goal) return d;\n    for (const m of adj[n] || []) {\n      if (!seen.has(m)) { seen.add(m); q.push([m, d + 1]); }\n    }\n  }\n  return -1;\n}",
  sol:"function hops(adj, start, goal) {\n  const seen = new Set([start]);\n  const q = [[start, 0]];\n  let head = 0;\n  while (head < q.length) {\n    const [n, d] = q[head]; head += 1;\n    if (n === goal) return d;\n    for (const m of adj[n] || []) {\n      if (!seen.has(m)) { seen.add(m); q.push([m, d + 1]); }\n    }\n  }\n  return -1;\n}",
  tests:[["hops({A:['B','X'],X:['Y'],Y:['G'],B:['G'],G:[]}, 'A', 'G')","2"],
         ["hops({A:['B'],B:['C'],C:[]}, 'A', 'C')","2"],
         ["hops({A:['B'],B:[],C:[]}, 'A', 'C')","-1"],
         ["hops({A:[]}, 'A', 'A')","0"]],
  edge:[["hops({}, 'A', 'A')","0"],
        ["hops({A:['B'],B:['A']}, 'A', 'B')","1"]],
  ex:"원인: <code>pop()</code> 은 <b>맨 뒤</b>를 꺼내므로 깊이 우선으로 퍼집니다. 방문 표시를 넣는 시점이 <b>큐에 담을 때</b>라서, 먼 길로 먼저 도달한 노드가 그 거리로 <b>못 박혀 버립니다</b>. 나중에 짧은 길로 와도 이미 본 노드라 갱신되지 않습니다.\n해결: 앞에서 꺼냅니다. <code>shift()</code> 는 매번 배열을 밀어 O(n) 이므로, 읽는 자리를 가리키는 <code>head</code> 를 하나 두고 <b>앞으로만 나아가면</b> 전체가 O(V+E) 로 남습니다.\n재발 방지: BFS 의 최단 거리 보장은 오직 '<b>거리가 짧은 것부터 꺼낸다</b>' 에서 나옵니다. 자료구조를 스택으로 바꾸는 순간 그 근거가 사라지므로, <b>지름길과 우회로가 함께 있는</b> 그래프를 고정 테스트로 두세요 — 사슬 하나짜리 그래프는 둘 다 통과합니다." },

{ track:"algo", cat:"debug", k:"의존성 없는 모듈이 순서에서 사라진다",
  q:"빌드 순서를 정합니다. <code>nodes</code> 전체를 위상 정렬해 돌려주고, <b>순환이 있으면 빈 배열</b>입니다. 진입 차수가 0 인 것은 <code>nodes</code> 에 적힌 순서대로 먼저 담습니다. 그런데 <b>아무 의존성도 없는 모듈</b>을 하나 넣으면 순서가 통째로 빈 배열이 됩니다.",
  src:"function topo(nodes, edges) {\n  const deg = new Map(), adj = new Map();\n  for (const [a, b] of edges) {\n    if (!adj.has(a)) adj.set(a, []);\n    adj.get(a).push(b);\n    deg.set(b, (deg.get(b) || 0) + 1);\n  }\n  const q = [...adj.keys()].filter(x => !deg.get(x));\n  const out = [];\n  while (q.length) {\n    const x = q.shift();\n    out.push(x);\n    for (const m of adj.get(x) || []) {\n      deg.set(m, deg.get(m) - 1);\n      if (deg.get(m) === 0) q.push(m);\n    }\n  }\n  return out.length === nodes.length ? out : [];\n}",
  sol:"function topo(nodes, edges) {\n  const deg = new Map(), adj = new Map();\n  for (const [a, b] of edges) {\n    if (!adj.has(a)) adj.set(a, []);\n    adj.get(a).push(b);\n    deg.set(b, (deg.get(b) || 0) + 1);\n  }\n  const q = nodes.filter(x => !deg.get(x));\n  const out = [];\n  while (q.length) {\n    const x = q.shift();\n    out.push(x);\n    for (const m of adj.get(x) || []) {\n      deg.set(m, deg.get(m) - 1);\n      if (deg.get(m) === 0) q.push(m);\n    }\n  }\n  return out.length === nodes.length ? out : [];\n}",
  tests:[["topo(['a','b','z'], [['a','b']])","['a','z','b']"],
         ["topo(['x'], [])","['x']"],
         ["topo(['a','b','c'], [['a','b'],['b','c']])","['a','b','c']"],
         ["topo(['a','b'], [['a','b'],['b','a']])","[]"]],
  edge:[["topo([], [])","[]"],
        ["topo(['p','q'], [['q','p']])","['q','p']"]],
  ex:"원인: 시작 후보를 <code>adj.keys()</code> 에서 골랐습니다. <code>adj</code> 에는 <b>간선을 내보내는 노드만</b> 들어 있으므로, 아무 의존성도 없는 외톨이 모듈은 후보에도 결과에도 끼지 못합니다. 마지막의 개수 검사가 이를 '순환' 으로 오해해 빈 배열을 돌려줍니다.\n해결: 후보는 <b>전체 노드 목록</b>에서 진입 차수가 0 인 것으로 고릅니다. 정답의 순서가 <code>nodes</code> 순서를 따르는 것도 이때 자연스럽게 보장됩니다.\n재발 방지: 그래프 알고리즘에서 '<b>노드 집합</b>' 과 '<b>간선에 등장한 이름들</b>' 은 다릅니다. 외톨이 노드·싱크 노드·소스 노드 셋을 각각 테스트에 넣고, 개수 검사로 순환을 판단한다면 그 검사가 <b>순환 말고 다른 이유로도 걸리지 않는지</b> 확인하세요." },

{ track:"algo", cat:"debug", k:"동점을 입력 순서로 풀면 답이 흔들린다",
  q:"단어 목록에서 <b>많이 나온 순서로 k 개</b>를 고릅니다. 횟수가 같으면 <b>사전순으로 앞선 단어</b>가 먼저입니다. 횟수가 모두 다르면 맞는데, <b>동점이 생기면</b> 입력에 적힌 순서대로 나옵니다.",
  src:"function topWords(words, k) {\n  const c = new Map();\n  for (const w of words) c.set(w, (c.get(w) || 0) + 1);\n  return [...c.entries()]\n    .sort((a, b) => b[1] - a[1])\n    .slice(0, k)\n    .map(e => e[0]);\n}",
  sol:"function topWords(words, k) {\n  const c = new Map();\n  for (const w of words) c.set(w, (c.get(w) || 0) + 1);\n  return [...c.entries()]\n    .sort((a, b) => b[1] - a[1] || (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0))\n    .slice(0, k)\n    .map(e => e[0]);\n}",
  tests:[["topWords(['b','a','b','a','c'], 2)","['a','b']"],
         ["topWords(['n','m'], 2)","['m','n']"],
         ["topWords(['x','x','y'], 1)","['x']"],
         ["topWords(['m','n'], 2)","['m','n']"]],
  edge:[["topWords([], 3)","[]"],
        ["topWords(['z'], 5)","['z']"]],
  ex:"원인: 비교 함수가 <b>횟수만</b> 봅니다. 횟수가 같은 두 단어에 대해 0 을 돌려주므로 순서가 정해지지 않고, 실제로는 <code>Map</code> 에 <b>처음 들어온 순서</b>가 그대로 남습니다. 같은 데이터를 순서만 바꿔 넣으면 답이 달라지므로 재현도, 검증도 어렵습니다.\n해결: 1순위 비교가 0 일 때 쓰일 <b>2순위 기준</b>을 <code>||</code> 로 이어 붙입니다. 여기서는 사전순이며, 이렇게 하면 어떤 입력 순서에서도 답이 하나로 정해집니다.\n재발 방지: 정렬 기준은 <b>전순서</b>가 되어야 합니다 — 임의의 두 원소에 대해 순서가 반드시 정해져야 한다는 뜻입니다. 비교 함수를 쓸 때마다 '동점이 나올 수 있는가, 나오면 무엇으로 가르는가' 를 묻고, <b>같은 값을 순서만 바꾼 입력</b> 두 벌을 테스트에 두세요." },

];
