/* 자바스크립트 실행형 디버깅 문항.
   앱의 testDoc 하네스는 tests+edge 전부 통과해야 gate 가 열리고,
   추가로 SRC 품질(var 금지 · 28줄 이하 · console.log 금지)을 점수에 반영한다.
   → sol 은 gate 통과 + 품질 100 을 모두 만족해야 한다. */
module.exports = [
{ k:"정규식 g 플래그는 상태를 가진다", fn:"isCode",
  q:"주문 코드가 'AB-1234' 형식인지 검사합니다. 같은 값을 두 번 연속으로 넣으면 두 번째는 false 가 나옵니다.",
  src:"const RE = /^[A-Z]{2}-\\d{4}$/g;\nfunction isCode(s) {\n  return RE.test(s);\n}",
  sol:"const RE = /^[A-Z]{2}-\\d{4}$/;\nfunction isCode(s) {\n  return RE.test(s);\n}",
  tests:[["[isCode('AB-1234'), isCode('AB-1234')]","[true,true]"],["isCode('ZZ-0000')","true"],["isCode('A-1234')","false"],["[isCode('QQ-1111'), isCode('QQ-1111'), isCode('QQ-1111')]","[true,true,true]"]],
  edge:[["isCode('')","false"],["isCode('AB-12345')","false"]],
  ex:"🐛 원인: g 플래그가 붙은 정규식은 lastIndex 를 기억합니다. test 가 성공하면 lastIndex 가 문자열 끝으로 옮겨가고, 다음 호출은 그 위치부터 찾다가 실패한 뒤 lastIndex 를 0 으로 되돌립니다. 그래서 결과가 true/false 로 번갈아 나옵니다.\n🔧 해결: 한 건씩 검사할 때는 g 플래그를 빼면 됩니다.\n🛡 재발 방지: 모듈 최상단에 정규식을 상수로 두는 건 좋은 습관이지만, g 나 y 플래그가 붙으면 그 상수는 '상태를 가진 객체' 가 됩니다. 검증용 정규식에는 g 를 쓰지 마세요." },

{ k:"map(parseInt) 의 두 번째 인자", fn:"toInts",
  q:"문자열 배열을 정수 배열로 바꿉니다. ['1','2','3'] 을 넣으면 [1, NaN, NaN] 이 나옵니다.",
  src:"function toInts(xs) {\n  return xs.map(parseInt);\n}",
  sol:"function toInts(xs) {\n  return xs.map((s) => parseInt(s, 10));\n}",
  tests:[["toInts(['1','2','3'])","[1,2,3]"],["toInts(['10','20'])","[10,20]"],["toInts(['7'])","[7]"],["toInts(['0','1','2','3'])","[0,1,2,3]"]],
  edge:[["toInts([])","[]"],["toInts(['08'])","[8]"]],
  ex:"🐛 원인: map 은 콜백에 (값, 인덱스, 배열) 세 개를 넘깁니다. parseInt 의 두 번째 인자는 진법이므로 parseInt('2', 1) 처럼 호출되어 NaN 이 됩니다.\n🔧 해결: 화살표 함수로 감싸 값만 넘기고 진법 10 을 명시합니다.\n🛡 재발 방지: 인자를 더 받는 함수를 map/forEach 에 그대로 넘기지 마세요. Number 처럼 인자가 하나인 함수만 안전합니다." },

{ k:"Array(n).fill 이 참조를 공유", fn:"buckets",
  q:"n 개의 빈 바구니를 만들어 첫 번째에만 값을 넣습니다. 그런데 모든 바구니에 값이 들어갑니다.",
  src:"function buckets(n, v) {\n  const b = new Array(n).fill([]);\n  b[0].push(v);\n  return b;\n}",
  sol:"function buckets(n, v) {\n  const b = Array.from({ length: n }, () => []);\n  b[0].push(v);\n  return b;\n}",
  tests:[["buckets(3,'x')","[['x'],[],[]]"],["buckets(2,1)","[[1],[]]"],["buckets(1,'a')","[['a']]"],["buckets(4,0)","[[0],[],[],[]]"]],
  edge:[["buckets(3,'x')[2].length","0"],["buckets(2,'y')[1].length","0"]],
  ex:"🐛 원인: fill([]) 은 배열 하나를 만들어 그 참조를 n 칸에 복사합니다. 모든 칸이 같은 배열이라 하나에 push 하면 전부 바뀝니다.\n🔧 해결: Array.from 의 매핑 함수는 칸마다 호출되므로 매번 새 배열이 생깁니다.\n🛡 재발 방지: fill 에 객체·배열을 넘기는 순간 참조 공유입니다. 원시값(0, null, '')일 때만 fill 을 쓰세요." },

{ k:"|| 는 0과 빈 문자열도 갈아치운다", fn:"withDefaults",
  q:"설정에 기본값을 채웁니다. 사용자가 재시도 횟수를 0 으로, 접두사를 빈 문자열로 명시했는데 기본값으로 덮어써집니다.",
  src:"function withDefaults(cfg) {\n  return {\n    retries: cfg.retries || 3,\n    prefix: cfg.prefix || 'log',\n  };\n}",
  sol:"function withDefaults(cfg) {\n  return {\n    retries: cfg.retries ?? 3,\n    prefix: cfg.prefix ?? 'log',\n  };\n}",
  tests:[["withDefaults({retries:0,prefix:''})","{retries:0,prefix:''}"],["withDefaults({})","{retries:3,prefix:'log'}"],["withDefaults({retries:5})","{retries:5,prefix:'log'}"],["withDefaults({prefix:'app'})","{retries:3,prefix:'app'}"]],
  edge:[["withDefaults({retries:0})","{retries:0,prefix:'log'}"],["withDefaults({prefix:null})","{retries:3,prefix:'log'}"]],
  ex:"🐛 원인: || 는 falsy 값 전체를 갈아치웁니다. 0, '', false, NaN 은 '값이 없음' 이 아니라 사용자가 정한 값인데도 기본값으로 대체됩니다.\n🔧 해결: ?? 는 null 과 undefined 일 때만 오른쪽을 씁니다.\n🛡 재발 방지: 기본값에는 ?? 를 쓰세요. || 는 '거짓 같으면' 이고 ?? 는 '없으면' 입니다. 숫자·문자열 설정에서는 이 차이가 곧 버그입니다." },

{ k:"replace 는 첫 번째만 바꾼다", fn:"maskAll",
  q:"본문에 있는 모든 전화번호를 '***' 로 가려야 하는데 첫 번째만 가려집니다.",
  src:"function maskAll(text) {\n  return text.replace('010', '***');\n}",
  sol:"function maskAll(text) {\n  return text.split('010').join('***');\n}",
  tests:[["maskAll('010-1 010-2')","'***-1 ***-2'"],["maskAll('010')","'***'"],["maskAll('a010b010c')","'a***b***c'"],["maskAll('010010')","'******'"]],
  edge:[["maskAll('없음')","'없음'"],["maskAll('')","''"]],
  ex:"🐛 원인: 문자열을 첫 인자로 넘긴 replace 는 처음 하나만 바꿉니다. 전역 치환이 아닙니다.\n🔧 해결: split/join 은 모든 조각을 갈아끼웁니다. replaceAll 이나 g 플래그 정규식도 같은 일을 합니다.\n🛡 재발 방지: '모두 바꾸기' 가 요구사항이면 replace 를 쓰기 전에 멈추세요. 테스트에 '두 번 나오는 입력' 을 반드시 넣습니다." },

{ k:"reduce 초기값 없이 빈 배열", fn:"total",
  q:"금액 합계를 구합니다. 항목이 하나도 없으면 TypeError 로 화면 전체가 깨집니다. 빈 배열이면 0 을 반환하세요.",
  src:"function total(items) {\n  return items.map((i) => i.price).reduce((a, b) => a + b);\n}",
  sol:"function total(items) {\n  return items.reduce((a, i) => a + i.price, 0);\n}",
  tests:[["total([])","0"],["total([{price:100}])","100"],["total([{price:1},{price:2}])","3"],["total([{price:10},{price:20},{price:30}])","60"]],
  edge:[["total([{price:0}])","0"],["total([{price:-5},{price:5}])","0"]],
  ex:"🐛 원인: 초기값 없는 reduce 는 첫 원소를 누산기로 씁니다. 배열이 비면 쓸 원소가 없어 TypeError 를 던집니다.\n🔧 해결: 초기값 0 을 넘기면 빈 배열에서도 안전하고, map 단계도 없앨 수 있습니다.\n🛡 재발 방지: reduce 에는 항상 초기값을 넣으세요. 타입도 함께 고정되어 읽기 쉬워집니다." },

{ k:"toFixed 는 문자열을 돌려준다", fn:"sumRounded",
  q:"두 금액을 소수점 둘째 자리까지 반올림해 더합니다. 3.14 와 2.72 를 넣으면 '3.142.72' 가 나옵니다.",
  src:"function sumRounded(a, b) {\n  return a.toFixed(2) + b.toFixed(2);\n}",
  sol:"function sumRounded(a, b) {\n  return Number(a.toFixed(2)) + Number(b.toFixed(2));\n}",
  tests:[["sumRounded(3.14,2.72)","5.86"],["sumRounded(1,2)","3"],["sumRounded(0.005,0)","0.01"],["sumRounded(1.256,1.244)","2.5"]],
  edge:[["sumRounded(0,0)","0"],["sumRounded(-1.5,1.5)","0"]],
  ex:"🐛 원인: toFixed 는 숫자가 아니라 문자열을 반환합니다. 문자열끼리 + 는 덧셈이 아니라 이어붙이기입니다.\n🔧 해결: Number() 로 다시 숫자로 되돌린 뒤 더합니다.\n🛡 재발 방지: 표시용 포맷팅(toFixed·toLocaleString)은 계산이 끝난 맨 마지막에만 쓰세요. 중간 계산에 끼면 타입이 조용히 바뀝니다." },

{ k:"Math.max 에 배열을 그대로", fn:"peak",
  q:"측정값 중 최댓값을 구합니다. 항상 NaN 이 나옵니다.",
  src:"function peak(xs) {\n  return Math.max(xs);\n}",
  sol:"function peak(xs) {\n  return xs.length ? Math.max(...xs) : 0;\n}",
  tests:[["peak([1,9,3])","9"],["peak([-5,-1])","-1"],["peak([42])","42"],["peak([0,0,7])","7"]],
  edge:[["peak([])","0"],["peak([2,2])","2"]],
  ex:"🐛 원인: Math.max 는 가변 인자를 받습니다. 배열을 통째로 넘기면 숫자로 변환하려다 NaN 이 됩니다. 게다가 인자가 하나도 없으면 -Infinity 를 반환하므로 빈 배열도 따로 막아야 합니다.\n🔧 해결: 스프레드로 펼치고, 빈 배열은 0 을 반환하도록 명시합니다.\n🛡 재발 방지: 아주 큰 배열은 스프레드가 호출 스택 한계에 걸립니다. 수만 개 이상이면 reduce 로 순회하세요." },

{ k:"for...in 은 문자열 키를 준다", fn:"sumIndexed",
  q:"배열의 인덱스를 모두 더합니다. [10,20,30] 을 넣으면 3이 아니라 '0012' 같은 값이 나옵니다.",
  src:"function sumIndexed(xs) {\n  let s = 0;\n  for (const i in xs) {\n    s = s + i;\n  }\n  return s;\n}",
  sol:"function sumIndexed(xs) {\n  let s = 0;\n  for (let i = 0; i < xs.length; i++) {\n    s = s + i;\n  }\n  return s;\n}",
  tests:[["sumIndexed([10,20,30])","3"],["sumIndexed([1,1])","1"],["sumIndexed([5])","0"],["sumIndexed([1,2,3,4])","6"]],
  edge:[["sumIndexed([])","0"],["typeof sumIndexed([1,2])","'number'"]],
  ex:"🐛 원인: for...in 은 '키' 를 돌고 객체의 키는 문자열입니다. 0 + '0' 은 문자열 이어붙이기가 되어 숫자 합계가 아니라 문자열이 만들어집니다.\n🔧 해결: 인덱스가 필요하면 일반 for 문이나 forEach 의 두 번째 인자를 씁니다.\n🛡 재발 방지: 배열에 for...in 은 쓰지 마세요. 순서 보장도 없고 프로토타입 체인의 열거 가능한 속성까지 딸려 옵니다. 값만 필요하면 for...of 입니다." },

{ k:"객체 비교는 참조 비교", fn:"hasPoint",
  q:"좌표 목록에 특정 좌표가 있는지 확인합니다. 분명 같은 값인데 항상 false 입니다.",
  src:"function hasPoint(list, p) {\n  return list.includes(p);\n}",
  sol:"function hasPoint(list, p) {\n  return list.some((q) => q.x === p.x && q.y === p.y);\n}",
  tests:[["hasPoint([{x:1,y:2}],{x:1,y:2})","true"],["hasPoint([{x:1,y:2}],{x:2,y:1})","false"],["hasPoint([{x:0,y:0},{x:3,y:4}],{x:3,y:4})","true"],["hasPoint([],{x:1,y:1})","false"]],
  edge:[["hasPoint([{x:1,y:2}],{x:1,y:3})","false"],["hasPoint([{x:-1,y:-1}],{x:-1,y:-1})","true"]],
  ex:"🐛 원인: includes 는 === 로 비교하고, 객체의 === 는 '같은 객체인가' 입니다. 값이 같아도 다른 객체면 false 입니다.\n🔧 해결: 비교 기준을 명시해 some 으로 찾습니다.\n🛡 재발 방지: 값으로 비교해야 하는 객체가 많다면 키를 문자열로 만들어(`${x},${y}`) Set 이나 Map 에 담는 편이 빠르고 안전합니다." },

{ k:"splice 로 순회 중 삭제", fn:"removeOdd",
  q:"홀수를 모두 빼야 하는데 홀수가 붙어 있으면 일부가 남습니다. 원본은 건드리지 마세요.",
  src:"function removeOdd(xs) {\n  const out = [...xs];\n  out.forEach((v, i) => {\n    if (v % 2 !== 0) out.splice(i, 1);\n  });\n  return out;\n}",
  sol:"function removeOdd(xs) {\n  return xs.filter((v) => v % 2 === 0);\n}",
  tests:[["removeOdd([1,3,2])","[2]"],["removeOdd([1,1,1,2])","[2]"],["removeOdd([2,4])","[2,4]"],["removeOdd([1,2,3,4,5,7])","[2,4]"]],
  edge:[["removeOdd([])","[]"],["removeOdd([1])","[]"]],
  ex:"🐛 원인: forEach 가 도는 동안 splice 로 길이를 줄이면 뒤 원소가 앞으로 당겨져 한 칸씩 건너뜁니다. 홀수가 연달아 있으면 두 번째가 살아남습니다.\n🔧 해결: 지우는 대신 남길 것만 고르는 filter 를 씁니다.\n🛡 재발 방지: 순회 중 배열 길이를 바꾸지 마세요. 꼭 제자리에서 지워야 한다면 뒤에서 앞으로 도세요." },

{ k:"Date 의 월은 0부터", fn:"ymd",
  q:"연·월·일로 'YYYY-MM-DD' 문자열을 만듭니다. 3월을 넣으면 04 가 나옵니다.",
  src:"function ymd(y, m, d) {\n  const dt = new Date(y, m, d);\n  const mm = String(dt.getMonth() + 1).padStart(2, '0');\n  const dd = String(dt.getDate()).padStart(2, '0');\n  return `${dt.getFullYear()}-${mm}-${dd}`;\n}",
  sol:"function ymd(y, m, d) {\n  const dt = new Date(y, m - 1, d);\n  const mm = String(dt.getMonth() + 1).padStart(2, '0');\n  const dd = String(dt.getDate()).padStart(2, '0');\n  return `${dt.getFullYear()}-${mm}-${dd}`;\n}",
  tests:[["ymd(2024,3,5)","'2024-03-05'"],["ymd(2024,1,1)","'2024-01-01'"],["ymd(2024,12,31)","'2024-12-31'"],["ymd(2023,11,9)","'2023-11-09'"]],
  edge:[["ymd(2024,2,29)","'2024-02-29'"],["ymd(2000,10,1)","'2000-10-01'"]],
  ex:"🐛 원인: Date 생성자의 월은 0(1월)부터 11(12월)까지입니다. 사람이 쓰는 3월을 그대로 넘기면 4월이 만들어지고, getMonth()+1 로 다시 읽으니 04 가 나옵니다.\n🔧 해결: 생성할 때 m - 1 로 보정합니다. 읽을 때의 +1 과 짝을 이룹니다.\n🛡 재발 방지: 월은 넣을 때 -1, 뺄 때 +1 이 항상 짝입니다. 한쪽만 있으면 버그입니다. 12월 31일과 2월 29일을 테스트에 꼭 넣으세요." },

{ k:"delete 는 배열에 구멍을 남긴다", fn:"dropAt",
  q:"인덱스 하나를 배열에서 빼야 하는데, 길이가 그대로이고 빈 칸이 남습니다.",
  src:"function dropAt(xs, i) {\n  const out = [...xs];\n  delete out[i];\n  return out;\n}",
  sol:"function dropAt(xs, i) {\n  return xs.filter((_, k) => k !== i);\n}",
  tests:[["dropAt([1,2,3],1)","[1,3]"],["dropAt(['a','b'],0)","['b']"],["dropAt([1,2,3],2)","[1,2]"],["dropAt([9],0)","[]"]],
  edge:[["dropAt([1,2],5)","[1,2]"],["dropAt([],0)","[]"]],
  ex:"🐛 원인: delete 는 속성을 지울 뿐 배열의 길이를 줄이지 않습니다. 그 자리에 empty 구멍이 남아 length 는 그대로이고 JSON 으로는 null 로 보입니다.\n🔧 해결: filter 로 인덱스가 다른 것만 남기면 길이까지 정상입니다. splice(i, 1) 도 되지만 원본을 바꿉니다.\n🛡 재발 방지: 배열 원소 제거에 delete 를 쓰지 마세요. 희소 배열은 map·forEach 가 구멍을 건너뛰어 이후 로직 전체를 이상하게 만듭니다." },

{ k:"NaN 은 자기 자신과 같지 않다", fn:"countNaN",
  q:"측정 실패(NaN)가 몇 건인지 셉니다. NaN 이 섞여 있는데 항상 0 이 나옵니다.",
  src:"function countNaN(xs) {\n  return xs.filter((v) => v === NaN).length;\n}",
  sol:"function countNaN(xs) {\n  return xs.filter((v) => Number.isNaN(v)).length;\n}",
  tests:[["countNaN([1,NaN,3])","1"],["countNaN([NaN,NaN])","2"],["countNaN([1,2])","0"],["countNaN([0,NaN,NaN,5])","2"]],
  edge:[["countNaN([])","0"],["countNaN(['x',undefined,null])","0"]],
  ex:"🐛 원인: NaN 은 IEEE 754 규정상 자기 자신을 포함해 어떤 값과도 같지 않습니다. v === NaN 은 언제나 false 입니다.\n🔧 해결: Number.isNaN 으로 판정합니다. 전역 isNaN 은 인자를 숫자로 변환해 버려서 'abc' 도 true 가 되므로 쓰지 마세요.\n🛡 재발 방지: indexOf 도 === 기반이라 NaN 을 못 찾습니다. includes 는 SameValueZero 라 찾습니다 — 이 차이를 기억해 두세요." },

{ k:"push 는 배열이 아니라 길이를 반환", fn:"appended",
  q:"원본을 건드리지 않고 값을 덧붙인 새 배열을 돌려줘야 하는데 숫자가 반환됩니다.",
  src:"function appended(xs, v) {\n  const out = [...xs];\n  return out.push(v);\n}",
  sol:"function appended(xs, v) {\n  return [...xs, v];\n}",
  tests:[["appended([1,2],3)","[1,2,3]"],["appended([],'a')","['a']"],["appended(['x'],'y')","['x','y']"],["appended([0],0)","[0,0]"]],
  edge:[["(() => { const a = [1]; appended(a, 2); return a; })()","[1]"],["appended([1,2,3],4).length","4"]],
  ex:"🐛 원인: Array.prototype.push 는 추가 후의 새 길이(숫자)를 반환합니다. 배열이 아닙니다.\n🔧 해결: 스프레드로 새 배열을 만들어 그대로 반환합니다.\n🛡 재발 방지: 제자리 변경 메서드(push·pop·splice·sort·reverse)의 반환값을 이어 쓰지 마세요. 불변으로 다루려면 스프레드나 concat·toSorted 를 쓰세요." },

{ k:"얕은 전개와 중첩 객체", fn:"bumpQty",
  q:"주문의 수량만 1 늘린 새 객체를 반환합니다. 그런데 원본 주문의 수량까지 같이 늘어납니다.",
  src:"function bumpQty(order) {\n  const next = { ...order };\n  next.item.qty = next.item.qty + 1;\n  return next;\n}",
  sol:"function bumpQty(order) {\n  return { ...order, item: { ...order.item, qty: order.item.qty + 1 } };\n}",
  tests:[["bumpQty({id:1,item:{qty:1}}).item.qty","2"],
         ["(() => { const o = {id:1,item:{qty:1}}; bumpQty(o); return o.item.qty; })()","1"],
         ["bumpQty({id:2,item:{qty:0}})","{id:2,item:{qty:1}}"],
         ["(() => { const o = {id:3,item:{qty:5}}; const n = bumpQty(o); return [o.item.qty, n.item.qty]; })()","[5,6]"]],
  edge:[["bumpQty({id:9,item:{qty:-1}}).item.qty","0"],["bumpQty({id:1,item:{qty:1},memo:'x'}).memo","'x'"]],
  ex:"🐛 원인: { ...order } 는 얕은 전개입니다. 최상위 키만 새로 만들고 item 은 원본과 같은 객체를 가리키므로, next.item.qty 를 고치면 원본도 바뀝니다.\n🔧 해결: 바꾸려는 경로의 모든 층을 새로 만듭니다.\n🛡 재발 방지: 불변 갱신은 '건드리는 경로만 새로' 가 원칙입니다. 중첩이 세 층을 넘으면 상태 구조를 평평하게 만드는 것을 먼저 고려하세요." },

{ k:"정렬 비교 함수는 부호를 반환해야 한다", fn:"byName",
  q:"이름으로 오름차순 정렬합니다. 대부분 맞는 것 같은데 결과가 뒤죽박죽입니다.",
  src:"function byName(rows) {\n  return [...rows].sort((a, b) => a.name > b.name);\n}",
  sol:"function byName(rows) {\n  return [...rows].sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));\n}",
  tests:[["byName([{name:'c'},{name:'a'},{name:'b'}]).map((r) => r.name)","['a','b','c']"],
         ["byName([{name:'z'},{name:'y'}]).map((r) => r.name)","['y','z']"],
         ["byName([{name:'b'},{name:'a'},{name:'d'},{name:'c'}]).map((r) => r.name)","['a','b','c','d']"],
         ["byName([{name:'a'}]).map((r) => r.name)","['a']"]],
  edge:[["byName([]).length","0"],["byName([{name:'a'},{name:'a'}]).length","2"]],
  ex:"🐛 원인: 비교 함수는 음수·0·양수를 반환해야 합니다. true/false 를 주면 true 는 1, false 는 0 으로 변환되어 '작다' 를 표현할 방법이 사라집니다. 원소가 적으면 우연히 맞는 것처럼 보입니다.\n🔧 해결: 세 갈래로 -1/0/1 을 반환합니다. 문자열이면 a.name.localeCompare(b.name) 이 더 간결하고 한글 정렬도 맞습니다.\n🛡 재발 방지: 비교 함수를 쓸 때는 원소를 4개 이상 넣어 테스트하세요. 2~3개로는 잘못된 비교 함수도 통과합니다." },

{ k:"find 는 못 찾으면 undefined", fn:"nameOf",
  q:"id 로 사용자 이름을 찾습니다. 없는 id 를 넣으면 TypeError 로 죽습니다. 없으면 '알 수 없음' 을 반환하세요.",
  src:"function nameOf(users, id) {\n  return users.find((u) => u.id === id).name;\n}",
  sol:"function nameOf(users, id) {\n  return users.find((u) => u.id === id)?.name ?? '알 수 없음';\n}",
  tests:[["nameOf([{id:1,name:'kim'}],1)","'kim'"],["nameOf([{id:1,name:'kim'}],9)","'알 수 없음'"],["nameOf([],1)","'알 수 없음'"],["nameOf([{id:1,name:'a'},{id:2,name:'b'}],2)","'b'"]],
  edge:[["nameOf([{id:0,name:'zero'}],0)","'zero'"],["nameOf([{id:1}],1)","'알 수 없음'"]],
  ex:"🐛 원인: find 는 조건에 맞는 게 없으면 undefined 를 반환합니다. 거기에 .name 을 붙이면 TypeError 입니다.\n🔧 해결: 옵셔널 체이닝 ?. 으로 안전하게 접근하고 ?? 로 기본값을 줍니다.\n🛡 재발 방지: find·match·querySelector 처럼 '없을 수 있는' API 의 반환값에는 바로 점을 찍지 마세요. 없을 때의 동작을 먼저 정합니다." },

{ k:"문자열 덧셈으로 바뀌는 합계", fn:"sumInputs",
  q:"입력 폼에서 온 값(문자열)들을 더합니다. ['1','2'] 를 넣으면 12 가 나옵니다.",
  src:"function sumInputs(vals) {\n  return vals.reduce((a, b) => a + b, 0);\n}",
  sol:"function sumInputs(vals) {\n  return vals.reduce((a, b) => a + Number(b), 0);\n}",
  tests:[["sumInputs(['1','2'])","3"],["sumInputs(['10','20','30'])","60"],["sumInputs(['5'])","5"],["sumInputs(['1','2','3','4'])","10"]],
  edge:[["sumInputs([])","0"],["sumInputs(['0','0'])","0"]],
  ex:"🐛 원인: + 는 한쪽이 문자열이면 이어붙이기가 됩니다. 초기값 0 에 '1' 을 더하면 '01' 이 되고 그 뒤로 계속 문자열입니다.\n🔧 해결: 더하기 전에 Number 로 변환합니다.\n🛡 재발 방지: DOM·JSON·CSV 에서 온 값은 전부 문자열입니다. 경계에서 한 번에 숫자로 바꾸고, 그 뒤로는 숫자만 흐르게 하세요." },

{ k:"클로저 카운터가 매번 초기화", fn:"makeCounter",
  q:"호출할 때마다 1씩 증가하는 카운터를 만드는 함수인데, 항상 1만 반환합니다.",
  src:"function makeCounter() {\n  return function () {\n    let n = 0;\n    n = n + 1;\n    return n;\n  };\n}",
  sol:"function makeCounter() {\n  let n = 0;\n  return function () {\n    n = n + 1;\n    return n;\n  };\n}",
  tests:[["(() => { const c = makeCounter(); return [c(), c(), c()]; })()","[1,2,3]"],
         ["(() => { const c = makeCounter(); c(); return c(); })()","2"],
         ["(() => { const a = makeCounter(); const b = makeCounter(); a(); return b(); })()","1"],
         ["(() => { const c = makeCounter(); return [c(), c()]; })()","[1,2]"]],
  edge:[["typeof makeCounter()","'function'"],["makeCounter()()","1"]],
  ex:"🐛 원인: 상태 변수 n 이 반환되는 함수 '안' 에 있어 호출할 때마다 새로 만들어집니다. 클로저가 기억할 게 없습니다.\n🔧 해결: n 을 바깥 스코프로 옮기면 반환된 함수가 그 변수를 계속 붙잡습니다.\n🛡 재발 방지: 클로저의 핵심은 '어느 스코프에 선언했는가' 입니다. 유지되어야 할 상태는 반환되는 함수보다 바깥에 두세요. 카운터를 두 개 만들면 서로 독립인지도 확인합니다." },

{ k:"음수 나머지", fn:"wrapIndex",
  q:"인덱스를 길이 안으로 순환시킵니다. -1 을 넣으면 마지막 인덱스가 나와야 하는데 음수가 그대로 나옵니다.",
  src:"function wrapIndex(i, len) {\n  return i % len;\n}",
  sol:"function wrapIndex(i, len) {\n  return ((i % len) + len) % len;\n}",
  tests:[["wrapIndex(-1,5)","4"],["wrapIndex(0,5)","0"],["wrapIndex(7,5)","2"],["wrapIndex(-7,5)","3"]],
  edge:[["wrapIndex(5,5)","0"],["wrapIndex(-5,5)","0"]],
  ex:"🐛 원인: 자바스크립트의 % 는 '나머지' 이지 '모듈로' 가 아닙니다. 피제수의 부호를 따라가므로 -1 % 5 는 -1 입니다.\n🔧 해결: len 을 한 번 더해 양수로 만든 뒤 다시 나머지를 취합니다.\n🛡 재발 방지: 캐러셀·원형 버퍼·시계 계산처럼 순환하는 인덱스는 음수 입력을 반드시 테스트하세요. 파이썬의 % 는 반대로 제수의 부호를 따르므로 언어를 오갈 때도 주의합니다." },

{ k:"getter 안에서 자기 자신 호출", fn:"parseSafe",
  q:"JSON 문자열을 파싱하되 깨진 입력이면 null 을 반환해야 합니다. 지금은 깨진 입력에서 예외가 그대로 올라옵니다.",
  src:"function parseSafe(s) {\n  if (!s) return null;\n  return JSON.parse(s);\n}",
  sol:"function parseSafe(s) {\n  try {\n    return JSON.parse(s);\n  } catch {\n    return null;\n  }\n}",
  tests:[["parseSafe('{\"a\":1}')","{a:1}"],["parseSafe('깨짐')","null"],["parseSafe('[1,2]')","[1,2]"],["parseSafe('{a:1}')","null"]],
  edge:[["parseSafe('')","null"],["parseSafe('null')","null"]],
  ex:"🐛 원인: 빈 문자열만 걸러도 '깨짐' 같은 값은 그대로 JSON.parse 로 들어가 SyntaxError 를 던집니다. 입력 검증과 예외 처리는 다른 일입니다.\n🔧 해결: try/catch 로 감싸 파싱 실패를 값으로 바꿉니다.\n🛡 재발 방지: 외부에서 온 문자열(응답 본문·로컬스토리지·쿼리스트링)은 언제든 깨져 있을 수 있습니다. 파싱은 예외를 던지는 지점이라고 보고 항상 감싸세요." },

{ k:"조기 반환이 루프를 끊는다", fn:"allPositive",
  q:"모든 값이 양수인지 확인합니다. 첫 원소만 보고 판단해 버립니다.",
  src:"function allPositive(xs) {\n  for (const v of xs) {\n    if (v > 0) return true;\n    return false;\n  }\n  return true;\n}",
  sol:"function allPositive(xs) {\n  for (const v of xs) {\n    if (v <= 0) return false;\n  }\n  return true;\n}",
  tests:[["allPositive([1,2,-3])","false"],["allPositive([1,2,3])","true"],["allPositive([-1,2])","false"],["allPositive([5,0])","false"]],
  edge:[["allPositive([])","true"],["allPositive([1])","true"]],
  ex:"🐛 원인: 루프 첫 바퀴에서 무조건 return 이 실행됩니다. '하나라도 조건을 어기면 실패' 인데 '첫 원소가 조건을 만족하면 성공' 으로 뒤집혀 있습니다.\n🔧 해결: 루프 안에서는 반증만 찾아 false 를 반환하고, 끝까지 살아남으면 true 를 반환합니다.\n🛡 재발 방지: '모두 ~인가' 는 반례를 찾는 루프, '하나라도 ~인가' 는 사례를 찾는 루프입니다. every/some 을 쓰면 이 구조가 이름으로 드러납니다." },

{ k:"typeof null 은 object", fn:"isObject",
  q:"값이 순수 객체인지 판정합니다. null 을 넣으면 true 가 나옵니다.",
  src:"function isObject(v) {\n  return typeof v === 'object';\n}",
  sol:"function isObject(v) {\n  return typeof v === 'object' && v !== null && !Array.isArray(v);\n}",
  tests:[["isObject(null)","false"],["isObject({})","true"],["isObject([])","false"],["isObject({a:1})","true"]],
  edge:[["isObject(undefined)","false"],["isObject('x')","false"]],
  ex:"🐛 원인: typeof null 은 'object' 입니다. 자바스크립트 초기 구현의 버그가 호환성 때문에 고정된 것입니다. 배열도 typeof 로는 'object' 라 함께 걸립니다.\n🔧 해결: null 검사와 Array.isArray 를 함께 씁니다.\n🛡 재발 방지: typeof 하나로 타입을 판정하지 마세요. null·배열·Date 는 모두 'object' 입니다. 엄밀히 구분해야 하면 Object.prototype.toString.call(v) 를 쓰세요." },
];
