/* SQL 실행형 디버깅 문항 (sql.js / SQLite).
   앱의 __sqlGrade 는 사용자 쿼리와 sol 을 같은 스키마에서 각각 돌려 행을 비교한다.
   ordered:true 면 순서까지, 아니면 정렬 후 비교.
   → src 는 sol 과 '다른 결과' 를 내야 하고(그래야 고칠 게 있다), sol 은 문제 설명과 맞아야 한다. */
module.exports = [
{ k:"LEFT JOIN 을 WHERE 가 INNER JOIN 으로 되돌린다", ordered:true,
  q:"모든 부서를 나열하되 각 부서의 2024년 지출 합계를 함께 보여줘야 합니다. 지출이 한 건도 없는 부서도 0 으로 나와야 하는데 아예 사라집니다. dept, spent 두 컬럼을 dept 오름차순으로 출력하세요.",
  schema:"CREATE TABLE depts (id INTEGER, dept TEXT);\nINSERT INTO depts VALUES (1,'개발'),(2,'디자인'),(3,'법무');\nCREATE TABLE spend (dept_id INTEGER, yr INTEGER, amount INTEGER);\nINSERT INTO spend VALUES (1,2024,100),(1,2024,200),(2,2023,500),(2,2024,50);",
  src:"SELECT d.dept, COALESCE(SUM(s.amount),0) AS spent\nFROM depts d\nLEFT JOIN spend s ON s.dept_id = d.id\nWHERE s.yr = 2024\nGROUP BY d.dept\nORDER BY d.dept;",
  sol:"SELECT d.dept, COALESCE(SUM(s.amount),0) AS spent\nFROM depts d\nLEFT JOIN spend s ON s.dept_id = d.id AND s.yr = 2024\nGROUP BY d.dept\nORDER BY d.dept;",
  ex:"🐛 원인: LEFT JOIN 이 오른쪽에 짝이 없는 행을 NULL 로 채워 살려 놓아도, WHERE s.yr = 2024 가 그 NULL 행을 다시 걸러냅니다. 결과적으로 INNER JOIN 과 같아져 법무(지출 없음)와 디자인(2024 건은 있으나 2023 건만 매칭됐다면)까지 사라집니다.\n🔧 해결: 오른쪽 테이블에 대한 조건은 ON 절로 옮깁니다. 그러면 조인 단계에서 걸러지고 짝 없는 왼쪽 행은 NULL 로 남습니다.\n🛡 재발 방지: LEFT JOIN 을 쓴 뒤 WHERE 에 오른쪽 테이블 컬럼이 등장하면 거의 항상 버그입니다. 'NULL 을 남기고 싶은가' 를 기준으로 ON 과 WHERE 를 나누세요." },

{ k:"NOT IN 과 NULL", ordered:true,
  q:"한 번도 주문하지 않은 고객의 이름을 name 오름차순으로 출력해야 하는데, 결과가 아예 비어 있습니다.",
  schema:"CREATE TABLE customers (id INTEGER, name TEXT);\nINSERT INTO customers VALUES (1,'김'),(2,'박'),(3,'이');\nCREATE TABLE orders (id INTEGER, customer_id INTEGER);\nINSERT INTO orders VALUES (10,1),(11,NULL),(12,3);",
  src:"SELECT name FROM customers\nWHERE id NOT IN (SELECT customer_id FROM orders)\nORDER BY name;",
  sol:"SELECT name FROM customers\nWHERE id NOT IN (SELECT customer_id FROM orders WHERE customer_id IS NOT NULL)\nORDER BY name;",
  ex:"🐛 원인: 서브쿼리 결과에 NULL 이 하나라도 있으면 NOT IN 은 어떤 값에 대해서도 참이 될 수 없습니다. 'x <> NULL' 이 참도 거짓도 아닌 UNKNOWN 이기 때문입니다. 그래서 결과가 통째로 비어 버립니다.\n🔧 해결: 서브쿼리에서 NULL 을 걸러냅니다. NOT EXISTS 로 바꾸면 NULL 에 영향받지 않아 더 안전합니다.\n🛡 재발 방지: NOT IN 의 서브쿼리 컬럼이 NULL 을 허용하는지 항상 확인하세요. 습관적으로 NOT EXISTS 를 쓰면 이 함정을 통째로 피할 수 있습니다." },

{ k:"조인 팬아웃이 합계를 부풀린다", ordered:true,
  q:"주문별 결제 총액과 상품 개수를 함께 보고 싶습니다. 결제가 여러 건인 주문에서 상품 개수가 실제보다 크게 나옵니다. order_id, paid, items 를 order_id 오름차순으로 출력하세요.",
  schema:"CREATE TABLE items (order_id INTEGER, sku TEXT);\nINSERT INTO items VALUES (1,'A'),(1,'B'),(2,'C');\nCREATE TABLE pays (order_id INTEGER, amount INTEGER);\nINSERT INTO pays VALUES (1,300),(1,700),(2,500);",
  src:"SELECT i.order_id, SUM(p.amount) AS paid, COUNT(i.sku) AS items\nFROM items i\nJOIN pays p ON p.order_id = i.order_id\nGROUP BY i.order_id\nORDER BY i.order_id;",
  sol:"SELECT i.order_id,\n  (SELECT SUM(p.amount) FROM pays p WHERE p.order_id = i.order_id) AS paid,\n  COUNT(i.sku) AS items\nFROM items i\nGROUP BY i.order_id\nORDER BY i.order_id;",
  ex:"🐛 원인: 두 개의 1:N 테이블을 함께 조인하면 행이 곱해집니다. 주문 1은 상품 2건 × 결제 2건 = 4행이 되어 상품 개수가 2가 아니라 4로, 결제 합계도 두 배로 집계됩니다.\n🔧 해결: 한쪽만 조인하고 나머지는 스칼라 서브쿼리(또는 각각 집계한 뒤 조인)로 가져옵니다.\n🛡 재발 방지: 한 쿼리에서 1:N 테이블을 둘 이상 조인하면서 집계하면 거의 항상 팬아웃입니다. 집계 대상이 두 개 이상이면 먼저 각각 집계한 뒤 조인하세요." },

{ k:"COUNT(컬럼) 은 NULL 을 세지 않는다", ordered:true,
  q:"부서별 직원 수를 세는데, 이메일이 없는 직원이 빠집니다. dept, n 을 dept 오름차순으로 출력하세요.",
  schema:"CREATE TABLE emp (dept TEXT, name TEXT, email TEXT);\nINSERT INTO emp VALUES ('개발','김','k@x'),('개발','박',NULL),('영업','이',NULL),('영업','최','c@x');",
  src:"SELECT dept, COUNT(email) AS n FROM emp GROUP BY dept ORDER BY dept;",
  sol:"SELECT dept, COUNT(*) AS n FROM emp GROUP BY dept ORDER BY dept;",
  ex:"🐛 원인: COUNT(email) 은 email 이 NULL 이 아닌 행만 셉니다. '직원 수' 를 물었는데 '이메일 있는 직원 수' 를 센 것입니다.\n🔧 해결: 행 수를 세려면 COUNT(*) 를 씁니다.\n🛡 재발 방지: COUNT(*) 는 행 수, COUNT(col) 은 NULL 이 아닌 값의 수, COUNT(DISTINCT col) 은 서로 다른 값의 수입니다. 세 개를 구분해서 쓰세요." },

{ k:"WHERE 로는 집계를 거를 수 없다", ordered:true,
  q:"주문이 2건 이상인 고객만 골라 customer, n 을 customer 오름차순으로 출력해야 하는데 쿼리가 실행되지 않습니다.",
  schema:"CREATE TABLE orders (id INTEGER, customer TEXT);\nINSERT INTO orders VALUES (1,'김'),(2,'김'),(3,'박'),(4,'이'),(5,'이'),(6,'이');",
  src:"SELECT customer, COUNT(*) AS n\nFROM orders\nWHERE COUNT(*) >= 2\nGROUP BY customer\nORDER BY customer;",
  sol:"SELECT customer, COUNT(*) AS n\nFROM orders\nGROUP BY customer\nHAVING COUNT(*) >= 2\nORDER BY customer;",
  ex:"🐛 원인: WHERE 는 그룹으로 묶기 '전' 에 개별 행을 거릅니다. 그 시점에는 COUNT(*) 라는 값이 존재하지 않습니다.\n🔧 해결: 집계 결과로 거를 때는 GROUP BY 뒤의 HAVING 을 씁니다.\n🛡 재발 방지: WHERE 는 행 필터, HAVING 은 그룹 필터입니다. 성능상 행 단위로 거를 수 있는 조건은 WHERE 에 두어 집계 대상을 먼저 줄이세요." },

{ k:"= NULL 은 아무것도 찾지 못한다", ordered:true,
  q:"배송지가 입력되지 않은 주문을 찾아야 하는데 결과가 비어 있습니다. id 를 오름차순으로 출력하세요.",
  schema:"CREATE TABLE orders (id INTEGER, address TEXT);\nINSERT INTO orders VALUES (1,'서울'),(2,NULL),(3,''),(4,NULL);",
  src:"SELECT id FROM orders WHERE address = NULL ORDER BY id;",
  sol:"SELECT id FROM orders WHERE address IS NULL ORDER BY id;",
  ex:"🐛 원인: NULL 은 '값이 없음' 이라 어떤 값과도 같지 않고, NULL 과도 같지 않습니다. address = NULL 은 항상 UNKNOWN 이라 WHERE 를 통과하는 행이 없습니다.\n🔧 해결: IS NULL / IS NOT NULL 을 씁니다.\n🛡 재발 방지: 빈 문자열 ''과 NULL 은 다릅니다. 이 데이터에는 둘 다 있으니, '미입력' 의 정의를 먼저 정하고 필요하면 address IS NULL OR address = '' 로 명시하세요." },

{ k:"UNION 이 중복을 지운다", ordered:true,
  q:"올해와 작년의 구매 이력을 모두 이어 붙여 전체 건수를 봐야 합니다. 같은 금액이 반복된 건이 사라져 건수가 모자랍니다. amount 를 오름차순으로 출력하세요.",
  schema:"CREATE TABLE y2024 (amount INTEGER);\nINSERT INTO y2024 VALUES (100),(100),(200);\nCREATE TABLE y2023 (amount INTEGER);\nINSERT INTO y2023 VALUES (100),(300);",
  src:"SELECT amount FROM y2024\nUNION\nSELECT amount FROM y2023\nORDER BY amount;",
  sol:"SELECT amount FROM y2024\nUNION ALL\nSELECT amount FROM y2023\nORDER BY amount;",
  ex:"🐛 원인: UNION 은 두 결과를 합친 뒤 중복 행을 제거합니다. 100원짜리 구매가 세 건 있어도 한 건으로 줄어듭니다.\n🔧 해결: 중복을 유지하려면 UNION ALL 을 씁니다. 중복 제거를 위한 정렬·해싱도 사라져 더 빠릅니다.\n🛡 재발 방지: 기본값이 UNION(중복 제거)이라는 점이 함정입니다. 이력·로그처럼 '건수' 가 의미 있는 데이터에는 항상 UNION ALL 을 쓰세요." },

{ k:"정수 나눗셈이 소수를 버린다", ordered:true,
  q:"부서별 평균 급여를 소수점 이하까지 보고 싶은데 전부 정수로 잘려 나옵니다. dept, avg_pay 를 dept 오름차순으로 출력하세요.",
  schema:"CREATE TABLE pay (dept TEXT, amount INTEGER);\nINSERT INTO pay VALUES ('개발',100),('개발',101),('영업',200),('영업',201),('영업',203);",
  src:"SELECT dept, SUM(amount)/COUNT(*) AS avg_pay\nFROM pay GROUP BY dept ORDER BY dept;",
  sol:"SELECT dept, SUM(amount)*1.0/COUNT(*) AS avg_pay\nFROM pay GROUP BY dept ORDER BY dept;",
  ex:"🐛 원인: 정수끼리 나누면 SQLite 는 정수 나눗셈을 해 소수를 버립니다. 100.5 가 100 이 됩니다.\n🔧 해결: 한쪽에 1.0 을 곱해 실수 연산으로 만듭니다. CAST(SUM(amount) AS REAL) 이나 그냥 AVG(amount) 도 같은 결과입니다.\n🛡 재발 방지: 비율·평균·전환율처럼 소수가 나와야 하는 계산은 나누기 전에 타입을 확인하세요. 방언마다 정수 나눗셈 규칙이 달라 이식할 때도 자주 깨집니다." },

{ k:"AND 가 OR 보다 먼저 묶인다", ordered:true,
  q:"결제가 완료된 주문 중 금액이 100 미만이거나 10000 초과인 '이상 거래' 를 찾아야 합니다. 취소된 주문까지 섞여 나옵니다. id 를 오름차순으로 출력하세요.",
  schema:"CREATE TABLE orders (id INTEGER, status TEXT, amount INTEGER);\nINSERT INTO orders VALUES (1,'완료',50),(2,'취소',20000),(3,'완료',20000),(4,'완료',500),(5,'취소',10);",
  src:"SELECT id FROM orders\nWHERE status = '완료' AND amount < 100 OR amount > 10000\nORDER BY id;",
  sol:"SELECT id FROM orders\nWHERE status = '완료' AND (amount < 100 OR amount > 10000)\nORDER BY id;",
  ex:"🐛 원인: AND 가 OR 보다 우선순위가 높아 조건이 (status='완료' AND amount<100) OR (amount>10000) 로 묶입니다. 뒤쪽 OR 가지에는 상태 조건이 걸리지 않아 취소된 고액 주문까지 통과합니다.\n🔧 해결: 묶고 싶은 범위에 괄호를 칩니다.\n🛡 재발 방지: AND 와 OR 를 한 WHERE 절에 섞을 때는 우선순위를 외우지 말고 괄호를 치세요. 리뷰에서도 괄호 없는 AND/OR 혼용은 그 자체로 지적 대상입니다." },

{ k:"CASE 에 ELSE 가 없어 NULL 이 된다", ordered:true,
  q:"점수를 등급으로 바꿉니다. 60점 미만이 NULL 로 나옵니다. '하' 로 표시되어야 합니다. name, grade 를 name 오름차순으로 출력하세요.",
  schema:"CREATE TABLE score (name TEXT, pt INTEGER);\nINSERT INTO score VALUES ('김',95),('박',75),('이',40),('최',20);",
  src:"SELECT name,\n  CASE WHEN pt >= 90 THEN '상'\n       WHEN pt >= 60 THEN '중'\n  END AS grade\nFROM score ORDER BY name;",
  sol:"SELECT name,\n  CASE WHEN pt >= 90 THEN '상'\n       WHEN pt >= 60 THEN '중'\n       ELSE '하'\n  END AS grade\nFROM score ORDER BY name;",
  ex:"🐛 원인: CASE 의 모든 WHEN 이 거짓이고 ELSE 가 없으면 결과는 NULL 입니다. 오류가 아니라 조용히 빈 값이 되어 화면에는 빈칸으로 보입니다.\n🔧 해결: ELSE 를 명시해 나머지 경우를 정의합니다.\n🛡 재발 방지: CASE 에는 항상 ELSE 를 쓰세요. '있을 수 없는 경우' 라도 ELSE '미분류' 를 두면 데이터 이상을 바로 알아챌 수 있습니다." },

{ k:"AVG 는 NULL 을 빼고 계산한다", ordered:true,
  q:"설문 응답 점수의 평균을 냅니다. 무응답(NULL)을 0점으로 쳐야 하는데 아예 빠져서 평균이 높게 나옵니다. avg_pt 한 컬럼을 출력하세요.",
  schema:"CREATE TABLE survey (id INTEGER, pt INTEGER);\nINSERT INTO survey VALUES (1,10),(2,NULL),(3,20),(4,NULL);",
  src:"SELECT AVG(pt) AS avg_pt FROM survey;",
  sol:"SELECT AVG(COALESCE(pt,0)) AS avg_pt FROM survey;",
  ex:"🐛 원인: AVG 는 NULL 인 행을 분모에서도 빼 버립니다. (10+20)/2 = 15 가 되지만, 무응답을 0점으로 치면 (10+0+20+0)/4 = 7.5 여야 합니다.\n🔧 해결: COALESCE 로 NULL 을 0 으로 바꾼 뒤 평균을 냅니다.\n🛡 재발 방지: 집계 함수는 전부 NULL 을 건너뜁니다. '무응답을 0으로 볼 것인가, 모집단에서 뺄 것인가' 는 도메인 결정이므로 쿼리에 명시적으로 드러내야 합니다." },

{ k:"BETWEEN 이 마지막 날의 시각을 자른다", ordered:true,
  q:"3월 한 달간의 주문을 모두 뽑아야 하는데 3월 31일 오후 건이 빠집니다. id 를 오름차순으로 출력하세요.",
  schema:"CREATE TABLE orders (id INTEGER, created_at TEXT);\nINSERT INTO orders VALUES (1,'2024-03-01 09:00:00'),(2,'2024-03-15 12:00:00'),(3,'2024-03-31 18:30:00'),(4,'2024-04-01 08:00:00');",
  src:"SELECT id FROM orders\nWHERE created_at BETWEEN '2024-03-01' AND '2024-03-31'\nORDER BY id;",
  sol:"SELECT id FROM orders\nWHERE created_at >= '2024-03-01' AND created_at < '2024-04-01'\nORDER BY id;",
  ex:"🐛 원인: '2024-03-31' 은 문자열 비교에서 '2024-03-31 18:30:00' 보다 작습니다(짧은 쪽이 먼저 끝나므로). BETWEEN 의 상한이 그날 00:00 을 뜻하게 되어 31일 낮 시간대가 통째로 빠집니다.\n🔧 해결: 상한을 다음 달 1일 '미만' 으로 잡는 반열린 구간을 씁니다.\n🛡 재발 방지: 시각이 붙은 컬럼에 BETWEEN 을 쓰지 마세요. 기간 조건은 언제나 `>= 시작 AND < 다음_시작` 이 안전하고, 타임존·윤초·정밀도 변화에도 깨지지 않습니다." },

{ k:"COUNT 와 COUNT DISTINCT", ordered:true,
  q:"상품별로 '구매한 고객 수' 를 세야 하는데, 같은 고객이 여러 번 사면 중복으로 세어집니다. sku, buyers 를 sku 오름차순으로 출력하세요.",
  schema:"CREATE TABLE buys (sku TEXT, customer TEXT);\nINSERT INTO buys VALUES ('A','김'),('A','김'),('A','박'),('B','이'),('B','이');",
  src:"SELECT sku, COUNT(customer) AS buyers FROM buys GROUP BY sku ORDER BY sku;",
  sol:"SELECT sku, COUNT(DISTINCT customer) AS buyers FROM buys GROUP BY sku ORDER BY sku;",
  ex:"🐛 원인: COUNT(customer) 는 행 수를 셉니다. 같은 고객이 두 번 사면 두 번 세어져 '고객 수' 가 아니라 '구매 건수' 가 됩니다.\n🔧 해결: COUNT(DISTINCT customer) 로 서로 다른 값의 개수를 셉니다.\n🛡 재발 방지: 지표 이름에 '수' 가 붙으면 무엇의 수인지 먼저 확정하세요. 건수·사용자 수·세션 수는 전부 다른 쿼리이고, 셋을 섞으면 대시보드 전체가 틀어집니다." },

{ k:"문자열 이어붙이기는 || 다", ordered:true,
  q:"성과 이름을 붙여 전체 이름을 만듭니다. 결과가 전부 0 으로 나옵니다. full 한 컬럼을 오름차순으로 출력하세요.",
  schema:"CREATE TABLE person (last TEXT, first TEXT);\nINSERT INTO person VALUES ('김','철수'),('박','영희');",
  src:"SELECT last + first AS full FROM person ORDER BY full;",
  sol:"SELECT last || first AS full FROM person ORDER BY full;",
  ex:"🐛 원인: SQLite 에서 + 는 산술 덧셈입니다. 숫자가 아닌 문자열은 0 으로 변환되어 0 + 0 = 0 이 됩니다. 오류가 아니라 그럴듯한 값이 나오는 게 더 위험합니다.\n🔧 해결: 표준 SQL 의 문자열 연결 연산자 || 를 씁니다.\n🛡 재발 방지: + 로 문자열을 잇는 건 SQL Server 방언입니다. MySQL 은 CONCAT, 표준·SQLite·PostgreSQL 은 || 입니다. 방언을 넘나들 때 가장 먼저 깨지는 지점입니다." },

{ k:"LIMIT 앞에 ORDER BY 가 없다", ordered:true,
  q:"가장 비싼 상품 2건을 뽑아야 하는데 아무거나 두 개가 나옵니다. name, price 를 price 내림차순으로 출력하세요.",
  schema:"CREATE TABLE products (name TEXT, price INTEGER);\nINSERT INTO products VALUES ('USB',100),('노트북',900),('키보드',300),('모니터',700);",
  src:"SELECT name, price FROM products LIMIT 2;",
  sol:"SELECT name, price FROM products ORDER BY price DESC LIMIT 2;",
  ex:"🐛 원인: ORDER BY 가 없으면 행 순서는 정의되지 않습니다. 지금 우연히 맞아 보여도 인덱스·통계·플랜이 바뀌면 결과가 달라집니다.\n🔧 해결: LIMIT 은 반드시 ORDER BY 와 함께 씁니다.\n🛡 재발 방지: 'TOP N' 은 정렬 기준이 있어야 정의되는 개념입니다. 동점이 있을 수 있다면 타이브레이커 컬럼(예: ORDER BY price DESC, name)까지 넣어야 결과가 재현됩니다." },

{ k:"<> 가 NULL 행을 조용히 버린다", ordered:true,
  q:"상태가 '취소' 가 아닌 주문을 모두 세야 합니다. 상태가 아직 입력되지 않은(NULL) 주문이 빠집니다. id 를 오름차순으로 출력하세요.",
  schema:"CREATE TABLE orders (id INTEGER, status TEXT);\nINSERT INTO orders VALUES (1,'완료'),(2,'취소'),(3,NULL),(4,'배송중');",
  src:"SELECT id FROM orders WHERE status <> '취소' ORDER BY id;",
  sol:"SELECT id FROM orders WHERE status IS NULL OR status <> '취소' ORDER BY id;",
  ex:"🐛 원인: NULL <> '취소' 는 참이 아니라 UNKNOWN 입니다. WHERE 는 UNKNOWN 인 행을 버리므로, '취소가 아닌' 조건인데도 상태 미입력 행이 함께 사라집니다.\n🔧 해결: NULL 을 어떻게 볼지 명시합니다. COALESCE(status,'') <> '취소' 도 같은 결과를 냅니다.\n🛡 재발 방지: 부정 조건(<>, NOT IN, NOT LIKE)은 전부 NULL 을 삼킵니다. NULL 을 허용하는 컬럼에 부정 조건을 쓸 때는 반드시 NULL 처리를 함께 적으세요." },

{ k:"DISTINCT 가 의도한 컬럼에 걸리지 않는다", ordered:true,
  q:"주문한 적 있는 고객 목록을 중복 없이 뽑아야 하는데, 같은 고객이 여러 번 나옵니다. customer 를 오름차순으로 출력하세요.",
  schema:"CREATE TABLE orders (id INTEGER, customer TEXT);\nINSERT INTO orders VALUES (1,'김'),(2,'김'),(3,'박');",
  src:"SELECT DISTINCT customer, id FROM orders ORDER BY customer;",
  sol:"SELECT DISTINCT customer FROM orders ORDER BY customer;",
  ex:"🐛 원인: DISTINCT 는 특정 컬럼이 아니라 '선택된 행 전체' 에 걸립니다. id 를 함께 고르면 (김,1) 과 (김,2) 는 서로 다른 행이라 둘 다 남습니다.\n🔧 해결: 중복 판단에 쓰지 않을 컬럼은 SELECT 목록에서 빼야 합니다.\n🛡 재발 방지: DISTINCT 로 원하는 결과가 안 나오면 대개 SELECT 목록에 군더더기 컬럼이 있습니다. 정말 그 컬럼도 필요하다면 GROUP BY 와 집계로 어느 값을 고를지 정하세요." },

{ k:"LIKE 의 와일드카드 위치", ordered:true,
  q:"제목에 '오류' 가 들어간 로그를 찾아야 하는데, '오류' 로 시작하는 것만 나옵니다. id 를 오름차순으로 출력하세요.",
  schema:"CREATE TABLE logs (id INTEGER, title TEXT);\nINSERT INTO logs VALUES (1,'오류 발생'),(2,'결제 오류 로그'),(3,'정상 처리'),(4,'DB 오류');",
  src:"SELECT id FROM logs WHERE title LIKE '오류%' ORDER BY id;",
  sol:"SELECT id FROM logs WHERE title LIKE '%오류%' ORDER BY id;",
  ex:"🐛 원인: '오류%' 는 '오류로 시작하는' 패턴입니다. 문자열 어디든 포함되는지 보려면 앞에도 와일드카드가 필요합니다.\n🔧 해결: 앞뒤에 % 를 붙여 '%오류%' 로 만듭니다.\n🛡 재발 방지: 앞에 % 가 붙으면 인덱스를 못 씁니다. 대량 테이블에서 부분 문자열 검색이 잦다면 LIKE 대신 전문 검색(FTS)이나 별도 색인 컬럼을 검토하세요." },

{ k:"HAVING 에 쓴 별칭과 집계 순서", ordered:true,
  q:"평균 단가가 200 이상인 카테고리만 남겨야 하는데, 개별 주문 단가로 걸러져 결과가 다릅니다. cat, avg_price 를 cat 오름차순으로 출력하세요.",
  schema:"CREATE TABLE items (cat TEXT, price INTEGER);\nINSERT INTO items VALUES ('A',100),('A',500),('B',150),('B',180),('C',900);",
  src:"SELECT cat, AVG(price) AS avg_price\nFROM items\nWHERE price >= 200\nGROUP BY cat\nORDER BY cat;",
  sol:"SELECT cat, AVG(price) AS avg_price\nFROM items\nGROUP BY cat\nHAVING AVG(price) >= 200\nORDER BY cat;",
  ex:"🐛 원인: WHERE price >= 200 은 200 미만인 개별 행을 먼저 버립니다. A 카테고리는 100 이 빠진 채 평균이 500 으로 계산되고, B 는 모든 행이 사라져 그룹 자체가 없어집니다. 실제 평균(A=300, B=165)과 전혀 다릅니다.\n🔧 해결: 평균을 낸 '뒤' 에 거르는 HAVING 을 씁니다.\n🛡 재발 방지: '평균이 ~인 그룹' 과 '값이 ~인 행' 은 완전히 다른 조건입니다. 요구사항의 주어가 그룹인지 행인지 먼저 확인하세요." },

{ k:"자기 조인이 쌍을 두 번 만든다", ordered:true,
  q:"같은 팀에 속한 사람들의 조합을 한 번씩만 나열해야 하는데, (김,박)과 (박,김)이 둘 다 나옵니다. a, b 를 a, b 오름차순으로 출력하세요.",
  schema:"CREATE TABLE members (name TEXT, team TEXT);\nINSERT INTO members VALUES ('김','A'),('박','A'),('이','A'),('최','B');",
  src:"SELECT m1.name AS a, m2.name AS b\nFROM members m1 JOIN members m2\n  ON m1.team = m2.team AND m1.name <> m2.name\nORDER BY a, b;",
  sol:"SELECT m1.name AS a, m2.name AS b\nFROM members m1 JOIN members m2\n  ON m1.team = m2.team AND m1.name < m2.name\nORDER BY a, b;",
  ex:"🐛 원인: <> 는 서로 다르기만 하면 참이라 (김,박)과 (박,김)이 모두 나옵니다. 자기 자신만 제외했을 뿐 순서가 뒤집힌 쌍은 막지 못합니다.\n🔧 해결: < 로 비교하면 한쪽 방향만 남아 각 쌍이 정확히 한 번씩 나옵니다.\n🛡 재발 방지: 조합(순서 없음)과 순열(순서 있음)을 구분하세요. 조합이면 자기 조인에 부등호 하나로 방향을 고정하는 것이 표준 관용구입니다." },

{ k:"IN 서브쿼리가 엉뚱한 컬럼을 본다", ordered:true,
  q:"VIP 고객이 낸 주문만 뽑아야 하는데 모든 주문이 나옵니다. id 를 오름차순으로 출력하세요.",
  schema:"CREATE TABLE vips (customer_id INTEGER);\nINSERT INTO vips VALUES (1),(3);\nCREATE TABLE orders (id INTEGER, customer_id INTEGER);\nINSERT INTO orders VALUES (1,1),(2,2),(3,3),(4,4);",
  src:"SELECT id FROM orders o\nWHERE o.customer_id IN (SELECT o.customer_id FROM vips)\nORDER BY id;",
  sol:"SELECT id FROM orders o\nWHERE o.customer_id IN (SELECT v.customer_id FROM vips v)\nORDER BY id;",
  ex:"🐛 원인: 서브쿼리 안에서 o.customer_id 를 고르면 바깥 쿼리의 컬럼을 그대로 참조합니다. 조건이 'x IN (x, x, ...)' 이 되어 언제나 참이고, VIP 테이블은 행 수만 제공할 뿐 값은 쓰이지 않습니다.\n🔧 해결: 서브쿼리에서 참조할 테이블에 별칭을 붙이고 그 별칭으로 컬럼을 지정합니다.\n🛡 재발 방지: 상관 서브쿼리는 바깥 컬럼을 조용히 끌어다 씁니다. 서브쿼리 안 모든 컬럼에 테이블 별칭을 붙이는 습관이 이 실수를 원천 차단합니다." },

{ k:"GROUP BY 기준이 빠졌다", ordered:true,
  q:"연도별·부서별 지출 합계를 봐야 하는데 부서가 뭉쳐져 나옵니다. yr, dept, total 을 yr, dept 오름차순으로 출력하세요.",
  schema:"CREATE TABLE spend (yr INTEGER, dept TEXT, amount INTEGER);\nINSERT INTO spend VALUES (2024,'개발',100),(2024,'영업',200),(2023,'개발',50),(2023,'영업',70);",
  src:"SELECT yr, dept, SUM(amount) AS total\nFROM spend GROUP BY yr ORDER BY yr, dept;",
  sol:"SELECT yr, dept, SUM(amount) AS total\nFROM spend GROUP BY yr, dept ORDER BY yr, dept;",
  ex:"🐛 원인: GROUP BY 에 dept 가 빠져 연도 단위로만 묶였습니다. SQLite 는 오류 없이 그룹 안 임의의 dept 값을 보여 주므로 '부서별' 로 보이지만 실제로는 연도 합계입니다.\n🔧 해결: SELECT 에 있는 비집계 컬럼은 모두 GROUP BY 에 넣습니다.\n🛡 재발 방지: 다른 DB(PostgreSQL 등)는 같은 쿼리를 오류로 막습니다. SQLite 가 허용한다고 맞는 게 아니라, 오히려 조용히 틀린 값을 내는 쪽이 위험합니다." },

{ k:"COALESCE 자리가 잘못돼 0 이 사라진다", ordered:true,
  q:"상품별 재고를 보여 주되 재고 기록이 없으면 0 으로 표시해야 합니다. 기록이 없는 상품이 아예 안 나옵니다. sku, qty 를 sku 오름차순으로 출력하세요.",
  schema:"CREATE TABLE products (sku TEXT);\nINSERT INTO products VALUES ('A'),('B'),('C');\nCREATE TABLE stock (sku TEXT, qty INTEGER);\nINSERT INTO stock VALUES ('A',5),('C',0);",
  src:"SELECT p.sku, COALESCE(s.qty,0) AS qty\nFROM products p\nJOIN stock s ON s.sku = p.sku\nORDER BY p.sku;",
  sol:"SELECT p.sku, COALESCE(s.qty,0) AS qty\nFROM products p\nLEFT JOIN stock s ON s.sku = p.sku\nORDER BY p.sku;",
  ex:"🐛 원인: COALESCE 는 값이 NULL 일 때만 도와줍니다. INNER JOIN 은 짝이 없는 행을 아예 없애므로 NULL 이 될 기회조차 없습니다. B 는 결과에 등장하지 않습니다.\n🔧 해결: 왼쪽을 모두 남기는 LEFT JOIN 으로 바꿔야 COALESCE 가 일할 수 있습니다.\n🛡 재발 방지: '없으면 0' 요구사항은 COALESCE 하나로 끝나지 않습니다. 먼저 조인이 그 행을 남기는지 확인하고, 그다음에 NULL 을 채우세요." },

{ k:"ORDER BY 가 문자열 정렬을 한다", ordered:true,
  q:"버전 코드를 숫자 크기 순으로 정렬해야 하는데 10 이 9 보다 앞에 옵니다. code 를 숫자 오름차순으로 출력하세요.",
  schema:"CREATE TABLE rel (code TEXT);\nINSERT INTO rel VALUES ('2'),('10'),('9'),('100');",
  src:"SELECT code FROM rel ORDER BY code;",
  sol:"SELECT code FROM rel ORDER BY CAST(code AS INTEGER);",
  ex:"🐛 원인: code 가 TEXT 라 사전순으로 정렬됩니다. '10' 은 '9' 보다 앞이고 '100' 은 '2' 보다 앞입니다.\n🔧 해결: CAST 로 숫자로 바꿔 정렬합니다.\n🛡 재발 방지: 근본 해결은 컬럼 타입을 INTEGER 로 잡는 것입니다. 매 조회마다 CAST 하면 인덱스를 못 쓰고, 숫자가 아닌 값이 섞이면 조용히 0 으로 정렬됩니다." },
];
