/* 딥러닝 디버깅 12 — 손실이 줄긴 하는데 틀린 코드를 고친다.
   전부 결정적이고 순수 JS 다. 검증:  node ver_dbgjs.cjs ./dbg_dl.cjs */
module.exports = [

{ track:"dl", cat:"debug", k:"소프트맥스가 큰 로짓에서 넘친다",
  q:"로짓 배열을 확률로 바꿉니다. 실제 로짓은 수백까지 커질 수 있습니다. 결과는 소수 여섯째 자리까지 반올림합니다. 지금은 큰 값에서 <b>전부 <code>NaN</code></b> 이 됩니다.",
  src:"function softmax(xs) {\n  const e = xs.map(x => Math.exp(x));\n  const s = e.reduce((a, v) => a + v, 0);\n  return e.map(v => Math.round(v / s * 1e6) / 1e6);\n}",
  sol:"function softmax(xs) {\n  if (!xs.length) return [];\n  const m = Math.max(...xs);\n  const e = xs.map(x => Math.exp(x - m));\n  const s = e.reduce((a, v) => a + v, 0);\n  return e.map(v => Math.round(v / s * 1e6) / 1e6);\n}",
  tests:[["softmax([0, 0])","[0.5,0.5]"],
         ["softmax([1000, 1000])","[0.5,0.5]"],
         ["softmax([1000, 999])","[0.731059,0.268941]"],
         ["softmax([1, 2, 3])","[0.090031,0.244728,0.665241]"]],
  edge:[["softmax([])","[]"],
        ["softmax([-1000, -1000])","[0.5,0.5]"]],
  ex:"🐛 원인: <code>Math.exp(1000)</code> 은 <code>Infinity</code> 이고 <code>Infinity/Infinity</code> 는 <code>NaN</code> 입니다. 반대로 로짓이 아주 작으면 <code>exp</code> 가 전부 0 이 되어 <b>0 으로 나누기</b>가 됩니다. 작은 예제(<code>[1,2,3]</code>)로 테스트하면 완벽하게 동작합니다.\n🔧 해결: 소프트맥스는 <b>모든 입력에 같은 수를 더하거나 빼도 결과가 같습니다</b>. 최댓값을 빼면 지수의 인자가 0 이하가 되어 절대 넘치지 않고, 최댓값 항은 <code>exp(0) = 1</code> 이라 아래로도 무너지지 않습니다.\n🛡 재발 방지: 수치 안정성은 '<b>실전 크기의 값</b>' 을 테스트에 넣어야 드러납니다. 그리고 로그 확률이 필요하면 <code>log(softmax(x))</code> 대신 <b>log-softmax</b> 를 한 번에 계산하세요 — 중간에서 0 이 되는 값을 로그로 넘기지 않게 됩니다." },

{ track:"dl", cat:"debug", k:"드롭아웃이 추론에서도 켜져 있다",
  q:"드롭아웃 마스크를 적용합니다(역스케일 방식). <b>학습 중</b>에는 살아남은 값을 <code>1/(1-p)</code> 로 키우고, <b>추론</b>에서는 아무것도 하지 않습니다. 지금은 같은 입력에 매번 다른 예측이 나옵니다.",
  src:"function applyDropout(xs, mask, p, training) {\n  return xs.map((x, i) => (mask[i] ? x / (1 - p) : 0));\n}",
  sol:"function applyDropout(xs, mask, p, training) {\n  if (!training) return xs.slice();\n  return xs.map((x, i) => (mask[i] ? x / (1 - p) : 0));\n}",
  tests:[["applyDropout([1,2], [1,0], 0.5, true)","[2,0]"],
         ["applyDropout([1,2], [1,0], 0.5, false)","[1,2]"],
         ["applyDropout([4], [1], 0.5, false)","[4]"],
         ["applyDropout([4], [0], 0.5, true)","[0]"]],
  edge:[["applyDropout([], [], 0.5, true)","[]"],
        ["applyDropout([3,3], [1,1], 0, true)","[3,3]"]],
  ex:"🐛 원인: <code>training</code> 인자를 받아 놓고 쓰지 않았습니다. 추론에서도 뉴런이 꺼지면 같은 입력에 <b>매번 다른 출력</b>이 나오고, 배치 크기나 순서에 따라 결과가 흔들립니다 — 재현이 안 되는 예측만큼 디버깅하기 어려운 것이 없습니다.\n🔧 해결: 추론이면 입력을 그대로 돌려줍니다. 역스케일 방식은 <b>학습 때만</b> 나누므로 추론 경로에 추가 계산이 아예 없다는 것이 장점입니다.\n🛡 재발 방지: 학습·추론에서 동작이 갈리는 층은 드롭아웃뿐이 아닙니다 — <b>배치 정규화</b>도 학습에서는 배치 통계를, 추론에서는 누적 통계를 씁니다. 프레임워크의 <code>model.eval()</code> 을 빠뜨리는 것이 같은 사고이고, '학습에서는 좋은데 추론이 이상하다' 면 이 둘을 가장 먼저 보세요." },

{ track:"dl", cat:"debug", k:"기울기 클리핑을 원소마다 자른다",
  q:"기울기 벡터를 <b>전체 노름 기준</b>으로 자릅니다. 노름이 <code>max</code> 를 넘으면 벡터 전체에 같은 비율을 곱해 방향을 유지합니다. 결과는 소수 여섯째 자리까지 반올림합니다. 지금은 클리핑이 걸릴 때마다 <b>기울기 방향이 바뀝니다</b>.",
  src:"function clipGrad(g, max) {\n  return g.map(v => Math.max(-max, Math.min(max, v)));\n}",
  sol:"function clipGrad(g, max) {\n  const n = Math.sqrt(g.reduce((s, v) => s + v * v, 0));\n  if (n <= max || n === 0) return g.slice();\n  const k = max / n;\n  return g.map(v => Math.round(v * k * 1e6) / 1e6);\n}",
  tests:[["clipGrad([3, 4], 5)","[3,4]"],
         ["clipGrad([6, 8], 5)","[3,4]"],
         ["clipGrad([0, 0], 1)","[0,0]"],
         ["clipGrad([10, 0], 2)","[2,0]"]],
  edge:[["clipGrad([1], 10)","[1]"],
        ["clipGrad([-6, -8], 5)","[-3,-4]"]],
  ex:"🐛 원인: 원소마다 자르면 <b>큰 성분만 깎여</b> 벡터의 방향이 달라집니다. 기울기는 '어느 쪽으로 갈지' 를 담고 있으므로 방향이 바뀌면 최적화가 엉뚱한 곳으로 갑니다. 노름 클리핑의 목적은 <b>보폭만 줄이고 방향은 지키는</b> 것입니다.\n🔧 해결: 전체 노름을 구해 넘칠 때만 <code>max/노름</code> 을 <b>모든 원소에 같은 비율로</b> 곱합니다. 노름이 0 이면 나누지 않습니다.\n🛡 재발 방지: 클리핑이 자주 걸린다면 학습률·초기화·정규화가 잘못됐다는 신호일 수 있으니, <b>클리핑 발동 비율</b>을 로그로 남기세요. 그리고 값 자체를 자르는 클리핑(<code>clip_value</code>)도 쓰임이 있지만 <b>다른 도구</b>이므로 이름을 구분해야 합니다." },

{ track:"dl", cat:"debug", k:"학습률 워밍업이 0 에서 나눈다",
  q:"선형 워밍업 학습률입니다. <code>step</code> 이 <code>warmup</code> 미만이면 <code>lr × (step+1)/warmup</code>, 그 뒤로는 <code>lr</code> 입니다. <code>warmup</code> 이 0 이면 워밍업 없이 <code>lr</code> 입니다. 지금은 워밍업을 끄면 학습률이 <code>NaN</code> 이 됩니다.",
  src:"function warmupLr(lr, step, warmup) {\n  return step <= warmup ? lr * (step + 1) / warmup : lr;\n}",
  sol:"function warmupLr(lr, step, warmup) {\n  if (!(warmup > 0)) return lr;\n  return step < warmup ? lr * (step + 1) / warmup : lr;\n}",
  tests:[["warmupLr(0.1, 0, 10)","0.01"],
         ["warmupLr(0.1, 9, 10)","0.1"],
         ["warmupLr(0.1, 10, 10)","0.1"],
         ["warmupLr(0.1, 0, 0)","0.1"]],
  edge:[["warmupLr(0.2, 3, 0)","0.2"],
        ["warmupLr(0.2, 0, 1)","0.2"]],
  ex:"🐛 원인: 두 가지가 어긋났습니다. <code>&lt;=</code> 라서 워밍업이 <b>한 스텝 더</b> 이어지고, 그 자리에서 <code>(step+1)/warmup</code> 이 1 을 넘어 <b>기준 학습률보다 큰 값</b>이 나옵니다. 그리고 워밍업을 끄면(<code>warmup = 0</code>) <code>0 &lt;= 0</code> 이 참이라 0 으로 나누어 <code>Infinity</code> 가 됩니다 — 설정에서 워밍업을 끄는 것은 <b>흔한 실험 조건</b>이라 반드시 지나가는 경로입니다.\n🔧 해결: 경계를 <code>&lt;</code> 로 바로잡고, <code>warmup</code> 이 양수인지 <b>먼저</b> 봅니다. <code>!(warmup &gt; 0)</code> 으로 적으면 <code>NaN</code> 설정값도 함께 걸립니다.\n🛡 재발 방지: 스케줄러는 <b>스텝 0 과 마지막 스텝</b>, 그리고 <b>기능을 끈 설정</b>을 반드시 테스트하세요. 학습이 첫 스텝부터 <code>NaN</code> 이면 데이터가 아니라 스케줄러를 먼저 의심하는 것이 빠릅니다." },

{ track:"dl", cat:"debug", k:"패딩 토큰까지 손실에 넣는다",
  q:"패딩이 섞인 배치의 <b>평균 손실</b>을 구합니다. 마스크가 0 인 자리는 패딩이라 <b>빼고</b> 세야 합니다. 남는 토큰이 없으면 <code>null</code> 입니다. 지금은 문장이 짧은 배치에서 손실이 <b>비정상적으로 낮게</b> 나옵니다.",
  src:"function maskedLoss(losses, mask) {\n  const s = losses.reduce((a, v, i) => a + v * mask[i], 0);\n  return Math.round(s / losses.length * 1e6) / 1e6;\n}",
  sol:"function maskedLoss(losses, mask) {\n  let s = 0, n = 0;\n  for (let i = 0; i < losses.length; i += 1) {\n    if (!mask[i]) continue;\n    s += losses[i];\n    n += 1;\n  }\n  if (!n) return null;\n  return Math.round(s / n * 1e6) / 1e6;\n}",
  tests:[["maskedLoss([2, 2, 0, 0], [1, 1, 0, 0])","2"],
         ["maskedLoss([1, 3], [1, 1])","2"],
         ["maskedLoss([5, 0, 0, 0], [1, 0, 0, 0])","5"],
         ["maskedLoss([1, 1], [0, 0]) === null","true"]],
  edge:[["maskedLoss([], []) === null","true"],
        ["maskedLoss([4, 8, 0], [1, 1, 0])","6"]],
  ex:"🐛 원인: 분자에서는 패딩을 0 으로 지웠는데 <b>분모는 전체 길이</b>를 그대로 썼습니다. 그러면 패딩이 많은 배치일수록 평균이 작아져, 손실 곡선이 <b>배치 구성에 따라 출렁입니다</b>. 모델이 좋아진 것처럼 보이지만 실제로는 패딩 비율이 바뀐 것뿐입니다.\n🔧 해결: 마스크가 1 인 <b>실제 토큰 수</b>로 나눕니다. 배치에 유효 토큰이 하나도 없는 경우도 계약에 넣습니다.\n🛡 재발 방지: 마스킹은 '<b>분자와 분모를 같이</b>' 고쳐야 합니다 — 한쪽만 고치는 것이 가장 흔한 실수입니다. 그리고 길이가 비슷한 문장끼리 묶는 <b>버킷 배치</b>를 쓰면 패딩 자체가 줄어 이 문제의 영향도 함께 작아집니다." },

{ track:"dl", cat:"debug", k:"어텐션 마스크를 곱셈으로 건다",
  q:"어텐션 점수에 마스크를 겁니다. 마스크가 0 인 자리는 <b>소프트맥스 뒤 확률이 0</b> 이어야 하므로, 점수를 <code>-Infinity</code> 로 만들어야 합니다. 지금은 가려야 할 미래 토큰에 <b>확률이 남습니다</b>.",
  src:"function maskScores(scores, mask) {\n  return scores.map((v, i) => v * mask[i]);\n}",
  sol:"function maskScores(scores, mask) {\n  return scores.map((v, i) => (mask[i] ? v : -Infinity));\n}",
  tests:[["maskScores([1, 2, 3], [1, 1, 0])","[1,2,null]"],
         ["maskScores([1, 2], [1, 1])","[1,2]"],
         ["maskScores([5], [0])","[null]"],
         ["maskScores([-1, -2], [0, 1])","[null,-2]"]],
  edge:[["maskScores([], [])","[]"],
        ["maskScores([0, 0], [1, 0])","[0,null]"]],
  ex:"🐛 원인: 점수에 0 을 곱하면 <b>점수가 0 이 될 뿐</b> 확률이 0 이 되지 않습니다. <code>exp(0) = 1</code> 이라 소프트맥스 뒤에도 상당한 확률이 남고, 인과 어텐션이라면 모델이 <b>미래를 보게</b> 됩니다 — 학습 손실은 아주 좋아지고 생성 품질은 무너지는 전형적인 증상입니다.\n🔧 해결: 가릴 자리의 점수를 <code>-Infinity</code>(실무에서는 아주 큰 음수)로 바꿉니다. 그러면 <code>exp</code> 가 0 이 되어 확률이 정확히 0 이 됩니다.\n🛡 재발 방지: 마스킹은 '<b>어느 단계에서</b>' 거는지가 전부입니다 — 소프트맥스 <b>앞</b>이면 −∞, <b>뒤</b>라면 0 을 곱하고 다시 정규화해야 합니다. 그리고 모든 자리가 가려진 행은 소프트맥스가 <code>NaN</code> 이 되므로 그 경우도 따로 다뤄야 합니다." },

{ track:"dl", cat:"debug", k:"배치 정규화가 추론에서 배치 통계를 쓴다",
  q:"배치 정규화의 정규화 단계입니다. <b>학습</b>에서는 배치 평균·분산을, <b>추론</b>에서는 누적 평균·분산을 씁니다. 결과는 소수 여섯째 자리까지 반올림합니다. 지금은 배치 크기 1 로 추론하면 출력이 전부 0 입니다.",
  src:"function bnForward(xs, run, training, eps) {\n  const m = xs.reduce((s, x) => s + x, 0) / xs.length;\n  const v = xs.reduce((s, x) => s + (x - m) ** 2, 0) / xs.length;\n  return xs.map(x => Math.round((x - m) / Math.sqrt(v + eps) * 1e6) / 1e6);\n}",
  sol:"function bnForward(xs, run, training, eps) {\n  let m = run.mean, v = run.var;\n  if (training) {\n    m = xs.reduce((s, x) => s + x, 0) / xs.length;\n    v = xs.reduce((s, x) => s + (x - m) ** 2, 0) / xs.length;\n  }\n  return xs.map(x => Math.round((x - m) / Math.sqrt(v + eps) * 1e6) / 1e6);\n}",
  tests:[["bnForward([5], {mean:0, var:1}, false, 0)","[5]"],
         ["bnForward([1, 3], {mean:0, var:1}, false, 0)","[1,3]"],
         ["bnForward([1, 3], {mean:2, var:1}, true, 0)","[-1,1]"],
         ["bnForward([4, 4], {mean:0, var:4}, false, 0)","[2,2]"]],
  edge:[["bnForward([2], {mean:2, var:1}, false, 0)","[0]"],
        ["bnForward([0, 0], {mean:0, var:1}, true, 1)","[0,0]"]],
  ex:"🐛 원인: <code>training</code> 을 무시하고 언제나 <b>현재 배치</b>의 통계로 정규화합니다. 배치 크기가 1 이면 평균이 자기 자신이라 출력이 0 이 되고, 배치 구성에 따라 같은 입력의 예측이 달라집니다 — 서빙에서 재현이 안 되는 대표적 원인입니다.\n🔧 해결: 추론에서는 학습 중 모아 둔 <b>누적 평균·분산</b>을 씁니다. 프레임워크에서는 <code>model.eval()</code> 이 이 전환을 합니다.\n🛡 재발 방지: 배치 정규화는 <b>배치 안의 다른 표본에 의존</b>하는 드문 연산이라 여러 곳에서 새어 나갑니다 — 작은 배치, 배치 안 순서, 분산 학습에서의 통계 동기화. 배치 크기에 민감하다면 <b>레이어 정규화</b>나 그룹 정규화가 더 안전한 선택입니다." },

{ track:"dl", cat:"debug", k:"교차 엔트로피에 로그를 두 번 씌운다",
  q:"이미 <b>로그 확률</b>인 값과 정답 인덱스로 음의 로그 가능도를 구합니다. 결과는 소수 여섯째 자리까지 반올림합니다. 지금은 손실이 음수로 나오거나 <code>NaN</code> 이 됩니다.",
  src:"function nll(logProbs, target) {\n  return Math.round(-Math.log(logProbs[target]) * 1e6) / 1e6;\n}",
  sol:"function nll(logProbs, target) {\n  const v = logProbs[target];\n  if (v === undefined) return null;\n  return Math.round(-v * 1e6) / 1e6;\n}",
  tests:[["nll([-0.1, -2.3], 0)","0.1"],
         ["nll([-0.1, -2.3], 1)","2.3"],
         ["nll([0, -5], 0)","0"],
         ["nll([-1], 0)","1"]],
  edge:[["nll([-1, -1], 5) === null","true"],
        ["nll([-0.5, -0.5], 1)","0.5"]],
  ex:"🐛 원인: 입력이 <b>이미 로그</b>인데 또 <code>Math.log</code> 를 씌웠습니다. 로그 확률은 0 이하이므로 <code>log(음수)</code> 는 <code>NaN</code> 이고, 0 이면 <code>log(0) = -Infinity</code> 입니다. 이런 함수 이름 혼동(<code>softmax</code> 대 <code>log_softmax</code>, <code>CrossEntropyLoss</code> 대 <code>NLLLoss</code>)이 실전에서 가장 잦은 실수입니다.\n🔧 해결: 로그 확률은 <b>부호만 뒤집으면</b> 음의 로그 가능도입니다. 정답 인덱스가 범위 밖이면 상류 버그이므로 거절합니다.\n🛡 재발 방지: 손실 함수마다 '<b>무엇을 입력으로 받는가</b>'(로짓·확률·로그 확률)를 반드시 문서에서 확인하세요. 손실이 음수로 나오면 거의 언제나 이 혼동입니다 — 음의 로그 가능도는 <b>절대 음수가 될 수 없습니다</b>." },

{ track:"dl", cat:"debug", k:"He 초기화 분산이 팬아웃 기준이다",
  q:"ReLU 망의 <b>He 초기화</b> 표준편차를 구합니다. 식은 <code>√(2 / fanIn)</code> 입니다. 결과는 소수 여섯째 자리까지 반올림합니다. 지금은 층이 깊어질수록 활성값이 0 으로 사라집니다.",
  src:"function heStd(fanIn, fanOut) {\n  return Math.round(Math.sqrt(2 / fanOut) * 1e6) / 1e6;\n}",
  sol:"function heStd(fanIn, fanOut) {\n  if (!(fanIn > 0)) return null;\n  return Math.round(Math.sqrt(2 / fanIn) * 1e6) / 1e6;\n}",
  tests:[["heStd(2, 8)","1"],
         ["heStd(8, 2)","0.5"],
         ["heStd(200, 100)","0.1"],
         ["heStd(50, 50)","0.2"]],
  edge:[["heStd(0, 10) === null","true"],
        ["heStd(800, 1)","0.05"]],
  ex:"🐛 원인: He 초기화는 <b>순전파에서 활성값의 분산을 유지</b>하는 것이 목적이라 <code>fanIn</code> 이 기준입니다. <code>fanOut</code> 을 쓰면 층 모양에 따라 분산이 어긋나고, 층이 좁아지는 망에서는 활성값이 층마다 줄어 <b>깊은 층에서 신호가 사라집니다</b>. 정사각 층(<code>fanIn = fanOut</code>)만 테스트하면 통과합니다.\n🔧 해결: <code>√(2 / fanIn)</code> 입니다. 2 는 ReLU 가 <b>절반을 0 으로 만드는</b> 것을 보상하는 계수이고, tanh 계열이라면 Xavier(<code>1/fanIn</code> 또는 둘의 평균)를 씁니다.\n🛡 재발 방지: 초기화 버그는 '<b>학습이 잘 안 된다</b>' 는 모호한 증상으로만 나타납니다. 층별 활성값의 <b>표준편차를 찍어 보면</b> 층을 따라 커지는지 줄어드는지 한눈에 보입니다 — 초기화를 고칠 때 가장 빠른 진단 도구입니다." },

{ track:"dl", cat:"debug", k:"토큰 자르기가 뒤가 아니라 앞을 남긴다",
  q:"입력 토큰을 <b>최대 길이</b>에 맞춰 자릅니다. 대화 이력에서는 <b>최근 토큰</b>이 중요하므로 <b>뒤쪽</b>을 남깁니다. 지금은 모델이 최근 대화를 전혀 모릅니다.",
  src:"function truncate(tokens, maxLen) {\n  return tokens.slice(0, maxLen);\n}",
  sol:"function truncate(tokens, maxLen) {\n  if (maxLen <= 0) return [];\n  return tokens.length <= maxLen ? tokens.slice() : tokens.slice(tokens.length - maxLen);\n}",
  tests:[["truncate([1,2,3,4,5], 3)","[3,4,5]"],
         ["truncate([1,2], 5)","[1,2]"],
         ["truncate([1,2,3], 0)","[]"],
         ["truncate([1,2,3,4], 2)","[3,4]"]],
  edge:[["truncate([], 3)","[]"],
        ["truncate([9], 1)","[9]"]],
  ex:"🐛 원인: 앞에서 자르면 <b>가장 오래된 맥락만</b> 남습니다. 대화가 길어질수록 모델이 최근 질문을 못 보게 되어, '왜 갑자기 엉뚱한 답을 하지' 라는 증상이 <b>대화가 길어진 뒤에만</b> 나타납니다.\n🔧 해결: 뒤에서 <code>maxLen</code> 개를 남깁니다. <code>slice(-maxLen)</code> 은 <code>maxLen</code> 이 0 일 때 배열 전체가 되므로 <b>0 을 따로</b> 갈라야 합니다.\n🛡 재발 방지: 무엇을 버릴지는 <b>도메인 결정</b>입니다 — 대화는 최근이, 문서 요약은 앞부분이, RAG 컨텍스트는 관련도가 기준일 수 있습니다. 그리고 시스템 프롬프트처럼 <b>절대 잘리면 안 되는</b> 부분은 자르기 대상에서 빼고 예산을 따로 잡으세요." },

{ track:"dl", cat:"debug", k:"코사인 유사도가 정규화를 안 한다",
  q:"두 벡터의 <b>코사인 유사도</b>를 소수 여섯째 자리까지 구합니다. 영벡터가 섞이면 정의되지 않으므로 <code>null</code> 입니다. 지금은 값이 1 을 훌쩍 넘어 검색 순위가 <b>벡터 크기 순</b>이 됩니다.",
  src:"function cosSim(a, b) {\n  const dot = a.reduce((s, x, i) => s + x * b[i], 0);\n  return Math.round(dot * 1e6) / 1e6;\n}",
  sol:"function cosSim(a, b) {\n  if (a.length !== b.length) return null;\n  const dot = a.reduce((s, x, i) => s + x * b[i], 0);\n  const na = Math.sqrt(a.reduce((s, x) => s + x * x, 0));\n  const nb = Math.sqrt(b.reduce((s, x) => s + x * x, 0));\n  if (!na || !nb) return null;\n  return Math.round(dot / (na * nb) * 1e6) / 1e6;\n}",
  tests:[["cosSim([1, 0], [1, 0])","1"],
         ["cosSim([3, 0], [5, 0])","1"],
         ["cosSim([1, 0], [0, 1])","0"],
         ["cosSim([1, 1], [-1, -1])","-1"]],
  edge:[["cosSim([0, 0], [1, 1]) === null","true"],
        ["cosSim([1, 2], [1]) === null","true"]],
  ex:"🐛 원인: 내적만 쓰면 <b>벡터의 크기</b>가 그대로 반영됩니다. 임베딩의 노름은 문서 길이·빈도에 따라 제각각이라, 유사도 순위가 사실상 '긴 문서 순' 이 됩니다. 미리 정규화된 임베딩으로 테스트하면 두 값이 같아 통과합니다.\n🔧 해결: 두 노름의 곱으로 나눕니다. 영벡터는 방향이 없어 정의되지 않으므로 거절합니다.\n🛡 재발 방지: 임베딩을 <b>저장할 때 미리 정규화</b>해 두면 검색에서 내적만으로 코사인이 되고 계산도 빨라집니다. 대신 그 전제가 코드 전체에 걸리므로 <b>어디서 정규화했는지</b>를 한 곳에 적어 두세요 — 두 번 정규화하는 것은 무해하지만, 안 한 벡터가 하나 섞이면 순위가 조용히 망가집니다." },

{ track:"dl", cat:"debug", k:"누적 스텝에서 손실을 나누지 않는다",
  q:"기울기 누적에서 <b>스텝당 손실 기여분</b>을 구합니다. <code>accum</code> 스텝을 모아 한 번 갱신하므로 각 스텝의 손실을 <code>accum</code> 으로 나눠야 합니다. 결과는 소수 여섯째 자리까지 반올림합니다. 지금은 누적 스텝을 늘리면 <b>실효 학습률이 함께 커집니다</b>.",
  src:"function stepLoss(loss, accum) {\n  return Math.round(loss * 1e6) / 1e6;\n}",
  sol:"function stepLoss(loss, accum) {\n  if (!(accum >= 1)) return null;\n  return Math.round(loss / accum * 1e6) / 1e6;\n}",
  tests:[["stepLoss(4, 4)","1"],
         ["stepLoss(4, 1)","4"],
         ["stepLoss(1, 2)","0.5"],
         ["stepLoss(0, 8)","0"]],
  edge:[["stepLoss(4, 0) === null","true"],
        ["stepLoss(3, 3)","1"]],
  ex:"🐛 원인: 기울기 누적은 '<b>큰 배치를 여러 번에 나눠 계산</b>' 하는 기법입니다. 나누지 않으면 기울기가 <code>accum</code> 배로 쌓여, 실효 학습률이 그만큼 커집니다. 누적 스텝을 2 로 두는 순간 학습이 발산하는데 원인은 학습률처럼 보이지 않습니다.\n🔧 해결: 각 스텝의 손실을 <code>accum</code> 으로 나눕니다. 큰 배치 하나로 계산했을 때와 <b>같은 기울기</b>가 되는지가 검산 기준입니다.\n🛡 재발 방지: 기울기 누적은 손실 나누기 외에도 함정이 있습니다 — 마지막 자투리 배치, 배치 정규화 통계, 학습률 스케줄러를 <b>어느 시점에 진행시킬지</b>. '누적 없이 큰 배치' 와 결과가 같은지 작은 예제로 한 번 맞춰 보면 이 모두가 한 번에 검증됩니다." },

];
