/* 파이썬 실행형 디버깅 2차 — 고장난 코드를 받아 직접 고친다.
   검증 규칙 (하나라도 어기면 주입하지 않는다)
     1. sol 은 tests + edge 를 전부 통과해야 한다
     2. src 는 최소 하나의 tests 를 실패해야 한다
     3. src 는 문법 오류가 아니어야 한다 — 문법 오류 찾기는 디버깅이 아니다
     4. 트랙 안에서 함수 이름과 문제 줄기가 겹치지 않아야 한다 */
module.exports = [
{ k:"기본 인자는 한 번만 만들어진다", fn:"add_tag",
  q:"태그 목록에 값을 추가하는 함수인데, 목록을 넘기지 않고 두 번 호출하면 앞의 값이 남아 있습니다. 매번 새 목록에서 시작하도록 고치세요.",
  src:"def add_tag(tag, tags=[]):\n    tags.append(tag)\n    return tags",
  sol:"def add_tag(tag, tags=None):\n    if tags is None:\n        tags = []\n    tags.append(tag)\n    return tags",
  tests:[["add_tag('a')","['a']"],["[add_tag('a'), add_tag('b')]","[['a'], ['b']]"],["add_tag('c', ['x'])","['x', 'c']"],["[add_tag('p'), add_tag('q'), add_tag('r')]","[['p'], ['q'], ['r']]"]],
  edge:[["add_tag('z', [])","['z']"],["len(add_tag('k'))","1"]],
  ex:"🐛 원인: 기본 인자는 <b>함수 정의 시점에 한 번만</b> 평가됩니다. <code>tags=[]</code> 의 리스트는 모든 호출이 공유하는 <b>같은 객체</b>라, append 한 값이 다음 호출에 그대로 남습니다.\n🔧 해결: 기본값을 <code>None</code> 으로 두고 함수 안에서 새로 만듭니다. 이것이 파이썬의 표준 관용구입니다.\n🛡 재발 방지: 가변 객체(<code>list</code>·<code>dict</code>·<code>set</code>)를 기본 인자로 쓰지 마세요. 불변 객체(숫자·문자열·튜플·None)는 공유해도 안전합니다. 린터(<code>ruff B006</code>)가 이 패턴을 잡아 줍니다." },

{ k:"얕은 복사는 안쪽을 공유한다", fn:"clone_board",
  q:"2차원 격자를 복사해 한 칸만 바꾸는 함수인데, 원본의 같은 행도 함께 바뀝니다.",
  src:"def clone_board(board, r, c, v):\n    new = board.copy()\n    new[r] = new[r]\n    new[r][c] = v\n    return new",
  sol:"def clone_board(board, r, c, v):\n    new = [row.copy() for row in board]\n    new[r][c] = v\n    return new",
  tests:[["clone_board([[0,0],[0,0]], 0, 1, 9)","[[0,9],[0,0]]"],
         ["(lambda b: (clone_board(b,0,0,5), b))([[1,2],[3,4]])[1]","[[1,2],[3,4]]"],
         ["clone_board([[1]], 0, 0, 7)","[[7]]"],
         ["(lambda b: (clone_board(b,1,1,8), b[1][1]))([[0,0],[0,0]])[1]","0"]],
  edge:[["clone_board([[1,2,3]], 0, 2, 0)","[[1,2,0]]"],
        ["len(clone_board([[0],[0],[0]], 1, 0, 1))","3"]],
  ex:"🐛 원인: <code>list.copy()</code> 는 <b>얕은 복사</b>입니다. 바깥 리스트는 새로 만들지만 안쪽 행들은 <b>원본과 같은 객체</b>를 가리켜, <code>new[r][c] = v</code> 가 원본까지 바꿉니다.\n🔧 해결: 각 행도 복사합니다 — <code>[row.copy() for row in board]</code>. 더 깊은 중첩이면 <code>copy.deepcopy</code> 를 쓰지만 느립니다.\n🛡 재발 방지: <code>[[0]*3]*3</code> 은 같은 행을 <b>세 번 참조</b>하는 더 악명 높은 형태입니다 — 격자를 만들 때는 <code>[[0]*3 for _ in range(3)]</code> 를 쓰세요. 복사가 필요한지 판단하는 기준은 '<b>안쪽에 가변 객체가 있는가</b>' 입니다." },

{ k:"딕셔너리 순회 중 삭제", fn:"drop_empty",
  q:"값이 비어 있는 항목을 지우는 함수인데 RuntimeError 가 납니다.",
  src:"def drop_empty(d):\n    for k in d:\n        if not d[k]:\n            del d[k]\n    return d",
  sol:"def drop_empty(d):\n    for k in list(d):\n        if not d[k]:\n            del d[k]\n    return d",
  tests:[["drop_empty({'a': 1, 'b': '', 'c': 2})","{'a': 1, 'c': 2}"],
         ["drop_empty({'x': '', 'y': ''})","{}"],
         ["drop_empty({'a': 0, 'b': 1})","{'b': 1}"],
         ["drop_empty({'k': [1]})","{'k': [1]}"]],
  edge:[["drop_empty({})","{}"],["drop_empty({'a': None})","{}"]],
  ex:"🐛 원인: 딕셔너리를 순회하는 동안 크기가 바뀌면 파이썬이 <code>RuntimeError: dictionary changed size during iteration</code> 를 던집니다. 조용히 항목을 건너뛰는 것보다 낫다는 판단입니다.\n🔧 해결: <code>list(d)</code> 로 <b>키의 스냅샷</b>을 떠서 순회하면 순회 대상과 수정 대상이 분리됩니다. 또는 <code>{k: v for k, v in d.items() if v}</code> 로 새 딕셔너리를 만듭니다.\n🛡 재발 방지: 이 문제의 딕셔너리는 <b>원본을 제자리에서</b> 바꿉니다(반환값도 같은 객체). 호출자가 원본 보존을 기대한다면 새 딕셔너리를 만드는 쪽이 안전합니다 — 어느 쪽인지 함수 이름과 문서에 드러내세요." },

{ k:"is 로 값을 비교한다", fn:"is_not_found",
  q:"응답 코드가 404 인지 확인하는 함수인데, 계산이나 파싱으로 만들어진 404 는 True 가 나오지 않습니다.",
  src:"def is_not_found(code):\n    return code is 404",
  sol:"def is_not_found(code):\n    return code == 404",
  tests:[["is_not_found(int('404'))","True"],
         ["is_not_found(400 + 4)","True"],
         ["is_not_found(sum([400, 4]))","True"],
         ["is_not_found(200)","False"]],
  edge:[["is_not_found(404.0)","True"],
        ["is_not_found(405 - 1)","True"]],
  ex:"🐛 원인: <code>is</code> 는 <b>같은 객체인지</b>를 봅니다. CPython 은 −5~256 의 작은 정수만 미리 만들어 재사용하고, 그 밖의 값은 계산될 때마다 <b>새 객체</b>라 <code>is</code> 가 False 가 됩니다. 소스에 직접 쓴 404 는 상수 폴딩으로 우연히 통과할 수도 있어 더 헷갈립니다.\n🔧 해결: 값 비교는 <code>==</code> 입니다. 파이썬 3.8+ 는 이 실수에 <code>SyntaxWarning</code> 을 냅니다.\n🛡 재발 방지: <code>is</code> 가 정당한 곳은 <b>싱글턴 비교</b>뿐입니다 — <code>is None</code>, <code>is True</code>, <code>is not NotImplemented</code>. 이 문항의 테스트가 리터럴 대신 계산된 값만 쓰는 이유가 그것입니다 — <b>어떤 값으로 테스트하느냐</b>가 이 버그를 잡느냐 놓치느냐를 가릅니다." },

{ k:"list.sort() 는 None 을 돌려준다", fn:"top_two",
  q:"점수 목록에서 가장 큰 두 값을 돌려주는 함수인데 TypeError 가 납니다. 원본 목록도 바뀌지 않아야 합니다.",
  src:"def top_two(xs):\n    ordered = xs.sort(reverse=True)\n    return ordered[:2]",
  sol:"def top_two(xs):\n    ordered = sorted(xs, reverse=True)\n    return ordered[:2]",
  tests:[["top_two([3, 9, 1, 7])","[9, 7]"],
         ["top_two([5])","[5]"],
         ["(lambda v: (top_two(v), v))([1, 3, 2])[1]","[1, 3, 2]"],
         ["top_two([2, 2, 2])","[2, 2]"]],
  edge:[["top_two([])","[]"],
        ["top_two([-1, -5])","[-1, -5]"]],
  ex:"🐛 원인: <b>제자리에서 바꾸는 메서드는 <code>None</code> 을 돌려주는</b> 것이 파이썬의 규칙입니다. <code>list.sort()</code>·<code>reverse()</code>·<code>append()</code> 가 모두 그렇습니다. 반환값을 받아 쓰면 <code>None[:2]</code> 가 되어 TypeError 입니다.\n🔧 해결: 새 리스트가 필요하면 <code>sorted(xs, ...)</code> 를 씁니다. 원본도 보존되어 호출자를 놀라게 하지 않습니다.\n🛡 재발 방지: 이 규칙은 '<b>바꿨는가, 만들었는가</b>' 를 반환값으로 구분하려는 의도입니다 — <code>sort</code>/<code>sorted</code>, <code>reverse</code>/<code>reversed</code>, <code>x.append(v)</code>/<code>x + [v]</code> 의 쌍을 함께 외워 두면 헷갈리지 않습니다." },

{ k:"finally 의 return 이 결과를 덮는다", fn:"read_value",
  q:"자원을 정리하면서 값을 돌려주는 함수인데, 무엇을 넣어도 항상 -1 이 나옵니다. 정리는 그대로 하되 원래 값이 반환되도록 고치세요.",
  src:"def read_value(src):\n    log = []\n    try:\n        return src['v']\n    finally:\n        log.append('closed')\n        return -1",
  sol:"def read_value(src):\n    log = []\n    try:\n        return src['v']\n    finally:\n        log.append('closed')",
  tests:[["read_value({'v': 7})","7"],
         ["read_value({'v': 0})","0"],
         ["[read_value({'v': 1}), read_value({'v': 2})]","[1, 2]"],
         ["read_value({'v': 'ok'})","'ok'"]],
  edge:[["read_value({'v': None})","None"],
        ["[read_value({'v': i}) for i in range(3)]","[0, 1, 2]"]],
  ex:"🐛 원인: <code>finally</code> 안의 <code>return</code> 은 <b>try 의 반환값을 덮어씁니다</b>. 더 위험한 것은 <b>진행 중이던 예외까지 삼킨다</b>는 점입니다 — <code>src['v']</code> 가 KeyError 를 던져도 finally 의 return 이 실행되면서 예외가 사라지고, 호출자는 정상 반환으로 착각합니다.\n🔧 해결: finally 에서는 <b>정리만</b> 합니다. 값을 바꿔야 한다면 try/except 로 명시적으로 잡으세요.\n🛡 재발 방지: <code>break</code>·<code>continue</code> 도 finally 안에서는 같은 효과를 냅니다. 정리는 <code>with</code> 문(컨텍스트 매니저)에 맡기는 것이 가장 안전합니다 — 정리 코드가 반환 경로와 아예 섞이지 않습니다." },

{ k:"부동소수점 동등 비교", fn:"is_total",
  q:"금액 합계가 목표액과 같은지 확인하는 함수인데, 0.1 을 세 번 더한 값이 0.3 과 같지 않다고 나옵니다.",
  src:"def is_total(parts, target):\n    return sum(parts) == target",
  sol:"def is_total(parts, target):\n    return abs(sum(parts) - target) < 1e-9",
  tests:[["is_total([0.1, 0.1, 0.1], 0.3)","True"],
         ["is_total([0.1, 0.2], 0.3)","True"],
         ["is_total([1.0, 2.0], 3.0)","True"],
         ["is_total([0.1, 0.1], 0.3)","False"]],
  edge:[["is_total([], 0)","True"],
        ["is_total([1e-12], 0)","True"]],
  ex:"🐛 원인: 2진 부동소수점은 0.1 을 정확히 표현하지 못합니다. <code>0.1+0.2</code> 는 0.30000000000000004 라 <code>==</code> 가 False 입니다 — 계산 순서만 달라져도 마지막 비트가 흔들립니다.\n🔧 해결: <b>허용 오차(epsilon)</b> 안에 있으면 같다고 봅니다. 표준 라이브러리의 <code>math.isclose</code> 는 상대·절대 오차를 함께 다뤄 더 견고합니다.\n🛡 재발 방지: 돈은 애초에 float 로 다루지 마세요 — <code>Decimal</code> 이나 <b>정수 최소 단위</b>(원·센트)가 정답입니다. epsilon 비교는 값의 크기에 따라 적절한 값이 달라져(1e-9 는 큰 수에서 너무 엄격) 근본 해결이 아닙니다." },

{ k:"클래스 변수는 인스턴스가 공유한다", fn:"make_carts",
  q:"장바구니 객체를 만드는데, 한 장바구니에 담은 상품이 다른 장바구니에도 보입니다.",
  src:"class Cart:\n    items = []\n\n    def add(self, x):\n        self.items.append(x)\n        return self\n\n\ndef make_carts(a_items, b_items):\n    a, b = Cart(), Cart()\n    for x in a_items:\n        a.add(x)\n    for x in b_items:\n        b.add(x)\n    return [a.items, b.items]",
  sol:"class Cart:\n    def __init__(self):\n        self.items = []\n\n    def add(self, x):\n        self.items.append(x)\n        return self\n\n\ndef make_carts(a_items, b_items):\n    a, b = Cart(), Cart()\n    for x in a_items:\n        a.add(x)\n    for x in b_items:\n        b.add(x)\n    return [a.items, b.items]",
  tests:[["make_carts(['사과'], ['배'])","[['사과'], ['배']]"],
         ["make_carts([], ['x'])","[[], ['x']]"],
         ["make_carts(['a','b'], [])","[['a', 'b'], []]"],
         ["make_carts([], [])","[[], []]"]],
  edge:[["len(make_carts(['a'], ['b'])[0])","1"],
        ["make_carts(['1'], ['1'])","[['1'], ['1']]"]],
  ex:"🐛 원인: 클래스 본문에 쓴 <code>items = []</code> 는 <b>클래스 변수</b>라 모든 인스턴스가 <b>하나의 리스트</b>를 공유합니다. <code>self.items.append()</code> 는 대입이 아니라 <b>공유 객체의 수정</b>이라 모두에게 보입니다.\n🔧 해결: 인스턴스마다 상태를 가지려면 <code>__init__</code> 에서 <code>self.items = []</code> 로 만듭니다.\n🛡 재발 방지: 헷갈리는 이유는 <code>self.count += 1</code> 같은 <b>대입</b>은 인스턴스 속성을 새로 만들어(공유되지 않아) 정상처럼 보이기 때문입니다 — 가변 객체의 <b>수정</b>만 공유됩니다. 이 비대칭이 함정입니다. dataclass 의 <code>field(default_factory=list)</code> 도 같은 문제를 막는 장치입니다." },

{ k:"제너레이터는 한 번만 소비된다", fn:"summarize",
  q:"조건에 맞는 값들의 개수와 합을 함께 구하는 함수인데, 합이 항상 0 으로 나옵니다.",
  src:"def summarize(xs):\n    picked = (x for x in xs if x > 0)\n    return {'n': len(list(picked)), 'total': sum(picked)}",
  sol:"def summarize(xs):\n    picked = [x for x in xs if x > 0]\n    return {'n': len(picked), 'total': sum(picked)}",
  tests:[["summarize([1, -2, 3])","{'n': 2, 'total': 4}"],
         ["summarize([5])","{'n': 1, 'total': 5}"],
         ["summarize([-1, -2])","{'n': 0, 'total': 0}"],
         ["summarize([1, 2, 3, 4])","{'n': 4, 'total': 10}"]],
  edge:[["summarize([])","{'n': 0, 'total': 0}"],
        ["summarize([0, 1])","{'n': 1, 'total': 1}"]],
  ex:"🐛 원인: 제너레이터는 <b>한 번 소비되면 소진</b>됩니다. <code>list(picked)</code> 가 끝까지 읽어 버려 뒤이은 <code>sum(picked)</code> 은 <b>빈 것</b>을 더해 0이 됩니다 — 예외도 안 나서 원인 찾기가 어렵습니다.\n🔧 해결: 두 번 이상 순회해야 하면 <b>리스트로 실체화</b>합니다. 리스트 컴프리헨션의 대괄호 하나 차이입니다.\n🛡 재발 방지: 제너레이터의 장점은 <b>메모리를 안 쓰는 것</b>이라, 큰 데이터를 한 번만 훑을 때 씁니다. '<b>몇 번 순회할 것인가</b>' 로 리스트와 제너레이터를 고르세요. <code>itertools.tee</code> 로 복제할 수도 있지만 결국 메모리에 버퍼링됩니다." },

{ k:"정렬 키와 비교 함수", fn:"rank_by",
  q:"점수는 내림차순, 같으면 이름 오름차순으로 정렬해야 하는데 이름 순서가 뒤집혀 나옵니다.",
  src:"def rank_by(rows):\n    return [r['name'] for r in sorted(rows, key=lambda r: (r['score'], r['name']), reverse=True)]",
  sol:"def rank_by(rows):\n    return [r['name'] for r in sorted(rows, key=lambda r: (-r['score'], r['name']))]",
  tests:[["rank_by([{'name':'b','score':10},{'name':'a','score':10}])","['a', 'b']"],
         ["rank_by([{'name':'a','score':1},{'name':'b','score':5}])","['b', 'a']"],
         ["rank_by([{'name':'c','score':3},{'name':'a','score':3},{'name':'b','score':9}])","['b', 'a', 'c']"],
         ["rank_by([{'name':'x','score':0}])","['x']"]],
  edge:[["rank_by([])","[]"],
        ["rank_by([{'name':'a','score':2},{'name':'a','score':1}])","['a', 'a']"]],
  ex:"🐛 원인: <code>reverse=True</code> 는 <b>전체 정렬 결과를 뒤집습니다</b> — 점수뿐 아니라 2차 기준인 이름까지 내림차순이 됩니다. 두 기준의 방향이 다를 때는 쓸 수 없습니다.\n🔧 해결: 내림차순으로 원하는 <b>숫자 키에만 음수</b>를 붙입니다 — <code>(-score, name)</code>. 문자열은 음수를 붙일 수 없으니 이 방법이 안 통합니다.\n🛡 재발 방지: 문자열 키를 반대 방향으로 정렬해야 한다면, 파이썬의 정렬이 <b>안정적</b>(stable)이라는 성질을 이용해 <b>덜 중요한 기준부터 차례로</b> 정렬합니다 — <code>sorted(rows, key=name)</code> 뒤에 <code>sorted(..., key=score, reverse=True)</code>. 이것이 다중 기준 정렬의 일반해입니다." },

{ k:"zip 은 짧은 쪽에서 조용히 끊긴다", fn:"to_row",
  q:"헤더와 값을 짝지어 딕셔너리를 만드는 함수인데, 값이 하나 빠진 CSV 줄을 넣어도 오류 없이 짧은 딕셔너리가 나옵니다. 개수가 다르면 None 을 돌려주도록 고치세요.",
  src:"def to_row(headers, values):\n    return dict(zip(headers, values))",
  sol:"def to_row(headers, values):\n    if len(headers) != len(values):\n        return None\n    return dict(zip(headers, values))",
  tests:[["to_row(['a','b'], [1, 2])","{'a': 1, 'b': 2}"],
         ["to_row(['a','b','c'], [1, 2])","None"],
         ["to_row(['a'], [1, 2])","None"],
         ["to_row([], [])","{}"]],
  edge:[["to_row(['x'], [9])","{'x': 9}"],
        ["to_row(['a','b'], [])","None"]],
  ex:"🐛 원인: <code>zip</code> 은 <b>짧은 쪽에서 조용히 멈춥니다</b>. CSV 한 줄에 컬럼이 빠져 있어도 예외 없이 딕셔너리가 만들어지고, 없는 키는 나중에 <b>전혀 다른 곳에서</b> KeyError 로 터집니다 — 원인 지점과 증상 지점이 멀어지는 최악의 형태입니다.\n🔧 해결: 길이를 <b>명시적으로 검사</b>합니다. 파이썬 3.10+ 라면 <code>zip(a, b, strict=True)</code> 한 줄로 같은 검사를 얻습니다(대신 ValueError 를 던집니다).\n🛡 재발 방지: 데이터가 <b>바깥에서 들어오는 경계</b>에서는 '조용한 성공' 이 가장 위험합니다. 짧은 쪽에 맞추는 것이 의도라면 코드에 그렇게 적고, 아니라면 즉시 실패시키세요 — 이 결정을 안 하면 언어는 항상 전자로 동작합니다." },

{ k:"round 는 은행가 반올림이다", fn:"to_won",
  q:"금액을 원 단위로 반올림하는 함수인데, 0.5 로 끝나는 값이 어떤 것은 올라가고 어떤 것은 내려갑니다. 0.5 는 항상 올라가도록 고치세요.",
  src:"def to_won(x):\n    return round(x)",
  sol:"from decimal import Decimal, ROUND_HALF_UP\n\n\ndef to_won(x):\n    return int(Decimal(str(x)).quantize(Decimal('1'), rounding=ROUND_HALF_UP))",
  tests:[["to_won(2.5)","3"],
         ["to_won(0.5)","1"],
         ["to_won(1.5)","2"],
         ["to_won(4.5)","5"]],
  edge:[["to_won(2.4)","2"],
        ["to_won(3)","3"]],
  ex:"🐛 원인: 파이썬의 <code>round</code> 는 <b>은행가 반올림</b>(banker's rounding)입니다 — 정확히 0.5 일 때 <b>짝수 쪽으로</b> 갑니다. 그래서 <code>round(0.5)=0</code>, <code>round(1.5)=2</code>, <code>round(2.5)=2</code> 로 방향이 오락가락합니다.\n🔧 해결: 규칙을 명시적으로 정합니다 — <code>Decimal</code> 에 <code>ROUND_HALF_UP</code> 을 지정하면 언제나 0.5 가 올라갑니다. <code>Decimal(str(x))</code> 로 만들어야 float 오차가 섞여 들어오지 않습니다.\n🛡 재발 방지: 은행가 반올림은 버그가 아니라 <b>의도된 설계</b>입니다 — 많은 값을 더할 때 오차가 한쪽으로 쌓이지 않게 합니다. 문제는 <b>사람의 기대와 다르다</b>는 것이라, 회계·표시용 반올림은 규칙을 코드에 적어 두어야 합니다." },
];
