/* 코딩 연습 디버깅 13 — 자바스크립트에서 매일 밟는 함정들.
   계약
     1. src 는 문법 오류가 아니고 TODO 도 없다. 작은 입력에서는 통과하기도 한다.
     2. src 는 tests 중 최소 하나를 실패한다.
     3. sol 은 tests + edge 를 전부 통과한다.
     4. 전부 결정적 — 시각·난수는 쓰지 않는다.
   검증:  node ver_dbgjs.cjs ./dbg_code.cjs */
module.exports = [

/* ── 1교시 · 값이 조용히 바뀌는 자리 ───────────────────────────────── */

{ track:"code", cat:"debug", k:"map 이 넘겨 주는 두 번째 인자",
  q:"문자열 배열을 <b>정수 배열</b>로 바꿉니다. 원소가 하나일 때는 잘 되는데, 두 개부터는 <b>두 번째 원소부터 전부</b> 이상한 값이 됩니다.",
  src:"function toInts(list) {\n  return list.map(parseInt);\n}",
  sol:"function toInts(list) {\n  return list.map(s => Number.parseInt(s, 10));\n}",
  tests:[["toInts(['1','2','3'])","[1,2,3]"],
         ["toInts(['7','8'])","[7,8]"],
         ["toInts(['10'])","[10]"],
         ["toInts([])","[]"]],
  edge:[["toInts(['0','0'])","[0,0]"],
        ["toInts(['-5','+6'])","[-5,6]"]],
  ex:"🐛 원인: <code>map</code> 은 콜백에 <b>값·인덱스·배열</b> 세 개를 넘깁니다. <code>parseInt</code> 는 두 번째 인자를 <b>진법</b>으로 읽으므로 <code>parseInt('2', 1)</code> 처럼 불리고, 1 진법은 없으니 <code>NaN</code> 이 됩니다. 원소가 하나면 인덱스가 0 이라 '진법 생략' 으로 처리돼 우연히 통과합니다.\n🔧 해결: 함수 이름을 그대로 넘기지 말고 <b>필요한 인자만 받는 화살표 함수</b>로 감쌉니다. 진법 10 도 반드시 적습니다.\n🛡 재발 방지: <code>map</code>·<code>forEach</code>·<code>filter</code> 에 <b>인자를 두 개 이상 받는 함수</b>를 그대로 넘기는 것은 언제나 의심하세요. <code>['1','2'].map(Number)</code> 처럼 인자를 하나만 쓰는 함수는 안전하지만, 그 구분을 매번 따지느니 <b>화살표로 감싸는 것을 기본</b>으로 두는 편이 낫습니다." },

{ track:"code", cat:"debug", k:"0 과 빈 문자열이 기본값에 먹힌다",
  q:"설정 객체를 받아 <b>빠진 값에 기본값</b>을 채웁니다. 대부분 잘 되는데, 사용자가 일부러 <code>0</code> 이나 <b>빈 문자열</b>을 넣으면 그 값이 기본값으로 덮입니다.",
  src:"function settings(o) {\n  return {\n    retries: o.retries || 3,\n    tag: o.tag || 'none',\n    debug: o.debug || false,\n  };\n}",
  sol:"function settings(o) {\n  return {\n    retries: o.retries ?? 3,\n    tag: o.tag ?? 'none',\n    debug: o.debug ?? false,\n  };\n}",
  tests:[["settings({ retries: 0 })","{retries:0, tag:'none', debug:false}"],
         ["settings({ tag: '' })","{retries:3, tag:'', debug:false}"],
         ["settings({})","{retries:3, tag:'none', debug:false}"],
         ["settings({ retries: 5, tag: 'x', debug: true })","{retries:5, tag:'x', debug:true}"]],
  edge:[["settings({ debug: false })","{retries:3, tag:'none', debug:false}"],
        ["settings({ retries: 0, tag: '', debug: true })","{retries:0, tag:'', debug:true}"]],
  ex:"🐛 원인: <code>||</code> 는 '값이 없으면' 이 아니라 '<b>거짓 같으면</b>' 오른쪽을 씁니다. <code>0</code>·<code>''</code>·<code>false</code>·<code>NaN</code> 은 모두 거짓 같은 값이므로, <b>사용자가 일부러 넣은 값</b>이 기본값에 덮입니다. '재시도 0 번' 이 '재시도 3 번' 이 되는 식이라 사고가 큽니다.\n🔧 해결: <code>??</code> 는 <code>null</code> 과 <code>undefined</code> <b>둘만</b> 걸러 냅니다. 기본값 채우기의 뜻과 정확히 일치합니다.\n🛡 재발 방지: 기본값에는 <code>??</code>, 참·거짓 판단에만 <code>||</code> 라고 규칙을 정하세요. 특히 <b>숫자·문자열·불리언 설정값</b>에 <code>||</code> 를 쓰고 있다면 거의 예외 없이 버그입니다. 테스트에는 '<b>의미 있는 0</b>' 과 '<b>의미 있는 빈 문자열</b>' 을 반드시 넣으세요." },

{ track:"code", cat:"debug", k:"reduce 에 초기값을 주지 않았다",
  q:"장바구니 항목들의 <b>가격 합계</b>를 구합니다. 항목이 두 개 이상이면 이상한 문자열이 나오고, 항목이 하나면 객체가, <b>빈 배열이면 예외</b>가 납니다.",
  src:"function total(items) {\n  return items.reduce((s, it) => s + it.price);\n}",
  sol:"function total(items) {\n  return items.reduce((s, it) => s + it.price, 0);\n}",
  tests:[["total([{price:10},{price:5}])","15"],
         ["total([{price:7}])","7"],
         ["total([])","0"],
         ["total([{price:1},{price:2},{price:3}])","6"]],
  edge:[["total([{price:0}])","0"],
        ["total([{price:-5},{price:5}])","0"]],
  ex:"🐛 원인: 초기값을 안 주면 <code>reduce</code> 는 <b>첫 원소를 누적값으로</b> 쓰고 두 번째부터 훑습니다. 여기서는 누적값이 <b>객체</b>가 되어 <code>{...} + 5</code> 가 문자열 이어붙이기로 흘러갑니다. 원소가 하나면 콜백이 아예 안 불려 객체가 그대로 나오고, 빈 배열이면 <code>TypeError</code> 입니다.\n🔧 해결: 초기값 <code>0</code> 을 줍니다. 그러면 누적값의 <b>타입이 처음부터 고정</b>되고 빈 배열도 자연스럽게 0 이 됩니다.\n🛡 재발 방지: <code>reduce</code> 의 초기값은 '선택 인자' 가 아니라 <b>누적값의 타입 선언</b>이라고 생각하세요. 누적값과 원소의 타입이 다르면(숫자 ← 객체) 초기값은 <b>필수</b>입니다. 그리고 집계 함수의 첫 테스트는 언제나 <b>빈 입력</b>이어야 합니다." },

{ track:"code", cat:"debug", k:"짝수 개일 때 중앙값은 두 값의 평균이다",
  q:"숫자 목록의 <b>중앙값</b>을 구합니다(빈 목록은 <code>null</code>). 개수가 홀수면 맞는데, <b>짝수</b>면 가운데 두 값 중 <b>뒤쪽 값</b>이 그대로 나옵니다.",
  src:"function median(a) {\n  const s = a.slice().sort((x, y) => x - y);\n  return s[Math.floor(s.length / 2)];\n}",
  sol:"function median(a) {\n  if (a.length === 0) return null;\n  const s = a.slice().sort((x, y) => x - y);\n  const m = s.length >> 1;\n  return s.length % 2 ? s[m] : (s[m - 1] + s[m]) / 2;\n}",
  tests:[["median([1,2,3,4])","2.5"],
         ["median([1,2])","1.5"],
         ["median([3,1,2])","2"],
         ["median([5])","5"]],
  edge:[["median([])","null"],
        ["median([2,2,2,2])","2"]],
  ex:"🐛 원인: 가운데 <b>자리 하나</b>를 집는 코드는 개수가 홀수일 때만 맞습니다. 짝수면 가운데가 두 칸이고 중앙값은 그 <b>평균</b>인데, <code>Math.floor(n/2)</code> 는 언제나 뒤쪽 칸을 가리킵니다. 그리고 빈 배열에서는 <code>undefined</code> 가 새어 나갑니다.\n🔧 해결: 홀수·짝수를 갈라 짝수면 <code>(s[m-1] + s[m]) / 2</code> 를 돌려주고, 빈 입력은 맨 앞에서 계약대로 <code>null</code> 로 잘라 냅니다.\n🛡 재발 방지: 통계 함수는 <b>홀수·짝수·빈 입력</b> 세 가지를 고정 테스트로 두세요. 예제 데이터가 대개 홀수 개(3개, 5개)라서 짝수 버그는 실제 데이터가 들어온 뒤에야 드러납니다. 정렬 비교 함수를 빠뜨려 문자열로 견주는 실수도 함께 확인하세요." },

{ track:"code", cat:"debug", k:"글자 수는 code unit 개수가 아니다",
  q:"긴 문자열을 <code>n</code> <b>글자</b>까지만 남기고 <code>…</code> 을 붙입니다. 한글·영문은 맞는데, <b>이모지</b>가 섞이면 잘린 자리에서 글자가 깨지고 개수도 모자랍니다.",
  src:"function truncate(s, n) {\n  return s.length <= n ? s : s.slice(0, n) + '…';\n}",
  sol:"function truncate(s, n) {\n  const cp = [...s];\n  return cp.length <= n ? s : cp.slice(0, n).join('') + '…';\n}",
  tests:[["truncate('👍👍👍', 2)","'👍👍…'"],
         ["truncate('👍👍', 2)","'👍👍'"],
         ["truncate('안녕하세요', 3)","'안녕하…'"],
         ["truncate('abc', 5)","'abc'"]],
  edge:[["truncate('', 3)","''"],
        ["truncate('a👍b', 2)","'a👍…'"]],
  ex:"🐛 원인: 자바스크립트의 <code>length</code> 와 <code>slice</code> 는 <b>UTF-16 코드 단위</b>를 셉니다. 이모지 대부분은 코드 단위 <b>두 칸</b>을 차지하는 대리 쌍이라, <code>slice(0, 2)</code> 는 이모지 한 개만 남기거나 <b>쌍의 절반</b>을 잘라 깨진 글자를 만듭니다.\n🔧 해결: 스프레드(<code>[...s]</code>)는 문자열을 <b>코드 포인트 단위</b>로 나눕니다. 세는 것도 자르는 것도 그 배열로 하면 이모지가 쪼개지지 않습니다.\n🛡 재발 방지: 사용자에게 보여 줄 글자 수(<b>미리보기·요약·글자 수 제한</b>)에는 <code>.length</code> 를 쓰지 마세요. 국기나 가족 이모지처럼 여러 코드 포인트가 <b>한 글자로 보이는</b> 경우까지 맞추려면 <code>Intl.Segmenter</code> 가 필요합니다 — 테스트에 이모지 하나만 넣어도 이 층위 차이가 즉시 드러납니다." },

{ track:"code", cat:"debug", k:"replace 는 첫 번째 하나만 바꾼다",
  q:"제목을 URL 에 쓸 수 있는 <b>슬러그</b>로 바꿉니다. 앞뒤 공백을 떼고 소문자로 만든 뒤 <b>모든 공백</b>을 <code>-</code> 로 바꿔야 하는데, 단어가 세 개 이상이면 <b>뒤쪽 공백이 그대로</b> 남습니다.",
  src:"function slug(s) {\n  return s.trim().toLowerCase().replace(' ', '-');\n}",
  sol:"function slug(s) {\n  return s.trim().toLowerCase().replace(/ /g, '-');\n}",
  tests:[["slug('Hello World Again')","'hello-world-again'"],
         ["slug('x  y')","'x--y'"],
         ["slug('  A B  ')","'a-b'"],
         ["slug('one')","'one'"]],
  edge:[["slug('')","''"],
        ["slug(' Q ')","'q'"]],
  ex:"🐛 원인: <code>replace</code> 에 <b>문자열</b>을 주면 <b>처음 만난 하나</b>만 바꿉니다. 단어가 두 개인 예제(<code>'A B'</code>)에서는 공백이 하나뿐이라 통과하고, 세 개부터 조용히 어긋납니다.\n🔧 해결: <code>g</code> 플래그를 붙인 정규식(<code>/ /g</code>)이나 <code>replaceAll</code> 을 씁니다. 둘 다 <b>모든 자리</b>를 바꿉니다.\n🛡 재발 방지: '전부 바꾼다' 는 의도라면 코드에도 그 의도가 보여야 합니다. <code>replace</code> 를 볼 때마다 '한 번인가 전부인가' 를 묻고, 테스트에는 <b>바꿀 대상이 두 개 이상 나오는 입력</b>을 반드시 넣으세요 — 하나짜리 예제만으로는 영원히 통과합니다." },

{ track:"code", cat:"debug", k:"사용자 입력을 정규식으로 그대로 쓴다",
  q:"어떤 <b>글자 그대로</b>가 본문에 몇 번 나오는지 셉니다. 보통 글자는 맞는데, 찾을 말에 <code>.</code> 이 있으면 터무니없이 큰 수가 나오고 <code>+</code> 가 있으면 <b>예외</b>가 납니다.",
  src:"function countOccurrences(text, needle) {\n  return (text.match(new RegExp(needle, 'g')) || []).length;\n}",
  sol:"function countOccurrences(text, needle) {\n  if (needle === '') return 0;\n  return text.split(needle).length - 1;\n}",
  tests:[["countOccurrences('a.b.c', '.')","2"],
         ["countOccurrences('a+b', '+')","1"],
         ["countOccurrences('abc', 'b')","1"],
         ["countOccurrences('aaa', 'a')","3"]],
  edge:[["countOccurrences('', 'x')","0"],
        ["countOccurrences('a(b)c', '(b)')","1"]],
  ex:"🐛 원인: <code>new RegExp(needle)</code> 는 사용자가 준 글자를 <b>패턴 문법으로</b> 읽습니다. <code>.</code> 은 '아무 글자' 라 전부 세어 버리고, <code>+</code> 는 앞에 붙을 것이 없어 <b>SyntaxError</b> 입니다. 사용자 입력을 코드로 해석한다는 점에서 SQL 인젝션과 같은 종류의 실수입니다.\n🔧 해결: 정규식이 필요 없는 문제입니다. <code>split(needle).length - 1</code> 은 글자 그대로 나눈 조각 수에서 하나를 뺀 값이라 정확히 등장 횟수입니다. 빈 문자열만 계약대로 앞에서 막습니다.\n🛡 재발 방지: 정규식이 꼭 필요하다면 <b>메타문자를 이스케이프</b>한 뒤에 넣으세요(<code>needle.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&amp;')</code>). 더 좋은 습관은 '<b>사용자 입력을 문법으로 해석하는 자리</b>' 를 목록으로 적어 두고 각각 문자열 API 로 바꿀 수 있는지 먼저 묻는 것입니다." },

/* ── 2교시 · 공유되고 남아 있는 상태 ───────────────────────────────── */

{ track:"code", cat:"debug", k:"정렬이 부른 쪽의 배열을 바꾼다",
  q:"점수 배열을 <b>내림차순으로 정렬한 새 배열</b>을 돌려줍니다. 돌려주는 값은 맞는데, 함수를 부르고 나면 <b>넘긴 배열까지 순서가 바뀌어</b> 있습니다.",
  src:"function ranked(scores) {\n  return scores.sort((a, b) => b - a);\n}",
  sol:"function ranked(scores) {\n  return scores.slice().sort((a, b) => b - a);\n}",
  tests:[["(function(){ const a = [3,1,2]; ranked(a); return a; })()","[3,1,2]"],
         ["(function(){ const a = [1,2]; const r = ranked(a); return [r, a]; })()","[[2,1],[1,2]]"],
         ["ranked([3,1,2])","[3,2,1]"],
         ["ranked([])","[]"]],
  edge:[["ranked([5])","[5]"],
        ["(function(){ const a = []; ranked(a); return a.length; })()","0"]],
  ex:"🐛 원인: <code>Array.prototype.sort</code> 는 <b>제자리 정렬</b>입니다. 새 배열을 만드는 것이 아니라 <b>받은 배열 자체</b>를 뒤섞고 그 배열을 그대로 돌려줍니다. 반환값만 확인하는 테스트로는 절대 잡히지 않습니다.\n🔧 해결: <code>slice()</code>(또는 <code>[...scores]</code>, <code>toSorted()</code>)로 <b>먼저 복사</b>한 뒤 정렬합니다.\n🛡 재발 방지: <code>sort</code>·<code>reverse</code>·<code>splice</code>·<code>push</code>·<code>Object.assign(base, ...)</code> 는 전부 <b>인자를 고칩니다</b>. 공유되는 설정 객체나 캐시된 목록에 이 함수를 쓰면 첫 호출의 흔적이 이후 전부에 남습니다. 순수 함수를 테스트할 때는 반환값과 함께 '<b>원본이 그대로인가</b>' 를 반드시 못 박으세요." },

{ track:"code", cat:"debug", k:"펼침 복사는 한 겹만 복사한다",
  q:"사용자 객체에 태그를 하나 더한 <b>새 객체</b>를 만듭니다. 새 객체는 맞게 나오는데, <b>원래 객체의 태그 목록에도</b> 같은 태그가 붙어 있습니다.",
  src:"function updateTags(user, tag) {\n  const copy = { ...user };\n  copy.tags.push(tag);\n  return copy;\n}",
  sol:"function updateTags(user, tag) {\n  return { ...user, tags: [...user.tags, tag] };\n}",
  tests:[["(function(){ const u = {name:'a', tags:['x']}; const c = updateTags(u, 'y'); return [c.tags, u.tags]; })()","[['x','y'],['x']]"],
         ["(function(){ const u = {tags:['p']}; updateTags(u, 'q'); return u.tags.length; })()","1"],
         ["updateTags({name:'a', tags:[]}, 'z').tags","['z']"],
         ["updateTags({tags:['a']}, 'b').tags.length","2"]],
  edge:[["(function(){ const u = {tags:['a']}; const c = updateTags(u, 'b'); return c.tags === u.tags; })()","false"],
        ["updateTags({tags:['a'], n:1}, 'b').n","1"]],
  ex:"🐛 원인: <code>{ ...user }</code> 는 <b>한 겹만</b> 복사합니다. <code>tags</code> 칸에는 <b>같은 배열을 가리키는 참조</b>가 그대로 들어가므로, 복사본에 <code>push</code> 하면 원본의 배열이 늘어납니다. 새 객체만 확인하는 테스트는 전부 통과합니다.\n🔧 해결: <b>바꿀 중첩 값도 함께 새로 만듭니다</b>. <code>{ ...user, tags: [...user.tags, tag] }</code> 는 겉과 안 두 겹을 모두 갈아 끼우면서 나머지 필드는 그대로 옮깁니다.\n🛡 재발 방지: 불변 갱신은 '<b>바뀌는 경로 위의 모든 층</b>' 을 새로 만들어야 합니다. 중첩이 깊어지면 <code>structuredClone</code> 이나 불변 라이브러리를 쓰고, 테스트에는 <code>c.tags === u.tags</code> 처럼 <b>참조가 갈라졌는지</b>를 직접 확인하는 줄을 넣으세요." },

{ track:"code", cat:"debug", k:"훑는 도중에 지우면 한 칸을 건너뛴다",
  q:"배열에서 <b>홀수를 모두 지운</b> 새 배열을 돌려줍니다. 홀수가 흩어져 있으면 맞는데, <b>홀수가 이웃해 있으면</b> 일부가 남습니다.",
  src:"function dropOdds(a) {\n  const out = a.slice();\n  for (let i = 0; i < out.length; i += 1) {\n    if (out[i] % 2 === 1) out.splice(i, 1);\n  }\n  return out;\n}",
  sol:"function dropOdds(a) {\n  return a.filter(v => v % 2 === 0);\n}",
  tests:[["dropOdds([1,3,2])","[2]"],
         ["dropOdds([1,1,1])","[]"],
         ["dropOdds([1,2,3])","[2]"],
         ["dropOdds([2,4])","[2,4]"]],
  edge:[["dropOdds([])","[]"],
        ["dropOdds([0,1])","[0]"]],
  ex:"🐛 원인: <code>splice</code> 로 한 칸을 빼면 뒤의 원소들이 <b>한 칸씩 앞으로 당겨집니다</b>. 그런데 <code>i</code> 는 그대로 1 만큼 늘어나므로, 방금 당겨져 온 원소를 <b>보지 않고 지나칩니다</b>. 지울 것이 이웃해 있을 때만 드러나므로 예제에서는 통과합니다.\n🔧 해결: 지우면서 훑지 말고 <b>남길 것만 골라 새 배열을 만듭니다</b> — <code>filter</code> 한 줄이면 됩니다.\n🛡 재발 방지: 꼭 제자리에서 지워야 한다면 <b>뒤에서 앞으로</b> 훑거나 지운 뒤 <code>i</code> 를 되돌려야 합니다. 하지만 대부분의 경우 '거르기(filter)·모으기(map)·접기(reduce)' 로 바꾸는 편이 짧고 안전합니다 — <b>훑는 대상과 고치는 대상이 같으면</b> 언제나 의심하세요." },

{ track:"code", cat:"debug", k:"빈 객체는 사실 비어 있지 않다",
  q:"단어 목록에서 <b>두 번 이상 나온 단어</b>를 사전순으로 모읍니다. 보통 단어는 맞는데, <code>'constructor'</code>·<code>'toString'</code> 같은 단어는 <b>아무리 반복해도</b> 결과에 안 들어옵니다.",
  src:"function repeated(words) {\n  const c = {};\n  for (const w of words) c[w] = (c[w] || 0) + 1;\n  return Object.keys(c).filter(k => c[k] > 1).sort();\n}",
  sol:"function repeated(words) {\n  const c = new Map();\n  for (const w of words) c.set(w, (c.get(w) || 0) + 1);\n  return [...c.keys()].filter(k => c.get(k) > 1).sort();\n}",
  tests:[["repeated(['a','a','constructor','constructor'])","['a','constructor']"],
         ["repeated(['toString','toString','z'])","['toString']"],
         ["repeated(['b','b'])","['b']"],
         ["repeated(['x','y'])","[]"]],
  edge:[["repeated([])","[]"],
        ["repeated(['q','q','q'])","['q']"]],
  ex:"🐛 원인: <code>{}</code> 로 만든 객체는 <code>Object.prototype</code> 에서 <code>constructor</code>·<code>toString</code>·<code>hasOwnProperty</code> 같은 이름을 <b>물려받습니다</b>. <code>c['toString'] || 0</code> 은 물려받은 <b>함수</b>(참 같은 값)를 집어서 <code>함수 + 1</code> 이라는 문자열을 만들고, 그 뒤 <code>&gt; 1</code> 비교가 언제나 거짓이 됩니다.\n🔧 해결: 열쇠가 <b>바깥에서 들어오는 값</b>이면 <code>Map</code> 을 씁니다. <code>Map</code> 은 프로토타입 사슬과 무관하고 열쇠 순서도 넣은 순서로 보존합니다.\n🛡 재발 방지: 객체를 사전처럼 쓸 수밖에 없다면 <code>Object.create(null)</code> 로 만들거나 <code>Object.hasOwn(c, w)</code> 로 확인하세요. 사용자·파일·네트워크에서 온 이름을 <b>객체 키로 삼는 자리</b>는 프로토타입 오염 취약점의 입구이기도 하므로 목록으로 관리할 값어치가 있습니다." },

{ track:"code", cat:"debug", k:"g 플래그를 붙인 정규식은 자리를 기억한다",
  q:"문자열에 <b>숫자가 들어 있는지</b> 확인합니다. 처음 한 번은 맞는데, <b>같은 문자열을 다시 물으면</b> 답이 뒤집힙니다.",
  src:"const HAS = /\\d+/g;\nfunction hasNumber(s) {\n  return HAS.test(s);\n}",
  sol:"function hasNumber(s) {\n  return /\\d/.test(s);\n}",
  tests:[["hasNumber('a1')","true"],
         ["hasNumber('a1')","true"],
         ["hasNumber('xyz')","false"],
         ["hasNumber('7')","true"]],
  edge:[["hasNumber('')","false"],
        ["hasNumber('12ab34')","true"]],
  ex:"🐛 원인: <code>g</code> 플래그가 붙은 정규식 객체는 <b><code>lastIndex</code> 라는 상태</b>를 들고 있습니다. <code>test</code> 는 그 자리부터 찾고 성공하면 자리를 뒤로 옮기므로, <b>같은 정규식 객체를 다시 쓰면</b> 앞부분을 건너뛰고 실패합니다. 실패하면 자리가 0 으로 되돌아가 결과가 <b>참·거짓을 번갈아</b> 냅니다.\n🔧 해결: 존재 여부만 물을 때는 <code>g</code> 가 필요 없습니다. 플래그를 떼거나, 매번 새 정규식 리터럴을 쓰면 상태 자체가 생기지 않습니다.\n🛡 재발 방지: <b>모듈 최상단에 만들어 둔 정규식</b>에 <code>g</code>·<code>y</code> 가 붙어 있으면 그것은 <b>공유되는 가변 상태</b>입니다. 여러 번 훑을 목적이라면 쓰기 전에 <code>re.lastIndex = 0</code> 으로 되돌리거나 <code>matchAll</code>·<code>String.prototype.match</code> 처럼 상태를 남기지 않는 API 를 쓰세요." },

{ track:"code", cat:"debug", k:"메서드를 변수에 담으면 this 를 잃는다",
  q:"카운터 객체입니다. <code>inc()</code> 를 직접 부르면 잘 세는데, <code>run(n)</code> 으로 <b>여러 번 부르면</b> 결과가 전부 이상한 값이고 <b>객체의 값도 안 늘어납니다</b>.",
  src:"function makeCounter() {\n  return {\n    n: 0,\n    inc() { this.n += 1; return this.n; },\n    run(times) {\n      const f = this.inc;\n      const out = [];\n      for (let i = 0; i < times; i += 1) out.push(f());\n      return out;\n    },\n  };\n}",
  sol:"function makeCounter() {\n  return {\n    n: 0,\n    inc() { this.n += 1; return this.n; },\n    run(times) {\n      const out = [];\n      for (let i = 0; i < times; i += 1) out.push(this.inc());\n      return out;\n    },\n  };\n}",
  tests:[["makeCounter().run(3)","[1,2,3]"],
         ["makeCounter().run(1)","[1]"],
         ["(function(){ const c = makeCounter(); c.run(2); return c.n; })()","2"],
         ["makeCounter().run(0)","[]"]],
  edge:[["(function(){ const c = makeCounter(); c.inc(); return c.run(1); })()","[2]"],
        ["makeCounter().n","0"]],
  ex:"🐛 원인: <code>const f = this.inc</code> 는 <b>함수만</b> 꺼내 옵니다. 자바스크립트에서 <code>this</code> 는 함수가 <b>어떻게 불렸는지</b>로 정해지므로, <code>f()</code> 처럼 그냥 부르면 객체와의 연결이 끊깁니다. 그래서 <code>this.n</code> 이 엉뚱한 곳을 가리켜 <code>NaN</code> 이 나오고 원래 객체의 값은 그대로입니다.\n🔧 해결: 점 표기로 <b>객체에 붙여서</b> 부릅니다 — <code>this.inc()</code>. 꼭 꺼내야 한다면 <code>this.inc.bind(this)</code> 나 <code>() =&gt; this.inc()</code> 로 감싸세요.\n🛡 재발 방지: 메서드를 <b>콜백으로 넘기는 자리</b>(<code>arr.forEach(obj.method)</code>, <code>setTimeout(obj.method)</code>, 이벤트 핸들러)가 이 버그의 단골입니다. 클래스 필드에 화살표 함수로 정의하거나 넘길 때 감싸는 것을 습관으로 두고, 테스트에는 <b>호출 뒤 객체 상태</b>를 확인하는 줄을 넣으세요." },

];
