/* AI 엔지니어링 디버깅 13 — 파이프라인이 도는데 답만 조금씩 어긋나는 자리.
   계약
     1. src 는 문법 오류가 아니고 TODO 도 없다. 작은 입력에서는 통과하기도 한다.
     2. src 는 tests 중 최소 하나를 실패한다.
     3. sol 은 tests + edge 를 전부 통과한다.
     4. 전부 결정적 — 모델 호출·난수·시각은 쓰지 않는다.
   검증:  node ver_dbgjs.cjs ./dbg_ai.cjs */
module.exports = [

/* ── 1교시 · 모델에 넣기 전에 어긋나는 것 ──────────────────────────── */

{ track:"ai", cat:"debug", k:"마지막 청크가 색인에서 빠진다",
  q:"문서를 <code>size</code> 글자씩 <code>overlap</code> 만큼 겹쳐 자릅니다. 길이가 딱 떨어지면 맞는데, <b>남는 꼬리</b>가 있으면 그 부분이 통째로 색인에서 빠지고 문서가 <code>size</code> 보다 짧으면 <b>조각이 하나도</b> 안 나옵니다.",
  src:"function chunk(text, size, overlap) {\n  const out = [];\n  const step = size - overlap;\n  for (let i = 0; i + size <= text.length; i += step) out.push(text.slice(i, i + size));\n  return out;\n}",
  sol:"function chunk(text, size, overlap) {\n  const out = [];\n  const step = Math.max(1, size - overlap);\n  for (let i = 0; i < text.length; i += step) {\n    out.push(text.slice(i, i + size));\n    if (i + size >= text.length) break;\n  }\n  return out;\n}",
  tests:[["chunk('abcdef', 4, 1)","['abcd','def']"],
         ["chunk('abc', 5, 2)","['abc']"],
         ["chunk('abcdefg', 3, 1)","['abc','cde','efg']"],
         ["chunk('', 3, 1)","[]"]],
  edge:[["chunk('ab', 2, 0)","['ab']"],
        ["chunk('abcd', 2, 0)","['ab','cd']"]],
  ex:"원인: 반복 조건이 <code>i + size &lt;= text.length</code> 라 <b>온전한 크기의 조각만</b> 만듭니다. 꼬리가 <code>size</code> 보다 짧으면 그대로 버려지고, 문서 전체가 <code>size</code> 보다 짧으면 결과가 빈 배열입니다. 색인에서 조용히 사라진 문단은 <b>검색이 안 되는 이유조차 남기지 않습니다</b>.\n원인이 하나 더 있습니다 — <code>overlap &gt;= size</code> 면 <code>step</code> 이 0 이하가 되어 같은 자리를 무한히 돕니다.\n해결: 시작 자리가 <b>문서 안에 있는 동안</b> 돌면서 꼬리도 담고, 끝에 닿으면 멈춥니다. <code>step</code> 은 최소 1 로 묶어 둡니다.\n재발 방지: 청킹은 '<b>모든 글자가 적어도 한 조각에 들어간다</b>' 는 성질로 검사하세요. 조각들을 모아 원문을 덮는지 확인하는 성질 테스트 하나면 꼬리 누락·중복·무한 루프가 한꺼번에 잡힙니다." },

{ track:"ai", cat:"debug", k:"대화 기록을 오래된 쪽부터 채운다",
  q:"토큰 예산 <code>budget</code> 에서 응답용으로 <code>reserve</code> 를 떼고, 남는 자리에 <b>최근 메시지부터</b> 채워 <b>시간 순서대로</b> 돌려줍니다. 그런데 대화가 길어지면 <b>방금 한 말이 빠지고</b> 맨 처음 인사말만 남습니다.",
  src:"function fitHistory(msgs, budget, reserve) {\n  const out = [];\n  let used = 0;\n  for (const m of msgs) {\n    if (used + m.n > budget - reserve) break;\n    used += m.n;\n    out.push(m.id);\n  }\n  return out;\n}",
  sol:"function fitHistory(msgs, budget, reserve) {\n  const room = budget - reserve;\n  const out = [];\n  let used = 0;\n  for (let i = msgs.length - 1; i >= 0; i -= 1) {\n    if (used + msgs[i].n > room) break;\n    used += msgs[i].n;\n    out.unshift(msgs[i].id);\n  }\n  return out;\n}",
  tests:[["fitHistory([{id:'a',n:50},{id:'b',n:50},{id:'c',n:50}], 200, 100)","['b','c']"],
         ["fitHistory([{id:'a',n:30},{id:'b',n:30}], 100, 50)","['b']"],
         ["fitHistory([{id:'a',n:10}], 100, 50)","['a']"],
         ["fitHistory([{id:'a',n:200}], 100, 50)","[]"]],
  edge:[["fitHistory([], 100, 10)","[]"],
        ["fitHistory([{id:'x',n:0}], 10, 10)","['x']"]],
  ex:"원인: 앞에서부터 채우면 <b>가장 오래된 메시지</b>가 자리를 선점합니다. 대화 맥락에서 가장 중요한 것은 <b>최근 몇 턴</b>인데, 예산이 꽉 차면 그 부분이 잘려 나가 모델이 방금 한 이야기를 모릅니다. 대화가 짧을 때는 전부 들어가므로 티가 안 납니다.\n해결: <b>뒤에서부터</b> 담고 <code>unshift</code> 로 시간 순서를 되돌립니다. 남는 자리는 <code>budget - reserve</code> 이며, 이 <code>reserve</code> 를 빼먹으면 응답이 중간에 잘립니다.\n재발 방지: 컨텍스트 예산은 <b>시스템 프롬프트 + 검색 결과 + 대화 기록 + 응답 여유</b> 네 몫으로 나눠 적어 두세요. 그리고 '<b>어느 것부터 버릴 것인가</b>' 는 설계 결정이므로 코드가 아니라 문서에 먼저 적혀 있어야 합니다 — 대개 오래된 턴을 먼저 버리고 요약으로 갈음합니다." },

{ track:"ai", cat:"debug", k:"임베딩 캐시에 모델 이름이 빠졌다",
  q:"임베딩 캐시입니다. 없으면 <code>null</code> 을 돌려줍니다. 한 모델만 쓸 때는 잘 도는데, <b>임베딩 모델을 바꾸고 나서</b> 검색 품질이 무너집니다.",
  src:"function makeCache() {\n  const store = new Map();\n  return {\n    get(model, text) { return store.has(text) ? store.get(text) : null; },\n    put(model, text, vec) { store.set(text, vec); },\n  };\n}",
  sol:"function makeCache() {\n  const store = new Map();\n  const key = (model, text) => model + '\\u0000' + text;\n  return {\n    get(model, text) { const k = key(model, text); return store.has(k) ? store.get(k) : null; },\n    put(model, text, vec) { store.set(key(model, text), vec); },\n  };\n}",
  tests:[["(function(){ const c = makeCache(); c.put('m1','hi',[1,0]); return c.get('m2','hi'); })()","null"],
         ["(function(){ const c = makeCache(); c.put('m1','a',[1]); c.put('m2','a',[2]); return [c.get('m1','a'), c.get('m2','a')]; })()","[[1],[2]]"],
         ["(function(){ const c = makeCache(); c.put('m1','hi',[1,0]); return c.get('m1','hi'); })()","[1,0]"],
         ["(function(){ const c = makeCache(); return c.get('m1','x'); })()","null"]],
  edge:[["(function(){ const c = makeCache(); c.put('m1','',[9]); return c.get('m1',''); })()","[9]"],
        ["(function(){ const c = makeCache(); c.put('m1','a',[1]); return c.get('m1','b'); })()","null"]],
  ex:"원인: 캐시 열쇠가 <b>텍스트만</b>입니다. 모델을 바꾸면 벡터 공간 자체가 달라지는데, 같은 문장이라는 이유로 <b>옛 모델이 만든 벡터</b>가 그대로 나옵니다. 새로 만든 질의 벡터와 좌표계가 달라 유사도가 뒤죽박죽이 되고, 캐시가 채워져 있을수록 더 조용히 망가집니다.\n해결: 열쇠에 <b>모델 이름</b>을 넣습니다. 이름과 본문 사이에는 본문에 나올 수 없는 구분자(<code>\\u0000</code>)를 두어 <code>'m1' + 'a-b'</code> 와 <code>'m1-a' + 'b'</code> 가 겹치지 않게 합니다.\n재발 방지: 캐시 열쇠에는 <b>결과를 달라지게 하는 모든 것</b>이 들어가야 합니다 — 모델·버전·차원·정규화 방식·전처리 규칙. 모델을 바꿀 때 캐시를 통째로 비우는 절차를 배포 문서에 적어 두고, 저장할 때 <b>차원 수</b>도 함께 기록해 두면 사고를 조기에 잡습니다." },

{ track:"ai", cat:"debug", k:"같은 설정인데 캐시 열쇠가 달라진다",
  q:"호출 파라미터로 <b>캐시 열쇠</b>를 만듭니다. 같은 설정이면 같은 열쇠여야 하는데, <b>적는 순서만 바꿔도</b> 다른 열쇠가 나와 캐시가 거의 안 맞습니다.",
  src:"function cacheKey(params) {\n  return Object.keys(params).map(k => k + '=' + params[k]).join('&');\n}",
  sol:"function cacheKey(params) {\n  return Object.keys(params).sort().map(k => k + '=' + params[k]).join('&');\n}",
  tests:[["cacheKey({ b: 2, a: 1 })","'a=1&b=2'"],
         ["cacheKey({ t: 0.7, model: 'm' })","'model=m&t=0.7'"],
         ["cacheKey({ a: 1, b: 2 })","'a=1&b=2'"],
         ["cacheKey({})","''"]],
  edge:[["cacheKey({ z: 1 })","'z=1'"],
        ["cacheKey({ b: 1, a: 1, c: 1 })","'a=1&b=1&c=1'"]],
  ex:"원인: <code>Object.keys</code> 는 <b>넣은 순서</b>를 그대로 돌려줍니다. 같은 설정이라도 객체를 만든 자리가 다르면 열쇠 문자열이 달라져, 캐시 적중률이 떨어지고 실험 결과의 <b>재현성</b>도 깨집니다. 파라미터가 하나뿐인 예제에서는 절대 드러나지 않습니다.\n해결: 열쇠 이름을 <b>정렬</b>한 뒤 이어 붙입니다. 그러면 같은 설정이 언제나 같은 문자열이 됩니다.\n재발 방지: '같은 입력이면 같은 열쇠' 는 <b>정규화 규칙</b>이 있어야 보장됩니다 — 이름 정렬, 숫자 표기 통일(<code>0.70</code> 과 <code>0.7</code>), 기본값을 명시로 채우기까지 정해 두세요. 실험 추적에서도 같은 규칙으로 지문을 만들면 '<b>어제와 같은 설정인가</b>' 를 눈이 아니라 문자열로 답할 수 있습니다." },

{ track:"ai", cat:"debug", k:"입력과 출력의 단가가 다르다",
  q:"호출 <b>비용</b>을 계산합니다. 단가는 1,000 토큰 기준이고 입력과 출력이 <b>서로 다릅니다</b>. 그런데 출력이 긴 요청일수록 청구서와 계산이 크게 벌어집니다.",
  src:"function cost(inTok, outTok, priceIn, priceOut) {\n  return ((inTok + outTok) * priceIn) / 1000;\n}",
  sol:"function cost(inTok, outTok, priceIn, priceOut) {\n  return (inTok * priceIn + outTok * priceOut) / 1000;\n}",
  tests:[["cost(1000, 1000, 1, 3)","4"],
         ["cost(0, 1000, 1, 3)","3"],
         ["cost(1500, 500, 2, 4)","5"],
         ["cost(1000, 0, 2, 5)","2"]],
  edge:[["cost(0, 0, 1, 3)","0"],
        ["cost(500, 500, 2, 2)","2"]],
  ex:"원인: 토큰을 <b>먼저 더한 뒤</b> 입력 단가 하나로 곱했습니다. 출력 단가가 보통 입력의 서너 배이므로, 요약처럼 입력이 긴 작업에서는 오차가 작지만 <b>생성이 긴 작업</b>에서는 실제 비용의 절반도 안 되는 값이 나옵니다. 입력·출력 단가가 같은 모델로 시험하면 통과합니다.\n해결: 각각 제 단가로 곱한 뒤 더합니다.\n재발 방지: 비용 계산은 <b>단가가 다른 축이 몇 개인지</b>부터 세세요 — 입력·출력·캐시 적중 입력·이미지·툴 호출까지 축이 늘어납니다. 축마다 단가를 표로 두고 계산은 그 표를 훑는 한 줄로 쓰면, 새 축이 생겨도 계산식을 고칠 일이 없습니다. 그리고 <b>단가가 서로 다른 값</b>으로 테스트하세요." },

{ track:"ai", cat:"debug", k:"길이가 긴 벡터가 언제나 이긴다",
  q:"두 임베딩의 <b>코사인 유사도</b>를 구합니다(영 벡터면 0). 정규화된 벡터끼리는 맞는데, <b>길이가 제각각인</b> 벡터가 섞이면 긴 벡터가 무조건 상위에 옵니다.",
  src:"function sim(a, b) {\n  let d = 0;\n  for (let i = 0; i < a.length; i += 1) d += a[i] * b[i];\n  return d;\n}",
  sol:"function sim(a, b) {\n  let d = 0, na = 0, nb = 0;\n  for (let i = 0; i < a.length; i += 1) {\n    d += a[i] * b[i];\n    na += a[i] * a[i];\n    nb += b[i] * b[i];\n  }\n  if (na === 0 || nb === 0) return 0;\n  return d / (Math.sqrt(na) * Math.sqrt(nb));\n}",
  tests:[["sim([2,0], [1,0])","1"],
         ["sim([3,4], [3,4])","1"],
         ["sim([1,0], [1,0])","1"],
         ["sim([1,0], [0,1])","0"]],
  edge:[["sim([0,0], [1,0])","0"],
        ["sim([1,0], [-1,0])","-1"]],
  ex:"원인: 내적만 구하고 <b>길이로 나누지 않았습니다</b>. 코사인 유사도는 두 벡터가 이루는 <b>각도</b>만 보는 값인데, 내적은 각도에 <b>두 길이를 곱한</b> 값입니다. 그래서 방향이 어중간해도 길이만 길면 점수가 높게 나옵니다. 모두 정규화된 벡터라면 길이가 1 이라 우연히 같은 값이 됩니다.\n해결: 내적을 두 벡터의 길이 곱으로 나눕니다. 영 벡터는 각도가 정의되지 않으므로 계약대로 0 을 돌려줍니다.\n재발 방지: 벡터 저장소에 넣기 전에 <b>정규화해 두면</b> 내적이 곧 코사인이라 계산도 빨라지고 이런 실수 자체가 사라집니다. 다만 '저장할 때 정규화한다' 는 규칙을 지키지 않은 경로가 하나라도 생기면 다시 무너지므로, 색인 시점에 <b>길이가 1 인지 검사</b>하는 줄을 두세요." },

{ track:"ai", cat:"debug", k:"먼저 자르고 나서 거른다",
  q:"검색 결과에서 점수가 <code>q</code> <b>이상</b>인 문서를 <b>점수 높은 순서로 최대 <code>k</code> 개</b> 돌려줍니다. 결과가 이미 점수순으로 오면 맞는데, <b>순서가 섞여 오면</b> 좋은 문서가 사라지고 개수도 모자랍니다.",
  src:"function retrieve(docs, q, k) {\n  return docs.slice(0, k).filter(d => d.score >= q).map(d => d.id);\n}",
  sol:"function retrieve(docs, q, k) {\n  return docs.filter(d => d.score >= q)\n    .sort((a, b) => b.score - a.score)\n    .slice(0, k)\n    .map(d => d.id);\n}",
  tests:[["retrieve([{id:'a',score:0.1},{id:'b',score:0.9},{id:'c',score:0.8}], 0.5, 2)","['b','c']"],
         ["retrieve([{id:'a',score:0.5},{id:'b',score:0.6}], 0.5, 1)","['b']"],
         ["retrieve([{id:'a',score:0.9},{id:'b',score:0.8}], 0.5, 2)","['a','b']"],
         ["retrieve([{id:'a',score:0.1}], 0.5, 3)","[]"]],
  edge:[["retrieve([], 0.5, 3)","[]"],
        ["retrieve([{id:'a',score:0.5}], 0.5, 1)","['a']"]],
  ex:"원인: <b>자르기 → 거르기</b> 순서라 앞쪽 <code>k</code> 개 안에 든 문서만 후보가 됩니다. 그 안에서 임계값에 걸린 것이 빠지면 결과가 <code>k</code> 개보다 적어지고, 뒤쪽에 있던 <b>더 좋은 문서</b>는 아예 보지도 않습니다. 벡터 검색이 이미 정렬해서 주면 티가 안 나지만, 하이브리드 검색이나 필터를 거친 결과는 순서가 섞여 옵니다.\n해결: <b>거르고 → 줄 세우고 → 자릅니다</b>. 이 순서는 바꿀 수 없습니다.\n재발 방지: 파이프라인 단계의 순서 자체가 계약입니다. '<b>몇 개를 돌려주는가</b>' 와 '<b>무엇을 돌려주는가</b>' 를 각각 테스트로 못 박고, 입력 순서를 일부러 섞은 케이스를 넣으세요 — 상류가 정렬을 보장한다고 믿는 순간 그 보장이 사라지는 날 조용히 틀립니다." },

/* ── 2교시 · 모델이 준 것을 다루다 어긋나는 것 ─────────────────────── */

{ track:"ai", cat:"debug", k:"누적 확률을 넘기 직전에 멈춘다",
  q:"확률이 높은 토큰부터 담다가 <b>누적이 <code>p</code> 이상이 되면 그 토큰까지</b> 담고 멈춥니다(top-p). 그런데 <b>가장 큰 확률 하나가 이미 <code>p</code> 를 넘으면</b> 후보가 아예 비고, 마지막 토큰도 자주 빠집니다.",
  src:"function nucleus(probs, p) {\n  const idx = probs.map((v, i) => i).sort((a, b) => probs[b] - probs[a]);\n  const out = [];\n  let cum = 0;\n  for (const i of idx) {\n    cum += probs[i];\n    if (cum > p) break;\n    out.push(i);\n  }\n  return out;\n}",
  sol:"function nucleus(probs, p) {\n  const idx = probs.map((v, i) => i).sort((a, b) => probs[b] - probs[a]);\n  const out = [];\n  let cum = 0;\n  for (const i of idx) {\n    out.push(i);\n    cum += probs[i];\n    if (cum >= p) break;\n  }\n  return out;\n}",
  tests:[["nucleus([0.6,0.4], 0.5)","[0]"],
         ["nucleus([1.0], 0.9)","[0]"],
         ["nucleus([0.5,0.3,0.2], 0.9)","[0,1,2]"],
         ["nucleus([0.5,0.5], 1)","[0,1]"]],
  edge:[["nucleus([], 0.9)","[]"],
        ["nucleus([0.2,0.8], 0.5)","[1]"]],
  ex:"원인: 누적값을 <b>더한 뒤 검사하고, 통과해야 담습니다</b>. 그래서 임계를 넘긴 토큰은 담기지 않는데, 그 토큰이 바로 <b>확률 대부분을 차지하는 토큰</b>일 수 있습니다. 확률 1 짜리 결정적 분포에서는 후보가 통째로 비어 샘플링이 불가능해집니다.\n해결: <b>담고 → 더하고 → 검사</b> 순서로 바꿉니다. 'p 를 처음 넘기는 토큰까지 포함' 이라는 정의가 그대로 코드가 됩니다.\n재발 방지: 누적 임계 알고리즘은 <b>경계에 있는 원소를 포함하는가</b>가 정의의 전부입니다. 확률이 하나뿐인 분포, 임계와 정확히 같아지는 분포, 임계보다 첫 확률이 큰 분포 — 이 세 가지를 고정 테스트로 두면 순서 실수가 즉시 드러납니다." },

{ track:"ai", cat:"debug", k:"소프트맥스가 큰 점수에서 NaN 이 된다",
  q:"점수 배열을 <b>확률로</b> 바꿉니다. 작은 값에서는 잘 도는데, 실제 로짓처럼 <b>수백 단위</b>가 들어오면 전부 <code>NaN</code> 이 나옵니다.",
  src:"function softmax(xs) {\n  const e = xs.map(v => Math.exp(v));\n  const s = e.reduce((a, b) => a + b, 0);\n  return e.map(v => v / s);\n}",
  sol:"function softmax(xs) {\n  const m = Math.max(...xs);\n  const e = xs.map(v => Math.exp(v - m));\n  const s = e.reduce((a, b) => a + b, 0);\n  return e.map(v => v / s);\n}",
  tests:[["softmax([1000,1000])","[0.5,0.5]"],
         ["softmax([800,800,800])","[1/3,1/3,1/3]"],
         ["softmax([0,0])","[0.5,0.5]"],
         ["softmax([0])","[1]"]],
  edge:[["softmax([])","[]"],
        ["softmax([1,1])","[0.5,0.5]"]],
  ex:"원인: <code>Math.exp(800)</code> 은 배정밀도 부동소수의 표현 범위를 넘겨 <code>Infinity</code> 가 됩니다. 그다음 <code>Infinity / Infinity</code> 는 <code>NaN</code> 입니다. 값이 대략 710 을 넘으면 무너지는데, 교과서 예제의 <code>[1, 2, 3]</code> 같은 값으로는 절대 드러나지 않습니다.\n해결: 모든 값에서 <b>최댓값을 빼고</b> 지수를 취합니다. 소프트맥스는 입력에 같은 상수를 더하거나 빼도 결과가 <b>정확히 같으므로</b> 이는 근사가 아니라 항등식입니다. 지수의 최댓값이 <code>e⁰ = 1</code> 로 고정돼 넘칠 일이 없습니다.\n재발 방지: 지수·로그가 들어간 수식은 '<b>큰 수를 만든 뒤 줄이기</b>' 대신 '<b>작게 유지하며 계산하기</b>' 로 적으세요. 확률의 곱은 로그 합으로, 로그 합의 지수는 log-sum-exp 로 바꿉니다. 테스트에는 <b>실제 스케일의 값</b>을 반드시 하나 넣으세요." },

{ track:"ai", cat:"debug", k:"응답에 코드 펜스가 붙어 온다",
  q:"모델 응답에서 <b>JSON 을 꺼냅니다</b>(못 꺼내면 <code>null</code>). 순수 JSON 만 올 때는 잘 되는데, 모델이 <code>```json</code> 으로 감싸거나 <b>앞에 한마디 붙이면</b> 전부 실패합니다.",
  src:"function parseJson(reply) {\n  try {\n    return JSON.parse(reply);\n  } catch (e) {\n    return null;\n  }\n}",
  sol:"function parseJson(reply) {\n  const fence = reply.match(/```(?:json)?\\s*([\\s\\S]*?)```/);\n  const body = fence ? fence[1] : reply;\n  const a = body.indexOf('{'), z = body.lastIndexOf('}');\n  if (a < 0 || z < a) return null;\n  try {\n    return JSON.parse(body.slice(a, z + 1));\n  } catch (e) {\n    return null;\n  }\n}",
  tests:[["parseJson('```json\\n{\"a\":1}\\n```')","{a:1}"],
         ["parseJson('여기 있습니다: {\"a\":1}')","{a:1}"],
         ["parseJson('{\"a\":1}')","{a:1}"],
         ["parseJson('설명만 있고 JSON 은 없음')","null"]],
  edge:[["parseJson('')","null"],
        ["parseJson('```\\n{\"b\":[1,2]}\\n```')","{b:[1,2]}"]],
  ex:"원인: 모델의 출력은 <b>문자열이지 JSON 이 아닙니다</b>. '오직 JSON 만 답하라' 고 적어도 코드 펜스나 '알겠습니다' 한마디가 붙는 일이 흔하고, 그때마다 <code>JSON.parse</code> 는 예외를 던집니다. 실패를 <code>null</code> 로 삼키고 있어 <b>왜 비었는지</b>도 안 남습니다.\n해결: 펜스가 있으면 안쪽을 꺼내고, 없으면 첫 <code>{</code> 부터 마지막 <code>}</code> 까지를 잘라 파싱합니다. 그래도 실패하면 계약대로 <code>null</code> 입니다.\n재발 방지: 가능하면 <b>구조화 출력</b>(스키마 강제·함수 호출)을 써서 파싱 자체를 없애세요. 그럴 수 없다면 파싱을 <b>관대하게</b> 만들되 결과는 <b>엄격하게</b> 검증하고(스키마 검사), 실패한 원문을 로그에 남겨 프롬프트를 고칠 근거로 삼으세요." },

{ track:"ai", cat:"debug", k:"스트리밍 조각을 도착 순서대로 잇는다",
  q:"스트리밍으로 받은 조각들을 <b>본래 순서대로</b>(<code>i</code> 오름차순) 이어 붙입니다. 조각이 순서대로 도착하면 맞는데, <b>순서가 뒤섞여 오면</b> 글이 뒤죽박죽이 됩니다.",
  src:"function assemble(events) {\n  return events.map(e => e.text).join('');\n}",
  sol:"function assemble(events) {\n  return events.slice().sort((a, b) => a.i - b.i).map(e => e.text).join('');\n}",
  tests:[["assemble([{i:1,text:'b'},{i:0,text:'a'}])","'ab'"],
         ["assemble([{i:2,text:'c'},{i:0,text:'a'},{i:1,text:'b'}])","'abc'"],
         ["assemble([{i:0,text:'a'},{i:1,text:'b'}])","'ab'"],
         ["assemble([])","''"]],
  edge:[["assemble([{i:0,text:''}])","''"],
        ["assemble([{i:10,text:'y'},{i:2,text:'x'}])","'xy'"]],
  ex:"원인: 조각에 <b>순번이 붙어 있다는 것</b> 자체가 '도착 순서를 믿지 말라' 는 신호입니다. 그런데 코드는 받은 배열 순서 그대로 잇습니다. 한 연결로 순차 수신할 때는 우연히 맞지만, 재시도·병렬 수집·큐를 거치면 순서가 섞입니다.\n해결: <code>i</code> 로 <b>정렬한 뒤</b> 잇습니다. 원본 배열을 건드리지 않도록 <code>slice()</code> 로 복사한 뒤 정렬하세요 — <code>sort</code> 는 제자리 정렬입니다.\n재발 방지: 데이터에 <b>순번·타임스탬프·오프셋</b>이 있으면 그것이 곧 정렬 기준이고, 없으면 왜 없어도 되는지 근거를 적어야 합니다. 조각이 <b>빠졌는지</b>도 함께 확인하세요 — 순번이 0..n-1 로 이어지지 않으면 조립 결과는 조용히 틀린 글이 됩니다." },

{ track:"ai", cat:"debug", k:"정답 비교를 글자 그대로 한다",
  q:"모델 답과 정답이 <b>같은지</b> 봅니다. 앞뒤 공백·대소문자·<b>중간 공백 개수</b>·<b>끝의 마침표</b>는 무시해야 합니다. 그런데 사람이 보면 맞는 답이 자꾸 오답으로 집계됩니다.",
  src:"function exactMatch(pred, gold) {\n  return pred.trim() === gold.trim();\n}",
  sol:"function exactMatch(pred, gold) {\n  const norm = s => s.trim().toLowerCase().replace(/\\s+/g, ' ').replace(/\\.$/, '').trim();\n  return norm(pred) === norm(gold);\n}",
  tests:[["exactMatch(' Paris ', 'paris')","true"],
         ["exactMatch('Paris.', 'Paris')","true"],
         ["exactMatch('New  York', 'New York')","true"],
         ["exactMatch('Paris', 'Lyon')","false"]],
  edge:[["exactMatch('', '')","true"],
        ["exactMatch('.', '')","true"]],
  ex:"원인: <code>trim</code> 만으로는 계약의 <b>네 가지 중 하나</b>만 처리합니다. 대소문자·중간 공백·끝의 마침표는 그대로 남아, 사람이 보면 정답인 응답이 오답으로 집계됩니다. 평가 점수가 실제보다 낮게 나오면 <b>모델이 아니라 채점기를 고쳐야 할 상황</b>인데도 프롬프트만 붙들게 됩니다.\n해결: 정규화 함수를 하나 만들어 <b>양쪽에 똑같이</b> 적용합니다. 규칙을 한 곳에 모아 두면 나중에 조항을 더하기도 쉽습니다.\n재발 방지: 채점기는 <b>먼저 테스트를 갖춰야 하는 코드</b>입니다. '정답으로 쳐야 하는 응답' 과 '오답으로 쳐야 하는 응답' 목록을 사람이 직접 만들어 두고, 채점 규칙을 바꿀 때마다 그 목록으로 회귀 검사를 하세요. 규칙은 <b>평가 문서에 문장으로</b> 적혀 있어야 합니다." },

{ track:"ai", cat:"debug", k:"0 을 자르면 -0 이 되어 전부 뒤집힌다",
  q:"목록의 <b>뒤쪽 <code>n</code> 개</b>를 평가용으로 떼고 나머지를 학습용으로 나눕니다. <code>n</code> 이 1 이상이면 맞는데, <code>n</code> 이 <b>0</b> 이면 학습 데이터가 텅 비고 <b>전부 평가로</b> 들어갑니다.",
  src:"function holdout(items, n) {\n  return { train: items.slice(0, -n), test: items.slice(-n) };\n}",
  sol:"function holdout(items, n) {\n  const k = Math.min(n, items.length);\n  const cut = items.length - k;\n  return { train: items.slice(0, cut), test: items.slice(cut) };\n}",
  tests:[["holdout([1,2,3,4], 0)","{train:[1,2,3,4], test:[]}"],
         ["holdout([1,2,3,4], 1)","{train:[1,2,3], test:[4]}"],
         ["holdout([1,2,3], 3)","{train:[], test:[1,2,3]}"],
         ["holdout([1,2,3], 5)","{train:[], test:[1,2,3]}"]],
  edge:[["holdout([], 0)","{train:[], test:[]}"],
        ["holdout([1,2], 2)","{train:[], test:[1,2]}"]],
  ex:"원인: <code>-n</code> 은 <code>n</code> 이 0 일 때 <code>-0</code> 이고, <code>slice</code> 는 그것을 <b>0 으로</b> 봅니다. 그래서 <code>slice(0, -0)</code> 은 빈 배열, <code>slice(-0)</code> 은 <b>배열 전체</b>가 되어 학습·평가가 통째로 뒤집힙니다. 스윕에서 <code>n=0</code> 을 한 번 넣는 순간 전체 실험이 무의미해지는데, 예외도 경고도 없습니다.\n해결: 음수 인덱스에 기대지 말고 <b>자를 자리를 직접 계산</b>합니다. <code>Math.min</code> 으로 목록보다 큰 <code>n</code> 도 함께 막힙니다.\n재발 방지: 음수 인덱스는 '뒤에서 세기' 라는 편의 문법이지 <b>0 을 다루지 못합니다</b>. 개수를 받아 자르는 함수에는 언제나 <code>n = 0</code> 과 <code>n &gt;= length</code> 두 경계를 테스트로 두고, 데이터 분할 함수라면 '<b>train 과 test 의 합이 원본과 같은가</b>' 를 성질 테스트로 박아 두세요." },

];
