/* DevOps 실습 2차 — 실습이 하나도 없던 6개 유닛을 연다.
   Kubernetes 운영 · CI/CD · Observability · 비용·확장 · Docker 최적화 · 브랜치와 시크릿.

   클러스터도 클라우드 계정도 필요 없다. 실제로 판단이 갈리는 자리는 대개 계산이다
   — 레플리카를 몇 개로 늘릴지, 캐시 층이 깨지는 순서가 어떤지, 어떤 태그를 배포할지.
   그 알맹이만 함수로 떼어 내면 브라우저에서 그대로 채점된다.

   채점은 앱의 JS 하네스가 한다. */
module.exports = [
/* ── Kubernetes 운영 ──────────────────────────────────────── */
{
  unit: "Kubernetes 운영",
  lesson: "직접 짜 보기 — 몇 개로 늘리고 언제 죽일 것인가",
  th: {
    sum: "쿠버네티스는 **'되어 있어야 할 모습'** 을 적어 두면 그 상태로 계속 맞춰 준다.",
    body: [
      { h: "목표를 적으면 맞춰 준다", t: "'레플리카 3개' 라고 적어 두면 하나가 죽어도 알아서 하나를 더 띄운다. 우리가 할 일은 '어떻게' 가 아니라 '무엇이 되어 있어야 하는가' 를 적는 것이다." },
      { h: "자동 확장은 비율로 정한다", t: "지금 사용률이 목표보다 높으면 그 비율만큼 레플리카를 늘린다. 목표 50%인데 지금 100%면 두 배가 필요하다는 뜻이다. 올림해서 정수로 만들고, 최소·최대 범위를 벗어나지 않게 자른다." },
      { h: "두 검사는 뜻이 다르다", t: "'살아 있나(liveness)' 가 실패하면 컨테이너를 **다시 띄운다.** '받을 준비가 됐나(readiness)' 가 실패하면 트래픽만 안 보낸다. 준비 검사에 쓸 것을 살아 있음 검사에 쓰면, 잠깐 느려진 것만으로 계속 재시작이 돈다." },
      { h: "요청과 상한은 다르다", t: "요청(request)은 '이만큼은 확보해 달라' 이고 상한(limit)은 '이 이상은 못 쓴다' 이다. 요청을 안 적으면 스케줄러가 아무 데나 넣어 서로 밀어내고, 상한을 안 적으면 하나가 노드를 통째로 먹는다." },
    ],
    code: { c: "desired = ceil(current * (nowPct / targetPct))\ndesired = min(max(desired, minR), maxR)", cap: "목표를 적으면 맞춰 준다" },
    key: ["'되어 있어야 할 모습' 을 적는다", "확장은 사용률 비율로", "liveness 와 readiness 는 다르다"],
  },
  q: [
    {
      k: "desiredReplicas · 사용률로 개수 정하기",
      qq: "지금 레플리카 수·현재 사용률·목표 사용률·최소·최대를 받아 <b>필요한 레플리카 수</b>를 돌려주세요. 올림하고 범위 안으로 잘라 줍니다.",
      src: "function desiredReplicas(cur, nowPct, targetPct, min, max) {\n  return Math.ceil(cur * (nowPct / targetPct));\n}",
      sol: "function desiredReplicas(cur, nowPct, targetPct, min, max) {\n  const want = Math.ceil(cur * (nowPct / targetPct));\n  return Math.min(max, Math.max(min, want));\n}",
      tests: [["desiredReplicas(2, 100, 50, 1, 10)", "4"],
              ["desiredReplicas(2, 100, 50, 1, 3)", "3"],
              ["desiredReplicas(4, 10, 50, 2, 10)", "2"]],
      edge: [["desiredReplicas(2, 50, 50, 1, 10)", "2"],
             ["desiredReplicas(1, 0, 50, 1, 10)", "1"]],
      ex: "범위를 안 자르면 사용률이 튀는 순간 수백 개를 띄우려 하고, 반대로 0개까지 줄여 서비스가 끊깁니다. 최소·최대는 자동 확장이 폭주하지 않게 잡아 주는 안전선이에요.",
    },
    {
      k: "probeAction · 검사 결과에 맞는 조치",
      qq: "검사 종류와 성공 여부를 받아 조치를 돌려주세요. <code>liveness</code> 실패는 <code>'restart'</code>, <code>readiness</code> 실패는 <code>'noTraffic'</code>, 성공이면 <code>'ok'</code> 입니다.",
      src: "function probeAction(kind, ok) {\n  return ok ? 'ok' : 'restart';\n}",
      sol: "function probeAction(kind, ok) {\n  if (ok) return 'ok';\n  return kind === 'liveness' ? 'restart' : 'noTraffic';\n}",
      tests: [["probeAction('liveness', false)", "'restart'"],
              ["probeAction('readiness', false)", "'noTraffic'"],
              ["probeAction('readiness', true)", "'ok'"]],
      edge: [["probeAction('liveness', true)", "'ok'"]],
      ex: "준비 검사 실패에 재시작을 걸면, 시작할 때 잠깐 느린 것만으로 계속 다시 뜹니다. 영영 준비되지 못하는 무한 재시작이 되는 것이 이 실수예요.",
    },
    {
      k: "fitsOnNode · 요청한 만큼 자리가 있는가",
      qq: "노드의 남은 용량과 파드가 <b>요청한</b> 양을 비교해 배치 가능한지 판단하세요. 요청을 <b>적지 않았으면</b>(<code>undefined</code>) 0으로 봅니다.",
      src: "function fitsOnNode(free, req) {\n  return free.cpu >= req.cpu && free.mem >= req.mem;\n}",
      sol: "function fitsOnNode(free, req) {\n  const cpu = req.cpu || 0;\n  const mem = req.mem || 0;\n  return free.cpu >= cpu && free.mem >= mem;\n}",
      tests: [["fitsOnNode({ cpu: 2, mem: 4 }, { cpu: 1, mem: 2 })", "true"],
              ["fitsOnNode({ cpu: 2, mem: 4 }, { cpu: 3, mem: 2 })", "false"],
              ["fitsOnNode({ cpu: 2, mem: 4 }, {})", "true"]],
      edge: [["fitsOnNode({ cpu: 0, mem: 0 }, {})", "true"],
             ["fitsOnNode({ cpu: 2, mem: 4 }, { cpu: 2, mem: 4 })", "true"]],
      ex: "요청을 안 적은 파드를 비교하면 undefined 와 견주게 되어 결과가 늘 거짓이 됩니다. 실제 클러스터에서는 반대로 '아무 데나 들어가는' 파드가 되어 노드를 밀어내요.",
    },
  ],
},
/* ── CI/CD 파이프라인 ─────────────────────────────────────── */
{
  unit: "CI/CD 파이프라인",
  lesson: "직접 짜 보기 — 무엇을 언제 통과시킬 것인가",
  th: {
    sum: "파이프라인은 **통과 기준을 코드로 적어 둔 것**이다. 사람 판단이 끼면 그때마다 달라진다.",
    body: [
      { h: "빠른 것부터 세운다", t: "형식 검사·단위 테스트처럼 빠른 단계를 앞에 둔다. 30분짜리 통합 테스트를 다 돌고 나서 세미콜론 때문에 떨어지면 그 30분이 통째로 낭비다. 실패는 되도록 빨리 만나야 싸다." },
      { h: "무엇을 배포할지는 태그가 정한다", t: "브랜치 이름으로 배포를 정하면 같은 이름에 다른 내용이 들어갈 수 있다. 커밋이나 버전 태그로 정하면 '무엇이 배포됐는지' 가 하나로 정해진다. 되돌릴 때도 그 태그만 있으면 된다." },
      { h: "같은 것을 다시 만들지 않는다", t: "테스트에서 만든 빌드 결과물을 그대로 배포한다. 배포 단계에서 다시 빌드하면 테스트한 것과 다른 것이 나갈 수 있다 — 라이브러리 버전이 그사이 바뀌었을 수도 있다." },
      { h: "비밀은 값으로 넘기지 않는다", t: "설정 파일이나 로그에 열쇠가 한 번 찍히면 그 기록을 보는 모두가 볼 수 있다. 이름만 적어 두고 실행할 때 넣어 주는 방식으로 만든다." },
    ],
    code: { c: "stages: [lint, test, build, deploy]   # 빠른 것부터\ndeploy: image: app:${'{'}COMMIT_SHA{'}'}      # 태그로 못 박는다", cap: "기준을 코드로 적어 둔다" },
    key: ["빠른 단계를 앞에", "배포는 태그로 못 박는다", "테스트한 결과물을 그대로"],
  },
  q: [
    {
      k: "orderStages · 빠른 것부터 세우기",
      qq: "단계 목록을 <b>평균 소요 시간이 짧은 순</b>으로 정렬해 이름만 돌려주세요. 시간이 같으면 <b>들어온 순서</b>를 지킵니다.",
      src: "function orderStages(stages) {\n  return stages.sort((a, b) => a.sec - b.sec).map(s => s.name);\n}",
      sol: "function orderStages(stages) {\n  return stages.slice().sort((a, b) => a.sec - b.sec).map(s => s.name);\n}",
      tests: [["orderStages([{ name: 'test', sec: 60 }, { name: 'lint', sec: 5 }])", "['lint', 'test']"],
              ["(() => { const a = [{ name: 'b', sec: 2 }, { name: 'a', sec: 1 }]; orderStages(a); return a[0].name; })()", "'b'"],
              ["orderStages([{ name: 'x', sec: 1 }, { name: 'y', sec: 1 }])", "['x', 'y']"]],
      edge: [["orderStages([])", "[]"]],
      ex: "sort 는 받은 배열을 그 자리에서 뒤집습니다. 설정 목록을 넘겼다면 원본이 바뀌어, 다음에 그 목록을 쓰는 곳이 엉뚱한 순서를 보게 돼요. 복사한 뒤에 정렬해야 합니다.",
    },
    {
      k: "imageTag · 무엇을 배포할지 못 박기",
      qq: "커밋 해시와 브랜치를 받아 이미지 태그를 만들어 주세요. 형식은 <code>app:커밋해시앞7자</code> 이고, <b>브랜치 이름은 쓰지 않습니다</b>.",
      src: "function imageTag(sha, branch) {\n  return 'app:' + branch;\n}",
      sol: "function imageTag(sha, branch) {\n  return 'app:' + sha.slice(0, 7);\n}",
      tests: [["imageTag('abcdef1234567890', 'main')", "'app:abcdef1'"],
              ["imageTag('0123456789abcdef', 'hotfix')", "'app:0123456'"],
              ["imageTag('abcdef1234567890', 'main') === imageTag('abcdef1234567890', 'dev')", "true"]],
      edge: [["imageTag('abc', 'main')", "'app:abc'"]],
      ex: "브랜치 이름으로 태그를 달면 같은 이름 안에 다른 내용이 계속 덮어써집니다. 'main 을 배포했다' 는 말이 무엇을 배포했는지 알려 주지 못해요. 커밋으로 못 박으면 되돌릴 때도 그 태그만 있으면 됩니다.",
    },
    {
      k: "shouldDeploy · 통과 기준을 코드로",
      qq: "테스트 통과 여부·브랜치·보호 브랜치 목록을 받아 배포할지 정하세요. <b>테스트를 통과했고 보호 브랜치일 때만</b> <code>true</code> 입니다.",
      src: "function shouldDeploy(passed, branch, protectedBranches) {\n  return protectedBranches.includes(branch);\n}",
      sol: "function shouldDeploy(passed, branch, protectedBranches) {\n  return passed === true && protectedBranches.includes(branch);\n}",
      tests: [["shouldDeploy(true, 'main', ['main'])", "true"],
              ["shouldDeploy(false, 'main', ['main'])", "false"],
              ["shouldDeploy(true, 'feature', ['main'])", "false"]],
      edge: [["shouldDeploy(true, 'main', [])", "false"],
             ["shouldDeploy(undefined, 'main', ['main'])", "false"]],
      ex: "테스트 결과를 안 보면, 빨간 파이프라인에서도 배포가 나갑니다. 그리고 결과가 아직 안 들어와 undefined 일 때도 막아야 해요 — '아직 모름' 은 '통과' 가 아닙니다.",
    },
  ],
},
/* ── Observability ────────────────────────────────────────── */
{
  unit: "Observability",
  lesson: "직접 짜 보기 — 무엇을 봐야 알 수 있는가",
  th: {
    sum: "관측성은 **바깥에서 본 것만으로 안에서 무슨 일이 있었는지 알 수 있는가**를 묻는다.",
    body: [
      { h: "세 가지를 함께 본다", t: "지표(숫자)는 '무엇이 이상한가', 로그(사건)는 '무슨 일이 있었나', 추적(요청의 여정)은 '어디서 느렸나' 를 알려 준다. 하나만 있으면 늘 절반만 알게 된다." },
      { h: "오류율은 비율로 본다", t: "'오류 100건' 은 요청이 100만이면 아무 일도 아니고 200이면 큰일이다. 전체 대비 비율로 봐야 규모가 달라져도 같은 기준으로 판단할 수 있다. 요청이 0일 때 나누지 않도록 조심한다." },
      { h: "예산으로 판단한다", t: "'99.9% 성공' 을 목표로 하면 0.1% 는 실패해도 된다는 뜻이다. 이 여유를 예산처럼 쓰면, 조금 실패했다고 매번 소동을 벌이지 않게 된다. 예산이 다 떨어졌을 때만 배포를 멈춘다." },
      { h: "알림은 사람이 할 일이 있을 때만", t: "조치할 것이 없는 알림이 쌓이면 진짜 알림도 무시하게 된다. '지금 누군가 무엇을 해야 하는가' 에 답할 수 없는 알림은 지표로만 남긴다." },
    ],
    code: { c: "errorRate = total ? errors / total : 0\nburned  = errorRate / (1 - slo)      // 예산을 얼마나 썼나", cap: "비율로 보고 예산으로 판단한다" },
    key: ["지표·로그·추적을 함께", "오류율은 비율로", "알림은 조치할 게 있을 때만"],
  },
  q: [
    {
      k: "errorRate · 0으로 나누지 않기",
      qq: "전체 요청 수와 오류 수를 받아 <b>오류율</b>을 돌려주세요. 요청이 <b>0건</b>이면 <code>0</code> 입니다.",
      src: "function errorRate(total, errors) {\n  return errors / total;\n}",
      sol: "function errorRate(total, errors) {\n  return total > 0 ? errors / total : 0;\n}",
      tests: [["errorRate(200, 2)", "0.01"],
              ["errorRate(0, 0)", "0"],
              ["errorRate(1000000, 100)", "0.0001"]],
      edge: [["errorRate(0, 5)", "0"],
             ["errorRate(4, 4)", "1"]],
      ex: "요청이 0일 때 나누면 NaN 이 나오고, 그 값은 어떤 비교에서도 거짓이라 알림이 조용히 안 울립니다. 새벽처럼 요청이 없는 시간대에 딱 이 상태가 돼요.",
    },
    {
      k: "burnRate · 예산을 얼마나 썼나",
      qq: "오류율과 목표 성공률(SLO)을 받아 <b>예산 소진 배율</b>을 돌려주세요. <code>오류율 / (1 - SLO)</code> 이고, 여유가 0이면 <code>0</code> 입니다.",
      src: "function burnRate(errRate, slo) {\n  return errRate / (1 - slo);\n}",
      sol: "function burnRate(errRate, slo) {\n  const budget = 1 - slo;\n  return budget > 0 ? errRate / budget : 0;\n}",
      /* 소수 계산에는 오차가 붙는다. 1 - 0.999 는 정확히 0.001 이 아니라서
         값을 그대로 견주면 정답도 떨어진다 — 그래서 아주 작은 차이는 허용한다. */
      tests: [["Math.abs(burnRate(0.001, 0.999) - 1) < 1e-6", "true"],
              ["Math.abs(burnRate(0.002, 0.999) - 2) < 1e-6", "true"],
              ["burnRate(0, 0.999)", "0"]],
      edge: [["burnRate(0.5, 1)", "0"],
             ["Math.abs(burnRate(0.01, 0.99) - 1) < 1e-6", "true"]],
      ex: "목표를 100% 로 잡으면 여유가 0이라 나눗셈이 무한이 됩니다. 대시보드에 Infinity 가 찍히고 알림 규칙이 전부 걸려요. 애초에 100% 목표는 지킬 수 없는 약속이기도 합니다.",
    },
    {
      k: "shouldPage · 사람을 깨울 것인가",
      qq: "예산 소진 배율과 지속 시간(분)을 받아 알림 수준을 정하세요. <b>배율 14 이상이 5분 넘게</b>면 <code>'page'</code>, <b>배율 1 이상이 60분 넘게</b>면 <code>'ticket'</code>, 아니면 <code>'none'</code> 입니다.",
      src: "function shouldPage(burn, minutes) {\n  return burn >= 1 ? 'page' : 'none';\n}",
      sol: "function shouldPage(burn, minutes) {\n  if (burn >= 14 && minutes > 5) return 'page';\n  if (burn >= 1 && minutes > 60) return 'ticket';\n  return 'none';\n}",
      tests: [["shouldPage(20, 10)", "'page'"],
              ["shouldPage(2, 120)", "'ticket'"],
              ["shouldPage(2, 10)", "'none'"]],
      edge: [["shouldPage(20, 5)", "'none'"],
             ["shouldPage(0, 999)", "'none'"]],
      ex: "조금만 새도 사람을 깨우면, 며칠 만에 아무도 알림을 안 보게 됩니다. 빠르게 타는 것은 바로 깨우고, 천천히 타는 것은 낮에 처리할 일감으로 남기는 것이 이 규칙이에요.",
    },
  ],
},
/* ── 비용·확장 ────────────────────────────────────────────── */
{
  unit: "비용·확장",
  lesson: "직접 짜 보기 — 돈이 어디서 새는가",
  th: {
    sum: "클라우드 비용은 대개 **안 쓰는데 켜 둔 것**과 **필요 이상으로 큰 것**에서 샌다.",
    body: [
      { h: "시간 단위로 계산된다", t: "켜 둔 시간만큼 돈이 나간다. 개발용 서버를 밤과 주말에 끄기만 해도 절반 아래로 떨어진다. '나중에 정리하자' 는 대개 다음 달 청구서로 돌아온다." },
      { h: "다 쓰지도 않는 크기를 잡는다", t: "평균 사용률이 10% 라면 그 서버는 열 배 큰 것이다. 몇 배를 쓰고 있는지 재고 그만큼 줄이면 된다. 다만 최대 순간을 견딜 여유는 남겨 둬야 한다." },
      { h: "약정과 요구량은 함께 본다", t: "미리 약정하면 싸지만, 약정한 양보다 적게 쓰면 그만큼 버린다. 늘 쓰는 만큼만 약정하고 나머지는 그때그때 쓰는 방식이 대개 싸다." },
      { h: "가장 큰 항목부터 본다", t: "항목이 수십 개여도 대개 상위 몇 개가 대부분을 차지한다. 작은 것부터 손대면 시간만 쓰고 청구서는 그대로다. 큰 것부터 정렬해 보는 것이 첫걸음이다." },
    ],
    code: { c: "monthly = hourly * hoursOn * 30\nrightSize = ceil(current * usedPct / targetPct)", cap: "끄고, 줄이고, 큰 것부터" },
    key: ["켜 둔 시간만큼 나간다", "쓰는 만큼으로 줄인다", "큰 항목부터 본다"],
  },
  q: [
    {
      k: "monthlyCost · 꺼 두면 얼마나 아끼나",
      qq: "시간당 요금과 <b>하루에 켜 두는 시간</b>을 받아 30일 요금을 돌려주세요. 하루 24시간을 넘겨 적었으면 <b>24로 자릅니다</b>.",
      src: "function monthlyCost(hourly, hoursPerDay) {\n  return hourly * hoursPerDay * 30;\n}",
      sol: "function monthlyCost(hourly, hoursPerDay) {\n  const h = Math.min(24, Math.max(0, hoursPerDay));\n  return hourly * h * 30;\n}",
      tests: [["monthlyCost(100, 24)", "72000"],
              ["monthlyCost(100, 8)", "24000"],
              ["monthlyCost(100, 48)", "72000"]],
      edge: [["monthlyCost(100, 0)", "0"],
             ["monthlyCost(100, -5)", "0"]],
      ex: "하루 8시간만 켜면 요금이 3분의 1입니다. 개발용 서버를 밤과 주말에 끄는 것만으로 큰 몫이 줄어요. 입력이 24를 넘거나 음수인 경우를 막아 두면 계산이 늘 말이 됩니다.",
    },
    {
      k: "rightSize · 쓰는 만큼으로 줄이기",
      qq: "현재 크기·평균 사용률·목표 사용률을 받아 <b>알맞은 크기</b>를 돌려주세요. 올림하고 <b>최소 1</b> 입니다.",
      src: "function rightSize(cur, usedPct, targetPct) {\n  return Math.round(cur * usedPct / targetPct);\n}",
      sol: "function rightSize(cur, usedPct, targetPct) {\n  return Math.max(1, Math.ceil(cur * usedPct / targetPct));\n}",
      tests: [["rightSize(10, 10, 50)", "2"],
              ["rightSize(10, 1, 50)", "1"],
              ["rightSize(8, 90, 60)", "12"]],
      edge: [["rightSize(4, 0, 50)", "1"],
             ["rightSize(3, 50, 50)", "3"]],
      ex: "반올림하면 0이 나올 수 있고, 크기 0인 서버는 존재하지 않습니다. 그리고 내림하면 목표 사용률을 넘겨 버려요 — 여유를 남기려면 올림이 맞습니다.",
    },
    {
      k: "topCost · 큰 항목부터 보기",
      qq: "비용 항목 목록에서 <b>상위 <code>n</code>개</b>의 이름을 큰 순서로 돌려주세요. 원본 목록은 그대로 둡니다.",
      src: "function topCost(items, n) {\n  return items.sort((a, b) => b.cost - a.cost).slice(0, n).map(x => x.name);\n}",
      sol: "function topCost(items, n) {\n  return items.slice().sort((a, b) => b.cost - a.cost).slice(0, n).map(x => x.name);\n}",
      tests: [["topCost([{ name: 'a', cost: 1 }, { name: 'b', cost: 9 }], 1)", "['b']"],
              ["topCost([{ name: 'a', cost: 1 }, { name: 'b', cost: 9 }, { name: 'c', cost: 5 }], 2)", "['b', 'c']"],
              ["(() => { const xs = [{ name: 'a', cost: 1 }, { name: 'b', cost: 9 }]; topCost(xs, 1); return xs[0].name; })()", "'a'"]],
      edge: [["topCost([], 3)", "[]"],
             ["topCost([{ name: 'a', cost: 1 }], 5)", "['a']"]],
      ex: "sort 는 받은 배열을 그 자리에서 뒤집습니다. 원본이 바뀌면 그 목록을 쓰는 다른 화면의 순서까지 달라져요. 복사한 뒤에 정렬하면 이런 일이 없습니다.",
    },
  ],
},
/* ── Docker·컨테이너 최적화 ───────────────────────────────── */
{
  unit: "Docker·컨테이너 최적화",
  lesson: "직접 짜 보기 — 캐시를 살리는 순서",
  th: {
    sum: "이미지 빌드는 **줄 단위로 캐시**된다. 한 줄이 바뀌면 그 아래는 전부 다시 만든다.",
    body: [
      { h: "바뀌는 것을 아래에 둔다", t: "소스 코드는 매번 바뀌고 의존성 목록은 가끔 바뀐다. 그래서 의존성 설치를 먼저 하고 소스 복사를 나중에 한다. 순서를 반대로 두면 한 글자만 고쳐도 라이브러리를 통째로 다시 받는다." },
      { h: "필요한 것만 복사한다", t: "`COPY . .` 는 `.git` 이나 로그까지 다 넣는다. 이미지가 커지고, 그 안에 비밀이 섞여 들어가기도 한다. 무엇을 넣지 않을지 적어 두는 것이 먼저다." },
      { h: "빌드 도구는 결과물에 넣지 않는다", t: "컴파일러와 빌드 캐시는 실행에 필요 없다. 빌드 단계와 실행 단계를 나누고 결과물만 옮기면 이미지가 몇 배 작아진다. 작을수록 배포가 빠르고 공격 면도 좁다." },
      { h: "태그는 못 박는다", t: "`latest` 는 시간이 지나면 다른 것을 가리킨다. 어제 되던 빌드가 오늘 깨지는 이유가 대개 이것이다. 버전을 적어 두면 언제 빌드해도 같은 것이 나온다." },
    ],
    code: { c: "COPY package.json .      # 가끔 바뀐다 — 위\nRUN npm ci\nCOPY . .                 # 자주 바뀐다 — 아래", cap: "자주 바뀌는 것을 아래에" },
    key: ["줄 단위로 캐시된다", "자주 바뀌는 것을 아래에", "`latest` 를 쓰지 않는다"],
  },
  q: [
    {
      k: "cacheHits · 어디까지 캐시가 살아남나",
      qq: "이전 빌드의 줄 목록과 이번 줄 목록을 받아, <b>처음부터 몇 줄까지 그대로인지</b> 돌려주세요. 그 아래는 전부 다시 만들어집니다.",
      src: "function cacheHits(prev, next) {\n  return next.filter(x => prev.includes(x)).length;\n}",
      sol: "function cacheHits(prev, next) {\n  let n = 0;\n  while (n < prev.length && n < next.length && prev[n] === next[n]) n++;\n  return n;\n}",
      tests: [["cacheHits(['a', 'b', 'c'], ['a', 'b', 'c'])", "3"],
              ["cacheHits(['a', 'b', 'c'], ['a', 'x', 'c'])", "1"],
              ["cacheHits(['a', 'b'], ['x', 'b'])", "0"]],
      edge: [["cacheHits([], ['a'])", "0"],
             ["cacheHits(['a'], ['a', 'b'])", "1"]],
      ex: "캐시는 '있는지' 가 아니라 '처음부터 이어지는지' 로 판단됩니다. 가운데 한 줄이 바뀌면 그 아래는 내용이 같아도 전부 다시 만들어져요. 그래서 순서가 중요합니다.",
    },
    {
      k: "orderLayers · 자주 바뀌는 것을 아래로",
      qq: "빌드 단계를 <b>바뀌는 빈도가 낮은 순</b>으로 정렬해 이름만 돌려주세요. 빈도가 같으면 들어온 순서를 지킵니다.",
      src: "function orderLayers(steps) {\n  return steps.slice().sort((a, b) => b.churn - a.churn).map(s => s.name);\n}",
      sol: "function orderLayers(steps) {\n  return steps.slice().sort((a, b) => a.churn - b.churn).map(s => s.name);\n}",
      tests: [["orderLayers([{ name: 'src', churn: 9 }, { name: 'deps', churn: 1 }])", "['deps', 'src']"],
              ["orderLayers([{ name: 'base', churn: 0 }, { name: 'src', churn: 9 }, { name: 'deps', churn: 2 }])", "['base', 'deps', 'src']"],
              ["orderLayers([{ name: 'a', churn: 1 }, { name: 'b', churn: 1 }])", "['a', 'b']"]],
      edge: [["orderLayers([])", "[]"]],
      ex: "자주 바뀌는 것을 위에 두면 그 아래가 매번 다시 만들어집니다. 소스 한 글자를 고쳤을 뿐인데 라이브러리를 통째로 다시 받는 빌드가 이렇게 나와요.",
    },
    {
      k: "pinTag · latest 를 쓰지 않기",
      qq: "이미지 이름과 버전을 받아 태그를 만들어 주세요. 버전이 <b>없거나 <code>'latest'</code></b> 면 <code>null</code> 을 돌려줍니다.",
      src: "function pinTag(image, version) {\n  return image + ':' + (version || 'latest');\n}",
      sol: "function pinTag(image, version) {\n  if (!version || version === 'latest') return null;\n  return image + ':' + version;\n}",
      tests: [["pinTag('node', '20.11.1')", "'node:20.11.1'"],
              ["pinTag('node', 'latest')", "null"],
              ["pinTag('node')", "null"]],
      edge: [["pinTag('node', '')", "null"],
             ["pinTag('alpine', '3.19')", "'alpine:3.19'"]],
      ex: "latest 는 시간이 지나면 다른 것을 가리킵니다. 어제 되던 빌드가 오늘 깨지는데 코드는 하나도 안 바뀌었어요. 못 박아 두면 언제 빌드해도 같은 것이 나옵니다.",
    },
  ],
},
/* ── 확장 토픽 1 · 브랜치 전략과 시크릿 ───────────────────── */
{
  unit: "확장 토픽 1 · 브랜치 전략과 시크릿",
  lesson: "직접 짜 보기 — 합치는 규칙과 감추는 규칙",
  th: {
    sum: "브랜치 규칙은 **팀이 합의한 순서**이고, 시크릿 규칙은 **한 번 새면 되돌릴 수 없다**는 사실에서 나온다.",
    body: [
      { h: "이름에 규칙을 담는다", t: "`feat/`·`fix/`·`hotfix/` 처럼 앞머리를 정해 두면 도구가 자동으로 갈라 처리할 수 있다. 사람이 매번 판단하지 않아도 되고, 급한 수정만 다르게 다루는 것도 자동으로 된다." },
      { h: "짧게 살다 사라진다", t: "브랜치를 오래 두면 그동안 본줄기가 멀리 가서, 합칠 때 충돌이 산더미가 된다. 작게 나눠 자주 합치는 편이 결국 빠르다. 합친 브랜치는 지워서 목록을 깨끗하게 둔다." },
      { h: "새어 나간 열쇠는 지워지지 않는다", t: "기록에 한 번 들어간 열쇠는 나중에 지워도 이미 복제된 곳에는 남아 있다. 그래서 '지우기' 가 아니라 **'무효로 만들고 새로 발급'** 이 정답이다." },
      { h: "새기 전에 막는다", t: "열쇠처럼 생긴 글자를 커밋 전에 걸러 내는 검사를 두면 대부분은 들어가기 전에 막힌다. 사람이 조심하는 것보다 훨씬 확실하다." },
    ],
    code: { c: "feat/login-form   →  일반\nhotfix/crash      →  급함, 바로 배포 줄로\n\n# 새면: 지우지 말고 무효로 만들고 새로 발급", cap: "규칙은 이름에, 열쇠는 무효화로" },
    key: ["앞머리로 규칙을 담는다", "짧게 살다 사라진다", "새면 무효로 만들고 새로 발급"],
  },
  q: [
    {
      k: "branchKind · 이름으로 갈라 처리하기",
      qq: "브랜치 이름을 받아 종류를 돌려주세요. <code>hotfix/</code>는 <code>'urgent'</code>, <code>feat/</code>·<code>fix/</code>는 <code>'normal'</code>, 그 밖에는 <code>'unknown'</code> 입니다.",
      src: "function branchKind(name) {\n  return name.startsWith('hotfix/') ? 'urgent' : 'normal';\n}",
      sol: "function branchKind(name) {\n  if (name.startsWith('hotfix/')) return 'urgent';\n  if (name.startsWith('feat/') || name.startsWith('fix/')) return 'normal';\n  return 'unknown';\n}",
      tests: [["branchKind('hotfix/crash')", "'urgent'"],
              ["branchKind('feat/login')", "'normal'"],
              ["branchKind('temp')", "'unknown'"]],
      edge: [["branchKind('fix/typo')", "'normal'"],
             ["branchKind('')", "'unknown'"]],
      ex: "규칙에 없는 이름을 'normal' 로 넘기면, 오타 난 브랜치가 정상 흐름을 타고 그대로 흘러갑니다. 모르는 것은 모른다고 해야 그 자리에서 걸러져요.",
    },
    {
      k: "staleBranches · 오래된 것 찾아내기",
      qq: "브랜치 목록에서 마지막 커밋이 <b><code>days</code>일보다 오래된</b> 것의 이름을 돌려주세요. <b>보호 브랜치는 제외</b>합니다.",
      src: "function staleBranches(list, days, protectedNames) {\n  return list.filter(b => b.ageDays > days).map(b => b.name);\n}",
      sol: "function staleBranches(list, days, protectedNames) {\n  return list\n    .filter(b => b.ageDays > days && !protectedNames.includes(b.name))\n    .map(b => b.name);\n}",
      tests: [["staleBranches([{ name: 'old', ageDays: 90 }, { name: 'new', ageDays: 1 }], 30, [])", "['old']"],
              ["staleBranches([{ name: 'main', ageDays: 90 }], 30, ['main'])", "[]"],
              ["staleBranches([{ name: 'a', ageDays: 30 }], 30, [])", "[]"]],
      edge: [["staleBranches([], 30, [])", "[]"],
             ["staleBranches([{ name: 'main', ageDays: 90 }, { name: 'x', ageDays: 90 }], 30, ['main'])", "['x']"]],
      ex: "보호 브랜치를 빼지 않으면 정리 스크립트가 main 을 지우려 듭니다. 자동화는 사람보다 훨씬 빠르고 훨씬 망설임이 없어서, 예외를 먼저 적어 둬야 해요.",
    },
    {
      k: "looksLikeSecret · 새기 전에 막기",
      qq: "글자를 받아 <b>열쇠처럼 보이는지</b> 판단하세요. <code>'AKIA'</code> 로 시작하거나, <code>'-----BEGIN'</code> 을 포함하거나, <b>32자 이상의 16진수</b>면 참입니다.",
      src: "function looksLikeSecret(s) {\n  return s.startsWith('AKIA');\n}",
      sol: "function looksLikeSecret(s) {\n  if (s.startsWith('AKIA')) return true;\n  if (s.includes('-----BEGIN')) return true;\n  return /^[0-9a-f]{32,}$/i.test(s);\n}",
      tests: [["looksLikeSecret('AKIAIOSFODNN7EXAMPLE')", "true"],
              ["looksLikeSecret('-----BEGIN PRIVATE KEY-----')", "true"],
              ["looksLikeSecret('0123456789abcdef0123456789abcdef')", "true"]],
      edge: [["looksLikeSecret('hello world')", "false"],
             ["looksLikeSecret('0123abcd')", "false"]],
      ex: "한 가지 모양만 막으면 나머지는 그대로 통과합니다. 기록에 한 번 들어간 열쇠는 나중에 지워도 이미 복제된 곳에 남아 있어서, 들어가기 전에 막는 것이 유일한 방법이에요.",
    },
  ],
},
];
