/* sql — 40자 미만 해설 83개를 '왜 그런가 + 나머지는 왜 아닌가' 로 다시 쓴다.
   node ex_short.cjs --apply ex_sql.cjs */
module.exports = { track: "sql", fixes: [
  { k: "빈칸", ex0: "FROM 다음에 테이블 이름", ex: "SELECT * FROM users 에서 FROM 은 '어느 표에서 가져올지' 를 정한다. 열 이름은 SELECT 뒤에, 표 이름은 FROM 뒤에 온다. FROM 을 빼면 어느 표인지 알 수 없어 문법 오류가 난다. 대소문자는 구분하지 않으므로 from 도 된다." },
  { k: "문장 끝", ex0: "세미콜론(;) 으로 문장을", ex: "SQL 문장은 세미콜론 ; 으로 끝낸다. 문장을 여러 개 이어 적을 때 어디서 끊기는지 알려 주는 표시다. 마침표와 쉼표는 문장 끝이 아니라 소수점과 항목 구분에 쓰이고, 콜론은 SQL 에서 문장 끝 기호가 아니다. 한 문장만 보낼 때는 생략해도 되는 도구가 많다." },
  { k: "개념", ex0: "SELECT 로 데이터를 조회", ex: "표에서 데이터를 읽어 오는 명령은 SELECT 다. GET 은 HTTP 의 말이고, SHOW 는 MySQL 에서 표 목록 같은 메타 정보를 볼 때만 쓰며, EXTRACT 는 날짜에서 연·월을 뽑는 함수다. 넷 중 행을 조회하는 것은 SELECT 뿐이다." },
  { k: "전체 선택", ex0: "SELECT * 는 모든 열", ex: "SELECT * 의 별표는 '모든 열' 이다. 표의 열 이름을 몰라도 전부 볼 수 있어 편하지만, 실제 서비스 코드에서는 필요한 열만 적는 것이 낫다. % 는 LIKE 의 와일드카드, # 와 @ 는 열 선택과 관계없는 기호다." },
  { k: "특정 열", ex0: "필요한 열 이름을 SELECT 뒤에", ex: "열 이름은 SELECT 뒤에, 표 이름은 FROM 뒤에 온다. 그래서 SELECT name FROM users 다. SELECT users FROM name 은 순서가 뒤바뀌어 name 이라는 표를 찾다 실패하고, GET 은 SQL 명령이 아니며, FROM 으로 시작하는 문장은 문법에 없다." },
  { k: "빈칸", ex0: "SQL에서 '같다'는 = 하나", ex: "SQL 에서 '같다' 는 = 하나다. WHERE age = 20 처럼 쓴다. 프로그래밍 언어의 == 는 SQL 에 없어 문법 오류가 난다. '같지 않다' 는 <> 또는 != 이고, NULL 과 비교할 때는 = 가 아니라 IS NULL 을 써야 한다." },
  { k: "문자열 조건", ex0: "문자열은 작은따옴표로 감싸고 = 로 비교", ex: "문자열 값은 작은따옴표로 감싸고 = 로 비교한다. city = Seoul 처럼 따옴표가 없으면 Seoul 을 열 이름으로 여겨 오류가 난다. == 는 SQL 에 없고, is 는 NULL 검사(IS NULL)에만 쓰는 키워드라 문자열 비교에는 맞지 않는다." },
  { k: "개념", ex0: "WHERE 로 조건을 지정", ex: "조건에 맞는 행만 남기는 절은 WHERE 다. SELECT * FROM users WHERE age > 20 처럼 FROM 뒤에 온다. IF 는 조건식 함수, FILTER 와 ONLY 는 표준 SQL 의 절이 아니다. 집계한 뒤의 조건은 WHERE 가 아니라 HAVING 이다." },
  { k: "여러 조건", ex0: "AND 는 둘 다 참, OR 은 하나만 참", ex: "두 조건을 모두 만족해야 할 때는 AND 로 잇는다. 하나만 만족해도 되면 OR 이다. WITH 는 CTE 를 시작하는 키워드라 뜻이 다르고, ALSO 와 PLUS 는 SQL 에 없다. AND 와 OR 을 섞을 때는 괄호로 묶어야 우선순위 실수를 막는다." },
  { k: "크기 비교", ex0: "> 는 초과(같은 값 미포함)", ex: "'초과' 는 같은 값을 포함하지 않으므로 price > 100 이다. >= 는 '이상' 이라 100 도 들어가고, = 는 딱 100 만, < 는 미만이다. 100 이 포함되는지 아닌지가 초과와 이상을 가르는 유일한 차이다." },
  { k: "내림차순", ex0: "DESC 는 내림차순, ASC 는 오름차순", ex: "큰 값부터 작은 값 순으로 정렬하는 키워드는 DESC(descending) 다. ASC 는 오름차순이며 아무것도 적지 않으면 기본값이다. HIGH 와 DOWN 은 SQL 키워드가 아니다. ORDER BY score DESC 처럼 열 이름 뒤에 붙인다." },
  { k: "빈칸", ex0: "LIMIT n 으로 개수를 제한", ex: "MySQL 과 PostgreSQL 에서는 LIMIT 5 로 결과 행 수를 제한한다. 보통 ORDER BY 와 함께 써서 '상위 몇 개' 를 뽑는다. SQL Server 는 SELECT TOP 5, Oracle 은 FETCH FIRST 5 ROWS ONLY 처럼 문법이 달라 DB 마다 확인해야 한다." },
  { k: "개념", ex0: "ORDER BY 열이름 으로 정렬", ex: "결과의 순서를 정하는 절은 ORDER BY 다. ORDER BY age DESC 처럼 열과 방향을 적는다. SORT 는 SQL 키워드가 아니고, GROUP BY 는 같은 값끼리 묶는 것이라 정렬이 아니며, RANK 는 순위를 매기는 윈도우 함수다." },
  { k: "조합", ex0: "정렬 후 LIMIT 로 상위 N개", ex: "'점수 높은 순 3명' 은 먼저 점수 내림차순으로 정렬(ORDER BY score DESC)한 뒤 앞에서 3 개만 자른다(LIMIT 3). GROUP BY 는 묶어서 집계하는 것이라 순위와 관계없고, SORT 와 TOP 은 표준 SQL 의 조합이 아니다." },
  { k: "개념", ex0: "COUNT(*) 로 행 수를 센다", ex: "행의 개수를 세는 함수는 COUNT() 다. COUNT(*) 는 모든 행을, COUNT(열) 은 그 열이 NULL 이 아닌 행만 센다. SUM() 은 값을 더하는 것이라 개수가 아니고, NUM() 과 TOTAL() 은 표준 함수가 아니다." },
  { k: "빈칸", ex0: "MAX() 는 최댓값, MIN() 은 최솟값", ex: "가장 큰 값은 MAX(열), 가장 작은 값은 MIN(열) 이다. 둘 다 NULL 을 무시한다. 숫자뿐 아니라 날짜와 문자열에도 쓸 수 있어 MAX(created_at) 은 가장 최근 시각이 된다." },
  { k: "합계", ex0: "SUM() 은 합계", ex: "열의 값을 모두 더하는 함수는 SUM(price) 다. COUNT(price) 는 값의 개수를 세는 것이라 합이 아니고, ADD 와 TOTAL 은 표준 SQL 함수가 아니다. SUM 은 NULL 을 건너뛰고, 행이 하나도 없으면 0 이 아니라 NULL 을 돌려준다." },
  { k: "평균", ex0: "AVG() 는 평균값", ex: "평균을 구하는 함수는 AVG() 다. MEAN 은 통계 용어이지 SQL 함수가 아니고, MEDIAN 은 일부 DB 에만 있는 중앙값 함수이며, MID 는 문자열 함수다. AVG 는 NULL 을 빼고 계산하므로 NULL 을 0 으로 치고 싶다면 COALESCE 로 바꿔야 한다." },
  { k: "JOIN", ex0: "JOIN 으로 테이블을 결합", ex: "두 표를 연결해 한 번에 조회하는 명령은 JOIN 이다. MERGE 는 두 표의 내용을 합쳐 넣는 쓰기 명령이고, CONNECT 와 LINK 는 SQL 키워드가 아니다. JOIN 은 ON 으로 어떤 열이 같을 때 연결할지 정해야 한다." },
  { k: "연결 조건", ex0: "JOIN ... ON 조건 형태", ex: "JOIN 의 연결 기준은 ON 뒤에 적는다. users u JOIN orders o ON u.id = o.user_id 처럼 두 표의 어느 열이 같아야 하는지 정한다. BY 는 ORDER BY·GROUP BY 에 붙는 말이고, AT 과 IF 는 JOIN 에 쓰지 않는다." },
  { k: "개념", ex0: "GROUP BY 로 묶은 뒤 집계", ex: "같은 값을 가진 행끼리 묶어 집계하는 절은 GROUP BY 다. GROUP BY city 뒤에 COUNT(*) 나 SUM() 을 쓰면 도시마다 하나의 결과가 나온다. ORDER BY 는 순서만 바꾸고, JOIN 은 표를 연결하며, UNION 은 두 결과를 위아래로 붙인다." },
  { k: "활용", ex0: "city 로 묶고 COUNT 로 센다", ex: "'도시별 인원 수' 는 도시로 묶고(GROUP BY city) 각 묶음의 행 수를 센다(COUNT(*)). WHERE city 는 특정 도시만 거르는 것이고, ORDER BY city 는 순서만 바꿀 뿐 묶지 않으며, LIMIT 은 개수 제한이라 집계와 관계없다." },
  { k: "개념", ex0: "INNER JOIN은 조인 조건이 일치하는 행만", ex: "INNER JOIN 은 ON 조건이 맞는 행만 돌려준다. 한쪽에만 있는 행은 결과에서 빠진다. 왼쪽 표의 모든 행을 남기려면 LEFT JOIN, 매칭되지 않는 행만 보려면 LEFT JOIN 뒤에 WHERE 오른쪽.id IS NULL 을 붙인다." },
  { k: "빈칸", ex0: "INNER JOIN은 교집합에 해당하는 행만", ex: "양쪽에 모두 있는 행만 가져오는 것이 INNER JOIN 이다. 벤 다이어그램의 교집합에 해당한다. 그냥 JOIN 이라고만 써도 INNER 로 취급된다. LEFT 나 RIGHT 는 한쪽의 모든 행을 남기는 OUTER JOIN 이다." },
  { k: "빈칸", ex0: "테이블 N개를 연결하려면 보통 N-1개의 JOIN", ex: "표를 하나 더 연결할 때마다 JOIN 절이 하나씩 필요하다. 세 표면 첫 표에 둘째를 붙이고, 그 결과에 셋째를 붙이므로 JOIN 이 두 번이다. 일반화하면 N 개 표에 N-1 개의 JOIN 이다." },
  { k: "쿼리", ex0: "a, b, c 세 테이블을 두 번의 JOIN", ex: "FROM a JOIN b ON ... JOIN c ON ... 은 a, b, c 세 표를 연결한다. JOIN 이 두 번 나오면 표는 세 개다. JOIN 개수를 세면 하나 적게 나오므로 '표 수 = JOIN 수 + 1' 로 센다." },
  { k: "빈칸", ex0: "AS로 별칭을 지정하며, 대부분의 DB에서 AS는 생략", ex: "열이나 표에 다른 이름을 붙이는 키워드는 AS 다. SELECT name AS 이름, FROM users AS u 처럼 쓴다. 대부분의 DB 에서 AS 는 생략할 수 있어 users u 라고만 적어도 되지만, 읽기 쉽도록 열 별칭에는 붙이는 편이 좋다." },
  { k: "빈칸", ex0: "AS로 집계 결과 컬럼에 total 같은 별칭", ex: "COUNT(*) 의 결과 열은 이름이 COUNT(*) 라 다루기 불편하다. AS total 을 붙이면 결과 열 이름이 total 이 되어 프로그램에서 읽기 쉽다. ORDER BY total 처럼 별칭을 뒤에서 다시 쓸 수도 있다." },
  { k: "쿼리", ex0: "u는 users 테이블의 별칭으로", ex: "FROM users u 의 u 는 users 표에 붙인 짧은 별칭이다. 그 뒤로 u.name 처럼 표 이름 대신 쓴다. 두 표에 같은 이름의 열이 있을 때 어느 표의 열인지 밝히는 데 꼭 필요하다. 함수도, 데이터베이스 이름도, 열 이름도 아니다." },
  { k: "개념", ex0: "VALUES에 지정한 값으로 새 행 하나가 삽입", ex: "INSERT INTO 표 (열) VALUES (값) 은 새 행을 하나 추가한다. name 이 'Kim' 인 행이 생긴다. 기존 행을 고치는 것은 UPDATE, 행을 지우는 것은 DELETE, 표를 지우는 것은 DROP 이다. INSERT 는 언제나 '추가' 다." },
  { k: "쿼리", ex0: "명시하지 않은 컬럼은 정의된 기본값이나 NULL", ex: "INSERT 에서 적지 않은 열은 표를 만들 때 정한 DEFAULT 값이 들어가고, 기본값이 없으면 NULL 이 된다. NOT NULL 인데 기본값도 없는 열을 빼면 그때만 오류가 난다. 앞 행의 값을 복사하거나 0 을 넣는 일은 없다." },
  { k: "개념", ex0: "SET 절에 컬럼=새값 을 지정", ex: "UPDATE 표 SET 열 = 값 WHERE 조건 에서 무엇을 어떻게 바꿀지는 SET 이 정한다. WHERE 는 어느 행을 바꿀지, VALUES 는 INSERT 에서 새 값을 적는 곳, FROM 은 SELECT 에서 표를 고르는 곳이라 역할이 다르다." },
  { k: "쿼리", ex0: "WHERE id=5로 대상 행을 한정하여 age만 30", ex: "UPDATE users SET age = 30 WHERE id = 5 는 id 가 5 인 행의 age 만 30 으로 바꾼다. WHERE 가 대상을 한 행으로 좁힌다. 행을 지우거나 추가하지 않고, WHERE 가 없었다면 모든 사용자의 age 가 30 이 되었을 것이다." },
  { k: "주의", ex0: "WHERE가 없으면 전체 행이 갱신되므로", ex: "UPDATE 에 WHERE 를 빼면 오류 없이 표의 모든 행이 바뀐다. 이것이 UPDATE 사고의 대표적 원인이다. 첫 행만 바뀌거나 아무것도 안 바뀌는 일은 없다. 실행 전에 같은 WHERE 로 SELECT 를 먼저 해 보는 습관이 안전하다." },
  { k: "빈칸", ex0: "DELETE FROM 테이블 WHERE 조건 형식으로 행을", ex: "행을 지우는 명령은 DELETE FROM 표 WHERE 조건 이다. WHERE 를 빼면 모든 행이 지워진다. DROP TABLE 은 표 자체를 없애고, TRUNCATE 는 모든 행을 한 번에 비우는 별도 명령이다. REMOVE 는 SQL 에 없다." },
  { k: "개념", ex0: "WHERE 조건으로 삭제 대상 행을 한정", ex: "DELETE 는 WHERE 로 어느 행을 지울지 정해야 한다. 없으면 전부 지워진다. ORDER BY 와 GROUP BY 는 조회용 절이고, HAVING 은 집계 결과에 거는 조건이라 DELETE 대상을 좁히는 데 쓰지 않는다." },
  { k: "기간으로 고르기", ex0: "> 와 = 와 <= 를 써야 한다", ex: "2 월 주문은 날짜가 2026-02-01 이상이고 2026-03-01 미만인 행이다. WHERE ordered_at >= '2026-02-01' AND ordered_at < '2026-03-01' 처럼 시작은 포함, 끝은 제외로 잡아야 3 월 1 일 0 시 주문이 섞이지 않는다. BETWEEN 은 양 끝을 포함하므로 시각이 있는 열에는 경계가 어긋난다." },
  { k: "쿼리", ex0: "DISTINCT로 city의 중복을 제거한 고유 목록", ex: "SELECT DISTINCT city 는 같은 도시를 한 번만 보여 준다. 그래서 '중복 없는 도시 목록' 이다. 도시의 개수를 세려면 COUNT(DISTINCT city), 가장 큰 값은 MAX(city) 이고, DISTINCT 가 없으면 행마다 도시가 중복되어 나온다." },
  { k: "LIKE", ex0: "_ (밑줄)은 임의의 한 글자, % 는 임의 개수", ex: "LIKE 에서 밑줄 _ 은 정확히 한 글자, % 는 0 글자 이상 아무 길이다. 'a_' 는 두 글자 단어, 'a%' 는 a 로 시작하는 모든 단어에 맞는다. 물음표와 별표는 셸이나 정규식의 기호이지 SQL LIKE 의 와일드카드가 아니다." },
  { k: "BETWEEN", ex0: "BETWEEN은 양 끝 경계값을 모두 포함", ex: "BETWEEN 1 AND 10 은 1 이상 10 이하다. 양 끝 값 1 과 10 이 모두 들어간다. 그래서 '10 미만' 이 필요하면 BETWEEN 대신 >= 1 AND < 10 으로 써야 한다. 날짜·시각 열에서 특히 이 차이가 자주 문제가 된다." },
  { k: "IN", ex0: "IN은 목록 중 하나와 일치하는지 검사하며 여러 OR", ex: "age IN (10, 20, 30) 은 age = 10 OR age = 20 OR age = 30 과 같다. 목록 안의 값 중 하나와 같으면 참이다. 범위(10 이상 30 이하)가 아니라 딱 그 값들만이고, NULL 은 IN 으로 잡히지 않아 IS NULL 을 따로 써야 한다." },
  { k: "빈칸", ex0: "LENGTH는 문자열의 길이를 반환한다. 'apple'은 5글자", ex: "LENGTH('apple') 은 글자 수 5 를 돌려준다. 한글은 DB 와 인코딩에 따라 LENGTH 가 바이트 수를 돌려주기도 하므로, 글자 수가 필요하면 CHAR_LENGTH 를 쓰는 편이 안전하다. 빈 문자열은 0, NULL 은 NULL 이다." },
  { k: "함수", ex0: "LENGTH가 문자열 길이를 반환한다. UPPER는 대문자", ex: "문자열의 길이는 LENGTH() 다. UPPER 는 대문자로 바꾸고, CONCAT 은 이어 붙이며, ROUND 는 숫자를 반올림한다. 넷 가운데 숫자를 돌려주는 문자열 함수는 LENGTH 뿐이다." },
  { k: "빈칸", ex0: "UPPER('abc') → 'ABC' 처럼 대문자로", ex: "UPPER() 는 문자열의 모든 글자를 대문자로 바꾼다. 반대는 LOWER() 다. 대소문자를 구분하지 않고 비교하려면 양쪽에 UPPER 를 씌운다. 다만 열에 함수를 씌우면 그 열의 인덱스를 쓰지 못하므로 큰 표에서는 주의한다." },
  { k: "함수", ex0: "CONCAT은 문자열을 이어 붙인다. 공백 없이", ex: "CONCAT('SQL', '문법') 은 두 문자열을 그대로 이어 SQL문법 이 된다. 공백은 넣어 주지 않으므로 띄우려면 CONCAT('SQL', ' ', '문법') 처럼 공백을 인자로 넣어야 한다. 순서는 인자 순서 그대로이고, NULL 이 섞이면 MySQL 에서는 전체가 NULL 이 된다." },
  { k: "함수", ex0: "CONCAT('a','b') → 'ab' 처럼 문자열을 연결", ex: "두 문자열을 이어 붙이는 표준 함수는 CONCAT() 이다. 인자를 여러 개 받아 순서대로 붙인다. PostgreSQL 과 Oracle 은 || 연산자로도 붙일 수 있고, MySQL 은 CONCAT_WS 로 구분자를 끼워 붙이는 함수가 따로 있다." },
  { k: "빈칸", ex0: "1번째부터 4글자를 뽑으면 c, o, d, i", ex: "SUBSTRING('coding', 1, 4) 는 1 번째 글자부터 4 글자를 뽑는다. SQL 의 위치는 0 이 아니라 1 부터 세므로 c, o, d, i 네 글자 codi 가 된다. 프로그래밍 언어의 0 시작 인덱스와 다르다는 점이 헷갈리기 쉽다." },
  { k: "함수", ex0: "7번째 글자는 'W'이고 거기서 5글자를 뽑으면", ex: "SUBSTRING('Hello World', 7, 5) 는 7 번째 글자부터 5 글자다. H(1) e(2) l(3) l(4) o(5) 공백(6) W(7) 이므로 W 부터 다섯 글자 World 가 나온다. 공백도 한 글자로 센다는 점에 주의한다." },
  { k: "빈칸", ex0: "MOD는 나머지를 반환한다. 10을 3으로", ex: "MOD(10, 3) 은 10 을 3 으로 나눈 나머지 1 을 돌려준다. 몫 3 이 아니다. 짝수 판별(MOD(n, 2) = 0)이나 순환 번호 매기기에 쓴다. MySQL 과 PostgreSQL 은 % 연산자로도 같은 계산을 한다." },
  { k: "빈칸", ex0: "절댓값 함수 ABS는 부호를 없앤 값", ex: "ABS(-15) 는 부호를 뗀 절댓값 15 를 돌려준다. 양수를 넣으면 그대로 나온다. 두 값의 차이가 얼마나 큰지 방향과 상관없이 볼 때 ABS(a - b) 처럼 쓴다." },
  { k: "함수", ex0: "ABS는 절댓값을 반환한다. -7의 절댓값은 7", ex: "ABS 는 절댓값이므로 ABS(-7) 은 7 이다. 부호만 사라지고 크기는 그대로다. 0 은 0 이고, 양수는 바뀌지 않는다. 14 는 부호를 뒤집어 더한 값이고 -7 그대로는 ABS 를 적용하지 않은 값이다." },
  { k: "빈칸", ex0: "CASE 다음에 WHEN 조건 THEN 결과", ex: "CASE 식은 CASE WHEN 조건 THEN 값 ... ELSE 값 END 꼴이다. 조건을 적는 자리가 WHEN 이다. IF 는 MySQL 의 별도 함수이고 CASE 안에서는 WHEN 을 써야 한다. WHEN 은 여러 번 이어 붙일 수 있고 위에서부터 처음 참인 것이 선택된다." },
  { k: "CASE", ex0: "CASE 식은 반드시 END로 닫아야", ex: "CASE 식은 END 로 끝난다. END 가 없으면 문법 오류다. STOP, CLOSE, FINISH 는 SQL 키워드가 아니다. END 뒤에 AS 별칭 을 붙여 결과 열에 이름을 줄 수 있다." },
  { k: "CASE", ex0: "ELSE가 없고 참인 조건이 없으면 CASE는 NULL", ex: "어떤 WHEN 도 참이 아니고 ELSE 도 없으면 CASE 의 결과는 NULL 이다. 오류가 나지 않고 0 이나 빈 문자열도 아니다. 그래서 집계나 비교에서 예상 밖의 NULL 이 섞이지 않도록 ELSE 를 적어 두는 습관이 좋다." },
  { k: "CASE", ex0: "1=1은 항상 참이므로 THEN의 '참'", ex: "1 = 1 은 언제나 참이므로 첫 WHEN 이 선택되어 '참' 이 나온다. ELSE '거짓' 은 조건이 거짓일 때만 쓰인다. 오류나 NULL 이 될 이유가 없다. 1=1 은 조건을 항상 참으로 만들 때 자주 쓰는 관용구다." },
  { k: "빈칸", ex0: "CASE ... END AS 별칭 형태로 컬럼에 이름", ex: "CASE ... END 는 하나의 값을 만드는 식이므로 다른 열처럼 AS 로 이름을 붙일 수 있다. CASE WHEN score > 60 THEN '합격' ELSE '불합격' END AS 결과 처럼 쓴다. 이름을 붙이지 않으면 결과 열 이름이 식 전체가 되어 다루기 어렵다." },
  { k: "빈칸", ex0: "20은 거짓이므로 세 번째 값 200", ex: "IF(조건, 참일 때, 거짓일 때) 에서 10 > 20 은 거짓이므로 세 번째 인자 200 이 나온다. 100 은 조건이 참일 때의 값이다. IF 는 MySQL 함수이고, 표준 SQL 에서는 같은 일을 CASE 로 쓴다." },
  { k: "IF", ex0: "1=1은 참이므로 두 번째 인자 'a'", ex: "IF(1=1, 'a', 'b') 는 조건이 참이므로 두 번째 인자 'a' 를 돌려준다. 'b' 는 거짓일 때의 값이다. 오류나 NULL 이 나올 이유가 없다. MySQL 의 IF() 는 CASE WHEN 1=1 THEN 'a' ELSE 'b' END 와 같다." },
  { k: "빈칸", ex0: "처음 두 값이 NULL이므로 NULL이 아닌 10", ex: "COALESCE 는 인자를 왼쪽부터 보며 NULL 이 아닌 첫 값을 돌려준다. 앞의 두 NULL 을 건너뛰고 10 이 나온다. 모든 인자가 NULL 이면 결과도 NULL 이다. '값이 없으면 기본값' 을 표현하는 가장 흔한 방법이다." },
  { k: "NULL", ex0: "첫 인자가 NULL이므로 다음 값 5", ex: "COALESCE(NULL, 5) 는 첫 인자가 NULL 이라 다음 값 5 를 돌려준다. 0 이 아니라 5 다. 오류도 나지 않는다. COALESCE(col, 0) 처럼 쓰면 NULL 인 값을 0 으로 바꿔 계산에 넣을 수 있다." },
  { k: "NULL", ex0: "COALESCE는 인자 개수 제한이 없어 여러 값을", ex: "COALESCE 는 인자를 두 개 이상 얼마든지 받아 왼쪽부터 NULL 이 아닌 첫 값을 고른다. 숫자·문자열·날짜 어떤 타입이든 되고, NULL 만 돌려주는 것도 아니다. 인자가 정확히 둘인 함수는 MySQL 의 IFNULL 이나 Oracle 의 NVL 이다." },
  { k: "NULL", ex0: "첫 값 10이 NULL이 아니므로 그대로 10", ex: "IFNULL(a, b) 는 a 가 NULL 일 때만 b 를 돌려준다. 10 은 NULL 이 아니므로 그대로 10 이다. 20 은 첫 값이 NULL 이었을 때 나올 값이고, 두 값을 더하지는 않는다. 표준 SQL 에서는 COALESCE(10, 20) 과 같다." },
  { k: "NULL", ex0: "첫 값이 NULL이므로 대체값 100", ex: "NVL(a, b) 는 Oracle 에서 a 가 NULL 이면 b 를 돌려주는 함수다. 첫 값이 NULL 이므로 100 이 나온다. 0 이 아니고 오류도 아니다. MySQL 의 IFNULL, 표준의 COALESCE 와 같은 역할이다." },
  { k: "빈칸", ex0: "SUM은 NULL을 무시하고 더한다. 5 + 15", ex: "집계 함수는 NULL 을 건너뛴다. SUM 은 5 와 15 만 더해 20 이다. NULL 을 0 으로 세지도, 결과를 NULL 로 만들지도 않는다. 같은 이유로 AVG 는 NULL 을 뺀 두 값의 평균 10 이 되고 COUNT(col) 은 2 다." },
  { k: "이전 행 참조", ex0: "이전 행은 LAG, 다음 행은 LEAD", ex: "정렬된 순서에서 바로 앞 행의 값을 가져오는 윈도우 함수는 LAG 다. LAG(amount) OVER (ORDER BY dt) 처럼 쓴다. 다음 행은 LEAD 다. 전날 대비 증감처럼 '앞 행과 비교' 할 때 자기 조인 없이 쓸 수 있다." },
  { k: "CTE 키워드", ex0: "CTE는 WITH cte_name AS ( ... ) 형태", ex: "CTE(공통 테이블 식)는 WITH 이름 AS (쿼리) 로 시작하고, 그 뒤 본 쿼리에서 이름을 표처럼 쓴다. 복잡한 서브쿼리를 위로 빼서 읽기 쉽게 만드는 문법이다. 재귀 CTE 는 WITH RECURSIVE 로 시작한다." },
  { k: "집계 조건 절", ex0: "집계 후 그룹 필터는 HAVING, 집계 전 행 필터는 WHERE", ex: "COUNT(*) > 5 처럼 집계 결과에 조건을 걸려면 HAVING 을 쓴다. WHERE 는 묶기 전의 행에 거는 조건이라 집계 함수를 쓸 수 없다. 순서는 WHERE → GROUP BY → HAVING 이며, 행 조건은 WHERE 에 두어야 집계할 행이 줄어 빠르다." },
  { k: "월 추출", ex0: "MONTH('2026-07-21')은 7을 반환", ex: "MySQL 에서 날짜의 월은 MONTH(날짜) 로 뽑는다. '2026-07-21' 이면 7 이다. 표준 SQL 과 PostgreSQL 은 EXTRACT(MONTH FROM 날짜) 를 쓴다. 연도는 YEAR, 일은 DAY 다." },
  { k: "YEAR", ex0: "YEAR()는 날짜에서 연도를 정수로", ex: "YEAR('2026-07-21') 은 연도 2026 을 정수로 돌려준다. 7 은 MONTH, 21 은 DAY 의 결과이고 07-21 처럼 문자열 조각을 돌려주는 함수는 아니다. 연도별로 묶어 집계할 때 GROUP BY YEAR(dt) 로 쓴다." },
  { k: "COMMIT", ex0: "COMMIT은 트랜잭션 내 모든 변경을 확정", ex: "트랜잭션 안의 변경을 확정해 영구히 남기는 명령은 COMMIT 이다. ROLLBACK 은 반대로 전부 취소한다. SAVE 와 END 는 이 뜻의 SQL 명령이 아니다. COMMIT 전까지는 다른 세션에서 변경이 보이지 않을 수 있다." },
  { k: "롤백 결과", ex0: "커밋 전 ROLLBACK은 해당 트랜잭션의 모든 변경을", ex: "COMMIT 전에 ROLLBACK 하면 그 트랜잭션에서 한 INSERT·UPDATE·DELETE 가 모두 없던 일이 된다. 일부만 남거나 자동으로 커밋되지 않고, 오류도 아니다. 일부만 되돌리고 싶으면 SAVEPOINT 를 잡아 두고 그 지점까지만 ROLLBACK 한다." },
  { k: "D", ex0: "지속성은 한 번 커밋된 변경은 장애가 나도", ex: "커밋된 데이터가 정전이나 장애 뒤에도 남아 있는 성질이 지속성(Durability)이다. ACID 의 D 다. 일관성은 규칙이 깨지지 않는 것, 격리성은 동시 트랜잭션이 서로 끼어들지 않는 것이라 장애 뒤 보존과는 다른 성질이다. WAL 이 이 보장을 구현한다." },
  { k: "NOT NULL", ex0: "NOT NULL 제약은 해당 컬럼에 값이 반드시", ex: "NULL 을 허용하지 않는 제약은 NOT NULL 이다. 값 없이 INSERT 하면 오류가 난다. UNIQUE 는 중복 금지, PRIMARY KEY 는 NOT NULL 과 UNIQUE 를 합친 것, CHECK 는 값의 범위 조건이라 각각 다른 규칙이다." },
  { k: "문법", ex0: "표준 SQL의 형변환 문법은 CAST(표현식 AS 대상타입)", ex: "표준 형변환은 CAST(값 AS 타입) 이다. 쉼표가 아니라 AS 로 잇고, 순서도 값이 먼저다. CONVERT 는 MySQL 과 SQL Server 에 있는 비표준 함수이고 인자 순서가 DB 마다 달라 CAST 를 쓰는 편이 이식성이 좋다." },
  { k: "숫자→문자", ex0: "정수 123을 문자열 '123'으로 변환", ex: "CAST(123 AS CHAR) 는 숫자 123 을 문자열 '123' 으로 바꾼다. 보기에는 같지만 타입이 달라 그 뒤 CONCAT 이나 LIKE 에 쓸 수 있다. 오류나 NULL 이 되지 않고, 정수 그대로 남지도 않는다." },
  { k: "CONCAT", ex0: "CONCAT은 인자를 문자열로 변환해 이어붙이므로", ex: "CONCAT 은 인자를 모두 문자열로 바꾼 뒤 이어 붙인다. 숫자 5 도 '5' 가 되어 '10' 뒤에 붙으니 '105' 다. 더해서 15 가 되지 않고 공백도 끼지 않는다. 숫자 덧셈을 원했다면 CAST('10' AS SIGNED) + 5 처럼 써야 한다." },
  { k: "비교 변환", ex0: "숫자와 문자열을 비교하면 문자열이 숫자로 변환", ex: "정수 열과 문자열 '5' 를 비교하면 DB 가 문자열을 숫자로 바꿔 비교하므로 col = 5 와 같은 결과가 나온다. 오류나 항상 거짓이 되지 않고, 문자 순서로 비교하지도 않는다. 다만 반대 방향(문자열 열을 숫자와 비교)은 열 전체가 변환되어 인덱스를 못 쓰므로 피한다." },
  { k: "합계 결과", ex0: "생성된 값은 1,2,3,4,5이며 합은", ex: "재귀 CTE nums 는 1 에서 시작해 n + 1 을 5 까지 만든다. 1, 2, 3, 4, 5 다섯 행이 생기고 SUM(n) 은 15 다. 종료 조건 WHERE n < 5 가 없으면 무한히 늘어나므로 재귀 CTE 에는 반드시 멈추는 조건이 있어야 한다." },
  { k: "연산자 채우기", ex0: "UNION ALL은 중복 제거 없이 두 결과의 모든 행", ex: "두 SELECT 결과를 위아래로 붙이는 연산자는 UNION 이다. UNION 만 쓰면 중복 행을 제거하고, UNION ALL 은 제거 없이 모두 남긴다. 중복 제거에는 정렬 비용이 들므로 중복이 없거나 상관없다면 UNION ALL 이 빠르다." },
  { k: "INTERSECT 행 수", ex0: "양쪽 모두에 있는 값은 3,4 뿐", ex: "INTERSECT 는 두 결과에 모두 있는 행만 남긴다. A 의 {1,2,3,4} 와 B 의 {3,4,5,6} 에 공통인 값은 3 과 4 뿐이라 2 행이다. UNION 이었다면 6 행, EXCEPT(A - B) 였다면 1 과 2 로 2 행이다." },
  { k: "총계 행 수", ex0: "ROLLUP은 항상 하나의 총계 행", ex: "ROLLUP(region) 은 region 별 소계에 더해 모든 region 을 합친 총계 행을 하나 만든다. region 이 몇 종류든 총계는 한 행이고, 그 행의 region 값은 NULL 로 표시된다. 소계 행은 종류 수만큼 3 개다." },
  { k: "CUBE 집합 수", ex0: "CUBE(n)은 2^n개 집합을 만든다", ex: "CUBE 는 열의 모든 부분집합으로 묶는다. 열이 세 개면 (a,b,c), (a,b), (a,c), (b,c), (a), (b), (c), () 의 2^3 = 8 가지다. ROLLUP(a, b, c) 였다면 계층을 따라 (a,b,c), (a,b), (a), () 네 가지만 만든다." },
  { k: "배열생성", ex0: "JSON_ARRAY는 인자들을 순서대로 담은 JSON 배열", ex: "JSON_ARRAY(1, 2, 'a') 는 인자를 순서대로 담은 JSON 배열 [1, 2, \"a\"] 를 만든다. 문자열은 큰따옴표로 감싸이는 JSON 규칙을 따른다. 중괄호는 JSON 객체(JSON_OBJECT)의 표기이고, 소괄호나 쉼표로 이은 문자열은 JSON 이 아니다." },
] };
