/* 컴파일 언어 실행형(구현) — 로컬 러너의 실제 컴파일러·테스트 러너가 판정한다.
   디버깅(고장 고치기)이 아니라 '명세를 받아 처음부터 구현하는' 문항이다.
   검증: sol 은 통과, src(빈 껍데기)는 반드시 실패해야 한다. */
module.exports = [
/* ───────────────── Java ───────────────── */
{ lang:"java", k:"LRU 캐시", cat:"internals",
  q:"용량이 정해진 <b>LRU 캐시</b>를 구현하세요. <code>get(k)</code> 은 없으면 <code>-1</code>, 있으면 값을 돌려주며 <b>최근 사용으로 갱신</b>합니다. <code>put(k, v)</code> 는 용량을 넘으면 <b>가장 오래 안 쓴 키</b>를 버립니다. 같은 키의 put 은 값을 덮고 최근 사용으로 올립니다.",
  src:"import java.util.*;\n\npublic class Sol {\n    private final int cap;\n    private final Map<Integer, Integer> map = new HashMap<>();\n\n    public Sol(int cap) { this.cap = cap; }\n\n    public int get(int k) {\n        // TODO: 없으면 -1, 있으면 최근 사용으로 갱신\n        return -1;\n    }\n\n    public void put(int k, int v) {\n        // TODO: 용량 초과 시 가장 오래 안 쓴 키를 버린다\n    }\n}",
  sol:"import java.util.*;\n\npublic class Sol {\n    private final int cap;\n    private final LinkedHashMap<Integer, Integer> map = new LinkedHashMap<>();\n\n    public Sol(int cap) { this.cap = cap; }\n\n    public int get(int k) {\n        if (!map.containsKey(k)) return -1;\n        int v = map.remove(k);\n        map.put(k, v);\n        return v;\n    }\n\n    public void put(int k, int v) {\n        if (map.containsKey(k)) map.remove(k);\n        else if (map.size() >= cap) {\n            Iterator<Integer> it = map.keySet().iterator();\n            it.next(); it.remove();\n        }\n        map.put(k, v);\n    }\n}",
  test:{"SolTest.java":"import org.junit.jupiter.api.Test;\nimport static org.junit.jupiter.api.Assertions.*;\n\nclass SolTest {\n    @Test void basic() {\n        Sol c = new Sol(2);\n        c.put(1, 10); c.put(2, 20);\n        assertEquals(10, c.get(1));\n        assertEquals(20, c.get(2));\n    }\n    @Test void evictsOldest() {\n        Sol c = new Sol(2);\n        c.put(1, 10); c.put(2, 20); c.put(3, 30);\n        assertEquals(-1, c.get(1));\n        assertEquals(30, c.get(3));\n    }\n    @Test void getRefreshes() {\n        Sol c = new Sol(2);\n        c.put(1, 10); c.put(2, 20);\n        c.get(1);\n        c.put(3, 30);\n        assertEquals(10, c.get(1));\n        assertEquals(-1, c.get(2));\n    }\n    @Test void updateExisting() {\n        Sol c = new Sol(2);\n        c.put(1, 10); c.put(1, 99); c.put(2, 20); c.put(3, 30);\n        assertEquals(-1, c.get(1));\n        assertEquals(20, c.get(2));\n    }\n    @Test void missing() {\n        assertEquals(-1, new Sol(1).get(42));\n    }\n}\n"},
  ex:"🎯 LRU 는 '<b>가장 오래 안 쓴 것을 버린다</b>' 는 규칙입니다. 핵심은 <code>get</code> 도 <b>사용</b>이라는 것 — 조회만 해도 최근 사용으로 올라가야 합니다. 이걸 빼면 LRU 가 아니라 FIFO 가 되어, 매번 쓰는 항목이 '오래 전에 넣었다' 는 이유로 쫓겨납니다.\n💡 <code>LinkedHashMap</code> 은 <b>삽입 순서를 유지</b>하므로 '지우고 다시 넣기' 로 최근 사용을 맨 뒤로 보낼 수 있습니다 — 별도 연결 리스트 없이 O(1) LRU 가 됩니다. 자바에는 <code>accessOrder=true</code> 생성자와 <code>removeEldestEntry</code> 오버라이드라는 더 짧은 길도 있습니다.\n⚠️ 같은 키의 <code>put</code> 은 <b>크기가 늘지 않으므로</b> 축출하면 안 됩니다 — 이 경계를 놓치면 용량이 남는데도 항목이 사라집니다.\n🔧 실전 캐시는 여기에 만료(TTL)·용량 기준(개수 vs 바이트)·동시성이 더해집니다. Caffeine 같은 라이브러리는 LRU 대신 <b>W-TinyLFU</b> 를 쓰는데, 한 번 스캔하고 마는 대량 조회에 캐시가 통째로 오염되는 것을 막기 위해서입니다." },

{ lang:"java", k:"다중 기준 정렬", cat:"internals",
  q:"직원 목록을 <b>부서 오름차순 → 급여 내림차순 → 이름 오름차순</b>으로 정렬하는 <code>sort</code> 를 구현하세요. 원본 리스트를 정렬해 그대로 돌려주면 됩니다.",
  src:"import java.util.*;\n\npublic class Sol {\n    public static class Emp {\n        public final String dept, name;\n        public final int salary;\n        public Emp(String dept, String name, int salary) {\n            this.dept = dept; this.name = name; this.salary = salary;\n        }\n    }\n\n    public static List<Emp> sort(List<Emp> xs) {\n        // TODO: 부서 ↑ · 급여 ↓ · 이름 ↑\n        return xs;\n    }\n}",
  sol:"import java.util.*;\nimport java.util.Comparator;\n\npublic class Sol {\n    public static class Emp {\n        public final String dept, name;\n        public final int salary;\n        public Emp(String dept, String name, int salary) {\n            this.dept = dept; this.name = name; this.salary = salary;\n        }\n    }\n\n    public static List<Emp> sort(List<Emp> xs) {\n        xs.sort(Comparator.comparing((Emp e) -> e.dept)\n                .thenComparing(Comparator.comparingInt((Emp e) -> e.salary).reversed())\n                .thenComparing(e -> e.name));\n        return xs;\n    }\n}",
  test:{"SolTest.java":"import org.junit.jupiter.api.Test;\nimport java.util.*;\nimport static org.junit.jupiter.api.Assertions.*;\n\nclass SolTest {\n    private static String names(List<Sol.Emp> xs) {\n        StringBuilder sb = new StringBuilder();\n        for (Sol.Emp e : xs) { if (sb.length() > 0) sb.append(','); sb.append(e.name); }\n        return sb.toString();\n    }\n\n    @Test void byDeptThenSalary() {\n        List<Sol.Emp> xs = new ArrayList<>(List.of(\n            new Sol.Emp(\"b\", \"x\", 100), new Sol.Emp(\"a\", \"y\", 100), new Sol.Emp(\"a\", \"z\", 200)));\n        assertEquals(\"z,y,x\", names(Sol.sort(xs)));\n    }\n    @Test void tieBrokenByName() {\n        List<Sol.Emp> xs = new ArrayList<>(List.of(\n            new Sol.Emp(\"a\", \"n2\", 500), new Sol.Emp(\"a\", \"n1\", 500)));\n        assertEquals(\"n1,n2\", names(Sol.sort(xs)));\n    }\n    @Test void salaryDescending() {\n        List<Sol.Emp> xs = new ArrayList<>(List.of(\n            new Sol.Emp(\"a\", \"low\", 1), new Sol.Emp(\"a\", \"high\", 9)));\n        assertEquals(\"high,low\", names(Sol.sort(xs)));\n    }\n    @Test void singleAndEmpty() {\n        assertEquals(\"solo\", names(Sol.sort(new ArrayList<>(List.of(new Sol.Emp(\"a\", \"solo\", 1))))));\n        assertEquals(\"\", names(Sol.sort(new ArrayList<>())));\n    }\n}\n"},
  ex:"🎯 다중 기준 정렬의 핵심은 <b>방향이 섞일 때</b>입니다. 전체에 <code>reversed()</code> 를 걸면 모든 기준이 뒤집히므로, <b>뒤집을 기준에만</b> 걸어야 합니다 — <code>comparingInt(...).reversed()</code> 를 <code>thenComparing</code> 안에 넣는 이유입니다.\n💡 <code>Comparator.comparing(...).thenComparing(...)</code> 는 '<b>앞이 같으면 뒤로</b>' 라는 규칙을 코드 순서 그대로 표현합니다. 직접 <code>compare</code> 를 쓰면 if 사다리가 되어 기준이 늘 때마다 깨지기 쉽습니다.\n⚠️ <code>comparing(e -&gt; e.salary)</code> 처럼 박싱을 쓰면 매 비교마다 <code>Integer</code> 객체가 생깁니다 — <code>comparingInt</code> 가 그 비용을 없앱니다. 정렬은 O(n log n) 번 비교하므로 이 차이가 실제로 보입니다.\n🔧 자바의 정렬은 <b>안정 정렬</b>이라, 기준을 나눠 여러 번 정렬해도 같은 결과를 얻을 수 있습니다(덜 중요한 것부터). 다만 한 번에 하는 편이 빠르고 의도도 명확합니다." },

{ lang:"java", k:"구간 병합", cat:"internals",
  q:"겹치는 구간들을 <b>병합</b>하는 <code>merge</code> 를 구현하세요. <code>[[1,3],[2,6],[8,10]]</code> → <code>[[1,6],[8,10]]</code>. <b>맞닿은 구간</b>(<code>[1,2]</code>와 <code>[2,3]</code>)도 하나로 합칩니다. 결과는 시작점 오름차순입니다.",
  src:"import java.util.*;\n\npublic class Sol {\n    public static int[][] merge(int[][] xs) {\n        // TODO: 정렬 후 겹치면 합치기\n        return xs;\n    }\n}",
  sol:"import java.util.*;\n\npublic class Sol {\n    public static int[][] merge(int[][] xs) {\n        if (xs.length == 0) return new int[0][];\n        int[][] a = xs.clone();\n        Arrays.sort(a, (p, q) -> Integer.compare(p[0], q[0]));\n        List<int[]> out = new ArrayList<>();\n        int[] cur = new int[] { a[0][0], a[0][1] };\n        for (int i = 1; i < a.length; i++) {\n            if (a[i][0] <= cur[1]) cur[1] = Math.max(cur[1], a[i][1]);\n            else { out.add(cur); cur = new int[] { a[i][0], a[i][1] }; }\n        }\n        out.add(cur);\n        return out.toArray(new int[0][]);\n    }\n}",
  test:{"SolTest.java":"import org.junit.jupiter.api.Test;\nimport java.util.*;\nimport static org.junit.jupiter.api.Assertions.*;\n\nclass SolTest {\n    @Test void overlapping() {\n        assertArrayEquals(new int[][]{{1,6},{8,10}},\n            Sol.merge(new int[][]{{1,3},{2,6},{8,10}}));\n    }\n    @Test void touching() {\n        assertArrayEquals(new int[][]{{1,3}}, Sol.merge(new int[][]{{1,2},{2,3}}));\n    }\n    @Test void unsortedInput() {\n        assertArrayEquals(new int[][]{{1,10}}, Sol.merge(new int[][]{{5,10},{1,6}}));\n    }\n    @Test void contained() {\n        assertArrayEquals(new int[][]{{1,10}}, Sol.merge(new int[][]{{1,10},{3,4}}));\n    }\n    @Test void emptyAndSingle() {\n        assertEquals(0, Sol.merge(new int[0][]).length);\n        assertArrayEquals(new int[][]{{2,5}}, Sol.merge(new int[][]{{2,5}}));\n    }\n}\n"},
  ex:"🎯 구간 병합의 첫 걸음은 <b>시작점으로 정렬</b>하는 것입니다. 정렬해 두면 '<b>다음 구간의 시작이 현재 끝보다 작거나 같으면 겹친다</b>' 는 판정 하나로 전부 처리됩니다 — 정렬하지 않으면 모든 쌍을 비교해야 합니다.\n💡 병합할 때 <code>Math.max</code> 가 필요한 이유는 <b>포함 관계</b> 때문입니다. <code>[1,10]</code> 다음에 <code>[3,4]</code> 가 오면 끝을 4로 줄이면 안 됩니다 — 테스트의 <code>contained</code> 가 이 경우를 잡습니다.\n⚠️ '맞닿음' 을 겹침으로 볼지는 <b>도메인 결정</b>입니다. 예약 시간이라면 <code>[1,2]</code> 와 <code>[2,3]</code> 은 충돌이 아니지만, 커버리지 구간이라면 이어 붙이는 게 맞습니다 — 이 문항은 후자이고, <code>&lt;=</code> 와 <code>&lt;</code> 한 글자가 그 결정입니다.\n🔧 같은 패턴이 캘린더 충돌 검사, 메모리 블록 병합, IP 대역 정리, 로그 시간대 집계에 그대로 쓰입니다. 이어서 자주 나오는 문제는 '<b>새 구간 하나 삽입</b>' 인데, 정렬이 이미 되어 있으면 O(n) 으로 풉니다." },

{ lang:"java", k:"스트림으로 그룹 집계", cat:"internals",
  q:"주문 목록을 <b>고객별로 묶어 합계</b>를 구하는 <code>totals</code> 를 구현하세요. 결과는 <code>Map&lt;String, Integer&gt;</code> 이고, <b>금액이 0 이하인 주문은 제외</b>합니다. 제외 후 주문이 하나도 없는 고객은 결과에 넣지 않습니다.",
  src:"import java.util.*;\n\npublic class Sol {\n    public static class Order {\n        public final String customer;\n        public final int amount;\n        public Order(String customer, int amount) { this.customer = customer; this.amount = amount; }\n    }\n\n    public static Map<String, Integer> totals(List<Order> xs) {\n        // TODO: 금액 0 이하 제외 후 고객별 합계\n        return new HashMap<>();\n    }\n}",
  sol:"import java.util.*;\nimport java.util.stream.*;\n\npublic class Sol {\n    public static class Order {\n        public final String customer;\n        public final int amount;\n        public Order(String customer, int amount) { this.customer = customer; this.amount = amount; }\n    }\n\n    public static Map<String, Integer> totals(List<Order> xs) {\n        return xs.stream()\n            .filter(o -> o.amount > 0)\n            .collect(Collectors.groupingBy(o -> o.customer,\n                     Collectors.summingInt(o -> o.amount)));\n    }\n}",
  test:{"SolTest.java":"import org.junit.jupiter.api.Test;\nimport java.util.*;\nimport static org.junit.jupiter.api.Assertions.*;\n\nclass SolTest {\n    @Test void sumsPerCustomer() {\n        Map<String, Integer> m = Sol.totals(List.of(\n            new Sol.Order(\"a\", 100), new Sol.Order(\"a\", 50), new Sol.Order(\"b\", 30)));\n        assertEquals(150, m.get(\"a\"));\n        assertEquals(30, m.get(\"b\"));\n    }\n    @Test void dropsNonPositive() {\n        Map<String, Integer> m = Sol.totals(List.of(\n            new Sol.Order(\"a\", 100), new Sol.Order(\"a\", -20), new Sol.Order(\"a\", 0)));\n        assertEquals(100, m.get(\"a\"));\n    }\n    @Test void customerWithOnlyBadOrdersIsAbsent() {\n        Map<String, Integer> m = Sol.totals(List.of(\n            new Sol.Order(\"a\", 10), new Sol.Order(\"ghost\", -5)));\n        assertFalse(m.containsKey(\"ghost\"));\n        assertEquals(1, m.size());\n    }\n    @Test void empty() {\n        assertTrue(Sol.totals(List.of()).isEmpty());\n    }\n}\n"},
  ex:"🎯 <code>groupingBy</code> 는 '<b>분류 함수 + 다운스트림 수집기</b>' 구조입니다. 두 번째 인자를 바꾸면 개수(<code>counting</code>)·평균(<code>averagingInt</code>)·목록(<code>toList</code>)으로 자유롭게 바뀝니다 — 이 조합을 알면 대부분의 집계가 한 줄입니다.\n💡 <b>필터가 그룹핑보다 먼저</b> 와야 합니다. 순서를 바꾸면 제외된 주문만 있는 고객이 <b>합계 0인 항목</b>으로 남습니다 — 테스트의 <code>ghost</code> 가 그 차이를 잡습니다. '없는 것' 과 '0인 것' 은 다릅니다.\n⚠️ <code>groupingBy</code> 의 기본 맵은 <code>HashMap</code> 이라 <b>순서가 보장되지 않습니다</b>. 순서가 필요하면 세 인자 버전으로 <code>TreeMap::new</code> 나 <code>LinkedHashMap::new</code> 를 지정하세요.\n🔧 스트림은 짧지만 공짜가 아닙니다 — 작은 컬렉션에서는 for 루프가 더 빠릅니다. 스트림을 쓰는 이유는 속도가 아니라 <b>의도가 드러나는 것</b>이며, 병렬 스트림은 상태를 공유하지 않을 때만 안전합니다." },

{ lang:"java", k:"제네릭 병합 정렬", cat:"internals",
  q:"정렬된 두 리스트를 <b>정렬을 유지하며 병합</b>하는 제네릭 메서드 <code>merge</code> 를 구현하세요. 시그니처는 <code>&lt;T extends Comparable&lt;T&gt;&gt; List&lt;T&gt; merge(List&lt;T&gt; a, List&lt;T&gt; b)</code> 이고, <b>같은 값이면 a 의 것을 먼저</b> 넣습니다(안정성).",
  src:"import java.util.*;\n\npublic class Sol {\n    public static <T extends Comparable<T>> List<T> merge(List<T> a, List<T> b) {\n        // TODO: 두 정렬 리스트를 한 번에 훑어 병합\n        return new ArrayList<>();\n    }\n}",
  sol:"import java.util.*;\n\npublic class Sol {\n    public static <T extends Comparable<T>> List<T> merge(List<T> a, List<T> b) {\n        List<T> out = new ArrayList<>(a.size() + b.size());\n        int i = 0, j = 0;\n        while (i < a.size() && j < b.size()) {\n            if (a.get(i).compareTo(b.get(j)) <= 0) out.add(a.get(i++));\n            else out.add(b.get(j++));\n        }\n        while (i < a.size()) out.add(a.get(i++));\n        while (j < b.size()) out.add(b.get(j++));\n        return out;\n    }\n}",
  test:{"SolTest.java":"import org.junit.jupiter.api.Test;\nimport java.util.*;\nimport static org.junit.jupiter.api.Assertions.*;\n\nclass SolTest {\n    @Test void ints() {\n        assertEquals(List.of(1, 2, 3, 4, 5, 6), Sol.merge(List.of(1, 3, 5), List.of(2, 4, 6)));\n    }\n    @Test void strings() {\n        assertEquals(List.of(\"a\", \"b\", \"c\"), Sol.merge(List.of(\"a\", \"c\"), List.of(\"b\")));\n    }\n    @Test void unevenLengths() {\n        assertEquals(List.of(1, 2, 7, 8, 9), Sol.merge(List.of(1, 8, 9), List.of(2, 7)));\n    }\n    @Test void emptySide() {\n        assertEquals(List.of(1, 2), Sol.merge(List.of(1, 2), List.of()));\n        assertEquals(List.of(3), Sol.merge(List.of(), List.of(3)));\n        assertEquals(List.of(), Sol.merge(new ArrayList<Integer>(), new ArrayList<Integer>()));\n    }\n    @Test void duplicatesKeepBoth() {\n        assertEquals(List.of(2, 2, 2), Sol.merge(List.of(2, 2), List.of(2)));\n    }\n}\n"},
  ex:"🎯 병합은 <b>양쪽을 한 번씩만 훑습니다</b> — O(n+m). '합친 뒤 다시 정렬' 은 O((n+m)log(n+m)) 이라, <b>이미 정렬되어 있다는 정보</b>를 버리는 셈입니다.\n💡 <code>&lt;=</code> 가 <b>안정성</b>을 만듭니다. 같은 값일 때 a 를 먼저 넣어야 '앞선 입력이 앞에 온다' 는 성질이 유지됩니다 — 병합 정렬이 안정 정렬인 근거가 바로 이 한 글자입니다.\n⚠️ <code>&lt;T extends Comparable&lt;T&gt;&gt;</code> 는 '비교 가능한 타입만 받는다' 는 <b>컴파일 시점 계약</b>입니다. 이게 없으면 <code>compareTo</code> 를 부를 수 없고, 런타임 캐스팅으로 우회하면 타입 안전성을 잃습니다.\n🔧 이 루틴이 외부 정렬(메모리에 안 들어가는 데이터)의 핵심이기도 합니다 — 조각별로 정렬해 파일에 쓰고, 여러 조각을 <b>k-way 병합</b>으로 합칩니다. LSM 트리의 컴팩션이 정확히 이 구조입니다." },

{ lang:"java", k:"CSV 한 줄 파싱", cat:"internals",
  q:"CSV <b>한 줄</b>을 필드 배열로 파싱하는 <code>parse</code> 를 구현하세요. 규칙: 콤마로 나누되 <b>따옴표 안의 콤마는 구분자가 아니고</b>, 따옴표 안의 <code>\"\"</code> 는 따옴표 한 개입니다. 따옴표는 결과에 포함하지 않습니다.",
  src:"import java.util.*;\n\npublic class Sol {\n    public static String[] parse(String line) {\n        // TODO: 따옴표 상태를 추적하며 한 글자씩\n        return line.split(\",\");\n    }\n}",
  sol:"import java.util.*;\n\npublic class Sol {\n    public static String[] parse(String line) {\n        List<String> out = new ArrayList<>();\n        StringBuilder cur = new StringBuilder();\n        boolean inQuote = false;\n        for (int i = 0; i < line.length(); i++) {\n            char c = line.charAt(i);\n            if (inQuote) {\n                if (c == '\"' && i + 1 < line.length() && line.charAt(i + 1) == '\"') { cur.append('\"'); i++; }\n                else if (c == '\"') inQuote = false;\n                else cur.append(c);\n            } else if (c == '\"') inQuote = true;\n            else if (c == ',') { out.add(cur.toString()); cur.setLength(0); }\n            else cur.append(c);\n        }\n        out.add(cur.toString());\n        return out.toArray(new String[0]);\n    }\n}",
  test:{"SolTest.java":"import org.junit.jupiter.api.Test;\nimport static org.junit.jupiter.api.Assertions.*;\n\nclass SolTest {\n    @Test void plain() {\n        assertArrayEquals(new String[]{\"a\", \"b\", \"c\"}, Sol.parse(\"a,b,c\"));\n    }\n    @Test void quotedComma() {\n        assertArrayEquals(new String[]{\"a\", \"b,c\", \"d\"}, Sol.parse(\"a,\\\"b,c\\\",d\"));\n    }\n    @Test void escapedQuote() {\n        assertArrayEquals(new String[]{\"say \\\"hi\\\"\"}, Sol.parse(\"\\\"say \\\"\\\"hi\\\"\\\"\\\"\"));\n    }\n    @Test void emptyFields() {\n        assertArrayEquals(new String[]{\"\", \"a\", \"\"}, Sol.parse(\",a,\"));\n    }\n    @Test void single() {\n        assertArrayEquals(new String[]{\"only\"}, Sol.parse(\"only\"));\n    }\n}\n"},
  ex:"🎯 CSV 가 '<b>콤마로 나누면 되는 형식</b>' 이라는 오해가 실무에서 가장 많은 데이터 사고를 냅니다. 주소·상품명·메모에 콤마가 들어가는 순간 <code>split(\",\")</code> 은 필드 수를 바꿔 버립니다.\n💡 해법은 <b>상태 기계</b>입니다 — '따옴표 안인가' 라는 상태 하나로 콤마의 의미가 달라집니다. 렉서와 같은 구조이며, 정규식으로는 깔끔하게 표현되지 않는 종류의 문제입니다.\n⚠️ <code>\"\"</code> 이스케이프 처리에는 <b>한 글자 앞을 내다보는</b> 판단이 필요합니다 — 다음 글자도 따옴표면 리터럴 하나, 아니면 인용 종료입니다. 이걸 빼먹으면 따옴표가 든 텍스트에서 필드가 어긋납니다.\n🔧 실전에서는 라이브러리를 쓰는 게 맞습니다 — 줄바꿈이 든 필드, BOM, 인코딩, 구분자 변형(TSV·세미콜론)까지 처리해야 하기 때문입니다. 다만 <b>왜 라이브러리가 필요한지</b>는 한 번 직접 짜 봐야 이해됩니다." },

/* ───────────────── C ───────────────── */
{ lang:"c", k:"동적 배열", cat:"internals",
  q:"용량이 자동으로 늘어나는 <b>동적 배열</b>을 구현하세요. <code>vec_push</code> 는 가득 차면 용량을 <b>2배</b>(0이면 1)로 늘리고, <code>vec_get</code> 은 범위 밖이면 <code>-1</code> 을 돌려줍니다. <code>vec_free</code> 는 메모리를 해제합니다.",
  src:"#include <stdlib.h>\n\ntypedef struct { int *data; int len; int cap; } Vec;\n\nvoid vec_push(Vec *v, int x) {\n    /* TODO: 가득 차면 용량 2배로 늘린 뒤 추가 */\n}\n\nint vec_get(Vec *v, int i) {\n    /* TODO: 범위 밖이면 -1 */\n    return 0;\n}\n\nvoid vec_free(Vec *v) {\n    /* TODO */\n}",
  sol:"#include <stdlib.h>\n\ntypedef struct { int *data; int len; int cap; } Vec;\n\nvoid vec_push(Vec *v, int x) {\n    if (v->len >= v->cap) {\n        int ncap = v->cap ? v->cap * 2 : 1;\n        int *nd = realloc(v->data, (size_t)ncap * sizeof(int));\n        if (!nd) return;\n        v->data = nd;\n        v->cap = ncap;\n    }\n    v->data[v->len++] = x;\n}\n\nint vec_get(Vec *v, int i) {\n    if (i < 0 || i >= v->len) return -1;\n    return v->data[i];\n}\n\nvoid vec_free(Vec *v) {\n    free(v->data);\n    v->data = NULL;\n    v->len = 0;\n    v->cap = 0;\n}",
  test:{"test.c":"#include <stdio.h>\n#include <stdlib.h>\n\ntypedef struct { int *data; int len; int cap; } Vec;\nvoid vec_push(Vec *v, int x);\nint vec_get(Vec *v, int i);\nvoid vec_free(Vec *v);\n\nint main(void) {\n    Vec v = {0};\n    for (int i = 0; i < 100; i++) vec_push(&v, i * 2);\n    if (v.len != 100) { printf(\"len=%d, 기대 100\\n\", v.len); return 1; }\n    if (vec_get(&v, 0) != 0 || vec_get(&v, 99) != 198) { printf(\"값이 틀렸다\\n\"); return 1; }\n    if (vec_get(&v, 100) != -1 || vec_get(&v, -1) != -1) { printf(\"범위 검사 실패\\n\"); return 1; }\n    if (v.cap < v.len) { printf(\"cap=%d < len=%d\\n\", v.cap, v.len); return 1; }\n    vec_free(&v);\n    if (v.data != NULL || v.len != 0) { printf(\"해제 후 상태가 남았다\\n\"); return 1; }\n    Vec e = {0};\n    if (vec_get(&e, 0) != -1) { printf(\"빈 배열 조회 실패\\n\"); return 1; }\n    vec_free(&e);\n    printf(\"ok\\n\");\n    return 0;\n}\n"},
  ex:"🎯 동적 배열의 핵심은 <b>2배 증가(amortized doubling)</b>입니다. 한 칸씩 늘리면 push 마다 전체 복사가 일어나 총 O(n²) 이지만, 2배로 늘리면 <b>평균 O(1)</b> 이 됩니다 — 늘리는 횟수가 log n 번뿐이기 때문입니다.\n💡 <code>realloc</code> 은 가능하면 제자리에서 늘리고, 안 되면 새로 할당해 복사한 뒤 옛 블록을 해제합니다. <b>반환값을 원래 포인터에 바로 대입하면 안 됩니다</b> — 실패 시 NULL 이 들어와 기존 데이터를 잃습니다. 임시 변수로 받는 것이 정석입니다.\n⚠️ <code>vec_free</code> 에서 포인터를 <b>NULL 로 만드는 것</b>이 이중 해제를 막습니다. C 에는 소유권을 언어가 강제하는 장치가 없으므로, '해제 후 NULL' 같은 관례가 방어선 역할을 합니다.\n🔧 C++ 의 <code>vector</code>, Go 의 <code>slice</code>, 파이썬의 <code>list</code> 가 전부 이 구조입니다 — 증가 배수만 다릅니다(1.5배를 쓰면 해제된 공간을 재사용할 수 있어 메모리 단편화에 유리합니다)." },

{ lang:"c", k:"문자열 토크나이저", cat:"internals",
  q:"구분자로 문자열을 <b>자르는 개수</b>를 세고 각 조각의 길이를 채우는 <code>tokenize</code> 를 구현하세요. <code>tokenize(s, sep, lens, max)</code> 는 조각 수를 돌려주고 <code>lens[i]</code> 에 길이를 넣습니다. <b>빈 조각도 셉니다</b>(<code>\"a,,b\"</code> 는 3개). <code>max</code> 를 넘으면 넘는 부분은 세기만 하고 기록하지 않습니다.",
  src:"#include <stddef.h>\n\nint tokenize(const char *s, char sep, int *lens, int max) {\n    /* TODO: 구분자로 조각을 세고 길이를 기록 */\n    return 0;\n}",
  sol:"#include <stddef.h>\n\nint tokenize(const char *s, char sep, int *lens, int max) {\n    int count = 0, cur = 0;\n    for (const char *p = s; ; p++) {\n        if (*p == sep || *p == '\\0') {\n            if (count < max) lens[count] = cur;\n            count++;\n            cur = 0;\n            if (*p == '\\0') break;\n        } else {\n            cur++;\n        }\n    }\n    return count;\n}",
  test:{"test.c":"#include <stdio.h>\n\nint tokenize(const char *s, char sep, int *lens, int max);\n\nint main(void) {\n    int lens[8];\n    if (tokenize(\"a,bb,ccc\", ',', lens, 8) != 3) { printf(\"개수 실패\\n\"); return 1; }\n    if (lens[0] != 1 || lens[1] != 2 || lens[2] != 3) { printf(\"길이 실패: %d %d %d\\n\", lens[0], lens[1], lens[2]); return 1; }\n    if (tokenize(\"a,,b\", ',', lens, 8) != 3 || lens[1] != 0) { printf(\"빈 조각 실패\\n\"); return 1; }\n    if (tokenize(\"\", ',', lens, 8) != 1 || lens[0] != 0) { printf(\"빈 문자열 실패\\n\"); return 1; }\n    if (tokenize(\"x\", ',', lens, 8) != 1 || lens[0] != 1) { printf(\"구분자 없음 실패\\n\"); return 1; }\n    int small[2];\n    if (tokenize(\"a,b,c,d\", ',', small, 2) != 4) { printf(\"상한 초과 시 개수 실패\\n\"); return 1; }\n    if (tokenize(\",\", ',', lens, 8) != 2) { printf(\"구분자만 있는 경우 실패\\n\"); return 1; }\n    printf(\"ok\\n\");\n    return 0;\n}\n"},
  ex:"🎯 이 함수의 설계에 C 의 관용구가 두 개 들어 있습니다 — <b>버퍼와 상한을 함께 받고</b>, <b>필요한 전체 개수를 반환</b>합니다. 상한을 넘어도 개수는 정확히 돌려주므로 호출자가 '<b>얼마나 필요한지 먼저 물어보고</b>' 재호출할 수 있습니다(<code>snprintf</code> 와 같은 계약).\n💡 <b>빈 조각을 세는지</b>가 이 부류 함수의 핵심 차이입니다. <code>strtok</code> 은 연속 구분자를 하나로 취급해 <code>\"a,,b\"</code> 를 2개로 봅니다 — CSV 처럼 <b>빈 필드가 의미 있는</b> 형식에서는 치명적입니다.\n⚠️ 루프가 <code>'\\0'</code> 을 <b>구분자처럼 처리한 뒤 종료</b>하는 구조라 마지막 조각도 자연히 기록됩니다 — 이 대칭을 놓치면 마지막 조각이 빠지거나 코드가 지저분해집니다. 빈 문자열도 '조각 1개(길이 0)' 로 일관되게 처리됩니다.\n🔧 <code>strtok</code> 은 <b>원본을 수정하고 내부 상태를 전역에 둡니다</b> — 재진입 불가라 멀티스레드에서 쓰면 안 되고, 그래서 <code>strtok_r</code> 이 따로 있습니다. 직접 짜는 편이 나은 대표적인 표준 함수입니다." },

{ lang:"c", k:"비트 플래그", cat:"internals",
  q:"32비트 정수를 <b>플래그 집합</b>으로 쓰는 함수들을 구현하세요. <code>flag_set(f, i)</code>·<code>flag_clear(f, i)</code>·<code>flag_test(f, i)</code>(0 또는 1)·<code>flag_count(f)</code>(켜진 비트 수). 인덱스는 0~31 이며 <b>범위 밖이면 원본을 그대로</b> 돌려주고 test 는 0 입니다.",
  src:"unsigned int flag_set(unsigned int f, int i) {\n    /* TODO */\n    return f;\n}\n\nunsigned int flag_clear(unsigned int f, int i) {\n    /* TODO */\n    return f;\n}\n\nint flag_test(unsigned int f, int i) {\n    /* TODO */\n    return 0;\n}\n\nint flag_count(unsigned int f) {\n    /* TODO */\n    return 0;\n}",
  sol:"unsigned int flag_set(unsigned int f, int i) {\n    if (i < 0 || i > 31) return f;\n    return f | (1u << i);\n}\n\nunsigned int flag_clear(unsigned int f, int i) {\n    if (i < 0 || i > 31) return f;\n    return f & ~(1u << i);\n}\n\nint flag_test(unsigned int f, int i) {\n    if (i < 0 || i > 31) return 0;\n    return (int)((f >> i) & 1u);\n}\n\nint flag_count(unsigned int f) {\n    int n = 0;\n    while (f) { f &= f - 1; n++; }\n    return n;\n}",
  test:{"test.c":"#include <stdio.h>\n\nunsigned int flag_set(unsigned int f, int i);\nunsigned int flag_clear(unsigned int f, int i);\nint flag_test(unsigned int f, int i);\nint flag_count(unsigned int f);\n\nint main(void) {\n    unsigned int f = 0;\n    f = flag_set(f, 0);\n    f = flag_set(f, 3);\n    if (f != 9u) { printf(\"set 실패: %u\\n\", f); return 1; }\n    if (!flag_test(f, 3) || flag_test(f, 1)) { printf(\"test 실패\\n\"); return 1; }\n    if (flag_count(f) != 2) { printf(\"count 실패: %d\\n\", flag_count(f)); return 1; }\n    f = flag_clear(f, 3);\n    if (f != 1u || flag_test(f, 3)) { printf(\"clear 실패: %u\\n\", f); return 1; }\n    unsigned int hi = flag_set(0, 31);\n    if (hi != 2147483648u) { printf(\"최상위 비트 실패: %u\\n\", hi); return 1; }\n    if (flag_count(0xFFFFFFFFu) != 32) { printf(\"전체 카운트 실패\\n\"); return 1; }\n    if (flag_set(5u, 32) != 5u || flag_test(5u, -1) != 0) { printf(\"범위 검사 실패\\n\"); return 1; }\n    if (flag_set(1u, 0) != 1u) { printf(\"이미 켜진 비트 실패\\n\"); return 1; }\n    printf(\"ok\\n\");\n    return 0;\n}\n"},
  ex:"🎯 비트 플래그는 <b>32개의 불리언을 4바이트에</b> 담습니다. 권한·상태·옵션처럼 '켜짐/꺼짐' 이 여럿일 때 메모리와 비교 비용을 크게 줄이고, 여러 플래그를 <b>한 번의 AND 로 동시에</b> 검사할 수 있습니다.\n💡 세 연산이 각각 다른 연산자를 씁니다 — 켜기는 <code>|</code>, 끄기는 <code>&amp; ~</code>, 검사는 <code>&gt;&gt;</code> 와 <code>&amp; 1</code>. 특히 끄기의 <code>~(1u &lt;&lt; i)</code> 는 '그 비트만 0이고 나머지는 1' 인 마스크라, 다른 비트를 건드리지 않습니다.\n⚠️ <code>1 &lt;&lt; 31</code> 은 <b>부호 있는 int 에서 정의되지 않은 동작</b>입니다 — 반드시 <code>1u</code> 로 부호 없는 리터럴을 쓰세요. 32 이상 시프트도 UB 라 범위 검사가 안전성의 일부입니다.\n🔧 <code>f &amp;= f - 1</code> 은 <b>가장 낮은 켜진 비트 하나를 지우는</b> 유명한 트릭(Brian Kernighan 알고리즘)입니다 — 켜진 비트 수만큼만 돌아 32번 도는 것보다 빠릅니다. 요즘 CPU 에는 <code>popcount</code> 명령이 있어 컴파일러가 한 명령으로 바꿔 주기도 합니다." },

{ lang:"c", k:"링 버퍼", cat:"internals",
  q:"고정 크기 <b>링 버퍼</b>를 구현하세요. <code>rb_push</code> 는 가득 차면 <code>0</code>(실패), 아니면 <code>1</code>. <code>rb_pop</code> 은 비었으면 <code>0</code>, 아니면 <code>1</code> 을 돌려주고 <code>*out</code> 에 값을 넣습니다. 인덱스는 배열 끝에서 <b>처음으로 감깁니다</b>.",
  src:"#define RB_CAP 4\n\ntypedef struct { int buf[RB_CAP]; int head; int tail; int size; } Ring;\n\nint rb_push(Ring *r, int x) {\n    /* TODO: 가득 차면 0 */\n    return 0;\n}\n\nint rb_pop(Ring *r, int *out) {\n    /* TODO: 비었으면 0 */\n    return 0;\n}",
  sol:"#define RB_CAP 4\n\ntypedef struct { int buf[RB_CAP]; int head; int tail; int size; } Ring;\n\nint rb_push(Ring *r, int x) {\n    if (r->size >= RB_CAP) return 0;\n    r->buf[r->tail] = x;\n    r->tail = (r->tail + 1) % RB_CAP;\n    r->size++;\n    return 1;\n}\n\nint rb_pop(Ring *r, int *out) {\n    if (r->size == 0) return 0;\n    *out = r->buf[r->head];\n    r->head = (r->head + 1) % RB_CAP;\n    r->size--;\n    return 1;\n}",
  test:{"test.c":"#include <stdio.h>\n\n#define RB_CAP 4\ntypedef struct { int buf[RB_CAP]; int head; int tail; int size; } Ring;\nint rb_push(Ring *r, int x);\nint rb_pop(Ring *r, int *out);\n\nint main(void) {\n    Ring r = {0};\n    int v;\n    if (rb_pop(&r, &v) != 0) { printf(\"빈 버퍼 pop 실패\\n\"); return 1; }\n    for (int i = 1; i <= 4; i++) if (!rb_push(&r, i)) { printf(\"push %d 실패\\n\", i); return 1; }\n    if (rb_push(&r, 5) != 0) { printf(\"가득 찬 뒤 push 가 성공했다\\n\"); return 1; }\n    if (!rb_pop(&r, &v) || v != 1) { printf(\"FIFO 실패: %d\\n\", v); return 1; }\n    if (!rb_push(&r, 5)) { printf(\"자리 생긴 뒤 push 실패\\n\"); return 1; }\n    int want[4] = {2, 3, 4, 5};\n    for (int i = 0; i < 4; i++) {\n        if (!rb_pop(&r, &v) || v != want[i]) { printf(\"감기 실패: %d, 기대 %d\\n\", v, want[i]); return 1; }\n    }\n    if (rb_pop(&r, &v) != 0) { printf(\"다 비운 뒤 pop 이 성공했다\\n\"); return 1; }\n    printf(\"ok\\n\");\n    return 0;\n}\n"},
  ex:"🎯 링 버퍼는 <b>메모리를 새로 잡지 않고</b> 큐를 만듭니다 — 인덱스가 끝에서 처음으로 감기며 같은 공간을 돌려 씁니다. 임베디드·오디오·네트워크 드라이버처럼 <b>할당이 금지되거나 비싼</b> 환경의 기본 자료구조입니다.\n💡 <code>head == tail</code> 이 '비었음' 인지 '가득 참' 인지 구분되지 않는 것이 이 구조의 고전적 난제입니다. 해법은 두 가지 — <b>size 를 따로 두거나</b>(이 문항), 한 칸을 비워 두는 것입니다.\n⚠️ 나머지 연산 <code>% RB_CAP</code> 이 감기를 만듭니다. 용량이 <b>2의 거듭제곱</b>이면 <code>&amp; (CAP-1)</code> 로 바꿀 수 있어 나눗셈 없이 처리됩니다 — 실시간 코드에서 흔히 쓰는 최적화입니다.\n🔧 생산자·소비자가 각각 하나인 경우(SPSC)에는 <b>락 없이도</b> 안전하게 만들 수 있습니다 — head 는 소비자만, tail 은 생산자만 쓰기 때문입니다. 고성능 큐가 이 성질 위에 세워집니다." },

{ lang:"c", k:"구조체 정렬", cat:"internals",
  q:"학생 배열을 <b>점수 내림차순, 같으면 이름 오름차순</b>으로 정렬하는 <code>sort_students</code> 를 구현하세요. 표준 <code>qsort</code> 를 쓰고 비교 함수를 직접 작성하세요.",
  src:"#include <stdlib.h>\n#include <string.h>\n\ntypedef struct { char name[16]; int score; } Student;\n\nvoid sort_students(Student *xs, int n) {\n    /* TODO: qsort 와 비교 함수 */\n}",
  sol:"#include <stdlib.h>\n#include <string.h>\n\ntypedef struct { char name[16]; int score; } Student;\n\nstatic int cmp_student(const void *a, const void *b) {\n    const Student *p = (const Student *)a;\n    const Student *q = (const Student *)b;\n    if (p->score != q->score) return q->score - p->score;\n    return strcmp(p->name, q->name);\n}\n\nvoid sort_students(Student *xs, int n) {\n    qsort(xs, (size_t)n, sizeof(Student), cmp_student);\n}",
  test:{"test.c":"#include <stdio.h>\n#include <string.h>\n\ntypedef struct { char name[16]; int score; } Student;\nvoid sort_students(Student *xs, int n);\n\nint main(void) {\n    Student xs[5] = { {\"bob\", 80}, {\"amy\", 95}, {\"cat\", 80}, {\"dan\", 70}, {\"eve\", 95} };\n    sort_students(xs, 5);\n    const char *want[5] = { \"amy\", \"eve\", \"bob\", \"cat\", \"dan\" };\n    for (int i = 0; i < 5; i++) {\n        if (strcmp(xs[i].name, want[i]) != 0) {\n            printf(\"%d번째가 %s, 기대 %s\\n\", i, xs[i].name, want[i]);\n            return 1;\n        }\n    }\n    Student one[1] = { {\"solo\", 1} };\n    sort_students(one, 1);\n    if (strcmp(one[0].name, \"solo\") != 0) { printf(\"단일 원소 실패\\n\"); return 1; }\n    sort_students(xs, 0);\n    printf(\"ok\\n\");\n    return 0;\n}\n"},
  ex:"🎯 <code>qsort</code> 의 비교 함수는 <b><code>const void *</code></b> 를 받습니다 — 타입을 모르는 범용 정렬이라, 안에서 실제 타입으로 캐스팅하는 것이 호출 규약입니다. 이 인터페이스가 C 에서 '제네릭' 을 흉내 내는 표준 방식입니다.\n💡 반환값의 규칙은 '<b>음수면 a 가 앞</b>, 0이면 같음, 양수면 b 가 앞' 입니다. 내림차순은 <code>q->score - p->score</code> 처럼 <b>순서를 뒤집어</b> 만듭니다.\n⚠️ 뺄셈으로 비교하는 것은 <b>오버플로 위험</b>이 있습니다 — 점수처럼 작은 값은 안전하지만, 값이 크면 <code>(a &gt; b) - (a &lt; b)</code> 형태가 안전합니다. 오래된 코드베이스에서 이 버그가 조용히 잠들어 있는 경우가 많습니다.\n🔧 <code>qsort</code> 는 <b>안정 정렬이 아닙니다</b> — 같은 점수의 순서가 보장되지 않으므로, 이 문항처럼 <b>2차 기준을 명시</b>해야 결과가 결정적입니다. 안정성이 필요하면 원래 인덱스를 마지막 기준으로 넣는 것이 표준 트릭입니다." },

/* ───────────────── C++ ───────────────── */
{ lang:"cpp", k:"RAII 자원 관리", cat:"internals",
  q:"<b>RAII</b> 로 자원을 관리하는 <code>Guard</code> 를 구현하세요. 생성자에서 카운터를 <b>+1</b>, 소멸자에서 <b>−1</b> 합니다. 복사는 <b>금지</b>하고 이동은 허용하되, <b>이동된 원본은 소멸 시 감소시키지 않아야</b> 합니다.",
  src:"#pragma once\n\nstruct Guard {\n    int *counter;\n    explicit Guard(int *c) : counter(c) { /* TODO: 증가 */ }\n    ~Guard() { /* TODO: 감소 (이동된 뒤라면 하지 않는다) */ }\n    // TODO: 복사 금지 · 이동 허용\n};",
  sol:"#pragma once\n#include <utility>\n\nstruct Guard {\n    int *counter;\n    explicit Guard(int *c) : counter(c) { if (counter) ++(*counter); }\n    Guard(const Guard &) = delete;\n    Guard &operator=(const Guard &) = delete;\n    Guard(Guard &&other) noexcept : counter(other.counter) { other.counter = nullptr; }\n    Guard &operator=(Guard &&other) noexcept {\n        if (this != &other) {\n            if (counter) --(*counter);\n            counter = other.counter;\n            other.counter = nullptr;\n        }\n        return *this;\n    }\n    ~Guard() { if (counter) --(*counter); }\n};",
  srcName:"sol.h",
  test:{"test.cpp":"#include \"catch.hpp\"\n#include <utility>\n#include <type_traits>\n#include \"sol.h\"\n\nTEST_CASE(\"스코프를 벗어나면 해제된다\") {\n    int c = 0;\n    { Guard g(&c); REQUIRE(c == 1); }\n    REQUIRE(c == 0);\n}\n\nTEST_CASE(\"이동한 원본은 감소시키지 않는다\") {\n    int c = 0;\n    {\n        Guard a(&c);\n        Guard b(std::move(a));\n        REQUIRE(c == 1);\n    }\n    REQUIRE(c == 0);\n}\n\nTEST_CASE(\"복사는 금지된다\") {\n    REQUIRE_FALSE(std::is_copy_constructible<Guard>::value);\n}\n\nTEST_CASE(\"여러 개가 각각 센다\") {\n    int c = 0;\n    { Guard a(&c); Guard b(&c); REQUIRE(c == 2); }\n    REQUIRE(c == 0);\n}\n"},
  ex:"🎯 RAII 는 '<b>자원의 수명을 객체의 수명에 묶는다</b>' 는 C++ 의 근본 아이디어입니다. 예외가 나든 일찍 return 하든 소멸자는 <b>반드시</b> 불리므로, '해제를 잊는' 종류의 버그가 구조적으로 사라집니다.\n💡 이동을 지원하려면 <b>원본을 빈 상태로</b> 만들어야 합니다 — 여기서는 포인터를 nullptr 로. 안 그러면 원본과 이동된 객체가 <b>둘 다 소멸하며 두 번 감소</b>시킵니다. 실제 자원이라면 이중 해제(크래시)입니다.\n⚠️ 복사를 <code>= delete</code> 로 막는 것이 중요합니다. 자원을 소유하는 객체가 얕게 복사되면 두 객체가 같은 자원을 가리키고, 먼저 소멸한 쪽이 해제해 <b>나머지가 댕글링</b>이 됩니다 — 컴파일 오류로 만드는 것이 최선의 방어입니다.\n🔧 이것이 <code>unique_ptr</code>·<code>lock_guard</code>·<code>fstream</code> 이 동작하는 방식입니다. '<b>5의 법칙</b>' — 소멸자·복사 생성자·복사 대입·이동 생성자·이동 대입 중 하나를 정의하면 나머지도 고려해야 한다 — 가 여기서 나옵니다." },

{ lang:"cpp", k:"템플릿과 최댓값 선택", cat:"internals",
  q:"컨테이너에서 <b>키 함수 기준 최댓값</b>을 찾는 템플릿 <code>maxBy</code> 를 구현하세요. <code>maxBy(v, f)</code> 는 <code>f(x)</code> 가 가장 큰 원소를 돌려주고, <b>동점이면 앞선 것</b>을 고릅니다. 빈 컨테이너면 <code>std::runtime_error</code> 를 던집니다.",
  src:"#pragma once\n#include <vector>\n#include <stdexcept>\n\ntemplate <typename T, typename F>\nT maxBy(const std::vector<T> &v, F f) {\n    // TODO: f(x) 가 최대인 원소, 동점이면 앞선 것\n    return T();\n}",
  sol:"#pragma once\n#include <vector>\n#include <stdexcept>\n#include <cstddef>\n\ntemplate <typename T, typename F>\nT maxBy(const std::vector<T> &v, F f) {\n    if (v.empty()) throw std::runtime_error(\"empty\");\n    const T *best = &v[0];\n    auto bestKey = f(v[0]);\n    for (std::size_t i = 1; i < v.size(); ++i) {\n        auto k = f(v[i]);\n        if (k > bestKey) { bestKey = k; best = &v[i]; }\n    }\n    return *best;\n}",
  srcName:"sol.h",
  test:{"test.cpp":"#include \"catch.hpp\"\n#include <vector>\n#include <string>\n#include <stdexcept>\n#include \"sol.h\"\n\nTEST_CASE(\"길이가 가장 긴 문자열\") {\n    std::vector<std::string> v{\"a\", \"abc\", \"ab\"};\n    REQUIRE(maxBy(v, [](const std::string &s) { return s.size(); }) == \"abc\");\n}\n\nTEST_CASE(\"동점이면 앞선 것\") {\n    std::vector<std::string> v{\"xy\", \"ab\"};\n    REQUIRE(maxBy(v, [](const std::string &s) { return s.size(); }) == \"xy\");\n}\n\nTEST_CASE(\"음수 키도 다룬다\") {\n    std::vector<int> v{-5, -1, -9};\n    REQUIRE(maxBy(v, [](int x) { return x; }) == -1);\n}\n\nTEST_CASE(\"빈 컨테이너는 예외\") {\n    std::vector<int> v;\n    REQUIRE_THROWS_AS(maxBy(v, [](int x) { return x; }), std::runtime_error);\n}\n"},
  ex:"🎯 템플릿은 <b>타입마다 코드를 생성</b>합니다 — <code>maxBy</code> 하나로 문자열·정수·구조체를 모두 처리하면서, 각각에 대해 최적화된 코드가 나옵니다(런타임 다형성과 다른 지점).\n💡 키 함수를 <b>매 비교마다 다시 부르지 않는 것</b>이 중요합니다. 최고 키를 변수에 들고 있으면 호출이 n 번이지만, 비교마다 양쪽을 부르면 2n 번입니다 — 키 계산이 비싸면(문자열 파싱·거리 계산) 두 배 차이가 그대로 드러납니다.\n⚠️ '동점이면 앞선 것' 을 만들려면 <code>&gt;</code> 를 써야 합니다(<code>&gt;=</code> 면 뒤엣것으로 바뀝니다). <code>std::max_element</code> 도 같은 규칙으로 첫 번째를 돌려줍니다 — 한 글자가 계약을 바꿉니다.\n🔧 C++20 이라면 <code>std::ranges::max_element(v, {}, f)</code> 로 projection 을 넘겨 같은 일을 합니다. 직접 짜 보면 표준 알고리즘의 <b>비교자·투영</b> 인터페이스가 왜 그 모양인지 이해됩니다." },

{ lang:"cpp", k:"이동 의미론", cat:"internals",
  q:"버퍼를 소유하는 <code>Buf</code> 를 구현하세요. 복사 생성자는 <b>데이터를 복사</b>하고 <code>g_copies</code> 를 증가, 이동 생성자는 <b>포인터만 훔치고</b> <code>g_moves</code> 를 증가시킵니다(전역 카운터, 테스트가 정의). 이동된 원본의 <code>data</code> 는 <code>nullptr</code> 이어야 합니다.",
  src:"#pragma once\n#include <cstddef>\n\nextern int g_copies;\nextern int g_moves;\n\nstruct Buf {\n    int *data;\n    std::size_t n;\n    explicit Buf(std::size_t n_) : data(new int[n_]()), n(n_) {}\n    // TODO: 복사 생성자(깊은 복사 + g_copies), 이동 생성자(포인터 이동 + g_moves)\n    ~Buf() { delete[] data; }\n};",
  sol:"#pragma once\n#include <cstddef>\n#include <algorithm>\n\nextern int g_copies;\nextern int g_moves;\n\nstruct Buf {\n    int *data;\n    std::size_t n;\n    explicit Buf(std::size_t n_) : data(new int[n_]()), n(n_) {}\n    Buf(const Buf &o) : data(new int[o.n]), n(o.n) {\n        std::copy(o.data, o.data + o.n, data);\n        ++g_copies;\n    }\n    Buf(Buf &&o) noexcept : data(o.data), n(o.n) {\n        o.data = nullptr;\n        o.n = 0;\n        ++g_moves;\n    }\n    ~Buf() { delete[] data; }\n};",
  srcName:"sol.h",
  test:{"test.cpp":"#include \"catch.hpp\"\n#include <utility>\n#include \"sol.h\"\n\nint g_copies = 0;\nint g_moves = 0;\n\nTEST_CASE(\"복사는 깊은 복사다\") {\n    g_copies = 0; g_moves = 0;\n    Buf a(4);\n    a.data[0] = 7;\n    Buf b(a);\n    b.data[0] = 9;\n    REQUIRE(a.data[0] == 7);\n    REQUIRE(g_copies == 1);\n}\n\nTEST_CASE(\"이동은 포인터를 훔친다\") {\n    g_copies = 0; g_moves = 0;\n    Buf a(4);\n    a.data[1] = 5;\n    Buf b(std::move(a));\n    REQUIRE(a.data == nullptr);\n    REQUIRE(b.data[1] == 5);\n    REQUIRE(g_moves == 1);\n    REQUIRE(g_copies == 0);\n}\n\nTEST_CASE(\"이동 후 소멸이 안전하다\") {\n    g_copies = 0; g_moves = 0;\n    { Buf a(2); Buf b(std::move(a)); }\n    REQUIRE(g_moves == 1);\n}\n"},
  ex:"🎯 이동 의미론은 '<b>어차피 버릴 객체의 자원을 훔쳐 오는</b>' 최적화입니다. 100만 원소 벡터를 반환할 때 복사하면 100만 번 복사지만, 이동하면 <b>포인터 몇 개</b>만 옮깁니다.\n💡 이동 생성자는 반드시 <b>원본을 유효하지만 비어 있는 상태</b>로 만들어야 합니다 — 여기서는 nullptr. 원본의 소멸자가 여전히 불리기 때문에, 포인터를 비우지 않으면 <b>같은 메모리를 두 번 delete</b> 합니다.\n⚠️ 이동 생성자에는 <code>noexcept</code> 를 붙여야 합니다. <code>std::vector</code> 는 재할당 시 이동 생성자가 noexcept 일 때만 이동을 쓰고, 아니면 <b>안전을 위해 복사</b>합니다 — 강한 예외 보장을 지키기 위해서입니다. 이 키워드 하나로 성능이 갈립니다.\n🔧 <code>std::move</code> 는 <b>아무것도 이동시키지 않습니다</b> — 그냥 우측값으로 캐스팅해 '이동 생성자를 골라라' 고 알릴 뿐입니다. 이름이 오해를 부르는 대표적인 표준 함수입니다." },

{ lang:"cpp", k:"상위 k개 뽑기", cat:"internals",
  q:"점수 배열에서 <b>상위 k개</b>를 내림차순으로 돌려주는 <code>topK</code> 를 구현하세요. <code>k</code> 가 크기보다 크면 전부, 0 이하면 빈 벡터입니다. 전체 정렬 대신 <b>부분 정렬</b>(<code>partial_sort</code> 또는 <code>nth_element</code>)을 쓰세요.",
  src:"#pragma once\n#include <vector>\n#include <algorithm>\n\ninline std::vector<int> topK(std::vector<int> v, int k) {\n    // TODO: 부분 정렬로 상위 k개\n    return {};\n}",
  sol:"#pragma once\n#include <vector>\n#include <algorithm>\n#include <functional>\n#include <cstddef>\n\ninline std::vector<int> topK(std::vector<int> v, int k) {\n    if (k <= 0) return {};\n    if (k > static_cast<int>(v.size())) k = static_cast<int>(v.size());\n    std::partial_sort(v.begin(), v.begin() + k, v.end(), std::greater<int>());\n    v.resize(static_cast<std::size_t>(k));\n    return v;\n}",
  srcName:"sol.h",
  test:{"test.cpp":"#include \"catch.hpp\"\n#include <vector>\n#include \"sol.h\"\n\nTEST_CASE(\"상위 3개\") {\n    REQUIRE(topK({5, 1, 9, 3, 7}, 3) == std::vector<int>{9, 7, 5});\n}\n\nTEST_CASE(\"k 가 크기보다 크면 전부\") {\n    REQUIRE(topK({2, 1}, 5) == std::vector<int>{2, 1});\n}\n\nTEST_CASE(\"k 가 0 이하\") {\n    REQUIRE(topK({1, 2}, 0).empty());\n    REQUIRE(topK({1, 2}, -1).empty());\n}\n\nTEST_CASE(\"중복 값\") {\n    REQUIRE(topK({4, 4, 1}, 2) == std::vector<int>{4, 4});\n}\n\nTEST_CASE(\"빈 입력\") {\n    REQUIRE(topK({}, 3).empty());\n}\n"},
  ex:"🎯 '상위 k개' 에 <b>전체 정렬</b>은 과합니다. 정렬은 O(n log n) 이지만 <code>partial_sort</code> 는 O(n log k) — k 가 작으면(상위 10개, 100만 건) 차이가 큽니다. <b>필요한 만큼만 정렬한다</b>는 발상입니다.\n💡 순서가 필요 없다면 <code>nth_element</code> 가 더 빠릅니다(평균 O(n)) — k번째 원소를 제자리에 놓고 앞뒤를 대략 나눌 뿐, 각 부분을 정렬하지는 않습니다. '상위 k개를 정렬된 상태로' 원할 때만 partial_sort 를 씁니다.\n⚠️ <code>k</code> 를 <b>먼저 클램프</b>하지 않으면 <code>v.begin() + k</code> 가 범위를 벗어나 UB 입니다. 경계 처리가 알고리즘 선택보다 먼저입니다.\n🔧 스트리밍 데이터에서는 <b>크기 k 의 최소 힙</b>을 쓰는 것이 표준입니다 — 전체를 메모리에 두지 않고 O(n log k) 로 상위 k개를 유지합니다. '실시간 랭킹' 이 그 구조로 돌아갑니다." },

{ lang:"cpp", k:"연관 컨테이너와 사용자 정의 순서", cat:"internals",
  q:"버전 번호를 <b>정렬된 집합</b>으로 관리하세요. <code>Version{major, minor}</code> 을 <code>std::set</code> 에 담아 <b>major 오름차순, 같으면 minor 오름차순</b>으로 정렬되게 하고, <code>insertAll</code> 은 중복을 제거한 정렬 결과를 <code>\"1.2,2.0\"</code> 형식 문자열로 돌려줍니다.",
  src:"#pragma once\n#include <set>\n#include <string>\n#include <vector>\n\nstruct Version {\n    int major, minor;\n    // TODO: set 이 정렬할 수 있도록 순서를 정의하세요\n};\n\ninline std::string insertAll(const std::vector<Version> &vs) {\n    // TODO: set 에 넣고 \"1.2,2.0\" 형식으로\n    return \"\";\n}",
  sol:"#pragma once\n#include <set>\n#include <string>\n#include <vector>\n\nstruct Version {\n    int major, minor;\n    bool operator<(const Version &o) const {\n        if (major != o.major) return major < o.major;\n        return minor < o.minor;\n    }\n};\n\ninline std::string insertAll(const std::vector<Version> &vs) {\n    std::set<Version> s(vs.begin(), vs.end());\n    std::string out;\n    for (const auto &v : s) {\n        if (!out.empty()) out += \",\";\n        out += std::to_string(v.major) + \".\" + std::to_string(v.minor);\n    }\n    return out;\n}",
  srcName:"sol.h",
  test:{"test.cpp":"#include \"catch.hpp\"\n#include <vector>\n#include <string>\n#include \"sol.h\"\n\nTEST_CASE(\"정렬된다\") {\n    REQUIRE(insertAll({{2,0},{1,2},{1,10}}) == \"1.2,1.10,2.0\");\n}\n\nTEST_CASE(\"중복이 제거된다\") {\n    REQUIRE(insertAll({{1,0},{1,0},{1,0}}) == \"1.0\");\n}\n\nTEST_CASE(\"minor 로 갈린다\") {\n    REQUIRE(insertAll({{1,5},{1,1}}) == \"1.1,1.5\");\n}\n\nTEST_CASE(\"빈 입력\") {\n    REQUIRE(insertAll({}) == \"\");\n}\n"},
  ex:"🎯 <code>std::set</code>·<code>map</code> 은 <b>순서가 있는</b> 컨테이너라 원소 타입에 '작다' 의 정의가 필요합니다. <code>operator&lt;</code> 를 정의하거나 비교자를 템플릿 인자로 넘기는 두 가지 길이 있습니다.\n💡 이 비교는 <b>엄격한 약한 순서</b>를 만족해야 합니다 — 특히 <code>!(a&lt;b) &amp;&amp; !(b&lt;a)</code> 이면 '같다' 로 취급됩니다. 그래서 <b>중복 제거의 기준도 이 비교</b>이며, 별도의 <code>operator==</code> 는 쓰이지 않습니다.\n⚠️ 잘못된 비교자(예: 항상 true 를 반환)는 컴파일은 되지만 <b>런타임에 트리를 망가뜨립니다</b> — 무한 루프나 크래시가 나며 원인 추적이 매우 어렵습니다. 1.10 이 1.2 보다 뒤에 오는 것(문자열 비교라면 반대)도 이 정의가 결정합니다.\n🔧 순서가 필요 없다면 <code>unordered_set</code> 이 평균 O(1) 로 더 빠르지만, 그때는 <b>해시 함수</b>를 제공해야 합니다. '정렬이 필요한가' 가 두 컨테이너를 가르는 질문입니다." },

/* ───────────────── Go ───────────────── */
{ lang:"go", k:"인터페이스와 다형성", cat:"internals",
  q:"도형 면적을 다루는 인터페이스를 구현하세요. <code>Shape</code> 인터페이스에 <code>Area() float64</code> 를 두고 <code>Rect</code>·<code>Circle</code> 이 구현하며, <code>TotalArea([]Shape) float64</code> 는 합계를 돌려줍니다. 원주율은 <code>math.Pi</code> 를 쓰세요.",
  src:"package ex\n\ntype Shape interface {\n\tArea() float64\n}\n\ntype Rect struct{ W, H float64 }\ntype Circle struct{ R float64 }\n\n// TODO: Rect·Circle 에 Area 를 구현하고 TotalArea 를 완성하세요\n\nfunc (r Rect) Area() float64 { return 0 }\n\nfunc (c Circle) Area() float64 { return 0 }\n\nfunc TotalArea(shapes []Shape) float64 {\n\treturn 0\n}",
  sol:"package ex\n\nimport \"math\"\n\ntype Shape interface {\n\tArea() float64\n}\n\ntype Rect struct{ W, H float64 }\ntype Circle struct{ R float64 }\n\nfunc (r Rect) Area() float64 { return r.W * r.H }\n\nfunc (c Circle) Area() float64 { return math.Pi * c.R * c.R }\n\nfunc TotalArea(shapes []Shape) float64 {\n\tsum := 0.0\n\tfor _, s := range shapes {\n\t\tsum += s.Area()\n\t}\n\treturn sum\n}",
  test:{"go.mod":"module ex\n\ngo 1.21\n","sol_test.go":"package ex\n\nimport (\n\t\"math\"\n\t\"testing\"\n)\n\nfunc TestRect(t *testing.T) {\n\tif got := (Rect{W: 3, H: 4}).Area(); got != 12 {\n\t\tt.Fatalf(\"got %v, want 12\", got)\n\t}\n}\n\nfunc TestCircle(t *testing.T) {\n\tgot := (Circle{R: 2}).Area()\n\tif math.Abs(got-4*math.Pi) > 1e-9 {\n\t\tt.Fatalf(\"got %v, want %v\", got, 4*math.Pi)\n\t}\n}\n\nfunc TestTotal(t *testing.T) {\n\tgot := TotalArea([]Shape{Rect{W: 2, H: 3}, Rect{W: 1, H: 1}})\n\tif got != 7 {\n\t\tt.Fatalf(\"got %v, want 7\", got)\n\t}\n}\n\nfunc TestMixed(t *testing.T) {\n\tgot := TotalArea([]Shape{Rect{W: 1, H: 1}, Circle{R: 1}})\n\tif math.Abs(got-(1+math.Pi)) > 1e-9 {\n\t\tt.Fatalf(\"got %v\", got)\n\t}\n}\n\nfunc TestEmpty(t *testing.T) {\n\tif got := TotalArea(nil); got != 0 {\n\t\tt.Fatalf(\"got %v, want 0\", got)\n\t}\n}\n"},
  ex:"🎯 Go 의 인터페이스는 <b>암묵적</b>입니다 — <code>implements</code> 선언 없이 <b>메서드 집합이 맞으면</b> 그 인터페이스입니다. 그래서 <b>인터페이스를 쓰는 쪽에서 정의</b>할 수 있고, 남의 패키지 타입도 내 인터페이스에 끼워 넣을 수 있습니다.\n💡 그 결과 인터페이스가 <b>작아집니다</b>. <code>io.Reader</code> 는 메서드가 하나뿐인데도 Go 생태계 전체를 관통합니다 — '<b>인터페이스가 클수록 추상화가 약하다</b>' 는 Go 격언이 여기서 나옵니다.\n⚠️ 값 수신자(<code>func (r Rect)</code>)와 포인터 수신자(<code>func (r *Rect)</code>)의 차이가 중요합니다 — 포인터 수신자로 정의하면 <code>Rect{}</code> 값은 인터페이스를 만족하지 <b>않고</b> <code>&amp;Rect{}</code> 만 만족합니다. 컴파일 오류 메시지가 이 경우 특히 헷갈립니다.\n🔧 인터페이스 값은 <b>(타입, 값)</b> 쌍입니다 — 그래서 nil 포인터를 담은 인터페이스는 <code>iface != nil</code> 입니다. Go 의 가장 유명한 함정이며, 에러를 인터페이스로 다루는 코드에서 자주 물립니다." },

{ lang:"go", k:"커스텀 에러와 errors.As", cat:"internals",
  q:"검증 실패를 <b>필드 정보를 담은 에러</b>로 표현하세요. <code>ValidationError{Field, Msg}</code> 가 <code>error</code> 를 구현하고(<code>\"field: msg\"</code> 형식), <code>Validate(name string, age int)</code> 는 이름이 비었으면 <code>name</code> 필드(<code>required</code>), 나이가 음수면 <code>age</code> 필드 에러를 돌려줍니다. <code>FieldOf(err)</code> 는 <code>errors.As</code> 로 필드명을 꺼내고 아니면 빈 문자열입니다.",
  src:"package ex\n\ntype ValidationError struct {\n\tField string\n\tMsg   string\n}\n\n// TODO: Error() 구현\n\nfunc Validate(name string, age int) error {\n\t// TODO: 이름 → 나이 순으로 검사\n\treturn nil\n}\n\nfunc FieldOf(err error) string {\n\t// TODO: errors.As 로 필드명 꺼내기\n\treturn \"\"\n}",
  sol:"package ex\n\nimport \"errors\"\n\ntype ValidationError struct {\n\tField string\n\tMsg   string\n}\n\nfunc (e *ValidationError) Error() string { return e.Field + \": \" + e.Msg }\n\nfunc Validate(name string, age int) error {\n\tif name == \"\" {\n\t\treturn &ValidationError{Field: \"name\", Msg: \"required\"}\n\t}\n\tif age < 0 {\n\t\treturn &ValidationError{Field: \"age\", Msg: \"must be >= 0\"}\n\t}\n\treturn nil\n}\n\nfunc FieldOf(err error) string {\n\tvar ve *ValidationError\n\tif errors.As(err, &ve) {\n\t\treturn ve.Field\n\t}\n\treturn \"\"\n}",
  test:{"go.mod":"module ex\n\ngo 1.21\n","sol_test.go":"package ex\n\nimport (\n\t\"errors\"\n\t\"fmt\"\n\t\"testing\"\n)\n\nfunc TestValid(t *testing.T) {\n\tif err := Validate(\"kim\", 20); err != nil {\n\t\tt.Fatalf(\"정상 입력인데 에러: %v\", err)\n\t}\n}\n\nfunc TestNameField(t *testing.T) {\n\terr := Validate(\"\", 20)\n\tif FieldOf(err) != \"name\" {\n\t\tt.Fatalf(\"got %q\", FieldOf(err))\n\t}\n}\n\nfunc TestAgeField(t *testing.T) {\n\terr := Validate(\"kim\", -1)\n\tif FieldOf(err) != \"age\" {\n\t\tt.Fatalf(\"got %q\", FieldOf(err))\n\t}\n}\n\nfunc TestWrapped(t *testing.T) {\n\terr := fmt.Errorf(\"saving user: %w\", Validate(\"\", 1))\n\tif FieldOf(err) != \"name\" {\n\t\tt.Fatalf(\"감싼 에러에서 못 찾았다: %q\", FieldOf(err))\n\t}\n}\n\nfunc TestOther(t *testing.T) {\n\tif FieldOf(errors.New(\"other\")) != \"\" {\n\t\tt.Fatal(\"관계없는 에러에서 필드를 찾았다\")\n\t}\n\tif FieldOf(nil) != \"\" {\n\t\tt.Fatal(\"nil 에서 필드를 찾았다\")\n\t}\n}\n\nfunc TestMessage(t *testing.T) {\n\terr := Validate(\"\", 1)\n\tif err.Error() != \"name: required\" {\n\t\tt.Fatalf(\"got %q\", err.Error())\n\t}\n}\n"},
  ex:"🎯 에러에 <b>구조</b>를 주면 호출자가 프로그래밍 방식으로 반응할 수 있습니다 — 문자열을 파싱하는 대신 <code>errors.As</code> 로 타입을 꺼내 필드명을 얻고, 그 필드를 UI 에서 하이라이트하는 식입니다.\n💡 <code>errors.As</code> 는 <b>Unwrap 체인을 따라가며</b> 해당 타입을 찾습니다 — 그래서 상위 계층이 <code>%w</code> 로 컨텍스트를 덧붙여도 원래 타입을 잃지 않습니다. 값 비교인 <code>errors.Is</code> 와 타입 추출인 <code>errors.As</code> 의 역할 분담이 여기 있습니다.\n⚠️ 포인터 수신자로 <code>Error()</code> 를 정의했다면 <b>포인터를 돌려줘야</b> 합니다(<code>&amp;ValidationError{}</code>). 그리고 <code>errors.As</code> 의 두 번째 인자는 <b>포인터의 포인터</b>(<code>&amp;ve</code>)여야 합니다 — 여기 넣을 대상을 채워 주기 때문입니다.\n🔧 흔한 함정: 에러를 담는 변수를 <b>구체 타입</b>으로 선언하고 nil 을 반환하면, 인터페이스에 담기는 순간 <code>err != nil</code> 이 됩니다. 에러는 항상 <code>error</code> 타입 변수로 다루세요." },

{ lang:"go", k:"defer 와 panic 회복", cat:"internals",
  q:"패닉을 잡아 에러로 바꾸는 <code>SafeDiv(a, b int) (result int, err error)</code> 를 구현하세요. <code>b</code> 가 0이면 런타임 패닉이 나는데, <b><code>defer</code> + <code>recover</code></b> 로 잡아 <code>err</code> 에 담고 <code>result</code> 는 0 이어야 합니다. 정상일 때는 몫과 <code>nil</code> 입니다.",
  src:"package ex\n\nfunc SafeDiv(a, b int) (result int, err error) {\n\t// TODO: defer + recover 로 패닉을 에러로\n\treturn a / b, nil\n}",
  sol:"package ex\n\nimport \"fmt\"\n\nfunc SafeDiv(a, b int) (result int, err error) {\n\tdefer func() {\n\t\tif r := recover(); r != nil {\n\t\t\tresult = 0\n\t\t\terr = fmt.Errorf(\"복구됨: %v\", r)\n\t\t}\n\t}()\n\treturn a / b, nil\n}",
  test:{"go.mod":"module ex\n\ngo 1.21\n","sol_test.go":"package ex\n\nimport \"testing\"\n\nfunc TestNormal(t *testing.T) {\n\tgot, err := SafeDiv(10, 2)\n\tif err != nil || got != 5 {\n\t\tt.Fatalf(\"got %d, %v\", got, err)\n\t}\n}\n\nfunc TestZero(t *testing.T) {\n\tgot, err := SafeDiv(1, 0)\n\tif err == nil {\n\t\tt.Fatal(\"0으로 나눴는데 에러가 없다\")\n\t}\n\tif got != 0 {\n\t\tt.Fatalf(\"패닉 시 결과는 0이어야 한다: %d\", got)\n\t}\n}\n\nfunc TestStillUsableAfterPanic(t *testing.T) {\n\tSafeDiv(1, 0)\n\tgot, err := SafeDiv(9, 3)\n\tif err != nil || got != 3 {\n\t\tt.Fatalf(\"패닉 이후 정상 호출 실패: %d, %v\", got, err)\n\t}\n}\n\nfunc TestNegative(t *testing.T) {\n\tgot, _ := SafeDiv(-9, 3)\n\tif got != -3 {\n\t\tt.Fatalf(\"got %d\", got)\n\t}\n}\n"},
  ex:"🎯 <code>recover</code> 는 <b><code>defer</code> 안에서만</b> 동작합니다 — 패닉이 스택을 되감는 중에 defer 가 실행되고, 거기서 recover 를 부르면 되감기가 멈춥니다. 다른 곳에서 부르면 그냥 nil 을 돌려줍니다.\n💡 <b>이름 있는 반환값</b>(<code>result int, err error</code>)이 필수입니다. defer 는 return 값이 정해진 <b>뒤에</b> 실행되므로, 이름이 있어야 그 값을 고쳐 쓸 수 있습니다 — 익명 반환값이면 recover 는 되지만 에러를 돌려줄 방법이 없습니다.\n⚠️ Go 에서 패닉은 <b>예외가 아닙니다</b>. 예상 가능한 실패(파일 없음·검증 실패)는 에러 값으로 다루고, 패닉은 '프로그램 논리가 깨졌다' 는 신호로 남겨 둡니다 — 모든 함수를 recover 로 감싸는 것은 Go 스타일이 아닙니다.\n🔧 정당한 사용처는 <b>경계</b>입니다 — HTTP 핸들러에서 패닉을 잡아 500 을 돌려주고 서버는 계속 돌게 하거나, 라이브러리 내부의 재귀 파서가 밖으로는 에러를 내보낼 때. '경계에서 한 번' 이 원칙입니다." },

{
 "lang": "go",
 "k": "맵과 슬라이스로 집계",
 "cat": "internals",
 "q": "단어 목록의 <b>빈도 상위 N개</b>를 구하는 <code>TopWords(words []string, n int) []string</code> 를 구현하세요. 빈도 내림차순, <b>같으면 사전순</b>으로 정렬하고 상위 n개를 돌려줍니다. n 이 종류 수보다 크면 전부입니다.",
 "src": "package ex\n\nfunc TopWords(words []string, n int) []string {\n\t// TODO: 빈도 집계 후 빈도 ↓ · 사전순 ↑ 정렬\n\treturn nil\n}",
 "sol": "package ex\n\nimport \"sort\"\n\nfunc TopWords(words []string, n int) []string {\n\tcount := map[string]int{}\n\tfor _, w := range words {\n\t\tcount[w]++\n\t}\n\tkeys := make([]string, 0, len(count))\n\tfor k := range count {\n\t\tkeys = append(keys, k)\n\t}\n\tsort.Slice(keys, func(i, j int) bool {\n\t\tif count[keys[i]] != count[keys[j]] {\n\t\t\treturn count[keys[i]] > count[keys[j]]\n\t\t}\n\t\treturn keys[i] < keys[j]\n\t})\n\tif n > len(keys) {\n\t\tn = len(keys)\n\t}\n\tif n < 0 {\n\t\tn = 0\n\t}\n\treturn keys[:n]\n}",
 "test": {
  "go.mod": "module ex\n\ngo 1.21\n",
  "sol_test.go": "package ex\n\nimport \"testing\"\n\nfunc join(xs []string) string {\n\ts := \"\"\n\tfor i, x := range xs {\n\t\tif i > 0 {\n\t\t\ts += \",\"\n\t\t}\n\t\ts += x\n\t}\n\treturn s\n}\n\nfunc TestByFrequency(t *testing.T) {\n\tif got := join(TopWords([]string{\"a\", \"b\", \"a\", \"c\", \"a\", \"b\"}, 2)); got != \"a,b\" {\n\t\tt.Fatalf(\"got %q\", got)\n\t}\n}\n\nfunc TestTieByAlpha(t *testing.T) {\n\tif got := join(TopWords([]string{\"z\", \"y\"}, 2)); got != \"y,z\" {\n\t\tt.Fatalf(\"동점은 사전순이어야 한다: %q\", got)\n\t}\n}\n\nfunc TestNBiggerThanKinds(t *testing.T) {\n\tif got := join(TopWords([]string{\"a\", \"a\"}, 10)); got != \"a\" {\n\t\tt.Fatalf(\"got %q\", got)\n\t}\n}\n\nfunc TestDeterministic(t *testing.T) {\n\twords := []string{\"a\", \"b\", \"c\", \"a\", \"b\", \"c\"}\n\tfirst := join(TopWords(words, 3))\n\tfor i := 0; i < 20; i++ {\n\t\tif join(TopWords(words, 3)) != first {\n\t\t\tt.Fatal(\"호출마다 결과가 달라진다 — 맵 순회 순서에 의존하고 있다\")\n\t\t}\n\t}\n}\n\nfunc TestEmpty(t *testing.T) {\n\tif got := TopWords(nil, 3); len(got) != 0 {\n\t\tt.Fatalf(\"길이가 0이어야 한다: %v\", got)\n\t}\n}\n"
 },
 "ex": "🎯 Go 의 <b>맵 순회 순서는 무작위</b>입니다 — 의도적으로 무작위화해서, 순서에 의존하는 코드가 <b>테스트에서 바로 깨지게</b> 만듭니다. 그래서 정렬된 결과가 필요하면 키를 슬라이스로 꺼내 <b>명시적으로 정렬</b>해야 합니다.\n💡 이 문항의 <code>TestDeterministic</code> 이 그 함정을 노립니다 — 동점 처리를 빼먹으면 같은 입력에 다른 결과가 나오고, <b>가끔 실패하는 테스트</b>가 됩니다. 실전에서 가장 짜증나는 종류의 버그입니다.\n⚠️ <code>sort.Slice</code> 는 <b>안정 정렬이 아닙니다</b>(<code>sort.SliceStable</code> 이 따로 있습니다). 그래서 동점 기준을 명시하지 않으면 순서가 보장되지 않습니다 — '어차피 같은 값인데' 가 아니라 <b>출력이 결정적인가</b>가 기준입니다.\n🔧 상위 n개만 필요하다면 전체 정렬 대신 <b>힙</b>을 쓸 수 있지만(<code>container/heap</code>), 종류 수가 수만 이하면 정렬이 더 단순하고 빠른 경우가 많습니다 — 최적화는 측정 후에 하세요."
},

{
 "lang": "go",
 "k": "제네릭 함수",
 "cat": "internals",
 "q": "Go 제네릭으로 <code>Map</code>·<code>Filter</code>·<code>Reduce</code> 를 구현하세요. <code>Map[T, U any]([]T, func(T) U) []U</code>, <code>Filter[T any]([]T, func(T) bool) []T</code>, <code>Reduce[T, U any]([]T, U, func(U, T) U) U</code> 이며, <b>입력이 비어도 nil 이 아닌 빈 슬라이스</b>를 돌려주세요.",
 "src": "package ex\n\n// TODO: 제네릭 Map · Filter · Reduce\n\nfunc Map[T any, U any](xs []T, f func(T) U) []U {\n\treturn nil\n}\n\nfunc Filter[T any](xs []T, f func(T) bool) []T {\n\treturn nil\n}\n\nfunc Reduce[T any, U any](xs []T, init U, f func(U, T) U) U {\n\treturn init\n}",
 "sol": "package ex\n\nfunc Map[T any, U any](xs []T, f func(T) U) []U {\n\tout := make([]U, 0, len(xs))\n\tfor _, x := range xs {\n\t\tout = append(out, f(x))\n\t}\n\treturn out\n}\n\nfunc Filter[T any](xs []T, f func(T) bool) []T {\n\tout := make([]T, 0, len(xs))\n\tfor _, x := range xs {\n\t\tif f(x) {\n\t\t\tout = append(out, x)\n\t\t}\n\t}\n\treturn out\n}\n\nfunc Reduce[T any, U any](xs []T, init U, f func(U, T) U) U {\n\tacc := init\n\tfor _, x := range xs {\n\t\tacc = f(acc, x)\n\t}\n\treturn acc\n}",
 "test": {
  "go.mod": "module ex\n\ngo 1.21\n",
  "sol_test.go": "package ex\n\nimport \"testing\"\n\nfunc TestMap(t *testing.T) {\n\tgot := Map([]string{\"ab\", \"cde\"}, func(s string) int { return len(s) })\n\tif len(got) != 2 || got[0] != 2 || got[1] != 3 {\n\t\tt.Fatalf(\"got %v\", got)\n\t}\n}\n\nfunc TestFilter(t *testing.T) {\n\tgot := Filter([]int{1, 2, 3, 4}, func(x int) bool { return x%2 == 0 })\n\tif len(got) != 2 || got[0] != 2 || got[1] != 4 {\n\t\tt.Fatalf(\"got %v\", got)\n\t}\n}\n\nfunc TestReduce(t *testing.T) {\n\tif got := Reduce([]int{1, 2, 3}, 0, func(a, x int) int { return a + x }); got != 6 {\n\t\tt.Fatalf(\"got %d\", got)\n\t}\n}\n\nfunc TestReduceTypeChange(t *testing.T) {\n\tif got := Reduce([]string{\"a\", \"bc\"}, 0, func(a int, x string) int { return a + len(x) }); got != 3 {\n\t\tt.Fatalf(\"타입이 바뀌는 축약 실패: %d\", got)\n\t}\n\tif got := Reduce([]string{\"x\", \"y\"}, \"\", func(a string, x string) string { return a + x }); got != \"xy\" {\n\t\tt.Fatalf(\"got %q\", got)\n\t}\n}\n\nfunc TestEmptyNotNil(t *testing.T) {\n\tm := Map([]int{}, func(x int) int { return x })\n\tf := Filter([]int{}, func(x int) bool { return true })\n\tif m == nil || f == nil {\n\t\tt.Fatal(\"빈 입력에도 nil 이 아닌 슬라이스를 돌려줘야 한다\")\n\t}\n\tif len(m) != 0 || len(f) != 0 {\n\t\tt.Fatal(\"길이가 0이어야 한다\")\n\t}\n}\n"
 },
 "ex": "🎯 Go 1.18 의 제네릭은 <b>타입 파라미터</b>로 '어떤 타입이든 같은 코드' 를 씁니다. <code>Map[T, U]</code> 처럼 입력과 출력 타입이 <b>다를 수 있다</b>는 점이 중요합니다 — 이게 없으면 string→int 변환을 표현할 수 없습니다.\n💡 <code>make([]U, 0, len(xs))</code> 로 <b>용량을 미리 잡는</b> 것이 요령입니다. append 가 자라면서 재할당·복사하는 것을 한 번에 막아, 큰 슬라이스에서 눈에 띄는 차이를 냅니다.\n⚠️ <b>nil 슬라이스와 빈 슬라이스는 다릅니다</b>. 둘 다 <code>len == 0</code> 이지만 JSON 으로 직렬화하면 nil 은 <code>null</code>, 빈 슬라이스는 <code>[]</code> 가 됩니다 — API 응답에서 클라이언트가 깨지는 흔한 원인이라 테스트가 이것을 확인합니다.\n🔧 Go 커뮤니티는 제네릭 <code>Map</code>/<code>Filter</code> 남용에 조심스럽습니다 — for 루프가 더 읽기 쉬울 때가 많기 때문입니다. 제네릭이 확실히 이기는 곳은 <b>자료구조</b>(집합·큐·캐시)와 타입 안전한 유틸리티입니다."
},

/* ───────────────── Rust ───────────────── */
{ lang:"rust", k:"Result 조합과 커스텀 에러", cat:"internals",
  q:"설정 문자열 <code>\"key=value\"</code> 를 파싱하는 <code>parse_port(s: &str) -> Result&lt;u16, ConfigError&gt;</code> 를 구현하세요. <code>=</code> 가 없으면 <code>ConfigError::Malformed</code>, 키가 <code>port</code> 가 아니면 <code>ConfigError::UnknownKey(키)</code>, 숫자가 아니거나 범위를 넘으면 <code>ConfigError::BadNumber</code> 입니다. 키와 값의 <b>공백은 무시</b>합니다.",
  src:"#[derive(Debug, PartialEq)]\npub enum ConfigError {\n    Malformed,\n    UnknownKey(String),\n    BadNumber,\n}\n\npub fn parse_port(s: &str) -> Result<u16, ConfigError> {\n    // TODO: = 로 나누고 키를 확인한 뒤 숫자로\n    Ok(0)\n}",
  sol:"#[derive(Debug, PartialEq)]\npub enum ConfigError {\n    Malformed,\n    UnknownKey(String),\n    BadNumber,\n}\n\npub fn parse_port(s: &str) -> Result<u16, ConfigError> {\n    let (key, val) = s.split_once('=').ok_or(ConfigError::Malformed)?;\n    if key.trim() != \"port\" {\n        return Err(ConfigError::UnknownKey(key.trim().to_string()));\n    }\n    val.trim().parse::<u16>().map_err(|_| ConfigError::BadNumber)\n}",
  test:{"sol.rs":"use ex::{parse_port, ConfigError};\n\n#[test]\nfn ok() {\n    assert_eq!(parse_port(\"port=8080\"), Ok(8080));\n}\n\n#[test]\nfn spaces_are_trimmed() {\n    assert_eq!(parse_port(\" port = 80 \"), Ok(80));\n}\n\n#[test]\nfn malformed() {\n    assert_eq!(parse_port(\"port\"), Err(ConfigError::Malformed));\n}\n\n#[test]\nfn unknown_key() {\n    assert_eq!(parse_port(\"host=x\"), Err(ConfigError::UnknownKey(\"host\".to_string())));\n}\n\n#[test]\nfn bad_number() {\n    assert_eq!(parse_port(\"port=abc\"), Err(ConfigError::BadNumber));\n    assert_eq!(parse_port(\"port=99999\"), Err(ConfigError::BadNumber));\n}\n"},
  ex:"🎯 러스트의 <code>Result</code> 는 실패를 <b>타입에 드러냅니다</b> — 호출자는 성공만 처리하고 넘어갈 수 없고, 컴파일러가 강제합니다. 에러를 열거형으로 만들면 '<b>어떤 방식으로 실패했는가</b>' 까지 타입이 표현합니다.\n💡 <code>?</code> 연산자는 '실패면 즉시 반환' 을 한 글자로 줄입니다. <code>ok_or</code> 는 <code>Option</code> 을 <code>Result</code> 로, <code>map_err</code> 는 에러 타입을 바꿔 줍니다 — 이 세 조각으로 대부분의 변환이 조립됩니다.\n⚠️ <code>parse::&lt;u16&gt;()</code> 는 <b>범위 초과도 실패</b>로 처리합니다 — 99999는 u16 범위를 넘으므로 별도 검사가 필요 없습니다. 타입을 좁게 고르는 것 자체가 검증인 셈입니다.\n🔧 실전에서는 <code>thiserror</code> 로 <code>Display</code>·<code>Error</code> 구현을 자동 생성하고, 라이브러리 경계에서는 구체적 열거형을, 애플리케이션에서는 <code>anyhow</code> 같은 통합 타입을 쓰는 것이 관례입니다 — <b>누가 이 에러를 보고 무엇을 결정하는가</b>가 선택 기준입니다." },

{ lang:"rust", k:"이터레이터 체인", cat:"internals",
  q:"로그 줄에서 <b>느린 요청의 평균 응답 시간</b>을 구하는 <code>slow_avg(lines: &[&str], threshold: u32) -> Option&lt;f64&gt;</code> 를 구현하세요. 각 줄은 <code>\"GET /path 250\"</code> 형식이고 <b>마지막 필드가 응답 시간(ms)</b> 입니다. 파싱 실패 줄은 건너뛰고, <code>threshold</code> <b>이상</b>인 것만 평균 냅니다. 해당 줄이 없으면 <code>None</code> 입니다.",
  src:"pub fn slow_avg(lines: &[&str], threshold: u32) -> Option<f64> {\n    // TODO: 파싱 → 임계 이상 필터 → 평균\n    None\n}",
  sol:"pub fn slow_avg(lines: &[&str], threshold: u32) -> Option<f64> {\n    let times: Vec<u32> = lines\n        .iter()\n        .filter_map(|l| l.split_whitespace().last())\n        .filter_map(|t| t.parse::<u32>().ok())\n        .filter(|t| *t >= threshold)\n        .collect();\n    if times.is_empty() {\n        return None;\n    }\n    let sum: u32 = times.iter().sum();\n    Some(sum as f64 / times.len() as f64)\n}",
  test:{"sol.rs":"use ex::slow_avg;\n\n#[test]\nfn averages_slow_ones() {\n    let lines = [\"GET /a 100\", \"GET /b 300\", \"GET /c 500\"];\n    assert_eq!(slow_avg(&lines, 200), Some(400.0));\n}\n\n#[test]\nfn threshold_is_inclusive() {\n    let lines = [\"GET /a 200\"];\n    assert_eq!(slow_avg(&lines, 200), Some(200.0));\n}\n\n#[test]\nfn skips_unparsable() {\n    let lines = [\"GET /a xxx\", \"GET /b 400\", \"\"];\n    assert_eq!(slow_avg(&lines, 100), Some(400.0));\n}\n\n#[test]\nfn none_when_no_match() {\n    let lines = [\"GET /a 10\"];\n    assert_eq!(slow_avg(&lines, 100), None);\n}\n\n#[test]\nfn empty_input() {\n    assert_eq!(slow_avg(&[], 100), None);\n}\n"},
  ex:"🎯 이터레이터 체인은 <b>지연 평가</b>입니다 — <code>filter_map</code>·<code>filter</code> 는 각 원소를 <b>한 번씩만</b> 통과시키며, <code>collect</code> 같은 소비자를 만나기 전까지 아무 일도 하지 않습니다. 중간 벡터가 생기지 않아 for 루프만큼 빠릅니다.\n💡 <code>filter_map</code> 은 '<b>변환하면서 실패한 것은 버리기</b>' 입니다 — <code>map</code> 후 <code>filter</code> 로 나누면 <code>Option</code> 을 두 번 다뤄야 합니다. <code>.ok()</code> 로 <code>Result</code> 를 <code>Option</code> 으로 바꿔 흘려보내는 조합이 러스트다운 파싱 파이프라인입니다.\n⚠️ '해당 줄이 없으면 평균이 아니라 <code>None</code>' 이 중요합니다 — 0으로 나누면 <code>NaN</code> 이 나오고, 그 NaN 이 대시보드와 알람으로 조용히 퍼집니다. <b>정의되지 않은 값을 타입으로 표현</b>하는 것이 러스트의 방식입니다.\n🔧 <code>collect</code> 없이 <code>sum</code> 과 <code>count</code> 를 각각 부르면 이터레이터를 <b>두 번 소비</b>해야 해서 안 됩니다 — 한 번에 접으려면 <code>fold((0, 0))</code> 로 합과 개수를 함께 누적합니다. 큰 로그에서는 이 차이가 메모리를 가릅니다." },

{ lang:"rust", k:"소유권과 빌림", cat:"internals",
  q:"문자열 벡터에서 <b>가장 긴 것의 참조</b>를 돌려주는 <code>longest&lt;'a&gt;(xs: &'a [String]) -> Option&lt;&'a str&gt;</code> 를 구현하세요. 동점이면 <b>앞선 것</b>, 비었으면 <code>None</code> 입니다. <b>복제(clone)하지 말고 참조를 돌려주세요</b>. 길이는 바이트 기준(<code>len()</code>)입니다.",
  src:"pub fn longest<'a>(xs: &'a [String]) -> Option<&'a str> {\n    // TODO: 복제 없이 가장 긴 것의 참조\n    None\n}",
  sol:"pub fn longest<'a>(xs: &'a [String]) -> Option<&'a str> {\n    let mut best: Option<&'a str> = None;\n    for s in xs {\n        match best {\n            Some(b) if s.len() <= b.len() => {}\n            _ => best = Some(s.as_str()),\n        }\n    }\n    best\n}",
  test:{"sol.rs":"use ex::longest;\n\n#[test]\nfn picks_longest() {\n    let v = vec![\"a\".to_string(), \"abc\".to_string(), \"ab\".to_string()];\n    assert_eq!(longest(&v), Some(\"abc\"));\n}\n\n#[test]\nfn ties_pick_first() {\n    let v = vec![\"xy\".to_string(), \"ab\".to_string()];\n    assert_eq!(longest(&v), Some(\"xy\"));\n}\n\n#[test]\nfn empty_is_none() {\n    let v: Vec<String> = vec![];\n    assert_eq!(longest(&v), None);\n}\n\n#[test]\nfn borrow_points_into_input() {\n    let v = vec![\"hello\".to_string()];\n    let got = longest(&v).unwrap();\n    assert_eq!(got.as_ptr(), v[0].as_ptr());\n}\n\n#[test]\nfn multibyte() {\n    let v = vec![\"한글\".to_string(), \"ab\".to_string()];\n    assert_eq!(longest(&v), Some(\"한글\"));\n}\n"},
  ex:"🎯 수명 표기 <code>&lt;'a&gt;</code> 는 '<b>반환한 참조는 입력이 살아 있는 동안 유효하다</b>' 는 약속입니다. 이 약속 덕에 컴파일러가 '입력이 먼저 사라지는' 코드를 <b>컴파일 시점에</b> 거부합니다 — C 의 댕글링 포인터가 구조적으로 불가능해집니다.\n💡 참조를 돌려주면 <b>복제 비용이 0</b> 입니다. <code>clone()</code> 으로 우회하면 컴파일은 통과하지만 문자열마다 힙 할당이 생깁니다 — 테스트가 <code>as_ptr()</code> 로 <b>같은 메모리를 가리키는지</b> 확인하는 이유입니다.\n⚠️ <code>len()</code> 은 <b>바이트 수</b>입니다 — '한글'(6바이트)이 'ab'(2바이트)보다 길다고 판정됩니다. 글자 수로 비교하려면 <code>chars().count()</code> 를 써야 하며, 어느 쪽이 맞는지는 요구사항이 정합니다.\n🔧 수명을 명시해야 하는 경우는 생각보다 적습니다 — 입력이 하나면 컴파일러가 추론합니다(수명 생략 규칙). 여러 참조 중 <b>어느 것과 묶이는지</b> 모호할 때만 사람이 적어 줍니다." },
];
