/* 실행형이 0이던 마지막 8개 트랙(ai·math·fp·cs·compiler·arduino·dbt·mobile)에
   실행 문항을 넣는다. 각 트랙의 핵심 알고리즘을 '직접 굴려 보는' 문제로 골랐다 —
   개념 설명으로는 못 잡는 오해(pop 순서, 좌결합, 뷰 공유, LRU 갱신)를 테스트가 드러낸다.
   주의: 앱 하네스가 쓰는 이름(SRC·TS·eq·gate·impl·P·row 등)과 겹치지 않게 짓는다. */
module.exports = [
/* ───────────── ai ───────────── */
{ track:"ai", k:"BPE 병합", cat:"internals",
  q:"토크나이저의 <b>BPE 병합</b>을 구현하세요. <code>bpe(word, merges)</code> 는 단어를 글자로 쪼갠 뒤, <b>병합 규칙을 순서대로</b> 하나씩 적용합니다. 각 규칙은 왼쪽부터 한 번 훑으며 이웃한 <code>[a,b]</code> 쌍을 <code>a+b</code> 로 합칩니다. 토큰 배열을 돌려주세요.",
  src:"function bpe(word, merges) {\n  // TODO: 글자로 쪼갠 뒤 규칙을 순서대로 적용\n  return word.split('');\n}",
  sol:"function bpe(word, merges) {\n  let toks = word.split('');\n  merges.forEach(([a, b]) => {\n    const out = [];\n    for (let i = 0; i < toks.length; i++) {\n      if (toks[i] === a && toks[i + 1] === b) { out.push(a + b); i++; }\n      else out.push(toks[i]);\n    }\n    toks = out;\n  });\n  return toks;\n}",
  tests:[["bpe('low',[['l','o'],['lo','w']])","['low']"],
         ["bpe('lowest',[['l','o'],['lo','w']])","['low','e','s','t']"],
         ["bpe('lolo',[['l','o']])","['lo','lo']"],
         ["bpe('ll',[['l','o']])","['l','l']"]],
  edge:[["bpe('',[['a','b']])","[]"],
        ["bpe('abc',[])","['a','b','c']"]],
  ex:"🎯 BPE(Byte Pair Encoding)는 <b>자주 붙어 나오는 쌍부터</b> 병합 규칙을 배우고, 인코딩할 때는 그 규칙을 <b>배운 순서대로</b> 다시 적용합니다. 어휘에 없는 새 단어도 조각으로 표현할 수 있는 이유입니다.\n💡 규칙 순서가 곧 우선순위입니다. <code>l+o</code> 를 먼저 합쳐야 <code>lo+w</code> 규칙이 적용될 수 있습니다 — 병합은 앞 단계의 결과 위에서 일어납니다.\n⚠️ LLM 이 'strawberry 의 r 개수' 를 자주 틀리는 이유가 여기 있습니다. 모델은 글자가 아니라 <b>병합된 토큰</b>을 보므로, 글자 단위 질문에 약합니다. 숫자 계산이 토큰 경계에 따라 흔들리는 것도 같은 원인입니다.\n🔧 같은 텍스트라도 토크나이저가 다르면 토큰 수가 달라 <b>비용과 컨텍스트 길이</b>가 달라집니다. 프롬프트 비용을 추정할 때는 반드시 해당 모델의 토크나이저로 세야 합니다." },

{ track:"ai", k:"컨텍스트 예산 배분", cat:"design",
  q:"RAG 에서 <b>컨텍스트 창 예산</b>에 문서를 채우세요. <code>pack(docs, budget)</code> 은 <code>{id, tokens, score}</code> 배열에서 <b>score 높은 순</b>(같으면 앞선 것 먼저)으로 고르되, 남은 예산에 <b>안 들어가는 문서는 건너뛰고</b> 다음 문서를 계속 검토합니다. 고른 id 배열을 돌려주세요.",
  src:"function pack(docs, budget) {\n  // TODO: score 순 정렬 후 예산에 맞게 담기\n  return [];\n}",
  sol:"function pack(docs, budget) {\n  const sorted = docs.map((d, i) => [d, i])\n    .sort((x, y) => y[0].score - x[0].score || x[1] - y[1])\n    .map((p) => p[0]);\n  const out = [];\n  let left = budget;\n  sorted.forEach((d) => {\n    if (d.tokens <= left) { out.push(d.id); left -= d.tokens; }\n  });\n  return out;\n}",
  tests:[["pack([{id:'a',tokens:50,score:9},{id:'b',tokens:60,score:8},{id:'c',tokens:40,score:7}],100)","['a','c']"],
         ["pack([{id:'a',tokens:50,score:9},{id:'b',tokens:60,score:8},{id:'c',tokens:40,score:7}],200)","['a','b','c']"],
         ["pack([{id:'x',tokens:30,score:5},{id:'y',tokens:30,score:5}],30)","['x']"],
         ["pack([{id:'a',tokens:80,score:1},{id:'b',tokens:20,score:9}],100)","['b','a']"]],
  edge:[["pack([],100)","[]"],
        ["pack([{id:'x',tokens:101,score:10}],100)","[]"]],
  ex:"🎯 컨텍스트 창은 <b>유한한 예산</b>입니다. 검색된 문서를 다 넣을 수 없으므로 '관련도 높은 것부터, 들어가는 만큼' 담는 배분 문제가 됩니다.\n💡 큰 문서가 안 들어간다고 멈추면 안 됩니다 — <b>건너뛰고 다음을 검토</b>해야 작은 문서로 남은 예산을 채울 수 있습니다. 배낭 문제의 탐욕 근사와 같은 구조입니다.\n⚠️ 관련도만 보고 채우면 <b>같은 내용의 중복 문서</b>가 예산을 다 먹을 수 있습니다. 실전에서는 중복 제거(MMR 같은 다양성 보정)를 함께 씁니다. 또 '가운데에 넣은 문서는 잘 못 본다'(lost in the middle)는 위치 효과도 있습니다.\n🔧 프롬프트·시스템 지시·출력 여유분을 뺀 것이 실제 문서 예산입니다. 예산 계산을 안 하면 잘리는 건 대개 <b>가장 마지막에 넣은 지시문</b>입니다." },

{ track:"ai", k:"코사인 유사도와 벡터 검색", cat:"internals",
  q:"임베딩 검색의 핵심인 <b>코사인 유사도</b>를 구현하세요. <code>cosine(a, b)</code> 는 두 벡터의 유사도(<b>영벡터면 <code>null</code></b>), <code>topK(query, docs, k)</code> 는 <code>{id, v}</code> 문서들 중 유사도 높은 순으로 <b>k개의 id</b> 를 돌려줍니다(영벡터 문서는 제외).",
  src:"function cosine(a, b) {\n  // TODO: dot / (|a||b|), 영벡터는 null\n  return 0;\n}\n\nfunction topK(query, docs, k) {\n  // TODO: 유사도 내림차순 k개 id\n  return [];\n}",
  sol:"function cosine(a, b) {\n  let dot = 0, na = 0, nb = 0;\n  for (let i = 0; i < a.length; i++) {\n    dot += a[i] * b[i]; na += a[i] * a[i]; nb += b[i] * b[i];\n  }\n  if (na === 0 || nb === 0) return null;\n  return dot / Math.sqrt(na * nb);\n}\n\nfunction topK(query, docs, k) {\n  return docs.map((d) => ({ id: d.id, s: cosine(query, d.v) }))\n    .filter((d) => d.s !== null)\n    .sort((x, y) => y.s - x.s)\n    .slice(0, k).map((d) => d.id);\n}",
  tests:[["cosine([1,0],[0,1])","0"],
         ["cosine([1,2],[2,4])","1"],
         ["cosine([0,0],[1,2])","null"],
         ["topK([1,0],[{id:'a',v:[1,0]},{id:'b',v:[0,1]},{id:'c',v:[1,1]}],2)","['a','c']"]],
  edge:[["cosine([2,0],[4,0])","1"],
        ["topK([1,0],[{id:'z',v:[0,0]},{id:'b',v:[1,1]}],5)","['b']"]],
  ex:"🎯 코사인 유사도는 <b>방향</b>만 봅니다. <code>[1,2]</code> 와 <code>[2,4]</code> 는 길이가 달라도 방향이 같아 유사도 1 — 문서 길이에 덜 휘둘리는 성질이라 임베딩 검색의 표준이 됐습니다.\n💡 분모를 <code>√(na·nb)</code> 로 한 번에 계산하면 <code>√na·√nb</code> 보다 부동소수점 오차가 작습니다. <code>√5·√20 ≈ 10.000000000000002</code> 처럼 정확히 1이어야 할 값이 흔들리는 걸 막습니다.\n⚠️ <b>영벡터의 유사도는 정의되지 않습니다</b> — 0으로 나누면 NaN 이 조용히 퍼져 정렬 전체가 무의미해집니다. NaN 은 모든 비교에서 false 라 sort 가 이상하게 동작하는데, 원인을 찾기가 매우 어렵습니다.\n🔧 실제 벡터 DB 는 전수 비교 대신 근사 최근접(HNSW 등)을 쓰지만, <b>거리 함수의 성질</b>은 그대로입니다. 임베딩 모델이 정규화된 벡터를 내면 코사인과 내적이 같아져 더 빠른 내적을 씁니다." },

/* ───────────── math ───────────── */
{ track:"math", k:"유클리드 호제법과 모듈러 역원", cat:"internals",
  q:"<b>유클리드 호제법</b>과 <b>모듈러 역원</b>을 구현하세요. <code>gcd(a, b)</code> 는 최대공약수, <code>inv(a, m)</code> 은 <code>a·x ≡ 1 (mod m)</code> 인 <code>0 ≤ x &lt; m</code> 입니다. <b>a 와 m 이 서로소가 아니면 역원이 없으므로 <code>null</code></b> 을 돌려주세요.",
  src:"function gcd(a, b) {\n  // TODO: 호제법\n  return 1;\n}\n\nfunction inv(a, m) {\n  // TODO: 확장 유클리드\n  return null;\n}",
  sol:"function gcd(a, b) {\n  while (b) { [a, b] = [b, a % b]; }\n  return a;\n}\n\nfunction inv(a, m) {\n  let [r0, r1] = [a % m, m], [s0, s1] = [1, 0];\n  while (r1) {\n    const q = Math.floor(r0 / r1);\n    [r0, r1] = [r1, r0 - q * r1];\n    [s0, s1] = [s1, s0 - q * s1];\n  }\n  if (r0 !== 1) return null;\n  return ((s0 % m) + m) % m;\n}",
  tests:[["gcd(12,18)","6"],
         ["inv(3,7)","5"],
         ["inv(2,4)","null"],
         ["inv(10,17)","12"]],
  edge:[["gcd(7,0)","7"],
        ["inv(1,13)","1"]],
  ex:"🎯 모듈러 세계에서 '나눗셈' 은 <b>역원 곱하기</b>입니다. <code>3·5 = 15 ≡ 1 (mod 7)</code> 이므로 mod 7 에서 3으로 나누는 것은 5를 곱하는 것과 같습니다.\n💡 역원은 <b>서로소일 때만</b> 존재합니다. <code>inv(2,4)</code> 가 null 인 이유: 2의 배수는 mod 4 에서 0 아니면 2라 절대 1이 되지 못합니다. RSA 가 서로소 조건 위에 서 있는 이유이기도 합니다.\n⚠️ 확장 유클리드가 주는 계수는 <b>음수일 수 있습니다</b>. <code>(s % m + m) % m</code> 로 양수 범위에 넣지 않으면 -2 같은 답이 나옵니다 — 언어의 <code>%</code> 가 음수를 어떻게 다루는지가 이 버그의 단골 원인입니다.\n🔧 해시 분배·순환 버퍼·암호까지, '나머지 세계의 산술' 은 생각보다 넓게 쓰입니다. 페르마 소정리(<code>a^(m-2)</code>, m 이 소수일 때)는 같은 답을 주는 다른 길입니다." },

{ track:"math", k:"조합 — 오버플로 없이", cat:"internals",
  q:"이항계수 <code>comb(n, k)</code> 를 구현하세요. 팩토리얼을 다 곱한 뒤 나누면 큰 수에서 <b>정밀도를 잃으므로</b>, <b>하나 곱할 때마다 바로 나누는</b> 방식으로 구현하세요. <code>k &lt; 0</code> 또는 <code>k &gt; n</code> 이면 0, <code>min(k, n−k)</code> 로 반복을 줄이세요.",
  src:"function comb(n, k) {\n  // TODO: 곱하고 바로 나누기\n  return 0;\n}",
  sol:"function comb(n, k) {\n  if (k < 0 || k > n) return 0;\n  const m = Math.min(k, n - k);\n  let r = 1;\n  for (let i = 1; i <= m; i++) r = r * (n - m + i) / i;\n  return r;\n}",
  tests:[["comb(5,2)","10"],
         ["comb(10,3)","120"],
         ["comb(52,5)","2598960"],
         ["comb(40,20)","137846528820"]],
  edge:[["comb(0,0)","1"],
        ["comb(3,5)","0"]],
  ex:"🎯 <code>52! / (5!·47!)</code> 를 곧이곧대로 계산하면 <code>52!</code> 이 약 8×10⁶⁷ — 부동소수점의 정밀도(2⁵³, 약 9×10¹⁵)를 아득히 넘어 <b>답이 어긋납니다</b>. 수식이 맞아도 계산 순서가 틀리면 값이 틀립니다.\n💡 <code>r · (n−m+i) / i</code> 는 매 단계가 <b>정확한 정수</b>입니다 — i개의 연속 정수 곱은 항상 i! 로 나누어떨어지기 때문입니다. 중간값이 최종 답의 수십 배를 넘지 않아 안전합니다.\n⚠️ <code>min(k, n−k)</code> 최적화는 속도만이 아니라 <b>정밀도</b> 문제이기도 합니다. <code>comb(40,39)</code> 를 39번 곱하면 쓸데없이 큰 중간값을 만듭니다.\n🔧 확률 계산에서는 아예 <b>로그 공간</b>(logGamma)으로 가는 것이 표준입니다. 로또 확률처럼 곱셈이 수백 번이면 log 로 더하고 마지막에 exp 합니다." },

{ track:"math", k:"연립방정식 — 크라메르 공식", cat:"internals",
  q:"연립방정식 <code>ax + by = e</code>, <code>cx + dy = f</code> 를 <b>크라메르 공식</b>으로 푸세요. <code>solve2(a,b,c,d,e,f)</code> 는 <code>[x, y]</code> 를 돌려주고, <b>행렬식 <code>ad − bc</code> 가 0이면</b>(해가 없거나 무한) <code>null</code> 입니다.",
  src:"function solve2(a, b, c, d, e, f) {\n  // TODO: 행렬식 검사 후 크라메르\n  return [0, 0];\n}",
  sol:"function solve2(a, b, c, d, e, f) {\n  const det = a * d - b * c;\n  if (det === 0) return null;\n  return [(e * d - b * f) / det, (a * f - c * e) / det];\n}",
  tests:[["solve2(1,1,1,-1,3,1)","[2,1]"],
         ["solve2(2,0,0,2,4,6)","[2,3]"],
         ["solve2(1,2,2,4,3,6)","null"],
         ["solve2(3,-1,1,1,5,3)","[2,1]"]],
  edge:[["solve2(1,0,0,1,0,0)","[0,0]"],
        ["solve2(1,2,2,4,3,5)","null"]],
  ex:"🎯 행렬식 <code>ad − bc</code> 는 이 연립방정식이 <b>유일한 해를 갖는지</b>를 판별합니다. 0이라는 것은 두 직선이 평행(해 없음)하거나 같은 직선(해 무한)이라는 뜻입니다.\n💡 크라메르 공식은 분자의 행렬식에서 <b>해당 열을 상수항으로 바꾼 것</b>입니다: <code>x = det([[e,b],[f,d]])/det</code>. 2×2 에서는 이게 가장 간단한 직접 해법입니다.\n⚠️ 행렬식 검사를 <b>먼저</b> 하지 않으면 0으로 나눠 <code>Infinity</code> 나 <code>NaN</code> 이 조용히 흘러갑니다. 그래픽스에서 역행렬 없는 변환을 뒤집으려 할 때 정확히 이 사고가 납니다.\n🔧 실수 계수 실전 코드에서는 <code>det === 0</code> 대신 <code>|det| &lt; ε</code> 로 판정합니다 — 부동소수점에서는 '거의 평행' 도 수치적으로 위험하기 때문입니다. 큰 시스템은 크라메르 대신 가우스 소거(LU 분해)를 씁니다." },

/* ───────────── fp ───────────── */
{ track:"fp", k:"커링", cat:"internals",
  q:"<b>커링</b>을 구현하세요. <code>curry(fn)</code> 은 인자를 나눠 받을 수 있는 함수를 돌려줍니다. 호출마다 인자를 <b>모으고</b>, 모인 개수가 <code>fn.length</code> 에 이르면 원함수를 호출합니다. <code>f(1)(2)(3)</code> 도 <code>f(1,2)(3)</code> 도 같아야 하고, <b>부분 적용을 재사용해도</b> 서로 영향이 없어야 합니다.",
  src:"function curry(fn) {\n  // TODO: fn.length 만큼 모이면 호출\n  return fn;\n}",
  sol:"function curry(fn) {\n  const step = (args) => (...next) => {\n    const all = args.concat(next);\n    return all.length >= fn.length ? fn(...all) : step(all);\n  };\n  return step([]);\n}",
  tests:[["curry((a,b,c)=>a+b+c)(1)(2)(3)","6"],
         ["curry((a,b,c)=>a+b+c)(1,2)(3)","6"],
         ["curry((a,b)=>a*b)(4,5)","20"],
         ["(() => { const add=curry((a,b)=>a+b); const add1=add(1); return [add1(2), add1(10)]; })()","[3,11]"]],
  edge:[["curry((a)=>a*2)(7)","14"],
        ["curry((a,b,c)=>a+b+c)(1)(2,3)","6"]],
  ex:"🎯 커링의 핵심은 <b>인자를 배열로 모아 두었다가</b> 충분해지면 원함수를 부르는 것입니다. <code>fn.length</code>(선언된 매개변수 수)가 '충분함' 의 기준입니다.\n💡 <code>args.concat(next)</code> 로 <b>새 배열</b>을 만드는 것이 재사용의 비결입니다. <code>add1 = add(1)</code> 을 여러 번 호출해도 각 호출이 자기 배열을 갖기 때문에 서로를 오염시키지 않습니다 — push 로 공유 배열에 쌓으면 두 번째 호출부터 틀어집니다.\n⚠️ <code>fn.length</code> 는 기본값·나머지 매개변수를 <b>세지 않습니다</b>. <code>(a, b = 1) => …</code> 의 length 는 1이라 커링이 일찍 발사됩니다.\n🔧 커링은 '설정을 먼저, 데이터를 나중에' 받는 API 를 만들 때 빛납니다. <code>log('error')</code> 처럼 부분 적용해 두고 재사용하는 패턴이 대표적입니다." },

{ track:"fp", k:"불변 갱신과 구조 공유", cat:"internals",
  q:"중첩 객체를 <b>불변으로 갱신</b>하는 <code>setIn(obj, path, value)</code> 를 구현하세요. 원본은 그대로 두고, <b>경로 위의 객체만 복사</b>하고 <b>경로 밖의 가지는 그대로 공유</b>합니다(구조 공유). 빈 경로면 <code>value</code> 자체를, 중간 경로가 없으면 만들어 가며 넣으세요.",
  src:"function setIn(obj, path, value) {\n  // TODO: 경로 위만 복사\n  return obj;\n}",
  sol:"function setIn(obj, path, value) {\n  if (path.length === 0) return value;\n  const [head, ...rest] = path;\n  const base = obj && typeof obj === 'object' ? obj : {};\n  return Object.assign({}, base, { [head]: setIn(base[head], rest, value) });\n}",
  tests:[["setIn({a:{b:1},z:{c:2}},['a','b'],9)","{a:{b:9},z:{c:2}}"],
         ["(() => { const o={a:{b:1},z:{c:2}}; const n2=setIn(o,['a','b'],9); return n2.z===o.z; })()","true"],
         ["(() => { const o={a:{b:1}}; setIn(o,['a','b'],9); return o.a.b; })()","1"],
         ["(() => { const o={a:{b:1}}; const n2=setIn(o,['a','b'],9); return n2.a===o.a; })()","false"]],
  edge:[["setIn({x:1},[],5)","5"],
        ["setIn({},['a','b'],1)","{a:{b:1}}"]],
  ex:"🎯 불변 갱신은 '전부 복사' 가 아닙니다. <b>바뀐 경로 위의 객체만</b> 새로 만들고 나머지 가지는 <b>참조를 그대로 공유</b>합니다 — 그래서 깊은 트리도 갱신 비용이 경로 길이에 비례합니다.\n💡 <code>n.z === o.z</code> 가 true 인 것이 핵심 테스트입니다. React 가 <code>===</code> 비교만으로 '이 가지는 안 바뀌었으니 리렌더 생략' 을 판단할 수 있는 근거가 바로 이 구조 공유입니다.\n⚠️ <code>obj.a.b = 9</code> 로 직접 고치면 참조가 안 바뀌어 React·Redux 가 <b>변경을 감지하지 못합니다</b>. 반대로 <code>JSON.parse(JSON.stringify(o))</code> 전체 복사는 감지는 되지만 모든 가지가 새 참조라 <b>모든 곳이 리렌더</b>됩니다.\n🔧 Immer 는 이 패턴을 Proxy 로 자동화한 것이고, <code>structuredClone</code> 은 공유 없는 전체 복사입니다 — 셋의 차이를 알고 골라 써야 합니다." },

{ track:"fp", k:"지연 평가와 메모이즈", cat:"internals",
  q:"<b>한 번만 계산하는 지연 값</b> <code>lazy(fn)</code> 을 구현하세요. 돌려준 함수를 처음 부를 때만 <code>fn</code> 을 실행해 결과를 기억하고, 이후엔 기억한 값을 돌려줍니다. <b><code>fn</code> 이 <code>undefined</code> 를 돌려줘도 다시 실행하면 안 됩니다</b> — 값이 아니라 <b>실행 여부 플래그</b>로 판단하세요.",
  src:"function lazy(fn) {\n  let value;\n  return () => {\n    if (value === undefined) value = fn();\n    return value;\n  };\n}",
  sol:"function lazy(fn) {\n  let done = false, value;\n  return () => {\n    if (!done) { value = fn(); done = true; }\n    return value;\n  };\n}",
  tests:[["(() => { let n2=0; const f=lazy(()=>{n2++; return 42;}); f(); f(); return [n2, f()]; })()","[1,42]"],
         ["(() => { let n2=0; const f=lazy(()=>{n2++;}); f(); f(); return n2; })()","1"],
         ["(() => { let n2=0; lazy(()=>{n2++;}); return n2; })()","0"],
         ["lazy(()=>'x')()","'x'"]],
  edge:[["(() => { let n2=0; const f=lazy(()=>{n2++; return null;}); return [f(), f(), n2]; })()","[null,null,1]"],
        ["(() => { let n2=0; const mk=()=>lazy(()=>++n2); const f=mk(), g=mk(); return [f(), g(), f()]; })()","[1,2,1]"]],
  ex:"🎯 시작 코드는 그럴듯하지만 <b>값으로 실행 여부를 판단하는</b> 버그가 있습니다. <code>fn</code> 이 <code>undefined</code> 를 돌려주면 '아직 실행 안 함' 과 구별이 안 되어 <b>매번 다시 실행</b>됩니다.\n💡 그래서 <code>done</code> 플래그를 <b>따로</b> 둡니다. '실행했는가' 와 '결과가 무엇인가' 는 다른 정보이고, 하나의 변수에 욱여넣으면 특정 값에서 무너집니다 — 캐시에서 <code>null</code> 을 '없음' 으로 쓰다 당하는 사고와 같은 뿌리입니다.\n⚠️ 부수효과가 있는 <code>fn</code> 이면 이 버그는 <b>이중 과금·중복 요청</b>이 됩니다. 테스트의 <code>n2</code> 카운터가 그 시나리오를 흉내 낸 것입니다.\n🔧 이 패턴이 곧 싱글턴 초기화·<code>lazy val</code>·React 의 <code>useMemo</code> 입니다. 다인자 버전이 메모이제이션(인자를 키로 한 결과 캐시)입니다." },

/* ───────────── cs ───────────── */
{ track:"cs", k:"2의 보수", cat:"internals",
  q:"<b>2의 보수</b> 표현을 구현하세요. <code>toSigned(bits)</code> 는 비트 문자열을 부호 있는 정수로 읽습니다 — <b>최상위 비트가 1이면 <code>2^폭</code> 을 뺀 값</b>입니다. <code>toBits(n, width)</code> 는 반대로 정수를 <code>width</code> 비트 문자열로 만듭니다(음수는 <code>2^width</code> 를 더해 표현).",
  src:"function toSigned(bits) {\n  // TODO: 최상위 비트가 1이면 음수\n  return parseInt(bits, 2);\n}\n\nfunction toBits(n, width) {\n  // TODO: 음수는 2^width 를 더해서\n  return n.toString(2);\n}",
  sol:"function toSigned(bits) {\n  const n = parseInt(bits, 2);\n  return bits[0] === '1' ? n - 2 ** bits.length : n;\n}\n\nfunction toBits(n, width) {\n  const u = n < 0 ? n + 2 ** width : n;\n  return u.toString(2).padStart(width, '0');\n}",
  tests:[["toSigned('1111')","-1"],
         ["toSigned('0111')","7"],
         ["toBits(-3,4)","'1101'"],
         ["toBits(6,4)","'0110'"]],
  edge:[["toSigned('10000000')","-128"],
        ["toBits(-1,8)","'11111111'"]],
  ex:"🎯 2의 보수에서 <b>같은 비트가 폭에 따라 다른 수</b>입니다. <code>1111</code> 은 4비트로 읽으면 −1, 부호 없이 읽으면 15 — 비트 자체에는 부호 정보가 없고 <b>해석 규칙</b>이 부호를 만듭니다.\n💡 −1 이 '전부 1' 인 이유: <code>x + (−x) = 2^w ≡ 0</code> 이 되도록 음수를 <code>2^w − x</code> 로 놓았기 때문입니다. 이 덕에 CPU 는 덧셈 회로 하나로 부호 있는/없는 덧셈을 모두 처리합니다.\n⚠️ 표현 범위가 <b>비대칭</b>입니다. 8비트는 −128~127 이라 <code>−(−128)</code> 이 다시 −128 이 되는 오버플로가 납니다 — <code>abs()</code> 가 음수를 돌려주는 유명한 버그의 원인입니다.\n🔧 C 의 정수 캐스팅, 네트워크 패킷의 부호 있는 필드, 자바스크립트 비트 연산(32비트로 잘림)까지 — <code>x | 0</code> 이 큰 수를 음수로 만드는 이유가 전부 이 규칙입니다." },

{ track:"cs", k:"해시 테이블 — 선형 탐사", cat:"internals",
  q:"<b>개방 주소법(선형 탐사)</b> 해시 테이블을 구현하세요. <code>makeTable(size)</code> 는 <code>{put, find}</code> 를 돌려줍니다. 해시는 <code>key % size</code>, 충돌하면 <b>다음 칸으로</b>(끝에서 처음으로 감아서) 탐사합니다. 같은 키는 값을 덮어쓰고, <b>가득 차면 <code>put</code> 은 <code>false</code></b>, 없는 키의 <code>find</code> 는 <code>undefined</code> 입니다.",
  src:"function makeTable(size) {\n  const keys = new Array(size).fill(null), vals = new Array(size);\n  return {\n    put(k, v) {\n      // TODO: 선형 탐사\n      keys[k % size] = k; vals[k % size] = v;\n      return true;\n    },\n    find(k) {\n      // TODO: 탐사하며 찾기\n      return vals[k % size];\n    },\n  };\n}",
  sol:"function makeTable(size) {\n  const keys = new Array(size).fill(null), vals = new Array(size);\n  return {\n    put(k, v) {\n      for (let i = 0; i < size; i++) {\n        const j = (k % size + i) % size;\n        if (keys[j] === null || keys[j] === k) { keys[j] = k; vals[j] = v; return true; }\n      }\n      return false;\n    },\n    find(k) {\n      for (let i = 0; i < size; i++) {\n        const j = (k % size + i) % size;\n        if (keys[j] === null) return undefined;\n        if (keys[j] === k) return vals[j];\n      }\n      return undefined;\n    },\n  };\n}",
  tests:[["(() => { const tb=makeTable(4); tb.put(1,'a'); tb.put(5,'b'); return [tb.find(1), tb.find(5)]; })()","['a','b']"],
         ["(() => { const tb=makeTable(4); tb.put(1,'a'); tb.put(1,'z'); return tb.find(1); })()","'z'"],
         ["(() => { const tb=makeTable(2); tb.put(0,'a'); tb.put(1,'b'); return tb.put(2,'c'); })()","false"],
         ["(() => { const tb=makeTable(4); tb.put(1,'a'); return tb.find(9); })()","undefined"]],
  edge:[["(() => { const tb=makeTable(3); tb.put(2,'x'); tb.put(5,'y'); return tb.find(5); })()","'y'"],
        ["(() => { const tb=makeTable(2); tb.put(0,'a'); tb.put(0,'b'); return tb.put(2,'c'); })()","true"]],
  ex:"🎯 충돌은 예외가 아니라 <b>일상</b>입니다. <code>1</code> 과 <code>5</code> 는 <code>% 4</code> 로 같은 칸에 가려 하고, 선형 탐사는 '옆 칸으로 밀어 넣기' 로 해결합니다 — find 도 <b>같은 경로를 그대로 따라가야</b> 찾습니다.\n💡 <code>find</code> 가 <b>빈 칸을 만나면 멈추는</b> 것이 성능의 핵심입니다. 빈 칸이 있다는 건 넣을 때 여기까지 밀린 적이 없다는 뜻이므로 더 볼 필요가 없습니다. 이 성질 때문에 삭제는 그냥 비우면 안 되고 묘비(tombstone)를 남겨야 합니다.\n⚠️ 테이블이 차오를수록 탐사가 길어져 O(1) 이 O(n) 으로 무너집니다. 실전 해시맵이 <b>적재율 70~90%에서 리사이즈</b>하는 이유입니다.\n🔧 파이썬 dict·러스트 HashMap 이 개방 주소법 계열입니다. 캐시 지역성이 좋아 체이닝(연결 리스트)보다 실제 메모리에서 빠른 경우가 많습니다." },

{ track:"cs", k:"스택으로 트리 순회", cat:"internals",
  q:"재귀 없이 <b>명시적 스택</b>으로 이진 트리를 <b>전위 순회</b>하세요. <code>preorder(root)</code> 는 <code>{v, l, r}</code> 트리에서 방문 순서(자신→왼쪽→오른쪽)대로 값 배열을 돌려줍니다. 스택은 LIFO 이므로 <b>오른쪽 자식을 먼저 push</b> 해야 왼쪽이 먼저 나옵니다.",
  src:"function preorder(root) {\n  if (!root) return [];\n  const stack = [root], out = [];\n  while (stack.length) {\n    const node = stack.pop();\n    out.push(node.v);\n    if (node.l) stack.push(node.l);\n    if (node.r) stack.push(node.r);\n  }\n  return out;\n}",
  sol:"function preorder(root) {\n  if (!root) return [];\n  const stack = [root], out = [];\n  while (stack.length) {\n    const node = stack.pop();\n    out.push(node.v);\n    if (node.r) stack.push(node.r);\n    if (node.l) stack.push(node.l);\n  }\n  return out;\n}",
  tests:[["preorder({v:1,l:{v:2},r:{v:3}})","[1,2,3]"],
         ["preorder({v:1,l:{v:2,l:{v:4},r:{v:5}},r:{v:3}})","[1,2,4,5,3]"],
         ["preorder({v:1,r:{v:2,r:{v:3}}})","[1,2,3]"],
         ["preorder({v:7})","[7]"]],
  edge:[["preorder(null)","[]"],
        ["preorder({v:1,l:{v:2,l:{v:3}}})","[1,2,3]"]],
  ex:"🎯 시작 코드의 버그는 <b>push 순서</b> 하나입니다. 스택은 나중에 넣은 것이 먼저 나오므로(LIFO), 왼쪽을 먼저 방문하려면 <b>오른쪽을 먼저 push</b> 해야 합니다 — 직관과 반대라 누구나 한 번은 틀립니다.\n💡 재귀 순회와 스택 순회는 같은 알고리즘입니다. 재귀는 <b>호출 스택</b>이 이 스택 역할을 대신해 줄 뿐입니다. 그래서 아주 깊은 트리에서 재귀는 스택 오버플로가 나고, 명시적 스택은 힙 메모리만큼 버팁니다.\n⚠️ 중위(in-order) 순회는 이 방식으로 안 됩니다 — 부모를 pop 하기 전에 왼쪽 전체를 먼저 처리해야 해서 '왼쪽으로 파고들며 쌓기' 라는 다른 패턴이 필요합니다. 전위에서 통한 방법을 그대로 옮기면 틀립니다.\n🔧 파일 탐색기의 폴더 트리, DOM 순회, JSON 직렬화가 모두 전위 순회입니다. 스택 대신 큐를 쓰면 그대로 BFS(레벨 순회)가 됩니다." },

/* ───────────── compiler ───────────── */
{ track:"compiler", k:"어휘 분석 — 최장 일치", cat:"internals",
  q:"<b>어휘 분석기(lexer)</b>를 구현하세요. <code>lex(srcText)</code> 는 소문자 식별자(<code>a-z</code> 시작, 이후 숫자 허용)·정수·연산자(<code>+ - * / = ==</code>)를 토큰으로 자릅니다. 공백은 건너뛰고, <b><code>==</code> 는 <code>=</code> 두 개가 아니라 한 토큰</b>(최장 일치)이며, 모르는 문자를 만나면 <code>null</code> 입니다.",
  src:"function lex(srcText) {\n  // TODO: 최장 일치로 토큰 자르기\n  return srcText.split(' ').map((w) => ({ t: 'id', v: w }));\n}",
  sol:"function lex(srcText) {\n  const out = [];\n  let i = 0;\n  while (i < srcText.length) {\n    const ch = srcText[i];\n    if (ch === ' ') { i++; continue; }\n    if (/[0-9]/.test(ch)) {\n      let j = i; while (j < srcText.length && /[0-9]/.test(srcText[j])) j++;\n      out.push({ t: 'num', v: Number(srcText.slice(i, j)) }); i = j; continue;\n    }\n    if (/[a-z]/.test(ch)) {\n      let j = i; while (j < srcText.length && /[a-z0-9]/.test(srcText[j])) j++;\n      out.push({ t: 'id', v: srcText.slice(i, j) }); i = j; continue;\n    }\n    if (srcText.slice(i, i + 2) === '==') { out.push({ t: 'op', v: '==' }); i += 2; continue; }\n    if ('+-*/='.includes(ch)) { out.push({ t: 'op', v: ch }); i++; continue; }\n    return null;\n  }\n  return out;\n}",
  tests:[["lex('ab1 = 10')","[{t:'id',v:'ab1'},{t:'op',v:'='},{t:'num',v:10}]"],
         ["lex('a==b')","[{t:'id',v:'a'},{t:'op',v:'=='},{t:'id',v:'b'}]"],
         ["lex('12+345')","[{t:'num',v:12},{t:'op',v:'+'},{t:'num',v:345}]"],
         ["lex('a $ b')","null"]],
  edge:[["lex('')","[]"],
        ["lex('x=1==2')","[{t:'id',v:'x'},{t:'op',v:'='},{t:'num',v:1},{t:'op',v:'=='},{t:'num',v:2}]"]],
  ex:"🎯 렉서의 제1규칙은 <b>최장 일치(maximal munch)</b>입니다. <code>==</code> 를 보면 <code>=</code> 두 개가 아니라 가장 긴 토큰 하나로 자릅니다 — 그래서 <b><code>==</code> 검사를 <code>=</code> 보다 먼저</b> 해야 합니다. 순서를 바꾸면 render 는 되는데 파서가 엉뚱한 곳에서 죽습니다.\n💡 숫자·식별자도 같은 원리입니다. <code>345</code> 는 '3, 4, 5' 가 아니라 한 덩어리를 <b>끝까지 읽고</b> 하나의 토큰으로 만듭니다. 렉서는 '문자를 상태에 따라 묶는' 유한 상태 기계입니다.\n⚠️ 모르는 문자를 조용히 건너뛰면 <b>오류 위치가 파서로 밀려나</b> 진단이 어려워집니다. 렉서 단계에서 즉시 실패해야 '몇 번째 글자가 문제' 라고 말할 수 있습니다.\n🔧 자바스크립트의 유명한 함정 <code>a+++b</code> 가 <code>(a++)+b</code> 로 읽히는 것도 최장 일치 때문입니다. 문법 설계는 렉서 규칙까지 고려해야 합니다." },

{ track:"compiler", k:"재귀 하강 파서", cat:"internals",
  q:"<b>재귀 하강</b>으로 수식을 계산하세요. <code>evalExpr(s)</code> 는 <code>+ - * / ( )</code> 와 정수로 된 식(공백 없음)을 계산합니다. 문법은 <code>expr → term (±term)*</code>, <code>term → factor (×÷factor)*</code>, <code>factor → 숫자 | (expr)</code> 이고, <b>같은 우선순위는 왼쪽부터</b>(<code>10-2-3 = 5</code>) 계산합니다.",
  src:"function evalExpr(s) {\n  // TODO: expr → term → factor\n  let acc = 0;\n  s.split(/[+]/).forEach((part) => { acc += Number(part) || 0; });\n  return acc;\n}",
  sol:"function evalExpr(s) {\n  let pos = 0;\n  const factor = () => {\n    if (s[pos] === '(') { pos++; const v = expr(); pos++; return v; }\n    let j = pos; while (j < s.length && /[0-9]/.test(s[j])) j++;\n    const v = Number(s.slice(pos, j)); pos = j; return v;\n  };\n  const term = () => {\n    let v = factor();\n    while (s[pos] === '*' || s[pos] === '/') { const op = s[pos++]; const w = factor(); v = op === '*' ? v * w : v / w; }\n    return v;\n  };\n  const expr = () => {\n    let v = term();\n    while (s[pos] === '+' || s[pos] === '-') { const op = s[pos++]; const w = term(); v = op === '+' ? v + w : v - w; }\n    return v;\n  };\n  return expr();\n}",
  tests:[["evalExpr('2+3*4')","14"],
         ["evalExpr('(2+3)*4')","20"],
         ["evalExpr('10-2-3')","5"],
         ["evalExpr('20/2/5')","2"]],
  edge:[["evalExpr('7')","7"],
        ["evalExpr('2*(3+4)-5')","9"]],
  ex:"🎯 우선순위는 <b>문법 계층</b>으로 표현됩니다. <code>expr</code> 가 <code>term</code> 을 부르고 <code>term</code> 이 <code>factor</code> 를 부르는 구조에서, <b>아래층일수록 먼저 묶입니다</b> — 그래서 <code>*</code> 가 <code>+</code> 보다 세게 결합합니다.\n💡 좌결합은 <b>재귀가 아니라 반복문</b>으로 만듭니다. <code>10-2-3</code> 을 <code>while</code> 로 왼쪽부터 누적하면 <code>(10−2)−3 = 5</code>. 오른쪽 재귀로 쓰면 <code>10−(2−3) = 11</code> 이 됩니다 — 뺄셈·나눗셈에서만 드러나는 함정이라 덧셈으로만 테스트하면 못 잡습니다.\n⚠️ 괄호는 <code>factor</code> 안에서 <code>expr</code> 를 다시 부르는 <b>상호 재귀</b>로 처리됩니다. 이 되부름이 중첩 괄호를 공짜로 처리해 줍니다.\n🔧 진짜 컴파일러의 파서도 구조는 같습니다 — 값을 바로 계산하는 대신 <b>AST 노드를 만들어</b> 돌려줄 뿐입니다. 이 계산기에서 <code>return v</code> 를 <code>return {op, left, right}</code> 로 바꾸면 파서가 됩니다." },

{ track:"compiler", k:"션팅 야드와 후위 계산", cat:"internals",
  q:"<b>션팅 야드</b> 알고리즘을 구현하세요. <code>toPostfix(s)</code> 는 공백으로 구분된 중위 표기식을 후위 표기로 바꿉니다(<code>* /</code> 가 <code>+ -</code> 보다 우선, 같은 우선순위는 좌결합, 괄호 지원). <code>evalPostfix(s)</code> 는 후위 표기를 스택으로 계산합니다 — <b>pop 순서에 주의</b>: 먼저 pop 한 것이 <b>오른쪽</b> 피연산자입니다.",
  src:"function toPostfix(s) {\n  // TODO: 연산자 스택으로 변환\n  return s;\n}\n\nfunction evalPostfix(s) {\n  // TODO: 스택 계산 — pop 순서 주의\n  return 0;\n}",
  sol:"function toPostfix(s) {\n  const prec = { '+': 1, '-': 1, '*': 2, '/': 2 };\n  const out = [], ops = [];\n  s.split(' ').forEach((t) => {\n    if (t === '(') ops.push(t);\n    else if (t === ')') { while (ops[ops.length - 1] !== '(') out.push(ops.pop()); ops.pop(); }\n    else if (prec[t]) {\n      while (ops.length && prec[ops[ops.length - 1]] >= prec[t]) out.push(ops.pop());\n      ops.push(t);\n    } else out.push(t);\n  });\n  return out.concat(ops.reverse()).join(' ');\n}\n\nfunction evalPostfix(s) {\n  const st = [];\n  s.split(' ').forEach((t) => {\n    if (t.length === 1 && '+-*/'.includes(t)) {\n      const b = st.pop(), a = st.pop();\n      st.push(t === '+' ? a + b : t === '-' ? a - b : t === '*' ? a * b : a / b);\n    } else st.push(Number(t));\n  });\n  return st[0];\n}",
  tests:[["toPostfix('3 + 4 * 2')","'3 4 2 * +'"],
         ["toPostfix('( 1 + 2 ) * 3')","'1 2 + 3 *'"],
         ["evalPostfix('10 2 -')","8"],
         ["evalPostfix('5 1 2 + 4 * + 3 -')","14"]],
  edge:[["toPostfix('1 - 2 - 3')","'1 2 - 3 -'"],
        ["evalPostfix('6 2 /')","3"]],
  ex:"🎯 후위 표기의 매력은 <b>괄호와 우선순위가 사라진다</b>는 것입니다. 변환할 때 이미 순서가 결정되어, 계산기는 스택 하나로 왼쪽에서 오른쪽으로 읽기만 하면 됩니다.\n💡 변환 규칙의 핵심은 '<b>스택 위의 연산자가 나보다 세거나 같으면 먼저 내보낸다</b>' 입니다. '같으면' 이 좌결합을 만듭니다 — <code>1 - 2 - 3</code> 이 <code>1 2 - 3 -</code> 이 되는 이유입니다. <code>&gt;=</code> 를 <code>&gt;</code> 로 바꾸면 우결합이 되어 답이 달라집니다.\n⚠️ 계산에서 가장 흔한 버그는 <b>pop 순서</b>입니다. 먼저 pop 한 값이 <b>오른쪽</b> 피연산자라 <code>a - b</code> 의 a 는 <b>두 번째</b> pop 입니다. 덧셈·곱셈은 교환법칙 때문에 버그가 숨고, 뺄셈에서야 드러납니다.\n🔧 JVM·파이썬 바이트코드가 정확히 이 구조의 스택 머신입니다. 컴파일 = 중위(사람의 표기) → 후위(기계의 순서) 변환이라는 감각을 이 문제로 얻을 수 있습니다." },

/* ───────────── arduino ───────────── */
{ track:"arduino", k:"버튼 디바운스", cat:"internals",
  q:"기계식 버튼의 <b>디바운스</b>를 구현하세요. <code>makeDebounce(ms)</code> 는 <code>(reading, now)</code> 를 받는 함수를 돌려줍니다. 새 읽기값이 <b><code>ms</code> 밀리초 동안 유지될 때만</b> 안정값을 그 값으로 바꾸고, 항상 현재 안정값을 돌려줍니다. 읽기값이 흔들리면 대기 시간은 <b>다시 시작</b>됩니다. 초기 안정값은 0 입니다.",
  src:"function makeDebounce(ms) {\n  // TODO: 후보가 ms 동안 유지되면 안정값 갱신\n  return (reading, now) => reading;\n}",
  sol:"function makeDebounce(ms) {\n  let stable = 0, cand = 0, since = 0;\n  return (reading, now) => {\n    if (reading !== cand) { cand = reading; since = now; }\n    if (cand !== stable && now - since >= ms) stable = cand;\n    return stable;\n  };\n}",
  tests:[["(() => { const d=makeDebounce(50); return [d(1,0), d(1,30), d(1,50)]; })()","[0,0,1]"],
         ["(() => { const d=makeDebounce(50); d(1,0); d(0,20); d(1,40); return d(1,100); })()","1"],
         ["(() => { const d=makeDebounce(50); d(1,0); d(0,20); return d(1,60); })()","0"],
         ["(() => { const d=makeDebounce(50); d(1,0); d(1,50); d(0,60); return [d(0,100), d(0,110)]; })()","[1,0]"]],
  edge:[["(() => { const d=makeDebounce(0); return d(1,5); })()","1"],
        ["(() => { const d=makeDebounce(50); return [d(0,0), d(0,100)]; })()","[0,0]"]],
  ex:"🎯 기계식 접점은 누르는 순간 수 밀리초 동안 <b>붙었다 떨어졌다를 반복</b>합니다(채터링). 그대로 읽으면 한 번 눌렀는데 인터럽트가 수십 번 발생합니다 — 카운터가 몇 씩 뛰는 고전적 증상입니다.\n💡 해법은 '<b>같은 값이 충분히 오래 유지될 때만 믿는다</b>' 입니다. 값이 흔들리면 <code>since</code> 를 지금으로 리셋해 대기 시간을 다시 시작하는 것이 핵심입니다 — 리셋 없이 첫 변화 시각만 기억하면 채터링 중간에 잘못 확정됩니다.\n⚠️ <code>delay(50)</code> 으로 기다리는 방식은 그동안 <b>다른 입력·통신이 전부 멈춥니다</b>. 시각을 인자로 받는 이 구조(비차단)라야 루프가 계속 돌 수 있고, 테스트도 가능해집니다.\n🔧 같은 패턴이 소프트웨어에도 그대로 있습니다 — 검색창의 디바운스, 알림 묶어 보내기, 헬스체크의 연속 N회 실패 조건이 모두 '흔들림을 걸러 안정 신호만 통과' 시키는 같은 필터입니다." },

{ track:"arduino", k:"아날로그 값 매핑", cat:"internals",
  q:"센서 값을 다른 범위로 <b>매핑</b>하세요. <code>mapRange(x, inLo, inHi, outLo, outHi)</code> 는 <code>x</code> 를 입력 범위에서 출력 범위로 비례 변환합니다. <b>입력 범위를 벗어나면 잘라내고(clamp)</b>, 결과는 <b>내림(floor)</b>으로 정수화합니다. 출력 범위는 뒤집혀 있을 수도 있습니다.",
  src:"function mapRange(x, inLo, inHi, outLo, outHi) {\n  // TODO: clamp 후 비례 변환, floor\n  return x;\n}",
  sol:"function mapRange(x, inLo, inHi, outLo, outHi) {\n  const cx = Math.min(Math.max(x, inLo), inHi);\n  return Math.floor((cx - inLo) * (outHi - outLo) / (inHi - inLo) + outLo);\n}",
  tests:[["mapRange(512,0,1023,0,255)","127"],
         ["mapRange(0,0,1023,0,255)","0"],
         ["mapRange(1023,0,1023,0,255)","255"],
         ["mapRange(2000,0,1023,0,255)","255"]],
  edge:[["mapRange(-5,0,1023,0,255)","0"],
        ["mapRange(5,0,10,100,0)","50"]],
  ex:"🎯 10비트 ADC(0~1023)를 8비트 PWM(0~255)으로 옮기는 것이 아두이노의 가장 흔한 계산입니다. 공식은 '<b>입력에서의 비율을 출력 범위에 다시 펼치기</b>' — <code>(x−inLo)·(outHi−outLo)/(inHi−inLo)+outLo</code> 입니다.\n💡 <b>곱셈을 먼저, 나눗셈을 나중에</b> 해야 정수 연산에서 정밀도를 잃지 않습니다. <code>x/1023*255</code> 를 정수로 계산하면 <code>x/1023</code> 이 거의 항상 0이 됩니다 — C 정수 나눗셈의 고전적 함정입니다.\n⚠️ 아두이노의 내장 <code>map()</code> 은 <b>범위를 벗어난 입력을 자르지 않습니다</b>. 센서 스파이크가 그대로 출력 범위 밖으로 나가 서보를 한계 밖으로 밀 수 있어, 실전에서는 <code>constrain()</code> 을 함께 쓰는 것이 정석입니다.\n🔧 출력 범위를 <code>(100, 0)</code> 처럼 뒤집으면 <b>반전 매핑</b>이 공짜로 됩니다 — 밝을수록 LED 를 어둡게 하는 조도 반응이 한 줄로 끝납니다." },

{ track:"arduino", k:"링 버퍼 이동평균", cat:"internals",
  q:"노이즈 낀 센서 값을 <b>이동평균</b>으로 부드럽게 만드세요. <code>makeAvg(n)</code> 은 값을 하나 받을 때마다 <b>최근 n개의 평균</b>을 돌려주는 함수를 만듭니다. 링 버퍼로 구현하고, <b>버퍼가 차기 전에는 지금까지 받은 개수로</b> 나눠야 합니다.",
  src:"function makeAvg(n) {\n  const buf = [];\n  return (v) => {\n    buf.push(v);\n    return buf.reduce((a, b) => a + b, 0) / n;\n  };\n}",
  sol:"function makeAvg(n) {\n  const buf = new Array(n).fill(0);\n  let idx = 0, count = 0, sum = 0;\n  return (v) => {\n    if (count === n) sum -= buf[idx];\n    else count++;\n    buf[idx] = v; sum += v;\n    idx = (idx + 1) % n;\n    return sum / count;\n  };\n}",
  tests:[["(() => { const a=makeAvg(3); return [a(3), a(6), a(9), a(12)]; })()","[3,4.5,6,9]"],
         ["(() => { const a=makeAvg(2); a(10); a(20); return a(30); })()","25"],
         ["(() => { const a=makeAvg(4); return a(8); })()","8"],
         ["(() => { const a=makeAvg(3); a(10); a(10); return a(100); })()","40"]],
  edge:[["(() => { const a=makeAvg(1); a(5); return a(9); })()","9"],
        ["(() => { const a=makeAvg(2); a(1); return a(2); })()","1.5"]],
  ex:"🎯 시작 코드의 버그는 <b>분모</b>입니다. 버퍼가 차기 전에 n 으로 나누면 첫 값들이 실제보다 작게 나옵니다 — 전원을 켠 직후 몇 초간 센서가 '낮게' 읽히는 미스터리의 정체가 대개 이것입니다.\n💡 링 버퍼는 <b>메모리가 고정</b>이고, 합계를 증분으로 유지하면(나갈 값 빼고 들어올 값 더하기) 매번 전체를 다시 더하지 않아 <b>O(1)</b> 입니다. 마이크로컨트롤러의 2KB RAM 에서는 이 차이가 생존의 문제입니다.\n⚠️ 창 크기 n 은 트레이드오프입니다 — 크면 부드럽지만 <b>반응이 느려지고</b>, 작으면 빠르지만 노이즈가 남습니다. 스파이크 노이즈(순간 튐)에는 평균보다 <b>중앙값 필터</b>가 훨씬 강합니다.\n🔧 같은 원리가 서버 모니터링의 이동평균 그래프, 주가의 MA 선, 지수이동평균(EMA, 버퍼 없이 <code>avg += α(v−avg)</code>)으로 이어집니다." },

/* ───────────── dbt ───────────── */
{ track:"dbt", k:"모델 의존성 위상 정렬", cat:"internals",
  q:"dbt 가 모델을 실행하는 순서를 계산하세요. <code>order(models)</code> 는 <code>{모델명: [의존 모델들]}</code> 을 받아 <b>의존이 먼저 오는 실행 순서</b>를 돌려줍니다. 여러 개가 가능할 때는 <b>선언 순서에서 앞선 것</b>을 먼저 고르고, <b>순환 의존이면 <code>null</code></b> 입니다.",
  src:"function order(models) {\n  // TODO: 의존 해소 순서대로, 순환이면 null\n  return Object.keys(models);\n}",
  sol:"function order(models) {\n  const done = [], names = Object.keys(models);\n  while (done.length < names.length) {\n    const pick = names.find((nm) => !done.includes(nm) &&\n      models[nm].every((d) => done.includes(d)));\n    if (!pick) return null;\n    done.push(pick);\n  }\n  return done;\n}",
  tests:[["order({raw:[], stg:['raw'], mart:['stg']})","['raw','stg','mart']"],
         ["order({mart:['stg'], stg:['raw'], raw:[]})","['raw','stg','mart']"],
         ["order({a:['b'], b:['a']})","null"],
         ["order({d:['b','c'], b:['a'], c:['a'], a:[]})","['a','b','c','d']"]],
  edge:[["order({})","[]"],
        ["order({a:['a']})","null"]],
  ex:"🎯 dbt 의 <code>ref()</code> 가 만드는 것이 바로 이 <b>의존성 그래프(DAG)</b>입니다. staging 이 raw 보다 먼저 돌면 빈 테이블을 읽게 되므로, 실행 순서는 곧 <b>데이터 정합성</b>입니다.\n💡 위상 정렬의 규칙은 하나입니다 — '<b>의존이 전부 해소된 노드만 실행할 수 있다</b>'. 그런 노드가 하나도 없는데 남아 있다면 그것이 순환의 증거이고, dbt 는 이때 컴파일 단계에서 바로 실패시킵니다.\n⚠️ 순환은 대개 <b>편의상 지름길</b>에서 생깁니다 — mart 가 다른 mart 를 참조하고 그 mart 가 다시 첫 번째를 참조하는 식. 해법은 공통 부분을 <b>아래 계층(staging/intermediate)으로 내리는</b> 것입니다.\n🔧 같은 알고리즘이 Airflow 의 태스크 스케줄링, make 의 빌드 순서, npm 의 의존성 설치에 들어 있습니다. 의존이 없는 노드들은 <b>병렬 실행</b>이 가능한데, dbt 의 <code>--threads</code> 가 정확히 그 지점을 활용합니다." },

{ track:"dbt", k:"증분 모델 — merge", cat:"internals",
  q:"증분(incremental) 모델의 <b>merge 전략</b>을 구현하세요. <code>merge(target, incoming, key)</code> 는 기존 행과 새 행을 <code>key</code> 로 맞춰 <b>있으면 갱신, 없으면 추가</b>(upsert)합니다. 기존 행의 위치는 유지하고 새 행은 뒤에 순서대로 붙이며, <b>원본 배열은 바꾸지 않습니다</b>.",
  src:"function merge(target, incoming, key) {\n  // TODO: key 로 upsert, 원본 불변\n  return target.concat(incoming);\n}",
  sol:"function merge(target, incoming, key) {\n  const out = target.map((r) => {\n    const hit = incoming.find((nr) => nr[key] === r[key]);\n    return hit ? Object.assign({}, r, hit) : r;\n  });\n  incoming.forEach((nr) => {\n    if (!target.some((r) => r[key] === nr[key])) out.push(nr);\n  });\n  return out;\n}",
  tests:[["merge([{id:1,v:'a'}],[{id:1,v:'b'}],'id')","[{id:1,v:'b'}]"],
         ["merge([{id:1,v:'a'}],[{id:2,v:'b'}],'id')","[{id:1,v:'a'},{id:2,v:'b'}]"],
         ["(() => { const tg=[{id:1,v:'a'}]; merge(tg,[{id:1,v:'b'}],'id'); return tg[0].v; })()","'a'"],
         ["merge([{id:1,v:'a'},{id:2,v:'b'}],[{id:2,v:'B'},{id:3,v:'c'}],'id')","[{id:1,v:'a'},{id:2,v:'B'},{id:3,v:'c'}]"]],
  edge:[["merge([],[{id:1,v:'x'}],'id')","[{id:1,v:'x'}]"],
        ["merge([{id:1,v:'a'}],[],'id')","[{id:1,v:'a'}]"]],
  ex:"🎯 매일 전체 테이블을 다시 만들면(full refresh) 데이터가 클수록 비용이 폭증합니다. 증분 모델은 <b>새로 온 것만 처리</b>하되, 이미 있는 키는 <b>갱신</b>해야 합니다 — 그냥 append 만 하면 같은 주문이 두 줄이 되어 매출이 두 배로 잡힙니다.\n💡 그래서 merge 의 본질은 <code>unique_key</code> 입니다. dbt 의 <code>incremental</code> 전략에서 unique_key 를 지정하면 웨어하우스의 MERGE 문으로 번역됩니다 — 이 문제의 로직이 그 축소판입니다.\n⚠️ <b>늦게 도착하는 데이터</b>(late-arriving)가 증분의 최대 함정입니다. '어제 이후 것만' 필터에 걸리지 않은 수정분은 영원히 반영되지 않습니다 — lookback 창을 두거나 주기적 full refresh 로 보정합니다.\n🔧 원본 불변은 재시도 안전성과 직결됩니다. 실행이 중간에 실패해도 target 이 반쯤 바뀐 상태로 남지 않아야 <b>멱등한 재실행</b>이 가능합니다." },

{ track:"dbt", k:"데이터 테스트 3종", cat:"internals",
  q:"dbt 의 기본 <b>데이터 테스트</b>를 구현하세요. 각 함수는 <b>위반한 행의 인덱스 배열</b>을 돌려줍니다. <code>notNull(rows, col)</code> 은 null·undefined 인 행, <code>unique(rows, col)</code> 은 <b>두 번째 이후의 중복</b> 행(첫 등장은 통과), <code>acceptedValues(rows, col, allowed)</code> 는 허용 목록 밖의 행입니다.",
  src:"function notNull(rows, col) {\n  // TODO\n  return [];\n}\n\nfunction unique(rows, col) {\n  // TODO: 첫 등장은 통과\n  return [];\n}\n\nfunction acceptedValues(rows, col, allowed) {\n  // TODO\n  return [];\n}",
  sol:"function notNull(rows, col) {\n  return rows.flatMap((r, i) => (r[col] === null || r[col] === undefined ? [i] : []));\n}\n\nfunction unique(rows, col) {\n  const seen = {};\n  return rows.flatMap((r, i) => {\n    const kv = String(r[col]);\n    if (seen[kv] !== undefined) return [i];\n    seen[kv] = i; return [];\n  });\n}\n\nfunction acceptedValues(rows, col, allowed) {\n  return rows.flatMap((r, i) => (allowed.includes(r[col]) ? [] : [i]));\n}",
  tests:[["notNull([{a:1},{a:null},{a:undefined}],'a')","[1,2]"],
         ["unique([{id:1},{id:2},{id:1}],'id')","[2]"],
         ["acceptedValues([{s:'ok'},{s:'bad'},{s:'ok'}],'s',['ok','fail'])","[1]"],
         ["unique([{id:1},{id:2}],'id')","[]"]],
  edge:[["notNull([],'a')","[]"],
        ["unique([{id:1},{id:1},{id:1}],'id')","[1,2]"]],
  ex:"🎯 dbt 테스트의 발상은 단순합니다 — '<b>위반 행을 찾는 쿼리</b>를 돌려 결과가 0행이면 통과'. 테스트가 데이터 자체를 검사하므로, 코드가 아니라 <b>파이프라인에 들어온 데이터</b>의 품질을 지킵니다.\n💡 <code>unique</code> 가 첫 등장을 통과시키는 것은 '어느 행이 잘못인가' 를 지목하기 위해서입니다. 중복 자체를 세는 것과 위반 행을 찾는 것은 다른 질문입니다 — 후자라야 <b>고칠 대상</b>이 나옵니다.\n⚠️ <code>not_null</code> 과 <code>unique</code> 는 기본 중의 기본이지만, <b>조인 키에 걸어 두지 않으면</b> 팬아웃(행 뻥튀기)을 조인 후에야 발견하게 됩니다. 테스트는 문제를 <b>가장 상류에서</b> 잡는 장치입니다.\n🔧 <code>accepted_values</code> 는 스키마의 열거형이 없는 웨어하우스에서 enum 역할을 합니다. 새 상태값이 추가되면 테스트가 먼저 깨져 '코드와 데이터의 계약' 이 어긋났음을 알려 줍니다." },

/* ───────────── mobile ───────────── */
{ track:"mobile", k:"무한 스크롤 페이지 병합", cat:"internals",
  q:"무한 스크롤의 <b>페이지 병합</b>을 구현하세요. <code>appendPage(state, page)</code> 는 <code>{items, hasMore}</code> 상태에 <code>{items, nextCursor}</code> 응답을 합칩니다. <b>id 가 이미 있는 항목은 제외</b>(페이지 안의 중복 포함)하고, <code>hasMore</code> 는 <b><code>nextCursor !== null</code></b> 로 정합니다. 원본 상태는 바꾸지 마세요.",
  src:"function appendPage(state, page) {\n  // TODO: id 중복 제거 + hasMore 갱신\n  return { items: state.items.concat(page.items), hasMore: true };\n}",
  sol:"function appendPage(state, page) {\n  const seen = new Set(state.items.map((it) => it.id));\n  const fresh = [];\n  page.items.forEach((it) => {\n    if (!seen.has(it.id)) { seen.add(it.id); fresh.push(it); }\n  });\n  return { items: state.items.concat(fresh), hasMore: page.nextCursor !== null };\n}",
  tests:[["appendPage({items:[{id:1}],hasMore:true},{items:[{id:2}],nextCursor:'c'})","{items:[{id:1},{id:2}],hasMore:true}"],
         ["appendPage({items:[{id:1}],hasMore:true},{items:[{id:1},{id:2}],nextCursor:null})","{items:[{id:1},{id:2}],hasMore:false}"],
         ["(() => { const st={items:[{id:1}],hasMore:true}; appendPage(st,{items:[{id:2}],nextCursor:null}); return st.items.length; })()","1"],
         ["appendPage({items:[{id:1}],hasMore:true},{items:[],nextCursor:null})","{items:[{id:1}],hasMore:false}"]],
  edge:[["appendPage({items:[],hasMore:true},{items:[{id:9}],nextCursor:'x'})","{items:[{id:9}],hasMore:true}"],
        ["appendPage({items:[],hasMore:true},{items:[{id:1},{id:1}],nextCursor:null})","{items:[{id:1}],hasMore:false}"]],
  ex:"🎯 스크롤 중에 <b>새 글이 위에 끼어들면</b> 오프셋 기반 페이지네이션은 같은 항목을 다음 페이지에서 또 내려보냅니다. 중복 제거 없이 붙이면 리스트에 같은 카드가 두 번 보이고, key 중복으로 렌더링 경고까지 납니다.\n💡 그래서 모바일 피드는 <b>커서 기반</b>이 표준입니다. '몇 번째부터' 가 아니라 '이 항목 다음부터' 를 요청하므로 끼어듦에 강합니다 — 그래도 재시도·캐시 때문에 중복은 여전히 올 수 있어 <b>클라이언트 쪽 방어</b>가 필요합니다.\n⚠️ <code>hasMore</code> 를 <code>items.length &gt; 0</code> 으로 정하면 <b>마지막 페이지가 우연히 꽉 찼을 때</b> 판별할 수 없습니다. 서버가 명시한 <code>nextCursor</code> 의 null 여부가 유일하게 믿을 수 있는 신호입니다.\n🔧 상태를 새 객체로 돌려주는 것은 React Native 의 <code>FlatList</code> 가 <code>data</code> 참조 변화로 갱신을 감지하기 때문입니다 — 제자리에서 push 하면 화면이 안 바뀝니다." },

{ track:"mobile", k:"오프라인 큐 flush", cat:"internals",
  q:"오프라인에서 쌓인 작업 큐를 <b>순서대로 전송</b>하세요. <code>flush(queue, send)</code> 는 각 작업에 <code>send(action)</code> 을 호출해 <code>true</code>(성공)/<code>false</code>(실패)를 받습니다. <b>실패하면 즉시 멈추고</b>, <code>{sent, rest}</code> — 보낸 것들과 남은 것들(실패한 것 포함, 순서 보존) — 를 돌려줍니다. 원본 큐는 바꾸지 마세요.",
  src:"function flush(queue, send) {\n  // TODO: 실패 시 중단, {sent, rest}\n  queue.forEach(send);\n  return { sent: queue, rest: [] };\n}",
  sol:"function flush(queue, send) {\n  const sent = [];\n  for (let i = 0; i < queue.length; i++) {\n    if (!send(queue[i])) return { sent, rest: queue.slice(i) };\n    sent.push(queue[i]);\n  }\n  return { sent, rest: [] };\n}",
  tests:[["flush(['a','b'],()=>true)","{sent:['a','b'],rest:[]}"],
         ["flush(['a','b','c'],(x)=>x!=='b')","{sent:['a'],rest:['b','c']}"],
         ["(() => { const got=[]; flush(['x','y'],(a)=>{got.push(a); return true;}); return got; })()","['x','y']"],
         ["flush(['a'],()=>false)","{sent:[],rest:['a']}"]],
  edge:[["flush([],()=>true)","{sent:[],rest:[]}"],
        ["(() => { const memq=['a','b']; flush(memq,()=>false); return memq.length; })()","2"]],
  ex:"🎯 오프라인 우선 앱의 핵심 규칙은 <b>순서 보존</b>입니다. '수정 → 삭제' 를 '삭제 → 수정' 으로 보내면 서버에서 없는 문서를 수정하려다 실패합니다. 큐는 사용자의 <b>의도의 순서</b>를 담고 있습니다.\n💡 실패 시 <b>즉시 멈추는</b> 이유도 순서 때문입니다. 실패한 작업을 건너뛰고 다음을 보내면 뒤의 작업이 앞의 결과에 의존할 때 데이터가 꼬입니다. 실패 지점부터 통째로 남겨야 다음 flush 에서 <b>이어서</b> 보낼 수 있습니다.\n⚠️ 남긴 작업을 다시 보낼 것이므로 서버 API 는 <b>멱등</b>해야 합니다 — 같은 요청이 두 번 가도 결과가 하나여야 합니다. 클라이언트가 만든 요청 ID(idempotency key)가 그 장치입니다.\n🔧 원본 큐를 건드리지 않는 것은 flush 도중 앱이 죽어도 <b>저장된 큐가 온전</b>해야 하기 때문입니다. 성공 목록을 확인한 뒤에야 저장소에서 지우는 2단계가 안전합니다." },

{ track:"mobile", k:"이미지 캐시 — 용량 LRU", cat:"internals",
  q:"이미지 캐시를 <b>바이트 용량 기준 LRU</b> 로 구현하세요. <code>makeCache(cap)</code> 은 <code>{put, get}</code> 을 돌려줍니다. <code>put(key, size)</code> 는 공간이 모자라면 <b>가장 오래 안 쓴 항목부터 제거</b>하고 넣습니다(<b>항목 하나가 <code>cap</code> 을 넘으면 <code>false</code></b>). <code>get(key)</code> 은 적중 시 <code>true</code> 를 돌려주며 그 항목을 <b>최근 사용으로 갱신</b>합니다. 같은 키의 put 은 크기를 교체합니다.",
  src:"function makeCache(cap) {\n  const m = new Map();\n  return {\n    put(key, size) {\n      // TODO: 용량 초과 시 LRU 제거\n      m.set(key, size);\n      return true;\n    },\n    get(key) {\n      // TODO: 적중 시 최근 사용 갱신\n      return m.has(key);\n    },\n  };\n}",
  sol:"function makeCache(cap) {\n  const m = new Map();\n  let used = 0;\n  return {\n    put(key, size) {\n      if (size > cap) return false;\n      if (m.has(key)) { used -= m.get(key); m.delete(key); }\n      while (used + size > cap) {\n        const old = m.keys().next().value;\n        used -= m.get(old); m.delete(old);\n      }\n      m.set(key, size); used += size;\n      return true;\n    },\n    get(key) {\n      if (!m.has(key)) return false;\n      const size = m.get(key);\n      m.delete(key); m.set(key, size);\n      return true;\n    },\n  };\n}",
  tests:[["(() => { const c=makeCache(100); c.put('a',60); c.put('b',30); c.put('c',30); return [c.get('a'), c.get('b')]; })()","[false,true]"],
         ["(() => { const c=makeCache(100); c.put('a',60); c.put('b',30); c.get('a'); c.put('c',30); return [c.get('a'), c.get('b')]; })()","[true,false]"],
         ["(() => { const c=makeCache(50); return c.put('big',51); })()","false"],
         ["(() => { const c=makeCache(100); c.put('a',60); c.put('a',10); c.put('b',80); return c.get('a'); })()","true"]],
  edge:[["(() => { const c=makeCache(100); c.put('a',100); c.put('b',1); return c.get('a'); })()","false"],
        ["(() => { const c=makeCache(10); return c.get('nope'); })()","false"]],
  ex:"🎯 이미지 캐시는 <b>개수가 아니라 바이트</b>로 제한해야 합니다. 썸네일 100장과 원본 사진 100장은 메모리 사용량이 수백 배 차이라, 개수 제한은 OOM 을 막지 못합니다.\n💡 자바스크립트 <code>Map</code> 은 <b>삽입 순서를 보존</b>하므로, '지우고 다시 넣기' 로 최근 사용을 맨 뒤로 보내면 맨 앞이 항상 LRU 가 됩니다 — 별도 연결 리스트 없이 LRU 가 구현되는 우아한 트릭입니다.\n⚠️ <code>get</code> 이 순서를 갱신하지 않으면 LRU 가 아니라 <b>FIFO</b> 가 됩니다. 매 화면마다 쓰는 프로필 아이콘이 '오래 전에 넣었다' 는 이유로 쫓겨나 네트워크를 다시 타는 성능 버그가 조용히 생깁니다.\n🔧 실전 모바일 캐시는 이 구조의 2층입니다 — 메모리 LRU(빠름, 작음) 아래 디스크 LRU(느림, 큼)를 두고, 메모리에서 밀려난 것을 디스크에서 다시 찾습니다. Glide·Coil·SDWebImage 가 모두 이 구조입니다." },
];
