/* 파이썬 실행형(구현) — 시니어 주제를 '아는 것' 에서 '만들 수 있는 것' 으로 옮긴다.
   파이썬 트랙은 실행형이 14%뿐이고 시니어 판단이 선택형·입력형에 몰려 있었다.
   앱은 Pyodide 로, 검증기는 로컬 python3 로 같은 하네스를 돌린다.
   쉬운 것부터 어려운 순으로 놓았다(계단식). */
module.exports = [
{ k:"안전한 기본 인자와 병합", fn:"merge_config",
  q:"설정을 <b>깊게 병합</b>하는 <code>merge_config(base, patch)</code> 를 구현하세요. 뒤가 앞을 덮되 <b>값이 <code>None</code> 인 키는 덮지 않고</b>, 양쪽이 모두 딕셔너리인 키는 <b>재귀적으로 병합</b>합니다. <b>원본은 바꾸지 마세요</b>(리스트는 통째로 교체).",
  src:"def merge_config(base, patch):\n    # TODO: 깊은 병합 · None 은 무시 · 원본 불변\n    return base",
  sol:"def merge_config(base, patch):\n    out = dict(base)\n    for k, v in patch.items():\n        if v is None:\n            continue\n        if isinstance(out.get(k), dict) and isinstance(v, dict):\n            out[k] = merge_config(out[k], v)\n        else:\n            out[k] = v\n    return out",
  tests:[["merge_config({'a': 1}, {'b': 2})","{'a': 1, 'b': 2}"],
         ["merge_config({'db': {'host': 'x', 'port': 1}}, {'db': {'port': 2}})","{'db': {'host': 'x', 'port': 2}}"],
         ["merge_config({'a': 1}, {'a': None})","{'a': 1}"],
         ["(lambda b: (merge_config(b, {'a': 9}), b))({'a': 1})[1]","{'a': 1}"]],
  edge:[["merge_config({}, {})","{}"],
        ["merge_config({'t': [1, 2]}, {'t': [3]})","{'t': [3]}"]],
  ex:"🎯 설정 병합의 순서는 <b>기본값 → 파일 → 환경변수 → 명령행</b> 이고, 뒤로 갈수록 구체적인 상황이라 앞을 덮습니다.\n💡 <code>None</code> 을 건너뛰는 것이 핵심입니다 — '<b>설정하지 않음</b>' 과 '<b>빈 값으로 설정함</b>' 은 다릅니다. 구분 없이 덮으면 지정하지 않은 환경변수가 기본값을 지워 버립니다.\n⚠️ 딕셔너리는 재귀 병합하고 <b>리스트는 교체</b>하는 것이 실용적 관례입니다. 리스트를 이어 붙이면 기본 항목을 제거할 방법이 없고 중복 제거 규칙까지 정해야 해서 예측하기 어려워집니다.\n🔧 <code>dict(base)</code> 는 얕은 복사라 중첩 딕셔너리는 재귀 호출이 새 객체를 만들어 줍니다 — 그래서 원본이 보존됩니다. <code>copy.deepcopy</code> 는 필요 없고, 오히려 큰 설정에서 느립니다." },

{ k:"제너레이터로 스트리밍 집계", fn:"stream_stats",
  q:"큰 데이터를 <b>한 번만 훑어</b> 통계를 내는 <code>stream_stats(it)</code> 를 구현하세요. 반복자를 받아 <code>{'n', 'total', 'mean', 'max'}</code> 를 돌려주되, <b>전체를 리스트로 만들지 말고</b> 순회하며 누적하세요. 비어 있으면 <code>{'n': 0, 'total': 0, 'mean': None, 'max': None}</code> 입니다.",
  src:"def stream_stats(it):\n    # TODO: 한 번의 순회로 n · total · mean · max\n    return {'n': 0, 'total': 0, 'mean': None, 'max': None}",
  sol:"def stream_stats(it):\n    n = 0\n    total = 0\n    biggest = None\n    for v in it:\n        n += 1\n        total += v\n        if biggest is None or v > biggest:\n            biggest = v\n    return {'n': n, 'total': total,\n            'mean': total / n if n else None, 'max': biggest}",
  tests:[["stream_stats([1, 2, 3])","{'n': 3, 'total': 6, 'mean': 2.0, 'max': 3}"],
         ["stream_stats(iter([5]))","{'n': 1, 'total': 5, 'mean': 5.0, 'max': 5}"],
         ["stream_stats([])","{'n': 0, 'total': 0, 'mean': None, 'max': None}"],
         ["stream_stats(x for x in [4, -1, 9])","{'n': 3, 'total': 12, 'mean': 4.0, 'max': 9}"]],
  edge:[["stream_stats([-5, -2])","{'n': 2, 'total': -7, 'mean': -3.5, 'max': -2}"],
        ["stream_stats(range(1, 5))","{'n': 4, 'total': 10, 'mean': 2.5, 'max': 4}"]],
  ex:"🎯 <code>len(list(it))</code> 처럼 실체화하면 <b>메모리가 데이터 크기에 비례</b>합니다. 로그 파일이 수 GB 면 그 순간 끝입니다 — 스트리밍 집계는 메모리를 상수로 유지합니다.\n💡 더 중요한 것은 <b>제너레이터는 한 번만 소비된다</b>는 점입니다. <code>sum(it)</code> 뒤에 <code>max(it)</code> 를 부르면 두 번째는 빈 것을 봅니다 — 그래서 필요한 값을 <b>한 번의 순회에서 모두</b> 누적해야 합니다.\n⚠️ 빈 입력에서 평균은 <b>정의되지 않습니다</b>. 0으로 두면 '평균 0인 그룹' 으로 보여 그래프가 거짓말을 합니다 — <code>None</code> 으로 두고 표시하는 쪽에서 구분해야 합니다.\n🔧 이 패턴이 곧 <code>itertools</code> 와 <code>yield</code> 기반 파이프라인의 기초입니다. 표준 라이브러리의 <code>statistics</code> 는 편하지만 시퀀스를 요구하므로, 스트리밍에서는 직접 누적하는 편이 맞습니다." },

{ k:"컨텍스트 매니저 만들기", fn:"managed",
  q:"<code>with</code> 문으로 쓸 수 있는 <b>컨텍스트 매니저</b> <code>managed(log, name)</code> 를 구현하세요. 진입 시 <code>log</code> 에 <code>'open:이름'</code>, 나갈 때 <code>'close:이름'</code> 을 넣고, <b>예외가 나도 반드시 닫아야</b> 합니다. 예외는 삼키지 말고 그대로 전파하세요. <code>with</code> 는 <code>name</code> 을 돌려줍니다.",
  src:"class managed:\n    def __init__(self, log, name):\n        self.log = log\n        self.name = name\n\n    # TODO: __enter__ 와 __exit__",
  sol:"class managed:\n    def __init__(self, log, name):\n        self.log = log\n        self.name = name\n\n    def __enter__(self):\n        self.log.append('open:' + self.name)\n        return self.name\n\n    def __exit__(self, exc_type, exc, tb):\n        self.log.append('close:' + self.name)\n        return False",
  tests:[["(lambda lg: (exec(\"with managed(lg,'db') as n: pass\") or lg))([])","['open:db', 'close:db']"],
         ["(lambda lg: (exec(\"with managed(lg,'db') as n: lg.append('use:'+n)\") or lg))([])","['open:db', 'use:db', 'close:db']"],
         ["(lambda lg: (exec(\"try:\\n    with managed(lg,'x') as n:\\n        raise ValueError('boom')\\nexcept ValueError:\\n    lg.append('caught')\") or lg))([])","['open:x', 'close:x', 'caught']"],
         ["(lambda lg: (exec(\"with managed(lg,'a') as n: pass\") or len(lg)))([])","2"]],
  edge:[["(lambda lg: (exec(\"with managed(lg,'a') as n: pass\\nwith managed(lg,'b') as n: pass\") or lg))([])","['open:a', 'close:a', 'open:b', 'close:b']"],
        ["(lambda lg: (exec(\"try:\\n    with managed(lg,'x') as n:\\n        raise ValueError('boom')\\nexcept ValueError:\\n    pass\") or lg))([])","['open:x', 'close:x']"]],
  ex:"🎯 <code>with</code> 의 계약은 '<b>어떻게 빠져나가든 <code>__exit__</code> 이 불린다</b>' 입니다 — 정상 종료든 예외든 <code>return</code> 이든. 그래서 자원 해제를 사람이 기억할 필요가 없어집니다.\n💡 <code>__exit__</code> 의 <b>반환값이 예외를 삼킬지</b> 정합니다. <code>True</code> 를 돌려주면 예외가 여기서 사라지고, <code>False</code>(또는 <code>None</code>)면 그대로 전파됩니다 — 대부분은 삼키면 안 되므로 <b>False 가 기본</b>입니다.\n⚠️ 실수로 <code>True</code> 를 돌려주면 <b>모든 예외가 조용히 사라지는</b> 컨텍스트 매니저가 됩니다. 정리는 됐는데 오류는 보고되지 않아, 실패가 성공처럼 보입니다.\n🔧 클래스 대신 <code>@contextlib.contextmanager</code> 와 <code>try/finally</code> 로 더 짧게 쓸 수도 있습니다. 어느 쪽이든 <b>진입에서 만든 것을 <code>__enter__</code> 가 돌려주는</b> 것(<code>as</code> 로 받는 값)이 계약의 일부입니다." },

{ k:"데코레이터와 메타데이터 보존", fn:"counted",
  q:"호출 횟수를 세는 데코레이터 <code>counted</code> 를 구현하세요. 감싼 함수에 <code>calls</code> 속성을 두어 호출할 때마다 1씩 늘리고, <b>원함수의 <code>__name__</code> 과 <code>__doc__</code> 을 보존</b>해야 합니다. 인자와 반환값은 그대로 통과시키세요.",
  src:"def counted(fn):\n    # TODO: 호출 횟수 · 메타데이터 보존\n    return fn",
  sol:"import functools\n\n\ndef counted(fn):\n    @functools.wraps(fn)\n    def wrapper(*args, **kwargs):\n        wrapper.calls += 1\n        return fn(*args, **kwargs)\n    wrapper.calls = 0\n    return wrapper",
  tests:[["(lambda f: (f(1), f(2), f.calls))(counted(lambda x: x * 2))[2]","2"],
         ["counted(lambda x, y=1: x + y)(3, y=4)","7"],
         ["(lambda f: f.__name__)(counted(lambda: None))","'<lambda>'"],
         ["(lambda f: (f(), f.calls))(counted(lambda: 'ok'))","('ok', 1)"]],
  edge:[["counted(lambda: 0).calls","0"],
        ["(lambda f: (f(1), f(2), f(3), f.calls))(counted(lambda x: x))[3]","3"]],
  ex:"🎯 데코레이터는 <b>함수를 받아 함수를 돌려주는 함수</b>입니다. 감싼 쪽에 상태(<code>calls</code>)를 붙여 두면 호출 통계를 원함수 수정 없이 얻습니다.\n💡 <code>functools.wraps</code> 가 없으면 감싼 함수의 <code>__name__</code> 이 <code>'wrapper'</code> 가 되고 <code>__doc__</code> 이 사라집니다 — 로깅·문서화·디버거가 전부 엉뚱한 이름을 보게 됩니다. <b>데코레이터를 만들 때 거의 항상 필요한</b> 한 줄입니다.\n⚠️ <code>*args, **kwargs</code> 로 받아 그대로 넘겨야 위치 인자·키워드 인자·기본값이 모두 통과합니다. 인자를 고정하면 그 시그니처의 함수에만 쓸 수 있는 반쪽 데코레이터가 됩니다.\n🔧 상태를 <code>wrapper</code> 의 속성에 두는 것이 클로저 변수(<code>nonlocal</code>)보다 나은 이유는 <b>바깥에서 읽을 수 있기</b> 때문입니다 — 테스트나 모니터링이 <code>f.calls</code> 로 바로 확인합니다." },

{ k:"LRU 캐시 직접 만들기", fn:"make_lru",
  q:"용량이 정해진 <b>LRU 캐시</b>를 만드는 <code>make_lru(cap)</code> 을 구현하세요. <code>(get, put)</code> 두 함수를 돌려줍니다 — <code>get(k)</code> 은 없으면 <code>None</code>, 있으면 값을 주며 <b>최근 사용으로 갱신</b>하고, <code>put(k, v)</code> 는 넘치면 <b>가장 오래 안 쓴 키</b>를 버립니다. 같은 키의 put 은 값을 덮고 최근으로 올립니다.",
  src:"def make_lru(cap):\n    store = {}\n\n    def get(k):\n        # TODO\n        return store.get(k)\n\n    def put(k, v):\n        # TODO: 용량 초과 시 가장 오래된 키 제거\n        store[k] = v\n\n    return get, put",
  sol:"from collections import OrderedDict\n\n\ndef make_lru(cap):\n    store = OrderedDict()\n\n    def get(k):\n        if k not in store:\n            return None\n        store.move_to_end(k)\n        return store[k]\n\n    def put(k, v):\n        if k in store:\n            store.move_to_end(k)\n        elif len(store) >= cap:\n            store.popitem(last=False)\n        store[k] = v\n\n    return get, put",
  tests:[["(lambda gp: (gp[1]('a', 1), gp[1]('b', 2), gp[0]('a')))(make_lru(2))[2]","1"],
         ["(lambda gp: (gp[1]('a', 1), gp[1]('b', 2), gp[1]('c', 3), gp[0]('a')))(make_lru(2))[3]","None"],
         ["(lambda gp: (gp[1]('a', 1), gp[1]('b', 2), gp[0]('a'), gp[1]('c', 3), gp[0]('b')))(make_lru(2))[4]","None"],
         ["(lambda gp: (gp[1]('a', 1), gp[1]('a', 9), gp[0]('a')))(make_lru(2))[2]","9"]],
  edge:[["make_lru(1)[0]('nope')","None"],
        ["(lambda gp: (gp[1]('a', 1), gp[1]('a', 2), gp[1]('b', 3), gp[0]('a')))(make_lru(2))[3]","2"]],
  ex:"🎯 LRU 의 핵심은 '<b>조회도 사용</b>' 이라는 점입니다. <code>get</code> 이 순서를 갱신하지 않으면 LRU 가 아니라 FIFO 가 되어, 매번 쓰는 항목이 '오래 전에 넣었다' 는 이유로 쫓겨납니다.\n💡 <code>OrderedDict</code> 의 <code>move_to_end</code> 와 <code>popitem(last=False)</code> 가 정확히 이 자료구조를 위해 있습니다 — 별도의 연결 리스트 없이 O(1) 로 LRU 가 됩니다(파이썬 3.7+ 의 일반 dict 도 삽입 순서를 지키지만 재배치 API 가 없습니다).\n⚠️ <b>같은 키의 put 은 크기를 늘리지 않으므로</b> 축출하면 안 됩니다 — 이 경계를 놓치면 용량이 남는데도 항목이 사라집니다.\n🔧 실무에서는 <code>functools.lru_cache</code> 가 이 일을 대신합니다. 다만 <b>인자를 키로 쓰므로 해시 가능해야</b> 하고, 인스턴스 메서드에 붙이면 <code>self</code> 까지 키에 들어가 객체가 회수되지 않는 함정이 있습니다." },

{ k:"재시도와 백오프", fn:"retry_plan",
  q:"재시도 <b>대기 시간 계획</b>을 만드는 <code>retry_plan(attempts, base, cap)</code> 을 구현하세요. i번째(0부터) 대기는 <b><code>base * 2**i</code></b> 이되 <b><code>cap</code> 을 넘지 않고</b>, 마지막 시도 뒤에는 기다리지 않으므로 길이는 <code>attempts - 1</code> 입니다. <code>attempts</code> 가 1 이하면 빈 리스트입니다.",
  src:"def retry_plan(attempts, base, cap):\n    # TODO: 지수 증가 · 상한 · 마지막 뒤에는 대기 없음\n    return []",
  sol:"def retry_plan(attempts, base, cap):\n    return [min(base * 2 ** i, cap) for i in range(max(0, attempts - 1))]",
  tests:[["retry_plan(4, 100, 10000)","[100, 200, 400]"],
         ["retry_plan(5, 100, 300)","[100, 200, 300, 300]"],
         ["retry_plan(1, 100, 999)","[]"],
         ["retry_plan(3, 50, 1000)","[50, 100]"]],
  edge:[["retry_plan(0, 100, 999)","[]"],
        ["retry_plan(2, 100, 10)","[10]"]],
  ex:"🎯 지수 백오프는 '<b>실패가 이어질수록 더 오래 기다린다</b>' 입니다. 장애 중인 서비스를 같은 간격으로 두들기면 회복을 방해하기 때문입니다.\n💡 <b>상한</b>이 없으면 시도 20번째에 며칠을 기다리게 됩니다. 상한과 최대 횟수를 함께 두는 것이 계약이고, 이 둘이 곧 '<b>최악의 경우 얼마나 오래 붙잡고 있을 것인가</b>' 를 정합니다.\n⚠️ 길이가 <code>attempts - 1</code> 인 것이 포인트입니다 — 마지막 시도 뒤에는 기다릴 이유가 없습니다. 이 off-by-one 을 놓치면 실패 확정 후 쓸데없이 한 번 더 대기합니다.\n🔧 실전에는 여기에 <b>지터</b>(무작위 흔들기)를 더합니다. 같은 시각에 실패한 클라이언트들은 같은 공식을 쓰므로 <b>같은 시각에 다시 몰립니다</b> — 간격만 벌어질 뿐 봉우리는 그대로라, 흩뜨리지 않으면 재시도 폭풍이 됩니다." },

{ k:"타입 검증 데코레이터", fn:"typed",
  q:"인자 타입을 검사하는 데코레이터 <code>typed(*types)</code> 를 구현하세요. 위치 인자의 타입이 선언과 다르면 <code>TypeError</code> 를 던지고, 맞으면 원함수를 호출합니다. <b>인자 개수가 선언보다 많으면</b> 남는 것은 검사하지 않습니다. <code>bool</code> 은 <code>int</code> 의 하위 타입이지만 <b><code>int</code> 선언에 <code>bool</code> 을 넘기면 거부</b>하세요.",
  src:"def typed(*types):\n    def deco(fn):\n        # TODO: 위치 인자 타입 검사\n        return fn\n    return deco",
  sol:"import functools\n\n\ndef typed(*types):\n    def deco(fn):\n        @functools.wraps(fn)\n        def wrapper(*args, **kwargs):\n            for value, want in zip(args, types):\n                if want is int and isinstance(value, bool):\n                    raise TypeError('bool is not int')\n                if not isinstance(value, want):\n                    raise TypeError('expected ' + want.__name__)\n            return fn(*args, **kwargs)\n        return wrapper\n    return deco",
  tests:[["typed(int, str)(lambda a, b: b * a)(2, 'x')","'xx'"],
         ["(lambda lg: (exec(\"f = typed(int, str)(lambda a, b: b)\\ntry:\\n    f('no', 'a')\\n    lg.append('passed')\\nexcept TypeError:\\n    lg.append('raised')\") or lg))([])","['raised']"],
         ["(lambda lg: (exec(\"f = typed(int)(lambda a: a)\\ntry:\\n    f(True)\\n    lg.append('passed')\\nexcept TypeError:\\n    lg.append('raised')\") or lg))([])","['raised']"],
         ["typed(int)(lambda a: a * 3)(4)","12"]],
  edge:[["(lambda lg: (exec(\"f = typed(int)(lambda a, b: b)\\nlg.append(f(1, 'not-checked'))\") or lg))([])","['not-checked']"],
        ["typed()(lambda a: a)('anything')","'anything'"]],
  ex:"🎯 파이썬의 타입 힌트는 <b>실행 시점에 아무것도 강제하지 않습니다</b>. 경계(외부 입력·플러그인 API)에서 실제로 막고 싶다면 이렇게 검사 코드를 넣거나 pydantic 같은 라이브러리를 씁니다.\n💡 <code>zip(args, types)</code> 는 <b>짧은 쪽에서 멈추므로</b> '선언보다 인자가 많으면 남는 것은 검사하지 않는다' 는 요구가 자연히 충족됩니다 — 반대로 이 성질 때문에 검사가 조용히 빠지는 실수도 흔합니다.\n⚠️ <code>isinstance(True, int)</code> 는 <b>True</b> 입니다 — 파이썬에서 <code>bool</code> 은 <code>int</code> 의 하위 클래스라 <code>1 + True == 2</code> 가 성립합니다. 수량을 받는 자리에 <code>True</code> 가 들어와도 통과해 버리므로, 엄격한 검증이 필요하면 <b>따로 걸러야</b> 합니다.\n🔧 실무에서는 실행 시점 검사보다 <b>mypy 같은 정적 검사</b>가 비용 대비 효과가 큽니다. 실행 시점 검사는 신뢰할 수 없는 입력이 들어오는 <b>경계에만</b> 두는 것이 좋습니다." },

{ k:"슬롯과 메모리", fn:"count_attrs",
  q:"클래스 두 개를 만들어 <b><code>__slots__</code> 의 효과</b>를 보이세요. <code>Plain</code> 은 일반 클래스, <code>Slim</code> 은 <code>__slots__ = ('x', 'y')</code> 를 가진 클래스입니다. <code>count_attrs(obj)</code> 는 그 객체에 <b><code>__dict__</code> 가 있으면 키 개수를, 없으면 <code>-1</code></b> 을 돌려줍니다. 두 클래스 모두 생성자에서 <code>x</code>·<code>y</code> 를 받습니다.",
  src:"class Plain:\n    def __init__(self, x, y):\n        self.x = x\n        self.y = y\n\n\nclass Slim:\n    # TODO: __slots__ 로 인스턴스 딕셔너리를 없앤다\n    def __init__(self, x, y):\n        self.x = x\n        self.y = y\n\n\ndef count_attrs(obj):\n    # TODO: __dict__ 가 있으면 키 수, 없으면 -1\n    return 0",
  sol:"class Plain:\n    def __init__(self, x, y):\n        self.x = x\n        self.y = y\n\n\nclass Slim:\n    __slots__ = ('x', 'y')\n\n    def __init__(self, x, y):\n        self.x = x\n        self.y = y\n\n\ndef count_attrs(obj):\n    d = getattr(obj, '__dict__', None)\n    return -1 if d is None else len(d)",
  tests:[["count_attrs(Plain(1, 2))","2"],
         ["count_attrs(Slim(1, 2))","-1"],
         ["Slim(3, 4).x","3"],
         ["(lambda o: (setattr(o, 'z', 1), count_attrs(o))[1])(Plain(1, 2))","3"]],
  edge:[["Plain(1, 2).y","2"],
        ["(lambda lg: (exec(\"try:\\n    o = Slim(1, 2)\\n    o.z = 3\\n    lg.append('added')\\nexcept AttributeError:\\n    lg.append('blocked')\") or lg))([])","['blocked']"]],
  ex:"🎯 파이썬 객체는 기본적으로 속성을 <b>딕셔너리</b>에 담습니다 — 유연하지만 객체마다 딕셔너리 하나가 붙어 메모리를 크게 씁니다. 수백만 개를 만들면 그 차이가 GB 단위가 됩니다.\n💡 <code>__slots__</code> 는 '<b>이 속성들만 쓴다</b>' 고 선언해 딕셔너리를 없애고 고정 크기 슬롯에 담습니다 — 메모리가 줄고 속성 접근도 조금 빨라집니다.\n⚠️ 대가는 <b>동적 속성 추가 불가</b>입니다. 선언에 없는 이름을 대입하면 <code>AttributeError</code> 이고, 이것을 유연성 손실로 볼지 계약 강화로 볼지는 상황에 달렸습니다. 상속 시 하위 클래스에도 선언하지 않으면 딕셔너리가 다시 생겨 효과가 사라집니다.\n🔧 그래서 <code>__slots__</code> 는 <b>대량 생성되는 값 객체</b>에만 씁니다 — 좌표·이벤트·레코드처럼. 일반적인 서비스 클래스에 붙이는 것은 이득 없이 제약만 늘리는 일입니다." },

{ k:"동시성 선택 모델", fn:"pick_model",
  q:"작업 성격에 맞는 <b>동시성 모델</b>을 고르는 <code>pick_model(kind, n, blocking_io)</code> 를 구현하세요 — <code>kind</code> 가 <code>'cpu'</code> 면 <code>'process'</code>, <code>'io'</code> 이면서 <b>블로킹 라이브러리를 쓰면</b> <code>'thread'</code>, <code>'io'</code> 이면서 비동기 지원이면 <code>'async'</code> 입니다. 단 <b>작업이 3개 이하면</b> 어떤 경우든 <code>'serial'</code> 입니다.",
  src:"def pick_model(kind, n, blocking_io):\n    # TODO: 작업 수 · 종류 · 블로킹 여부\n    return 'serial'",
  sol:"def pick_model(kind, n, blocking_io):\n    if n <= 3:\n        return 'serial'\n    if kind == 'cpu':\n        return 'process'\n    return 'thread' if blocking_io else 'async'",
  tests:[["pick_model('cpu', 100, False)","'process'"],
         ["pick_model('io', 100, True)","'thread'"],
         ["pick_model('io', 100, False)","'async'"],
         ["pick_model('cpu', 2, False)","'serial'"]],
  edge:[["pick_model('io', 3, True)","'serial'"],
        ["pick_model('io', 4, True)","'thread'"]],
  ex:"🎯 파이썬의 동시성 선택은 <b>GIL 때문에</b> 갈립니다. CPU 작업은 스레드를 늘려도 GIL 하나를 서로 뺏느라 빨라지지 않습니다 — <b>프로세스</b>로 나눠야 코어를 실제로 씁니다.\n💡 I/O 작업은 반대입니다. 기다리는 동안 GIL 을 놓기 때문에 스레드로도 잘 겹칩니다. <code>asyncio</code> 는 더 가볍지만 <b>라이브러리가 async 를 지원해야</b> 합니다 — 블로킹 드라이버를 async 코드에서 부르면 이벤트 루프 전체가 멈춥니다.\n⚠️ 작업이 몇 개뿐이면 <b>병렬화 비용이 이득보다 큽니다</b>. 프로세스 생성·직렬화·통신에 드는 시간이 작업 자체보다 오래 걸리는 구간이 반드시 있습니다 — 측정 없이 병렬화부터 하는 것이 흔한 실수입니다.\n🔧 파이썬 3.13 의 free-threaded 빌드가 GIL 을 선택적으로 없애면서 이 지형이 바뀌는 중입니다. 다만 확산까지는 시간이 걸리므로, 당분간은 '<b>CPU 는 프로세스, I/O 는 스레드나 async</b>' 가 실무 기준입니다." },

{ k:"프로파일 결과 해석", fn:"hotspots",
  q:"프로파일 결과에서 <b>최적화 대상</b>을 고르는 <code>hotspots(rows, ratio)</code> 를 구현하세요. <code>rows</code> 는 <code>(이름, 누적시간)</code> 목록이고, <b>전체 시간에서 차지하는 비중이 <code>ratio</code> 이상</b>인 함수 이름을 <b>시간 내림차순</b>(동률이면 이름 오름차순)으로 돌려줍니다. 합이 0이면 빈 리스트입니다.",
  src:"def hotspots(rows, ratio):\n    # TODO: 비중 계산 후 정렬\n    return []",
  sol:"def hotspots(rows, ratio):\n    total = sum(t for _, t in rows)\n    if total <= 0:\n        return []\n    picked = [(name, t) for name, t in rows if t / total >= ratio]\n    picked.sort(key=lambda p: (-p[1], p[0]))\n    return [name for name, _ in picked]",
  tests:[["hotspots([('a', 70), ('b', 20), ('c', 10)], 0.2)","['a', 'b']"],
         ["hotspots([('a', 50), ('b', 50)], 0.5)","['a', 'b']"],
         ["hotspots([('z', 10), ('a', 10)], 0.5)","['a', 'z']"],
         ["hotspots([('a', 100)], 0.99)","['a']"]],
  edge:[["hotspots([], 0.1)","[]"],
        ["hotspots([('a', 0), ('b', 0)], 0.1)","[]"]],
  ex:"🎯 최적화의 첫 규칙은 '<b>측정하지 않은 것을 고치지 않는다</b>' 입니다. 사람의 직감은 병목을 자주 틀리고, 프로파일러는 <b>어디에 시간이 실제로 갔는지</b>만 말합니다.\n💡 <b>비중</b>으로 보는 것이 중요합니다 — 절대 시간 1초가 큰지 작은지는 전체가 2초냐 200초냐에 달렸습니다. 전체의 5% 를 절반으로 줄여 봐야 2.5% 개선이고, 이것이 암달의 법칙이 말하는 상한입니다.\n⚠️ <b>누적 시간(cumulative)과 자체 시간(tottime)은 다릅니다</b>. 누적은 하위 호출까지 포함하므로 <code>main</code> 이 항상 1위입니다 — 최적화 대상은 대개 자체 시간이 큰 함수이고, 둘을 헷갈리면 엉뚱한 곳을 팝니다.\n🔧 동률에 이름 순 정렬을 넣은 것은 <b>출력이 결정적이어야</b> 하기 때문입니다. 프로파일 결과를 CI 에서 비교한다면 순서가 흔들리는 것만으로 실패가 납니다." },

{ k:"의존성 위상 정렬", fn:"resolve_order",
  q:"모듈 <b>초기화 순서</b>를 구하는 <code>resolve_order(deps)</code> 를 구현하세요. <code>{이름: [의존]}</code> 을 받아 의존이 먼저 오는 순서를 돌려주되, 여러 개가 가능하면 <b>이름 오름차순</b>으로 고릅니다. <b>순환이면 <code>None</code></b> 입니다.",
  src:"def resolve_order(deps):\n    # TODO: 의존이 모두 해소된 것 중 이름 순으로\n    return list(deps)",
  sol:"def resolve_order(deps):\n    done = []\n    names = sorted(deps)\n    while len(done) < len(names):\n        ready = [n for n in names\n                 if n not in done and all(d in done for d in deps[n])]\n        if not ready:\n            return None\n        done.append(ready[0])\n    return done",
  tests:[["resolve_order({'app': ['db'], 'db': []})","['db', 'app']"],
         ["resolve_order({'b': ['a'], 'c': ['a'], 'a': []})","['a', 'b', 'c']"],
         ["resolve_order({'x': ['y'], 'y': ['x']})","None"],
         ["resolve_order({'solo': []})","['solo']"]],
  edge:[["resolve_order({})","[]"],
        ["resolve_order({'a': ['a']})","None"]],
  ex:"🎯 초기화 순서를 손으로 관리하면 모듈이 늘 때마다 깨집니다. <b>의존 관계만 선언</b>하고 순서는 계산하게 하는 것이 위상 정렬이고, 이것이 dbt·make·Airflow·패키지 매니저가 공통으로 하는 일입니다.\n💡 규칙은 하나입니다 — '<b>의존이 전부 끝난 것만 실행할 수 있다</b>'. 그런 것이 하나도 없는데 남아 있으면 그것이 <b>순환의 증거</b>이고, 순서를 만들 방법이 없으므로 실패시켜야 합니다.\n⚠️ 이름 순으로 고르는 것은 <b>출력을 결정적으로</b> 만들기 위해서입니다. 같은 입력에 매번 다른 순서가 나오면 재현 불가능한 버그가 생기고, 테스트도 가끔 실패하게 됩니다.\n🔧 자기 자신을 의존하는 경우(<code>{'a': ['a']}</code>)도 순환입니다 — 흔히 놓치는 경계이고, 설정 파일에서 오타로 실제로 생깁니다. 순환이 발견되면 공통 부분을 <b>아래 계층으로 내리는</b> 것이 정석 해법입니다." },

{ k:"슬라이딩 윈도우 최댓값", fn:"window_max",
  q:"크기 <code>k</code> 인 <b>슬라이딩 윈도우</b>의 최댓값 목록을 구하는 <code>window_max(xs, k)</code> 를 구현하세요. 매 창마다 다시 훑지 말고 <b>덱(deque)</b> 으로 <b>O(n)</b> 에 처리하세요. <code>k</code> 가 0 이하이거나 길이보다 크면 빈 리스트입니다.",
  src:"def window_max(xs, k):\n    # TODO: 덱으로 후보만 남기며 한 번에 훑기\n    return []",
  sol:"from collections import deque\n\n\ndef window_max(xs, k):\n    if k <= 0 or k > len(xs):\n        return []\n    out = []\n    idx = deque()\n    for i, v in enumerate(xs):\n        while idx and xs[idx[-1]] <= v:\n            idx.pop()\n        idx.append(i)\n        if idx[0] <= i - k:\n            idx.popleft()\n        if i >= k - 1:\n            out.append(xs[idx[0]])\n    return out",
  tests:[["window_max([1, 3, -1, -3, 5, 3, 6, 7], 3)","[3, 3, 5, 5, 6, 7]"],
         ["window_max([1, 2, 3], 1)","[1, 2, 3]"],
         ["window_max([9, 8, 7], 2)","[9, 8]"],
         ["window_max([1, 2, 3], 3)","[3]"]],
  edge:[["window_max([1, 2], 0)","[]"],
        ["window_max([1, 2], 5)","[]"]],
  ex:"🎯 창마다 <code>max()</code> 를 다시 부르면 <b>O(n·k)</b> 입니다 — 창이 커질수록 느려집니다. 덱을 쓰면 각 원소가 한 번 들어가고 한 번 나오므로 전체가 <b>O(n)</b> 입니다.\n💡 덱에는 '<b>앞으로 최댓값이 될 가능성이 있는 후보</b>' 만 남깁니다. 새 값보다 작은 것들은 그 값이 창에 있는 한 절대 최댓값이 될 수 없으므로 <b>뒤에서 버립니다</b> — 그래서 덱은 항상 내림차순이고 맨 앞이 현재 최댓값입니다.\n⚠️ 값이 아니라 <b>인덱스를 담는</b> 것이 요령입니다. 창을 벗어났는지 판단하려면 위치가 필요하기 때문입니다 — 값만 담으면 같은 값이 여러 개일 때 어느 것이 나갔는지 알 수 없습니다.\n🔧 이 구조를 '단조 덱(monotonic deque)' 이라 부르고, 주가의 이동 최고가·센서 스파이크 감지·스트리밍 통계에 그대로 쓰입니다. 파이썬의 <code>collections.deque</code> 는 양끝 삽입·삭제가 O(1) 이라 이 용도에 맞습니다." },
];
