/* 시스템 설계·네트워크 실행형 — '설계 문서로만 배운 것' 을 직접 계산해 본다.
   전부 결정적(시각·난수 없음), 순수 JS라 오프라인에서 돈다.
   쉬운 것부터 어려운 것 순으로 놓았다(계단식).
   주의: 앱 하네스가 쓰는 이름(SRC·TS·eq·gate·impl·P·row·parts·qp 등)과 겹치지 않게 짓는다. */
module.exports = [
/* ───────── sysd — 설계의 뒤에 있는 계산 ───────── */
{ track:"sysd", k:"용량 산정", cat:"design",
  q:"서비스 용량을 <b>산정</b>하세요. <code>capacity(dau, perUser, peakX, bytes)</code> 는 일 사용자 수·1인당 요청 수·피크 배수·요청당 저장 바이트를 받아 <code>{qps, peakQps, dailyGB}</code> 를 돌려줍니다. 평균 QPS 는 하루 요청을 <b>86400 으로</b> 나누고, 셋 다 <b>소수 둘째 자리에서 반올림</b>합니다. GB 는 1e9 바이트 기준입니다.",
  src:"function capacity(dau, perUser, peakX, bytes) {\n  // TODO: 하루 요청 → 평균 QPS → 피크 QPS → 일 저장량\n  return { qps: 0, peakQps: 0, dailyGB: 0 };\n}",
  sol:"function capacity(dau, perUser, peakX, bytes) {\n  const rd = (x) => Math.round(x * 100) / 100;\n  const daily = dau * perUser;\n  const qps = daily / 86400;\n  return { qps: rd(qps), peakQps: rd(qps * peakX), dailyGB: rd(daily * bytes / 1e9) };\n}",
  tests:[["capacity(86400, 1, 1, 1000)","{qps:1,peakQps:1,dailyGB:0.09}"],
         ["capacity(1000000, 10, 3, 500).qps","115.74"],
         ["capacity(1000000, 10, 3, 500).peakQps","347.22"],
         ["capacity(1000000, 10, 3, 500).dailyGB","5"]],
  edge:[["capacity(0, 10, 3, 500)","{qps:0,peakQps:0,dailyGB:0}"],
        ["capacity(86400, 2, 5, 0).peakQps","10"]],
  ex:"🎯 용량 산정은 <b>나눗셈 두 번</b>이 전부입니다 — 하루 요청을 86,400초로 나눠 평균 QPS 를 얻고, 피크 배수를 곱합니다. 어려운 건 계산이 아니라 <b>어떤 수를 넣을지 정하는 것</b>입니다.\n💡 피크 배수가 핵심입니다. 평균 QPS 로 서버를 잡으면 <b>점심시간에 무너집니다</b> — 소비자 서비스는 보통 2~5배, 이벤트성 서비스는 10배 이상 튑니다. '평균으로 설계하고 피크에 죽는' 것이 용량 산정 실패의 전형입니다.\n⚠️ 저장량은 <b>누적</b>이라는 점이 QPS 와 다릅니다. 일 5GB 면 1년에 1.8TB 이고, 여기에 복제본 3벌과 인덱스·백업이 곱해집니다 — 원본 크기만 보고 디스크를 잡으면 몇 달 뒤 급하게 늘리게 됩니다.\n🔧 면접에서도 실무에서도 <b>단위를 소리 내어 말하는</b> 것이 실수를 줄입니다 — '초당 요청', '일 바이트', '월 달러'. 숫자를 외우기보다 86,400초·1e9 바이트 같은 기준점 몇 개만 들고 있으면 됩니다." },

{ track:"sysd", k:"쿼럼 판정", cat:"design",
  q:"복제본 <code>n</code> 대에서 <b>쿼럼</b>을 판정하세요. <code>quorum(n, r, w)</code> 는 <code>{strong, canRead, canWrite}</code> 를 돌려줍니다 — <b>strong</b> 은 <code>r + w &gt; n</code>(읽기가 최신 쓰기를 반드시 본다), <b>canRead·canWrite</b> 는 <b>한 대가 죽어도</b> 각각 정족수를 채울 수 있는지(<code>n - 1 &gt;= r</code>, <code>n - 1 &gt;= w</code>)입니다.",
  src:"function quorum(n, r, w) {\n  // TODO: 강한 일관성 조건 · 1대 장애 내성\n  return { strong: false, canRead: false, canWrite: false };\n}",
  sol:"function quorum(n, r, w) {\n  return {\n    strong: r + w > n,\n    canRead: n - 1 >= r,\n    canWrite: n - 1 >= w,\n  };\n}",
  tests:[["quorum(3, 2, 2)","{strong:true,canRead:true,canWrite:true}"],
         ["quorum(3, 1, 1)","{strong:false,canRead:true,canWrite:true}"],
         ["quorum(3, 1, 3)","{strong:true,canRead:true,canWrite:false}"],
         ["quorum(5, 3, 3).strong","true"]],
  edge:[["quorum(3, 3, 1)","{strong:true,canRead:false,canWrite:true}"],
        ["quorum(1, 1, 1)","{strong:true,canRead:false,canWrite:false}"]],
  ex:"🎯 <code>R + W &gt; N</code> 은 '읽는 집합과 쓰는 집합이 <b>반드시 겹친다</b>' 는 뜻입니다. 겹치는 노드가 최신 값을 갖고 있으므로 읽기가 그것을 봅니다 — 이 부등식 하나가 강한 일관성의 전부입니다.\n💡 그래서 조합이 곧 트레이드오프입니다. <code>N=3, W=3, R=1</code> 은 읽기가 빠르지만 <b>한 대만 죽어도 쓰기가 멈춥니다</b>. <code>W=2, R=2</code> 는 양쪽 다 한 대 장애를 견디면서 일관성도 지켜, 실무의 기본값이 됐습니다.\n⚠️ <code>R=W=1</code> 은 가장 빠르지만 방금 쓴 값을 못 읽을 수 있습니다 — '최종적으로는' 맞습니다. 장바구니처럼 충돌을 나중에 합칠 수 있는 데이터에는 합리적이고, 잔액에는 아닙니다.\n🔧 N 은 보통 홀수로 잡습니다 — 짝수는 정족수를 채우는 데 필요한 대수가 늘 뿐 장애 내성이 더 좋아지지 않습니다(N=4 도 N=3 도 견디는 장애는 1대)." },

{ track:"sysd", k:"슬라이딩 윈도우 카운터", cat:"internals",
  q:"<b>슬라이딩 윈도우</b> 레이트 리밋을 구현하세요. <code>makeWindow(limit, windowMs)</code> 는 <code>allow(now)</code> 를 돌려줍니다. <b>윈도우 안의 요청 수</b>가 <code>limit</code> 미만일 때만 허용하고 그 시각을 기록합니다. 윈도우를 벗어난 기록은 버립니다(경계는 <b>포함</b>: <code>now - t &lt; windowMs</code> 인 것만 유효).",
  src:"function makeWindow(limit, windowMs) {\n  const hits = [];\n  return { allow(now) {\n    // TODO: 오래된 기록을 버리고 개수로 판정\n    hits.push(now);\n    return true;\n  } };\n}",
  sol:"function makeWindow(limit, windowMs) {\n  let hits = [];\n  return { allow(now) {\n    hits = hits.filter((t) => now - t < windowMs);\n    if (hits.length >= limit) return false;\n    hits.push(now);\n    return true;\n  } };\n}",
  tests:[["(() => { const wd=makeWindow(2,1000); return [wd.allow(0), wd.allow(100), wd.allow(200)]; })()","[true,true,false]"],
         ["(() => { const wd=makeWindow(2,1000); wd.allow(0); wd.allow(100); return wd.allow(1000); })()","true"],
         ["(() => { const wd=makeWindow(1,1000); wd.allow(0); return [wd.allow(999), wd.allow(1000)]; })()","[false,true]"],
         ["(() => { const wd=makeWindow(3,100); return [wd.allow(0), wd.allow(50), wd.allow(99), wd.allow(99)]; })()","[true,true,true,false]"]],
  edge:[["(() => { const wd=makeWindow(0,1000); return wd.allow(0); })()","false"],
        ["(() => { const wd=makeWindow(2,1000); wd.allow(0); wd.allow(1); return wd.allow(5000); })()","true"]],
  ex:"🎯 고정 윈도우(매 분 0초에 리셋)는 <b>경계에서 두 배가 통과</b>합니다 — 59초에 한도만큼, 61초에 또 한도만큼. 슬라이딩 윈도우는 '지금부터 과거 N밀리초' 를 보므로 그 구멍이 없습니다.\n💡 대가는 <b>메모리</b>입니다. 요청 시각을 전부 들고 있어야 하므로 한도가 크면 기록도 큽니다 — 그래서 실무에서는 근사법(고정 윈도우 두 개를 가중 평균하는 sliding window log 대신 counter)을 자주 씁니다.\n⚠️ 경계 조건이 계약입니다. <code>now - t &lt; windowMs</code> 와 <code>&lt;=</code> 는 정확히 1ms 차이에서 갈리고, 테스트가 그 지점(999 vs 1000)을 찌릅니다 — 문서에 적히지 않으면 구현마다 달라지는 부분입니다.\n🔧 분산 환경에서는 이 배열이 <b>서버마다 따로</b>라 실제 한도가 서버 수만큼 곱해집니다. 전역 한도가 필요하면 Redis 같은 공유 저장소로 올려야 하고, 그 순간 지연과 가용성이 새 문제로 들어옵니다." },

{ track:"sysd", k:"벡터 클록", cat:"internals",
  q:"<b>벡터 클록</b>으로 두 버전의 관계를 판정하세요. <code>compare(a, b)</code> 는 <code>{node: count}</code> 두 개를 받아 <code>'before'</code>·<code>'after'</code>·<code>'concurrent'</code>·<code>'equal'</code> 중 하나를 돌려줍니다. 없는 노드는 0으로 봅니다. a 의 모든 항목이 b <b>이하이고 하나라도 작으면</b> before 입니다.",
  src:"function compare(a, b) {\n  // TODO: 모든 노드를 비교해 관계를 판정\n  return 'equal';\n}",
  sol:"function compare(a, b) {\n  const keys = new Set(Object.keys(a).concat(Object.keys(b)));\n  let less = false, more = false;\n  keys.forEach((k) => {\n    const x = a[k] || 0, y = b[k] || 0;\n    if (x < y) less = true;\n    if (x > y) more = true;\n  });\n  if (less && more) return 'concurrent';\n  if (less) return 'before';\n  if (more) return 'after';\n  return 'equal';\n}",
  tests:[["compare({a:1}, {a:2})","'before'"],
         ["compare({a:2,b:1}, {a:1,b:1})","'after'"],
         ["compare({a:1,b:0}, {a:0,b:1})","'concurrent'"],
         ["compare({a:1,b:2}, {a:1,b:2})","'equal'"]],
  edge:[["compare({}, {})","'equal'"],
        ["compare({a:1}, {b:1})","'concurrent'"]],
  ex:"🎯 벽시계로는 분산 이벤트의 순서를 정할 수 없습니다 — 서버마다 시계가 어긋나고, 되감기기도 합니다. 벡터 클록은 시간 대신 '<b>누가 무엇을 보았는가</b>' 로 순서를 만듭니다.\n💡 핵심은 <b>concurrent 라는 세 번째 답</b>입니다. 두 버전이 서로를 모르고 갈라졌다는 뜻이고, 시스템이 자동으로 고를 수 없다는 신호입니다 — 마지막 쓰기 승리(LWW)로 뭉개면 그중 하나가 조용히 사라집니다.\n⚠️ 그래서 Dynamo 계열은 충돌을 <b>애플리케이션에 넘깁니다</b>. 장바구니는 합집합으로 합치고(그래서 지운 물건이 되살아나는 현상이 생깁니다), 문서는 사용자에게 물어봅니다 — '무엇이 옳은가' 는 도메인만 압니다.\n🔧 노드가 늘수록 벡터가 커지는 것이 실용적 약점이라, 실무에서는 항목 수를 제한하거나 버전 벡터·도트 버전 벡터 같은 변형을 씁니다." },

{ track:"sysd", k:"팬아웃 비용 비교", cat:"design",
  q:"타임라인 전략의 <b>쓰기·읽기 비용</b>을 비교하세요. <code>fanout(followers, posts, reads)</code> 는 <code>{onWrite, onRead}</code> 를 돌려줍니다 — <b>쓰기 시 팬아웃</b>은 글마다 팔로워 수만큼 쓰고 읽기는 1회, <b>읽기 시 팬아웃</b>은 쓰기 1회에 읽을 때마다 팔로우 수만큼 읽습니다. 각각 <b>총 연산 수</b>입니다.",
  src:"function fanout(followers, posts, reads) {\n  // TODO: 두 전략의 총 연산 수\n  return { onWrite: 0, onRead: 0 };\n}",
  sol:"function fanout(followers, posts, reads) {\n  return {\n    onWrite: posts * followers + reads,\n    onRead: posts + reads * followers,\n  };\n}",
  tests:[["fanout(100, 1, 1)","{onWrite:101,onRead:101}"],
         ["fanout(1000000, 1, 10)","{onWrite:1000010,onRead:10000001}"],
         ["fanout(10, 100, 1000)","{onWrite:2000,onRead:10100}"],
         ["fanout(0, 5, 5)","{onWrite:5,onRead:5}"]],
  edge:[["fanout(100, 0, 0)","{onWrite:0,onRead:0}"],
        ["fanout(1, 1, 1)","{onWrite:2,onRead:2}"]],
  ex:"🎯 같은 기능을 <b>쓰기에서 미리 퍼뜨릴지, 읽을 때 모을지</b> 의 선택입니다. 답은 '어느 쪽이 더 자주 일어나는가' 에 달려 있고, 이 함수는 그 비교를 숫자로 만듭니다.\n💡 보통 <b>읽기가 훨씬 많으므로</b> 쓰기 시 팬아웃(미리 각자의 타임라인에 넣어 두기)이 기본입니다. 읽기는 자기 목록 한 번만 보면 끝나니까요.\n⚠️ 그런데 팔로워 100만 명인 계정이 글을 올리면 <b>쓰기 한 번이 100만 번의 쓰기</b>가 됩니다 — 이 순간 팬아웃이 무너집니다. 그래서 트위터·인스타그램은 <b>혼합</b>을 씁니다: 보통 계정은 쓰기 팬아웃, 유명인은 읽기 팬아웃으로 두고 읽을 때 합칩니다.\n🔧 어느 쪽이든 '<b>읽기:쓰기 비율</b>' 을 먼저 측정해야 합니다. 이 비율 없이 아키텍처를 고르는 것은 동전 던지기이고, 서비스가 크면서 비율이 바뀌면 전략도 바뀌어야 합니다." },

{ track:"sysd", k:"샤드 리밸런싱 이동량", cat:"design",
  q:"샤드를 늘릴 때 <b>옮겨야 하는 키의 수</b>를 세세요. <code>moved(keys, from, to)</code> 는 키 배열이 <code>hash % from</code> 에서 <code>hash % to</code> 로 바뀔 때 <b>담당 샤드가 달라지는 키의 수</b>를 돌려줍니다. 키는 정수 해시값입니다.",
  src:"function moved(keys, from, to) {\n  // TODO: 담당 샤드가 바뀐 키를 센다\n  return 0;\n}",
  sol:"function moved(keys, from, to) {\n  return keys.filter((k) => k % from !== k % to).length;\n}",
  tests:[["moved([0,1,2,3,4,5,6,7,8,9,10,11], 3, 4)","9"],
         ["moved([0,1,2,3], 2, 2)","0"],
         ["moved([0,1,2,3,4,5,6,7], 4, 8)","4"],
         ["moved([0,1,2,3,4,5,6,7], 2, 4)","4"]],
  edge:[["moved([], 3, 4)","0"],
        ["moved([12], 3, 4)","0"]],
  ex:"🎯 <code>hash % N</code> 은 단순하지만 N 이 바뀌면 <b>거의 모든 키가 이사</b>합니다. 3→4 로 늘릴 때 12개 중 9개가 옮겨 갑니다 — 캐시라면 그 순간 적중률이 바닥을 치고, 원본이 그 부하를 그대로 받습니다.\n💡 예외가 <b>2배로 늘리는 경우</b>입니다(4→8, 2→4). 이때는 딱 절반만 옮기면 되므로 '샤드는 2의 거듭제곱으로' 라는 실무 관례가 생겼습니다 — 테스트가 그 대비를 보여 줍니다.\n⚠️ 그래서 애초에 <b>논리 샤드를 많이</b> 만들어 두고(예: 1,024개) 물리 노드에 나눠 붙이는 방식이 널리 쓰입니다. 노드를 늘릴 때 논리 샤드 단위로만 옮기면 되고 해시 함수는 그대로입니다.\n🔧 일관된 해싱(consistent hashing)은 같은 문제를 다른 방식으로 풉니다 — 링 위에서 빠진 구간의 키만 이동하므로 재배치량이 <code>1/N</code> 수준으로 줄어듭니다." },

{ track:"sysd", k:"분산 ID 생성", cat:"internals",
  q:"스노우플레이크 방식 <b>64비트 ID</b> 를 만드세요. <code>makeId(ms, node, seq)</code> 는 <b>타임스탬프 41비트 · 노드 10비트 · 시퀀스 12비트</b> 로 조립하고, <code>parseId(id)</code> 는 되돌립니다. 각 필드가 범위를 넘으면 <code>makeId</code> 는 <code>null</code> 입니다. 큰 수는 <code>BigInt</code> 로 다루고 ID 는 <b>문자열</b>로 돌려주세요.",
  src:"function makeId(ms, node, seq) {\n  // TODO: 41 + 10 + 12 비트로 조립\n  return null;\n}\n\nfunction parseId(id) {\n  // TODO: 되돌리기\n  return { ms: 0, node: 0, seq: 0 };\n}",
  sol:"function makeId(ms, node, seq) {\n  if (ms < 0 || ms >= 2 ** 41 || node < 0 || node >= 1024 || seq < 0 || seq >= 4096) return null;\n  const v = (BigInt(ms) << 22n) | (BigInt(node) << 12n) | BigInt(seq);\n  return v.toString();\n}\n\nfunction parseId(id) {\n  const v = BigInt(id);\n  return {\n    ms: Number(v >> 22n),\n    node: Number((v >> 12n) & 1023n),\n    seq: Number(v & 4095n),\n  };\n}",
  tests:[["makeId(0, 0, 1)","'1'"],
         ["parseId(makeId(1700000000000, 7, 42))","{ms:1700000000000,node:7,seq:42}"],
         ["makeId(1, 0, 0)","'4194304'"],
         ["makeId(0, 1024, 0)","null"]],
  edge:[["makeId(0, 0, 4096)","null"],
        ["parseId(makeId(0, 1023, 4095))","{ms:0,node:1023,seq:4095}"]],
  ex:"🎯 분산 ID 의 요구는 셋입니다 — <b>겹치지 않고, 대략 시간순이고, 조율 없이 만들 수 있을 것</b>. 시각·노드·시퀀스를 비트로 나눠 담으면 셋이 동시에 충족됩니다.\n💡 <b>시각이 상위 비트</b>에 오는 것이 핵심입니다. 그래야 ID 를 정렬하면 대략 시간순이 되고, B-트리 인덱스에 순차 삽입되어 페이지 분할이 줄어듭니다 — UUIDv4 가 인덱스에 나쁜 이유의 반대입니다.\n⚠️ 자바스크립트의 <code>Number</code> 는 2⁵³ 까지만 정확해서 <b>64비트 ID 를 담지 못합니다</b>. BigInt 로 만들고 <b>문자열로 주고받는</b> 것이 정석입니다 — JSON 에 숫자로 넣으면 클라이언트에서 조용히 끝자리가 뭉개집니다.\n🔧 시계가 되감기면(NTP 보정) 같은 ID 가 두 번 나올 수 있어, 실전 구현은 마지막 발급 시각을 기억했다가 <b>되감김을 감지하면 기다리거나 거부</b>합니다. 노드 번호를 어떻게 배정할지도 운영 문제로 남습니다." },

{ track:"sysd", k:"장애 감지 — 하트비트", cat:"internals",
  q:"하트비트로 <b>노드 생사</b>를 판정하세요. <code>makeDetector(timeout, k)</code> 는 <code>{beat(node, now), dead(now)}</code> 를 돌려줍니다. <code>beat</code> 는 마지막 신호 시각을 갱신하고, <code>dead</code> 는 <b><code>now - 마지막신호 &gt; timeout</code></b> 인 노드 이름을 <b>이름 오름차순</b>으로 돌려줍니다. 단, <b><code>k</code> 대 이상이 동시에 죽은 것으로 보이면</b> 네트워크 문제로 간주해 <b>빈 배열</b>을 돌려줍니다.",
  src:"function makeDetector(timeout, k) {\n  const last = {};\n  return {\n    beat(node, now) { last[node] = now; },\n    dead(now) {\n      // TODO: 타임아웃 판정 + 대량 실패는 네트워크 문제로 간주\n      return Object.keys(last);\n    },\n  };\n}",
  sol:"function makeDetector(timeout, k) {\n  const last = {};\n  return {\n    beat(node, now) { last[node] = now; },\n    dead(now) {\n      const out = Object.keys(last).filter((nd) => now - last[nd] > timeout).sort();\n      return out.length >= k ? [] : out;\n    },\n  };\n}",
  tests:[["(() => { const dt=makeDetector(100,3); dt.beat('a',0); dt.beat('b',0); return dt.dead(50); })()","[]"],
         ["(() => { const dt=makeDetector(100,3); dt.beat('a',0); dt.beat('b',200); return dt.dead(200); })()","['a']"],
         ["(() => { const dt=makeDetector(100,3); dt.beat('b',0); dt.beat('a',0); dt.beat('c',300); return dt.dead(300); })()","['a','b']"],
         ["(() => { const dt=makeDetector(100,3); ['a','b','c'].forEach(x=>dt.beat(x,0)); return dt.dead(300); })()","[]"]],
  edge:[["(() => { const dt=makeDetector(100,3); dt.beat('a',0); return dt.dead(100); })()","[]"],
        ["(() => { const dt=makeDetector(100,2); dt.beat('a',0); dt.beat('b',0); return dt.dead(300); })()","[]"]],
  ex:"🎯 하트비트 판정은 <b>타임아웃 하나</b>로 끝나 보이지만, 그 순간 '노드가 죽었나, 네트워크가 끊겼나' 를 구분할 수 없다는 근본 문제가 남습니다.\n💡 <b>동시에 여러 대가 죽어 보이면</b> 대개 죽은 건 그들이 아니라 <b>나와 그들 사이의 네트워크</b>입니다. 그때 전부 장애로 처리하면 멀쩡한 노드를 클러스터에서 쫓아내고 데이터를 재배치해 상황을 악화시킵니다 — 임계치 <code>k</code> 가 그 폭주를 막습니다.\n⚠️ 경계도 계약입니다 — <code>&gt;</code> 라서 정확히 timeout 인 순간은 아직 살아 있습니다. 이런 한 끗이 '왜 어떤 노드는 빠지고 어떤 노드는 안 빠지냐' 는 운영 질문으로 돌아옵니다.\n🔧 실전은 고정 타임아웃 대신 <b>phi accrual</b> 같은 적응형 판정을 씁니다 — 최근 하트비트 간격의 분포를 보고 '지금 안 오는 것이 얼마나 이상한지' 를 확률로 냅니다. 네트워크가 느려지면 문턱도 함께 느슨해집니다." },

{ track:"sysd", k:"리더 선출 — 과반수 득표", cat:"internals",
  q:"<b>리더 선출</b> 결과를 판정하세요. <code>elect(total, votes)</code> 는 전체 노드 수와 <code>{후보: 득표}</code> 를 받아 <b>과반수</b>(<code>&gt; total/2</code>)를 얻은 후보 이름을, 없으면 <code>null</code> 을 돌려줍니다. 득표 합이 <code>total</code> 을 넘으면 <b>잘못된 투표</b>이므로 <code>null</code> 입니다.",
  src:"function elect(total, votes) {\n  // TODO: 합계 검증 후 과반수 판정\n  return null;\n}",
  sol:"function elect(total, votes) {\n  const names = Object.keys(votes);\n  const sum = names.reduce((s, nm) => s + votes[nm], 0);\n  if (sum > total) return null;\n  const win = names.find((nm) => votes[nm] > total / 2);\n  return win === undefined ? null : win;\n}",
  tests:[["elect(5, {a:3, b:2})","'a'"],
         ["elect(5, {a:2, b:2})","null"],
         ["elect(4, {a:2, b:2})","null"],
         ["elect(4, {a:3, b:1})","'a'"]],
  edge:[["elect(3, {a:2, b:2})","null"],
        ["elect(1, {a:1})","'a'"]],
  ex:"🎯 과반수는 '<b>절반 초과</b>' 입니다 — 4대에서 2표는 과반이 아닙니다. 이 한 끗이 중요한 이유는, 과반 집합 두 개는 <b>반드시 겹치기</b> 때문입니다. 겹치면 서로 다른 리더가 동시에 뽑힐 수 없습니다.\n💡 짝수 대수가 손해인 이유가 여기 있습니다. 4대는 3표가 필요하지만 3대도 2표면 되므로, <b>둘 다 1대 장애만 견딥니다</b> — 대수만 늘고 내성은 그대로입니다. 그래서 클러스터는 홀수로 잡습니다.\n⚠️ 득표 합이 전체를 넘으면 <b>이중 투표</b>가 있었다는 뜻이고, 그 상태의 결과는 믿을 수 없습니다. Raft 가 '한 임기에 한 표' 를 디스크에 기록하는 이유입니다 — 재시작 후 다시 투표하면 같은 임기에 두 표를 던지게 됩니다.\n🔧 스플릿 브레인(양쪽이 각자 리더라고 믿음)은 과반수 규칙으로 막습니다. 네트워크가 갈라져도 <b>과반을 가진 쪽만</b> 일을 계속하고, 소수 쪽은 스스로 멈춥니다 — 가용성을 일관성과 바꾸는 결정입니다." },

{ track:"sysd", k:"읽기 복제본 라우팅", cat:"design",
  q:"읽기를 <b>복제본에 배분</b>하세요. <code>route(replicas, maxLagMs, needFresh)</code> 는 <code>{name, lagMs, load}</code> 목록에서 하나를 고릅니다 — <code>needFresh</code> 면 <b>리더</b>(<code>lagMs === 0</code>)를, 아니면 <b>지연이 <code>maxLagMs</code> 이하인 것 중 부하가 가장 낮은 것</b>을 고릅니다. 동률이면 앞선 것, 없으면 <b>리더로 되돌아갑니다</b>(그것도 없으면 <code>null</code>).",
  src:"function route(replicas, maxLagMs, needFresh) {\n  // TODO: 신선도 요구 → 지연 필터 → 최소 부하\n  return replicas[0] ? replicas[0].name : null;\n}",
  sol:"function route(replicas, maxLagMs, needFresh) {\n  const leader = replicas.find((rp) => rp.lagMs === 0);\n  if (needFresh) return leader ? leader.name : null;\n  let best = null;\n  replicas.forEach((rp) => {\n    if (rp.lagMs > maxLagMs) return;\n    if (!best || rp.load < best.load) best = rp;\n  });\n  if (best) return best.name;\n  return leader ? leader.name : null;\n}",
  tests:[["route([{name:'L',lagMs:0,load:90},{name:'R1',lagMs:50,load:10}], 100, false)","'R1'"],
         ["route([{name:'L',lagMs:0,load:90},{name:'R1',lagMs:50,load:10}], 100, true)","'L'"],
         ["route([{name:'L',lagMs:0,load:90},{name:'R1',lagMs:5000,load:1}], 100, false)","'L'"],
         ["route([{name:'L',lagMs:0,load:5},{name:'R1',lagMs:10,load:9}], 100, false)","'L'"]],
  edge:[["route([], 100, false)","null"],
        ["route([{name:'R1',lagMs:20,load:1}], 100, true)","null"]],
  ex:"🎯 읽기 분산의 이득은 크지만 공짜가 아닙니다 — 복제본은 <b>지연만큼 과거</b>를 보여 줍니다. 그래서 라우팅은 '이 읽기가 최신이어야 하는가' 라는 질문에서 시작합니다.\n💡 '방금 쓴 뒤의 읽기' 는 대개 최신이어야 합니다(read-your-writes). 그 요청만 리더로 보내고 나머지는 복제본으로 보내면, <b>정합성을 지키면서도 리더 부하를 대부분 덜어냅니다</b>.\n⚠️ 지연이 임계치를 넘은 복제본은 <b>빼야</b> 합니다. 안 빼면 사용자마다 다른 과거를 보게 되어 '어떤 사람은 보이고 어떤 사람은 안 보인다' 는 재현 불가 버그가 됩니다. 뺐더니 남는 게 없으면 리더로 되돌아가는 것이 안전한 기본값입니다.\n🔧 부하 기준은 커넥션 수·큐 길이·응답 시간 중 무엇이든 될 수 있지만, <b>측정 주기가 길면 이미 지난 정보</b>로 배분하게 됩니다 — 그래서 실전 LB 는 '최근 요청 수' 처럼 즉시 갱신되는 지표를 씁니다." },

{ track:"sysd", k:"멱등키 저장소", cat:"internals",
  q:"<b>멱등 요청</b> 처리기를 만드세요. <code>makeStore(ttl)</code> 는 <code>{run(key, now, fn)}</code> 을 돌려줍니다. 같은 키가 <b>TTL 안</b>에 다시 오면 <code>fn</code> 을 부르지 않고 <b>기억한 결과</b>를 돌려주고, TTL 이 지났으면 다시 실행합니다. 반환은 <code>{value, cached}</code> 입니다.",
  src:"function makeStore(ttl) {\n  const seen = {};\n  return { run(key, now, fn) {\n    // TODO: TTL 안이면 기억한 결과, 아니면 실행\n    return { value: fn(), cached: false };\n  } };\n}",
  sol:"function makeStore(ttl) {\n  const seen = {};\n  return { run(key, now, fn) {\n    const hit = seen[key];\n    if (hit && now - hit.at < ttl) return { value: hit.value, cached: true };\n    const value = fn();\n    seen[key] = { value, at: now };\n    return { value, cached: false };\n  } };\n}",
  tests:[["(() => { const st=makeStore(100); let n=0; st.run('k',0,()=>++n); return st.run('k',50,()=>++n); })()","{value:1,cached:true}"],
         ["(() => { const st=makeStore(100); let n=0; st.run('k',0,()=>++n); return st.run('k',200,()=>++n); })()","{value:2,cached:false}"],
         ["(() => { const st=makeStore(100); let n=0; st.run('a',0,()=>++n); return st.run('b',0,()=>++n); })()","{value:2,cached:false}"],
         ["(() => { const st=makeStore(100); let n=0; st.run('k',0,()=>++n); st.run('k',10,()=>++n); st.run('k',20,()=>++n); return n; })()","1"]],
  edge:[["(() => { const st=makeStore(100); let n=0; st.run('k',0,()=>++n); return st.run('k',100,()=>++n).cached; })()","false"],
        ["(() => { const st=makeStore(100); return st.run('k',0,()=>null); })()","{value:null,cached:false}"]],
  ex:"🎯 멱등키는 '<b>같은 요청이 두 번 와도 효과는 한 번</b>' 을 만드는 장치입니다. 결제 요청에서 응답이 유실되면 클라이언트는 재시도할 수밖에 없는데, 그때 이중 결제를 막는 것이 이것입니다.\n💡 결과를 <b>기억해 두는 것</b>이 절반입니다. 두 번째 요청에 '이미 처리됨' 이라고만 답하면 클라이언트는 결과(주문 번호)를 받을 방법이 없습니다 — 처음 응답을 그대로 돌려줘야 재시도가 진짜로 안전해집니다.\n⚠️ TTL 은 '재시도가 일어날 만한 시간' 보다 넉넉해야 합니다. 너무 짧으면 늦은 재시도가 새 요청으로 처리되고, 너무 길면 저장소가 계속 자랍니다 — 보통 24시간 정도를 씁니다.\n🔧 실전에서는 이 저장소가 메모리가 아니라 <b>DB 의 유니크 제약</b>입니다. 키 삽입과 실제 처리를 <b>한 트랜잭션</b>에 묶어야 '키만 기록되고 처리는 안 된' 구멍이 생기지 않습니다. 진행 중 상태(processing)를 따로 두어 동시 요청을 막는 것도 필요합니다." },

{ track:"sysd", k:"백프레셔와 부하 차단", cat:"design",
  q:"과부하에서 <b>무엇을 버릴지</b> 정하세요. <code>shed(queue, capacity)</code> 는 <code>{id, priority, deadlineMs}</code> 대기열에서 <b>처리할 것</b>의 id 배열을 돌려줍니다. <b>마감이 이미 지난 것</b>(<code>deadlineMs &lt;= 0</code>)은 먼저 버리고, 남은 것 중 <b>우선순위가 높은 순</b>(숫자가 클수록 높음, 동률이면 마감이 급한 순)으로 <code>capacity</code> 개만 남깁니다.",
  src:"function shed(queue, capacity) {\n  // TODO: 만료 제거 → 우선순위·마감 정렬 → capacity 만큼\n  return queue.slice(0, capacity).map((x) => x.id);\n}",
  sol:"function shed(queue, capacity) {\n  return queue\n    .filter((x) => x.deadlineMs > 0)\n    .sort((a, b) => b.priority - a.priority || a.deadlineMs - b.deadlineMs)\n    .slice(0, capacity)\n    .map((x) => x.id);\n}",
  tests:[["shed([{id:'a',priority:1,deadlineMs:100},{id:'b',priority:5,deadlineMs:100}], 1)","['b']"],
         ["shed([{id:'a',priority:1,deadlineMs:0},{id:'b',priority:1,deadlineMs:50}], 5)","['b']"],
         ["shed([{id:'a',priority:2,deadlineMs:900},{id:'b',priority:2,deadlineMs:50}], 1)","['b']"],
         ["shed([{id:'a',priority:1,deadlineMs:10},{id:'b',priority:3,deadlineMs:10},{id:'c',priority:2,deadlineMs:10}], 2)","['b','c']"]],
  edge:[["shed([], 3)","[]"],
        ["shed([{id:'a',priority:1,deadlineMs:-5}], 3)","[]"]],
  ex:"🎯 과부하에서 <b>전부 처리하려는 시도가 가장 나쁜 선택</b>입니다. 큐가 무한정 자라면 모든 요청의 지연이 함께 늘어 결국 아무도 제때 응답을 못 받습니다 — 일부를 <b>빨리 거절</b>하는 편이 전체 품질을 지킵니다.\n💡 가장 먼저 버릴 것은 <b>이미 마감이 지난 요청</b>입니다. 처리해 봐야 사용자는 떠났고, 그 자원은 아직 기다릴 가치가 있는 요청에서 뺏어 온 것입니다 — '죽은 요청에 일하지 않기' 가 부하 차단의 첫 규칙입니다.\n⚠️ 우선순위는 <b>미리 정해 둬야</b> 합니다. 장애 중에 '무엇이 중요한가' 를 논의할 시간은 없습니다. 보통 결제·인증 같은 핵심 흐름을 위에, 추천·통계 같은 부가 기능을 아래에 둡니다.\n🔧 거절할 때는 <b>빠르게, 명확한 신호로</b>(429 + Retry-After) 해야 합니다. 느린 거절은 자원을 쓰면서 사용자도 붙잡아 두는 최악의 조합이고, 신호가 없으면 클라이언트가 즉시 재시도해 상황을 더 나쁘게 만듭니다." },

/* ───────── net — 프로토콜을 직접 굴린다 ───────── */
{ track:"net", k:"CIDR 서브넷 계산", cat:"internals",
  q:"IPv4 <b>CIDR</b> 를 계산하세요. <code>subnet(cidr)</code> 는 <code>'192.168.1.10/24'</code> 를 받아 <code>{network, broadcast, hosts}</code> 를 돌려줍니다 — 네트워크·브로드캐스트 주소는 점 표기 문자열이고 <code>hosts</code> 는 <b>사용 가능한 호스트 수</b>(<code>2^(32-prefix) - 2</code>, /31 이하는 0)입니다.",
  src:"function subnet(cidr) {\n  // TODO: 마스크를 만들어 네트워크·브로드캐스트 계산\n  return { network: '', broadcast: '', hosts: 0 };\n}",
  sol:"function subnet(cidr) {\n  const [ip, pfxRaw] = cidr.split('/');\n  const pfx = Number(pfxRaw);\n  const toNum = (s) => s.split('.').reduce((a, b) => a * 256 + Number(b), 0);\n  const toStr = (v) => [v >>> 24, (v >>> 16) & 255, (v >>> 8) & 255, v & 255].join('.');\n  const mask = pfx === 0 ? 0 : (0xffffffff << (32 - pfx)) >>> 0;\n  const net = (toNum(ip) & mask) >>> 0;\n  const bcast = (net | (~mask >>> 0)) >>> 0;\n  const size = 2 ** (32 - pfx);\n  return { network: toStr(net), broadcast: toStr(bcast), hosts: size > 2 ? size - 2 : 0 };\n}",
  tests:[["subnet('192.168.1.10/24')","{network:'192.168.1.0',broadcast:'192.168.1.255',hosts:254}"],
         ["subnet('10.0.5.200/16').network","'10.0.0.0'"],
         ["subnet('172.16.3.7/20')","{network:'172.16.0.0',broadcast:'172.16.15.255',hosts:4094}"],
         ["subnet('192.168.1.130/25').network","'192.168.1.128'"]],
  edge:[["subnet('8.8.8.8/32')","{network:'8.8.8.8',broadcast:'8.8.8.8',hosts:0}"],
        ["subnet('1.2.3.4/31').hosts","0"]],
  ex:"🎯 CIDR 의 <code>/24</code> 는 '<b>앞 24비트가 네트워크</b>' 라는 뜻입니다. IP 와 마스크를 AND 하면 네트워크 주소가, 마스크를 뒤집어 OR 하면 브로드캐스트 주소가 나옵니다 — 비트 연산 두 번이 전부입니다.\n💡 <code>/25</code> 같은 어중간한 경계에서 실수가 납니다. 192.168.1.130 은 <code>/24</code> 면 192.168.1.0 대역이지만 <code>/25</code> 면 192.168.1.<b>128</b> 대역입니다 — 방화벽 규칙이 조용히 다른 대역을 열게 되는 지점입니다.\n⚠️ 자바스크립트의 비트 연산은 <b>부호 있는 32비트</b>라 최상위 비트가 켜지면 음수가 됩니다 — <code>&gt;&gt;&gt; 0</code> 로 부호를 털지 않으면 128.x 이상 주소에서 전부 틀립니다.\n🔧 <code>-2</code> 는 네트워크 주소와 브로드캐스트 주소를 뺀 것입니다. 다만 <code>/31</code> 은 점대점 링크용으로 2개를 모두 쓰는 예외가 있고(RFC 3021), 클라우드 VPC 는 서브넷마다 몇 개를 더 예약합니다 — 계산기의 숫자와 실제 배정 가능 수가 다른 이유입니다." },

{ track:"net", k:"인터넷 체크섬", cat:"internals",
  q:"<b>인터넷 체크섬</b>(RFC 1071)을 구현하세요. <code>checksum(words)</code> 는 16비트 워드 배열을 받아 <b>1의 보수 합</b>을 구하고(올림이 나면 <b>되돌려 더함</b>), 그 결과를 <b>비트 반전</b>해 돌려줍니다. <code>verify(words, sum)</code> 는 체크섬을 포함해 다시 계산했을 때 0이 되는지 봅니다.",
  src:"function checksum(words) {\n  // TODO: 1의 보수 합 → 올림 되돌리기 → 반전\n  return 0;\n}\n\nfunction verify(words, sum) {\n  // TODO\n  return false;\n}",
  sol:"function checksum(words) {\n  let acc = 0;\n  words.forEach((w) => {\n    acc += w;\n    if (acc > 0xffff) acc = (acc & 0xffff) + 1;\n  });\n  return (~acc) & 0xffff;\n}\n\nfunction verify(words, sum) {\n  return checksum(words.concat([sum])) === 0;\n}",
  tests:[["checksum([0x0001, 0x0002])","65532"],
         ["checksum([0xffff, 0x0001])","65534"],
         ["verify([0x0001, 0x0002], checksum([0x0001, 0x0002]))","true"],
         ["verify([0x1234, 0x5678], checksum([0x1234, 0x5678]))","true"]],
  edge:[["checksum([])","65535"],
        ["verify([0x0001], checksum([0x0002]))","false"]],
  ex:"🎯 인터넷 체크섬은 <b>덧셈과 반전</b>뿐입니다. 계산이 싸야 라우터가 패킷마다 할 수 있기 때문이고, 그 대가로 <b>오류 검출 능력이 약합니다</b> — 두 바이트가 서로 상쇄되게 바뀌면 못 잡습니다.\n💡 '올림을 되돌려 더한다'(end-around carry)가 1의 보수 산술의 특징입니다. 이 성질 덕분에 <b>워드 순서를 바꿔도 결과가 같고</b>, 그래서 라우터가 헤더 일부만 고칠 때 전체를 다시 계산하지 않고 <b>차분만 반영</b>할 수 있습니다(TTL 감소마다 전체 재계산은 너무 비쌉니다).\n⚠️ 검증이 '<b>0이 나오는가</b>' 인 것도 같은 성질에서 옵니다 — 원래 합과 그 반전을 더하면 전부 1이 되고, 그걸 다시 반전하면 0입니다. 구현이 맞는지 확인할 때 이 항등식이 가장 빠른 점검입니다.\n🔧 그래서 체크섬은 <b>실수로 인한 손상</b>을 잡을 뿐 <b>고의적 변조</b>는 못 막습니다 — 누구나 다시 계산할 수 있기 때문입니다. 무결성이 필요하면 HMAC 이나 TLS 가 필요하고, 강한 오류 검출이 필요하면 CRC 를 씁니다." },

{ track:"net", k:"라우팅 테이블 — 최장 접두사", cat:"internals",
  q:"<b>최장 접두사 매칭</b>으로 다음 홉을 고르세요. <code>lookup(table, ip)</code> 는 <code>{cidr, via}</code> 목록에서 <b>ip 를 포함하면서 prefix 가 가장 긴</b> 항목의 <code>via</code> 를 돌려줍니다. 동률이면 앞선 것, 맞는 게 없으면 <code>null</code> 입니다(<code>0.0.0.0/0</code> 은 항상 매칭됩니다).",
  src:"function lookup(table, ip) {\n  // TODO: 포함 여부 검사 후 가장 긴 접두사\n  return table[0] ? table[0].via : null;\n}",
  sol:"function lookup(table, ip) {\n  const toNum = (s) => s.split('.').reduce((a, b) => a * 256 + Number(b), 0);\n  const target = toNum(ip);\n  let best = null, bestPfx = -1;\n  table.forEach((rt) => {\n    const [net, pfxRaw] = rt.cidr.split('/');\n    const pfx = Number(pfxRaw);\n    const mask = pfx === 0 ? 0 : (0xffffffff << (32 - pfx)) >>> 0;\n    if (((toNum(net) & mask) >>> 0) !== ((target & mask) >>> 0)) return;\n    if (pfx > bestPfx) { bestPfx = pfx; best = rt.via; }\n  });\n  return best;\n}",
  tests:[["lookup([{cidr:'0.0.0.0/0',via:'gw'},{cidr:'10.0.0.0/8',via:'vpn'}], '10.1.2.3')","'vpn'"],
         ["lookup([{cidr:'0.0.0.0/0',via:'gw'},{cidr:'10.0.0.0/8',via:'vpn'}], '8.8.8.8')","'gw'"],
         ["lookup([{cidr:'10.0.0.0/8',via:'a'},{cidr:'10.1.0.0/16',via:'b'}], '10.1.5.5')","'b'"],
         ["lookup([{cidr:'10.0.0.0/8',via:'a'},{cidr:'10.1.0.0/16',via:'b'}], '10.2.5.5')","'a'"]],
  edge:[["lookup([], '1.2.3.4')","null"],
        ["lookup([{cidr:'192.168.1.1/32',via:'host'},{cidr:'192.168.1.0/24',via:'lan'}], '192.168.1.1')","'host'"]],
  ex:"🎯 라우팅 테이블에는 <b>겹치는 규칙이 정상적으로</b> 존재합니다 — 기본 경로(<code>0.0.0.0/0</code>)는 모든 주소에 맞고, 구체적인 경로는 일부에만 맞습니다. 그래서 '어느 것을 쓸까' 라는 규칙이 필요하고, 답은 <b>가장 구체적인 것</b>입니다.\n💡 이것이 nginx location, 파일 시스템 마운트, DNS 존 위임에도 같은 형태로 나타납니다 — <b>구체성이 일반성을 이긴다</b>는 원리는 라우팅 전반의 공통 문법입니다.\n⚠️ <code>/32</code> 는 호스트 하나만 가리키는 가장 구체적인 경로입니다. 특정 서버 한 대만 다른 경로로 보내는 트릭에 쓰이지만, 반대로 <b>왜 이 서버만 이상하게 동작하는지</b> 몇 시간을 태우는 원인이 되기도 합니다.\n🔧 실제 라우터는 이 선형 탐색 대신 <b>트라이(trie)</b> 를 씁니다 — 접두사 길이만큼만 비교하면 되어 수십만 개 경로에서도 상수 시간에 가깝습니다. 원리는 같고 자료구조만 다릅니다." },

{ track:"net", k:"TCP 혼잡 제어", cat:"internals",
  q:"TCP 의 <b>혼잡 윈도우</b> 변화를 계산하세요. <code>congestion(events, ssthresh)</code> 는 <code>'ack'</code>·<code>'loss'</code> 배열을 처리하며 <b>cwnd 를 1부터</b> 시작합니다 — <b>느린 시작</b>(cwnd &lt; ssthresh)에서는 ack 마다 <b>2배</b>, <b>혼잡 회피</b>에서는 <b>+1</b>, 손실이 나면 <b>ssthresh 를 cwnd 의 절반(최소 1)으로</b> 낮추고 cwnd 를 1로 되돌립니다. 매 단계의 cwnd 배열을 돌려주세요.",
  src:"function congestion(events, ssthresh) {\n  let cwnd = 1;\n  const out = [];\n  // TODO: 느린 시작 · 혼잡 회피 · 손실 처리\n  return out;\n}",
  sol:"function congestion(events, ssthresh) {\n  let cwnd = 1, th = ssthresh;\n  const out = [];\n  events.forEach((ev) => {\n    if (ev === 'loss') {\n      th = Math.max(1, Math.floor(cwnd / 2));\n      cwnd = 1;\n    } else if (cwnd < th) {\n      cwnd *= 2;\n    } else {\n      cwnd += 1;\n    }\n    out.push(cwnd);\n  });\n  return out;\n}",
  tests:[["congestion(['ack','ack','ack'], 8)","[2,4,8]"],
         ["congestion(['ack','ack','ack','ack'], 8)","[2,4,8,9]"],
         ["congestion(['ack','ack','loss','ack'], 8)","[2,4,1,2]"],
         ["congestion(['loss','ack'], 8)","[1,2]"]],
  edge:[["congestion([], 8)","[]"],
        ["congestion(['ack','ack','loss','ack','ack','ack'], 8)","[2,4,1,2,3,4]"]],
  ex:"🎯 TCP 는 네트워크의 용량을 <b>모릅니다</b> — 그래서 '늘려 보다가 깨지면 물러선다' 를 반복하며 스스로 찾아냅니다. 느린 시작의 지수 증가는 그 탐색을 빠르게, 혼잡 회피의 선형 증가는 조심스럽게 만듭니다.\n💡 손실을 <b>혼잡 신호로 해석</b>하는 것이 이 알고리즘의 전제입니다. 유선망에서는 대체로 맞지만 <b>무선망에서는 틀립니다</b> — 전파 간섭으로 인한 손실인데 TCP 는 '길이 막혔다' 고 오해해 속도를 절반으로 떨어뜨립니다.\n⚠️ 손실 후 ssthresh 가 <b>절반으로</b> 내려가는 것이 핵심입니다(곱셈적 감소). 증가는 더하기, 감소는 곱하기 — 이 비대칭(AIMD)이 여러 흐름이 대역폭을 공평하게 나눠 갖게 만드는 수학적 근거입니다.\n🔧 요즘은 손실 대신 <b>지연 증가</b>를 신호로 쓰는 BBR 같은 알고리즘이 늘고 있습니다. 버퍼가 큰 장비에서 손실이 나기 전에 이미 지연이 크게 늘어나는 문제(버퍼블로트)를 피하기 위해서입니다." },

{ track:"net", k:"슬라이딩 윈도우 ACK", cat:"internals",
  q:"수신 측 <b>슬라이딩 윈도우</b>를 구현하세요. <code>receive(base, size, arrivals)</code> 는 기대 시퀀스 번호와 윈도우 크기, 도착 순서를 받아 <code>{base, delivered}</code> 를 돌려줍니다 — <b>연속으로 이어지는 것만 전달</b>하고 base 를 밀며, 윈도우 밖(<code>seq &lt; base</code> 또는 <code>&gt;= base+size</code>)은 <b>버립니다</b>. 중복도 버립니다.",
  src:"function receive(base, size, arrivals) {\n  const buf = {};\n  const delivered = [];\n  // TODO: 창 안에 담고, 이어지는 것부터 전달\n  return { base, delivered };\n}",
  sol:"function receive(base, size, arrivals) {\n  const buf = {};\n  const delivered = [];\n  arrivals.forEach((seq) => {\n    if (seq < base || seq >= base + size) return;\n    if (buf[seq]) return;\n    buf[seq] = true;\n    while (buf[base]) { delivered.push(base); delete buf[base]; base++; }\n  });\n  return { base, delivered };\n}",
  tests:[["receive(0, 4, [0,1,2])","{base:3,delivered:[0,1,2]}"],
         ["receive(0, 4, [1,2,0])","{base:3,delivered:[0,1,2]}"],
         ["receive(0, 4, [1,2,3])","{base:0,delivered:[]}"],
         ["receive(0, 4, [0,0,1])","{base:2,delivered:[0,1]}"]],
  edge:[["receive(0, 4, [9])","{base:0,delivered:[]}"],
        ["receive(5, 3, [5,6,7,8])","{base:9,delivered:[5,6,7,8]}"]],
  ex:"🎯 순서가 뒤바뀌어 도착하는 것은 <b>정상</b>입니다 — 패킷마다 다른 경로를 갈 수 있기 때문입니다. 수신 측은 버퍼에 담아 두었다가 <b>빈칸이 메워지는 순간 한꺼번에</b> 위로 올려보냅니다.\n💡 그래서 앞의 패킷 하나가 유실되면 <b>뒤의 것들이 다 도착해도 전달되지 않습니다</b>(head-of-line blocking). 데이터는 이미 도착해 있는데 응용 계층은 아무것도 못 받는 상태 — 테스트 3번이 정확히 그 장면입니다.\n⚠️ 윈도우 밖 패킷을 버리는 것은 <b>메모리 보호</b>입니다. 크기를 정해 두지 않으면 악의적이거나 고장 난 송신자가 먼 미래의 시퀀스를 보내 수신 버퍼를 고갈시킬 수 있습니다.\n🔧 HTTP/2 가 한 TCP 연결에 여러 스트림을 태우면서 이 문제가 도드라졌습니다 — 무관한 스트림까지 함께 멈추기 때문입니다. HTTP/3 이 UDP 기반 QUIC 으로 옮겨 간 가장 큰 이유가 이 헤드 오브 라인 블로킹의 제거입니다." },

{ track:"net", k:"재전송 타임아웃 계산", cat:"internals",
  q:"TCP 의 <b>RTO</b> 를 계산하세요(RFC 6298). <code>rto(samples)</code> 는 RTT 표본 배열을 순서대로 처리합니다 — 첫 표본은 <code>srtt = r</code>, <code>rttvar = r/2</code> 이고, 이후에는 <code>rttvar = 0.75·rttvar + 0.25·|srtt − r|</code>, <code>srtt = 0.875·srtt + 0.125·r</code> 입니다. 결과는 <code>srtt + 4·rttvar</code> 를 <b>소수 둘째 자리에서 반올림</b>한 값입니다.",
  src:"function rto(samples) {\n  // TODO: 첫 표본 초기화 후 지수 이동 평균\n  return 0;\n}",
  sol:"function rto(samples) {\n  if (!samples.length) return 0;\n  let srtt = samples[0], rttvar = samples[0] / 2;\n  for (let i = 1; i < samples.length; i++) {\n    const r = samples[i];\n    rttvar = 0.75 * rttvar + 0.25 * Math.abs(srtt - r);\n    srtt = 0.875 * srtt + 0.125 * r;\n  }\n  return Math.round((srtt + 4 * rttvar) * 100) / 100;\n}",
  tests:[["rto([100])","300"],
         ["rto([100,100])","250"],
         ["rto([100,200])","362.5"],
         ["rto([100,100,100])","212.5"]],
  edge:[["rto([])","0"],
        ["rto([100,100,100,100])","184.38"]],
  ex:"🎯 RTO 는 '<b>얼마나 기다렸다 재전송할까</b>' 입니다. 너무 짧으면 멀쩡한 패킷을 중복 전송해 혼잡을 키우고, 너무 길면 손실 복구가 느려집니다 — 그래서 평균만이 아니라 <b>변동폭</b>까지 봅니다.\n💡 <code>srtt + 4·rttvar</code> 에서 4배가 핵심입니다. RTT 가 들쭉날쭉한 경로(모바일·위성)에서는 rttvar 가 커져 RTO 도 자동으로 넉넉해집니다 — <b>네트워크 성격에 따라 스스로 적응</b>하는 공식입니다.\n⚠️ 지수 이동 평균의 계수(1/8, 1/4)는 <b>시프트 연산으로 계산되도록</b> 고른 값입니다. 커널이 패킷마다 수행하는 계산이라 나눗셈을 피한 것이고, 30년 넘게 그대로 쓰이고 있습니다.\n🔧 재전송해도 응답이 없으면 RTO 를 <b>2배씩 늘립니다</b>(지수 백오프). 그리고 재전송한 패킷의 RTT 는 표본으로 쓰지 않습니다 — 원본에 대한 응답인지 재전송에 대한 응답인지 알 수 없어 측정이 오염되기 때문입니다(Karn 알고리즘)." },

{ track:"net", k:"chunked 인코딩 파싱", cat:"internals",
  q:"HTTP <b>chunked 전송 인코딩</b>을 해석하세요. <code>dechunk(body)</code> 는 <code>'5\\r\\nhello\\r\\n0\\r\\n\\r\\n'</code> 형식을 받아 본문을 이어 붙여 돌려줍니다. 길이는 <b>16진수</b>이고, <b>길이 0인 청크</b>가 끝 신호입니다. 형식이 깨지면 <code>null</code> 을 돌려주세요.",
  src:"function dechunk(body) {\n  // TODO: 16진수 길이를 읽고 그만큼 잘라 붙인다\n  return body;\n}",
  sol:"function dechunk(body) {\n  let i = 0, out = '';\n  for (;;) {\n    const nl = body.indexOf('\\r\\n', i);\n    if (nl < 0) return null;\n    const size = parseInt(body.slice(i, nl), 16);\n    if (Number.isNaN(size) || size < 0) return null;\n    if (size === 0) return out;\n    const start = nl + 2;\n    if (start + size > body.length) return null;\n    out += body.slice(start, start + size);\n    i = start + size + 2;\n  }\n}",
  tests:[["dechunk('5\\r\\nhello\\r\\n0\\r\\n\\r\\n')","'hello'"],
         ["dechunk('5\\r\\nhello\\r\\n5\\r\\nworld\\r\\n0\\r\\n\\r\\n')","'helloworld'"],
         ["dechunk('a\\r\\n0123456789\\r\\n0\\r\\n\\r\\n')","'0123456789'"],
         ["dechunk('0\\r\\n\\r\\n')","''"]],
  edge:[["dechunk('5\\r\\nhi\\r\\n0\\r\\n\\r\\n')","null"],
        ["dechunk('zz\\r\\nhi\\r\\n')","null"]],
  ex:"🎯 chunked 인코딩은 '<b>전체 길이를 미리 모를 때</b>' 쓰입니다 — 스트리밍 응답이나 동적으로 생성되는 본문이 그렇습니다. <code>Content-Length</code> 를 못 적는 대신 조각마다 길이를 앞에 붙입니다.\n💡 길이가 <b>16진수</b>인 것을 놓치면 10 이상에서 전부 틀립니다 — <code>'a'</code> 는 10바이트입니다. 실수해도 작은 청크에서는 안 드러나서 운영에서야 발견되는 종류입니다.\n⚠️ 길이와 실제 데이터가 어긋날 때 <b>관대하게 처리하면 보안 구멍</b>이 됩니다. 프록시와 서버가 청크 경계를 다르게 해석하면 <b>요청 스머글링</b>(HTTP request smuggling)이 성립합니다 — 하나의 요청이 둘로 쪼개져 인증을 우회합니다. 그래서 파서는 엄격해야 합니다.\n🔧 마지막 <code>0</code> 청크 뒤에는 트레일러 헤더가 올 수 있습니다(체크섬 등). 본문을 다 보낸 뒤에야 알 수 있는 정보를 담는 자리인데, 지원하는 클라이언트가 적어 실제로는 드물게 쓰입니다." },

{ track:"net", k:"DNS 레코드 해석", cat:"internals",
  q:"DNS <b>CNAME 체인</b>을 따라가세요. <code>resolve(zone, name)</code> 는 <code>{name: {type, value}}</code> 에서 최종 A 레코드의 IP 를 돌려줍니다 — CNAME 이면 그 대상으로 계속 따라가고, <b>10단계를 넘거나</b> 순환이면 <code>null</code>, 레코드가 없어도 <code>null</code> 입니다.",
  src:"function resolve(zone, name) {\n  // TODO: CNAME 을 따라가되 순환·과도한 단계를 막는다\n  const rec = zone[name];\n  return rec ? rec.value : null;\n}",
  sol:"function resolve(zone, name) {\n  const seen = new Set();\n  let cur = name;\n  for (let i = 0; i < 10; i++) {\n    if (seen.has(cur)) return null;\n    seen.add(cur);\n    const rec = zone[cur];\n    if (!rec) return null;\n    if (rec.type === 'A') return rec.value;\n    cur = rec.value;\n  }\n  return null;\n}",
  tests:[["resolve({'a.com':{type:'A',value:'1.2.3.4'}}, 'a.com')","'1.2.3.4'"],
         ["resolve({'w.com':{type:'CNAME',value:'a.com'},'a.com':{type:'A',value:'1.2.3.4'}}, 'w.com')","'1.2.3.4'"],
         ["resolve({'x.com':{type:'CNAME',value:'y.com'},'y.com':{type:'CNAME',value:'x.com'}}, 'x.com')","null"],
         ["resolve({}, 'nope.com')","null"]],
  edge:[["resolve({'a.com':{type:'CNAME',value:'missing.com'}}, 'a.com')","null"],
        ["resolve({'a.com':{type:'A',value:'1.1.1.1'},'b.com':{type:'CNAME',value:'a.com'},'c.com':{type:'CNAME',value:'b.com'}}, 'c.com')","'1.1.1.1'"]],
  ex:"🎯 CNAME 은 '<b>이 이름은 저 이름의 별칭</b>' 이라 해석이 <b>한 번에 끝나지 않습니다</b>. 리졸버는 A 레코드를 만날 때까지 따라가야 하고, 그 과정에서 순환에 빠질 수 있습니다.\n💡 <b>방문 기록과 단계 상한</b>을 둘 다 두는 것이 정석입니다. 순환은 기록으로 잡히지만, 순환이 아니면서 아주 긴 체인(설정 실수)은 상한으로만 막힙니다 — 상한이 없으면 리졸버가 매달립니다.\n⚠️ 체인이 길수록 <b>지연이 쌓입니다</b>. 각 단계가 캐시 미스면 왕복이 한 번씩 더 늘어나 첫 접속이 느려집니다 — CDN 을 여러 겹 두다 보면 실제로 3~4단계 CNAME 이 생깁니다.\n🔧 DNS 표준상 <b>도메인 루트(zone apex)에는 CNAME 을 둘 수 없습니다</b> — 그래서 <code>example.com</code> 을 CDN 에 붙이려면 ALIAS·ANAME 같은 제공업체별 확장을 쓰게 됩니다. 이 제약을 모르면 '왜 www 는 되는데 루트는 안 되지' 로 한참 헤맵니다." },

{ track:"net", k:"MTU 와 단편화", cat:"internals",
  q:"IP <b>단편화</b>를 계산하세요. <code>fragment(payload, mtu, headerLen)</code> 는 페이로드 바이트 수를 MTU 안에 나눠 담습니다 — 조각마다 헤더가 붙고, <b>마지막 조각을 뺀 나머지의 데이터 크기는 8의 배수</b>여야 합니다. <code>{count, sizes}</code>(각 조각의 <b>데이터</b> 크기)를 돌려주세요. 담을 수 없으면 <code>null</code> 입니다.",
  src:"function fragment(payload, mtu, headerLen) {\n  // TODO: 조각당 데이터 크기를 8의 배수로 맞춰 나눈다\n  return { count: 1, sizes: [payload] };\n}",
  sol:"function fragment(payload, mtu, headerLen) {\n  const room = Math.floor((mtu - headerLen) / 8) * 8;\n  if (room <= 0) return null;\n  if (payload <= mtu - headerLen) return { count: 1, sizes: [payload] };\n  const sizes = [];\n  let left = payload;\n  while (left > room) { sizes.push(room); left -= room; }\n  sizes.push(left);\n  return { count: sizes.length, sizes };\n}",
  tests:[["fragment(100, 1500, 20)","{count:1,sizes:[100]}"],
         ["fragment(3000, 1500, 20)","{count:3,sizes:[1480,1480,40]}"],
         ["fragment(2960, 1500, 20)","{count:2,sizes:[1480,1480]}"],
         ["fragment(1481, 1500, 20)","{count:2,sizes:[1480,1]}"]],
  edge:[["fragment(100, 20, 20)","null"],
        ["fragment(1480, 1500, 20)","{count:1,sizes:[1480]}"]],
  ex:"🎯 MTU 는 링크가 한 번에 나를 수 있는 최대 크기입니다. 넘으면 <b>쪼개서</b> 보내야 하고, 조각마다 헤더가 다시 붙어 오버헤드가 늘어납니다 — 3,000바이트가 3조각이 되면 헤더도 3배입니다.\n💡 <b>8의 배수</b> 제약은 IP 헤더의 조각 오프셋 필드가 <b>8바이트 단위</b>로 세기 때문입니다(13비트로 65,535바이트를 표현하려면 단위를 키워야 했습니다). 그래서 이더넷의 1500에서 헤더 20을 뺀 1480이 딱 떨어지는 것이 우연이 아닙니다.\n⚠️ 단편화의 진짜 문제는 <b>조각 하나만 잃어도 전체를 다시 보내야</b> 한다는 것입니다. 그래서 IPv6 는 중간 라우터의 단편화를 아예 금지하고, TCP 는 <b>경로 MTU 발견</b>으로 처음부터 쪼개지지 않을 크기로 보냅니다.\n🔧 그 경로 MTU 발견이 ICMP 를 막는 방화벽 때문에 실패하면 <b>연결은 되는데 큰 응답만 멈추는</b> 유명한 증상이 나옵니다 — '작은 페이지는 열리는데 파일 다운로드만 안 되는' 장애의 단골 원인입니다." },

{ track:"net", k:"NAT 매핑 테이블", cat:"internals",
  q:"<b>NAT</b> 포트 매핑을 구현하세요. <code>makeNat(startPort, max)</code> 는 <code>{map(ip, port), lookup(ext)}</code> 를 돌려줍니다. <code>map</code> 은 내부 <code>(ip, port)</code> 에 외부 포트를 배정하고(<b>같은 쌍이면 같은 포트를 재사용</b>), 포트를 다 쓰면 <code>null</code> 입니다. <code>lookup</code> 은 외부 포트로 <code>'ip:port'</code> 를 되찾고, 없으면 <code>null</code> 입니다.",
  src:"function makeNat(startPort, max) {\n  const fwd = {}, rev = {};\n  let next = startPort;\n  return {\n    map(ip, port) {\n      // TODO: 기존 매핑 재사용 · 포트 소진 처리\n      return next++;\n    },\n    lookup(ext) {\n      return rev[ext] || null;\n    },\n  };\n}",
  sol:"function makeNat(startPort, max) {\n  const fwd = {}, rev = {};\n  let next = startPort;\n  return {\n    map(ip, port) {\n      const key = ip + ':' + port;\n      if (fwd[key] !== undefined) return fwd[key];\n      if (next >= startPort + max) return null;\n      const ext = next++;\n      fwd[key] = ext;\n      rev[ext] = key;\n      return ext;\n    },\n    lookup(ext) {\n      return rev[ext] || null;\n    },\n  };\n}",
  tests:[["(() => { const nt=makeNat(40000,2); return [nt.map('10.0.0.1',80), nt.map('10.0.0.2',80)]; })()","[40000,40001]"],
         ["(() => { const nt=makeNat(40000,2); nt.map('10.0.0.1',80); return nt.map('10.0.0.1',80); })()","40000"],
         ["(() => { const nt=makeNat(40000,2); nt.map('a',1); nt.map('b',1); return nt.map('c',1); })()","null"],
         ["(() => { const nt=makeNat(40000,2); const e=nt.map('10.0.0.1',80); return nt.lookup(e); })()","'10.0.0.1:80'"]],
  edge:[["(() => { const nt=makeNat(40000,2); return nt.lookup(40000); })()","null"],
        ["(() => { const nt=makeNat(40000,1); nt.map('a',1); return nt.map('a',1); })()","40000"]],
  ex:"🎯 NAT 은 사설 IP 여럿을 공인 IP 하나로 내보냅니다. 구분은 <b>포트 번호</b>로 하며, 그 대응표가 이 자료구조입니다 — IPv4 주소 고갈을 수십 년 미룬 장치입니다.\n💡 <b>같은 내부 쌍은 같은 외부 포트를 재사용</b>해야 합니다. 매번 새로 배정하면 서버 입장에서 같은 클라이언트가 다른 출발지로 보여, 세션이 끊기고 포트도 금방 소진됩니다.\n⚠️ 포트는 유한합니다(약 64,000). 사용자가 많거나 커넥션을 많이 여는 앱이 있으면 <b>포트 고갈</b>이 나고, 증상은 '일부 연결만 안 되는' 형태로 나타나 원인 찾기가 어렵습니다 — CGNAT 환경에서 특히 흔합니다.\n🔧 NAT 뒤에서는 <b>외부에서 먼저 연결할 수 없습니다</b> — 매핑이 없기 때문입니다. P2P·화상통화가 STUN/TURN·홀 펀칭 같은 기법을 쓰는 이유이고, IPv6 가 이 복잡도를 없애려는 이유이기도 합니다." },

{ track:"net", k:"우선순위 큐 스케줄링", cat:"design",
  q:"<b>가중치 라운드로빈</b>으로 큐를 서비스하세요. <code>schedule(queues, rounds)</code> 는 <code>{name, weight, backlog}</code> 목록을 받아, 매 라운드 각 큐를 <b>선언 순서대로</b> 돌며 <b>가중치만큼</b>(단, 남은 backlog 까지만) 처리합니다. 처리한 순서대로 큐 이름을 나열해 돌려주세요.",
  src:"function schedule(queues, rounds) {\n  // TODO: 라운드마다 가중치만큼 처리\n  return [];\n}",
  sol:"function schedule(queues, rounds) {\n  const left = queues.map((q) => q.backlog);\n  const out = [];\n  for (let r = 0; r < rounds; r++) {\n    queues.forEach((q, i) => {\n      const take = Math.min(q.weight, left[i]);\n      for (let n = 0; n < take; n++) out.push(q.name);\n      left[i] -= take;\n    });\n  }\n  return out;\n}",
  tests:[["schedule([{name:'hi',weight:2,backlog:10},{name:'lo',weight:1,backlog:10}], 2)","['hi','hi','lo','hi','hi','lo']"],
         ["schedule([{name:'a',weight:1,backlog:1},{name:'b',weight:1,backlog:3}], 2)","['a','b','b']"],
         ["schedule([{name:'a',weight:3,backlog:2}], 1)","['a','a']"],
         ["schedule([{name:'a',weight:1,backlog:0},{name:'b',weight:1,backlog:1}], 1)","['b']"]],
  edge:[["schedule([], 3)","[]"],
        ["schedule([{name:'a',weight:2,backlog:5}], 0)","[]"]],
  ex:"🎯 엄격한 우선순위(높은 큐를 다 비우고 다음)는 <b>낮은 큐가 영원히 굶는</b> 문제가 있습니다. 가중치 라운드로빈은 '많이 주되 <b>0은 주지 않는다</b>' 로 그 사이를 잡습니다.\n💡 가중치가 곧 <b>대역폭 배분 비율</b>입니다. 2:1 이면 장기적으로 대역폭도 2:1 로 나뉩니다 — 이 예측 가능성 덕분에 SLA 를 숫자로 약속할 수 있습니다.\n⚠️ 패킷 크기가 다르면 '개수 기준' 배분이 <b>실제 대역폭 배분과 어긋납니다</b> — 작은 패킷 2개와 큰 패킷 1개는 개수로는 2:1 이지만 바이트로는 반대일 수 있습니다. 그래서 실제 라우터는 바이트를 세는 결손 라운드로빈(DRR)을 씁니다.\n🔧 같은 구조가 스레드 풀·작업 큐·API 테넌트 분리에도 그대로 쓰입니다. '중요한 일을 먼저, 하지만 나머지도 언젠가는' 이라는 요구가 있는 곳이면 어디든 같은 답이 나옵니다." },

{ track:"net", k:"TLS 핸드셰이크 왕복", cat:"design",
  q:"연결 수립에 드는 <b>왕복 수</b>를 계산하세요. <code>handshake(version, resumed, rttMs)</code> 는 총 지연(ms)을 돌려줍니다 — TCP 3-way 가 <b>1 RTT</b>, 그 위에 TLS 1.2 는 <b>2 RTT</b>, TLS 1.3 은 <b>1 RTT</b> 가 듭니다. 세션 재개면 1.2 는 <b>1 RTT</b>, 1.3 은 <b>0 RTT</b> 입니다. 모르는 버전은 <code>null</code> 입니다.",
  src:"function handshake(version, resumed, rttMs) {\n  // TODO: TCP 1 RTT + TLS 버전·재개별 RTT\n  return rttMs;\n}",
  sol:"function handshake(version, resumed, rttMs) {\n  const tls = { '1.2': resumed ? 1 : 2, '1.3': resumed ? 0 : 1 }[version];\n  if (tls === undefined) return null;\n  return (1 + tls) * rttMs;\n}",
  tests:[["handshake('1.2', false, 50)","150"],
         ["handshake('1.3', false, 50)","100"],
         ["handshake('1.3', true, 50)","50"],
         ["handshake('1.2', true, 50)","100"]],
  edge:[["handshake('1.1', false, 50)","null"],
        ["handshake('1.3', true, 0)","0"]],
  ex:"🎯 첫 요청이 느린 이유는 대역폭이 아니라 <b>왕복 수</b>입니다. TCP 3-way 1회에 TLS 1.2 가 2회를 더하면, 데이터가 오가기도 전에 이미 <b>RTT 3배</b>가 흘렀습니다 — RTT 50ms 면 150ms, 200ms 면 600ms 입니다.\n💡 TLS 1.3 이 핸드셰이크를 1 RTT 로 줄인 것이 그래서 큰 개선입니다. 협상할 암호 조합을 미리 좁혀 <b>왕복 한 번을 통째로 없앤</b> 설계이고, 세션 재개(0-RTT)에서는 첫 데이터를 핸드셰이크와 <b>함께</b> 보냅니다.\n⚠️ 0-RTT 에는 <b>재전송 공격</b> 위험이 있습니다 — 공격자가 그 첫 요청을 그대로 다시 보낼 수 있어, <b>멱등한 요청에만</b> 써야 합니다. 결제 요청을 0-RTT 로 보내면 안 되는 이유입니다.\n🔧 그래서 지연 개선의 순서는 대개 이렇습니다 — <b>가까운 곳에서 응답하고</b>(CDN·엣지, RTT 자체를 줄임), <b>연결을 재사용하고</b>(keep-alive·HTTP/2), 그다음이 압축과 캐시입니다. 왕복 하나가 바이트 수십 KB 보다 비쌀 때가 많습니다." },
];
