/* 실행형이 0이던 데이터·ML 트랙(numpy·pandas·stat·mleval·ml·dl)에 실행 문항을 넣는다.
   이 영역은 '공식을 외웠는데 축을 잘못 잡거나 분모를 틀리는' 실수가 대부분이라
   직접 계산해 보는 것이 가장 확실하다.
   주의: 앱 하네스가 쓰는 이름(SRC·TS·eq·gate·impl 등)과 겹치지 않게 짓는다. */
module.exports = [
/* ───────────── numpy ───────────── */
{ track:"numpy", k:"브로드캐스팅 규칙", cat:"internals",
  q:"두 배열의 <b>브로드캐스팅 결과 모양</b>을 계산하세요. 규칙: 뒤에서부터 짝을 맞추고, <b>같거나 한쪽이 1</b>이면 큰 쪽으로 늘어납니다. 맞지 않으면 <code>null</code> 입니다. 짧은 쪽 앞은 <b>1로 채웁니다</b>.",
  src:"function bshape(a, b) {\n  // TODO: 뒤에서부터 비교해 결과 모양을 만드세요\n  return null;\n}",
  sol:"function bshape(a, b) {\n  const n = Math.max(a.length, b.length);\n  const out = [];\n  for (let i = 0; i < n; i++) {\n    const x = a[a.length - 1 - i];\n    const y = b[b.length - 1 - i];\n    const dx = x === undefined ? 1 : x;\n    const dy = y === undefined ? 1 : y;\n    if (dx !== dy && dx !== 1 && dy !== 1) return null;\n    out.unshift(Math.max(dx, dy));\n  }\n  return out;\n}",
  tests:[["bshape([3,1],[3,4])","[3,4]"],
         ["bshape([5],[3,5])","[3,5]"],
         ["bshape([3,2],[3,4])","null"],
         ["bshape([2,1,3],[4,3])","[2,4,3]"]],
  edge:[["bshape([],[3])","[3]"],["bshape([1],[1])","[1]"]],
  ex:"🎯 브로드캐스팅은 <b>뒤에서부터</b> 짝을 맞춥니다. 앞쪽 차원이 모자라면 1로 채워지므로 <code>(5,)</code> 와 <code>(3,5)</code> 는 맞고 <code>(5,)</code> 와 <code>(5,3)</code> 은 맞지 않습니다.\n💡 이 방향 때문에 '행 벡터를 각 행에 더하기' 는 자연스럽지만 '열 벡터를 각 열에 더하기' 는 <code>(n,1)</code> 로 <b>모양을 바꿔 줘야</b> 합니다. <code>reshape(-1,1)</code> 이 늘 등장하는 이유입니다.\n⚠️ 가장 위험한 것은 <b>조용히 맞는</b> 경우입니다. <code>(100,1)</code> 과 <code>(100,)</code> 를 더하면 오류가 아니라 <code>(100,100)</code> 이 되어 메모리를 만 배 씁니다 — 예측 결과와 정답의 모양이 어긋났을 때 흔히 일어납니다.\n🔧 그래서 계산 전에 <code>.shape</code> 를 찍어 보는 습관이 실제로 시간을 아낍니다." },

{ track:"numpy", k:"축을 따라 집계하기", cat:"internals",
  q:"2차원 배열에서 <code>axis</code> 를 따라 합을 구하세요. <code>sumAxis(m, axis)</code> 에서 <b>axis=0 은 행을 가로질러(열별 합)</b>, <b>axis=1 은 열을 가로질러(행별 합)</b> 입니다. <code>axis=null</code> 이면 전체 합입니다.",
  src:"function sumAxis(m, axis) {\n  // TODO: axis 0/1/null\n  return 0;\n}",
  sol:"function sumAxis(m, axis) {\n  if (axis === null) return m.reduce((s, r) => s + r.reduce((a, b) => a + b, 0), 0);\n  if (axis === 1) return m.map((r) => r.reduce((a, b) => a + b, 0));\n  return m[0].map((_, c) => m.reduce((s, r) => s + r[c], 0));\n}",
  tests:[["sumAxis([[1,2],[3,4]],0)","[4,6]"],
         ["sumAxis([[1,2],[3,4]],1)","[3,7]"],
         ["sumAxis([[1,2],[3,4]],null)","10"],
         ["sumAxis([[1,2,3]],0)","[1,2,3]"]],
  edge:[["sumAxis([[1,2,3]],1)","[6]"],
        ["sumAxis([[5]],null)","5"]],
  ex:"🎯 <code>axis</code> 는 '<b>어느 축을 없앨 것인가</b>' 입니다. <code>axis=0</code> 은 행 축이 사라져 열별 결과가 남고, <code>axis=1</code> 은 열 축이 사라져 행별 결과가 남습니다.\n💡 '축을 따라 계산한다' 를 '그 축 방향으로 훑는다' 로 읽으면 헷갈립니다. <b>결과의 모양</b>으로 기억하세요 — <code>(2,3)</code> 에서 <code>axis=0</code> 이면 <code>(3,)</code>, <code>axis=1</code> 이면 <code>(2,)</code> 입니다.\n⚠️ 이걸 뒤집으면 '샘플별 평균' 대신 '특성별 평균' 을 구하게 되는데, <b>모양이 우연히 맞으면 오류도 안 납니다</b>. 정사각 행렬로 테스트하면 못 잡으므로 이 문항의 테스트는 모두 비정사각입니다.\n🔧 <code>keepdims=True</code> 는 축을 없애지 않고 1로 남겨 브로드캐스팅이 그대로 되게 합니다 — 정규화할 때 특히 유용합니다." },

{ track:"numpy", k:"행렬 곱", cat:"internals",
  q:"행렬 곱 <code>matmul(a, b)</code> 를 구현하세요. <code>a</code> 가 <code>(n,k)</code>, <code>b</code> 가 <code>(k,m)</code> 이면 결과는 <code>(n,m)</code> 입니다. 안쪽 차원이 맞지 않으면 <code>null</code> 을 돌려주세요.",
  src:"function matmul(a, b) {\n  // TODO: 차원 검사 후 곱\n  return null;\n}",
  sol:"function matmul(a, b) {\n  if (!a.length || !b.length || a[0].length !== b.length) return null;\n  return a.map((row) =>\n    b[0].map((_, j) => row.reduce((s, v, k) => s + v * b[k][j], 0)));\n}",
  tests:[["matmul([[1,2],[3,4]],[[5,6],[7,8]])","[[19,22],[43,50]]"],
         ["matmul([[1,2,3]],[[1],[1],[1]])","[[6]]"],
         ["matmul([[1,2]],[[1,2],[3,4]])","[[7,10]]"],
         ["matmul([[1,2]],[[1,2]])","null"]],
  edge:[["matmul([[1,0],[0,1]],[[5,6],[7,8]])","[[5,6],[7,8]]"],
        ["matmul([],[[1]])","null"]],
  ex:"🎯 행렬 곱은 <b>안쪽 차원이 맞아야</b> 합니다 — <code>(n,k) × (k,m)</code>. 이 조건을 코드로 확인하지 않으면 잘못된 값이 조용히 계산됩니다.\n💡 결과 <code>(i,j)</code> 는 'a 의 i행과 b 의 j열의 내적' 입니다. 신경망의 한 층이 정확히 이 연산이고, 그래서 가중치 행렬의 모양이 <code>(입력 차원, 출력 차원)</code> 입니다.\n⚠️ 행렬 곱은 <b>교환법칙이 성립하지 않습니다</b>. <code>a×b</code> 와 <code>b×a</code> 는 모양부터 다를 수 있고, 둘 다 가능해도 값이 다릅니다 — 순서를 바꿔 '차원이 맞으니 됐다' 고 넘어가면 안 됩니다.\n🔧 <code>*</code> 는 요소별 곱이고 행렬 곱은 <code>@</code> 또는 <code>matmul</code> 입니다. 파이썬에서 이 둘을 혼동하면 브로드캐스팅 때문에 오류 없이 엉뚱한 결과가 나옵니다." },

{ track:"numpy", k:"뷰와 복사", cat:"internals",
  q:"배열 슬라이스가 <b>원본을 공유하는지</b> 확인하는 모델을 만드세요. <code>slice(arr, s, e)</code> 는 <b>뷰</b>(원본 공유)를 돌려주고, <code>copy(arr, s, e)</code> 는 독립된 배열을 돌려줍니다. 뷰에 값을 쓰면 원본도 바뀌어야 합니다.",
  src:"function slice(arr, s, e) {\n  // TODO: 원본을 공유하는 뷰 — {get, set, length}\n  return null;\n}\n\nfunction copy(arr, s, e) {\n  return arr.slice(s, e);\n}",
  sol:"function slice(arr, s, e) {\n  return {\n    length: e - s,\n    get(i) { return arr[s + i]; },\n    set(i, v) { arr[s + i] = v; },\n  };\n}\n\nfunction copy(arr, s, e) {\n  return arr.slice(s, e);\n}",
  tests:[["(() => { const a=[1,2,3,4]; const v=slice(a,1,3); v.set(0,99); return a; })()","[1,99,3,4]"],
         ["(() => { const a=[1,2,3,4]; const c=copy(a,1,3); c[0]=99; return a; })()","[1,2,3,4]"],
         ["(() => { const a=[1,2,3,4]; return slice(a,1,3).get(1); })()","3"],
         ["(() => { const a=[1,2,3,4]; return slice(a,1,3).length; })()","2"]],
  edge:[["(() => { const a=[1,2,3]; const v=slice(a,0,3); v.set(2,9); return a[2]; })()","9"],
        ["copy([1,2,3],0,0)","[]"]],
  ex:"🎯 numpy 의 기본 슬라이싱은 <b>복사가 아니라 뷰</b>입니다. <code>b = a[1:3]</code> 뒤에 <code>b[0] = 99</code> 하면 <b>a 도 바뀝니다</b> — 파이썬 리스트 슬라이싱과 정반대라 가장 자주 당하는 지점입니다.\n💡 뷰인 이유는 성능입니다. 큰 배열을 자를 때마다 복사하면 메모리와 시간이 배로 듭니다. 그래서 numpy 는 '같은 메모리를 다른 모양으로 보는' 것을 기본으로 삼습니다.\n⚠️ 반대로 <b>팬시 인덱싱</b>(<code>a[[0,2]]</code>)과 <b>불리언 인덱싱</b>은 복사입니다. 어떤 것이 뷰이고 어떤 것이 복사인지가 규칙으로 갈리므로, 헷갈리면 <code>.copy()</code> 를 명시하세요.\n🔧 원본을 지키고 싶으면 <code>.copy()</code>, 메모리를 아끼려면 뷰 — 이 선택을 코드에 드러내는 것이 나중의 디버깅 시간을 줄입니다." },

/* ───────────── pandas ───────────── */
{ track:"pandas", k:"그룹별 집계", cat:"internals",
  q:"레코드 배열을 <b>키로 묶어 집계</b>하세요. <code>groupAgg(rows, key, value)</code> 는 <code>{키: {n, sum, mean}}</code> 을 돌려줍니다. <code>value</code> 가 <code>null</code>·<code>undefined</code>인 행은 <b>집계에서 제외</b>하되 그룹은 남깁니다.",
  src:"function groupAgg(rows, key, value) {\n  // TODO: 결측을 빼고 그룹별 n·sum·mean\n  return {};\n}",
  sol:"function groupAgg(rows, key, value) {\n  const out = {};\n  rows.forEach((r) => {\n    const k = r[key];\n    if (!out[k]) out[k] = { n: 0, sum: 0, mean: null };\n    const v = r[value];\n    if (v === null || v === undefined) return;\n    out[k].n += 1;\n    out[k].sum += v;\n  });\n  Object.keys(out).forEach((k) => {\n    out[k].mean = out[k].n ? out[k].sum / out[k].n : null;\n  });\n  return out;\n}",
  tests:[["groupAgg([{g:'a',v:1},{g:'a',v:3},{g:'b',v:10}],'g','v')","{a:{n:2,sum:4,mean:2},b:{n:1,sum:10,mean:10}}"],
         ["groupAgg([{g:'a',v:null},{g:'a',v:4}],'g','v').a","{n:1,sum:4,mean:4}"],
         ["groupAgg([{g:'x',v:null}],'g','v').x","{n:0,sum:0,mean:null}"],
         ["Object.keys(groupAgg([{g:'a',v:1},{g:'b',v:2}],'g','v')).sort()","['a','b']"]],
  edge:[["groupAgg([],'g','v')","{}"],
        ["groupAgg([{g:'a',v:0}],'g','v').a.mean","0"]],
  ex:"🎯 판다스의 집계 함수는 <b>결측(NaN)을 자동으로 건너뜁니다</b>. 그래서 <code>mean()</code> 의 분모는 전체 행 수가 아니라 <b>값이 있는 행 수</b>입니다 — 이걸 모르면 평균이 왜 높은지 설명하지 못합니다.\n💡 결측을 0으로 볼지 제외할지는 <b>도메인 결정</b>입니다. '응답하지 않음' 을 0점으로 치는 것과 모집단에서 빼는 것은 전혀 다른 값을 냅니다.\n⚠️ 값이 하나도 없는 그룹의 평균은 <b>정의되지 않습니다</b>. 0으로 채우면 '평균 0인 그룹' 으로 보여 그래프가 거짓말을 합니다 — null 로 두고 화면에서 구분해야 합니다.\n🔧 <code>count()</code> 는 결측이 아닌 값의 수, <code>size()</code> 는 그룹의 행 수입니다. 둘의 차이가 곧 결측 개수라 데이터 점검에 유용합니다." },

{ track:"pandas", k:"조인의 종류", cat:"internals",
  q:"두 테이블을 키로 합치는 <code>join(left, right, key, how)</code> 를 만드세요. <code>how</code> 는 <code>'inner'</code>·<code>'left'</code> 입니다. left 조인에서 짝이 없으면 오른쪽 컬럼은 <code>null</code> 이고, 오른쪽에 같은 키가 여러 개면 <b>행이 늘어납니다</b>.",
  src:"function join(left, right, key, how) {\n  // TODO: inner / left\n  return [];\n}",
  sol:"function join(left, right, key, how) {\n  const out = [];\n  left.forEach((l) => {\n    const hits = right.filter((r) => r[key] === l[key]);\n    if (hits.length) {\n      hits.forEach((r) => out.push(Object.assign({}, l, r)));\n    } else if (how === 'left') {\n      const blank = {};\n      Object.keys(right[0] || {}).forEach((k) => { if (k !== key) blank[k] = null; });\n      out.push(Object.assign({}, l, blank));\n    }\n  });\n  return out;\n}",
  tests:[["join([{id:1,a:'x'}],[{id:1,b:'y'}],'id','inner')","[{id:1,a:'x',b:'y'}]"],
         ["join([{id:2,a:'x'}],[{id:1,b:'y'}],'id','inner')","[]"],
         ["join([{id:2,a:'x'}],[{id:1,b:'y'}],'id','left')","[{id:2,a:'x',b:null}]"],
         ["join([{id:1,a:'x'}],[{id:1,b:'y'},{id:1,b:'z'}],'id','inner').length","2"]],
  edge:[["join([],[{id:1,b:'y'}],'id','left')","[]"],
        ["join([{id:1,a:'x'}],[],'id','left')","[{id:1,a:'x'}]"]],
  ex:"🎯 조인에서 가장 자주 놀라는 것은 <b>행이 늘어나는</b> 것입니다. 오른쪽에 같은 키가 2개면 왼쪽 1행이 2행이 되고, 그 상태로 합계를 내면 <b>두 배</b>가 됩니다(팬아웃).\n🔧 그래서 조인 전후에 <b>행 수를 확인</b>하는 습관이 필요합니다. 판다스에서는 <code>validate='1:1'</code>·<code>'1:m'</code> 로 기대를 코드에 못 박을 수 있습니다.\n💡 left 조인은 '왼쪽은 다 남긴다' 는 뜻이고, 짝이 없으면 오른쪽 컬럼이 NaN 이 됩니다. 그 NaN 을 그대로 집계하면 조용히 제외되므로 <b>결측 처리를 먼저</b> 정해야 합니다.\n⚠️ 조인 키의 <b>타입이 다르면</b> 아무것도 매칭되지 않습니다. 한쪽이 문자열 '1' 이고 한쪽이 정수 1인 경우가 실제로 가장 흔한 원인입니다." },

{ track:"pandas", k:"결측치 채우기", cat:"internals",
  q:"시계열 값의 결측을 채우세요. <code>fill(rows, method)</code> 에서 <code>'ffill'</code> 은 <b>직전 값</b>으로, <code>'mean'</code> 은 <b>결측이 아닌 값들의 평균</b>으로 채웁니다. ffill 에서 <b>맨 앞이 결측이면 채울 수 없어</b> null 로 남습니다.",
  src:"function fill(rows, method) {\n  // TODO: ffill / mean\n  return rows.slice();\n}",
  sol:"function fill(rows, method) {\n  if (method === 'mean') {\n    const ok = rows.filter((v) => v !== null);\n    const m = ok.length ? ok.reduce((a, b) => a + b, 0) / ok.length : null;\n    return rows.map((v) => (v === null ? m : v));\n  }\n  let last = null;\n  return rows.map((v) => {\n    if (v !== null) { last = v; return v; }\n    return last;\n  });\n}",
  tests:[["fill([1,null,3],'ffill')","[1,1,3]"],
         ["fill([null,2,null],'ffill')","[null,2,2]"],
         ["fill([1,null,3],'mean')","[1,2,3]"],
         ["fill([null,null],'mean')","[null,null]"]],
  edge:[["fill([],'ffill')","[]"],
        ["fill([5,null,null],'ffill')","[5,5,5]"]],
  ex:"🎯 결측 채우기는 <b>없던 정보를 만들어 내는</b> 일입니다. 어떤 방법을 쓰든 원본에 없던 값이 생기므로, 선택 근거가 분석 결과의 일부가 됩니다.\n💡 <b>ffill</b> 은 '값이 바뀌지 않았다' 는 가정입니다 — 센서나 잔액처럼 상태가 유지되는 데이터에 맞고, 온도처럼 계속 변하는 값에는 부적절합니다. 맨 앞이 결측이면 채울 직전 값이 없다는 점도 중요합니다.\n⚠️ <b>평균 채우기</b>는 분산을 인위적으로 줄입니다. 채운 값이 전부 같으므로 표준편차가 작아지고 상관계수가 왜곡됩니다.\n🔧 가장 위험한 것은 <b>학습 데이터 전체의 평균</b>으로 채운 뒤 train/test 를 나누는 것입니다. 테스트 정보가 학습에 새어 들어가는 누수(leakage)이므로, 평균은 반드시 학습 데이터에서만 계산해야 합니다." },

{ track:"pandas", k:"피벗과 재구조화", cat:"internals",
  q:"긴 형식(long)을 넓은 형식(wide)으로 바꾸세요. <code>pivot(rows, index, col, value)</code> 는 <code>{index값: {col값: value}}</code> 를 돌려줍니다. <b>같은 (index, col) 조합이 두 번</b> 나오면 <code>null</code> 을 돌려주세요(집계 방법이 없으므로).",
  src:"function pivot(rows, index, col, value) {\n  // TODO: 중복 조합이면 null\n  return {};\n}",
  sol:"function pivot(rows, index, col, value) {\n  const out = {};\n  for (const r of rows) {\n    const i = r[index];\n    const c = r[col];\n    if (!out[i]) out[i] = {};\n    if (c in out[i]) return null;\n    out[i][c] = r[value];\n  }\n  return out;\n}",
  tests:[["pivot([{d:'1일',p:'a',v:10},{d:'1일',p:'b',v:20}],'d','p','v')","{'1일':{a:10,b:20}}"],
         ["pivot([{d:'1일',p:'a',v:10},{d:'2일',p:'a',v:30}],'d','p','v')","{'1일':{a:10},'2일':{a:30}}"],
         ["pivot([{d:'1일',p:'a',v:10},{d:'1일',p:'a',v:20}],'d','p','v')","null"],
         ["Object.keys(pivot([{d:'x',p:'a',v:1}],'d','p','v'))","['x']"]],
  edge:[["pivot([],'d','p','v')","{}"],
        ["pivot([{d:'x',p:'a',v:null}],'d','p','v')","{x:{a:null}}"]],
  ex:"🎯 피벗은 <b>같은 데이터를 다른 모양으로</b> 보는 것입니다. 긴 형식은 저장·집계에 좋고, 넓은 형식은 사람이 읽고 비교하기에 좋습니다.\n⚠️ 핵심 조건은 <b>(index, column) 조합이 유일해야 한다</b>는 것입니다. 중복이 있으면 한 칸에 값이 두 개라 무엇을 넣을지 정할 수 없습니다 — 판다스의 <code>pivot</code> 은 이때 오류를 내고, <code>pivot_table</code> 은 집계 함수(기본 평균)로 합칩니다.\n💡 그래서 <code>pivot_table</code> 이 조용히 평균을 내는 것이 함정이 될 수 있습니다. 중복이 있다는 사실 자체가 데이터 문제일 수 있는데 그냥 넘어가기 때문입니다.\n🔧 넓은 형식은 <b>열이 데이터에 따라 늘어납니다</b>. 새 카테고리가 생기면 컬럼이 생기므로, 저장은 긴 형식으로 하고 표시할 때만 피벗하는 것이 관리에 유리합니다." },

/* ───────────── stat ───────────── */
{ track:"stat", k:"표본 표준편차의 분모", cat:"internals",
  q:"평균·<b>모집단 표준편차</b>(분모 n)·<b>표본 표준편차</b>(분모 n−1)를 구하세요. <code>stats(xs)</code> 는 <code>{mean, pstd, sstd}</code> 를 돌려주고, 값이 <b>1개면 sstd 는 null</b> 입니다.",
  src:"function stats(xs) {\n  // TODO: 분모가 다른 두 표준편차\n  return { mean: 0, pstd: 0, sstd: null };\n}",
  sol:"function stats(xs) {\n  const n = xs.length;\n  if (!n) return { mean: null, pstd: null, sstd: null };\n  const mean = xs.reduce((a, b) => a + b, 0) / n;\n  const ss = xs.reduce((a, b) => a + (b - mean) * (b - mean), 0);\n  return {\n    mean,\n    pstd: Math.sqrt(ss / n),\n    sstd: n > 1 ? Math.sqrt(ss / (n - 1)) : null,\n  };\n}",
  tests:[["stats([2,4,4,4,5,5,7,9]).mean","5"],
         ["stats([2,4,4,4,5,5,7,9]).pstd","2"],
         ["Math.round(stats([2,4,4,4,5,5,7,9]).sstd*1000)/1000","2.138"],
         ["stats([5]).sstd","null"]],
  edge:[["stats([]).mean","null"],
        ["stats([3,3,3]).pstd","0"]],
  ex:"🎯 분모가 <code>n</code> 이냐 <code>n-1</code> 이냐는 '<b>가진 데이터가 전부인가, 표본인가</b>' 로 갈립니다. 표본으로 모집단의 분산을 추정할 때 <code>n</code> 으로 나누면 <b>실제보다 작게</b> 나오므로 보정합니다(베셀 보정).\n💡 왜 작아지는가 — 편차를 <b>표본 평균</b> 기준으로 재는데, 표본 평균은 그 표본에 가장 가까운 값이라 편차가 과소평가됩니다. 자유도가 하나 줄었다고 표현합니다.\n⚠️ 라이브러리 기본값이 다릅니다. numpy 의 <code>std()</code> 는 기본이 <code>ddof=0</code>(모집단), 판다스의 <code>std()</code> 는 <code>ddof=1</code>(표본)입니다 — <b>같은 데이터에 다른 값</b>이 나오므로 어느 쪽인지 확인해야 합니다.\n🔧 데이터가 1개면 표본 표준편차는 <b>정의되지 않습니다</b>(0으로 나눔). 0으로 채우면 '변동이 없다' 는 거짓 정보가 됩니다." },

{ track:"stat", k:"사분위와 이상치", cat:"internals",
  q:"사분위수와 <b>IQR 이상치</b>를 구하세요. <code>quartiles(xs)</code> 는 <code>{q1, q2, q3}</code> 를(정렬 후 <b>선형 보간</b>), <code>outliers(xs)</code> 는 <code>Q1−1.5×IQR</code> 미만이거나 <code>Q3+1.5×IQR</code> 초과인 값을 돌려줍니다.",
  src:"function pct(sorted, p) {\n  const i = (sorted.length - 1) * p;\n  const lo = Math.floor(i);\n  const hi = Math.ceil(i);\n  return sorted[lo] + (sorted[hi] - sorted[lo]) * (i - lo);\n}\n\nfunction quartiles(xs) {\n  // TODO\n  return { q1: 0, q2: 0, q3: 0 };\n}\n\nfunction outliers(xs) {\n  // TODO\n  return [];\n}",
  sol:"function pct(sorted, p) {\n  const i = (sorted.length - 1) * p;\n  const lo = Math.floor(i);\n  const hi = Math.ceil(i);\n  return sorted[lo] + (sorted[hi] - sorted[lo]) * (i - lo);\n}\n\nfunction quartiles(xs) {\n  const s = [...xs].sort((a, b) => a - b);\n  return { q1: pct(s, 0.25), q2: pct(s, 0.5), q3: pct(s, 0.75) };\n}\n\nfunction outliers(xs) {\n  const { q1, q3 } = quartiles(xs);\n  const iqr = q3 - q1;\n  return xs.filter((v) => v < q1 - 1.5 * iqr || v > q3 + 1.5 * iqr);\n}",
  tests:[["quartiles([1,2,3,4,5]).q2","3"],
         ["quartiles([1,2,3,4,5]).q1","2"],
         ["outliers([1,2,3,4,100])","[100]"],
         ["outliers([1,2,3,4,5])","[]"]],
  edge:[["(() => { const a=[3,1,2]; outliers(a); return a; })()","[3,1,2]"],
        ["quartiles([10]).q2","10"]],
  ex:"🎯 IQR 방식이 평균±표준편차보다 나은 이유는 <b>이상치에 강하다</b>는 것입니다. 평균과 표준편차는 이상치 자체에 끌려가므로, 극단값이 있으면 기준선이 함께 넓어져 그 값을 정상으로 판정합니다.\n💡 1.5 라는 계수는 정규분포에서 약 0.7% 가 걸리도록 정해진 관행값입니다 — 법칙이 아니라 <b>선택</b>이므로 도메인에 따라 3.0 을 쓰기도 합니다.\n⚠️ '이상치' 가 곧 '잘못된 값' 은 아닙니다. 진짜 극단 사건일 수도 있으므로 <b>지우기 전에 왜 그런지</b> 확인해야 합니다 — 사기 탐지에서는 이상치가 오히려 찾는 대상입니다.\n🔧 백분위 계산 방법이 여러 가지라 라이브러리마다 Q1 값이 다를 수 있습니다. 이 문항은 선형 보간(numpy 기본)을 씁니다. 그리고 <code>sort</code> 는 원본을 바꾸므로 복사 후 정렬해야 합니다 — 엣지 케이스가 그것을 검사합니다." },

{ track:"stat", k:"상관계수", cat:"internals",
  q:"두 변수의 <b>피어슨 상관계수</b>를 구하세요. <code>corr(xs, ys)</code> 는 −1~1 사이 값을 돌려주고, 어느 한쪽의 <b>표준편차가 0이면</b> 정의되지 않으므로 <code>null</code> 입니다.",
  src:"function corr(xs, ys) {\n  // TODO: 공분산 / (표준편차 곱)\n  return 0;\n}",
  sol:"function corr(xs, ys) {\n  const n = xs.length;\n  if (n < 2 || ys.length !== n) return null;\n  const mx = xs.reduce((a, b) => a + b, 0) / n;\n  const my = ys.reduce((a, b) => a + b, 0) / n;\n  let cov = 0;\n  let vx = 0;\n  let vy = 0;\n  for (let i = 0; i < n; i++) {\n    const dx = xs[i] - mx;\n    const dy = ys[i] - my;\n    cov += dx * dy;\n    vx += dx * dx;\n    vy += dy * dy;\n  }\n  if (vx === 0 || vy === 0) return null;\n  return cov / Math.sqrt(vx * vy);\n}",
  tests:[["corr([1,2,3],[2,4,6])","1"],
         ["corr([1,2,3],[6,4,2])","-1"],
         ["Math.abs(corr([1,2,3,4],[1,3,2,4])-0.8)<1e-9","true"],
         ["corr([1,1,1],[1,2,3])","null"]],
  edge:[["corr([1],[1])","null"],
        ["Math.abs(corr([1,2,3,4,5],[2,4,6,8,10])-1)<1e-12","true"]],
  ex:"🎯 상관계수는 <b>선형 관계의 강도</b>만 잽니다. 완벽한 곡선 관계(y = x²)도 상관계수가 0에 가까울 수 있으므로, 값이 낮다고 '관계가 없다' 고 결론 내면 안 됩니다.\n⚠️ <b>상관은 인과가 아닙니다</b>. 아이스크림 판매와 익사 사고는 강한 상관이 있지만 원인은 '여름' 이라는 제3의 변수입니다.\n💡 한쪽이 <b>상수면 정의되지 않습니다</b> — 분모가 0이 됩니다. 0을 돌려주면 '관계 없음' 으로 읽히는데, 사실은 '잴 수 없음' 이라 완전히 다른 뜻입니다.\n🔧 상관계수는 이상치에 아주 민감합니다. 점 하나가 0.2 를 0.9 로 만들 수 있으므로 <b>산점도를 반드시 함께</b> 보세요 — 앤스컴의 4중주가 이걸 보여 주는 고전적인 예입니다." },

{ track:"stat", k:"큰 수의 법칙", cat:"internals",
  q:"주사위를 n번 던진 평균이 기댓값 3.5 에 가까워지는지 확인하세요. 결정적으로 하기 위해 <b>1,2,3,4,5,6 을 순환</b>하며 던집니다. <code>runMean(n)</code> 은 n번 던진 평균을, <code>within(n, tol)</code> 은 3.5 와의 오차가 tol 이하인지 돌려줍니다.",
  src:"function roll(i) {\n  return (i % 6) + 1;\n}\n\nfunction runMean(n) {\n  // TODO\n  return 0;\n}\n\nfunction within(n, tol) {\n  return Math.abs(runMean(n) - 3.5) <= tol;\n}",
  sol:"function roll(i) {\n  return (i % 6) + 1;\n}\n\nfunction runMean(n) {\n  if (n <= 0) return null;\n  let s = 0;\n  for (let i = 0; i < n; i++) s += roll(i);\n  return s / n;\n}\n\nfunction within(n, tol) {\n  return Math.abs(runMean(n) - 3.5) <= tol;\n}",
  tests:[["runMean(6)","3.5"],
         ["runMean(1)","1"],
         ["within(60,0.01)","true"],
         ["within(1,0.01)","false"]],
  edge:[["runMean(0)","null"],
        ["within(600,0.005)","true"]],
  ex:"🎯 큰 수의 법칙은 '<b>시행이 늘면 표본 평균이 기댓값에 수렴한다</b>' 는 것입니다. 다만 수렴은 <b>보장</b>이지 <b>속도</b>가 아닙니다 — 오차는 대략 1/√n 로 줄어들므로 정확도를 10배 높이려면 시행을 100배 해야 합니다.\n⚠️ 흔한 오해가 '<b>도박사의 오류</b>' 입니다. 앞면이 연속 5번 나왔다고 뒷면이 나올 차례가 아닙니다 — 주사위는 과거를 기억하지 않고, 평균이 수렴하는 것은 <b>초기 편차가 희석되기</b> 때문이지 반대 결과가 보상해 주기 때문이 아닙니다.\n💡 그래서 <code>runMean(1) = 1</code> 처럼 작은 n 에서는 기댓값과 한참 멀 수 있습니다. A/B 테스트에서 표본이 적을 때 결론을 내면 안 되는 이유가 이것입니다.\n🔧 이 문항은 결정적으로 만들려고 순환 주사위를 썼습니다 — 실제 무작위였다면 같은 코드가 매번 다른 결과를 내 채점할 수 없습니다." },

/* ───────────── mleval ───────────── */
{ track:"mleval", k:"혼동행렬과 정밀도·재현율", cat:"internals",
  q:"이진 분류 결과로 <b>정밀도·재현율·F1</b> 을 구하세요. <code>metrics(y, p)</code> 에서 <code>y</code> 는 정답, <code>p</code> 는 예측(0/1)입니다. <b>분모가 0이면 해당 지표는 null</b> 입니다.",
  src:"function metrics(y, p) {\n  // TODO: tp/fp/fn 을 세고 precision·recall·f1\n  return { precision: null, recall: null, f1: null };\n}",
  sol:"function metrics(y, p) {\n  let tp = 0;\n  let fp = 0;\n  let fn = 0;\n  y.forEach((t, i) => {\n    if (p[i] === 1 && t === 1) tp++;\n    else if (p[i] === 1) fp++;\n    else if (t === 1) fn++;\n  });\n  const precision = tp + fp ? tp / (tp + fp) : null;\n  const recall = tp + fn ? tp / (tp + fn) : null;\n  const f1 = precision && recall ? (2 * precision * recall) / (precision + recall) : null;\n  return { precision, recall, f1 };\n}",
  tests:[["metrics([1,1,0,0],[1,0,1,0])","{precision:0.5,recall:0.5,f1:0.5}"],
         ["metrics([1,1,1,1],[1,1,1,1])","{precision:1,recall:1,f1:1}"],
         ["metrics([1,0],[0,0]).precision","null"],
         ["metrics([1,1,0],[1,1,1]).recall","1"]],
  edge:[["metrics([0,0],[0,0])","{precision:null,recall:null,f1:null}"],
        ["Math.abs(metrics([1,1,0],[1,1,1]).f1-0.8)<1e-9","true"]],
  ex:"🎯 <b>정밀도</b>는 '골라낸 것 중 맞은 비율', <b>재현율</b>은 '실제 양성 중 찾아낸 비율' 입니다. 분모가 다르므로 서로 다른 질문에 답합니다.\n💡 둘은 대개 <b>맞바꿈 관계</b>입니다. 임계값을 낮추면 더 많이 양성으로 판정해 재현율이 오르고 정밀도가 떨어집니다 — 어느 쪽이 중요한지는 도메인이 정합니다. 암 검진은 재현율(놓치면 큰일), 스팸 필터는 정밀도(정상 메일을 지우면 큰일)입니다.\n⚠️ 아무것도 양성으로 예측하지 않으면 정밀도의 <b>분모가 0</b>입니다. 이걸 0으로 처리하면 '정밀도 0인 모델' 로 보이지만 사실은 '잴 수 없음' 입니다.\n🔧 F1 은 둘의 조화평균이라 <b>한쪽이 낮으면 크게 떨어집니다</b>. 산술평균이었다면 정밀도 1.0·재현율 0.0 인 쓸모없는 모델이 0.5 를 받습니다." },

{ track:"mleval", k:"불균형 데이터에서 정확도의 함정", cat:"internals",
  q:"양성이 <b>1%</b> 인 데이터에서 '<b>전부 음성</b>' 이라고 찍는 모델의 정확도·재현율을 계산하세요. <code>evaluate(y, p)</code> 는 <code>{accuracy, recall}</code> 을 돌려주고, <code>allNegative(n)</code> 은 길이 n 의 0 배열을 만듭니다.",
  src:"function makeY(n, positives) {\n  return Array.from({ length: n }, (_, i) => (i < positives ? 1 : 0));\n}\n\nfunction allNegative(n) {\n  // TODO\n  return [];\n}\n\nfunction evaluate(y, p) {\n  // TODO: accuracy 와 recall\n  return { accuracy: 0, recall: null };\n}",
  sol:"function makeY(n, positives) {\n  return Array.from({ length: n }, (_, i) => (i < positives ? 1 : 0));\n}\n\nfunction allNegative(n) {\n  return new Array(n).fill(0);\n}\n\nfunction evaluate(y, p) {\n  const hit = y.filter((t, i) => t === p[i]).length;\n  const pos = y.filter((t) => t === 1).length;\n  const tp = y.filter((t, i) => t === 1 && p[i] === 1).length;\n  return { accuracy: hit / y.length, recall: pos ? tp / pos : null };\n}",
  tests:[["evaluate(makeY(100,1), allNegative(100)).accuracy","0.99"],
         ["evaluate(makeY(100,1), allNegative(100)).recall","0"],
         ["evaluate(makeY(10,5), allNegative(10)).accuracy","0.5"],
         ["allNegative(3)","[0,0,0]"]],
  edge:[["evaluate(makeY(100,0), allNegative(100)).recall","null"],
        ["evaluate(makeY(4,2),[1,1,0,0]).accuracy","1"]],
  ex:"🎯 정확도 <b>99%</b> 인데 <b>재현율 0%</b> — 아무것도 못 잡는 모델이 훌륭해 보입니다. 불균형 데이터에서 정확도가 무의미한 이유가 이것입니다.\n💡 사기 탐지·질병 진단·이상 감지는 대부분 양성이 1% 미만입니다. 이런 문제에서 정확도를 보고하는 리포트는 <b>거의 항상 잘못됐습니다</b>.\n🔧 대신 봐야 할 것은 재현율·정밀도·PR-AUC 입니다. ROC-AUC 도 불균형에서는 낙관적으로 보이는 경향이 있어, 양성이 아주 드물면 <b>PR 곡선</b>이 더 정직합니다.\n⚠️ 그리고 '전부 음성' 같은 <b>기준선 모델</b>을 항상 함께 측정하세요. 새 모델이 그것보다 나은지가 첫 번째 질문이고, 여기서 걸러지는 프로젝트가 생각보다 많습니다." },

{ track:"mleval", k:"k-겹 교차검증 분할", cat:"internals",
  q:"길이 <code>n</code> 인 데이터를 <code>k</code> 겹으로 나누세요. <code>folds(n, k)</code> 는 각 겹의 <b>테스트 인덱스 배열</b>을 돌려줍니다. 나누어떨어지지 않으면 <b>앞쪽 겹부터 하나씩 더</b> 가져가고, 모든 인덱스는 <b>정확히 한 번씩</b> 테스트에 쓰여야 합니다.",
  src:"function folds(n, k) {\n  // TODO: 겹마다 테스트 인덱스\n  return [];\n}",
  sol:"function folds(n, k) {\n  const base = Math.floor(n / k);\n  const extra = n % k;\n  const out = [];\n  let at = 0;\n  for (let i = 0; i < k; i++) {\n    const size = base + (i < extra ? 1 : 0);\n    out.push(Array.from({ length: size }, (_, j) => at + j));\n    at += size;\n  }\n  return out;\n}",
  tests:[["folds(6,3)","[[0,1],[2,3],[4,5]]"],
         ["folds(7,3)","[[0,1,2],[3,4],[5,6]]"],
         ["folds(5,5)","[[0],[1],[2],[3],[4]]"],
         ["folds(7,3).reduce((a,f)=>a.concat(f),[]).sort((a,b)=>a-b)","[0,1,2,3,4,5,6]"]],
  edge:[["folds(2,3)","[[0],[1],[]]"],
        ["folds(6,3).every(f=>f.length===2)","true"]],
  ex:"🎯 교차검증의 핵심은 <b>모든 데이터가 정확히 한 번 테스트에 쓰이는</b> 것입니다. 겹치면 낙관적으로, 빠지면 일부 데이터가 평가에 안 쓰입니다 — 테스트 4가 그것을 검사합니다.\n💡 나누어떨어지지 않을 때 나머지를 <b>버리면</b> 데이터가 낭비되고, <b>한 겹에 몰면</b> 그 겹만 평가가 불안정해집니다. 앞쪽 겹부터 하나씩 나눠 갖는 것이 표준입니다.\n⚠️ 이 문항은 순서대로 잘랐지만 실제로는 <b>섞어야</b> 합니다. 데이터가 클래스나 시간순으로 정렬돼 있으면 한 겹에 특정 클래스만 들어갑니다 — 분류 문제에서는 클래스 비율을 유지하는 <b>층화(stratified)</b> 분할을 씁니다.\n🔧 시계열은 예외입니다. 미래로 과거를 예측하게 되므로 무작위 분할이 곧 누수이고, 시간 순서를 지키는 분할을 써야 합니다." },

{ track:"mleval", k:"임계값과 트레이드오프", cat:"internals",
  q:"확률 예측에 <b>임계값</b>을 적용해 지표가 어떻게 변하는지 보세요. <code>atThreshold(y, prob, t)</code> 는 <code>prob ≥ t</code> 를 양성으로 보고 <code>{precision, recall}</code> 을 돌려줍니다.",
  src:"function atThreshold(y, prob, t) {\n  // TODO: 임계값 적용 후 정밀도·재현율\n  return { precision: null, recall: null };\n}",
  sol:"function atThreshold(y, prob, t) {\n  let tp = 0;\n  let fp = 0;\n  let fn = 0;\n  y.forEach((truth, i) => {\n    const pred = prob[i] >= t ? 1 : 0;\n    if (pred === 1 && truth === 1) tp++;\n    else if (pred === 1) fp++;\n    else if (truth === 1) fn++;\n  });\n  return {\n    precision: tp + fp ? tp / (tp + fp) : null,\n    recall: tp + fn ? tp / (tp + fn) : null,\n  };\n}",
  tests:[["atThreshold([1,1,0,0],[0.9,0.6,0.4,0.1],0.5)","{precision:1,recall:1}"],
         ["atThreshold([1,1,0,0],[0.9,0.6,0.4,0.1],0.95).recall","0"],
         ["atThreshold([1,1,0,0],[0.9,0.6,0.4,0.1],0.05)","{precision:0.5,recall:1}"],
         ["atThreshold([1,1,0,0],[0.9,0.6,0.4,0.1],0.95).precision","null"]],
  edge:[["atThreshold([1,0],[0.5,0.5],0.5)","{precision:0.5,recall:1}"],
        ["atThreshold([0,0],[0.1,0.2],0.5).recall","null"]],
  ex:"🎯 분류 모델이 실제로 내놓는 것은 <b>확률</b>이고, 0/1 판정은 <b>임계값을 정한 뒤</b>에야 생깁니다. 기본값 0.5 는 관행일 뿐 최적이 아닙니다.\n💡 임계값을 <b>낮추면</b> 더 많이 양성으로 판정해 재현율이 오르고 정밀도가 떨어집니다. 테스트 2·3 이 그 양극단입니다 — 0.95 에서는 아무것도 못 잡고, 0.05 에서는 다 잡지만 절반이 오탐입니다.\n🔧 그래서 '모델 성능' 을 하나의 숫자로 말하면 불완전합니다. ROC·PR 곡선은 <b>모든 임계값에서의 성능</b>을 한눈에 보여 주고, 실제 임계값은 오탐과 미탐의 비용을 따져 정합니다.\n⚠️ 불균형 데이터에서 0.5 를 그대로 쓰면 모델이 거의 아무것도 양성으로 예측하지 않습니다 — 임계값 조정만으로 쓸모가 크게 달라집니다." },

/* ───────────── ml ───────────── */
{ track:"ml", k:"경사하강 한 걸음", cat:"internals",
  q:"단순 선형회귀 <code>y = w·x + b</code> 의 <b>MSE 손실</b>에 대해 경사하강 한 스텝을 구현하세요. <code>step(w, b, xs, ys, lr)</code> 는 갱신된 <code>[w, b]</code> 를 돌려줍니다. 손실은 <code>mean((wx+b−y)²)</code> 입니다.",
  src:"function step(w, b, xs, ys, lr) {\n  // TODO: 기울기를 구해 w, b 를 갱신\n  return [w, b];\n}",
  sol:"function step(w, b, xs, ys, lr) {\n  const n = xs.length;\n  let gw = 0;\n  let gb = 0;\n  xs.forEach((x, i) => {\n    const err = w * x + b - ys[i];\n    gw += 2 * err * x;\n    gb += 2 * err;\n  });\n  return [w - (lr * gw) / n, b - (lr * gb) / n];\n}",
  tests:[["step(0,0,[1,2],[2,4],0.1)","[1,0.6000000000000001]"],
         ["step(2,0,[1,2],[2,4],0.1)","[2,0]"],
         ["step(0,0,[1],[1],0.5)","[1,1]"],
         ["step(1,0,[0],[0],0.1)","[1,0]"]],
  edge:[["step(0,0,[1,2],[2,4],0)","[0,0]"],
        ["(() => { const L=(w,b)=>[1,2].reduce((s,x,i)=>s+Math.pow(w*x+b-[2,4][i],2),0)/2; const [w,b]=step(0,0,[1,2],[2,4],0.1); return L(w,b) < L(0,0); })()","true"]],
  ex:"🎯 경사하강은 '<b>손실이 줄어드는 방향으로 조금 이동</b>' 을 반복합니다. 기울기는 손실이 <b>커지는</b> 방향이므로 빼야 합니다 — 부호를 잘못 쓰면 손실이 발산합니다.\n💡 이미 정답인 지점(<code>w=2, b=0</code>)에서는 오차가 0이라 기울기도 0이고 <b>제자리에 머뭅니다</b>. 테스트 2가 그것을 확인합니다 — 수렴한 뒤에도 움직인다면 구현이 틀린 것입니다.\n⚠️ <code>2/n</code> 계수를 빼먹어도 방향은 같아서 <b>학습은 됩니다</b>. 다만 실효 학습률이 달라지므로 논문의 하이퍼파라미터를 그대로 썼을 때 결과가 재현되지 않습니다.\n🔧 학습률이 너무 크면 골짜기를 건너뛰며 발산하고, 너무 작으면 영원히 안 끝납니다. 손실이 <b>줄지 않고 튄다면</b> 가장 먼저 학습률을 낮춰 보세요." },

{ track:"ml", k:"표준화와 데이터 누수", cat:"internals",
  q:"학습 데이터로 <b>평균·표준편차를 구해</b> 학습·테스트를 모두 변환하세요. <code>fit(train)</code> 은 <code>{mean, std}</code> 를, <code>apply(xs, p)</code> 는 변환된 배열을 돌려줍니다. <b>테스트 데이터로 다시 fit 하면 안 됩니다</b>.",
  src:"function fit(train) {\n  // TODO: 평균·표준편차\n  return { mean: 0, std: 1 };\n}\n\nfunction apply(xs, p) {\n  // TODO: (x - mean) / std\n  return xs.slice();\n}",
  sol:"function fit(train) {\n  const n = train.length;\n  const mean = train.reduce((a, b) => a + b, 0) / n;\n  const v = train.reduce((a, b) => a + (b - mean) * (b - mean), 0) / n;\n  const std = Math.sqrt(v);\n  return { mean, std: std === 0 ? 1 : std };\n}\n\nfunction apply(xs, p) {\n  return xs.map((x) => (x - p.mean) / p.std);\n}",
  tests:[["fit([1,2,3]).mean","2"],
         ["apply([1,2,3], fit([1,2,3]))[1]","0"],
         ["(() => { const p=fit([1,2,3]); return apply([4], p)[0] > apply([3], p)[0]; })()","true"],
         ["fit([5,5,5]).std","1"]],
  edge:[["apply([], fit([1,2,3]))","[]"],
        ["(() => { const p=fit([0,10]); return apply([5], p)[0]; })()","0"]],
  ex:"🎯 전처리 파라미터는 <b>학습 데이터에서만</b> 구해야 합니다. 전체 데이터로 평균을 내면 테스트 정보가 학습에 새어 들어가(<b>데이터 누수</b>) 성능이 실제보다 좋게 나옵니다.\n⚠️ 이 누수는 <b>발견하기 어렵습니다</b> — 오류가 나지 않고 검증 점수도 좋아 보이며, 실제 서비스에 올린 뒤에야 성능이 무너집니다.\n💡 테스트 3이 중요한 성질을 확인합니다. 학습 때 못 본 값(4)도 <b>같은 파라미터로</b> 변환되어야 순서가 보존됩니다. 테스트마다 다시 fit 하면 같은 값이 상황에 따라 다르게 변환됩니다.\n🔧 표준편차가 0인 상수 특성은 <b>0으로 나눔</b>이 됩니다. 1로 대체하거나 그 특성을 아예 버려야 하고, 상수 특성은 예측에 기여하지 않으므로 버리는 편이 낫습니다." },

{ track:"ml", k:"학습·검증 분할과 시계열", cat:"internals",
  q:"데이터를 학습·테스트로 나누세요. <code>splitRandom(n, ratio)</code> 는 앞 <code>ratio</code> 만큼을 학습으로(결정적), <code>splitTime(times, cut)</code> 는 <b>cut 이전을 학습, 이후를 테스트</b>로 나눕니다. 각각 <code>{train, test}</code> 인덱스 배열입니다.",
  src:"function splitRandom(n, ratio) {\n  // TODO: 앞 ratio 를 학습\n  return { train: [], test: [] };\n}\n\nfunction splitTime(times, cut) {\n  // TODO: 시각 기준 분할\n  return { train: [], test: [] };\n}",
  sol:"function splitRandom(n, ratio) {\n  const k = Math.floor(n * ratio);\n  const all = Array.from({ length: n }, (_, i) => i);\n  return { train: all.slice(0, k), test: all.slice(k) };\n}\n\nfunction splitTime(times, cut) {\n  const train = [];\n  const test = [];\n  times.forEach((t, i) => (t < cut ? train : test).push(i));\n  return { train, test };\n}",
  tests:[["splitRandom(10,0.8).train.length","8"],
         ["splitRandom(10,0.8).test","[8,9]"],
         ["splitTime([1,2,3,4],3)","{train:[0,1],test:[2,3]}"],
         ["splitTime([5,1,3],3).train","[1]"]],
  edge:[["splitRandom(0,0.8)","{train:[],test:[]}"],
        ["splitTime([1,2],10)","{train:[0,1],test:[]}"]],
  ex:"🎯 시계열에서 <b>무작위 분할은 곧 누수</b>입니다. 미래 데이터로 학습해 과거를 예측하게 되므로 검증 점수가 비현실적으로 좋아지고, 실제 서비스에서는 그 성능이 안 나옵니다.\n💡 시각 기준 분할은 <b>실제 사용 조건</b>을 흉내 냅니다 — 우리는 항상 '지금까지의 데이터로 앞을 예측' 하기 때문입니다.\n⚠️ 시계열이 아니어도 무작위 분할이 위험할 때가 있습니다. 같은 사용자의 여러 행이 학습과 테스트에 <b>나뉘어 들어가면</b> 모델이 그 사용자를 외워 버립니다 — 그룹 단위로 나눠야 합니다.\n🔧 이 문항의 <code>splitRandom</code> 은 채점을 위해 결정적으로 만들었습니다. 실제로는 섞되 <b>시드를 고정</b>해야 실험이 재현됩니다." },

{ track:"ml", k:"과적합의 신호", cat:"internals",
  q:"에포크별 학습·검증 손실이 주어집니다. <b>검증 손실이 최소가 된 뒤 patience 번 연속 나아지지 않으면</b> 멈추는 조기 종료를 구현하세요. <code>earlyStop(valLoss, patience)</code> 는 <b>멈추는 에포크 인덱스</b>를(안 멈추면 -1) 돌려줍니다.",
  src:"function earlyStop(valLoss, patience) {\n  // TODO: 최고 기록 뒤 patience 번 개선 없으면 중단\n  return -1;\n}",
  sol:"function earlyStop(valLoss, patience) {\n  let best = Infinity;\n  let wait = 0;\n  for (let i = 0; i < valLoss.length; i++) {\n    if (valLoss[i] < best) { best = valLoss[i]; wait = 0; continue; }\n    wait += 1;\n    if (wait >= patience) return i;\n  }\n  return -1;\n}",
  tests:[["earlyStop([1.0,0.8,0.6,0.7,0.75],2)","4"],
         ["earlyStop([1.0,0.8,0.6,0.5,0.4],2)","-1"],
         ["earlyStop([1.0,1.1,1.2],2)","2"],
         ["earlyStop([1.0,0.9,1.0,0.8,0.9,1.0],2)","5"]],
  edge:[["earlyStop([],2)","-1"],
        ["earlyStop([1.0,1.1],1)","1"]],
  ex:"🎯 과적합은 <b>학습 손실은 계속 줄어드는데 검증 손실이 올라가기 시작하는</b> 지점에서 드러납니다. 모델이 일반적인 규칙 대신 학습 데이터의 잡음을 외우기 시작한 것입니다.\n🔧 조기 종료는 가장 값싼 정규화입니다 — 하이퍼파라미터 하나(patience)만 정하면 되고, 학습 시간까지 줄여 줍니다.\n💡 <b>patience 가 필요한 이유</b>는 검증 손실이 매끄럽게 움직이지 않기 때문입니다. 한 번 올랐다고 멈추면 잡음에 속아 너무 일찍 끝냅니다 — 테스트 4가 오르내리는 경우를 검사합니다.\n⚠️ 조기 종료 시점을 <b>테스트 세트로 고르면</b> 그 자체가 누수입니다. 검증 세트로 멈추고, 최종 성능은 건드리지 않은 테스트 세트로 한 번만 재야 합니다." },

/* ───────────── dl ───────────── */
{ track:"dl", k:"소프트맥스와 수치 안정성", cat:"internals",
  q:"<b>소프트맥스</b>를 구현하세요. 큰 값에서 <code>exp</code> 가 넘치지 않도록 <b>최댓값을 빼고</b> 계산해야 합니다. <code>softmax(xs)</code> 는 합이 1인 확률 배열을 돌려줍니다.",
  src:"function softmax(xs) {\n  // TODO: 최댓값을 빼고 exp — 그냥 exp 하면 큰 값에서 넘친다\n  return xs.map(() => 0);\n}",
  sol:"function softmax(xs) {\n  const m = Math.max(...xs);\n  const ex = xs.map((x) => Math.exp(x - m));\n  const s = ex.reduce((a, b) => a + b, 0);\n  return ex.map((v) => v / s);\n}",
  tests:[["softmax([0,0])","[0.5,0.5]"],
         ["Math.abs(softmax([1,2,3]).reduce((a,b)=>a+b,0)-1)<1e-12","true"],
         ["softmax([1000,1000]).every(v=>Number.isFinite(v))","true"],
         ["softmax([1000,1000])","[0.5,0.5]"]],
  edge:[["softmax([5])","[1]"],
        ["softmax([0,1])[1]>softmax([0,1])[0]","true"]],
  ex:"🎯 소프트맥스에서 <b>최댓값을 빼도 결과가 같습니다</b>. 분자와 분모에 같은 상수 <code>e^(-m)</code> 이 곱해져 약분되기 때문입니다 — 수학적으로 동일하고 수치적으로만 안전해집니다.\n⚠️ 빼지 않으면 <code>exp(1000)</code> 이 <code>Infinity</code> 가 되고 <code>Infinity/Infinity = NaN</code> 이 됩니다. 테스트 3이 정확히 그 상황이라, 순진한 구현은 여기서 무너집니다.\n💡 이런 <b>수학적으로는 같지만 수치적으로 다른</b> 변형이 딥러닝 구현 곳곳에 있습니다. log-sum-exp, 크로스엔트로피의 log-softmax 결합, 배치 정규화의 엡실론이 모두 같은 이유입니다.\n🔧 그래서 프레임워크는 <code>softmax</code> 뒤에 <code>log</code> 를 따로 취하지 말고 <b>log_softmax</b> 를 쓰라고 안내합니다 — 두 연산을 합치면 정밀도 손실이 줄어듭니다." },

{ track:"dl", k:"크로스엔트로피 손실", cat:"internals",
  q:"다중 분류의 <b>크로스엔트로피</b>를 구현하세요. <code>ce(probs, label)</code> 는 <code>−log(probs[label])</code> 이고, 확률이 0이면 <code>−log(0) = ∞</code> 이므로 <b>아주 작은 값으로 클리핑</b>해야 합니다(1e-12).",
  src:"function ce(probs, label) {\n  // TODO: 클리핑 후 -log\n  return 0;\n}\n\nfunction batchCE(batch, labels) {\n  // TODO: 평균 손실\n  return 0;\n}",
  sol:"const EPS = 1e-12;\n\nfunction ce(probs, label) {\n  return -Math.log(Math.max(probs[label], EPS));\n}\n\nfunction batchCE(batch, labels) {\n  if (!batch.length) return 0;\n  return batch.reduce((s, p, i) => s + ce(p, labels[i]), 0) / batch.length;\n}",
  tests:[["ce([1,0],0)","0"],
         ["Math.abs(ce([0.5,0.5],0)-Math.log(2))<1e-12","true"],
         ["Number.isFinite(ce([0,1],0))","true"],
         ["Math.abs(batchCE([[1,0],[0,1]],[0,1]))<1e-12","true"]],
  edge:[["batchCE([],[])","0"],
        ["ce([0,1],0)>25","true"]],
  ex:"🎯 크로스엔트로피는 '<b>정답 클래스에 얼마나 확신했는가</b>' 만 봅니다. 정답에 1.0 을 주면 손실 0, 0.5 를 주면 log 2 ≈ 0.69 입니다.\n⚠️ 정답 확률이 <b>정확히 0</b>이면 손실이 무한대가 되어 학습 전체가 NaN 으로 오염됩니다. 클리핑이 그걸 막고, 테스트 3이 그 상황을 검사합니다.\n💡 이 손실이 정확도보다 나은 점은 <b>확신의 정도까지</b> 벌한다는 것입니다. 틀린 답에 0.51 로 확신한 모델과 0.99 로 확신한 모델은 정확도가 같지만 손실은 크게 다릅니다.\n🔧 실무에서는 소프트맥스와 크로스엔트로피를 <b>합친 함수</b>를 씁니다(<code>cross_entropy</code>). 따로 계산하면 log(exp(...)) 에서 정밀도가 손실되고, 합치면 수식이 정리되어 안정적입니다." },

{ track:"dl", k:"ReLU 와 기울기 소실", cat:"internals",
  q:"<b>시그모이드</b>와 <b>ReLU</b> 의 미분을 구현하고, 층을 <code>n</code> 개 쌓았을 때 기울기가 어떻게 되는지 계산하세요. <code>chain(gradFn, x, n)</code> 은 같은 지점에서 미분값을 <code>n</code> 번 곱한 값을 돌려줍니다.",
  src:"function dSigmoid(x) {\n  // TODO: s(1-s)\n  return 0;\n}\n\nfunction dRelu(x) {\n  // TODO: x>0 이면 1, 아니면 0\n  return 0;\n}\n\nfunction chain(gradFn, x, n) {\n  // TODO: 미분값을 n 번 곱한다\n  return 1;\n}",
  sol:"function dSigmoid(x) {\n  const s = 1 / (1 + Math.exp(-x));\n  return s * (1 - s);\n}\n\nfunction dRelu(x) {\n  return x > 0 ? 1 : 0;\n}\n\nfunction chain(gradFn, x, n) {\n  return Math.pow(gradFn(x), n);\n}",
  tests:[["dSigmoid(0)","0.25"],
         ["dRelu(3)","1"],
         ["dRelu(-3)","0"],
         ["chain(dSigmoid,0,10)<1e-6","true"]],
  edge:[["chain(dRelu,3,50)","1"],
        ["chain(dRelu,-1,3)","0"]],
  ex:"🎯 역전파는 각 층의 미분을 <b>곱해 가며</b> 거슬러 올라갑니다. 그래서 층마다 1보다 작은 수를 곱하면 아래층에 도달할 즈음 기울기가 사라집니다.\n💡 시그모이드의 미분은 <b>최대가 0.25</b> 입니다(x=0에서). 10층만 쌓아도 0.25¹⁰ ≈ 1e-6 이라 아래층은 사실상 학습되지 않습니다 — 테스트 4가 그 계산입니다.\n🔧 ReLU 는 양수 구간에서 미분이 <b>정확히 1</b>이라 아무리 곱해도 줄지 않습니다. 깊은 망이 학습 가능해진 결정적 이유 중 하나입니다.\n⚠️ 대신 ReLU 는 음수 구간에서 미분이 0이라, 한 번 음수로 죽은 뉴런이 <b>영영 학습되지 않을</b> 수 있습니다(dying ReLU). Leaky ReLU 나 GELU 가 이 문제를 완화합니다." },

{ track:"dl", k:"파라미터 수 세기", cat:"internals",
  q:"완전연결 신경망의 <b>학습 파라미터 수</b>를 세세요. <code>dense(layers)</code> 는 층 크기 배열(<code>[입력, 은닉, ..., 출력]</code>)을 받아 <b>가중치 + 편향</b> 총합을 돌려줍니다. <code>conv(inC, outC, k)</code> 는 <code>k×k</code> 합성곱의 파라미터 수입니다.",
  src:"function dense(layers) {\n  // TODO: 각 층 사이의 (in*out + out)\n  return 0;\n}\n\nfunction conv(inC, outC, k) {\n  // TODO: 커널 + 편향\n  return 0;\n}",
  sol:"function dense(layers) {\n  let total = 0;\n  for (let i = 0; i + 1 < layers.length; i++) {\n    total += layers[i] * layers[i + 1] + layers[i + 1];\n  }\n  return total;\n}\n\nfunction conv(inC, outC, k) {\n  return inC * outC * k * k + outC;\n}",
  tests:[["dense([2,3,1])","13"],
         ["dense([784,128,10])","101770"],
         ["conv(3,64,3)","1792"],
         ["dense([10])","0"]],
  edge:[["conv(1,1,1)","2"],
        ["dense([1,1])","2"]],
  ex:"🎯 완전연결 층의 파라미터는 <code>입력 × 출력 + 출력</code> 입니다 — 가중치 행렬과 편향 벡터입니다. 편향을 빼먹는 것이 가장 흔한 계산 실수입니다.\n💡 숫자가 커지는 속도를 보세요. <code>784→128→10</code> 이 벌써 10만 개가 넘습니다. 이미지 크기를 두 배로 하면 입력 차원이 4배가 되고 파라미터도 그만큼 늘어납니다 — 완전연결로 이미지를 다루기 어려운 이유입니다.\n🔧 합성곱은 <b>커널을 모든 위치에서 공유</b>하므로 입력 크기와 무관하게 파라미터가 정해집니다. <code>conv(3,64,3)</code> 이 1,792개인데, 같은 일을 완전연결로 하면 수백만 개가 필요합니다.\n⚠️ 파라미터 수는 <b>메모리와 과적합 위험</b>의 대략적인 지표입니다. 다만 연산량(FLOPs)은 별개라, 파라미터가 적어도 느린 모델이 있습니다." },
];
