/* 실행형이 0이던 네 트랙(os·net·devops·sysd)에 실행 가능한 문항을 넣는다.
   이 영역의 지식은 대부분 '알고리즘' 이라 순수 함수로 정확히 표현되고 채점된다.
   앱의 testDoc 품질 규칙(var 금지 · 주석 뺀 28줄 이하 · console.log 금지)을 지킨다. */
module.exports = [
/* ───────────── OS ───────────── */
{ track:"os", k:"LRU 페이지 교체", cat:"internals",
  q:"프레임 <b>3개</b>짜리 메모리에서 <b>LRU</b>(가장 오래 안 쓴 것 교체) 정책으로 페이지를 관리하세요. <code>lru(pages, frames)</code> 는 <b>페이지 폴트 횟수</b>를 돌려줍니다. 이미 올라와 있는 페이지를 참조하면 '최근 사용' 으로 갱신됩니다.",
  src:"function lru(pages, frames) {\n  // TODO: 폴트 수를 세세요\n  return 0;\n}",
  sol:"function lru(pages, frames) {\n  const mem = [];\n  let faults = 0;\n  pages.forEach((p) => {\n    const i = mem.indexOf(p);\n    if (i >= 0) { mem.splice(i, 1); mem.push(p); return; }\n    faults++;\n    if (mem.length === frames) mem.shift();\n    mem.push(p);\n  });\n  return faults;\n}",
  tests:[["lru([1,2,3,1,2,4],3)","4"],
         ["lru([1,1,1,1],3)","1"],
         ["lru([1,2,3,4,1,2,5,1,2,3,4,5],3)","10"],
         ["lru([1,2,3],3)","3"]],
  edge:[["lru([],3)","0"],["lru([1,2,1,2],1)","4"]],
  ex:"🎯 LRU 는 '<b>과거에 오래 안 쓴 것은 앞으로도 안 쓸 것</b>' 이라는 지역성 가정에 기댑니다. 실제 프로그램의 참조는 시간적 지역성이 강해서 대부분 잘 맞습니다.\n💡 핵심은 <b>적중했을 때도 순서를 갱신</b>하는 것입니다. 이걸 빠뜨리면 FIFO 가 되어 버립니다 — 폴트 수가 달라지므로 테스트가 바로 잡아냅니다.\n⚠️ 진짜 LRU 는 <b>참조마다 순서를 갱신</b>해야 해서 하드웨어로 구현하기 비쌉니다. 그래서 실제 OS 는 참조 비트를 쓰는 clock(second-chance) 같은 근사 알고리즘을 씁니다.\n🔧 이 구조는 캐시에도 그대로 쓰입니다 — Map 의 삽입 순서를 이용하면 자바스크립트에서 O(1) LRU 를 만들 수 있습니다." },

{ track:"os", k:"벨레이디의 역설", cat:"internals",
  q:"<b>FIFO</b> 페이지 교체를 구현하고, 프레임을 <b>늘렸는데 폴트가 더 많아지는</b> 경우를 확인하세요. <code>fifo(pages, frames)</code> 는 폴트 횟수를 돌려줍니다.",
  src:"function fifo(pages, frames) {\n  // TODO: 들어온 순서대로 내보내는 FIFO\n  return 0;\n}",
  sol:"function fifo(pages, frames) {\n  const mem = [];\n  let faults = 0;\n  pages.forEach((p) => {\n    if (mem.indexOf(p) >= 0) return;\n    faults++;\n    if (mem.length === frames) mem.shift();\n    mem.push(p);\n  });\n  return faults;\n}",
  tests:[["fifo([1,2,3,4,1,2,5,1,2,3,4,5],3)","9"],
         ["fifo([1,2,3,4,1,2,5,1,2,3,4,5],4)","10"],
         ["fifo([1,1,1],3)","1"],
         ["fifo([1,2,3,1,2,3],3)","3"]],
  edge:[["fifo([],5)","0"],["fifo([1,2,1,2],1)","4"]],
  ex:"🎯 테스트 1·2 를 보세요. 프레임을 3에서 4로 <b>늘렸는데 폴트가 9에서 10으로 늘었습니다</b> — 이것이 <b>벨레이디의 역설</b>(Belady's anomaly)입니다.\n💡 직관과 어긋나지만 FIFO 에서는 실제로 일어납니다. 자원을 늘리면 항상 나아진다는 가정이 <b>증명 없이 성립하지 않는다</b>는 좋은 예입니다.\n🔧 LRU 처럼 <b>스택 성질</b>을 가진 알고리즘에서는 이 현상이 없습니다 — 프레임 n 개일 때 메모리에 있는 페이지 집합이 n+1 개일 때의 부분집합이기 때문입니다.\n⚠️ 그래서 '메모리를 늘렸는데 더 느려졌다' 는 보고를 무시하면 안 됩니다. 캐시 정책에 따라 실제로 가능한 일입니다." },

{ track:"os", k:"라운드로빈 스케줄링", cat:"internals",
  q:"<b>라운드로빈</b> 스케줄러를 구현하세요. 모든 프로세스가 시각 0에 도착하고 타임 퀀텀은 <code>q</code> 입니다. <code>rr(burst, q)</code> 는 각 프로세스의 <b>완료 시각 배열</b>을 돌려줍니다(입력 순서 그대로).",
  src:"function rr(burst, q) {\n  // TODO: 큐를 돌며 q 만큼씩 실행\n  return burst.map(() => 0);\n}",
  sol:"function rr(burst, q) {\n  const left = burst.slice();\n  const done = burst.map(() => 0);\n  const queue = burst.map((_, i) => i);\n  let t = 0;\n  while (queue.length) {\n    const i = queue.shift();\n    const run = Math.min(q, left[i]);\n    t += run;\n    left[i] -= run;\n    if (left[i] === 0) done[i] = t;\n    else queue.push(i);\n  }\n  return done;\n}",
  tests:[["rr([5,3,1],2)","[9,8,5]"],
         ["rr([4,4],2)","[6,8]"],
         ["rr([3],5)","[3]"],
         ["rr([1,1,1],1)","[1,2,3]"]],
  edge:[["rr([],2)","[]"],["rr([10],3)","[10]"]],
  ex:"🎯 라운드로빈은 <b>공평성</b>을 위해 응답 시간을 희생합니다. 모든 프로세스가 번갈아 조금씩 진행되므로 짧은 작업도 끝까지 기다립니다.\n💡 <b>퀀텀 크기</b>가 성격을 정합니다. 너무 크면 FCFS 가 되어 짧은 작업이 긴 작업 뒤에 갇히고, 너무 작으면 문맥 교환 비용이 실행 시간을 잡아먹습니다.\n🔧 구현의 핵심은 '남은 시간이 0이 아니면 <b>큐 뒤로</b> 다시 넣는' 것입니다. 이때 큐에 다시 넣는 시점을 잘못 잡으면(예: 새로 도착한 프로세스보다 먼저) 순서가 달라집니다.\n⚠️ 실제 OS 는 순수 라운드로빈을 쓰지 않습니다. 우선순위와 대화형 여부를 반영한 다단계 큐(MLFQ)로 '짧고 대화형인 작업' 을 우대합니다." },

{ track:"os", k:"메모리 할당 전략", cat:"internals",
  q:"빈 공간 목록에서 요청 크기를 담을 블록을 고르는 <b>first-fit</b>(앞에서 처음 맞는 것)과 <b>best-fit</b>(남는 조각이 가장 작은 것)을 구현하세요. 각각 <b>고른 블록의 인덱스</b>를 돌려주고, 없으면 -1 입니다.",
  src:"function firstFit(holes, size) {\n  // TODO\n  return -1;\n}\n\nfunction bestFit(holes, size) {\n  // TODO\n  return -1;\n}",
  sol:"function firstFit(holes, size) {\n  return holes.findIndex((h) => h >= size);\n}\n\nfunction bestFit(holes, size) {\n  let best = -1;\n  holes.forEach((h, i) => {\n    if (h < size) return;\n    if (best < 0 || h < holes[best]) best = i;\n  });\n  return best;\n}",
  tests:[["firstFit([100,50,200],60)","0"],
         ["bestFit([100,50,200],60)","0"],
         ["firstFit([100,50,200],150)","2"],
         ["bestFit([300,120,200],110)","1"]],
  edge:[["firstFit([10,20],50)","-1"],["bestFit([],10)","-1"]],
  ex:"🎯 두 전략의 차이는 <b>외부 단편화</b>에서 드러납니다. first-fit 은 빠르지만 앞쪽에 작은 조각을 계속 남기고, best-fit 은 남는 조각을 최소화하려다 <b>쓸모없이 작은 조각</b>을 잔뜩 만듭니다.\n💡 측정 결과로는 first-fit 이 best-fit 보다 대체로 낫습니다 — 탐색이 훨씬 빠르고 단편화도 크게 나쁘지 않기 때문입니다. '더 똑똑해 보이는' 전략이 항상 이기지 않습니다.\n⚠️ 동점 처리가 중요합니다. best-fit 에서 같은 크기가 여러 개면 어느 것을 고를지 정해야 결과가 재현됩니다 — 이 문항은 '먼저 나온 것' 입니다.\n🔧 현대 할당기는 크기별 자유 목록(segregated free list)이나 buddy system 으로 탐색 자체를 없앱니다." },

{ track:"os", k:"가상 주소 변환", cat:"internals",
  q:"페이지 크기가 <b>4096바이트</b>인 시스템에서 가상 주소를 <b>페이지 번호와 오프셋</b>으로 나누고, 페이지 테이블로 물리 주소를 계산하세요. 테이블에 없는 페이지는 <code>-1</code>(페이지 폴트)입니다.",
  src:"const PAGE = 4096;\n\nfunction split(addr) {\n  // TODO: [페이지번호, 오프셋]\n  return [0, 0];\n}\n\nfunction translate(addr, table) {\n  // TODO: table[페이지번호] 가 프레임 번호. 없으면 -1\n  return -1;\n}",
  sol:"const PAGE = 4096;\n\nfunction split(addr) {\n  return [Math.floor(addr / PAGE), addr % PAGE];\n}\n\nfunction translate(addr, table) {\n  const [page, off] = split(addr);\n  const frame = table[page];\n  if (frame === undefined) return -1;\n  return frame * PAGE + off;\n}",
  tests:[["split(4096)","[1,0]"],
         ["split(5000)","[1,904]"],
         ["translate(5000,{1:3})","13192"],
         ["translate(5000,{0:3})","-1"]],
  edge:[["split(0)","[0,0]"],["translate(0,{0:0})","0"]],
  ex:"🎯 페이지 크기가 <b>2의 거듭제곱</b>인 이유가 여기 있습니다. 4096 = 2¹² 이므로 하위 12비트가 그대로 오프셋이고 나머지가 페이지 번호입니다 — 나눗셈이 아니라 <b>비트 자르기</b>로 끝납니다.\n💡 그래서 실제 구현은 <code>addr &gt;&gt; 12</code> 와 <code>addr &amp; 0xFFF</code> 입니다. 이 문항은 읽기 쉽게 나눗셈으로 썼지만 하드웨어에서는 배선 하나로 처리됩니다.\n⚠️ 매핑이 없으면 <b>페이지 폴트</b>입니다 — 오류가 아니라 정상적인 신호로, OS 가 디스크에서 페이지를 올리고 명령을 다시 실행합니다.\n🔧 페이지 테이블을 매번 읽으면 메모리 접근이 두 배가 되므로, <b>TLB</b>(변환 캐시)가 최근 변환을 들고 있습니다. TLB 적중률이 성능을 크게 좌우합니다." },

{ track:"os", k:"세마포어와 임계 구역", cat:"internals",
  q:"카운팅 세마포어를 모델링하세요. <code>make(n)</code> 은 초기값 n 의 세마포어를 만들고, <code>acquire(s, id)</code> 는 자원을 얻거나(<code>true</code>) 대기열에 넣고(<code>false</code>), <code>release(s)</code> 는 반납하며 대기자가 있으면 <b>먼저 기다린 순서로</b> 깨웁니다. <code>release</code> 는 깨운 id 또는 <code>null</code> 을 돌려줍니다.",
  src:"function make(n) {\n  return { count: n, waiting: [] };\n}\n\nfunction acquire(s, id) {\n  // TODO\n  return false;\n}\n\nfunction release(s) {\n  // TODO\n  return null;\n}",
  sol:"function make(n) {\n  return { count: n, waiting: [] };\n}\n\nfunction acquire(s, id) {\n  if (s.count > 0) { s.count -= 1; return true; }\n  s.waiting.push(id);\n  return false;\n}\n\nfunction release(s) {\n  if (s.waiting.length) return s.waiting.shift();\n  s.count += 1;\n  return null;\n}",
  tests:[["(() => { const s = make(2); return [acquire(s,'a'), acquire(s,'b'), acquire(s,'c')]; })()","[true,true,false]"],
         ["(() => { const s = make(1); acquire(s,'a'); acquire(s,'b'); return release(s); })()","'b'"],
         ["(() => { const s = make(1); acquire(s,'a'); return release(s); })()","null"],
         ["(() => { const s = make(1); acquire(s,'a'); acquire(s,'b'); acquire(s,'c'); return [release(s), release(s)]; })()","['b','c']"]],
  edge:[["(() => { const s = make(0); return acquire(s,'a'); })()","false"],
        ["(() => { const s = make(1); acquire(s,'a'); release(s); return s.count; })()","1"]],
  ex:"🎯 세마포어의 핵심은 <b>반납할 때 대기자가 있으면 카운트를 올리지 않는</b> 것입니다. 올려 버리면 깨운 대기자와 새로 온 요청이 같은 자원을 두고 다시 경쟁합니다.\n💡 대기 순서를 <b>FIFO</b> 로 하면 굶주림(starvation)이 없습니다. 순서를 정하지 않으면 운 나쁜 스레드가 영원히 못 들어갈 수 있습니다.\n⚠️ 실제 세마포어에서 어려운 부분은 이 로직이 아니라 <b>원자성</b>입니다. count 확인과 감소 사이에 다른 스레드가 끼어들면 두 스레드가 동시에 들어가므로, 하드웨어 원자 명령이나 커널 지원이 필요합니다.\n🔧 초기값 1인 세마포어가 뮤텍스와 비슷하지만 같지는 않습니다 — 뮤텍스는 <b>잠근 스레드만 풀 수</b> 있고, 세마포어는 누구나 반납할 수 있습니다." },

/* ───────────── NET ───────────── */
{ track:"net", k:"CIDR 대역 계산", cat:"internals",
  q:"CIDR 표기(<code>192.168.1.0/24</code>)를 받아 <b>네트워크 주소·브로드캐스트 주소·사용 가능한 호스트 수</b>를 계산하세요. <code>cidr(s)</code> 는 <code>{network, broadcast, hosts}</code> 를 돌려줍니다(주소는 점 표기 문자열).",
  src:"function toInt(ip) {\n  return ip.split('.').reduce((a, b) => a * 256 + Number(b), 0);\n}\n\nfunction toIp(n) {\n  return [24, 16, 8, 0].map((s) => (n >>> s) & 255).join('.');\n}\n\nfunction cidr(s) {\n  // TODO: 네트워크·브로드캐스트·호스트 수\n  return { network: '', broadcast: '', hosts: 0 };\n}",
  sol:"function toInt(ip) {\n  return ip.split('.').reduce((a, b) => a * 256 + Number(b), 0);\n}\n\nfunction toIp(n) {\n  return [24, 16, 8, 0].map((s) => (n >>> s) & 255).join('.');\n}\n\nfunction cidr(s) {\n  const [ip, bitsRaw] = s.split('/');\n  const bits = Number(bitsRaw);\n  const mask = bits === 0 ? 0 : (0xffffffff << (32 - bits)) >>> 0;\n  const net = (toInt(ip) & mask) >>> 0;\n  const bc = (net | (~mask >>> 0)) >>> 0;\n  const size = Math.pow(2, 32 - bits);\n  return { network: toIp(net), broadcast: toIp(bc), hosts: size > 2 ? size - 2 : 0 };\n}",
  tests:[["cidr('192.168.1.10/24').network","'192.168.1.0'"],
         ["cidr('192.168.1.10/24').broadcast","'192.168.1.255'"],
         ["cidr('192.168.1.10/24').hosts","254"],
         ["cidr('10.0.0.0/8').broadcast","'10.255.255.255'"]],
  edge:[["cidr('192.168.1.5/31').hosts","0"],
        ["cidr('172.16.5.130/26').network","'172.16.5.128'"]],
  ex:"🎯 CIDR 의 <code>/24</code> 는 '<b>앞 24비트가 네트워크</b>' 라는 뜻입니다. 마스크를 AND 하면 네트워크 주소, 마스크의 반전을 OR 하면 브로드캐스트가 나옵니다.\n💡 사용 가능한 호스트가 <b>2개 적은</b> 이유는 네트워크 주소(모두 0)와 브로드캐스트(모두 1)를 쓸 수 없기 때문입니다. <code>/31</code> 은 주소가 2개뿐이라 호스트가 0이고, 점대점 링크에서만 특수하게 씁니다.\n⚠️ 자바스크립트의 비트 연산은 <b>부호 있는 32비트</b>라 <code>&gt;&gt;&gt; 0</code> 로 부호 없는 값으로 되돌려야 합니다 — 빼먹으면 <code>10.0.0.0/8</code> 같은 큰 주소에서 음수가 나옵니다.\n🔧 이 계산은 방화벽 규칙·라우팅·VPC 서브넷 설계에서 매일 씁니다. <code>/26</code> 이 64개 주소라는 감각이 있으면 서브넷 쪼개기가 훨씬 빨라집니다." },

{ track:"net", k:"IP 가 대역에 속하는가", cat:"internals",
  q:"IP 가 여러 CIDR 대역 중 하나에 속하는지 판정하는 <code>inAny(ip, ranges)</code> 를 만드세요. 그리고 <b>가장 구체적인</b>(prefix 가 가장 긴) 대역을 고르는 <code>longest(ip, ranges)</code> 도 구현하세요 — 없으면 <code>null</code> 입니다.",
  src:"function toInt(ip) {\n  return ip.split('.').reduce((a, b) => a * 256 + Number(b), 0);\n}\n\nfunction inRange(ip, range) {\n  // TODO\n  return false;\n}\n\nfunction inAny(ip, ranges) {\n  return ranges.some((r) => inRange(ip, r));\n}\n\nfunction longest(ip, ranges) {\n  // TODO: 가장 긴 prefix\n  return null;\n}",
  sol:"function toInt(ip) {\n  return ip.split('.').reduce((a, b) => a * 256 + Number(b), 0);\n}\n\nfunction inRange(ip, range) {\n  const [net, bitsRaw] = range.split('/');\n  const bits = Number(bitsRaw);\n  const mask = bits === 0 ? 0 : (0xffffffff << (32 - bits)) >>> 0;\n  return ((toInt(ip) & mask) >>> 0) === ((toInt(net) & mask) >>> 0);\n}\n\nfunction inAny(ip, ranges) {\n  return ranges.some((r) => inRange(ip, r));\n}\n\nfunction longest(ip, ranges) {\n  const hit = ranges.filter((r) => inRange(ip, r));\n  if (!hit.length) return null;\n  return hit.reduce((a, b) => (Number(b.split('/')[1]) > Number(a.split('/')[1]) ? b : a));\n}",
  tests:[["inRange('192.168.1.50','192.168.1.0/24')","true"],
         ["inRange('192.168.2.50','192.168.1.0/24')","false"],
         ["inAny('10.1.2.3',['192.168.0.0/16','10.0.0.0/8'])","true"],
         ["longest('10.1.2.3',['10.0.0.0/8','10.1.0.0/16','0.0.0.0/0'])","'10.1.0.0/16'"]],
  edge:[["longest('8.8.8.8',['10.0.0.0/8'])","null"],
        ["inRange('1.2.3.4','0.0.0.0/0')","true"]],
  ex:"🎯 라우팅 테이블은 <b>가장 긴 prefix 가 이깁니다</b>(longest prefix match). 기본 경로 <code>0.0.0.0/0</code> 이 모든 주소에 맞지만, 더 구체적인 경로가 있으면 그쪽으로 갑니다.\n💡 방화벽·보안그룹 규칙도 같은 원리로 읽어야 합니다. '허용 규칙과 차단 규칙이 둘 다 맞을 때 어느 쪽이 이기는가' 는 제품마다 다르므로 반드시 확인하세요.\n⚠️ <code>/0</code> 은 마스크가 0이라 <code>0xffffffff &lt;&lt; 32</code> 가 되는데, 자바스크립트의 시프트는 <b>32로 나눈 나머지</b>를 쓰므로 <code>&lt;&lt; 0</code> 이 되어 마스크가 전체 비트가 됩니다 — 별도로 처리해야 하는 이유입니다.\n🔧 대역이 많으면 선형 탐색 대신 트라이(radix tree)를 씁니다. 실제 라우터가 그렇게 동작합니다." },

{ track:"net", k:"슬라이딩 윈도우", cat:"internals",
  q:"윈도우 크기 <code>w</code> 인 <b>Go-Back-N</b> 전송을 모델링하세요. <code>send(n, w, lost)</code> 는 패킷 0~n-1 을 보내는데, <code>lost</code> 에 있는 번호는 <b>처음 보낼 때만</b> 유실됩니다(재전송은 성공). <b>총 전송 횟수</b>를 돌려주세요.",
  src:"function send(n, w, lost) {\n  // TODO: 유실된 패킷부터 윈도우를 되돌려 다시 보낸다\n  return n;\n}",
  sol:"function send(n, w, lost) {\n  const dropped = new Set(lost);\n  let base = 0;\n  let sent = 0;\n  while (base < n) {\n    const end = Math.min(base + w, n);\n    let firstLoss = -1;\n    for (let i = base; i < end; i++) {\n      sent++;\n      if (dropped.has(i)) { dropped.delete(i); firstLoss = i; break; }\n    }\n    base = firstLoss >= 0 ? firstLoss : end;\n  }\n  return sent;\n}",
  tests:[["send(5,3,[])","5"],
         ["send(5,3,[1])","6"],
         ["send(6,3,[0])","7"],
         ["send(4,2,[])","4"]],
  edge:[["send(0,3,[])","0"],["send(3,1,[1])","4"]],
  ex:"🎯 <b>Go-Back-N</b> 은 유실된 패킷부터 <b>전부 다시</b> 보냅니다. 수신 측이 순서 없는 패킷을 버리므로 구현이 단순하지만, 손실 하나에 여러 패킷을 재전송합니다.\n💡 윈도우가 클수록 처리량이 높지만 <b>손실 시 재전송 비용도 커집니다</b>. 손실률이 높은 링크에서 큰 윈도우가 오히려 손해인 이유입니다.\n🔧 <b>선택적 반복</b>(Selective Repeat)은 유실된 것만 다시 보내 효율이 좋지만, 수신 측이 순서 없는 패킷을 버퍼링해야 해서 복잡합니다. 현대 TCP 는 SACK 으로 이 방향을 씁니다.\n⚠️ 윈도우 크기는 <b>대역폭 × 지연</b>(BDP)에 맞춰야 링크를 채웁니다. 위성처럼 지연이 큰 링크에서 작은 윈도우를 쓰면 대역폭이 아무리 커도 못 씁니다." },

{ track:"net", k:"URL 정규화", cat:"internals",
  q:"두 URL 이 <b>같은 자원을 가리키는지</b> 판정하는 <code>same(a, b)</code> 를 만드세요. 규칙: 스킴·호스트는 <b>대소문자 무시</b>, 기본 포트(http 80 / https 443)는 <b>생략과 같음</b>, 빈 경로는 <code>/</code> 와 같음, <b>프래그먼트는 무시</b>, 나머지는 그대로 비교합니다.",
  src:"function norm(u) {\n  // TODO: 비교 가능한 형태로 정규화\n  return u;\n}\n\nfunction same(a, b) {\n  return norm(a) === norm(b);\n}",
  sol:"const DEFAULT = { 'http:': '80', 'https:': '443' };\n\nfunction norm(u) {\n  const x = new URL(u);\n  const port = x.port && x.port !== DEFAULT[x.protocol] ? ':' + x.port : '';\n  const path = x.pathname || '/';\n  return x.protocol.toLowerCase() + '//' + x.hostname.toLowerCase() + port + path + x.search;\n}\n\nfunction same(a, b) {\n  return norm(a) === norm(b);\n}",
  tests:[["same('http://Example.com/a','http://example.com/a')","true"],
         ["same('http://example.com:80/a','http://example.com/a')","true"],
         ["same('https://example.com','https://example.com/')","true"],
         ["same('http://example.com/a#top','http://example.com/a')","true"]],
  edge:[["same('http://example.com/a?x=1','http://example.com/a?x=2')","false"],
        ["same('http://example.com/a','https://example.com/a')","false"]],
  ex:"🎯 URL 비교를 <b>문자열로</b> 하면 같은 자원을 다르다고 판정합니다. 캐시 키·중복 크롤링 방지·CORS 출처 비교가 모두 이 정규화에 기댑니다.\n💡 기본 포트는 <b>있어도 없는 것과 같습니다</b>. <code>https://example.com:443/</code> 과 <code>https://example.com/</code> 은 동일한 자원이고, 브라우저의 출처 비교도 이 규칙을 씁니다.\n⚠️ <b>프래그먼트(#)는 서버로 가지 않습니다</b> — 브라우저 안에서만 쓰이므로 서버 입장에서 같은 자원입니다.\n🔧 반면 <b>경로 대소문자와 쿼리 순서는 함부로 무시하면 안 됩니다</b>. 경로는 서버 구현에 따라 구분될 수 있고, 쿼리 순서를 정렬하면 순서가 의미 있는 API 에서 틀린 결과를 냅니다. 이 문항이 그것들을 건드리지 않는 이유입니다." },

{ track:"net", k:"체크섬", cat:"internals",
  q:"인터넷 체크섬(1의 보수 합)을 구현하세요. <code>checksum(words)</code> 는 16비트 워드 배열을 받아 <b>합의 1의 보수</b>를 돌려줍니다. 더하다 자리올림이 생기면 <b>하위로 되돌려 더합니다</b>(end-around carry).",
  src:"function checksum(words) {\n  // TODO: 16비트 1의 보수 합\n  return 0;\n}\n\nfunction verify(words, sum) {\n  return checksum(words.concat([sum])) === 0;\n}",
  sol:"function checksum(words) {\n  let sum = 0;\n  words.forEach((w) => {\n    sum += w;\n    if (sum > 0xffff) sum = (sum & 0xffff) + 1;\n  });\n  return (~sum) & 0xffff;\n}\n\nfunction verify(words, sum) {\n  return checksum(words.concat([sum])) === 0;\n}",
  tests:[["checksum([0x0001,0x0002])","65532"],
         ["checksum([0xffff,0x0001])","65534"],
         ["checksum([0x0000])","65535"],
         ["verify([0x0001,0x0002], checksum([0x0001,0x0002]))","true"]],
  edge:[["verify([0x1234,0x5678], checksum([0x1234,0x5678]))","true"],
        ["verify([0x1234,0x5678], 0)","false"]],
  ex:"🎯 인터넷 체크섬의 장점은 <b>계산이 아주 싸다</b>는 것입니다. 덧셈과 보수만으로 되므로 라우터가 매 패킷마다 다시 계산해도 부담이 없습니다.\n💡 <b>검증이 우아합니다</b> — 데이터에 체크섬까지 포함해 다시 합하면 0이 나옵니다. 별도 비교 로직이 필요 없습니다.\n⚠️ 대신 <b>오류 검출 능력이 약합니다</b>. 두 워드의 순서가 바뀌거나 상쇄되는 오류는 잡지 못합니다. 그래서 이더넷은 훨씬 강한 CRC-32 를 쓰고, 체크섬은 그 위의 얕은 방어입니다.\n🔧 end-around carry(자리올림을 하위로 되돌리기)가 1의 보수 산술의 핵심입니다 — 이걸 빼먹으면 큰 값에서 결과가 달라집니다." },

{ track:"net", k:"HTTP 요청 줄 파싱", cat:"internals",
  q:"HTTP 요청의 <b>첫 줄과 헤더</b>를 파싱하세요. <code>parse(raw)</code> 는 <code>{method, path, version, headers}</code> 를 돌려줍니다. 헤더 이름은 <b>소문자로 정규화</b>하고, 같은 이름이 여러 번 오면 <b>쉼표로 이어</b> 붙입니다. 형식이 잘못되면 <code>null</code> 입니다.",
  src:"function parse(raw) {\n  // TODO: 첫 줄 + 헤더\n  return null;\n}",
  sol:"function parse(raw) {\n  const lines = String(raw).split('\\r\\n');\n  const m = /^([A-Z]+) (\\S+) (HTTP\\/\\d\\.\\d)$/.exec(lines[0] || '');\n  if (!m) return null;\n  const headers = {};\n  for (let i = 1; i < lines.length && lines[i]; i++) {\n    const c = lines[i].indexOf(':');\n    if (c < 0) return null;\n    const k = lines[i].slice(0, c).trim().toLowerCase();\n    const v = lines[i].slice(c + 1).trim();\n    headers[k] = headers[k] === undefined ? v : headers[k] + ',' + v;\n  }\n  return { method: m[1], path: m[2], version: m[3], headers };\n}",
  tests:[["parse('GET /a HTTP/1.1\\r\\nHost: x.com\\r\\n\\r\\n').method","'GET'"],
         ["parse('GET /a HTTP/1.1\\r\\nHost: x.com\\r\\n\\r\\n').headers.host","'x.com'"],
         ["parse('GET /a HTTP/1.1\\r\\nAccept: a\\r\\nACCEPT: b\\r\\n\\r\\n').headers.accept","'a,b'"],
         ["parse('나쁜 줄\\r\\n\\r\\n')","null"]],
  edge:[["parse('POST /x HTTP/1.0\\r\\n\\r\\n').path","'/x'"],
        ["parse('GET /a HTTP/1.1\\r\\n헤더없음\\r\\n\\r\\n')","null"]],
  ex:"🎯 HTTP 헤더 이름은 <b>대소문자를 구분하지 않습니다</b>. <code>Host</code>·<code>host</code>·<code>HOST</code> 가 모두 같으므로, 파싱 즉시 소문자로 정규화하지 않으면 조회할 때마다 실수합니다.\n💡 같은 헤더가 여러 번 오는 것은 <b>정상</b>입니다. 명세상 쉼표로 이어 붙인 것과 같은 의미이고, 그래서 <code>Accept: a</code> 두 줄과 <code>Accept: a,b</code> 한 줄이 동등합니다(<code>Set-Cookie</code> 는 예외).\n⚠️ 줄 구분은 <code>\\r\\n</code> 입니다. <code>\\n</code> 만 처리하면 헤더 값 끝에 <code>\\r</code> 가 남아 비교가 조용히 실패합니다.\n🔧 실제 파서에서는 <b>헤더 개수와 길이에 상한</b>이 필요합니다. 무한히 긴 헤더를 보내는 공격(Slowloris 계열)이 실재합니다." },

/* ───────────── DEVOPS ───────────── */
{ track:"devops", k:"시맨틱 버전 비교", cat:"internals",
  q:"<b>시맨틱 버전</b>을 비교하는 <code>cmp(a, b)</code> 를 만드세요(a&lt;b 면 -1, 같으면 0, a&gt;b 면 1). 숫자는 <b>사전순이 아니라 수로</b> 비교하고, <b>프리릴리스가 붙은 쪽이 더 낮습니다</b>(<code>1.0.0-rc.1</code> &lt; <code>1.0.0</code>).",
  src:"function cmp(a, b) {\n  // TODO: major.minor.patch 비교 + 프리릴리스 규칙\n  return 0;\n}",
  sol:"function parse(v) {\n  const [core, pre] = String(v).split('-');\n  return { nums: core.split('.').map(Number), pre: pre || null };\n}\n\nfunction cmp(a, b) {\n  const x = parse(a);\n  const y = parse(b);\n  for (let i = 0; i < 3; i++) {\n    if (x.nums[i] !== y.nums[i]) return x.nums[i] < y.nums[i] ? -1 : 1;\n  }\n  if (x.pre === y.pre) return 0;\n  if (x.pre === null) return 1;\n  if (y.pre === null) return -1;\n  return x.pre < y.pre ? -1 : 1;\n}",
  tests:[["cmp('1.2.3','1.10.0')","-1"],
         ["cmp('2.0.0','1.99.99')","1"],
         ["cmp('1.0.0-rc.1','1.0.0')","-1"],
         ["cmp('1.0.0','1.0.0')","0"]],
  edge:[["cmp('1.0.0-alpha','1.0.0-beta')","-1"],
        ["cmp('0.1.0','0.0.9')","1"]],
  ex:"🎯 가장 흔한 버그는 <b>문자열로 비교하는</b> 것입니다. <code>'1.10.0' &lt; '1.2.3'</code> 이 사전순으로는 참이라, 배포 스크립트가 최신 버전을 못 고릅니다.\n💡 프리릴리스가 <b>더 낮다</b>는 규칙이 직관과 어긋납니다 — <code>1.0.0-rc.1</code> 은 <code>1.0.0</code> 을 향해 가는 중이므로 아직 그것이 아닙니다. 그래서 <code>^1.0.0</code> 범위는 기본적으로 프리릴리스를 포함하지 않습니다.\n⚠️ 정식 규격에서는 프리릴리스 식별자를 점으로 나눠 <b>숫자는 수로, 문자는 사전순</b>으로 비교합니다(<code>rc.2</code> &lt; <code>rc.10</code>). 이 문항은 단순화했지만 실무에서는 라이브러리를 쓰는 편이 안전합니다.\n🔧 버전 비교가 틀리면 롤백이 롤포워드가 됩니다 — 배포 도구에서 이 함수는 조용히 치명적입니다." },

{ track:"devops", k:"환경 설정 병합", cat:"internals",
  q:"설정을 <b>기본값 → 파일 → 환경변수</b> 순으로 덮어쓰며 병합하세요. <code>merge(...sources)</code> 는 <b>중첩 객체는 깊게</b> 병합하고, 배열은 <b>통째로 교체</b>하며, <code>undefined</code> 값은 <b>무시</b>합니다(있는 값을 지우면 안 됩니다).",
  src:"function merge(...sources) {\n  // TODO: 깊은 병합 · 배열은 교체 · undefined 무시\n  return {};\n}",
  sol:"function isObj(v) {\n  return v !== null && typeof v === 'object' && !Array.isArray(v);\n}\n\nfunction merge(...sources) {\n  return sources.reduce((acc, src) => {\n    if (!isObj(src)) return acc;\n    Object.keys(src).forEach((k) => {\n      const v = src[k];\n      if (v === undefined) return;\n      acc[k] = isObj(v) && isObj(acc[k]) ? merge(acc[k], v) : v;\n    });\n    return acc;\n  }, {});\n}",
  tests:[["merge({a:1},{b:2})","{a:1,b:2}"],
         ["merge({a:1},{a:2})","{a:2}"],
         ["merge({db:{host:'x',port:1}},{db:{port:2}})","{db:{host:'x',port:2}}"],
         ["merge({tags:['a','b']},{tags:['c']})","{tags:['c']}"]],
  edge:[["merge({a:1},{a:undefined})","{a:1}"],
        ["merge({a:{b:1}},{a:null})","{a:null}"]],
  ex:"🎯 설정 병합에서 가장 자주 나오는 버그는 <b>얕은 병합</b>입니다. <code>{...base, ...file}</code> 로 하면 <code>db</code> 객체가 통째로 교체되어 파일에 안 적은 <code>host</code> 가 사라집니다.\n💡 <b>배열은 깊게 병합하지 않는 것</b>이 맞습니다. 인덱스별로 병합하면 '기본 태그 3개 + 사용자 태그 1개' 가 뒤섞여 예측할 수 없는 값이 됩니다 — 교체가 직관적입니다.\n⚠️ <code>undefined</code> 를 그대로 덮어쓰면 <b>있던 설정이 사라집니다</b>. 환경변수를 읽을 때 없는 값이 <code>undefined</code> 로 오므로 이 처리가 없으면 기본값까지 날아갑니다.\n🔧 <code>null</code> 은 다릅니다 — '명시적으로 비움' 이라는 의도일 수 있으므로 덮어쓰는 것이 맞습니다. undefined 와 null 을 구분하는 것이 이 함수의 핵심입니다." },

{ track:"devops", k:"크론 표현식 매칭", cat:"internals",
  q:"5필드 크론 표현식이 주어진 시각에 <b>실행되는지</b> 판정하세요. <code>match(expr, t)</code> 에서 <code>t</code> 는 <code>{min, hour, dom, mon, dow}</code> 입니다. 지원할 문법은 <code>*</code>, 숫자, 쉼표 목록(<code>1,15</code>), 범위(<code>1-5</code>), 간격(<code>*/15</code>) 입니다.",
  src:"function field(spec, v) {\n  // TODO: 한 필드가 값 v 에 맞는지\n  return false;\n}\n\nfunction match(expr, t) {\n  const p = expr.split(' ');\n  return field(p[0], t.min) && field(p[1], t.hour) && field(p[2], t.dom)\n    && field(p[3], t.mon) && field(p[4], t.dow);\n}",
  sol:"function field(spec, v) {\n  return String(spec).split(',').some((part) => {\n    const [range, stepRaw] = part.split('/');\n    const step = stepRaw ? Number(stepRaw) : 1;\n    let lo;\n    let hi;\n    if (range === '*') { lo = -Infinity; hi = Infinity; }\n    else if (range.indexOf('-') > 0) {\n      const se = range.split('-');\n      lo = Number(se[0]); hi = Number(se[1]);\n    } else { lo = Number(range); hi = Number(range); }\n    if (v < lo || v > hi) return false;\n    if (step === 1) return true;\n    const base = lo === -Infinity ? 0 : lo;\n    return (v - base) % step === 0;\n  });\n}\n\nfunction match(expr, t) {\n  const p = expr.split(' ');\n  return field(p[0], t.min) && field(p[1], t.hour) && field(p[2], t.dom)\n    && field(p[3], t.mon) && field(p[4], t.dow);\n}",
  tests:[["match('* * * * *',{min:7,hour:3,dom:1,mon:1,dow:0})","true"],
         ["match('0 3 * * *',{min:0,hour:3,dom:9,mon:5,dow:2})","true"],
         ["match('0 3 * * *',{min:1,hour:3,dom:9,mon:5,dow:2})","false"],
         ["match('*/15 * * * *',{min:30,hour:0,dom:1,mon:1,dow:0})","true"]],
  edge:[["match('*/15 * * * *',{min:31,hour:0,dom:1,mon:1,dow:0})","false"],
        ["match('0 9-17 * * 1-5',{min:0,hour:12,dom:3,mon:6,dow:3})","true"]],
  ex:"🎯 크론 표현식을 <b>눈으로 읽어 확신하는</b> 것이 사고의 시작입니다. <code>*/15</code> 가 '15분마다' 인 건 맞지만 <code>5/15</code> 는 '5분부터 15분 간격' 이고, <code>0 */2 * * *</code> 는 짝수 시각에만 돕니다.\n⚠️ 가장 유명한 함정은 <b>day-of-month 와 day-of-week 가 둘 다 지정되면 OR</b> 로 동작한다는 것입니다(대부분의 크론 구현). <code>0 0 1 * 1</code> 은 '1일이거나 월요일' 이지 '1일이면서 월요일' 이 아닙니다 — 이 문항은 AND 로 단순화했으니 실제 스케줄러 문서를 꼭 확인하세요.\n💡 시간대도 함정입니다. 서버 타임존이 UTC 면 '매일 09:00' 이 한국 시간 18:00 이고, 서머타임이 있는 지역에서는 특정 시각이 <b>건너뛰거나 두 번</b> 실행됩니다.\n🔧 그래서 배치는 실행 시각이 아니라 <b>처리 대상 날짜</b>를 인자로 받아야 재실행이 안전합니다." },

{ track:"devops", k:"롤링 배포 계산", cat:"internals",
  q:"인스턴스 <b>total</b> 대를 롤링 배포합니다. 매 단계 <b>①올릴 수 있는 만큼 신버전을 올리고(총 파드 ≤ total + maxSurge, 신버전 ≤ total) ②내릴 수 있는 만큼 구버전을 내립니다(가용 = 구+신 ≥ total − maxUnavailable)</b>. <code>rollout(total, maxUnavailable, maxSurge)</code> 는 각 단계의 <code>[구버전, 신버전]</code> 을 돌려줍니다.",
  src:"function rollout(total, maxUnavailable, maxSurge) {\n  const steps = [];\n  let old = total;\n  let neu = 0;\n  // TODO: 올리고 내리기를 반복하며 단계를 기록하세요\n  return steps;\n}",
  sol:"function rollout(total, maxUnavailable, maxSurge) {\n  const steps = [];\n  let old = total;\n  let neu = 0;\n  while (old > 0 || neu < total) {\n    const up = Math.min(total - neu, total + maxSurge - (old + neu));\n    neu += up;\n    const down = Math.min(old, (old + neu) - (total - maxUnavailable));\n    old -= down;\n    steps.push([old, neu]);\n  }\n  return steps;\n}",
  tests:[["rollout(4,1,1)","[[2,1],[0,3],[0,4]]"],
         ["rollout(4,0,1)","[[3,1],[2,2],[1,3],[0,4]]"],
         ["rollout(2,1,1)","[[0,1],[0,2]]"],
         ["rollout(4,0,1).every(s=>s[0]+s[1]>=4)","true"]],
  edge:[["rollout(3,1,0)","[[2,0],[1,1],[0,2],[0,3]]"],
        ["rollout(1,1,0)","[[0,0],[0,1]]"]],
  ex:"🎯 <code>maxUnavailable</code> 은 '<b>최소 몇 대는 살아 있어야 하는가</b>', <code>maxSurge</code> 는 '<b>일시적으로 몇 대까지 더 띄울 수 있는가</b>' 입니다. 둘의 조합이 배포 속도와 안전성을 정합니다.\n💡 <code>maxSurge: 0</code> 이면 추가 자원 없이 진행되지만 <b>먼저 내려야</b> 올릴 자리가 생깁니다 — 엣지 케이스 <code>rollout(3,1,0)</code> 의 첫 단계 <code>[2,0]</code> 이 그것입니다. 가용 대수가 반드시 줄어들므로 남은 인스턴스가 늘어난 부하를 감당해야 합니다.\n⚠️ <code>rollout(1,1,0)</code> 은 첫 단계가 <code>[0,0]</code> — <b>완전한 중단</b>입니다. 인스턴스 1대에 maxUnavailable 1은 무중단이 아니라는 뜻이고, 무중단을 원하면 최소 2대 + maxSurge 가 필요합니다.\n🔧 반대로 <code>maxUnavailable: 0</code> 이면 가용 대수가 절대 줄지 않지만 자원이 잠깐 더 필요합니다. 자원이 빠듯하면 배포가 아예 진행되지 않습니다." },

{ track:"devops", k:"Dockerfile 캐시 무효화", cat:"internals",
  q:"Dockerfile 의 명령 목록과 <b>바뀐 파일 목록</b>이 주어집니다. <code>firstInvalid(steps, changed)</code> 는 <b>캐시가 처음 깨지는 단계의 인덱스</b>를 돌려줍니다. <code>COPY</code>/<code>ADD</code> 는 대상 경로가 바뀐 파일에 걸리면 깨지고, 그 <b>이후 모든 단계</b>도 깨집니다. 안 깨지면 -1 입니다.",
  src:"function firstInvalid(steps, changed) {\n  // TODO: COPY/ADD 의 소스가 바뀐 파일과 겹치는 첫 지점\n  return -1;\n}",
  sol:"function firstInvalid(steps, changed) {\n  return steps.findIndex((s) => {\n    const m = /^(COPY|ADD)\\s+(\\S+)/.exec(s);\n    if (!m) return false;\n    const src = m[2];\n    return changed.some((f) => f === src || (src === '.' ? true : f.indexOf(src) === 0));\n  });\n}",
  tests:[["firstInvalid(['FROM node','COPY package.json .','RUN npm ci','COPY . .','RUN npm run build'],['src/app.js'])","3"],
         ["firstInvalid(['FROM node','COPY package.json .','RUN npm ci','COPY . .'],['package.json'])","1"],
         ["firstInvalid(['FROM node','RUN apt-get update'],['src/a.js'])","-1"],
         ["firstInvalid(['FROM node','COPY src/ .','RUN build'],['src/a.js'])","1"]],
  edge:[["firstInvalid([],['a.js'])","-1"],
        ["firstInvalid(['FROM node','COPY . .'],[])","-1"]],
  ex:"🎯 도커 빌드 캐시는 <b>단계 단위</b>입니다. 한 단계가 깨지면 그 뒤는 전부 다시 실행되므로, <b>자주 바뀌는 것을 뒤에</b> 두는 것이 빌드 시간을 좌우합니다.\n🔧 그래서 <code>COPY package.json</code> → <code>RUN npm ci</code> → <code>COPY . .</code> 순서가 정석입니다. 소스만 고치면 의존성 설치 캐시가 살아남아 빌드가 몇 분에서 몇 초로 줄어듭니다.\n⚠️ 순서를 뒤집어 <code>COPY . .</code> 를 먼저 두면 <b>파일 하나만 고쳐도 npm ci 가 다시 돕니다</b>. 테스트 1이 그 상황(인덱스 3에서 깨짐)과 테스트 2(인덱스 1에서 깨짐)를 비교합니다.\n💡 <code>.dockerignore</code> 도 중요합니다. <code>node_modules</code> 나 <code>.git</code> 이 컨텍스트에 들어가면 무관한 변경으로 캐시가 깨지고 전송량도 커집니다." },

{ track:"devops", k:"배포 실패율과 중단 판단", cat:"internals",
  q:"배포를 진행하며 인스턴스별 헬스체크 결과를 받습니다. <code>shouldStop(results, minSamples, maxFailRate)</code> 는 <b>표본이 minSamples 이상 모인 뒤부터</b> 실패율을 보고, 초과하면 그 시점 인덱스를 돌려줍니다(중단). 끝까지 괜찮으면 -1 입니다.",
  src:"function shouldStop(results, minSamples, maxFailRate) {\n  // TODO: 표본이 충분할 때만 판정\n  return -1;\n}",
  sol:"function shouldStop(results, minSamples, maxFailRate) {\n  let fail = 0;\n  for (let i = 0; i < results.length; i++) {\n    if (!results[i]) fail++;\n    const n = i + 1;\n    if (n < minSamples) continue;\n    if (fail / n > maxFailRate) return i;\n  }\n  return -1;\n}",
  tests:[["shouldStop([true,true,true,true,false],3,0.2)","-1"],
         ["shouldStop([false,false,true,true,true],3,0.2)","2"],
         ["shouldStop([true,true,true,true],3,0.2)","-1"],
         ["shouldStop([false],3,0.2)","-1"]],
  edge:[["shouldStop([],3,0.2)","-1"],
        ["shouldStop([false,false,false],1,0.5)","0"]],
  ex:"🎯 <b>최소 표본 수</b>가 없으면 첫 인스턴스 하나가 실패했을 때 실패율 100% 로 읽혀 멀쩡한 배포를 계속 중단합니다. 통계적으로 판단할 수 없는 구간을 건너뛰는 것이 이 조건의 목적입니다.\n💡 반대로 표본을 너무 많이 요구하면 <b>문제를 늦게 발견</b>합니다. 배포 규모와 허용 위험에 맞춰 정해야 하는 값입니다.\n⚠️ 실패율을 <b>누적</b>으로 볼지 <b>최근 창</b>으로 볼지도 선택입니다. 누적은 초반 실패가 계속 발목을 잡고, 최근 창은 회복을 반영하지만 잡음에 민감합니다.\n🔧 이 판단이 자동화되지 않으면 새벽 배포에서 아무도 못 잡습니다 — 사람이 그래프를 보는 구조는 게이트가 아닙니다." },

/* ───────────── SYSD ───────────── */
{ track:"sysd", k:"일관 해싱", cat:"internals",
  q:"<b>일관 해싱</b> 링을 만드세요. <code>build(nodes, vnodes)</code> 는 각 노드마다 가상 노드를 만들어 정렬된 링을 돌려주고, <code>lookup(ring, key)</code> 는 해시가 <b>그 이상인 첫 지점</b>의 노드를 고릅니다(넘어가면 처음으로 돌아옵니다).",
  src:"function hash(s) {\n  let h = 2166136261;\n  for (let i = 0; i < s.length; i++) {\n    h ^= s.charCodeAt(i);\n    h = Math.imul(h, 16777619) >>> 0;\n  }\n  return h;\n}\n\nfunction build(nodes, vnodes) {\n  // TODO: [{h, node}] 를 h 오름차순으로\n  return [];\n}\n\nfunction lookup(ring, key) {\n  // TODO\n  return null;\n}",
  sol:"function hash(s) {\n  let h = 2166136261;\n  for (let i = 0; i < s.length; i++) {\n    h ^= s.charCodeAt(i);\n    h = Math.imul(h, 16777619) >>> 0;\n  }\n  return h;\n}\n\nfunction build(nodes, vnodes) {\n  const ring = [];\n  nodes.forEach((n) => {\n    for (let i = 0; i < vnodes; i++) ring.push({ h: hash(n + '#' + i), node: n });\n  });\n  return ring.sort((a, b) => a.h - b.h);\n}\n\nfunction lookup(ring, key) {\n  if (!ring.length) return null;\n  const h = hash(key);\n  const hit = ring.find((e) => e.h >= h);\n  return (hit || ring[0]).node;\n}",
  tests:[["build(['a','b'],2).length","4"],
         ["build(['a','b'],2).every((e,i,r)=>i===0||r[i-1].h<=e.h)","true"],
         ["typeof lookup(build(['a','b','c'],10),'key1')","'string'"],
         ["(() => { const r = build(['a','b','c'],10); return lookup(r,'k') === lookup(r,'k'); })()","true"]],
  edge:[["lookup([],'k')","null"],
        ["(() => { const r = build(['a'],5); return lookup(r,'anything'); })()","'a'"]],
  ex:"🎯 일반 해싱(<code>hash(key) % N</code>)은 노드가 하나 늘거나 빠지면 <b>거의 모든 키가 이동</b>합니다. 캐시라면 전체가 한꺼번에 비어 원본이 무너집니다.\n🔧 일관 해싱은 링 위에 노드를 놓고 키를 시계 방향으로 가장 가까운 노드에 배정합니다. 노드가 빠지면 <b>그 구간의 키만</b> 옆 노드로 넘어가므로 이동량이 1/N 수준입니다.\n💡 <b>가상 노드</b>가 없으면 링 위 분포가 들쭉날쭉해 특정 노드에 부하가 몰립니다. 노드마다 수십~수백 개의 가상 노드를 두어 고르게 만듭니다.\n⚠️ 조회가 선형 탐색이면 링이 커질수록 느려집니다 — 실제로는 정렬된 배열에 <b>이진 탐색</b>을 씁니다. 이 문항은 동작에 집중하려고 find 를 썼습니다." },

{ track:"sysd", k:"블룸 필터", cat:"internals",
  q:"<b>블룸 필터</b>를 구현하세요. <code>add(f, key)</code> 는 k개 해시 위치의 비트를 켜고, <code>has(f, key)</code> 는 모두 켜져 있으면 <code>true</code> 입니다. <b>거짓 양성은 있어도 거짓 음성은 없어야</b> 합니다.",
  src:"function make(m, k) {\n  return { bits: new Array(m).fill(0), m, k };\n}\n\nfunction hashAt(key, i, m) {\n  let h = 2166136261 ^ i;\n  for (let j = 0; j < key.length; j++) {\n    h ^= key.charCodeAt(j);\n    h = Math.imul(h, 16777619) >>> 0;\n  }\n  return h % m;\n}\n\nfunction add(f, key) {\n  // TODO\n}\n\nfunction has(f, key) {\n  // TODO\n  return false;\n}",
  sol:"function make(m, k) {\n  return { bits: new Array(m).fill(0), m, k };\n}\n\nfunction hashAt(key, i, m) {\n  let h = 2166136261 ^ i;\n  for (let j = 0; j < key.length; j++) {\n    h ^= key.charCodeAt(j);\n    h = Math.imul(h, 16777619) >>> 0;\n  }\n  return h % m;\n}\n\nfunction add(f, key) {\n  for (let i = 0; i < f.k; i++) f.bits[hashAt(key, i, f.m)] = 1;\n}\n\nfunction has(f, key) {\n  for (let i = 0; i < f.k; i++) {\n    if (!f.bits[hashAt(key, i, f.m)]) return false;\n  }\n  return true;\n}",
  tests:[["(() => { const f = make(64,3); add(f,'a'); return has(f,'a'); })()","true"],
         ["(() => { const f = make(1024,3); add(f,'a'); add(f,'b'); return [has(f,'a'), has(f,'b')]; })()","[true,true]"],
         ["(() => { const f = make(1024,3); return has(f,'nope'); })()","false"],
         ["(() => { const f = make(1024,3); ['a','b','c','d'].forEach(x=>add(f,x)); return ['a','b','c','d'].every(x=>has(f,x)); })()","true"]],
  edge:[["(() => { const f = make(1024,3); add(f,''); return has(f,''); })()","true"],
        ["(() => { const f = make(1024,3); add(f,'x'); return f.bits.filter(b=>b).length<=3; })()","true"]],
  ex:"🎯 블룸 필터는 '<b>확실히 없다</b>' 만 보장합니다. 하나라도 비트가 0이면 절대 넣은 적이 없고(거짓 음성 없음), 전부 1이면 있을 수도 있습니다(거짓 양성 가능).\n💡 이 비대칭이 쓸모의 전부입니다. 캐시 앞에 두면 '없는 키' 조회를 <b>디스크에 가기 전에</b> 걸러낼 수 있어, 존재하지 않는 키를 계속 찾는 캐시 관통을 막습니다.\n⚠️ 원소를 <b>지울 수 없습니다</b>. 비트를 끄면 그 비트를 공유하는 다른 원소까지 사라져 거짓 음성이 생깁니다 — 삭제가 필요하면 counting Bloom filter 를 씁니다.\n🔧 크기 m 과 해시 개수 k 는 예상 원소 수와 허용 오탐률로 계산합니다. k 를 너무 늘리면 비트가 빨리 차서 오히려 오탐이 늘어납니다." },

{ track:"sysd", k:"벡터 클럭", cat:"internals",
  q:"<b>벡터 클럭</b>으로 두 사건의 관계를 판정하세요. <code>compare(a, b)</code> 는 <code>'before'</code>·<code>'after'</code>·<code>'equal'</code>·<code>'concurrent'</code> 중 하나를 돌려줍니다. 없는 노드의 값은 <b>0</b> 으로 봅니다.",
  src:"function compare(a, b) {\n  // TODO: 모든 성분을 비교해 관계를 판정\n  return 'concurrent';\n}",
  sol:"function compare(a, b) {\n  const keys = Object.keys(Object.assign({}, a, b));\n  let le = true;\n  let ge = true;\n  keys.forEach((k) => {\n    const x = a[k] || 0;\n    const y = b[k] || 0;\n    if (x > y) le = false;\n    if (x < y) ge = false;\n  });\n  if (le && ge) return 'equal';\n  if (le) return 'before';\n  if (ge) return 'after';\n  return 'concurrent';\n}",
  tests:[["compare({a:1},{a:2})","'before'"],
         ["compare({a:2,b:1},{a:1,b:1})","'after'"],
         ["compare({a:1,b:0},{a:0,b:1})","'concurrent'"],
         ["compare({a:1,b:1},{a:1,b:1})","'equal'"]],
  edge:[["compare({},{})","'equal'"],
        ["compare({a:1},{b:1})","'concurrent'"]],
  ex:"🎯 분산 시스템에는 <b>전역 시계가 없습니다</b>. 서버들의 시각은 조금씩 어긋나므로 타임스탬프 비교로는 인과 관계를 알 수 없습니다.\n🔧 벡터 클럭은 각 노드의 카운터를 모아 <b>인과 관계</b>를 표현합니다. 모든 성분이 작거나 같고 하나라도 작으면 '먼저 일어난 일' 이고, 서로 엇갈리면 <b>동시(concurrent)</b> — 즉 순서를 정할 수 없습니다.\n💡 '동시' 를 감지할 수 있다는 것이 핵심입니다. 이것이 곧 <b>충돌</b>이므로, 시스템은 자동 병합하거나 사용자에게 물어야 합니다. 타임스탬프만 쓰면 '나중 쓰기가 이긴다' 로 <b>조용히 데이터를 잃습니다</b>.\n⚠️ 대가는 크기입니다. 노드 수만큼 성분이 늘어나므로, 노드가 자주 바뀌는 환경에서는 정리(pruning) 전략이 필요합니다." },

{ track:"sysd", k:"토큰 버킷", cat:"internals",
  q:"<b>토큰 버킷</b> 레이트 리미터를 만드세요. 버킷 용량 <code>cap</code>, 초당 <code>rate</code> 개씩 채워집니다. <code>allow(b, now, n)</code> 은 경과 시간만큼 토큰을 채운 뒤 n 개를 쓸 수 있으면 소비하고 <code>true</code>, 아니면 <code>false</code> 입니다.",
  src:"function make(cap, rate) {\n  return { cap, rate, tokens: cap, last: 0 };\n}\n\nfunction allow(b, now, n) {\n  // TODO: 경과 시간만큼 보충 → 소비 판정\n  return false;\n}",
  sol:"function make(cap, rate) {\n  return { cap, rate, tokens: cap, last: 0 };\n}\n\nfunction allow(b, now, n) {\n  const gain = (now - b.last) * b.rate;\n  b.tokens = Math.min(b.cap, b.tokens + gain);\n  b.last = now;\n  if (b.tokens < n) return false;\n  b.tokens -= n;\n  return true;\n}",
  tests:[["(() => { const b = make(5,1); return [allow(b,0,5), allow(b,0,1)]; })()","[true,false]"],
         ["(() => { const b = make(5,1); allow(b,0,5); return allow(b,2,2); })()","true"],
         ["(() => { const b = make(5,1); allow(b,0,5); return allow(b,1,2); })()","false"],
         ["(() => { const b = make(5,1); allow(b,0,5); allow(b,100,0); return b.tokens; })()","5"]],
  edge:[["(() => { const b = make(3,1); return allow(b,0,10); })()","false"],
        ["(() => { const b = make(3,1); return allow(b,0,0); })()","true"]],
  ex:"🎯 토큰 버킷은 <b>평균 속도는 제한하되 순간적인 몰림(burst)은 허용</b>합니다. 용량만큼 모아 뒀다가 한 번에 쓸 수 있어, 간헐적으로 요청하는 정상 클라이언트를 막지 않습니다.\n💡 고정 창 방식과 비교해 보세요. 고정 창은 경계에서 <b>두 배</b>가 통과하지만(59초에 5회, 61초에 또 5회), 토큰 버킷은 그런 구간이 없습니다.\n🔧 <b>보충 상한</b>이 중요합니다. <code>Math.min(cap, ...)</code> 을 빼먹으면 오래 쉰 클라이언트가 무한한 토큰을 쌓아 한 번에 서버를 넘어뜨립니다 — 테스트 4가 그것을 검사합니다.\n⚠️ 서버가 여러 대면 버킷도 공유돼야 합니다. 인스턴스마다 메모리에 두면 실제 한도가 인스턴스 수만큼 늘어납니다." },

{ track:"sysd", k:"과반 리더 선출", cat:"internals",
  q:"과반수 투표로 리더를 뽑습니다. <code>elect(total, votes)</code> 는 각 후보의 득표를 세어 <b>과반(total/2 초과)</b> 을 얻은 후보를 돌려주고, 없으면 <code>null</code> 입니다. 표는 <code>{voter: candidate}</code> 이고 <b>한 투표자는 한 표</b>만 갖습니다.",
  src:"function elect(total, votes) {\n  // TODO: 과반 득표자\n  return null;\n}",
  sol:"function elect(total, votes) {\n  const count = {};\n  Object.keys(votes).forEach((v) => {\n    const c = votes[v];\n    count[c] = (count[c] || 0) + 1;\n  });\n  const need = Math.floor(total / 2) + 1;\n  const win = Object.keys(count).find((c) => count[c] >= need);\n  return win === undefined ? null : win;\n}",
  tests:[["elect(5,{n1:'a',n2:'a',n3:'a',n4:'b',n5:'b'})","'a'"],
         ["elect(5,{n1:'a',n2:'a',n3:'b',n4:'b'})","null"],
         ["elect(3,{n1:'x',n2:'x'})","'x'"],
         ["elect(4,{n1:'a',n2:'a',n3:'b',n4:'b'})","null"]],
  edge:[["elect(1,{n1:'solo'})","'solo'"],
        ["elect(5,{})","null"]],
  ex:"🎯 과반을 요구하는 이유는 <b>두 개의 리더가 동시에 존재할 수 없게</b> 하기 위해서입니다. 과반은 어떤 두 집합도 반드시 겹치므로(quorum intersection), 서로 다른 두 후보가 동시에 과반을 얻을 수 없습니다.\n⚠️ 이게 <b>스플릿 브레인</b>을 막는 원리입니다. 네트워크가 둘로 갈라져도 과반을 가진 쪽만 리더를 뽑을 수 있고, 나머지는 스스로 물러납니다.\n💡 그래서 노드 수를 <b>홀수</b>로 둡니다. 4대면 2:2 로 갈렸을 때 양쪽 다 과반이 안 되어 서비스가 멈추고, 5대면 3:2 로 한쪽이 계속 일할 수 있습니다. 4대는 3대보다 나은 게 없습니다.\n🔧 실제 Raft·Paxos 는 여기에 <b>임기(term)</b>와 로그 최신성 조건을 더합니다 — 과반만으로는 오래된 데이터를 가진 노드가 리더가 될 수 있기 때문입니다." },

{ track:"sysd", k:"LRU 캐시", cat:"internals",
  q:"용량 <code>cap</code> 의 <b>LRU 캐시</b>를 만드세요. <code>get(c, k)</code> 는 값을 돌려주며 <b>최근 사용으로 갱신</b>하고(없으면 <code>null</code>), <code>put(c, k, v)</code> 는 넣되 용량을 넘으면 <b>가장 오래 안 쓴 것</b>을 버립니다.",
  src:"function make(cap) {\n  return { cap, map: new Map() };\n}\n\nfunction get(c, k) {\n  // TODO\n  return null;\n}\n\nfunction put(c, k, v) {\n  // TODO\n}",
  sol:"function make(cap) {\n  return { cap, map: new Map() };\n}\n\nfunction get(c, k) {\n  if (!c.map.has(k)) return null;\n  const v = c.map.get(k);\n  c.map.delete(k);\n  c.map.set(k, v);\n  return v;\n}\n\nfunction put(c, k, v) {\n  if (c.map.has(k)) c.map.delete(k);\n  c.map.set(k, v);\n  if (c.map.size > c.cap) c.map.delete(c.map.keys().next().value);\n}",
  tests:[["(() => { const c = make(2); put(c,'a',1); put(c,'b',2); return [get(c,'a'), get(c,'b')]; })()","[1,2]"],
         ["(() => { const c = make(2); put(c,'a',1); put(c,'b',2); put(c,'c',3); return get(c,'a'); })()","null"],
         ["(() => { const c = make(2); put(c,'a',1); put(c,'b',2); get(c,'a'); put(c,'c',3); return [get(c,'a'), get(c,'b')]; })()","[1,null]"],
         ["(() => { const c = make(2); put(c,'a',1); put(c,'a',9); return [get(c,'a'), c.map.size]; })()","[9,1]"]],
  edge:[["(() => { const c = make(1); put(c,'a',1); put(c,'b',2); return get(c,'a'); })()","null"],
        ["(() => { const c = make(2); return get(c,'nope'); })()","null"]],
  ex:"🎯 자바스크립트의 <code>Map</code> 은 <b>삽입 순서를 유지</b>합니다. 그래서 '삭제 후 재삽입' 으로 최근 사용을 표현하면 별도 연결 리스트 없이 LRU 가 됩니다.\n💡 <b>get 에서도 순서를 갱신</b>하는 것이 핵심입니다. 이걸 빼먹으면 FIFO 가 되어, 자주 읽히는 항목이 오래됐다는 이유로 쫓겨납니다 — 테스트 3이 정확히 그 차이를 봅니다.\n🔧 <code>map.keys().next().value</code> 가 가장 오래된 키입니다. Map 의 이터레이터는 삽입 순서를 따르므로 첫 번째가 곧 LRU 대상입니다.\n⚠️ 같은 키를 다시 넣을 때 <b>먼저 지우지 않으면</b> 순서가 갱신되지 않습니다. Map 의 <code>set</code> 은 이미 있는 키의 위치를 바꾸지 않기 때문입니다 — 테스트 4가 크기까지 함께 확인합니다." },
];
