/* 데브옵스 실행형 — 운영에서 '규칙을 잘못 읽어' 생기는 사고를 직접 구현해 본다.
   전부 결정적(시각은 인자로 받는다), 순수 JS라 오프라인에서 돈다.
   주의: 앱 하네스가 쓰는 이름(SRC·TS·eq·gate·impl·P·row·parts·qp 등)과 겹치지 않게 짓는다. */
module.exports = [
{ track:"devops", k:"도커 레이어 캐시 무효화", cat:"internals",
  q:"Dockerfile 빌드에서 <b>어느 줄부터 캐시가 깨지는지</b> 계산하세요. <code>cacheHits(prev, next)</code> 는 이전 빌드와 이번 빌드의 명령 배열을 받아, <b>앞에서부터 같은 동안만</b> 캐시가 맞고 <b>한 줄이라도 달라지면 그 아래는 전부 다시 빌드</b>됩니다. 캐시가 맞은 줄 수를 돌려주세요.",
  src:"function cacheHits(prev, next) {\n  // TODO: 앞에서부터 같은 동안만 캐시\n  return next.filter((c) => prev.includes(c)).length;\n}",
  sol:"function cacheHits(prev, next) {\n  let n = 0;\n  while (n < next.length && n < prev.length && prev[n] === next[n]) n++;\n  return n;\n}",
  tests:[["cacheHits(['FROM node','COPY package.json','RUN npm i','COPY .'],['FROM node','COPY package.json','RUN npm i','COPY .'])","4"],
         ["cacheHits(['FROM node','COPY .','RUN npm i'],['FROM node','COPY .','RUN npm i --prod'])","2"],
         ["cacheHits(['FROM node','COPY .','RUN npm i'],['FROM node','COPY package.json','RUN npm i'])","1"],
         ["cacheHits(['FROM node'],['FROM alpine','COPY .'])","0"]],
  edge:[["cacheHits([],['FROM node'])","0"],
        ["cacheHits(['A','B','C'],['A','B'])","2"]],
  ex:"🎯 도커 캐시는 <b>줄 단위가 아니라 누적</b>입니다. 한 줄이 바뀌면 그 아래는 내용이 같아도 <b>전부 다시</b> 실행됩니다 — 이전 레이어가 달라졌으니 결과가 같다고 보장할 수 없기 때문입니다.\n💡 그래서 <b>자주 바뀌는 것을 아래로</b> 내리는 것이 Dockerfile 최적화의 핵심입니다. <code>COPY package.json</code> → <code>RUN npm install</code> → <code>COPY .</code> 순서면 소스만 고쳤을 때 의존성 설치가 캐시에 걸립니다. 반대로 <code>COPY .</code> 를 먼저 하면 <b>매 빌드마다 전체 설치</b>입니다.\n⚠️ <code>COPY</code> 는 명령 문자열뿐 아니라 <b>파일 내용의 해시</b>로도 판정합니다 — 명령은 같은데 파일이 바뀌면 캐시가 깨집니다. <code>.dockerignore</code> 로 불필요한 파일(로그·.git)을 빼야 엉뚱한 변경으로 캐시가 날아가지 않습니다.\n🔧 CI 에서 캐시가 늘 깨진다면 대개 <b>순서 문제이거나 .dockerignore 누락</b>입니다. 멀티스테이지 빌드로 빌드 도구와 런타임을 분리하면 캐시 효율과 이미지 크기를 동시에 잡습니다." },

{ track:"devops", k:"nginx location 우선순위", cat:"internals",
  q:"nginx 의 <b>location 매칭 우선순위</b>를 구현하세요. <code>pickLocation(rules, path)</code> 는 <code>{type, pat}</code> 규칙 중 하나를 고릅니다 — <b><code>'exact'</code>(<code>=</code>) 가 최우선</b>, 그다음 <b><code>'prefix'</code> 중 가장 긴 것</b>, 마지막이 <b><code>'regex'</code>(먼저 선언된 것)</b>. 없으면 <code>null</code> 입니다.",
  src:"function pickLocation(rules, path) {\n  // TODO: exact → 최장 prefix → 첫 regex\n  const hit = rules.find((r) => path.startsWith(r.pat));\n  return hit ? hit.pat : null;\n}",
  sol:"function pickLocation(rules, path) {\n  const exact = rules.find((r) => r.type === 'exact' && r.pat === path);\n  if (exact) return exact.pat;\n  let best = null;\n  rules.forEach((r) => {\n    if (r.type !== 'prefix' || !path.startsWith(r.pat)) return;\n    if (!best || r.pat.length > best.length) best = r.pat;\n  });\n  if (best) return best;\n  const re = rules.find((r) => r.type === 'regex' && new RegExp(r.pat).test(path));\n  return re ? re.pat : null;\n}",
  tests:[["pickLocation([{type:'prefix',pat:'/'},{type:'exact',pat:'/health'}],'/health')","'/health'"],
         ["pickLocation([{type:'prefix',pat:'/'},{type:'prefix',pat:'/api/v1'}],'/api/v1/users')","'/api/v1'"],
         ["pickLocation([{type:'regex',pat:'\\\\.png$'},{type:'prefix',pat:'/static'}],'/static/a.png')","'/static'"],
         ["pickLocation([{type:'regex',pat:'\\\\.png$'}],'/img/a.png')","'\\\\.png$'"]],
  edge:[["pickLocation([{type:'prefix',pat:'/api'}],'/other')","null"],
        ["pickLocation([{type:'regex',pat:'^/a'},{type:'regex',pat:'^/ab'}],'/abc')","'^/a'"]],
  ex:"🎯 nginx 의 location 은 <b>설정 파일 순서대로 매칭되지 않습니다</b>. 정확 일치(<code>=</code>)가 먼저, 그다음 <b>가장 긴 접두사</b>, 마지막이 정규식입니다 — 이 규칙을 모르면 '위에 썼는데 왜 안 먹지' 로 몇 시간을 씁니다.\n💡 '가장 긴 접두사' 는 라우팅의 보편 원리입니다 — IP 라우팅 테이블도 longest prefix match 로 동작합니다. 구체적인 규칙이 일반적인 규칙을 이겨야 <code>/</code> catch-all 이 모든 것을 삼키지 않습니다.\n⚠️ 정규식은 <b>선언 순서</b>가 중요합니다(먼저 매칭되는 것이 이김). 그래서 정규식 location 은 순서를 바꾸는 것만으로 동작이 달라져, 리팩터링 시 사고가 나기 쉽습니다.\n🔧 <code>^~</code> 접두사는 '이 접두사가 맞으면 정규식을 아예 보지 마라' 는 지시로, 정적 파일 경로에서 자주 씁니다. 헷갈릴 때는 <code>nginx -T</code> 로 최종 병합 설정을 확인하는 것이 가장 빠릅니다." },

{ track:"devops", k:"semver 범위 매칭", cat:"internals",
  q:"의존성 <b>버전 범위</b>를 판정하세요. <code>satisfies(version, range)</code> 는 <code>'1.4.2'</code> 같은 버전이 범위에 드는지 봅니다 — <code>'^1.2.3'</code> 은 <b>맨 왼쪽 0이 아닌 자리를 고정</b>(<code>&gt;=1.2.3 &lt;2.0.0</code>), <code>'~1.2.3'</code> 은 <b>패치만 허용</b>(<code>&gt;=1.2.3 &lt;1.3.0</code>), 그냥 <code>'1.2.3'</code> 은 정확히 일치입니다.",
  src:"function satisfies(version, range) {\n  // TODO: ^ ~ 정확 일치\n  return version === range;\n}",
  sol:"function satisfies(version, range) {\n  const cmp = (a, b) => {\n    for (let i = 0; i < 3; i++) { if (a[i] !== b[i]) return a[i] - b[i]; }\n    return 0;\n  };\n  const num = (s) => s.split('.').map(Number);\n  const op = range[0] === '^' || range[0] === '~' ? range[0] : '=';\n  const base = num(op === '=' ? range : range.slice(1));\n  const v = num(version);\n  if (op === '=') return cmp(v, base) === 0;\n  if (cmp(v, base) < 0) return false;\n  const upper = op === '~' ? [base[0], base[1] + 1, 0] : [base[0] + 1, 0, 0];\n  return cmp(v, upper) < 0;\n}",
  tests:[["satisfies('1.4.2','^1.2.3')","true"],
         ["satisfies('2.0.0','^1.2.3')","false"],
         ["satisfies('1.2.9','~1.2.3')","true"],
         ["satisfies('1.3.0','~1.2.3')","false"]],
  edge:[["satisfies('1.2.2','^1.2.3')","false"],
        ["satisfies('1.2.3','1.2.3')","true"]],
  ex:"🎯 <code>^</code> 와 <code>~</code> 의 차이가 곧 <b>무엇을 신뢰하는가</b>입니다. <code>^</code> 는 '마이너 업데이트는 호환된다' 는 semver 약속을 믿는 것이고, <code>~</code> 는 '패치만 받겠다' 는 보수적 선택입니다.\n💡 <code>package.json</code> 의 기본이 <code>^</code> 라, <code>npm install</code> 시점에 따라 <b>다른 버전이 설치될 수 있습니다</b> — '내 컴퓨터에서는 되는데' 의 흔한 원인입니다. 그래서 <code>package-lock.json</code> 을 커밋하고 CI 에서는 <code>npm ci</code> 로 <b>락 파일 그대로</b> 설치합니다.\n⚠️ 0.x 버전은 예외 규칙이 있습니다 — semver 는 0.x 를 불안정으로 보아 <code>^0.2.3</code> 이 <code>&gt;=0.2.3 &lt;0.3.0</code> 으로 동작합니다(마이너도 깨질 수 있다고 가정). 라이브러리가 1.0 을 찍는 것이 '이제 호환성을 약속한다' 는 선언인 이유입니다.\n🔧 공급망 사고 이후로는 범위 대신 <b>정확한 고정 + 자동 갱신 PR</b>(Dependabot·Renovate)이 늘고 있습니다. 업데이트를 자동화하되 <b>언제 들어올지는 사람이 정하는</b> 방식입니다." },

{ track:"devops", k:"롤링 업데이트 배치 계산", cat:"internals",
  q:"쿠버네티스 <b>롤링 업데이트</b>의 각 단계를 계산하세요. <code>rollSteps(total, maxSurge, maxUnavailable)</code> 는 파드 하나가 늘거나 줄 때마다 <code>[신버전 수, 구버전 수]</code> 를 기록해 돌려줍니다. <b>총합은 <code>total + maxSurge</code> 이하</b>, <b>가용 수는 <code>total − maxUnavailable</code> 이상</b>을 항상 지켜야 하며, <b>늘릴 수 있으면 먼저 늘리고</b> 안 되면 줄입니다.",
  src:"function rollSteps(total, maxSurge, maxUnavailable) {\n  // TODO: 상한·하한을 지키며 한 개씩\n  return [[total, 0]];\n}",
  sol:"function rollSteps(total, maxSurge, maxUnavailable) {\n  const steps = [];\n  let neu = 0, old = total;\n  while (neu < total || old > 0) {\n    if (neu < total && neu + old < total + maxSurge) neu++;\n    else if (old > 0 && neu + old - 1 >= total - maxUnavailable) old--;\n    else break;\n    steps.push([neu, old]);\n  }\n  return steps;\n}",
  tests:[["rollSteps(2,1,0)","[[1,2],[1,1],[2,1],[2,0]]"],
         ["rollSteps(2,2,0)","[[1,2],[2,2],[2,1],[2,0]]"],
         ["rollSteps(1,1,0)","[[1,1],[1,0]]"],
         ["rollSteps(3,0,1)","[[0,2],[1,2],[1,1],[2,1],[2,0],[3,0]]"]],
  edge:[["rollSteps(1,0,1)","[[0,0],[1,0]]"],
        ["rollSteps(2,0,0)","[]"]],
  ex:"🎯 <code>maxSurge</code> 는 '<b>잠깐 더 띄워도 되는 수</b>', <code>maxUnavailable</code> 은 '<b>잠깐 줄어도 되는 수</b>' 입니다. 이 둘이 배포 중 서비스 용량의 상한과 하한을 정합니다.\n💡 surge 가 있으면 <b>새 파드를 먼저 띄우고</b> 준비되면 구 파드를 내립니다 — 용량이 유지되는 대신 자원이 일시적으로 더 듭니다. 반대로 <code>maxSurge=0, maxUnavailable=1</code> 이면 <b>먼저 줄이고 나중에 늘립니다</b>(테스트 4의 첫 단계가 <code>[0,2]</code> 인 이유) — 자원은 아끼지만 배포 중 실제 용량이 줄어듭니다.\n⚠️ <b>둘 다 0이면 배포가 아예 진행되지 않습니다</b> — 늘릴 수도 줄일 수도 없어 첫 걸음을 못 뗍니다(엣지 케이스가 빈 배열인 이유). 쿠버네티스가 이 조합을 거부하는 이유를 직접 계산해 보면 알 수 있습니다.\n🔧 진짜 무중단은 여기에 <b>readiness probe</b> 와 <b>graceful shutdown</b> 이 더해져야 완성됩니다 — 새 파드가 '준비됨' 을 보고하기 전에 트래픽이 가면 502가, 구 파드가 드레인 없이 죽으면 진행 중 요청이 끊깁니다." },

{ track:"devops", k:"cron 표현식 판정", cat:"internals",
  q:"<b>cron 표현식</b>이 특정 시각에 실행되는지 판정하세요. <code>cronFires(expr, min, hour, dom, mon, dow)</code> 에서 각 필드는 <code>'*'</code>·숫자·<code>'a,b'</code>·<code>'*/n'</code>(0부터 n 간격) 형식입니다. <b>모든 필드가 맞아야</b> 실행됩니다.",
  src:"function cronFires(expr, min, hour, dom, mon, dow) {\n  // TODO: 필드별 매칭\n  return expr.split(' ')[0] === String(min);\n}",
  sol:"function cronFires(expr, min, hour, dom, mon, dow) {\n  const vals = [min, hour, dom, mon, dow];\n  return expr.split(' ').every((f, i) => {\n    const v = vals[i];\n    if (f === '*') return true;\n    if (f.startsWith('*/')) return v % Number(f.slice(2)) === 0;\n    return f.split(',').some((x) => Number(x) === v);\n  });\n}",
  tests:[["cronFires('0 3 * * *', 0, 3, 15, 6, 2)","true"],
         ["cronFires('0 3 * * *', 30, 3, 15, 6, 2)","false"],
         ["cronFires('*/15 * * * *', 30, 9, 1, 1, 1)","true"],
         ["cronFires('0 0,12 * * *', 0, 12, 1, 1, 1)","true"]],
  edge:[["cronFires('*/15 * * * *', 7, 9, 1, 1, 1)","false"],
        ["cronFires('* * * * *', 59, 23, 31, 12, 6)","true"]],
  ex:"🎯 cron 의 다섯 필드는 <b>분·시·일·월·요일</b> 이고, <b>모두 맞아야</b> 실행됩니다 — 하나라도 어긋나면 그 시각은 건너뜁니다. <code>0 3 * * *</code> 이 '매일 새벽 3시' 인 이유입니다.\n💡 <code>*/15</code> 는 '15분마다' 가 아니라 <b>'15로 나누어떨어지는 값'</b> 입니다 — 0·15·30·45분에 돕니다. 만든 시각 기준이 아니라 <b>절대 시각 기준</b>이라, 수백 대의 서버가 같은 표현식을 쓰면 <b>정각에 동시에</b> 몰립니다(thundering herd).\n⚠️ 일(dom)과 요일(dow)을 <b>둘 다 지정하면 OR</b> 로 동작하는 것이 표준 cron 의 유명한 함정입니다 — <code>0 0 1 * 1</code> 은 '1일이면서 월요일' 이 아니라 '1일 <b>또는</b> 월요일' 입니다.\n🔧 서버의 <b>타임존</b>도 사고의 단골입니다. UTC 로 도는 컨테이너에서 '매일 자정' 이 현지 시각 오전 9시가 되고, 서머타임이 있는 지역에서는 하루가 통째로 건너뛰거나 두 번 실행됩니다." },

{ track:"devops", k:"백업 보존 정책 — GFS", cat:"internals",
  q:"<b>백업 보존</b>을 계산하세요. <code>keepBackups(days, policy)</code> 는 경과일 배열(0=오늘)에서 남길 것을 고릅니다 — <b>최근 <code>daily</code> 일 이내는 전부</b>, 그 밖에는 <b><code>weekly</code> 개까지 7의 배수인 날만</b> 남기고 나머지는 지웁니다. 남길 날짜를 오름차순으로 돌려주세요.",
  src:"function keepBackups(days, policy) {\n  // TODO: 최근 daily + 주간 weekly 개\n  return days.slice(0, policy.daily);\n}",
  sol:"function keepBackups(days, policy) {\n  const sorted = days.slice().sort((a, b) => a - b);\n  const keep = sorted.filter((d) => d < policy.daily);\n  let wk = 0;\n  sorted.forEach((d) => {\n    if (d < policy.daily || d % 7 !== 0 || wk >= policy.weekly) return;\n    keep.push(d); wk++;\n  });\n  return keep.sort((a, b) => a - b);\n}",
  tests:[["keepBackups([0,1,2,3,7,14,21],{daily:3,weekly:2})","[0,1,2,7,14]"],
         ["keepBackups([0,1,2,3,4,5],{daily:7,weekly:0})","[0,1,2,3,4,5]"],
         ["keepBackups([7,14,21,28],{daily:0,weekly:2})","[7,14]"],
         ["keepBackups([0,5,10,15],{daily:3,weekly:5})","[0]"]],
  edge:[["keepBackups([],{daily:3,weekly:2})","[]"],
        ["keepBackups([21,7,14],{daily:0,weekly:3})","[7,14,21]"]],
  ex:"🎯 GFS(Grandfather-Father-Son)는 '<b>가까운 과거는 촘촘히, 먼 과거는 성기게</b>' 라는 원칙입니다. 어제 실수는 어제 백업으로, 반년 전 데이터 손상은 월간 백업으로 되돌립니다 — 전부 보관하면 비용이 선형으로 늘고, 최근 것만 두면 늦게 발견한 사고에 대응할 수 없습니다.\n💡 보존 정책의 진짜 질문은 <b>RPO(얼마나 잃어도 되나)</b> 와 <b>RTO(얼마나 빨리 복구해야 하나)</b> 입니다. 이 둘을 정하지 않으면 '넉넉히 두자' 가 되어 비용만 늘고, 정작 필요한 시점의 백업은 없는 경우가 생깁니다.\n⚠️ 백업의 존재보다 중요한 것은 <b>복원 테스트</b>입니다 — 몇 년치를 모아 뒀는데 복원해 보니 스키마가 안 맞거나 암호화 키가 없는 사고가 실제로 흔합니다. '테스트하지 않은 백업은 백업이 아니다' 는 격언 그대로입니다.\n🔧 삭제 자동화는 <b>보수적으로</b> 짜야 합니다 — 이 함수의 버그는 곧 데이터 영구 손실입니다. 실전에서는 삭제 대신 보관 계층 이동(S3 Glacier), 삭제 지연, 객체 잠금(WORM)을 함께 씁니다." },

{ track:"devops", k:"리소스 요청과 스케줄링", cat:"internals",
  q:"파드를 노드에 <b>스케줄링</b>하세요. <code>schedule(nodes, pod)</code> 는 <code>{name, cpu, mem}</code> 여유 노드들 중 <b>파드의 cpu·mem 요청을 모두 수용</b>하는 노드 하나를 고릅니다. 여럿이면 <b>배치 후 남는 cpu 가 가장 적은</b>(꽉 채우는) 노드를, 그래도 같으면 <b>앞선 노드</b>를 고르고, 없으면 <code>null</code>(Pending) 입니다.",
  src:"function schedule(nodes, pod) {\n  // TODO: 수용 가능한 노드 중 가장 빈틈 없는 곳\n  return nodes[0] ? nodes[0].name : null;\n}",
  sol:"function schedule(nodes, pod) {\n  let best = null, bestLeft = Infinity;\n  nodes.forEach((nd) => {\n    if (nd.cpu < pod.cpu || nd.mem < pod.mem) return;\n    const left = nd.cpu - pod.cpu;\n    if (left < bestLeft) { best = nd.name; bestLeft = left; }\n  });\n  return best;\n}",
  tests:[["schedule([{name:'a',cpu:4,mem:8},{name:'b',cpu:2,mem:8}],{cpu:2,mem:4})","'b'"],
         ["schedule([{name:'a',cpu:1,mem:8},{name:'b',cpu:4,mem:2}],{cpu:2,mem:4})","null"],
         ["schedule([{name:'a',cpu:4,mem:8}],{cpu:4,mem:8})","'a'"],
         ["schedule([{name:'a',cpu:3,mem:8},{name:'b',cpu:3,mem:8}],{cpu:1,mem:1})","'a'"]],
  edge:[["schedule([],{cpu:1,mem:1})","null"],
        ["schedule([{name:'a',cpu:2,mem:2}],{cpu:2,mem:3})","null"]],
  ex:"🎯 스케줄러는 <b>requests(요청)</b> 로 자리를 잡습니다 — limits 가 아니라 requests 의 합이 노드 용량을 넘지 않게 배치합니다. 그래서 requests 를 안 적으면 스케줄러가 '<b>0을 요청했다</b>' 고 보고 무한정 밀어 넣습니다.\n💡 '남는 자리가 가장 적은 노드' 를 고르는 것은 <b>빈 포장(bin packing)</b> 전략입니다 — 노드를 꽉 채워 빈 노드를 만들면 오토스케일러가 그 노드를 <b>없앨 수 있어</b> 비용이 줄어듭니다. 반대 전략(가장 여유 있는 노드)은 장애 격리에 유리합니다.\n⚠️ requests 는 <b>예약</b>이고 limits 는 <b>상한</b>입니다. 둘 사이의 차이만큼 오버커밋되어, 모두가 동시에 limits 까지 쓰면 CPU 는 쓰로틀링, <b>메모리는 OOMKill</b> 로 갈립니다 — 메모리는 압축 불가능한 자원이라 봐주지 않습니다.\n🔧 아무 노드에도 안 들어가면 파드는 <b>Pending</b> 으로 남습니다. <code>kubectl describe pod</code> 의 이벤트에 'Insufficient cpu' 처럼 <b>어느 자원이 모자랐는지</b> 정확히 나오니, 짐작하지 말고 그것부터 읽으세요." },

{ track:"devops", k:"CI 파이프라인 실행 순서", cat:"internals",
  q:"CI 잡의 <b>실행 순서와 병렬 그룹</b>을 계산하세요. <code>stages(jobs)</code> 는 <code>{잡이름: [선행 잡들]}</code> 을 받아, <b>동시에 실행할 수 있는 잡들의 묶음</b>을 순서대로 돌려줍니다(각 묶음은 이름 오름차순). 순환이면 <code>null</code> 입니다.",
  src:"function stages(jobs) {\n  // TODO: 선행이 모두 끝난 것끼리 한 묶음\n  return [Object.keys(jobs)];\n}",
  sol:"function stages(jobs) {\n  const done = new Set(), out = [];\n  const names = Object.keys(jobs);\n  while (done.size < names.length) {\n    const ready = names.filter((nm) => !done.has(nm) && jobs[nm].every((d) => done.has(d)));\n    if (!ready.length) return null;\n    ready.sort();\n    out.push(ready);\n    ready.forEach((nm) => done.add(nm));\n  }\n  return out;\n}",
  tests:[["stages({lint:[],test:[],build:['lint','test'],deploy:['build']})","[['lint','test'],['build'],['deploy']]"],
         ["stages({a:[],b:['a'],c:['a']})","[['a'],['b','c']]"],
         ["stages({a:['b'],b:['a']})","null"],
         ["stages({solo:[]})","[['solo']]"]],
  edge:[["stages({})","[]"],
        ["stages({a:[],b:['a'],c:['b'],d:[]})","[['a','d'],['b'],['c']]"]],
  ex:"🎯 CI 의 실행 시간은 <b>가장 긴 경로</b>가 정합니다 — 순차로 늘어놓으면 합이지만, 의존이 없는 잡을 <b>같은 단계에 묶으면</b> 그 단계의 최댓값만 듭니다. lint 와 test 를 나란히 돌리는 것만으로 파이프라인이 눈에 띄게 짧아집니다.\n💡 '선행이 모두 끝난 잡들' 을 한 묶음으로 뽑는 이 계산이 곧 <b>위상 정렬의 레벨 버전</b>입니다. GitHub Actions 의 <code>needs</code>, GitLab 의 <code>stage</code>, Airflow 의 DAG 가 전부 같은 구조입니다.\n⚠️ 의존을 <b>필요 이상으로</b> 걸면 병렬성이 죽습니다 — 'deploy 는 build 다음' 은 진짜 의존이지만 'test 는 lint 다음' 은 대개 습관입니다. 반대로 순환이 생기면 파이프라인은 시작조차 못 하고 즉시 실패해야 합니다.\n🔧 실전에서는 여기에 <b>캐시와 아티팩트</b>가 더해집니다 — 같은 단계의 잡들이 같은 의존성을 각자 설치하면 병렬화의 이득을 설치 시간이 먹습니다. 무엇을 공유하고 무엇을 격리할지가 다음 설계 지점입니다." },

{ track:"devops", k:"블루-그린 전환 판정", cat:"internals",
  q:"<b>블루-그린 배포</b>의 전환 가능 여부를 판정하세요. <code>canSwitch(green)</code> 은 <code>{ready, total, healthChecks, errorRate}</code> 를 받아 <b>모든 인스턴스가 준비되고</b>(ready === total, total &gt; 0), <b>헬스체크가 3회 이상 연속 성공</b>했고, <b>오류율이 1% 미만</b>일 때만 <code>true</code> 입니다. 아니면 <b>실패 사유 문자열</b>을 돌려주세요(위 순서로 첫 사유 하나).",
  src:"function canSwitch(green) {\n  // TODO: 세 조건을 순서대로 검사\n  return green.ready === green.total;\n}",
  sol:"function canSwitch(green) {\n  if (!green.total || green.ready !== green.total) return 'not-ready';\n  if (green.healthChecks < 3) return 'unhealthy';\n  if (green.errorRate >= 0.01) return 'error-rate';\n  return true;\n}",
  tests:[["canSwitch({ready:3,total:3,healthChecks:5,errorRate:0.001})","true"],
         ["canSwitch({ready:2,total:3,healthChecks:5,errorRate:0})","'not-ready'"],
         ["canSwitch({ready:3,total:3,healthChecks:1,errorRate:0})","'unhealthy'"],
         ["canSwitch({ready:3,total:3,healthChecks:5,errorRate:0.05})","'error-rate'"]],
  edge:[["canSwitch({ready:0,total:0,healthChecks:9,errorRate:0})","'not-ready'"],
        ["canSwitch({ready:1,total:1,healthChecks:3,errorRate:0.0099})","true"]],
  ex:"🎯 블루-그린은 <b>전환 스위치</b>가 전부입니다 — 신버전(그린)을 완전히 띄워 검증한 뒤 트래픽을 한 번에 넘깁니다. 롤백도 스위치를 되돌리는 것이라 <b>초 단위</b>이고, 이것이 롤링 업데이트에 없는 장점입니다.\n💡 판정 조건을 <b>코드로 못 박는 것</b>이 핵심입니다. '사람이 보고 괜찮으면 넘긴다' 는 배포 시각(금요일 저녁)과 담당자에 따라 흔들립니다 — 자동 판정이면 조건 자체를 리뷰할 수 있습니다.\n⚠️ <code>total === 0</code> 을 먼저 막지 않으면 <b>인스턴스가 하나도 없는 그린</b>이 '전부 준비됨' 으로 통과합니다(0 === 0). 배포 자동화에서 이런 경계 하나가 전면 장애가 됩니다 — 엣지 케이스가 곧 사고 시나리오입니다.\n🔧 블루-그린의 비용은 <b>두 벌을 동시에</b> 띄우는 것이고, 어려운 부분은 애플리케이션이 아니라 <b>데이터베이스</b>입니다 — 스키마가 양쪽 버전과 모두 호환되어야 롤백이 진짜로 가능합니다(확장-수축 마이그레이션)." },

{ track:"devops", k:"로그 로테이션", cat:"internals",
  q:"<b>로그 로테이션</b>을 구현하세요. <code>rotate(files, maxFiles)</code> 는 현재 파일 목록(<code>['app.log','app.log.1',…]</code>)을 받아 회전 후 목록을 돌려줍니다 — 번호가 <b>큰 것부터 하나씩 올리고</b>, <code>app.log</code> 는 <code>app.log.1</code> 이 되며, <b><code>maxFiles</code> 를 넘는 번호는 삭제</b>됩니다. 새 <code>app.log</code> 는 결과에 포함하지 않습니다. 결과는 번호 오름차순입니다.",
  src:"function rotate(files, maxFiles) {\n  // TODO: 큰 번호부터 올리고 초과분 삭제\n  return files.map((f) => f + '.1');\n}",
  sol:"function rotate(files, maxFiles) {\n  const num = (f) => (f === 'app.log' ? 0 : Number(f.split('.').pop()));\n  return files\n    .map((f) => num(f) + 1)\n    .filter((n) => n <= maxFiles)\n    .sort((a, b) => a - b)\n    .map((n) => 'app.log.' + n);\n}",
  tests:[["rotate(['app.log'],3)","['app.log.1']"],
         ["rotate(['app.log','app.log.1'],3)","['app.log.1','app.log.2']"],
         ["rotate(['app.log','app.log.1','app.log.2','app.log.3'],3)","['app.log.1','app.log.2','app.log.3']"],
         ["rotate(['app.log','app.log.1','app.log.2'],2)","['app.log.1','app.log.2']"]],
  edge:[["rotate([],3)","[]"],
        ["rotate(['app.log'],0)","[]"]],
  ex:"🎯 로그 로테이션이 없으면 디스크가 찹니다 — 그리고 디스크가 차면 <b>로그를 못 쓰는 것으로 끝나지 않습니다</b>. DB 는 쓰기를 거부하고, 임시 파일을 쓰는 모든 프로세스가 실패해 전면 장애가 됩니다.\n💡 회전은 <b>큰 번호부터</b> 처리해야 합니다. 작은 번호부터 올리면 <code>.1 → .2</code> 가 기존 <code>.2</code> 를 덮어써 로그가 사라집니다 — 배열을 제자리에서 옮길 때의 방향 문제와 같은 구조입니다.\n⚠️ 실전의 함정은 <b>열려 있는 파일 핸들</b>입니다. 프로세스가 <code>app.log</code> 를 열어 둔 채 파일 이름만 바꾸면 <b>이름이 바뀐 파일에 계속 씁니다</b>(inode 를 잡고 있으므로) — 새 <code>app.log</code> 는 영원히 비어 있습니다. 그래서 <code>copytruncate</code> 나 <b>SIGHUP 으로 재오픈</b>을 알리는 절차가 필요합니다.\n🔧 컨테이너 환경에서는 앱이 <b>stdout 으로만</b> 쓰고 로테이션은 런타임(도커·containerd)이나 수집기(fluent-bit)에 맡기는 것이 표준입니다 — 앱이 파일 관리를 하지 않는 것이 12-factor 의 권고입니다." },

{ track:"devops", k:"에러 버짓 소진율", cat:"internals",
  q:"<b>에러 버짓</b>을 계산하세요. <code>budget(slo, total, errors, elapsed)</code> 에서 <code>slo</code> 는 목표 성공률(0.999), <code>elapsed</code> 는 기간 경과 비율(0~1)입니다. <code>{used, burn}</code> 을 돌려주세요 — <code>used</code> 는 <b>허용 오류 대비 소진 비율</b>, <code>burn</code> 은 <b><code>used / elapsed</code>(소진 속도)</b>. 요청이 0이거나 경과가 0이면 각각 0 입니다.",
  src:"function budget(slo, total, errors, elapsed) {\n  // TODO: 허용 오류 대비 소진과 속도\n  return { used: errors / total, burn: 1 };\n}",
  sol:"function budget(slo, total, errors, elapsed) {\n  if (!total) return { used: 0, burn: 0 };\n  const allowed = total * (1 - slo);\n  const used = allowed ? errors / allowed : 0;\n  return { used, burn: elapsed ? used / elapsed : 0 };\n}",
  tests:[["[+budget(0.99,1000,5,0.5).used.toFixed(4), +budget(0.99,1000,5,0.5).burn.toFixed(4)]","[0.5,1]"],
         ["[+budget(0.99,1000,10,0.5).used.toFixed(4), +budget(0.99,1000,10,0.5).burn.toFixed(4)]","[1,2]"],
         ["budget(0.99, 1000, 0, 0.5)","{used:0,burn:0}"],
         ["[+budget(0.999,10000,5,0.25).used.toFixed(4), +budget(0.999,10000,5,0.25).burn.toFixed(4)]","[0.5,2]"]],
  edge:[["budget(0.99, 0, 0, 0.5)","{used:0,burn:0}"],
        ["[+budget(0.99,1000,5,0).used.toFixed(4), budget(0.99,1000,5,0).burn]","[0.5,0]"]],
  ex:"🎯 SLO 99.9% 는 '<b>0.1% 는 실패해도 된다</b>' 는 뜻입니다 — 그 0.1% 가 <b>에러 버짓</b>이고, 이것을 예산처럼 쓰는 것이 SRE 의 발상입니다. 버짓이 남으면 과감히 배포하고, 다 쓰면 안정화에 집중합니다.\n💡 <b>소진 속도(burn rate)</b> 가 실제 알람의 기준입니다. burn 이 1이면 기간이 끝날 때 정확히 예산을 다 쓰고, 2면 <b>절반 시점에 소진</b>됩니다 — 절대 오류 수보다 이 비율이 '지금 대응해야 하나' 를 훨씬 잘 말해 줍니다.\n⚠️ 짧은 창의 burn rate 만 보면 <b>순간 스파이크에 매번 깨어나고</b>, 긴 창만 보면 심각한 장애를 늦게 압니다. 그래서 실전에서는 <b>다중 창</b>(예: 1시간 burn &gt; 14 이면 즉시 호출, 6시간 burn &gt; 6 이면 티켓)을 씁니다.\n🔧 요청이 0일 때 0으로 나누는 것을 막는 것이 중요합니다 — 새벽 트래픽 0 구간에서 NaN 이 대시보드를 채우면 <b>알람 신뢰를 잃습니다</b>. 신뢰를 잃은 알람은 없는 것보다 나쁩니다." },

{ track:"devops", k:"환경 변수 우선순위 병합", cat:"internals",
  q:"설정의 <b>우선순위 병합</b>을 구현하세요. <code>mergeConfig(layers)</code> 는 <code>[기본값, 파일, 환경변수, CLI]</code> 순의 객체 배열을 <b>뒤가 앞을 덮도록</b> 병합합니다. 값이 <code>undefined</code> 인 키는 <b>덮지 않고</b>, 값이 객체면 <b>재귀적으로 병합</b>합니다(배열은 통째로 교체).",
  src:"function mergeConfig(layers) {\n  // TODO: 뒤가 앞을 덮되 undefined 는 무시\n  return Object.assign({}, ...layers);\n}",
  sol:"function mergeConfig(layers) {\n  const isObj = (v) => v && typeof v === 'object' && !Array.isArray(v);\n  const two = (a, b) => {\n    const out = Object.assign({}, a);\n    Object.keys(b).forEach((k) => {\n      if (b[k] === undefined) return;\n      out[k] = isObj(out[k]) && isObj(b[k]) ? two(out[k], b[k]) : b[k];\n    });\n    return out;\n  };\n  return layers.reduce(two, {});\n}",
  tests:[["mergeConfig([{port:80},{port:8080}])","{port:8080}"],
         ["mergeConfig([{port:80,host:'a'},{port:undefined}])","{port:80,host:'a'}"],
         ["mergeConfig([{db:{host:'a',port:5432}},{db:{host:'b'}}])","{db:{host:'b',port:5432}}"],
         ["mergeConfig([{tags:['a','b']},{tags:['c']}])","{tags:['c']}"]],
  edge:[["mergeConfig([])","{}"],
        ["mergeConfig([{a:1},{},{b:2}])","{a:1,b:2}"]],
  ex:"🎯 12-factor 앱의 설정 우선순위는 <b>기본값 → 파일 → 환경변수 → 명령행</b> 입니다. 뒤로 갈수록 '더 구체적인 상황' 이라 앞을 덮습니다 — 이 순서가 곧 '어디서 바꿔야 하는가' 의 답입니다.\n💡 <code>undefined</code> 를 건너뛰는 것이 핵심입니다. 환경변수가 <b>설정되지 않은 것</b>과 <b>빈 값으로 설정된 것</b>은 다릅니다 — 구분 없이 <code>Object.assign</code> 하면 설정 안 한 변수가 기본값을 <b>undefined 로 지워 버립니다</b>.\n⚠️ 객체는 재귀 병합하고 <b>배열은 교체</b>하는 것이 실용적 관례입니다. 배열을 이어 붙이면 기본 태그를 지울 방법이 없고, 중복 제거 규칙까지 정해야 해서 예측하기 어려워집니다 — 여러 설정 라이브러리가 이 규칙을 택한 이유입니다.\n🔧 병합 결과를 <b>기동 시 한 번 로그로 남기되</b> 비밀 값은 마스킹하세요. '어느 계층의 값이 최종적으로 이겼는가' 를 못 보는 것이 설정 디버깅이 어려운 첫 번째 이유입니다." },
];
