/* Git 실행형 두 번째 묶음 — 패치·객체·이력·협업 규칙을 계산으로 만든다.
   첫 묶음이 '커밋 그래프와 세 공간' 이었다면, 이쪽은 **주고받는 것**이다 —
   diff 한 덩어리, 객체 이름, 태그와 버전, 브랜치 보호. */
module.exports = [

/* ───────────── 패치를 읽는다 ───────────── */
{ track: "git", k: "헝크 머리를 읽는다 · hunkHeader", cat: "internals",
  q: "<code>@@ -12,7 +12,9 @@</code> 같은 헝크 머리에서 <b>[옛 시작, 옛 줄 수, 새 시작, 새 줄 수]</b> 를 뽑아 주세요. 줄 수가 생략되면 <b>1</b> 입니다. 헝크 머리가 아니면 빈 배열입니다.",
  src: "function hunkHeader(line) {\n  // TODO: 생략된 줄 수를 1 로 채우는 것을 잊지 마세요\n  return [];\n}",
  sol: "function hunkHeader(line) {\n  const m = String(line).match(/^@@ -(\\d+)(?:,(\\d+))? \\+(\\d+)(?:,(\\d+))? @@/);\n  if (!m) return [];\n  return [Number(m[1]), m[2] === undefined ? 1 : Number(m[2]),\n          Number(m[3]), m[4] === undefined ? 1 : Number(m[4])];\n}",
  tests: [['hunkHeader("@@ -12,7 +12,9 @@ func()")', '[12,7,12,9]'],
    ['hunkHeader("@@ -1 +1 @@")', '[1,1,1,1]'],
    ['hunkHeader("@@ -0,0 +1,5 @@")', '[0,0,1,5]'],
    ['hunkHeader("not a hunk")', '[]']],
  edge: [['hunkHeader("@@ -3,0 +4,2 @@")', '[3,0,4,2]'],
    ['hunkHeader("@@ -10 +10,3 @@")', '[10,1,10,3]']],
  ex: "패치를 적용하는 도구가 가장 먼저 하는 일입니다. <b>어느 줄부터 몇 줄을</b> 무엇으로 바꾸는지가 이 한 줄에 들어 있습니다.\n<b>줄 수가 생략되면 1</b> 이라는 규칙을 놓치면 한 줄짜리 변경이 통째로 어긋납니다. 실제 패치에서 아주 흔한 모양이라 이 예외를 빠뜨리면 곧 걸립니다.\n세 번째 테스트의 <code>-0,0</code> 은 <b>새로 만들어진 파일</b>입니다. 옛 쪽에 줄이 하나도 없다는 뜻이라 시작 줄도 0 입니다. 반대로 <code>+0,0</code> 은 파일이 통째로 지워진 경우입니다.\n<code>@@</code> 뒤에 붙는 함수 이름은 사람이 읽으라고 넣어 주는 것이라 적용에는 쓰이지 않습니다 — 그래서 정규식이 그 부분을 보지 않습니다." },

{ track: "git", k: "더하고 뺀 줄을 센다 · patchStats", cat: "impl",
  q: "통합 diff 의 줄 목록을 받아 <b>[더한 줄, 뺀 줄]</b> 을 세어 주세요. <code>+++</code> 와 <code>---</code> 로 시작하는 <b>파일 머리는 세지 않습니다.</b>",
  src: "function patchStats(lines) {\n  // TODO: 파일 머리를 먼저 걸러 내세요\n  return [0, 0];\n}",
  sol: "function patchStats(lines) {\n  let add = 0, del = 0;\n  lines.forEach((L) => {\n    const s = String(L);\n    if (s.indexOf(\"+++\") === 0 || s.indexOf(\"---\") === 0) return;\n    if (s[0] === \"+\") add++;\n    else if (s[0] === \"-\") del++;\n  });\n  return [add, del];\n}",
  tests: [['patchStats(["+++ b/a.js","--- a/a.js","+one","-two","+three"])', '[2,1]'],
    ['patchStats([])', '[0,0]'],
    ['patchStats([" ctx","+a"])', '[1,0]'],
    ['patchStats(["-x","-y","-z"])', '[0,3]']],
  edge: [['patchStats(["+++ b/x","--- a/x"])', '[0,0]'],
    ['patchStats(["++a"])', '[1,0]']],
  ex: "<code>git diff --stat</code> 이 세는 방식입니다. 규칙은 <b>첫 글자 하나</b>뿐이라 놀랄 만큼 단순합니다.\n첫 엣지 케이스가 이 문제의 전부입니다. <b>파일 머리도 <code>+</code>·<code>-</code> 로 시작합니다.</b> 그것을 세면 파일 하나마다 더한 줄과 뺀 줄이 하나씩 부풀려집니다 — 통계가 조금씩 틀리는데 눈에 잘 안 띄어 오래 살아남는 종류의 버그입니다.\n두 번째 엣지 케이스는 <code>++a</code> 처럼 <b>내용 자체가 <code>+</code> 로 시작하는 줄</b>입니다. diff 형식에서는 앞의 한 글자만 표시이고 나머지는 내용이라, 이것은 정상적으로 '더한 줄' 입니다.\n같은 이유로 diff 를 사람이 눈으로 읽을 때도 <b>맨 앞 한 칸</b>만 보면 됩니다. 그 한 칸이 공백이면 바뀌지 않은 줄입니다." },

{ track: "git", k: "요약 한 줄을 만든다 · shortStat", cat: "impl",
  q: "<code>[[파일, 더한 줄, 뺀 줄], …]</code> 를 받아 <code>\"2 files changed, 3 insertions(+), 1 deletion(-)\"</code> 형태로 만들어 주세요. <b>0인 항목은 빼고</b>, 1일 때는 단수형을 씁니다.",
  src: "function shortStat(files) {\n  // TODO: 0인 항목을 빼고, 단수·복수를 가르세요\n  return files.length + \" files changed\";\n}",
  sol: "function shortStat(files) {\n  const add = files.reduce((s, f) => s + f[1], 0);\n  const del = files.reduce((s, f) => s + f[2], 0);\n  const bits = [files.length + \" file\" + (files.length === 1 ? \"\" : \"s\") + \" changed\"];\n  if (add) bits.push(add + \" insertion\" + (add === 1 ? \"\" : \"s\") + \"(+)\");\n  if (del) bits.push(del + \" deletion\" + (del === 1 ? \"\" : \"s\") + \"(-)\");\n  return bits.join(\", \");\n}",
  tests: [['shortStat([["a",3,1]])', '"1 file changed, 3 insertions(+), 1 deletion(-)"'],
    ['shortStat([["a",1,0],["b",2,0]])', '"2 files changed, 3 insertions(+)"'],
    ['shortStat([["a",0,5]])', '"1 file changed, 5 deletions(-)"'],
    ['shortStat([])', '"0 files changed"']],
  edge: [['shortStat([["a",1,1]])', '"1 file changed, 1 insertion(+), 1 deletion(-)"'],
    ['shortStat([["a",0,0]])', '"1 file changed"']],
  ex: "사소해 보이지만 <b>사람이 매일 읽는 줄</b>이라 정확도가 값어치를 합니다. 커밋 목록에서 변경 규모를 한눈에 가늠하는 근거이기 때문입니다.\n0인 항목을 빼는 규칙이 요점입니다. '0 deletions(-)' 이 늘 붙어 있으면 읽는 사람이 그 자리를 무시하게 되고, 그러면 진짜 삭제가 있을 때도 눈에 안 들어옵니다. <b>없는 것은 적지 않는 것</b>이 좋은 요약의 기본입니다.\n마지막 엣지 케이스가 재미있는 경우입니다 — <b>줄 수는 그대로인데 파일은 바뀐</b> 상태입니다. 실행 권한만 바뀌었거나, 파일 이름만 바뀌었거나, 바이너리 파일이 교체된 경우가 여기 해당합니다.\n단수·복수를 가르는 것도 그냥 예의가 아닙니다. '1 files' 처럼 어긋난 문구는 <b>기계가 만든 티</b>가 나서, 읽는 사람이 그 도구를 덜 믿게 됩니다." },

{ track: "git", k: "낱말 단위로 견준다 · wordDiff", cat: "impl",
  q: "문장 두 개를 받아 <b>[더해진 낱말 수, 사라진 낱말 수]</b> 를 세어 주세요. 같은 낱말이 여러 번 나오면 <b>개수만큼</b> 따로 셉니다.",
  src: "function wordDiff(a, b) {\n  // TODO: 겹치는 낱말을 개수까지 맞춰 세어 보세요\n  return [0, 0];\n}",
  sol: "function wordDiff(a, b) {\n  const x = String(a).split(/\\s+/).filter(Boolean);\n  const y = String(b).split(/\\s+/).filter(Boolean);\n  const left = x.slice();\n  let kept = 0;\n  y.forEach((w) => {\n    const i = left.indexOf(w);\n    if (i >= 0) { left.splice(i, 1); kept++; }\n  });\n  return [y.length - kept, x.length - kept];\n}",
  tests: [['wordDiff("the quick fox","the slow fox")', '[1,1]'],
    ['wordDiff("a b","a b")', '[0,0]'],
    ['wordDiff("","a b")', '[2,0]'],
    ['wordDiff("a b","")', '[0,2]']],
  edge: [['wordDiff("a a b","a b")', '[0,1]'], ['wordDiff("","")', '[0,0]']],
  ex: "<code>git diff --word-diff</code> 가 하는 일입니다. 문서나 번역 파일에서는 <b>줄 단위 diff 가 쓸모없어집니다</b> — 낱말 하나만 고쳐도 문단 전체가 바뀐 것으로 보이기 때문입니다.\n<b>개수까지 맞춰 세는 것</b>이 이 문제의 핵심입니다. 집합으로 다루면 첫 엣지 케이스에서 틀립니다 — <code>\"a a b\"</code> 에서 <code>a</code> 하나가 사라진 것을 못 잡습니다. 그래서 찾은 낱말을 목록에서 <b>빼면서</b> 세어야 합니다.\n실제 도구는 여기에 더해 <b>어느 자리에서</b> 바뀌었는지까지 계산합니다(최장 공통 부분 수열). 이 문제는 그중 개수만 세는 간이판이지만, '무엇을 같다고 볼 것인가' 를 정하는 부분은 똑같습니다.\n공백을 어떻게 다룰지도 정해야 합니다. 여기서는 연속 공백을 하나로 보지만, 들여쓰기가 의미를 갖는 파일에서는 그렇게 하면 안 됩니다." },

{ track: "git", k: "패치가 붙는 자리인가 · hunkApplies", cat: "debug",
  q: "파일의 줄 목록과 <b>붙일 시작 줄 번호(1부터)</b>, 그리고 헝크가 전제하는 <b>문맥 줄</b>을 받아, 그 자리에 그대로 맞는지 판정해 주세요.",
  src: "function hunkApplies(lines, start, context) {\n  // TODO: 줄 번호는 1부터인데 배열은 0부터입니다\n  return true;\n}",
  sol: "function hunkApplies(lines, start, context) {\n  return context.every((c, i) => lines[start - 1 + i] === c);\n}",
  tests: [['hunkApplies(["a","b","c"],2,["b","c"])', 'true'],
    ['hunkApplies(["a","b","c"],1,["b"])', 'false'],
    ['hunkApplies(["a"],1,["a"])', 'true'],
    ['hunkApplies(["a","b"],2,["b","c"])', 'false']],
  edge: [['hunkApplies([],1,[])', 'true'], ['hunkApplies(["a"],1,[])', 'true']],
  ex: "패치가 <b>왜 안 붙는지</b>를 설명해 주는 계산입니다. 헝크는 '이 자리에 이런 줄들이 있을 것' 을 전제하는데, 그 전제가 깨지면 적용이 거부됩니다.\n네 번째 테스트가 실제로 가장 흔한 실패입니다. 배열 범위를 넘어선 자리는 <code>undefined</code> 라 어떤 문자열과도 같지 않으므로 자연스럽게 거짓이 됩니다 — 따로 길이를 검사하지 않아도 되는 이유입니다.\n두 번째 테스트는 <b>줄 번호가 1부터</b>라는 것을 잊었을 때 나는 실수를 그대로 보여 줍니다. diff 형식은 사람 기준으로 1부터 세고 배열은 0부터 세는데, 이 하나 차이가 패치를 엉뚱한 자리에 붙입니다.\n실제 도구는 딱 맞지 않을 때 <b>위아래로 조금씩 옮겨 가며</b> 다시 시도합니다(퍼지 매칭). 그래서 가끔 패치가 붙기는 하는데 <b>엉뚱한 자리에</b> 붙는 일이 생기고, 그것이 조용한 사고가 됩니다." },

/* ───────────── 객체와 이름 ───────────── */
{ track: "git", k: "내용이 곧 이름이다 · objectId", cat: "internals",
  q: "종류와 내용을 받아 <code>\"종류 길이\\0내용\"</code> 을 해시한 <b>여덟 자리 16진수</b>를 돌려주세요. 해시 함수는 djb2 를 씁니다 — 시작값 5381, 글자마다 <code>(h * 33) ^ 코드</code>.",
  src: "function objectId(type, content) {\n  // TODO: 머리말(종류·길이·널 바이트)을 붙여 해시하세요\n  return \"\";\n}",
  sol: "function objectId(type, content) {\n  const text = type + \" \" + content.length + \"\\u0000\" + content;\n  let h = 5381;\n  for (let i = 0; i < text.length; i++) {\n    h = ((h * 33) ^ text.charCodeAt(i)) >>> 0;\n  }\n  return h.toString(16).padStart(8, \"0\");\n}",
  tests: [['objectId("blob","hello") === objectId("blob","hello")', 'true'],
    ['objectId("blob","hello") === objectId("blob","world")', 'false'],
    ['objectId("blob","hello") === objectId("tree","hello")', 'false'],
    ['objectId("blob","").length', '8']],
  edge: [['objectId("blob","a").length', '8'],
    ['objectId("blob","ab") === objectId("blob","ba")', 'false']],
  ex: "Git 이 파일을 저장하는 방식의 뼈대입니다. 이름을 정해 두고 내용을 담는 것이 아니라, <b>내용으로 이름을 만듭니다.</b> 그래서 같은 내용은 저장소 어디에 몇 번 나타나도 객체 하나입니다.\n머리말에 <b>종류와 길이</b>를 붙이는 것이 중요합니다. 세 번째 테스트가 그 이유입니다 — 같은 내용이라도 blob 과 tree 는 다른 것이므로 이름도 달라야 합니다. 길이를 넣는 것은 이어 붙인 데이터가 어디서 끝나는지 못 박아 두기 위해서입니다.\n이 성질이 <b>변경 감지</b>도 공짜로 해결합니다. 파일이 바뀌었는지 알려면 내용을 견줄 필요 없이 이름만 견주면 됩니다. `git status` 가 큰 저장소에서도 빠른 이유가 여기 있습니다.\n실제 Git 은 djb2 가 아니라 SHA-1(요즘은 SHA-256 도)을 씁니다. 우연히 같은 이름이 나오면 서로 다른 파일이 하나로 뭉개지므로, <b>충돌이 사실상 없는</b> 해시라야 이 설계가 성립합니다." },

{ track: "git", k: "한 층만 펼친다 · treeList", cat: "internals",
  q: "파일 경로 목록을 받아 <b>맨 윗 층의 항목</b>만 <code>\"이름 종류\"</code> 형태로 사전순으로 돌려주세요. 슬래시가 있으면 <code>tree</code>, 없으면 <code>blob</code> 입니다.",
  src: "function treeList(paths) {\n  // TODO: 첫 슬래시 앞까지만 보세요\n  return [];\n}",
  sol: "function treeList(paths) {\n  const seen = Object.create(null);\n  paths.forEach((raw) => {\n    const s = String(raw);\n    const i = s.indexOf(\"/\");\n    if (i < 0) seen[s] = \"blob\";\n    else seen[s.slice(0, i)] = \"tree\";\n  });\n  return Object.keys(seen).sort().map((k) => k + \" \" + seen[k]);\n}",
  tests: [['treeList(["a.js","src/b.js","src/c.js"])', '["a.js blob","src tree"]'],
    ['treeList([])', '[]'],
    ['treeList(["z.js","a.js"])', '["a.js blob","z.js blob"]'],
    ['treeList(["docs/x/y.md"])', '["docs tree"]']],
  edge: [['treeList(["a","a/b"])', '["a tree"]'],
    ['treeList(["b.js"])', '["b.js blob"]']],
  ex: "Git 의 트리 객체는 <b>한 층만</b> 담습니다. 하위 폴더는 또 다른 트리의 이름을 가리킬 뿐이라, 폴더 구조가 트리들의 사슬로 표현됩니다.\n이 설계 덕분에 <b>바뀌지 않은 폴더는 그대로 재사용</b>됩니다. 깊은 폴더의 파일 하나를 고치면 그 경로 위의 트리들만 새로 만들어지고, 나머지는 이름이 같으므로 이미 있는 객체를 가리킵니다.\n<code>Object.create(null)</code> 을 쓴 이유는 경로 이름이 <code>constructor</code> 나 <code>toString</code> 일 수 있기 때문입니다. 평범한 <code>{}</code> 로는 상속받은 속성과 뒤섞여 엉뚱하게 동작합니다.\n엣지 케이스의 <code>[\"a\", \"a/b\"]</code> 는 Git 에서 <b>실제로는 있을 수 없는</b> 상태입니다 — 같은 이름이 파일이면서 폴더일 수는 없기 때문입니다. 그래도 코드가 무너지지 않고 한쪽으로 정하는 편이 안전합니다." },

{ track: "git", k: "버전을 숫자로 견준다 · semverSort", cat: "impl",
  q: "<code>\"v1.10.0\"</code> 같은 태그 목록을 <b>버전 순서</b>로 정렬해 주세요. 앞의 <code>v</code> 는 있을 수도 없을 수도 있고, 빠진 자리는 0으로 봅니다.",
  src: "function semverSort(tags) {\n  // TODO: 문자열이 아니라 숫자로 견주세요\n  return tags.slice().sort();\n}",
  sol: "function semverSort(tags) {\n  const num = (t) => String(t).replace(/^v/, \"\").split(\".\").map(Number);\n  return tags.slice().sort((a, b) => {\n    const x = num(a), y = num(b);\n    for (let i = 0; i < 3; i++) {\n      if ((x[i] || 0) !== (y[i] || 0)) return (x[i] || 0) - (y[i] || 0);\n    }\n    return 0;\n  });\n}",
  tests: [['semverSort(["v1.10.0","v1.9.0","v1.2.0"])', '["v1.2.0","v1.9.0","v1.10.0"]'],
    ['semverSort(["2.0.0","10.0.0","1.0.0"])', '["1.0.0","2.0.0","10.0.0"]'],
    ['semverSort([])', '[]'],
    ['semverSort(["v1.0.0"])', '["v1.0.0"]']],
  edge: [['semverSort(["v1.0","v1.0.1"])', '["v1.0","v1.0.1"]'],
    ['semverSort(["v0.9.9","v1.0.0"])', '["v0.9.9","v1.0.0"]']],
  ex: "시작 코드의 기본 정렬이 왜 틀리는지가 이 문제의 전부입니다. 문자열로 견주면 <b><code>\"10\"</code> 이 <code>\"9\"</code> 보다 앞에</b> 옵니다 — 첫 글자 <code>1</code> 과 <code>9</code> 를 먼저 보기 때문입니다.\n실제로 <code>v1.10.0</code> 이 <code>v1.9.0</code> 보다 먼저 나오는 릴리스 목록은 흔한 사고입니다. 태그가 열 개를 넘는 순간 드러나는데, 그전까지는 멀쩡해 보여서 늦게 발견됩니다.\n<b>자리마다 숫자로</b> 견주면 해결됩니다. 빠진 자리를 0으로 채우는 규칙 덕분에 <code>v1.0</code> 과 <code>v1.0.1</code> 도 자연스럽게 정렬됩니다.\n실제 시맨틱 버전에는 <code>1.0.0-rc.1</code> 같은 사전 배포 꼬리표가 붙기도 합니다. 그 규칙은 '꼬리표가 있으면 없는 것보다 먼저' 라 여기서 한 단계 더 복잡해집니다 — 다룰 일이 있으면 규칙을 먼저 읽고 시작해야 합니다." },

{ track: "git", k: "가장 가까운 태그로 부른다 · describeVersion", cat: "impl",
  q: "태그 목록 <code>[[이름, 커밋], …]</code> 과 <b>새것부터 늘어놓은</b> 커밋 사슬, 그리고 기준 커밋을 받으세요. 그 커밋부터 <b>과거 쪽으로</b> 가장 먼저 만나는 태그를 찾아, 바로 그 커밋이면 태그 이름을, 아니면 <code>\"태그-거리-g커밋\"</code> 을 돌려줍니다. 없으면 <code>null</code> 입니다.",
  src: "function describeVersion(tags, chain, id) {\n  // TODO: 기준 커밋 자리에서 과거 쪽으로 훑으세요\n  return null;\n}",
  sol: "function describeVersion(tags, chain, id) {\n  const at = chain.indexOf(id);\n  if (at < 0) return null;\n  const byId = Object.create(null);\n  tags.forEach((t) => { byId[t[1]] = t[0]; });\n  for (let i = at; i < chain.length; i++) {\n    if (byId[chain[i]]) {\n      return i === at ? byId[chain[i]]\n                      : byId[chain[i]] + \"-\" + (i - at) + \"-g\" + id;\n    }\n  }\n  return null;\n}",
  tests: [['describeVersion([["v1.0","c3"]],["c1","c2","c3"],"c3")', '"v1.0"'],
    ['describeVersion([["v1.0","c3"]],["c1","c2","c3"],"c1")', '"v1.0-2-gc1"'],
    ['describeVersion([],["c1"],"c1")', 'null'],
    ['describeVersion([["v1.0","c3"]],["c1","c2","c3"],"zz")', 'null']],
  edge: [['describeVersion([["v2","c1"],["v1","c3"]],["c1","c2","c3"],"c2")', '"v1-1-gc2"'],
    ['describeVersion([["v1","c1"]],["c1"],"c1")', '"v1"']],
  ex: "<code>git describe</code> 가 만드는 이름입니다. <b>지금 이 커밋이 어느 릴리스 이후 몇 번째인가</b>를 한 줄로 말해 줍니다. 빌드 산출물에 이 문자열을 박아 두면, 나중에 그 파일만 보고도 어느 소스에서 나왔는지 되짚을 수 있습니다.\n방향이 <b>과거 쪽</b>이라는 점이 요점입니다. 아직 태그가 붙지 않은 최신 커밋에서도 이름을 만들 수 있어야 하기 때문입니다 — 그래서 앞으로 나올 태그가 아니라 이미 지나온 태그를 찾습니다.\n엣지 케이스가 그 방향을 분명히 보여 줍니다. <code>c2</code> 기준으로 <code>v2</code>(<code>c1</code>)는 미래 쪽이라 쓰이지 않고, 과거 쪽의 <code>v1</code>(<code>c3</code>)이 뽑힙니다.\n<code>g</code> 접두사는 'git' 을 뜻합니다. 다른 버전 관리 도구와 섞여 쓰이던 시절의 흔적인데, <b>이 문자열이 커밋 해시라는 표시</b>로 지금도 남아 있습니다." },

{ track: "git", k: "함께 만든 사람을 모은다 · coAuthors", cat: "impl",
  q: "커밋 메시지에서 <code>Co-Authored-By: 이름 &lt;메일&gt;</code> 줄의 <b>메일 주소</b>만 모아 사전순으로 돌려주세요. 같은 주소는 한 번만 담고, 대소문자를 가리지 않습니다.",
  src: "function coAuthors(msg) {\n  // TODO: 줄마다 형식을 확인하고 겹치는 것을 걸러 내세요\n  return [];\n}",
  sol: "function coAuthors(msg) {\n  const out = [];\n  String(msg).split(\"\\n\").forEach((L) => {\n    const m = L.match(/^Co-Authored-By:.*<([^>]+)>/i);\n    if (m && out.indexOf(m[1]) < 0) out.push(m[1]);\n  });\n  return out.sort();\n}",
  tests: [['coAuthors("feat: x\\n\\nCo-Authored-By: A <a@x.com>")', '["a@x.com"]'],
    ['coAuthors("x")', '[]'],
    ['coAuthors("Co-Authored-By: B <b@x>\\nCo-Authored-By: A <a@x>")', '["a@x","b@x"]'],
    ['coAuthors("Co-Authored-By: A <a@x>\\nCo-Authored-By: A2 <a@x>")', '["a@x"]']],
  edge: [['coAuthors("")', '[]'],
    ['coAuthors("co-authored-by: A <a@x>")', '["a@x"]']],
  ex: "짝 프로그래밍이나 여러 사람이 함께 만든 커밋에서 <b>기여를 나눠 기록하는</b> 관행입니다. 플랫폼이 이 줄을 읽어 여러 사람의 기여로 세어 줍니다.\n메일 주소를 기준으로 <b>겹치는 것을 거르는</b> 이유는 네 번째 테스트에 있습니다. 같은 사람이 이름을 다르게 적어도 주소가 같으면 한 사람이므로, 이름이 아니라 주소로 판단해야 합니다.\n마지막 엣지 케이스의 <code>i</code> 플래그가 없으면 소문자로 적힌 줄을 놓칩니다. 사람이 손으로 적는 줄이라 대소문자가 제각각인 것이 정상이고, <b>사람 입력을 다루는 코드는 늘 이 여유를 두어야</b> 합니다.\n형식이 정해져 있다는 점이 중요합니다. 커밋 메시지는 자유 문장이지만, 이렇게 <b>기계가 읽는 줄</b>을 규칙으로 정해 두면 자유 문장과 구조를 한 곳에 담을 수 있습니다." },

/* ───────────── 이력을 고른다 ───────────── */
{ track: "git", k: "저쪽에 없는 것만 · cherryPickable", cat: "impl",
  q: "<code>\"해시 제목\"</code> 형태의 커밋 목록 둘을 받아, <b>앞 목록에만 있는</b> 커밋을 원래 순서로 돌려주세요. 같은지는 <b>제목</b>으로 판단합니다(해시는 다를 수 있습니다).",
  src: "function cherryPickable(a, b) {\n  // TODO: 해시 말고 제목으로 견주세요\n  return a;\n}",
  sol: "function cherryPickable(a, b) {\n  const subj = (s) => String(s).slice(String(s).indexOf(\" \") + 1);\n  const have = b.map(subj);\n  return a.filter((x) => have.indexOf(subj(x)) < 0);\n}",
  tests: [['cherryPickable(["a1 fix null","a2 add log"],["b9 fix null"])', '["a2 add log"]'],
    ['cherryPickable(["a1 x"],["b1 x"])', '[]'],
    ['cherryPickable(["a1 x"],[])', '["a1 x"]'],
    ['cherryPickable([],["b1 x"])', '[]']],
  edge: [['cherryPickable(["a1 x y"],["b1 x y"])', '[]'],
    ['cherryPickable(["a1 x"],["b1 X"])', '["a1 x"]']],
  ex: "<code>git cherry</code> 가 하는 판단입니다. 같은 변경이 이미 저쪽에 들어갔는지 보려는 것인데, <b>해시로는 알 수 없습니다</b> — 체리픽하거나 리베이스하면 같은 변경이라도 해시가 달라지기 때문입니다.\n그래서 <b>내용으로 견줍니다.</b> 이 문제는 제목으로 간단히 했지만, 실제 Git 은 변경 내용 자체를 해시한 값(patch-id)을 씁니다. 제목만 보면 '오타 수정' 같은 흔한 제목이 서로 다른 변경인데도 같다고 판정됩니다.\n마지막 엣지 케이스는 <b>대소문자를 가린다</b>는 것을 못 박습니다. 사람이 보기에는 같은 제목이지만 규칙은 규칙대로 동작해야 하고, 그 규칙을 문서에 적어 두어야 합니다.\n릴리스 브랜치에 급한 수정만 골라 넣을 때 이 계산이 필요합니다. <b>이미 들어간 것을 또 넣으면</b> 충돌이 나거나 조용히 두 번 적용됩니다." },

{ track: "git", k: "여러 커밋을 하나로 · squashMessage", cat: "impl",
  q: "커밋 메시지 목록을 받아 합칠 메시지의 <b>줄 배열</b>을 만들어 주세요. 첫 메시지의 첫 줄이 제목이 되고, 나머지는 <code>\"* 첫 줄\"</code> 로 뒤에 붙습니다. 빈 목록은 빈 배열입니다.",
  src: "function squashMessage(msgs) {\n  // TODO: 각 메시지의 첫 줄만 씁니다\n  return msgs;\n}",
  sol: "function squashMessage(msgs) {\n  if (!msgs.length) return [];\n  const out = [String(msgs[0]).split(\"\\n\")[0]];\n  msgs.slice(1).forEach((m) => out.push(\"* \" + String(m).split(\"\\n\")[0]));\n  return out;\n}",
  tests: [['squashMessage(["feat: 결제","fix: 오타","fix: 널 처리"])', '["feat: 결제","* fix: 오타","* fix: 널 처리"]'],
    ['squashMessage(["only"])', '["only"]'],
    ['squashMessage([])', '[]'],
    ['squashMessage(["a\\nbody","b"])', '["a","* b"]']],
  edge: [['squashMessage(["x","y\\nz"])', '["x","* y"]'],
    ['squashMessage(["",""])', '["","* "]']],
  ex: "여러 커밋을 하나로 합칠 때 만들어지는 메시지의 모양입니다. 작업 도중의 '오타 수정', 'wip' 같은 커밋들을 <b>하나의 뜻 있는 커밋</b>으로 묶는 일이 흔합니다.\n<b>첫 줄만 쓰는 것</b>이 규칙인 이유는 커밋 메시지의 구조 때문입니다. 첫 줄은 제목이고 빈 줄 뒤부터가 본문인데, 합칠 때 본문까지 전부 가져오면 읽을 수 없는 덩어리가 됩니다.\n합치는 것이 늘 옳지는 않습니다. <b>따로 되돌릴 수 있어야 하는 변경</b>이라면 커밋도 따로 두는 편이 낫습니다. 합치면 그중 하나만 골라 되돌릴 수 없게 됩니다.\n마지막 엣지 케이스처럼 빈 메시지가 섞이면 <code>\"* \"</code> 같은 빈 항목이 남습니다. 실무 도구는 이런 줄을 걸러 내는데, <b>걸러 낼지 남길지를 정하는 것</b>도 규칙의 일부입니다." },

{ track: "git", k: "다음 버전은 무엇인가 · conventionalBump", cat: "impl",
  q: "커밋 제목 목록을 받아 올려야 할 자리를 돌려주세요. <code>!</code> 가 붙었거나 <code>BREAKING CHANGE</code> 가 있으면 <code>\"major\"</code>, <code>feat:</code> 가 있으면 <code>\"minor\"</code>, <code>fix:</code> 가 있으면 <code>\"patch\"</code>, 아니면 <code>\"none\"</code> 입니다.",
  src: "function conventionalBump(msgs) {\n  // TODO: 가장 큰 것이 이깁니다\n  return \"patch\";\n}",
  sol: "function conventionalBump(msgs) {\n  let out = \"none\";\n  msgs.forEach((m) => {\n    const s = String(m);\n    if (/^[a-z]+(\\(.+\\))?!:/.test(s) || s.indexOf(\"BREAKING CHANGE\") >= 0) out = \"major\";\n    else if (out !== \"major\" && /^feat(\\(.+\\))?:/.test(s)) out = \"minor\";\n    else if (out === \"none\" && /^fix(\\(.+\\))?:/.test(s)) out = \"patch\";\n  });\n  return out;\n}",
  tests: [['conventionalBump(["fix: a"])', '"patch"'],
    ['conventionalBump(["fix: a","feat: b"])', '"minor"'],
    ['conventionalBump(["feat: b","feat!: c"])', '"major"'],
    ['conventionalBump(["docs: x"])', '"none"']],
  edge: [['conventionalBump([])', '"none"'],
    ['conventionalBump(["chore: x","BREAKING CHANGE: y"])', '"major"']],
  ex: "커밋 메시지에 <b>형식을 정해 두면</b> 다음 버전 번호를 사람이 정하지 않아도 됩니다. 릴리스 자동화의 출발점입니다.\n<b>가장 큰 것이 이긴다</b>는 규칙이 요점입니다. 한 릴리스에 수정과 기능과 깨는 변경이 섞여 있으면, 사용자에게 가장 큰 영향을 주는 것을 기준으로 삼아야 합니다.\n순서에 상관없이 같은 답이 나오는 것도 중요합니다. 세 번째 테스트에서 <code>feat</code> 를 먼저 보고 <code>feat!</code> 를 나중에 봐도 <code>major</code> 가 되어야 하는데, 그래서 <code>major</code> 로 정해진 뒤에는 낮추지 않도록 조건을 걸었습니다.\n이 방식의 진짜 값어치는 <b>변경 로그가 저절로 만들어지는 것</b>입니다. 형식이 정해져 있으면 어떤 커밋이 사용자에게 보일 항목인지 기계가 골라낼 수 있습니다 — 사람이 릴리스 노트를 다시 쓰지 않아도 됩니다." },

{ track: "git", k: "몇 번 만에 찾는가 · bisectSteps", cat: "impl",
  q: "의심되는 커밋이 <code>n</code> 개일 때 이분 탐색으로 범인을 찾는 데 필요한 <b>최대 확인 횟수</b>를 구해 주세요. 1개 이하면 0입니다.",
  src: "function bisectSteps(n) {\n  // TODO: 반씩 줄여 가며 몇 번인지 세어 보세요\n  return n;\n}",
  sol: "function bisectSteps(n) {\n  if (n <= 1) return 0;\n  let steps = 0, left = n;\n  while (left > 1) {\n    left = Math.ceil(left / 2);\n    steps++;\n  }\n  return steps;\n}",
  tests: [['bisectSteps(1)', '0'],
    ['bisectSteps(2)', '1'],
    ['bisectSteps(8)', '3'],
    ['bisectSteps(1000)', '10']],
  edge: [['bisectSteps(0)', '0'], ['bisectSteps(1024)', '10']],
  ex: "<code>git bisect</code> 가 얼마나 값싼지를 보여 주는 숫자입니다. 커밋 <b>1,000개에서 열 번</b>이면 찾습니다.\n하나씩 되짚으면 최악의 경우 1,000번을 확인해야 합니다. 반씩 줄이면 그 수가 <b>로그로</b> 줄어드는데, 이 차이가 '못 할 일' 과 '한 시간이면 되는 일' 을 가릅니다.\n네 번째 테스트와 엣지 케이스를 나란히 보면 규모의 감이 잡힙니다. 1,000개도 1,024개도 열 번입니다 — <b>커밋이 두 배가 되어도 한 번만 늘어납니다.</b>\n실전에서 이 값어치를 쓰려면 <b>좋은지 나쁜지 자동으로 판정하는 명령</b>이 있어야 합니다. `git bisect run` 에 그 명령을 주면 열 번의 확인을 사람 없이 끝냅니다 — 재현 스크립트를 먼저 만드는 것이 언제나 첫 단계인 이유입니다." },

{ track: "git", k: "지나온 자리를 짚는다 · reflogAt", cat: "debug",
  q: "reflog 항목 목록(새것이 앞)과 <code>\"HEAD@{2}\"</code> 형태의 지정자를 받아 그 항목을 돌려주세요. 형식이 다르거나 범위를 넘으면 <code>null</code> 입니다.",
  src: "function reflogAt(entries, spec) {\n  // TODO: HEAD@{숫자} 형식만 받아들이세요\n  return entries[0];\n}",
  sol: "function reflogAt(entries, spec) {\n  const m = String(spec).match(/^HEAD@\\{(\\d+)\\}$/);\n  if (!m) return null;\n  const i = Number(m[1]);\n  return i < entries.length ? entries[i] : null;\n}",
  tests: [['reflogAt(["a1","b2","c3"],"HEAD@{0}")', '"a1"'],
    ['reflogAt(["a1","b2","c3"],"HEAD@{2}")', '"c3"'],
    ['reflogAt(["a1"],"HEAD@{5}")', 'null'],
    ['reflogAt(["a1"],"main@{0}")', 'null']],
  edge: [['reflogAt([],"HEAD@{0}")', 'null'],
    ['reflogAt(["x"],"HEAD@{00}")', '"x"']],
  ex: "잃어버린 커밋을 되살릴 때 쓰는 지정자입니다. <code>HEAD@{0}</code> 은 지금, <code>HEAD@{2}</code> 는 <b>두 번 전에 HEAD 가 있던 자리</b>입니다.\n<code>reset --hard</code> 로 날린 커밋도 여기 남아 있습니다. 커밋은 지워진 것이 아니라 <b>가리키는 이름이 없어졌을 뿐</b>이라, 해시를 찾아 브랜치를 붙이면 그대로 돌아옵니다.\n네 번째 테스트가 <code>main@{0}</code> 을 거부하는 것은 이 문제의 규칙일 뿐입니다. 실제 Git 은 브랜치마다 reflog 를 따로 두어 <code>main@{0}</code> 도 유효합니다 — 형식을 어디까지 받아들일지는 <b>정하고 문서에 적어야</b> 하는 종류의 결정입니다.\n한 가지 주의할 점은 reflog 가 <b>로컬에만 있다</b>는 것입니다. 다른 사람의 저장소에는 내 reflog 가 없고, 보관 기간도 무한하지 않으므로 <b>알아챘을 때 바로</b> 확인해야 합니다." },

/* ───────────── 협업의 규칙 ───────────── */
{ track: "git", k: "이름만 바뀐 것인가 · detectRename", cat: "impl",
  q: "<b>생긴 파일</b>과 <b>사라진 파일</b>의 목록(각각 <code>[경로, 줄 배열]</code>)과 기준 비율을 받아, 내용이 그만큼 겹치는 짝을 <code>[사라진 경로, 생긴 경로]</code> 로 돌려주세요. 비율은 <b>겹치는 줄 ÷ 더 긴 쪽의 줄 수 × 100</b> 입니다.",
  src: "function detectRename(added, removed, pct) {\n  // TODO: 사라진 파일마다 가장 닮은 것을 찾으세요\n  return [];\n}",
  sol: "function detectRename(added, removed, pct) {\n  const out = [];\n  removed.forEach((r) => {\n    let best = null, score = 0;\n    added.forEach((a) => {\n      const same = r[1].filter((x) => a[1].indexOf(x) >= 0).length;\n      const sim = same / Math.max(r[1].length, a[1].length, 1) * 100;\n      if (sim > score) { score = sim; best = a[0]; }\n    });\n    if (best && score >= pct) out.push([r[0], best]);\n  });\n  return out.sort();\n}",
  tests: [['detectRename([["new.js",["a","b","c"]]],[["old.js",["a","b","c"]]],50)', '[["old.js","new.js"]]'],
    ['detectRename([["new.js",["x"]]],[["old.js",["a","b","c"]]],50)', '[]'],
    ['detectRename([],[["old.js",["a"]]],50)', '[]'],
    ['detectRename([["n.js",["a","b"]]],[["o.js",["a","b","c","d"]]],50)', '[["o.js","n.js"]]']],
  edge: [['detectRename([["n",["a"]]],[["o",["a"]]],100)', '[["o","n"]]'],
    ['detectRename([["n",["a","b"]]],[["o",["a","c"]]],60)', '[]']],
  ex: "Git 은 파일 이름 변경을 <b>기록하지 않습니다.</b> 커밋에는 '이 파일이 사라지고 저 파일이 생겼다' 만 남고, 이름이 바뀐 것인지는 나중에 <b>내용을 견줘 짐작</b>합니다.\n이 설계가 낯설지만 이득이 큽니다. 이름 변경을 따로 기록하면 그 기록이 틀릴 수 있는데, 내용으로 판단하면 <b>이름과 내용이 함께 바뀐 경우</b>도 자연히 다뤄집니다.\n기준 비율이 판단을 바꾼다는 것이 마지막 엣지 케이스입니다. 절반이 같은 두 파일을 '이름 변경' 으로 볼지 '삭제와 생성' 으로 볼지는 정답이 없어, Git 도 이 값을 옵션으로 열어 둡니다(<code>-M50%</code> 이 기본).\n판정이 달라지면 <b>이력 추적도 달라집니다.</b> 이름 변경으로 보면 `git log --follow` 가 옛 이름 시절까지 따라가고, 아니면 파일이 그 시점에 태어난 것으로 보입니다." },

{ track: "git", k: "이 줄은 누가 · blameAt", cat: "impl",
  q: "<code>[[커밋, [바꾼 줄 번호…]], …]</code> 를 <b>오래된 것부터</b> 받아, 어떤 줄을 <b>마지막으로 건드린</b> 커밋을 돌려주세요. 아무도 건드리지 않았으면 <code>null</code> 입니다.",
  src: "function blameAt(history, line) {\n  // TODO: 마지막으로 건드린 것이 답입니다\n  return history.length ? history[0][0] : null;\n}",
  sol: "function blameAt(history, line) {\n  let who = null;\n  history.forEach((h) => { if (h[1].indexOf(line) >= 0) who = h[0]; });\n  return who;\n}",
  tests: [['blameAt([["c1",[1,2]],["c2",[2,3]]],2)', '"c2"'],
    ['blameAt([["c1",[1,2]],["c2",[3]]],1)', '"c1"'],
    ['blameAt([["c1",[1]]],9)', 'null'],
    ['blameAt([],1)', 'null']],
  edge: [['blameAt([["c1",[5]],["c2",[5]],["c3",[6]]],5)', '"c2"'],
    ['blameAt([["c1",[0]]],0)', '"c1"']],
  ex: "<code>git blame</code> 이 답하는 질문입니다. 이름과 달리 <b>탓하려고</b> 쓰는 도구가 아니라, '이 줄이 왜 이렇게 되었는지' 를 되짚어 그 커밋의 메시지와 연결된 이슈를 찾으려고 씁니다.\n<b>마지막으로 건드린 것</b>이 답이라는 점이 중요합니다. 첫 엣지 케이스에서 <code>c3</code> 가 가장 최근이지만 5번 줄을 건드리지 않았으므로 답이 아닙니다.\n이 도구의 한계도 알아 둘 값어치가 있습니다. 들여쓰기를 바꾸거나 코드를 옮기기만 한 커밋이 <b>모든 줄의 마지막 수정자</b>가 되어 진짜 이력을 가립니다. 그래서 공백 변경을 무시하는 옵션(<code>-w</code>)이나 옮겨진 줄을 따라가는 옵션(<code>-C</code>)이 있습니다.\n포맷터를 처음 적용한 커밋처럼 <b>대량 변경 커밋</b>을 blame 에서 건너뛰도록 목록에 적어 두는 기능도 있습니다 — 그런 커밋 하나가 이력 전체를 못 쓰게 만들기 때문입니다." },

{ track: "git", k: "이 파일을 건드린 커밋 · fileHistory", cat: "impl",
  q: "<code>[[커밋, [바뀐 파일…]], …]</code> 와 경로를 받아 그 파일을 건드린 커밋만 <b>원래 순서로</b> 돌려주세요. 경로는 <b>정확히 같아야</b> 합니다.",
  src: "function fileHistory(commits, target) {\n  // TODO: 부분 일치가 아니라 정확히 같은 경로만 봅니다\n  return commits.map((c) => c[0]);\n}",
  sol: "function fileHistory(commits, target) {\n  return commits.filter((c) => c[1].indexOf(target) >= 0).map((c) => c[0]);\n}",
  tests: [['fileHistory([["c1",["a.js"]],["c2",["b.js","a.js"]]],"a.js")', '["c1","c2"]'],
    ['fileHistory([["c1",["a.js"]]],"z.js")', '[]'],
    ['fileHistory([],"a")', '[]'],
    ['fileHistory([["c1",["src/a.js"]]],"src/a.js")', '["c1"]']],
  edge: [['fileHistory([["c1",["a.js"]]],"a")', '[]'],
    ['fileHistory([["c1",[]],["c2",["a"]]],"a")', '["c2"]']],
  ex: "<code>git log -- 경로</code> 가 하는 걸러 내기입니다. 파일 하나의 이력만 보면 <b>왜 이렇게 되었는지</b>를 훨씬 빨리 알 수 있습니다.\n첫 엣지 케이스가 중요한 함정입니다. 경로를 <b>부분 일치</b>로 견주면 <code>\"a\"</code> 가 <code>\"a.js\"</code>·<code>\"data/a\"</code>·<code>\"main.java\"</code> 까지 걸어 버립니다. 정확히 같은지 보거나, 폴더라면 <code>\"경로/\"</code> 로 시작하는지 보아야 합니다.\n두 번째 엣지 케이스의 <b>파일을 하나도 바꾸지 않은 커밋</b>은 실제로 있습니다 — 빈 커밋이나 병합 커밋이 그렇습니다. 코드가 무너지지 않아야 합니다.\n실제 Git 은 여기에 더해 <b>이름이 바뀌기 전까지</b> 따라갈 수 있습니다(<code>--follow</code>). 앞의 detectRename 이 그 판정을 맡는데, 짐작이라 가끔 놓친다는 점은 알고 써야 합니다." },

{ track: "git", k: "오래 묵은 브랜치 · staleBranches", cat: "review",
  q: "<code>[[이름, 마지막 커밋 날짜], …]</code> 와 오늘 날짜, 기준 일수를 받아 <b>기준을 넘게 묵은</b> 브랜치 이름을 사전순으로 돌려주세요. 날짜는 정수 일수입니다.",
  src: "function staleBranches(branches, today, days) {\n  // TODO: '넘는다' 와 '같다' 를 가르세요\n  return branches.map((b) => b[0]);\n}",
  sol: "function staleBranches(branches, today, days) {\n  return branches.filter((b) => today - b[1] > days).map((b) => b[0]).sort();\n}",
  tests: [['staleBranches([["old",10],["new",100]],110,60)', '["old"]'],
    ['staleBranches([["a",50]],100,60)', '[]'],
    ['staleBranches([],100,60)', '[]'],
    ['staleBranches([["z",1],["a",2]],200,60)', '["a","z"]']],
  edge: [['staleBranches([["x",40]],100,60)', '[]'],
    ['staleBranches([["x",39]],100,60)', '["x"]']],
  ex: "브랜치는 <b>늘어나기만 하고 줄지 않는</b> 성질이 있습니다. 병합된 뒤에도 지우지 않으면 목록이 수백 개가 되어, 정작 필요한 브랜치를 찾기 어려워집니다.\n엣지 케이스 두 개가 <b>경계</b>를 못 박습니다. 딱 60일 된 것은 포함되지 않고 61일부터 포함됩니다. 이런 기준은 <code>&gt;</code> 와 <code>&gt;=</code> 중 무엇을 쓸지 정하고 <b>적어 두어야</b> 나중에 다투지 않습니다.\n다만 오래되었다고 지워도 되는 것은 아닙니다. <b>병합되지 않은 브랜치</b>에는 아직 살아 있는 작업이 들어 있을 수 있어, 실무에서는 '병합됨 + 오래됨' 둘을 함께 봅니다.\n지우기 전에 <b>알리는 단계</b>를 두는 것도 흔합니다. 목록을 만들어 주인에게 보내고, 응답이 없으면 그때 정리합니다 — 되살릴 수는 있지만 아무도 그 사실을 모르는 것이 문제이기 때문입니다." },

{ track: "git", k: "보호 규칙에 걸리는가 · protectionCheck", cat: "security",
  q: "규칙 <code>[리뷰 필수, 검사 필수, 강제 푸시 허용]</code> 과 시도 <code>[리뷰 수, 검사 통과, 강제 여부]</code> 를 받아, 막히면 <b>이유</b>를, 통과하면 <b>빈 문자열</b>을 돌려주세요. 확인 순서는 리뷰 → 검사 → 강제입니다.",
  src: "function protectionCheck(rules, push) {\n  // TODO: 정해진 순서대로 확인하세요\n  return \"\";\n}",
  sol: "function protectionCheck(rules, push) {\n  if (rules[0] && !push[0]) return \"리뷰 승인이 없다\";\n  if (rules[1] && !push[1]) return \"필수 검사가 통과하지 않았다\";\n  if (!rules[2] && push[2]) return \"강제 푸시가 금지되어 있다\";\n  return \"\";\n}",
  tests: [['protectionCheck([true,true,false],[1,true,false])', '""'],
    ['protectionCheck([true,true,false],[0,true,false])', '"리뷰 승인이 없다"'],
    ['protectionCheck([true,true,false],[1,false,false])', '"필수 검사가 통과하지 않았다"'],
    ['protectionCheck([true,true,false],[1,true,true])', '"강제 푸시가 금지되어 있다"']],
  edge: [['protectionCheck([false,false,true],[0,false,true])', '""'],
    ['protectionCheck([false,true,false],[0,false,false])', '"필수 검사가 통과하지 않았다"']],
  ex: "브랜치 보호 규칙이 하는 판정입니다. 규칙 자체는 단순한데, <b>어디에 설정하느냐</b>를 헷갈리기 쉽습니다 — 검사를 돌리는 것은 워크플로 파일이지만 그것을 <b>필수로 만드는 것</b>은 저장소 설정입니다.\n<b>확인 순서를 정해 두는 것</b>이 실무에서 중요합니다. 여러 이유로 막혔을 때 어느 것을 먼저 알려 줄지가 정해져 있어야, 사람이 하나씩 고쳐 나갈 수 있습니다. 전부 한꺼번에 쏟아 내면 오히려 읽지 않습니다.\n마지막 엣지 케이스가 규칙의 독립성을 보여 줍니다. 리뷰는 필수가 아니라 리뷰 0개로도 통과하지만, 검사는 필수라 거기서 막힙니다.\n규칙을 관리자에게도 적용할지가 늘 논쟁거리입니다. 예외를 두면 급할 때 편하지만, <b>급할 때가 사고가 가장 잘 나는 때</b>라 예외를 두지 않는 팀이 많습니다." },
];
