/* Git 실행형 — Git 의 동작을 직접 모델링해 본다.
   커밋 그래프는 부모 링크를 가진 노드 목록, 파일은 이름→내용 맵으로 다룬다.
   '브랜치는 포인터', '충돌은 같은 줄을 다르게 고친 것', 'diff 는 계산된다' 를
   설명으로 읽는 대신 손으로 만들어 확인한다. */
module.exports = [

/* ───────────── 커밋 그래프 ───────────── */
{ track: "git", k: "커밋 역사 거슬러 오르기 · historyOf", cat: "internals",
  q: "커밋 목록은 <code>{id, ps}</code> 배열이고 <code>ps</code> 는 부모 id 배열입니다. <code>head</code> 에서 <b>첫 번째 부모만</b> 따라 뿌리까지 올라간 id 배열을 돌려주세요.",
  src: "function historyOf(commits, head) {\n  // TODO: id 로 빨리 찾을 수 있게 만든 뒤 부모를 따라 올라가세요\n  return [];\n}",
  sol: "function historyOf(commits, head) {\n  const byId = new Map(commits.map((c) => [c.id, c]));\n  const out = [];\n  let cur = head;\n  while (cur && byId.has(cur)) {\n    out.push(cur);\n    cur = byId.get(cur).ps[0] || null;\n  }\n  return out;\n}",
  tests: [['historyOf([{id:"a",ps:[]},{id:"b",ps:["a"]},{id:"c",ps:["b"]}],"c")', '["c","b","a"]'],
    ['historyOf([{id:"a",ps:[]},{id:"b",ps:["a"]}],"b")', '["b","a"]'],
    ['historyOf([{id:"a",ps:[]},{id:"m",ps:["a","b"]},{id:"b",ps:["a"]}],"m")', '["m","a"]'],
    ['historyOf([{id:"a",ps:[]}],"a")', '["a"]']],
  edge: [['historyOf([],"a")', '[]'], ['historyOf([{id:"a",ps:[]}],"zzz")', '[]']],
  ex: "<code>git log</code> 가 하는 일이 정확히 이것입니다. 커밋은 <b>부모를 가리키는 링크</b>를 갖고 있고, 로그는 그 링크를 거슬러 오르며 출력합니다.\n<b>첫 번째 부모만</b> 따라가는 것이 세 번째 테스트의 요점입니다. 병합 커밋은 부모가 둘인데, 첫 부모는 '병합해 들어간 쪽'(대개 <code>main</code>)입니다. <code>git log --first-parent</code> 는 이렇게 걸어 <b>주 줄기만</b> 보여 줍니다.\n방향에 주의하세요. 커밋은 <b>부모를 가리킬 뿐 자식을 모릅니다</b>. 그래서 '이 커밋 다음에 뭐가 왔나' 는 전체를 훑어야 알 수 있고, 반대로 '조상은 누구인가' 는 즉시 답할 수 있습니다.\n뿌리 커밋의 <code>ps</code> 는 빈 배열이라 <code>ps[0]</code> 이 <code>undefined</code> 가 되고 반복이 끝납니다. 이 자연스러운 종료가 링크드 리스트의 <code>null</code> 종료와 같은 구조입니다." },

{ track: "git", k: "조상인지 판정 · isAncestor", cat: "internals",
  q: "커밋 <code>a</code> 가 <code>b</code> 에서 <b>부모를 따라 닿을 수 있는 커밋</b>인지 판정해 주세요. 병합 커밋의 부모가 둘이므로 모든 부모를 봐야 합니다. 자기 자신은 조상으로 봅니다.",
  src: "function isAncestor(commits, a, b) {\n  // TODO: b 에서 시작해 모든 부모 방향으로 훑으세요\n  return false;\n}",
  sol: "function isAncestor(commits, a, b) {\n  const byId = new Map(commits.map((c) => [c.id, c]));\n  const seen = new Set();\n  const stack = [b];\n  while (stack.length) {\n    const id = stack.pop();\n    if (id === a) return true;\n    if (seen.has(id) || !byId.has(id)) continue;\n    seen.add(id);\n    byId.get(id).ps.forEach((p) => stack.push(p));\n  }\n  return false;\n}",
  tests: [['isAncestor([{id:"a",ps:[]},{id:"b",ps:["a"]},{id:"c",ps:["b"]}],"a","c")', "true"],
    ['isAncestor([{id:"a",ps:[]},{id:"b",ps:["a"]},{id:"c",ps:["b"]}],"c","a")', "false"],
    ['isAncestor([{id:"a",ps:[]},{id:"b",ps:["a"]},{id:"m",ps:["a","b"]}],"b","m")', "true"],
    ['isAncestor([{id:"a",ps:[]},{id:"x",ps:[]}],"x","a")', "false"]],
  edge: [['isAncestor([{id:"a",ps:[]}],"a","a")', "true"], ['isAncestor([],"a","b")', "false"]],
  ex: "이 판정 하나가 Git 의 여러 동작을 결정합니다. <b>fast-forward 가 가능한가</b>, <b>이 브랜치는 이미 병합됐는가</b>(<code>git branch --merged</code>), <b>태그가 이 릴리스에 포함됐는가</b>가 전부 같은 질문입니다.\n<code>seen</code> 집합이 필요한 이유는 병합 때문입니다. 부모가 둘인 커밋에서 갈라진 두 길이 다시 만나면 같은 커밋을 여러 번 방문하게 되고, 큰 저장소에서는 그 중복이 지수로 불어납니다.\n자기 자신을 조상으로 볼지는 <b>정의의 문제</b>입니다. Git 의 <code>merge-base --is-ancestor</code> 도 같은 커밋이면 참을 돌려줍니다 — 그래야 '이미 최신이다' 를 자연스럽게 판정할 수 있습니다.\n네 번째 테스트처럼 <b>서로 이어지지 않은</b> 두 뿌리가 있을 수 있습니다. 저장소를 합쳤을 때 실제로 생기고, 그때 <code>git merge</code> 는 <code>--allow-unrelated-histories</code> 를 요구합니다." },

{ track: "git", k: "공통 조상 찾기 · mergeBase", cat: "internals",
  q: "두 커밋의 <b>공통 조상 중 <code>b</code> 쪽에서 가장 가까운 것</b>의 id 를 돌려주세요. 없으면 <code>null</code> 입니다. 이것이 3-way 병합의 기준점입니다.",
  src: "function mergeBase(commits, a, b) {\n  // TODO: a 에서 닿는 것을 모아 두고, b 에서 가까운 순서로 훑으며 처음 겹치는 것을 찾으세요\n  return null;\n}",
  sol: "function mergeBase(commits, a, b) {\n  const byId = new Map(commits.map((c) => [c.id, c]));\n  const reach = (start) => {\n    const seen = new Set();\n    const stack = [start];\n    while (stack.length) {\n      const id = stack.pop();\n      if (seen.has(id) || !byId.has(id)) continue;\n      seen.add(id);\n      byId.get(id).ps.forEach((p) => stack.push(p));\n    }\n    return seen;\n  };\n  const fromA = reach(a);\n  const queue = [b];\n  const done = new Set();\n  while (queue.length) {\n    const id = queue.shift();\n    if (done.has(id) || !byId.has(id)) continue;\n    done.add(id);\n    if (fromA.has(id)) return id;\n    byId.get(id).ps.forEach((p) => queue.push(p));\n  }\n  return null;\n}",
  tests: [['mergeBase([{id:"a",ps:[]},{id:"b",ps:["a"]},{id:"c",ps:["a"]}],"b","c")', '"a"'],
    ['mergeBase([{id:"a",ps:[]},{id:"b",ps:["a"]},{id:"c",ps:["b"]}],"b","c")', '"b"'],
    ['mergeBase([{id:"a",ps:[]},{id:"b",ps:["a"]},{id:"c",ps:["b"]},{id:"d",ps:["a"]}],"c","d")', '"a"'],
    ['mergeBase([{id:"a",ps:[]},{id:"x",ps:[]}],"a","x")', "null"]],
  edge: [['mergeBase([{id:"a",ps:[]}],"a","a")', '"a"'], ['mergeBase([],"a","b")', "null"]],
  ex: "3-way 병합은 이 <b>기준점(merge base)</b> 없이는 성립하지 않습니다. '조상 대비 내가 바꾼 것' 과 '조상 대비 저쪽이 바꾼 것' 을 비교해야 하기 때문입니다.\n너비 우선으로 훑는 것이 중요합니다. 깊이 우선으로 가면 공통 조상을 만나기는 하지만 <b>가장 가까운 것</b>이라는 보장이 없습니다. 먼 조상을 기준으로 잡으면, 이미 합쳐진 변경이 다시 충돌로 나타납니다.\n실제 Git 은 이보다 정교합니다. 공통 조상이 여럿일 때(교차 병합) <code>recursive</code>·<code>ort</code> 전략은 그 조상들을 다시 병합해 <b>가상의 기준점</b>을 만듭니다. 그래서 같은 두 브랜치라도 전략에 따라 충돌 여부가 달라질 수 있습니다.\n<code>git merge-base a b</code> 로 직접 확인할 수 있습니다. PR 의 diff 가 '내 브랜치와 main 의 차이' 가 아니라 <b>기준점과의 차이</b>인 것도 이 때문입니다." },

{ track: "git", k: "앞섰나 뒤처졌나 · aheadBehind", cat: "internals",
  q: "내 브랜치가 상대보다 <b>몇 커밋 앞서 있고 몇 커밋 뒤처졌는지</b>를 <code>[앞선 수, 뒤처진 수]</code> 로 돌려주세요. <code>git status</code> 가 보여 주는 그 숫자입니다.",
  src: "function aheadBehind(commits, mine, theirs) {\n  // TODO: 각자에서 닿는 커밋 집합을 만들어 차집합의 크기를 세세요\n  return [0, 0];\n}",
  sol: "function aheadBehind(commits, mine, theirs) {\n  const byId = new Map(commits.map((c) => [c.id, c]));\n  const reach = (start) => {\n    const seen = new Set();\n    const stack = [start];\n    while (stack.length) {\n      const id = stack.pop();\n      if (seen.has(id) || !byId.has(id)) continue;\n      seen.add(id);\n      byId.get(id).ps.forEach((p) => stack.push(p));\n    }\n    return seen;\n  };\n  const a = reach(mine);\n  const b = reach(theirs);\n  let ahead = 0;\n  let behind = 0;\n  a.forEach((x) => { if (!b.has(x)) ahead++; });\n  b.forEach((x) => { if (!a.has(x)) behind++; });\n  return [ahead, behind];\n}",
  tests: [['aheadBehind([{id:"a",ps:[]},{id:"b",ps:["a"]}],"b","a")', "[1,0]"],
    ['aheadBehind([{id:"a",ps:[]},{id:"b",ps:["a"]}],"a","b")', "[0,1]"],
    ['aheadBehind([{id:"a",ps:[]},{id:"b",ps:["a"]},{id:"c",ps:["a"]}],"b","c")', "[1,1]"],
    ['aheadBehind([{id:"a",ps:[]},{id:"b",ps:["a"]},{id:"c",ps:["b"]},{id:"d",ps:["a"]}],"c","d")', "[2,1]"]],
  edge: [['aheadBehind([{id:"a",ps:[]}],"a","a")', "[0,0]"], ['aheadBehind([],"a","b")', "[0,0]"]],
  ex: "<code>git status</code> 의 '<b>Your branch is ahead of 'origin/main' by 2 commits</b>' 가 바로 이 계산입니다. Git 은 <code>git rev-list --left-right --count main...origin/main</code> 로 같은 답을 냅니다.\n점 <b>세 개</b>(<code>...</code>)가 대칭 차집합을 뜻하는 것이 여기서 나옵니다. 점 두 개(<code>..</code>)는 한쪽 방향만 세므로 '뒤처진 수' 를 놓칩니다.\n둘 다 0 이 아니면 <b>역사가 갈라졌다</b>는 뜻이고, 이때 그냥 <code>push</code> 하면 거부됩니다. 앞선 수만 있으면 fast-forward 로 밀 수 있고, 뒤처진 수만 있으면 그냥 당겨오면 됩니다.\n이 숫자가 <code>fetch</code> 시점 기준이라는 점을 잊기 쉽습니다. <code>origin/main</code> 은 마지막으로 받아 온 사본이므로, 오래 fetch 하지 않았다면 이 숫자도 낡은 것입니다." },

{ track: "git", k: "어떤 병합이 되는가 · mergeKind", cat: "internals",
  q: "현재 브랜치 <code>base</code> 에 <code>topic</code> 을 병합할 때 어떤 일이 벌어질지 판정해 주세요. <code>\"up-to-date\"</code> · <code>\"fast-forward\"</code> · <code>\"merge\"</code> · <code>\"unrelated\"</code> 중 하나입니다.",
  src: "function mergeKind(commits, base, topic) {\n  // TODO: 조상 관계와 공통 조상 유무로 네 경우를 가르세요\n  return \"merge\";\n}",
  sol: "function mergeKind(commits, base, topic) {\n  const byId = new Map(commits.map((c) => [c.id, c]));\n  const reach = (start) => {\n    const seen = new Set();\n    const stack = [start];\n    while (stack.length) {\n      const id = stack.pop();\n      if (seen.has(id) || !byId.has(id)) continue;\n      seen.add(id);\n      byId.get(id).ps.forEach((p) => stack.push(p));\n    }\n    return seen;\n  };\n  const a = reach(base);\n  const b = reach(topic);\n  if (a.has(topic)) return \"up-to-date\";\n  if (b.has(base)) return \"fast-forward\";\n  let shared = false;\n  a.forEach((x) => { if (b.has(x)) shared = true; });\n  return shared ? \"merge\" : \"unrelated\";\n}",
  tests: [['mergeKind([{id:"a",ps:[]},{id:"b",ps:["a"]}],"a","b")', '"fast-forward"'],
    ['mergeKind([{id:"a",ps:[]},{id:"b",ps:["a"]}],"b","a")', '"up-to-date"'],
    ['mergeKind([{id:"a",ps:[]},{id:"b",ps:["a"]},{id:"c",ps:["a"]}],"b","c")', '"merge"'],
    ['mergeKind([{id:"a",ps:[]},{id:"x",ps:[]}],"a","x")', '"unrelated"']],
  edge: [['mergeKind([{id:"a",ps:[]}],"a","a")', '"up-to-date"'],
    ['mergeKind([{id:"a",ps:[]},{id:"b",ps:["a"]},{id:"c",ps:["b"]}],"a","c")', '"fast-forward"']],
  ex: "'병합했는데 병합 커밋이 안 생겼다' 는 질문의 답이 이 함수 안에 있습니다. <code>topic</code> 이 <code>base</code> 를 <b>조상으로 갖고 있으면</b> 합칠 것이 없어 이름표만 앞으로 옮깁니다 — fast-forward 입니다.\n판정 순서가 중요합니다. <b>up-to-date 를 먼저</b> 봐야 합니다. 같은 커밋이면 양쪽 조건이 모두 참이라, 순서가 뒤집히면 아무 일도 없는데 fast-forward 라고 답하게 됩니다.\n<code>unrelated</code> 는 공통 조상이 아예 없는 경우입니다. 별도로 시작한 저장소를 합칠 때 실제로 생기고, Git 은 실수를 막으려고 <code>--allow-unrelated-histories</code> 를 명시하게 합니다.\n<code>--no-ff</code> 를 주면 fast-forward 가 가능해도 <b>일부러 병합 커밋을 만듭니다</b>. 'PR 하나가 커밋 하나의 덩어리였다' 는 정보를 역사에 남기기 위해서입니다." },

/* ───────────── 병합의 실제 ───────────── */
{ track: "git", k: "한 줄의 3-way 병합 · mergeLine", cat: "internals",
  q: "공통 조상의 줄 <code>base</code>, 내 줄 <code>ours</code>, 상대 줄 <code>theirs</code> 가 주어집니다. 병합 결과 줄을 돌려주고, 양쪽이 <b>서로 다르게</b> 바꿨으면 <code>\"CONFLICT\"</code> 를 돌려주세요.",
  src: "function mergeLine(base, ours, theirs) {\n  // TODO: '누가 바꿨는가' 세 경우를 먼저 말로 정리하세요\n  return ours;\n}",
  sol: "function mergeLine(base, ours, theirs) {\n  if (ours === theirs) return ours;\n  if (ours === base) return theirs;\n  if (theirs === base) return ours;\n  return \"CONFLICT\";\n}",
  tests: [['mergeLine("a","a","b")', '"b"'],
    ['mergeLine("a","b","a")', '"b"'],
    ['mergeLine("a","b","c")', '"CONFLICT"'],
    ['mergeLine("a","b","b")', '"b"']],
  edge: [['mergeLine("a","a","a")', '"a"'], ['mergeLine("","x","")', '"x"']],
  ex: "네 줄이 병합의 전부입니다. 규칙은 '<b>바꾼 쪽의 것을 쓴다</b>' 하나이고, <b>둘 다 바꿨는데 결과가 다를 때만</b> 사람을 부릅니다.\n두 번째와 네 번째 테스트가 자주 오해되는 지점입니다. 양쪽이 <b>똑같이</b> 바꿨으면 충돌이 아닙니다 — 결과가 하나로 정해지기 때문입니다. 그래서 두 사람이 같은 오타를 같은 방식으로 고쳤다면 조용히 합쳐집니다.\n기준점(base)이 필요한 이유도 여기서 분명해집니다. <code>ours</code> 와 <code>theirs</code> 만 보면 '다르다' 는 것만 알 뿐 <b>누가 바꿨는지</b> 알 수 없어, 안 바꾼 쪽의 옛 내용으로 덮어쓰는 사고가 납니다. 2-way 병합이 위험한 이유입니다.\n실제 Git 은 줄 하나가 아니라 <b>덩어리(hunk)</b> 단위로 같은 판단을 합니다. 그래서 서로 다른 함수를 고쳤다면 같은 파일이라도 충돌하지 않습니다." },

{ track: "git", k: "파일 단위 3-way 병합 · threeWayMerge", cat: "internals",
  q: "세 파일이 같은 줄 수의 배열로 주어집니다. 줄마다 3-way 병합을 해 결과 배열을 돌려주고, <b>한 줄이라도 충돌하거나 줄 수가 다르면</b> <code>null</code> 을 돌려주세요.",
  src: "function threeWayMerge(base, ours, theirs) {\n  // TODO: 줄 수부터 확인하고, 줄마다 앞 문제의 규칙을 적용하세요\n  return ours;\n}",
  sol: "function threeWayMerge(base, ours, theirs) {\n  if (ours.length !== base.length) return null;\n  if (theirs.length !== base.length) return null;\n  const out = [];\n  for (let i = 0; i < base.length; i++) {\n    const b = base[i];\n    const o = ours[i];\n    const t = theirs[i];\n    if (o === t) out.push(o);\n    else if (o === b) out.push(t);\n    else if (t === b) out.push(o);\n    else return null;\n  }\n  return out;\n}",
  tests: [['threeWayMerge(["x","y"],["X","y"],["x","Y"])', '["X","Y"]'],
    ['threeWayMerge(["x","y"],["X","y"],["Z","y"])', "null"],
    ['threeWayMerge(["x"],["x"],["x"])', '["x"]'],
    ['threeWayMerge(["a","b","c"],["a","B","c"],["a","b","C"])', '["a","B","C"]']],
  edge: [['threeWayMerge([],[],[])', "[]"], ['threeWayMerge(["x"],["x","y"],["x"])', "null"]],
  ex: "첫 번째 테스트가 <b>병합이 왜 대체로 잘 되는지</b>를 보여 줍니다. 같은 파일을 둘이 고쳐도 <b>다른 줄</b>이면 충돌하지 않습니다. '같은 파일을 건드리면 충돌' 이라는 흔한 오해가 여기서 깨집니다.\n줄 수가 다르면 <code>null</code> 로 처리한 것은 이 모델의 <b>단순화</b>입니다. 실제 Git 은 줄이 추가·삭제되어도 diff 알고리즘으로 <b>대응되는 위치</b>를 찾아냅니다. 그래서 위에 열 줄을 넣어도 아래쪽 수정과 충돌하지 않습니다.\n그 정렬이 실패하는 지점이 바로 <b>현실의 충돌</b>입니다. 두 사람이 같은 영역을 서로 다르게 재구성했다면 Git 이 대응시킬 방법이 없어 사람에게 넘깁니다.\n<code>null</code> 대신 충돌 표식을 넣은 파일을 만드는 것이 Git 의 선택입니다. 자동 병합에 실패해도 <b>작업 파일은 남겨</b> 사람이 이어서 고칠 수 있게 하기 위해서입니다." },

{ track: "git", k: "충돌 파일 추리기 · conflictedFiles", cat: "internals",
  q: "세 개의 <code>{파일: 내용}</code> 객체가 주어집니다. 3-way 규칙으로 병합했을 때 <b>충돌하는 파일 이름</b>을 사전순 배열로 돌려주세요. 한쪽에만 있는 새 파일은 충돌이 아닙니다.",
  src: "function conflictedFiles(base, ours, theirs) {\n  // TODO: 세 객체의 파일 이름을 모두 모은 뒤 하나씩 판정하세요\n  return [];\n}",
  sol: "function conflictedFiles(base, ours, theirs) {\n  const names = new Set();\n  [base, ours, theirs].forEach((m) => Object.keys(m).forEach((f) => names.add(f)));\n  const out = [];\n  names.forEach((f) => {\n    const b = base[f];\n    const o = ours[f];\n    const t = theirs[f];\n    if (o === t) return;\n    if (o === b || t === b) return;\n    out.push(f);\n  });\n  return out.sort();\n}",
  tests: [['conflictedFiles({a:"1"},{a:"2"},{a:"3"})', '["a"]'],
    ['conflictedFiles({a:"1"},{a:"2"},{a:"1"})', "[]"],
    ['conflictedFiles({a:"1",b:"1"},{a:"2",b:"1"},{a:"1",b:"3"})', "[]"],
    ['conflictedFiles({a:"1"},{a:"2",n:"x"},{a:"3",n:"y"})', '["a","n"]']],
  edge: [['conflictedFiles({},{},{})', "[]"], ['conflictedFiles({},{n:"x"},{})', "[]"]],
  ex: "<code>git merge</code> 가 멈추기 전에 하는 계산이 이것입니다. 파일별로 판정하고, <b>하나라도 충돌하면</b> 병합을 중단한 채 표식을 남깁니다.\n네 번째 테스트의 <code>n</code> 이 중요합니다. 양쪽이 <b>같은 이름의 새 파일을 다르게</b> 만들면 충돌입니다 — 기준점에 없으므로 '누가 바꿨는지' 를 정할 수 없기 때문입니다. Git 은 이것을 <code>both added</code> 로 보고합니다.\n반대로 마지막 엣지 케이스처럼 <b>한쪽만</b> 새 파일을 만들었으면 그냥 추가됩니다. 상대가 지운 적이 없으니 다툴 것이 없습니다.\n결과를 정렬한 것은 <b>재현 가능성</b> 때문입니다. <code>Set</code> 의 순회 순서에 기대면 입력 순서에 따라 결과가 흔들려, 테스트가 간헐적으로 실패합니다." },

{ track: "git", k: "충돌 표식 찾기 · conflictLines", cat: "debug",
  q: "파일 내용에서 <b>충돌 표식이 남아 있는 줄</b>의 번호(1부터)를 배열로 돌려주세요. 표식은 <code>&lt;</code>·<code>=</code>·<code>&gt;</code> 가 <b>정확히 7개</b> 연속으로 줄 맨 앞에 오고, 그 뒤는 줄 끝이거나 공백입니다.",
  src: "function conflictLines(text) {\n  // TODO: 줄로 쪼갠 뒤 각 줄의 앞부분을 검사하세요\n  return [];\n}",
  sol: "function conflictLines(text) {\n  const out = [];\n  text.split(\"\\n\").forEach((line, i) => {\n    if (/^(<{7}|={7}|>{7})(\\s|$)/.test(line)) out.push(i + 1);\n  });\n  return out;\n}",
  tests: [['conflictLines("a\\n<<<<<<< HEAD\\nb\\n=======\\nc\\n>>>>>>> x\\nd")', "[2,4,6]"],
    ['conflictLines("hello\\nworld")', "[]"],
    ['conflictLines("=======")', "[1]"],
    ['conflictLines("x = 1\\ny === z")', "[]"]],
  edge: [['conflictLines("")', "[]"], ['conflictLines("<<<<<<<<")', "[]"]],
  ex: "충돌을 고친 뒤 표식을 지우는 것을 잊고 커밋하는 사고는 놀랄 만큼 자주 납니다. Git 은 파일 <b>내용을 검사하지 않으므로</b> 그대로 커밋됩니다 — 그래서 이 검사를 <code>pre-commit</code> 훅에 넣는 것이 표준적인 예방책입니다.\n<b>정확히 7개</b>라는 조건이 핵심입니다. 마지막 엣지 케이스의 여덟 개는 표식이 아니고, 네 번째 테스트의 <code>y === z</code> 도 등호가 셋이라 걸리지 않습니다. 조건을 느슨하게 잡으면 <b>멀쩡한 코드를 막는</b> 도구가 되어 아무도 안 쓰게 됩니다.\n뒤에 공백이나 줄 끝이 와야 한다는 조건도 같은 이유입니다. <code>&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;</code> 처럼 이어지는 문자는 표식이 아닙니다.\n줄 번호를 1부터 세는 것은 편집기와 컴파일러의 관례를 따른 것입니다. 도구가 뱉는 위치는 사람이 그대로 눌러 이동할 수 있어야 쓸모가 있습니다." },

{ track: "git", k: "diff 는 계산된다 · diffCount", cat: "internals",
  q: "두 파일(줄 배열)에서 <code>[추가된 줄 수, 삭제된 줄 수]</code> 를 돌려주세요. 순서를 지키며 공통으로 남는 줄을 <b>최대한 많이</b> 잡는 기준입니다.",
  src: "function diffCount(a, b) {\n  // TODO: 최장 공통 부분수열의 길이를 구하면 나머지가 답입니다\n  return [0, 0];\n}",
  sol: "function diffCount(a, b) {\n  const n = a.length;\n  const m = b.length;\n  let prev = new Array(m + 1).fill(0);\n  for (let i = 1; i <= n; i++) {\n    const cur = new Array(m + 1).fill(0);\n    for (let j = 1; j <= m; j++) {\n      if (a[i - 1] === b[j - 1]) cur[j] = prev[j - 1] + 1;\n      else cur[j] = Math.max(prev[j], cur[j - 1]);\n    }\n    prev = cur;\n  }\n  const same = prev[m];\n  return [m - same, n - same];\n}",
  tests: [['diffCount(["a","b","c"],["a","x","c"])', "[1,1]"],
    ['diffCount(["a","b"],["a","b","c"])', "[1,0]"],
    ['diffCount(["a","b","c"],["a","c"])', "[0,1]"],
    ['diffCount(["a","b","c"],["a","b","c"])', "[0,0]"]],
  edge: [['diffCount([],[])', "[0,0]"], ['diffCount(["a"],[])', "[0,1]"]],
  ex: "Git 이 diff 를 <b>저장하지 않는다</b>는 사실이 이 문제의 요점입니다. 커밋에는 스냅숏만 있고, 화면에 보이는 <code>+3 -1</code> 은 두 스냅숏을 비교해 <b>그때 계산한 결과</b>입니다.\n계산의 핵심은 <b>최장 공통 부분수열</b>입니다. 순서를 지키며 살아남는 줄을 최대로 잡으면, 나머지가 자연스럽게 추가와 삭제가 됩니다. 그래야 '가장 작은 변경' 으로 보이는 diff 가 나옵니다.\n이 정의 때문에 diff 는 <b>유일하지 않습니다</b>. 같은 길이의 공통 부분수열이 여러 개면 어느 것을 고르느냐에 따라 보이는 모양이 달라집니다. Git 의 <code>--diff-algorithm=patience</code>·<code>histogram</code> 이 존재하는 이유이고, 어떤 알고리즘은 사람이 읽기 좋은 diff 를 냅니다.\n표를 한 줄만 굴려 메모리를 줄였습니다. 파일이 수만 줄이면 <code>n × m</code> 표를 통째로 잡을 수 없어, 실제 구현도 이런 절약을 합니다." },

/* ───────────── 세 공간과 되돌리기 ───────────── */
{ track: "git", k: "status 를 직접 계산한다 · statusOf", cat: "debug",
  q: "<code>head</code>·<code>index</code>·<code>work</code> 세 개의 <code>{파일: 내용}</code> 객체가 주어집니다. 파일 이름 사전순으로 <code>\"staged:이름\"</code>·<code>\"modified:이름\"</code>·<code>\"untracked:이름\"</code> 을 담은 배열을 돌려주세요. 한 파일이 두 상태를 동시에 가질 수 있습니다.",
  src: "function statusOf(head, index, work) {\n  // TODO: 추적된 적 없는 파일을 먼저 가려내고, 나머지는 두 비교를 각각 하세요\n  return [];\n}",
  sol: "function statusOf(head, index, work) {\n  const names = new Set();\n  [head, index, work].forEach((m) => Object.keys(m).forEach((f) => names.add(f)));\n  const out = [];\n  Array.from(names).sort().forEach((f) => {\n    const tracked = (f in head) || (f in index);\n    if (!tracked) {\n      out.push(\"untracked:\" + f);\n      return;\n    }\n    if (index[f] !== head[f]) out.push(\"staged:\" + f);\n    if ((f in work) && work[f] !== index[f]) out.push(\"modified:\" + f);\n  });\n  return out;\n}",
  tests: [['statusOf({a:"1"},{a:"2"},{a:"2"})', '["staged:a"]'],
    ['statusOf({a:"1"},{a:"1"},{a:"2"})', '["modified:a"]'],
    ['statusOf({a:"1"},{a:"2"},{a:"3"})', '["staged:a","modified:a"]'],
    ['statusOf({},{},{n:"x"})', '["untracked:n"]']],
  edge: [['statusOf({},{},{})', "[]"], ['statusOf({a:"1"},{a:"1"},{a:"1"})', "[]"]],
  ex: "<code>git status</code> 는 마법이 아니라 <b>세 공간의 두 번의 비교</b>입니다. <code>head↔index</code> 가 'Changes to be committed', <code>index↔work</code> 가 'Changes not staged for commit' 입니다.\n세 번째 테스트가 처음 보면 당황스러운 상태입니다. <code>add</code> 한 뒤 또 고치면 <b>같은 파일이 양쪽에 동시에</b> 나타납니다. 오류가 아니라 정확한 보고이고, 이 상태로 커밋하면 <code>add</code> 한 시점의 내용만 들어갑니다.\n추적 여부를 <code>head</code> 와 <code>index</code> <b>양쪽</b>으로 판단한 것에 이유가 있습니다. 새로 만들어 <code>add</code> 만 한 파일은 <code>head</code> 에 없지만 이미 추적 중이라, <code>head</code> 만 보면 untracked 로 잘못 분류됩니다.\n실제 <code>git status</code> 는 여기에 삭제·이름 변경·충돌 상태까지 더합니다. 그래도 뼈대는 이 두 번의 비교이고, 그것만 알아도 출력이 읽힙니다." },

{ track: "git", k: "reset 의 세 단계 · resetTo", cat: "internals",
  q: "상태는 <code>[head, index, work]</code> 배열입니다. <code>mode</code>(<code>\"soft\"</code>·<code>\"mixed\"</code>·<code>\"hard\"</code>)에 따라 <code>target</code> 으로 되돌린 새 배열을 돌려주세요. 원본은 바꾸지 않습니다.",
  src: "function resetTo(state, mode, target) {\n  // TODO: soft 는 head 만, mixed 는 index 까지, hard 는 work 까지입니다\n  return state;\n}",
  sol: "function resetTo(state, mode, target) {\n  const head = target;\n  let index = state[1];\n  let work = state[2];\n  if (mode === \"mixed\" || mode === \"hard\") index = target;\n  if (mode === \"hard\") work = target;\n  return [head, index, work];\n}",
  tests: [['resetTo(["c2","c2","c2"],"soft","c1")', '["c1","c2","c2"]'],
    ['resetTo(["c2","c2","c2"],"mixed","c1")', '["c1","c1","c2"]'],
    ['resetTo(["c2","c2","c2"],"hard","c1")', '["c1","c1","c1"]'],
    ['resetTo(["c2","c2","작업중"],"soft","c1")', '["c1","c2","작업중"]']],
  edge: [['resetTo(["c1","c1","c1"],"hard","c1")', '["c1","c1","c1"]'],
    ['resetTo(["c2","x","y"],"mixed","c2")', '["c2","c2","y"]']],
  ex: "<code>reset</code> 의 세 모드는 '<b>어디까지 끌고 내려갈 것인가</b>' 하나로 정리됩니다. head 만, index 까지, work 까지 — 딱 그 세 단계입니다.\n네 번째 테스트가 <code>--soft</code> 를 쓰는 이유를 보여 줍니다. 작업 중인 내용이 그대로 남으므로, 커밋을 쪼개거나 메시지를 다시 쓸 때 <b>아무것도 잃지 않습니다</b>.\n<code>--hard</code> 만 <code>work</code> 를 건드립니다. 그래서 <b>커밋되지 않은 수정을 지우는</b> 유일한 모드이고, Git 에서 진짜로 데이터를 잃을 수 있는 몇 안 되는 명령입니다.\n원본 배열을 바꾸지 않고 새 배열을 돌려준 것도 의도적입니다. 상태를 제자리에서 고치면 '되돌리기 전 상태' 가 사라져, 실행 취소를 만들 수 없습니다 — 편집기와 상태 관리 라이브러리가 불변 갱신을 쓰는 것과 같은 이유입니다." },

{ track: "git", k: "커밋을 재생한다 · applyCommits", cat: "internals",
  q: "커밋은 <code>{set:{파일:내용}, del:[파일]}</code> 입니다. 빈 상태에서 시작해 순서대로 적용한 뒤, 남은 파일을 <code>\"이름=내용\"</code> 형태로 사전순 배열에 담아 돌려주세요.",
  src: "function applyCommits(commits) {\n  // TODO: 상태 하나를 두고 커밋을 차례로 적용하세요\n  return [];\n}",
  sol: "function applyCommits(commits) {\n  const files = new Map();\n  commits.forEach((c) => {\n    Object.keys(c.set || {}).forEach((f) => files.set(f, c.set[f]));\n    (c.del || []).forEach((f) => files.delete(f));\n  });\n  return Array.from(files.keys()).sort().map((f) => f + \"=\" + files.get(f));\n}",
  tests: [['applyCommits([{set:{a:"1"}},{set:{b:"2"}}])', '["a=1","b=2"]'],
    ['applyCommits([{set:{a:"1"}},{set:{a:"2"}}])', '["a=2"]'],
    ['applyCommits([{set:{a:"1",b:"2"}},{del:["a"]}])', '["b=2"]'],
    ['applyCommits([{set:{a:"1"}},{del:["a"]},{set:{a:"3"}}])', '["a=3"]']],
  edge: [['applyCommits([])', "[]"], ['applyCommits([{del:["없는파일"]}])', "[]"]],
  ex: "<code>rebase</code>·<code>cherry-pick</code>·<code>revert</code> 가 전부 이 '<b>커밋을 다시 적용한다</b>' 위에 서 있습니다. 커밋을 옮기는 것이 아니라 <b>그 변경을 새 자리에 재생</b>하는 것입니다.\n그래서 순서를 바꾸면 결과가 달라질 수 있습니다. 네 번째 테스트에서 삭제와 재생성의 순서를 바꾸면 파일이 사라집니다 — <code>rebase -i</code> 로 커밋 순서를 바꿀 때 조심해야 하는 이유입니다.\n마지막 엣지 케이스처럼 <b>없는 파일을 지우는</b> 커밋도 그냥 넘어가게 두었습니다. 실제 재생에서는 여기서 '적용할 수 없다' 며 멈추고 사람을 부르는데, 그것이 rebase 중에 만나는 충돌입니다.\n<code>Map</code> 을 쓴 것은 삽입 순서를 유지하기 위해서가 아니라 <code>delete</code> 가 명확하기 때문입니다. 출력을 정렬했으므로 순서에는 의존하지 않습니다." },

{ track: "git", k: "이름을 잃은 커밋 · lostCommits", cat: "debug",
  q: "커밋 목록과 <b>현재 살아 있는 ref</b>(브랜치·태그가 가리키는 id) 목록이 주어집니다. 어떤 ref 에서도 <b>부모를 따라 닿지 않는</b> 커밋 id 를 사전순으로 돌려주세요.",
  src: "function lostCommits(commits, refs) {\n  // TODO: ref 에서 닿는 것을 모두 표시한 뒤 남은 것을 고르세요\n  return [];\n}",
  sol: "function lostCommits(commits, refs) {\n  const byId = new Map(commits.map((c) => [c.id, c]));\n  const alive = new Set();\n  const stack = refs.slice();\n  while (stack.length) {\n    const id = stack.pop();\n    if (alive.has(id) || !byId.has(id)) continue;\n    alive.add(id);\n    byId.get(id).ps.forEach((p) => stack.push(p));\n  }\n  return commits.map((c) => c.id).filter((id) => !alive.has(id)).sort();\n}",
  tests: [['lostCommits([{id:"a",ps:[]},{id:"b",ps:["a"]},{id:"z",ps:["a"]}],["b"])', '["z"]'],
    ['lostCommits([{id:"a",ps:[]},{id:"b",ps:["a"]}],["b"])', "[]"],
    ['lostCommits([{id:"a",ps:[]},{id:"b",ps:["a"]}],[])', '["a","b"]'],
    ['lostCommits([{id:"a",ps:[]},{id:"b",ps:["a"]},{id:"c",ps:["b"]}],["a"])', '["b","c"]']],
  edge: [['lostCommits([],["x"])', "[]"], ['lostCommits([{id:"a",ps:[]}],["a"])', "[]"]],
  ex: "'커밋을 날렸다' 는 말이 대개 사실이 아닌 이유가 이 함수에 있습니다. 사라진 것은 <b>이름</b>이고 커밋 객체는 저장소에 그대로 남아 있습니다 — 다만 아무도 가리키지 않을 뿐입니다.\n<code>git fsck --unreachable</code> 이 정확히 이 목록을 뽑아 줍니다. 실무에서는 <code>git reflog</code> 가 훨씬 편한데, reflog 자체가 <b>임시 ref 역할</b>을 해서 이 커밋들을 살려 두기 때문입니다.\n네 번째 테스트가 <code>reset --hard HEAD~2</code> 직후의 모습입니다. <code>b</code>·<code>c</code> 는 도달 불가가 되지만 해시만 알면 <code>git switch -c 복구 c</code> 로 그대로 되살아납니다.\n영원하지는 않습니다. <code>git gc</code> 는 도달 불가 객체를 기본 약 90일 뒤 정리합니다. 그래서 사고 직후에 되살리는 것이 중요하고, 정리가 끝난 뒤에는 방법이 없습니다." },

{ track: "git", k: "치워 둔 것 되꺼내기 · stashApply", cat: "internals",
  q: "현재 작업 상태 <code>work</code> 와 치워 둔 <code>stash</code>(둘 다 <code>{파일:내용}</code>)가 주어집니다. <b>같은 파일을 서로 다른 내용으로</b> 갖고 있으면 <code>null</code>(충돌), 아니면 합친 결과를 <code>\"이름=내용\"</code> 사전순 배열로 돌려주세요.",
  src: "function stashApply(work, stash) {\n  // TODO: 겹치는 파일부터 확인하고, 안전하면 합치세요\n  return [];\n}",
  sol: "function stashApply(work, stash) {\n  const merged = Object.assign({}, work);\n  const names = Object.keys(stash);\n  for (let i = 0; i < names.length; i++) {\n    const f = names[i];\n    if ((f in work) && work[f] !== stash[f]) return null;\n    merged[f] = stash[f];\n  }\n  return Object.keys(merged).sort().map((f) => f + \"=\" + merged[f]);\n}",
  tests: [['stashApply({a:"1"},{b:"2"})', '["a=1","b=2"]'],
    ['stashApply({a:"1"},{a:"2"})', "null"],
    ['stashApply({a:"1"},{a:"1"})', '["a=1"]'],
    ['stashApply({},{a:"1",b:"2"})', '["a=1","b=2"]']],
  edge: [['stashApply({},{})', "[]"], ['stashApply({a:"1"},{})', '["a=1"]']],
  ex: "<code>git stash pop</code> 이 <b>실패할 수 있다</b>는 사실을 잊기 쉽습니다. 치워 둔 뒤 같은 파일을 또 고쳤다면 되꺼낼 때 충돌합니다.\n이때 Git 은 stash 를 <b>목록에서 지우지 않습니다</b>. 적용에 실패했으므로 지우면 작업이 사라지기 때문입니다. 충돌을 해결한 뒤 <code>git stash drop</code> 으로 직접 정리해야 하는데, 이 단계를 잊어 같은 stash 가 남아 있는 일이 흔합니다.\n세 번째 테스트처럼 <b>내용이 같으면</b> 충돌이 아닙니다. 3-way 병합과 같은 원리입니다 — 결과가 하나로 정해지면 사람을 부를 이유가 없습니다.\n충돌 시 <code>null</code> 로 <b>아무것도 바꾸지 않고</b> 돌려주는 것이 중요합니다. 절반만 적용하고 실패하면 어느 파일이 어느 상태인지 알 수 없어, 되돌리는 것조차 어려워집니다." },

/* ───────────── 탐색과 도구 ───────────── */
{ track: "git", k: "이분 탐색으로 범인 찾기 · firstBad", cat: "debug",
  q: "오래된 것부터 정렬된 커밋 배열과 <code>isBad(커밋)</code> 판정 함수가 주어집니다. 한 번 나빠지면 계속 나쁘다고 할 때 <b>처음 나빠진 커밋</b>을 돌려주세요. 없으면 <code>null</code> 입니다.",
  src: "function firstBad(commits, isBad) {\n  // TODO: 전부 확인하지 말고 절반씩 줄이세요\n  return commits[0] || null;\n}",
  sol: "function firstBad(commits, isBad) {\n  if (!commits.length) return null;\n  let lo = 0;\n  let hi = commits.length - 1;\n  while (lo < hi) {\n    const mid = (lo + hi) >> 1;\n    if (isBad(commits[mid])) hi = mid;\n    else lo = mid + 1;\n  }\n  return isBad(commits[lo]) ? commits[lo] : null;\n}",
  tests: [['firstBad(["c1","c2","c3","c4"],(x)=>x>="c3")', '"c3"'],
    ['firstBad(["c1","c2","c3"],(x)=>x>="c1")', '"c1"'],
    ['firstBad(["c1","c2","c3"],()=>false)', "null"],
    ['firstBad(["c1","c2","c3","c4","c5"],(x)=>x>="c5")', '"c5"']],
  edge: [['firstBad([],()=>true)', "null"], ['firstBad(["c1"],(x)=>x==="c1")', '"c1"']],
  ex: "<code>git bisect</code> 가 이것입니다. 커밋이 1000개여도 <b>10번만 확인</b>하면 범인을 찾습니다 — 하나씩 되돌아가는 것과는 차원이 다른 속도입니다.\n성립 조건이 있습니다. '<b>한 번 나빠지면 계속 나쁘다</b>' 는 단조성입니다. 중간에 고쳐졌다 다시 깨졌다면 이분 탐색은 아무 결과나 내놓습니다. 그래서 bisect 전에 '이 증상이 단조로운가' 를 먼저 생각해야 합니다.\n마지막에 <code>isBad(commits[lo])</code> 를 한 번 더 확인하는 것이 요점입니다. 전부 정상이면 <code>lo</code> 는 마지막 자리에 멈추는데, 그것을 그대로 답으로 내면 <b>멀쩡한 커밋을 범인으로</b> 지목하게 됩니다.\n판정을 스크립트로 만들면 <code>git bisect run ./test.sh</code> 한 줄로 전 과정이 자동화됩니다. 이때 스크립트는 정상 0, 이상 1을 돌려주면 되고, 빌드 자체가 안 되는 커밋은 125를 돌려 건너뛰게 합니다." },

{ track: "git", k: "줄마다 마지막 작성자 · blame", cat: "internals",
  q: "커밋 목록이 오래된 것부터 주어집니다. 각 커밋은 <code>{id, changed:[줄인덱스]}</code> 입니다. <code>lineCount</code> 개 줄 각각에 대해 <b>마지막으로 그 줄을 바꾼 커밋 id</b> 배열을 돌려주세요. 한 번도 안 바뀐 줄은 <code>null</code> 입니다.",
  src: "function blame(history, lineCount) {\n  // TODO: 오래된 것부터 덮어써 나가면 마지막에 최신만 남습니다\n  return [];\n}",
  sol: "function blame(history, lineCount) {\n  const owner = new Array(lineCount).fill(null);\n  history.forEach((c) => {\n    c.changed.forEach((i) => {\n      if (i >= 0 && i < lineCount) owner[i] = c.id;\n    });\n  });\n  return owner;\n}",
  tests: [['blame([{id:"a",changed:[0,1]},{id:"b",changed:[1]}],3)', '["a","b",null]'],
    ['blame([{id:"a",changed:[0]}],2)', '["a",null]'],
    ['blame([{id:"a",changed:[0]},{id:"b",changed:[0]}],1)', '["b"]'],
    ['blame([],2)', "[null,null]"]],
  edge: [['blame([{id:"a",changed:[9]}],2)', "[null,null]"], ['blame([],0)', "[]"]],
  ex: "<code>git blame</code> 은 '누가 잘못했나' 를 찾는 도구가 아니라 <b>맥락을 찾는 도구</b>입니다. 줄에서 커밋 해시를 얻고, 그 커밋의 <b>메시지</b>를 읽는 것이 진짜 목적입니다.\n그래서 커밋 메시지가 '수정' 뿐이면 blame 도 쓸모가 없어집니다. 좋은 메시지를 쓰는 실용적인 이유가 여기 있습니다.\n오래된 것부터 덮어쓰는 단순한 구조라 <b>중간 작성자가 가려집니다</b>. 실제 Git 도 마찬가지여서, 그 줄의 전체 사연을 보려면 <code>git log -L</code> 이나 <code>blame</code> 을 이전 커밋에서 다시 돌려야 합니다.\n전체 포맷을 적용한 커밋 하나가 blame 을 통째로 덮어 버리는 것도 이 구조 때문입니다. 그래서 그런 커밋은 <code>.git-blame-ignore-revs</code> 에 적어 <b>건너뛰게</b> 해 둡니다." },

{ track: "git", k: "무시 규칙 적용하기 · ignored", cat: "internals",
  q: "간단한 <code>.gitignore</code> 규칙을 적용해 <b>무시되는 파일</b>을 사전순으로 돌려주세요. 규칙은 <code>*.log</code> 같은 이름 패턴, <code>dir/</code> 같은 폴더 접두사, <code>!</code> 로 시작하는 예외 셋입니다. <b>뒤에 오는 규칙이 앞을 덮습니다.</b>",
  src: "function ignored(patterns, files) {\n  // TODO: 파일마다 모든 규칙을 순서대로 적용해 마지막 판정을 남기세요\n  return [];\n}",
  sol: "function ignored(patterns, files) {\n  const toRe = (p) => new RegExp(\"^\" + p.replace(/[.+^${}()|[\\]\\\\]/g, \"\\\\$&\").replace(/\\*/g, \"[^/]*\") + \"$\");\n  return files.filter((f) => {\n    let hit = false;\n    patterns.forEach((p) => {\n      const neg = p.charAt(0) === \"!\";\n      const body = neg ? p.slice(1) : p;\n      if (body.slice(-1) === \"/\") {\n        if (f.indexOf(body) === 0) hit = !neg;\n        return;\n      }\n      const name = f.split(\"/\").pop();\n      if (toRe(body).test(f) || toRe(body).test(name)) hit = !neg;\n    });\n    return hit;\n  }).sort();\n}",
  tests: [['ignored(["*.log"],["a.log","b.txt","x/c.log"])', '["a.log","x/c.log"]'],
    ['ignored(["node_modules/"],["node_modules/x.js","src/a.js"])', '["node_modules/x.js"]'],
    ['ignored([".env","!.env.example"],[".env",".env.example"])', '[".env"]'],
    ['ignored([],["a.log"])', "[]"]],
  edge: [['ignored(["*.log"],[])', "[]"], ['ignored(["*"],["a","b"])', '["a","b"]']],
  ex: "<b>뒤에 오는 규칙이 앞을 덮는다</b>는 것이 <code>.gitignore</code> 의 핵심 규칙입니다. 그래서 <code>!.env.example</code> 예외는 반드시 <code>.env</code> 보다 <b>아래</b>에 적어야 합니다 — 위에 적으면 아무 효과가 없습니다.\n패턴에 슬래시가 없으면 <b>어느 깊이의 파일이든</b> 이름만 맞으면 걸립니다. 첫 번째 테스트의 <code>x/c.log</code> 가 그 경우입니다. 저장소 루트의 것만 지정하려면 <code>/dist</code> 처럼 앞에 슬래시를 붙입니다.\n정규식을 만들 때 <b>특수 문자를 먼저 이스케이프</b>하는 것이 중요합니다. <code>.env</code> 의 점을 그대로 두면 아무 문자나 대응해 <code>aenv</code> 까지 걸립니다 — 사용자 입력으로 정규식을 만들 때 늘 나오는 함정입니다.\n실제 Git 은 여기에 <code>**</code>, 폴더별 <code>.gitignore</code>, 전역 설정까지 더합니다. 어떤 규칙이 걸렸는지 모를 때는 <code>git check-ignore -v 파일</code> 이 그 규칙을 정확히 알려 줍니다." },

{ track: "git", k: "해시를 몇 자까지 줄일까 · shortestUnique", cat: "internals",
  q: "해시 문자열 배열이 주어집니다. 앞에서 <code>n</code> 글자만 잘랐을 때 <b>서로 겹치지 않는 가장 작은 <code>n</code></b> 을 돌려주세요. 해시가 하나뿐이면 1 입니다.",
  src: "function shortestUnique(hashes) {\n  // TODO: 1부터 늘려 가며 겹침이 사라지는 지점을 찾으세요\n  return 40;\n}",
  sol: "function shortestUnique(hashes) {\n  if (hashes.length < 2) return 1;\n  const max = Math.max.apply(null, hashes.map((h) => h.length));\n  for (let n = 1; n <= max; n++) {\n    const seen = new Set(hashes.map((h) => h.slice(0, n)));\n    if (seen.size === hashes.length) return n;\n  }\n  return max;\n}",
  tests: [['shortestUnique(["abc","bcd"])', "1"],
    ['shortestUnique(["abc","abd"])', "3"],
    ['shortestUnique(["aaa","aab","abc"])', "3"],
    ['shortestUnique(["a1","b2","c3"])', "1"]],
  edge: [['shortestUnique(["abc"])', "1"], ['shortestUnique(["ab","ab"])', "2"]],
  ex: "Git 이 <code>1a2b3c4</code> 처럼 <b>짧은 해시</b>를 보여 줄 수 있는 근거가 이 계산입니다. 저장소 안에서 겹치지 않을 만큼만 보여 주면 사람이 읽고 쓰기 편합니다.\n그래서 짧은 해시의 길이는 <b>저장소마다 다르고 시간이 지나면 늘어납니다</b>. 커밋이 쌓이면 앞 7글자가 겹치기 시작해, Git 이 자동으로 8글자·9글자로 늘립니다.\n문서나 스크립트에 짧은 해시를 박아 두면 언젠가 <b>모호하다(ambiguous)</b>는 오류를 만나는 이유가 이것입니다. 영구히 남길 곳에는 전체 해시를 쓰는 것이 안전합니다.\n마지막 엣지 케이스처럼 <b>완전히 같은 값</b>이 둘 있으면 어떤 길이로도 구분되지 않아 최대 길이를 돌려줍니다. 실제 저장소에서는 같은 커밋이 두 번 등장하지 않으므로 생기지 않는 상황이지만, 함수가 무한히 도는 것은 막아야 합니다." },

{ track: "git", k: "부모가 먼저 오도록 · topoOrder", cat: "internals",
  q: "커밋 목록을 <b>부모가 항상 먼저 오도록</b> 정렬해 id 배열로 돌려주세요. 동시에 놓을 수 있는 것이 여럿이면 <b>사전순</b>으로 먼저 놓습니다. 목록에 없는 부모는 무시합니다.",
  src: "function topoOrder(commits) {\n  // TODO: 남은 부모 수를 세고, 0이 된 것부터 꺼내세요\n  return commits.map((c) => c.id);\n}",
  sol: "function topoOrder(commits) {\n  const byId = new Map(commits.map((c) => [c.id, c]));\n  const need = new Map(commits.map((c) => [c.id, 0]));\n  const kids = new Map(commits.map((c) => [c.id, []]));\n  commits.forEach((c) => c.ps.forEach((p) => {\n    if (!byId.has(p)) return;\n    need.set(c.id, need.get(c.id) + 1);\n    kids.get(p).push(c.id);\n  }));\n  const ready = commits.filter((c) => need.get(c.id) === 0).map((c) => c.id).sort();\n  const out = [];\n  while (ready.length) {\n    const id = ready.shift();\n    out.push(id);\n    kids.get(id).forEach((k) => {\n      need.set(k, need.get(k) - 1);\n      if (need.get(k) === 0) ready.push(k);\n    });\n    ready.sort();\n  }\n  return out;\n}",
  tests: [['topoOrder([{id:"c",ps:["b"]},{id:"b",ps:["a"]},{id:"a",ps:[]}])', '["a","b","c"]'],
    ['topoOrder([{id:"a",ps:[]},{id:"b",ps:["a"]},{id:"c",ps:["a"]}])', '["a","b","c"]'],
    ['topoOrder([{id:"m",ps:["b","c"]},{id:"b",ps:["a"]},{id:"c",ps:["a"]},{id:"a",ps:[]}])', '["a","b","c","m"]'],
    ['topoOrder([{id:"b",ps:["없음"]}])', '["b"]']],
  edge: [['topoOrder([])', "[]"], ['topoOrder([{id:"a",ps:[]}])', '["a"]']],
  ex: "<code>git log --topo-order</code> 가 하는 일입니다. 기본 로그는 <b>커밋 시각</b> 순으로 보여 주는데, 시각은 컴퓨터 시계에서 오므로 <b>신뢰할 수 없습니다</b> — 시계가 틀린 기계에서 만든 커밋은 조상보다 과거로 표시됩니다.\n위상 정렬은 시각 대신 <b>부모 관계</b>만 씁니다. 그래서 '자식이 부모보다 먼저 나오는' 이상한 로그가 생기지 않습니다.\n세 번째 테스트가 병합 커밋입니다. <code>m</code> 은 부모가 둘이므로 <b>둘 다 나온 뒤에야</b> 놓일 수 있습니다. 남은 부모 수를 세는 방식이 이것을 자연스럽게 처리합니다.\n동률을 사전순으로 고정한 것은 <b>결과를 재현 가능하게</b> 만들기 위해서입니다. 규칙이 없으면 입력 순서에 따라 답이 흔들려, 무엇이 맞는지 판단할 수 없게 됩니다." }
,

/* ───────────── 도구를 직접 만들어 본다 ───────────── */
{ track: "git", k: "status 출력 읽기 · parseStatusPorcelain", cat: "debug",
  q: "<code>git status --porcelain</code> 의 줄들이 배열로 주어집니다. 각 줄은 <b>두 글자 코드 + 공백 + 경로</b> 입니다. 첫 글자는 스테이지, 둘째 글자는 작업 폴더의 상태이고 <code>?</code> 는 추적 안 됨입니다. <code>\"경로:분류\"</code> 를 사전순 배열로 돌려주세요. 분류는 <code>untracked</code>·<code>staged</code>·<code>modified</code>·<code>both</code> 입니다.",
  src: "function parseStatusPorcelain(lines) {\n  // TODO: 앞 두 글자를 각각 떼어 보세요\n  return [];\n}",
  sol: "function parseStatusPorcelain(lines) {\n  return lines.map((line) => {\n    const x = line.charAt(0);\n    const y = line.charAt(1);\n    const file = line.slice(3);\n    if (x === \"?\") return file + \":untracked\";\n    const st = x !== \" \";\n    const wt = y !== \" \";\n    if (st && wt) return file + \":both\";\n    if (st) return file + \":staged\";\n    return file + \":modified\";\n  }).sort();\n}",
  tests: [['parseStatusPorcelain(["M  a.txt"])', '["a.txt:staged"]'],
    ['parseStatusPorcelain([" M b.txt"])', '["b.txt:modified"]'],
    ['parseStatusPorcelain(["MM c.txt"])', '["c.txt:both"]'],
    ['parseStatusPorcelain(["?? z.txt","A  a.txt"])', '["a.txt:staged","z.txt:untracked"]']],
  edge: [['parseStatusPorcelain([])', "[]"], ['parseStatusPorcelain(["?? x/y.txt"])', '["x/y.txt:untracked"]']],
  ex: "<code>--porcelain</code> 은 '<b>기계가 읽으라고</b>' 만든 출력입니다. 사람이 보는 <code>git status</code> 의 문장은 Git 버전이나 언어 설정에 따라 바뀌지만, porcelain 형식은 <b>바꾸지 않겠다고 약속된</b> 형식입니다.\n스크립트에서 사람용 출력을 파싱하면 어느 날 조용히 깨집니다. 도구가 기계용 출력을 따로 제공한다면 반드시 그쪽을 쓰세요 — <code>--porcelain</code>·<code>--format</code>·<code>--json</code> 이 그런 약속입니다.\n두 글자가 <b>서로 다른 공간</b>을 뜻한다는 것이 핵심입니다. 첫 글자는 head↔index, 둘째 글자는 index↔작업 폴더입니다. <code>MM</code> 은 'add 한 뒤 또 고쳤다' 는 뜻이고, 세 번째 테스트가 그 상태입니다.\n경로를 <code>slice(3)</code> 으로 떼는 것은 형식이 <b>고정 폭</b>이기 때문입니다. 공백으로 나누면 이름에 공백이 든 파일에서 깨집니다 — 파일 이름을 만만하게 보면 안 되는 대표적인 자리입니다." },

{ track: "git", k: "다음 버전 계산 · nextVersion", cat: "internals",
  q: "<code>\"v1.4.2\"</code> 같은 태그와 <code>\"major\"</code>·<code>\"minor\"</code>·<code>\"patch\"</code> 중 하나가 주어집니다. <b>다음 버전 태그</b>를 같은 형식으로 돌려주세요. 아래 자리는 0으로 내려갑니다.",
  src: "function nextVersion(tag, kind) {\n  // TODO: v 를 떼고 숫자 셋으로 나눈 뒤 다시 붙이세요\n  return tag;\n}",
  sol: "function nextVersion(tag, kind) {\n  const nums = tag.replace(/^v/, \"\").split(\".\").map(Number);\n  let major = nums[0];\n  let minor = nums[1];\n  let patch = nums[2];\n  if (kind === \"major\") { major += 1; minor = 0; patch = 0; }\n  else if (kind === \"minor\") { minor += 1; patch = 0; }\n  else patch += 1;\n  return \"v\" + major + \".\" + minor + \".\" + patch;\n}",
  tests: [['nextVersion("v1.4.2","patch")', '"v1.4.3"'],
    ['nextVersion("v1.4.2","minor")', '"v1.5.0"'],
    ['nextVersion("v1.4.2","major")', '"v2.0.0"'],
    ['nextVersion("v0.9.9","minor")', '"v0.10.0"']],
  edge: [['nextVersion("1.0.0","patch")', '"v1.0.1"'], ['nextVersion("v9.9.9","major")', '"v10.0.0"']],
  ex: "<b>아래 자리를 0으로 내리는 것</b>이 시맨틱 버전의 규칙입니다. <code>1.4.2</code> 에서 minor 를 올리면 <code>1.5.0</code> 이지 <code>1.5.2</code> 가 아닙니다 — 패치 번호는 '그 minor 안에서 몇 번째 수정인가' 라서 새 minor 에서는 다시 0부터 셉니다.\n네 번째 테스트가 문자열 비교의 함정을 보여 줍니다. <code>0.9.9</code> 의 다음은 <code>0.10.0</code> 이고, 문자열로 비교하면 <code>0.10.0</code> 이 <code>0.9.0</code> 보다 <b>작다</b>고 나옵니다. 버전은 반드시 <b>자리별 숫자</b>로 비교해야 합니다.\n<code>v</code> 접두사는 Git 태그의 관례일 뿐 시맨틱 버전 명세에는 없습니다. 그래서 태그에서 읽을 때는 떼고, 다시 붙일 때만 씁니다 — <b>경계에서 정규화</b>하는 습관입니다.\n실무에서는 이 계산을 사람이 하지 않습니다. 커밋 메시지 규약을 지키면 도구가 <code>feat</code> 은 minor, <code>fix</code> 는 patch, <code>BREAKING CHANGE</code> 는 major 로 읽어 자동으로 올려 줍니다." },

{ track: "git", k: "커밋 메시지 규약 검사 · lintCommitMessage", cat: "review",
  q: "커밋 메시지를 검사해 <b>어긴 규칙 이름</b>을 사전순 배열로 돌려주세요. 규칙은 셋입니다 — <code>too-long</code>(제목이 50자 초과), <code>trailing-period</code>(제목이 마침표로 끝남), <code>no-blank-line</code>(본문이 있는데 제목 다음 줄이 비어 있지 않음).",
  src: "function lintCommitMessage(msg) {\n  // TODO: 줄로 나눈 뒤 첫 줄과 둘째 줄을 각각 보세요\n  return [];\n}",
  sol: "function lintCommitMessage(msg) {\n  const lines = msg.split(\"\\n\");\n  const title = lines[0] || \"\";\n  const out = [];\n  if (title.length > 50) out.push(\"too-long\");\n  if (title.slice(-1) === \".\") out.push(\"trailing-period\");\n  if (lines.length > 1 && lines[1].trim() !== \"\") out.push(\"no-blank-line\");\n  return out.sort();\n}",
  tests: [['lintCommitMessage("결제 타임아웃을 늘린다")', "[]"],
    ['lintCommitMessage("결제 타임아웃을 늘린다.")', '["trailing-period"]'],
    ['lintCommitMessage("제목\\n본문이 바로 붙었다")', '["no-blank-line"]'],
    ['lintCommitMessage("제목\\n\\n본문은 빈 줄 뒤에")', "[]"]],
  edge: [['lintCommitMessage("")', "[]"],
    ['lintCommitMessage("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.")', '["too-long","trailing-period"]']],
  ex: "이런 검사를 <code>commit-msg</code> 훅이나 CI 에 걸어 두면, 규약이 <b>사람의 규율이 아니라 도구의 일</b>이 됩니다. 사람에게 매번 지적하는 것보다 훨씬 값이 쌉니다.\n세 규칙 모두 이유가 있습니다. 제목이 길면 <code>git log --oneline</code> 과 이메일 제목에서 잘리고, 마침표는 제목에 어울리지 않으며, <b>빈 줄이 없으면</b> Git 이 본문까지 제목의 일부로 취급해 요약이 통째로 망가집니다.\n검사 결과를 <b>정렬해서</b> 돌려준 것은 출력이 흔들리지 않게 하기 위해서입니다. 같은 입력에 같은 순서로 답해야 테스트가 안정적이고, 사람도 결과를 비교할 수 있습니다.\n실무에서 이런 도구는 <b>막을지 경고만 할지</b>를 신중히 정해야 합니다. 너무 엄격하면 <code>--no-verify</code> 로 우회하는 문화가 생기고, 그러면 아무것도 검사하지 않는 것과 같아집니다." },

{ track: "git", k: "릴리스 노트 만들기 · changelogFrom", cat: "internals",
  q: "<code>\"feat: 로그인 추가\"</code> 같은 커밋 제목 배열이 주어집니다. <code>feat</code>·<code>fix</code> 만 골라 <code>\"기능: 로그인 추가\"</code>·<code>\"수정: …\"</code> 형태로 바꾸되, <b>기능을 먼저</b> 두고 각 묶음 안에서는 <b>주어진 순서</b>를 지켜 배열로 돌려주세요. 규약을 따르지 않은 줄은 버립니다.",
  src: "function changelogFrom(titles) {\n  // TODO: 콜론 앞의 종류를 떼어 두 묶음으로 나누세요\n  return [];\n}",
  sol: "function changelogFrom(titles) {\n  const feats = [];\n  const fixes = [];\n  titles.forEach((line) => {\n    const at = line.indexOf(\":\");\n    if (at < 0) return;\n    const kind = line.slice(0, at).trim();\n    const text = line.slice(at + 1).trim();\n    if (!text) return;\n    if (kind === \"feat\") feats.push(\"기능: \" + text);\n    else if (kind === \"fix\") fixes.push(\"수정: \" + text);\n  });\n  return feats.concat(fixes);\n}",
  tests: [['changelogFrom(["feat: 로그인 추가"])', '["기능: 로그인 추가"]'],
    ['changelogFrom(["fix: 타임아웃","feat: 검색"])', '["기능: 검색","수정: 타임아웃"]'],
    ['changelogFrom(["chore: 의존성 정리"])', "[]"],
    ['changelogFrom(["feat: A","feat: B","fix: C"])', '["기능: A","기능: B","수정: C"]']],
  edge: [['changelogFrom([])', "[]"], ['changelogFrom(["feat:"])', "[]"]],
  ex: "<b>관례적 커밋(Conventional Commits)</b> 규약을 지키면 릴리스 노트가 이렇게 기계적으로 만들어집니다. 규약의 값어치는 '보기 좋아서' 가 아니라 <b>기계가 읽을 수 있어서</b>입니다.\n<code>chore</code>·<code>refactor</code> 를 버리는 것도 의도입니다. 릴리스 노트는 <b>사용자가 체감하는 변화</b>만 담아야 합니다. 내부 정리까지 다 적으면 아무도 읽지 않는 목록이 됩니다.\n마지막 엣지 케이스처럼 <b>내용이 빈 줄</b>을 걸러야 합니다. 형식만 맞고 알맹이가 없는 입력은 실제로 들어오고, 그대로 두면 '기능: ' 이라는 빈 항목이 릴리스 노트에 남습니다.\n묶음 순서를 고정하고 묶음 안에서는 입력 순서를 지킨 것은 <b>재현 가능성</b> 때문입니다. 같은 커밋 목록에서 항상 같은 노트가 나와야, 자동 생성 결과를 사람이 검토할 수 있습니다." }

];
