/* React · HTML/CSS 실행형 문항 — 브라우저에서 실제로 렌더하고 DOM 을 검사한다.
   둘 다 오프라인 1순위 엔진(벤더링된 React + Sucrase, 브라우저 자체 CSS)이라 러너가 없어도 풀린다.

   React 하네스가 주는 도구: Q QA COUNT TXT ATTR CLICK CLICKN TYPE
   HTML  하네스가 주는 도구: Q QA COUNT CS TXT ATTR RECT W H SRCCSS
   컴포넌트는 반드시 function App 으로 선언되어야 한다. */
module.exports = { react: [
{ k:"조건부 렌더링", lv:1,
  q:"버튼을 누를 때마다 상세 내용이 나타났다 사라지는 토글을 만드세요. 버튼은 <code>.tog</code>, 상세 내용은 <code>.detail</code> 클래스이고 처음에는 <b>상세가 없어야</b> 합니다. 상세 안의 글자는 '내용' 입니다.",
  src:"function App() {\n  // 여기에 구현하세요\n  return <div></div>;\n}",
  sol:"function App() {\n  const [open, setOpen] = React.useState(false);\n  return (\n    <div>\n      <button className=\"tog\" onClick={() => setOpen(!open)}>토글</button>\n      {open && <div className=\"detail\">내용</div>}\n    </div>\n  );\n}",
  tests:[{d:"처음에는 상세가 없다", js:"COUNT('.detail')===0"},
         {d:"한 번 누르면 나타난다", js:"(CLICK('.tog'), COUNT('.detail')===1)"},
         {d:"상세에 '내용' 이 있다", js:"TXT('.detail')==='내용'"},
         {d:"다시 누르면 사라진다", js:"(CLICK('.tog'), COUNT('.detail')===0)"}],
  ex:"조건부 렌더링은 '숨기는' 게 아니라 <b>만들지 않는</b> 것입니다. <code>{open &amp;&amp; &lt;div/&gt;}</code> 는 open 이 거짓이면 아무 요소도 만들지 않으므로 DOM 에서 완전히 사라집니다. CSS 로 display:none 하는 것과 달라서, 안에 있던 상태와 이펙트도 함께 정리됩니다.\n⚠️ 주의: <code>{count &amp;&amp; &lt;div/&gt;}</code> 처럼 숫자를 조건에 쓰면 0 일 때 <b>0 이 그대로 화면에 찍힙니다</b>. 조건은 항상 불리언으로 만드세요." },

{ k:"리스트 렌더링과 key", lv:1,
  q:"주어진 배열을 <code>ul.list</code> 안에 <code>li</code> 로 렌더하세요. 각 항목의 글자는 배열의 값 그대로이고, 항목마다 <code>key</code> 를 주어야 합니다.",
  src:"const ITEMS = ['사과', '배', '감'];\n\nfunction App() {\n  // ITEMS 를 ul.list 안에 li 로 렌더하세요\n  return <div></div>;\n}",
  sol:"const ITEMS = ['사과', '배', '감'];\n\nfunction App() {\n  return (\n    <ul className=\"list\">\n      {ITEMS.map((it) => (\n        <li key={it}>{it}</li>\n      ))}\n    </ul>\n  );\n}",
  tests:[{d:"ul.list 가 있다", js:"COUNT('ul.list')===1"},
         {d:"li 가 3개다", js:"COUNT('ul.list li')===3"},
         {d:"첫 항목이 '사과'", js:"QA('ul.list li')[0].textContent.trim()==='사과'"},
         {d:"마지막 항목이 '감'", js:"QA('ul.list li')[2].textContent.trim()==='감'"}],
  ex:"<code>map</code> 이 돌려준 배열을 그대로 JSX 에 넣으면 React 가 각 원소를 렌더합니다. <code>key</code> 는 화면에 보이지 않지만, 목록이 바뀔 때 React 가 '어느 항목이 그대로이고 어느 것이 새것인지' 판단하는 기준입니다.\n⚠️ 주의: key 에 배열 인덱스를 쓰면 중간에 항목을 넣거나 지울 때 잘못된 항목이 재사용되어, 입력값이나 애니메이션이 엉뚱한 행에 남습니다. 값 자체가 고유하면 그 값을, 아니면 안정적인 id 를 쓰세요." },

{ k:"제어 컴포넌트", lv:2,
  q:"입력창에 글자를 치면 그 아래에 그대로 보여 주세요. 입력은 <code>.in</code>, 출력은 <code>.out</code> 클래스입니다. 입력값은 React 상태로 관리해야 합니다(제어 컴포넌트).",
  src:"function App() {\n  return (\n    <div>\n      <input className=\"in\" />\n      <p className=\"out\"></p>\n    </div>\n  );\n}",
  sol:"function App() {\n  const [v, setV] = React.useState('');\n  return (\n    <div>\n      <input className=\"in\" value={v} onChange={(e) => setV(e.target.value)} />\n      <p className=\"out\">{v}</p>\n    </div>\n  );\n}",
  tests:[{d:"처음에는 출력이 비어 있다", js:"TXT('.out')===''"},
         {d:"입력하면 그대로 보인다", js:"(TYPE('.in','안녕'), TXT('.out')==='안녕')"},
         {d:"다시 입력하면 갱신된다", js:"(TYPE('.in','바뀜'), TXT('.out')==='바뀜')"},
         {d:"입력창의 값도 상태를 따른다", js:"Q('.in').value==='바뀜'"}],
  ex:"제어 컴포넌트는 입력창의 값을 <b>DOM 이 아니라 React 상태가</b> 소유하는 방식입니다. <code>value</code> 로 상태를 내려보내고 <code>onChange</code> 로 되받습니다.\n⚠️ 주의: <code>value</code> 만 주고 <code>onChange</code> 를 안 주면 입력이 아예 안 됩니다 — 상태가 안 바뀌니 React 가 매번 옛 값으로 되돌리기 때문입니다. 반대로 초기값만 주고 싶다면 <code>defaultValue</code> 를 쓰세요." },

{ k:"이전 상태로 갱신하기", lv:2,
  q:"버튼 한 번에 카운터를 <b>2씩</b> 올리세요. 단 setter 를 <b>두 번</b> 불러 1씩 두 번 올리는 방식으로 구현해야 합니다. 숫자는 <code>.cnt</code>, 버튼은 <code>.inc</code> 이고 초기값은 0 입니다.",
  src:"function App() {\n  const [n, setN] = React.useState(0);\n  const bump = () => {\n    setN(n + 1);\n    setN(n + 1);   // 왜 2가 안 오를까?\n  };\n  return (\n    <div>\n      <span className=\"cnt\">{n}</span>\n      <button className=\"inc\" onClick={bump}>+</button>\n    </div>\n  );\n}",
  sol:"function App() {\n  const [n, setN] = React.useState(0);\n  const bump = () => {\n    setN((p) => p + 1);\n    setN((p) => p + 1);\n  };\n  return (\n    <div>\n      <span className=\"cnt\">{n}</span>\n      <button className=\"inc\" onClick={bump}>+</button>\n    </div>\n  );\n}",
  tests:[{d:"초기값 0", js:"TXT('.cnt')==='0'"},
         {d:"한 번 누르면 2", js:"(CLICK('.inc'), TXT('.cnt')==='2')"},
         {d:"두 번 누르면 4", js:"(CLICK('.inc'), TXT('.cnt')==='4')"},
         {d:"다섯 번 누르면 10", js:"(CLICK('.inc'),CLICK('.inc'),CLICK('.inc'), TXT('.cnt')==='10')"}],
  ex:"한 번의 이벤트 안에서 <code>n</code> 은 <b>그 렌더 시점에 고정된 값</b>입니다. <code>setN(n+1)</code> 을 두 번 불러도 둘 다 '0+1' 을 예약하므로 결과는 1 입니다.\n🔧 함수형 갱신 <code>setN(p =&gt; p+1)</code> 은 '예약된 직전 값' 을 받아 계산하므로 두 번이 제대로 쌓입니다.\n🛡 규칙: 새 값이 <b>이전 값에 의존하면</b> 항상 함수형 갱신을 쓰세요. 이 버그는 클릭을 빠르게 여러 번 할 때만 드러나기도 해서 재현이 어렵습니다." },

{ k:"입력으로 목록 거르기", lv:2,
  q:"검색어를 입력하면 목록이 <b>포함하는 항목만</b> 남도록 하세요. 입력은 <code>.q</code>, 목록은 <code>ul.list</code> 안의 <code>li</code> 입니다. 처음에는 전부 보입니다.",
  src:"const NAMES = ['apple', 'banana', 'cherry', 'grape'];\n\nfunction App() {\n  // 검색어를 상태로 두고 걸러진 목록을 렌더하세요\n  return <div></div>;\n}",
  sol:"const NAMES = ['apple', 'banana', 'cherry', 'grape'];\n\nfunction App() {\n  const [q, setQ] = React.useState('');\n  const shown = NAMES.filter((n) => n.includes(q));\n  return (\n    <div>\n      <input className=\"q\" value={q} onChange={(e) => setQ(e.target.value)} />\n      <ul className=\"list\">\n        {shown.map((n) => (\n          <li key={n}>{n}</li>\n        ))}\n      </ul>\n    </div>\n  );\n}",
  tests:[{d:"처음에는 4개 모두 보인다", js:"COUNT('ul.list li')===4"},
         {d:"'an' 을 치면 banana 만 남는다", js:"(TYPE('.q','an'), COUNT('ul.list li')===1)"},
         {d:"남은 항목이 banana", js:"QA('ul.list li')[0].textContent.trim()==='banana'"},
         {d:"지우면 다시 4개", js:"(TYPE('.q',''), COUNT('ul.list li')===4)"}],
  ex:"걸러진 목록은 <b>상태로 따로 두지 않습니다</b>. 검색어라는 하나의 상태에서 매 렌더마다 계산해 내면 두 값이 어긋날 일이 없습니다 — 이것이 '파생 상태를 만들지 말라' 는 원칙입니다.\n⚠️ 주의: <code>filter</code> 결과를 <code>useState</code> 에 또 담고 <code>useEffect</code> 로 동기화하는 코드를 흔히 보는데, 렌더가 두 번 돌고 한 프레임 동안 옛 목록이 보입니다. 계산으로 끝낼 수 있으면 상태를 늘리지 마세요." },

{ k:"props 로 자식에게 내려보내기", lv:2,
  q:"이름을 받아 인사말을 보여 주는 <code>Hello</code> 컴포넌트를 만들고, App 에서 서로 다른 이름 두 개로 렌더하세요. 각 인사말은 <code>.hi</code> 클래스이고 내용은 '안녕, 이름!' 형식입니다.",
  src:"function App() {\n  // Hello 컴포넌트를 만들고 '김', '박' 으로 두 번 렌더하세요\n  return <div></div>;\n}",
  sol:"function Hello({ name }) {\n  return <p className=\"hi\">안녕, {name}!</p>;\n}\n\nfunction App() {\n  return (\n    <div>\n      <Hello name=\"김\" />\n      <Hello name=\"박\" />\n    </div>\n  );\n}",
  tests:[{d:"인사말이 2개다", js:"COUNT('.hi')===2"},
         {d:"첫 번째는 '안녕, 김!'", js:"QA('.hi')[0].textContent.replace(/\\s+/g,' ').trim()==='안녕, 김!'"},
         {d:"두 번째는 '안녕, 박!'", js:"QA('.hi')[1].textContent.replace(/\\s+/g,' ').trim()==='안녕, 박!'"},
         {d:"같은 컴포넌트를 재사용했다", js:"QA('.hi')[0].tagName===QA('.hi')[1].tagName"}],
  ex:"props 는 부모가 자식에게 주는 <b>읽기 전용 입력</b>입니다. 같은 컴포넌트를 다른 props 로 여러 번 렌더하는 것이 재사용의 기본 단위입니다.\n⚠️ 주의: 자식이 props 를 직접 수정하면 안 됩니다. 값을 바꿔야 한다면 상태를 부모에 두고 <b>바꾸는 함수</b>를 props 로 내려보내세요(상태 끌어올리기). 그래야 데이터가 한 방향으로만 흐릅니다." },

{ k:"객체 상태를 불변으로 갱신", lv:3,
  q:"폼의 두 필드를 하나의 객체 상태로 관리하세요. 이름 입력은 <code>.name</code>, 도시 입력은 <code>.city</code>, 결과 표시는 <code>.out</code> 이고 '이름/도시' 형식으로 보여 줍니다. 한 필드를 고쳐도 다른 필드가 사라지면 안 됩니다.",
  src:"function App() {\n  const [f, setF] = React.useState({ name: '', city: '' });\n  // 두 입력을 연결하세요 — 한쪽을 고쳐도 다른 쪽이 남아야 합니다\n  return <div></div>;\n}",
  sol:"function App() {\n  const [f, setF] = React.useState({ name: '', city: '' });\n  const set = (k) => (e) => setF({ ...f, [k]: e.target.value });\n  return (\n    <div>\n      <input className=\"name\" value={f.name} onChange={set('name')} />\n      <input className=\"city\" value={f.city} onChange={set('city')} />\n      <p className=\"out\">{f.name}/{f.city}</p>\n    </div>\n  );\n}",
  tests:[{d:"처음에는 '/' 만 있다", js:"TXT('.out')==='/'"},
         {d:"이름을 넣으면 반영된다", js:"(TYPE('.name','김'), TXT('.out')==='김/')"},
         {d:"도시를 넣어도 이름이 남는다", js:"(TYPE('.city','서울'), TXT('.out')==='김/서울')"},
         {d:"이름을 바꿔도 도시가 남는다", js:"(TYPE('.name','박'), TXT('.out')==='박/서울')"}],
  ex:"객체 상태는 <b>새 객체를 만들어</b> 넣어야 합니다. <code>{...f, [k]: v}</code> 는 기존 필드를 모두 복사한 뒤 한 칸만 덮어씁니다.\n⚠️ 주의: <code>f.name = v; setF(f)</code> 처럼 원본을 고쳐 같은 객체를 넣으면 React 는 <b>참조가 같아서 안 바뀐 것으로 보고 다시 그리지 않습니다</b>. 반대로 <code>setF({name: v})</code> 처럼 전개를 빼먹으면 city 가 통째로 사라집니다 — 둘 다 흔한 실수입니다." },

{ k:"항목 추가와 삭제", lv:3,
  q:"입력한 내용을 목록에 추가하고, 각 항목의 삭제 버튼으로 지울 수 있게 하세요. 입력 <code>.in</code>, 추가 버튼 <code>.add</code>, 목록 <code>ul.list</code> 의 <code>li</code>, 삭제 버튼은 각 항목 안의 <code>.del</code> 입니다. 추가 후 입력창은 비워집니다.",
  src:"function App() {\n  const [items, setItems] = React.useState([]);\n  // 추가와 삭제를 구현하세요\n  return <div></div>;\n}",
  sol:"function App() {\n  const [items, setItems] = React.useState([]);\n  const [v, setV] = React.useState('');\n  const add = () => {\n    if (!v) return;\n    setItems([...items, v]);\n    setV('');\n  };\n  const del = (i) => setItems(items.filter((_, k) => k !== i));\n  return (\n    <div>\n      <input className=\"in\" value={v} onChange={(e) => setV(e.target.value)} />\n      <button className=\"add\" onClick={add}>추가</button>\n      <ul className=\"list\">\n        {items.map((it, i) => (\n          <li key={i}>\n            {it}\n            <button className=\"del\" onClick={() => del(i)}>x</button>\n          </li>\n        ))}\n      </ul>\n    </div>\n  );\n}",
  tests:[{d:"처음에는 비어 있다", js:"COUNT('ul.list li')===0"},
         {d:"하나 추가하면 1개", js:"(TYPE('.in','가'), CLICK('.add'), COUNT('ul.list li')===1)"},
         {d:"추가 후 입력창이 비워진다", js:"Q('.in').value===''"},
         {d:"두 개 더 추가하면 3개", js:"(TYPE('.in','나'),CLICK('.add'),TYPE('.in','다'),CLICK('.add'), COUNT('ul.list li')===3)"},
         {d:"가운데 것을 지우면 2개가 남는다", js:"(CLICKN('.del',1), COUNT('ul.list li')===2 && QA('ul.list li')[1].textContent.indexOf('다')>=0)"}],
  ex:"추가는 <code>[...items, v]</code>, 삭제는 <code>filter</code> — 둘 다 <b>새 배열</b>을 만듭니다. <code>push</code>·<code>splice</code> 는 원본을 고쳐 참조가 그대로라 다시 그려지지 않습니다.\n⚠️ 주의: 여기서는 항목이 뒤에만 추가되고 key 도 인덱스라 문제가 없지만, 중간 삽입이나 정렬이 생기면 인덱스 key 는 곧바로 버그가 됩니다. 실무에서는 추가 시점에 고유 id 를 붙이세요." },

{ k:"useEffect 와 정리 함수", lv:3,
  q:"마운트될 때 1초 간격 타이머를 걸고, 언마운트될 때 반드시 해제하세요. 화면에는 경과 초를 <code>.sec</code> 에 표시하고(초기 0), 해제 여부를 확인할 수 있도록 <code>window.__cleared</code> 를 정리 함수에서 true 로 설정하세요. 토글 버튼 <code>.tog</code> 로 타이머 컴포넌트를 켜고 끕니다.",
  src:"function Timer() {\n  const [s, setS] = React.useState(0);\n  // 1초마다 s 를 1 올리고, 언마운트 때 정리하세요\n  return <span className=\"sec\">{s}</span>;\n}\n\nfunction App() {\n  const [on, setOn] = React.useState(true);\n  return (\n    <div>\n      <button className=\"tog\" onClick={() => setOn(!on)}>토글</button>\n      {on && <Timer />}\n    </div>\n  );\n}",
  sol:"function Timer() {\n  const [s, setS] = React.useState(0);\n  React.useEffect(() => {\n    const id = setInterval(() => setS((p) => p + 1), 1000);\n    return () => {\n      clearInterval(id);\n      window.__cleared = true;\n    };\n  }, []);\n  return <span className=\"sec\">{s}</span>;\n}\n\nfunction App() {\n  const [on, setOn] = React.useState(true);\n  return (\n    <div>\n      <button className=\"tog\" onClick={() => setOn(!on)}>토글</button>\n      {on && <Timer />}\n    </div>\n  );\n}",
  tests:[{d:"처음에 0 이 보인다", js:"TXT('.sec')==='0'"},
         {d:"끄면 타이머가 사라진다", js:"(CLICK('.tog'), COUNT('.sec')===0)"},
         {d:"정리 함수가 호출됐다", js:"window.__cleared===true"},
         {d:"다시 켜면 0부터 시작한다", js:"(CLICK('.tog'), TXT('.sec')==='0')"}],
  ex:"<code>useEffect</code> 가 돌려주는 함수가 <b>정리 함수</b>입니다. 언마운트될 때, 그리고 의존성이 바뀌어 이펙트를 다시 걸기 직전에 호출됩니다.\n⚠️ 주의: 정리를 빼먹으면 컴포넌트가 사라진 뒤에도 타이머가 계속 돌며 없는 상태를 갱신하려 듭니다 — 메모리 누수이자 경고의 원인입니다. 의존성 배열 <code>[]</code> 는 '마운트 때 한 번' 을 뜻하고, 안에서 쓰는 값이 있으면 반드시 배열에 넣어야 옛 값을 붙잡지 않습니다." },

{ k:"상태 끌어올리기", lv:3,
  q:"두 개의 버튼(<code>.a</code>, <code>.b</code>)이 <b>하나의 카운터</b>를 공유하도록 만드세요. 어느 쪽을 눌러도 같은 숫자 <code>.total</code> 이 1씩 올라갑니다. 버튼은 별도 컴포넌트로 만들고 상태는 부모가 가집니다.",
  src:"function Btn(props) {\n  // 부모가 준 함수를 호출하기만 하는 버튼\n  return <button></button>;\n}\n\nfunction App() {\n  // 상태를 여기서 관리하고 Btn 두 개에 내려보내세요\n  return <div></div>;\n}",
  sol:"function Btn({ cls, onHit }) {\n  return (\n    <button className={cls} onClick={onHit}>\n      +\n    </button>\n  );\n}\n\nfunction App() {\n  const [n, setN] = React.useState(0);\n  const hit = () => setN((p) => p + 1);\n  return (\n    <div>\n      <span className=\"total\">{n}</span>\n      <Btn cls=\"a\" onHit={hit} />\n      <Btn cls=\"b\" onHit={hit} />\n    </div>\n  );\n}",
  tests:[{d:"초기값 0", js:"TXT('.total')==='0'"},
         {d:"a 를 누르면 1", js:"(CLICK('.a'), TXT('.total')==='1')"},
         {d:"b 를 누르면 2 — 같은 값을 공유한다", js:"(CLICK('.b'), TXT('.total')==='2')"},
         {d:"섞어 눌러도 누적된다", js:"(CLICK('.a'),CLICK('.b'),CLICK('.a'), TXT('.total')==='5')"}],
  ex:"두 컴포넌트가 같은 값을 써야 하면 그 값을 <b>공통 부모로 끌어올립니다</b>. 자식은 값을 갖지 않고 '눌렸다' 는 사실만 알립니다.\n⚠️ 주의: 자식마다 각자 상태를 두고 부모에서 합치려 하면 반드시 어긋납니다. 하나의 진실 공급원(single source of truth)을 정하는 것이 핵심이고, 이 원칙을 앱 전체로 확장한 것이 상태 관리 라이브러리입니다." },

{ k:"조건에 따라 클래스 바꾸기", lv:2,
  q:"버튼을 누르면 상자의 클래스가 <code>on</code> 과 <code>off</code> 사이를 오가게 하세요. 상자는 <code>.box</code>, 버튼은 <code>.tog</code> 이고 처음 상태는 <code>off</code> 입니다.",
  src:"function App() {\n  const [on, setOn] = React.useState(false);\n  // .box 에 on/off 클래스를 조건부로 붙이세요\n  return <div></div>;\n}",
  sol:"function App() {\n  const [on, setOn] = React.useState(false);\n  return (\n    <div>\n      <button className=\"tog\" onClick={() => setOn(!on)}>토글</button>\n      <div className={'box ' + (on ? 'on' : 'off')} />\n    </div>\n  );\n}",
  tests:[{d:"처음에는 off 다", js:"Q('.box').classList.contains('off')===true"},
         {d:"처음에는 on 이 아니다", js:"Q('.box').classList.contains('on')===false"},
         {d:"누르면 on 이 된다", js:"(CLICK('.tog'), Q('.box').classList.contains('on')===true)"},
         {d:"누르면 off 가 빠진다", js:"Q('.box').classList.contains('off')===false"}],
  ex:"JSX 의 클래스 속성은 <code>class</code> 가 아니라 <code>className</code> 입니다(<code>class</code> 가 자바스크립트 예약어이기 때문). 값은 그냥 문자열이므로 조건으로 조립하면 됩니다.\n⚠️ 주의: 클래스가 서너 개로 늘어나면 문자열 조립이 금방 지저분해집니다. 배열을 만들어 <code>.filter(Boolean).join(' ')</code> 하거나 clsx 같은 작은 도구를 쓰는 게 읽기 좋습니다." },

{ k:"이벤트 버블링 막기", lv:2,
  q:"카드 전체를 누르면 카드가 열리고(<code>.oc</code> 증가), 카드 안의 삭제 버튼을 누르면 <b>삭제만</b> 일어나야 합니다(<code>.ic</code> 만 증가). 지금은 삭제를 눌러도 카드가 함께 열립니다. 카드는 <code>.card</code>, 빈 영역은 <code>.pad</code>, 삭제 버튼은 <code>.del</code> 입니다.",
  src:"function App() {\n  const [oc, setOc] = React.useState(0);\n  const [ic, setIc] = React.useState(0);\n  return (\n    <div>\n      <div className=\"card\" onClick={() => setOc((p) => p + 1)}>\n        <span className=\"pad\">카드 본문</span>\n        <button className=\"del\" onClick={() => setIc((p) => p + 1)}>삭제</button>\n      </div>\n      <span className=\"oc\">{oc}</span>\n      <span className=\"ic\">{ic}</span>\n    </div>\n  );\n}",
  sol:"function App() {\n  const [oc, setOc] = React.useState(0);\n  const [ic, setIc] = React.useState(0);\n  const del = (e) => {\n    e.stopPropagation();\n    setIc((p) => p + 1);\n  };\n  return (\n    <div>\n      <div className=\"card\" onClick={() => setOc((p) => p + 1)}>\n        <span className=\"pad\">카드 본문</span>\n        <button className=\"del\" onClick={del}>삭제</button>\n      </div>\n      <span className=\"oc\">{oc}</span>\n      <span className=\"ic\">{ic}</span>\n    </div>\n  );\n}",
  tests:[{d:"처음에는 둘 다 0", js:"TXT('.oc')==='0' && TXT('.ic')==='0'"},
         {d:"삭제를 누르면 삭제만 오른다", js:"(CLICK('.del'), TXT('.ic')==='1' && TXT('.oc')==='0')"},
         {d:"본문을 누르면 카드가 열린다", js:"(CLICK('.pad'), TXT('.oc')==='1')"},
         {d:"본문 클릭은 삭제를 건드리지 않는다", js:"TXT('.ic')==='1'"},
         {d:"삭제를 또 눌러도 카드는 그대로", js:"(CLICK('.del'), TXT('.ic')==='2' && TXT('.oc')==='1')"}],
  ex:"클릭은 눌린 요소에서 시작해 조상으로 <b>거슬러 올라갑니다</b>(버블링). 그래서 카드 안의 버튼을 누르면 버튼 핸들러와 카드 핸들러가 <b>둘 다</b> 실행됩니다.\n🔧 <code>e.stopPropagation()</code> 이 그 전파를 그 지점에서 멈춥니다.\n⚠️ <code>preventDefault()</code> 와 헷갈리지 마세요 — 그건 전파가 아니라 <b>브라우저 기본 동작</b>(링크 이동·폼 제출)을 막습니다. 목록 행 전체가 클릭 가능하고 그 안에 버튼이 있는 UI 에서 이 버그가 가장 자주 나옵니다.\n💡 남용하면 바깥에서 '아무 데나 클릭하면 닫기' 같은 처리가 조용히 죽습니다. 막기보다 <code>e.target</code> 을 확인해 분기하는 편이 나을 때도 있습니다." }
],
html: [
{ k:"flex 로 양끝 배치", lv:2,
  q:"헤더의 로고를 왼쪽 끝, 메뉴를 오른쪽 끝에 붙이고 <b>세로는 가운데</b>로 맞추세요. <code>.bar</code> 는 flex 컨테이너여야 합니다.",
  src:"<style>\n  .bar { height: 60px; background: #eef; }\n  .logo { width: 60px; height: 20px; background: #47f; }\n  .menu { width: 90px; height: 20px; background: #f74; }\n</style>\n<div class=\"bar\">\n  <div class=\"logo\"></div>\n  <div class=\"menu\"></div>\n</div>",
  sol:"<style>\n  .bar { height: 60px; background: #eef; display: flex; justify-content: space-between; align-items: center; }\n  .logo { width: 60px; height: 20px; background: #47f; }\n  .menu { width: 90px; height: 20px; background: #f74; }\n</style>\n<div class=\"bar\">\n  <div class=\"logo\"></div>\n  <div class=\"menu\"></div>\n</div>",
  tests:[{d:".bar 가 flex 컨테이너다", js:"CS('.bar','display')==='flex'"},
         {d:"로고가 왼쪽 끝에 붙는다", js:"Math.abs(RECT('.logo').left-RECT('.bar').left)<3"},
         {d:"메뉴가 오른쪽 끝에 붙는다", js:"Math.abs(RECT('.menu').right-RECT('.bar').right)<3"},
         {d:"둘 다 세로 가운데다", js:"Math.abs((RECT('.logo').top+RECT('.logo').bottom)/2-(RECT('.bar').top+RECT('.bar').bottom)/2)<3 && Math.abs((RECT('.menu').top+RECT('.menu').bottom)/2-(RECT('.bar').top+RECT('.bar').bottom)/2)<3"}],
  ex:"<code>justify-content: space-between</code> 은 남는 공간을 <b>항목 사이에만</b> 나눠 주므로 첫 항목은 시작에, 마지막 항목은 끝에 붙습니다. <code>align-items: center</code> 가 교차축(세로)을 가운데로 맞춥니다.\n💡 항목이 셋이 되면 가운데가 정확히 중앙이 아닐 수 있습니다(양옆 폭이 다르면). 진짜 중앙이 필요하면 가운데 항목을 <code>position: absolute</code> 로 띄우거나 3열 grid 를 쓰세요." },

{ k:"grid 로 반응형 카드", lv:3,
  q:"카드들을 <b>3열 그리드</b>로 배치하고 열 사이 간격을 10px 로 주세요. <code>.grid</code> 가 grid 컨테이너이고, 각 카드는 같은 너비여야 합니다.",
  src:"<style>\n  .grid { width: 320px; background: #eef; }\n  .card { height: 40px; background: #47f; }\n</style>\n<div class=\"grid\">\n  <div class=\"card\"></div>\n  <div class=\"card\"></div>\n  <div class=\"card\"></div>\n</div>",
  sol:"<style>\n  .grid { width: 320px; background: #eef; display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px; }\n  .card { height: 40px; background: #47f; }\n</style>\n<div class=\"grid\">\n  <div class=\"card\"></div>\n  <div class=\"card\"></div>\n  <div class=\"card\"></div>\n</div>",
  tests:[{d:".grid 가 grid 컨테이너다", js:"CS('.grid','display')==='grid'"},
         {d:"카드 3개가 한 줄에 있다", js:"Math.abs(RECT(QA('.card')[0].tagName+'') ? 0 : 0)===0 && Math.abs(QA('.card')[0].getBoundingClientRect().top-QA('.card')[2].getBoundingClientRect().top)<2"},
         {d:"세 카드의 너비가 같다", js:"(function(){var w=QA('.card').map(function(e){return Math.round(e.getBoundingClientRect().width);});return w[0]===w[1]&&w[1]===w[2];})()"},
         {d:"열 간격이 10px 다", js:"Math.abs((QA('.card')[1].getBoundingClientRect().left-QA('.card')[0].getBoundingClientRect().right)-10)<1.5"}],
  ex:"<code>grid-template-columns: repeat(3, 1fr)</code> 은 남는 공간을 셋으로 <b>똑같이</b> 나눕니다. <code>1fr</code> 은 '남은 공간의 한 몫' 이라 컨테이너 너비가 바뀌어도 비율이 유지됩니다.\n💡 <code>gap</code> 은 항목 <b>사이</b>에만 들어가고 바깥 가장자리에는 붙지 않습니다 — margin 으로 간격을 주던 시절의 '첫/마지막 항목만 margin 빼기' 같은 잔재주가 필요 없어집니다.\n⚠️ 폭이 좁아질 때 열 수를 자동으로 줄이려면 <code>repeat(auto-fit, minmax(100px, 1fr))</code> 을 쓰세요." },

{ k:"box-sizing 과 실제 너비", lv:2,
  q:"패딩과 테두리를 포함해 상자의 <b>전체 너비가 정확히 200px</b> 이 되게 하세요. 지금은 패딩과 테두리가 더해져 더 넓습니다. <code>width: 200px</code> 는 그대로 두세요.",
  src:"<style>\n  .box { width: 200px; padding: 20px; border: 5px solid #47f; background: #eef; }\n</style>\n<div class=\"box\">내용</div>",
  sol:"<style>\n  .box { width: 200px; padding: 20px; border: 5px solid #47f; background: #eef; box-sizing: border-box; }\n</style>\n<div class=\"box\">내용</div>",
  tests:[{d:"전체 너비가 200px 다", js:"Math.abs(W('.box')-200)<1"},
         {d:"box-sizing 이 border-box 다", js:"CS('.box','box-sizing')==='border-box'"},
         {d:"패딩 20px 를 유지했다", js:"parseFloat(CS('.box','padding-left'))===20"},
         {d:"테두리 5px 를 유지했다", js:"parseFloat(CS('.box','border-left-width'))===5"}],
  ex:"기본값 <code>content-box</code> 에서 <code>width</code> 는 <b>내용 영역만</b>의 너비입니다. 패딩 20+20 과 테두리 5+5 가 더해져 실제로는 250px 를 차지합니다.\n🔧 <code>border-box</code> 로 바꾸면 <code>width</code> 가 '테두리까지 포함한 전체' 를 뜻하게 되어 계산이 직관적입니다.\n💡 그래서 많은 프로젝트가 <code>*, *::before, *::after { box-sizing: border-box }</code> 를 리셋에 넣습니다. 레이아웃 계산이 어긋나면 가장 먼저 확인할 속성입니다." },

{ k:"position absolute 의 기준", lv:3,
  q:"배지를 카드의 <b>오른쪽 위 모서리</b>에 겹쳐 놓으세요(모서리에서 각각 8px 안쪽). 카드가 기준이 되어야 하고, 페이지를 스크롤해도 카드에 붙어 있어야 합니다.",
  src:"<style>\n  .wrap { padding: 40px; }\n  .card { width: 200px; height: 120px; background: #eef; }\n  .badge { width: 24px; height: 24px; background: #f74; }\n</style>\n<div class=\"wrap\">\n  <div class=\"card\">\n    <div class=\"badge\"></div>\n  </div>\n</div>",
  sol:"<style>\n  .wrap { padding: 40px; }\n  .card { width: 200px; height: 120px; background: #eef; position: relative; }\n  .badge { width: 24px; height: 24px; background: #f74; position: absolute; top: 8px; right: 8px; }\n</style>\n<div class=\"wrap\">\n  <div class=\"card\">\n    <div class=\"badge\"></div>\n  </div>\n</div>",
  tests:[{d:"카드가 기준(position: relative)이다", js:"CS('.card','position')==='relative'"},
         {d:"배지가 absolute 다", js:"CS('.badge','position')==='absolute'"},
         {d:"카드 오른쪽에서 8px 안쪽이다", js:"Math.abs(RECT('.card').right-RECT('.badge').right-8)<1.5"},
         {d:"카드 위에서 8px 아래다", js:"Math.abs(RECT('.badge').top-RECT('.card').top-8)<1.5"}],
  ex:"<code>position: absolute</code> 는 가장 가까운 <b>배치된 조상</b>(static 이 아닌 조상)을 기준으로 자리를 잡습니다. 아무도 없으면 문서 전체가 기준이 되어 엉뚱한 곳으로 날아갑니다.\n🔧 그래서 '기준이 될 부모에 <code>position: relative</code>' 가 짝을 이루는 관용구입니다.\n⚠️ 주의: <code>transform</code>·<code>filter</code>·<code>will-change</code> 가 걸린 조상도 기준이 됩니다. 배지가 갑자기 다른 곳에 붙는다면 중간에 <code>transform</code> 이 생겼는지 확인하세요." },

{ k:"선택자 우선순위", lv:3,
  q:"제목 글자색을 빨강(rgb(255, 0, 0))으로 만드세요. 기존 규칙을 <b>지우지 말고</b>, 우선순위가 더 높은 규칙을 추가해서 이겨야 합니다. <code>!important</code> 는 쓰지 마세요.",
  src:"<style>\n  .card p { color: rgb(0, 0, 255); }\n  p { color: rgb(0, 128, 0); }\n</style>\n<div class=\"card\">\n  <p id=\"title\">제목</p>\n</div>",
  sol:"<style>\n  .card p { color: rgb(0, 0, 255); }\n  p { color: rgb(0, 128, 0); }\n  #title { color: rgb(255, 0, 0); }\n</style>\n<div class=\"card\">\n  <p id=\"title\">제목</p>\n</div>",
  tests:[{d:"글자색이 빨강이다", js:"CS('#title','color')==='rgb(255, 0, 0)'"},
         {d:"기존 .card p 규칙을 지우지 않았다", js:"/\\.card\\s+p\\s*\\{[^}]*rgb\\(0,\\s*0,\\s*255\\)/.test(SRCCSS())"},
         {d:"기존 p 규칙을 지우지 않았다", js:"/(^|\\})\\s*p\\s*\\{[^}]*rgb\\(0,\\s*128,\\s*0\\)/.test(SRCCSS())"},
         {d:"!important 를 쓰지 않았다", js:"SRCCSS().indexOf('!important')<0"}],
  ex:"우선순위는 (인라인, id 개수, 클래스/속성/의사클래스 개수, 요소 개수) 를 <b>자리수처럼</b> 비교합니다. <code>#title</code> 은 (0,1,0,0), <code>.card p</code> 는 (0,0,1,1) 이라 id 하나가 클래스 몇 개보다도 셉니다.\n💡 같은 우선순위면 <b>나중에 쓴 규칙</b>이 이깁니다. 그래서 순서만 바꿔도 해결되는 경우가 많습니다.\n⚠️ <code>!important</code> 는 이 계산을 통째로 건너뛰기 때문에, 한 번 쓰면 다음 사람은 또 <code>!important</code> 로 이겨야 합니다. 그래서 이 문항에서 금지했습니다." },

{ k:"이미지 비율 유지", lv:2,
  q:"썸네일이 항상 <b>4:3 비율</b>(가로 200px, 세로 150px)을 유지하고, 안의 내용이 넘치면 잘리도록 하세요. <code>.thumb</code> 의 세로 값을 직접 150px 로 쓰지 말고 비율로 지정하세요.",
  src:"<style>\n  .thumb { width: 200px; background: #47f; }\n</style>\n<div class=\"thumb\"></div>",
  sol:"<style>\n  .thumb { width: 200px; aspect-ratio: 4 / 3; overflow: hidden; background: #47f; }\n</style>\n<div class=\"thumb\"></div>",
  tests:[{d:"가로가 200px 다", js:"Math.abs(W('.thumb')-200)<1"},
         {d:"세로가 150px 다", js:"Math.abs(H('.thumb')-150)<1.5"},
         {d:"aspect-ratio 로 지정했다", js:"/aspect-ratio/.test(SRCCSS())"},
         {d:"세로를 150px 로 직접 쓰지 않았다", js:"!/height\\s*:\\s*150px/.test(SRCCSS())"}],
  ex:"<code>aspect-ratio</code> 는 한 축이 정해지면 나머지를 비율로 계산합니다. 가로가 반응형으로 변해도 비율이 유지되므로, 이미지가 로드되기 전에도 자리가 확보되어 <b>레이아웃이 튀지 않습니다</b>(CLS 개선).\n💡 예전에는 <code>padding-top: 75%</code> 트릭을 썼습니다 — 퍼센트 padding 이 '부모의 가로' 를 기준으로 계산된다는 성질을 이용한 것인데, 지금은 <code>aspect-ratio</code> 로 의도가 그대로 드러납니다.\n⚠️ 실제 <code>&lt;img&gt;</code> 에는 <code>object-fit: cover</code> 를 함께 주어야 비율이 다른 원본이 찌그러지지 않고 잘립니다." },

{ k:"긴 텍스트 말줄임", lv:2,
  q:"한 줄짜리 제목이 상자를 넘치면 <b>… 로 잘리게</b> 하세요. 상자 <code>.title</code> 의 너비는 150px 이고, 줄바꿈 없이 한 줄을 유지해야 합니다.",
  src:"<style>\n  .title { width: 150px; background: #eef; }\n</style>\n<div class=\"title\">아주 길어서 절대 한 줄에 들어가지 않는 제목입니다</div>",
  sol:"<style>\n  .title { width: 150px; background: #eef; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }\n</style>\n<div class=\"title\">아주 길어서 절대 한 줄에 들어가지 않는 제목입니다</div>",
  tests:[{d:"줄바꿈을 막았다", js:"CS('.title','white-space')==='nowrap'"},
         {d:"넘치는 부분을 숨겼다", js:"CS('.title','overflow')==='hidden'"},
         {d:"말줄임표를 켰다", js:"CS('.title','text-overflow')==='ellipsis'"},
         {d:"한 줄 높이를 유지한다", js:"H('.title')<40"}],
  ex:"말줄임은 세 속성이 <b>모두 있어야</b> 동작합니다. 줄바꿈을 막고(nowrap), 넘친 부분을 잘라내고(hidden), 잘린 자리에 … 를 그립니다(ellipsis). 하나라도 빠지면 아무 일도 일어나지 않습니다.\n⚠️ 주의: 이건 <b>한 줄</b>에만 통합니다. 여러 줄을 말줄임하려면 <code>display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical</code> 조합이 필요합니다.\n💡 잘린 제목은 마우스를 올려도 전체가 안 보이므로 <code>title</code> 속성으로 원문을 함께 주는 게 친절합니다." },

{ k:"sticky 헤더", lv:3,
  q:"목록 위의 헤더가 스크롤해도 컨테이너 <b>맨 위에 붙어 있게</b> 하세요. 헤더는 <code>.head</code> 이고 스크롤 컨테이너는 <code>.scroll</code> 입니다.",
  src:"<style>\n  .scroll { height: 120px; overflow: auto; background: #eef; }\n  .head { background: #47f; color: #fff; padding: 6px; }\n  .row { height: 40px; border-bottom: 1px solid #ccd; }\n</style>\n<div class=\"scroll\">\n  <div class=\"head\">머리글</div>\n  <div class=\"row\"></div><div class=\"row\"></div><div class=\"row\"></div>\n  <div class=\"row\"></div><div class=\"row\"></div><div class=\"row\"></div>\n</div>",
  sol:"<style>\n  .scroll { height: 120px; overflow: auto; background: #eef; }\n  .head { background: #47f; color: #fff; padding: 6px; position: sticky; top: 0; }\n  .row { height: 40px; border-bottom: 1px solid #ccd; }\n</style>\n<div class=\"scroll\">\n  <div class=\"head\">머리글</div>\n  <div class=\"row\"></div><div class=\"row\"></div><div class=\"row\"></div>\n  <div class=\"row\"></div><div class=\"row\"></div><div class=\"row\"></div>\n</div>",
  tests:[{d:"헤더가 sticky 다", js:"CS('.head','position')==='sticky'"},
         {d:"top 이 지정되어 있다", js:"CS('.head','top')==='0px'"},
         {d:"스크롤 전에는 컨테이너 위에 있다", js:"Math.abs(RECT('.head').top-RECT('.scroll').top)<2"},
         {d:"스크롤해도 위에 붙어 있다", js:"(function(){var s=Q('.scroll');s.scrollTop=100;return Math.abs(s.getBoundingClientRect().top-Q('.head').getBoundingClientRect().top)<2;})()"}],
  ex:"<code>position: sticky</code> 는 평소에는 보통 흐름대로 놓이다가, 지정한 임계선(<code>top: 0</code>)에 닿으면 그 자리에 <b>고정</b>됩니다. fixed 와 달리 자기 부모 영역을 벗어나지는 않습니다.\n⚠️ 가장 흔한 실패 원인 두 가지: <code>top</code>(또는 left/right/bottom)을 안 줘서 임계선이 없는 경우, 그리고 조상 중에 <code>overflow: hidden</code>·<code>auto</code> 가 있어 <b>다른 스크롤 컨테이너에 갇힌</b> 경우입니다. 붙지 않으면 조상들의 overflow 부터 확인하세요." },

{ k:"flex-wrap 과 최소 너비", lv:3,
  q:"태그들이 한 줄에 다 안 들어가면 <b>다음 줄로 넘어가게</b> 하세요. <code>.tags</code> 는 flex 컨테이너이고 너비는 200px 입니다. 태그 사이 간격은 8px 입니다.",
  src:"<style>\n  .tags { width: 200px; background: #eef; display: flex; }\n  .tag { width: 80px; height: 24px; background: #47f; }\n</style>\n<div class=\"tags\">\n  <div class=\"tag\"></div><div class=\"tag\"></div><div class=\"tag\"></div>\n</div>",
  sol:"<style>\n  .tags { width: 200px; background: #eef; display: flex; flex-wrap: wrap; gap: 8px; }\n  .tag { width: 80px; height: 24px; background: #47f; flex-shrink: 0; }\n</style>\n<div class=\"tags\">\n  <div class=\"tag\"></div><div class=\"tag\"></div><div class=\"tag\"></div>\n</div>",
  tests:[{d:"줄바꿈을 켰다", js:"CS('.tags','flex-wrap')==='wrap'"},
         {d:"태그가 80px 너비를 유지한다", js:"Math.abs(QA('.tag')[0].getBoundingClientRect().width-80)<1"},
         {d:"세 번째 태그가 다음 줄로 넘어갔다", js:"QA('.tag')[2].getBoundingClientRect().top>QA('.tag')[0].getBoundingClientRect().top+10"},
         {d:"같은 줄의 두 태그 간격이 8px 다", js:"Math.abs((QA('.tag')[1].getBoundingClientRect().left-QA('.tag')[0].getBoundingClientRect().right)-8)<1.5"}],
  ex:"flex 의 기본값은 <code>nowrap</code> 이라 항목들이 <b>찌그러지면서</b>라도 한 줄에 남습니다. 그래서 '너비를 줬는데 무시된다' 는 현상이 생깁니다 — 무시된 게 아니라 <code>flex-shrink: 1</code> 기본값이 줄인 것입니다.\n🔧 <code>flex-wrap: wrap</code> 으로 넘치면 다음 줄로 보내고, 크기를 지키고 싶은 항목에는 <code>flex-shrink: 0</code> 을 줍니다.\n💡 <code>gap</code> 은 줄 사이(row-gap)에도 함께 적용되므로 세로 간격까지 한 번에 해결됩니다." },

{ k:"z-index 와 쌓임 맥락", lv:3,
  q:"팝오버 <code>.pop</code> 이 헤더 <code>.head</code> <b>위에</b> 보이게 하세요. 두 요소 모두 이미 <code>position</code> 이 잡혀 있습니다. 요소의 순서나 구조는 바꾸지 마세요.",
  src:"<style>\n  .head { position: relative; z-index: 10; height: 40px; background: #47f; }\n  .body { position: relative; height: 80px; background: #eef; }\n  .pop { position: absolute; top: -20px; left: 10px; width: 100px; height: 40px; background: #f74; }\n</style>\n<div class=\"head\"></div>\n<div class=\"body\"><div class=\"pop\"></div></div>",
  sol:"<style>\n  .head { position: relative; z-index: 10; height: 40px; background: #47f; }\n  .body { position: relative; z-index: 20; height: 80px; background: #eef; }\n  .pop { position: absolute; top: -20px; left: 10px; width: 100px; height: 40px; background: #f74; }\n</style>\n<div class=\"head\"></div>\n<div class=\"body\"><div class=\"pop\"></div></div>",
  tests:[{d:".body 의 z-index 가 .head 보다 크다", js:"parseInt(CS('.body','z-index'),10)>parseInt(CS('.head','z-index'),10)"},
         {d:".head 의 z-index 를 낮추지 않았다", js:"parseInt(CS('.head','z-index'),10)===10"},
         {d:"팝오버가 헤더와 겹치는 위치에 있다", js:"RECT('.pop').top<RECT('.head').bottom"},
         {d:"팝오버가 겹친 지점에서 맨 위에 있다", js:"(function(){var r=RECT('.pop');var e=document.elementFromPoint(r.left+5,r.top+5);return e&&e.classList.contains('pop');})()"}],
  ex:"핵심은 <code>.pop</code> 의 <code>z-index</code> 를 아무리 올려도 소용없다는 것입니다. <code>.pop</code> 은 <code>.body</code> 가 만든 <b>쌓임 맥락 안</b>에 갇혀 있어서, <code>.body</code> 전체가 <code>.head</code> 보다 아래면 그 안의 무엇도 위로 올라올 수 없습니다.\n🔧 그래서 올려야 할 것은 자식이 아니라 <b>맥락을 만든 부모</b>입니다.\n⚠️ 쌓임 맥락은 z-index 뿐 아니라 <code>opacity</code> 가 1 미만이거나 <code>transform</code>·<code>filter</code>·<code>will-change</code> 가 걸려도 생깁니다. 'z-index: 9999 를 줬는데 안 올라온다' 의 거의 모든 원인이 이것입니다." },

{ k:"가운데 정렬 세 가지", lv:1,
  q:"상자 <code>.card</code> 를 컨테이너 <code>.box</code> 의 <b>가로 가운데</b>에만 놓으세요(세로는 위쪽 그대로). flex 를 쓰지 말고 <code>margin</code> 으로 해결하세요.",
  src:"<style>\n  .box { width: 300px; height: 100px; background: #eef; }\n  .card { width: 100px; height: 30px; background: #47f; }\n</style>\n<div class=\"box\">\n  <div class=\"card\"></div>\n</div>",
  sol:"<style>\n  .box { width: 300px; height: 100px; background: #eef; }\n  .card { width: 100px; height: 30px; background: #47f; margin-left: auto; margin-right: auto; }\n</style>\n<div class=\"box\">\n  <div class=\"card\"></div>\n</div>",
  tests:[{d:"가로 중심이 맞는다", js:"Math.abs((RECT('.card').left+RECT('.card').right)/2-(RECT('.box').left+RECT('.box').right)/2)<2"},
         {d:"세로는 위쪽 그대로다", js:"Math.abs(RECT('.card').top-RECT('.box').top)<2"},
         {d:"flex 를 쓰지 않았다", js:"CS('.box','display')!=='flex'"},
         {d:"margin auto 를 썼다", js:"/margin(-left|-right)?\\s*:[^;]*auto/.test(SRCCSS())"}],
  ex:"블록 요소는 <b>너비가 정해져 있을 때만</b> <code>margin: 0 auto</code> 로 가운데에 옵니다. 남는 공간을 좌우 margin 이 똑같이 나눠 갖기 때문입니다. 너비가 <code>auto</code> 면 이미 부모를 가득 채우고 있어 남는 공간이 없습니다.\n⚠️ 세로 가운데는 이 방법으로 안 됩니다 — 세로 방향의 <code>auto</code> margin 은 0 으로 계산되기 때문입니다(flex 컨테이너 안에서는 예외적으로 동작합니다).\n💡 그래서 세로까지 가운데면 flex 나 grid 의 <code>place-items: center</code> 가 정답입니다." },

{ k:"버튼 접근성과 대비", lv:2,
  q:"아이콘만 있는 버튼 <code>.icon-btn</code> 에 <b>스크린 리더가 읽을 이름</b>을 주고, 최소 터치 영역 <b>44×44px</b>을 확보하세요. 화면에 보이는 글자는 늘리지 마세요.",
  src:"<style>\n  .icon-btn { width: 24px; height: 24px; border: 0; background: #47f; color: #fff; padding: 0; }\n</style>\n<button class=\"icon-btn\">×</button>",
  sol:"<style>\n  .icon-btn { width: 44px; height: 44px; border: 0; background: #47f; color: #fff; padding: 0; }\n</style>\n<button class=\"icon-btn\" aria-label=\"닫기\">×</button>",
  tests:[{d:"접근 가능한 이름이 있다", js:"!!(ATTR('.icon-btn','aria-label')||'').trim()"},
         {d:"너비가 44px 이상이다", js:"W('.icon-btn')>=44"},
         {d:"높이가 44px 이상이다", js:"H('.icon-btn')>=44"},
         {d:"보이는 글자는 그대로 ×", js:"TXT('.icon-btn')==='×'"}],
  ex:"아이콘만 있는 버튼은 스크린 리더에 '버튼' 이라고만 읽히거나 '곱하기 기호' 로 읽힙니다. <code>aria-label</code> 로 <b>하는 일</b>을 이름으로 줘야 합니다.\n💡 44×44px 는 애플 휴먼 인터페이스 가이드라인의 최소 터치 영역이고, WCAG 2.2 의 Target Size(Minimum)는 24×24px 를 하한으로 둡니다. 시각적으로 작게 보이고 싶다면 아이콘은 24px 로 두고 <code>padding</code> 으로 클릭 영역만 넓히는 방법도 있습니다.\n⚠️ <code>div</code> 에 <code>onclick</code> 을 다는 대신 <code>button</code> 을 쓰세요. 키보드 포커스·엔터/스페이스 활성화·역할 안내가 공짜로 따라옵니다." }
]};
