/* JavaScript 실습 3차 — 실습이 하나도 없던 6개 유닛을 연다.
   클로저·this · 객체 서술자와 불변성 · 이터레이터와 제너레이터 · 날짜·시간 ·
   런타임 타입 검증 · 비동기 심화.

   채점은 앱의 JS 하네스가 한다. 검사식이 프라미스를 돌려주면 기다렸다 판정하므로
   async 함수도 낼 수 있다 — 그 전에는 이 유닛들을 열 수 없었다.

   영영 끝나지 않는 코드는 넣지 않았다. 무한 제너레이터를 통째로 펼치는 시작 코드는
   '틀린 답' 이 아니라 '멎은 화면' 이 되고, 그건 배우는 사람에게 아무것도 알려 주지 않는다. */
module.exports = [
/* ── 클로저·스코프·this ───────────────────────────────────── */
{
  unit: "클로저·스코프·this",
  lesson: "직접 짜 보기 — 함수가 기억하는 것",
  th: {
    sum: "함수는 만들어진 자리를 **기억한다.** 그래서 바깥 변수를 계속 쓸 수 있다 — 이것이 클로저다.",
    body: [
      { h: "각자 자기 것을 갖게 하려면", t: "변수를 함수 **바깥**에 두면 만들어진 모든 함수가 그 하나를 나눠 쓴다. 카운터를 두 개 만들었는데 같이 올라가는 이유다. 변수를 만드는 함수 **안**에 두면 부를 때마다 새 변수가 생겨 각자 자기 것을 갖는다." },
      { h: "let 과 var 는 기억하는 것이 다르다", t: "`for (var i ...)` 의 `i` 는 반복문 전체에 하나뿐이라, 안에서 만든 함수들이 **끝난 뒤의 값** 하나를 함께 본다. `let` 은 한 바퀴마다 새 `i` 를 만들어 각 함수가 자기 바퀴의 값을 기억한다." },
      { h: "this 는 '어떻게 불렸는가' 로 정해진다", t: "`obj.greet()` 로 부르면 `this` 가 `obj` 지만, `const f = obj.greet; f()` 처럼 떼어 내 부르면 `this` 가 딴 것이 된다. 콜백으로 넘길 때 이 사고가 난다. `bind` 하거나 화살표 함수로 감싸서 붙여 둔다." },
    ],
    code: { c: "function makeCounter() {\n  let n = 0;              // 부를 때마다 새로 생긴다\n  return () => ++n;\n}\n\nconst f = obj.greet.bind(obj);   // this 를 붙여 둔다", cap: "안에 두면 각자, 밖에 두면 함께" },
    key: ["클로저는 만들어진 자리를 기억한다", "`let` 은 바퀴마다 새로 만든다", "`this` 는 부르는 방식이 정한다"],
  },
  q: [
    {
      k: "makeCounter · 각자 자기 숫자 갖기",
      qq: "부를 때마다 <b>1씩 올라간 값</b>을 돌려주는 함수를 만들어 주세요. <code>makeCounter()</code> 로 만든 <b>카운터끼리는 서로 영향이 없어야</b> 합니다.",
      src: "let n = 0;\nfunction makeCounter() {\n  return function () {\n    n += 1;\n    return n;\n  };\n}",
      sol: "function makeCounter() {\n  let n = 0;\n  return function () {\n    n += 1;\n    return n;\n  };\n}",
      tests: [["(() => { const c = makeCounter(); c(); return c(); })()", "2"],
              ["(() => { const a = makeCounter(); a(); a(); const b = makeCounter(); return b(); })()", "1"],
              ["(() => { const a = makeCounter(); const b = makeCounter(); a(); a(); return b(); })()", "1"]],
      edge: [["(() => makeCounter()())()", "1"]],
      ex: "변수를 함수 바깥에 두면 만들어진 모든 카운터가 그 하나를 나눠 씁니다. 하나를 올리면 다른 것도 같이 올라가요. 안에 두면 부를 때마다 새 변수가 생겨 각자 자기 숫자를 갖습니다.",
    },
    {
      k: "makeAdders · 바퀴마다 자기 값 기억하기",
      qq: "<code>0..n-1</code> 각각을 더하는 함수들의 배열을 돌려주세요. <code>makeAdders(3)[0](10)</code> 은 <code>10</code>, <code>[2](10)</code> 은 <code>12</code> 입니다.",
      src: "function makeAdders(n) {\n  const out = [];\n  for (var i = 0; i < n; i++) {\n    out.push(function (x) { return x + i; });\n  }\n  return out;\n}",
      sol: "function makeAdders(n) {\n  const out = [];\n  for (let i = 0; i < n; i++) {\n    out.push(function (x) { return x + i; });\n  }\n  return out;\n}",
      tests: [["makeAdders(3)[0](10)", "10"],
              ["makeAdders(3)[2](10)", "12"],
              ["makeAdders(3).map(f => f(0))", "[0, 1, 2]"]],
      edge: [["makeAdders(0).length", "0"],
             ["makeAdders(1)[0](5)", "5"]],
      ex: "var 로 만든 i 는 반복문 전체에 하나뿐이라, 함수들이 전부 '끝난 뒤의 값' 하나를 함께 봅니다. 그래서 전부 n 을 더해요. let 은 한 바퀴마다 새 i 를 만들어 줍니다.",
    },
    {
      k: "detach · 떼어 내도 this 를 잃지 않기",
      qq: "객체에서 <code>greet</code> 를 떼어 내 <b>따로 불러도</b> 자기 <code>title</code> 을 쓰게 만들어 주세요.",
      src: "function detach(obj) {\n  return obj.greet;\n}\n\nconst room = {\n  title: '회의실',\n  greet() { return this.title + ' 입니다'; },\n};",
      sol: "function detach(obj) {\n  return obj.greet.bind(obj);\n}\n\nconst room = {\n  title: '회의실',\n  greet() { return this.title + ' 입니다'; },\n};",
      tests: [["detach(room)()", "'회의실 입니다'"],
              ["detach({ title: '창고', greet: room.greet })()", "'창고 입니다'"],
              ["[detach(room)].map(f => f())", "['회의실 입니다']"]],
      edge: [["detach({ title: '', greet: room.greet })()", "' 입니다'"]],
      ex: "obj.greet() 로 부르면 this 가 obj 지만, 떼어 내 부르면 this 가 딴 것이 됩니다. 콜백으로 넘길 때 늘 생기는 사고예요. bind 로 붙여 두면 어디서 불러도 자기 객체를 봅니다.",
    },
  ],
},
/* ── 객체 심화 — 서술자·접근자·불변성 (중급) ──────────────── */
{
  unit: "객체 심화 — 서술자·접근자·불변성 (중급)",
  lesson: "직접 짜 보기 — 못 바꾸게 만들기",
  th: {
    sum: "객체의 속성에는 값 말고도 **쓸 수 있는가·셀 수 있는가** 같은 설정이 붙어 있다. 그것이 서술자다.",
    body: [
      { h: "읽기 전용으로 잠그기", t: "`Object.defineProperty(o, 'k', { writable: false })` 로 두면 그 속성은 고쳐지지 않는다. 느슨한 모드에서는 **오류도 안 나고 조용히 무시된다** — 그래서 '분명 바꿨는데 왜 그대로지' 로 나타난다. 잠근 쪽을 의심할 줄 알아야 한다." },
      { h: "접근자로 검사 자리를 만든다", t: "`get`·`set` 을 두면 값을 읽고 쓸 때 함수가 대신 돈다. 세터에서 검사하면 **잘못된 값이 들어오는 순간** 막을 수 있다. 나중에 화면에 나올 때가 돼서야 이상한 값을 발견하는 것보다 훨씬 낫다." },
      { h: "freeze 는 한 겹만 언다", t: "`Object.freeze(o)` 는 `o` 의 속성만 잠근다. `o.inner` 가 객체라면 그 **안쪽은 그대로 바꿀 수 있다.** 얼렸다고 안심하면 안쪽에서 조용히 값이 바뀐다. 깊이 얼리려면 안쪽까지 돌면서 얼려야 한다." },
    ],
    code: { c: "Object.defineProperty(o, 'id', { value: 1, writable: false });\n\nObject.freeze(o);        // 한 겹만\nObject.values(o).forEach(v => typeof v === 'object' && Object.freeze(v));", cap: "잠그기와 검사 자리" },
    key: ["`writable: false` 는 조용히 무시된다", "세터가 검사 자리", "`freeze` 는 한 겹만"],
  },
  q: [
    {
      k: "lockId · 못 바꾸는 속성 만들기",
      qq: "객체에 <code>id</code> 를 넣되 <b>나중에 못 바꾸게</b> 하세요. 값을 다시 대입해도 그대로여야 합니다.",
      src: "function lockId(o, id) {\n  o.id = id;\n  return o;\n}",
      sol: "function lockId(o, id) {\n  Object.defineProperty(o, 'id', { value: id, writable: false, enumerable: true });\n  return o;\n}",
      tests: [["lockId({}, 7).id", "7"],
              ["(() => { const o = lockId({}, 7); o.id = 99; return o.id; })()", "7"],
              ["Object.getOwnPropertyDescriptor(lockId({}, 1), 'id').writable", "false"]],
      edge: [["(() => { const o = lockId({ name: '가' }, 1); o.id = 2; return o.name + o.id; })()", "'가1'"]],
      ex: "그냥 대입하면 언제든 덮어쓸 수 있습니다. writable: false 로 두면 고치려는 시도가 무시돼요. 느슨한 모드에서는 오류도 안 나니, 값이 안 바뀌면 잠긴 속성인지 의심해 봐야 합니다.",
    },
    {
      k: "makeTemp · 세터에서 막기",
      qq: "<code>celsius</code> 를 읽고 쓸 수 있는 객체를 만드세요. <b>-273.15 미만</b>을 넣으면 <b>무시</b>하고 이전 값을 지킵니다.",
      src: "function makeTemp(c) {\n  return { celsius: c };\n}",
      sol: "function makeTemp(c) {\n  let v = c;\n  return {\n    get celsius() { return v; },\n    set celsius(x) {\n      if (x >= -273.15) v = x;\n    },\n  };\n}",
      tests: [["makeTemp(20).celsius", "20"],
              ["(() => { const t = makeTemp(20); t.celsius = 30; return t.celsius; })()", "30"],
              ["(() => { const t = makeTemp(20); t.celsius = -300; return t.celsius; })()", "20"]],
      edge: [["(() => { const t = makeTemp(0); t.celsius = -273.15; return t.celsius; })()", "-273.15"]],
      ex: "그냥 속성이면 어떤 값이든 들어옵니다. 세터를 두면 값이 들어오는 그 순간이 검사 자리가 되어, 이상한 값이 객체 안에 자리 잡는 것을 막을 수 있어요.",
    },
    {
      k: "deepFreeze · 안쪽까지 얼리기",
      qq: "객체를 <b>안쪽 객체까지</b> 얼려 주세요. 중첩된 값도 바뀌지 않아야 합니다.",
      src: "function deepFreeze(o) {\n  Object.freeze(o);\n  return o;\n}",
      sol: "function deepFreeze(o) {\n  Object.freeze(o);\n  Object.values(o).forEach(v => {\n    if (v && typeof v === 'object' && !Object.isFrozen(v)) deepFreeze(v);\n  });\n  return o;\n}",
      tests: [["(() => { const o = deepFreeze({ a: { b: 1 } }); o.a.b = 9; return o.a.b; })()", "1"],
              ["(() => { const o = deepFreeze({ a: 1 }); o.a = 9; return o.a; })()", "1"],
              ["Object.isFrozen(deepFreeze({ a: { b: 1 } }).a)", "true"]],
      edge: [["(() => { const o = deepFreeze({ a: { b: { c: 1 } } }); o.a.b.c = 9; return o.a.b.c; })()", "1"]],
      ex: "Object.freeze 는 한 겹만 잠급니다. 안쪽 객체는 그대로라 조용히 바뀌어요. '얼렸으니 안전하다' 고 믿는 순간이 제일 위험합니다 — 안쪽까지 돌면서 얼려야 해요.",
    },
  ],
},
/* ── 이터레이터와 제너레이터 — 지연 평가 (심화) ───────────── */
{
  unit: "이터레이터와 제너레이터 — 지연 평가 (심화)",
  lesson: "직접 짜 보기 — 필요할 때 하나씩 꺼내기",
  th: {
    sum: "제너레이터는 값을 **미리 다 만들지 않는다.** 달라고 할 때 하나씩 만들어 준다.",
    body: [
      { h: "yield 는 잠깐 멈추는 자리", t: "`function*` 안의 `yield` 는 값을 하나 내주고 **거기서 멈춘다.** 다음에 달라고 하면 멈춘 자리부터 이어서 돈다. 그래서 끝이 없는 수열도 만들 수 있다 — 필요한 만큼만 꺼내 쓰면 되기 때문이다." },
      { h: "몇 개를 낼지 정확히 세기", t: "'n개를 낸다' 는 반복 조건 하나에 달려 있다. 하나 더 내거나 덜 내는 실수는 짧은 목록에서는 눈에 잘 안 띄고, 뒤에서 계산이 어긋난 뒤에야 드러난다." },
      { h: "Symbol.iterator 가 있어야 펼칠 수 있다", t: "`[...x]` 나 `for...of` 는 `x[Symbol.iterator]` 를 찾는다. 없으면 `TypeError` 다. 내가 만든 객체를 이 문법으로 쓰고 싶으면 그 자리를 만들어 주면 된다 — 제너레이터 함수를 그대로 넣으면 가장 짧다." },
    ],
    code: { c: "function* fib(n) {\n  let a = 0, b = 1;\n  for (let i = 0; i < n; i++) { yield a; [a, b] = [b, a + b]; }\n}\n\nconst r = { *[Symbol.iterator]() { yield 1; yield 2; } };\n[...r];   // [1, 2]", cap: "달라고 할 때 하나씩" },
    key: ["`yield` 는 멈추는 자리", "몇 개를 낼지 정확히", "`Symbol.iterator` 가 있어야 펼쳐진다"],
  },
  q: [
    {
      k: "fibGen · n개만 내주기",
      qq: "피보나치 수를 <b>앞에서 n개</b> 내주는 제너레이터를 만드세요. <code>[...fibGen(5)]</code> 는 <code>[0,1,1,2,3]</code> 입니다.",
      src: "function* fibGen(n) {\n  let a = 0, b = 1;\n  for (let i = 0; i < n - 1; i++) {\n    yield a;\n    [a, b] = [b, a + b];\n  }\n}",
      sol: "function* fibGen(n) {\n  let a = 0, b = 1;\n  for (let i = 0; i < n; i++) {\n    yield a;\n    [a, b] = [b, a + b];\n  }\n}",
      tests: [["[...fibGen(5)]", "[0, 1, 1, 2, 3]"],
              ["[...fibGen(1)]", "[0]"],
              ["[...fibGen(8)].length", "8"]],
      edge: [["[...fibGen(0)]", "[]"]],
      ex: "n - 1 로 돌면 언제나 하나가 모자랍니다. 다섯 개를 달라고 했는데 네 개가 오고, 한 개를 달라고 하면 아예 비어 있어요. 짧은 목록에서는 눈에 잘 안 띕니다.",
    },
    {
      k: "takeFirst · 앞에서 n개만 꺼내기",
      qq: "반복 가능한 것에서 <b>앞의 n개</b>만 배열로 꺼내 주세요. 원래 개수보다 크게 달라고 하면 있는 만큼만 줍니다.",
      src: "function takeFirst(iterable, n) {\n  const out = [];\n  for (const v of iterable) {\n    out.push(v);\n    if (out.length > n) break;\n  }\n  return out;\n}",
      sol: "function takeFirst(iterable, n) {\n  const out = [];\n  if (n <= 0) return out;\n  for (const v of iterable) {\n    out.push(v);\n    if (out.length >= n) break;\n  }\n  return out;\n}",
      tests: [["takeFirst([1, 2, 3, 4], 2)", "[1, 2]"],
              ["takeFirst([1, 2], 5)", "[1, 2]"],
              ["takeFirst('abc', 2)", "['a', 'b']"]],
      edge: [["takeFirst([1, 2, 3], 0)", "[]"],
             ["takeFirst([], 3)", "[]"]],
      ex: "'담고 나서 n 을 넘었으면 멈춘다' 로 쓰면 언제나 하나를 더 담습니다. 담은 개수가 n 에 닿는 순간 멈춰야 하고, 0개를 달라고 한 경우도 따로 챙겨야 해요.",
    },
    {
      k: "makeRange · 펼칠 수 있는 객체 만들기",
      qq: "<code>[...makeRange(1, 4)]</code> 가 <code>[1,2,3]</code> 이 되게 하세요. <code>to</code> 는 포함하지 않습니다.",
      src: "function makeRange(from, to) {\n  return { from: from, to: to };\n}",
      sol: "function makeRange(from, to) {\n  return {\n    from: from,\n    to: to,\n    *[Symbol.iterator]() {\n      for (let i = from; i < to; i++) yield i;\n    },\n  };\n}",
      tests: [["[...makeRange(1, 4)]", "[1, 2, 3]"],
              ["[...makeRange(0, 1)]", "[0]"],
              ["(() => { let s = 0; for (const v of makeRange(1, 4)) s += v; return s; })()", "6"]],
      edge: [["[...makeRange(3, 3)]", "[]"]],
      ex: "[...x] 와 for...of 는 x[Symbol.iterator] 를 찾습니다. 없으면 값이 있어도 TypeError 예요. 그 자리에 제너레이터 함수를 넣어 주면 내가 만든 객체도 배열처럼 펼쳐집니다.",
    },
  ],
},
/* ── 날짜·시간 처리 — 타임존과 계산 함정 (중급) ───────────── */
{
  unit: "날짜·시간 처리 — 타임존과 계산 함정 (중급)",
  lesson: "직접 짜 보기 — 달과 날을 정확히 다루기",
  th: {
    sum: "자바스크립트 날짜에서 **월은 0부터** 시작한다. 그리고 날짜 계산을 글자로 하면 월말에서 무너진다.",
    body: [
      { h: "월만 0부터인 이유는 없다", t: "`new Date(2024, 2, 1)` 은 2월이 아니라 **3월** 1일이다. 연·일·시는 그대로인데 월만 0부터라 헷갈린다. 사람이 쓰는 달을 받는 함수를 만든다면 안에서 1을 빼 주고, 그 사실을 이름이나 주석에 남긴다." },
      { h: "글자를 더하면 32일이 생긴다", t: "`'2024-01-31'` 의 뒤 두 자리에 1을 더하면 `'2024-01-32'` 다. 달이 며칠까지 있는지, 윤년인지를 글자는 모른다. 날짜로 바꿔서 더하면 달과 해가 알아서 넘어간다." },
      { h: "시차를 피하려면 UTC 로", t: "`new Date('2024-03-01')` 은 UTC 자정으로 읽히는데 `getDate()` 는 **내 지역 시각**으로 답한다. 시차가 있는 곳에서는 하루가 밀려 보인다. 날짜만 다룰 때는 `Date.UTC` 와 `toISOString` 으로 통일하는 것이 가장 덜 아프다." },
    ],
    code: { c: "new Date(Date.UTC(y, m - 1, d))       // 사람이 쓰는 달 → 0부터로\n  .toISOString().slice(0, 10);        // 'YYYY-MM-DD'", cap: "UTC 로 통일하면 시차가 안 끼어든다" },
    key: ["월은 0부터", "글자로 날짜 계산 금지", "날짜만 다룰 땐 UTC"],
  },
  q: [
    {
      k: "isoDate · 사람이 쓰는 달로 받기",
      qq: "연·월·일을 <b>사람이 쓰는 대로</b>(3월이면 3) 받아 <code>\"YYYY-MM-DD\"</code> 를 돌려주세요.",
      src: "function isoDate(y, m, d) {\n  return new Date(Date.UTC(y, m, d)).toISOString().slice(0, 10);\n}",
      sol: "function isoDate(y, m, d) {\n  return new Date(Date.UTC(y, m - 1, d)).toISOString().slice(0, 10);\n}",
      tests: [["isoDate(2024, 3, 1)", "'2024-03-01'"],
              ["isoDate(2024, 12, 31)", "'2024-12-31'"],
              ["isoDate(2024, 1, 5)", "'2024-01-05'"]],
      edge: [["isoDate(2024, 2, 29)", "'2024-02-29'"]],
      ex: "Date 는 월만 0부터 셉니다. 그대로 넘기면 한 달씩 밀리고, 12월을 넣으면 다음 해 1월이 돼요. 사람이 쓰는 달을 받는다면 안에서 1을 빼 줍니다.",
    },
    {
      k: "addDays · 달을 넘겨서 더하기",
      qq: "<code>\"YYYY-MM-DD\"</code> 에 <code>n</code>일을 더한 날짜를 돌려주세요. <b>달과 해가 넘어가도</b> 맞아야 합니다.",
      src: "function addDays(iso, n) {\n  const day = Number(iso.slice(8, 10)) + n;\n  return iso.slice(0, 8) + String(day).padStart(2, '0');\n}",
      sol: "function addDays(iso, n) {\n  const t = new Date(iso + 'T00:00:00Z').getTime();\n  return new Date(t + n * 86400000).toISOString().slice(0, 10);\n}",
      tests: [["addDays('2024-01-31', 1)", "'2024-02-01'"],
              ["addDays('2024-03-05', 3)", "'2024-03-08'"],
              ["addDays('2024-12-31', 1)", "'2025-01-01'"]],
      edge: [["addDays('2024-02-28', 1)", "'2024-02-29'"],
             ["addDays('2024-03-01', 0)", "'2024-03-01'"]],
      ex: "글자의 뒤 두 자리에 더하면 '2024-01-32' 같은 날짜가 만들어집니다. 달이 며칠까지 있는지, 윤년인지를 글자는 모르거든요. 날짜로 바꿔 더하면 알아서 넘어갑니다.",
    },
    {
      k: "daysBetween · 며칠 차이인가",
      qq: "두 날짜가 <b>며칠 차이</b>인지 돌려주세요. 순서를 바꿔 넣어도 <b>같은 값</b>이어야 합니다.",
      src: "function daysBetween(a, b) {\n  const ta = new Date(a + 'T00:00:00Z').getTime();\n  const tb = new Date(b + 'T00:00:00Z').getTime();\n  return (tb - ta) / 86400000;\n}",
      sol: "function daysBetween(a, b) {\n  const ta = new Date(a + 'T00:00:00Z').getTime();\n  const tb = new Date(b + 'T00:00:00Z').getTime();\n  return Math.abs(tb - ta) / 86400000;\n}",
      tests: [["daysBetween('2024-03-01', '2024-03-05')", "4"],
              ["daysBetween('2024-03-05', '2024-03-01')", "4"],
              ["daysBetween('2024-02-28', '2024-03-01')", "2"]],
      edge: [["daysBetween('2024-03-01', '2024-03-01')", "0"]],
      ex: "뺄셈은 순서에 따라 음수가 나옵니다. '며칠 차이' 는 방향이 없는 값이니 절댓값을 취해야 해요. 그리고 2024년은 윤년이라 2월이 29일까지 있는데, 시각으로 계산하면 그런 것을 신경 쓸 필요가 없습니다.",
    },
  ],
},
/* ── 타입 안전과 검증 — 런타임 방어와 TS 개념 (심화) ──────── */
{
  unit: "타입 안전과 검증 — 런타임 방어와 TS 개념 (심화)",
  lesson: "직접 짜 보기 — 들어온 값을 믿지 않기",
  th: {
    sum: "바깥에서 온 값은 **무엇이든 될 수 있다.** 쓰기 전에 확인하는 자리를 한 곳 만들어 둔다.",
    body: [
      { h: "typeof 는 몇 가지를 못 가린다", t: "`typeof null` 은 `'object'` 이고 배열도 `'object'` 다. 초창기의 실수인데 고치면 옛 코드가 깨져서 그대로 남았다. 그래서 `null` 은 먼저 걸러 내고 배열은 `Array.isArray` 로 따로 물어봐야 한다." },
      { h: "NaN 은 숫자다", t: "`typeof NaN` 은 `'number'` 다. 계산이 실패해서 나온 값인데 타입만 보면 멀쩡해 보인다. 이 값은 어떤 계산에 들어가도 결과를 `NaN` 으로 만들어 조용히 퍼진다. `Number.isFinite` 로 '쓸 수 있는 숫자인지' 를 묻는다." },
      { h: "|| 와 ?? 는 다르다", t: "`v || 기본값` 은 `0`·`''`·`false` 처럼 **멀쩡한 값도** 기본값으로 바꿔 버린다. 수량 0이 1로, 빈 이름이 '손님' 으로 둔갑한다. '값이 아예 없을 때만' 이라면 `??` 다 — `null` 과 `undefined` 에만 반응한다." },
    ],
    code: { c: "if (v === null) return 'null';\nif (Array.isArray(v)) return 'array';\n\nNumber.isFinite(v)     // NaN·Infinity 를 걸러 준다\nv ?? 기본값             // 0 과 '' 는 그대로 둔다", cap: "확인은 한 곳에서" },
    key: ["`typeof null` 은 `'object'`", "`NaN` 은 숫자다", "`??` 는 없을 때만"],
  },
  q: [
    {
      k: "kindOf · 종류를 제대로 말하기",
      qq: "값의 종류를 돌려주세요. <code>null</code> 이면 <code>'null'</code>, 배열이면 <code>'array'</code>, 그 밖에는 <code>typeof</code> 결과입니다.",
      src: "function kindOf(v) {\n  return typeof v;\n}",
      sol: "function kindOf(v) {\n  if (v === null) return 'null';\n  if (Array.isArray(v)) return 'array';\n  return typeof v;\n}",
      tests: [["kindOf(null)", "'null'"],
              ["kindOf([1, 2])", "'array'"],
              ["kindOf('가')", "'string'"]],
      edge: [["kindOf({})", "'object'"],
             ["kindOf(undefined)", "'undefined'"]],
      ex: "typeof null 은 'object' 이고 배열도 'object' 입니다. 초창기의 실수인데 고치면 옛 코드가 깨져서 그대로 남았어요. 이 둘은 먼저 따로 물어봐야 합니다.",
    },
    {
      k: "isNumber · 쓸 수 있는 숫자인가",
      qq: "계산에 <b>쓸 수 있는 숫자</b>면 <code>true</code> 를 돌려주세요. <code>NaN</code> 과 <code>Infinity</code> 는 아닙니다.",
      src: "function isNumber(v) {\n  return typeof v === 'number';\n}",
      sol: "function isNumber(v) {\n  return Number.isFinite(v);\n}",
      tests: [["isNumber(3)", "true"],
              ["isNumber(NaN)", "false"],
              ["isNumber(Infinity)", "false"]],
      edge: [["isNumber('3')", "false"],
             ["isNumber(0)", "true"]],
      ex: "typeof NaN 은 'number' 입니다. 계산이 실패해서 나온 값인데 타입만 보면 멀쩡해 보여요. 그리고 NaN 은 어떤 계산에 들어가도 결과를 NaN 으로 만들어 조용히 퍼집니다.",
    },
    {
      k: "withDefault · 없을 때만 기본값",
      qq: "값이 <b>없을 때만</b>(<code>null</code>·<code>undefined</code>) 기본값을 돌려주세요. <code>0</code> 이나 빈 문자열은 <b>그대로</b> 둡니다.",
      src: "function withDefault(v, d) {\n  return v || d;\n}",
      sol: "function withDefault(v, d) {\n  return v ?? d;\n}",
      tests: [["withDefault(0, 10)", "0"],
              ["withDefault(null, 10)", "10"],
              ["withDefault('', '손님')", "''"]],
      edge: [["withDefault(undefined, 10)", "10"],
             ["withDefault(false, true)", "false"]],
      ex: "|| 는 0·빈 문자열·false 처럼 멀쩡한 값도 기본값으로 바꿔 버립니다. 수량 0이 10으로 둔갑하는 식이에요. '아예 없을 때만' 이라면 ?? 를 씁니다.",
    },
  ],
},
/* ── 비동기 심화 ──────────────────────────────────────────── */
{
  unit: "비동기 심화",
  lesson: "직접 짜 보기 — 여러 개를 안전하게 기다리기",
  th: {
    sum: "여러 비동기 작업을 다룰 때는 **하나가 실패하면 어떻게 할지**를 먼저 정해야 한다.",
    body: [
      { h: "all 은 하나만 실패해도 전부 버린다", t: "`Promise.all` 은 하나라도 거부되면 그 자리에서 거부한다. 나머지가 성공했어도 결과를 받을 수 없다. '되는 것만이라도 받고 싶다' 면 `Promise.allSettled` 다 — 각각의 성공·실패를 모아서 준다." },
      { h: "forEach 는 기다려 주지 않는다", t: "`arr.forEach(async ...)` 는 안쪽 함수가 프라미스를 돌려줘도 **그냥 버린다.** 그래서 아직 아무것도 안 끝났는데 다음 줄로 넘어간다. 순서대로 기다리려면 `for...of` 안에서 `await` 한다." },
      { h: "삼킨 오류는 사라진 단서다", t: "`.catch(() => null)` 은 무엇이 왜 실패했는지를 그 자리에서 지운다. 나중에 '왜 값이 비지' 를 거슬러 올라가는 시간이 처음부터 알렸을 때보다 훨씬 길다. 최소한 메시지는 남긴다." },
    ],
    code: { c: "const rs = await Promise.allSettled(ps);   // 실패해도 나머지를 받는다\n\nfor (const f of fns) out.push(await f());  // 순서대로 기다린다", cap: "실패를 어떻게 다룰지 먼저 정한다" },
    key: ["`all` 은 하나 실패에 전부 버린다", "`forEach` 는 안 기다린다", "오류를 삼키지 않는다"],
  },
  q: [
    {
      k: "settleAll · 실패해도 나머지는 받기",
      qq: "프라미스 배열을 받아 <b>성공한 것은 값</b>, <b>실패한 것은 <code>null</code></b> 로 채운 배열을 돌려주세요. 하나가 실패해도 나머지는 받아야 합니다.",
      src: "async function settleAll(ps) {\n  return await Promise.all(ps);\n}",
      sol: "async function settleAll(ps) {\n  const rs = await Promise.allSettled(ps);\n  return rs.map(r => (r.status === 'fulfilled' ? r.value : null));\n}",
      tests: [["settleAll([Promise.resolve(1), Promise.resolve(2)])", "[1, 2]"],
              ["settleAll([Promise.resolve(1), Promise.reject(new Error('x'))])", "[1, null]"],
              ["settleAll([Promise.reject(new Error('x'))])", "[null]"]],
      edge: [["settleAll([])", "[]"]],
      ex: "Promise.all 은 하나라도 거부되면 그 자리에서 거부합니다. 성공한 것까지 통째로 버려져요. 각각의 결과가 필요하면 allSettled 로 모아서 받습니다.",
    },
    {
      k: "runInOrder · 순서대로 기다리기",
      qq: "함수 배열을 <b>앞에서부터 하나씩</b> 실행해 결과를 순서대로 담아 돌려주세요. 앞의 것이 끝난 뒤에 다음 것을 시작합니다.",
      src: "async function runInOrder(fns) {\n  const out = [];\n  fns.forEach(async (f) => {\n    out.push(await f());\n  });\n  return out;\n}",
      sol: "async function runInOrder(fns) {\n  const out = [];\n  for (const f of fns) {\n    out.push(await f());\n  }\n  return out;\n}",
      tests: [["runInOrder([() => Promise.resolve(1), () => Promise.resolve(2)])", "[1, 2]"],
              ["runInOrder([async () => 'a', async () => 'b', async () => 'c'])", "['a', 'b', 'c']"],
              ["runInOrder([() => new Promise(r => setTimeout(() => r(1), 20)), async () => 2])", "[1, 2]"]],
      edge: [["runInOrder([])", "[]"]],
      ex: "forEach 는 안쪽 async 함수가 돌려준 프라미스를 그냥 버립니다. 그래서 아직 아무것도 안 담겼는데 빈 배열이 먼저 돌아가요. 기다리려면 for...of 안에서 await 해야 합니다.",
    },
    {
      k: "tryRun · 실패 이유를 남기기",
      qq: "함수를 실행해 성공하면 <code>[null, 값]</code>, 실패하면 <code>[메시지, null]</code> 을 돌려주세요.",
      src: "async function tryRun(f) {\n  const v = await Promise.resolve().then(f).catch(() => null);\n  return [null, v];\n}",
      sol: "async function tryRun(f) {\n  try {\n    return [null, await f()];\n  } catch (e) {\n    return [e.message, null];\n  }\n}",
      tests: [["tryRun(async () => 7)", "[null, 7]"],
              ["tryRun(async () => { throw new Error('디스크 없음'); })", "['디스크 없음', null]"],
              ["tryRun(() => Promise.reject(new Error('끊김')))", "['끊김', null]"]],
      edge: [["tryRun(async () => 0)", "[null, 0]"]],
      ex: "catch 에서 null 만 돌려주면 무엇이 왜 실패했는지가 그 자리에서 사라집니다. 나중에 '왜 값이 비지' 를 거슬러 올라가는 시간이 훨씬 길어요. 최소한 메시지는 남겨야 합니다.",
    },
  ],
},
];
