/* Linux 실행형 — 셸과 커널이 하는 계산을 직접 만들어 본다.
   권한 비트, 경로 정규화, glob 펼치기, PATH 탐색, 프로세스 트리,
   로그 집계, cron 표현식, du/df 계산. 설명으로 읽는 대신 손으로 확인한다. */
module.exports = [

/* ───────────── 권한과 경로 ───────────── */
{ track: "linux", k: "권한 비트를 rwx 로 · modeToRwx", cat: "internals",
  q: "<code>644</code> 같은 8진수 문자열을 <code>\"rw-r--r--\"</code> 형태로 바꿔 주세요. 각 자리는 읽기 4 · 쓰기 2 · 실행 1 을 더한 값입니다.",
  src: "function modeToRwx(mode) {\n  // TODO: 자리마다 4·2·1 비트가 켜졌는지 보세요\n  return \"\";\n}",
  sol: "function modeToRwx(mode) {\n  return String(mode).split(\"\").map((ch) => {\n    const n = Number(ch);\n    return (n & 4 ? \"r\" : \"-\") + (n & 2 ? \"w\" : \"-\") + (n & 1 ? \"x\" : \"-\");\n  }).join(\"\");\n}",
  tests: [['modeToRwx("644")', '"rw-r--r--"'],
    ['modeToRwx("755")', '"rwxr-xr-x"'],
    ['modeToRwx("600")', '"rw-------"'],
    ['modeToRwx("777")', '"rwxrwxrwx"']],
  edge: [['modeToRwx("000")', '"---------"'], ['modeToRwx("400")', '"r--------"']],
  ex: "<code>ls -l</code> 의 앞 아홉 글자가 정확히 이 계산입니다. 자리 하나가 **소유자·그룹·나머지** 세 부류에 하나씩 대응합니다.\n비트 연산으로 보면 규칙이 단순해집니다 — <code>4</code>·<code>2</code>·<code>1</code> 은 겹치지 않는 비트라, 더한 값에서 각각을 다시 뽑아낼 수 있습니다. 8진수를 쓰는 이유가 이것입니다. 세 비트가 한 자리에 정확히 들어맞습니다.\n<code>600</code> 은 개인키에 반드시 필요한 권한입니다. 그룹이나 다른 사용자가 읽을 수 있으면 ssh 가 키 사용을 아예 거부합니다.\n실제 <code>ls -l</code> 은 앞에 한 글자를 더 붙여 <b>종류</b>를 알려 줍니다 — <code>-</code> 는 일반 파일, <code>d</code> 는 디렉터리, <code>l</code> 은 심볼릭 링크입니다." },

{ track: "linux", k: "umask 를 적용한다 · applyUmask", cat: "internals",
  q: "새 파일의 기본 권한 <code>666</code> 에서 <code>umask</code> 가 지정한 비트를 <b>깎은</b> 결과를 세 자리 문자열로 돌려주세요. 폴더면 기본이 <code>777</code> 입니다.",
  src: "function applyUmask(umask, isDir) {\n  // TODO: 기본값에서 umask 비트를 지우세요\n  return \"666\";\n}",
  sol: "function applyUmask(umask, isDir) {\n  const base = isDir ? [7, 7, 7] : [6, 6, 6];\n  const mask = String(umask).padStart(3, \"0\").split(\"\").map(Number);\n  return base.map((b, i) => b & ~mask[i] & 7).join(\"\");\n}",
  tests: [['applyUmask("022", false)', '"644"'],
    ['applyUmask("022", true)', '"755"'],
    ['applyUmask("077", false)', '"600"'],
    ['applyUmask("000", false)', '"666"']],
  edge: [['applyUmask("077", true)', '"700"'], ['applyUmask("777", false)', '"000"']],
  ex: "'새 파일이 왜 <code>644</code> 로 생기지' 의 답이 여기 있습니다. 커널은 <code>666</code> 으로 만들려 하고, <b>umask 가 그중 일부를 깎습니다</b>.\n중요한 것은 <b>깎기만 한다</b>는 점입니다. umask 로는 권한을 <b>더할 수 없습니다</b> — 그래서 파일이 처음부터 실행 권한을 갖는 일이 없고, 실행 파일에는 <code>chmod +x</code> 를 따로 해야 합니다.\n폴더의 기본이 <code>777</code> 인 이유는 <code>x</code>(들어가기)가 없으면 폴더가 쓸모없어지기 때문입니다. 그래서 같은 <code>umask 022</code> 로도 파일은 <code>644</code>, 폴더는 <code>755</code> 가 됩니다.\n서비스 계정에 <code>umask 077</code> 을 주면 만들어지는 모든 것이 <b>자기만 읽을 수 있게</b> 되어, 실수로 남에게 노출되는 일을 구조적으로 막습니다." },

{ track: "linux", k: "경로를 정규화한다 · normalizePath", cat: "internals",
  q: "절대 경로 문자열에서 <code>.</code>·<code>..</code>·중복 슬래시를 정리해 표준형으로 돌려주세요. 뿌리 위로는 올라가지 않습니다. 결과는 항상 <code>/</code> 로 시작하고, 뿌리가 아니면 끝에 <code>/</code> 를 붙이지 않습니다.",
  src: "function normalizePath(p) {\n  // TODO: / 로 쪼갠 뒤 스택에 쌓았다 빼세요\n  return p;\n}",
  sol: "function normalizePath(p) {\n  const out = [];\n  String(p).split(\"/\").forEach((part) => {\n    if (part === \"\" || part === \".\") return;\n    if (part === \"..\") { out.pop(); return; }\n    out.push(part);\n  });\n  return \"/\" + out.join(\"/\");\n}",
  tests: [['normalizePath("/a/b/../c")', '"/a/c"'],
    ['normalizePath("/a//b/./c/")', '"/a/b/c"'],
    ['normalizePath("/../..")', '"/"'],
    ['normalizePath("/a/b/c/../../d")', '"/a/d"']],
  edge: [['normalizePath("/")', '"/"'], ['normalizePath("/.")', '"/"']],
  ex: "커널이 경로를 해석할 때 하는 일과 같습니다. <code>..</code> 를 만나면 <b>한 칸 되돌아가는</b> 스택 연산입니다.\n<b>뿌리 위로 올라가지 않는 것</b>이 중요한 안전장치입니다. <code>pop()</code> 은 빈 배열에서 아무 일도 하지 않으므로 자연스럽게 처리됩니다. 이 규칙이 없으면 <code>../../../etc/passwd</code> 같은 입력으로 의도한 폴더 밖을 읽는 <b>경로 순회 공격</b>이 성립합니다.\n웹 서버가 업로드 경로를 다룰 때 반드시 정규화한 뒤 <b>허용된 접두사로 시작하는지</b> 확인해야 하는 이유입니다. 정규화 없이 문자열만 검사하면 우회됩니다.\n실제 파일 시스템에서는 심볼릭 링크 때문에 더 복잡합니다. <code>..</code> 가 링크를 따라가면 예상과 다른 곳으로 갈 수 있어, 진짜 확인은 <code>realpath</code> 로 해야 합니다." },

/* ───────────── 셸이 하는 일 ───────────── */
{ track: "linux", k: "glob 을 펼친다 · expandGlob", cat: "internals",
  q: "파일 이름 목록에서 셸 패턴에 맞는 것을 <b>사전순</b>으로 돌려주세요. <code>*</code> 는 슬래시를 뺀 아무 문자열, <code>?</code> 는 아무 한 글자입니다. 맞는 것이 없으면 <b>패턴 자체</b>를 담은 배열을 돌려줍니다(bash 기본 동작).",
  src: "function expandGlob(pattern, files) {\n  // TODO: 패턴을 정규식으로 바꾸되 특수 문자를 먼저 막으세요\n  return files;\n}",
  sol: "function expandGlob(pattern, files) {\n  const body = String(pattern)\n    .replace(/[.+^${}()|[\\]\\\\]/g, \"\\\\$&\")\n    .replace(/\\*/g, \"[^/]*\")\n    .replace(/\\?/g, \"[^/]\");\n  const re = new RegExp(\"^\" + body + \"$\");\n  const hit = files.filter((f) => re.test(f)).sort();\n  return hit.length ? hit : [pattern];\n}",
  tests: [['expandGlob("*.txt", ["a.txt","b.log","c.txt"])', '["a.txt","c.txt"]'],
    ['expandGlob("?.log", ["a.log","ab.log"])', '["a.log"]'],
    ['expandGlob("*.md", ["a.txt"])', '["*.md"]'],
    ['expandGlob("a*", ["ab","ac","ba"])', '["ab","ac"]']],
  edge: [['expandGlob("*", [])', '["*"]'], ['expandGlob("a.b", ["a.b","axb"])', '["a.b"]']],
  ex: "<code>ls *.txt</code> 를 쳤을 때 <b>셸이 먼저</b> 하는 일입니다. <code>ls</code> 는 이미 펼쳐진 이름 목록만 받습니다.\n세 번째 테스트가 bash 의 유명한 함정입니다. <b>맞는 파일이 하나도 없으면 패턴이 글자 그대로</b> 넘어갑니다. 그래서 <code>rm *.bak</code> 이 '<code>*.bak</code> 이라는 파일이 없다' 는 이상한 오류를 냅니다. <code>shopt -s nullglob</code> 을 켜면 빈 목록이 됩니다.\n마지막 엣지 케이스가 <b>이스케이프의 이유</b>입니다. <code>.</code> 를 그대로 두면 정규식에서 아무 문자나 맞아 <code>axb</code> 까지 걸립니다 — 사용자 입력으로 정규식을 만들 때 늘 나오는 함정입니다.\n<code>*</code> 가 슬래시를 넘지 않는 것도 규칙입니다. 하위 폴더까지 훑으려면 <code>**</code> 를 켜야 하고, 이것이 <code>.gitignore</code> 와 여러 빌드 도구의 패턴 규칙에도 그대로 이어집니다." },

{ track: "linux", k: "PATH 에서 명령을 찾는다 · whichCmd", cat: "internals",
  q: "<code>PATH</code>(콜론으로 이어진 문자열)와 <code>{경로: [파일이름…]}</code> 지도가 주어집니다. 명령 이름을 <b>앞에서부터</b> 찾아 처음 만난 전체 경로를 돌려주세요. 없으면 <code>null</code> 입니다.",
  src: "function whichCmd(path, dirs, name) {\n  // TODO: PATH 를 콜론으로 쪼개 순서대로 보세요\n  return null;\n}",
  sol: "function whichCmd(path, dirs, name) {\n  const dirList = String(path).split(\":\").filter((x) => x);\n  for (let i = 0; i < dirList.length; i++) {\n    const dir = dirList[i];\n    const files = dirs[dir] || [];\n    if (files.indexOf(name) >= 0) return dir + \"/\" + name;\n  }\n  return null;\n}",
  tests: [['whichCmd("/usr/bin:/bin", {"/usr/bin":["ls"],"/bin":["ls","cat"]}, "ls")', '"/usr/bin/ls"'],
    ['whichCmd("/bin:/usr/bin", {"/usr/bin":["ls"],"/bin":["ls","cat"]}, "ls")', '"/bin/ls"'],
    ['whichCmd("/usr/bin:/bin", {"/usr/bin":["ls"],"/bin":["cat"]}, "cat")', '"/bin/cat"'],
    ['whichCmd("/usr/bin", {"/usr/bin":["ls"]}, "python")', "null"]],
  edge: [['whichCmd("", {}, "ls")', "null"], ['whichCmd("/a::/b", {"/b":["x"]}, "x")', '"/b/x"']],
  ex: "명령 이름만 쳤을 때 셸이 하는 탐색입니다. <b>앞에서부터 찾다가 처음 만난 것</b>을 실행하고 나머지는 보지 않습니다.\n첫 두 테스트가 같은 파일 구성에 <code>PATH</code> 순서만 다른 경우입니다. 순서가 곧 우선순위이므로, <code>PATH</code> 앞쪽에 폴더를 넣으면 시스템 명령을 <b>덮어쓸 수 있습니다</b>. <code>pyenv</code>·<code>nvm</code> 같은 버전 관리 도구가 정확히 이 원리로 동작합니다.\n같은 성질이 <b>공격 경로</b>이기도 합니다. 누구나 쓸 수 있는 폴더가 <code>PATH</code> 앞에 있으면 남이 가짜 <code>ls</code> 를 심을 수 있습니다. 현재 폴더 <code>.</code> 를 <code>PATH</code> 에 넣지 않는 관례가 여기서 나왔습니다.\n마지막 엣지 케이스의 빈 항목(<code>::</code>)은 실제로는 <b>현재 폴더</b>를 뜻해 위험합니다. 여기서는 걸러 냈지만, 실제 시스템에서는 이 빈 항목 때문에 사고가 납니다." },

{ track: "linux", k: "따옴표를 고려해 인자 쪼개기 · splitArgs", cat: "debug",
  q: "명령줄 문자열을 셸처럼 인자 배열로 쪼개 주세요. 공백으로 나누되 <b>큰따옴표나 작은따옴표로 감싼 부분은 하나</b>로 봅니다. 따옴표 자체는 결과에 넣지 않습니다.",
  src: "function splitArgs(line) {\n  // TODO: 따옴표 안인지 밖인지 상태를 들고 한 글자씩 보세요\n  return String(line).split(\" \");\n}",
  sol: "function splitArgs(line) {\n  const out = [];\n  let cur = \"\";\n  let quote = \"\";\n  let has = false;\n  for (const ch of String(line)) {\n    if (quote) {\n      if (ch === quote) quote = \"\";\n      else cur += ch;\n    } else if (ch === '\"' || ch === \"'\") {\n      quote = ch;\n      has = true;\n    } else if (ch === \" \") {\n      if (cur || has) out.push(cur);\n      cur = \"\";\n      has = false;\n    } else cur += ch;\n  }\n  if (cur || has) out.push(cur);\n  return out;\n}",
  tests: [['splitArgs("rm My Doc.txt")', '["rm","My","Doc.txt"]'],
    ['splitArgs(\'rm "My Doc.txt"\')', '["rm","My Doc.txt"]'],
    ['splitArgs("echo  a   b")', '["echo","a","b"]'],
    ['splitArgs("git commit -m \'first commit\'")', '["git","commit","-m","first commit"]']],
  edge: [['splitArgs("")', "[]"], ['splitArgs(\'a ""\')', '["a",""]']],
  ex: "첫 두 테스트의 차이가 <b>따옴표를 씌워야 하는 이유의 전부</b>입니다. <code>rm $file</code> 에서 파일 이름이 <code>My Doc.txt</code> 이면 인자가 <b>둘로 갈라져</b> 엉뚱한 것을 지웁니다.\n최악은 우연히 <code>My</code> 라는 파일이 존재하는 경우입니다 — 오류도 없이 조용히 사라집니다. 그래서 셸 스크립트에서 변수는 예외 없이 <code>\"$var\"</code> 로 감쌉니다.\n세 번째 테스트처럼 <b>연속된 공백은 하나로</b> 취급됩니다. 그래서 빈 인자를 만들려면 반드시 따옴표가 필요하고, 마지막 엣지 케이스가 그 경우입니다 — <code>has</code> 플래그가 없으면 이 빈 인자가 사라집니다.\n실제 셸은 여기에 변수 펼치기, <code>$(…)</code>, 이스케이프까지 더합니다. 그래서 문자열로 명령을 조립해 실행하는 것은 <b>명령어 주입</b>의 통로가 되고, 배열로 인자를 넘기는 API 를 써야 안전합니다." },

/* ───────────── 프로세스와 자원 ───────────── */
{ track: "linux", k: "프로세스 트리를 그린다 · childrenOf", cat: "internals",
  q: "<code>{pid, ppid}</code> 목록에서 주어진 PID 의 <b>모든 후손</b> PID 를 오름차순으로 돌려주세요. 자기 자신은 넣지 않습니다.",
  src: "function childrenOf(procs, pid) {\n  // TODO: 부모별 자식 목록을 만든 뒤 아래로 훑으세요\n  return [];\n}",
  sol: "function childrenOf(procs, pid) {\n  const kids = new Map();\n  procs.forEach((p) => {\n    if (!kids.has(p.ppid)) kids.set(p.ppid, []);\n    kids.get(p.ppid).push(p.pid);\n  });\n  const out = [];\n  const stack = (kids.get(pid) || []).slice();\n  while (stack.length) {\n    const id = stack.pop();\n    if (out.indexOf(id) >= 0) continue;\n    out.push(id);\n    (kids.get(id) || []).forEach((k) => stack.push(k));\n  }\n  return out.sort((a, b) => a - b);\n}",
  tests: [['childrenOf([{pid:2,ppid:1},{pid:3,ppid:2},{pid:4,ppid:1}], 1)', "[2,3,4]"],
    ['childrenOf([{pid:2,ppid:1},{pid:3,ppid:2}], 2)', "[3]"],
    ['childrenOf([{pid:2,ppid:1},{pid:3,ppid:2}], 3)', "[]"],
    ['childrenOf([{pid:2,ppid:1},{pid:3,ppid:1},{pid:4,ppid:3},{pid:5,ppid:4}], 1)', "[2,3,4,5]"]],
  edge: [['childrenOf([], 1)', "[]"], ['childrenOf([{pid:1,ppid:0}], 1)', "[]"]],
  ex: "<code>ps --forest</code> 가 그리는 나무가 이 구조입니다. 프로세스는 <b>부모를 알고</b>, 자식 목록은 전체를 훑어 만들어야 합니다 — Git 커밋 그래프와 같은 방향성입니다.\n서비스를 확실히 끄려면 <b>후손까지</b> 잡아야 합니다. 부모만 죽이면 자식은 살아남아 PID 1 에게 입양되고, 포트를 계속 잡고 있어 재시작이 실패합니다.\n그래서 systemd 는 프로세스를 <b>cgroup 에 묶어</b> 통째로 관리합니다. '분명 껐는데 포트가 안 열린다' 는 문제가 이 관리 덕분에 사라졌습니다.\n<code>out</code> 에 이미 있는지 확인하는 줄은 데이터가 어긋나 순환이 생겨도 무한히 돌지 않게 합니다. 실제 시스템에서는 생기지 않지만, 입력을 믿지 않는 습관은 그대로 값어치가 있습니다." },

{ track: "linux", k: "load average 를 판정한다 · loadVerdict", cat: "debug",
  q: "1분 load 와 코어 수가 주어집니다. 코어당 부하로 <code>\"idle\"</code>(0.7 미만) · <code>\"busy\"</code>(0.7 이상 1.0 미만) · <code>\"saturated\"</code>(1.0 이상 2.0 미만) · <code>\"overloaded\"</code>(2.0 이상)를 돌려주세요.",
  src: "function loadVerdict(load, cores) {\n  // TODO: 코어 수로 나눈 값으로 판정하세요\n  return \"busy\";\n}",
  sol: "function loadVerdict(load, cores) {\n  if (!cores) return \"overloaded\";\n  const per = load / cores;\n  if (per < 0.7) return \"idle\";\n  if (per < 1.0) return \"busy\";\n  if (per < 2.0) return \"saturated\";\n  return \"overloaded\";\n}",
  tests: [['loadVerdict(2, 4)', '"idle"'],
    ['loadVerdict(3.2, 4)', '"busy"'],
    ['loadVerdict(5, 4)', '"saturated"'],
    ['loadVerdict(9, 4)', '"overloaded"']],
  edge: [['loadVerdict(0, 1)', '"idle"'], ['loadVerdict(1, 1)', '"saturated"']],
  ex: "load average 의 절대값은 <b>아무 의미가 없습니다.</b> 코어 수로 나눠야 비로소 판단이 됩니다 — 코어 32개 서버의 load 8은 한가하고, 코어 1개의 load 4는 심각합니다.\n마지막 두 엣지 케이스가 그 대비입니다. 같은 숫자라도 코어 수에 따라 완전히 다른 판정이 나옵니다.\n리눅스의 load 는 CPU 뿐 아니라 <b>디스크를 기다리는 프로세스도 포함</b>합니다. 그래서 CPU 사용률은 낮은데 load 가 높은 조합이 나오고, 그때는 I/O 병목을 의심해야 합니다. 이것이 다른 유닉스 계열과 다른 리눅스만의 정의입니다.\n1·5·15분 세 숫자를 함께 보는 이유는 <b>추세</b> 때문입니다. 1분이 15분보다 크면 지금 나빠지는 중이고, 반대면 회복 중입니다 — 한 숫자만 보면 알 수 없는 정보입니다." },

{ track: "linux", k: "메모리 여유를 계산한다 · availableMem", cat: "debug",
  q: "<code>{total, used, buffCache, free}</code>(MB)가 주어집니다. 실제로 쓸 수 있는 양은 <code>free + buffCache</code> 이고, 이 값이 전체의 10% 미만이면 <code>-1</code> 을 돌려주세요. 아니면 그 값을 돌려줍니다.",
  src: "function availableMem(m) {\n  // TODO: 캐시는 필요하면 회수됩니다\n  return m.free;\n}",
  sol: "function availableMem(m) {\n  const avail = m.free + m.buffCache;\n  if (avail < m.total * 0.1) return -1;\n  return avail;\n}",
  tests: [['availableMem({total:1000, used:800, buffCache:150, free:50})', "200"],
    ['availableMem({total:1000, used:950, buffCache:30, free:20})', "-1"],
    ['availableMem({total:1000, used:100, buffCache:0, free:900})', "900"],
    ['availableMem({total:2000, used:1000, buffCache:900, free:100})', "1000"]],
  edge: [['availableMem({total:100, used:100, buffCache:0, free:0})', "-1"],
    ['availableMem({total:1000, used:0, buffCache:100, free:0})', "100"]],
  ex: "<code>free -h</code> 를 읽을 때 가장 흔한 오해가 여기 있습니다. 첫 번째 테스트에서 <code>free</code> 는 50MB 뿐이지만 <b>실제 여유는 200MB</b> 입니다.\n리눅스는 남는 메모리를 <b>파일 캐시로 전부 씁니다.</b> 놀리는 메모리는 낭비이기 때문입니다. 그 캐시는 새 프로그램이 메모리를 요구하면 즉시 회수되므로, 사실상 여유 공간입니다.\n그래서 <code>free</code> 열만 보고 '메모리가 없다' 고 판단하면 거의 언제나 틀립니다. 요즘 <code>free</code> 명령은 아예 <code>available</code> 열을 따로 계산해 보여 줍니다.\n진짜 위험 신호는 <b>스왑 사용량이 계속 늘고 디스크 I/O 가 치솟는</b> 상태입니다. 그때는 메모리 부족이 성능 문제로 나타나고, 더 진행되면 OOM Killer 가 프로세스를 죽입니다." },

/* ───────────── 텍스트와 로그 ───────────── */
{ track: "linux", k: "가장 많이 나온 값 세기 · topCounts", cat: "internals",
  q: "문자열 배열에서 많이 나온 순으로 <code>\"개수 값\"</code> 형태 배열을 <code>n</code> 개까지 돌려주세요. 개수가 같으면 <b>값의 사전순</b>으로 앞에 둡니다.",
  src: "function topCounts(items, n) {\n  // TODO: 세고, 정렬하고, 잘라 내세요\n  return [];\n}",
  sol: "function topCounts(items, n) {\n  const count = new Map();\n  items.forEach((x) => count.set(x, (count.get(x) || 0) + 1));\n  return Array.from(count.keys())\n    .sort((a, b) => (count.get(b) - count.get(a)) || (a < b ? -1 : a > b ? 1 : 0))\n    .slice(0, n)\n    .map((k) => count.get(k) + \" \" + k);\n}",
  tests: [['topCounts(["a","b","a","c","a","b"], 2)', '["3 a","2 b"]'],
    ['topCounts(["x","y"], 5)', '["1 x","1 y"]'],
    ['topCounts(["b","a"], 1)', '["1 a"]'],
    ['topCounts(["e","e","e"], 1)', '["3 e"]']],
  edge: [['topCounts([], 3)', "[]"], ['topCounts(["a"], 0)', "[]"]],
  ex: "셸의 <code>sort | uniq -c | sort -rn | head</code> 관용구를 코드로 옮긴 것입니다. 접속 IP, 오류 코드, 느린 URL 을 찾을 때 손이 저절로 치게 되는 조합입니다.\n<code>uniq</code> 앞에 <code>sort</code> 가 반드시 필요한 이유가 여기서 드러납니다 — <code>uniq</code> 는 <b>인접한 중복만</b> 지우므로, 정렬하지 않으면 떨어져 있는 같은 값이 따로 세어집니다. 오류도 나지 않아 조용히 틀립니다.\n<b>동점 규칙</b>을 사전순으로 못 박은 것이 세 번째 테스트입니다. 규칙이 없으면 실행할 때마다 순서가 흔들려 결과를 비교할 수 없습니다.\n로그가 아주 클 때는 이 방식이 메모리를 많이 씁니다. 상위 몇 개만 필요하다면 크기 <code>n</code> 인 최소 힙으로 메모리를 <code>n</code> 에 비례하게 줄일 수 있습니다." },

{ track: "linux", k: "로그 줄을 필드로 나눈다 · parseLogLine", cat: "debug",
  q: "<code>\"2024-01-05 10:03:11 ERROR payment timeout\"</code> 형태의 줄에서 <code>[\"날짜시각\", \"수준\", \"나머지\"]</code> 세 조각을 돌려주세요. 형식이 맞지 않으면 <code>null</code> 입니다. 수준은 <code>INFO</code>·<code>WARN</code>·<code>ERROR</code> 중 하나입니다.",
  src: "function parseLogLine(line) {\n  // TODO: 앞 세 조각만 나누고 나머지는 붙여 두세요\n  return null;\n}",
  sol: "function parseLogLine(line) {\n  const cols = String(line).split(\" \");\n  if (cols.length < 4) return null;\n  const level = cols[2];\n  if ([\"INFO\", \"WARN\", \"ERROR\"].indexOf(level) < 0) return null;\n  return [cols[0] + \" \" + cols[1], level, cols.slice(3).join(\" \")];\n}",
  tests: [['parseLogLine("2024-01-05 10:03:11 ERROR payment timeout")', '["2024-01-05 10:03:11","ERROR","payment timeout"]'],
    ['parseLogLine("2024-01-05 10:03:11 INFO ok")', '["2024-01-05 10:03:11","INFO","ok"]'],
    ['parseLogLine("2024-01-05 10:03:11 TRACE hi")', "null"],
    ['parseLogLine("bad line")', "null"]],
  edge: [['parseLogLine("")', "null"], ['parseLogLine("2024-01-05 10:03:11 WARN a b c")', '["2024-01-05 10:03:11","WARN","a b c"]']],
  ex: "<b>앞의 정해진 개수만 나누고 나머지는 통째로 두는 것</b>이 로그 파싱의 기본형입니다. 메시지에 공백이 몇 개 있든 마지막 조각이 전부 흡수합니다.\n마지막 엣지 케이스가 그 요점입니다. <code>split(\" \")</code> 결과를 그대로 쓰면 메시지가 조각나므로, <code>slice(3).join(\" \")</code> 로 다시 붙여야 합니다.\n형식이 다르면 <code>null</code> 을 돌려주는 것도 중요합니다. 로그에는 <b>스택 트레이스와 여러 줄 출력</b>이 섞여 들어오므로, 모든 줄이 형식에 맞을 것이라 가정하면 파서가 터집니다.\n이런 파싱이 필요하다는 것 자체가 <b>구조화된 로그를 쓰지 않은 대가</b>입니다. JSON 한 줄로 남기면 필드를 정확히 뽑을 수 있고, 이 함수와 그 미묘한 버그들이 전부 사라집니다." },

{ track: "linux", k: "구간의 오류율을 낸다 · errorRate", cat: "debug",
  q: "로그 수준 배열에서 <code>ERROR</code> 의 비율을 <b>백분율 정수</b>(반올림)로 돌려주세요. 줄이 하나도 없으면 <code>0</code> 입니다.",
  src: "function errorRate(levels) {\n  // TODO: 세고 나누되 0으로 나누지 않게 하세요\n  return 0;\n}",
  sol: "function errorRate(levels) {\n  if (!levels.length) return 0;\n  let bad = 0;\n  levels.forEach((x) => { if (x === \"ERROR\") bad++; });\n  return Math.round(bad / levels.length * 100);\n}",
  tests: [['errorRate(["INFO","ERROR","INFO","INFO"])', "25"],
    ['errorRate(["ERROR","ERROR"])', "100"],
    ['errorRate(["INFO","WARN"])', "0"],
    ['errorRate(["ERROR","INFO","INFO"])', "33"]],
  edge: [['errorRate([])', "0"], ['errorRate(["WARN"])', "0"]],
  ex: "장애 판단의 기준은 오류의 <b>절대 개수가 아니라 비율</b>입니다. 요청이 열 배 늘면 오류도 열 배 늘어 보이지만 서비스는 멀쩡할 수 있습니다.\n빈 배열을 먼저 막는 줄이 없으면 <code>0/0</code> 이 <code>NaN</code> 이 되고, 그 <code>NaN</code> 이 경보 조건 비교에서 조용히 거짓이 되어 <b>경보가 울리지 않습니다.</b> 새벽에 아무도 모르게 서비스가 죽는 전형적인 경로입니다.\n실무의 경보는 대개 '5분 동안 오류율 5% 초과' 처럼 <b>구간과 임계값</b>을 함께 정합니다. 순간값으로 걸면 잡음에 계속 울려 아무도 보지 않게 됩니다.\n트래픽이 거의 없는 시간대에는 요청 두 건 중 한 건만 실패해도 50% 가 되므로, <b>최소 표본 수</b> 조건을 함께 두는 것이 실용적입니다." },

/* ───────────── 디스크와 정기 작업 ───────────── */
{ track: "linux", k: "폴더별 용량을 합친다 · duByDir", cat: "internals",
  q: "<code>{path, size}</code> 목록에서 <b>최상위 폴더별</b> 합계를 <code>\"폴더 합계\"</code> 형태로, 큰 순서대로 돌려주세요. 같으면 폴더 이름 사전순입니다. 경로는 항상 <code>/</code> 로 시작합니다.",
  src: "function duByDir(files) {\n  // TODO: 경로에서 첫 번째 조각만 뽑아 묶으세요\n  return [];\n}",
  sol: "function duByDir(files) {\n  const sum = new Map();\n  files.forEach((f) => {\n    const top = \"/\" + String(f.path).split(\"/\").filter((x) => x)[0];\n    sum.set(top, (sum.get(top) || 0) + f.size);\n  });\n  return Array.from(sum.keys())\n    .sort((a, b) => (sum.get(b) - sum.get(a)) || (a < b ? -1 : 1))\n    .map((k) => k + \" \" + sum.get(k));\n}",
  tests: [['duByDir([{path:"/var/log/a",size:100},{path:"/var/lib/b",size:50},{path:"/etc/c",size:10}])', '["/var 150","/etc 10"]'],
    ['duByDir([{path:"/a/x",size:1},{path:"/b/y",size:1}])', '["/a 1","/b 1"]'],
    ['duByDir([{path:"/var/x",size:5}])', '["/var 5"]'],
    ['duByDir([{path:"/a/x",size:3},{path:"/a/y",size:4}])', '["/a 7"]']],
  edge: [['duByDir([])', "[]"], ['duByDir([{path:"/tmp/f",size:0}])', '["/tmp 0"]']],
  ex: "<code>du -sh /* | sort -h</code> 로 디스크를 뒤질 때 하는 계산입니다. <b>큰 덩어리부터 좁혀 들어가는</b> 것이 요령입니다.\n디스크가 꽉 찼을 때 <code>df</code> 는 '어느 파티션' 까지만 알려 주고, <b>어느 폴더가 범인인지</b>는 이 집계가 알려 줍니다. 실무에서는 <code>/var</code> 가 가장 흔한 범인이고, 그 안에서는 <code>/var/log</code> 입니다.\n동점 규칙을 정한 것은 결과를 재현 가능하게 하기 위해서입니다. 집계 결과를 사람이 비교하려면 순서가 안정적이어야 합니다.\n주의할 점 하나 — <b>지워졌지만 프로세스가 열고 있는 파일</b>은 이 집계에 잡히지 않으면서 공간은 차지합니다. <code>du</code> 와 <code>df</code> 가 어긋나면 그것을 의심하고 <code>lsof +L1</code> 로 찾아야 합니다." },

{ track: "linux", k: "cron 표현식을 읽는다 · cronMatches", cat: "internals",
  q: "<code>\"분 시 일 월 요일\"</code> 다섯 필드 표현식과 <code>{min, hour, day, month, dow}</code> 시각이 주어집니다. 일치하면 <code>true</code> 입니다. 각 필드는 <code>*</code>, 숫자, <code>*/n</code> 만 지원합니다.",
  src: "function cronMatches(expr, at) {\n  // TODO: 필드마다 세 형태를 각각 판정하세요\n  return true;\n}",
  sol: "function cronMatches(expr, at) {\n  const fields = String(expr).trim().split(/\\s+/);\n  if (fields.length !== 5) return false;\n  const now = [at.min, at.hour, at.day, at.month, at.dow];\n  const ok = (spec, val) => {\n    if (spec === \"*\") return true;\n    if (spec.slice(0, 2) === \"*/\") {\n      const step = Number(spec.slice(2));\n      return step > 0 && val % step === 0;\n    }\n    return Number(spec) === val;\n  };\n  return fields.every((spec, i) => ok(spec, now[i]));\n}",
  tests: [['cronMatches("0 3 * * *", {min:0,hour:3,day:5,month:1,dow:2})', "true"],
    ['cronMatches("0 3 * * *", {min:0,hour:4,day:5,month:1,dow:2})', "false"],
    ['cronMatches("*/15 * * * *", {min:30,hour:1,day:1,month:1,dow:0})', "true"],
    ['cronMatches("*/15 * * * *", {min:31,hour:1,day:1,month:1,dow:0})', "false"]],
  edge: [['cronMatches("* * * * *", {min:7,hour:7,day:7,month:7,dow:7})', "true"],
    ['cronMatches("0 3 * *", {min:0,hour:3,day:1,month:1,dow:1})', "false"]],
  ex: "필드 순서가 <b>분 · 시 · 일 · 월 · 요일</b> 이라는 것이 첫 번째 관문입니다. <code>0 3 * * *</code> 는 매일 3시 정각이고, <code>*/3 * * * *</code> 는 3분마다입니다 — 이 둘을 헷갈리는 실수가 가장 흔합니다.\n마지막 엣지 케이스처럼 <b>필드 수가 다르면</b> 즉시 거짓으로 처리해야 합니다. 잘못 적은 표현식이 조용히 다른 시각에 도는 것보다, 명확히 실패하는 편이 훨씬 낫습니다.\n실제 cron 은 범위(<code>1-5</code>), 목록(<code>1,3,5</code>), 이름(<code>MON</code>)까지 지원하고, 일과 요일이 <b>둘 다 지정되면 OR</b> 로 동작하는 특이한 규칙도 있습니다 — 직관과 달라 사고의 원인이 됩니다.\n표현식이 헷갈릴 때는 옆에 사람 말로 주석을 달아 두는 것이 서로에게 친절합니다. 읽는 사람이 매번 해독하지 않아도 됩니다." },

{ track: "linux", k: "로그 회전을 결정한다 · rotatePlan", cat: "ops",
  q: "로그 파일 목록 <code>{name, sizeMB, ageDays}</code> 에서 <b>크기가 100MB 이상이거나 7일보다 오래된</b> 파일의 이름을 사전순으로 돌려주세요. 이미 압축된 파일(<code>.gz</code> 로 끝남)은 제외합니다.",
  src: "function rotatePlan(logs) {\n  // TODO: 조건 세 개를 순서대로 걸러 내세요\n  return [];\n}",
  sol: "function rotatePlan(logs) {\n  return logs\n    .filter((l) => String(l.name).slice(-3) !== \".gz\")\n    .filter((l) => l.sizeMB >= 100 || l.ageDays > 7)\n    .map((l) => l.name)\n    .sort();\n}",
  tests: [['rotatePlan([{name:"a.log",sizeMB:150,ageDays:1}])', '["a.log"]'],
    ['rotatePlan([{name:"b.log",sizeMB:10,ageDays:9}])', '["b.log"]'],
    ['rotatePlan([{name:"c.log",sizeMB:10,ageDays:3}])', "[]"],
    ['rotatePlan([{name:"d.log.gz",sizeMB:900,ageDays:99}])', "[]"]],
  edge: [['rotatePlan([])', "[]"], ['rotatePlan([{name:"e.log",sizeMB:100,ageDays:0}])', '["e.log"]']],
  ex: "<code>logrotate</code> 가 매일 하는 판단입니다. 조건은 대개 <b>크기 또는 나이</b> 이고, 둘 중 하나만 넘어도 회전시킵니다.\n이미 압축된 파일을 제외하는 것이 중요합니다. 빠뜨리면 같은 로그를 계속 다시 압축하며 CPU 와 I/O 를 낭비합니다.\n마지막 엣지 케이스에서 <b>정확히 100MB</b> 가 포함되는 것에 주목하세요. 경계값을 포함할지 말지는 정의의 문제이므로, 문서가 아니라 <b>테스트로 못 박아</b> 두어야 나중에 조용히 바뀌지 않습니다.\n회전할 때 파일을 <code>rm</code> 하지 않고 <b>옮긴 뒤 프로세스에 신호를 보내는</b> 것이 핵심입니다. 열려 있는 파일을 지우면 공간이 반환되지 않고 애플리케이션은 사라진 파일에 계속 씁니다." },

/* ───────────── 스크립트의 안전 ───────────── */
{ track: "linux", k: "위험한 rm 을 막는다 · isDangerousRm", cat: "security",
  q: "<code>rm -rf</code> 의 대상 경로가 위험한지 판정해 주세요. <b>빈 문자열</b>, <code>/</code>, <b>슬래시 한 개짜리 최상위 경로</b>(<code>/etc</code> 등), <b>슬래시로 끝나는 변수 미치환 흔적</b>(<code>$</code> 포함)이면 <code>true</code> 입니다.",
  src: "function isDangerousRm(path) {\n  // TODO: 빈 값과 최상위 경로를 각각 막으세요\n  return false;\n}",
  sol: "function isDangerousRm(path) {\n  const p = String(path == null ? \"\" : path).trim();\n  if (!p) return true;\n  if (p.indexOf(\"$\") >= 0) return true;\n  if (p === \"/\") return true;\n  const seg = p.split(\"/\").filter((x) => x);\n  return p.charAt(0) === \"/\" && seg.length <= 1;\n}",
  tests: [['isDangerousRm("")', "true"],
    ['isDangerousRm("/")', "true"],
    ['isDangerousRm("/etc")', "true"],
    ['isDangerousRm("/srv/app/tmp")', "false"]],
  edge: [['isDangerousRm("/var/log/old")', "false"], ['isDangerousRm("$DIR/build")', "true"]],
  ex: "<code>rm -rf \"$DIR/\"</code> 에서 <code>DIR</code> 이 비면 <code>rm -rf /</code> 가 됩니다. 스팀 클라이언트가 사용자 홈을 통째로 지운 사고가 정확히 이 형태였습니다.\n<code>set -u</code> 로 없는 변수를 오류로 만드는 것이 첫 번째 방어이고, 이렇게 <b>대상 경로를 실행 전에 검사</b>하는 것이 두 번째입니다. 지우는 명령에는 방어를 두 겹 두어도 지나치지 않습니다.\n마지막 엣지 케이스는 <code>$</code> 가 남아 있는 경우입니다 — 변수가 펼쳐지지 않았다는 뜻이므로, 그 상태로 지우면 무슨 일이 벌어질지 알 수 없습니다.\n최상위 경로를 막는 것도 의도적입니다. <code>/etc</code>·<code>/var</code> 를 통째로 지울 이유는 거의 없고, 정말 필요하다면 사람이 손으로 확인하며 하는 편이 맞습니다." },

{ track: "linux", k: "종료 코드를 해석한다 · exitMeaning", cat: "debug",
  q: "프로세스 종료 코드를 <code>\"ok\"</code>(0) · <code>\"error\"</code>(1~127) · <code>\"signal:이름\"</code>(128 초과)으로 해석해 주세요. 신호는 <code>130</code>=INT, <code>137</code>=KILL, <code>143</code>=TERM 만 이름을 붙이고 나머지는 <code>\"signal:\"+번호</code> 입니다.",
  src: "function exitMeaning(code) {\n  // TODO: 128 을 넘으면 신호로 죽은 것입니다\n  return \"ok\";\n}",
  sol: "function exitMeaning(code) {\n  if (code === 0) return \"ok\";\n  if (code <= 127) return \"error\";\n  const names = { 130: \"INT\", 137: \"KILL\", 143: \"TERM\" };\n  return \"signal:\" + (names[code] || (code - 128));\n}",
  tests: [['exitMeaning(0)', '"ok"'],
    ['exitMeaning(1)', '"error"'],
    ['exitMeaning(137)', '"signal:KILL"'],
    ['exitMeaning(143)', '"signal:TERM"']],
  edge: [['exitMeaning(127)', '"error"'], ['exitMeaning(139)', '"signal:11"']],
  ex: "<b>128 + 신호 번호</b> 라는 규칙이 이 함수의 전부입니다. 컨테이너가 <code>137</code> 로 죽었다면 <code>128+9</code>, 즉 <b>KILL</b> 로 강제 종료된 것입니다.\n실무에서 <code>137</code> 은 거의 언제나 <b>메모리 한도 초과</b>입니다. 도커나 쿠버네티스가 한도를 넘은 컨테이너를 죽인 것이고, 애플리케이션 로그에는 아무것도 남지 않아 더 헷갈립니다. 종료 코드가 유일한 단서인 경우가 많습니다.\n<code>143</code>(TERM)은 반대로 <b>정상적인 종료 요청</b>입니다. 배포로 컨테이너를 교체할 때 나오는 값이라 장애가 아닙니다 — 이 둘을 구분하지 못하면 멀쩡한 배포를 장애로 오인합니다.\n마지막 엣지 케이스 <code>139</code> 는 <code>128+11</code>, 즉 <b>세그멘테이션 오류</b>입니다. C·C++ 프로그램에서 잘못된 메모리 접근이 있었다는 뜻입니다." },

{ track: "linux", k: "환경 변수를 펼친다 · expandVars", cat: "internals",
  q: "문자열 안의 <code>$NAME</code> 과 <code>${NAME}</code> 을 환경 변수 지도의 값으로 바꿔 주세요. <b>정의되지 않은 변수는 빈 문자열</b>로 바뀝니다. 이름은 영문자·숫자·밑줄로 이루어집니다.",
  src: "function expandVars(text, env) {\n  // TODO: 두 형태를 하나의 정규식으로 잡을 수 있습니다\n  return text;\n}",
  sol: "function expandVars(text, env) {\n  return String(text).replace(/\\$\\{([A-Za-z0-9_]+)\\}|\\$([A-Za-z0-9_]+)/g,\n    (all, a, b) => {\n      const key = a || b;\n      return Object.prototype.hasOwnProperty.call(env, key) ? String(env[key]) : \"\";\n    });\n}",
  tests: [['expandVars("hi $USER", {USER:"kim"})', '"hi kim"'],
    ['expandVars("${A}/${B}", {A:"x", B:"y"})', '"x/y"'],
    ['expandVars("v=$NOPE!", {})', '"v=!"'],
    ['expandVars("$A$B", {A:"1", B:"2"})', '"12"']],
  edge: [['expandVars("no vars", {})', '"no vars"'], ['expandVars("$", {})', '"$"']],
  ex: "셸이 명령을 실행하기 <b>전에</b> 하는 치환입니다. 프로그램은 이미 펼쳐진 문자열만 받습니다.\n세 번째 테스트가 셸 스크립트 사고의 근원입니다. 정의되지 않은 변수가 <b>조용히 빈 문자열</b>이 되어, <code>rm -rf $DIR/</code> 이 <code>rm -rf /</code> 가 됩니다. <code>set -u</code> 를 켜면 이 경우 오류로 멈추므로, 스크립트 첫 줄에 반드시 넣어야 합니다.\n<code>${NAME}</code> 중괄호 형태가 필요한 이유는 <b>경계</b> 때문입니다. <code>$AB</code> 는 <code>AB</code> 라는 변수를 찾지만 <code>${A}B</code> 는 <code>A</code> 의 값 뒤에 <code>B</code> 를 붙입니다.\n실제 셸은 <code>${VAR:-기본값}</code>, <code>${VAR:?메시지}</code>, <code>${VAR#접두사}</code> 같은 확장까지 지원합니다. 특히 앞의 둘은 <code>set -u</code> 와 함께 쓰면 '없으면 이 값' 과 '없으면 오류' 를 깔끔하게 표현할 수 있습니다." },

{ track: "linux", k: "IP 가 대역 안인가 · inCidr", cat: "security",
  q: "IPv4 주소가 <code>\"10.0.0.0/8\"</code> 같은 CIDR 대역에 속하는지 판정해 주세요. 주소나 대역 형식이 잘못되면 <code>false</code> 입니다.",
  src: "function inCidr(ip, cidr) {\n  // TODO: 32비트 정수로 바꾼 뒤 앞에서 prefix 비트만 비교하세요\n  return false;\n}",
  sol: "function inCidr(ip, cidr) {\n  const toNum = (s) => {\n    const oct = String(s).split(\".\");\n    if (oct.length !== 4) return null;\n    let n = 0;\n    for (let i = 0; i < 4; i++) {\n      const v = Number(oct[i]);\n      if (!(v >= 0 && v <= 255) || oct[i] === \"\") return null;\n      n = n * 256 + v;\n    }\n    return n;\n  };\n  const cw = String(cidr).split(\"/\");\n  if (cw.length !== 2) return false;\n  const bits = Number(cw[1]);\n  if (!(bits >= 0 && bits <= 32)) return false;\n  const a = toNum(ip);\n  const b = toNum(cw[0]);\n  if (a === null || b === null) return false;\n  const size = Math.pow(2, 32 - bits);\n  return Math.floor(a / size) === Math.floor(b / size);\n}",
  tests: [['inCidr("10.1.2.3", "10.0.0.0/8")', "true"],
    ['inCidr("11.1.2.3", "10.0.0.0/8")', "false"],
    ['inCidr("192.168.1.5", "192.168.1.0/24")', "true"],
    ['inCidr("192.168.2.5", "192.168.1.0/24")', "false"]],
  edge: [['inCidr("1.2.3.4", "0.0.0.0/0")', "true"], ['inCidr("bad", "10.0.0.0/8")', "false"]],
  ex: "방화벽 규칙과 보안 그룹이 하는 판정입니다. IP 를 <b>32비트 정수</b>로 보면 대역 판정은 '앞의 <code>n</code> 비트가 같은가' 하나로 줄어듭니다.\n비트 시프트 대신 나눗셈을 쓴 것은 자바스크립트의 비트 연산이 <b>부호 있는 32비트</b>라 <code>128.x.x.x</code> 이상에서 음수가 되기 때문입니다. 언어의 수 표현이 도메인과 어긋나는 자리이고, 모르면 특정 IP 대역에서만 틀리는 버그가 됩니다.\n<code>0.0.0.0/0</code> 은 <b>모든 주소</b>를 뜻합니다. 보안 그룹에서 이 값은 '인터넷 전체에 열림' 이라, 데이터베이스 포트에 이것이 걸려 있으면 즉시 고쳐야 할 사고입니다.\n입력 검증을 촘촘히 한 이유가 있습니다. 접근 제어에 쓰이는 함수가 잘못된 입력에 <code>true</code> 를 돌려주면 그것이 곧 **보안 구멍**입니다 — 애매하면 거부하는 쪽이 안전합니다." },

{ track: "linux", k: "재시도 간격을 계산한다 · backoffDelays", cat: "ops",
  q: "첫 지연 <code>base</code> 초에서 시작해 <b>두 배씩</b> 늘리되 <code>cap</code> 초를 넘지 않는 재시도 지연 배열을 <code>n</code> 개 돌려주세요.",
  src: "function backoffDelays(base, cap, n) {\n  // TODO: 두 배씩 늘리되 상한에서 멈추세요\n  return [];\n}",
  sol: "function backoffDelays(base, cap, n) {\n  const out = [];\n  let cur = base;\n  for (let i = 0; i < n; i++) {\n    out.push(Math.min(cur, cap));\n    cur = cur * 2;\n  }\n  return out;\n}",
  tests: [['backoffDelays(1, 30, 5)', "[1,2,4,8,16]"],
    ['backoffDelays(1, 10, 5)', "[1,2,4,8,10]"],
    ['backoffDelays(5, 5, 3)', "[5,5,5]"],
    ['backoffDelays(2, 100, 4)', "[2,4,8,16]"]],
  edge: [['backoffDelays(1, 30, 0)', "[]"], ['backoffDelays(3, 1, 2)', "[1,1]"]],
  ex: "실패한 요청을 <b>같은 간격으로</b> 재시도하면 장애 상황에서 부하가 그대로 유지되어, 회복하려는 서버를 계속 밀어붙입니다. 지수 백오프는 그 압력을 빠르게 줄입니다.\n<b>상한(cap)</b> 이 필요한 이유는 두 배씩 늘리면 금세 몇 시간이 되기 때문입니다. 두 번째 테스트가 상한에 걸리는 순간을 보여 줍니다.\n실제로는 여기에 <b>지터(무작위 흔들림)</b> 를 더해야 합니다. 같은 시각에 실패한 클라이언트 수천 개가 정확히 같은 지연으로 재시도하면, 회복하는 순간 다시 몰려가 서버를 또 넘어뜨립니다 — <b>천둥 소리 무리 문제</b>입니다.\n재시도를 붙이기 전에 확인할 것이 하나 더 있습니다. 그 요청이 <b>여러 번 실행돼도 안전한가</b>(멱등적인가)입니다. 결제나 주문 생성에 무턱대고 재시도를 붙이면 중복이 생깁니다." },

{ track: "linux", k: "디스크 경보를 낸다 · diskAlerts", cat: "ops",
  q: "<code>{mount, usedPct, inodePct}</code> 목록에서 <b>둘 중 하나라도 90 이상</b>인 마운트의 이름을 사전순으로 돌려주세요.",
  src: "function diskAlerts(rows) {\n  // TODO: 공간과 inode 는 따로 찹니다\n  return [];\n}",
  sol: "function diskAlerts(rows) {\n  return rows\n    .filter((r) => r.usedPct >= 90 || r.inodePct >= 90)\n    .map((r) => r.mount)\n    .sort();\n}",
  tests: [['diskAlerts([{mount:"/",usedPct:95,inodePct:10}])', '["/"]'],
    ['diskAlerts([{mount:"/var",usedPct:20,inodePct:99}])', '["/var"]'],
    ['diskAlerts([{mount:"/",usedPct:50,inodePct:50}])', "[]"],
    ['diskAlerts([{mount:"/b",usedPct:91,inodePct:1},{mount:"/a",usedPct:1,inodePct:91}])', '["/a","/b"]']],
  edge: [['diskAlerts([])', "[]"], ['diskAlerts([{mount:"/",usedPct:90,inodePct:0}])', '["/"]']],
  ex: "디스크 경보를 <b>공간만</b> 보고 걸어 두면 두 번째 테스트 같은 상황을 놓칩니다. 공간은 20% 밖에 안 썼는데 <b>파일 개수(inode)</b>가 다 차서 새 파일을 못 만드는 상태입니다.\n작은 파일을 수백만 개 만드는 세션 저장소·캐시·메일 큐에서 실제로 벌어집니다. <code>df -h</code> 만 보면 원인을 영영 못 찾습니다.\n임계값을 90% 로 둔 것은 <b>대응할 시간을 벌기 위해서</b>입니다. 100% 에서 알리면 이미 서비스가 멈춘 뒤입니다.\n더 나은 경보는 절대값이 아니라 <b>증가 속도</b>를 함께 보는 것입니다. '이 속도면 6시간 뒤 가득 찬다' 는 예측이 있으면 새벽에 깨지 않아도 됩니다." },

{ track: "linux", k: "설정 파일을 읽는다 · parseIni", cat: "internals",
  q: "<code>key=value</code> 형식의 설정 줄 배열에서 <code>\"key=value\"</code> 를 <b>키 사전순</b>으로 돌려주세요. <code>#</code> 로 시작하는 주석과 빈 줄은 건너뛰고, 앞뒤 공백은 없앱니다. 같은 키가 여러 번 나오면 <b>마지막 값</b>이 이깁니다.",
  src: "function parseIni(lines) {\n  // TODO: 주석과 빈 줄을 먼저 걸러 내세요\n  return [];\n}",
  sol: "function parseIni(lines) {\n  const conf = new Map();\n  lines.forEach((raw) => {\n    const line = String(raw).trim();\n    if (!line || line.charAt(0) === \"#\") return;\n    const at = line.indexOf(\"=\");\n    if (at < 0) return;\n    conf.set(line.slice(0, at).trim(), line.slice(at + 1).trim());\n  });\n  return Array.from(conf.keys()).sort().map((k) => k + \"=\" + conf.get(k));\n}",
  tests: [['parseIni(["b=2","a=1"])', '["a=1","b=2"]'],
    ['parseIni(["# comment","a=1"])', '["a=1"]'],
    ['parseIni(["a=1","a=2"])', '["a=2"]'],
    ['parseIni(["  a  =  1  "])', '["a=1"]']],
  edge: [['parseIni([])', "[]"], ['parseIni(["no equals here"])', "[]"]],
  ex: "<code>sshd_config</code>·<code>my.cnf</code> 같은 설정 파일이 이 형식입니다. 파서가 단순해 보여도 <b>규칙을 정확히 아는 것</b>이 중요합니다.\n세 번째 테스트가 실무에서 가장 자주 물어보는 질문입니다 — 같은 키가 두 번 있으면 어느 쪽이 이기는가. 여기서는 마지막이지만, <b>sshd 는 첫 번째가 이깁니다.</b> 설정을 파일 끝에 덧붙였는데 반영되지 않는 유명한 함정이 여기서 나옵니다.\n값에 <code>=</code> 가 들어갈 수 있으므로 <code>split(\"=\")</code> 이 아니라 <b>첫 번째 위치에서만</b> 잘라야 합니다. 비밀번호나 URL 이 값이면 실제로 문제가 됩니다.\n형식에 맞지 않는 줄을 조용히 건너뛰는 것이 항상 옳지는 않습니다. 오타 난 설정 줄이 무시되어 '분명 적었는데 안 먹는다' 가 되므로, 실제 도구는 경고를 남기는 편이 낫습니다." },

{ track: "linux", k: "심볼릭 링크를 따라간다 · resolveLink", cat: "debug",
  q: "<code>{경로: 가리키는곳}</code> 링크 지도에서 최종 목적지를 돌려주세요. 링크가 아닌 경로는 그대로 돌려주고, <b>순환이 있으면</b> <code>null</code> 입니다.",
  src: "function resolveLink(links, path) {\n  // TODO: 따라가되 이미 지나온 곳을 기억하세요\n  return path;\n}",
  sol: "function resolveLink(links, path) {\n  const seen = new Set();\n  let cur = path;\n  while (Object.prototype.hasOwnProperty.call(links, cur)) {\n    if (seen.has(cur)) return null;\n    seen.add(cur);\n    cur = links[cur];\n  }\n  return cur;\n}",
  tests: [['resolveLink({"/a":"/b"}, "/a")', '"/b"'],
    ['resolveLink({"/a":"/b","/b":"/c"}, "/a")', '"/c"'],
    ['resolveLink({"/a":"/b","/b":"/a"}, "/a")', "null"],
    ['resolveLink({}, "/x")', '"/x"']],
  edge: [['resolveLink({"/a":"/a"}, "/a")', "null"], ['resolveLink({"/a":"/b"}, "/z")', '"/z"']],
  ex: "<code>realpath</code> 가 하는 일입니다. 링크가 링크를 가리킬 수 있으므로 <b>더 이상 링크가 아닐 때까지</b> 따라갑니다.\n<b>순환 검사</b>가 없으면 세 번째 테스트에서 영원히 돕니다. 실제 커널도 이런 순환을 막기 위해 따라가는 횟수에 상한(보통 40)을 두고, 넘으면 <code>ELOOP</code> 오류를 냅니다.\n배포에서 <code>current -> releases/2024-01-05</code> 처럼 링크만 바꿔 전환하는 방식이 널리 쓰입니다. <b>전환이 원자적</b>이고 롤백도 링크를 되돌리는 것으로 끝나기 때문입니다.\n주의할 점은 <b>상대 경로 링크</b>입니다. 링크가 가리키는 값이 상대 경로면 그 링크가 있는 위치를 기준으로 풀어야 하는데, 이것을 빠뜨리면 옮긴 뒤에 조용히 깨집니다." },

{ track: "linux", k: "명령 실행 시간을 재 본다 · slowest", cat: "ops",
  q: "<code>{cmd, ms}</code> 목록에서 <b>느린 순서</b>로 <code>\"명령 ms\"</code> 배열을 <code>n</code> 개까지 돌려주세요. 시간이 같으면 명령 이름 사전순입니다.",
  src: "function slowest(runs, n) {\n  // TODO: 정렬 기준을 두 단계로 두세요\n  return [];\n}",
  sol: "function slowest(runs, n) {\n  return runs.slice()\n    .sort((a, b) => (b.ms - a.ms) || (a.cmd < b.cmd ? -1 : a.cmd > b.cmd ? 1 : 0))\n    .slice(0, n)\n    .map((r) => r.cmd + \" \" + r.ms);\n}",
  tests: [['slowest([{cmd:"a",ms:10},{cmd:"b",ms:30}], 1)', '["b 30"]'],
    ['slowest([{cmd:"b",ms:5},{cmd:"a",ms:5}], 2)', '["a 5","b 5"]'],
    ['slowest([{cmd:"a",ms:1}], 5)', '["a 1"]'],
    ['slowest([{cmd:"x",ms:2},{cmd:"y",ms:9},{cmd:"z",ms:4}], 2)', '["y 9","z 4"]']],
  edge: [['slowest([], 3)', "[]"], ['slowest([{cmd:"a",ms:1}], 0)', "[]"]],
  ex: "느린 것을 찾는 일은 <b>재는 것에서 시작합니다.</b> 짐작으로 최적화하면 엉뚱한 곳을 고치고, 효과가 있었는지도 알 수 없습니다.\n<code>slice()</code> 로 사본을 만들어 정렬한 것에 이유가 있습니다. <code>sort</code> 는 <b>원본 배열을 제자리에서</b> 바꾸므로, 호출한 쪽이 들고 있던 순서가 조용히 망가집니다.\n두 단계 정렬을 <code>||</code> 로 잇는 것이 자바스크립트의 관용구입니다. 앞 비교가 0(같음)일 때만 뒤 비교로 넘어갑니다.\n실무에서는 평균보다 <b>p95·p99</b> 를 봅니다. 평균은 소수의 아주 느린 요청을 감추는데, 사용자가 이탈하는 것은 바로 그 소수의 경험 때문입니다." }

];
