/* Linux 실행형 2 — 텍스트 도구와 관측 값을 손으로 만들어 본다.
   awk/sort/uniq 가 하는 집계, 프로세스 상태와 부하, 시그널과 종료,
   네트워크 상태와 아카이브. 첫 실행형 유닛과 겹치지 않는 함수만 다룬다. */
module.exports = [

/* ───────────── 텍스트 도구가 하는 계산 ───────────── */
{ track: "linux", k: "칸을 골라 뽑는다 · cutFields", cat: "internals",
  q: "구분자로 나뉜 한 줄에서 <b>1부터 세는</b> 칸 번호 목록에 해당하는 값만 골라 배열로 돌려주세요. 범위를 벗어난 번호는 건너뜁니다.",
  src: "function cutFields(line, sep, cols) {\n  // TODO: sep 으로 쪼갠 뒤 1부터 세는 번호로 고르세요\n  return [];\n}",
  sol: "function cutFields(line, sep, cols) {\n  const f = String(line).split(sep);\n  const out = [];\n  cols.forEach((c) => { if (c >= 1 && c <= f.length) out.push(f[c - 1]); });\n  return out;\n}",
  tests: [['cutFields("a:b:c:d", ":", [1,3])', '["a","c"]'],
    ['cutFields("a:b:c", ":", [3,1])', '["c","a"]'],
    ['cutFields("a:b", ":", [5])', '[]'],
    ['cutFields("root:x:0:0", ":", [1,3,4])', '["root","0","0"]']],
  edge: [['cutFields("solo", ":", [1])', '["solo"]'], ['cutFields("a,b", ",", [2,2])', '["b","b"]']],
  ex: "<code>cut -d: -f1,3</code> 이 하는 일입니다. 칸 번호를 <b>1부터</b> 세는 것이 유닉스 도구들의 공통 약속이라, 배열 첨자로 바꿀 때 하나를 빼야 합니다.\n번호 순서를 그대로 따르는 것은 이 구현의 선택입니다. 진짜 <code>cut</code> 은 <b>언제나 왼쪽부터</b> 내보내서 <code>-f3,1</code> 을 써도 1번이 먼저 나옵니다. 도구의 동작을 안다고 생각했다가 이런 자리에서 어긋납니다.\n<code>/etc/passwd</code> 를 읽는 것이 전형적인 쓰임입니다. 콜론으로 나뉜 일곱 칸에 이름·UID·GID·홈·셸이 들어 있어, 칸 번호만 알면 원하는 것을 뽑아낼 수 있습니다.\n구분자가 <b>연속으로 나오면</b> 빈 칸이 생깁니다. 공백으로 나뉜 표를 <code>cut</code> 으로 다루기 어려운 이유가 이것이라, 그럴 때는 연속 공백을 하나로 보는 <code>awk</code> 를 씁니다." },

{ track: "linux", k: "칸을 기준으로 정렬한다 · sortByField", cat: "internals",
  q: "줄 목록을 <b>지정한 칸의 숫자</b> 기준으로 오름차순 정렬해 돌려주세요. 값이 같으면 원래 순서를 지킵니다.",
  src: "function sortByField(lines, sep, col) {\n  // TODO: 칸 값을 숫자로 바꿔 견주세요\n  return lines;\n}",
  sol: "function sortByField(lines, sep, col) {\n  const keyed = lines.map((s, i) => [Number(String(s).split(sep)[col - 1]), i, s]);\n  keyed.sort((a, b) => (a[0] - b[0]) || (a[1] - b[1]));\n  return keyed.map((x) => x[2]);\n}",
  tests: [['sortByField(["a 30","b 4","c 100"], " ", 2)', '["b 4","a 30","c 100"]'],
    ['sortByField(["x:2","y:1"], ":", 2)', '["y:1","x:2"]'],
    ['sortByField(["a 5","b 5","c 1"], " ", 2)', '["c 1","a 5","b 5"]'],
    ['sortByField([], " ", 1)', '[]']],
  edge: [['sortByField(["only 7"], " ", 2)', '["only 7"]'], ['sortByField(["a 0","b -1"], " ", 2)', '["b -1","a 0"]']],
  ex: "<code>sort -t' ' -k2 -n</code> 입니다. <code>-n</code> 이 없으면 <b>글자 순서</b>로 정렬되어 <code>100</code> 이 <code>30</code> 보다 앞에 옵니다 — 로그를 크기순으로 본다고 믿었는데 아닌 경우의 대부분이 이 실수입니다.\n값이 같을 때 원래 순서를 지키는 것을 <b>안정 정렬</b>이라 합니다. 두 번 정렬해 두 기준을 겹쳐 쓸 수 있게 해 주는 성질이라, 먼저 이름으로 정렬하고 다시 크기로 정렬하면 크기가 같은 것끼리는 이름순이 됩니다.\n원래 자리를 함께 담아 견주는 것은 안정성을 보장하는 고전적인 방법입니다. 언어가 안정 정렬을 약속하지 않을 때도 안전합니다.\n실무에서는 <code>du -h | sort -h</code> 처럼 <b>사람이 읽는 단위</b>를 정렬해야 할 때가 많습니다. <code>-h</code> 없이 정렬하면 <code>9K</code> 가 <code>1G</code> 보다 크게 잡힙니다." },

{ track: "linux", k: "같은 줄을 세어 접는다 · countLines", cat: "logs",
  q: "줄 목록에서 같은 줄이 몇 번 나왔는지 세어 <code>[개수, 줄]</code> 쌍의 배열로 돌려주세요. 개수 내림차순, 같으면 처음 나온 순서입니다.",
  src: "function countLines(lines) {\n  // TODO: 세고 나서 개수로 정렬하세요\n  return [];\n}",
  sol: "function countLines(lines) {\n  const n = new Map(), first = new Map();\n  lines.forEach((s, i) => {\n    n.set(s, (n.get(s) || 0) + 1);\n    if (!first.has(s)) first.set(s, i);\n  });\n  return [...n.keys()].sort((a, b) => (n.get(b) - n.get(a)) || (first.get(a) - first.get(b)))\n    .map((s) => [n.get(s), s]);\n}",
  tests: [['countLines(["a","b","a"])', '[[2,"a"],[1,"b"]]'],
    ['countLines(["x","x","x"])', '[[3,"x"]]'],
    ['countLines(["p","q"])', '[[1,"p"],[1,"q"]]'],
    ['countLines([])', '[]']],
  edge: [['countLines(["z"])', '[[1,"z"]]'], ['countLines(["b","a","b","a"])', '[[2,"b"],[2,"a"]]']],
  ex: "<code>sort | uniq -c | sort -rn</code> 은 로그를 다룰 때 가장 자주 쓰는 한 줄입니다. 어떤 오류가 <b>가장 많이</b> 났는지를 바로 보여 줍니다.\n<code>uniq</code> 는 <b>붙어 있는</b> 같은 줄만 접는다는 함정이 있습니다. 앞에 <code>sort</code> 를 붙이지 않으면 흩어져 있는 같은 줄이 각각 1로 세어져, 결과가 조용히 틀립니다.\n여기서는 Map 으로 세므로 정렬이 필요 없습니다. 대신 <b>처음 나온 자리</b>를 함께 기억해서 개수가 같을 때의 순서를 정해 두었습니다. 순서가 정해지지 않으면 같은 입력에 다른 답이 나올 수 있습니다.\n로그가 아주 클 때는 전체를 정렬하는 비용이 문제가 됩니다. 그래서 해시로 세는 방식이 실제 도구에서도 더 빠른 선택이 됩니다." },

{ track: "linux", k: "칸별로 합을 낸다 · sumBy", cat: "logs",
  q: "<code>[열쇠, 숫자]</code> 쌍의 배열에서 열쇠별 합을 구해, 합이 큰 순서로 <code>[열쇠, 합]</code> 배열을 돌려주세요. 합이 같으면 열쇠의 사전순입니다.",
  src: "function sumBy(rows) {\n  // TODO: 열쇠별로 더한 뒤 정렬하세요\n  return [];\n}",
  sol: "function sumBy(rows) {\n  const m = new Map();\n  rows.forEach((r) => m.set(r[0], (m.get(r[0]) || 0) + Number(r[1])));\n  return [...m.keys()].sort((a, b) => (m.get(b) - m.get(a)) || (a < b ? -1 : a > b ? 1 : 0))\n    .map((k) => [k, m.get(k)]);\n}",
  tests: [['sumBy([["a",1],["b",5],["a",2]])', '[["b",5],["a",3]]'],
    ['sumBy([["x",10]])', '[["x",10]]'],
    ['sumBy([["a",1],["b",1]])', '[["a",1],["b",1]]'],
    ['sumBy([])', '[]']],
  edge: [['sumBy([["a",-1],["a",1]])', '[["a",0]]'], ['sumBy([["z",2],["y",2]])', '[["y",2],["z",2]]']],
  ex: "<code>awk '{s[$1]+=$2} END{for(k in s) print k, s[k]}'</code> 을 코드로 옮긴 것입니다. awk 의 연관 배열은 선언 없이 쓰면 <b>0에서 시작</b>하므로 한 줄로 집계가 됩니다.\n대역폭을 IP 별로 더하거나, 응답 시간을 경로별로 더하는 일이 전부 이 모양입니다. 로그 한 줄이 <code>[열쇠, 값]</code> 으로 줄어들면 나머지는 같은 계산입니다.\nawk 의 <code>for(k in s)</code> 는 <b>순서를 약속하지 않습니다</b>. 그래서 실제로는 뒤에 <code>sort</code> 를 파이프로 붙이는데, 여기서 정렬 규칙을 못 박아 둔 이유도 같습니다.\n합이 같을 때 사전순으로 정한 것은 취향이 아니라 <b>재현성</b>을 위한 것입니다. 같은 입력에 언제나 같은 출력이 나와야 그 결과를 테스트에 쓸 수 있습니다." },

{ track: "linux", k: "바꾼 자리를 센다 · sedReplace", cat: "internals",
  q: "한 줄에서 찾을 문자열을 바꿀 문자열로 치환하고 <code>[바뀐 줄, 바꾼 횟수]</code> 를 돌려주세요. <code>all</code> 이 거짓이면 <b>맨 처음 하나만</b> 바꿉니다.",
  src: "function sedReplace(line, from, to, all) {\n  // TODO: 처음 하나만 바꿀지 전부 바꿀지 나누세요\n  return [line, 0];\n}",
  sol: "function sedReplace(line, from, to, all) {\n  const s = String(line);\n  const at = s.indexOf(from);\n  if (at < 0 || from === \"\") return [s, 0];\n  if (!all) return [s.slice(0, at) + to + s.slice(at + from.length), 1];\n  const bits = s.split(from);\n  return [bits.join(to), bits.length - 1];\n}",
  tests: [['sedReplace("a-b-c", "-", "+", false)', '["a+b-c",1]'],
    ['sedReplace("a-b-c", "-", "+", true)', '["a+b+c",2]'],
    ['sedReplace("abc", "z", "y", true)', '["abc",0]'],
    ['sedReplace("aaa", "a", "b", true)', '["bbb",3]']],
  edge: [['sedReplace("", "a", "b", true)', '["",0]'], ['sedReplace("ab", "", "x", true)', '["ab",0]']],
  ex: "<code>sed 's/a/b/'</code> 와 <code>sed 's/a/b/g'</code> 의 차이입니다. <code>g</code> 가 없으면 <b>줄마다 첫 번째 하나만</b> 바뀌는데, 이것을 모르고 쓴 치환은 대부분 조용히 절반만 됩니다.\n바꾼 횟수를 함께 돌려주는 것이 중요합니다. 0 이 나왔다면 <b>찾는 문자열이 없었다</b>는 뜻이라, 정규식이 틀렸거나 파일이 이미 바뀐 것입니다. 횟수를 안 보면 '했는데 안 됐다' 를 알 수 없습니다.\n빈 문자열을 찾으라는 요청을 <b>0건으로 잘라 낸 것</b>은 방어입니다. 빈 문자열은 모든 자리에 있어서 그대로 두면 무한히 끼워 넣게 됩니다.\n실무에서 <code>sed -i</code> 로 파일을 직접 고칠 때는 먼저 <code>-i</code> 없이 돌려 결과를 눈으로 봅니다. 되돌릴 수 없는 명령은 언제나 예행연습을 먼저 합니다." },

/* ───────────── 프로세스와 부하 ───────────── */
{ track: "linux", k: "부하 평균을 읽는다 · loadVerdictPct", cat: "ops",
  q: "1분 부하 평균과 코어 수로 <b>코어당 부하를 백분율</b>(반올림)로 구해 돌려주세요. 코어 수가 0 이하면 <code>-1</code> 을 돌려줍니다.",
  src: "function loadVerdictPct(load1, cores) {\n  // TODO: 코어로 나눈 뒤 백분율로 바꾸세요\n  return 0;\n}",
  sol: "function loadVerdictPct(load1, cores) {\n  if (!(cores > 0)) return -1;\n  return Math.round((load1 / cores) * 100);\n}",
  tests: [['loadVerdictPct(4, 4)', '100'],
    ['loadVerdictPct(2, 4)', '50'],
    ['loadVerdictPct(8, 4)', '200'],
    ['loadVerdictPct(1, 0)', '-1']],
  edge: [['loadVerdictPct(0, 8)', '0'], ['loadVerdictPct(3, 8)', '38']],
  ex: "부하 평균 <code>4.0</code> 은 그 자체로는 아무 뜻이 없습니다. <b>코어 수로 나눠야</b> 비로소 '꽉 찼다' 인지 '반만 쓴다' 인지 알 수 있습니다.\n부하 평균은 CPU 사용률이 아니라 <b>실행 대기 중인 작업 수</b>입니다. 그래서 디스크를 기다리는 프로세스도 여기에 잡혀, CPU 는 놀고 있는데 부하가 높은 상황이 생깁니다. 그럴 때는 <code>iostat</code> 을 봐야 합니다.\n100% 를 넘었다고 곧바로 문제는 아닙니다. 짧게 넘는 것은 정상이고, <b>1분·5분·15분</b> 세 값을 함께 보아 늘어나는 추세인지 줄어드는 추세인지를 봅니다.\n컨테이너에서는 함정이 하나 더 있습니다. 부하 평균은 <b>호스트 전체</b>의 값이라, 컨테이너에 할당된 CPU 로 나누면 엉뚱한 숫자가 나옵니다." },

{ track: "linux", k: "프로세스 상태 글자 · procState", cat: "internals",
  q: "<code>ps</code> 의 상태 글자 하나를 받아 뜻을 문자열로 돌려주세요. <code>R</code>=실행, <code>S</code>=대기, <code>D</code>=중단불가, <code>Z</code>=좀비, <code>T</code>=정지, 그 밖은 <code>\"unknown\"</code> 입니다.",
  src: "function procState(ch) {\n  // TODO: 글자를 뜻으로 옮기세요\n  return \"unknown\";\n}",
  sol: "function procState(ch) {\n  const map = { R: \"running\", S: \"sleeping\", D: \"uninterruptible\",\n                Z: \"zombie\", T: \"stopped\" };\n  return map[String(ch).charAt(0)] || \"unknown\";\n}",
  tests: [['procState("R")', '"running"'],
    ['procState("Z")', '"zombie"'],
    ['procState("D")', '"uninterruptible"'],
    ['procState("Q")', '"unknown"']],
  edge: [['procState("")', '"unknown"'], ['procState("S+")', '"sleeping"']],
  ex: "<code>ps aux</code> 의 STAT 칸을 읽는 일입니다. 대부분의 프로세스는 <code>S</code> — 무언가를 <b>기다리는 중</b>이고, 이것이 정상입니다.\n<code>D</code> 상태가 위험 신호입니다. <b>시그널로도 깨울 수 없는</b> 상태라 <code>kill -9</code> 조차 듣지 않고, 대개 디스크나 네트워크 파일 시스템이 응답하지 않는다는 뜻입니다. 프로세스를 죽이려 애쓸 것이 아니라 저장 장치를 봐야 합니다.\n<code>Z</code>(좀비)는 이미 끝난 프로세스가 <b>부모가 종료 코드를 거둬 가기를</b> 기다리는 상태입니다. 좀비 자체는 자원을 거의 쓰지 않지만, 쌓인다면 부모가 제 일을 안 하고 있다는 뜻입니다.\nSTAT 뒤에 붙는 글자도 뜻이 있습니다 — <code>+</code> 는 포그라운드, <code>s</code> 는 세션 리더, <code>l</code> 은 멀티스레드입니다. 그래서 첫 글자만 떼어 읽습니다." },

{ track: "linux", k: "고아를 다시 붙인다 · reparent", cat: "internals",
  q: "<code>[pid, ppid]</code> 목록에서 지정한 pid 가 죽었을 때, 그 자식들의 새 부모 pid 를 담은 배열을 돌려주세요. 고아는 <code>1</code> 번이 거둡니다. 자식은 pid 오름차순입니다.",
  src: "function reparent(procs, dead) {\n  // TODO: 죽은 프로세스의 자식을 찾아 1로 옮기세요\n  return [];\n}",
  sol: "function reparent(procs, dead) {\n  return procs.filter((p) => p[1] === dead)\n    .map((p) => p[0]).sort((a, b) => a - b)\n    .map((pid) => [pid, 1]);\n}",
  tests: [['reparent([[2,1],[3,2],[4,2]], 2)', '[[3,1],[4,1]]'],
    ['reparent([[2,1],[3,2]], 3)', '[]'],
    ['reparent([[9,5],[7,5]], 5)', '[[7,1],[9,1]]'],
    ['reparent([], 1)', '[]']],
  edge: [['reparent([[2,1]], 1)', '[[2,1]]'], ['reparent([[5,4]], 4)', '[[5,1]]']],
  ex: "부모가 먼저 죽으면 자식은 사라지지 않고 <b>init(pid 1)</b> 이 거둡니다. 그래서 터미널을 닫아도 <code>nohup</code> 으로 띄운 것이 계속 도는 것입니다.\n이 규칙이 없으면 좀비를 거둘 사람이 없어집니다. pid 1 은 자식이 끝날 때마다 종료 코드를 거둬 가는 일을 하고, 그래서 컨테이너에서 <b>pid 1 이 그 일을 안 하는 프로그램</b>이면 좀비가 쌓입니다.\n컨테이너의 전형적인 실수가 여기 있습니다. 셸 스크립트를 pid 1 로 띄우면 시그널도 전달하지 않고 자식도 거두지 않아, <code>docker stop</code> 이 10초를 기다렸다 강제 종료하게 됩니다. <code>--init</code> 이나 <code>exec</code> 로 해결합니다.\n최근 리눅스에는 중간 조상을 지정하는 방법도 있습니다. 그러면 pid 1 이 아니라 지정된 프로세스가 고아를 거둬, 프로세스 감독자가 자기 자손을 계속 관리할 수 있습니다." },

{ track: "linux", k: "시그널 번호와 뜻 · signalOf", cat: "ops",
  q: "시그널 이름을 받아 <code>[번호, 잡을 수 있는가]</code> 를 돌려주세요. <code>TERM</code>=15, <code>KILL</code>=9, <code>INT</code>=2, <code>HUP</code>=1 이고, <code>KILL</code> 만 잡을 수 없습니다. 모르는 이름은 <code>[-1, false]</code> 입니다.",
  src: "function signalOf(name) {\n  // TODO: 이름을 번호로 옮기고 잡을 수 있는지 표시하세요\n  return [-1, false];\n}",
  sol: "function signalOf(name) {\n  const num = { HUP: 1, INT: 2, KILL: 9, TERM: 15 };\n  const n = num[String(name).toUpperCase().replace(/^SIG/, \"\")];\n  if (n === undefined) return [-1, false];\n  return [n, n !== 9];\n}",
  tests: [['signalOf("TERM")', '[15,true]'],
    ['signalOf("KILL")', '[9,false]'],
    ['signalOf("SIGINT")', '[2,true]'],
    ['signalOf("USR1")', '[-1,false]']],
  edge: [['signalOf("hup")', '[1,true]'], ['signalOf("")', '[-1,false]']],
  ex: "<code>kill</code> 은 이름과 달리 <b>시그널을 보내는</b> 명령입니다. 기본값이 <code>TERM</code>(15)이라 대부분의 프로그램은 이것을 받고 스스로 정리한 뒤 끝납니다.\n<code>KILL</code>(9)만 잡을 수 없는 것이 핵심입니다. 커널이 프로세스에게 알리지 않고 곧바로 없애 버리므로, <b>열린 파일을 닫거나 임시 파일을 지울 기회가 없습니다.</b> 그래서 <code>-9</code> 는 마지막 수단입니다.\n<code>INT</code>(2)는 Ctrl+C 이고, <code>HUP</code>(1)은 원래 '터미널 연결이 끊겼다' 는 뜻이었습니다. 지금은 관례적으로 <b>설정을 다시 읽으라</b>는 신호로 쓰여, 서버를 재시작하지 않고 설정만 갱신할 때 씁니다.\n<code>SIG</code> 접두사를 떼고 받는 것은 실용적인 선택입니다. <code>kill -TERM</code> 과 <code>kill -SIGTERM</code> 이 둘 다 통하는 것과 같습니다." },

{ track: "linux", k: "종료를 기다린다 · shutdownPlan", cat: "ops",
  q: "정리에 걸리는 시간과 기다려 주는 시간을 받아 <code>[\"graceful\", 걸린시간]</code> 또는 <code>[\"forced\", 기다린시간]</code> 을 돌려주세요. 정확히 같으면 정상 종료로 봅니다.",
  src: "function shutdownPlan(cleanupMs, graceMs) {\n  // TODO: 유예 안에 끝나는지 견주세요\n  return [\"forced\", graceMs];\n}",
  sol: "function shutdownPlan(cleanupMs, graceMs) {\n  if (cleanupMs <= graceMs) return [\"graceful\", cleanupMs];\n  return [\"forced\", graceMs];\n}",
  tests: [['shutdownPlan(2000, 10000)', '["graceful",2000]'],
    ['shutdownPlan(30000, 10000)', '["forced",10000]'],
    ['shutdownPlan(10000, 10000)', '["graceful",10000]'],
    ['shutdownPlan(0, 5000)', '["graceful",0]']],
  edge: [['shutdownPlan(1, 0)', '["forced",0]'], ['shutdownPlan(0, 0)', '["graceful",0]']],
  ex: "<code>systemctl stop</code> 이나 <code>docker stop</code> 이 하는 계산입니다. 먼저 <code>TERM</code> 을 보내고, <b>유예 시간이 지나도 안 끝나면</b> <code>KILL</code> 을 보냅니다.\n기본 유예가 10초인 곳이 많습니다. 처리 중인 요청이 그보다 오래 걸리는 서비스라면 배포할 때마다 요청이 잘려 나가는데, 사용자에게는 <b>가끔 나는 오류</b>로만 보여 원인을 찾기 어렵습니다.\n반대로 유예를 아주 길게 잡는 것도 답이 아닙니다. 정말로 멈춰 버린 프로세스를 그만큼 기다리게 되어 배포가 느려집니다. <b>실제 정리 시간을 재서</b> 거기에 여유를 더하는 것이 맞습니다.\n정리 시간이 유예와 정확히 같을 때를 정상으로 본 것은 경계값 선택입니다. 이런 자리를 문서에 적어 두지 않으면 구현마다 달라져, 아슬아슬한 상황에서 재현되지 않는 차이가 생깁니다." },

/* ───────────── 파일 시스템과 아카이브 ───────────── */
{ track: "linux", k: "사람이 읽는 크기 · humanSize", cat: "internals",
  q: "바이트 수를 <code>1024</code> 기준으로 줄여 <code>\"1.5K\"</code> 처럼 돌려주세요. 소수 첫째 자리까지 쓰되 <b>정수면 소수점을 붙이지 않습니다.</b> 단위는 B·K·M·G 입니다.",
  src: "function humanSize(bytes) {\n  // TODO: 1024 로 나누며 단위를 올리세요\n  return \"0B\";\n}",
  sol: "function humanSize(bytes) {\n  const unit = [\"B\", \"K\", \"M\", \"G\"];\n  let n = Number(bytes), i = 0;\n  while (n >= 1024 && i < 3) { n = n / 1024; i++; }\n  const r = Math.round(n * 10) / 10;\n  return (Number.isInteger(r) ? String(r) : r.toFixed(1)) + unit[i];\n}",
  tests: [['humanSize(512)', '"512B"'],
    ['humanSize(1536)', '"1.5K"'],
    ['humanSize(1048576)', '"1M"'],
    ['humanSize(0)', '"0B"']],
  edge: [['humanSize(1023)', '"1023B"'], ['humanSize(1073741824)', '"1G"']],
  ex: "<code>ls -lh</code>·<code>du -h</code> 가 보여 주는 값입니다. 사람이 읽기 좋게 줄이는 대신 <b>정확한 값을 잃습니다</b> — <code>1.5K</code> 는 1536 일 수도, 1540 일 수도 있습니다.\n그래서 크기를 견주거나 더해야 할 때는 <b>줄이기 전의 바이트</b>로 해야 합니다. 사람이 읽는 값끼리 더하면 반올림 오차가 쌓입니다.\n1024 냐 1000 이냐는 오래된 다툼입니다. <code>-h</code> 는 1024, <code>--si</code> 는 1000 을 쓰고, 디스크 제조사는 1000 을 씁니다. 1TB 짜리를 샀는데 931GB 로 보이는 이유가 이 차이입니다.\n정수일 때 소수점을 떼는 것은 눈에 띄지 않지만 중요한 선택입니다. <code>1.0M</code> 보다 <code>1M</code> 이 읽기 쉽고, 실제 도구들도 그렇게 합니다." },

{ track: "linux", k: "가장 큰 것부터 · topFiles", cat: "ops",
  q: "<code>[경로, 바이트]</code> 목록에서 큰 것부터 <code>n</code> 개의 <b>경로만</b> 배열로 돌려주세요. 크기가 같으면 경로 사전순입니다.",
  src: "function topFiles(files, n) {\n  // TODO: 크기 내림차순으로 정렬한 뒤 잘라내세요\n  return [];\n}",
  sol: "function topFiles(files, n) {\n  return files.slice()\n    .sort((a, b) => (b[1] - a[1]) || (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0))\n    .slice(0, Math.max(n, 0))\n    .map((f) => f[0]);\n}",
  tests: [['topFiles([["a",10],["b",50],["c",20]], 2)', '["b","c"]'],
    ['topFiles([["x",1]], 5)', '["x"]'],
    ['topFiles([["a",5],["b",5]], 2)', '["a","b"]'],
    ['topFiles([["a",1]], 0)', '[]']],
  edge: [['topFiles([], 3)', '[]'], ['topFiles([["z",9],["y",9]], 1)', '["y"]']],
  ex: "디스크가 찼을 때 가장 먼저 하는 일입니다. <code>du -a | sort -rn | head</code> 로 <b>범인 몇 개</b>를 찾으면 대개 그것으로 끝납니다.\n원본 배열을 <code>slice()</code> 로 복사한 뒤 정렬하는 것에 이유가 있습니다. <code>sort</code> 는 <b>원본을 그 자리에서 바꾸므로</b>, 넘겨받은 배열을 정렬하면 부르는 쪽의 순서까지 바뀌어 버립니다. 남의 데이터를 조용히 고치는 함수는 나중에 반드시 문제를 일으킵니다.\n<code>n</code> 이 목록보다 클 때 알아서 짧게 돌려주는 것은 <code>slice</code> 의 성질입니다. 따로 검사할 필요가 없어 코드가 짧아집니다.\n실무에서 한 가지 더 봐야 할 것이 있습니다 — 지웠는데 공간이 안 돌아오면, <b>지운 파일을 아직 열고 있는 프로세스</b>가 있는 것입니다. <code>lsof +L1</code> 로 찾아 그 프로세스를 재시작해야 합니다." },

{ track: "linux", k: "아카이브에서 꺼낼 것 · tarSelect", cat: "internals",
  q: "아카이브 안 경로 목록에서 지정한 접두사로 시작하는 것만 골라 <b>원래 순서대로</b> 돌려주세요. 접두사가 빈 문자열이면 전부 고릅니다.",
  src: "function tarSelect(paths, prefix) {\n  // TODO: 접두사로 시작하는지 보세요\n  return [];\n}",
  sol: "function tarSelect(paths, prefix) {\n  if (!prefix) return paths.slice();\n  return paths.filter((p) => String(p).indexOf(prefix) === 0);\n}",
  tests: [['tarSelect(["src/a.js","doc/b.md","src/c.js"], "src/")', '["src/a.js","src/c.js"]'],
    ['tarSelect(["a","b"], "")', '["a","b"]'],
    ['tarSelect(["x/y"], "z")', '[]'],
    ['tarSelect(["src/a","srcx/b"], "src/")', '["src/a"]']],
  edge: [['tarSelect([], "s")', '[]'], ['tarSelect(["a/b/c"], "a/b")', '["a/b/c"]']],
  ex: "<code>tar -xf backup.tar src/</code> 가 하는 고르기입니다. 통째로 풀지 않고 <b>필요한 가지만</b> 꺼내면 시간과 공간을 아낍니다.\n접두사 비교의 함정이 시험에 들어 있습니다 — <code>src/</code> 로 걸러야 <code>srcx/</code> 가 딸려 오지 않습니다. 슬래시를 빼먹으면 이름이 비슷한 폴더가 조용히 섞입니다.\n아카이브를 풀 때 가장 위험한 것은 <b>절대 경로나 <code>..</code> 가 든 항목</b>입니다. 남이 만든 아카이브를 그대로 풀면 시스템 파일을 덮어쓸 수 있어, 요즘 <code>tar</code> 는 기본으로 이런 항목을 잘라 냅니다.\n그래서 아카이브를 풀기 전에는 언제나 <code>tar -tf</code> 로 <b>목록만 먼저 봅니다</b>. 이 함수가 하는 일이 정확히 그 목록 보기의 절반입니다." },

{ track: "linux", k: "찾을 것을 좁힌다 · findMatch", cat: "ops",
  q: "<code>[경로, 바이트, 수정일]</code> 목록에서 <b>최소 크기 이상</b>이고 <b>기준일보다 오래된</b> 것만 골라 경로 배열로 돌려주세요. 순서는 그대로입니다.",
  src: "function findMatch(files, minSize, olderThan) {\n  // TODO: 두 조건을 모두 만족하는 것만 고르세요\n  return [];\n}",
  sol: "function findMatch(files, minSize, olderThan) {\n  return files.filter((f) => f[1] >= minSize && f[2] < olderThan)\n    .map((f) => f[0]);\n}",
  tests: [['findMatch([["a",100,5],["b",10,5],["c",100,50]], 50, 10)', '["a"]'],
    ['findMatch([["a",100,5]], 100, 10)', '["a"]'],
    ['findMatch([["a",100,10]], 50, 10)', '[]'],
    ['findMatch([], 0, 100)', '[]']],
  edge: [['findMatch([["a",0,0]], 0, 1)', '["a"]'], ['findMatch([["a",5,1],["b",6,1]], 6, 2)', '["b"]']],
  ex: "<code>find . -size +50k -mtime +7</code> 를 코드로 옮긴 것입니다. 로그 정리 작업이 대개 이 모양이라, <b>조건 두 개로 지울 것을 좁히고</b> 나머지는 손대지 않습니다.\n경계가 어느 쪽에 붙는지가 중요합니다. 여기서는 크기는 <b>이상</b>, 날짜는 <b>미만</b>으로 잡았습니다. 진짜 <code>find</code> 의 <code>+7</code> 은 '7일보다 오래된' 이라 오늘 것은 안 잡히는데, 이 미묘함 때문에 하루치가 남거나 하루치가 더 지워집니다.\n지우는 작업에서는 <b>먼저 목록만 뽑아 눈으로 봅니다.</b> <code>find ... -delete</code> 를 바로 쓰면 조건이 틀렸을 때 되돌릴 방법이 없습니다.\n<code>-mtime</code> 은 <b>내용이 바뀐</b> 시각입니다. 접근 시각(<code>-atime</code>)이나 상태 변경 시각(<code>-ctime</code>)과 다르므로, '안 쓰는 파일' 을 찾는다면서 <code>-mtime</code> 을 쓰면 자주 읽히는 파일까지 지웁니다." },

{ track: "linux", k: "링크는 몇 개인가 · linkCount", cat: "internals",
  q: "<code>[경로, inode]</code> 목록에서 지정한 경로와 <b>같은 inode</b> 를 가리키는 경로의 수를 돌려주세요. 자기 자신도 셉니다. 경로가 없으면 0 입니다.",
  src: "function linkCount(entries, path) {\n  // TODO: 그 경로의 inode 를 찾아 같은 것을 세세요\n  return 0;\n}",
  sol: "function linkCount(entries, path) {\n  const me = entries.filter((e) => e[0] === path)[0];\n  if (!me) return 0;\n  return entries.filter((e) => e[1] === me[1]).length;\n}",
  tests: [['linkCount([["a",7],["b",7],["c",9]], "a")', '2'],
    ['linkCount([["a",7],["b",7],["c",9]], "c")', '1'],
    ['linkCount([["a",1]], "zz")', '0'],
    ['linkCount([["a",3],["b",3],["c",3]], "b")', '3']],
  edge: [['linkCount([], "a")', '0'], ['linkCount([["a",0],["b",0]], "a")', '2']],
  ex: "<code>ls -l</code> 두 번째 칸의 숫자가 이 값입니다. 파일의 진짜 이름은 <b>inode 번호</b>이고, 경로는 거기 붙인 이름표라 여러 개일 수 있습니다.\n하드 링크가 <b>복사가 아니라 같은 파일</b>인 것이 여기서 드러납니다. 한쪽으로 고치면 다른 쪽도 바뀌고, 한쪽을 지워도 파일은 남습니다 — 링크 수가 0이 될 때 비로소 공간이 돌아옵니다.\n심볼릭 링크는 완전히 다른 것입니다. <b>경로 문자열을 담은 별개의 파일</b>이라 원본을 지우면 끊어진 링크가 되고, 파일 시스템을 넘어갈 수 있습니다. 하드 링크는 넘어갈 수 없습니다.\n지웠는데 공간이 안 돌아오는 두 번째 이유가 이것입니다. 다른 곳에 하드 링크가 남아 있으면 링크 수가 0이 아니라 파일이 살아 있습니다." },

/* ───────────── 네트워크와 서비스 ───────────── */
{ track: "linux", k: "포트를 쓰는 것 · portOwner", cat: "ops",
  q: "<code>[포트, 프로세스, 상태]</code> 목록에서 지정한 포트를 <code>\"LISTEN\"</code> 으로 잡고 있는 프로세스 이름을 돌려주세요. 없으면 빈 문자열입니다.",
  src: "function portOwner(socks, port) {\n  // TODO: 포트와 상태가 모두 맞는 것을 찾으세요\n  return \"\";\n}",
  sol: "function portOwner(socks, port) {\n  const found = socks.filter((s) => s[0] === port && s[2] === \"LISTEN\")[0];\n  return found ? found[1] : \"\";\n}",
  tests: [['portOwner([[80,"nginx","LISTEN"],[443,"nginx","LISTEN"]], 80)', '"nginx"'],
    ['portOwner([[3000,"node","ESTAB"]], 3000)', '""'],
    ['portOwner([[22,"sshd","LISTEN"]], 21)', '""'],
    ['portOwner([], 80)', '""']],
  edge: [['portOwner([[8080,"java","LISTEN"]], 8080)', '"java"'], ['portOwner([[80,"a","LISTEN"],[80,"b","LISTEN"]], 80)', '"a"']],
  ex: "<code>ss -ltnp</code> 로 하는 일입니다. '주소가 이미 사용 중' 오류를 만났을 때 <b>누가 쓰고 있는지</b>부터 찾는 것이 첫 단계입니다.\n상태를 함께 보는 것이 핵심입니다. 같은 포트 번호가 <code>ESTAB</code> 로도 잔뜩 보이는데 그것들은 <b>이미 맺어진 연결</b>이지 듣고 있는 소켓이 아닙니다. 상태를 안 보면 엉뚱한 프로세스를 죽이게 됩니다.\n포트가 비어 있는데도 못 여는 경우가 있습니다. <code>TIME_WAIT</code> 로 남아 있거나, 1024 미만 포트를 일반 사용자가 열려는 것입니다. 후자는 <b>권한</b> 문제라 프로세스를 찾아도 소용없습니다.\n<code>-p</code> 로 프로세스 이름을 보려면 대개 관리자 권한이 필요합니다. 남의 프로세스 정보는 커널이 알려 주지 않기 때문이라, 이름 칸이 비어 있으면 권한부터 의심합니다." },

{ track: "linux", k: "서비스를 다시 살릴까 · restartVerdict", cat: "ops",
  q: "종료 코드와 재시작 정책을 받아 다시 띄울지 참·거짓으로 돌려주세요. <code>\"always\"</code> 는 언제나, <code>\"on-failure\"</code> 는 코드가 0이 아닐 때, <code>\"no\"</code> 는 언제나 아닙니다.",
  src: "function restartVerdict(code, policy) {\n  // TODO: 정책마다 판단을 나누세요\n  return false;\n}",
  sol: "function restartVerdict(code, policy) {\n  if (policy === \"always\") return true;\n  if (policy === \"on-failure\") return code !== 0;\n  return false;\n}",
  tests: [['restartVerdict(0, "always")', 'true'],
    ['restartVerdict(0, "on-failure")', 'false'],
    ['restartVerdict(1, "on-failure")', 'true'],
    ['restartVerdict(1, "no")', 'false']],
  edge: [['restartVerdict(137, "on-failure")', 'true'], ['restartVerdict(0, "no")', 'false']],
  ex: "systemd 의 <code>Restart=</code> 설정이 하는 판단입니다. 한 줄짜리 규칙인데 <b>어떤 것을 고르느냐가 장애의 성격을 바꿉니다.</b>\n<code>always</code> 는 배치 작업에 위험합니다. 제 일을 마치고 정상 종료한 것도 다시 띄워, 같은 일을 끝없이 반복하게 됩니다. 한 번 돌고 끝나야 하는 것에는 <code>on-failure</code> 나 <code>no</code> 를 씁니다.\n<code>on-failure</code> 에도 함정이 있습니다. <b>설정 파일이 잘못돼서</b> 실패하는 것이면 다시 띄워도 똑같이 실패해, 재시작만 반복하며 로그를 채웁니다. 그래서 대개 <b>횟수 제한과 간격</b>을 함께 겁니다.\n종료 코드 137 은 128+9 — <b>KILL 로 죽었다</b>는 뜻입니다. 컨테이너에서 이 코드를 보면 대개 메모리 한도를 넘어 커널이 죽인 것이라, 재시작 정책이 아니라 메모리 설정을 봐야 합니다." },

{ track: "linux", k: "환경을 물려받는다 · mergeEnv", cat: "internals",
  q: "부모 환경 변수 객체와 덮어쓸 값의 목록을 받아, 정렬된 <code>\"KEY=VALUE\"</code> 문자열 배열로 돌려주세요. 값이 <code>null</code> 인 항목은 <b>지웁니다.</b>",
  src: "function mergeEnv(base, over) {\n  // TODO: 덮어쓰고 지운 뒤 정렬하세요\n  return [];\n}",
  sol: "function mergeEnv(base, over) {\n  const m = Object.assign({}, base);\n  Object.keys(over).forEach((k) => {\n    if (over[k] === null) delete m[k]; else m[k] = over[k];\n  });\n  return Object.keys(m).sort().map((k) => k + \"=\" + m[k]);\n}",
  tests: [['mergeEnv({A:"1"}, {B:"2"})', '["A=1","B=2"]'],
    ['mergeEnv({A:"1"}, {A:"9"})', '["A=9"]'],
    ['mergeEnv({A:"1",B:"2"}, {A:null})', '["B=2"]'],
    ['mergeEnv({}, {})', '[]']],
  edge: [['mergeEnv({Z:"1",A:"2"}, {})', '["A=2","Z=1"]'], ['mergeEnv({A:"1"}, {A:null,B:"3"})', '["B=3"]']],
  ex: "자식 프로세스를 띄울 때 커널이 넘겨 주는 것이 이 목록입니다. 환경 변수는 <b>부모에서 자식으로만</b> 흐르고, 자식이 바꾼 것은 부모에게 돌아가지 않습니다.\n'스크립트에서 <code>export</code> 했는데 셸에서 안 보인다' 의 답이 여기 있습니다. 스크립트는 자식 셸에서 돌므로 바뀐 환경이 함께 사라집니다. 지금 셸에 반영하려면 <code>source</code> 로 <b>같은 프로세스에서</b> 읽어야 합니다.\n지우는 것과 빈 값으로 두는 것은 다릅니다. <code>A=\"\"</code> 는 <b>있지만 빈 값</b>이라 프로그램이 '설정됨' 으로 판단할 수 있어, 정말 지우려면 <code>unset</code> 을 해야 합니다.\n정렬해서 내보내는 것은 <b>재현성</b> 때문입니다. 객체의 열쇠 순서에 기대면 같은 설정으로도 다른 결과가 나올 수 있어, 컨테이너 이미지 해시 같은 것이 흔들립니다." },

{ track: "linux", k: "느린 구간을 짚는다 · slowestHop", cat: "ops",
  q: "<code>[홉번호, 누적ms]</code> 목록에서 <b>앞 홉과의 차이가 가장 큰</b> 홉 번호를 돌려주세요. 첫 홉의 차이는 그 값 자체입니다. 같으면 앞선 홉을 고릅니다.",
  src: "function slowestHop(hops) {\n  // TODO: 앞 홉과의 차이를 견주세요\n  return 0;\n}",
  sol: "function slowestHop(hops) {\n  let best = 0, gap = -1, prev = 0;\n  hops.forEach((h) => {\n    const d = h[1] - prev;\n    if (d > gap) { gap = d; best = h[0]; }\n    prev = h[1];\n  });\n  return best;\n}",
  tests: [['slowestHop([[1,5],[2,10],[3,90]])', '3'],
    ['slowestHop([[1,50],[2,55]])', '1'],
    ['slowestHop([[1,10],[2,20],[3,30]])', '1'],
    ['slowestHop([])', '0']],
  edge: [['slowestHop([[1,3]])', '1'], ['slowestHop([[1,1],[2,100],[3,101]])', '2']],
  ex: "<code>traceroute</code> 결과를 읽는 방법입니다. 각 줄의 숫자는 <b>누적</b>이라 그 자체로는 뜻이 적고, <b>앞 홉과의 차이</b>가 그 구간에서 든 시간입니다.\n뒤로 갈수록 값이 커지는 것은 정상입니다. 문제는 <b>갑자기 뛰는 자리</b>이고, 거기가 대개 다른 통신사로 넘어가는 지점이거나 대륙을 건너는 구간입니다.\n중간 홉의 값이 크다고 그 라우터가 느린 것은 아닙니다. 라우터는 <b>지나가는 패킷을 처리하는 일을 우선</b>하고 자기에게 온 응답은 뒤로 미루므로, 중간에 튀었다가 다음 홉에서 다시 낮아지는 것은 무시해도 됩니다.\n그래서 진짜 신호는 <b>튄 값이 끝까지 이어지는 것</b>입니다. 어느 홉부터 커진 값이 마지막까지 유지된다면 거기가 실제 병목입니다." },

{ track: "linux", k: "동시 접속을 센다 · peakConnections", cat: "ops",
  q: "<code>[시작, 끝]</code> 시각 목록에서 <b>가장 많이 겹친 순간의 개수</b>를 돌려주세요. 끝나는 시각과 시작하는 시각이 같으면 겹치지 않은 것으로 봅니다.",
  src: "function peakConnections(spans) {\n  // TODO: 시작 +1, 끝 -1 로 훑으세요\n  return 0;\n}",
  sol: "function peakConnections(spans) {\n  const ev = [];\n  spans.forEach((s) => { ev.push([s[0], 1]); ev.push([s[1], -1]); });\n  ev.sort((a, b) => (a[0] - b[0]) || (a[1] - b[1]));\n  let cur = 0, top = 0;\n  ev.forEach((e) => { cur += e[1]; if (cur > top) top = cur; });\n  return top;\n}",
  tests: [['peakConnections([[1,5],[2,6],[7,8]])', '2'],
    ['peakConnections([[1,2],[2,3]])', '1'],
    ['peakConnections([[1,9],[2,9],[3,9]])', '3'],
    ['peakConnections([])', '0']],
  edge: [['peakConnections([[0,1]])', '1'], ['peakConnections([[1,4],[2,3],[5,6]])', '2']],
  ex: "동시 접속 수를 구하는 표준적인 방법입니다. 구간을 <b>시작 +1 · 끝 -1 인 사건</b>으로 바꾸고 시간순으로 훑으면 한 번에 답이 나옵니다.\n정렬할 때 <b>끝을 시작보다 먼저</b> 두는 것이 문제에서 요구한 경계입니다. 같은 시각에 하나가 끝나고 하나가 시작하면 겹치지 않았다고 보는 것이라, 이 순서를 뒤집으면 답이 1 커집니다.\n구간마다 다른 구간을 전부 견주면 항목 수의 제곱이 됩니다. 사건으로 바꾸면 정렬 비용만 남아, 로그 수백만 줄에서도 쓸 수 있습니다.\n같은 계산이 여러 곳에 쓰입니다 — 회의실 예약이 겹치는지, 워커 풀이 몇 개 필요한지, 커넥션 풀 크기를 얼마로 잡을지가 전부 이 모양입니다." },

];
