/* go 트랙 로그 분석 2 — 고루틴·채널·컨텍스트가 남긴 기록에서 원인을 짚는다. */
module.exports = [
{
  t: "log", k: "받는 사람이 사라진 채널", cat: "logs", d: 3, track: "go",
  file: "/var/log/edge-svc/app.log",
  q: "요청이 타임아웃될 때마다 고루틴 수가 늘고 줄지 않습니다. 원인 줄을 고르세요.",
  items: [
    { txt: "09:00:00 INFO  app: 고루틴 42, 메모리 120MB" },
    { txt: "09:00:04 INFO  app: 최근 배포 없음, 트래픽 평시 수준" },
    { txt: "09:00:10 INFO  api: 요청마다 작업 고루틴 1개 생성, 결과를 버퍼 없는 채널로 전달" },
    { txt: "09:05:00 WARN  api: 상류 지연으로 요청 300건 타임아웃, 핸들러는 즉시 반환" },
    { txt: "09:05:01 INFO  api: 작업 고루틴은 결과를 보내려고 채널에서 계속 대기", bad: true },
    { txt: "09:10:00 WARN  app: 고루틴 42 → 8,410" },
    { txt: "09:40:00 ERROR app: 메모리 1.9GB, OOMKilled" },
  ],
  ex: "버퍼 없는 채널은 <b>받는 쪽이 있어야</b> 보낼 수 있습니다. 핸들러가 타임아웃으로 먼저 돌아가면 아무도 받지 않으므로 작업 고루틴은 영원히 멈춘 채 남고, 그것이 잡고 있는 메모리도 회수되지 않습니다. 고루틴 수 급증은 결과입니다. 처방은 버퍼 1짜리 채널을 쓰거나 <code>select</code> 로 <code>ctx.Done()</code> 을 함께 기다려 <b>포기할 줄 알게</b> 만드는 것이고, 예방은 고루틴 수를 지표로 감시하는 것입니다.",
},
{
  t: "log", k: "함수가 끝날 때까지 닫히지 않는다", cat: "logs", d: 2, track: "go",
  file: "/var/log/edge-svc/app.log",
  q: "대량 파일을 처리하는 배치만 파일 디스크립터 부족으로 죽습니다. 원인 줄을 고르세요.",
  items: [
    { txt: "10:00:00 INFO  batch: 대상 파일 12,000개, ulimit -n 1024" },
    { txt: "10:00:00 INFO  batch: 디스크 여유 충분, 권한 정상" },
    { txt: "10:00:01 INFO  batch: 처음 200개는 정상 처리" },
    { txt: "10:00:01 INFO  batch: 하나의 함수 안에서 for 루프로 전부 처리" },
    { txt: "10:00:02 INFO  batch: 루프 안에서 os.Open 후 defer f.Close()", bad: true },
    { txt: "10:00:20 INFO  batch: 열린 파일 수 1,019" },
    { txt: "10:00:21 ERROR batch: too many open files" },
    { txt: "10:00:21 ERROR batch: 처리 중단 (1,020/12,000)" },
  ],
  ex: "<code>defer</code> 는 루프가 아니라 <b>함수가 끝날 때</b> 실행됩니다. 그래서 12,000개를 여는 동안 하나도 닫히지 않고 1,024 에서 막힙니다. 열린 파일 수가 한도 직전까지 오른 줄이 그것을 보여 줍니다. 처방은 <b>루프 본문을 함수로 빼서</b> 반복마다 닫히게 하거나, 루프 안에서 <code>defer</code> 없이 명시적으로 닫는 것입니다. 같은 함정이 잠금 해제와 트랜잭션 종료에도 있습니다.",
},
{
  t: "log", k: "만들지 않은 맵에 쓴다", cat: "logs", d: 2, track: "go",
  file: "/var/log/edge-svc/app.log",
  q: "특정 요청 형태에서만 패닉이 납니다. 원인 줄을 고르세요.",
  items: [
    { txt: "11:00:00 INFO  api: 요청 본문에 tags 필드가 있으면 정상 처리" },
    { txt: "11:00:02 INFO  api: 스키마 검증 통과, 필수 필드 누락 없음" },
    { txt: "11:00:05 INFO  api: 구조체 Config 의 Labels map[string]string 는 선언만 되어 있음", bad: true },
    { txt: "11:00:06 INFO  api: tags 가 없는 요청은 JSON 언마샬에서 Labels 를 채우지 않음" },
    { txt: "11:00:07 INFO  api: 이후 코드가 cfg.Labels[\"src\"] = \"api\" 로 기록 시도" },
    { txt: "11:00:07 ERROR api: panic: assignment to entry in nil map" },
    { txt: "11:00:08 ERROR api: 고루틴 패닉으로 프로세스 종료" },
  ],
  ex: "선언만 한 맵은 <code>nil</code> 이고, <b>읽기는 되지만 쓰기는 패닉</b>입니다. tags 가 있는 요청에서는 언마샬이 맵을 만들어 주므로 문제가 드러나지 않다가, 없는 요청에서 터집니다. 처방은 <code>make(map[string]string)</code> 으로 <b>생성자에서 반드시 초기화</b>하는 것이고, 예방은 구조체를 직접 리터럴로 만들지 말고 <code>NewConfig()</code> 를 거치게 강제하는 것입니다.",
},
{
  t: "log", k: "같은 배열을 두 슬라이스가 쓴다", cat: "logs", d: 4, track: "go",
  file: "/var/log/edge-svc/app.log",
  q: "필터 결과를 만들었더니 원본 목록의 값이 바뀝니다. 원인 줄을 고르세요.",
  items: [
    { txt: "12:00:00 INFO  api: 목록 조회 성공, 캐시 미사용" },
    { txt: "12:00:00 INFO  api: 응답 직전까지 값 검증 통과" },
    { txt: "12:00:00 INFO  api: 원본 items 길이 100, 용량 128" },
    { txt: "12:00:00 INFO  api: 필터 조건 status=active" },
    { txt: "12:00:01 INFO  api: 필터는 head := items[:0] 로 시작해 append 로 채움", bad: true },
    { txt: "12:00:02 INFO  api: append 가 같은 배열의 앞쪽을 덮어씀" },
    { txt: "12:00:04 WARN  api: 호출자가 들고 있던 items 의 앞 37칸이 바뀜 (결과 길이 37)" },
    { txt: "12:00:10 WARN  qa: 같은 목록을 두 화면이 공유하면 값이 섞임" },
  ],
  ex: "슬라이스는 <b>배열을 가리키는 창</b>입니다. <code>items[:0]</code> 로 시작해 <code>append</code> 하면 용량이 남아 있는 한 <b>같은 배열</b>에 덮어쓰므로, 호출자가 보던 원본이 조용히 바뀝니다. 오류는 없고 값만 틀립니다. 처방은 결과를 <code>make([]T, 0, len(items))</code> 로 <b>새로 잡아</b> 담는 것이고, 원본을 넘겨받는 함수라면 <b>수정하지 않는다</b>는 계약을 주석과 테스트로 못박아야 합니다.",
},
{
  t: "log", k: "끝을 정하지 않은 기다림", cat: "logs", d: 2, track: "go",
  file: "/var/log/edge-svc/app.log",
  q: "상류가 느려지자 우리 서비스가 함께 멈췄습니다. 원인 줄을 고르세요.",
  items: [
    { txt: "13:00:00 INFO  api: 상류 호출 평균 40ms, 동시 처리 200" },
    { txt: "13:00:05 INFO  api: 커넥션 풀 최대 200" },
    { txt: "13:10:00 WARN  upstream: 응답 지연 40ms → 무응답" },
    { txt: "13:10:01 INFO  api: http.Get 을 context.Background() 로 호출 — 마감 없음", bad: true },
    { txt: "13:10:30 WARN  api: 대기 중 요청 200, 새 요청은 풀 대기" },
    { txt: "13:11:00 ERROR api: 자체 헬스체크까지 지연, 인스턴스 교체" },
    { txt: "13:20:00 ERROR ops: 상류가 회복돼도 적체가 안 풀림" },
  ],
  ex: "마감이 없는 요청은 <b>영원히 기다립니다</b>. 상류가 무응답이 되면 그 대기가 커넥션과 고루틴을 붙잡아, 상류 하나의 장애가 우리 서비스 전체로 번집니다(전파 장애). 처방은 모든 외부 호출에 <code>context.WithTimeout</code> 을 걸고 <b>실패로 빨리 돌아오는 것</b>이며, 회로 차단기와 동시 호출 상한을 더하면 상류가 아파도 우리는 서 있을 수 있습니다.",
},
{
  t: "log", k: "세기도 전에 끝난 기다림", cat: "logs", d: 3, track: "go",
  file: "/var/log/edge-svc/app.log",
  q: "병렬 집계 결과가 실행할 때마다 다릅니다. 원인 줄을 고르세요.",
  items: [
    { txt: "14:00:00 INFO  job: 파티션 16개 병렬 집계 시작" },
    { txt: "14:00:00 INFO  job: 입력 파티션 목록 확인 완료" },
    { txt: "14:00:00 INFO  job: 각 고루틴이 시작하자마자 wg.Add(1) 호출", bad: true },
    { txt: "14:00:00 INFO  job: 본체는 곧바로 wg.Wait() 진입" },
    { txt: "14:00:00 INFO  job: Wait 시점에 등록된 작업 3개" },
    { txt: "14:00:01 WARN  job: 집계 완료 보고 (실제 처리 파티션 3~16, 실행마다 다름)" },
    { txt: "14:30:00 WARN  qa: 같은 입력에 합계가 매번 다름" },
  ],
  ex: "<code>wg.Add(1)</code> 을 <b>고루틴 안에서</b> 부르면, 아직 시작하지 못한 고루틴은 세어지지 않습니다. <code>Wait()</code> 는 등록된 것만 기다리고 곧바로 통과하므로 결과가 실행마다 달라집니다. 오류도 패닉도 없고 <b>숫자만 틀립니다</b>. 처방은 고루틴을 <b>띄우기 전에</b> 바깥에서 <code>Add</code> 하는 것이고, 예방은 경합 검출기(<code>-race</code>)를 CI 에서 늘 켜 두는 것입니다.",
},
{
  t: "log", k: "복사된 잠금은 잠그지 못한다", cat: "logs", d: 4, track: "go",
  file: "/var/log/edge-svc/app.log",
  q: "뮤텍스로 감쌌는데도 카운터 값이 어긋납니다. 원인 줄을 고르세요.",
  items: [
    { txt: "15:00:00 INFO  app: Counter 구조체에 sync.Mutex 임베드" },
    { txt: "15:00:01 INFO  app: 증가 메서드는 값 수신자 func (c Counter) Inc()", bad: true },
    { txt: "15:00:02 INFO  app: 호출마다 구조체와 뮤텍스가 통째로 복사됨" },
    { txt: "15:00:03 INFO  app: go vet — copylocks 경고 있음(빌드는 통과)" },
    { txt: "15:00:10 WARN  app: 1,000회 증가 후 값 947" },
    { txt: "15:00:20 WARN  test: -race 실행 시 데이터 경합 보고" },
  ],
  ex: "값 수신자는 <b>구조체를 복사</b>하고, 그 안의 뮤텍스도 함께 복사됩니다. 그러면 각자 자기 사본을 잠그는 셈이라 아무도 막지 못하고, 증가가 유실됩니다. <code>go vet</code> 의 copylocks 경고가 이미 그 사실을 말하고 있었습니다. 처방은 <b>포인터 수신자</b>(<code>func (c *Counter) Inc()</code>)로 바꾸는 것이고, 예방은 vet 과 <code>-race</code> 를 CI 에서 실패 조건으로 두는 것입니다.",
},
{
  t: "log", k: "고른 select 가 메모리를 먹는다", cat: "logs", d: 4, track: "go",
  file: "/var/log/edge-svc/app.log",
  q: "메시지를 많이 받을수록 메모리가 계단식으로 오릅니다. 원인 줄을 고르세요.",
  items: [
    { txt: "16:00:00 INFO  consumer: 초당 4,000건 수신, 처리 정상" },
    { txt: "16:00:00 INFO  consumer: 처리 지연 p95 8ms, 큐 적체 없음" },
    { txt: "16:00:00 INFO  consumer: 힙 프로파일에 큰 객체 없음" },
    { txt: "16:00:01 INFO  consumer: 루프마다 select { case m := <-ch: ... ; case <-time.After(30*time.Second): ... }", bad: true },
    { txt: "16:00:02 INFO  consumer: time.After 는 호출할 때마다 타이머를 새로 만든다" },
    { txt: "16:00:03 INFO  runtime: 활성 타이머 수 118,000" },
    { txt: "16:00:30 WARN  app: RSS 240MB → 1.3GB" },
    { txt: "16:05:00 ERROR app: GC 시간 비율 31%, 처리 지연 급증" },
  ],
  ex: "<code>time.After</code> 는 부른 즉시 타이머를 만들고, <b>만료될 때까지 회수되지 않습니다</b>. 메시지가 빨리 오면 30초짜리 타이머가 초당 4,000개씩 쌓입니다. 활성 타이머 11만이 그 결과입니다. 처방은 <code>time.NewTimer</code> 를 <b>루프 밖에서 한 번</b> 만들고 <code>Reset</code> 으로 재사용하는 것이며, 컨텍스트 마감으로 대신할 수 있으면 그쪽이 더 간단합니다.",
},
{
  t: "log", k: "여럿이 한 맵에 쓴다", cat: "logs", d: 2, track: "go",
  file: "/var/log/edge-svc/app.log",
  q: "동시 처리량을 올리자 프로세스가 즉사합니다. 원인 줄을 고르세요.",
  items: [
    { txt: "17:00:00 INFO  job: 입력 8,000건, 배치 처리 시작" },
    { txt: "17:00:00 INFO  job: errgroup 으로 8개 병렬 처리" },
    { txt: "17:00:00 INFO  job: 각 고루틴은 서로 다른 입력 구간을 맡음" },
    { txt: "17:00:01 INFO  job: 결과를 공용 map[string]Result 에 각 고루틴이 직접 기록", bad: true },
    { txt: "17:00:02 INFO  job: 동시성 2 에서는 재현되지 않음" },
    { txt: "17:00:10 INFO  job: 동시성 8 로 상향" },
    { txt: "17:00:11 ERROR runtime: fatal error: concurrent map writes" },
    { txt: "17:00:11 ERROR runtime: 복구 불가 — recover 로도 잡히지 않음" },
  ],
  ex: "내장 맵은 <b>동시 쓰기를 지원하지 않습니다</b>. 런타임이 이를 감지하면 <code>fatal error</code> 로 프로세스를 즉시 끝내며, 이것은 패닉이 아니라 <code>recover</code> 로도 못 잡습니다. 동시성이 낮을 때 재현되지 않은 것이 발견을 늦췄습니다. 처방은 뮤텍스로 감싸거나, 각 고루틴이 <b>자기 몫만 채우는 슬라이스</b>에 인덱스로 쓰고 마지막에 합치는 것입니다(<code>sync.Map</code> 은 읽기 위주일 때만).",
},
{
  t: "log", k: "소문자 필드는 채워지지 않는다", cat: "logs", d: 2, track: "go",
  file: "/var/log/edge-svc/app.log",
  q: "JSON 을 잘 받았는데 값이 전부 기본값입니다. 원인 줄을 고르세요.",
  items: [
    { txt: "18:00:00 INFO  api: 요청 본문 {\"userId\":91,\"amount\":12000}" },
    { txt: "18:00:00 INFO  api: json.Unmarshal 반환 err == nil" },
    { txt: "18:00:01 INFO  api: 대상 구조체 필드가 userId, amount 로 소문자 시작", bad: true },
    { txt: "18:00:02 INFO  api: 언마샬 후 값 userId=0 amount=0" },
    { txt: "18:00:03 WARN  api: 금액 0 으로 주문 생성" },
    { txt: "18:00:30 ERROR ops: 0원 주문 214건 정정 필요" },
  ],
  ex: "인코딩 패키지는 <b>내보내진(대문자로 시작하는) 필드만</b> 봅니다. 소문자 필드는 채워지지 않는데 <code>err</code> 는 <code>nil</code> 이라 성공처럼 보입니다 — 가장 위험한 종류의 실패입니다. 처방은 필드를 대문자로 바꾸고 <code>`json:\"userId\"`</code> 태그로 이름을 맞추는 것이고, 예방은 필수 값에 대한 <b>검증</b>을 언마샬 직후에 두어 0 이나 빈 문자열을 그대로 흘려보내지 않는 것입니다.",
},
];
