/* web 트랙 로그 분석 — 네트워크 탭과 액세스 로그를 읽고 원인을 짚는다. */
module.exports = [
{
  t: "log", k: "요청은 보냈는데 서버에 안 닿는다", cat: "logs", d: 2, track: "web",
  file: "network.log",
  q: "프런트에서 API 를 부르면 콘솔에만 오류가 뜨고 서버 로그에는 아무 것도 없습니다. 원인 줄을 고르세요.",
  items: [
    { txt: "09:00:00 INFO  page: https://app.example.com 로드 완료" },
    { txt: "09:00:00 INFO  app: 로그인 상태 확인됨, 토큰 만료까지 42분" },
    { txt: "09:00:01 INFO  net: 같은 출처 요청 GET /config 200" },
    { txt: "09:00:01 INFO  net: OPTIONS https://api.example.com/v1/orders 204" },
    { txt: "09:00:01 INFO  net: 응답 헤더 Access-Control-Allow-Origin: https://app.example.com" },
    { txt: "09:00:01 INFO  net: 요청 헤더에 Authorization 포함, 허용 목록에는 없음", bad: true },
    { txt: "09:00:01 WARN  browser: Request header field authorization is not allowed by Access-Control-Allow-Headers" },
    { txt: "09:00:01 ERROR net: GET /v1/orders 취소됨 (본 요청 미전송)" },
  ],
  ex: "사전 요청(OPTIONS)은 200 을 받았지만 <b>보낼 헤더 목록에 Authorization 이 없어</b> 브라우저가 본 요청을 아예 보내지 않았습니다. 서버 로그가 비어 있는 것이 그 증거입니다 — 막은 것은 서버가 아니라 브라우저입니다. Allow-Origin 이 맞다고 끝이 아닙니다. 처방은 응답에 <code>Access-Control-Allow-Headers: Authorization, Content-Type</code> 을 더하는 것이고, 쿠키를 쓴다면 <code>Allow-Credentials</code> 와 정확한 Origin 도 함께 맞춰야 합니다.",
},
{
  t: "log", k: "배포했는데 옛 화면이 그대로다", cat: "logs", d: 2, track: "web",
  file: "access.log",
  q: "새 버전을 올렸는데 일부 사용자는 강제 새로고침을 해야 바뀝니다. 원인 줄을 고르세요.",
  items: [
    { txt: "10:00:00 INFO  deploy: v42 배포 완료, 정적 파일 해시 갱신" },
    { txt: "10:00:10 INFO  cdn: /assets/app.9f21c.js 304 (해시 파일명, 캐시 정상)" },
    { txt: "10:00:20 INFO  cdn: /index.html Cache-Control: public, max-age=31536000", bad: true },
    { txt: "10:00:30 INFO  cdn: /index.html 200 from cache (age 82,400s)" },
    { txt: "10:01:00 WARN  app: 옛 index.html 이 지워진 app.3b77a.js 를 참조" },
    { txt: "10:01:05 ERROR app: Loading chunk 7 failed, 흰 화면" },
  ],
  ex: "해시가 붙은 자산은 오래 캐시해도 되지만, <b>그 해시를 가리키는 index.html 은 그러면 안 됩니다</b>. 1년짜리 캐시가 붙은 진입 문서가 옛 파일 이름을 계속 가리키니 이미 지워진 청크를 부르고 흰 화면이 납니다. 처방은 진입 문서에 <code>no-cache</code>(또는 짧은 max-age + <code>must-revalidate</code>)를 주는 것 — <b>이름이 고정된 파일은 짧게, 이름에 해시가 있는 파일은 길게</b> 가 원칙입니다.",
},
{
  t: "log", k: "로그인은 되는데 다음 요청이 401", cat: "logs", d: 3, track: "web",
  file: "network.log",
  q: "로그인 응답은 200 인데 이어지는 API 가 전부 401 입니다. 원인 줄을 고르세요.",
  items: [
    { txt: "11:00:00 INFO  net: POST https://api.example.com/login 200" },
    { txt: "11:00:00 INFO  net: Set-Cookie: sid=…; HttpOnly; Secure; SameSite=Lax", bad: true },
    { txt: "11:00:01 INFO  page: 문서 출처는 https://app.example.com (다른 사이트)" },
    { txt: "11:00:02 WARN  browser: 교차 사이트 요청에 sid 쿠키를 붙이지 않음" },
    { txt: "11:00:02 WARN  net: GET /v1/me 401" },
    { txt: "11:00:03 ERROR app: 로그인 화면으로 되돌아감, 무한 반복" },
  ],
  ex: "<code>SameSite=Lax</code> 는 <b>다른 사이트에서 시작한 요청에 쿠키를 붙이지 않습니다</b>. app 과 api 가 다른 등록 도메인이므로 로그인으로 받은 쿠키가 그다음 요청에는 실리지 않고, 서버는 당연히 401 을 냅니다. 401 과 되돌아감은 결과입니다. 처방은 두 가지 중 하나 — <b>같은 사이트로 묶어</b>(api.app.example.com) Lax 를 유지하거나, <code>SameSite=None; Secure</code> 로 열고 CSRF 방어를 따로 두는 것입니다.",
},
{
  t: "log", k: "본문만 4MB", cat: "logs", d: 2, track: "web",
  file: "access.log",
  q: "목록 화면이 느린데 서버 처리 시간은 30ms 입니다. 원인 줄을 고르세요.",
  items: [
    { txt: "12:00:00 INFO  api: GET /v1/products 200 처리 30ms" },
    { txt: "12:00:00 INFO  api: 응답 본문 4.2MB (상품 8,000건 전체)" },
    { txt: "12:00:00 INFO  api: 요청 헤더 Accept-Encoding: gzip, br" },
    { txt: "12:00:00 INFO  api: 응답 헤더에 Content-Encoding 없음 — 압축 미적용", bad: true },
    { txt: "12:00:03 WARN  net: 전송 3.1초 (모바일 4G)" },
    { txt: "12:00:04 WARN  perf: 화면 완성 3.4초, 그중 서버 시간 0.03초" },
  ],
  ex: "브라우저는 압축을 받겠다고 했는데 서버가 <b>그대로 보냈습니다</b>. JSON 은 대개 8~10배 줄어들므로 4.2MB 가 0.5MB 가 되고 전송 3.1초가 0.4초가 됩니다. 처리 30ms 와 완성 3.4초의 격차가 병목이 네트워크에 있음을 이미 말하고 있었습니다. 처방은 게이트웨이나 앱에서 gzip·br 을 켜는 것이고, 더 근본적으로는 <b>8,000건을 한 번에 보내지 않는 것</b>(페이지네이션·필드 선택)입니다.",
},
{
  t: "log", k: "첫 바이트까지 세 번을 돈다", cat: "logs", d: 2, track: "web",
  file: "access.log",
  q: "주소를 직접 입력해 들어오면 첫 화면이 유독 느립니다. 원인 줄을 고르세요.",
  items: [
    { txt: "13:00:00 INFO  net: http://example.com/ → 301 https://example.com/ (180ms)" },
    { txt: "13:00:00 INFO  net: https://example.com/ → 301 https://www.example.com/ (190ms)" },
    { txt: "13:00:01 INFO  net: https://www.example.com/ → 302 /home (170ms)" },
    { txt: "13:00:01 INFO  net: 리다이렉트 3회, 각 단계마다 새 TLS 핸드셰이크", bad: true },
    { txt: "13:00:02 WARN  perf: TTFB 940ms (서버 처리 40ms)" },
    { txt: "13:00:02 WARN  perf: 모바일에서 첫 화면 2.6초" },
  ],
  ex: "정답 주소에 닿기까지 <b>세 번을 되돌려 보냈습니다</b>. 리다이렉트는 각각 왕복과 연결 비용이 있고, 프로토콜과 호스트가 바뀌면 TLS 도 다시 맺어야 합니다. TTFB 940ms 중 서버는 40ms 뿐이라는 사실이 그것을 가리킵니다. 처방은 <b>한 번에 최종 주소로</b> 보내는 것(http://example.com → https://www.example.com 직행)이고, HSTS 를 붙이면 http 단계 자체가 사라집니다.",
},
{
  t: "log", k: "남의 스크립트가 내 화면을 막는다", cat: "logs", d: 2, track: "web",
  file: "network.log",
  q: "본문 렌더가 1.8초 동안 시작되지 않습니다. 원인 줄을 고르세요.",
  items: [
    { txt: "14:00:00 INFO  net: GET / 200 (TTFB 60ms)" },
    { txt: "14:00:00 INFO  parser: <head> 파싱 시작" },
    { txt: "14:00:00 INFO  parser: <script src='//tag.vendor.example/t.js'> — async·defer 없음", bad: true },
    { txt: "14:00:01 WARN  net: tag.vendor.example 응답 1,760ms" },
    { txt: "14:00:02 WARN  parser: 파서 차단, DOM 구축 대기" },
    { txt: "14:00:02 WARN  perf: FCP 1.9초 (HTML 은 60ms 에 도착)" },
  ],
  ex: "<code>&lt;head&gt;</code> 의 일반 스크립트는 <b>내려받아 실행할 때까지 파서를 멈춥니다</b>. 남의 도메인이 느리면 내 화면이 그만큼 안 뜨고, HTML 이 60ms 에 도착한 것은 아무 소용이 없습니다. 처방은 <code>defer</code>(문서 파싱 뒤 실행) 나 <code>async</code> 를 붙이고, 정말 필요 없으면 <b>본문 끝으로 내리거나 지연 로드</b>하는 것입니다. 예방은 서드파티 스크립트마다 <b>없을 때도 화면이 뜨는지</b> 확인하는 것입니다.",
},
{
  t: "log", k: "누르려는 순간 버튼이 도망간다", cat: "logs", d: 2, track: "web",
  file: "browser-console.log",
  q: "화면이 뜬 뒤 내용이 아래로 밀려 오탭이 생깁니다. 원인 줄을 고르세요.",
  items: [
    { txt: "15:00:00 INFO  render: 텍스트 먼저 표시 (FCP 0.7초)" },
    { txt: "15:00:01 INFO  net: hero.jpg 200 (1.2MB, 1600x900)" },
    { txt: "15:00:01 INFO  render: <img> 에 width·height 속성 없음, CSS 종횡비도 없음", bad: true },
    { txt: "15:00:01 WARN  render: 이미지 도착 후 본문 420px 아래로 이동" },
    { txt: "15:00:02 WARN  perf: CLS 0.31 (기준 0.1)" },
    { txt: "15:00:03 WARN  ux: 오탭 이벤트 급증" },
  ],
  ex: "이미지 크기를 미리 알려 주지 않으면 브라우저는 <b>자리를 비워 둘 수 없어</b> 도착한 뒤에야 밀어냅니다. 그것이 레이아웃 이동이고 CLS 0.31 과 오탭은 그 결과입니다. 처방은 <code>&lt;img width height&gt;</code> 를 적어 브라우저가 종횡비로 자리를 잡게 하는 것(또는 CSS <code>aspect-ratio</code>)이고, 광고·배너처럼 나중에 채워지는 영역도 <b>최소 높이를 미리 잡아</b> 두어야 합니다.",
},
{
  t: "log", k: "글자가 3초 동안 안 보인다", cat: "logs", d: 2, track: "web",
  file: "network.log",
  q: "화면은 떴는데 본문 글자가 한동안 보이지 않습니다. 원인 줄을 고르세요.",
  items: [
    { txt: "16:00:00 INFO  net: GET / 200 (TTFB 55ms)" },
    { txt: "16:00:00 INFO  net: HTML 안에 인라인 임계 CSS 포함" },
    { txt: "16:00:00 INFO  net: CSS 200 (40ms), 자체 도메인" },
    { txt: "16:00:00 INFO  render: 레이아웃 완료, 텍스트 노드 준비됨" },
    { txt: "16:00:00 INFO  css: @font-face 에 font-display 지정 없음 (기본 block)", bad: true },
    { txt: "16:00:01 WARN  net: pretendard.woff2 응답 2,900ms (외부 CDN)" },
    { txt: "16:00:03 WARN  render: 그 사이 텍스트가 보이지 않음 (FOIT)" },
    { txt: "16:00:04 WARN  perf: LCP 3.2초, 이탈률 상승" },
  ],
  ex: "기본 동작은 폰트를 기다리는 동안 <b>글자를 아예 그리지 않는 것</b>입니다. 레이아웃은 끝났는데 화면은 비어 있는 이유가 그것이고, 느린 CDN 이 그 시간을 3초로 늘렸습니다. 처방은 <code>font-display: swap</code> — 먼저 대체 글꼴로 보여 주고 도착하면 바꿔치기합니다. 바뀔 때의 흔들림이 걱정되면 <b>비슷한 굵기·자폭의 대체 글꼴</b>을 지정하고, 핵심 폰트는 <code>preload</code> 로 미리 받습니다.",
},
{
  t: "log", k: "로그인이 새로고침마다 풀린다", cat: "logs", d: 3, track: "web",
  file: "network.log",
  q: "로그인한 뒤 다른 페이지로 가면 다시 로그인 화면이 뜹니다. 원인 줄을 고르세요.",
  items: [
    { txt: "17:00:00 INFO  net: POST https://www.example.com/login 200" },
    { txt: "17:00:00 INFO  net: Set-Cookie: sid=…; Domain=www.example.com; Path=/login", bad: true },
    { txt: "17:00:01 INFO  net: GET https://www.example.com/dashboard" },
    { txt: "17:00:01 WARN  browser: 요청 경로가 /dashboard 라 sid 쿠키 미전송" },
    { txt: "17:00:01 WARN  net: GET /dashboard 302 → /login" },
    { txt: "17:00:02 WARN  app: 로그인 → 대시보드 → 로그인 반복" },
  ],
  ex: "쿠키에 <code>Path=/login</code> 을 박아 두어 <b>그 경로에서만</b> 전송됩니다. 대시보드 요청에는 쿠키가 없으니 서버가 로그인으로 되돌리고, 되돌아온 로그인 화면에서는 쿠키가 있으니 다시 통과하는 고리가 생깁니다. 처방은 세션 쿠키의 <code>Path=/</code> 로 두는 것이고, Domain 은 <b>정말 하위 도메인과 공유해야 할 때만</b> 지정합니다 — 필요 없이 넓히면 이번에는 유출 위험이 커집니다.",
},
{
  t: "log", k: "https 페이지가 http 를 부른다", cat: "logs", d: 2, track: "web",
  file: "browser-console.log",
  q: "일부 이미지와 차트만 보이지 않습니다. 원인 줄을 고르세요.",
  items: [
    { txt: "18:00:00 INFO  page: https://shop.example.com/product/71 로드" },
    { txt: "18:00:00 INFO  net: 문서·스크립트·스타일 모두 200" },
    { txt: "18:00:00 INFO  net: 인증서 유효, HSTS 적용됨" },
    { txt: "18:00:00 INFO  net: 자체 자산 200 (모두 https)" },
    { txt: "18:00:01 INFO  net: 상품 이미지 URL 이 DB 에 http:// 로 저장돼 있음", bad: true },
    { txt: "18:00:01 WARN  browser: Mixed Content — http 이미지 요청 차단됨" },
    { txt: "18:00:01 WARN  browser: 차트 라이브러리도 http 로 로드 시도, 차단" },
    { txt: "18:00:02 ERROR app: 이미지 자리 빈칸, 차트 미표시" },
  ],
  ex: "https 문서 안에서 http 자원을 부르면 브라우저가 <b>내용을 바꿔치기당할 수 있다고 보고 막습니다</b>. 자체 자산이 모두 https 인데도 화면이 비는 이유는 데이터에 저장된 주소가 http 이기 때문입니다. 처방은 데이터의 주소를 https 로 일괄 정정하고, 렌더 시 <b>프로토콜을 강제</b>하는 것입니다. 임시 방편으로 <code>upgrade-insecure-requests</code> 를 줄 수 있지만, 저장된 값이 틀렸다는 사실은 남습니다.",
},
{
  t: "log", k: "여섯 개씩 줄을 선다", cat: "logs", d: 3, track: "web",
  file: "network.log",
  q: "타일 이미지가 많은 페이지에서만 로딩이 계단처럼 밀립니다. 원인 줄을 고르세요.",
  items: [
    { txt: "19:00:00 INFO  net: 문서 200 (TTFB 50ms)" },
    { txt: "19:00:00 INFO  net: 이미지 평균 크기 38KB (압축·크기 적정)" },
    { txt: "19:00:00 INFO  net: 이미지 요청 84건 대기열에 등록" },
    { txt: "19:00:00 INFO  net: 이미지 호스트 static.example.com" },
    { txt: "19:00:00 INFO  net: 협상 프로토콜 http/1.1 (ALPN 에 h2 없음)", bad: true },
    { txt: "19:00:01 WARN  net: 동시 연결 6개 제한, 나머지 78건 대기" },
    { txt: "19:00:03 WARN  perf: 마지막 이미지 도착 4.8초" },
    { txt: "19:00:04 WARN  perf: 폭포수 그래프가 6줄 계단 모양" },
  ],
  ex: "HTTP/1.1 은 호스트마다 <b>동시 연결이 여섯 개</b>로 제한됩니다. 84건을 보내면 여섯씩 끊어져 계단 모양이 되고, 마지막 이미지는 5초 가까이 걸립니다. 처방은 <b>HTTP/2 이상을 켜는 것</b> — 한 연결에서 다중화되어 제한이 사라집니다. 그 전에는 스프라이트·도메인 샤딩으로 우회했지만, h2 에서는 오히려 손해이므로 <b>먼저 프로토콜부터 확인</b>해야 합니다.",
},
{
  t: "log", k: "서비스 워커가 옛 파일을 지킨다", cat: "logs", d: 3, track: "web",
  file: "browser-console.log",
  q: "배포 후에도 일부 기기에서만 옛 버전이 계속 뜹니다. 원인 줄을 고르세요.",
  items: [
    { txt: "20:00:00 INFO  deploy: v51 배포, CDN 캐시 무효화 완료" },
    { txt: "20:00:02 INFO  cdn: /index.html 200 (age 0, 최신 응답)" },
    { txt: "20:00:05 INFO  sw: 기존 서비스 워커 활성 상태 (v50 프리캐시)" },
    { txt: "20:00:06 INFO  sw: fetch 핸들러가 cache-first 로 응답, 네트워크 확인 없음", bad: true },
    { txt: "20:00:07 INFO  sw: 새 워커 설치됨, 상태 waiting" },
    { txt: "20:00:08 WARN  sw: skipWaiting·clients.claim 호출 없음 — 탭을 모두 닫아야 교체" },
    { txt: "20:00:20 WARN  app: 사용자 30% 가 v50 을 계속 사용" },
    { txt: "20:05:00 ERROR api: v50 이 삭제된 엔드포인트 호출, 404 급증" },
  ],
  ex: "서비스 워커는 <b>CDN 보다 앞</b>에 있습니다. cache-first 로 응답하면 네트워크를 보지 않으므로 CDN 무효화는 아무 효과가 없고, 새 워커는 waiting 에 머물러 탭을 모두 닫기 전까지 교체되지 않습니다. 30% 잔존과 404 는 그 결과입니다. 처방은 진입 문서와 API 를 <b>network-first</b> 로 두고, 새 버전에서 <code>skipWaiting()</code>·<code>clients.claim()</code> 으로 즉시 넘겨받되 <b>사용자에게 새로고침을 안내</b>하는 것입니다.",
},
];
