/* rust 트랙 로그 분석 2 — 패닉·비동기 런타임이 남긴 기록에서 원인을 짚는다. */
module.exports = [
{
  t: "log", k: "릴리스에서만 숫자가 돈다", cat: "logs", d: 3, track: "rust",
  file: "/var/log/ledger/app.log",
  q: "테스트에서는 잡히던 오류가 배포판에서는 잘못된 값으로 조용히 지나갑니다. 원인 줄을 고르세요.",
  items: [
    { txt: "09:00:00 INFO  app: build profile release, overflow-checks 기본값" },
    { txt: "09:00:01 INFO  app: 단위 테스트는 debug 빌드로 전부 통과" },
    { txt: "09:00:01 INFO  app: 배포 전 스테이징에서도 이상 없음" },
    { txt: "09:00:02 INFO  app: 잔액 계산에 u32 사용, 입력은 외부 API 값" },
    { txt: "09:00:04 INFO  app: 차감 로직 balance - amount 를 검사 없이 수행", bad: true },
    { txt: "09:00:06 INFO  app: amount 12,000 > balance 8,000 인 요청 도착" },
    { txt: "09:00:06 WARN  app: 결과 잔액 4,294,963,296" },
    { txt: "09:20:00 ERROR ops: 해당 계정에서 대량 출금 시도 감지" },
  ],
  ex: "부호 없는 정수의 뺄셈이 <b>음수가 되면 감싸 돕니다</b>. 디버그 빌드는 오버플로에서 패닉하지만 릴리스는 기본적으로 검사를 끄므로, 테스트에서 보이던 사고가 배포판에서는 <b>거대한 잔액</b>으로 조용히 지나갑니다. 처방은 <code>checked_sub</code>·<code>saturating_sub</code> 로 <b>모자란 경우를 값으로 다루는 것</b>이고, 금액처럼 위험한 계산에는 릴리스에서도 <code>overflow-checks = true</code> 를 켜 두는 편이 낫습니다.",
},
{
  t: "log", k: "비동기 안에서 막고 서 있다", cat: "logs", d: 3, track: "rust",
  file: "/var/log/ledger/app.log",
  q: "요청 몇 건이 무거운 계산을 하는 동안 서버 전체가 응답하지 않습니다. 원인 줄을 고르세요.",
  items: [
    { txt: "10:00:00 INFO  app: tokio 멀티스레드 런타임, 워커 스레드 4" },
    { txt: "10:00:02 INFO  api: 평시 p95 12ms, 동시 요청 300" },
    { txt: "10:04:00 INFO  api: 리포트 요청 4건 수신" },
    { txt: "10:04:01 INFO  api: 핸들러가 async 안에서 CPU 집약 압축을 직접 수행(0.8초)", bad: true },
    { txt: "10:04:02 WARN  tokio: 워커 4개 모두 점유, 대기 태스크 1,900" },
    { txt: "10:04:05 WARN  api: 헬스체크 응답 없음" },
    { txt: "10:04:10 ERROR lb: 인스턴스 제외" },
  ],
  ex: "비동기 런타임의 워커는 <b>양보하는 지점(await)</b>이 있어야 다른 태스크로 넘어갑니다. CPU 를 0.8초 붙잡는 코드는 그 사이 워커 하나를 통째로 막고, 네 건이면 런타임 전체가 멈춥니다. 대기 태스크 1,900 은 결과입니다. 처방은 무거운 계산을 <code>spawn_blocking</code>(또는 별도 스레드 풀)으로 보내는 것이고, 예방은 <b>블로킹 호출을 async 함수 안에서 금지</b>하는 린트를 두는 것입니다.",
},
{
  t: "log", k: "잠금을 쥔 채 기다린다", cat: "logs", d: 4, track: "rust",
  file: "/var/log/ledger/app.log",
  q: "부하가 조금만 올라가면 모든 요청이 영원히 멈춥니다. 원인 줄을 고르세요.",
  items: [
    { txt: "11:00:00 INFO  app: 기동 정상, 헬스체크 통과" },
    { txt: "11:00:00 INFO  app: 커넥션 풀·타임아웃 설정 변경 없음" },
    { txt: "11:00:00 INFO  app: 공유 상태를 std::sync::Mutex 로 보호" },
    { txt: "11:00:01 INFO  app: 동시 요청 2 에서는 재현되지 않음" },
    { txt: "11:00:02 INFO  api: 잠금을 얻은 뒤 그 범위 안에서 DB 호출을 await", bad: true },
    { txt: "11:00:03 INFO  tokio: 태스크가 await 에서 다른 워커로 옮겨질 수 있음" },
    { txt: "11:00:10 WARN  api: 대기 중 요청 200, 진행 0" },
    { txt: "11:00:40 ERROR api: 전체 요청 타임아웃, 재시작으로만 복구" },
  ],
  ex: "동기 잠금을 쥔 채 <code>await</code> 하면, 그 태스크가 멈춰 있는 동안 <b>잠금도 함께 붙잡혀</b> 있습니다. 다른 태스크는 잠금을 못 얻고, 잠금을 쥔 태스크는 DB 를 기다리니 진행이 없습니다. 처방은 <b>await 전에 잠금을 놓는 것</b>(필요한 값만 복사해 나오기)이고, 잠금 범위 안에서 반드시 기다려야 한다면 <code>tokio::sync::Mutex</code> 를 써야 합니다.",
},
{
  t: "log", k: "글자 가운데를 자른다", cat: "logs", d: 2, track: "rust",
  file: "/var/log/ledger/app.log",
  q: "한국어 입력에서만 미리보기 생성이 패닉합니다. 원인 줄을 고르세요.",
  items: [
    { txt: "12:00:00 INFO  api: 미리보기 생성 요청 처리 시작" },
    { txt: "12:00:00 INFO  api: 미리보기 길이 20자로 자르기" },
    { txt: "12:00:01 INFO  api: 영문 입력은 정상 처리" },
    { txt: "12:00:02 INFO  api: 자르기를 &text[..20] 로 수행 — 바이트 인덱스", bad: true },
    { txt: "12:00:03 INFO  api: 한글 한 글자는 UTF-8 로 3바이트" },
    { txt: "12:00:03 ERROR api: panic: byte index 20 is not a char boundary" },
    { txt: "12:00:04 ERROR api: 요청 실패, 500 반환" },
  ],
  ex: "문자열 슬라이싱은 <b>바이트 단위</b>이고, 경계가 글자 가운데면 패닉합니다. 영문은 대부분 1바이트라 20이 우연히 경계에 맞았을 뿐입니다. 처방은 <code>chars().take(20)</code> 처럼 <b>글자 단위</b>로 다루거나 <code>char_indices</code> 로 안전한 경계를 찾는 것이고, 예방은 사용자 입력을 자르는 함수에 <b>다국어 문자열 테스트</b>를 반드시 넣는 것입니다.",
},
{
  t: "log", k: "복제가 초당 수만 번", cat: "logs", d: 3, track: "rust",
  file: "/var/log/ledger/app.log",
  q: "CPU 는 100% 인데 실제 처리량은 낮습니다. 원인 줄을 고르세요.",
  items: [
    { txt: "13:00:00 INFO  api: 요청 초당 1,200, CPU 100%" },
    { txt: "13:00:00 INFO  api: GC 없음(러스트), 메모리 사용량 안정" },
    { txt: "13:00:01 INFO  api: 외부 호출 없음 — 전부 로컬 계산" },
    { txt: "13:00:01 INFO  perf: 프로파일 상위 항목 memcpy 41%, malloc 18%" },
    { txt: "13:00:02 INFO  api: 규칙 목록(약 8MB)을 요청마다 clone() 해서 필터에 전달", bad: true },
    { txt: "13:00:03 INFO  api: 필터는 값을 읽기만 함" },
    { txt: "13:00:10 WARN  api: p95 18ms → 240ms" },
    { txt: "13:10:00 WARN  ops: 인스턴스를 늘려도 처리량이 비례해 늘지 않음" },
  ],
  ex: "읽기만 하는 데이터를 <b>요청마다 통째로 복제</b>했습니다. 8MB 를 초당 1,200번 복사하면 CPU 가 memcpy 로 채워지고, 인스턴스를 늘려도 낭비가 비례해 늘 뿐입니다. 프로파일의 memcpy 41% 가 그 지문입니다. 처방은 <b>참조로 빌려주는 것</b>(<code>&amp;[Rule]</code>)이고, 소유권을 여러 곳에서 나눠 가져야 한다면 <code>Arc</code> 로 <b>가리키기만</b> 하면 됩니다.",
},
{
  t: "log", k: "서로를 붙잡은 두 노드", cat: "logs", d: 4, track: "rust",
  file: "/var/log/ledger/app.log",
  q: "세션이 끝나도 메모리가 회수되지 않습니다. 원인 줄을 고르세요.",
  items: [
    { txt: "14:00:00 INFO  app: 세션 시작·종료 이벤트는 정상 기록" },
    { txt: "14:00:00 INFO  app: 세션마다 부모·자식 노드 구조 생성" },
    { txt: "14:00:01 INFO  app: 자식이 부모를 Rc 로 들고, 부모도 자식을 Rc 로 보관", bad: true },
    { txt: "14:00:02 INFO  app: 세션 종료 시 최상위 참조만 해제" },
    { txt: "14:00:03 INFO  app: 두 노드의 강한 참조 수가 서로 1 로 남음" },
    { txt: "14:10:00 WARN  app: 세션 12,000건 종료 후 RSS 그대로" },
    { txt: "14:40:00 ERROR app: 메모리 한도 초과로 재시작" },
  ],
  ex: "참조 세기는 <b>순환을 풀지 못합니다</b>. 부모와 자식이 서로를 강하게 붙잡으면 바깥에서 놓아도 카운트가 0 이 되지 않아 영원히 남습니다. 강한 참조 수가 서로 1 이라는 줄이 그 상태입니다. 처방은 <b>한쪽을 약한 참조</b>(<code>Weak</code>)로 바꾸는 것 — 보통 자식이 부모를 약하게 가리킵니다. 예방은 소유 방향을 <b>한 방향으로</b> 정하고 그림으로 그려 두는 것입니다.",
},
{
  t: "log", k: "끝없이 받아 주는 큐", cat: "logs", d: 2, track: "rust",
  file: "/var/log/ledger/app.log",
  q: "소비자가 느려진 순간부터 메모리가 계속 오릅니다. 원인 줄을 고르세요.",
  items: [
    { txt: "15:00:00 INFO  app: 파이프라인 기동, 입력 정상" },
    { txt: "15:00:00 INFO  app: 생산자 8, 소비자 2" },
    { txt: "15:00:01 INFO  app: 채널은 unbounded_channel 사용", bad: true },
    { txt: "15:00:02 INFO  app: 평시 큐 길이 0~5" },
    { txt: "15:04:00 WARN  db: 쓰기 지연 3ms → 900ms" },
    { txt: "15:04:30 WARN  app: 큐 길이 1,240,000, RSS 2.6GB" },
    { txt: "15:05:00 ERROR app: 메모리 부족으로 종료 (유실 120만 건)" },
  ],
  ex: "한도가 없는 큐는 <b>느려진 소비자를 메모리로 메꿉니다</b>. 상류가 잠깐 느려져도 생산자는 계속 밀어 넣을 수 있어 적체가 그대로 메모리가 되고, 결국 쌓아 둔 것까지 전부 잃습니다. 처방은 <b>유계 채널</b>로 바꿔 큐가 차면 생산자가 기다리게(=역압) 하는 것이고, 기다릴 수 없는 성격이면 <b>가장 오래된 것부터 버리는</b> 정책을 명시해야 합니다.",
},
{
  t: "log", k: "붙잡지 않은 손잡이", cat: "logs", d: 3, track: "rust",
  file: "/var/log/ledger/app.log",
  q: "배포 때마다 마지막 작업 몇 건이 흔적 없이 사라집니다. 원인 줄을 고르세요.",
  items: [
    { txt: "16:00:00 INFO  app: 종료 신호 수신 — HTTP 서버는 진행 중 요청을 기다린 뒤 종료" },
    { txt: "16:00:01 INFO  app: 후처리는 tokio::spawn 으로 띄우고 JoinHandle 을 버림", bad: true },
    { txt: "16:00:01 INFO  app: 런타임 종료 시 미완료 태스크는 그냥 취소됨" },
    { txt: "16:00:02 WARN  app: 진행 중이던 후처리 7건 중단" },
    { txt: "16:05:00 WARN  ops: 정산 누락 7건, 오류 로그는 없음" },
    { txt: "16:20:00 WARN  ops: 배포마다 비슷한 규모의 누락이 반복됨" },
  ],
  ex: "떼어 놓은 태스크는 <b>아무도 기다리지 않습니다</b>. 런타임이 내려가면 미완료 태스크는 조용히 취소되고, 실패가 아니라 <b>없던 일</b>이 되므로 로그조차 남지 않습니다. 처방은 손잡이를 모아 두었다가 종료 시 <code>JoinSet</code> 으로 <b>끝날 때까지 기다리는 것</b>이고, 유실되면 안 되는 일이라면 애초에 메모리 태스크가 아니라 <b>영속 큐</b>에 넣어야 합니다.",
},
{
  t: "log", k: "성공했다고 믿고 넘어간 값", cat: "logs", d: 2, track: "rust",
  file: "/var/log/ledger/app.log",
  q: "특정 사용자 데이터에서만 프로세스가 즉시 죽습니다. 원인 줄을 고르세요.",
  items: [
    { txt: "17:00:00 INFO  api: 프로필 조회 요청 처리 시작" },
    { txt: "17:00:00 INFO  api: 대부분 사용자에게는 birth_date 가 있음" },
    { txt: "17:00:01 INFO  api: 파싱 결과에 .unwrap() 사용 — 실패 시 패닉", bad: true },
    { txt: "17:00:02 INFO  db: 2013년 이전 가입자는 birth_date 가 빈 문자열" },
    { txt: "17:00:02 ERROR api: panic: called `Result::unwrap()` on an `Err` value" },
    { txt: "17:00:03 ERROR app: 워커 스레드 종료, 요청 500" },
  ],
  ex: "<code>unwrap()</code> 은 '실패할 리 없다' 는 <b>주장</b>입니다. 옛 데이터에 빈 값이 하나만 있어도 그 주장이 깨지고 프로세스가 죽습니다. 대부분 사용자에게는 값이 있다는 줄이 그 위험을 이미 보여 줍니다. 처방은 <code>?</code> 로 <b>오류를 위로 올리거나</b> <code>unwrap_or</code>·<code>match</code> 로 없는 경우를 값으로 다루는 것이고, 예방은 운영 경로에서 <code>unwrap</code>·<code>expect</code> 를 린트로 막는 것입니다.",
},
{
  t: "log", k: "한 줄씩 읽지 않고 통째로 읽었다", cat: "logs", d: 2, track: "rust",
  file: "/var/log/ledger/app.log",
  q: "파일이 커진 날부터 임포트 작업이 메모리 부족으로 죽습니다. 원인 줄을 고르세요.",
  items: [
    { txt: "18:00:00 INFO  import: 작업 시작, 입력 경로 확인" },
    { txt: "18:00:00 INFO  import: 대상 파일 4.8GB (지난달 900MB)" },
    { txt: "18:00:00 INFO  import: 컨테이너 메모리 한도 2GB" },
    { txt: "18:00:01 INFO  import: 처리 자체는 한 줄씩 독립적으로 가능" },
    { txt: "18:00:02 INFO  import: fs::read_to_string 으로 전체를 메모리에 적재", bad: true },
    { txt: "18:00:20 WARN  import: RSS 1.9GB, 아직 파싱 전" },
    { txt: "18:00:25 ERROR k8s: OOMKilled" },
  ],
  ex: "한 줄씩 처리하면 되는 일을 <b>통째로 올렸습니다</b>. 파일이 한도보다 커지면 파싱을 시작하기도 전에 죽고, 파일이 자라는 서비스에서는 시간 문제일 뿐이었습니다. 처방은 <code>BufReader::lines()</code> 로 <b>흘려보내며</b> 처리하는 것이고, 예방은 입력 크기를 로그에 남겨 <b>메모리 한도와 함께</b> 보는 것입니다.",
},
];
