/* ml 트랙 로그 분석 — 학습 로그가 남긴 증거로 원인을 짚는다.
   원인 줄을 일부러 INFO 등급에도 두고, 그 앞에 붉은 청어(먼저 뜬 WARN)를 깔았다.
   '첫 WARN 을 찍는다' 로는 못 맞히게 하려는 것이다. */
module.exports = [
{
  t: "log", k: "학습은 완벽한데 서비스에서 무너진다", cat: "logs", d: 3, track: "ml",
  file: "train.log",
  q: "오프라인 검증 점수는 0.99 인데 배포 첫날 0.71 로 떨어졌습니다. 가장 먼저 고쳐야 하는 원인 한 줄을 고르세요.",
  items: [
    { txt: "09:00:00 INFO  train: dataset 120,000 rows, 40 features, target=churn" },
    { txt: "09:00:05 WARN  train: 양성 비율 8% — 불균형 데이터" },
    { txt: "09:00:09 INFO  train: StandardScaler.fit(X_all) 실행 후 train/val 분할", bad: true },
    { txt: "09:00:40 INFO  train: epoch 1 val_auc 0.981" },
    { txt: "09:01:20 INFO  train: epoch 5 val_auc 0.994" },
    { txt: "09:32:10 WARN  serve: 실서비스 첫날 auc 0.71 (오프라인 대비 -0.28)" },
    { txt: "09:33:30 ERROR eval: 오프라인·온라인 지표 불일치로 배포 롤백" },
  ],
  ex: "전처리를 <b>전체 데이터로 먼저 학습</b>한 뒤 나눴습니다. 검증 세트의 평균과 분산이 스케일러를 통해 훈련에 새어 든 것이라, 검증 점수는 이미 검증 답안을 곁눈질한 점수입니다. 불균형 경고는 사실이지만 이 사고의 원인은 아닙니다 — 8% 양성으로도 auc 0.99 는 나오지 않습니다. 전처리는 <b>훈련으로만 fit 하고 검증에는 transform 만</b> 해야 하며, <code>Pipeline</code> 으로 묶으면 순서를 틀릴 수 없습니다.",
},
{
  t: "log", k: "loss 가 nan 으로 죽는다", cat: "logs", d: 2, track: "ml",
  file: "train.log",
  q: "학습 시작 1분 만에 loss 가 nan 이 되고 가중치가 전부 깨졌습니다. 원인 줄을 고르세요.",
  items: [
    { txt: "10:00:00 INFO  train: lr=0.30 batch=256 optimizer=SGD momentum=0.9" },
    { txt: "10:00:06 INFO  train: step 10 loss 2.29, 가중치 노름 정상" },
    { txt: "10:00:12 WARN  train: step 20 loss 2.31 → 4.90 (증가)" },
    { txt: "10:00:18 INFO  train: step 40 loss 6.02" },
    { txt: "10:00:24 WARN  train: step 60 grad_norm 1.2e+04, clip 설정 없음", bad: true },
    { txt: "10:00:30 ERROR train: step 80 loss nan" },
    { txt: "10:00:36 ERROR train: 가중치 전부 nan, 체크포인트 저장 중단" },
  ],
  ex: "기울기가 <b>1만 배로 폭발</b>했는데 자르지 않았습니다. 한 번의 갱신이 가중치를 유한 범위 밖으로 밀어내면 그 뒤 모든 계산이 nan 이 됩니다. loss 가 오르기 시작한 20 스텝은 <b>증상의 시작</b>이지 원인이 아닙니다 — lr 이 큰 채로 두면 어차피 발산합니다. 처방은 <code>clip_grad_norm_(params, 1.0)</code> 과 lr 을 10배 낮춰 다시 재는 것이고, 예방은 grad_norm 을 학습 지표로 함께 기록해 폭발을 <b>nan 이 되기 전에</b> 보는 것입니다.",
},
{
  t: "log", k: "배치를 키웠더니 OOM", cat: "logs", d: 2, track: "ml",
  file: "train.log",
  q: "어제까지 돌던 학습이 오늘 CUDA out of memory 로 죽습니다. 원인 줄을 고르세요.",
  items: [
    { txt: "11:00:00 INFO  train: GPU 0 memory 24GB, model params 1.3B" },
    { txt: "11:00:10 INFO  train: mixed precision(amp) 사용, optimizer=AdamW" },
    { txt: "11:00:20 WARN  train: dataloader 대기 220ms/step (GPU 유휴)" },
    { txt: "11:00:41 INFO  train: config batch_size 8 → 32 로 변경 (실험 가속 목적)", bad: true },
    { txt: "11:00:45 WARN  train: allocator 조각화 91%, reserved 22.4GB" },
    { txt: "11:00:47 ERROR train: CUDA out of memory. Tried to allocate 3.10 GiB" },
    { txt: "11:00:47 ERROR train: 프로세스 종료, epoch 0 체크포인트 없음" },
  ],
  ex: "배치를 4배로 키우면 활성값 메모리도 대략 4배가 됩니다. 파라미터·옵티마이저 상태는 그대로여도 <b>순전파에서 잡아 두는 중간 텐서</b>가 한계를 넘습니다. 조각화 경고와 OOM 은 그 뒤에 따라온 결과입니다. 데이터로더 대기는 별개의 병목이고, 그것을 고치려고 배치를 키운 것이 사고를 불렀습니다. 처방은 <b>gradient accumulation</b> — 배치 8로 4번 모아 갱신하면 메모리는 그대로 두고 유효 배치만 32가 됩니다.",
},
{
  t: "log", k: "정확도 0.999 가 반가운 적은 없다", cat: "logs", d: 3, track: "ml",
  file: "train.log",
  q: "검증 f1 이 0.998 인 모델이 운영에서는 한 건도 잡지 못합니다. 원인 줄을 고르세요.",
  items: [
    { txt: "12:00:00 INFO  train: features 41개, target=fraud" },
    { txt: "12:00:02 INFO  train: 특성 목록에 chargeback_at 포함 (사고 확정 뒤 기록되는 열)", bad: true },
    { txt: "12:00:30 WARN  train: 단일 특성 중요도 0.97, 나머지 40개 합 0.03" },
    { txt: "12:01:00 INFO  train: val accuracy 0.9993 f1 0.998" },
    { txt: "12:30:00 WARN  serve: 실시간 추론에서 chargeback_at 이 전부 null" },
    { txt: "12:31:00 ERROR serve: 예측 양성률 0.0%, 24시간 탐지 0건" },
  ],
  ex: "<b>미래에 생기는 값</b>을 특성으로 넣었습니다. 사고가 확정된 뒤에야 채워지는 열이므로, 학습 시점에는 정답을 그대로 알려 주는 것과 같고 추론 시점에는 언제나 비어 있습니다. 중요도 0.97 은 원인이 아니라 <b>가장 먼저 보이는 증상</b>입니다 — 한 특성이 모든 것을 설명하면 누수를 의심해야 합니다. 예방은 특성마다 <b>언제 채워지는 값인지</b>를 적어 두고, 추론 시점에 존재하지 않는 열을 자동으로 걸러내는 것입니다.",
},
{
  t: "log", k: "GPU 는 노는데 학습만 느리다", cat: "logs", d: 2, track: "ml",
  file: "train.log",
  q: "같은 모델·같은 데이터인데 학습이 열 배 느려졌습니다. 원인 줄을 고르세요.",
  items: [
    { txt: "13:00:00 INFO  train: GPU util 12%, step time 840ms" },
    { txt: "13:00:30 WARN  train: 예상 학습 시간 46시간 (지난주 4시간)" },
    { txt: "13:01:00 INFO  train: DataLoader(num_workers=0), 증강은 PIL 로 CPU 에서 수행", bad: true },
    { txt: "13:01:30 INFO  train: CPU 8코어 중 1코어만 100%, 나머지 유휴" },
    { txt: "13:02:00 WARN  train: GPU 유휴 88%" },
    { txt: "13:57:00 WARN  train: epoch 1/50 완료 (55분 소요)" },
  ],
  ex: "데이터를 만드는 쪽이 <b>한 프로세스에서 순서대로</b> 돌고 있습니다. GPU 는 다음 배치를 기다리느라 대부분 놀고, 한 코어만 증강으로 100% 입니다. GPU util 12% 와 예상 시간 46시간은 <b>같은 원인의 두 얼굴</b>이지 서로의 원인이 아닙니다. 처방은 <code>num_workers</code> 를 코어 수에 맞춰 올리고 <code>pin_memory=True</code>, <code>prefetch_factor</code> 를 주는 것입니다. 예방은 학습 지표에 <b>GPU util 과 데이터 대기 시간</b>을 항상 함께 남기는 것입니다.",
},
{
  t: "log", k: "검증 점수가 에폭마다 요동친다", cat: "logs", d: 3, track: "ml",
  file: "train.log",
  q: "검증 정확도가 0.52 → 0.78 → 0.41 로 튀어 어느 체크포인트를 써야 할지 알 수 없습니다. 원인 줄을 고르세요.",
  items: [
    { txt: "14:00:00 INFO  train: model=ResNet18 batch=2 (메모리 절약 목적)" },
    { txt: "14:00:10 INFO  train: 데이터 12,000장, 증강 randcrop+flip" },
    { txt: "14:00:20 INFO  train: epoch 1 train_acc 0.71 val_acc 0.52" },
    { txt: "14:01:00 WARN  train: val_acc 0.52 → 0.78 → 0.41 로 에폭마다 요동" },
    { txt: "14:01:30 INFO  train: BatchNorm running stats 가 샘플 2개짜리 배치로 갱신됨", bad: true },
    { txt: "14:02:00 WARN  eval: model.eval() 결과가 model.train() 결과와 0.30 차이" },
    { txt: "14:02:30 ERROR eval: 검증 점수를 신뢰할 수 없어 실험 중단" },
  ],
  ex: "<b>BatchNorm 은 배치 통계로 정규화</b>합니다. 배치가 2개면 평균과 분산이 표본 두 개로 정해져 에폭마다 전혀 다른 값이 running stats 에 쌓이고, 추론 때 쓰는 통계가 학습 때와 달라집니다. 요동치는 val_acc 와 train/eval 격차는 둘 다 그 결과입니다. 처방은 배치를 키우거나(누적으로 대신할 수 없습니다 — 정규화는 실제 배치 안에서 일어납니다) <b>GroupNorm·LayerNorm</b> 처럼 배치 크기와 무관한 정규화로 바꾸는 것입니다.",
},
{
  t: "log", k: "같은 명령을 세 번 돌리면 세 값이 나온다", cat: "logs", d: 2, track: "ml",
  file: "train.log",
  q: "하이퍼파라미터 탐색 결과를 재현할 수 없습니다. 원인 줄을 고르세요.",
  items: [
    { txt: "15:00:00 INFO  train: 같은 명령 3회 실행 비교 시작" },
    { txt: "15:00:10 WARN  train: run A val_f1 0.812, run B 0.774, run C 0.831" },
    { txt: "15:00:20 INFO  train: seed 미설정 — numpy·torch·DataLoader shuffle 모두 시스템 난수", bad: true },
    { txt: "15:00:40 INFO  train: 탐색 결과 lr=3e-4 채택 (2위와 차이 0.02)" },
    { txt: "15:40:00 WARN  train: 재현 실험에서 lr=3e-4 가 lr=1e-3 보다 낮게 나옴" },
    { txt: "15:41:00 ERROR train: 실험 비교가 무의미해져 탐색 전체 재실행" },
  ],
  ex: "씨앗을 고정하지 않아 <b>실행마다 다른 난수</b>로 초기화·셔플이 일어났습니다. 그 결과 편차가 0.06 인데 탐색은 0.02 차이로 승자를 골랐습니다 — <b>잡음을 보고 결정</b>한 것입니다. 세 값이 다르다는 경고는 증상이고, 재현 실패는 그 뒤의 일입니다. 처방은 seed 를 모두 고정하고, 그래도 남는 편차를 알기 위해 <b>같은 설정을 3회 이상 돌려 평균과 표준편차로</b> 비교하는 것입니다.",
},
{
  t: "log", k: "정확도 99.9% 인데 한 건도 못 잡는다", cat: "logs", d: 2, track: "ml",
  file: "train.log",
  q: "사기 탐지 모델이 학습은 성공했다는데 알림이 하루 종일 0건입니다. 원인 줄을 고르세요.",
  items: [
    { txt: "16:00:00 INFO  train: rows 2,000,000 · positive 1,940 (0.097%)" },
    { txt: "16:00:30 INFO  train: metric=accuracy, EarlyStopping(monitor='accuracy')" },
    { txt: "16:01:00 INFO  train: epoch 3 accuracy 0.99903" },
    { txt: "16:01:30 WARN  train: confusion matrix TP=0 FP=0 FN=1,940", bad: true },
    { txt: "16:02:00 INFO  train: 개선 없음 — 조기 종료, 최고 성능 체크포인트 저장" },
    { txt: "16:30:00 WARN  serve: 사기 탐지 알림 24시간 0건" },
    { txt: "16:31:00 ERROR serve: 미탐 피해 집계 시작" },
  ],
  ex: "모델이 <b>전부 음성이라고 답하는 법</b>을 배웠습니다. 양성이 0.097% 이므로 그렇게만 해도 정확도 99.903% 이고, 정확도를 감시하는 조기 종료는 그것을 최고 성능으로 저장합니다. 혼동 행렬의 TP=0 이 그 사실을 처음 드러낸 줄입니다. 처방은 지표를 <b>PR-AUC·재현율</b> 로 바꾸고 임계값을 비용으로 정하는 것이며, 불균형에서는 <b>정확도를 아예 기록하지 않는 것</b>이 가장 확실한 예방입니다.",
},
{
  t: "log", k: "조기 종료가 끝내 발동하지 않는다", cat: "logs", d: 3, track: "ml",
  file: "train.log",
  q: "60 에폭을 다 돌고 나온 모델이 10 에폭 시점보다 나쁩니다. 원인 줄을 고르세요.",
  items: [
    { txt: "17:00:00 INFO  train: EarlyStopping(monitor='loss', patience=5) 설정" },
    { txt: "17:00:30 INFO  train: epoch 10 loss 0.31 val_loss 0.44" },
    { txt: "17:01:00 INFO  train: 감시 대상 'loss' 는 훈련 손실 키다", bad: true },
    { txt: "17:01:30 WARN  train: val_loss 12 에폭 연속 상승 (0.44 → 0.71)" },
    { txt: "17:02:00 INFO  train: epoch 60 loss 0.004 — 조기 종료 미발동" },
    { txt: "17:03:00 WARN  eval: 최종 모델 val_f1 0.61 (10 에폭 시점 0.78)" },
  ],
  ex: "감시하는 키를 <b>훈련 손실</b>로 잡았습니다. 훈련 손실은 과적합이 진행될수록 계속 내려가므로 '개선 중' 으로 보이고, 조기 종료는 영원히 발동하지 않습니다. val_loss 상승 경고는 이미 늦은 증상입니다. 처방은 <code>monitor='val_loss'</code> 로 바꾸고 <code>restore_best_weights</code> 를 켜는 것이며, 예방은 <b>감시 키를 시작 로그에 그대로 찍어</b> 오타와 혼동을 눈으로 확인하는 것입니다.",
},
{
  t: "log", k: "체크포인트는 같은데 결과가 다르다", cat: "logs", d: 3, track: "ml",
  file: "serve.log",
  q: "학습 때와 같은 가중치를 올렸는데 운영 f1 이 절반입니다. 원인 줄을 고르세요.",
  items: [
    { txt: "18:00:00 INFO  serve: checkpoint epoch42.pt 로드 완료 (sha 일치)" },
    { txt: "18:00:02 INFO  serve: 모델 버전 v7, 학습 커밋 9f1c2a 와 일치" },
    { txt: "18:00:05 INFO  serve: 검증 세트 재현 점수 f1 0.79 (학습 때와 동일)" },
    { txt: "18:00:20 INFO  serve: 워커 4개 기동, 평균 지연 31ms" },
    { txt: "18:00:30 WARN  serve: 운영 트래픽 f1 0.42" },
    { txt: "18:00:40 INFO  serve: 전처리가 학습은 sklearn Pipeline, 서빙은 수기 구현", bad: true },
    { txt: "18:01:00 WARN  serve: 범주형 인코딩 순서가 학습(등장 순)과 다름(알파벳 순)" },
    { txt: "18:02:00 ERROR serve: 입력 분포 드리프트 경보 PSI 0.61" },
  ],
  ex: "가중치는 같지만 <b>모델에 들어가는 숫자가 다릅니다</b>. 전처리를 두 벌로 유지하면 언젠가 반드시 갈라지고, 여기서는 범주 인코딩 순서가 어긋나 같은 범주가 다른 정수로 들어갔습니다. 검증 세트 재현 점수가 멀쩡했던 것은 그 경로에서 학습 때의 파이프라인을 그대로 썼기 때문입니다. 처방은 전처리를 <b>모델과 함께 직렬화</b>해 하나만 두는 것이고, 예방은 배포 때 <b>같은 입력에 대한 전처리 출력</b>을 두 경로에서 비교하는 검사입니다.",
},
{
  t: "log", k: "GPU 를 여덟 배 썼는데 1.6배", cat: "logs", d: 3, track: "ml",
  file: "train.log",
  q: "분산 학습으로 바꿨는데 처리량이 기대만큼 늘지 않습니다. 원인 줄을 고르세요.",
  items: [
    { txt: "19:00:00 INFO  train: DDP 8 GPU, per-GPU batch 4" },
    { txt: "19:00:08 INFO  train: 8개 랭크 모두 초기화 완료, NCCL 백엔드" },
    { txt: "19:00:16 INFO  train: 첫 스텝 손실 8개 랭크 동일 (동기화 정상)" },
    { txt: "19:00:30 WARN  train: 1 GPU 대비 처리량 1.6배 (기대 6~7배)" },
    { txt: "19:01:00 INFO  train: all-reduce 가 step 마다 1.2GB, 인터커넥트 10GbE", bad: true },
    { txt: "19:01:30 INFO  train: 계산 90ms, 통신 대기 540ms" },
    { txt: "19:02:00 WARN  train: GPU util 평균 18%" },
    { txt: "19:03:00 WARN  cost: 시간당 요금 8배, 학습 시간 단축은 0.6배" },
  ],
  ex: "스텝마다 <b>1.2GB 를 10GbE 로 주고받습니다</b>. 산술만 해도 1초 가까이 걸리는 통신이라 90ms 짜리 계산이 통신에 파묻힙니다. 처리량 1.6배와 util 18% 는 같은 사실의 다른 표현입니다. 처방은 배치를 키워 <b>스텝당 통신 횟수를 줄이거나</b>, gradient bucketing·압축을 쓰거나, 애초에 인터커넥트가 빠른 노드를 쓰는 것입니다. 예방은 분산으로 바꾸기 전에 <b>계산 시간 대 통신량</b>을 먼저 재 보는 것입니다.",
},
{
  t: "log", k: "50 에폭이 1 에폭에서 멈췄다", cat: "logs", d: 3, track: "ml",
  file: "train.log",
  q: "학습은 50 에폭을 다 돌았는데 성능이 1 에폭 수준에 머물렀습니다. 원인 줄을 고르세요.",
  items: [
    { txt: "20:00:00 INFO  train: OneCycleLR(max_lr=0.01, total_steps=50), epochs=50" },
    { txt: "20:00:20 INFO  train: epoch 1 · 배치 50개 처리 완료" },
    { txt: "20:00:25 WARN  train: lr 0.01 → 0.0000 (1 에폭 만에 스케줄 종료)" },
    { txt: "20:00:30 INFO  train: scheduler.step() 이 배치 루프 안에 있음", bad: true },
    { txt: "20:05:00 WARN  train: epoch 2~50 동안 lr 0, loss 변화 없음" },
    { txt: "20:40:00 ERROR train: 최종 성능이 epoch 1 체크포인트와 동일" },
  ],
  ex: "<code>total_steps</code> 는 에폭 수로 주고 <code>step()</code> 은 배치마다 불렀습니다. 스케줄이 세는 단위와 호출 단위가 어긋나 첫 에폭에서 일정이 끝나 버렸고, 그 뒤 49 에폭은 lr 0 으로 <b>아무 것도 학습하지 않은 채</b> 흘렀습니다. lr 이 0 이 됐다는 경고는 증상입니다. 처방은 <code>total_steps=len(loader)*epochs</code> 로 맞추는 것이고, 예방은 <b>lr 을 스텝마다 기록</b>해 일정 곡선을 눈으로 확인하는 것입니다.",
},
];
