/* c 트랙 로그 분석 2 — 크래시·사니타이저·시스템 로그에서 원인을 짚는다. */
module.exports = [
{
  t: "log", k: "놓아준 뒤에 읽었다", cat: "logs", d: 3, track: "c",
  file: "/var/log/feed-daemon/crash.log",
  q: "부하가 높을 때만 값이 이상하거나 드물게 죽습니다. 원인 줄을 고르세요.",
  items: [
    { txt: "09:00:00 INFO  daemon: 세션 캐시 항목 4,200, 처리 정상" },
    { txt: "09:00:02 INFO  daemon: 만료 처리에서 free(session) 호출" },
    { txt: "09:00:03 INFO  daemon: 해시 테이블에는 같은 포인터가 그대로 남아 있음", bad: true },
    { txt: "09:04:10 WARN  daemon: 조회 결과 user_id 가 0 또는 쓰레기 값" },
    { txt: "09:04:40 ERROR asan: heap-use-after-free READ of size 8" },
    { txt: "09:04:40 ERROR daemon: SIGSEGV, 코어 덤프 생성" },
  ],
  ex: "메모리를 놓아준 뒤에도 <b>그것을 가리키는 포인터</b>가 남아 있었습니다. 할당기가 그 자리를 재사용하기 전까지는 옛 값이 그대로 읽히므로 한동안 멀쩡해 보이고, 재사용되는 순간 쓰레기 값이나 크래시가 됩니다. 쓰레기 값 경고가 먼저 나온 이유가 그것입니다. 처방은 <b>해제와 참조 제거를 한 함수에서</b> 함께 하고 해제 뒤 포인터를 <code>NULL</code> 로 만드는 것이며, 예방은 CI 에서 ASan 을 켜는 것입니다.",
},
{
  t: "log", k: "한 칸을 더 썼다", cat: "logs", d: 2, track: "c",
  file: "/var/log/feed-daemon/crash.log",
  q: "설정 값이 무작위로 초기화되는 것처럼 보입니다. 원인 줄을 고르세요.",
  items: [
    { txt: "10:00:00 INFO  daemon: 설정 로드(항목 16개) — int buf[16] 뒤에 int limit 선언" },
    { txt: "10:00:02 INFO  daemon: 채우기 루프 for (i = 0; i <= 16; i++)", bad: true },
    { txt: "10:00:03 INFO  daemon: buf[16] 쓰기가 limit 를 덮음" },
    { txt: "10:00:04 WARN  daemon: limit 값 500 → 0" },
    { txt: "10:00:10 WARN  daemon: 처리량 제한이 0 이 되어 모든 요청 거절" },
    { txt: "10:01:00 WARN  ops: 설정을 다시 올려도 잠시 뒤 같은 증상" },
  ],
  ex: "길이 16 배열의 유효한 인덱스는 0~15 인데 <code>&lt;=</code> 때문에 <b>한 칸을 더</b> 썼습니다. 스택에서는 그 자리에 다른 변수가 있으므로, 크래시 없이 <b>남의 값이 바뀝니다</b>. 요청 거절은 그 결과입니다. 처방은 <code>i &lt; n</code> 으로 고치는 것이고, 예방은 크기를 <code>sizeof(buf)/sizeof(buf[0])</code> 로 계산해 상수를 두 번 적지 않는 것입니다.",
},
{
  t: "log", k: "돌아간 뒤에도 살아 있을 줄 알았다", cat: "logs", d: 3, track: "c",
  file: "/var/log/feed-daemon/crash.log",
  q: "함수가 돌려준 문자열이 때때로 깨져 있습니다. 원인 줄을 고르세요.",
  items: [
    { txt: "11:00:00 INFO  daemon: 포맷 함수 호출 12,000회, 대부분 정상" },
    { txt: "11:00:00 INFO  daemon: 입력 문자열은 항상 64자 미만" },
    { txt: "11:00:01 INFO  daemon: 함수 안에서 char tmp[64] 로 문자열 구성" },
    { txt: "11:00:02 INFO  daemon: return tmp; 로 지역 배열 주소를 반환", bad: true },
    { txt: "11:00:03 INFO  daemon: 호출자가 곧바로 쓰면 값이 남아 있어 정상처럼 보임" },
    { txt: "11:00:20 WARN  daemon: 다른 함수 호출을 한 번 거치면 내용이 깨짐" },
    { txt: "11:00:30 ERROR daemon: 로그에 제어문자 섞임, 파서 중단" },
  ],
  ex: "지역 배열은 <b>함수가 끝나면 사라지는 스택 공간</b>입니다. 그 주소를 돌려주면 다음 호출이 같은 자리를 덮어쓸 때까지만 우연히 맞습니다 — 그래서 '가끔' 깨집니다. 처방은 호출자가 준 버퍼에 <b>채워 주는 형태</b>(<code>void fmt(char *out, size_t n, ...)</code>)로 바꾸거나, 동적 할당해 주고 <b>누가 해제하는지</b>를 문서로 정하는 것입니다.",
},
{
  t: "log", k: "형식 문자열이 거짓말한다", cat: "logs", d: 2, track: "c",
  file: "/var/log/feed-daemon/app.log",
  q: "64비트 장비에서만 로그 숫자가 엉뚱합니다. 원인 줄을 고르세요.",
  items: [
    { txt: "12:00:00 INFO  daemon: 32비트 장비에서는 값이 정상 출력됨" },
    { txt: "12:00:01 INFO  daemon: 처리 바이트 수는 long long 으로 누적" },
    { txt: "12:00:02 INFO  daemon: 컴파일 경고 -Wformat 은 꺼져 있음" },
    { txt: "12:00:03 INFO  daemon: printf(\"bytes=%d\\n\", total) 로 출력", bad: true },
    { txt: "12:00:04 WARN  daemon: bytes=-1794967296 (실제 2,500,000,000)" },
    { txt: "12:00:30 WARN  ops: 사용량 집계가 음수로 청구됨" },
  ],
  ex: "형식 지정자와 인자의 <b>크기가 다릅니다</b>. <code>%d</code> 는 4바이트를 꺼내는데 실제 값은 8바이트라, 아키텍처와 호출 규약에 따라 잘리거나 엉뚱한 값이 나옵니다. 32비트에서 맞았던 것은 우연입니다. 처방은 <code>%lld</code>(또는 <code>PRId64</code>)를 쓰는 것이고, 예방은 <code>-Wformat -Werror</code> 로 <b>컴파일러가 먼저 잡게</b> 하는 것입니다.",
},
{
  t: "log", k: "두 번 놓아준 메모리", cat: "logs", d: 3, track: "c",
  file: "/var/log/feed-daemon/crash.log",
  q: "오류 경로로 들어갈 때만 프로세스가 중단됩니다. 원인 줄을 고르세요.",
  items: [
    { txt: "13:00:00 INFO  daemon: 정상 경로는 하루 200만 건 무사고" },
    { txt: "13:00:00 INFO  daemon: 파싱 실패율 0.4% (평소 수준)" },
    { txt: "13:00:01 INFO  daemon: 파싱 실패 시 cleanup(ctx) 호출" },
    { txt: "13:00:02 INFO  daemon: cleanup 안에서 free(ctx->buf)" },
    { txt: "13:00:03 INFO  daemon: 호출자도 오류 처리 끝에 free(ctx->buf) 를 다시 호출", bad: true },
    { txt: "13:00:04 ERROR glibc: free(): double free or corruption (fasttop)" },
    { txt: "13:00:04 ERROR daemon: SIGABRT" },
  ],
  ex: "같은 메모리를 <b>두 곳에서</b> 놓아주었습니다. 할당기의 내부 목록이 망가지면 그 자리에서 죽거나, 더 나쁘게는 <b>한참 뒤 엉뚱한 곳</b>에서 죽습니다. 정상 경로가 무사고였던 것은 그 길로 가지 않았기 때문입니다. 처방은 <b>해제 책임을 한 곳에 몰아주는 것</b> — 만든 쪽이 놓거나, cleanup 만 놓게 하고 호출자는 손대지 않는 규칙을 문서와 이름으로 못박습니다. 해제 뒤 <code>NULL</code> 대입도 도움이 됩니다.",
},
{
  t: "log", k: "곱하다 넘친 크기", cat: "logs", d: 4, track: "c",
  file: "/var/log/feed-daemon/crash.log",
  q: "아주 큰 입력을 주면 크래시가 나고 보안팀이 익스플로잇 가능성을 지적했습니다. 원인 줄을 고르세요.",
  items: [
    { txt: "14:00:00 INFO  daemon: 요청 헤더에 개수 필드 count 존재" },
    { txt: "14:00:01 INFO  daemon: count 상한 검사 없음, 타입은 unsigned int" },
    { txt: "14:00:02 INFO  daemon: malloc(count * sizeof(item)) 로 버퍼 확보", bad: true },
    { txt: "14:00:03 INFO  daemon: count=1,073,741,825 · sizeof(item)=4 → 곱셈 결과 4" },
    { txt: "14:00:04 INFO  daemon: malloc 성공(4바이트), 이후 루프가 전부 기록" },
    { txt: "14:00:04 ERROR asan: heap-buffer-overflow WRITE of size 4" },
    { txt: "14:00:05 ERROR daemon: 힙 메타데이터 손상, 임의 코드 실행 가능성" },
  ],
  ex: "크기 계산에서 <b>곱셈이 넘쳤습니다</b>. 결과가 작은 값으로 감싸 돌아 <code>malloc</code> 은 성공하고, 그 뒤 루프가 힙을 마음껏 넘어 씁니다. 할당 성공이 안전을 뜻하지 않는다는 것이 핵심입니다. 처방은 곱하기 전에 <b>넘침을 검사</b>하거나(<code>count &gt; SIZE_MAX / sizeof(item)</code>), <code>calloc</code> 처럼 검사해 주는 함수를 쓰는 것이고, 입력에는 반드시 상한을 두어야 합니다.",
},
{
  t: "log", k: "문자로 받은 EOF", cat: "logs", d: 3, track: "c",
  file: "/var/log/feed-daemon/app.log",
  q: "특정 바이너리 입력에서 읽기 루프가 끝나지 않거나 일찍 끝납니다. 원인 줄을 고르세요.",
  items: [
    { txt: "15:00:00 INFO  daemon: 텍스트 입력은 정상 처리" },
    { txt: "15:00:01 INFO  daemon: 이 플랫폼의 char 는 부호 있음" },
    { txt: "15:00:02 INFO  daemon: 읽기 루프가 char c = getchar(); while (c != EOF)", bad: true },
    { txt: "15:00:03 INFO  daemon: 입력에 0xFF 바이트 포함" },
    { txt: "15:00:04 WARN  daemon: 0xFF 가 -1 로 해석되어 EOF 와 구별되지 않음" },
    { txt: "15:00:05 WARN  daemon: 파일 중간에서 읽기 종료, 뒤 12MB 무시" },
  ],
  ex: "<code>getchar()</code> 가 <code>int</code> 를 돌려주는 이유가 여기 있습니다. 모든 바이트 값(0~255)과 <b>구별되는 EOF(-1)</b>를 함께 표현해야 하기 때문입니다. 결과를 <code>char</code> 에 담으면 0xFF 가 -1 이 되어 데이터 한가운데서 끝나거나(부호 있는 char), EOF 를 영영 못 만납니다(부호 없는 char). 처방은 <code>int c = getchar();</code> 로 받는 것입니다.",
},
{
  t: "log", k: "오류 경로에서만 새는 메모리", cat: "logs", d: 2, track: "c",
  file: "/var/log/feed-daemon/app.log",
  q: "정상일 때는 안정적인데 오류가 잦은 날에만 메모리가 오릅니다. 원인 줄을 고르세요.",
  items: [
    { txt: "16:00:00 INFO  daemon: RSS 180MB 안정, 오류율 0.01%" },
    { txt: "16:00:00 INFO  daemon: 힙 프로파일 평탄" },
    { txt: "16:00:01 INFO  daemon: 요청마다 buf = malloc(...) 로 시작" },
    { txt: "16:20:00 WARN  upstream: 오류율 0.01% → 12%" },
    { txt: "16:20:01 INFO  daemon: 검증 실패 시 free 없이 return -1", bad: true },
    { txt: "16:40:00 WARN  valgrind: definitely lost 412,000 blocks" },
    { txt: "17:30:00 ERROR daemon: RSS 2.4GB, OOM killer 에 의해 종료" },
  ],
  ex: "성공 경로에는 <code>free</code> 가 있지만 <b>중간에 빠져나가는 길</b>에는 없었습니다. 오류가 드물 때는 티가 안 나다가 오류율이 오르면 그대로 메모리 증가가 됩니다. 상류 오류율 상승은 방아쇠일 뿐입니다. 처방은 <b>정리 코드를 한 곳에 모으는 것</b> — <code>goto cleanup;</code> 으로 모든 실패 경로가 같은 출구를 지나게 하면 빠뜨릴 수 없습니다.",
},
{
  t: "log", k: "신호 처리기 안에서 부른 것", cat: "logs", d: 4, track: "c",
  file: "/var/log/feed-daemon/app.log",
  q: "종료 신호를 보내면 가끔 프로세스가 멈춘 채 남습니다. 원인 줄을 고르세요.",
  items: [
    { txt: "17:00:00 INFO  daemon: 작업 스레드가 로그를 기록하는 중" },
    { txt: "17:00:00 INFO  daemon: 로그 함수는 내부적으로 malloc 을 사용" },
    { txt: "17:00:01 INFO  daemon: SIGTERM 수신" },
    { txt: "17:00:01 INFO  daemon: 신호 처리기가 printf 로 종료 메시지 출력", bad: true },
    { txt: "17:00:01 WARN  daemon: 할당기 잠금을 이미 쥔 상태에서 다시 요구" },
    { txt: "17:00:02 WARN  ops: 프로세스 CPU 0%, 응답 없음 — SIGKILL 로만 종료" },
  ],
  ex: "신호 처리기는 <b>아무 때나 끼어듭니다</b>. 잠금을 쥐고 있는 순간에 끼어들어 같은 잠금을 요구하는 함수(<code>printf</code>·<code>malloc</code>)를 부르면 자기 자신을 기다리는 교착이 됩니다. 처방은 처리기 안에서 <b>async-signal-safe 한 것만</b> 하는 것 — 보통은 플래그 하나를 <code>volatile sig_atomic_t</code> 에 세우고 <b>주 루프가 그것을 보고</b> 정리하게 만듭니다.",
},
{
  t: "log", k: "스택을 넘어선 복사", cat: "logs", d: 2, track: "c",
  file: "/var/log/feed-daemon/crash.log",
  q: "긴 사용자 이름을 넣으면 프로세스가 즉시 중단됩니다. 원인 줄을 고르세요.",
  items: [
    { txt: "18:00:00 INFO  daemon: 이름 필드 처리(평균 12자), 로컬 버퍼 char name[32]" },
    { txt: "18:00:02 INFO  daemon: 입력 길이 검사 없이 strcpy(name, input)", bad: true },
    { txt: "18:00:03 INFO  daemon: 입력 길이 512자" },
    { txt: "18:00:03 ERROR libc: *** stack smashing detected ***" },
    { txt: "18:00:03 ERROR daemon: SIGABRT, 재시작" },
    { txt: "18:00:20 WARN  ops: 같은 입력으로 언제든 재현 가능" },
  ],
  ex: "<code>strcpy</code> 는 <b>목적지 크기를 모릅니다</b>. 32바이트 버퍼에 512바이트를 밀어 넣으면 스택의 반환 주소까지 덮이고, 스택 보호 장치가 감지해 프로세스를 끝냅니다(감지되지 않았다면 임의 코드 실행입니다). 처방은 길이를 아는 복사(<code>snprintf</code>·<code>strlcpy</code>)를 쓰고 <b>입력 길이를 먼저 검사</b>하는 것이며, 예방은 위험한 함수 목록을 정적 분석으로 금지하는 것입니다.",
},
];
