/* python 트랙 로그 분석 2 — 워커·배치 로그에서 원인을 짚는다. */
module.exports = [
{
  t: "log", k: "서머타임 하루의 두 시", cat: "logs", d: 3, track: "python",
  file: "/var/log/billing-worker/app.log",
  q: "연 두 번, 특정 날짜에만 청구가 중복되거나 누락됩니다. 원인 줄을 고르세요.",
  items: [
    { txt: "01:00:00 INFO  billing: 시간별 사용량 집계 시작 (지역 America/New_York)" },
    { txt: "01:00:00 INFO  billing: 입력 레코드 수 42,180, 전날과 비슷" },
    { txt: "01:00:01 INFO  billing: 요금표 버전 v9 (변경 없음)" },
    { txt: "01:00:01 INFO  billing: 구간 계산에 naive datetime + timedelta(hours=1) 사용", bad: true },
    { txt: "01:00:02 INFO  billing: 구간 01:00~02:00 처리" },
    { txt: "01:00:03 INFO  billing: 구간 01:00~02:00 처리 (같은 벽시계 시각이 두 번 존재)" },
    { txt: "01:30:00 WARN  billing: 같은 사용량 레코드가 두 청구서에 포함" },
    { txt: "02:00:00 WARN  ops: 3월에는 반대로 한 시간치가 통째로 누락됨" },
  ],
  ex: "시간대 정보가 없는 시각에 <code>timedelta</code> 를 더하면 <b>벽시계로만</b> 계산됩니다. 서머타임이 끝나는 날에는 같은 벽시계 시각이 두 번 오고, 시작하는 날에는 한 시간이 사라지므로 중복과 누락이 함께 생깁니다. 처방은 <b>UTC 로 계산하고 표시할 때만</b> 지역 시간으로 바꾸는 것이며, 지역 시간으로 더해야 한다면 <code>zoneinfo</code> 로 aware 하게 만든 뒤 절대 시간(<code>timestamp</code>)에서 더해야 합니다.",
},
{
  t: "log", k: "1원이 계속 모자란다", cat: "logs", d: 2, track: "python",
  file: "/var/log/billing-worker/app.log",
  q: "정산 합계가 항목 합과 몇 원씩 어긋납니다. 원인 줄을 고르세요.",
  items: [
    { txt: "09:00:00 INFO  settle: 항목 128,400건 합산 시작" },
    { txt: "09:00:04 INFO  settle: 원장 조회 성공, 누락 항목 0" },
    { txt: "09:00:07 INFO  settle: 통화 단위 KRW 단일" },
    { txt: "09:00:10 INFO  settle: 금액을 float 로 읽어 누적", bad: true },
    { txt: "09:00:40 INFO  settle: 합계 8,214,993.9999999991" },
    { txt: "09:00:41 INFO  settle: round(합계, 0) → 8,214,994" },
    { txt: "09:01:00 WARN  settle: 원장 합계와 3원 차이" },
    { txt: "09:30:00 WARN  audit: 차이가 매일 다르고 재현되지 않음" },
  ],
  ex: "<b>이진 부동소수</b>는 0.1 을 정확히 담지 못합니다. 12만 건을 누적하면 오차가 쌓여 마지막 반올림에서 몇 원이 갈리고, 데이터 순서가 바뀌면 값도 바뀌므로 재현되지 않습니다. 3원 차이는 결과일 뿐입니다. 처방은 돈을 <code>Decimal</code> 로 다루거나 <b>최소 단위(원·센트)의 정수</b>로 저장하는 것이고, 예방은 금액 컬럼을 <code>NUMERIC</code> 으로 두어 데이터베이스에서부터 float 이 되지 않게 하는 것입니다.",
},
{
  t: "log", k: "내 파일이 표준 모듈을 가렸다", cat: "logs", d: 2, track: "python",
  file: "/var/log/report-svc/app.log",
  q: "새 파일 하나를 추가했을 뿐인데 관계없는 기능이 깨졌습니다. 원인 줄을 고르세요.",
  items: [
    { txt: "10:00:00 INFO  app: 기동, 작업 디렉터리 /srv/report" },
    { txt: "10:00:01 INFO  app: 어제 추가된 파일 /srv/report/queue.py" },
    { txt: "10:00:02 INFO  app: sys.path[0] 는 스크립트가 있는 디렉터리", bad: true },
    { txt: "10:00:03 WARN  app: import queue → /srv/report/queue.py 로 해석됨" },
    { txt: "10:00:04 ERROR app: AttributeError: module 'queue' has no attribute 'Queue'" },
    { txt: "10:00:05 ERROR app: 스레드 풀 초기화 실패, 종료" },
  ],
  ex: "파이썬은 <b>스크립트가 있는 디렉터리를 먼저</b> 뒤집니다. 그래서 표준 라이브러리와 같은 이름의 파일을 만들면 그 파일이 표준 모듈을 가리고, 엉뚱한 곳에서 <code>AttributeError</code> 가 납니다. 처방은 파일 이름을 바꾸는 것이고(<code>queue.py</code> → <code>job_queue.py</code>), 예방은 코드를 <b>패키지 안</b>에 두고 진입점만 최상위에 남기는 것 — 그러면 최상위에 흔한 이름의 파일이 생길 일이 없습니다.",
},
{
  t: "log", k: "로그가 세 번씩 찍힌다", cat: "logs", d: 2, track: "python",
  file: "/var/log/report-svc/app.log",
  q: "같은 로그가 여러 줄씩 중복되고 디스크가 빨리 찹니다. 원인 줄을 고르세요.",
  items: [
    { txt: "11:00:00 INFO  app: 워커 3개 기동" },
    { txt: "11:00:00 INFO  app: 로그 레벨 INFO, 파일 핸들러 1개 예정" },
    { txt: "11:00:01 INFO  app: 각 모듈이 import 시점에 logging.basicConfig() 호출", bad: true },
    { txt: "11:00:02 INFO  app: 루트 로거 핸들러 3개 등록됨" },
    { txt: "11:00:03 INFO  job: 시작" },
    { txt: "11:00:03 INFO  job: 시작" },
    { txt: "11:00:03 INFO  job: 시작" },
    { txt: "11:40:00 WARN  ops: 로그 볼륨 하루 40GB, 보관 기간 3일로 축소" },
  ],
  ex: "핸들러가 <b>루트 로거에 세 번</b> 붙었습니다. 로그 레코드는 상위 로거로 전파되며 붙어 있는 핸들러마다 한 번씩 출력되므로, 핸들러 수만큼 줄이 늘어납니다. 40GB 는 그 결과입니다. 처방은 로깅 설정을 <b>진입점에서 한 번만</b> 하고 모듈에서는 <code>logging.getLogger(__name__)</code> 만 쓰는 것이며, 예방은 설정을 <code>dictConfig</code> 로 한곳에 모으는 것입니다.",
},
{
  t: "log", k: "포크한 자식이 잠긴 채 태어난다", cat: "logs", d: 4, track: "python",
  file: "/var/log/report-svc/app.log",
  q: "멀티프로세싱으로 바꾼 뒤 자식 프로세스가 무작위로 멈춥니다. 원인 줄을 고르세요.",
  items: [
    { txt: "12:00:00 INFO  app: 기동 완료, 요청 처리 정상" },
    { txt: "12:00:00 INFO  app: 백그라운드 로깅 스레드 1개 실행 중" },
    { txt: "12:00:01 INFO  app: 메트릭 전송 스레드 1개 실행 중" },
    { txt: "12:00:02 INFO  pool: multiprocessing 시작 방식 fork (리눅스 기본)", bad: true },
    { txt: "12:00:03 INFO  pool: 자식 8개 생성" },
    { txt: "12:00:04 WARN  pool: 자식 3개가 첫 로그 출력에서 멈춤" },
    { txt: "12:05:00 WARN  pool: 멈춘 자식은 CPU 0%, 스택은 lock.acquire" },
    { txt: "12:10:00 ERROR app: 작업 큐 적체, 타임아웃 처리" },
  ],
  ex: "<code>fork</code> 는 <b>메모리는 복사하고 스레드는 복사하지 않습니다</b>. 부모의 다른 스레드가 잠금을 쥔 순간 포크되면, 자식에는 <b>영원히 풀리지 않는 잠금</b>만 남아 첫 로그 출력에서 멈춥니다. 무작위로 보이는 이유가 그것입니다. 처방은 시작 방식을 <code>spawn</code> 으로 바꾸는 것이고(자식이 깨끗하게 시작합니다), 그럴 수 없다면 <b>스레드를 띄우기 전에</b> 프로세스 풀을 먼저 만들어야 합니다.",
},
{
  t: "log", k: "두 번째로 훑을 때는 비어 있다", cat: "logs", d: 2, track: "python",
  file: "/var/log/report-svc/app.log",
  q: "집계 결과의 절반이 0 으로 나옵니다. 예외는 없습니다. 원인 줄을 고르세요.",
  items: [
    { txt: "13:00:00 INFO  report: rows = (r for r in read_csv(...)) 로 1차 집계 완료 (건수 84,120)" },
    { txt: "13:00:02 INFO  report: 2차 집계 — 같은 rows 를 다시 순회", bad: true },
    { txt: "13:00:02 INFO  report: 2차 집계 건수 0" },
    { txt: "13:00:03 WARN  report: 평균·최대 항목이 모두 0 으로 기록됨" },
    { txt: "13:10:00 WARN  qa: 오류 로그 없음 — 숫자만 틀림" },
    { txt: "13:20:00 WARN  ops: 리포트 수치가 전날 대비 절반" },
  ],
  ex: "제너레이터는 <b>한 번 흐르면 끝</b>입니다. 다시 순회하면 예외 없이 빈 것으로 취급되므로 합계가 0 이 되고, 로그에는 아무 것도 남지 않습니다. 건수가 0 으로 찍힌 것이 그 사실을 조용히 알려 준 기록입니다. 처방은 두 번 이상 볼 데이터라면 <code>list()</code> 로 <b>실체화</b>하거나, 한 번의 순회에서 필요한 값을 <b>모두 함께</b> 계산하는 것입니다. 예방은 집계 함수가 <b>건수 0</b>을 만나면 경고를 남기게 하는 것입니다.",
},
{
  t: "log", k: "장비를 옮기니 한글이 깨진다", cat: "logs", d: 2, track: "python",
  file: "/var/log/report-svc/app.log",
  q: "같은 코드가 개발 장비에서는 되고 배포 컨테이너에서만 실패합니다. 원인 줄을 고르세요.",
  items: [
    { txt: "14:00:00 INFO  app: 적재 작업 시작, 대상 테이블 orders" },
    { txt: "14:00:00 INFO  app: 개발 장비에서 같은 파일 적재 성공 이력 있음" },
    { txt: "14:00:00 INFO  app: 입력 파일 orders-2026-08.csv (UTF-8, 한글 포함)" },
    { txt: "14:00:01 INFO  app: 컨테이너 로케일 LANG=C, 기본 인코딩 ascii" },
    { txt: "14:00:02 INFO  app: open(path) 호출 — encoding 인자 없음", bad: true },
    { txt: "14:00:03 WARN  app: 첫 1,204행은 정상 처리 (ASCII 만 있는 구간)" },
    { txt: "14:00:04 ERROR app: UnicodeDecodeError: 'ascii' codec can't decode byte 0xed" },
    { txt: "14:00:05 ERROR app: 적재 중단, 부분 커밋 상태로 종료" },
  ],
  ex: "<code>open()</code> 은 인코딩을 안 주면 <b>실행 환경의 기본값</b>을 씁니다. 개발 장비는 UTF-8, 컨테이너는 ascii 라 같은 파일이 다르게 읽히고, 한글이 처음 나오는 행에서 터집니다. ASCII 구간이 먼저 통과한 것이 문제를 늦게 드러냈습니다. 처방은 <code>open(path, encoding=\"utf-8\")</code> 로 <b>항상 명시</b>하는 것이고, 예방은 컨테이너에 <code>PYTHONUTF8=1</code> 을 두어 기본값 자체를 고정하는 것입니다.",
},
{
  t: "log", k: "요청은 살아 있는데 워커가 죽는다", cat: "logs", d: 3, track: "python",
  file: "/var/log/report-svc/gunicorn.log",
  q: "무거운 리포트 요청만 항상 실패하고 서버 오류 로그에는 원인이 없습니다. 원인 줄을 고르세요.",
  items: [
    { txt: "15:00:00 INFO  gunicorn: 워커 4, 클래스 sync, timeout 30" },
    { txt: "15:00:02 INFO  api: 짧은 요청은 p95 60ms 로 정상" },
    { txt: "15:00:10 INFO  api: POST /reports 접수, 예상 처리 90초" },
    { txt: "15:00:20 INFO  api: 처리 진행 중, DB 스캔 40% " },
    { txt: "15:00:30 INFO  gunicorn: 워커 타임아웃은 요청 처리 시간에 걸린다", bad: true },
    { txt: "15:00:30 WARN  gunicorn: [CRITICAL] WORKER TIMEOUT (pid:31)" },
    { txt: "15:00:30 ERROR gunicorn: 워커 강제 종료·재기동, 클라이언트에 502" },
    { txt: "15:00:31 WARN  db: 진행 중이던 트랜잭션 롤백" },
  ],
  ex: "동기 워커의 <code>timeout</code> 은 유휴 시간이 아니라 <b>요청 처리 시간</b>에 걸립니다. 90초짜리 작업은 30초에 반드시 죽고, 죽인 쪽이 워커 관리자라 애플리케이션 로그에는 원인이 남지 않습니다. 처방은 <b>긴 작업을 요청 밖으로</b> 빼는 것 — 큐에 넣고 즉시 접수 응답을 준 뒤 결과를 따로 받게 합니다. 임시로 timeout 을 늘릴 수는 있지만, 그 사이 워커 하나가 통째로 묶인다는 사실은 그대로입니다.",
},
{
  t: "log", k: "설치는 됐는데 안 보인다", cat: "logs", d: 2, track: "python",
  file: "/var/log/report-svc/deploy.log",
  q: "패키지를 설치했는데도 서비스가 ModuleNotFoundError 로 죽습니다. 원인 줄을 고르세요.",
  items: [
    { txt: "16:00:00 INFO  deploy: 배포 산출물 내려받기 완료" },
    { txt: "16:00:00 INFO  deploy: pip install -r requirements.txt 성공 (42개)" },
    { txt: "16:00:02 INFO  deploy: requirements.txt 에 httpx 포함 확인" },
    { txt: "16:00:05 INFO  deploy: which pip → /usr/bin/pip (python 3.9)" },
    { txt: "16:00:06 INFO  deploy: 서비스 실행 명령은 /opt/venv/bin/python app.py", bad: true },
    { txt: "16:00:10 WARN  systemd: app.service 시작" },
    { txt: "16:00:11 ERROR app: ModuleNotFoundError: No module named 'httpx'" },
    { txt: "16:00:12 ERROR systemd: 재시작 3회 후 실패 상태" },
  ],
  ex: "설치한 인터프리터와 실행하는 인터프리터가 <b>다릅니다</b>. <code>pip</code> 는 시스템 파이썬에 넣었고 서비스는 가상환경으로 도니, 설치는 성공했는데도 모듈이 없습니다. 처방은 <code>/opt/venv/bin/python -m pip install ...</code> 처럼 <b>실행할 인터프리터로</b> 설치하는 것이고, 예방은 배포 스크립트에서 <code>python -m pip</code> 형태만 쓰고 <code>pip</code> 단독 호출을 금지하는 것입니다.",
},
{
  t: "log", k: "인스턴스마다 다른 줄 알았던 목록", cat: "logs", d: 3, track: "python",
  file: "/var/log/report-svc/app.log",
  q: "사용자 A 의 장바구니에 B 의 상품이 섞여 나옵니다. 원인 줄을 고르세요.",
  items: [
    { txt: "17:00:00 INFO  app: 세션 분리 정상, 인증 토큰 사용자별 상이" },
    { txt: "17:00:00 INFO  app: 요청 스레드마다 독립된 컨텍스트" },
    { txt: "17:00:00 INFO  app: 요청마다 Cart() 인스턴스를 새로 생성" },
    { txt: "17:00:01 INFO  app: class Cart 에 items = [] 를 클래스 본문에 선언", bad: true },
    { txt: "17:00:02 INFO  app: 사용자 A 담기 → len(items) 1" },
    { txt: "17:00:03 INFO  app: 사용자 B 담기 → len(items) 2" },
    { txt: "17:00:10 WARN  app: 서로 다른 세션의 장바구니 내용이 합쳐짐" },
    { txt: "17:30:00 ERROR ops: 잘못된 결제 4건 환불" },
  ],
  ex: "클래스 본문에 쓴 <code>items = []</code> 는 <b>클래스에 하나만</b> 존재합니다. 인스턴스를 새로 만들어도 같은 리스트를 가리키므로 모든 사용자가 한 바구니를 공유합니다. 인스턴스별로 두려면 <code>__init__</code> 안에서 <code>self.items = []</code> 로 만들어야 합니다. 같은 함정이 <b>기본 인자</b>에도 있습니다(<code>def f(xs=[])</code>) — 기본값은 정의 시점에 한 번만 만들어집니다.",
},
];
