/* 로그 분석 20문항 — linux 10 · cloud 10.
   두 트랙 모두 log 가 0이었다. 서버와 클라우드야말로 로그로 먹고사는 자리인데.

   설계 원칙(ver_log.cjs 가 검사하는 것들):
     · 원인 줄은 대개 INFO 다 — ERROR 는 뒤따라온 증상이라, 등급으로 찍히면 훈련이 안 된다
     · 그래서 앞쪽에 상관없는 WARN 을 하나 두어 '첫 WARN 이상' 규칙을 깬다
     · 원인 줄은 로그답게 짧게 쓰고, 세부(파일·수치·요청 ID)는 증상 줄에 붙인다
     · 자리를 흩어 둔다 */
module.exports = [

/* ══════════════ linux ══════════════ */
{
  t: "log", k: "쓸 공간은 남았는데 못 쓴다", cat: "logs", d: 3, track: "linux",
  file: "/var/log/syslog",
  q: "디스크 사용률이 61% 인데 파일 생성이 전부 실패합니다. 원인이 되는 한 줄을 고르세요.",
  items: [
    { txt: "09:11:58 INFO  cron[2210]: (root) CMD (/srv/etl/rotate.sh)", bad: false },
    { txt: "09:12:02 INFO  rotate[2211]: unpacked 4,120,000 session files into /var/spool/sess", bad: false },
    { txt: "09:12:03 INFO  df[2260]: /dev/sda1 inode 65.5M total, 65.5M used, 0 free", bad: true },
    { txt: "09:12:05 INFO  df[2260]: /dev/sda1 block 1.0T total, 612G used, 388G avail", bad: false },
    { txt: "09:12:41 ERROR app[1180]: open('/var/spool/sess/9f21.tmp'): No space left on device", bad: false },
    { txt: "09:12:42 WARN  app[1180]: falling back to /tmp, retry 1 of 3", bad: false },
    { txt: "09:12:43 ERROR app[1180]: session store unavailable, returning 500 to 812 clients", bad: false },
    { txt: "09:13:02 INFO  monitor[900]: disk 61 percent", bad: false },
  ],
  ex: "리눅스 파일 시스템은 <b>블록</b>과 <b>아이노드</b>를 따로 셉니다. 블록은 파일의 내용이 차지하는 공간이고 아이노드는 파일 하나하나의 기록입니다. 작은 파일을 수백만 개 만들면 용량은 남아도 아이노드가 먼저 바닥나고, 그때 커널이 돌려주는 오류가 하필 <code>No space left on device</code> 라서 용량 문제로 착각하기 딱 좋습니다. <code>df</code> 만 보면 61% 라 아무 문제가 없어 보이고, <code>df -i</code> 를 봐야 100% 가 드러납니다. 나머지 줄은 전부 그 뒤에 따라온 증상입니다. 고칠 곳은 세션 파일을 잘게 쪼개 쌓아 두는 쪽이지 디스크를 늘리는 쪽이 아닙니다.",
},
{
  t: "log", k: "로그인마다 30초씩 멈춘다", cat: "logs", d: 3, track: "linux",
  file: "/var/log/auth.log",
  q: "SSH 로그인이 접속할 때마다 30초 넘게 걸립니다. 그 지연을 만드는 한 줄을 고르세요.",
  items: [
    { txt: "22:03:58 INFO  sshd[3300]: Server listening on 0.0.0.0 port 22", bad: false },
    { txt: "22:04:01 WARN  kernel: TCP: possible SYN flooding on port 443, sending cookies", bad: false },
    { txt: "22:04:01 INFO  sshd[3301]: Connection from 203.0.113.44 port 51122", bad: false },
    { txt: "22:04:02 WARN  systemd-resolved[410]: DNS server 10.0.0.2 timed out, try 3 of 3", bad: true },
    { txt: "22:04:32 INFO  sshd[3301]: Accepted publickey for deploy from 203.0.113.44 port 51122", bad: false },
    { txt: "22:04:32 INFO  sshd[3301]: pam_unix(sshd:session): session opened for user deploy", bad: false },
    { txt: "22:04:33 INFO  sshd[3301]: User child is on pid 3310", bad: false },
    { txt: "22:05:10 INFO  monitor[900]: ssh login latency 31.2s, threshold 5s", bad: false },
  ],
  ex: "인증 자체는 멀쩡합니다 — 공개키가 받아들여졌고 세션도 열렸습니다. 다만 <b>받아들여지기까지 31초</b>가 걸렸고, 그 사이에 있던 유일한 사건이 이름 풀이 실패입니다. sshd 는 접속한 주소를 이름으로 되돌려 보는 설정(<code>UseDNS</code>)이 켜져 있으면 로그인 판정 전에 그 조회를 기다리고, 응답 없는 DNS 서버는 <b>거절이 아니라 침묵</b>으로 답하므로 시간 초과가 날 때까지 그대로 멈춥니다. 앞의 SYN 경고는 다른 포트의 일이라 상관이 없습니다. 고칠 곳은 sshd 설정이거나 닿지 않는 DNS 서버 쪽이지 네트워크 대역폭이 아닙니다.",
},
{
  t: "log", k: "재시작을 반복하다 포기했다", cat: "logs", d: 3, track: "linux",
  file: "journalctl -u orders",
  q: "서비스가 재시작을 되풀이하다 결국 뜨지 않습니다. 되풀이의 뿌리가 되는 한 줄을 고르세요.",
  items: [
    { txt: "04:59:58 INFO  systemd[1]: orders.service: Scheduled restart job, restart counter is at 4", bad: false },
    { txt: "04:59:58 WARN  systemd[1]: orders.service: Failed with result 'exit-code'", bad: false },
    { txt: "05:00:01 INFO  systemd[1]: Started orders.service", bad: false },
    { txt: "05:00:01 INFO  orders[7701]: open /etc/orders/env: permission denied", bad: true },
    { txt: "05:00:01 ERROR orders[7701]: DB_URL is empty, refusing to start with no database", bad: false },
    { txt: "05:00:01 WARN  systemd[1]: orders.service: Main process exited, code=exited, status=1", bad: false },
    { txt: "05:00:06 ERROR systemd[1]: orders.service: Start request repeated too quickly", bad: false },
    { txt: "05:00:06 ERROR systemd[1]: orders.service: Failed with result 'exit-code'", bad: false },
  ],
  ex: "<code>Start request repeated too quickly</code> 는 systemd 가 <b>포기했다는 통보</b>일 뿐 이유가 아닙니다. 한 바퀴를 거슬러 올라가면 프로세스가 설정 파일을 못 읽었고, 그래서 <code>DB_URL</code> 이 비었고, 그래서 종료 코드 1로 끝났습니다. 읽지 못한 이유는 권한이므로 <code>EnvironmentFile</code> 의 소유자와 모드를 서비스 계정에 맞추면 됩니다. 이런 로그를 읽을 때의 요령은 <b>가장 시끄러운 줄이 아니라 가장 먼저 어긋난 줄</b>을 찾는 것입니다. 재시작 카운터가 이미 4인 것으로 보아 같은 일이 그 전부터 반복되고 있었다는 것도 함께 읽힙니다.",
},
{
  t: "log", k: "지웠는데 공간이 안 는다", cat: "logs", d: 3, track: "linux",
  file: "/var/log/messages",
  q: "24GB 짜리 로그를 지웠는데 남은 공간이 그대로입니다. 이유를 말해 주는 한 줄을 고르세요.",
  items: [
    { txt: "03:10:00 INFO  admin[9001]: rm -f /var/log/nginx/access.log (24 GB)", bad: false },
    { txt: "03:10:01 INFO  df[9002]: / 100G total, 96G used, 0 avail", bad: false },
    { txt: "03:10:20 INFO  lsof[9010]: nginx(812) holds access.log (deleted) 24G", bad: true },
    { txt: "03:10:21 INFO  df[9002]: / 100G total, 96G used, 0 avail", bad: false },
    { txt: "03:11:02 ERROR app[1180]: write /var/lib/app/queue: no space left on device", bad: false },
    { txt: "03:11:40 WARN  admin[9001]: du -sh /var/log now reports 0.4G, df still reports 96G used", bad: false },
    { txt: "03:12:00 INFO  admin[9001]: reboot scheduled to reclaim space", bad: false },
  ],
  ex: "유닉스에서 <code>rm</code> 은 <b>이름을 지울 뿐</b>입니다. 실제 데이터는 그 파일을 열고 있는 프로세스가 하나도 남지 않았을 때 비로소 반환됩니다. nginx 가 여전히 그 파일 기술자를 쥐고 로그를 쓰고 있으므로 24GB 는 그대로 잡혀 있고, <code>du</code> 는 이름을 따라 세니까 줄었다고 하고 <code>df</code> 는 실제 블록을 세니까 안 줄었다고 합니다 — 두 숫자가 어긋나는 것 자체가 이 상황의 표식입니다. 되돌리는 방법은 재부팅이 아니라 그 프로세스에 로그를 다시 열게 하는 것(<code>nginx -s reopen</code>)이고, 애초에 로그 회전 설정이 그 신호를 보내 주었어야 합니다.",
},
{
  t: "log", k: "부하는 40인데 CPU 는 논다", cat: "logs", d: 4, track: "linux",
  file: "top · iostat",
  q: "부하 평균이 40을 넘는데 CPU 사용률은 5% 입니다. 어디가 막혔는지 알려 주는 한 줄을 고르세요.",
  items: [
    { txt: "14:02:00 INFO  top: load average 41.2 38.9 20.1", bad: false },
    { txt: "14:02:00 INFO  top: Cpu(s) 4.1 us 1.2 sy 12.6 id 82.0 wa", bad: false },
    { txt: "14:02:05 INFO  iostat: sdb util 100.00 await 1840ms queue 128", bad: true },
    { txt: "14:02:05 INFO  iostat: sda util 3.10 await 2ms queue 0", bad: false },
    { txt: "14:02:10 WARN  kernel: task backup:9912 blocked for more than 120 seconds", bad: false },
    { txt: "14:02:10 INFO  ps: 37 processes in state D (uninterruptible sleep)", bad: false },
    { txt: "14:03:00 ERROR app[1180]: request timeout after 30s waiting on upstream read", bad: false },
  ],
  ex: "리눅스의 부하 평균은 <b>CPU 를 기다리는 것만 세지 않습니다</b> — 디스크를 기다리며 깨울 수 없는 상태(D)에 있는 프로세스도 함께 셉니다. 그래서 CPU 가 놀고 있는데도 40이 나옵니다. <code>82.0 wa</code> 는 '기다리는 중' 이라는 사실을 알려 주지만 <b>어디를</b> 기다리는지는 말해 주지 않습니다. 그 자리를 짚는 것은 장치별 숫자입니다: 한 장치만 이용률 100%에 대기 1.8초이고 다른 장치는 멀쩡하므로, 그 장치에 얹힌 작업(여기서는 백업)이 범인입니다. 120초 경고와 요청 시간 초과는 전부 같은 병목이 위로 번진 모습입니다.",
},
{
  t: "log", k: "손으로는 되는데 크론에서만 안 된다", cat: "logs", d: 2, track: "linux",
  file: "/var/log/syslog",
  q: "같은 스크립트가 터미널에서는 되고 크론에서만 실패합니다. 차이를 만드는 한 줄을 고르세요.",
  items: [
    { txt: "01:59:59 WARN  CRON[4400]: (root) run-parts: /etc/cron.hourly/logrotate took 41s", bad: false },
    { txt: "02:00:01 INFO  CRON[4410]: (deploy) CMD (/srv/etl/run.sh)", bad: false },
    { txt: "02:00:01 INFO  CRON[4410]: (deploy) ENV (PATH=/usr/bin:/bin HOME=/home/deploy)", bad: true },
    { txt: "02:00:01 ERROR run.sh[4411]: line 8: aws: command not found", bad: false },
    { txt: "02:00:01 ERROR run.sh[4411]: line 12: jq: command not found", bad: false },
    { txt: "02:00:02 WARN  CRON[4410]: (deploy) MAIL (mailed 2 bytes of output, status 0x004b)", bad: false },
    { txt: "02:00:02 INFO  CRON[4410]: (deploy) END (/srv/etl/run.sh)", bad: false },
    { txt: "09:14:00 INFO  shell[7712]: deploy ran /srv/etl/run.sh by hand, exit 0", bad: false },
  ],
  ex: "크론은 로그인 셸이 아닙니다. <code>.bashrc</code> 도 <code>.profile</code> 도 읽지 않고, 아주 짧은 <code>PATH</code> 만 들고 실행합니다. 터미널에서 되던 <code>aws</code> 와 <code>jq</code> 는 대개 <code>/usr/local/bin</code> 에 있는데 크론의 경로에는 그 자리가 없으므로 '없는 명령' 이 됩니다. 두 개의 <code>command not found</code> 는 결과일 뿐이고, 그 원인을 이미 크론이 친절하게 적어 두었습니다. 고치는 방법은 스크립트 안에서 절대 경로를 쓰거나 crontab 안에 <code>PATH</code> 를 따로 명시하는 것입니다. 같은 함정이 로케일과 <code>HOME</code> 에도 있으니, 손으로 되는 것과 자동으로 되는 것을 같다고 믿지 않는 편이 좋습니다.",
},
{
  t: "log", k: "메모리는 넉넉한데 죽는다", cat: "logs", d: 3, track: "linux",
  file: "/var/log/messages",
  q: "호스트 메모리는 41GB 나 남았는데 프로세스가 강제 종료됩니다. 한계를 정한 한 줄을 고르세요.",
  items: [
    { txt: "11:20:00 INFO  free: total 64G used 21G available 41G", bad: false },
    { txt: "11:20:05 INFO  kernel: memory cgroup /docker/9f2 usage 2048M limit 2048M", bad: true },
    { txt: "11:20:06 INFO  app[1]: import batch 4 of 9, heap 1.9G, rows 4,120,000", bad: false },
    { txt: "11:20:07 ERROR kernel: Memory cgroup out of memory: Killed process 41 (python)", bad: false },
    { txt: "11:20:07 INFO  kernel: oom_reaper: reaped process 41 (python), anon-rss:0kB", bad: false },
    { txt: "11:20:08 WARN  containerd[880]: task 9f2 exited with code 137", bad: false },
    { txt: "11:20:40 INFO  monitor[900]: host memory 33 percent, no alert raised", bad: false },
  ],
  ex: "컨테이너 안의 프로세스는 <b>호스트의 메모리가 아니라 자기 cgroup 의 한도</b>를 씁니다. 여기서는 2048M 이 상한이고 사용량이 정확히 거기 닿았습니다. 그래서 호스트에 41GB 가 남아 있어도 커널은 그 cgroup 안에서 하나를 골라 죽입니다. 종료 코드 137 은 128+9, 곧 SIGKILL 이라는 뜻이라 '누가 밖에서 죽였다' 는 표식입니다. 감시 도구가 호스트만 보고 있으면 이 사고는 <b>지표상 아무 일도 없는 채로</b> 일어나므로, 컨테이너 단위 메모리 지표를 따로 보아야 합니다. 고칠 곳은 한도를 올리든 배치 크기를 줄이든 둘 중 하나입니다.",
},
{
  t: "log", k: "포트가 아직 잡혀 있다", cat: "logs", d: 3, track: "linux",
  file: "journalctl -u api",
  q: "서비스를 멈췄다가 다시 띄우는데 포트를 잡지 못합니다. 이유가 되는 한 줄을 고르세요.",
  items: [
    { txt: "16:40:02 INFO  deploy[5501]: systemctl stop api", bad: false },
    { txt: "16:40:02 INFO  systemd[1]: api.service: Stopping, sending SIGTERM to main process 4410", bad: false },
    { txt: "16:40:03 INFO  systemd[1]: api.service: KillMode=process, children left running", bad: true },
    { txt: "16:40:03 INFO  systemd[1]: api.service: Deactivated successfully", bad: false },
    { txt: "16:40:04 INFO  deploy[5501]: systemctl start api", bad: false },
    { txt: "16:40:04 ERROR api[6602]: listen tcp 0.0.0.0:8080: bind: address already in use", bad: false },
    { txt: "16:40:04 WARN  systemd[1]: api.service: Failed with result 'exit-code'", bad: false },
    { txt: "16:40:09 INFO  ss[6610]: LISTEN 0.0.0.0:8080 users:((\"api-worker\",pid=4419))", bad: false },
  ],
  ex: "systemd 는 <code>Deactivated successfully</code> 라고 적었고 실제로 <b>주 프로세스</b>는 죽었습니다. 다만 <code>KillMode=process</code> 는 주 프로세스에만 신호를 보내고 그 자식들은 내버려 두라는 뜻이라, 실제로 포트를 듣고 있던 워커가 살아남았습니다. <code>ss</code> 가 그 사실을 확인해 줍니다 — 8080 을 쥐고 있는 것은 옛 워커입니다. 이것은 <code>TIME_WAIT</code> 과 다릅니다: 그쪽은 소켓이 잠깐 남는 것이라 <code>SO_REUSEADDR</code> 로 넘어가지만, 여기서는 <b>살아 있는 프로세스</b>가 듣고 있으므로 어떤 옵션으로도 뚫리지 않습니다. 유닛의 <code>KillMode</code> 를 기본값(control-group)으로 되돌리는 것이 답입니다.",
},
{
  t: "log", k: "그룹에 넣었는데 안 된다", cat: "logs", d: 2, track: "linux",
  file: "/var/log/auth.log",
  q: "sudo 그룹에 넣었는데도 그 사람만 sudo 를 못 씁니다. 이유를 알려 주는 한 줄을 고르세요.",
  items: [
    { txt: "09:41:02 INFO  sshd[3120]: Accepted publickey for jin from 10.0.4.11", bad: false },
    { txt: "09:41:02 INFO  sshd[3120]: pam_unix(sshd:session): session opened for user jin", bad: false },
    { txt: "10:02:11 INFO  usermod[3010]: added user jin to group sudo", bad: true },
    { txt: "10:02:30 INFO  sudo[3210]: id -nG jin returns jin developers", bad: false },
    { txt: "10:02:31 ERROR sudo[3210]: jin is not in the sudoers file. This incident will be reported", bad: false },
    { txt: "10:02:33 WARN  sudo[3212]: 1 incorrect password attempt for user jin", bad: false },
    { txt: "10:05:00 INFO  getent[3300]: group sudo lists root deploy jin", bad: false },
  ],
  ex: "그룹 목록은 <b>세션이 시작될 때 한 번</b> 정해져서 그 뒤로는 바뀌지 않습니다. 로그인은 09:41 이었고 그룹 추가는 10:02 였으니, 이미 열려 있던 세션은 옛 목록을 그대로 들고 있습니다. 그래서 <code>getent</code> 는 새 목록을 보여 주는데(시스템의 기록) <code>id -nG</code> 는 옛 목록을 보여 줍니다(내 세션이 들고 있는 것) — 두 명령이 다른 답을 하는 것 자체가 이 상황의 표식입니다. 다시 로그인하면 그대로 됩니다. 비밀번호 오류 한 줄은 사람이 당황해서 남긴 흔적이지 원인이 아닙니다.",
},
{
  t: "log", k: "열 수 있는 파일이 바닥났다", cat: "logs", d: 3, track: "linux",
  file: "journalctl -u gateway",
  q: "접속이 늘자 게이트웨이가 파일도 소켓도 열지 못합니다. 한계를 정한 한 줄을 고르세요.",
  items: [
    { txt: "20:14:58 WARN  gateway[2201]: upstream cache-02 slow, p99 812ms", bad: false },
    { txt: "20:15:00 INFO  systemd[1]: gateway.service: LimitNOFILE=1024", bad: true },
    { txt: "20:15:00 INFO  gateway[2201]: 12,400 active connections, 3,100 idle keep-alive", bad: false },
    { txt: "20:15:04 ERROR gateway[2201]: accept: too many open files", bad: false },
    { txt: "20:15:04 ERROR gateway[2201]: open /etc/ssl/certs/ca.pem: too many open files", bad: false },
    { txt: "20:15:05 WARN  gateway[2201]: health endpoint returning 503 to load balancer", bad: false },
    { txt: "20:15:20 INFO  lsof[2290]: gateway holds 1024 descriptors", bad: false },
    { txt: "20:16:00 INFO  monitor[900]: host file-max usage 0.4 percent", bad: false },
  ],
  ex: "유닉스에서는 소켓도 파일 기술자입니다. 접속 하나가 곧 기술자 하나이므로, 12,400개를 받으려는 프로세스에 1,024개 한도를 준 순간 결과는 정해져 있습니다. 감시 지표가 함정입니다 — <b>시스템 전체 한도</b>는 0.4% 밖에 안 썼으니 호스트만 보면 아무 문제가 없습니다. 막고 있는 것은 프로세스별 한도이고 그것을 정한 것은 유닛 파일입니다. 인증서를 못 여는 쪽의 오류가 이 종류의 고장이 얼마나 엉뚱한 곳에서 터지는지 보여 줍니다: 기술자가 없으면 <b>파일이든 소켓이든 가리지 않고</b> 실패합니다. <code>LimitNOFILE</code> 을 올리고 유휴 연결도 함께 줄입니다.",
},

/* ══════════════ cloud ══════════════ */
{
  t: "log", k: "대상이 하나도 건강하지 않다", cat: "logs", d: 3, track: "cloud",
  file: "alb access log · target log",
  q: "앱은 정상 응답하는데 로드밸런서가 502 를 돌려줍니다. 판정을 가른 한 줄을 고르세요.",
  items: [
    { txt: "07:59:40 WARN  alb: idle timeout raised to 60s by configuration change", bad: false },
    { txt: "08:00:01 INFO  alb: target i-0a41 registered in target group tg-api", bad: false },
    { txt: "08:00:11 INFO  api[i-0a41]: server listening on port 8080", bad: false },
    { txt: "08:00:12 INFO  api[i-0a41]: GET /health 302 redirect to /login", bad: true },
    { txt: "08:00:12 WARN  alb: health check failed for i-0a41, expected 200 but got 302", bad: false },
    { txt: "08:00:42 ERROR alb: no healthy targets in tg-api, returning 502 to clients", bad: false },
    { txt: "08:01:00 INFO  api[i-0a41]: GET /orders 200 in 41ms, requested from bastion", bad: false },
  ],
  ex: "우회로로 들어온 요청이 알리바이입니다 — 앱은 살아 있고 그 요청은 잘 처리합니다. 문제는 <b>헬스 체크 경로가 인증 미들웨어 뒤에 있다</b>는 것입니다. 로그인되지 않은 요청이므로 앱은 규칙대로 로그인 화면으로 보내고, 로드밸런서는 200 만 건강으로 세도록 설정돼 있으니 302 를 실패로 봅니다. 그래서 살아 있는 대상이 전부 제외되고 502 가 나갑니다. 고칠 곳은 두 군데 중 하나입니다: 헬스 체크 경로를 인증에서 빼거나, 기대 코드에 302 를 더하거나. 앞의 유휴 시간 설정 변경은 시간이 가깝다는 것 말고는 이 일과 상관이 없습니다.",
},
{
  t: "log", k: "새 인스턴스를 계속 버린다", cat: "logs", d: 4, track: "cloud",
  file: "asg activity · elb health",
  q: "확장할 때마다 새 인스턴스가 뜨자마자 종료되고 다시 뜹니다. 그 고리를 만드는 한 줄을 고르세요.",
  items: [
    { txt: "12:00:00 INFO  asg: scaling out, desired capacity 4 to 6", bad: false },
    { txt: "12:00:30 INFO  ec2: instance i-0b71 entered state running", bad: false },
    { txt: "12:00:35 WARN  cloud-init: package mirror slow, 3 of 41 packages installed", bad: false },
    { txt: "12:01:00 INFO  elb: health check GET /health to i-0b71 connection refused", bad: false },
    { txt: "12:01:00 INFO  asg: health check grace period 60s elapsed for i-0b71", bad: true },
    { txt: "12:01:01 WARN  asg: terminating unhealthy instance i-0b71", bad: false },
    { txt: "12:01:02 INFO  asg: launching replacement instance to keep desired capacity", bad: false },
    { txt: "12:04:00 ERROR asg: 9 instances launched and terminated within 3 minutes", bad: false },
  ],
  ex: "부팅에 필요한 시간과 <b>건강해지기를 기다려 주는 시간</b>이 어긋난 것입니다. 이 인스턴스는 아직 패키지를 깔고 있어 앱이 뜨지도 않았는데, 유예 시간 60초가 끝나 버렸으니 그 뒤의 접속 거부는 곧바로 '고장' 으로 판정됩니다. 그래서 죽이고, 자리를 채우려 또 띄우고, 그것도 같은 이유로 죽습니다 — 요금만 쓰면서 영원히 도는 고리입니다. 접속 거부 자체는 부팅 중이라면 <b>정상</b>이라는 점이 이 문제의 핵심입니다. 유예 시간을 실제 부팅 시간보다 넉넉히 잡거나, 이미지를 미리 구워 부팅을 짧게 만들면 끊깁니다.",
},
{
  t: "log", k: "권한은 있는데 거부당한다", cat: "logs", d: 4, track: "cloud",
  file: "app log · cloudtrail",
  q: "버킷 권한이 분명히 있는데 업로드가 403 으로 막힙니다. 거부한 쪽을 알려 주는 한 줄을 고르세요.",
  items: [
    { txt: "15:29:58 WARN  app: image resize took 812ms, above the 500ms budget", bad: false },
    { txt: "15:30:02 INFO  kms: GenerateDataKey denied for role app-role on key 4f2a", bad: true },
    { txt: "15:30:02 INFO  app: PutObject s3://uploads/2026/09/a1.jpg with sse aws:kms", bad: false },
    { txt: "15:30:02 ERROR s3: PutObject 403 AccessDenied, request id 9F2A7C3B1D", bad: false },
    { txt: "15:30:03 INFO  iam: policy simulator says s3:PutObject on uploads/* is allowed", bad: false },
    { txt: "15:30:05 ERROR app: upload failed after 3 attempts, giving up", bad: false },
    { txt: "15:31:00 INFO  s3: bucket policy last modified 2026-04-11, unchanged since", bad: false },
  ],
  ex: "암호화된 버킷에 파일을 올리는 일은 <b>두 개의 허가</b>를 받습니다. 하나는 객체를 넣을 권한이고 다른 하나는 그 객체를 암호화할 키를 쓸 권한입니다. 정책 시뮬레이터가 통과라고 말하는 것은 앞쪽뿐이라, 키 정책에 이 역할이 없으면 결과는 그대로 403 입니다. 저장소가 돌려주는 오류 문구가 둘을 구별해 주지 않기 때문에 사람들은 버킷 정책만 몇 시간씩 들여다봅니다. 구별하는 방법은 감사 로그를 보는 것입니다 — 거부한 것이 저장소인지 키 관리 쪽인지가 거기 적혀 있습니다. 고칠 곳은 키 정책에 이 역할의 <code>GenerateDataKey</code> 를 더하는 것입니다.",
},
{
  t: "log", k: "가끔만 시간이 초과된다", cat: "logs", d: 4, track: "cloud",
  file: "lambda report",
  q: "같은 함수가 평소 40밀리초인데 가끔 10초를 넘겨 실패합니다. 그 차이를 만든 한 줄을 고르세요.",
  items: [
    { txt: "03:00:00 INFO  lambda: report duration 41ms billed 42ms init none", bad: false },
    { txt: "03:00:01 INFO  lambda: report duration 38ms billed 38ms init none", bad: false },
    { txt: "03:05:00 WARN  lambda: concurrent executions 8, provisioned concurrency 0", bad: false },
    { txt: "03:05:01 INFO  lambda: cold start, creating a new execution environment", bad: false },
    { txt: "03:05:01 INFO  ec2: attaching network interface in subnet-0a1 for the function", bad: false },
    { txt: "03:05:11 INFO  lambda: init duration 9,840ms", bad: true },
    { txt: "03:05:12 ERROR lambda: task timed out after 10.00 seconds", bad: false },
    { txt: "03:05:13 INFO  apigw: returned 502 to the client after upstream failure", bad: false },
  ],
  ex: "두 종류의 호출이 섞여 있습니다. 이미 준비된 환경을 다시 쓰는 호출은 40밀리초로 끝나고(<code>init none</code>), 새 환경을 만드는 호출은 준비에만 9.8초를 씁니다. 시간 초과가 10초이므로 준비가 끝나자마자 곧바로 넘긴 것입니다 — <b>일한 시간이 아니라 준비한 시간</b>이 예산을 먹었습니다. 준비가 유독 긴 이유는 그 앞줄에 있습니다: 사설 네트워크 안에서 도는 함수는 네트워크 인터페이스를 붙이는 절차를 함께 거칩니다. 그래서 이 사고는 <b>부하가 늘어 새 환경이 생길 때만</b> 보이고, 평소 지표에는 흔적이 남지 않습니다. 예열해 두거나 제한 시간을 준비 시간까지 감안해 잡습니다.",
},
{
  t: "log", k: "같은 주문이 두 번 처리됐다", cat: "logs", d: 4, track: "cloud",
  file: "sqs · worker log",
  q: "큐에 한 번 넣은 주문이 두 번 결제됐습니다. 재처리를 부른 한 줄을 고르세요.",
  items: [
    { txt: "05:59:50 WARN  sqs: ApproximateAgeOfOldestMessage 412s on queue orders", bad: false },
    { txt: "06:00:00 INFO  sqs: ReceiveMessage returned msg 7c1 with receipt handle r-1", bad: false },
    { txt: "06:00:00 INFO  worker-a: processing order 8812, payment gateway call started", bad: false },
    { txt: "06:00:30 INFO  sqs: visibility timeout 30s expired for msg 7c1", bad: true },
    { txt: "06:00:31 INFO  sqs: ReceiveMessage returned msg 7c1 with receipt handle r-2", bad: false },
    { txt: "06:00:31 INFO  worker-b: processing order 8812, payment gateway call started", bad: false },
    { txt: "06:01:30 ERROR ledger: order 8812 charged twice, total amount 42,000", bad: false },
  ],
  ex: "큐는 메시지를 꺼내 준 뒤 <b>일정 시간 동안만</b> 남에게 안 보이게 감춰 둡니다. 그 시간이 지나도록 처리 완료 신호가 오지 않으면 '저 일꾼이 죽었나 보다' 라고 판단하고 다시 내놓습니다 — 그것이 이 큐의 설계이고 고장이 아닙니다. 여기서는 결제가 30초보다 오래 걸리는 일인데 감춤 시간이 30초였으니, 앞선 일꾼이 아직 일하는 중에 다른 일꾼이 같은 주문을 받아 갔습니다. 고치는 길은 둘입니다: 감춤 시간을 실제 처리 시간보다 넉넉히 잡거나 처리 중에 계속 연장하는 것, 그리고 더 근본적으로는 <b>같은 요청을 두 번 받아도 한 번만 반영되게</b> 만드는 것입니다.",
},
{
  t: "log", k: "요금이 하루 만에 두 배가 됐다", cat: "logs", d: 3, track: "cloud",
  file: "cost explorer · vpc flow log",
  q: "저장 용량도 서버 수도 그대로인데 하루 비용이 두 배가 됐습니다. 돈이 새는 자리를 고르세요.",
  items: [
    { txt: "00:00:00 INFO  billing: daily cost 412 USD against a 7-day average of 180 USD", bad: false },
    { txt: "00:00:00 INFO  billing: EC2 61 USD, RDS 44 USD, S3 storage 12 USD", bad: false },
    { txt: "00:00:00 WARN  billing: cost anomaly detected, 129 percent above baseline", bad: false },
    { txt: "00:00:00 INFO  billing: NatGateway-Bytes 288 USD for 4.8 TB processed", bad: false },
    { txt: "00:00:01 INFO  vpcflow: 4.6 TB from subnet-private to the object storage prefix list", bad: true },
    { txt: "00:00:02 INFO  etl: nightly export wrote 4.6 TB to s3://warehouse/raw", bad: false },
    { txt: "00:00:03 INFO  billing: DataTransfer-Out-Bytes 3 USD", bad: false },
  ],
  ex: "요금 항목만 보면 게이트웨이가 288달러를 썼다는 것까지는 알 수 있지만 <b>왜</b> 는 알 수 없습니다. 흐름 로그가 그 자리를 짚습니다: 사설 서브넷에서 나간 4.6TB 가 전부 <b>같은 계정의 객체 저장소</b>로 갔습니다. 인터넷으로 나간 것이 아닌데도 게이트웨이를 지났으니 GB 마다 처리 요금을 낸 것입니다. 바깥으로 나간 전송량이 대조군입니다 — 진짜 인터넷으로 간 것은 3달러뿐입니다. 고치는 방법은 대역폭을 줄이는 것이 아니라 <b>경로를 바꾸는 것</b>입니다. 저장소용 게이트웨이 엔드포인트를 만들면 그 트래픽이 게이트웨이를 지나지 않고, 이 항목은 거의 0이 됩니다.",
},
{
  t: "log", k: "배포 중에만 절반이 실패한다", cat: "logs", d: 4, track: "cloud",
  file: "ecs deployment · api log",
  q: "무중단 배포인데 5분 동안 요청의 절반이 실패했습니다. 그렇게 만든 한 줄을 고르세요.",
  items: [
    { txt: "18:59:30 WARN  ecs: service api has one previous failed deployment on record", bad: false },
    { txt: "19:00:00 INFO  ecs: deployment d-71 started, desired 6, rolling update", bad: false },
    { txt: "19:00:05 INFO  migrate: renamed column orders.paid_at to orders.settled_at", bad: true },
    { txt: "19:00:42 INFO  ecs: 3 tasks running revision 71, 3 tasks running revision 70", bad: false },
    { txt: "19:00:45 ERROR api rev70: column orders.paid_at does not exist", bad: false },
    { txt: "19:00:45 INFO  api rev71: GET /orders 200 in 38ms", bad: false },
    { txt: "19:01:00 WARN  alb: 5xx rate 48 percent on target group tg-api", bad: false },
    { txt: "19:05:41 INFO  ecs: deployment d-71 completed, 5xx rate back to 0.1 percent", bad: false },
  ],
  ex: "무중단 배포의 뜻은 <b>두 판본이 잠깐 같이 산다</b>는 것입니다. 그 사이에 옛 판본이 읽던 열의 이름을 바꿔 버렸으니, 새 판본은 멀쩡하고 옛 판본만 전부 실패합니다 — 실패율이 정확히 절반인 것이 그 증거입니다. 절반이라는 숫자가 대수가 반반이라는 사실과 맞아떨어지는지 확인하는 것이 이런 로그를 읽는 요령입니다. 스키마 변경은 <b>두 단계</b>로 나눠야 합니다: 먼저 새 열을 더해 양쪽이 다 읽히게 만들고, 모든 태스크가 새 판본이 된 뒤에 옛 열을 지웁니다. 배포가 끝나자 오류가 사라진 것은 고쳐서가 아니라 옛 판본이 다 없어졌기 때문입니다.",
},
{
  t: "log", k: "용량은 남는데 스로틀이 난다", cat: "logs", d: 4, track: "cloud",
  file: "dynamodb metrics",
  q: "쓰기 용량을 40% 만 쓰는데도 요청이 계속 거절됩니다. 이유를 알려 주는 한 줄을 고르세요.",
  items: [
    { txt: "21:00:00 INFO  ddb: table orders provisioned at 1000 write capacity units", bad: false },
    { txt: "21:00:00 INFO  ddb: consumed 412 write units averaged over five minutes", bad: false },
    { txt: "21:00:05 WARN  app: write latency p99 1,240ms, p50 unchanged at 8ms", bad: false },
    { txt: "21:00:08 ERROR app: ProvisionedThroughputExceededException on PutItem", bad: false },
    { txt: "21:00:08 INFO  ddb: CloudWatch ThrottledRequests 4,120 in one minute", bad: false },
    { txt: "21:00:09 INFO  ddb: 96 percent of writes carry the key 2026-09-08", bad: true },
    { txt: "21:00:30 INFO  ddb: table size 41 GB spread across 12 partitions", bad: false },
  ],
  ex: "용량은 테이블 전체에 걸어 두지만 실제로 일하는 것은 <b>조각(파티션) 하나하나</b>이고, 각 조각은 자기 몫만 처리합니다. 열두 조각에 1,000을 나눠 두었는데 쓰기의 96%가 한 열쇠로 몰리면 그 열쇠가 사는 조각만 자기 몫을 넘겨 거절하고, 나머지 열한 조각은 놀고 있습니다. 그래서 평균 사용률은 41%로 한가해 보입니다 — <b>평균이 감추는 쏠림</b>이 이 사고의 전부입니다. p50 은 그대로인데 p99 만 튀는 것도 같은 이야기입니다. 날짜를 열쇠로 쓰면 오늘 들어오는 모든 쓰기가 한 곳으로 갑니다. 열쇠에 임의의 접미사를 붙이거나 아예 다른 축을 열쇠로 고릅니다.",
},
{
  t: "log", k: "옛 파일이 계속 나온다", cat: "logs", d: 3, track: "cloud",
  file: "deploy log · cdn log",
  q: "배포하고 캐시를 지웠는데도 브라우저가 옛 파일을 받습니다. 남아 있는 자리를 고르세요.",
  items: [
    { txt: "12:59:50 WARN  deploy: build produced no source map for app.js", bad: false },
    { txt: "13:00:00 INFO  deploy: uploaded app.js to s3://site/app.js with etag 7c1", bad: false },
    { txt: "13:00:01 INFO  deploy: created invalidation I-99 for path /index.html", bad: false },
    { txt: "13:00:21 INFO  cdn: /app.js served from cache, age 41,200s, max-age 86,400", bad: true },
    { txt: "13:00:22 ERROR browser: Uncaught TypeError: render is not a function", bad: false },
    { txt: "13:00:30 WARN  monitor: client side javascript error rate 12 percent", bad: false },
    { txt: "13:10:00 INFO  cdn: /index.html served from origin, age 0", bad: false },
  ],
  ex: "캐시를 지운 것은 맞지만 <b>지운 경로가 하나뿐</b>이었습니다. 새 문서는 새 스크립트를 부르는데 그 스크립트는 여전히 열한 시간 묵은 사본이 나가고, 남은 수명이 하루니까 저절로 사라지지도 않습니다. 브라우저의 오류는 <b>새 문서와 옛 스크립트가 짝이 안 맞아서</b> 나는 것이므로, 코드를 아무리 봐도 원인이 나오지 않습니다. 급하면 스크립트 경로도 함께 지우면 되고, 근본적으로는 파일 이름에 내용 해시를 넣어 <code>app.7c1f.js</code> 처럼 만듭니다. 그러면 내용이 바뀔 때마다 이름이 바뀌므로 지울 일 자체가 없어지고, 문서만 짧은 수명으로 두면 됩니다.",
},
{
  t: "log", k: "연결 수가 먼저 바닥났다", cat: "logs", d: 3, track: "cloud",
  file: "lambda · rds log",
  q: "데이터베이스는 한가한데 연결을 더 받지 못합니다. 연결을 다 써 버린 자리를 고르세요.",
  items: [
    { txt: "07:00:00 INFO  rds: max_connections 100, current connections 41", bad: false },
    { txt: "07:00:01 INFO  lambda: reserved concurrency not set, account limit is 1000", bad: false },
    { txt: "07:00:02 INFO  sqs: 4,200 messages available, event source batch size 1", bad: false },
    { txt: "07:00:05 WARN  lambda: concurrent executions 380 and still climbing", bad: false },
    { txt: "07:00:06 INFO  lambda: each invocation opens its own connection, no pooling", bad: true },
    { txt: "07:00:07 ERROR rds: FATAL sorry, too many clients already", bad: false },
    { txt: "07:00:08 ERROR api: returned 500, database unavailable to the web tier", bad: false },
    { txt: "07:02:00 INFO  rds: CPU 12 percent, no slow queries in the last hour", bad: false },
  ],
  ex: "서버리스에서 자주 겪는 어긋남입니다. 함수는 <b>부하만큼 얼마든지 늘어나도록</b> 만들어졌고 데이터베이스는 <b>연결 수가 정해져</b> 있습니다. 큐에 4,200건이 쌓였고 한 번에 한 건씩 처리하니 함수가 수백 개로 늘었는데, 각 호출이 자기 연결을 열면 100개 한도는 순식간에 넘습니다. 자원 지표가 알리바이입니다 — 데이터베이스는 일이 없어 한가합니다. 막힌 것은 처리 능력이 아니라 <b>들어가는 문의 개수</b>입니다. 고치는 방법은 함수 쪽 동시 실행 수를 데이터베이스가 감당할 만큼으로 묶어 두거나, 연결을 대신 관리해 주는 프록시를 앞에 두는 것입니다.",
},

];
