/* javascript 트랙 로그 분석 2 — Node 서버가 남긴 기록에서 원인을 짚는다. */
module.exports = [
{
  t: "log", k: "잡지 않은 거절이 프로세스를 끈다", cat: "logs", d: 2, track: "javascript",
  file: "/var/log/api-node/app.log",
  q: "간헐적으로 프로세스가 통째로 재시작되는데 오류 스택이 짧습니다. 원인 줄을 고르세요.",
  items: [
    { txt: "09:00:00 INFO  app: node 20.11, 워커 1, 요청 처리 정상" },
    { txt: "09:12:00 INFO  api: 알림 발송을 sendMail(...) 로 호출하고 await 하지 않음", bad: true },
    { txt: "09:12:01 WARN  smtp: 연결 거부 (ECONNREFUSED)" },
    { txt: "09:12:01 ERROR node: [UnhandledPromiseRejection] ECONNREFUSED" },
    { txt: "09:12:01 ERROR node: 프로세스 종료 코드 1" },
    { txt: "09:12:03 WARN  pm2: 재시작 (누적 27회), 진행 중 요청 41건 유실" },
  ],
  ex: "프라미스를 만들어 놓고 <b>아무도 결과를 받지 않았습니다</b>. Node 15 부터 잡히지 않은 거절은 프로세스를 종료시키므로, 부수적인 알림 실패가 서비스 전체를 내립니다. SMTP 거부는 방아쇠일 뿐 원인이 아닙니다. 처방은 <code>await</code> 하거나 <code>.catch()</code> 를 붙여 <b>실패를 그 자리에서 삼키는 것</b>이고, 예방은 <code>no-floating-promises</code> 규칙으로 이런 호출을 정적 검사에서 잡는 것입니다.",
},
{
  t: "log", k: "한 요청이 모두를 멈춘다", cat: "logs", d: 3, track: "javascript",
  file: "/var/log/api-node/app.log",
  q: "큰 파일을 올린 사용자 한 명 때문에 전체 응답이 멎습니다. 원인 줄을 고르세요.",
  items: [
    { txt: "10:00:00 INFO  api: p95 30ms, 이벤트 루프 지연 2ms" },
    { txt: "10:04:00 INFO  api: POST /import 수신, 본문 90MB" },
    { txt: "10:04:01 INFO  api: 본문 전체를 문자열로 모아 JSON.parse 후 검증", bad: true },
    { txt: "10:04:03 WARN  node: 이벤트 루프 지연 2ms → 3,900ms" },
    { txt: "10:04:04 WARN  api: 동시 요청 전부 대기, 헬스체크 응답 없음" },
    { txt: "10:04:09 ERROR lb: 인스턴스 비정상 판정, 트래픽 제외" },
  ],
  ex: "<code>JSON.parse</code> 는 <b>동기</b>이고, 90MB 를 파싱하는 동안 이벤트 루프가 완전히 멈춥니다. 그래서 관계없는 요청과 헬스체크까지 함께 죽습니다. 루프 지연 3.9초는 원인이 아니라 그 결과입니다. 처방은 스트리밍 파서로 <b>조각내어</b> 처리하거나, 큰 입력은 워커 스레드·별도 잡으로 넘기는 것이고, 예방은 본문 크기 상한을 두고 <b>이벤트 루프 지연을 지표로</b> 감시하는 것입니다.",
},
{
  t: "log", k: "캐시가 아니라 새는 그릇", cat: "logs", d: 2, track: "javascript",
  file: "/var/log/api-node/app.log",
  q: "메모리가 하루 종일 우상향하다가 밤마다 죽습니다. 원인 줄을 고르세요.",
  items: [
    { txt: "11:00:00 INFO  app: RSS 210MB, 요청 누적 12만" },
    { txt: "11:00:05 INFO  app: 응답 캐시를 모듈 전역 Map 에 저장" },
    { txt: "11:00:10 INFO  app: 캐시 키에 요청 id 포함 — 같은 키가 두 번 오지 않음", bad: true },
    { txt: "11:00:15 INFO  app: 캐시 항목 수 118,904, 만료·상한 없음" },
    { txt: "13:00:00 WARN  app: RSS 1.4GB, GC 시간 비율 22%" },
    { txt: "23:40:00 ERROR node: JavaScript heap out of memory" },
  ],
  ex: "키에 <b>요청 id</b> 가 들어가 같은 키가 두 번 오지 않습니다. 그러면 적중은 영원히 없고 항목만 쌓이므로, 이름만 캐시일 뿐 실제로는 <b>무한히 자라는 그릇</b>입니다. RSS 상승과 힙 OOM 은 결과입니다. 처방은 키를 실제 응답을 결정하는 값으로 만들고, <b>상한과 만료</b>가 있는 LRU 를 쓰는 것입니다. 예방은 캐시 지표에 <b>적중률과 항목 수</b>를 함께 남기는 것 — 적중률 0% 는 캐시가 아니라 누수입니다.",
},
{
  t: "log", k: "기다릴 필요 없는 것을 기다린다", cat: "logs", d: 2, track: "javascript",
  file: "/var/log/api-node/app.log",
  q: "목록 화면 API 하나가 유독 느립니다. 각 호출은 빠릅니다. 원인 줄을 고르세요.",
  items: [
    { txt: "12:00:00 INFO  api: GET /dashboard 수신" },
    { txt: "12:00:00 INFO  api: 위젯 12개, 각 위젯마다 외부 호출 1회" },
    { txt: "12:00:00 INFO  api: 외부 호출 평균 응답 90ms" },
    { txt: "12:00:00 INFO  api: for 루프 안에서 await 로 하나씩 호출", bad: true },
    { txt: "12:00:01 INFO  api: 동시 진행 중인 외부 호출 수 항상 1" },
    { txt: "12:00:01 WARN  api: 총 소요 1,120ms (90ms × 12 + 오버헤드)" },
    { txt: "12:00:02 WARN  ux: 대시보드 첫 화면 체감 지연 신고" },
  ],
  ex: "각 호출은 빠른데 <b>줄을 세웠습니다</b>. 루프 안의 <code>await</code> 는 앞의 응답이 와야 다음을 시작하므로 12번의 왕복이 그대로 더해집니다. 동시 진행 수가 늘 1이라는 줄이 그 모양을 보여 줍니다. 서로 필요하지 않은 호출이면 <code>Promise.all</code> 로 <b>함께 보내</b> 총 시간이 가장 느린 하나로 줄어듭니다. 외부에 부담이 걱정되면 동시 실행 수에 상한을 두면 됩니다.",
},
{
  t: "log", k: "겹쳐 도는 주기 작업", cat: "logs", d: 3, track: "javascript",
  file: "/var/log/api-node/app.log",
  q: "동기화 작업이 가끔 같은 데이터를 두 번 처리합니다. 원인 줄을 고르세요.",
  items: [
    { txt: "13:00:00 INFO  sync: setInterval(run, 10_000) 등록" },
    { txt: "13:00:10 INFO  sync: run 시작 → 4초 만에 완료" },
    { txt: "13:05:00 WARN  db: 상류 지연으로 run 소요 24초" },
    { txt: "13:05:10 INFO  sync: 이전 실행이 끝나기 전에 다음 실행이 시작됨", bad: true },
    { txt: "13:05:20 INFO  sync: 동시에 도는 run 3개" },
    { txt: "13:05:30 WARN  sync: 같은 레코드를 두 번 이관, 중복 키 오류 12건" },
  ],
  ex: "<code>setInterval</code> 은 <b>앞의 실행이 끝났는지 보지 않습니다</b>. 작업이 주기보다 길어지면 겹쳐 돌고, 같은 레코드를 여러 실행이 함께 집습니다. 상류 지연은 방아쇠일 뿐입니다. 처방은 작업이 <b>끝난 뒤</b> 다음을 예약하는 것(<code>setTimeout</code> 재귀)이고, 겹쳐도 안전하도록 <b>실행 중 플래그</b>나 분산 잠금을 두는 것입니다. 이관 자체를 멱등하게 만들면 중복 키 오류도 사라집니다.",
},
{
  t: "log", k: "받는 속도보다 빨리 읽는다", cat: "logs", d: 3, track: "javascript",
  file: "/var/log/api-node/app.log",
  q: "대용량 파일 전송 중에만 메모리가 급증합니다. 원인 줄을 고르세요.",
  items: [
    { txt: "14:00:00 INFO  api: GET /export 요청, 대상 2.4GB" },
    { txt: "14:00:00 INFO  api: 원본은 디스크에서 스트림으로 읽는 중" },
    { txt: "14:00:01 INFO  api: data 이벤트에서 res.write(chunk) 만 호출, 반환값 무시", bad: true },
    { txt: "14:00:02 INFO  net: 클라이언트 대역폭 2Mbps (모바일)" },
    { txt: "14:00:20 WARN  node: RSS 300MB → 2.1GB (내부 버퍼 적체)" },
    { txt: "14:00:40 ERROR node: JavaScript heap out of memory" },
  ],
  ex: "읽는 쪽이 <b>쓰는 쪽의 사정을 무시</b>했습니다. <code>res.write()</code> 가 <code>false</code> 를 돌려주면 '버퍼가 찼으니 잠시 멈추라' 는 뜻인데, 그것을 보지 않으면 느린 클라이언트에게 보낼 데이터가 메모리에 쌓입니다. 처방은 <code>pipeline(src, res)</code> 로 <b>역압</b>을 자동으로 처리하는 것이고, 직접 쓸 때는 <code>false</code> 를 받으면 <code>drain</code> 까지 기다려야 합니다.",
},
{
  t: "log", k: "\"false\" 는 참이다", cat: "logs", d: 2, track: "javascript",
  file: "/var/log/api-node/boot.log",
  q: "기능 스위치를 껐는데도 계속 켜져 있습니다. 원인 줄을 고르세요.",
  items: [
    { txt: "15:00:00 INFO  boot: 환경변수 FEATURE_NEW_CHECKOUT=false 로 배포" },
    { txt: "15:00:00 INFO  boot: 설정 로드 완료, 오류 없음" },
    { txt: "15:00:01 INFO  boot: if (process.env.FEATURE_NEW_CHECKOUT) 로 분기", bad: true },
    { txt: "15:00:01 INFO  boot: 환경변수 값은 언제나 문자열" },
    { txt: "15:00:02 WARN  app: 새 결제 화면이 활성 상태로 기동" },
    { txt: "15:10:00 ERROR ops: 롤백하려 스위치를 껐으나 변화 없음" },
  ],
  ex: "환경변수는 <b>언제나 문자열</b>이고, 빈 문자열이 아닌 <code>\"false\"</code> 는 참입니다. 그래서 끄려고 넣은 값이 오히려 켜는 값이 되고, 롤백 수단이 작동하지 않습니다. 처방은 <code>=== \"true\"</code> 처럼 <b>명시적으로 비교</b>하거나 설정 스키마로 파싱해 불리언으로 바꾸는 것이고, 예방은 기동 로그에 <b>해석된 값</b>(문자열이 아니라 true/false)을 찍어 눈으로 확인하는 것입니다.",
},
{
  t: "log", k: "워커마다 자기만의 한도", cat: "logs", d: 3, track: "javascript",
  file: "/var/log/api-node/app.log",
  q: "초당 100회로 제한했는데 상류가 400회를 받았다고 항의합니다. 원인 줄을 고르세요.",
  items: [
    { txt: "16:00:00 INFO  app: cluster 모드, 워커 4개 기동" },
    { txt: "16:00:01 INFO  app: 각 워커가 자체 메모리에 호출 카운터 보관", bad: true },
    { txt: "16:00:02 INFO  app: 제한 설정 100 req/s (워커별로 적용됨)" },
    { txt: "16:00:10 INFO  app: 워커별 카운터 최대 98~100" },
    { txt: "16:00:11 WARN  upstream: 실제 수신 392 req/s" },
    { txt: "16:00:30 ERROR upstream: 계약 위반으로 키 일시 정지" },
  ],
  ex: "한도가 <b>프로세스마다</b> 걸렸습니다. 워커가 넷이면 상류가 보는 값은 네 배가 되고, 각 워커의 계기판은 정상으로 보입니다. 워커별 카운터가 98~100 이라는 줄이 그 사실을 그대로 말해 줍니다. 처방은 카운터를 <b>공유 저장소</b>(레디스 등)에 두어 전체를 하나로 세는 것이고, 그것이 어려우면 워커 수로 나눈 몫을 각자에게 주되 <b>워커 수가 바뀌면 함께 바뀌게</b> 해야 합니다.",
},
{
  t: "log", k: "모듈은 한 번만 만들어진다", cat: "logs", d: 3, track: "javascript",
  file: "/var/log/api-node/test.log",
  q: "테스트를 따로 돌리면 통과하는데 함께 돌리면 실패합니다. 원인 줄을 고르세요.",
  items: [
    { txt: "17:00:00 INFO  test: 스위트 A 시작" },
    { txt: "17:00:01 INFO  test: db 모듈이 최초 require 때 커넥션 풀을 만들어 모듈 스코프에 보관", bad: true },
    { txt: "17:00:02 INFO  test: A 가 풀 설정을 테스트용으로 덮어씀" },
    { txt: "17:00:10 INFO  test: 스위트 B 시작 — require 는 캐시된 같은 인스턴스를 반환" },
    { txt: "17:00:11 WARN  test: B 가 A 의 설정을 그대로 물려받음" },
    { txt: "17:00:12 ERROR test: B 3건 실패 (단독 실행 시 전부 통과)" },
  ],
  ex: "<code>require</code> 는 모듈을 <b>한 번만 평가하고 결과를 캐시</b>합니다. 모듈 스코프에 만든 커넥션 풀은 프로세스 전체가 공유하므로, 앞 스위트가 바꾼 상태가 뒤 스위트로 넘어갑니다. 단독 실행에서 통과하는 것이 그 증거입니다. 처방은 상태를 모듈 스코프가 아니라 <b>함수가 만들어 돌려주는 값</b>으로 바꾸는 것(팩터리)이고, 테스트에서는 스위트마다 새로 만들고 끝나면 닫아야 합니다.",
},
{
  t: "log", k: "엔진마다 다르게 읽히는 날짜", cat: "logs", d: 2, track: "javascript",
  file: "/var/log/api-node/app.log",
  q: "같은 데이터가 브라우저와 서버에서 하루 다르게 표시됩니다. 원인 줄을 고르세요.",
  items: [
    { txt: "18:00:00 INFO  api: 응답 필드 due = '2026-08-24'" },
    { txt: "18:00:00 INFO  web: new Date('2026-08-24') → UTC 자정으로 해석", bad: true },
    { txt: "18:00:01 INFO  web: 브라우저 시간대 UTC-07:00" },
    { txt: "18:00:01 INFO  web: 화면 표시 2026-08-23" },
    { txt: "18:00:02 WARN  qa: 서버 렌더 결과는 2026-08-24" },
    { txt: "18:00:10 WARN  ops: 마감일이 하루 당겨져 보인다는 문의 다수" },
  ],
  ex: "날짜만 있는 ISO 문자열은 <b>UTC 자정</b>으로 해석됩니다. 그것을 지역 시간으로 표시하면 UTC 서쪽에서는 하루 전으로 보이고, 서버는 그대로 두니 두 화면이 갈립니다. 처방은 <b>날짜와 시점을 구분</b>하는 것 — 달력상의 날짜라면 문자열로 다루거나 지역 시간 자정으로 명시해 만들고, 시점이라면 오프셋이 포함된 형식으로 주고받아야 합니다.",
},
];
