/* java 트랙 로그 분석 2 — JVM·런타임이 남긴 기록에서 원인을 짚는다.
   원인 줄을 INFO 에도 두고 앞에 붉은 청어를 깔았다 — 첫 경고를 찍는 것으로는 못 푼다. */
module.exports = [
{
  t: "log", k: "같은 라이브러리가 두 벌 들어왔다", cat: "logs", d: 3, track: "java",
  file: "/var/log/order-svc/boot.log",
  q: "로컬에서는 뜨는 서비스가 배포 환경에서만 기동 중 죽습니다. 원인 줄을 고르세요.",
  items: [
    { txt: "08:00:00 INFO  boot: Spring Boot 3.2 기동, 프로파일 prod" },
    { txt: "08:00:02 INFO  boot: 클래스패스 jar 214개" },
    { txt: "08:00:03 INFO  boot: guava 32.1 과 guava 20.0 이 모두 클래스패스에 있음", bad: true },
    { txt: "08:00:04 WARN  boot: 같은 이름 클래스가 두 jar 에 존재, 먼저 발견된 쪽을 사용" },
    { txt: "08:00:05 ERROR boot: NoSuchMethodError: com.google.common.base.Preconditions.checkArgument" },
    { txt: "08:00:05 ERROR boot: ApplicationContext 초기화 실패, 종료" },
  ],
  ex: "같은 라이브러리의 <b>두 버전</b>이 클래스패스에 있습니다. 어느 쪽이 먼저 발견되는지는 순서에 달렸으므로 로컬과 배포 환경이 갈리고, 옛 클래스가 먼저 잡히면 새 API 를 부를 때 <code>NoSuchMethodError</code> 가 납니다. 컴파일은 새 버전으로 했으니 빌드는 통과합니다. 처방은 <code>dependency:tree</code> 로 누가 옛 버전을 끌고 오는지 찾아 제외하는 것이고, 예방은 의존성 수렴 검사(enforcer)를 빌드에 넣어 <b>두 버전이 섞이면 빌드를 깨뜨리는</b> 것입니다.",
},
{
  t: "log", k: "정규식 하나가 코어를 태운다", cat: "logs", d: 3, track: "java",
  file: "/var/log/order-svc/app.log",
  q: "특정 입력이 들어올 때만 CPU 가 한 코어씩 100% 로 붙잡힙니다. 원인 줄을 고르세요.",
  items: [
    { txt: "09:00:00 INFO  api: 평시 p95 40ms, cpu 30%" },
    { txt: "09:02:00 INFO  api: 배포 없음, 트래픽 평시 수준" },
    { txt: "09:04:00 WARN  api: 요청 3건이 60초 넘게 응답 없음" },
    { txt: "09:04:10 INFO  api: 스레드 덤프 — 세 스레드 모두 RUNNABLE, java.util.regex.Pattern$Loop.match" },
    { txt: "09:04:20 INFO  api: 검증 정규식 (\\\\w+\\\\s?)+$ 로 사용자 입력을 통째로 검사", bad: true },
    { txt: "09:04:30 INFO  api: 문제 입력 길이 42자, 공백 포함" },
    { txt: "09:05:00 WARN  api: cpu 100% × 3 코어, 요청 큐 적체" },
    { txt: "09:06:00 ERROR api: 헬스체크 실패로 인스턴스 교체" },
  ],
  ex: "<b>중첩 수량자</b>가 있는 정규식은 실패하는 입력에서 경우의 수가 지수로 늘어납니다(<code>(\\w+\\s?)+$</code>). 42자 입력 하나가 코어를 몇 분씩 붙잡고, 스레드는 RUNNABLE 이라 데드락으로도 보이지 않습니다. 처방은 정규식을 <b>중첩 없이</b> 다시 쓰거나 문자열 처리로 바꾸는 것이고, 예방은 사용자 입력에 <b>길이 상한</b>을 두고 검증에 시간 제한을 거는 것입니다.",
},
{
  t: "log", k: "서버 시각으로 저장된 시간", cat: "logs", d: 3, track: "java",
  file: "/var/log/order-svc/app.log",
  q: "예약 시간이 사용자마다 몇 시간씩 어긋납니다. 원인 줄을 고르세요.",
  items: [
    { txt: "10:00:00 INFO  api: 예약 생성 요청 수신 (요청 본문 2026-08-24T09:00+09:00)" },
    { txt: "10:00:00 INFO  api: 파싱 결과 LocalDateTime 2026-08-24T09:00 (오프셋 버림)", bad: true },
    { txt: "10:00:01 INFO  db: reservations.starts_at = '2026-08-24 09:00:00' (TIMESTAMP WITHOUT TIME ZONE)" },
    { txt: "10:00:02 INFO  api: 서버 기본 시간대 UTC, 배치 서버는 Asia/Seoul" },
    { txt: "10:05:00 WARN  batch: 알림 발송 시각이 예약보다 9시간 이릅니다" },
    { txt: "10:06:00 WARN  qa: 해외 사용자 예약은 최대 17시간 어긋남" },
  ],
  ex: "오프셋이 붙은 시각을 <b>오프셋을 버리고</b> 저장했습니다. <code>LocalDateTime</code> 은 '어느 지역인지 모르는 벽시계' 라 읽는 쪽의 기본 시간대에 따라 뜻이 달라지고, 서버와 배치의 기본 시간대가 다르면 그만큼 어긋납니다. 처방은 시점을 <code>Instant</code>(또는 <code>TIMESTAMPTZ</code>)로 저장하고 <b>표시할 때만</b> 사용자 시간대로 바꾸는 것이며, 예방은 서버 기본 시간대를 UTC 로 고정하고 <code>LocalDateTime.now()</code> 사용을 금지하는 것입니다.",
},
{
  t: "log", k: "로그를 쓰다 요청이 멈춘다", cat: "logs", d: 3, track: "java",
  file: "/var/log/order-svc/app.log",
  q: "디스크가 느려진 시간대에 API 응답이 통째로 밀립니다. 원인 줄을 고르세요.",
  items: [
    { txt: "11:00:00 INFO  api: p95 45ms, 로그 초당 12,000줄" },
    { txt: "11:20:00 WARN  node: 디스크 io-wait 38% (이웃 파드의 백업 작업)" },
    { txt: "11:20:10 INFO  log: appender 는 동기식, 요청 스레드가 직접 파일에 기록", bad: true },
    { txt: "11:20:20 INFO  api: 스레드 덤프 — 톰캣 워커 180개 중 174개가 write0 에서 BLOCKED" },
    { txt: "11:20:30 WARN  api: p95 45ms → 3,400ms" },
    { txt: "11:21:00 ERROR api: 워커 고갈, 503 반환" },
  ],
  ex: "로그를 <b>요청 스레드가 직접</b> 파일에 씁니다. 평소에는 보이지 않지만 디스크가 느려지면 그 지연이 그대로 요청 지연이 되고, 워커가 모두 쓰기에 묶이면 서비스가 멈춥니다. io-wait 상승은 방아쇠일 뿐 원인이 아닙니다 — 같은 디스크에서 동기로 쓰는 구조가 원인입니다. 처방은 <b>비동기 appender</b> 와 큐 상한, 넘치면 버리는 정책이고, 예방은 로그량 자체를 줄이는 것입니다.",
},
{
  t: "log", k: "공유한 포매터가 날짜를 망친다", cat: "logs", d: 3, track: "java",
  file: "/var/log/order-svc/app.log",
  q: "부하가 높을 때만 저장된 날짜가 드물게 엉뚱한 값이 됩니다. 원인 줄을 고르세요.",
  items: [
    { txt: "12:00:00 INFO  api: 주문 저장 초당 40건, 오류 0" },
    { txt: "12:10:00 INFO  api: 저장 경로 코드 변경 없음 (2개월째 동일)" },
    { txt: "12:30:00 INFO  api: 초당 900건으로 증가 (프로모션)" },
    { txt: "12:30:05 WARN  api: 저장된 주문 중 12건의 날짜가 1970 또는 2075" },
    { txt: "12:30:10 INFO  api: 날짜 변환에 static final SimpleDateFormat 한 개를 공유", bad: true },
    { txt: "12:30:20 INFO  api: 예외는 없음 — 값만 조용히 틀림" },
    { txt: "12:31:00 WARN  ops: 정산 배치가 해당 주문을 집계에서 누락" },
  ],
  ex: "<code>SimpleDateFormat</code> 은 <b>스레드 안전하지 않습니다</b>. 내부 <code>Calendar</code> 를 상태로 쓰기 때문에 두 스레드가 동시에 들어오면 서로의 중간 상태를 섞어 읽고, 예외 없이 <b>틀린 날짜</b>가 나옵니다. 부하가 낮을 때 안 보이던 이유가 그것입니다. 처방은 불변인 <code>DateTimeFormatter</code> 로 바꾸는 것이고, 옛 코드를 유지해야 한다면 <code>ThreadLocal</code> 로 인스턴스를 스레드마다 두어야 합니다.",
},
{
  t: "log", k: "힙은 멀쩡한데 메모리가 는다", cat: "logs", d: 4, track: "java",
  file: "/var/log/order-svc/app.log",
  q: "힙 사용량은 안정적인데 컨테이너 메모리만 계속 오릅니다. 원인 줄을 고르세요.",
  items: [
    { txt: "13:00:00 INFO  jvm: -Xmx2g, 힙 사용 1.1G 안정" },
    { txt: "13:00:04 INFO  jvm: 메타스페이스 180M, 스레드 74 (평시와 같음)" },
    { txt: "13:00:07 INFO  jvm: 힙 덤프에서 큰 객체 없음" },
    { txt: "13:00:10 INFO  jvm: GC 후 힙 사용 1.05G, Full GC 없음" },
    { txt: "13:00:20 WARN  k8s: 컨테이너 RSS 2.9G / limit 3G" },
    { txt: "13:00:30 INFO  netty: ByteBuf 를 직접 할당하고 release() 호출 누락", bad: true },
    { txt: "13:00:40 INFO  jvm: Direct buffer 사용 1.7G (MaxDirectMemorySize 무제한)" },
    { txt: "13:05:00 ERROR k8s: OOMKilled, 재시작 counter 6" },
  ],
  ex: "새는 곳이 <b>힙 밖</b>입니다. 네티의 <code>ByteBuf</code> 는 참조 카운트로 관리되는 <b>직접 메모리</b>라 GC 가 회수해 주지 않고, <code>release()</code> 를 빠뜨리면 힙 그래프는 평온한데 RSS 만 오릅니다. 힙만 보던 관측이 이 사고를 6번 놓쳤습니다. 처방은 누수 지점을 <code>ResourceLeakDetector</code> 로 잡고 <code>try/finally</code> 로 반드시 놓아주는 것이며, 예방은 <code>MaxDirectMemorySize</code> 를 명시해 <b>힙 밖도 한도가 있게</b> 만드는 것입니다.",
},
{
  t: "log", k: "한 번 죽은 스케줄러는 다시 안 돈다", cat: "logs", d: 3, track: "java",
  file: "/var/log/order-svc/app.log",
  q: "매분 돌던 동기화 작업이 어느 순간부터 아무 로그도 남기지 않습니다. 원인 줄을 고르세요.",
  items: [
    { txt: "14:00:00 INFO  sched: scheduleAtFixedRate(sync, 0, 60, SECONDS) 등록" },
    { txt: "14:00:30 INFO  sched: 스레드 풀 1, 대기 작업 0" },
    { txt: "14:01:00 INFO  sync: 완료 (변경 12건)" },
    { txt: "14:02:00 ERROR sync: NullPointerException at SyncJob.merge" },
    { txt: "14:02:00 INFO  sched: 작업 예외 발생 — 이후 스케줄 취소됨(반환된 Future 를 아무도 확인하지 않음)", bad: true },
    { txt: "14:10:00 WARN  ops: sync 로그가 8분째 없음" },
    { txt: "15:00:00 ERROR ops: 재고 수치가 한 시간째 갱신 안 됨" },
  ],
  ex: "<code>scheduleAtFixedRate</code> 는 작업이 예외를 던지면 <b>그 뒤 실행을 조용히 중단</b>합니다. 예외는 반환된 <code>Future</code> 안에 담기므로, 아무도 <code>get()</code> 을 부르지 않으면 로그조차 남지 않습니다. NPE 한 줄은 방아쇠이고, 사고는 <b>그 뒤로 영영 안 돈다</b>는 데 있습니다. 처방은 작업 본문을 <code>try/catch</code> 로 감싸 절대 예외가 새어 나가지 않게 하는 것이고, 예방은 '마지막 성공 시각' 을 지표로 두어 <b>안 도는 것</b>을 경보로 잡는 것입니다.",
},
{
  t: "log", k: "배포 때마다 잘리는 요청", cat: "logs", d: 2, track: "java",
  file: "/var/log/order-svc/app.log",
  q: "무중단 배포라는데 배포 순간마다 오류가 수백 건 찍힙니다. 원인 줄을 고르세요.",
  items: [
    { txt: "15:00:00 INFO  deploy: 롤링 업데이트 시작, 파드 4개" },
    { txt: "15:00:01 INFO  k8s: SIGTERM 전송 → 파드 1" },
    { txt: "15:00:01 INFO  app: 컨텍스트 즉시 종료, 진행 중 요청 처리 안 함", bad: true },
    { txt: "15:00:01 WARN  lb: 파드 1 로 보낸 요청 180건 연결 끊김" },
    { txt: "15:00:02 ERROR client: 502 Bad Gateway 184건" },
    { txt: "15:00:30 INFO  deploy: 파드 2~4 도 같은 패턴 반복" },
  ],
  ex: "종료 신호를 받고 <b>곧바로</b> 닫았습니다. 처리 중이던 요청은 응답을 받지 못하고, 로드밸런서가 목록에서 빼기까지의 짧은 틈에 들어온 요청도 끊깁니다. 처방은 <b>우아한 종료</b> — SIGTERM 을 받으면 새 요청만 거절하고 진행 중인 것을 끝낸 뒤 닫는 것(<code>server.shutdown=graceful</code>)이며, 그 전에 <code>preStop</code> 으로 몇 초 기다려 로드밸런서가 먼저 빼도록 해야 완전해집니다.",
},
{
  t: "log", k: "배포 직후만 느린 것은 누수가 아니다", cat: "logs", d: 3, track: "java",
  file: "/var/log/order-svc/app.log",
  q: "배포 직후 2분간만 응답이 느리고 그 뒤 정상입니다. 원인 줄을 고르세요.",
  items: [
    { txt: "16:00:00 INFO  deploy: 새 파드 기동, 트래픽 즉시 25% 유입" },
    { txt: "16:00:05 WARN  api: p95 1,900ms (평소 45ms)" },
    { txt: "16:00:10 INFO  jvm: 힙 사용 400MB, GC 정상, 스레드 60" },
    { txt: "16:00:15 INFO  jvm: JIT 컴파일 대기 큐 4,100, 대부분 인터프리터로 실행 중", bad: true },
    { txt: "16:01:40 INFO  jvm: C2 컴파일 완료율 96%" },
    { txt: "16:02:00 INFO  api: p95 47ms 로 회복" },
    { txt: "16:02:10 WARN  ops: 배포마다 같은 구간에서 알림이 울려 무시하는 습관이 생김" },
  ],
  ex: "느린 이유는 누수도 GC 도 아니라 <b>아직 컴파일되지 않아서</b>입니다. JVM 은 처음에는 인터프리터로 돌다가 자주 쓰이는 코드를 기계어로 바꾸므로, 새 파드는 몇 분간 느립니다. 힙과 GC 가 멀쩡하다는 줄이 그 방향을 이미 가리킵니다. 처방은 트래픽을 <b>천천히 올리고</b>(준비성 프로브 + 가중치) 기동 시 주요 경로를 예열하는 것이며, 예방은 배포 직후 구간을 경보에서 <b>따로 다루는</b> 것입니다.",
},
{
  t: "log", k: "대문자로 바꿨을 뿐인데", cat: "logs", d: 4, track: "java",
  file: "/var/log/order-svc/app.log",
  q: "터키 지역 사용자만 로그인에 실패합니다. 원인 줄을 고르세요.",
  items: [
    { txt: "17:00:00 INFO  auth: 로그인 요청 정상 처리 (ko, en, ja)" },
    { txt: "17:00:10 INFO  auth: 토큰 서명·만료 검증 로직 변경 없음" },
    { txt: "17:00:20 WARN  auth: tr 지역 요청 실패율 100%" },
    { txt: "17:00:30 INFO  auth: 컨테이너 기본 로케일이 요청 헤더에 따라 설정됨" },
    { txt: "17:00:40 INFO  auth: 헤더 이름 비교에 name.toUpperCase() 사용 (로케일 미지정)", bad: true },
    { txt: "17:00:45 INFO  auth: 'title'.toUpperCase() → 'TİTLE' (점 있는 İ)" },
    { txt: "17:00:50 ERROR auth: 헤더 조회 실패 → 토큰 없음 → 401" },
  ],
  ex: "로케일을 지정하지 않은 <code>toUpperCase()</code> 는 <b>기본 로케일</b>을 따릅니다. 터키어에서 i 의 대문자는 점이 있는 İ 라서 문자열 비교가 어긋나고, 다른 지역에서는 절대 재현되지 않습니다. 실패율 100% 라는 경고는 증상입니다. 처방은 기계적인 비교에 <code>toUpperCase(Locale.ROOT)</code> 를 쓰는 것이고, 예방은 <b>사람에게 보여 줄 때만</b> 사용자 로케일을 쓰고 내부 처리에는 절대 쓰지 않는 규칙입니다.",
},
];
