/* react 트랙 로그 분석 — 브라우저 콘솔·프로파일러·빌드 로그를 읽고 원인을 짚는다. */
module.exports = [
{
  t: "log", k: "렌더가 멈추지 않는다", cat: "logs", d: 2, track: "react",
  file: "browser-console.log",
  q: "화면이 열리자마자 탭이 멈추고 팬이 돕니다. 원인 줄을 고르세요.",
  items: [
    { txt: "09:00:00 INFO  app: mount <Dashboard/>" },
    { txt: "09:00:00 INFO  fetch: GET /api/widgets 200 (41ms)" },
    { txt: "09:00:00 WARN  react: Dashboard 가 1초에 780회 렌더" },
    { txt: "09:00:01 INFO  react: useEffect(() => setItems(data)) — 의존성 배열 없음", bad: true },
    { txt: "09:00:02 WARN  react: setState 호출 깊이 경고, 이벤트 루프 점유 98%" },
    { txt: "09:00:05 ERROR react: Maximum update depth exceeded" },
  ],
  ex: "의존성 배열이 없는 <code>useEffect</code> 는 <b>렌더가 끝날 때마다</b> 실행됩니다. 그 안에서 상태를 바꾸니 다시 렌더되고, 다시 효과가 돌아 무한 고리가 됩니다. 780회 렌더와 update depth 오류는 그 결과입니다. 처방은 <code>useEffect(..., [data])</code> 처럼 <b>언제 다시 돌아야 하는지</b>를 적어 주는 것이고, 애초에 data 로부터 계산되는 값이면 상태로 만들지 말고 <b>렌더 중에 계산</b>하면 효과 자체가 필요 없습니다.",
},
{
  t: "log", k: "타이머가 옛날 값을 본다", cat: "logs", d: 3, track: "react",
  file: "browser-console.log",
  q: "카운터가 1에서 더 오르지 않습니다. 원인 줄을 고르세요.",
  items: [
    { txt: "10:00:00 INFO  app: mount <Timer/> count=0, useEffect(..., []) 에서 setInterval 등록" },
    { txt: "10:00:01 INFO  react: interval tick — setCount(count + 1), count 는 0", bad: true },
    { txt: "10:00:02 WARN  react: 렌더는 매 초 일어나는데 count 는 계속 1" },
    { txt: "10:00:03 INFO  react: interval 콜백은 등록 시점 렌더의 변수를 계속 참조" },
    { txt: "10:00:30 WARN  app: 사용자 신고 — 타이머가 멈춘 것처럼 보임" },
    { txt: "10:00:45 WARN  app: 새로고침해도 같은 증상, 콘솔 오류는 없음" },
  ],
  ex: "빈 의존성 배열로 한 번만 등록한 콜백은 <b>그때의 렌더에 갇혀</b> 있습니다. 그 안의 <code>count</code> 는 영원히 0 이라 <code>setCount(0 + 1)</code> 만 반복합니다 — 오래된 클로저입니다. 매 초 렌더된다는 경고는 증상입니다. 처방은 <code>setCount(c => c + 1)</code> 처럼 <b>이전 값을 인자로 받는 갱신</b>을 쓰는 것이고, 콜백이 최신 값을 봐야 한다면 ref 에 담거나 의존성에 넣어 다시 등록해야 합니다.",
},
{
  t: "log", k: "목록을 지웠더니 엉뚱한 입력이 남는다", cat: "logs", d: 3, track: "react",
  file: "browser-console.log",
  q: "가운데 항목을 지웠더니 아래 항목에 적어 둔 입력값이 위로 밀려 남습니다. 원인 줄을 고르세요.",
  items: [
    { txt: "11:00:00 INFO  app: <TodoList> 항목 5개 렌더" },
    { txt: "11:00:05 INFO  app: 각 항목은 내부에 <input> 상태를 가짐" },
    { txt: "11:00:10 INFO  react: 목록 렌더에 key={index} 사용", bad: true },
    { txt: "11:00:20 INFO  app: 사용자가 가운데 항목 삭제" },
    { txt: "11:00:20 WARN  react: 3~5번 컴포넌트가 언마운트되지 않고 재사용됨" },
    { txt: "11:00:21 WARN  app: 입력값이 한 칸씩 밀려 보임" },
  ],
  ex: "<code>key</code> 는 리액트가 <b>어느 것이 어느 것인지</b> 알아보는 이름표입니다. 인덱스를 쓰면 항목이 지워졌을 때 3번이 2번이 되므로 리액트는 '2번은 그대로 있다' 고 판단해 컴포넌트와 그 안의 상태를 재사용합니다. 밀려 보이는 입력값은 그 결과입니다. 처방은 <b>항목 자체의 고유 id</b>를 key 로 쓰는 것이고, 순서가 절대 바뀌지 않는 정적 목록이 아니라면 인덱스는 쓰지 않습니다.",
},
{
  t: "log", k: "화면을 떠나도 계속 듣고 있다", cat: "logs", d: 2, track: "react",
  file: "browser-console.log",
  q: "여러 화면을 오가다 보면 브라우저가 점점 느려집니다. 원인 줄을 고르세요.",
  items: [
    { txt: "12:00:00 INFO  app: route /chat 진입, WebSocket 연결" },
    { txt: "12:00:02 INFO  react: useEffect 에서 socket.on('msg', handler) 등록" },
    { txt: "12:00:05 INFO  react: 정리 함수(return) 없음 — 언마운트 시 해제 안 됨", bad: true },
    { txt: "12:01:00 INFO  app: route /chat ↔ /home 12회 이동" },
    { txt: "12:01:30 WARN  app: 같은 메시지가 12번 화면에 표시" },
    { txt: "12:02:00 WARN  perf: JS 힙 48MB → 410MB, 리스너 수 1,344" },
    { txt: "12:03:00 ERROR app: 탭 응답 없음" },
  ],
  ex: "효과가 등록한 구독을 <b>떠날 때 풀지 않았습니다</b>. 화면을 오갈 때마다 리스너가 하나씩 쌓여 같은 메시지를 여러 번 처리하고, 해제되지 않은 클로저가 옛 컴포넌트 트리를 붙잡아 메모리도 늘어납니다. 힙 증가와 중복 표시는 같은 원인의 두 얼굴입니다. 처방은 효과에서 <b>정리 함수를 돌려주는 것</b>(<code>return () =&gt; socket.off('msg', handler)</code>) 이고, 예방은 '등록하는 코드를 쓸 때 해제부터 쓰기' 입니다.",
},
{
  t: "log", k: "서버와 브라우저가 다른 화면을 그린다", cat: "logs", d: 3, track: "react",
  file: "browser-console.log",
  q: "새로고침할 때마다 화면이 한 번 깜빡이며 다시 그려집니다. 원인 줄을 고르세요.",
  items: [
    { txt: "13:00:00 INFO  ssr: /orders 렌더 완료 (34ms)" },
    { txt: "13:00:00 INFO  ssr: 응답 HTML 에 '방금 전' 텍스트 포함" },
    { txt: "13:00:01 INFO  client: hydration 시작" },
    { txt: "13:00:01 INFO  react: 렌더 중 new Date() 로 상대 시간 계산", bad: true },
    { txt: "13:00:01 WARN  react: Text content did not match. Server: '방금 전' Client: '1초 전'" },
    { txt: "13:00:01 WARN  react: 트리 전체를 클라이언트에서 다시 렌더" },
    { txt: "13:00:02 WARN  perf: LCP 2.9초 (하이드레이션 재렌더 포함)" },
  ],
  ex: "렌더 중에 <b>서버와 브라우저에서 값이 달라지는 것</b>을 읽었습니다. 하이드레이션은 서버가 보낸 HTML 과 클라이언트 렌더가 같다고 가정하므로, 다르면 리액트는 그 부분(때로는 트리 전체)을 버리고 다시 그립니다 — 깜빡임과 LCP 악화가 그것입니다. 처방은 시간·난수처럼 변하는 값을 <b>효과 안에서 채우고</b> 첫 렌더에는 서버가 보낸 값을 그대로 쓰는 것입니다.",
},
{
  t: "log", k: "아이콘 하나에 300KB", cat: "logs", d: 2, track: "react",
  file: "vite-build.log",
  q: "번들이 갑자기 세 배로 커졌습니다. 원인 줄을 고르세요.",
  items: [
    { txt: "14:00:00 INFO  build: 시작, 이전 번들 210KB (gzip)" },
    { txt: "14:00:05 INFO  build: 의존성 설치 변경 없음, 락파일 동일" },
    { txt: "14:00:20 INFO  build: 청크 vendor 612KB · app 98KB" },
    { txt: "14:00:21 WARN  build: 단일 청크 500KB 초과 경고" },
    { txt: "14:00:25 INFO  build: import { Check } from 'ui-kit' — 배럴 파일이 컴포넌트 340개를 재수출", bad: true },
    { txt: "14:00:26 INFO  build: ui-kit 은 사이드이펙트 표시가 없어 트리셰이킹 불가" },
    { txt: "14:00:40 WARN  perf: 초기 로드 TTI 1.4초 → 4.1초" },
  ],
  ex: "배럴 파일에서 하나만 가져와도 <b>재수출된 340개가 모두 그래프에 들어옵니다</b>. 패키지에 <code>sideEffects: false</code> 표시가 없으면 번들러는 지워도 되는지 알 수 없어 통째로 남깁니다. 청크 경고와 TTI 악화는 그 결과입니다. 처방은 <code>import Check from 'ui-kit/Check'</code> 처럼 <b>실제 파일을 직접 가리키거나</b> 패키지에 사이드이펙트 표시를 하는 것이고, 예방은 번들 크기를 CI 예산으로 묶는 것입니다.",
},
{
  t: "log", k: "컨텍스트 하나가 앱 전체를 다시 그린다", cat: "logs", d: 3, track: "react",
  file: "profiler.log",
  q: "글자 하나 입력할 때마다 관계없는 화면까지 다시 그려집니다. 원인 줄을 고르세요.",
  items: [
    { txt: "15:00:00 INFO  profiler: 커밋 1 — 렌더된 컴포넌트 412개, 18ms" },
    { txt: "15:00:00 INFO  profiler: 전체 트리 컴포넌트 수 430" },
    { txt: "15:00:01 INFO  profiler: 입력 한 글자마다 커밋 1회" },
    { txt: "15:00:02 WARN  profiler: React.memo 로 감싼 컴포넌트도 다시 렌더됨" },
    { txt: "15:00:03 INFO  react: <AppContext.Provider value={{user, theme, setQuery}}> — 매 렌더 새 객체", bad: true },
    { txt: "15:00:04 INFO  profiler: 구독 컴포넌트 389개가 값 변경으로 판정" },
    { txt: "15:00:10 WARN  perf: 입력 지연 p95 240ms" },
  ],
  ex: "Provider 의 <code>value</code> 를 <b>렌더마다 새로 만든 객체</b>로 주면, 내용이 같아도 참조가 달라 모든 구독자가 변경으로 봅니다. <code>React.memo</code> 는 props 를 비교할 뿐 컨텍스트 구독은 막지 못하므로 소용이 없습니다 — 그 경고가 힌트였습니다. 처방은 <code>useMemo</code> 로 value 를 고정하고, 더 나아가 <b>자주 바뀌는 값과 거의 안 바뀌는 값을 다른 컨텍스트로 쪼개는 것</b>입니다.",
},
{
  t: "log", k: "한 글자에 표 전체를 다시 계산한다", cat: "logs", d: 2, track: "react",
  file: "profiler.log",
  q: "검색창 입력이 눈에 띄게 밀립니다. 원인 줄을 고르세요.",
  items: [
    { txt: "16:00:00 INFO  profiler: <SearchPage> 마운트, 행 12,000" },
    { txt: "16:00:02 INFO  profiler: 초기 렌더 190ms (허용 범위)" },
    { txt: "16:00:04 INFO  app: 검색창은 제어 컴포넌트, 상태는 페이지에 있음" },
    { txt: "16:00:05 INFO  profiler: 입력 이벤트 → 상태 갱신 → 커밋" },
    { txt: "16:00:06 WARN  profiler: 커밋당 렌더 시간 180ms" },
    { txt: "16:00:07 INFO  react: 렌더 본문에서 rows.filter(...).sort(...) 를 매번 수행", bad: true },
    { txt: "16:00:08 INFO  profiler: filter+sort 만 162ms, 실제 DOM 갱신 9ms" },
    { txt: "16:00:20 WARN  perf: 입력 지연 p95 210ms, 키 입력 유실 신고" },
  ],
  ex: "무거운 계산이 <b>렌더 본문</b>에 있어 키를 누를 때마다 12,000행을 다시 거릅니다. DOM 갱신은 9ms 뿐이므로 병목은 리액트가 아니라 계산입니다. 처방은 <code>useMemo(() =&gt; rows.filter(...).sort(...), [rows, query])</code> 로 <b>입력이 바뀔 때만</b> 계산하고, 그래도 무거우면 입력을 디바운스하거나 목록을 가상화하는 것입니다. 예방은 프로파일러에서 <b>렌더 시간과 커밋 시간을 나눠 보는</b> 습관입니다.",
},
{
  t: "log", k: "요청이 줄을 서서 온다", cat: "logs", d: 2, track: "react",
  file: "browser-console.log",
  q: "데이터가 다 뜨기까지 2초가 넘게 걸립니다. 원인 줄을 고르세요.",
  items: [
    { txt: "17:00:00 INFO  fetch: GET /api/me 200 (180ms) — 응답 뒤 <Orders> 렌더 시작" },
    { txt: "17:00:01 INFO  fetch: GET /api/orders 200 (240ms) — /me 응답 후 시작", bad: true },
    { txt: "17:00:01 INFO  fetch: GET /api/coupons 200 (210ms) — /orders 응답 후 시작" },
    { txt: "17:00:02 WARN  perf: 세 요청이 겹치지 않음, 총 대기 630ms" },
    { txt: "17:00:02 WARN  perf: 첫 화면 완성까지 2.1초" },
    { txt: "17:00:03 WARN  perf: 같은 세 요청을 함께 보내면 240ms 면 끝난다" },
  ],
  ex: "부모가 받아야 자식이 렌더되고, 자식이 렌더돼야 다음 요청이 시작되는 <b>폭포수</b>입니다. 세 요청은 서로 필요하지 않은데도 순서대로 줄을 섰습니다. 겹치지 않는다는 경고는 그 모양을 그대로 보여 줍니다. 처방은 서로 독립인 요청을 <b>한 곳에서 병렬로</b> 시작하는 것(<code>Promise.all</code>, 라우트 로더, 프리페치)이고, 목록이 필요한 상세 정보는 <b>부모가 미리 함께 요청</b>해 자식이 기다리지 않게 하는 것입니다.",
},
{
  t: "log", k: "늦게 온 응답이 화면을 덮어쓴다", cat: "logs", d: 3, track: "react",
  file: "browser-console.log",
  q: "검색어를 빠르게 바꾸면 이전 검색 결과가 화면에 남습니다. 원인 줄을 고르세요.",
  items: [
    { txt: "18:00:00 INFO  app: 검색창 입력 시작, 디바운스 없음" },
    { txt: "18:00:00 INFO  app: query='ap' → GET /search?q=ap 시작" },
    { txt: "18:00:00 INFO  app: query='apple' → GET /search?q=apple 시작" },
    { txt: "18:00:01 INFO  fetch: /search?q=apple 200 (120ms) → setResults" },
    { txt: "18:00:02 INFO  fetch: /search?q=ap 200 (980ms) → setResults", bad: true },
    { txt: "18:00:02 WARN  app: 화면 결과가 'ap' 것으로 바뀜 (입력은 'apple')" },
    { txt: "18:00:30 WARN  app: 사용자 신고 — 검색 결과가 입력과 어긋남" },
  ],
  ex: "먼저 보낸 요청이 <b>나중에 도착</b>했고, 취소하지 않았으므로 그 응답이 최신 결과를 덮어썼습니다. 응답 순서는 요청 순서를 지키지 않는다는 것이 핵심입니다. 처방은 새 요청을 보낼 때 <code>AbortController</code> 로 이전 것을 끊거나, 효과의 정리 함수에서 <b>취소 플래그</b>를 세워 늦게 온 응답을 버리는 것입니다. 라이브러리를 쓴다면 쿼리 키에 검색어를 넣어 <b>키가 다른 응답은 서로 덮지 않게</b> 합니다.",
},
{
  t: "log", k: "두 번 실행되는 효과", cat: "logs", d: 3, track: "react",
  file: "browser-console.log",
  q: "개발 모드에서만 결제 요청이 두 번 나갑니다. 원인 줄을 고르세요.",
  items: [
    { txt: "19:00:00 INFO  app: StrictMode 활성 (개발 모드)" },
    { txt: "19:00:01 INFO  react: <Checkout> 마운트 → 효과 실행 → 정리 → 재실행" },
    { txt: "19:00:01 INFO  app: 효과 본문에서 POST /pay 호출, 정리 함수 없음", bad: true },
    { txt: "19:00:02 WARN  api: POST /pay 두 건, 동일 카트 id, 멱등 키 없음" },
    { txt: "19:00:03 WARN  api: 두 건 모두 승인됨" },
    { txt: "19:00:10 ERROR ops: 이중 청구 문의 접수" },
  ],
  ex: "StrictMode 는 <b>효과를 일부러 두 번 실행</b>해 정리가 빠진 곳을 드러냅니다. 문제는 두 번 실행하는 개발 모드가 아니라, 효과가 <b>다시 실행되면 안 되는 부수효과</b>를 담고 있다는 것입니다 — 운영에서도 재연결·재마운트로 같은 일이 일어납니다. 처방은 결제 같은 동작을 효과가 아니라 <b>사용자 행동 핸들러</b>에서 부르고, 서버에는 <b>멱등 키</b>를 함께 보내 같은 요청을 두 번 받아도 한 번만 처리하게 하는 것입니다.",
},
{
  t: "log", k: "만 개의 DOM 노드", cat: "logs", d: 2, track: "react",
  file: "profiler.log",
  q: "목록을 스크롤하면 프레임이 뚝뚝 끊깁니다. 원인 줄을 고르세요.",
  items: [
    { txt: "20:00:00 INFO  profiler: <Feed> 마운트, 데이터 10,000건" },
    { txt: "20:00:01 INFO  profiler: 초기 커밋 2,400ms" },
    { txt: "20:00:02 WARN  perf: DOM 노드 84,000개, 스타일 재계산 610ms" },
    { txt: "20:00:03 INFO  react: rows.map 으로 10,000행을 모두 렌더 (가상화 없음)", bad: true },
    { txt: "20:00:05 WARN  perf: 스크롤 중 프레임 12fps, 롱태스크 8회" },
    { txt: "20:00:30 WARN  perf: 모바일에서 탭 강제 종료 보고" },
  ],
  ex: "보이지도 않는 <b>1만 행을 전부 DOM 에 만들었습니다</b>. 노드가 많으면 렌더뿐 아니라 스타일 재계산·레이아웃이 모두 느려지고, 스크롤마다 롱태스크가 생깁니다. 84,000 노드와 12fps 는 원인이 아니라 그 결과입니다. 처방은 <b>가상화</b> — 화면에 보이는 20~30행만 만들고 스크롤에 따라 갈아 끼우는 것이며, 그 전에 페이지네이션으로 데이터 자체를 줄일 수 있으면 그것이 더 낫습니다.",
},
];
