/* 로그 분석 32문항 — php · dbt · dl · mobile 각 8개.
   log 이 0인 트랙 중 '운영 중 기록을 읽고 원인을 짚는' 것이 자연스러운 넷이다.

   설계 원칙(ver_log.cjs 가 검사하는 것들):
     · 원인 줄은 대개 INFO — ERROR 는 뒤따라온 증상이라, 등급으로 찍히면 훈련이 안 된다
     · 앞쪽에 상관없는 WARN 을 하나 깔아 '첫 WARN 이상' 규칙을 깬다
     · 원인 줄은 짧게, 세부(파일·수치·요청 ID)는 증상 줄에 붙인다
     · 자리는 미리 배분한다 */
module.exports = [

/* ══════════════ php ══════════════ */
{
  t: "log", k: "500 인데 로그가 비어 있다", cat: "logs", d: 3, track: "php",
  file: "php-fpm.log · nginx error.log",
  q: "요청이 500 으로 끝나는데 애플리케이션 로그에는 아무것도 남지 않습니다. 이유가 되는 한 줄을 고르세요.",
  items: [
    { txt: "10:00:01 WARN  nginx: ssl certificate for api.example.com expires in 21 days", bad: false },
    { txt: "10:02:14 INFO  php-fpm: pool www started, log_errors=Off display_errors=Off", bad: true },
    { txt: "10:02:41 INFO  nginx: POST /orders HTTP/1.1 upstream fastcgi://127.0.0.1:9000", bad: false },
    { txt: "10:02:41 ERROR nginx: upstream sent no data while reading response header", bad: false },
    { txt: "10:02:41 ERROR nginx: POST /orders 500 0 bytes sent, request id 9f21ac", bad: false },
    { txt: "10:02:41 INFO  php-fpm: child 3312 exited on signal 11 (SIGSEGV) after 0.4s", bad: false },
    { txt: "10:03:00 INFO  monitor: application log file /var/log/app.log unchanged for 41 minutes", bad: false },
  ],
  ex: "치명적 오류가 실제로 났고(자식 프로세스가 신호 11로 죽었습니다) 웹 서버는 그 사실을 정직하게 500으로 알렸습니다. 그런데 <b>기록을 남기는 설정이 꺼져</b> 있으니 원인을 적을 곳이 없습니다. <code>display_errors</code> 를 운영에서 끄는 것은 옳지만 <code>log_errors</code> 까지 끄면 사고가 통째로 보이지 않게 됩니다. 둘은 하는 일이 다릅니다 — 하나는 사용자에게 보여 줄지, 다른 하나는 우리가 남길지입니다. 먼저 기록을 켜고 <code>error_log</code> 경로를 정한 뒤에야 진짜 원인을 찾을 수 있습니다.",
},
{
  t: "log", k: "업로드가 조용히 사라진다", cat: "logs", d: 3, track: "php",
  file: "php error.log",
  q: "8MB 파일 업로드가 오류 없이 실패하고 서버에는 파일이 없습니다. 한계를 정한 한 줄을 고르세요.",
  items: [
    { txt: "13:40:02 WARN  php: session.gc_maxlifetime is shorter than the cookie lifetime", bad: false },
    { txt: "13:41:10 INFO  php: request POST /upload content-length 8,412,904", bad: false },
    { txt: "13:41:10 INFO  php: post_max_size=8M upload_max_filesize=32M memory_limit=256M", bad: true },
    { txt: "13:41:10 WARN  php: POST Content-Length of 8412904 bytes exceeds the limit", bad: false },
    { txt: "13:41:10 INFO  app: $_FILES is empty, $_POST is empty, proceeding with defaults", bad: false },
    { txt: "13:41:10 INFO  app: upload handler finished, redirect 302 to /upload?ok=1", bad: false },
    { txt: "13:45:00 INFO  monitor: upload success rate 61 percent over the last hour", bad: false },
  ],
  ex: "한도가 <b>두 개</b>이고 작은 쪽이 이깁니다. 파일 하나의 상한은 32MB 로 넉넉한데 요청 전체의 상한이 8MB 라, 파일에 양식 값과 경계 문자열까지 더해진 요청이 그 선을 넘습니다. 무서운 점은 실패하는 방식입니다 — 넘긴 요청은 본문을 통째로 버리므로 <code>$_FILES</code> 도 <code>$_POST</code> 도 <b>빈 채로</b> 코드에 도착합니다. 그래서 애플리케이션은 아무 일도 없었다는 듯 성공 화면으로 보냅니다. 두 값을 함께 올리고, 빈 요청을 성공으로 다루지 않도록 코드에서도 확인해야 합니다.",
},
{
  t: "log", k: "로그인이 자꾸 풀린다", cat: "logs", d: 3, track: "php",
  file: "app.log · lb access log",
  q: "사용자가 몇 번 클릭하면 로그아웃됩니다. 원인을 알려 주는 한 줄을 고르세요.",
  items: [
    { txt: "09:10:00 WARN  app: deprecated function strftime() called in report.php", bad: false },
    { txt: "09:12:01 INFO  lb: GET /me -> web-01, session 7c1f, user 41", bad: false },
    { txt: "09:12:03 INFO  lb: GET /cart -> web-02, session 7c1f, user (none)", bad: false },
    { txt: "09:12:03 INFO  app[web-02]: session 7c1f not found, creating a new empty session", bad: false },
    { txt: "09:12:03 INFO  php[web-02]: session.save_handler=files, local save_path", bad: true },
    { txt: "09:12:04 ERROR app[web-02]: redirect to /login, referer /cart", bad: false },
    { txt: "09:12:09 INFO  lb: GET /me -> web-01, session 7c1f, user 41", bad: false },
  ],
  ex: "같은 세션 번호를 들고 갔는데 서버에 따라 로그인 상태가 달라집니다. 서버가 둘이고 세션을 <b>각자의 로컬 파일</b>에 담기 때문입니다 — 처음 로그인한 서버에만 그 파일이 있으니, 다른 서버로 간 요청은 '모르는 세션' 을 받습니다. 로드밸런서 기록이 그 왕복을 그대로 보여 줍니다. 고치는 길은 둘입니다: 세션을 공유 저장소에 두거나(레디스·데이터베이스), 같은 사용자를 늘 같은 서버로 보내는 것입니다. 뒤쪽은 그 서버가 죽으면 모두 로그아웃되므로, 대개는 공유 저장소가 답입니다.",
},
{
  t: "log", k: "목록 화면에서만 메모리가 터진다", cat: "logs", d: 3, track: "php",
  file: "php error.log",
  q: "주문 목록 화면만 메모리 부족으로 죽습니다. 그렇게 만든 한 줄을 고르세요.",
  items: [
    { txt: "22:00:00 WARN  php: opcache.revalidate_freq is 60, changes may take a minute", bad: false },
    { txt: "22:03:11 INFO  app: GET /orders/export requested by admin 7", bad: false },
    { txt: "22:03:11 INFO  db: select * from orders returned 1,240,000 rows in 8.2s", bad: false },
    { txt: "22:03:19 INFO  app: fetchAll() into array, building csv string in memory", bad: true },
    { txt: "22:03:24 ERROR php: Allowed memory size of 268435456 bytes exhausted (tried 8192)", bad: false },
    { txt: "22:03:24 ERROR nginx: upstream prematurely closed connection, returning 502", bad: false },
    { txt: "22:04:00 INFO  monitor: php-fpm memory peak 256MB, other endpoints under 40MB", bad: false },
  ],
  ex: "결과가 124만 줄인데 그것을 <b>통째로 배열에 담고</b> 다시 문자열 하나로 이어 붙였습니다. 한도를 올려도 데이터가 늘면 같은 자리에서 다시 죽으므로 이것은 설정 문제가 아닙니다. 내보내기는 <b>흘려보내는 방식</b>으로 바꿔야 합니다 — 한 줄씩 읽어 한 줄씩 내보내면 메모리 사용량이 데이터 크기와 무관해집니다. 다른 화면들이 40MB 안에서 도는 것이 이 화면만의 문제라는 것을 알려 주고, 502 는 PHP 가 죽어 응답이 끊긴 결과일 뿐입니다.",
},
{
  t: "log", k: "동시 접속이 늘자 502 가 난다", cat: "logs", d: 4, track: "php",
  file: "php-fpm.log · nginx error.log",
  q: "부하가 조금 늘자 502 가 쏟아집니다. 대기를 만든 한 줄을 고르세요.",
  items: [
    { txt: "18:00:00 WARN  nginx: worker_connections 1024 may be low for this traffic", bad: false },
    { txt: "18:20:00 INFO  php-fpm: pool www pm=static pm.max_children=5", bad: false },
    { txt: "18:21:00 INFO  app: external payment API latency rose from 80ms to 3,100ms", bad: true },
    { txt: "18:21:30 WARN  php-fpm: server reached pm.max_children setting, consider raising it", bad: false },
    { txt: "18:21:31 INFO  php-fpm: listen queue 128 of 128 used, 412 requests waiting", bad: false },
    { txt: "18:21:40 ERROR nginx: connect() to unix:/run/php-fpm.sock failed, resource temporarily unavailable", bad: false },
    { txt: "18:21:40 ERROR nginx: GET /checkout 502 in 0ms, 1,204 occurrences in one minute", bad: false },
  ],
  ex: "일꾼이 다섯인데 <b>한 명이 3초씩 붙잡혀 있으면</b> 초당 두 요청도 못 받습니다. 늘어난 것은 접속 수가 아니라 <b>한 요청이 잡고 있는 시간</b>입니다 — 바깥 결제 API 가 느려지면서 일꾼들이 전부 그것을 기다리는 데 묶였고, 그 뒤로 들어온 요청이 대기줄을 채우다 넘쳐 502 가 됐습니다. <code>max_children</code> 을 올리면 잠깐 버티지만 메모리가 먼저 바닥납니다. 진짜 처방은 바깥 호출에 <b>짧은 제한 시간</b>을 걸고, 회로 차단기로 아픈 곳을 잠시 끊고, 늦어도 되는 일은 큐로 보내는 것입니다.",
},
{
  t: "log", k: "느린 것은 쿼리 하나가 아니다", cat: "logs", d: 3, track: "php",
  file: "slow query log · app.log",
  q: "목록 화면이 4초 걸리는데 느린 쿼리 기록에는 아무것도 없습니다. 이유를 알려 주는 한 줄을 고르세요.",
  items: [
    { txt: "11:00:00 WARN  db: table orders has not been analyzed for 34 days", bad: false },
    { txt: "11:05:01 INFO  app: GET /orders rendered in 4,120ms", bad: false },
    { txt: "11:05:01 INFO  db: select * from orders limit 100 -- 8ms", bad: false },
    { txt: "11:05:01 INFO  db: slow query log threshold is 1000ms, 0 entries recorded today", bad: false },
    { txt: "11:05:01 INFO  db: 100 queries of 'select * from users where id = ?' -- 6ms each", bad: true },
    { txt: "11:05:02 INFO  app: template rendering 41ms, serialization 12ms", bad: false },
    { txt: "11:06:00 INFO  monitor: /orders p50 3,900ms p99 5,200ms, database CPU 12 percent", bad: false },
  ],
  ex: "느린 쿼리 기록이 비어 있는 것은 <b>느린 쿼리가 없기 때문</b>입니다. 각 쿼리는 6밀리초로 빠르고 임계값 근처에도 못 갑니다. 문제는 하나가 느린 것이 아니라 <b>100번 도는 것</b>입니다 — 목록 한 줄마다 사용자를 한 번씩 조회하는 전형적인 모양이고, 왕복 비용까지 더해 4초가 됩니다. 데이터베이스 CPU 가 한가한 것도 같은 이야기를 합니다: 일이 무거운 것이 아니라 왕복이 많습니다. 처방은 한 번에 함께 읽어 오는 것(조인이나 미리 불러오기)이고, 감시에는 <b>요청당 쿼리 수</b>를 함께 남겨야 이런 것이 눈에 띕니다.",
},
{
  t: "log", k: "배포했는데 옛 코드가 돈다", cat: "logs", d: 2, track: "php",
  file: "deploy.log · php-fpm.log",
  q: "배포가 끝났는데도 옛 동작이 그대로입니다. 남아 있는 자리를 고르세요.",
  items: [
    { txt: "15:00:00 WARN  deploy: working tree had 2 untracked files, ignored", bad: false },
    { txt: "15:00:10 INFO  deploy: symlink /srv/app -> releases/2026-09-08-1500", bad: false },
    { txt: "15:00:11 INFO  php-fpm: opcache validate_timestamps=0, 4,120 scripts cached", bad: true },
    { txt: "15:00:11 INFO  deploy: done in 11s, no service restart requested", bad: false },
    { txt: "15:00:40 ERROR app: undefined method Order::settle() called in Checkout.php line 88", bad: false },
    { txt: "15:00:41 WARN  app: error rate 22 percent on /checkout", bad: false },
    { txt: "15:10:00 INFO  ops: file on disk shows the new code, response still shows the old", bad: false },
  ],
  ex: "파일은 바뀌었는데 <b>실행되는 것은 메모리에 담긴 옛 코드</b>입니다. 시간표 확인을 꺼 두면 성능은 좋아지지만, 그 대신 <b>다시 읽을 때를 우리가 알려 줘야</b> 합니다. 배포가 서비스를 다시 띄우지도, 캐시를 비우지도 않았으니 옛 코드가 그대로 남았습니다. 오류가 나는 이유는 더 고약합니다 — 어떤 파일은 새로 캐시되고 어떤 파일은 옛 것이라 <b>반쯤 섞인 상태</b>가 되기 때문입니다. 배포 절차에 캐시 비우기나 부드러운 재시작을 넣으면 됩니다.",
},
{
  t: "log", k: "시각이 아홉 시간 어긋난다", cat: "logs", d: 2, track: "php",
  file: "app.log",
  q: "화면에 찍히는 시각만 아홉 시간 이릅니다. 원인이 되는 한 줄을 고르세요.",
  items: [
    { txt: "08:00:00 WARN  app: composer.lock is older than composer.json", bad: false },
    { txt: "08:30:01 INFO  app: order 8812 created, stored created_at 2026-09-08 08:30:01", bad: false },
    { txt: "08:30:01 INFO  db: session time_zone is '+09:00', server default '+09:00'", bad: false },
    { txt: "08:30:02 INFO  app: rendering order page, formatting created_at for display", bad: false },
    { txt: "08:30:02 INFO  php: date.timezone is not set, falling back to UTC", bad: true },
    { txt: "08:30:02 WARN  app: displayed time 2026-09-07 23:30 differs from stored value", bad: false },
    { txt: "08:30:40 INFO  ops: same row read through the database client shows 08:30:01", bad: false },
  ],
  ex: "저장된 값은 맞습니다 — 데이터베이스로 직접 읽으면 08:30:01 입니다. 어긋나는 것은 <b>보여 줄 때</b>뿐이고, 그 자리에서 쓰는 시간대가 설정되지 않아 협정 세계시로 되돌아간 것입니다. 아홉 시간이라는 크기 자체가 어느 지역과의 차이인지 알려 주는 단서입니다. 이런 종류의 어긋남을 없애는 방법은 규칙을 하나로 정하는 것입니다: <b>저장은 협정 세계시로, 표시할 때만 지역 시간으로.</b> 그리고 그 지역을 애플리케이션 설정에 명시해 두면 서버가 바뀌어도 같은 화면이 나옵니다.",
},

/* ══════════════ dbt ══════════════ */
{
  t: "log", k: "성공했는데 표가 어제 것이다", cat: "logs", d: 3, track: "dbt",
  file: "dbt run log",
  q: "파이프라인이 초록불인데 대시보드 숫자가 어제 그대로입니다. 이유가 되는 한 줄을 고르세요.",
  items: [
    { txt: "04:00:00 WARN  dbt: 3 models have no description, docs will be incomplete", bad: false },
    { txt: "04:00:12 INFO  source raw.orders max loaded_at 2026-09-07 23:10 (28 hours ago)", bad: true },
    { txt: "04:00:13 INFO  running 41 models in 6 threads", bad: false },
    { txt: "04:02:41 INFO  OK created table model analytics.fct_orders in 148s", bad: false },
    { txt: "04:02:41 INFO  fct_orders row count 4,120,441 (yesterday 4,120,441)", bad: false },
    { txt: "04:03:00 INFO  Completed successfully. Done. PASS=41 WARN=0 ERROR=0 SKIP=0", bad: false },
    { txt: "08:10:00 INFO  bi: dashboard refreshed at 08:10, numbers unchanged since yesterday", bad: false },
  ],
  ex: "변환은 완벽하게 성공했습니다 — 다만 <b>어제 데이터를 다시 변환</b>했을 뿐입니다. 원천의 마지막 적재가 28시간 전이므로 상류가 멈춘 것이고, 변환 도구는 그 사실을 알 방법이 없어 정직하게 성공을 알립니다. 행 수가 어제와 똑같은 것이 그 결과입니다. <b>파이프라인이 성공했다는 말과 데이터가 최신이라는 말은 다릅니다.</b> 원천에 신선도 기준을 걸어 두면 이 상황에서 실행이 멈추거나 경보가 울립니다. 그것이 없으면 며칠이고 어제 숫자로 보고가 나갑니다.",
},
{
  t: "log", k: "증분 표에 중복이 쌓인다", cat: "logs", d: 3, track: "dbt",
  file: "dbt run log · test log",
  q: "증분 모델의 유일성 검사가 갑자기 실패합니다. 중복을 만든 한 줄을 고르세요.",
  items: [
    { txt: "02:00:00 WARN  dbt: package dbt_utils is 4 minor versions behind", bad: false },
    { txt: "02:05:00 INFO  upstream: replayed 12,400 events from 2026-09-07 after a fix", bad: false },
    { txt: "02:10:01 INFO  fct_events incremental, unique_key=none", bad: true },
    { txt: "02:12:30 INFO  OK created incremental model fct_events, 12,400 rows added", bad: false },
    { txt: "02:12:40 ERROR FAIL 12400 unique_fct_events_event_id, got 12,400 duplicate values", bad: false },
    { txt: "02:12:41 WARN  dbt: Done. PASS=40 WARN=0 ERROR=1 SKIP=2", bad: false },
    { txt: "06:00:00 INFO  bi: yesterday revenue reported 2x the payment provider total", bad: false },
  ],
  ex: "상류가 어제 것을 다시 보낸 것은 <b>정상적인 일</b>입니다 — 고쳐서 다시 흘리는 일은 늘 있습니다. 문제는 받는 쪽이 그것을 다룰 준비가 안 됐다는 것입니다. 유일 키가 없으면 증분 모델은 갱신할 자리를 찾지 못하고 <b>덧붙이기만</b> 하므로, 다시 온 12,400건이 그대로 사본이 되어 얹힙니다. 매출이 두 배로 보고된 것이 그 결과입니다. 키를 정해 두면 같은 식별자가 다시 왔을 때 덮어쓰므로 몇 번을 다시 보내도 결과가 같아집니다. 검사가 실패해 준 것은 <b>다행</b>입니다 — 없었다면 두 배가 그대로 보고됐습니다.",
},
{
  t: "log", k: "실행 순서가 뒤집혔다", cat: "logs", d: 3, track: "dbt",
  file: "dbt run log",
  q: "하류 모델이 상류보다 먼저 돌아 빈 표를 읽습니다. 원인이 되는 한 줄을 고르세요.",
  items: [
    { txt: "03:00:00 WARN  dbt: profiles.yml threads=16 exceeds the warehouse concurrency limit", bad: false },
    { txt: "03:00:05 INFO  fct_daily_sales compiled from analytics.stg_orders (hardcoded schema)", bad: true },
    { txt: "03:00:06 INFO  dependency graph built: 41 nodes, fct_daily_sales has 0 parents", bad: false },
    { txt: "03:00:07 INFO  OK created table analytics.fct_daily_sales, 0 rows", bad: false },
    { txt: "03:01:40 INFO  OK created table analytics.stg_orders, 4,120,441 rows", bad: false },
    { txt: "03:02:00 WARN  dbt: Completed successfully, 41 models, 1 model produced 0 rows", bad: false },
    { txt: "07:00:00 ERROR bi: daily sales dashboard shows zero for today", bad: false },
  ],
  ex: "부모가 <b>0개</b>라는 줄이 이 사고의 전부를 말합니다. 참조 함수 대신 스키마를 손으로 적으면 도구가 그것을 그냥 문자열로 보므로 의존 관계를 알 수 없고, 그래서 하류 모델을 아무 때나 — 여기서는 상류보다 먼저 — 돌립니다. 그 시점에 상류 표는 비어 있었으니 0행이 나왔고, 도구는 그것을 실패로 볼 이유가 없어 성공을 알립니다. 참조 함수로 바꾸면 순서가 저절로 맞고, 계보 문서와 환경 분리까지 함께 따라옵니다. <b>0행이 나왔을 때 실패시키는 검사</b>를 붙이면 이런 것을 다음번에는 빨리 잡습니다.",
},
{
  t: "log", k: "검사가 통과했는데 숫자가 틀리다", cat: "logs", d: 3, track: "dbt",
  file: "dbt test log",
  q: "모든 검사가 통과했는데 보고 숫자가 어긋납니다. 그 사실을 감춘 한 줄을 고르세요.",
  items: [
    { txt: "05:00:00 WARN  dbt: 2 tests are not documented in schema.yml", bad: false },
    { txt: "05:10:01 INFO  running 88 data tests", bad: false },
    { txt: "05:10:40 INFO  WARN 412 not_null_fct_orders_customer_id (severity: warn)", bad: false },
    { txt: "05:10:41 INFO  Done. PASS=87 WARN=1 ERROR=0 SKIP=0, exit code 0", bad: false },
    { txt: "05:10:42 INFO  test severity for the fct_orders suite is set to warn", bad: true },
    { txt: "05:11:00 INFO  ci: pipeline marked green, downstream refresh triggered", bad: false },
    { txt: "09:00:00 ERROR bi: customer segment report is missing 412 orders", bad: false },
  ],
  ex: "검사는 <b>제대로 잡았습니다</b> — 고객 식별자가 없는 주문이 412건이라고 정확히 알려 주었습니다. 다만 심각도가 경고라 종료 코드가 0이 됐고, 파이프라인은 초록불이 되어 하류를 그대로 새로 고쳤습니다. 그 412건이 어느 고객에도 속하지 않으니 세분화 보고에서 통째로 빠졌습니다. <b>막지 않는 검사는 없는 검사와 같습니다.</b> 경고는 처음 며칠만 보이고 곧 배경이 됩니다. 키에 대한 검사는 실패로 두어 파이프라인을 멈추게 하고, 정말로 허용할 것이라면 그 사실을 모델 안에서 명시적으로 다루는 편이 낫습니다.",
},
{
  t: "log", k: "하룻밤에 비용이 스무 배", cat: "logs", d: 4, track: "dbt",
  file: "dbt run log · warehouse billing",
  q: "평소 몇 분이던 실행이 세 시간을 돌며 비용이 폭증했습니다. 방아쇠가 된 한 줄을 고르세요.",
  items: [
    { txt: "01:00:00 WARN  warehouse: auto-suspend is set to 60 minutes for this warehouse", bad: false },
    { txt: "01:10:00 INFO  upstream: added column promo_code to raw.orders", bad: false },
    { txt: "01:30:02 INFO  fct_orders on_schema_change=sync_all_columns, rebuilding", bad: true },
    { txt: "01:30:03 INFO  fct_orders full refresh scanning 4.1 TB across 38 months", bad: false },
    { txt: "04:22:10 INFO  OK created incremental model fct_orders in 10,087s", bad: false },
    { txt: "04:22:11 WARN  dbt: Completed successfully in 3h 12m (previous run 4m 20s)", bad: false },
    { txt: "09:00:00 ERROR finance: warehouse spend for the day is 2,140 USD (average 108 USD)", bad: false },
  ],
  ex: "상류가 열을 하나 더한 것이 방아쇠였고, 그 변화를 어떻게 다룰지 정해 둔 설정이 <b>전체를 다시 만들라</b>는 쪽이었습니다. 그래서 38개월치 4.1TB 를 통째로 훑었습니다. 이 설정 자체가 나쁜 것은 아닙니다 — 새 열을 자동으로 따라가 주니 편합니다. 다만 큰 표에서는 그 대가가 이런 모양으로 옵니다. 방법은 두 가지입니다: 스키마 변화를 <b>사람이 승인</b>하게 두고 계획된 시점에 다시 만들거나, 실행 시간과 스캔량에 상한과 경보를 걸어 이런 실행이 세 시간을 다 쓰기 전에 멈추게 하는 것입니다.",
},
{
  t: "log", k: "실행이 매주 조금씩 느려진다", cat: "logs", d: 3, track: "dbt",
  file: "dbt run log",
  q: "데이터는 그대로인데 실행 시간이 계속 늘어납니다. 이유를 알려 주는 한 줄을 고르세요.",
  items: [
    { txt: "02:00:00 WARN  dbt: 6 models exceed 300 lines, consider splitting", bad: false },
    { txt: "02:00:10 INFO  materialization summary: view 39, table 2, incremental 0", bad: true },
    { txt: "02:00:11 INFO  model depth: fct_revenue depends on 7 chained views", bad: false },
    { txt: "02:04:30 INFO  OK created view analytics.fct_revenue in 0.4s", bad: false },
    { txt: "02:04:31 INFO  row counts unchanged from last week across all sources", bad: false },
    { txt: "08:00:12 WARN  bi: dashboard query on fct_revenue took 94s (4 weeks ago 22s)", bad: false },
    { txt: "08:00:13 INFO  warehouse: that query scanned 1.8 TB, 7 nested views expanded inline", bad: false },
  ],
  ex: "변환 자체는 0.4초로 빠릅니다 — 뷰를 만드는 일은 <b>정의를 적어 두는 것</b>뿐이라 언제나 빠릅니다. 값을 치르는 쪽은 조회입니다. 일곱 겹의 뷰가 조회 시점에 통째로 펼쳐져 1.8TB 를 훑으므로, 층이 하나 늘 때마다 대시보드가 느려집니다. 실행 시간과 조회 시간이 <b>반대 방향으로 움직이는 것</b>이 이 상황의 표식입니다. 자주 읽는 마트는 표로 굳히고, 큰 표는 증분으로 쌓습니다. 얇은 스테이징을 뷰로 두는 것은 그대로 두어도 괜찮습니다 — 문제는 겹의 수가 아니라 <b>끝단까지 뷰인 것</b>입니다.",
},
{
  t: "log", k: "누가 운영 표를 덮었다", cat: "logs", d: 3, track: "dbt",
  file: "dbt run log",
  q: "낮에 운영 표가 절반으로 줄었습니다. 그렇게 만든 한 줄을 고르세요.",
  items: [
    { txt: "14:00:00 WARN  warehouse: role analyst has write access to the analytics schema", bad: false },
    { txt: "14:12:00 INFO  dbt invoked by user jin from a laptop, command: run --select fct_orders", bad: false },
    { txt: "14:12:01 INFO  connection profile default target=prod schema=analytics", bad: true },
    { txt: "14:12:02 INFO  compiling fct_orders from branch feature/new-filter", bad: false },
    { txt: "14:14:40 INFO  OK created table analytics.fct_orders, 2,041,220 rows", bad: false },
    { txt: "14:15:00 WARN  bi: order dashboard row count dropped from 4.1M to 2.0M", bad: false },
    { txt: "14:20:00 ERROR ops: finance report for today is missing half of the orders", bad: false },
  ],
  ex: "잘못한 사람이 있는 것이 아니라 <b>잘못할 수 있게 되어 있던 것</b>이 문제입니다. 노트북에서 돌린 실행의 기본 대상이 운영이었고, 작업 중인 브랜치의 필터가 절반을 걸러 냈으며, 그 결과가 그대로 운영 표를 갈아 치웠습니다. 각 줄은 전부 정상 동작이고 오류도 없습니다. 막는 방법은 사람의 주의가 아니라 구조입니다: 기본 대상을 개발 스키마로 두고, 운영 대상은 <b>CI 에서만</b> 쓸 수 있는 자격으로 분리하며, 개인 계정에는 운영 스키마 쓰기 권한을 주지 않습니다.",
},
{
  t: "log", k: "이력이 남지 않았다", cat: "logs", d: 4, track: "dbt",
  file: "dbt snapshot log",
  q: "변경 이력을 쌓는 스냅샷에 새 기록이 안 생깁니다. 원인이 되는 한 줄을 고르세요.",
  items: [
    { txt: "03:00:00 WARN  dbt: snapshot target schema differs from the model target schema", bad: false },
    { txt: "03:00:20 INFO  snapshot customers strategy=timestamp updated_at=updated_at", bad: false },
    { txt: "03:00:21 INFO  source customers: 41,200 rows, 8,140 changed since yesterday", bad: false },
    { txt: "03:00:40 INFO  snapshot customers: 0 rows inserted, 0 rows updated", bad: false },
    { txt: "03:00:40 INFO  upstream loader copies updated_at from the source as-is", bad: true },
    { txt: "03:00:41 WARN  dbt: Done. PASS=1 WARN=0 ERROR=0, snapshot table unchanged for 12 days", bad: false },
    { txt: "10:00:00 ERROR analytics: customer tier history has no rows after 2026-08-27", bad: false },
  ],
  ex: "시각을 기준으로 삼는 전략은 <b>그 열이 실제로 바뀐다</b>는 전제 위에 있습니다. 상류 적재가 원천의 값을 그대로 복사해 오면 내용이 달라져도 그 시각은 옛날 그대로이므로, 스냅샷은 '바뀐 것이 없다' 고 판단합니다. 8,140행이 바뀌었는데 0행이 들어간 것이 그 어긋남을 그대로 보여 줍니다. 고치는 길은 둘입니다: 적재 쪽이 실제 갱신 시각을 남기게 하거나, 지켜볼 열을 지정해 <b>값을 견주는 전략</b>으로 바꾸는 것입니다. 뒤쪽은 느리지만 시각을 믿을 수 없을 때 확실합니다.",
},

/* ══════════════ dl ══════════════ */
{
  t: "log", k: "손실이 갑자기 NaN 이 된다", cat: "logs", d: 3, track: "dl",
  file: "train.log",
  q: "학습 도중 손실이 NaN 으로 바뀌고 회복되지 않습니다. 그 직전의 원인 줄을 고르세요.",
  items: [
    { txt: "01:00:00 WARN  train: dataloader worker 3 restarted after a timeout", bad: false },
    { txt: "01:20:10 INFO  epoch 4 step 1200 loss 2.14 lr 0.001 grad_norm 3.2", bad: false },
    { txt: "01:20:41 INFO  epoch 4 step 1400 loss 2.09 lr 0.001 grad_norm 812.5", bad: true },
    { txt: "01:20:52 INFO  epoch 4 step 1450 loss 41.20 lr 0.001 grad_norm 1.2e+06", bad: false },
    { txt: "01:21:00 INFO  epoch 4 step 1500 loss nan lr 0.001 grad_norm nan", bad: false },
    { txt: "01:21:30 WARN  train: 12 of 41 parameters contain nan after the update", bad: false },
    { txt: "01:40:00 INFO  train: loss remains nan for 2000 steps, accuracy 0.0", bad: false },
  ],
  ex: "NaN 은 결과이지 원인이 아닙니다. 거슬러 올라가면 기울기의 크기가 3.2에서 812로 <b>250배</b> 뛴 자리가 있고, 그 뒤로 백만 단위까지 커졌다가 표현할 수 없는 값이 됐습니다. 한 번 NaN 이 되면 곱셈으로 모든 가중치에 번지므로 회복되지 않습니다 — 그래서 손실만 보고 있으면 이미 늦습니다. <b>기울기 크기를 함께 기록</b>하면 이 지점을 미리 봅니다. 처방은 기울기 잘라내기, 학습률 낮추기, 그리고 데이터에 이상한 값이 섞였는지 확인하는 것입니다. 한 배치의 극단값 하나가 이런 폭주의 방아쇠가 되는 일이 흔합니다.",
},
{
  t: "log", k: "검증에서만 메모리가 터진다", cat: "logs", d: 3, track: "dl",
  file: "train.log",
  q: "학습은 되는데 검증을 돌릴 때만 메모리가 부족합니다. 이유가 되는 한 줄을 고르세요.",
  items: [
    { txt: "02:00:00 WARN  train: mixed precision requested but the device does not support it", bad: false },
    { txt: "02:10:00 INFO  epoch 1 training finished, peak memory 6.2 GB of 16 GB", bad: false },
    { txt: "02:10:01 INFO  entering validation loop, batch_size 128, grad mode still enabled", bad: true },
    { txt: "02:10:14 INFO  validation step 40, memory 11.8 GB and rising", bad: false },
    { txt: "02:10:31 ERROR CUDA out of memory: tried to allocate 512 MiB, 15.4 GB already allocated", bad: false },
    { txt: "02:10:31 ERROR train: run aborted at epoch 1, no checkpoint saved", bad: false },
    { txt: "02:11:00 INFO  ops: the same script finished fine when validation was skipped", bad: false },
  ],
  ex: "학습보다 검증이 메모리를 더 먹는 것은 <b>거꾸로</b>입니다. 검증은 갱신을 하지 않으니 원래 훨씬 가벼워야 합니다. 원인은 기울기 계산이 켜진 채로 돌고 있는 것입니다 — 그러면 모든 중간 결과가 되돌아가기를 위해 남아 있으므로, 배치마다 메모리가 쌓여 결국 넘칩니다. 메모리가 <b>점점 오른다</b>는 것이 그 표식입니다. 평가 구간은 기울기를 끄고 돌려야 하고, 함께 평가 모드로 바꿔야 정규화와 드롭아웃도 제대로 동작합니다. 체크포인트를 아직 저장하지 않은 것도 함께 고칠 일입니다 — 한 시간의 학습이 통째로 사라졌습니다.",
},
{
  t: "log", k: "가속기가 놀고 있다", cat: "logs", d: 3, track: "dl",
  file: "train.log · nvidia-smi",
  q: "학습이 예상보다 열 배 느린데 가속기 사용률은 낮습니다. 병목을 알려 주는 한 줄을 고르세요.",
  items: [
    { txt: "04:00:00 WARN  train: checkpoint directory has less than 10 GB free", bad: false },
    { txt: "04:05:00 INFO  step 100 time 1.82s (compute 0.11s, data wait 1.70s)", bad: false },
    { txt: "04:05:01 INFO  smi: utilization 6 percent, memory 4.1 GB of 40 GB", bad: false },
    { txt: "04:05:02 INFO  DataLoader num_workers=0, transforms decode jpeg on the fly", bad: true },
    { txt: "04:05:30 INFO  cpu: 1 core at 100 percent, 31 cores idle", bad: false },
    { txt: "04:20:00 WARN  train: estimated time to finish 41 hours (budget 4 hours)", bad: false },
    { txt: "04:20:01 INFO  ops: the same model trains in 3 hours on an identical machine", bad: false },
  ],
  ex: "가속기가 6퍼센트만 일하고 코어 하나만 100퍼센트라면 병목은 <b>계산이 아니라 준비</b>입니다. 데이터를 읽어 오는 일꾼이 0이면 그 일을 학습 과정이 직접 하므로, 한 배치를 준비하는 동안 가속기는 그냥 기다립니다. 단계 시간의 내역이 그것을 그대로 보여 줍니다 — 1.82초 중 1.70초가 기다림입니다. 처방은 일꾼 수를 코어에 맞춰 늘리고, 무거운 디코딩을 미리 해 두거나 가벼운 형식으로 바꾸고, 다음 배치를 미리 준비하게 하는 것입니다. <b>계산 시간과 대기 시간을 따로 기록</b>하는 습관이 이런 것을 한눈에 보여 줍니다.",
},
{
  t: "log", k: "평가 점수만 이상하다", cat: "logs", d: 4, track: "dl",
  file: "train.log",
  q: "학습 정확도는 높은데 평가만 무작위 수준입니다. 원인이 되는 한 줄을 고르세요.",
  items: [
    { txt: "06:00:00 WARN  train: label file was regenerated 2 days ago", bad: false },
    { txt: "06:30:00 INFO  epoch 20 train accuracy 0.972 loss 0.081", bad: false },
    { txt: "06:30:05 INFO  evaluate() called, module stays in training mode", bad: true },
    { txt: "06:30:40 INFO  batchnorm running stats updated during evaluation, 41 layers", bad: false },
    { txt: "06:30:41 INFO  eval accuracy 0.104 over 10 classes", bad: false },
    { txt: "06:30:42 WARN  train: eval accuracy is close to random for a 10-class task", bad: false },
    { txt: "06:31:00 INFO  ops: eval accuracy on the same data was 0.951 in last week's run", bad: false },
  ],
  ex: "평가 점수가 <b>무작위와 같은 수준</b>이면 모델이 못 배운 것이 아니라 평가 자체가 망가진 것을 먼저 의심합니다. 모드를 바꾸지 않으면 정규화 층이 배치별 통계를 쓰고 누적 통계까지 갱신하며, 드롭아웃도 계속 켜져 있습니다. 그래서 배치 구성에 따라 답이 흔들리고, 더 나쁘게는 <b>평가가 모델을 오염시킵니다</b> — 누적 통계가 평가 데이터로 덮이기 때문입니다. 지난주에 같은 데이터로 0.951 이었다는 것이 모델 자체는 멀쩡하다는 증거입니다. 평가 구간에서 모드를 바꾸고 기울기를 끄면 됩니다.",
},
{
  t: "log", k: "이어서 학습했더니 나빠졌다", cat: "logs", d: 4, track: "dl",
  file: "train.log",
  q: "체크포인트에서 이어 학습했더니 손실이 크게 뛰었습니다. 원인이 되는 한 줄을 고르세요.",
  items: [
    { txt: "08:00:00 WARN  train: torch version differs from the one that wrote the checkpoint", bad: false },
    { txt: "08:00:10 INFO  loaded model weights from ckpt_epoch30.pt", bad: false },
    { txt: "08:00:10 INFO  epoch 30 recorded loss was 0.212", bad: false },
    { txt: "08:00:11 INFO  optimizer created fresh, momentum buffers zeroed, lr reset to 0.1", bad: true },
    { txt: "08:00:12 INFO  scheduler restarted from step 0, warmup for 500 steps", bad: false },
    { txt: "08:02:00 WARN  train: epoch 31 loss 1.87, higher than epoch 30", bad: false },
    { txt: "08:40:00 INFO  train: loss back to 0.24 after 8 epochs of re-warming", bad: false },
  ],
  ex: "가중치는 잘 복원됐습니다. 되살리지 못한 것은 <b>최적화기의 상태</b>입니다. 모멘텀이나 적응형 방법의 누적 값은 지금까지의 학습 경로를 담고 있어서, 그것 없이 큰 학습률로 다시 시작하면 잘 자리 잡은 가중치를 흔들어 놓습니다. 손실이 뛰었다가 여덟 에폭 만에 겨우 제자리로 돌아온 것이 그 대가입니다. 체크포인트에는 가중치와 함께 <b>최적화기 상태·스케줄러 상태·에폭 번호</b>를 담아야 하고, 그래야 이어서 하는 학습이 처음부터 하는 것과 이어집니다. 판이 다르다는 경고는 확인할 값어치가 있지만 이 증상의 원인은 아닙니다.",
},
{
  t: "log", k: "장비를 늘렸는데 안 빨라진다", cat: "logs", d: 3, track: "dl",
  file: "train.log · nvidia-smi",
  q: "가속기를 네 장으로 늘렸는데 속도가 그대로입니다. 이유를 알려 주는 한 줄을 고르세요.",
  items: [
    { txt: "09:00:00 WARN  train: NCCL debug logging is enabled, this adds overhead", bad: false },
    { txt: "09:05:00 INFO  visible devices 4, model placed on cuda:0", bad: false },
    { txt: "09:05:01 INFO  smi: gpu0 utilization 94 percent, gpu1-3 utilization 0 percent", bad: false },
    { txt: "09:05:10 INFO  batch_size 64 unchanged from the single device run", bad: false },
    { txt: "09:05:10 INFO  no distributed backend, no data parallel wrapper", bad: true },
    { txt: "09:30:00 WARN  train: throughput 412 samples/s (single device run 408 samples/s)", bad: false },
    { txt: "09:30:01 INFO  finance: instance cost is now 4x the previous run", bad: false },
  ],
  ex: "장비를 붙였다고 저절로 나뉘어 도는 것이 아닙니다. 분산 방식을 켜지 않으면 모델은 <b>한 장에만</b> 올라가고 나머지는 켜진 채로 놀면서 요금만 냅니다. 사용률이 94와 0으로 갈린 것이 그 그림입니다. 처리량이 거의 그대로인데 비용만 네 배가 된 것도 같은 이야기입니다. 고칠 때는 두 가지를 함께 봅니다: 분산 방식을 켜는 것, 그리고 <b>전체 배치가 네 배가 되었으니</b> 학습률과 예열을 그에 맞게 조정하는 것입니다. 앞의 것만 하면 빨라지지만 잘 안 배우게 됩니다.",
},
{
  t: "log", k: "저장한 모델이 다른 답을 낸다", cat: "logs", d: 4, track: "dl",
  file: "train.log · serve.log",
  q: "같은 이미지에 학습 때와 서비스 때의 답이 다릅니다. 어긋난 자리를 고르세요.",
  items: [
    { txt: "10:00:00 WARN  serve: model file was copied without its config.json", bad: false },
    { txt: "10:05:00 INFO  train: eval accuracy 0.951 on the held-out set", bad: false },
    { txt: "10:10:00 INFO  serve: preprocessing resize 224 center-crop, normalize with imagenet stats", bad: false },
    { txt: "10:10:01 INFO  train: resize 256, crop 224, normalize with dataset stats", bad: true },
    { txt: "10:10:02 INFO  serve: inference on sample 41 -> class 3 (train pipeline gave class 7)", bad: false },
    { txt: "10:20:00 WARN  serve: production accuracy measured at 0.612 on the same held-out set", bad: false },
    { txt: "10:20:01 INFO  ops: model weights checksum matches the trained artifact exactly", bad: false },
  ],
  ex: "가중치는 <b>글자 하나까지 같습니다</b> — 확인값이 일치합니다. 달라진 것은 모델에 들어가기 전의 처리입니다. 크기를 줄이는 방식도 다르고 정규화에 쓰는 평균과 표준편차도 다르니, 같은 이미지가 <b>서로 다른 숫자 배열</b>이 되어 들어갑니다. 모델은 학습 때 본 분포에서만 잘 맞으므로 정확도가 0.95에서 0.61로 떨어집니다. 이런 어긋남을 막는 방법은 전처리를 모델과 <b>함께 묶어 저장</b>하고, 두 쪽이 같은 코드를 부르게 하는 것입니다. 그리고 배포 전에 같은 표본으로 양쪽 결과를 견주는 검사를 한 번 돌립니다.",
},
{
  t: "log", k: "잘 배우다가 갑자기 무너진다", cat: "logs", d: 4, track: "dl",
  file: "train.log",
  q: "20에폭까지 잘 배우다 검증 점수만 계속 나빠집니다. 그 전환점을 알려 주는 한 줄을 고르세요.",
  items: [
    { txt: "11:00:00 WARN  train: dataset shuffle buffer is smaller than one epoch", bad: false },
    { txt: "11:30:00 INFO  epoch 18 train loss 0.31 val loss 0.34 val acc 0.902", bad: false },
    { txt: "11:40:00 INFO  epoch 20 train loss 0.19 val loss 0.33 val acc 0.905", bad: false },
    { txt: "11:50:00 INFO  epoch 22 train loss 0.08 val loss 0.41 val acc 0.881", bad: true },
    { txt: "12:10:00 INFO  epoch 26 train loss 0.02 val loss 0.62 val acc 0.844", bad: false },
    { txt: "12:40:00 WARN  train: best checkpoint is from epoch 20, current epoch 32", bad: false },
    { txt: "12:40:01 INFO  train: training continues, stop condition is a fixed epoch count", bad: false },
  ],
  ex: "두 곡선이 <b>갈라지기 시작한 자리</b>가 전환점입니다. 그 전까지는 학습 손실과 검증 손실이 함께 내려가지만, 22에폭부터 학습만 계속 내려가고 검증은 올라갑니다 — 데이터를 외우기 시작한 것입니다. 정확도가 떨어지는 것보다 <b>손실이 먼저</b> 올라간다는 점도 기억할 만합니다. 손실이 확신의 정도까지 보기 때문입니다. 처방은 그 지점에서 멈추는 것(조기 종료)이고, 규제·증강·모델 크기 줄이기로 갈라지는 시점을 늦출 수도 있습니다. 정해진 에폭 수까지 도는 규칙이라 열 에폭을 헛돌고 있는 것도 함께 고칠 일입니다.",
},

/* ══════════════ mobile ══════════════ */
{
  t: "log", k: "화면이 5초 멈추고 죽는다", cat: "logs", d: 3, track: "mobile",
  file: "logcat",
  q: "앱이 잠깐 멈췄다가 응답 없음으로 종료됩니다. 원인이 되는 한 줄을 고르세요.",
  items: [
    { txt: "20:00:00 WARN  Choreographer: skipped 32 frames, the app may be doing too much work", bad: false },
    { txt: "20:14:01 INFO  ActivityManager: displayed com.shop/.FeedActivity in 412ms", bad: false },
    { txt: "20:14:30 INFO  FeedActivity: onCreate reading settings.json on the main thread", bad: false },
    { txt: "20:14:30 INFO  StrictMode: DiskRead and Network violation on the main thread", bad: true },
    { txt: "20:14:35 ERROR ActivityManager: ANR in com.shop, reason: Input dispatching timed out", bad: false },
    { txt: "20:14:35 ERROR ActivityManager: main thread blocked at okhttp3.RealCall.execute", bad: false },
    { txt: "20:14:40 INFO  ActivityManager: process com.shop killed, exit reason ANR", bad: false },
  ],
  ex: "응답 없음은 <b>화면을 그리는 스레드가 막혔다</b>는 뜻이고, 시스템은 그것을 몇 초만 참습니다. 검사 도구가 이미 그 자리를 정확히 짚어 주었습니다 — 그 스레드에서 디스크를 읽고 네트워크를 부르고 있습니다. 응답 없음과 막힌 호출 이름은 결과일 뿐이라, 어디서 멈췄는지는 알려 주지만 <b>왜 거기서 부르면 안 되는지</b>는 말해 주지 않습니다. 앞의 프레임 건너뜀 경고는 다른 화면의 일로 흔히 나오는 잡음입니다. 처방은 기다리는 일을 전부 다른 스레드로 보내고, 그동안 화면에는 자리 표시를 그리는 것입니다.",
},
{
  t: "log", k: "목록을 내리면 앱이 죽는다", cat: "logs", d: 3, track: "mobile",
  file: "logcat",
  q: "목록을 빠르게 내리다 보면 메모리 부족으로 죽습니다. 원인이 되는 한 줄을 고르세요.",
  items: [
    { txt: "21:00:00 WARN  Glide: image request cancelled because the view was recycled", bad: false },
    { txt: "21:10:00 INFO  FeedAdapter: decoding 4032x3024 jpeg without inSampleSize", bad: true },
    { txt: "21:10:04 INFO  art: heap 128 MB of 192 MB after 40 items", bad: false },
    { txt: "21:10:09 INFO  art: GC ran 18 times in 5 seconds, 340ms total pause", bad: false },
    { txt: "21:10:12 ERROR art: java.lang.OutOfMemoryError: Failed to allocate 48 MB allocation", bad: false },
    { txt: "21:10:12 ERROR AndroidRuntime: FATAL EXCEPTION in main, process com.shop", bad: false },
    { txt: "21:10:20 INFO  ops: the same list is fine on a device with a 512 MB heap limit", bad: false },
  ],
  ex: "사진 한 장이 4032×3024 이므로 화면에 그릴 형태로 펼치면 <b>약 48MB</b> 를 씁니다. 목록을 내리면 그런 것이 계속 만들어져 몇십 장 만에 앱에 허용된 메모리를 넘습니다. 화면에서 실제로 차지하는 크기는 손톱만 한데 원본 크기 그대로 읽은 것이 원인입니다. 표본 비율을 주어 <b>필요한 크기로 줄여 읽으면</b> 메모리 사용량이 수십 분의 일이 됩니다. 앞의 요청 취소 경고는 목록이 자리를 재사용할 때 늘 나오는 정상 동작입니다. 힙 한도가 큰 기기에서 안 죽는 것은 문제가 사라진 것이 아니라 늦게 오는 것뿐입니다.",
},
{
  t: "log", k: "특정 기기에서만 죽는다", cat: "logs", d: 3, track: "mobile",
  file: "crash report",
  q: "일부 기기에서만 실행 직후 죽습니다. 원인이 되는 한 줄을 고르세요.",
  items: [
    { txt: "07:00:00 WARN  build: minSdk 24, 3 libraries declare minSdk 21", bad: false },
    { txt: "07:20:01 INFO  crash: affected devices all report Android 13 or higher", bad: false },
    { txt: "07:20:02 INFO  manifest: no android:exported attribute on MainActivity receiver", bad: false },
    { txt: "07:20:03 INFO  app: registerReceiver called without RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED", bad: true },
    { txt: "07:20:04 ERROR AndroidRuntime: SecurityException: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED required", bad: false },
    { txt: "07:20:04 ERROR AndroidRuntime: at com.shop.MainActivity.onCreate(MainActivity.kt:41)", bad: false },
    { txt: "07:30:00 INFO  ops: crash-free rate 61 percent, unaffected devices are all Android 12 or lower", bad: false },
  ],
  ex: "'일부 기기에서만' 이라는 말의 정체가 <b>운영체제 판</b>인 경우가 많습니다. 새 판이 안전을 위해 요구 사항을 더하면, 그 요구를 채우지 않은 호출이 옛 판에서는 그냥 지나가고 새 판에서는 예외가 됩니다. 그래서 개발자의 기기에서는 멀쩡한데 사용자 절반이 못 씁니다. 판별 방법은 간단합니다 — 사고 보고를 <b>판 별로 나눠</b> 보면 경계가 또렷하게 드러납니다. 처방은 그 요구 사항을 명시하는 것이고, 이런 것을 미리 잡으려면 대상 판을 올릴 때 변경 사항 목록을 훑고 새 판 기기에서 한 번 돌려 봐야 합니다.",
},
{
  t: "log", k: "릴리스 빌드에서만 죽는다", cat: "logs", d: 4, track: "mobile",
  file: "crash report",
  q: "개발 빌드는 멀쩡한데 배포판만 죽습니다. 원인이 되는 한 줄을 고르세요.",
  items: [
    { txt: "16:00:00 WARN  build: 2 dependencies have no reproducible build metadata", bad: false },
    { txt: "16:10:00 INFO  build: minifyEnabled true, shrinkResources true, no keep rule for model classes", bad: true },
    { txt: "16:10:01 INFO  build: obfuscation renamed 4,120 classes and 18,900 methods", bad: false },
    { txt: "16:12:00 INFO  app: parsing /orders response with reflection based json mapper", bad: false },
    { txt: "16:12:01 ERROR AndroidRuntime: MissingFieldException: no field 'orderId' in class a.b.c", bad: false },
    { txt: "16:12:01 ERROR AndroidRuntime: at com.shop.net.Api.parse(SourceFile)", bad: false },
    { txt: "16:20:00 INFO  ops: the debug build with the same code parses the response correctly", bad: false },
  ],
  ex: "배포판에서만 나는 사고는 대개 <b>배포판에서만 하는 일</b> 때문입니다. 여기서는 이름 줄이기가 그것입니다. 필드 이름을 보고 값을 맞추는 방식으로 응답을 읽는데, 그 이름이 <code>a.b.c</code> 같은 것으로 바뀌었으니 맞출 것이 없습니다. 개발 빌드는 이 과정을 거치지 않아 멀쩡합니다. 예외 메시지에 남은 짧은 이름이 그 자체로 단서입니다. 처방은 이름을 지켜야 하는 클래스에 규칙을 걸어 두는 것이고, 더 나은 방법은 이름에 기대지 않는 방식으로 바꾸는 것입니다. 그리고 이런 것을 미리 잡으려면 <b>배포판으로도 시험</b>을 돌려야 합니다.",
},
{
  t: "log", k: "밤새 배터리가 닳는다", cat: "logs", d: 3, track: "mobile",
  file: "battery historian",
  q: "앱을 안 쓰는 밤에도 배터리가 30퍼센트 줄어듭니다. 원인이 되는 한 줄을 고르세요.",
  items: [
    { txt: "00:00:00 WARN  app: analytics queue has 412 pending events", bad: false },
    { txt: "00:30:00 INFO  MapScreen: onStop called, activity moved to background", bad: false },
    { txt: "00:30:01 INFO  LocationManager: requestLocationUpdates still active, 1s, high accuracy", bad: true },
    { txt: "00:30:02 INFO  PowerManager: partial wakelock 'loc' held by com.shop", bad: false },
    { txt: "05:00:00 INFO  historian: com.shop kept the cpu awake for 5h 12m overnight", bad: false },
    { txt: "05:00:01 WARN  historian: gps sensor active 5h 30m, com.shop responsible for 98 percent", bad: false },
    { txt: "05:00:02 INFO  historian: battery drop 30 percent, screen off the entire period", bad: false },
  ],
  ex: "화면이 꺼져 있었는데 위치 갱신이 <b>1초 간격 고정밀도로</b> 계속 돌았습니다. 위성 수신과 그것을 붙잡아 두는 잠금이 합쳐지면 배터리는 이렇게 사라집니다. 화면이 뒤로 갔다는 기록이 바로 앞에 있는데도 갱신이 살아 있다는 것이 어긋남의 표식입니다. 사고의 뿌리는 <b>등록만 하고 해제하지 않은 것</b>이고, 화면 코드에서 가장 흔한 실수입니다. 처방은 화면이 보이지 않게 될 때 해제하는 것, 필요한 정확도만 요청하는 것, 그리고 계속 알아야 하는 일이라면 화면에 매달지 말고 시스템이 관리하는 백그라운드 방식으로 옮기는 것입니다.",
},
{
  t: "log", k: "돌아오면 처음부터다", cat: "logs", d: 3, track: "mobile",
  file: "logcat",
  q: "다른 앱을 잠깐 쓰고 돌아오면 입력하던 내용이 사라집니다. 원인이 되는 한 줄을 고르세요.",
  items: [
    { txt: "12:00:00 WARN  app: leak canary detected a retained fragment, 1 instance", bad: false },
    { txt: "12:10:00 INFO  WriteActivity: user typed 412 characters into the draft field", bad: false },
    { txt: "12:11:00 INFO  ActivityManager: com.shop moved to background, user opened the camera", bad: false },
    { txt: "12:14:00 INFO  ActivityManager: killed com.shop to reclaim 180 MB for the foreground app", bad: false },
    { txt: "12:15:00 INFO  WriteActivity: onCreate with savedInstanceState = null, no draft restored", bad: true },
    { txt: "12:15:01 WARN  app: draft field rendered empty, 412 characters lost", bad: false },
    { txt: "12:15:10 INFO  ops: reproduced by enabling 'do not keep activities' in developer options", bad: false },
  ],
  ex: "시스템이 뒤에 있는 앱을 정리하는 것은 <b>정상 동작</b>입니다 — 앞에 있는 앱에 메모리가 필요하면 언제든 그렇게 합니다. 돌아왔을 때 앱은 처음부터 다시 만들어지고, 저장해 둔 상태가 없으니 비어 있습니다. 개발자 설정으로 이 상황을 <b>언제든 재현할 수 있다</b>는 점이 그것을 확인해 줍니다. 처방은 화면이 사라지기 전에 상태를 저장하고 다시 만들어질 때 복원하는 것이고, 사용자가 쓰던 글처럼 잃으면 안 되는 것은 메모리가 아니라 <b>저장소에 임시로 남겨</b> 두어야 합니다. 앞의 누수 경고는 다른 문제라 따로 볼 일입니다.",
},
{
  t: "log", k: "화면 전환에서 새는 메모리", cat: "logs", d: 4, track: "mobile",
  file: "logcat · heap dump",
  q: "화면을 오갈수록 메모리가 계속 늘어납니다. 붙들고 있는 자리를 고르세요.",
  items: [
    { txt: "14:00:00 WARN  app: strict mode detected an unclosed cursor in ReportDao", bad: false },
    { txt: "14:10:00 INFO  DetailActivity: created, instance count 1", bad: false },
    { txt: "14:20:00 INFO  DetailActivity: created, instance count 12 after 12 rotations", bad: false },
    { txt: "14:20:01 INFO  AnalyticsTracker is a singleton, listeners list has 12 entries", bad: false },
    { txt: "14:20:02 INFO  heap: 12 DetailActivity instances held by AnalyticsTracker", bad: true },
    { txt: "14:20:03 WARN  art: heap 148 MB of 192 MB, GC unable to reclaim", bad: false },
    { txt: "14:30:00 ERROR art: OutOfMemoryError while inflating the detail layout", bad: false },
  ],
  ex: "회수되지 못하는 이유는 <b>누군가 아직 가리키고 있기</b> 때문입니다. 힙을 찍어 보면 그 사슬이 그대로 나옵니다 — 앱이 사는 동안 계속 존재하는 단일 객체의 목록에 화면들이 하나씩 쌓여 있습니다. 회전할 때마다 새 화면이 등록되는데 옛 화면은 빠지지 않으니, 12번 돌리면 12개가 남고 각각이 그린 화면 전체를 함께 붙듭니다. 처방은 등록한 자리마다 <b>짝이 되는 해제</b>를 두는 것입니다. 앞의 커서 경고도 진짜 문제이지만 여기서 메모리를 먹는 크기와는 급이 다릅니다.",
},
{
  t: "log", k: "오프라인에서 요청이 쌓인다", cat: "logs", d: 3, track: "mobile",
  file: "logcat",
  q: "지하철에서 앱을 켜 두면 데이터와 배터리가 빠르게 줄어듭니다. 원인이 되는 한 줄을 고르세요.",
  items: [
    { txt: "17:00:00 WARN  app: certificate pinning validation added 40ms to each request", bad: false },
    { txt: "17:30:00 INFO  ConnectivityManager: network capabilities lost, no internet", bad: false },
    { txt: "17:30:01 INFO  SyncWorker: retry policy fixed 1s, max attempts unlimited, no connectivity check", bad: true },
    { txt: "17:30:02 INFO  SyncWorker: attempt 1 failed UnknownHostException", bad: false },
    { txt: "17:35:00 INFO  SyncWorker: attempt 300 failed UnknownHostException", bad: false },
    { txt: "17:35:01 WARN  PowerManager: com.shop kept the radio awake for 5 minutes straight", bad: false },
    { txt: "17:50:00 INFO  historian: 4,100 failed requests, 12 percent battery in 20 minutes", bad: false },
  ],
  ex: "연결이 없다는 것을 시스템이 이미 알려 주었는데도 <b>1초마다 무한히</b> 다시 시도합니다. 실패한 요청도 무선 장치를 깨우므로, 아무것도 못 보내면서 배터리만 씁니다. 스무 분에 4,100번이라는 숫자가 그 낭비를 그대로 보여 줍니다. 재시도에는 두 가지가 반드시 붙어야 합니다 — 간격을 점점 늘리는 것과 기기마다 조금씩 흩뜨리는 것입니다. 여기서는 그보다 앞선 처방이 있습니다: <b>연결이 없으면 시도하지 않고</b>, 돌아왔을 때 시스템이 깨워 주는 방식으로 맡기는 것입니다. 그러면 지하철 구간 내내 아무 일도 하지 않습니다.",
},

];
