/* ML 평가 1차 — 실습이 하나도 없던 8개 유닛.

   일부러 순수 파이썬으로 짰다. 지표는 직접 손으로 세어 봐야 뜻이 남는다.
   sklearn 을 부르면 "함수 이름 외우기" 가 되고, 왜 그 지표를 쓰는지는
   끝내 모른 채 지나간다. 꾸러미를 안 받으니 채점도 빠르다. */
module.exports = [
/* ── 대표 알고리즘 ───────────────────────────────────────── */
{
  unit: "대표 알고리즘",
  lesson: "직접 짜 보기 — 알고리즘의 속을 열어 본다",
  th: {
    sum: "대표 알고리즘들은 **'가까운 것끼리 묶는다'** 는 한 가지 생각을 저마다 다르게 푼 것이다.",
    body: [
      { h: "k-NN 은 외우고 나중에 찾는다", t: "학습이랄 게 없다. 데이터를 그대로 들고 있다가, 새 점이 오면 가장 가까운 k개를 찾아 다수결한다. 학습은 빠르지만 예측할 때마다 전부 뒤져야 해서 느리다 — 데이터가 커지면 이게 발목을 잡는다." },
      { h: "결정 트리는 질문을 이어 붙인다", t: "'이 값이 3보다 큰가' 같은 질문으로 데이터를 계속 반으로 가른다. 어떤 질문이 가장 잘 가르는지는 불순도(지니·엔트로피)가 얼마나 줄어드는지로 고른다. 사람이 읽을 수 있다는 게 큰 장점이다." },
      { h: "선형 모델은 직선을 하나 긋는다", t: "각 특성에 가중치를 곱해 더한다. 단순하지만 계수를 보면 '어느 특성이 얼마나 밀었는지' 가 바로 보인다. 설명이 필요한 자리에서 여전히 1순위다." },
      { h: "어떤 것이 최고인지는 정해져 있지 않다", t: "데이터의 모양에 따라 이기는 알고리즘이 다르다. 그래서 먼저 단순한 것으로 기준선을 만들고, 복잡한 것이 그것을 실제로 이기는지 확인한다." },
    ],
    code: { c: "# k-NN 한 점 예측\nd = [(dist(p, x), y) for x, y in train]\nd.sort()\n이웃 = d[:k]\n예측 = 다수결([y for _, y in 이웃])\n\n# 지니 불순도\n1 - sum(p*p for p in 비율들)", cap: "가까운 것끼리 묶는 여러 방법" },
    key: ["k-NN 은 예측할 때 일한다", "트리는 불순도가 줄어드는 질문을 고른다", "먼저 단순한 기준선부터"],
  },
  q: [
    {
      k: "knn · 가까운 것들의 다수결",
      qq: "1차원 학습 데이터 <code>[(값, 라벨)]</code> 에서 <code>x</code> 와 가장 가까운 <b>k개</b>의 다수결 라벨을 돌려주세요. 동점이면 <b>작은 라벨</b>입니다.",
      src: "def knn(train, x, k):\n    near = sorted(train, key=lambda t: abs(t[0] - x))[:k]\n    return near[0][1]\n",
      sol: "def knn(train, x, k):\n    near = sorted(train, key=lambda t: abs(t[0] - x))[:k]\n    cnt = {}\n    for _, y in near:\n        cnt[y] = cnt.get(y, 0) + 1\n    best = max(cnt.values())\n    return min(y for y, c in cnt.items() if c == best)\n",
      tests: [["knn([(0, 1), (0.1, 0), (0.2, 0)], 0.0, 3)", "0"], ["knn([(0, 0), (1, 1), (2, 1)], 1.4, 3)", "1"], ["knn([(5, 7)], 0, 1)", "7"]],
      edge: [["knn([(0, 1), (1, 0)], 0.5, 2)", "0"], ["knn([(0, 0), (1, 1), (2, 1)], 1.9, 1)", "1"]],
      ex: "가장 가까운 하나만 보면 그건 1-NN 입니다 — k를 준 의미가 없어요. 이웃 k개를 모두 세어 다수결해야 잡음 하나에 흔들리지 않습니다. 동점 규칙까지 정해 둬야 결과가 매번 같습니다.",
    },
    {
      k: "gini · 얼마나 섞여 있나",
      qq: "라벨 목록의 <b>지니 불순도</b> <code>1 - Σp²</code> 를 돌려주세요.",
      src: "def gini(ys):\n    if not ys:\n        return 0.0\n    n = len(ys)\n    return 1.0 - sum((ys.count(y) / n) for y in set(ys))\n",
      sol: "def gini(ys):\n    if not ys:\n        return 0.0\n    n = len(ys)\n    return 1.0 - sum((ys.count(y) / n) ** 2 for y in set(ys))\n",
      tests: [["gini([0, 0, 0])", "0.0"], ["gini([0, 1])", "0.5"], ["round(gini([0, 0, 1, 1, 1]), 4)", "0.48"]],
      edge: [["gini([])", "0.0"], ["gini([1, 1, 2, 2, 3, 3])", "1 - 3 * (1/3) ** 2"]],
      ex: "제곱을 빠뜨리면 비율의 합이 항상 1이라 결과가 언제나 0 이 됩니다 — 순수하든 뒤죽박죽이든 똑같이 0 이니 어떤 질문도 고를 수 없어요. 제곱이 '한 쪽으로 몰릴수록 크게' 만드는 장치입니다.",
    },
    {
      k: "best_split · 가장 잘 가르는 질문",
      qq: "값 기준점 후보들 중 <b>가중 지니가 가장 작은</b> 기준점을 돌려주세요. <code>x &lt; t</code> 면 왼쪽입니다. 동점이면 작은 기준점입니다.",
      src: "def best_split(data, cands):\n    def g(ys):\n        if not ys:\n            return 0.0\n        n = len(ys)\n        return 1.0 - sum((ys.count(y) / n) ** 2 for y in set(ys))\n    best, bt = None, None\n    for t in cands:\n        L = [y for x, y in data if x < t]\n        R = [y for x, y in data if x >= t]\n        s = g(L) + g(R)\n        if best is None or s < best:\n            best, bt = s, t\n    return bt\n",
      sol: "def best_split(data, cands):\n    def g(ys):\n        if not ys:\n            return 0.0\n        n = len(ys)\n        return 1.0 - sum((ys.count(y) / n) ** 2 for y in set(ys))\n    n = len(data)\n    best, bt = None, None\n    for t in cands:\n        L = [y for x, y in data if x < t]\n        R = [y for x, y in data if x >= t]\n        s = len(L) / n * g(L) + len(R) / n * g(R)\n        if best is None or s < best:\n            best, bt = s, t\n    return bt\n",
      tests: [["best_split([(0, 1), (1, 1), (2, 1), (3, 1), (4, 0), (5, 0), (6, 0), (7, 0), (8, 0), (9, 1)], [1, 5])", "5"], ["best_split([(0, 0), (1, 0), (2, 1), (3, 1)], [1, 2, 3])", "2"], ["best_split([(0, 0), (1, 0)], [1])", "1"]],
      edge: [["best_split([(0, 0), (1, 1), (2, 1), (3, 1)], [1, 2, 3])", "1"]],
      ex: "두 쪽의 불순도를 그냥 더하면, 한 쪽에 한 개만 떨어지는 치우친 분할이 유리해집니다 — 한 개짜리는 불순도가 늘 0 이니까요. 각 쪽의 크기로 가중해야 '전체가 얼마나 깨끗해졌나' 를 재는 것이 됩니다.",
    },
  ],
},
/* ── 분류 평가지표 ───────────────────────────────────────── */
{
  unit: "분류 평가지표",
  lesson: "직접 짜 보기 — 혼동행렬에서 시작하기",
  th: {
    sum: "분류 지표는 전부 **TP·FP·FN·TN 네 칸**에서 나온다. 이 네 칸을 세는 것부터 시작한다.",
    body: [
      { h: "네 칸의 뜻", t: "TP 는 맞다고 했고 실제로 맞은 것, FP 는 맞다고 했는데 아닌 것(헛짚음), FN 은 아니라고 했는데 맞은 것(놓침), TN 은 아니라고 했고 실제로도 아닌 것이다. 지표 이름을 외우기 전에 이 네 칸을 그려 보는 게 빠르다." },
      { h: "정밀도는 '내가 맞다 한 것 중', 재현율은 '실제 맞는 것 중'", t: "정밀도 = TP/(TP+FP), 재현율 = TP/(TP+FN). 분모가 다르다 — 정밀도는 내 예측을 세고 재현율은 실제 정답을 센다. 헛짚으면 정밀도가, 놓치면 재현율이 떨어진다." },
      { h: "둘은 대개 반대로 움직인다", t: "의심스러운 것까지 다 맞다고 하면 재현율은 오르고 정밀도는 떨어진다. 그래서 하나만 보고 좋아지면 대개 다른 하나를 버린 것이다. F1 은 둘의 조화평균이라 한쪽이 0 이면 0 이 된다." },
      { h: "정확도는 불균형에서 거짓말한다", t: "1%만 양성인 데이터에서 전부 음성이라고 하면 정확도 99%다. 아무 일도 안 하는 모델이 훌륭해 보인다 — 그래서 불균형 데이터에서는 정확도를 쓰지 않는다." },
    ],
    code: { c: "TP = 맞다 했고 실제 맞음\nFP = 맞다 했는데 아님   (헛짚음)\nFN = 아니라 했는데 맞음 (놓침)\n\n정밀도 = TP / (TP + FP)\n재현율 = TP / (TP + FN)\nF1    = 2PR / (P + R)", cap: "분모가 무엇인지가 전부다" },
    key: ["모든 지표는 네 칸에서 나온다", "정밀도는 헛짚음, 재현율은 놓침", "불균형에서 정확도는 거짓말"],
  },
  q: [
    {
      k: "confusion · 네 칸 세기",
      qq: "정답과 예측 목록(0/1)에서 <code>(TP, FP, FN, TN)</code> 을 돌려주세요.",
      src: "def confusion(y, p):\n    tp = sum(1 for a, b in zip(y, p) if a == 1 and b == 1)\n    fp = sum(1 for a, b in zip(y, p) if a == 1 and b == 0)\n    fn = sum(1 for a, b in zip(y, p) if a == 0 and b == 1)\n    tn = sum(1 for a, b in zip(y, p) if a == 0 and b == 0)\n    return (tp, fp, fn, tn)\n",
      sol: "def confusion(y, p):\n    tp = sum(1 for a, b in zip(y, p) if a == 1 and b == 1)\n    fp = sum(1 for a, b in zip(y, p) if a == 0 and b == 1)\n    fn = sum(1 for a, b in zip(y, p) if a == 1 and b == 0)\n    tn = sum(1 for a, b in zip(y, p) if a == 0 and b == 0)\n    return (tp, fp, fn, tn)\n",
      tests: [["confusion([1, 1, 0, 0], [1, 0, 1, 0])", "(1, 1, 1, 1)"], ["confusion([1, 1, 1], [1, 1, 1])", "(3, 0, 0, 0)"], ["confusion([0, 0], [1, 1])", "(0, 2, 0, 0)"]],
      edge: [["confusion([], [])", "(0, 0, 0, 0)"], ["confusion([1, 0], [0, 0])", "(0, 0, 1, 1)"]],
      ex: "FP 는 '예측이 1, 실제는 0' 입니다 — 시작 코드는 이걸 뒤집어서 FN 과 맞바꿔 놨어요. 헛짚음과 놓침이 서로 자리를 바꾸면, 그 위에 세운 정밀도와 재현율도 통째로 뒤바뀝니다.",
    },
    {
      k: "f1 · 한쪽만 좋아서는 안 된다",
      qq: "정밀도와 재현율의 <b>조화평균</b>을 돌려주세요. 분모가 0이면 0.0 입니다.",
      src: "def f1(prec, rec):\n    return (prec + rec) / 2\n",
      sol: "def f1(prec, rec):\n    if prec + rec == 0:\n        return 0.0\n    return 2 * prec * rec / (prec + rec)\n",
      tests: [["f1(1.0, 1.0)", "1.0"], ["f1(1.0, 0.0)", "0.0"], ["round(f1(0.5, 1.0), 4)", "0.6667"]],
      edge: [["f1(0.0, 0.0)", "0.0"], ["round(f1(0.2, 0.8), 4)", "0.32"]],
      ex: "산술평균은 한쪽이 0이어도 0.5 를 줍니다 — 아무것도 못 찾는 모델이 절반짜리로 보여요. 조화평균은 낮은 쪽에 끌려가서, 둘 다 괜찮아야만 점수가 나옵니다.",
    },
    {
      k: "balanced_acc · 불균형에서도 정직하게",
      qq: "양성 재현율과 음성 재현율의 <b>평균</b>을 돌려주세요. 한쪽 클래스가 없으면 그쪽 재현율은 0으로 봅니다.",
      src: "def balanced_acc(y, p):\n    return sum(1 for a, b in zip(y, p) if a == b) / len(y)\n",
      sol: "def balanced_acc(y, p):\n    pos = [b for a, b in zip(y, p) if a == 1]\n    neg = [b for a, b in zip(y, p) if a == 0]\n    r1 = sum(pos) / len(pos) if pos else 0.0\n    r0 = sum(1 for b in neg if b == 0) / len(neg) if neg else 0.0\n    return (r1 + r0) / 2\n",
      tests: [["balanced_acc([1, 0, 0, 0], [0, 0, 0, 0])", "0.5"], ["balanced_acc([1, 1, 0, 0], [1, 1, 0, 0])", "1.0"], ["balanced_acc([1, 0], [0, 1])", "0.0"]],
      edge: [["balanced_acc([1, 1], [1, 1])", "0.5"], ["round(balanced_acc([1, 1, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0]), 4)", "0.75"]],
      ex: "네 개 중 하나만 양성인데 전부 음성이라 답하면 정확도는 75%로 그럴듯합니다. 균형 정확도는 클래스마다 따로 재고 평균 내니 0.5 — '아무것도 못 맞혔다' 가 그대로 드러나요.",
    },
  ],
},
/* ── 회귀 평가와 정규화 ──────────────────────────────────── */
{
  unit: "회귀 평가와 정규화",
  lesson: "직접 짜 보기 — 오차를 재는 여러 자",
  th: {
    sum: "회귀 지표는 **큰 오차를 얼마나 미워하는가**로 갈린다. 자를 바꾸면 최선의 모델도 바뀐다.",
    body: [
      { h: "MAE 는 공평하고 MSE 는 예민하다", t: "MAE 는 오차를 그대로 더하고, MSE 는 제곱해서 더한다. 10만큼 틀린 하나가 1만큼 틀린 열보다 MSE 에서는 훨씬 나쁘다 — 큰 사고를 특히 피해야 하면 MSE, 이상치가 많아 흔들리기 싫으면 MAE 다." },
      { h: "RMSE 는 단위를 되돌린 MSE", t: "MSE 는 단위가 제곱이라 '원의 제곱' 처럼 읽히지 않는다. 제곱근을 씌우면 원래 단위로 돌아와 사람에게 설명하기 좋다." },
      { h: "R² 는 '평균보다 얼마나 나은가'", t: "1 - (내 오차)/(평균으로 찍은 오차) 다. 0 이면 평균과 같은 수준이고 음수면 평균보다 못한 것이다. 값이 0.9 라도 데이터가 원래 예측하기 쉬웠던 것일 수 있으니, 기준선과 함께 본다." },
      { h: "정규화는 자를 맞추는 일", t: "특성마다 단위가 다르면(키는 cm, 몸무게는 kg) 거리 기반 모델이 큰 숫자에만 끌린다. 표준화는 평균 0·표준편차 1로 맞춘다 — 이때 통계는 반드시 학습 데이터에서만 구해야 한다." },
    ],
    code: { c: "MAE  = mean(|y - ŷ|)\nMSE  = mean((y - ŷ)²)\nRMSE = √MSE\nR²   = 1 - Σ(y-ŷ)² / Σ(y-ȳ)²\n\nz = (x - 학습평균) / 학습표준편차", cap: "무엇을 미워할지 고르는 일" },
    key: ["MSE 는 큰 오차를 크게 미워한다", "R² 는 평균 대비 성적", "정규화 통계는 학습 데이터에서만"],
  },
  q: [
    {
      k: "rmse · 단위를 되돌린 오차",
      qq: "제곱오차의 평균에 <b>제곱근</b>을 씌운 값을 돌려주세요.",
      src: "def rmse(y, p):\n    return sum((a - b) ** 2 for a, b in zip(y, p)) / len(y)\n",
      sol: "def rmse(y, p):\n    return (sum((a - b) ** 2 for a, b in zip(y, p)) / len(y)) ** 0.5\n",
      tests: [["rmse([1.0, 2.0], [1.0, 2.0])", "0.0"], ["rmse([0.0, 0.0], [3.0, 3.0])", "3.0"], ["rmse([1.0], [3.0])", "2.0"]],
      edge: [["round(rmse([1.0, 2.0, 3.0], [2.0, 2.0, 2.0]), 4)", "0.8165"]],
      ex: "제곱근을 빼면 MSE 입니다. 값이 커 보이는 것도 문제지만, 단위가 '원의 제곱' 이라 '평균 얼마나 틀리나요' 라는 질문에 답할 수가 없어요.",
    },
    {
      k: "r2 · 평균보다 나은가",
      qq: "<code>1 - Σ(y-ŷ)² / Σ(y-ȳ)²</code> 를 돌려주세요. 정답이 전부 같으면 분모가 0이니 0.0 을 돌려줍니다.",
      src: "def r2(y, p):\n    m = sum(y) / len(y)\n    return 1 - sum((a - b) ** 2 for a, b in zip(y, p)) / sum((a - m) ** 2 for a in y)\n",
      sol: "def r2(y, p):\n    m = sum(y) / len(y)\n    den = sum((a - m) ** 2 for a in y)\n    if den == 0:\n        return 0.0\n    return 1 - sum((a - b) ** 2 for a, b in zip(y, p)) / den\n",
      tests: [["r2([1.0, 2.0, 3.0], [1.0, 2.0, 3.0])", "1.0"], ["r2([1.0, 2.0, 3.0], [2.0, 2.0, 2.0])", "0.0"], ["r2([5.0, 5.0], [1.0, 9.0])", "0.0"]],
      edge: [["r2([1.0, 3.0], [3.0, 1.0])", "-3.0"]],
      ex: "정답이 전부 같으면 '평균으로 찍은 오차' 가 0 이라 나눗셈이 터집니다. 상수 열은 실무에서 흔해요 — 지표 함수는 이런 경계에서 예외를 던지지 말고 뜻이 통하는 값을 돌려주는 편이 낫습니다.",
    },
    {
      k: "standardize · 통계는 학습에서만",
      qq: "학습 데이터의 평균·표준편차로 <b>테스트 데이터</b>를 표준화한 목록을 돌려주세요. 표준편차가 0이면 전부 0.0 입니다.",
      src: "def standardize(train, test):\n    m = sum(test) / len(test)\n    sd = (sum((x - m) ** 2 for x in test) / len(test)) ** 0.5\n    if sd == 0:\n        return [0.0] * len(test)\n    return [(x - m) / sd for x in test]\n",
      sol: "def standardize(train, test):\n    m = sum(train) / len(train)\n    sd = (sum((x - m) ** 2 for x in train) / len(train)) ** 0.5\n    if sd == 0:\n        return [0.0] * len(test)\n    return [(x - m) / sd for x in test]\n",
      tests: [["standardize([0.0, 2.0], [1.0])", "[0.0]"], ["standardize([0.0, 2.0], [3.0])", "[2.0]"], ["standardize([5.0, 5.0], [1.0, 2.0])", "[0.0, 0.0]"]],
      edge: [["standardize([0.0, 4.0], [0.0, 4.0])", "[-1.0, 1.0]"]],
      ex: "테스트 데이터의 평균을 쓰면 그건 시험 문제를 미리 본 겁니다. 실제 서비스에서는 다음 요청 하나만 들어오는데 그 하나의 평균은 자기 자신이라, 검증 점수만 좋고 현장에서는 무너져요. 통계는 학습 데이터에서만 구해 얼려 둡니다.",
    },
  ],
},
/* ── 지표 선택의 함정 ────────────────────────────────────── */
{
  unit: "지표 선택의 함정 (중급)",
  lesson: "직접 짜 보기 — 숫자가 속이는 자리",
  th: {
    sum: "지표는 **질문에 답할 뿐**이다. 틀린 질문을 하면 훌륭한 점수로 틀린 답을 얻는다.",
    body: [
      { h: "먼저 비용을 적는다", t: "놓침(FN)과 헛짚음(FP)의 값이 다르면, 지표도 그 차이를 반영해야 한다. 암 검진에서 놓침은 생명이고 헛짚음은 재검사다 — 이 둘을 같은 무게로 세는 F1 은 여기서 맞지 않는다." },
      { h: "기준선과 견준다", t: "'정확도 95%' 는 그 자체로는 아무 뜻이 없다. 전부 다수 클래스로 찍었을 때가 94% 라면 1%p 를 번 것뿐이다. 항상 가장 멍청한 모델의 점수를 먼저 구해 둔다." },
      { h: "평균은 소수 클래스를 지운다", t: "클래스가 여럿일 때 micro 평균은 데이터가 많은 클래스에 끌려간다. 클래스마다 똑같이 중요하면 macro 평균 — 클래스별로 구해서 그냥 평균 내는 것 — 을 쓴다." },
      { h: "한 숫자로 줄이면 잃는 게 있다", t: "지표 하나만 보고 모델을 고르면, 그 지표가 못 보는 실패는 배포하고 나서 알게 된다. 최소한 두세 개를 같이 본다." },
    ],
    code: { c: "# 기준선부터\nbase = max(라벨 비율)          # 다 찍기\n내 정확도 - base            # 실제로 번 것\n\n# 비용을 반영한 점수\n비용 = FN * 놓침값 + FP * 헛짚음값\n\n# macro: 클래스마다 구해서 평균", cap: "무엇을 묻고 있는지부터" },
    key: ["FN 과 FP 의 값은 다르다", "기준선 없이는 뜻이 없다", "macro 는 클래스를 공평하게 본다"],
  },
  q: [
    {
      k: "lift · 기준선 대비 얼마나 벌었나",
      qq: "모델 정확도에서 <b>다수 클래스로 다 찍었을 때의 정확도</b>를 뺀 값을 돌려주세요.",
      src: "def lift(y, p):\n    return sum(1 for a, b in zip(y, p) if a == b) / len(y)\n",
      sol: "def lift(y, p):\n    acc = sum(1 for a, b in zip(y, p) if a == b) / len(y)\n    base = max(y.count(v) for v in set(y)) / len(y)\n    return acc - base\n",
      tests: [["lift([1, 0, 0, 0], [0, 0, 0, 0])", "0.0"], ["lift([1, 1, 0, 0], [1, 1, 0, 0])", "0.5"], ["lift([1, 0], [0, 1])", "-0.5"]],
      edge: [["round(lift([1, 0, 0, 0, 0], [1, 0, 0, 0, 0]), 4)", "0.2"]],
      ex: "네 개 중 하나만 양성인 데이터에서 전부 음성이라 답하면 정확도 75% 입니다. 그럴듯하지만 번 것은 0 이에요 — 기준선을 빼 보면 아무 일도 안 했다는 게 바로 보입니다.",
    },
    {
      k: "cost · 놓침과 헛짚음의 값이 다르다",
      qq: "<code>FN</code> 한 건에 <code>c_fn</code>, <code>FP</code> 한 건에 <code>c_fp</code> 의 비용을 매겨 <b>총비용</b>을 돌려주세요.",
      src: "def cost(y, p, c_fn, c_fp):\n    wrong = sum(1 for a, b in zip(y, p) if a != b)\n    return wrong * (c_fn + c_fp)\n",
      sol: "def cost(y, p, c_fn, c_fp):\n    fn = sum(1 for a, b in zip(y, p) if a == 1 and b == 0)\n    fp = sum(1 for a, b in zip(y, p) if a == 0 and b == 1)\n    return fn * c_fn + fp * c_fp\n",
      tests: [["cost([1, 0], [0, 0], 100, 1)", "100"], ["cost([1, 0], [1, 1], 100, 1)", "1"], ["cost([1, 1], [1, 1], 100, 1)", "0"]],
      edge: [["cost([1, 0, 1, 0], [0, 1, 0, 1], 10, 2)", "24"]],
      ex: "틀린 개수만 세면 놓침과 헛짚음이 같은 값이 됩니다. 암 검진이라면 놓침 하나가 재검사 백 번보다 나쁜데, 그 차이가 지표에서 통째로 사라져요 — 비용을 아는 문제라면 비용으로 재야 합니다.",
    },
    {
      k: "macro_recall · 클래스를 공평하게",
      qq: "여러 클래스에서 <b>클래스마다 재현율을 구해 평균</b> 낸 값을 돌려주세요. 정답에 없는 클래스는 세지 않습니다.",
      src: "def macro_recall(y, p):\n    return sum(1 for a, b in zip(y, p) if a == b) / len(y)\n",
      sol: "def macro_recall(y, p):\n    ks = sorted(set(y))\n    rs = []\n    for k in ks:\n        idx = [b for a, b in zip(y, p) if a == k]\n        rs.append(sum(1 for b in idx if b == k) / len(idx))\n    return sum(rs) / len(rs)\n",
      tests: [["macro_recall([0, 0, 0, 1], [0, 0, 0, 0])", "0.5"], ["macro_recall([0, 1, 2], [0, 1, 2])", "1.0"], ["macro_recall([0, 0, 1, 1], [0, 1, 0, 1])", "0.5"]],
      edge: [["round(macro_recall([0, 0, 0, 0, 1, 2], [0, 0, 0, 0, 1, 1]), 4)", "0.6667"]],
      ex: "전체를 한꺼번에 세면 데이터가 많은 클래스가 점수를 다 차지합니다. 희귀 클래스를 하나도 못 맞혀도 점수는 높게 나와요 — 클래스마다 따로 재고 평균 내면 그 클래스의 실패가 1/n 만큼 정직하게 반영됩니다.",
    },
  ],
},
/* ── ROC-AUC와 PR-AUC ────────────────────────────────────── */
{
  unit: "ROC-AUC와 PR-AUC (중급)",
  lesson: "직접 짜 보기 — 순위를 재는 지표",
  th: {
    sum: "AUC 는 **점수의 순위만** 본다. '양성이 음성보다 높은 점수를 받았는가' 를 세는 것이다.",
    body: [
      { h: "임계값을 안 정해도 된다", t: "정밀도·재현율은 '0.5 넘으면 양성' 처럼 선을 그어야 나온다. AUC 는 모든 선을 한꺼번에 본 결과라, 아직 선을 어디에 그을지 안 정했을 때 모델끼리 견주기 좋다." },
      { h: "ROC-AUC 는 곧 순위 확률", t: "양성 하나와 음성 하나를 아무렇게나 뽑았을 때, 양성의 점수가 더 높을 확률이 바로 ROC-AUC 다. 0.5 는 동전 던지기, 1.0 은 완벽한 순서다. 그래서 모든 양성·음성 짝을 세어 직접 계산할 수 있다." },
      { h: "불균형에서는 PR-AUC", t: "음성이 압도적으로 많으면 ROC 곡선은 웬만해선 좋아 보인다. 음성을 조금 잘못 맞혀도 비율로는 티가 안 나기 때문이다. 양성이 드물 때는 정밀도-재현율 곡선이 차이를 더 정직하게 보여 준다." },
      { h: "동점은 반 점", t: "점수가 같은 짝은 순서를 말할 수 없으니 0.5로 센다. 이 처리를 빠뜨리면, 모두에게 같은 점수를 주는 모델이 0점이나 만점으로 나온다." },
    ],
    code: { c: "# ROC-AUC 를 직접 세기\n이긴짝 = 0\nfor 양성점수 in P:\n    for 음성점수 in N:\n        if 양성 > 음성: 이긴짝 += 1\n        elif 양성 == 음성: 이긴짝 += 0.5\nAUC = 이긴짝 / (len(P) * len(N))", cap: "모든 짝을 세면 그것이 AUC" },
    key: ["AUC 는 순위만 본다", "양성이 더 높을 확률과 같다", "동점은 0.5로 센다"],
  },
  q: [
    {
      k: "auc · 모든 짝을 세어 보기",
      qq: "정답(0/1)과 점수에서 <b>ROC-AUC</b> 를 짝 세기로 구하세요. 한쪽 클래스가 없으면 0.5 입니다.",
      src: "def auc(y, s):\n    P = [b for a, b in zip(y, s) if a == 1]\n    N = [b for a, b in zip(y, s) if a == 0]\n    if not P or not N:\n        return 0.5\n    win = sum(1 for p in P for n in N if p > n)\n    return win / (len(P) * len(N))\n",
      sol: "def auc(y, s):\n    P = [b for a, b in zip(y, s) if a == 1]\n    N = [b for a, b in zip(y, s) if a == 0]\n    if not P or not N:\n        return 0.5\n    win = 0.0\n    for p in P:\n        for n in N:\n            win += 1.0 if p > n else (0.5 if p == n else 0.0)\n    return win / (len(P) * len(N))\n",
      tests: [["auc([1, 0], [0.9, 0.1])", "1.0"], ["auc([1, 0], [0.5, 0.5])", "0.5"], ["auc([1, 0], [0.1, 0.9])", "0.0"]],
      edge: [["auc([1, 1], [0.5, 0.5])", "0.5"], ["auc([1, 1, 0, 0], [0.8, 0.5, 0.5, 0.1])", "0.875"]],
      ex: "동점을 안 세면, 모두에게 같은 점수를 주는 모델이 AUC 0 으로 나옵니다 — 실제로는 동전 던지기와 같은 0.5 인데요. 확률이 뭉치는 모델에서 이 처리가 결과를 크게 바꿉니다.",
    },
    {
      k: "pr_base · PR 곡선의 바닥",
      qq: "PR 곡선에서 <b>아무렇게나 찍는 모델</b>의 기준선 — 즉 양성 비율 — 을 돌려주세요.",
      src: "def pr_base(y):\n    return 0.5\n",
      sol: "def pr_base(y):\n    if not y:\n        return 0.0\n    return sum(y) / len(y)\n",
      tests: [["pr_base([1, 0, 0, 0])", "0.25"], ["pr_base([1, 1])", "1.0"], ["pr_base([0, 0])", "0.0"]],
      edge: [["pr_base([])", "0.0"], ["pr_base([1, 0])", "0.5"]],
      ex: "ROC 의 기준선은 언제나 0.5 라 외우기 쉽지만, PR 의 기준선은 **양성 비율**이라 데이터마다 다릅니다. 양성이 1% 인 데이터에서 PR-AUC 0.3 은 기준선의 30배예요 — 이 사실을 모르면 낮은 값을 보고 모델을 버리게 됩니다.",
    },
    {
      k: "prec_at_k · 위에서 k개만 본다",
      qq: "점수가 높은 <b>상위 k개</b> 중 양성의 비율을 돌려주세요. 점수가 같으면 앞에 온 것이 먼저입니다.",
      src: "def prec_at_k(y, s, k):\n    order = sorted(range(len(s)), key=lambda i: s[i])\n    top = order[:k]\n    return sum(y[i] for i in top) / k\n",
      sol: "def prec_at_k(y, s, k):\n    order = sorted(range(len(s)), key=lambda i: (-s[i], i))\n    top = order[:k]\n    return sum(y[i] for i in top) / k\n",
      tests: [["prec_at_k([1, 0, 1], [0.9, 0.1, 0.8], 2)", "1.0"], ["prec_at_k([1, 0, 0], [0.9, 0.8, 0.7], 3)", "1/3"], ["prec_at_k([0, 1], [0.9, 0.1], 1)", "0.0"]],
      edge: [["prec_at_k([1, 1, 0, 0], [0.4, 0.3, 0.2, 0.1], 2)", "1.0"]],
      ex: "정렬 방향을 안 뒤집으면 **가장 낮은 것부터** 뽑습니다 — 추천 목록 맨 위에 가장 관련 없는 것을 올리는 셈이에요. 오름차순이 기본이라는 걸 잊으면 조용히 정반대 결과가 나옵니다.",
    },
  ],
},
/* ── 교차검증 설계 ───────────────────────────────────────── */
{
  unit: "교차검증 설계 (심화)",
  lesson: "직접 짜 보기 — 나누는 방법이 결과를 정한다",
  th: {
    sum: "교차검증은 **어떻게 나누느냐**가 전부다. 잘못 나누면 점수가 부풀고, 그 사실을 배포 후에 안다.",
    body: [
      { h: "k-겹은 돌아가며 시험을 본다", t: "데이터를 k조각으로 나눠, 한 조각을 시험지로 두고 나머지로 배운다. k번 반복해 평균을 낸다 — 한 번만 나눴을 때의 운을 줄이는 장치다." },
      { h: "클래스 비율을 유지한다", t: "양성이 5%인 데이터를 무작정 나누면 어떤 조각에는 양성이 하나도 안 들어갈 수 있다. 층화(stratified) 분할은 조각마다 비율을 맞춘다 — 불균형에서는 기본이다." },
      { h: "시계열은 섞으면 안 된다", t: "미래 데이터로 배워 과거를 맞히는 것은 아무 뜻이 없다. 시계열은 항상 '앞부분으로 배우고 뒷부분으로 시험' 이어야 한다. 무작위 분할이 만든 높은 점수는 전부 거짓이다." },
      { h: "같은 사람이 양쪽에 있으면 누수", t: "한 환자의 사진이 학습과 검증에 나뉘어 들어가면, 모델은 그 환자를 외운 것으로 점수를 번다. 사람·기기·상점처럼 묶음이 있으면 묶음째로 나눈다(group split)." },
    ],
    code: { c: "# k-겹 인덱스\nfor i in range(k):\n    val   = idx[i::k]        # 한 조각\n    train = 나머지\n\n# 시계열: 앞으로만\ntrain = data[:t]\nval   = data[t:t+m]", cap: "무엇을 섞으면 안 되는가" },
    key: ["k-겹은 운을 줄인다", "불균형이면 층화", "시계열·묶음은 절대 섞지 않는다"],
  },
  q: [
    {
      k: "kfold · 조각으로 나누기",
      qq: "<code>n</code>개를 <code>k</code>조각으로 나눈 <b>검증 인덱스 목록</b>을 돌려주세요. 모든 인덱스가 <b>정확히 한 번</b>씩 나와야 합니다.",
      src: "def kfold(n, k):\n    size = n // k\n    return [list(range(i * size, (i + 1) * size)) for i in range(k)]\n",
      sol: "def kfold(n, k):\n    return [list(range(i, n, k)) for i in range(k)]\n",
      tests: [["sorted(x for f in kfold(7, 3) for x in f)", "list(range(7))"], ["len(kfold(10, 5))", "5"], ["sorted(x for f in kfold(10, 3) for x in f)", "list(range(10))"]],
      edge: [["sorted(x for f in kfold(5, 5) for x in f)", "list(range(5))"], ["kfold(4, 2)", "[[0, 2], [1, 3]]"]],
      ex: "`n // k` 로 자르면 나머지가 통째로 버려집니다 — 7개를 3조각으로 나눌 때 마지막 하나가 어디에도 안 들어가요. 검증에 한 번도 안 쓰인 데이터가 생기는 겁니다. 건너뛰기로 나누면 개수가 딱 안 떨어져도 전부 한 번씩 들어갑니다.",
    },
    {
      k: "time_split · 미래로 과거를 맞히지 않기",
      qq: "시간순 데이터에서 <code>i</code>번째 검증 구간의 <b>(학습 끝 위치, 검증 시작 위치)</b> 를 돌려주세요. 검증 구간 크기는 <code>m</code> 이고, 학습은 언제나 그 앞 전부입니다.",
      src: "def time_split(n, m, i):\n    start = i * m\n    return (n, start)\n",
      sol: "def time_split(n, m, i):\n    start = n - (i + 1) * m\n    return (start, start)\n",
      tests: [["time_split(10, 2, 0)", "(8, 8)"], ["time_split(10, 2, 1)", "(6, 6)"], ["time_split(6, 3, 0)", "(3, 3)"]],
      edge: [["time_split(5, 5, 0)", "(0, 0)"]],
      ex: "학습 끝이 n 이면 데이터 전체로 배운 뒤 그 안쪽을 시험 보는 것 — 답을 보고 시험 치는 셈입니다. 검증 구간은 반드시 학습 구간보다 **뒤**에 있어야 하고, 그래서 두 위치가 같은 점에서 맞물립니다.",
    },
    {
      k: "group_split · 같은 사람은 한쪽에만",
      qq: "<code>[(그룹, 값)]</code> 에서 <b>그룹 단위로</b> 검증 집합을 만드세요. 검증에 들어간 그룹의 값이 학습에 <b>하나도</b> 없어야 합니다. 검증 그룹 목록을 받아 학습 값 목록을 돌려줍니다.",
      src: "def group_split(rows, val_groups):\n    n = len(rows)\n    return [v for _, v in rows[: n // 2]]\n",
      sol: "def group_split(rows, val_groups):\n    vg = set(val_groups)\n    return [v for g, v in rows if g not in vg]\n",
      tests: [["group_split([('a', 1), ('a', 2), ('b', 3)], ['a'])", "[3]"], ["group_split([('a', 1), ('b', 2)], ['b'])", "[1]"], ["group_split([('a', 1), ('a', 2)], [])", "[1, 2]"]],
      edge: [["group_split([('a', 1), ('b', 2), ('a', 3)], ['a'])", "[2]"], ["group_split([('a', 1)], ['a'])", "[]"]],
      ex: "행을 반으로 자르면 같은 사람의 데이터가 양쪽에 걸칩니다. 모델은 그 사람을 외운 것만으로 점수를 벌고, 처음 보는 사람에게는 무너져요 — 나누는 단위를 '행' 이 아니라 '그룹' 으로 두는 것이 핵심입니다.",
    },
  ],
},
/* ── 임계값·비용 ─────────────────────────────────────────── */
{
  unit: "임계값·비용과 실전 괴리 (심화)",
  lesson: "직접 짜 보기 — 선을 어디에 그을 것인가",
  th: {
    sum: "모델이 내는 것은 점수이고, **선을 긋는 것은 사람의 결정**이다. 0.5 는 기본값일 뿐 정답이 아니다.",
    body: [
      { h: "0.5 는 아무 근거가 없다", t: "'확률 0.5 이상이면 양성' 은 관습일 뿐이다. 놓침이 비싸면 선을 낮춰 더 많이 잡고, 헛짚음이 비싸면 선을 높인다. 이 선은 지표가 아니라 비용으로 정한다." },
      { h: "총비용이 가장 작은 선을 찾는다", t: "후보 임계값마다 FN·FP 개수를 세어 비용을 계산하고, 가장 싼 것을 고른다. 몇 줄이면 되는데, 이걸 안 해서 기본값 0.5 로 나가는 모델이 많다." },
      { h: "확률이 진짜 확률이 아닐 수 있다", t: "모델이 0.9 라고 한 것들 중 실제로 90%가 양성이어야 '보정되었다' 고 한다. 안 그러면 그 숫자로 기댓값을 계산하는 순간 틀린다 — 운영에서 확률을 그대로 쓸 거면 보정을 확인한다." },
      { h: "학습 분포와 운영 분포는 다르다", t: "양성 비율이 학습 때와 달라지면 최적 임계값도 달라진다. 배포 후에도 임계값은 다시 볼 대상이지, 한 번 정하고 잊는 상수가 아니다." },
    ],
    code: { c: "best, bt = None, None\nfor t in 후보들:\n    p = [1 if s >= t else 0 for s in 점수]\n    c = FN(y,p)*놓침값 + FP(y,p)*헛짚음값\n    if best is None or c < best:\n        best, bt = c, t", cap: "선은 비용으로 정한다" },
    key: ["0.5 는 근거 없는 기본값", "비용이 최소인 선을 찾는다", "임계값은 다시 볼 대상"],
  },
  q: [
    {
      k: "best_threshold · 가장 싼 선 찾기",
      qq: "후보 임계값 중 <b>총비용이 가장 작은</b> 것을 돌려주세요. <code>점수 &gt;= t</code> 면 양성이고, 동점이면 <b>작은 임계값</b>입니다.",
      src: "def best_threshold(y, s, cands, c_fn, c_fp):\n    return 0.5\n",
      sol: "def best_threshold(y, s, cands, c_fn, c_fp):\n    best, bt = None, None\n    for t in sorted(cands):\n        p = [1 if v >= t else 0 for v in s]\n        fn = sum(1 for a, b in zip(y, p) if a == 1 and b == 0)\n        fp = sum(1 for a, b in zip(y, p) if a == 0 and b == 1)\n        c = fn * c_fn + fp * c_fp\n        if best is None or c < best:\n            best, bt = c, t\n    return bt\n",
      tests: [["best_threshold([1, 0], [0.4, 0.45], [0.3, 0.5], 100, 1)", "0.3"], ["best_threshold([1, 0], [0.6, 0.4], [0.5], 1, 1)", "0.5"], ["best_threshold([0, 0], [0.9, 0.8], [0.5, 0.95], 1, 5)", "0.95"]],
      edge: [["best_threshold([1, 1], [0.1, 0.2], [0.05, 0.5], 10, 1)", "0.05"]],
      ex: "놓침이 헛짚음보다 백 배 비싸면 선을 낮춰 의심스러운 것까지 다 잡는 편이 쌉니다. 0.5 를 그대로 쓰면 그 백 배를 그냥 내는 거예요 — 비용을 아는 문제라면 선도 비용으로 정합니다.",
    },
    {
      k: "recall_at · 재현율을 못 박고 나머지를 아끼기",
      qq: "재현율이 <code>target</code> <b>이상</b>이 되는 임계값 중 <b>가장 높은 것</b>을 돌려주세요. 없으면 후보 중 가장 낮은 것입니다.",
      src: "def recall_at(y, s, cands, target):\n    for t in sorted(cands):\n        p = [1 if v >= t else 0 for v in s]\n        tp = sum(1 for a, b in zip(y, p) if a == 1 and b == 1)\n        fn = sum(1 for a, b in zip(y, p) if a == 1 and b == 0)\n        if tp + fn and tp / (tp + fn) >= target:\n            return t\n    return min(cands)\n",
      sol: "def recall_at(y, s, cands, target):\n    for t in sorted(cands, reverse=True):\n        p = [1 if v >= t else 0 for v in s]\n        tp = sum(1 for a, b in zip(y, p) if a == 1 and b == 1)\n        fn = sum(1 for a, b in zip(y, p) if a == 1 and b == 0)\n        if tp + fn and tp / (tp + fn) >= target:\n            return t\n    return min(cands)\n",
      tests: [["recall_at([1, 1, 0], [0.9, 0.6, 0.1], [0.2, 0.5, 0.8], 1.0)", "0.5"], ["recall_at([1, 1], [0.9, 0.8], [0.5, 0.85], 1.0)", "0.5"], ["recall_at([1], [0.9], [0.1, 0.5, 0.95], 1.0)", "0.5"]],
      edge: [["recall_at([1, 1], [0.1, 0.2], [0.5, 0.9], 1.0)", "0.5"]],
      ex: "낮은 임계값부터 찾으면 조건을 만족하는 **가장 낮은** 선이 나옵니다 — 재현율은 맞지만 헛짚음이 필요 이상으로 많아져요. '재현율 99% 를 지키되 알림은 최소로' 가 실무의 요구라, 조건을 만족하는 것 중 가장 높은 선을 골라야 합니다.",
    },
    {
      k: "calib_gap · 확률이 진짜인가",
      qq: "점수가 <code>lo</code> 이상 <code>hi</code> 미만인 구간에서, <b>평균 점수</b>와 <b>실제 양성 비율</b>의 차이(절댓값)를 돌려주세요. 그 구간에 아무것도 없으면 0.0 입니다.",
      src: "def calib_gap(y, s, lo, hi):\n    idx = [i for i, v in enumerate(s) if lo <= v < hi]\n    if not idx:\n        return 0.0\n    return abs(sum(s[i] for i in idx) / len(idx) - 0.5)\n",
      sol: "def calib_gap(y, s, lo, hi):\n    idx = [i for i, v in enumerate(s) if lo <= v < hi]\n    if not idx:\n        return 0.0\n    avg = sum(s[i] for i in idx) / len(idx)\n    rate = sum(y[i] for i in idx) / len(idx)\n    return abs(avg - rate)\n",
      tests: [["calib_gap([1, 0], [0.5, 0.5], 0.4, 0.6)", "0.0"], ["calib_gap([0, 0], [0.9, 0.9], 0.8, 1.0)", "0.9"], ["round(calib_gap([1, 1], [0.9, 0.9], 0.8, 1.0), 10)", "0.1"]],
      edge: [["calib_gap([1], [0.3], 0.8, 1.0)", "0.0"]],
      ex: "'0.9 라고 말한 것들이 정말 90% 양성인가' 를 재는 것이 보정입니다. 평균 점수를 0.5 와 견주면 그건 보정이 아니라 그냥 '점수가 가운데서 얼마나 떨어졌나' 예요 — 반드시 **실제 비율**과 견줘야 합니다.",
    },
  ],
},
/* ── 코드 리뷰 ───────────────────────────────────────────── */
{
  unit: "코드 리뷰 — 결함 찾기",
  lesson: "직접 고쳐 보기 — 평가 코드에서 자주 걸리는 것",
  th: {
    sum: "평가 코드의 버그는 **점수를 올려 주기 때문에** 아무도 의심하지 않는다. 그래서 더 위험하다.",
    body: [
      { h: "점수가 갑자기 좋아지면 의심한다", t: "지표를 바꾸지도 않았는데 성능이 뛰었다면, 대개 누수가 생긴 것이다. 기뻐하기 전에 '무엇이 달라졌나' 를 먼저 본다 — 실무에서 가장 비싼 실수가 이것이다." },
      { h: "0으로 나누는 자리를 찾는다", t: "정밀도·재현율·R² 는 전부 분모가 0이 될 수 있다. 예외로 터지면 그래도 낫고, 조용히 nan 이 되면 평균에 섞여 전부를 망친다." },
      { h: "정답과 예측의 순서를 확인한다", t: "`f(y, p)` 와 `f(p, y)` 는 정밀도와 재현율을 맞바꾼다. 균형 잡힌 데이터에서는 값이 비슷해 눈치채기 어렵다 — 인자 이름을 명확히 쓰는 것이 최선의 방어다." },
      { h: "전처리가 전체 데이터를 봤는지 본다", t: "정규화, 결측 대치, 특성 선택이 학습·검증을 합친 데이터에서 이뤄졌으면 누수다. 이건 지표 코드가 아니라 그 위쪽에 있어서 리뷰에서 자주 놓친다." },
    ],
    code: { c: "# 리뷰 체크리스트\n□ 분모 0 을 막았나\n□ y 와 p 순서가 맞나\n□ 전처리가 학습 데이터만 봤나\n□ 기준선과 견줬나\n□ 점수가 갑자기 좋아졌다면 왜인가", cap: "점수가 좋아지면 먼저 의심한다" },
    key: ["누수는 점수를 올려서 숨는다", "분모 0 을 먼저 막는다", "y 와 p 순서를 확인한다"],
  },
  q: [
    {
      k: "precision_safe · 분모가 0인 자리",
      qq: "정밀도를 구하세요. <b>양성이라 예측한 것이 하나도 없으면</b> 0.0 입니다.",
      src: "def precision_safe(y, p):\n    tp = sum(1 for a, b in zip(y, p) if a == 1 and b == 1)\n    fp = sum(1 for a, b in zip(y, p) if a == 0 and b == 1)\n    return tp / (tp + fp)\n",
      sol: "def precision_safe(y, p):\n    tp = sum(1 for a, b in zip(y, p) if a == 1 and b == 1)\n    fp = sum(1 for a, b in zip(y, p) if a == 0 and b == 1)\n    if tp + fp == 0:\n        return 0.0\n    return tp / (tp + fp)\n",
      tests: [["precision_safe([1, 0], [0, 0])", "0.0"], ["precision_safe([1, 0], [1, 0])", "1.0"], ["precision_safe([1, 0], [1, 1])", "0.5"]],
      edge: [["precision_safe([], [])", "0.0"], ["precision_safe([0, 0], [0, 0])", "0.0"]],
      ex: "임계값을 높이면 양성 예측이 0 이 되는 일이 실제로 생깁니다. 그때 터지면 임계값 탐색 루프가 통째로 멈춰요 — 지표 함수는 경계에서 뜻이 통하는 값을 돌려주도록 만들어 둡니다.",
    },
    {
      k: "leak_free · 대치도 학습에서만",
      qq: "결측(<code>None</code>)을 <b>학습 데이터의 중앙값</b>으로 채운 테스트 목록을 돌려주세요. 학습에 값이 하나도 없으면 0.0 으로 채웁니다.",
      src: "def leak_free(train, test):\n    vals = sorted(v for v in train + test if v is not None)\n    if not vals:\n        return [0.0] * len(test)\n    med = vals[len(vals) // 2]\n    return [med if v is None else v for v in test]\n",
      sol: "def leak_free(train, test):\n    vals = sorted(v for v in train if v is not None)\n    if not vals:\n        return [0.0] * len(test)\n    med = vals[len(vals) // 2]\n    return [med if v is None else v for v in test]\n",
      tests: [["leak_free([1.0, 2.0, 3.0], [None])", "[2.0]"], ["leak_free([1.0, 2.0, 3.0], [None, 9.0, 9.0, 9.0])", "[2.0, 9.0, 9.0, 9.0]"], ["leak_free([None], [None])", "[0.0]"]],
      edge: [["leak_free([5.0], [None, None])", "[5.0, 5.0]"]],
      ex: "테스트 값까지 넣어 중앙값을 구하면, 채워 넣는 그 숫자에 이미 정답 쪽 정보가 섞입니다. 검증 점수는 오르고 실제 서비스에서는 떨어져요 — 대치·정규화·특성 선택은 전부 학습 데이터만 보고 정해야 합니다.",
    },
    {
      k: "eval_order · 인자 순서가 바뀌면",
      qq: "<code>(정밀도, 재현율)</code> 을 돌려주세요. 첫 인자가 <b>정답</b>, 둘째가 <b>예측</b>입니다. 분모가 0이면 0.0 입니다.",
      src: "def eval_order(y, p):\n    tp = sum(1 for a, b in zip(y, p) if a == 1 and b == 1)\n    pp = sum(y)\n    ap = sum(p)\n    prec = tp / pp if pp else 0.0\n    rec = tp / ap if ap else 0.0\n    return (prec, rec)\n",
      sol: "def eval_order(y, p):\n    tp = sum(1 for a, b in zip(y, p) if a == 1 and b == 1)\n    pp = sum(p)\n    ap = sum(y)\n    prec = tp / pp if pp else 0.0\n    rec = tp / ap if ap else 0.0\n    return (prec, rec)\n",
      tests: [["eval_order([1, 1, 0], [1, 0, 0])", "(1.0, 0.5)"], ["eval_order([1, 0, 0], [1, 1, 1])", "(1/3, 1.0)"], ["eval_order([1, 1], [1, 1])", "(1.0, 1.0)"]],
      edge: [["eval_order([0, 0], [0, 0])", "(0.0, 0.0)"], ["eval_order([1, 1, 1, 0], [1, 0, 0, 0])", "(1.0, 1/3)"]],
      ex: "정밀도의 분모는 **예측한 양성 수**, 재현율의 분모는 **실제 양성 수** 입니다. 시작 코드는 이 둘을 맞바꿔 놨어요 — 두 값이 통째로 뒤바뀝니다. 양성 개수가 양쪽에서 같은 데이터로만 시험하면 영영 못 잡습니다.",
    },
  ],
},
];
