/* 네트워크 실습 2차 — 실습이 하나도 없던 6개 유닛을 연다.
   HTTP 메서드와 멱등성 · HTTP 캐싱 · 쿠키와 CORS · 소켓 상태 · TCP 혼잡제어 · DNS/LB.

   네트워크는 눈에 안 보여서 '읽고 넘어가기' 가 되기 쉽다. 하지만 실제로 판단이
   갈리는 자리는 계산과 규칙이다 — 다시 보내도 되는 요청인지, 캐시가 아직 살아
   있는지, 이 요청이 미리 물어봐야 하는 요청인지. 그 규칙을 직접 짜 본다.

   채점은 앱의 JS 하네스가 한다. */
module.exports = [
/* ── HTTP 메서드·상태코드 중급 ────────────────────────────── */
{
  unit: "HTTP 메서드·상태코드 중급 — 안전성과 멱등성",
  lesson: "직접 짜 보기 — 다시 보내도 되는 요청인가",
  th: {
    sum: "**안전한 요청**은 아무것도 바꾸지 않고, **멱등한 요청**은 여러 번 보내도 결과가 같다.",
    body: [
      { h: "안전과 멱등은 다르다", t: "`GET` 은 아무것도 안 바꾸니 둘 다 해당한다. `DELETE` 는 바꾸긴 하지만 여러 번 지워도 결과가 같아 멱등이다. `POST` 는 부를 때마다 새로 만들어져 둘 다 아니다." },
      { h: "재시도 여부를 이것으로 정한다", t: "응답이 안 왔을 때 다시 보내도 되는지는 멱등성이 정한다. `POST` 를 그냥 다시 보내면 두 번 결제될 수 있다. 그래서 재시도가 필요한 `POST` 에는 요청 번호를 붙여 두 번째를 걸러 낸다." },
      { h: "PUT 과 PATCH 는 다르다", t: "`PUT` 은 전체를 그 내용으로 바꾸므로 몇 번 보내도 같은 상태가 된다. `PATCH` 는 '일부를 이렇게 고쳐라' 라서, `+1` 같은 내용이면 보낼 때마다 값이 달라진다." },
      { h: "상태 코드는 무리로 읽는다", t: "2xx 는 성공, 4xx 는 보낸 쪽 잘못, 5xx 는 서버 잘못이다. 4xx 를 재시도하면 몇 번을 해도 같은 결과이고, 5xx 는 잠시 뒤 다시 해 볼 만하다 — 재시도 규칙이 여기서 갈린다." },
    ],
    code: { c: "GET    안전 o  멱등 o\nDELETE 안전 x  멱등 o\nPOST   안전 x  멱등 x   →  재시도하려면 요청 번호가 필요", cap: "다시 보내도 되는가" },
    key: ["안전과 멱등은 다르다", "재시도 여부는 멱등성이 정한다", "4xx 는 재시도해도 같다"],
  },
  q: [
    {
      k: "isIdempotent · 다시 보내도 되는 메서드",
      qq: "메서드 이름을 받아 <b>멱등한지</b> 판단하세요. <code>GET</code>·<code>HEAD</code>·<code>PUT</code>·<code>DELETE</code>·<code>OPTIONS</code> 가 멱등입니다.",
      src: "function isIdempotent(method) {\n  return method === 'GET';\n}",
      sol: "function isIdempotent(method) {\n  return ['GET', 'HEAD', 'PUT', 'DELETE', 'OPTIONS'].includes(String(method).toUpperCase());\n}",
      tests: [["isIdempotent('GET')", "true"],
              ["isIdempotent('DELETE')", "true"],
              ["isIdempotent('POST')", "false"]],
      edge: [["isIdempotent('put')", "true"],
             ["isIdempotent('PATCH')", "false"]],
      ex: "GET 만 멱등이라고 보면 DELETE 재시도를 막게 되어 쓸데없이 실패가 남습니다. 반대로 POST 를 멱등이라고 보면 두 번 결제되는 사고가 나요 — 이 목록 하나가 재시도 규칙 전체를 정합니다.",
    },
    {
      k: "retryable · 다시 해 볼 만한 실패인가",
      qq: "상태 코드와 메서드를 받아 <b>재시도할지</b> 정하세요. <b>5xx 이면서 멱등한 메서드</b>일 때만 참입니다.",
      src: "function retryable(status, method) {\n  return status >= 400;\n}",
      sol: "function retryable(status, method) {\n  const idem = ['GET', 'HEAD', 'PUT', 'DELETE', 'OPTIONS'].includes(String(method).toUpperCase());\n  return status >= 500 && status < 600 && idem;\n}",
      tests: [["retryable(503, 'GET')", "true"],
              ["retryable(404, 'GET')", "false"],
              ["retryable(503, 'POST')", "false"]],
      edge: [["retryable(200, 'GET')", "false"],
             ["retryable(500, 'PUT')", "true"]],
      ex: "4xx 는 보낸 쪽 잘못이라 몇 번을 다시 보내도 같은 답이 옵니다. 그동안 서버만 두드리는 셈이에요. 그리고 5xx 라도 멱등하지 않은 요청을 다시 보내면 두 번 처리될 수 있습니다.",
    },
    {
      k: "statusGroup · 무리로 읽기",
      qq: "상태 코드를 받아 무리를 돌려주세요. 2xx는 <code>'success'</code>, 3xx는 <code>'redirect'</code>, 4xx는 <code>'client'</code>, 5xx는 <code>'server'</code>, 그 밖은 <code>'other'</code> 입니다.",
      src: "function statusGroup(status) {\n  return status < 400 ? 'success' : 'client';\n}",
      sol: "function statusGroup(status) {\n  if (status >= 200 && status < 300) return 'success';\n  if (status >= 300 && status < 400) return 'redirect';\n  if (status >= 400 && status < 500) return 'client';\n  if (status >= 500 && status < 600) return 'server';\n  return 'other';\n}",
      tests: [["statusGroup(204)", "'success'"],
              ["statusGroup(301)", "'redirect'"],
              ["statusGroup(503)", "'server'"]],
      edge: [["statusGroup(100)", "'other'"],
             ["statusGroup(404)", "'client'"]],
      ex: "성공과 실패로만 나누면 리다이렉트가 성공에 섞이고, 서버 잘못과 보낸 쪽 잘못이 한 덩어리가 됩니다. 그 둘은 재시도 규칙도 알림 규칙도 완전히 달라요.",
    },
  ],
},
/* ── HTTP 캐싱 심화 ───────────────────────────────────────── */
{
  unit: "HTTP 캐싱 심화 — Cache-Control·ETag·조건부 요청·CDN",
  lesson: "직접 짜 보기 — 다시 안 받아도 되는가",
  th: {
    sum: "캐싱은 두 단계다. **아예 묻지 않기**(신선한 동안)와 **바뀐 것만 받기**(조건부 요청).",
    body: [
      { h: "신선한 동안은 묻지 않는다", t: "`max-age=600` 이면 600초 동안은 서버에 묻지도 않고 캐시를 쓴다. 가장 빠른 요청은 아예 보내지 않은 요청이다. 대신 그동안 원본이 바뀌어도 모른다." },
      { h: "지났으면 물어보되 조건을 건다", t: "만료된 뒤에는 '내가 가진 것이 아직 맞나' 를 묻는다. 서버는 바뀐 게 없으면 `304` 만 돌려주고 본문은 안 보낸다. 다시 받는 것보다 훨씬 싸다." },
      { h: "무엇으로 견줄지 정한다", t: "내용의 지문(ETag)으로 견주면 1초 안에 여러 번 바뀌어도 정확하다. 수정 시각으로 견주면 초 단위라 그 안의 변경을 놓친다. 둘 다 있으면 지문이 우선이다." },
      { h: "바뀌면 주소를 바꾼다", t: "정적 파일은 이름에 내용 지문을 넣고 아주 길게 캐시한다. 내용이 바뀌면 이름이 바뀌니 캐시를 지울 필요가 없다. 같은 이름을 계속 쓰면서 캐시만 짧게 잡는 것보다 훨씬 낫다." },
    ],
    code: { c: "Cache-Control: max-age=600      // 600초는 묻지 않는다\nIf-None-Match: \"abc123\"          // 지났으면 조건부로\n→ 304 Not Modified              // 바뀐 게 없다", cap: "묻지 않기 → 조건부로 묻기" },
    key: ["신선한 동안은 묻지 않는다", "지났으면 조건부로 묻는다", "바뀌면 주소를 바꾼다"],
  },
  q: [
    {
      k: "isFresh · 아직 묻지 않아도 되는가",
      qq: "받은 시각·<code>max-age</code>(초)·지금 시각(초)을 받아 <b>아직 신선한지</b> 판단하세요. <b>정확히 만료된 순간은 신선하지 않습니다.</b>",
      src: "function isFresh(fetchedAt, maxAge, now) {\n  return now - fetchedAt <= maxAge;\n}",
      sol: "function isFresh(fetchedAt, maxAge, now) {\n  return now - fetchedAt < maxAge;\n}",
      tests: [["isFresh(0, 600, 300)", "true"],
              ["isFresh(0, 600, 600)", "false"],
              ["isFresh(0, 600, 601)", "false"]],
      edge: [["isFresh(0, 0, 0)", "false"],
             ["isFresh(100, 10, 105)", "true"]],
      ex: "경계를 정하지 않으면 딱 그 순간에만 다르게 동작합니다. 재현이 어려워 찾는 데 오래 걸려요 — 한쪽으로 못 박아 두면 모두가 같게 씁니다.",
    },
    {
      k: "revalidate · 바뀐 것만 받기",
      qq: "내가 가진 ETag 와 서버의 현재 ETag 를 받아 응답을 정하세요. 같으면 <code>{ status: 304, body: null }</code>, 다르면 <code>{ status: 200, body: 서버본문 }</code> 입니다.",
      src: "function revalidate(mine, serverTag, serverBody) {\n  return { status: 200, body: serverBody };\n}",
      sol: "function revalidate(mine, serverTag, serverBody) {\n  if (mine === serverTag) return { status: 304, body: null };\n  return { status: 200, body: serverBody };\n}",
      tests: [["revalidate('a1', 'a1', 'x')", "({ status: 304, body: null })"],
              ["revalidate('a1', 'b2', 'x')", "({ status: 200, body: 'x' })"],
              ["revalidate(null, 'b2', 'x')", "({ status: 200, body: 'x' })"]],
      edge: [["revalidate('', '', 'x')", "({ status: 304, body: null })"]],
      ex: "언제나 본문을 다시 보내면, 바뀐 게 없는데도 매번 전체를 내려받습니다. 조건부 요청의 값어치는 '바뀐 게 없다' 는 짧은 답 하나로 끝나는 데 있어요.",
    },
    {
      k: "assetUrl · 바뀌면 주소를 바꾸기",
      qq: "파일 이름과 내용 지문을 받아 <code>이름.지문.확장자</code> 꼴로 만들어 주세요. 지문이 <b>없으면 원래 이름</b> 그대로입니다.",
      src: "function assetUrl(name, hash) {\n  return name + '?v=' + hash;\n}",
      sol: "function assetUrl(name, hash) {\n  if (!hash) return name;\n  const i = name.lastIndexOf('.');\n  if (i < 0) return name + '.' + hash;\n  return name.slice(0, i) + '.' + hash + name.slice(i);\n}",
      tests: [["assetUrl('app.js', 'a1b2')", "'app.a1b2.js'"],
              ["assetUrl('app.js', '')", "'app.js'"],
              ["assetUrl('logo', 'x9')", "'logo.x9'"]],
      edge: [["assetUrl('a.b.css', 'z1')", "'a.b.z1.css'"],
             ["assetUrl('app.js', null)", "'app.js'"]],
      ex: "물음표 뒤에 붙이는 방식은 일부 중간 캐시가 무시해서 옛 파일이 계속 나갑니다. 이름 자체를 바꾸면 그것은 완전히 다른 파일이라 그런 일이 없어요.",
    },
  ],
},
/* ── 쿠키와 CORS 심화 ─────────────────────────────────────── */
{
  unit: "쿠키와 CORS 심화 — preflight·credentials·SameSite",
  lesson: "직접 짜 보기 — 다른 출처에서 부를 때",
  th: {
    sum: "브라우저는 **다른 출처**의 요청을 기본적으로 막는다. 서버가 허락한다고 말해야 열린다.",
    body: [
      { h: "출처는 세 가지가 모두 같아야 한다", t: "규약(http/https)·호스트·포트 중 하나만 달라도 다른 출처다. `https://a.com` 과 `http://a.com` 도 다르다. '같은 도메인인데 왜 막히지' 의 대부분이 포트나 규약 차이다." },
      { h: "단순한 요청은 바로 보낸다", t: "`GET`·`POST` 에 평범한 헤더만 있으면 브라우저가 그냥 보내고, 응답 헤더를 보고 읽을지 말지 정한다. 요청은 이미 서버에 도착한 뒤라는 점이 중요하다 — 막히는 것은 '읽기' 다." },
      { h: "그 밖에는 먼저 물어본다", t: "`PUT`·`DELETE` 이거나 별난 헤더가 있으면, 브라우저가 먼저 `OPTIONS` 로 '보내도 되냐' 고 묻는다(preflight). 서버가 허락하지 않으면 진짜 요청은 아예 나가지 않는다." },
      { h: "쿠키를 보내려면 양쪽이 다 켜야 한다", t: "클라이언트가 `credentials` 를 켜고, 서버도 허용한다고 답해야 한다. 이때 서버는 `*` 로 허용할 수 없고 출처를 정확히 적어야 한다. 한쪽만 켜면 조용히 쿠키 없이 나간다." },
    ],
    code: { c: "// 단순 요청: 그냥 보내고 응답 헤더로 판단\n// 그 밖: OPTIONS 로 먼저 물어본다\nAccess-Control-Allow-Origin: https://app.example.com", cap: "허락을 받아야 읽는다" },
    key: ["규약·호스트·포트가 모두 같아야 같은 출처", "단순하지 않으면 먼저 물어본다", "쿠키는 양쪽이 다 켜야 간다"],
  },
  q: [
    {
      k: "sameOrigin · 무엇이 같아야 같은 출처인가",
      qq: "두 주소가 <b>같은 출처</b>인지 판단하세요. <b>규약·호스트·포트</b>가 모두 같아야 합니다. 주소는 <code>{ scheme, host, port }</code> 로 옵니다.",
      src: "function sameOrigin(a, b) {\n  return a.host === b.host;\n}",
      sol: "function sameOrigin(a, b) {\n  return a.scheme === b.scheme && a.host === b.host && a.port === b.port;\n}",
      tests: [["sameOrigin({ scheme: 'https', host: 'a.com', port: 443 }, { scheme: 'https', host: 'a.com', port: 443 })", "true"],
              ["sameOrigin({ scheme: 'https', host: 'a.com', port: 443 }, { scheme: 'http', host: 'a.com', port: 443 })", "false"],
              ["sameOrigin({ scheme: 'https', host: 'a.com', port: 443 }, { scheme: 'https', host: 'a.com', port: 8443 })", "false"]],
      edge: [["sameOrigin({ scheme: 'https', host: 'a.com', port: 443 }, { scheme: 'https', host: 'b.com', port: 443 })", "false"]],
      ex: "호스트만 보면 https 와 http 가 같은 출처가 되어, 안전하지 않은 쪽에서 안전한 쪽의 자료를 읽을 수 있게 됩니다. 포트도 마찬가지라 개발 서버에서만 되는 일이 생겨요.",
    },
    {
      k: "needsPreflight · 먼저 물어봐야 하는 요청인가",
      qq: "메서드와 헤더 이름 목록을 받아 <b>미리 물어봐야 하는지</b> 판단하세요. <code>GET</code>·<code>HEAD</code>·<code>POST</code> 가 아니거나, <code>content-type</code>·<code>accept</code> 밖의 헤더가 있으면 참입니다.",
      src: "function needsPreflight(method, headers) {\n  return method === 'PUT' || method === 'DELETE';\n}",
      sol: "function needsPreflight(method, headers) {\n  const simple = ['GET', 'HEAD', 'POST'].includes(String(method).toUpperCase());\n  const simpleHeaders = ['content-type', 'accept'];\n  const odd = (headers || []).some(h => !simpleHeaders.includes(String(h).toLowerCase()));\n  return !simple || odd;\n}",
      tests: [["needsPreflight('GET', [])", "false"],
              ["needsPreflight('PUT', [])", "true"],
              ["needsPreflight('GET', ['X-Token'])", "true"]],
      edge: [["needsPreflight('POST', ['Content-Type'])", "false"],
             ["needsPreflight('PATCH', [])", "true"]],
      ex: "메서드만 보면 GET 에 인증 헤더를 붙인 요청이 그냥 나가는 것으로 판단합니다. 실제로는 브라우저가 먼저 물어보고, 서버가 그 헤더를 허용하지 않으면 진짜 요청은 아예 안 나가요.",
    },
    {
      k: "allowOrigin · 쿠키를 보낼 때의 규칙",
      qq: "요청 출처·허용 목록·쿠키 사용 여부를 받아 응답 헤더 값을 정하세요. 허용되지 않으면 <code>null</code>, <b>쿠키를 쓰면 출처를 정확히</b>, 아니면 <code>'*'</code> 도 됩니다.",
      src: "function allowOrigin(origin, allowed, withCredentials) {\n  return allowed.includes(origin) ? '*' : null;\n}",
      sol: "function allowOrigin(origin, allowed, withCredentials) {\n  if (!allowed.includes(origin)) return null;\n  return withCredentials ? origin : '*';\n}",
      tests: [["allowOrigin('https://a.com', ['https://a.com'], true)", "'https://a.com'"],
              ["allowOrigin('https://a.com', ['https://a.com'], false)", "'*'"],
              ["allowOrigin('https://b.com', ['https://a.com'], true)", "null"]],
      edge: [["allowOrigin('https://a.com', [], false)", "null"]],
      ex: "쿠키를 보내는 요청에 '*' 로 답하면 브라우저가 응답을 통째로 버립니다. 서버 로그에는 200 이 찍히는데 화면에는 아무것도 안 나와서, 원인을 찾기가 특히 어려워요.",
    },
  ],
},
/* ── 소켓 상태 전이 심화 ──────────────────────────────────── */
{
  unit: "소켓 상태 전이 심화 — TIME_WAIT·CLOSE_WAIT 진단",
  lesson: "직접 짜 보기 — 연결이 끝나는 순서",
  th: {
    sum: "연결을 닫는 것은 한 번에 끝나지 않는다. **양쪽이 각자 닫는다고 알려야** 완전히 끝난다.",
    body: [
      { h: "닫기는 네 번 오간다", t: "한쪽이 '나는 다 보냈다' 고 알리면 상대가 받았다고 답하고, 상대도 다 보내면 다시 알리고 답한다. 그래서 한쪽이 먼저 닫아도 반대 방향은 아직 살아 있을 수 있다." },
      { h: "CLOSE_WAIT 는 내 잘못이다", t: "상대가 닫자고 했는데 내가 `close()` 를 안 부르면 이 상태로 남는다. 이런 소켓이 쌓이면 파일 핸들이 바닥난다. 숫자가 계속 늘고 있다면 코드에서 닫기를 빠뜨린 것이다." },
      { h: "TIME_WAIT 는 정상이다", t: "먼저 닫은 쪽이 잠시 기다리는 상태다. 늦게 도착한 조각이 다음 연결에 섞이지 않도록 하는 안전장치다. 많다고 무조건 문제는 아니고, 짧은 연결을 아주 많이 만들 때 자연스럽게 늘어난다." },
      { h: "많으면 연결을 재사용한다", t: "요청마다 새로 연결하지 않고 이어 쓰면 닫는 일 자체가 줄어든다. 기다림 시간을 억지로 줄이는 것보다, 연결을 덜 만드는 쪽이 대개 옳은 해결이다." },
    ],
    code: { c: "상대가 닫자고 함 → 내가 close() 안 함 → CLOSE_WAIT (내 버그)\n내가 먼저 닫음        → TIME_WAIT (정상, 잠시 뒤 사라짐)", cap: "쌓이는 쪽이 어디인지 본다" },
    key: ["닫기는 양쪽이 각자 한다", "CLOSE_WAIT 는 내 버그", "TIME_WAIT 는 정상"],
  },
  q: [
    {
      k: "diagnose · 쌓이는 상태로 원인 짚기",
      qq: "상태별 소켓 수를 받아 진단을 돌려주세요. <code>CLOSE_WAIT</code>가 100개를 넘으면 <code>'leak'</code>, <code>TIME_WAIT</code>가 10000개를 넘으면 <code>'churn'</code>, 아니면 <code>'ok'</code> 입니다.",
      src: "function diagnose(counts) {\n  return counts.TIME_WAIT > 10000 ? 'churn' : 'ok';\n}",
      sol: "function diagnose(counts) {\n  if ((counts.CLOSE_WAIT || 0) > 100) return 'leak';\n  if ((counts.TIME_WAIT || 0) > 10000) return 'churn';\n  return 'ok';\n}",
      tests: [["diagnose({ CLOSE_WAIT: 500, TIME_WAIT: 10 })", "'leak'"],
              ["diagnose({ CLOSE_WAIT: 1, TIME_WAIT: 20000 })", "'churn'"],
              ["diagnose({ CLOSE_WAIT: 1, TIME_WAIT: 1 })", "'ok'"]],
      edge: [["diagnose({})", "'ok'"],
             ["diagnose({ CLOSE_WAIT: 500, TIME_WAIT: 20000 })", "'leak'"]],
      ex: "TIME_WAIT 만 보면 정상인 상태를 문제로 보고, 정작 내 버그인 CLOSE_WAIT 는 놓칩니다. 쌓이는 쪽이 어디인지가 원인을 가르는 첫 갈림길이에요.",
    },
    {
      k: "nextState · 닫는 순서 따라가기",
      qq: "지금 상태와 일어난 일을 받아 다음 상태를 돌려주세요. <code>ESTABLISHED</code>에서 상대가 닫자고(<code>'recvFin'</code>) 하면 <code>'CLOSE_WAIT'</code>, 내가 닫으면(<code>'close'</code>) <code>'FIN_WAIT'</code> 입니다. <code>CLOSE_WAIT</code>에서 내가 닫으면 <code>'LAST_ACK'</code> 입니다.",
      src: "function nextState(state, event) {\n  return event === 'close' ? 'FIN_WAIT' : state;\n}",
      sol: "function nextState(state, event) {\n  if (state === 'ESTABLISHED' && event === 'recvFin') return 'CLOSE_WAIT';\n  if (state === 'ESTABLISHED' && event === 'close') return 'FIN_WAIT';\n  if (state === 'CLOSE_WAIT' && event === 'close') return 'LAST_ACK';\n  return state;\n}",
      tests: [["nextState('ESTABLISHED', 'recvFin')", "'CLOSE_WAIT'"],
              ["nextState('ESTABLISHED', 'close')", "'FIN_WAIT'"],
              ["nextState('CLOSE_WAIT', 'close')", "'LAST_ACK'"]],
      edge: [["nextState('LAST_ACK', 'close')", "'LAST_ACK'"],
             ["nextState('ESTABLISHED', '아무일')", "'ESTABLISHED'"]],
      ex: "지금 상태를 안 보고 일어난 일만 보면, CLOSE_WAIT 에서 닫았을 때도 FIN_WAIT 로 갑니다. 상태 기계는 '어디에 있었는가' 와 '무슨 일이 있었는가' 둘 다 봐야 해요.",
    },
    {
      k: "connectionsNeeded · 연결을 덜 만들기",
      qq: "초당 요청 수·요청당 걸리는 초·연결 재사용 여부를 받아 <b>필요한 연결 수</b>를 돌려주세요. 재사용하면 <code>ceil(rps * sec)</code>, 안 하면 요청마다 하나입니다.",
      src: "function connectionsNeeded(rps, sec, reuse) {\n  return rps;\n}",
      sol: "function connectionsNeeded(rps, sec, reuse) {\n  return reuse ? Math.ceil(rps * sec) : rps;\n}",
      tests: [["connectionsNeeded(100, 0.05, true)", "5"],
              ["connectionsNeeded(100, 0.05, false)", "100"],
              ["connectionsNeeded(10, 1, true)", "10"]],
      edge: [["connectionsNeeded(0, 1, true)", "0"],
             ["connectionsNeeded(3, 0.1, true)", "1"]],
      ex: "재사용하면 '동시에 진행 중인 요청' 만큼만 연결이 있으면 됩니다. 100건이 아니라 5건이에요. 닫는 일 자체가 줄어드니 TIME_WAIT 도 함께 줄어듭니다.",
    },
  ],
},
/* ── TCP 핸드셰이크·혼잡제어 ──────────────────────────────── */
{
  unit: "TCP 핸드셰이크·혼잡제어",
  lesson: "직접 짜 보기 — 얼마나 빨리 보낼 것인가",
  th: {
    sum: "TCP 는 **얼마나 보내도 되는지 모른 채** 시작한다. 그래서 조금씩 늘려 가며 알아낸다.",
    body: [
      { h: "처음에는 아주 조금", t: "연결을 맺으면 작은 창으로 시작한다. 잘 도착하면 왕복마다 **두 배씩** 늘린다. 짧은 파일은 이 늘어나는 구간에서 다 끝나기 때문에, 첫 창 크기가 체감 속도를 크게 좌우한다." },
      { h: "잃어버리면 확 줄인다", t: "조각이 유실되면 길이 막혔다는 뜻이므로 창을 절반으로 줄인다. 그 뒤로는 두 배가 아니라 조금씩만 늘린다 — 다시 몰아붙이면 또 막히기 때문이다." },
      { h: "왕복 시간이 상한을 정한다", t: "한 번에 보낼 수 있는 양을 왕복 시간으로 나눈 것이 최대 속도다. 거리가 멀면 창을 키우지 않는 한 속도가 오르지 않는다 — 회선을 늘려도 안 빨라지는 이유가 이것이다." },
      { h: "연결을 맺는 데도 왕복이 든다", t: "세 번 오가야 연결이 되고, 암호화까지 하면 왕복이 더 붙는다. 작은 요청을 여러 번 보내면 이 준비 시간이 전체를 차지한다. 연결을 이어 쓰면 그만큼 사라진다." },
    ],
    code: { c: "cwnd = 1 → 2 → 4 → 8 ...      // 잘 가면 두 배\n손실 → cwnd = cwnd / 2         // 막히면 절반\n최대속도 = 창 / 왕복시간", cap: "조금씩 늘려 가며 알아낸다" },
    key: ["처음에는 작게 시작한다", "잃으면 절반으로 줄인다", "왕복 시간이 상한을 정한다"],
  },
  q: [
    {
      k: "cwndAfter · 두 배로 늘리고 절반으로 줄이기",
      qq: "지금 창 크기와 결과를 받아 다음 창을 돌려주세요. <code>'ok'</code>면 두 배, <code>'loss'</code>면 절반(<b>내림, 최소 1</b>)입니다.",
      src: "function cwndAfter(cwnd, result) {\n  return result === 'ok' ? cwnd * 2 : cwnd;\n}",
      sol: "function cwndAfter(cwnd, result) {\n  if (result === 'ok') return cwnd * 2;\n  return Math.max(1, Math.floor(cwnd / 2));\n}",
      tests: [["cwndAfter(4, 'ok')", "8"],
              ["cwndAfter(8, 'loss')", "4"],
              ["cwndAfter(1, 'loss')", "1"]],
      edge: [["cwndAfter(5, 'loss')", "2"],
             ["cwndAfter(1, 'ok')", "2"]],
      ex: "손실이 났는데 창을 그대로 두면 같은 속도로 계속 밀어붙입니다. 막힌 길에 더 부으니 손실이 더 나고, 그러다 모두가 함께 느려져요 — 줄이는 것이 결국 빠른 길입니다.",
    },
    {
      k: "maxThroughput · 왕복 시간이 정하는 상한",
      qq: "창 크기(바이트)와 왕복 시간(ms)을 받아 <b>초당 최대 바이트</b>를 돌려주세요. 왕복 시간이 <b>0이면 0</b> 입니다.",
      src: "function maxThroughput(windowBytes, rttMs) {\n  return windowBytes / rttMs;\n}",
      sol: "function maxThroughput(windowBytes, rttMs) {\n  if (!rttMs) return 0;\n  return windowBytes / (rttMs / 1000);\n}",
      tests: [["maxThroughput(65536, 100)", "655360"],
              ["maxThroughput(65536, 10)", "6553600"],
              ["maxThroughput(65536, 0)", "0"]],
      edge: [["maxThroughput(0, 100)", "0"],
             ["maxThroughput(1000, 1000)", "1000"]],
      ex: "밀리초로 그대로 나누면 단위가 1000배 어긋납니다. 그리고 거리가 멀어 왕복이 길면 창을 키우지 않는 한 속도가 안 올라요 — 회선만 늘려도 안 빨라지는 이유입니다.",
    },
    {
      k: "setupRtt · 준비에 드는 왕복 세기",
      qq: "TLS 사용 여부와 <b>연결 재사용</b> 여부를 받아 <b>준비에 드는 왕복 횟수</b>를 돌려주세요. 재사용하면 0, 아니면 TCP 1회에 TLS 를 쓰면 2회를 더합니다.",
      src: "function setupRtt(tls, reuse) {\n  return tls ? 3 : 1;\n}",
      sol: "function setupRtt(tls, reuse) {\n  if (reuse) return 0;\n  return tls ? 3 : 1;\n}",
      tests: [["setupRtt(true, false)", "3"],
              ["setupRtt(false, false)", "1"],
              ["setupRtt(true, true)", "0"]],
      edge: [["setupRtt(false, true)", "0"]],
      ex: "작은 요청을 여러 번 보내면 이 준비 시간이 전체의 대부분이 됩니다. 연결을 이어 쓰면 그게 통째로 사라져요 — 코드 한 줄로 체감 속도가 크게 달라지는 자리입니다.",
    },
  ],
},
/* ── DNS·로드밸런싱·CDN ───────────────────────────────────── */
{
  unit: "DNS·로드밸런싱·CDN",
  lesson: "직접 짜 보기 — 어디로 보낼지 정하기",
  th: {
    sum: "이름을 주소로 바꾸고(DNS), 여러 서버 중 하나를 고르고(LB), 가까운 사본에서 준다(CDN).",
    body: [
      { h: "이름은 여러 곳에 캐시된다", t: "DNS 응답에는 '얼마나 오래 써도 되는지(TTL)' 가 붙어 있고, 그동안 여러 곳이 그 답을 들고 있는다. 그래서 주소를 바꿔도 즉시 반영되지 않는다 — 바꾸기 전에 TTL 을 줄여 두는 것이 관례다." },
      { h: "이름 하나에 주소 여러 개", t: "여러 주소를 돌려주면 클라이언트가 그중 하나를 쓴다. 간단하지만 죽은 서버를 빼는 데 시간이 걸린다 — 캐시가 남아 있는 동안은 계속 그리로 간다." },
      { h: "붙은 자리를 유지할지 정한다", t: "같은 사용자를 늘 같은 서버로 보내면 서버가 들고 있는 상태를 쓸 수 있다. 대신 그 서버가 죽으면 그 사용자들만 크게 다친다. 상태를 밖에 두면 아무 서버나 써도 된다." },
      { h: "가까운 곳에서 주면 확실히 빠르다", t: "거리 자체가 줄어드니 다른 최적화보다 효과가 확실하다. 대신 원본이 바뀌었을 때 언제 새로 받아 갈지를 정해 둬야 한다 — 안 정하면 옛것이 오래 남는다." },
    ],
    code: { c: "TTL 60   → 바꾸기 전에 미리 줄여 둔다\nsticky   → 같은 사용자 같은 서버 (죽으면 그 사용자만 크게 다침)", cap: "고르는 규칙과 남는 시간" },
    key: ["DNS 답은 여러 곳에 캐시된다", "죽은 서버는 캐시가 만료돼야 빠진다", "상태를 밖에 두면 아무 서버나"],
  },
  q: [
    {
      k: "dnsCache · 언제까지 그 답을 쓰는가",
      qq: "응답 받은 시각·TTL(초)·지금 시각을 받아 <b>캐시된 답을 그대로 써도 되는지</b> 판단하세요. 정확히 만료된 순간은 안 됩니다.",
      src: "function dnsCache(gotAt, ttl, now) {\n  return now - gotAt <= ttl;\n}",
      sol: "function dnsCache(gotAt, ttl, now) {\n  return now - gotAt < ttl;\n}",
      tests: [["dnsCache(0, 60, 30)", "true"],
              ["dnsCache(0, 60, 60)", "false"],
              ["dnsCache(0, 60, 61)", "false"]],
      edge: [["dnsCache(0, 0, 0)", "false"],
             ["dnsCache(100, 60, 100)", "true"]],
      ex: "TTL 이 지났는데도 계속 쓰면, 옮긴 서버로 트래픽이 안 갑니다. 반대로 TTL 을 안 지키고 매번 물어보면 이름 서버가 요청을 다 받아 내야 해요.",
    },
    {
      k: "pickTarget · 붙은 자리를 지킬 것인가",
      qq: "서버 목록·사용자 번호·고정 여부를 받아 보낼 서버 이름을 돌려주세요. 고정이면 <code>사용자번호 % 서버수</code>, 아니면 <code>요청번호 % 서버수</code> 입니다. <b>살아 있는 서버 중에서만</b> 고릅니다.",
      src: "function pickTarget(servers, userId, reqNo, sticky) {\n  const i = sticky ? userId % servers.length : reqNo % servers.length;\n  return servers[i].name;\n}",
      sol: "function pickTarget(servers, userId, reqNo, sticky) {\n  const up = servers.filter(s => s.healthy);\n  if (!up.length) return null;\n  const i = (sticky ? userId : reqNo) % up.length;\n  return up[i].name;\n}",
      tests: [["pickTarget([{ name: 'a', healthy: true }, { name: 'b', healthy: false }], 1, 0, true)", "'a'"],
              ["pickTarget([{ name: 'a', healthy: true }, { name: 'b', healthy: true }], 1, 0, true)", "'b'"],
              ["pickTarget([{ name: 'a', healthy: false }], 0, 0, false)", "null"]],
      edge: [["pickTarget([{ name: 'a', healthy: true }], 7, 3, true)", "'a'"],
             ["pickTarget([], 1, 1, true)", "null"]],
      ex: "죽은 서버를 후보에 두면 그 자리에 배정된 사용자들이 통째로 실패합니다. 고정 배정이면 특정 사용자만 계속 안 되는 상황이 되어, '나만 안 돼요' 라는 문의로 들어와요.",
    },
    {
      k: "cdnHitRate · 가까운 곳에서 준 비율",
      qq: "가까운 곳에서 준 횟수와 원본까지 간 횟수를 받아 <b>적중률</b>을 돌려주세요. 요청이 <b>하나도 없으면 0</b> 입니다.",
      src: "function cdnHitRate(hits, misses) {\n  return hits / (hits + misses);\n}",
      sol: "function cdnHitRate(hits, misses) {\n  const total = hits + misses;\n  return total > 0 ? hits / total : 0;\n}",
      tests: [["cdnHitRate(90, 10)", "0.9"],
              ["cdnHitRate(0, 0)", "0"],
              ["cdnHitRate(0, 5)", "0"]],
      edge: [["cdnHitRate(5, 0)", "1"]],
      ex: "요청이 없을 때 나누면 NaN 이 나오고, 그 값은 어떤 비교에서도 거짓이라 경보가 조용히 안 울립니다. 새벽처럼 조용한 시간대에 딱 이 상태가 돼요.",
    },
  ],
},
];
