/* java — 정답률 15% 아래 끝맺음('컴파일 오류가 난다' 등)의 오답 48개를 구체적인 틀린 답으로 (72차) */
module.exports = { track: "java", fixes: [
  { k: "무한 반복", from: "컴파일 오류가 난다", to: "i 를 선언하기 전에 써서 컴파일러가 거부한다" },
  { k: "단독 return", from: "반환값이 없는데 return 을 써서", to: "반환값이 없는 return 은 허용되지 않아 컴파일러가 거부한다" },
  { k: "java-gen-covariant-array", from: "컴파일 에러가 발생한다", to: "Object[] 에 Integer 를 대입하는 줄에서 타입 불일치로 빌드가 멈춘다" },
  { k: "java-st-reuse", from: "컴파일 에러가 발생한다", to: "이미 닫힌 스트림 변수를 다시 쓰는 것을 컴파일러가 잡아내 빌드가 실패한다" },
  { k: "java-st-parallel-state", from: "자동으로 동기화되어 문제가 없다", to: "병렬 스트림이 add 호출을 알아서 동기화해 주어 결과가 정확히 나온다" },
  { k: "java-st-parallel-state", from: "스레드 안전성은 걱정하지 않아도 된다", to: "순서만 뒤바뀔 뿐 결과 자체는 정확하므로 ArrayList 를 그대로 써도 되고, 스레드 안전성은 순서 문제일 뿐이다" },
  { k: "java-st-parallel-state", from: "컴파일 에러가 발생한다", to: "람다 안에서 바깥 리스트를 건드리는 것은 effectively final 규칙에 걸려 컴파일되지 않는다" },
  { k: "java2-sealed-modifier", from: "아무 수식자도 필요 없다", to: "public 만 붙이면 되고 나머지 수식자는 선택이다" },
  { k: "java2-pat-instanceof", from: "범위 밖이라 오류가 난다", to: "&amp;&amp; 오른쪽에서는 아직 s 를 쓸 수 없어 범위 밖 변수라는 컴파일 오류로 빌드가 멈춘다" },
  { k: "java2-opt-ofnull", from: "컴파일 오류가 난다", to: "null 리터럴은 인자로 받지 않도록 선언돼 있어 컴파일러가 거부한다" },
  { k: "java2-opt-orelse-eager", from: "컴파일 오류가 난다", to: "orElse 에 메서드 호출식을 넘길 수 없어 컴파일 단계에서 걸린다" },
  { k: "java2-opt-param", from: "파라미터에 제네릭 타입을 쓸 수 없기 때문이다", to: "파라미터 자리의 Optional 은 제네릭 정보가 지워져 호출자가 넘길 타입을 알 수 없게 만들기 때문이다" },
  { k: "java2-null-unbox", from: "컴파일 오류가 난다", to: "Integer 를 int 에 대입하는 것은 명시적 캐스팅 없이는 허용되지 않아 컴파일이 실패한다" },
  { k: "java2-null-emptycoll", from: "원소 타입을 알 수 없게 된다", to: "null 은 타입이 없으므로 제네릭 타입 정보가 소거되어 호출부에서 원소 타입을 잃어버린다" },
  { k: "java2-time-parseerr", from: "컴파일 오류가 난다", to: "패턴 불일치는 컴파일 시점에 검사되므로 그 줄에서 빌드가 실패한다" },
  { k: "java2-time-store", from: "변환이 필요 없다", to: "사용자 지역의 LocalDateTime 을 그대로 저장한다 — 화면에 보이는 시각과 같아 변환 없이 바로 읽힌다" },
  { k: "java2-time-store", from: "로그처럼 바로 읽을 수 있기 때문이다", to: "사람이 읽기 쉬운 문자열로 저장한다 — 어느 시각인지 로그처럼 눈으로 바로 확인된다" },
  { k: "java2-time-store", from: "타임존 문제가 없다", to: "밀리초 값을 int 컬럼에 저장한다 — 숫자라 정렬과 비교가 빠르고 타임존을 신경 쓸 일이 사라진다" },
  { k: "java2-io-lines-leak", from: "자동으로 닫히므로 문제가 없다", to: "종단 연산이 끝나는 순간 스트림이 파일을 스스로 닫아 준다" },
  { k: "java2-io-lines-leak", from: "컴파일 오류가 난다", to: "AutoCloseable 자원을 try 밖에서 쓰는 것을 컴파일러가 막아 빌드가 실패한다" },
  { k: "java2-test-throws-usage", from: "두 번째 줄에서 컴파일 오류가 난다", to: "assertThrows 는 boolean 을 반환하므로 두 번째 줄의 getMessage() 호출이 컴파일되지 않는다" },
  { k: "java2-test-assertall", from: "순서 의존성을 드러내 주기 때문", to: "단언 실행 순서를 무작위로 섞어 순서 의존성을 드러내기 위해서" },
  { k: "java2-test-staticstate", from: "컴파일 오류가 난다", to: "테스트 클래스의 static 필드는 JUnit 규칙상 금지되어 컴파일러가 거부한다" },
  { k: "java2-build-nosuchmethod", from: "부르는 순간 이 오류가 난다", to: "JVM 힙이 부족해 클래스를 끝까지 로딩하지 못했고, 로딩되지 않은 메서드를 부르는 순간 이 오류로 이어진다" },
  { k: "java2-build-shade", from: "패키지 이름을 바꿀 필요가 없다", to: "두 jar 를 그냥 클래스패스에 함께 넣으면 JVM 이 알아서 구분해 준다. 패키지 이름은 그대로 두어도 된다" },
  { k: "java3-poly-ctor", from: "언어가 금지하므로 컴파일 에러가 발생한다", to: "생성자에서 재정의 가능한 메서드를 부르는 것은 언어가 금지하므로 컴파일러가 그 호출을 거부한다" },
  { k: "java3-imm-final-mean", from: "필드에 null을 넣을 수 없게 된다", to: "필드에 null 을 대입하는 것이 금지된다" },
  { k: "java3-def-ctor", from: "컴파일 에러가 발생한다", to: "생성자 인자를 복사 없이 필드에 넣는 것은 컴파일러가 거부한다" },
  { k: "java3-enum-emap-vs-hash", from: "따로 상수로 만들지 않아도 된다", to: "EnumMap 은 null 키를 허용해 더 유연하다 — '값 없음' 을 뜻하는 항목을 따로 상수로 두지 않고 null 로 표현한다" },
  { k: "java-hm-contract", from: "컴파일 에러가 발생한다", to: "equals 만 재정의한 클래스는 키로 쓸 수 없다는 컴파일 오류로 빌드가 멈춘다" },
  { k: "equals/hashCode", from: "그 필드를 바꿔도 조회에 문제가 없다", to: "가변 필드를 hashCode 계산에 쓰고 HashMap 키로 넣은 뒤 그 필드를 바꿔도 같은 키로 조회된다" },
  { k: "ZGC", from: "서버에서는 쓰지 않는다", to: "single-threaded 컬렉터라 코어를 하나만 쓰므로 소규모 힙과 임베디드 환경에 맞고 서버용으로는 만들지 않았다" },
  { k: "ThreadLocal 누수", from: "별도 정리 코드가 필요 없다", to: "스레드가 종료되면 즉시 모든 ThreadLocal 값이 자동으로 회수되므로 스레드 풀에서도 안전하며, remove() 를 따로 호출하지 않아도 값이 남지 않는다. 그래서 별도 정리 코드는 군더더기일 뿐이다" },
  { k: "java-cc-chm-lock", from: "읽는 일이 없기 때문이다", to: "읽기에도 배타적 락을 건다 — 그래야 다른 스레드가 쓰는 도중의 값을 읽는 일을 막을 수 있어서다" },
  { k: "java-jvm-suppressed", from: "끝내 확인할 수 없게 된다", to: "close 에서 난 예외가 던져지고 본문 예외는 그대로 사라져 호출자는 원래 원인을 끝내 알지 못한다" },
  { k: "java2-str-substring", from: "오버로드를 찾지 못해 컴파일 오류가 난다", to: "인덱스가 int 리터럴이라 substring(int, int) 오버로드를 찾지 못해 컴파일이 실패한다" },
  { k: "java2-str-loopconcat", from: "성능 문제가 생기지 않는다", to: "컴파일러가 자동으로 StringBuilder 하나로 합쳐 주므로 성능은 직접 쓴 것과 같다" },
  { k: "java2-str-tb-backslash", from: "컴파일 오류가 난다", to: "텍스트 블록 안의 역슬래시는 허용되지 않아 컴파일러가 거부한다" },
  { k: "java2-fn-specific", from: "컴파일 오류가 난다", to: "두 default 가 충돌한다는 컴파일 오류로 빌드가 실패한다" },
  { k: "java2-fn-classwins", from: "항상 컴파일 오류가 난다", to: "충돌로 판정되어 컴파일러가 클래스 선언을 거부한다" },
  { k: "java2-fn-objectmethod", from: "허용되지 않아 컴파일 오류가 난다", to: "인터페이스에서 Object 의 메서드를 다시 선언하는 것은 허용되지 않아 컴파일러가 거부한다" },
  { k: "java3-hc-constant", from: "컴파일 에러가 발생한다", to: "상수를 돌려주는 hashCode 는 계약 위반으로 컴파일러가 거부한다" },
  { k: "java3-hc-missing", from: "put 줄에서 컴파일 에러가 발생한다", to: "hashCode 없이 equals 만 재정의한 클래스는 키로 쓸 수 없어 put 줄에서 컴파일이 실패한다" },
  { k: "java3-annot-retention", from: "신경 쓸 필요가 없다", to: "@Target(ElementType.METHOD) 만 붙여 두면 충분하며 보존 정책은 기본값이 이미 RUNTIME 이라 그대로 읽힌다" },
  { k: "java3-ser-uid", from: "컴파일 에러가 발생한다", to: "serialVersionUID 가 없는 Serializable 클래스는 컴파일러가 거부한다" },
  { k: "java3-ser-defense", from: "화이트리스트 설정은 필요 없다", to: "readObject 메서드를 삭제해 두면 공격을 완전히 막을 수 있다. 메서드가 없으면 실행될 코드도 없어진다. 화이트리스트 설정은 그 다음 문제다" },
  { k: "java3-json-null", from: "둘은 같은 의미이므로 구분할 필요가 없다", to: "둘은 같은 의미이므로 파서가 하나로 합쳐서 넘겨준다" },
  { k: "java3-json-longid", from: "그보다 큰 값은 파싱 오류가 난다", to: "long 은 JSON 으로 표현할 수 없다 — JSON 숫자는 32비트까지만 규정되어 있어 그보다 큰 값은 파서가 거부한다" },
  { k: "java3-json-longid", from: "규격이 막아 주므로 걱정할 필요가 없다", to: "JSON 숫자는 규격상 임의 정밀도라 어떤 값도 안전하다 — 정밀도 손실은 소비자가 아니라 규격이 막아 주므로 문자열로 바꿀 이유가 사라진다" },
  { k: "java3-json-dto", from: "둘이 어긋날 일이 없기 때문이다", to: "엔티티를 그대로 쓰면 API 가 더 안정적이 된다 — 저장 구조와 응답이 같으니 둘이 어긋날 일이 사라져서다" },
  { k: "java3-ver-enum", from: "값이 늘어도 아무 문제가 없다", to: "구버전 소비자도 새 값을 자동으로 이해한다 — enum 은 이름 문자열로 그대로 전달되므로 값이 늘어도 그대로 읽힌다" },
  { k: "java3-perf-capacity", from: "지정해도 의미가 없다. 지정할 필요가 없다", to: "ArrayList 는 내부 배열 크기를 스스로 늘리지 않으므로 초기 용량을 지정해도 그 값은 그대로 무시된다" },
  { k: "java3-perf-treemap", from: "범위 조회 용도로는 쓰지 않는다", to: "TreeMap 은 해시 충돌이 많을 때만 쓰는 대체품이며, 정렬이나 범위 조회 용도로는 만들어지지 않았다" },
  { k: "java3-perf-boxing", from: "+= 연산자를 쓸 수 없어 컴파일 에러가 발생한다", to: "Long 변수에는 += 연산자를 쓸 수 없어 그 줄에서 컴파일이 실패한다" }
] };
