/* cpp — 정답률 15% 아래 끝맺음의 오답 42개를 구체적인 틀린 답으로 (72차) */
module.exports = { track: "cpp", fixes: [
  { k: "전달 방식 선택", from: "어디서나 접근할 수 있기 때문이다", to: "전역 변수를 만들어 사용한다. 어디서나 접근할 수 있어 복사가 사라져서다" },
  { k: "다형성", from: "이름이 같으면 구분할 수 없기 때문이다", to: "함수 이름을 바꿔야만 동작한다. 이름이 같으면 컴파일러가 둘을 구분하지 못해서다" },
  { k: "cpp-sptr-double", from: "컴파일 에러가 발생한다", to: "같은 포인터를 두 번 감싸는 것을 컴파일러가 잡아내 빌드가 멈춘다" },
  { k: "cpp-sptr-cycle", from: "컴파일 에러가 발생한다", to: "서로를 가리키는 shared_ptr 선언은 순환 참조로 판정되어 컴파일되지 않는다" },
  { k: "cpp-sptr-makeshared", from: "오래 남는 문제가 생기지 않는다", to: "weak_ptr 을 만들 수 없게 막아 주므로 제어 블록이 객체보다 오래 남는 문제를 원천에서 끊는다" },
  { k: "cpp-move-const", from: "컴파일 에러가 발생한다", to: "const 객체에 std::move 를 적용하는 것은 금지되어 컴파일러가 거부한다" },
  { k: "cpp-move-selfassign", from: "대입 결과를 쓰지 않기 때문이다", to: "반환 타입을 void 로 만드는 것이다. 대입 결과를 이어서 쓸 일이 없어서다" },
  { k: "cpp-erase-remove", from: "컴파일 에러가 발생한다", to: "반환값을 받지 않은 remove 호출은 컴파일러가 오류로 잡는다" },
  { k: "cpp-erase-rangefor", from: "컴파일 에러가 발생한다", to: "범위 기반 for 안의 push_back 은 언어가 금지해 컴파일러가 거부한다" },
  { k: "cpp-vf-nonvirtual", from: "컴파일 에러가 발생한다", to: "가상이 아닌 함수를 기반 포인터로 부르는 것은 컴파일러가 막는다" },
  { k: "cpp-vf-ctor", from: "컴파일 에러가 발생한다", to: "생성자 안의 가상 함수 호출은 문법 오류로 컴파일되지 않는다" },
  { k: "cpp-vf-defaultarg", from: "컴파일 에러가 발생한다", to: "기반과 다른 기본 인자는 재정의 규칙 위반으로 컴파일러가 거부한다" },
  { k: "cpp-vf-vdtor", from: "컴파일 에러가 발생한다", to: "가상 소멸자가 없는 기반 클래스를 상속하는 것은 컴파일러가 막는다" },
  { k: "cpp-vf-vdtor", from: "아무 문제가 없다", to: "Base 포인터로 delete 해도 두 소멸자가 모두 정상 호출된다" },
  { k: "cpp-vf-slicing-param", from: "복사가 일어나지 않기 때문이다", to: "Base 값으로 받되 const 를 붙여 준다. const 가 붙으면 복사가 생략되어서다" },
  { k: "cpp-vf-dtor-virtualcall", from: "표가 아직 남아 있기 때문이다", to: "파생 클래스 쪽 버전이 호출된다. 소멸자 안에서도 가상 함수 표가 그대로 남아 있어서다" },
  { k: "cpp-vf-dtor-virtualcall", from: "컴파일 에러가 발생한다", to: "소멸자 안의 가상 함수 호출은 컴파일러가 오류로 잡는다" },
  { k: "cpp-vf-constmismatch", from: "허용되지 않아 컴파일 에러가 발생한다", to: "기반과 이름은 같은데 시그니처가 다른 가상 함수는 허용되지 않아 컴파일러가 거부한다" },
  { k: "cpp-vf-hiding", from: "컴파일 에러가 발생한다", to: "기반의 오버로드와 이름이 겹친다는 모호성 오류로 컴파일되지 않는다" },
  { k: "cpp-const-overload", from: "컴파일 에러가 발생한다", to: "const 만 다른 두 함수는 같은 시그니처로 취급되어 재정의 오류로 컴파일이 실패한다" },
  { k: "cpp-const-constexpr", from: "컴파일 타임 계산과는 관계가 없기 때문이다", to: "constexpr 는 런타임 상수만 뜻한다. 컴파일 타임 계산은 매크로가 맡아서다" },
  { k: "cpp2-alg-stable", from: "추가 메모리를 전혀 쓰지 않는다", to: "stable_sort는 추가 메모리 없이 제자리에서 정렬한다" },
  { k: "cpp2-op-plus-nonmember", from: "클래스 내부 필드를 직접 더해 쓸 수 있기 때문이다", to: "비멤버 함수만 private 멤버에 접근할 수 있어서 클래스 내부 필드를 직접 더해 쓸 수 있어서다" },
  { k: "cpp2-exc-vector-move", from: "컴파일 에러가 발생한다", to: "noexcept 없는 이동 생성자를 가진 타입은 vector 원소가 될 수 없어 컴파일되지 않는다" },
  { k: "cpp2-exc-two-alloc", from: "두 번 해제되는 문제가 생길 수 있기 때문이다", to: "process가 인자를 값으로 받아 shared_ptr 복사가 두 번 일어나고, 그 과정에서 참조 계수가 어긋나 같은 객체가 두 번 해제될 수 있어서다" },
  { k: "cpp2-exc-noexcept-where", from: "예외를 막아 주기 때문", to: "생성자 전부 — 생성 도중의 예외를 없애 주어서" },
  { k: "cpp2-exc-raii-scope", from: "예외 안전성을 따로 고민할 필요가 없다", to: "컴파일러가 함수 끝마다 자원 해제 코드를 자동으로 삽입해 주기 때문에 잊어버릴 수 없다. 그래서 소멸자만 제대로 써 두면 예외 안전성은 저절로 따라온다" },
  { k: "cpp2-exc-raii-scope", from: "try/catch 블록의 실행 속도를 높여 주기 때문", to: "try/catch 블록의 실행 속도를 높여 주어서" },
  { k: "cpp2-exc-raii-scope", from: "예외를 발생하지 않게 막아 주기 때문", to: "예외가 처음부터 발생하지 않도록 막아 주어서" },
  { k: "cpp2-sv-temp-dangle", from: "sv가 복사본을 만들므로 문제가 없다", to: "sv가 문자열의 복사본을 들고 있어 원본이 사라져도 그대로 읽힌다" },
  { k: "cpp2-mod-init-if", from: "예외를 자동으로 잡아 주기 때문", to: "find 가 던지는 예외를 자동으로 잡아 주어서" },
  { k: "cpp2-mod-auto-when", from: "타입 안전성을 해치므로 절대 쓰지 않는다", to: "auto는 타입 안전성을 해치므로 코딩 규칙으로 금지한다" },
  { k: "cpp2-mod-constexpr-func", from: "상수 인자만 받을 수 있기 때문이다", to: "컴파일 에러가 난다 — constexpr 함수는 컴파일 타임에 값이 확정된 상수 인자만 받도록 정해져 있어서다" },
  { k: "cpp2-tpl-sfinae-mean", from: "즉시 컴파일 에러가 발생한다", to: "치환 실패 지점에서 즉시 하드 에러로 컴파일이 멈춘다" },
  { k: "cpp2-cc-thread-exception", from: "자동으로 정리되므로 문제가 없다", to: "예외가 나면 스레드 객체가 자동으로 detach 되어 정리된다" },
  { k: "cpp2-cc-cv-predicate", from: "그 예외를 걸러 낼 수 있기 때문이다", to: "notify_one이 여러 번 호출되면 대기 큐가 꼬여 예외가 발생할 수 있으므로, 루프로 감싸 두면 그 예외를 걸러 낼 수 있어서다" },
  { k: "cpp2-cc-cv-predicate", from: "뮤텍스를 자동으로 풀어 주기 때문", to: "술어 버전만 뮤텍스를 자동으로 풀어 주어서" },
  { k: "cpp2-cc-memory-order", from: "순서를 걱정할 필요가 없다", to: "모든 atomic 연산은 어떤 memory_order를 쓰든 전역적인 실행 순서가 완전히 보장되므로 순서 지정은 형식일 뿐이다" },
  { k: "cpp2-bld-static-linkage", from: "counter를 수정할 수 없게 된다", to: "counter가 읽기 전용 상수로 취급된다" },
  { k: "cpp2-bld-header-cost", from: "전혀 참조할 수 없게 된다", to: "B.h 안에 정의된 심볼들이 최종 링크 과정에서 제외되어 A.h를 쓰는 쪽에서는 참조하지 못하게 된다" },
  { k: "cpp3-static-downcast-ub", from: "컴파일 에러가 발생한다", to: "static_cast 는 다형 타입에 쓸 수 없어 컴파일러가 거부한다" },
  { k: "cpp3-mutable", from: "const를 제거하는 것 외에는 방법이 없다", to: "멤버 함수의 const를 제거하는 것이 유일한 길이다" },
  { k: "cpp3-virtual-base-cost", from: "만들어 둘 수 없게 된다", to: "가상 상속을 쓰면 힙 할당이 강제되므로 스택 위에는 그런 객체를 두지 못한다" },
  { k: "cpp3-return-local", from: "실행에는 문제가 없다", to: "정수 하나를 반환하기에는 비효율적일 뿐 정확성 자체에는 문제가 없다. 반환된 값 자체는 정상적으로 전달되므로 실행은 그대로 이어진다" },
  { k: "cpp3-ifstream-check", from: "errno를 직접 읽는 것 외에는 방법이 없다", to: "errno를 직접 읽는 것이 유일한 확인 수단이다" },
  { k: "cpp3-binary-mode", from: "파일 크기를 줄여 주기 때문", to: "파일 크기를 줄여 주어서" },
  { k: "cpp3-build-flags", from: "코드에 집중할 수 있기 때문이다", to: "최적화를 완전히 끄고(-O0) 컴파일한 뒤 경고는 모두 무시하고 넘어간다. 경고를 보지 않아야 코드에 집중할 수 있어서다" }
] };
