/* go — 정답률 15% 아래 끝맺음의 오답 22개를 구체적인 틀린 답으로 (72차) */
module.exports = { track: "go", fixes: [
  { k: "재할당 이유", from: "append 는 아무것도 반환하지 않기 때문이다", to: "append 가 반환값 없이 원본만 고쳐서" },
  { k: "go-if-embed", from: "Read 메서드를 따로 쓰지 않아도 된다", to: "Reader 의 구현을 상속받아 Read 메서드가 자동으로 채워진다" },
  { k: "go-if-nil-fix", from: "인터페이스를 쓰지 않는다", to: "반환 타입을 *MyErr로 바꿔 error 인터페이스를 거치지 않게 한다" },
  { k: "go-if-nil-call", from: "컴파일 에러가 발생한다", to: "nil 리시버 호출 가능성을 컴파일러가 잡아내 빌드가 멈춘다" },
  { k: "go-if-assert", from: "컴파일 에러가 발생한다", to: "단언 실패 가능성이 있는 코드는 컴파일러가 거부한다" },
  { k: "go2-si-01", from: "정렬을 따로 할 필요가 없다", to: "Builder 는 결과를 자동으로 정렬해 주기 때문 — WriteString 으로 넣은 조각을 사전순으로 배치해 돌려주므로 정렬 단계가 사라진다" },
  { k: "go3-slog-badkey", from: "컴파일 에러가 발생한다", to: "인자 개수가 홀수라는 이유로 컴파일러가 호출을 거부한다" },
  { k: "go3-flag-parse-order", from: "검사되므로 컴파일 에러가 발생한다", to: "플래그 정의는 Parse 앞에만 올 수 있도록 검사되므로 빌드가 실패한다" },
  { k: "go-sl-pass", from: "컴파일 에러가 발생한다", to: "슬라이스를 값으로 넘기는 함수 호출은 컴파일되지 않는다" },
  { k: "go-sl-nil", from: "구별할 방법이 없다", to: "[]int{} 와 완전히 동일한 값이라 s == nil 비교는 거짓이 되고 둘은 구별되지 않는다" },
  { k: "go-sl-range-copy", from: "대입하면 컴파일 오류가 난다", to: "v 가 상수로 선언되기 때문 — range 가 만드는 두 번째 변수는 const 라 대입하면 컴파일러가 거부한다" },
  { k: "go-cc-timeout", from: "별도 select 는 필요 없다", to: "ch.SetTimeout(d) 를 호출해 둔다. 채널에 타임아웃 설정이 있어 select 없이 끝난다" },
  { k: "go-cc-select-random", from: "컴파일 에러가 발생한다", to: "동시에 준비될 수 있는 케이스 조합은 컴파일러가 거부한다" },
  { k: "go-cc-nil-chan", from: "컴파일 에러가 발생한다", to: "nil 채널 연산은 정적으로 잡혀 빌드가 멈춘다" },
  { k: "go-cc-mutex-copy", from: "컴파일 에러가 발생한다", to: "Mutex 를 품은 구조체의 복사는 컴파일러가 거부한다" },
  { k: "go-panic-goroutine", from: "고루틴마다 recover 를 둘 필요가 없다", to: "가능하다 — main 고루틴이 언제나 잡아 준다. 고루틴마다 recover 를 두는 것은 중복이다" },
  { k: "go-err-customtype", from: "타입을 새로 정의할 필요가 없다", to: "에러 메시지 문자열에 담고 호출자가 파싱하게 한다 — 문자열 파싱이 가장 간단하고 타입 정의는 생략된다" },
  { k: "go-err-customtype", from: "반환값을 바꾸지 않아도 된다", to: "전역 변수에 마지막 에러 정보를 저장한다 — errno 처럼 호출 직후 전역을 읽으면 되므로 반환값은 그대로 둔다" },
  { k: "go-test-table", from: "for 문을 직접 쓰지 않아도 된다", to: "반복문을 대신하기 위해 — t.Run 이 테이블을 받아 케이스마다 함수를 불러 주므로 for 문이 사라진다" },
  { k: "go2-mw-06", from: "별도 처리가 필요 없다", to: "요청 고루틴에서 복구되고 클라이언트에는 자동으로 500이 전송되므로 핸들러 쪽 코드는 그대로 두면 된다" },
  { k: "go3-rows-close", from: "순서만 지키면 문제가 없다", to: "같은 db 에서 다음 Query 를 부르면 이전 rows 가 자동으로 닫히므로 순서만 지키면 커넥션은 회수된다" },
  { k: "go3-rows-close", from: "기능적으로는 문제가 없다", to: "결과 버퍼가 GC 될 때까지 남아 메모리 사용량만 조금 늘어날 뿐 커넥션은 곧바로 반납된다" }
] };
