/* react — 정답률 15% 아래 끝맺음의 오답 31개를 구체적인 틀린 답으로 (72차) */
module.exports = { track: "react", fixes: [
  { k: "react2-ctx-scope", from: "앱당 하나만 사용할 수 있기 때문이다", to: "Provider는 앱당 하나만 둘 수 있어 위치를 골라야 해서다" },
  { k: "react2-ctx-di", from: "트리 구조를 알고 있기 때문이다", to: "의존성 그래프를 분석해 순환 참조를 막아 준다. 트리 구조를 알고 있어서다" },
  { k: "react2-ref-init", from: "첫 렌더에서만 실행되므로 아무 문제가 없다", to: "첫 렌더에서만 실행되므로 인스턴스는 하나만 만들어진다" },
  { k: "react2-ref-scroll", from: "JavaScript 는 쓰지 않는다", to: "CSS 의 flex-direction: column-reverse 만으로 처리하고 JavaScript 는 손대지 않는다" },
  { k: "react2-rt-redirect", from: "주소가 덮어써지지 않기 때문이다", to: "쿼리 파라미터를 그대로 유지하기 위해서다. 주소가 덮어써지지 않아서다" },
  { k: "react3-prop-3", from: "두 동작이 하나로 묶여 있기 때문이다", to: "preventDefault 가 함께 무효가 된다. 두 동작이 하나로 묶여 있는 탓이다" },
  { k: "react3-deb-6", from: "노출 범위를 정할 수 있기 때문이다", to: "useImperativeHandle 을 사용한다. 노출 범위를 정할 수 있어서다" },
  { k: "react3-st-1", from: "파일이 분리되어 있기 때문이다", to: "JavaScript 에서 값을 읽어 올 수 없다는 점이다. 파일이 분리되어 있는 탓이다" },
  { k: "react3-dyn-5", from: "서버가 스타일을 보내지 않기 때문이다", to: "CSS 가 영원히 적용되지 않는다. 서버가 스타일을 보내지 않는 탓이다" },
  { k: "react2-test-snapshot", from: "렌더가 끝나지 않기 때문이다", to: "스냅샷은 비동기 컴포넌트에는 적용할 수 없다. 렌더가 끝나지 않는 까닭이다" },
  { k: "의존성 누락", from: "런타임 에러가 발생한다", to: "query 가 의존성에 없다는 런타임 오류로 렌더가 중단된다" },
  { k: "rx-ctx-notstore", from: "Context는 객체를 담을 수 없기 때문이다", to: "Context는 원시값만 담을 수 있고 객체는 담지 못하는 탓이다" },
  { k: "rx-upd-functional", from: "순서가 보장되지 않기 때문이다", to: "예측할 수 없다 — 실행할 때마다 결과가 달라진다. 호출 순서가 보장되지 않는 탓이다" },
  { k: "rx-memo-always", from: "훅을 사용하는 컴포넌트에는 적용할 수 없기 때문이다", to: "memo는 훅을 사용하는 컴포넌트에는 적용되지 않는 탓이다" },
  { k: "rx-fetch-cleanup", from: "다시 실행될 일이 없기 때문이다", to: "의존성 배열이 비어 있을 때는 호출되지 않는다. 다시 실행될 일이 없는 까닭이다" },
  { k: "rx-fetch-race", from: "자동으로 취소되므로 문제가 없다", to: "id가 바뀌면 이전 fetch가 자동으로 취소되어 늦은 응답은 버려진다" },
  { k: "rx-fetch-waterfall", from: "자동 병렬화하므로 문제가 없다", to: "React는 요청을 자동 병렬화하므로 총 대기 시간은 가장 느린 요청 하나와 같다" },
  { k: "rx-form-readonly", from: "input에는 value 속성이 없기 때문이다", to: "input에는 value 속성이 없어서 React 가 모르는 속성으로 취급하는 탓이다" },
  { k: "rx-form-reset", from: "자동으로 초기화하므로 코드가 필요 없다", to: "React가 제출 후 자동으로 초기화하므로 코드는 비워 두면 된다" },
  { k: "rx-hook-share", from: "훅 규칙 위반 오류가 난다", to: "두 번째 호출에서 훅 규칙 위반으로 렌더가 중단된다" },
  { k: "rx-hook-share", from: "파일 하나에 정의되어 있기 때문이다", to: "훅 내부 상태가 모듈 스코프에 저장되어 전역이 된다. 파일 하나에 정의되어 있는 까닭이다" },
  { k: "rx-pat-compound", from: "결합이 없기 때문이다", to: "각 Tab 이 자기 상태를 따로 가지고 Tabs 가 DOM 을 직접 조작한다. 서로 결합이 없는 구조다" },
  { k: "react2-key-random", from: "값이 겹칠 일이 없기 때문이다", to: "React 가 중복을 막아 주므로 성능상 가장 안전하다. 값이 겹칠 일이 없는 까닭이다" },
  { k: "react2-key-random", from: "평소에는 문제가 없다", to: "정렬 시에만 재마운트되고 평소에는 그대로 재사용된다" },
  { k: "react2-key-fragment", from: "key가 필요 없다", to: "map 대신 forEach로 push하면 key 없이도 경고가 사라진다" },
  { k: "react2-red-impossible", from: "아직 시작하지 않은 경우가 없기 때문이다", to: "isLoading 이 false 이고 data 도 null 인 상태다. 아직 시작하지 않은 경우가 없다는 이유에서다" },
  { k: "react2-red-nested", from: "중첩 객체를 일일이 펼칠 필요가 없다", to: "return Object.assign(state.user.profile, { name: action.name }); 로 바꿔 쓴다 원본을 직접 고치면 중첩 객체를 일일이 펼치는 수고가 사라진다" },
  { k: "react2-eb-self", from: "폴백이 없기 때문이다", to: "children 이 언마운트되고 빈 화면이 렌더된다. 폴백이 없는 탓이다" },
  { k: "react3-cache-6", from: "에러가 발생한다", to: "staleTime 은 0 을 허용하지 않아 설정 단계에서 예외가 던져진다" },
  { k: "react3-cache-6", from: "값이 남지 않기 때문이다", to: "캐시가 비활성화되어 화면이 언제나 비어 보인다. 값이 남지 않는 탓이다" },
  { k: "react3-cache-1", from: "낡은 값을 보이지 않기 때문이다", to: "새 데이터를 받을 때까지 화면을 비워 둔다. 낡은 값을 보이지 않는 원칙이다" }
] };
