/* 운영체제 실습 2차 — 실습이 하나도 없던 6개 유닛을 연다.
   프로세스와 스레드 · 컨텍스트 스위칭 · CPU 스케줄링 · 가상메모리 · 동기화와 데드락 ·
   I/O 모델.

   운영체제는 직접 만져 볼 일이 적어 '읽고 아는 것' 으로 끝나기 쉽다. 하지만 그
   개념들은 전부 계산으로 확인할 수 있다 — 대기 시간이 얼마인지, 페이지가 몇 번
   빠지는지, 자원 대기가 고리를 이루는지. 계산해 보면 왜 그런지가 손에 남는다.

   채점은 앱의 JS 하네스가 한다. */
module.exports = [
/* ── 프로세스 vs 스레드 ───────────────────────────────────── */
{
  unit: "프로세스 vs 스레드",
  lesson: "직접 짜 보기 — 따로 쓰는가 함께 쓰는가",
  th: {
    sum: "프로세스는 **메모리를 따로** 쓰고, 스레드는 **함께** 쓴다. 나머지 차이는 전부 여기서 나온다.",
    body: [
      { h: "따로 쓰면 안전하고 비싸다", t: "프로세스 하나가 잘못된 주소를 건드려도 다른 프로세스는 멀쩡하다. 대신 값을 주고받으려면 한 번 포장했다 푸는 과정을 거쳐야 해서 비용이 든다." },
      { h: "함께 쓰면 빠르고 위험하다", t: "스레드는 같은 변수를 그대로 본다. 주고받는 비용이 거의 없지만, 둘이 같은 값을 동시에 고치면 하나가 덮어써져 조용히 틀린 값이 남는다." },
      { h: "무엇이 각자의 것인가", t: "스레드마다 따로 갖는 것은 실행 위치와 자기 호출 기록(스택)이다. 힙과 열린 파일은 함께 쓴다. '이 값이 각자 것인가 함께 쓰는 것인가' 를 늘 물어야 한다." },
      { h: "하나가 죽으면", t: "프로세스가 죽어도 다른 프로세스는 산다. 하지만 스레드 하나가 프로세스를 죽이면 그 안의 모든 스레드가 함께 죽는다 — 격리 수준이 다르다는 것이 이 뜻이다." },
    ],
    code: { c: "프로세스: 메모리 따로 · 죽어도 남 · 주고받기 비쌈\n스레드  : 메모리 함께 · 같이 죽음 · 주고받기 쌈", cap: "따로냐 함께냐" },
    key: ["프로세스는 메모리를 따로 쓴다", "스레드는 같은 변수를 본다", "스택은 각자, 힙은 함께"],
  },
  q: [
    {
      k: "isShared · 무엇을 함께 쓰는가",
      qq: "자원 이름을 받아 같은 프로세스의 <b>스레드끼리 함께 쓰는지</b> 판단하세요. <code>'heap'</code>·<code>'file'</code>·<code>'code'</code>는 함께, <code>'stack'</code>·<code>'register'</code>는 각자입니다.",
      src: "function isShared(kind) {\n  return kind !== 'stack';\n}",
      sol: "function isShared(kind) {\n  return ['heap', 'file', 'code'].includes(kind);\n}",
      tests: [["isShared('heap')", "true"],
              ["isShared('stack')", "false"],
              ["isShared('register')", "false"]],
      edge: [["isShared('file')", "true"],
             ["isShared('모름')", "false"]],
      ex: "'스택만 각자' 로 외우면 레지스터처럼 각자인 것을 함께 쓴다고 보게 됩니다. 모르는 자원을 '함께 쓴다' 로 넘기는 것도 위험해요 — 모르면 각자로 두는 편이 안전합니다.",
    },
    {
      k: "crashImpact · 하나가 죽으면 몇이 죽나",
      qq: "실행 단위 목록과 죽은 단위의 프로세스 번호를 받아, <b>함께 죽는 단위 수</b>를 돌려주세요. 같은 프로세스의 스레드는 함께 죽습니다.",
      src: "function crashImpact(units, pid) {\n  return 1;\n}",
      sol: "function crashImpact(units, pid) {\n  return units.filter(u => u.pid === pid).length;\n}",
      tests: [["crashImpact([{ pid: 1 }, { pid: 1 }, { pid: 2 }], 1)", "2"],
              ["crashImpact([{ pid: 1 }, { pid: 2 }, { pid: 3 }], 2)", "1"],
              ["crashImpact([{ pid: 1 }, { pid: 1 }, { pid: 1 }], 1)", "3"]],
      edge: [["crashImpact([], 1)", "0"],
             ["crashImpact([{ pid: 1 }], 9)", "0"]],
      ex: "'하나 죽으면 하나' 로 보면 스레드 모델의 위험을 놓칩니다. 스레드 하나가 프로세스를 죽이면 그 안의 전부가 함께 죽어요 — 격리 수준이 다르다는 것이 이 뜻입니다.",
    },
    {
      k: "handoffCost · 주고받는 비용",
      qq: "자료 크기(바이트)와 방식을 받아 비용을 돌려주세요. <code>'thread'</code>는 <b>0</b>, <code>'process'</code>는 <b>크기만큼</b>(포장했다 푸는 비용)입니다.",
      src: "function handoffCost(bytes, mode) {\n  return bytes;\n}",
      sol: "function handoffCost(bytes, mode) {\n  return mode === 'thread' ? 0 : bytes;\n}",
      tests: [["handoffCost(1000, 'thread')", "0"],
              ["handoffCost(1000, 'process')", "1000"],
              ["handoffCost(0, 'process')", "0"]],
      edge: [["handoffCost(5000000, 'thread')", "0"]],
      ex: "스레드는 같은 메모리를 보니 넘길 것이 없습니다. 큰 자료를 자주 주고받는다면 이 차이가 그대로 성능이 돼요 — 프로세스로 나눌 때 가장 먼저 재 봐야 하는 값입니다.",
    },
  ],
},
/* ── 컨텍스트 스위칭 ──────────────────────────────────────── */
{
  unit: "컨텍스트 스위칭",
  lesson: "직접 짜 보기 — 갈아타는 데 드는 값",
  th: {
    sum: "CPU 하나로 여럿을 돌리려면 계속 **갈아타야** 한다. 갈아타는 것 자체가 일이다.",
    body: [
      { h: "하던 자리를 저장하고 불러온다", t: "지금 어디까지 했는지를 저장하고 다음 것의 기록을 불러온다. 그 사이 CPU 는 사용자 일을 하지 않는다. 이 시간이 짧아 보여도 초당 수천 번이면 무시할 수 없다." },
      { h: "캐시가 식는 것이 더 크다", t: "저장·복원 자체보다, 갈아탄 뒤 캐시에 원하는 값이 없어 느려지는 것이 더 크다. 그래서 잘게 자주 갈아타면 눈에 보이는 저장 비용보다 훨씬 많이 손해 본다." },
      { h: "시간 조각이 짧을수록 자주 갈아탄다", t: "조각을 짧게 주면 반응은 빨라지지만 갈아타는 횟수가 늘어 총 처리량이 준다. 길게 주면 반대다 — 무엇이 중요한지에 따라 고른다." },
      { h: "스레드끼리는 조금 싸다", t: "같은 프로세스 안의 스레드끼리 갈아탈 때는 메모리 지도를 바꾸지 않아도 되어 조금 싸다. 그래도 공짜는 아니다." },
    ],
    code: { c: "총 갈아타기 = 실행시간 / 시간조각\n낭비 = 총 갈아타기 * 한 번 비용", cap: "짧게 자를수록 자주 갈아탄다" },
    key: ["갈아타는 동안은 일을 못 한다", "캐시가 식는 것이 더 크다", "조각이 짧으면 자주 갈아탄다"],
  },
  q: [
    {
      k: "switchCount · 몇 번 갈아타나",
      qq: "총 실행 시간과 시간 조각을 받아 <b>갈아타는 횟수</b>를 돌려주세요. 마지막 조각 뒤에는 갈아탈 필요가 없습니다.",
      src: "function switchCount(runMs, sliceMs) {\n  return Math.ceil(runMs / sliceMs);\n}",
      sol: "function switchCount(runMs, sliceMs) {\n  return Math.max(0, Math.ceil(runMs / sliceMs) - 1);\n}",
      tests: [["switchCount(100, 10)", "9"],
              ["switchCount(100, 100)", "0"],
              ["switchCount(25, 10)", "2"]],
      edge: [["switchCount(0, 10)", "0"],
             ["switchCount(5, 10)", "0"]],
      ex: "조각 수를 그대로 세면 마지막에 한 번을 더 셉니다. 열 조각이면 갈아타기는 아홉 번이에요 — 울타리와 기둥을 세는 것과 같은 실수입니다.",
    },
    {
      k: "wastedMs · 갈아타느라 버린 시간",
      qq: "총 실행 시간·시간 조각·한 번 갈아타는 비용을 받아 <b>버린 시간</b>을 돌려주세요.",
      src: "function wastedMs(runMs, sliceMs, costMs) {\n  return costMs;\n}",
      sol: "function wastedMs(runMs, sliceMs, costMs) {\n  const n = Math.max(0, Math.ceil(runMs / sliceMs) - 1);\n  return n * costMs;\n}",
      tests: [["wastedMs(100, 10, 1)", "9"],
              ["wastedMs(100, 100, 1)", "0"],
              ["wastedMs(100, 1, 1)", "99"]],
      edge: [["wastedMs(0, 10, 1)", "0"],
             ["wastedMs(100, 10, 0)", "0"]],
      ex: "조각을 1ms 로 자르면 100ms 짜리 일에서 99ms 를 갈아타는 데 씁니다. 반응은 빨라 보여도 실제로 하는 일은 절반이 돼요 — 조각 크기는 이 둘 사이의 선택입니다.",
    },
    {
      k: "switchKind · 무엇을 갈아타는가",
      qq: "이전과 다음 실행 단위의 프로세스 번호를 받아 종류를 돌려주세요. 같으면 <code>'thread'</code>, 다르면 <code>'process'</code> 입니다.",
      src: "function switchKind(prev, next) {\n  return 'process';\n}",
      sol: "function switchKind(prev, next) {\n  return prev.pid === next.pid ? 'thread' : 'process';\n}",
      tests: [["switchKind({ pid: 1 }, { pid: 1 })", "'thread'"],
              ["switchKind({ pid: 1 }, { pid: 2 })", "'process'"],
              ["switchKind({ pid: 0 }, { pid: 0 })", "'thread'"]],
      edge: [["switchKind({ pid: 9 }, { pid: 9 })", "'thread'"]],
      ex: "전부 프로세스 전환으로 세면 비용을 실제보다 크게 잡습니다. 같은 프로세스 안의 스레드끼리는 메모리 지도를 그대로 두어도 되어 조금 싸요.",
    },
  ],
},
/* ── CPU 스케줄링 ─────────────────────────────────────────── */
{
  unit: "CPU 스케줄링",
  lesson: "직접 짜 보기 — 누구를 먼저 돌릴 것인가",
  th: {
    sum: "무엇을 먼저 돌리느냐로 **평균 기다림**이 크게 달라진다. 같은 일을 해도 그렇다.",
    body: [
      { h: "짧은 것을 먼저 하면 평균이 준다", t: "긴 일을 먼저 하면 뒤의 짧은 일들이 전부 그만큼 기다린다. 짧은 것부터 하면 기다리는 사람 수 자체가 줄어 평균 대기가 내려간다 — 계산해 보면 차이가 크다." },
      { h: "대신 긴 일이 굶는다", t: "짧은 일이 계속 들어오면 긴 일은 영영 차례가 안 온다. 오래 기다린 일의 우선순위를 조금씩 올려 주면 이 굶주림이 사라진다." },
      { h: "돌아가며 나누면 반응이 빠르다", t: "모두에게 조금씩 돌아가며 주면 아무도 오래 기다리지 않는다. 대화형 프로그램에 맞는다. 대신 갈아타는 횟수가 늘어 전체 처리량은 준다." },
      { h: "무엇을 좋게 할지 먼저 정한다", t: "평균 대기·최대 대기·처리량·공평함은 서로 당긴다. 전부 좋게 하는 방법은 없다. 무엇이 중요한 시스템인지 정하고 나서야 고를 수 있다." },
    ],
    code: { c: "// 짧은 것부터: 평균 대기가 내려간다\njobs.sort((a, b) => a.burst - b.burst)", cap: "무엇을 좋게 할지 먼저 정한다" },
    key: ["짧은 것부터 하면 평균이 준다", "대신 긴 일이 굶는다", "전부 좋게 할 수는 없다"],
  },
  q: [
    {
      k: "avgWait · 순서대로 돌렸을 때 평균 대기",
      qq: "작업 시간 목록을 <b>받은 순서대로</b> 돌렸을 때 <b>평균 대기 시간</b>을 돌려주세요. 첫 작업의 대기는 0입니다.",
      src: "function avgWait(bursts) {\n  return bursts.reduce((a, b) => a + b, 0) / bursts.length;\n}",
      sol: "function avgWait(bursts) {\n  if (!bursts.length) return 0;\n  let acc = 0;\n  let total = 0;\n  for (const b of bursts) {\n    total += acc;\n    acc += b;\n  }\n  return total / bursts.length;\n}",
      tests: [["avgWait([1, 2, 3])", "4 / 3"],
              ["avgWait([3, 2, 1])", "8 / 3"],
              ["avgWait([5])", "0"]],
      edge: [["avgWait([])", "0"],
             ["avgWait([0, 0])", "0"]],
      ex: "대기 시간은 '내 앞의 작업들이 끝날 때까지' 입니다. 작업 시간 자체를 평균 내는 것과는 완전히 다른 값이에요 — 앞에서부터 쌓아 가며 세야 합니다.",
    },
    {
      k: "sjfOrder · 짧은 것부터 세우기",
      qq: "작업 목록을 <b>짧은 것부터</b> 정렬해 이름만 돌려주세요. 시간이 같으면 <b>들어온 순서</b>를 지키고, 원본은 그대로 둡니다.",
      src: "function sjfOrder(jobs) {\n  return jobs.sort((a, b) => a.burst - b.burst).map(j => j.name);\n}",
      sol: "function sjfOrder(jobs) {\n  return jobs.slice().sort((a, b) => a.burst - b.burst).map(j => j.name);\n}",
      tests: [["sjfOrder([{ name: 'a', burst: 5 }, { name: 'b', burst: 1 }])", "['b', 'a']"],
              ["sjfOrder([{ name: 'a', burst: 1 }, { name: 'b', burst: 1 }])", "['a', 'b']"],
              ["(() => { const j = [{ name: 'a', burst: 5 }, { name: 'b', burst: 1 }]; sjfOrder(j); return j[0].name; })()", "'a'"]],
      edge: [["sjfOrder([])", "[]"]],
      ex: "sort 는 받은 배열을 그 자리에서 뒤집습니다. 스케줄러가 원본 큐를 넘겼다면 그 큐의 순서가 바뀌어, 다음 계산이 전혀 다른 전제에서 돌아가요.",
    },
    {
      k: "agedPriority · 오래 기다린 일을 올려 주기",
      qq: "기본 우선순위와 기다린 시간을 받아 <b>실제 우선순위</b>를 돌려주세요. <b>10ms 마다 1씩</b> 올라가고(내림), 상한은 <code>maxP</code> 입니다. 숫자가 클수록 먼저입니다.",
      src: "function agedPriority(base, waitedMs, maxP) {\n  return base;\n}",
      sol: "function agedPriority(base, waitedMs, maxP) {\n  return Math.min(maxP, base + Math.floor(waitedMs / 10));\n}",
      tests: [["agedPriority(1, 0, 10)", "1"],
              ["agedPriority(1, 55, 10)", "6"],
              ["agedPriority(1, 1000, 10)", "10"]],
      edge: [["agedPriority(10, 100, 10)", "10"],
             ["agedPriority(1, 9, 10)", "1"]],
      ex: "우선순위를 그대로 두면 낮은 일은 영영 차례가 안 옵니다. 시스템은 바쁘게 도는데 어떤 작업은 몇 시간째 그대로예요. 기다린 만큼 올려 주면 언젠가는 반드시 차례가 옵니다.",
    },
  ],
},
/* ── 메모리·가상메모리·페이지폴트 ─────────────────────────── */
{
  unit: "메모리·가상메모리·페이지폴트",
  lesson: "직접 짜 보기 — 없는 자리를 있는 것처럼",
  th: {
    sum: "가상메모리는 **실제보다 큰 메모리가 있는 것처럼** 보이게 한다. 없는 조각은 그때 가져온다.",
    body: [
      { h: "쪽 단위로 나눠 관리한다", t: "메모리를 일정한 크기의 쪽(page)으로 나누고, 필요한 쪽만 실제 메모리에 올린다. 그래서 프로그램이 메모리보다 커도 돌아간다." },
      { h: "없으면 그때 가져온다", t: "필요한 쪽이 올라와 있지 않으면 그 순간 멈추고 디스크에서 가져온다(page fault). 디스크는 메모리보다 몇 만 배 느려서, 이 횟수가 성능을 정한다." },
      { h: "무엇을 내보낼지 고른다", t: "자리가 없으면 하나를 내보내야 한다. 가장 오래 안 쓴 것을 내보내는 방식이 흔하다. 잘못 고르면 방금 내보낸 것을 바로 다시 가져오는 일이 반복된다." },
      { h: "훑는 순서가 결과를 바꾼다", t: "같은 자료라도 이어진 순서로 읽으면 한 쪽에서 여러 값을 쓰지만, 건너뛰며 읽으면 쪽마다 한 값만 쓰고 버린다. 코드는 같은데 몇 배 느려지는 자리가 여기다." },
    ],
    code: { c: "필요한 쪽이 없으면 → 멈추고 디스크에서 → 다시 실행\n자리가 없으면 → 가장 오래 안 쓴 쪽을 내보낸다", cap: "없는 쪽은 그때 가져온다" },
    key: ["쪽 단위로 올린다", "없으면 멈추고 가져온다", "훑는 순서가 결과를 바꾼다"],
  },
  q: [
    {
      k: "pageOf · 주소가 몇 번째 쪽인가",
      qq: "주소와 쪽 크기를 받아 <b>쪽 번호</b>를 돌려주세요. 주소가 <b>음수면 <code>null</code></b> 입니다.",
      src: "function pageOf(addr, pageSize) {\n  return Math.floor(addr / pageSize);\n}",
      sol: "function pageOf(addr, pageSize) {\n  if (addr < 0) return null;\n  return Math.floor(addr / pageSize);\n}",
      tests: [["pageOf(0, 4096)", "0"],
              ["pageOf(4095, 4096)", "0"],
              ["pageOf(4096, 4096)", "1"]],
      edge: [["pageOf(-1, 4096)", "null"],
             ["pageOf(8192, 4096)", "2"]],
      ex: "음수 주소를 그대로 나누면 -1 같은 쪽 번호가 나옵니다. 그 번호로 표를 찾으면 엉뚱한 자리를 읽거나 없는 항목을 만나요 — 들어올 수 없는 값은 그 자리에서 거절합니다.",
    },
    {
      k: "faults · 몇 번 가져오게 되나",
      qq: "쪽 접근 순서와 올려 둘 수 있는 칸 수를 받아, <b>가장 오래 안 쓴 것을 내보내는</b> 방식으로 <b>가져온 횟수</b>를 돌려주세요.",
      src: "function faults(refs, frames) {\n  return new Set(refs).size;\n}",
      sol: "function faults(refs, frames) {\n  const inMem = [];\n  let n = 0;\n  for (const p of refs) {\n    const i = inMem.indexOf(p);\n    if (i >= 0) {\n      inMem.splice(i, 1);\n      inMem.push(p);\n      continue;\n    }\n    n++;\n    if (inMem.length >= frames) inMem.shift();\n    inMem.push(p);\n  }\n  return n;\n}",
      tests: [["faults([1, 2, 3, 1, 2, 3], 3)", "3"],
              ["faults([1, 2, 3, 4, 1, 2], 3)", "6"],
              ["faults([1, 1, 1], 1)", "1"]],
      edge: [["faults([], 3)", "0"],
             ["faults([1, 2, 1, 2], 2)", "2"]],
      ex: "서로 다른 쪽의 개수를 세면 '칸이 모자라 내보냈다가 다시 가져오는' 경우를 통째로 놓칩니다. 칸이 3인데 쪽 4개를 돌려 쓰면 매번 다시 가져와요 — 그게 성능이 무너지는 자리입니다.",
    },
    {
      k: "scanCost · 훑는 순서가 만드는 차이",
      qq: "값의 개수·쪽 하나에 들어가는 값의 수·건너뛰는 간격을 받아 <b>건드리는 쪽의 수</b>를 돌려주세요.",
      src: "function scanCost(n, perPage, stride) {\n  return Math.ceil(n / perPage);\n}",
      sol: "function scanCost(n, perPage, stride) {\n  const pages = new Set();\n  for (let i = 0; i < n; i += stride) pages.add(Math.floor(i / perPage));\n  return pages.size;\n}",
      tests: [["scanCost(16, 4, 1)", "4"],
              ["scanCost(16, 4, 4)", "4"],
              ["scanCost(16, 4, 8)", "2"]],
      edge: [["scanCost(0, 4, 1)", "0"],
             ["scanCost(4, 4, 1)", "1"]],
      ex: "이어서 읽으면 한 쪽에서 값 네 개를 쓰지만, 네 칸씩 건너뛰면 쪽마다 한 값만 쓰고 버립니다. 코드는 거의 같은데 건드리는 쪽 수가 배로 늘어나요 — 몇 배 느려지는 자리가 여기입니다.",
    },
  ],
},
/* ── 동기화·데드락 ────────────────────────────────────────── */
{
  unit: "동기화·데드락",
  lesson: "직접 짜 보기 — 서로 기다리다 멈추는 것",
  th: {
    sum: "데드락은 **서로가 서로를 기다려** 아무도 못 가는 상태다. 고리가 생기면 그렇게 된다.",
    body: [
      { h: "네 가지가 모두 갖춰져야 생긴다", t: "자원을 혼자만 쓰고, 쥔 채로 더 기다리고, 빼앗을 수 없고, 기다림이 고리를 이루면 데드락이다. 넷 중 하나만 깨도 생기지 않는다 — 그래서 대책도 넷 중 하나를 고르는 일이다." },
      { h: "순서를 정하면 고리가 안 생긴다", t: "모두가 자원을 같은 순서로 잡으면 고리가 만들어질 수 없다. 가장 단순하고 가장 확실한 대책이라, 실무에서 제일 많이 쓴다." },
      { h: "고리는 그림으로 찾는다", t: "'누가 무엇을 쥐고 무엇을 기다리는가' 를 화살표로 그리면, 데드락은 그 화살표가 고리를 이룬 모양이다. 눈으로 찾기 어려울 뿐 규칙은 단순하다." },
      { h: "기다림에 끝을 두는 방법도 있다", t: "일정 시간 안에 못 잡으면 쥔 것을 놓고 물러난다. 고리가 생겨도 저절로 풀리지만, 여럿이 동시에 물러났다 동시에 다시 시도하면 계속 부딪힐 수 있다 — 물러나는 시간을 조금씩 다르게 둔다." },
    ],
    code: { c: "// 언제나 번호가 작은 자물쇠부터\nlock(Math.min(a, b));\nlock(Math.max(a, b));", cap: "순서를 정하면 고리가 안 생긴다" },
    key: ["고리가 생기면 데드락", "같은 순서로 잡으면 안 생긴다", "기다림에 끝을 두는 방법도"],
  },
  q: [
    {
      k: "hasCycle · 고리가 생겼는가",
      qq: "'누가 무엇을 기다리는가' 목록을 받아 <b>고리가 있는지</b> 판단하세요. <code>{ from, to }</code> 는 <code>from</code>이 <code>to</code>를 기다린다는 뜻입니다.",
      src: "function hasCycle(edges) {\n  return edges.length >= 2;\n}",
      sol: "function hasCycle(edges) {\n  const next = {};\n  edges.forEach(e => { next[e.from] = e.to; });\n  for (const start of Object.keys(next)) {\n    let cur = start;\n    for (let i = 0; i <= edges.length; i++) {\n      cur = next[cur];\n      if (cur === undefined) break;\n      if (cur === start) return true;\n    }\n  }\n  return false;\n}",
      tests: [["hasCycle([{ from: 'a', to: 'b' }, { from: 'b', to: 'a' }])", "true"],
              ["hasCycle([{ from: 'a', to: 'b' }, { from: 'b', to: 'c' }])", "false"],
              ["hasCycle([{ from: 'a', to: 'b' }, { from: 'b', to: 'c' }, { from: 'c', to: 'a' }])", "true"]],
      edge: [["hasCycle([])", "false"],
             ["hasCycle([{ from: 'a', to: 'a' }])", "true"]],
      ex: "기다림이 몇 개인지로는 아무것도 알 수 없습니다. 열 개가 줄줄이 이어져 있어도 고리가 아니면 언젠가 풀려요. 화살표를 따라가 제자리로 돌아오는지를 봐야 합니다.",
    },
    {
      k: "lockOrder · 같은 순서로 잡기",
      qq: "잡아야 할 자물쇠 번호 두 개를 받아 <b>잡을 순서</b>를 돌려주세요. <b>언제나 작은 번호부터</b>입니다.",
      src: "function lockOrder(a, b) {\n  return [a, b];\n}",
      sol: "function lockOrder(a, b) {\n  return a <= b ? [a, b] : [b, a];\n}",
      tests: [["lockOrder(1, 2)", "[1, 2]"],
              ["lockOrder(2, 1)", "[1, 2]"],
              ["lockOrder(5, 5)", "[5, 5]"]],
      edge: [["lockOrder(0, 9)", "[0, 9]"],
             ["lockOrder(9, 0)", "[0, 9]"]],
      ex: "받은 순서대로 잡으면, 한쪽은 1→2 로 다른 쪽은 2→1 로 잡아 고리가 만들어집니다. 모두가 같은 순서로 잡으면 고리 자체가 생길 수 없어요 — 가장 단순하고 확실한 대책입니다.",
    },
    {
      k: "backoffWait · 물러나는 시간을 다르게",
      qq: "시도 횟수·기본 대기·<b>0~1 사이의 값</b>을 받아 물러날 시간을 돌려주세요. <code>base * 2^attempt</code> 에 그 값을 곱하고 <b>내림</b>합니다.",
      src: "function backoffWait(attempt, base, r) {\n  return base * Math.pow(2, attempt);\n}",
      sol: "function backoffWait(attempt, base, r) {\n  return Math.floor(base * Math.pow(2, attempt) * r);\n}",
      tests: [["backoffWait(0, 100, 1)", "100"],
              ["backoffWait(2, 100, 0.5)", "200"],
              ["backoffWait(0, 100, 0)", "0"]],
      edge: [["backoffWait(3, 10, 0.25)", "20"],
             ["backoffWait(1, 100, 0.5)", "100"]],
      ex: "모두가 정확히 같은 시간을 기다리면, 물러났다가 동시에 다시 시도해 또 부딪힙니다. 이 부딪힘이 계속 반복돼요. 조금씩 다르게 흩어 두면 그 굴레가 끊어집니다.",
    },
  ],
},
/* ── I/O 모델 심화 ────────────────────────────────────────── */
{
  unit: "I/O 모델 심화 — 블로킹·논블로킹·다중화와 C10K",
  lesson: "직접 짜 보기 — 기다리는 방법을 고르기",
  th: {
    sum: "입출력을 기다리는 방법이 성능을 정한다. **붙들려 기다릴지, 물어보며 갈지, 알려 줄 때까지 잘지.**",
    body: [
      { h: "붙들려 기다리면 하나에 하나", t: "요청 하나마다 스레드 하나가 붙어 기다린다. 코드는 가장 단순하지만, 동시 접속이 만 개면 스레드도 만 개다. 메모리와 갈아타기 비용이 먼저 바닥난다." },
      { h: "물어보며 가면 CPU 를 태운다", t: "'왔니?' 를 계속 물어보면 붙들리지는 않지만, 아무 일이 없어도 CPU 를 쓴다. 연결이 많을수록 헛물음도 늘어난다." },
      { h: "다중화는 한 번에 물어본다", t: "'이 중에 준비된 것 알려 줘' 라고 한 번에 묻고 잠든다. 준비된 것이 생기면 깨워 준다. 스레드 하나로 수천 연결을 다루는 서버들이 이 방식이다." },
      { h: "그래도 계산은 막는다", t: "다중화를 써도 무거운 계산이 끼면 그동안 아무 연결도 처리되지 않는다. 기다림은 다중화로, 계산은 다른 일꾼에게 — 둘은 다른 문제다." },
    ],
    code: { c: "블로킹   : 연결당 스레드 1개\n다중화   : 스레드 1개가 수천 연결\n계산     : 어느 쪽이든 따로 넘긴다", cap: "기다림과 계산은 다른 문제" },
    key: ["붙들려 기다리면 연결당 스레드", "다중화는 한 번에 물어본다", "계산은 따로 넘긴다"],
  },
  q: [
    {
      k: "threadsNeeded · 방식에 따른 스레드 수",
      qq: "동시 연결 수와 방식을 받아 <b>필요한 스레드 수</b>를 돌려주세요. <code>'blocking'</code>은 연결마다 하나, <code>'mux'</code>는 <b>언제나 1</b> 입니다.",
      src: "function threadsNeeded(conns, mode) {\n  return conns;\n}",
      sol: "function threadsNeeded(conns, mode) {\n  return mode === 'mux' ? 1 : conns;\n}",
      tests: [["threadsNeeded(10000, 'blocking')", "10000"],
              ["threadsNeeded(10000, 'mux')", "1"],
              ["threadsNeeded(0, 'blocking')", "0"]],
      edge: [["threadsNeeded(0, 'mux')", "1"],
             ["threadsNeeded(1, 'blocking')", "1"]],
      ex: "연결이 만 개면 스레드도 만 개입니다. 스레드 하나에 스택만 몇 MB 라 메모리가 먼저 바닥나요 — C10K 라는 이름이 붙은 문제가 이것입니다.",
    },
    {
      k: "readyList · 준비된 것만 골라 주기",
      qq: "감시 중인 소켓 목록을 받아 <b>준비된 것의 번호만</b> 순서대로 돌려주세요. 준비된 것이 없으면 빈 배열입니다.",
      src: "function readyList(socks) {\n  return socks.map(s => s.fd);\n}",
      sol: "function readyList(socks) {\n  return socks.filter(s => s.ready).map(s => s.fd);\n}",
      tests: [["readyList([{ fd: 3, ready: true }, { fd: 4, ready: false }])", "[3]"],
              ["readyList([{ fd: 3, ready: false }])", "[]"],
              ["readyList([{ fd: 3, ready: true }, { fd: 4, ready: true }])", "[3, 4]"]],
      edge: [["readyList([])", "[]"],
             ["readyList([{ fd: 0, ready: true }])", "[0]"]],
      ex: "전부 돌려주면 준비 안 된 소켓을 읽으려다 그 자리에서 붙들립니다. 다중화의 값어치는 '준비된 것만' 에 있어요 — 그게 아니면 그냥 하나씩 물어보는 것과 같습니다.",
    },
    {
      k: "eventLoopBlocked · 계산이 막는 시간",
      qq: "이벤트 목록을 받아 <b>계산 때문에 다른 일이 못 도는 시간</b>을 합쳐 돌려주세요. <code>kind</code>가 <code>'cpu'</code>인 것만 셉니다.",
      src: "function eventLoopBlocked(events) {\n  return events.reduce((a, e) => a + e.ms, 0);\n}",
      sol: "function eventLoopBlocked(events) {\n  return events.filter(e => e.kind === 'cpu').reduce((a, e) => a + e.ms, 0);\n}",
      tests: [["eventLoopBlocked([{ kind: 'cpu', ms: 30 }, { kind: 'io', ms: 500 }])", "30"],
              ["eventLoopBlocked([{ kind: 'io', ms: 500 }])", "0"],
              ["eventLoopBlocked([{ kind: 'cpu', ms: 10 }, { kind: 'cpu', ms: 20 }])", "30"]],
      edge: [["eventLoopBlocked([])", "0"],
             ["eventLoopBlocked([{ kind: 'cpu', ms: 0 }])", "0"]],
      ex: "기다리는 시간까지 더하면 500ms 가 막힌 것처럼 보이지만, 기다리는 동안에는 다른 일이 돌아갑니다. 실제로 막는 것은 계산뿐이에요 — 이 둘을 섞으면 엉뚱한 곳을 고치게 됩니다.",
    },
  ],
},
];
