/* Testing 트랙 전용 프로젝트 — 테스트가 하나도 없는 코드를 물려받았다.
   현재 동작을 고정하고, 의존을 끊고, 경우를 설계하고, CI 에 물리기까지
   한 바퀴를 돌면 '고쳐도 안 무섭다' 는 말의 내용이 손에 남는다. */
module.exports = {
  lv: 3, em: "🧪",
  title: "테스트가 하나도 없는 코드를 물려받았다",
  desc: "손댈 때마다 무언가 깨지는 주문 계산 모듈에 특성화 테스트를 씌우고, 의존을 끊고, 경우를 설계하고, CI 에서 매번 돌게 만든다",
  skills: ["test", "code", "devops"],
  phases: [

  { t: "무엇이 무서운지 먼저 적는다", type: "note",
    goal: "코드를 건드리기 전에 <b>어디를 고칠 때 가장 겁이 나는지</b>와 <b>깨지면 무엇이 잘못되는지</b>를 적으세요.\n최근 장애가 있었다면 그것부터 적습니다 — 테스트를 어디에 먼저 쓸지 정하는 가장 강한 근거입니다.",
    ph: "예: 등급별 할인 계산 — 틀리면 돈이 잘못 빠짐 · 쿠폰 중복 적용 규칙이 if 안에 세 겹으로 묻혀 있음 · 지난달 장애: 자정 넘어가는 주문의 만료일 계산" },

  { t: "무엇부터 할 것인가", type: "decide",
    goal: "주문 금액 계산 함수가 400줄이고 테스트가 하나도 없습니다. 읽기도 어렵고 고쳐 달라는 요청은 이미 들어와 있습니다.",
    sit: "어디서부터 손대시겠습니까?",
    opts: [
      { label: "현재 동작을 그대로 고정하는 테스트를 먼저 붙이고, 그다음에 구조를 바꾼다",
        fx: { debugging: 3, system_design: 2, communication: 1 },
        fb: "✅ <b>특성화 테스트(characterization test)</b> 입니다. 지금 동작이 옳은지는 판단하지 않고 <b>있는 그대로</b> 못 박아 두는 것이 요점입니다. 그물이 생기고 나면 구조를 바꿔도 무엇이 달라졌는지 즉시 보입니다. 순서를 바꾸면 리팩터링이 동작을 바꿨는지 알 방법이 없습니다.",
        best: true },
      { label: "먼저 읽기 좋게 정리한 뒤 깔끔해진 코드에 테스트를 붙인다",
        fx: { system_design: -2, debugging: -1 },
        fb: "⚠️ 정리하는 도중에 동작이 바뀌어도 <b>알아챌 방법이 없습니다.</b> 리팩터링은 '동작을 바꾸지 않는 변경' 인데, 그것을 확인할 장치 없이 하는 것은 리팩터링이 아니라 그냥 다시 쓰는 것입니다." },
      { label: "요청받은 기능부터 고치고, 시간이 남으면 테스트를 붙인다",
        fx: { debugging: -2, leadership: -1 },
        fb: "⚠️ '시간이 남으면' 은 오지 않습니다. 게다가 지금이 바로 그 코드를 가장 잘 이해하고 있는 순간이라, 나중에 붙이면 훨씬 비쌉니다." },
      { label: "전체를 새로 쓰고 새 코드에만 테스트를 붙인다",
        fx: { system_design: -3, leadership: -2 },
        fb: "⚠️ 400줄 안에는 <b>몇 년치의 예외 처리</b>가 들어 있습니다. 그중 무엇이 실제 요구사항이고 무엇이 잔재인지 아무도 모르는 상태에서 새로 쓰면, 옛 버그를 고치는 대신 새 버그를 잔뜩 만듭니다." }] },

  { t: "현재 동작을 그대로 고정한다", type: "build",
    goal: "지금 코드의 동작을 <b>옳은지 따지지 않고</b> 있는 그대로 테스트로 적으세요.\n실제 입력 몇 개를 넣어 나온 값을 그대로 기대값으로 씁니다. 이상해 보이는 결과가 있으면 주석으로 표시만 해 둡니다.",
    hint: "값을 손으로 계산하려 하지 마세요. 함수를 돌려 <b>나온 값을 그대로 적는 것</b>이 특성화 테스트입니다. 목적은 '옳은가' 가 아니라 '지금과 같은가' 입니다. 나중에 진짜 버그로 확인되면 그때 기대값을 바꾸고 그 변경을 커밋 메시지에 남깁니다.",
    acc: "대표 입력 5개 이상에 대해 현재 값이 고정되고, 코드를 한 줄도 바꾸지 않은 상태에서 전부 통과하면 완료입니다.",
    lang: "javascript",
    sol: "/* 아주 작은 러너 — 프레임워크가 해 주는 일은 결국 이것이다 */\nconst out = [];\nfunction test(name, fn) {\n  try { fn(); out.push(\"PASS \" + name); }\n  catch (e) { out.push(\"FAIL \" + name + \" — \" + e.message); }\n}\nfunction expect(got) {\n  return { toBe(want) {\n    if (!Object.is(got, want))\n      throw new Error(\"기대 \" + JSON.stringify(want) + \", 실제 \" + JSON.stringify(got));\n  } };\n}\n\n/* 물려받은 코드 — 여기서는 한 줄도 바꾸지 않는다 */\nfunction calcOrder(o) {\n  let sum = o.amount;\n  if (o.coupon) sum -= o.coupon;\n  if (o.grade === \"gold\") sum = Math.round(sum * 0.9);\n  return sum;\n}\n\n/* 특성화 테스트 — '옳은 값' 이 아니라 '지금 값' 을 적는다.\n   기대값은 손으로 계산하지 않고 실행 결과를 그대로 옮겼다. */\ntest(\"일반 등급 · 쿠폰 없음\", () => {\n  expect(calcOrder({ grade: \"basic\", amount: 10000, coupon: null })).toBe(10000);\n});\ntest(\"골드 등급 · 10% 할인\", () => {\n  expect(calcOrder({ grade: \"gold\", amount: 10000, coupon: null })).toBe(9000);\n});\ntest(\"쿠폰이 등급 할인보다 먼저 적용된다\", () => {\n  expect(calcOrder({ grade: \"gold\", amount: 10000, coupon: 2000 })).toBe(7200);\n});\ntest(\"금액이 0이면 그대로 0\", () => {\n  expect(calcOrder({ grade: \"gold\", amount: 0, coupon: null })).toBe(0);\n});\n// 음수가 나온다. 버그로 보이지만 지금은 고정만 해 둔다.\ntest(\"쿠폰이 금액보다 크면 음수가 된다(현재 동작)\", () => {\n  expect(calcOrder({ grade: \"basic\", amount: 1000, coupon: 3000 })).toBe(-2000);\n});\n\nconsole.log(out.join(\"\\n\"));" },

  { t: "의존을 끊어 테스트할 수 있게 만든다", type: "build",
    goal: "함수 안에서 직접 부르던 <b>현재 시각과 환율 조회</b>를 바깥에서 넣을 수 있게 바꾸세요.\n동작은 그대로 두고 <b>넣을 자리(이음매)만</b> 만드는 것이 이 단계의 전부입니다.",
    hint: "기본값을 주면 기존 호출부를 한 줄도 고치지 않아도 됩니다. <code>function f(x, now = () =&gt; Date.now())</code> 처럼 두면 운영 코드는 그대로 돌고 테스트에서만 가짜를 넣습니다. 이렇게 <b>동작을 바꾸지 않는 변경</b>이라 특성화 테스트가 전부 통과해야 합니다.",
    acc: "앞 단계의 테스트가 하나도 수정 없이 통과하고, 새 테스트에서 고정된 시각과 고정 환율을 넣어 결과를 확인할 수 있으면 완료입니다.",
    lang: "javascript",
    sol: "const out = [];\nfunction test(name, fn) {\n  try { fn(); out.push(\"PASS \" + name); }\n  catch (e) { out.push(\"FAIL \" + name + \" — \" + e.message); }\n}\nfunction expect(got) {\n  return { toBe(want) {\n    if (!Object.is(got, want))\n      throw new Error(\"기대 \" + JSON.stringify(want) + \", 실제 \" + JSON.stringify(got));\n  } };\n}\n\n/* 바뀐 것은 '무엇을 하는가' 가 아니라 '어디서 가져오는가' 뿐이다.\n   기본값을 두었으므로 기존 호출부는 한 줄도 고치지 않아도 된다. */\nfunction calcOrder(order, deps) {\n  const d = deps || { now: () => Date.now(), rate: () => 1300 };\n  const at = new Date(d.now());\n  const rate = order.currency === \"USD\" ? d.rate() : 1;\n  const weekend = at.getUTCDay() === 0 || at.getUTCDay() === 6;\n  let sum = order.amount * rate;\n  if (weekend) sum = Math.round(sum * 0.95);   // 주말 5% 추가 할인\n  return sum;\n}\n\n/* 테스트에서는 시간을 멈추고 환율을 고정한다 */\nconst WED = Date.UTC(2024, 2, 6);   // 수요일\nconst SAT = Date.UTC(2024, 2, 9);   // 토요일\n\ntest(\"평일이면 추가 할인이 없다\", () => {\n  expect(calcOrder({ amount: 10000, currency: \"KRW\" },\n    { now: () => WED, rate: () => 1 })).toBe(10000);\n});\ntest(\"토요일이면 5% 더 깎인다\", () => {\n  expect(calcOrder({ amount: 10000, currency: \"KRW\" },\n    { now: () => SAT, rate: () => 1 })).toBe(9500);\n});\ntest(\"환율도 밖에서 넣는다\", () => {\n  expect(calcOrder({ amount: 10, currency: \"USD\" },\n    { now: () => WED, rate: () => 1300 })).toBe(13000);\n});\ntest(\"기본값이 있어 기존 호출부는 그대로 돈다\", () => {\n  expect(typeof calcOrder({ amount: 100, currency: \"KRW\" })).toBe(\"number\");\n});\n\nconsole.log(out.join(\"\\n\"));" },

  { t: "시간에 의존하는 계산을 어떻게 다룰까", type: "decide",
    goal: "만료일 계산이 <code>new Date()</code> 를 직접 부릅니다. 자정을 넘길 때만 값이 달라지는 버그가 보고되었습니다.",
    sit: "테스트로 재현하려면 어떻게 하시겠습니까?",
    opts: [
      { label: "시각을 인자로 받게 바꾸고 테스트에서 원하는 시각을 넣는다",
        fx: { system_design: 3, debugging: 2 },
        fb: "✅ 가장 단순하고 가장 오래 갑니다. 시각이 <b>입력이 되면</b> 자정 직전·직후·윤년·서머타임을 원하는 만큼 넣어 볼 수 있고, 테스트가 언제 돌아도 결과가 같습니다. 함수가 순수해지는 덤도 따라옵니다.",
        best: true },
      { label: "테스트 프레임워크의 가짜 타이머 기능으로 전역 시계를 바꿔치기한다",
        fx: { debugging: 1, system_design: -1 },
        fb: "⚠️ 동작하지만 <b>전역을 건드리는 방식</b>이라 되돌리는 것을 잊으면 다른 테스트가 이상해집니다. 코드를 고칠 수 없는 남의 라이브러리에는 유용하지만, 내 코드라면 인자로 받는 편이 낫습니다." },
      { label: "테스트를 자정이 아닌 시간대에만 돌도록 조건을 건다",
        fx: { debugging: -3, leadership: -1 },
        fb: "⚠️ 재현하려는 그 조건을 피하는 것입니다. 버그는 그대로 남고, 테스트는 '언제 도느냐에 따라 다른 것을 확인하는' 신뢰할 수 없는 것이 됩니다." },
      { label: "실행 시각을 로그로 남겨 두고 실패하면 로그를 보고 판단한다",
        fx: { debugging: -2 },
        fb: "⚠️ 사후 조사에는 도움이 되지만 <b>재현은 여전히 운에 맡기는</b> 상태입니다. 자정에만 나는 문제를 잡으려고 자정을 기다릴 수는 없습니다." }] },

  { t: "확인할 경우를 설계한다", type: "build",
    goal: "할인 규칙의 <b>경계값과 등가 분할</b>을 표로 정리하고, 그 표를 그대로 테스트로 옮기세요.\n조건이 여럿 얽혀 있으면 결정 표를 만들어 <b>정해지지 않은 조합</b>을 찾아냅니다.",
    hint: "'10만원 이상 무료 배송' 이면 99,999·100,000·100,001 셋을 봅니다. 같은 취급을 받는 값(50,000 과 70,000)은 하나만 봅니다. 테스트 러너의 표 기능(<code>test.each</code>)을 쓰면 경우를 데이터로 적을 수 있어 새 경우를 한 줄로 추가할 수 있습니다.",
    acc: "각 경계마다 아래·경계·위 세 값이 들어 있고, 표에서 결과가 정해지지 않은 조합을 최소 하나 찾아 기록했으면 완료입니다.",
    lang: "javascript",
    sol: "const out = [];\nfunction test(name, fn) {\n  try { fn(); out.push(\"PASS \" + name); }\n  catch (e) { out.push(\"FAIL \" + name + \" — \" + e.message); }\n}\nfunction expect(got) {\n  return { toBe(want) {\n    if (!Object.is(got, want))\n      throw new Error(\"기대 \" + JSON.stringify(want) + \", 실제 \" + JSON.stringify(got));\n  } };\n}\n\nfunction shippingFee(o) { return o.amount >= 100000 ? 0 : 3000; }\nfunction calcOrder(o) {\n  let sum = o.amount;\n  if (o.coupon) sum -= o.coupon;\n  if (o.grade === \"gold\") sum = Math.round(sum * 0.9);\n  if (o.first) sum = Math.round(sum * 0.9);\n  return sum;\n}\n\n/* 경계값 — 무료 배송 기준 100,000원.\n   표로 적어 두면 새 경우가 한 줄로 늘어난다. */\nconst BOUNDS = [[99999, 3000], [100000, 0], [100001, 0]];\nBOUNDS.forEach(([amount, want]) => {\n  test(\"금액 \" + amount + \" → 배송비 \" + want, () => {\n    expect(shippingFee({ amount })).toBe(want);\n  });\n});\n\n/* 결정 표 — 등급 × 쿠폰 × 첫 구매 */\nconst TABLE = [\n  [\"basic\", false, false, 10000],\n  [\"basic\", true,  false,  8000],\n  [\"gold\",  false, false,  9000],\n  [\"gold\",  true,  false,  7200],\n  [\"gold\",  false, true,   8100],\n  // [\"gold\", true, true, ???] ← 세 할인이 겹칠 때가 요구사항에 없다.\n  //   기획에 확인 요청함. 정해지기 전까지 테스트를 만들지 않는다.\n];\nTABLE.forEach(([grade, coupon, first, want]) => {\n  test(grade + \" / 쿠폰 \" + coupon + \" / 첫구매 \" + first, () => {\n    expect(calcOrder({ grade, amount: 10000, coupon: coupon ? 2000 : null, first }))\n      .toBe(want);\n  });\n});\n\nconsole.log(out.join(\"\\n\"));" },

  { t: "이 규칙을 어느 층에서 확인할까", type: "decide",
    goal: "할인 계산은 순수한 계산이고, 그 결과를 화면에 보여 주는 흐름도 있습니다. 확인할 경우는 서른 가지가 넘습니다.",
    sit: "어떻게 나누시겠습니까?",
    opts: [
      { label: "규칙 서른 가지는 단위 테스트로, 화면까지 이어지는지는 E2E 하나로 확인한다",
        fx: { system_design: 3, performance: 2 },
        fb: "✅ 층마다 <b>다른 종류의 위험</b>을 맡기는 것이 요점입니다. 계산 규칙은 입력과 출력이 분명하니 단위 테스트가 밀리초 단위로 서른 개를 끝내고, E2E 는 '조각들이 실제로 이어지는가' 하나만 봅니다. 같은 규칙을 여러 층에서 반복 확인하면 비용만 늘고 얻는 것이 없습니다.",
        best: true },
      { label: "서른 가지를 모두 E2E 로 확인해 실제와 가장 가깝게 만든다",
        fx: { performance: -3, system_design: -2 },
        fb: "⚠️ 경우 하나에 몇 초씩 걸려 스위트가 몇 분 단위로 늘어나고, 화면이 조금만 바뀌어도 서른 개가 한꺼번에 깨집니다. 현실성을 얻는 대신 <b>속도와 안정성을 모두 잃는</b> 교환입니다." },
      { label: "서른 가지를 모두 단위 테스트로 하고 E2E 는 만들지 않는다",
        fx: { system_design: -1, debugging: -1 },
        fb: "⚠️ 규칙은 완벽히 확인되지만 <b>조각들이 이어지는지</b>는 아무도 보지 않습니다. 계산은 맞는데 화면에 표시되지 않는 종류의 사고가 그대로 남습니다." },
      { label: "규칙마다 단위·통합·E2E 를 모두 만들어 빈틈을 없앤다",
        fx: { performance: -2, system_design: -2 },
        fb: "⚠️ 같은 것을 세 번 확인해도 <b>새로 알게 되는 것이 없습니다.</b> 대신 규칙이 바뀔 때마다 세 곳을 고쳐야 해서, 테스트가 변경을 막는 족쇄가 됩니다." }] },

  { t: "API 응답의 약속을 못 박는다", type: "build",
    goal: "주문 조회 API 의 <b>상태 코드·본문 구조·오류 형식·권한</b>을 테스트로 고정하세요.\n엔드포인트마다 <b>인증 없음 · 권한 없음 · 정상</b> 세 가지를 확인하는 헬퍼를 만들어 씁니다.",
    hint: "값 하나하나를 다 못 박으면 사소한 변경마다 테스트가 깨집니다. <b>클라이언트가 실제로 읽는 키</b>가 있는지와 타입이 맞는지를 봅니다. 권한 셋을 헬퍼로 만들어 두면 새 엔드포인트마다 세 줄로 끝납니다.",
    acc: "정상 응답의 필수 키가 확인되고, 인증 없음이 401·남의 자원이 403 을 돌려주며, 오류 본문의 형식이 고정되면 완료입니다.",
    lang: "javascript",
    sol: "const out = [];\nfunction test(name, fn) {\n  try { fn(); out.push(\"PASS \" + name); }\n  catch (e) { out.push(\"FAIL \" + name + \" — \" + e.message); }\n}\nfunction expect(got) {\n  return { toBe(want) {\n    if (!Object.is(got, want))\n      throw new Error(\"기대 \" + JSON.stringify(want) + \", 실제 \" + JSON.stringify(got));\n  } };\n}\n\n/* 서버 대신 가짜 API — 확인하려는 것은 '약속의 모양' 이다 */\nconst ORDERS = { 1: { id: 1, owner: \"me\", total: 9000, status: \"paid\", items: [] } };\nconst api = {\n  get(path, token) {\n    const id = path.split(\"/\")[2];\n    if (!token) return { status: 401, body: { code: \"UNAUTHENTICATED\", message: \"로그인이 필요합니다\" } };\n    const found = ORDERS[id];\n    if (!found) return { status: 404, body: { code: \"ORDER_NOT_FOUND\", message: \"주문이 없습니다\" } };\n    if (found.owner !== token) return { status: 403, body: { code: \"FORBIDDEN\", message: \"권한이 없습니다\" } };\n    return { status: 200, body: found };\n  }\n};\n\n/* 엔드포인트마다 되풀이되는 권한 셋을 헬퍼로 */\nfunction expectAuthTriple(path, mine, other) {\n  test(path + \" — 인증 없으면 401\", () => {\n    expect(api.get(path, null).status).toBe(401);\n  });\n  test(path + \" — 남의 자원이면 403\", () => {\n    expect(api.get(path, other).status).toBe(403);\n  });\n  test(path + \" — 정상이면 200\", () => {\n    expect(api.get(path, mine).status).toBe(200);\n  });\n}\nexpectAuthTriple(\"/orders/1\", \"me\", \"other\");\n\ntest(\"응답의 계약 — 클라이언트가 읽는 키가 있다\", () => {\n  const body = api.get(\"/orders/1\", \"me\").body;\n  // 값이 아니라 형태를 본다. 키가 늘어나는 것은 깨는 변경이 아니다.\n  [\"id\", \"total\", \"status\", \"items\"].forEach((k) => {\n    if (!(k in body)) throw new Error(\"계약에 있는 키가 없다: \" + k);\n  });\n  expect(typeof body.total).toBe(\"number\");\n});\n\ntest(\"오류 형식도 계약이다\", () => {\n  const res = api.get(\"/orders/999999\", \"me\");\n  expect(res.status).toBe(404);\n  expect(res.body.code).toBe(\"ORDER_NOT_FOUND\");\n  expect(typeof res.body.message).toBe(\"string\");\n});\n\nconsole.log(out.join(\"\\n\"));" },

  { t: "가끔 실패하는 테스트가 생겼다", type: "decide",
    goal: "새로 붙인 테스트 하나가 열 번에 한 번쯤 실패합니다. 다시 돌리면 통과합니다. 배포가 밀리고 있습니다.",
    sit: "어떻게 하시겠습니까?",
    opts: [
      { label: "원인을 찾을 때까지 격리해 표시하고, 담당자와 기한을 함께 정한다",
        fx: { debugging: 3, leadership: 2, communication: 1 },
        fb: "✅ 지금 당장 고칠 수 없다면 <b>스위트 전체의 신뢰를 지키는 것</b>이 우선입니다. 다만 격리는 '잊어버리기' 가 아니라 <b>기한이 붙은 유예</b> 여야 합니다. 담당자와 날짜가 없는 격리 목록은 1년 뒤에도 그대로 남아 있습니다.",
        best: true },
      { label: "실패하면 자동으로 세 번까지 재시도하도록 설정한다",
        fx: { debugging: -2, system_design: -1 },
        fb: "⚠️ 빨간불은 사라지지만 <b>원인은 그대로 남습니다.</b> 게다가 재시도로 가려진 그 불안정성이 운영에서는 열 번에 한 번 실패하는 기능일 수 있습니다 — 테스트가 알려 주려던 것을 덮은 셈입니다." },
      { label: "그 테스트를 삭제한다",
        fx: { debugging: -3, leadership: -2 },
        fb: "⚠️ 확인하던 것까지 함께 사라집니다. 흔들리는 테스트에도 대개 <b>진짜 문제가 하나 들어 있고</b>, 지우면 그 신호가 영영 없어집니다." },
      { label: "대기 시간을 넉넉히 늘려 두고 지켜본다",
        fx: { debugging: -1, performance: -1 },
        fb: "⚠️ 흔한 대응이지만 <b>스위트만 느려지고 언젠가 다시 실패합니다.</b> 고정 시간 대기 자체가 원인인 경우가 많으므로, 늘리는 대신 '조건이 만족될 때까지' 로 바꾸는 것이 진짜 해결입니다." }] },

  { t: "CI 에서 매번 돌게 만든다", type: "build",
    goal: "밀어 넣을 때마다 자동으로 돌게 하고, <b>통과해야만 병합</b>되도록 하세요.\n빠른 검사를 앞에 두고, 실패했을 때 원인이 보이도록 결과물을 남깁니다.",
    hint: "린트와 단위 테스트를 앞에 두면 대부분의 실패가 1분 안에 드러납니다. 실패했을 때 스크린숏·영상·로그를 <b>결과물로 올려 두어야</b> CI 에서만 나는 실패를 조사할 수 있습니다. '필수 검사' 지정은 워크플로가 아니라 저장소의 브랜치 보호 규칙에서 합니다.",
    acc: "PR 을 열면 검사가 자동으로 돌고, 실패한 상태에서는 병합 버튼이 막히며, 실패 시 결과물이 남으면 완료입니다.",
    lang: "yaml",
    sol: "name: test\non: [push, pull_request]\n\njobs:\n  quick:                      # 몇 십 초 안에 끝나는 것부터\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with: { node-version: \"20\", cache: \"npm\" }\n      - run: npm ci\n      - run: npm run lint\n      - run: npm run test:unit\n\n  e2e:\n    needs: quick              # 앞이 통과해야 무거운 것을 돈다\n    runs-on: ubuntu-latest\n    strategy:\n      matrix: { shard: [1, 2, 3] }   # 긴 스위트는 나눠 돌린다\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with: { node-version: \"20\", cache: \"npm\" }\n      - run: npm ci\n      - run: npx playwright test --shard=${{ matrix.shard }}/3\n      - uses: actions/upload-artifact@v4\n        if: failure()         # 실패했을 때만, 조사에 필요한 것을 남긴다\n        with:\n          name: e2e-${{ matrix.shard }}\n          path: playwright-report/\n\n# 병합을 막는 것은 이 파일이 아니라 브랜치 보호 규칙이다:\n#   Settings → Branches → Require status checks → quick, e2e" },

  { t: "비워 둔 곳을 적어 둔다", type: "note",
    goal: "여기까지 덮은 것과 <b>일부러 덮지 않은 것</b>을 나눠 적으세요.\n비워 둔 곳마다 <b>왜 비웠는지</b>와 <b>대신 무엇으로 위험을 줄이는지</b>를 함께 적습니다.",
    ph: "예: 덮음 — 할인 규칙 전 경우·권한 셋·주문 흐름 E2E 1개 / 비움 — 관리자 통계 화면(내부용, 깨져도 손해 작음), 결제 대행사 연동(샌드박스 불안정 → 모니터링 경보로 대신), 세 할인 중복(요구사항 미정 → 정해지면 추가)" }

]};
