/* Cloud 트랙 전용 프로젝트 — 빈 계정 하나로 서비스를 올린다.
   네트워크 · 권한 · 컴퓨트 · 데이터베이스 · 확장 · 관측 · 비용 · 복구까지
   한 바퀴를 돌면 '클라우드에 올린다' 는 말의 내용이 손에 남는다. */
module.exports = {
  lv: 3, em: "☁️",
  title: "빈 계정 하나로 서비스를 올린다",
  desc: "네트워크를 설계하고 최소 권한으로 잠근 뒤, 부하에 맞춰 늘어나고 장애를 견디고 비용이 새지 않는 구성을 코드로 만든다",
  skills: ["cloud", "devops", "security"],
  phases: [

  { t: "무엇을 올릴지, 무엇을 지킬지 먼저 적는다", type: "note",
    goal: "자원을 만들기 전에 <b>부하의 모양</b>과 <b>지켜야 할 숫자</b>를 적으세요.\n하루 요청 수와 몰리는 시간대, 허용되는 중단 시간(RTO), 잃어도 되는 데이터(RPO), 한 달 예산까지 정합니다.",
    ph: "예: 평일 낮 집중 · 피크 초당 200요청 · RTO 1시간 · RPO 15분 · 월 예산 80만원 · 개인정보 국내 보관 필수 · 운영은 백엔드 2명이 겸함" },

  { t: "네트워크부터 그린다", type: "build",
    goal: "VPC 와 서브넷을 만드세요. <b>퍼블릭에는 로드 밸런서와 NAT 만</b> 두고, 앱과 데이터베이스는 프라이빗에 둡니다.\n주소 범위는 나중에 연결할 다른 네트워크와 <b>겹치지 않게</b> 잡습니다.",
    hint: "서브넷이 퍼블릭인지 프라이빗인지는 이름이 아니라 <b>라우팅 테이블</b>이 정합니다. 인터넷 게이트웨이로 가는 경로가 있으면 퍼블릭입니다. AZ 는 최소 두 곳에 나누고, 서브넷 크기는 예약 5개를 빼고도 넉넉한지 계산해 두세요.",
    acc: "프라이빗 서브넷의 인스턴스에서 인터넷으로 나가는 것은 되고, 인터넷에서 그 인스턴스로 들어오는 것은 막히면 완료입니다.",
    lang: "hcl",
    sol: "# 다른 네트워크와 겹치지 않게 — 나중에 연결할 것까지 생각해서\nresource \"aws_vpc\" \"main\" {\n  cidr_block           = \"10.20.0.0/16\"\n  enable_dns_hostnames = true\n  tags = { Name = \"app\", Env = \"prod\", Team = \"pay\" }\n}\n\n# 퍼블릭 — 로드 밸런서와 NAT 만 둔다\nresource \"aws_subnet\" \"public\" {\n  for_each          = { a = \"10.20.1.0/24\", b = \"10.20.2.0/24\" }\n  vpc_id            = aws_vpc.main.id\n  cidr_block        = each.value\n  availability_zone = \"ap-northeast-2${each.key}\"\n}\n\n# 프라이빗 — 앱과 데이터베이스. /24 는 예약 5개를 빼도 251대\nresource \"aws_subnet\" \"private\" {\n  for_each          = { a = \"10.20.11.0/24\", b = \"10.20.12.0/24\" }\n  vpc_id            = aws_vpc.main.id\n  cidr_block        = each.value\n  availability_zone = \"ap-northeast-2${each.key}\"\n}\n\n# 퍼블릭으로 만드는 것은 이름이 아니라 이 경로다\nresource \"aws_route_table\" \"public\" {\n  vpc_id = aws_vpc.main.id\n  route {\n    cidr_block = \"0.0.0.0/0\"\n    gateway_id = aws_internet_gateway.igw.id\n  }\n}" },

  { t: "데이터베이스를 어디에 둘까", type: "decide",
    goal: "주문 데이터를 담을 관계형 데이터베이스가 필요합니다. RPO 는 15분, RTO 는 1시간으로 정해 두었습니다.",
    sit: "어떤 구성을 고르시겠습니까?",
    opts: [
      { label: "프라이빗 서브넷에 관리형 데이터베이스를 다중 AZ 로 두고 자동 백업을 켠다",
        fx: { database: 3, system_design: 2, security: 1 },
        fb: "✅ 정해 둔 숫자를 만족하는 가장 값싼 구성입니다. <b>다중 AZ</b> 가 자동 전환으로 RTO 를 지키고, <b>자동 백업과 시점 복원</b>이 RPO 를 지킵니다. 프라이빗에 두면 인터넷에서 닿을 경로 자체가 없어, 보안 그룹 설정을 실수해도 노출되지 않습니다.",
        best: true },
      { label: "가상 머신에 직접 설치하고 백업 스크립트를 cron 으로 돌린다",
        fx: { database: -2, system_design: -1 },
        fb: "⚠️ 패치·백업·장애 전환을 전부 직접 만들어야 합니다. 그중 하나만 빠져도 정해 둔 숫자를 못 지키는데, 대개 '복원해 본 적 없는 백업' 이 그 빠진 하나입니다. 관리형으로 안 되는 이유가 분명할 때만 고를 선택입니다." },
      { label: "퍼블릭 서브넷에 두고 보안 그룹으로 접근을 제한한다",
        fx: { security: -3, system_design: -1 },
        fb: "⚠️ 보안 그룹만으로도 막히기는 하지만, <b>설정 실수 하나가 곧바로 인터넷 노출</b>이 됩니다. 프라이빗에 두면 경로 자체가 없어 실수해도 안전합니다 — 겹을 하나 더 두는 것이 심층 방어입니다." },
      { label: "단일 AZ 로 두고 비용을 아낀 뒤 나중에 다중 AZ 로 바꾼다",
        fx: { system_design: -2, leadership: -1 },
        fb: "⚠️ 정해 둔 RTO 1시간을 지킬 수 없는 구성입니다. AZ 하나가 죽으면 새로 만들어 복원하는 데 그 이상 걸립니다. 요구를 먼저 정해 두고 그것을 못 지키는 구성을 고르는 것은 요구를 정하지 않은 것과 같습니다." }] },

  { t: "권한을 좁게 준다", type: "build",
    goal: "앱 인스턴스에 <b>역할</b>을 붙이고, 필요한 자원에만 필요한 행동만 허용하세요.\n키를 만들어 서버에 심지 않는 것이 이 단계의 요점입니다.",
    hint: "정책은 <b>기본이 거부</b>이므로 필요한 것만 적으면 됩니다. 자원에 <code>*</code> 를 쓰지 말고 버킷 이름과 경로까지 좁히세요. 조직 차원의 금지는 <code>Deny</code> 로 걸어 두면 하위에서 아무리 허용해도 뚫리지 않습니다.",
    acc: "인스턴스에서 지정한 버킷의 객체는 읽히고, 다른 버킷이나 삭제 요청은 거부되면 완료입니다.",
    lang: "json",
    sol: "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Sid\": \"ReadOwnBucketOnly\",\n      \"Effect\": \"Allow\",\n      \"Action\": [\"s3:GetObject\", \"s3:ListBucket\"],\n      \"Resource\": [\n        \"arn:aws:s3:::app-uploads-prod\",\n        \"arn:aws:s3:::app-uploads-prod/*\"\n      ]\n    },\n    {\n      \"Sid\": \"SecretsForThisAppOnly\",\n      \"Effect\": \"Allow\",\n      \"Action\": [\"secretsmanager:GetSecretValue\"],\n      \"Resource\": \"arn:aws:secretsmanager:*:*:secret:prod/app/*\"\n    },\n    {\n      \"Sid\": \"NeverDelete\",\n      \"Effect\": \"Deny\",\n      \"Action\": [\"s3:DeleteObject\", \"s3:DeleteBucket\"],\n      \"Resource\": \"*\"\n    }\n  ]\n}" },

  { t: "코드를 어디서 돌릴까", type: "decide",
    goal: "요청은 평일 낮에 몰리고 밤에는 거의 없습니다. 응답 시간은 대부분 데이터베이스 조회에서 나옵니다.",
    sit: "컴퓨트를 어떻게 고르시겠습니까?",
    opts: [
      { label: "컨테이너로 배포하고 동시 요청 수를 지표로 오토스케일을 건다",
        fx: { system_design: 3, performance: 2 },
        fb: "✅ 부하가 오르내리므로 자동 확장이 값어치를 냅니다. 지표를 <b>CPU 가 아니라 동시 요청 수</b>로 잡은 것이 핵심입니다 — 데이터베이스를 기다리는 시간이 대부분이면 CPU 는 한가한데도 이미 포화입니다. 컨테이너로 두면 배포 단위가 하나로 통일되어 환경 차이도 사라집니다.",
        best: true },
      { label: "피크에 맞춘 고정 대수의 가상 머신을 항상 켜 둔다",
        fx: { performance: -2, system_design: -1 },
        fb: "⚠️ 동작은 하지만 <b>밤과 주말에 그대로 낭비</b>됩니다. 피크가 하루 몇 시간이라면 켜 둔 시간의 대부분이 놀고 있는 셈입니다. 가장 단순한 구성이라는 장점은 있으니, 규모가 아주 작다면 선택지일 수 있습니다." },
      { label: "CPU 사용률을 지표로 오토스케일을 건다",
        fx: { performance: -2, debugging: -1 },
        fb: "⚠️ 방향은 맞지만 <b>지표가 틀렸습니다.</b> 데이터베이스 응답을 기다리는 동안 CPU 는 놀기 때문에, 서비스가 응답하지 못하는데도 스케일이 일어나지 않습니다. 무엇이 포화하는지를 먼저 재고 그 축을 지표로 삼아야 합니다." },
      { label: "요청마다 서버리스 함수로 처리한다",
        fx: { system_design: 1, database: -2 },
        fb: "⚠️ 부하 모양에는 잘 맞지만 <b>관계형 데이터베이스와의 궁합</b>이 문제입니다. 함수가 수천 개로 늘면 연결이 고갈됩니다. 연결 풀링 프록시를 앞에 두면 쓸 수 있으니, 그 준비 없이 고르면 피크에 무너집니다." },
    ] },

  { t: "받아 주고 늘어나게 만든다", type: "build",
    goal: "로드 밸런서를 퍼블릭에 두고 앱은 프라이빗에 두세요. <b>헬스 체크</b>와 <b>연결 드레이닝</b>, 그리고 <b>최소 2대 · 여러 AZ</b> 를 함께 설정합니다.",
    hint: "헬스 체크 경로는 <b>얕게</b> 두세요 — 데이터베이스까지 확인하면 아래쪽이 잠깐 흔들릴 때 모든 서버가 한꺼번에 빠집니다. 줄이는 조건은 늘리는 조건보다 느리고 둔하게 두어야 서버 수가 진동하지 않습니다.",
    acc: "인스턴스를 강제로 종료했을 때 요청이 끊기지 않고, 부하를 주면 대수가 늘었다가 부하가 사라지면 천천히 줄면 완료입니다.",
    lang: "hcl",
    sol: "resource \"aws_lb_target_group\" \"app\" {\n  port     = 8080\n  protocol = \"HTTP\"\n  vpc_id   = aws_vpc.main.id\n\n  # 얕게 본다 — 의존까지 확인하면 함께 무너진다\n  health_check {\n    path                = \"/healthz\"\n    interval            = 10\n    healthy_threshold   = 2\n    unhealthy_threshold = 3\n  }\n\n  # 진행 중인 요청이 끝날 때까지 기다렸다 뺀다\n  deregistration_delay = 30\n}\n\nresource \"aws_autoscaling_group\" \"app\" {\n  min_size            = 2      # 한 대면 그 한 대가 단일 장애점\n  max_size            = 12     # 상한은 사고 방지 장치다\n  vpc_zone_identifier = [for s in aws_subnet.private : s.id]\n  target_group_arns   = [aws_lb_target_group.app.arn]\n  health_check_type   = \"ELB\"\n}\n\n# CPU 가 아니라 동시 요청 수로 — 기다리는 시간이 대부분이므로\nresource \"aws_autoscaling_policy\" \"track\" {\n  autoscaling_group_name = aws_autoscaling_group.app.name\n  policy_type            = \"TargetTrackingScaling\"\n\n  target_tracking_configuration {\n    predefined_metric_specification {\n      predefined_metric_type = \"ALBRequestCountPerTarget\"\n    }\n    target_value     = 200\n    scale_in_cooldown  = 600   # 줄이기는 천천히\n    scale_out_cooldown = 60    # 늘리기는 빠르게\n  }\n}" },

  { t: "첫 달 요금이 예산의 두 배로 나왔다", type: "decide",
    goal: "예산은 80만원인데 명세서는 160만원입니다. 가장 큰 항목은 데이터 전송과 NAT 게이트웨이, 그다음이 인스턴스입니다.",
    sit: "무엇부터 하시겠습니까?",
    opts: [
      { label: "명세를 태그로 쪼개 보고, 안 쓰는 자원부터 걷어 낸 뒤 전송 경로를 고친다",
        fx: { system_design: 3, communication: 2, performance: 1 },
        fb: "✅ 순서가 요점입니다. <b>보이게 만들고 → 안 쓰는 것을 걷어 내고 → 구조를 고칩니다.</b> 주인 없는 디스크와 오래된 스냅숏이 대개 먼저 나오고, NAT 를 통과하던 객체 스토리지 트래픽은 <b>VPC 엔드포인트</b> 하나로 사라집니다. 이미지 앞에 CDN 을 두면 나가는 전송도 크게 줍니다.",
        best: true },
      { label: "인스턴스 타입을 한 단계씩 낮춰 전체 비용을 줄인다",
        fx: { performance: -2, system_design: -1 },
        fb: "⚠️ 가장 큰 항목이 인스턴스가 아닌데 인스턴스를 건드리는 것입니다. 게다가 사양을 낮추면 응답이 느려져 <b>대수가 늘어나</b> 오히려 비용이 그대로일 수 있습니다. 명세의 큰 항목부터 봐야 합니다." },
      { label: "1년 약정 할인을 최대한 크게 걸어 단가를 낮춘다",
        fx: { system_design: -2, leadership: -1 },
        fb: "⚠️ 안 쓰는 것을 정리하기 전에 약정하면 <b>안 쓰는 것에 더 오래 묶입니다.</b> 약정은 정리와 크기 조정이 끝난 뒤, '앞으로도 확실히 쓸 바닥 부분' 에만 겁니다." },
      { label: "결제 한도를 예산에 맞춰 걸어 그 이상 나가지 않게 한다",
        fx: { system_design: -3, leadership: -2 },
        fb: "⚠️ 한도에 걸리면 자원이 멈추거나 계정이 잠겨 <b>서비스 중단</b>으로 이어집니다. 필요한 것은 차단이 아니라 <b>예산 경보와 이상 감지</b>입니다 — 월말이 아니라 그날 알아채는 것이 목적입니다." }] },

  { t: "무슨 일이 벌어지는지 보이게 만든다", type: "build",
    goal: "로그를 구조화해 남기고, <b>사용자가 겪는 것</b>으로 경보를 거세요.\n자원 지표는 대시보드에만 두고, 호출은 오류율과 지연으로 겁니다.",
    hint: "요청 ID 를 입구에서 만들어 모든 하위 호출에 실어 보내고 로그에 함께 남기면, 흩어진 로그를 한 줄로 이을 수 있습니다. 지표 라벨에는 사용자 ID 처럼 종류가 많은 값을 넣지 마세요 — 시계열이 폭발합니다.",
    acc: "오류를 일부러 일으켰을 때 5분 안에 경보가 오고, 그 요청의 로그를 요청 ID 하나로 전부 찾을 수 있으면 완료입니다.",
    lang: "yaml",
    sol: "# 사람을 부르는 경보 — 사용자가 겪는 것으로만\nalarms:\n  - name: 오류율 급증\n    metric: HTTPCode_Target_5XX_Count / RequestCount\n    threshold: 0.05          # 5%\n    period: 300              # 5분 연속\n    action: page             # 전화\n\n  - name: 응답 꼬리 지연\n    metric: TargetResponseTime.p99\n    threshold: 2.0           # 초\n    period: 600\n    action: page\n\n  - name: 배치가 아예 돌지 않음   # 조용한 실패를 잡는다\n    metric: BatchSuccessCount\n    comparison: LessThanThreshold\n    threshold: 1\n    period: 90000            # 25시간\n    action: page\n\n# 부르지는 않고 보기만 하는 것\ndashboard_only:\n  - CPUUtilization\n  - DatabaseConnections\n  - NATGatewayBytesOut       # 비용이 튀는지 함께 본다\n\nlogging:\n  format: json\n  fields: [ts, level, req_id, user_id, route, status, ms]\n  retention_days: 30         # 감사 로그만 따로 1년\n  sampling:\n    traces: 0.05\n    always_keep: [error, slow]   # 필요한 것이 빠지면 의미가 없다" },

  { t: "재해 복구를 어디까지 준비할까", type: "decide",
    goal: "RTO 1시간 · RPO 15분으로 정해 두었습니다. 리전 전체가 죽는 경우까지 대비할지 논의 중입니다.",
    sit: "어떤 수준으로 준비하시겠습니까?",
    opts: [
      { label: "같은 리전 다중 AZ 를 기본으로 하고, 다른 리전에는 백업만 복제해 둔다",
        fx: { system_design: 3, database: 1, leadership: 1 },
        fb: "✅ 정해 둔 숫자에 맞는 균형입니다. 훨씬 자주 일어나는 <b>AZ 장애</b>는 다중 AZ 가 자동으로 막고, 드문 리전 장애에는 백업으로 대비합니다. 백업을 <b>다른 계정·다른 리전</b>에 두고 삭제 권한을 분리하면 랜섬웨어와 실수 삭제까지 함께 막힙니다.",
        best: true },
      { label: "두 리전에 똑같은 규모를 항상 돌리고 트래픽을 나눈다",
        fx: { system_design: -1, performance: 1 },
        fb: "⚠️ 가장 빠르지만 <b>비용이 두 배</b>이고 데이터 일관성 문제가 새로 생깁니다. RTO 가 1시간이라면 이 정도까지 갈 이유가 없습니다 — 정해 둔 숫자보다 과한 구성은 복잡함만 남깁니다." },
      { label: "매일 한 번 백업만 두고 장애가 나면 그때 복원한다",
        fx: { system_design: -3, database: -2 },
        fb: "⚠️ RPO 15분을 <b>구조적으로 지킬 수 없습니다.</b> 하루 한 번이면 최악의 경우 24시간치를 잃습니다. 숫자를 정해 두고 그것을 못 지키는 방식을 고르는 것은 숫자를 정하지 않은 것과 같습니다." },
      { label: "다중 AZ 만 켜 두고 리전 장애는 일어나면 대응한다",
        fx: { system_design: -1, leadership: -1 },
        fb: "⚠️ 다중 AZ 는 옳지만 <b>백업이 같은 리전에만</b> 있으면 리전 장애에서 데이터까지 함께 잃습니다. 백업을 다른 곳에 복제하는 것은 비용이 거의 들지 않으니, 이것만은 함께 해 두는 편이 낫습니다." }] },

  { t: "복원해 보고 시간을 잰다", type: "build",
    goal: "백업을 <b>실제로 복원해</b> 데이터가 맞는지 확인하고 <b>걸린 시간을 재세요.</b>\n그 시간이 곧 우리의 실제 RTO 입니다.",
    hint: "복원은 대개 <b>새 인스턴스를 만드는 방식</b>이라 접속 정보가 바뀝니다. 그 전환까지 포함해 재야 실제 시간이 나옵니다. 원본이 아닌 곳에 복원하고, 끝나면 반드시 정리해 요금이 계속 나가지 않게 합니다.",
    acc: "복원한 데이터의 행 수가 원본과 맞고, 시작부터 애플리케이션이 새 대상을 보기까지의 시간이 기록되면 완료입니다.",
    lang: "bash",
    sol: "set -euo pipefail\n\nSRC=app-prod-db\nDST=app-restore-test\nAT=\"2026-09-07T03:00:00Z\"      # 15분 전 시점으로 되돌려 본다\n\nSTART=$(date +%s)\n\n# 1) 시점 복원 — 원본은 그대로 두고 새 인스턴스로 만든다\naws rds restore-db-instance-to-point-in-time \\\n  --source-db-instance-identifier \"$SRC\" \\\n  --target-db-instance-identifier \"$DST\" \\\n  --restore-time \"$AT\" --no-publicly-accessible\n\naws rds wait db-instance-available --db-instance-identifier \"$DST\"\nEND=$(date +%s)\n\n# 2) 데이터가 맞는지 — 개수만이라도 견준다\nHOST=$(aws rds describe-db-instances --db-instance-identifier \"$DST\" \\\n  --query 'DBInstances[0].Endpoint.Address' --output text)\nSRC_N=$(psql -h \"$SRC_HOST\" -tAc 'select count(*) from orders')\nDST_N=$(psql -h \"$HOST\"     -tAc 'select count(*) from orders')\n\necho \"원본 $SRC_N / 복원 $DST_N · 복원 $((END-START))초\"\n[ \"$DST_N\" -gt 0 ] && echo \"복원 검증 통과\"\n\n# 3) 반드시 정리한다 — 연습용 인스턴스가 한 달을 돌면 그것도 사고다\naws rds delete-db-instance --db-instance-identifier \"$DST\" --skip-final-snapshot" },

  { t: "남은 위험을 적어 둔다", type: "note",
    goal: "여기까지 막은 것과 <b>아직 막지 못한 것</b>을 나눠 적으세요.\n막지 못한 것마다 <b>왜 지금은 두는지</b>와 <b>무엇이 신호가 되면 손대는지</b>를 함께 적습니다.",
    ph: "예: 막음 — AZ 장애·인스턴스 교체·실수 삭제(버전 관리)·예산 경보 / 남음 — 리전 장애(백업만 있음, 복원 4시간 예상 → RTO 초과, 매출 규모가 두 배 되면 대기 환경 검토) · 연결 고갈(현재 여유 있음, 함수 도입하면 프록시 필요) · 온콜 1명(휴가 때 공백 → 다음 분기 2명으로)" }

]};
