/* 파이썬 실습 5차 — 실습이 하나도 없던 6개 유닛을 더 연다.
   비동기 프로그래밍 · 동시성과 GIL · 측정(프로파일링) · 최적화 ·
   테스트 기초 · 아키텍처 기초.

   전부 표준 라이브러리만 쓴다 — Pyodide 안에서 인터넷 없이 돌아야 한다.
   시간을 재는 문항은 실제 시계를 쓰지 않는다. 기계가 바쁘면 결과가 흔들려서,
   같은 코드가 어떤 날은 통과하고 어떤 날은 떨어진다. 대신 잰 값을 인자로 받는다 —
   실무에서도 시간을 재는 부분과 판단하는 부분은 떼어 놓아야 시험할 수 있다. */
module.exports = [
/* ── 비동기 프로그래밍 ────────────────────────────────────── */
{
  unit: "비동기 프로그래밍",
  lesson: "직접 짜 보기 — 기다리는 동안 다른 일 하기",
  th: {
    sum: "`async` 는 빨라지는 마법이 아니다. **기다리는 동안 다른 일을 하게** 해 줄 뿐이다.",
    body: [
      { h: "기다림에만 효과가 있다", t: "네트워크 응답이나 파일을 기다리는 동안에는 CPU 가 논다. 그 시간에 다른 일을 시키는 것이 비동기다. 계산이 많은 일은 아무리 `async` 를 붙여도 빨라지지 않는다." },
      { h: "await 를 줄줄이 쓰면 순서대로다", t: "`await a()` 다음에 `await b()` 를 쓰면 a 가 끝나야 b 가 시작한다. 동시에 하려면 `asyncio.gather` 로 한꺼번에 넘겨야 한다 — 이걸 빠뜨리면 비동기로 짜고도 속도가 그대로다." },
      { h: "하나가 막으면 전부 멈춘다", t: "일꾼이 하나라, `await` 없이 오래 도는 코드가 끼면 그동안 아무것도 처리되지 않는다. `time.sleep` 이 대표적이다 — 잠깐 쉬려면 `asyncio.sleep` 을 써야 자리를 내준다." },
      { h: "실패해도 나머지는 받는다", t: "`gather` 는 기본적으로 하나가 실패하면 그 자리에서 예외를 낸다. `return_exceptions=True` 를 주면 실패한 것도 값으로 받아, 되는 것만이라도 쓸 수 있다." },
    ],
    code: { c: "results = await asyncio.gather(*tasks)          # 동시에\nresults = await asyncio.gather(*tasks, return_exceptions=True)", cap: "모아서 기다려야 겹쳐 돈다" },
    key: ["기다림에만 효과가 있다", "`gather` 로 모아서 기다린다", "막는 코드 하나가 전부를 멈춘다"],
  },
  q: [
    {
      k: "gather_all · 모아서 한꺼번에 기다리기", cat: "internals",
      qq: "코루틴 목록을 받아 <b>동시에</b> 실행하고 결과를 <b>순서대로</b> 돌려주세요.",
      src: "import asyncio\n\nLOG = []\n\n\nasync def mark(name, delay):\n    LOG.append(\"start:\" + name)\n    await asyncio.sleep(delay)\n    LOG.append(\"end:\" + name)\n    return name\n\n\nasync def gather_all(coros):\n    out = []\n    for c in coros:\n        out.append(await c)\n    return out",
      sol: "import asyncio\n\nLOG = []\n\n\nasync def mark(name, delay):\n    LOG.append(\"start:\" + name)\n    await asyncio.sleep(delay)\n    LOG.append(\"end:\" + name)\n    return name\n\n\nasync def gather_all(coros):\n    return list(await asyncio.gather(*coros))",
      /* 결과만 보면 두 방식이 같다. 그래서 '언제 시작했는가' 를 본다 —
         모아서 기다리면 둘 다 먼저 시작하고, 줄줄이 기다리면 앞의 것이 끝나야 시작한다. */
      tests: [["__import__('asyncio').run(gather_all([mark('a', 0.02), mark('b', 0)]))", "['a', 'b']"],
              ["(LOG.clear(), __import__('asyncio').run(gather_all([mark('a', 0.02), mark('b', 0)])), LOG)[2]", "['start:a', 'start:b', 'end:b', 'end:a']"],
              ["__import__('asyncio').run(gather_all([]))", "[]"]],
      edge: [["__import__('asyncio').run(gather_all([mark('x', 0)]))", "['x']"]],
      ex: "await 를 하나씩 줄줄이 쓰면 앞의 것이 끝나야 다음이 시작합니다. 결과는 같지만 걸리는 시간은 전부 더한 만큼이에요. gather 로 넘겨야 실제로 겹쳐서 진행됩니다.",
    },
    {
      k: "safe_gather · 실패해도 나머지는 받기", cat: "internals",
      qq: "코루틴 목록을 받아 성공한 것은 값, <b>실패한 것은 <code>None</code></b> 으로 채운 목록을 돌려주세요. 하나가 실패해도 나머지는 받아야 합니다.",
      src: "import asyncio\n\n\nasync def boom():\n    raise ValueError(\"실패\")\n\n\nasync def safe_gather(coros):\n    return list(await asyncio.gather(*coros))",
      sol: "import asyncio\n\n\nasync def boom():\n    raise ValueError(\"실패\")\n\n\nasync def safe_gather(coros):\n    rs = await asyncio.gather(*coros, return_exceptions=True)\n    return [None if isinstance(r, BaseException) else r for r in rs]",
      tests: [["__import__('asyncio').run(safe_gather([__import__('asyncio').sleep(0, 1)]))", "[1]"],
              ["__import__('asyncio').run(safe_gather([boom(), __import__('asyncio').sleep(0, 2)]))", "[None, 2]"],
              ["__import__('asyncio').run(safe_gather([boom()]))", "[None]"]],
      edge: [["__import__('asyncio').run(safe_gather([]))", "[]"]],
      ex: "gather 는 기본적으로 하나가 실패하면 그 자리에서 예외를 냅니다. 성공한 것까지 통째로 버려져요. return_exceptions 를 켜면 각각의 결과를 받아 되는 것만이라도 쓸 수 있습니다.",
    },
    {
      k: "blocking_ms · 진짜로 막는 시간 세기", cat: "internals",
      qq: "작업 목록을 받아 <b>이벤트 루프를 실제로 막는 시간</b>만 더해 주세요. <code>kind</code> 가 <code>'cpu'</code> 인 것만 셉니다.",
      src: "def blocking_ms(tasks):\n    return sum(t[\"ms\"] for t in tasks)",
      sol: "def blocking_ms(tasks):\n    return sum(t[\"ms\"] for t in tasks if t[\"kind\"] == \"cpu\")",
      tests: [["blocking_ms([{'kind': 'cpu', 'ms': 30}, {'kind': 'io', 'ms': 500}])", "30"],
              ["blocking_ms([{'kind': 'io', 'ms': 500}])", "0"],
              ["blocking_ms([{'kind': 'cpu', 'ms': 10}, {'kind': 'cpu', 'ms': 20}])", "30"]],
      edge: [["blocking_ms([])", "0"]],
      ex: "기다리는 시간까지 더하면 500ms 가 막힌 것처럼 보이지만, 기다리는 동안에는 다른 일이 돌아갑니다. 실제로 막는 것은 계산뿐이에요 — 이 둘을 섞으면 엉뚱한 곳을 고칩니다.",
    },
  ],
},
/* ── 동시성과 GIL ─────────────────────────────────────────── */
{
  unit: "동시성과 GIL",
  lesson: "직접 짜 보기 — 어느 쪽 일인지 가리기",
  th: {
    sum: "파이썬은 한 프로세스 안에서 **한 번에 한 줄만** 실행한다. 그래서 일의 종류부터 가려야 한다.",
    body: [
      { h: "계산이 많으면 스레드가 소용없다", t: "자물쇠를 쥔 스레드만 파이썬 코드를 돌린다. 계산이 많은 일은 스레드를 열 개 만들어도 결국 한 줄씩 도니 빨라지지 않는다. 오히려 갈아타는 비용만 는다." },
      { h: "기다리는 일은 자물쇠를 놓는다", t: "네트워크나 파일을 기다리는 동안에는 자물쇠를 놓아 준다. 그래서 기다림이 많은 일은 스레드를 늘리면 실제로 빨라진다 — 열 곳에 요청을 보내고 함께 기다리는 식이다." },
      { h: "계산은 프로세스로 나눈다", t: "프로세스마다 자물쇠가 따로 있어 진짜로 동시에 돈다. 대신 값을 넘길 때 포장했다 푸는 비용이 들어, 자료가 크면 그 비용이 이득을 갉아먹는다." },
      { h: "같이 고치는 값은 막는다", t: "스레드는 같은 변수를 본다. 둘이 동시에 고치면 하나가 덮어써져 조용히 값이 어긋난다. `Lock` 으로 한 번에 하나만 고치게 해야 한다." },
    ],
    code: { c: "기다림 많음 → ThreadPoolExecutor\n계산   많음 → ProcessPoolExecutor\n같이 고침    → with lock:", cap: "일의 종류부터 가린다" },
    key: ["계산에는 스레드가 소용없다", "기다림에는 스레드가 효과 있다", "같이 고치는 값은 막는다"],
  },
  q: [
    {
      k: "pick_pool · 어느 일꾼에게 맡길까", cat: "internals",
      qq: "작업 종류를 받아 맡길 곳을 정하세요. <code>'io'</code>는 <code>'thread'</code>, <code>'cpu'</code>는 <code>'process'</code>, 그 밖에는 <code>'inline'</code> 입니다.",
      src: "def pick_pool(kind):\n    return \"thread\"",
      sol: "def pick_pool(kind):\n    if kind == \"io\":\n        return \"thread\"\n    if kind == \"cpu\":\n        return \"process\"\n    return \"inline\"",
      tests: [["pick_pool('io')", "'thread'"],
              ["pick_pool('cpu')", "'process'"],
              ["pick_pool('none')", "'inline'"]],
      edge: [["pick_pool('')", "'inline'"]],
      ex: "계산이 많은 일에 스레드를 붙이면 아무 효과 없이 코드만 복잡해집니다. 자물쇠가 하나라 결국 한 줄씩 돌거든요. 종류를 먼저 가려야 맞는 도구를 고를 수 있습니다.",
    },
    {
      k: "speedup · 늘려서 얻는 만큼", cat: "internals",
      qq: "일꾼 수·작업 종류를 받아 <b>기대 배속</b>을 돌려주세요. <code>'io'</code>는 일꾼 수만큼, <code>'cpu'</code>는 <b>스레드면 1배</b>·<b>프로세스면 일꾼 수만큼</b>입니다.",
      src: "def speedup(workers, kind, pool):\n    return workers",
      sol: "def speedup(workers, kind, pool):\n    if kind == \"io\":\n        return workers\n    return workers if pool == \"process\" else 1",
      tests: [["speedup(4, 'io', 'thread')", "4"],
              ["speedup(4, 'cpu', 'thread')", "1"],
              ["speedup(4, 'cpu', 'process')", "4"]],
      edge: [["speedup(1, 'cpu', 'thread')", "1"],
             ["speedup(8, 'io', 'process')", "8"]],
      ex: "일꾼을 늘린 만큼 빨라진다고 보면, 계산 작업에 스레드를 잔뜩 붙여 놓고 왜 그대로인지 묻게 됩니다. 자물쇠가 하나라는 사실이 그 계산식을 바꿔요.",
    },
    {
      k: "final_count · 막지 않으면 어긋난다", cat: "internals",
      qq: "각 스레드가 올린 횟수 목록과 <b>자물쇠 사용 여부</b>를 받아 최종 값을 돌려주세요. 자물쇠를 쓰면 <b>전부 더한 값</b>, 안 쓰면 <b>가장 큰 값 하나</b>만 남습니다(덮어쓰기).",
      src: "def final_count(incs, locked):\n    return sum(incs)",
      sol: "def final_count(incs, locked):\n    if locked:\n        return sum(incs)\n    return max(incs) if incs else 0",
      tests: [["final_count([10, 20, 30], True)", "60"],
              ["final_count([10, 20, 30], False)", "30"],
              ["final_count([5], False)", "5"]],
      edge: [["final_count([], True)", "0"],
             ["final_count([], False)", "0"]],
      ex: "막지 않으면 두 스레드가 같은 값을 읽고 각자 올린 뒤 각자 씁니다. 나중에 쓴 것만 남아 나머지 증가가 통째로 사라져요 — 오류도 안 나고 숫자만 조용히 작아집니다.",
    },
  ],
},
/* ── 측정: 프로파일링 방법론 ──────────────────────────────── */
{
  unit: "측정: 프로파일링 방법론",
  lesson: "직접 짜 보기 — 짐작하지 말고 재기",
  th: {
    sum: "성능은 **재고 나서** 고친다. 짐작으로 고치면 엉뚱한 데를 고치고 시간만 쓴다.",
    body: [
      { h: "느린 곳은 대개 예상 밖이다", t: "코드를 보고 '여기가 느리겠지' 하고 고른 자리는 자주 틀린다. 재 보면 아무도 의심하지 않던 한 줄이 대부분을 차지하는 경우가 많다." },
      { h: "몇 개가 대부분을 차지한다", t: "함수 수십 개 중 상위 몇 개가 전체 시간의 대부분이다. 작은 것부터 손대면 시간만 쓰고 총 시간은 그대로다. 큰 것부터 정렬해 보는 것이 첫걸음이다." },
      { h: "전체를 얼마나 줄이는지 본다", t: "어떤 함수를 두 배 빠르게 해도, 그것이 전체의 5% 였다면 총 시간은 2.5% 밖에 안 준다. 고치기 전에 '이걸 없애면 전체가 얼마나 줄지' 를 먼저 계산한다." },
      { h: "재는 코드와 판단하는 코드를 나눈다", t: "시간을 재는 부분과 그 값을 보고 판단하는 부분을 나눠 두면, 판단 쪽을 시험할 수 있다. 붙어 있으면 실제로 오래 걸리는 일을 돌려야만 확인할 수 있다." },
    ],
    code: { c: "# 이 함수를 없애면 전체가 얼마나 줄까\ngain = fn_time / total_time", cap: "재고, 큰 것부터, 이득을 계산" },
    key: ["느린 곳은 예상 밖이다", "큰 것부터 본다", "고치기 전에 이득을 계산한다"],
  },
  q: [
    {
      k: "top_slow · 큰 것부터 보기", cat: "internals",
      qq: "함수별 걸린 시간을 받아 <b>오래 걸린 순서</b>로 상위 <code>n</code>개의 이름을 돌려주세요.",
      src: "def top_slow(times, n):\n    return sorted(times)[:n]",
      sol: "def top_slow(times, n):\n    return [k for k, _ in sorted(times.items(), key=lambda kv: -kv[1])][:n]",
      tests: [["top_slow({'a': 1, 'b': 9}, 1)", "['b']"],
              ["top_slow({'a': 1, 'b': 9, 'c': 5}, 2)", "['b', 'c']"],
              ["top_slow({'a': 1}, 5)", "['a']"]],
      edge: [["top_slow({}, 3)", "[]"],
             ["top_slow({'a': 1, 'b': 1}, 1)", "['a']"]],
      ex: "딕셔너리를 그냥 정렬하면 이름을 가나다순으로 늘어놓습니다. 걸린 시간과는 아무 상관이 없어요 — 무엇으로 정렬하는지가 이 함수의 전부입니다.",
    },
    {
      k: "overall_gain · 전체가 얼마나 줄까", cat: "internals",
      qq: "전체 시간·그 함수가 차지한 시간·<b>몇 배 빨라지는지</b>를 받아 <b>줄어드는 비율</b>을 돌려주세요. 전체가 0이면 0입니다.",
      src: "def overall_gain(total, part, factor):\n    return 1 - 1 / factor",
      sol: "def overall_gain(total, part, factor):\n    if total <= 0 or factor <= 0:\n        return 0.0\n    saved = part - part / factor\n    return saved / total",
      tests: [["overall_gain(100, 50, 2)", "0.25"],
              ["overall_gain(100, 5, 2)", "0.025"],
              ["overall_gain(100, 100, 2)", "0.5"]],
      edge: [["overall_gain(0, 10, 2)", "0.0"],
             ["overall_gain(100, 10, 1)", "0.0"]],
      ex: "'두 배 빠르게 했으니 전체가 절반' 은 그 함수가 전체일 때만 맞습니다. 5% 짜리를 두 배로 만들면 전체는 2.5% 줄어요 — 고치기 전에 이 계산을 해 보면 헛수고를 피합니다.",
    },
    {
      k: "is_regression · 느려졌다고 볼 것인가", cat: "internals",
      qq: "이전 값·지금 값·허용 비율을 받아 <b>느려졌다고 볼지</b> 판단하세요. <b>허용 비율보다 더 늘었을 때만</b> 참입니다.",
      src: "def is_regression(before, after, tolerance):\n    return after > before",
      sol: "def is_regression(before, after, tolerance):\n    if before <= 0:\n        return False\n    return (after - before) / before > tolerance",
      tests: [["is_regression(100, 130, 0.2)", "True"],
              ["is_regression(100, 110, 0.2)", "False"],
              ["is_regression(100, 90, 0.2)", "False"]],
      edge: [["is_regression(0, 100, 0.2)", "False"],
             ["is_regression(100, 120, 0.2)", "False"]],
      ex: "조금만 늘어도 경보를 울리면, 측정할 때마다 생기는 자연스러운 흔들림에 매번 걸립니다. 곧 아무도 그 경보를 안 봐요 — 허용 폭을 정해 두어야 진짜 회귀만 걸립니다.",
    },
  ],
},
/* ── 최적화: 자료구조·캐싱·벡터화 ─────────────────────────── */
{
  unit: "최적화: 자료구조·캐싱·벡터화",
  lesson: "직접 짜 보기 — 고르는 것만으로 빨라진다",
  th: {
    sum: "대부분의 최적화는 **자료구조를 바꾸는 것**으로 끝난다. 알고리즘을 새로 짤 일은 드물다.",
    body: [
      { h: "'안에 있나' 는 집합에게", t: "리스트에 `x in xs` 를 하면 처음부터 하나씩 훑는다. 목록이 10배 커지면 10배 느려진다. 집합은 몇 개가 들었든 거의 한 번에 답한다 — 순서가 필요 없다면 집합이다." },
      { h: "겹치는 계산은 기억해 둔다", t: "같은 입력으로 여러 번 부르는 함수는 결과를 기억해 두면 두 번째부터 공짜다. 다만 입력의 가짓수가 많으면 기억해 둘 자리가 계속 늘어나니, 크기를 정해 두는 것이 좋다." },
      { h: "이어 붙이기는 모았다 한 번에", t: "반복문에서 문자열에 `+=` 를 하면 매번 새 문자열이 만들어진다. 길어질수록 느려진다. 목록에 모았다가 마지막에 `join` 하면 이 낭비가 없다." },
      { h: "한 번만 훑는다", t: "같은 목록을 여러 번 도는 코드는 대개 한 번에 끝낼 수 있다. 자료가 작을 때는 티가 안 나지만, 커지면 그 차이가 그대로 시간이 된다." },
    ],
    code: { c: "seen = set(xs)          # '있나' 는 집합\n\"\".join(parts)          # 모았다 한 번에", cap: "고르는 것만으로 짧고 빨라진다" },
    key: ["'있나' 는 집합", "겹치는 계산은 기억해 둔다", "이어 붙이기는 `join`"],
  },
  q: [
    {
      k: "common · 겹치는 것 빠르게 찾기", cat: "internals",
      qq: "두 목록에서 <b>양쪽에 다 있는 값</b>을 첫 번째 목록의 <b>순서대로</b> 돌려주세요. 중복은 <b>한 번만</b> 담습니다.",
      src: "def common(a, b):\n    return [x for x in a if x in b]",
      sol: "def common(a, b):\n    bs = set(b)\n    seen = set()\n    out = []\n    for x in a:\n        if x in bs and x not in seen:\n            seen.add(x)\n            out.append(x)\n    return out",
      tests: [["common([1, 2, 3], [2, 3, 4])", "[2, 3]"],
              ["common([1, 1, 2], [1, 2])", "[1, 2]"],
              ["common([1, 2], [3])", "[]"]],
      edge: [["common([], [1])", "[]"],
             ["common([1], [])", "[]"]],
      ex: "먼저 중복을 안 걸러 같은 값이 여러 번 담깁니다. 그리고 리스트에 in 을 쓰면 값 하나마다 목록 전체를 훑어요 — 두 목록이 각각 만 개면 일억 번을 비교합니다. 한쪽을 집합으로 바꿔 두면 그 훑는 일이 사라집니다.",
    },
    {
      k: "memoize · 같은 입력은 다시 계산하지 않기", cat: "internals",
      qq: "함수를 받아 <b>같은 입력이면 지난 결과를 그대로 쓰는</b> 함수로 만들어 주세요. 실제로 부른 횟수는 <code>calls</code> 로 셉니다.",
      src: "def memoize(fn):\n    def wrapper(x):\n        return fn(x)\n    return wrapper",
      sol: "def memoize(fn):\n    cache = {}\n\n    def wrapper(x):\n        if x not in cache:\n            cache[x] = fn(x)\n        return cache[x]\n\n    return wrapper",
      tests: [["(lambda box: (lambda f: (f(2), f(2), box[0]))(memoize(lambda x: (box.__setitem__(0, box[0] + 1), x * 2)[1])))([0])", "(4, 4, 1)"],
              ["memoize(lambda x: x + 1)(1)", "2"],
              ["(lambda f: (f(1), f(2)))(memoize(lambda x: x * 10))", "(10, 20)"]],
      edge: [["memoize(lambda x: x)(0)", "0"]],
      ex: "감싸기만 하고 기억해 두지 않으면 매번 다시 계산합니다. 겉보기에는 잘 도니 '캐시를 붙였는데 왜 안 빨라지지' 로 나타나요 — 기억할 자리를 만들어야 합니다.",
    },
    {
      k: "join_all · 모았다 한 번에 붙이기", cat: "internals",
      qq: "값 목록을 받아 구분자로 이어 붙여 주세요. <b>반복문에서 문자열을 늘리지 말고</b> 한 번에 만듭니다.",
      src: "def join_all(parts, sep):\n    out = \"\"\n    for p in parts:\n        out += str(p) + sep\n    return out",
      sol: "def join_all(parts, sep):\n    return sep.join(str(p) for p in parts)",
      tests: [["join_all(['a', 'b'], ',')", "'a,b'"],
              ["join_all([1, 2, 3], '-')", "'1-2-3'"],
              ["join_all(['a'], ',')", "'a'"]],
      edge: [["join_all([], ',')", "''"],
             ["join_all(['a', 'b'], '')", "'ab'"]],
      ex: "반복문에서 += 로 늘리면 매번 새 문자열이 만들어져 길어질수록 느려집니다. 게다가 마지막에 구분자가 하나 더 붙어 결과도 틀려요 — join 은 사이에만 넣습니다.",
    },
  ],
},
/* ── 테스트 기초: 단위·통합·격리 ──────────────────────────── */
{
  unit: "테스트 기초: 단위·통합·격리",
  lesson: "직접 짜 보기 — 무엇을 어디까지 확인할 것인가",
  th: {
    sum: "테스트는 **범위**로 나뉜다. 함수 하나만 볼지, 여러 조각이 맞물리는지를 볼지.",
    body: [
      { h: "단위 테스트는 빠르고 좁다", t: "함수 하나를 바깥 의존 없이 확인한다. 빠르니 자주 돌릴 수 있고, 깨졌을 때 어디가 문제인지 바로 보인다. 대신 조각들이 맞물리는 부분은 못 잡는다." },
      { h: "통합 테스트는 느리고 넓다", t: "여러 조각을 실제로 이어 확인한다. 진짜 문제를 잡아 주지만 느려서 자주 못 돌린다. 단위 테스트를 많이, 통합 테스트를 적게 두는 것이 보통이다." },
      { h: "격리는 재현성을 위한 것", t: "테스트마다 새 자료로 시작해야 순서에 상관없이 같은 결과가 나온다. 안 그러면 따로 돌리면 통과하는데 함께 돌리면 실패하는, 가장 짜증나는 실패가 생긴다." },
      { h: "무엇을 확인하는지 이름에 적는다", t: "`test_1` 은 실패해도 아무것도 알려 주지 않는다. '무엇이 어떻게 되어야 한다' 로 적으면 실패 목록만 읽고도 상황이 보인다." },
    ],
    code: { c: "단위  : 함수 하나 · 빠름 · 많이\n통합  : 여러 조각 · 느림 · 적게\n격리  : 테스트마다 새 자료", cap: "범위를 정하고 이름에 적는다" },
    key: ["단위는 빠르고 좁다", "통합은 느리고 넓다", "테스트마다 새 자료로"],
  },
  q: [
    {
      k: "test_kind · 범위로 나누기", cat: "internals",
      qq: "테스트가 쓰는 바깥 의존 목록을 받아 종류를 정하세요. <b>하나도 없으면</b> <code>'unit'</code>, 있으면 <code>'integration'</code> 입니다.",
      src: "def test_kind(deps):\n    return \"unit\"",
      sol: "def test_kind(deps):\n    return \"unit\" if not deps else \"integration\"",
      tests: [["test_kind([])", "'unit'"],
              ["test_kind(['db'])", "'integration'"],
              ["test_kind(['db', 'http'])", "'integration'"]],
      edge: [["test_kind(None)", "'unit'"]],
      ex: "전부 단위라고 보면 느린 테스트가 빠른 무리에 섞여, 매 커밋마다 돌리는 검사가 몇 분씩 걸리게 됩니다. 범위를 나눠 두어야 무엇을 언제 돌릴지 정할 수 있어요.",
    },
    {
      k: "fresh_fixture · 테스트마다 새 자료", cat: "internals",
      qq: "기본 자료를 받아 <b>새 복사본</b>을 돌려주세요. 돌려준 것을 고쳐도 <b>원본은 그대로</b>여야 하고, 중첩된 목록까지 따로여야 합니다.",
      src: "def fresh_fixture(base):\n    return dict(base)",
      sol: "import copy\n\n\ndef fresh_fixture(base):\n    return copy.deepcopy(base)",
      tests: [["(lambda b: (fresh_fixture(b)['xs'].append(9), b['xs'])[1])({'xs': [1]})", "[1]"],
              ["fresh_fixture({'a': 1})", "{'a': 1}"],
              ["(lambda b: (fresh_fixture(b).__setitem__('a', 9), b['a'])[1])({'a': 1})", "1"]],
      edge: [["fresh_fixture({})", "{}"]],
      ex: "겉만 복사하면 안쪽 목록은 여전히 같은 것을 가리킵니다. 앞 테스트가 거기에 값을 더하면 다음 테스트가 그 값을 보게 돼요 — 순서에 따라 결과가 달라지는 테스트가 이렇게 생깁니다.",
    },
    {
      k: "test_name · 무엇이 어떻게 되어야 하는지", cat: "internals",
      qq: "대상·상황·기대를 받아 테스트 이름을 만들어 주세요. 형식은 <code>test_대상_상황_이면_기대</code> 입니다.",
      src: "def test_name(target, when, expect):\n    return \"test_\" + target",
      sol: "def test_name(target, when, expect):\n    return \"test_{}_{}_이면_{}\".format(target, when, expect)",
      tests: [["test_name('login', '비밀번호_틀림', '거부')", "'test_login_비밀번호_틀림_이면_거부'"],
              ["test_name('cart', '빈_목록', '0원')", "'test_cart_빈_목록_이면_0원'"],
              ["test_name('a', 'b', 'c')", "'test_a_b_이면_c'"]],
      edge: [["test_name('', '', '')", "'test___이면_'"]],
      ex: "이름에 대상만 적으면 실패 목록을 봐도 무엇이 잘못됐는지 알 수 없습니다. 상황과 기대까지 적어 두면 코드를 열지 않고도 상황이 보여요.",
    },
  ],
},
/* ── 아키텍처 기초: 레이어드·클린·DDD ─────────────────────── */
{
  unit: "아키텍처 기초: 레이어드·클린·DDD",
  lesson: "직접 짜 보기 — 어느 쪽을 향하게 할 것인가",
  th: {
    sum: "구조 설계의 핵심은 **의존이 어느 방향을 향하는가**다. 방향이 뒤집히면 바꾸기 어려워진다.",
    body: [
      { h: "안쪽은 바깥을 몰라야 한다", t: "업무 규칙이 데이터베이스나 화면을 직접 알면, 그것을 바꿀 때 규칙까지 함께 고쳐야 한다. 안쪽이 바깥을 모르면 바깥은 언제든 갈아 끼울 수 있다." },
      { h: "고리가 생기면 못 나눈다", t: "A 가 B 를 알고 B 가 A 를 알면 둘은 사실 하나다. 따로 시험할 수도, 따로 배포할 수도 없다. 방향을 한쪽으로 정리하면 이 매듭이 풀린다." },
      { h: "약속을 안쪽에 둔다", t: "'저장한다' 는 약속을 안쪽에 두고 바깥이 그것을 구현하면, 의존 방향이 뒤집힌다. 그래서 안쪽은 여전히 바깥을 모른 채로 바깥을 쓸 수 있다." },
      { h: "층을 건너뛰지 않는다", t: "화면이 데이터베이스를 직접 부르면 층을 나눈 의미가 사라진다. 당장은 짧아 보여도, 규칙이 두 곳에 흩어져 언젠가 어긋난다." },
    ],
    code: { c: "domain  ← application ← interface\n(안쪽)                        (바깥)\n안쪽은 바깥을 import 하지 않는다", cap: "안쪽은 바깥을 모른다" },
    key: ["안쪽은 바깥을 모른다", "고리가 생기면 못 나눈다", "층을 건너뛰지 않는다"],
  },
  q: [
    {
      k: "allowed_import · 안쪽은 바깥을 모른다", cat: "internals",
      qq: "가져오는 쪽과 가져오는 대상의 층을 받아 <b>허용되는지</b> 판단하세요. 층은 안쪽부터 <code>domain</code>·<code>application</code>·<code>interface</code> 이고, <b>바깥에서 안쪽으로만</b> 허용됩니다(같은 층도 허용).",
      src: "def allowed_import(src, dst):\n    return True",
      sol: "def allowed_import(src, dst):\n    rank = {\"domain\": 0, \"application\": 1, \"interface\": 2}\n    return rank.get(src, -1) >= rank.get(dst, -1)",
      tests: [["allowed_import('interface', 'domain')", "True"],
              ["allowed_import('domain', 'interface')", "False"],
              ["allowed_import('application', 'application')", "True"]],
      edge: [["allowed_import('domain', 'domain')", "True"],
             ["allowed_import('application', 'interface')", "False"]],
      ex: "전부 허용하면 업무 규칙이 화면과 데이터베이스를 직접 알게 됩니다. 그러면 화면 하나 바꾸는 데 규칙까지 고쳐야 하고, 규칙만 따로 시험할 수도 없어요.",
    },
    {
      k: "has_cycle · 서로 알면 하나다", cat: "internals",
      qq: "모듈 의존 목록을 받아 <b>서로 가리키는 짝</b>이 있는지 판단하세요. <code>(a, b)</code> 는 <code>a</code>가 <code>b</code>를 쓴다는 뜻입니다.",
      src: "def has_cycle(edges):\n    return len(edges) > 1",
      sol: "def has_cycle(edges):\n    s = set(edges)\n    return any((b, a) in s for a, b in s)",
      tests: [["has_cycle([('a', 'b'), ('b', 'a')])", "True"],
              ["has_cycle([('a', 'b'), ('b', 'c')])", "False"],
              ["has_cycle([('a', 'b')])", "False"]],
      edge: [["has_cycle([])", "False"],
             ["has_cycle([('a', 'a')])", "True"]],
      ex: "의존이 몇 개인지로는 아무것도 알 수 없습니다. 열 개가 줄줄이 이어져 있어도 한 방향이면 나눌 수 있어요. 서로 가리키는 짝이 있는지가 나눌 수 있느냐를 정합니다.",
    },
    {
      k: "layer_path · 층을 건너뛰지 않기", cat: "internals",
      qq: "호출 경로(층 이름 목록)를 받아 <b>층을 건너뛰지 않았는지</b> 판단하세요. 순서는 <code>interface</code> → <code>application</code> → <code>domain</code> 이고, <b>한 칸씩만</b> 내려가야 합니다.",
      src: "def layer_path(path):\n    return len(path) > 0",
      sol: "def layer_path(path):\n    rank = {\"interface\": 0, \"application\": 1, \"domain\": 2}\n    for a, b in zip(path, path[1:]):\n        if rank.get(b, -9) - rank.get(a, -9) != 1:\n            return False\n    return True",
      tests: [["layer_path(['interface', 'application', 'domain'])", "True"],
              ["layer_path(['interface', 'domain'])", "False"],
              ["layer_path(['interface'])", "True"]],
      edge: [["layer_path([])", "True"],
             ["layer_path(['domain', 'interface'])", "False"]],
      ex: "화면이 데이터베이스를 바로 부르면 당장은 코드가 짧습니다. 그런데 같은 규칙이 두 곳에 생기고, 한쪽만 고치는 날이 반드시 와요 — 그때부터 화면마다 동작이 달라집니다.",
    },
  ],
},
];
