/* 파이썬 실습 4차 — 실습이 하나도 없던 유닛 여섯 곳을 연다.

   테스트 · 예외 · 자료구조 · 표준 라이브러리 · 로깅 · 타입 힌트.
   앞의 세 차수가 '문법을 아는가' 였다면 여기는 '실무에서 무엇을 조심하는가' 다.

   전부 표준 라이브러리만 쓴다 — Pyodide 안에서 인터넷 없이 돌아야 한다.
   '예외가 나는가' 를 검사할 때는 unittest.TestCase().assertRaises 를 쓴다.
   검사식은 한 줄짜리 식이라 try 를 쓸 수 없는데, assertRaises 는 함수와 인자를
   그대로 받아 주는 한 줄 형태가 있어서 그 자리에 딱 맞는다. */
module.exports = [
/* ── 테스트 ───────────────────────────────────────────────── */
{
  unit: "테스트",
  lesson: "직접 짜 보기 — 테스트하기 좋은 함수 만들기",
  th: {
    sum: "테스트가 어려운 함수는 대개 **설계가 어려운 함수**다. 고쳐야 할 것은 테스트가 아니라 함수다.",
    body: [
      { h: "바깥을 직접 부르면 못 재 본다", t: "함수 안에서 현재 시각·난수·네트워크를 직접 부르면, 부를 때마다 답이 달라져 확인할 방법이 없다. 그 값을 **인자로 받으면** 원하는 값을 넣어 확인할 수 있다. 실무에서 '의존성 주입' 이라 부르는 것이 이 한 가지다." },
      { h: "실패 메시지가 절반이다", t: "`틀림` 이라고만 알려 주는 테스트는 어디가 틀렸는지 다시 찾아야 한다. **기대한 값과 실제 값**을 같이 적으면 메시지만 보고 바로 고칠 수 있다. 테스트는 통과할 때가 아니라 실패할 때 값을 한다." },
      { h: "경계에서 갈린다", t: "버그는 대개 한가운데가 아니라 **딱 경계**에 있다. 90점이 A인지 B인지, 빈 목록이 오면 어떻게 되는지. `>` 와 `>=` 하나 차이로 갈리는 자리를 먼저 확인한다." },
    ],
    code: { c: "def greet(hour):        # 시각을 받는다 — 안에서 now() 를 부르지 않는다\n    ...\n\nassert greet(9) == \"좋은 아침\"    # 언제 돌려도 같은 답", cap: "바깥 값을 받으면 확인할 수 있다" },
    key: ["시각·난수는 인자로 받는다", "실패 메시지에 기대·실제를 담는다", "경계값부터 확인한다"],
  },
  q: [
    {
      k: "check · 어디가 틀렸는지 말해 주기", cat: "testing",
      q: "두 값이 같으면 <b>빈 문자열</b>, 다르면 <code>\"기대: 2, 실제: 1\"</code> 꼴로 <b>두 값을 모두</b> 담은 메시지를 돌려주세요.",
      src: "def check(got, want):\n    if got == want:\n        return \"\"\n    return \"틀림\"",
      sol: "def check(got, want):\n    if got == want:\n        return \"\"\n    return \"기대: {}, 실제: {}\".format(want, got)",
      tests: [["check(1, 1)", "''"],
              ["check(1, 2)", "'기대: 2, 실제: 1'"],
              ["check('가', '나')", "'기대: 나, 실제: 가'"]],
      edge: [["check(0, 0)", "''"],
             ["check(None, 0)", "'기대: 0, 실제: None'"]],
      ex: "'틀림' 만 보고서는 무엇이 어떻게 틀렸는지 다시 찾아 나서야 합니다. 기대한 값과 실제 값을 함께 적어 두면 메시지 한 줄로 원인이 보여요.",
    },
    {
      k: "greet · 시각을 받아서 인사하기", cat: "testing",
      q: "시각(0~23)을 <b>인자로 받아</b> 인사말을 돌려주세요. 5~11시는 <code>\"좋은 아침\"</code>, 12~20시는 <code>\"안녕하세요\"</code>, 그 밖은 <code>\"안녕히 주무세요\"</code> 입니다.",
      src: "import datetime\n\n\ndef greet():\n    hour = datetime.datetime.now().hour\n    if 5 <= hour <= 11:\n        return \"좋은 아침\"\n    if 12 <= hour <= 20:\n        return \"안녕하세요\"\n    return \"안녕히 주무세요\"",
      sol: "def greet(hour):\n    if 5 <= hour <= 11:\n        return \"좋은 아침\"\n    if 12 <= hour <= 20:\n        return \"안녕하세요\"\n    return \"안녕히 주무세요\"",
      tests: [["greet(9)", "'좋은 아침'"],
              ["greet(15)", "'안녕하세요'"],
              ["greet(23)", "'안녕히 주무세요'"]],
      edge: [["greet(5)", "'좋은 아침'"],
             ["greet(0)", "'안녕히 주무세요'"]],
      ex: "함수 안에서 현재 시각을 직접 읽으면, 돌릴 때마다 답이 달라져 확인할 방법이 없습니다. 시각을 인자로 받으면 새벽 3시든 밤 11시든 마음대로 넣어 볼 수 있어요.",
    },
    {
      k: "grade · 90점은 A인가", cat: "testing",
      q: "90점 <b>이상</b>이면 <code>\"A\"</code>, 80점 <b>이상</b>이면 <code>\"B\"</code>, 그 밖은 <code>\"C\"</code> 를 돌려주세요.",
      src: "def grade(score):\n    if score > 90:\n        return \"A\"\n    if score > 80:\n        return \"B\"\n    return \"C\"",
      sol: "def grade(score):\n    if score >= 90:\n        return \"A\"\n    if score >= 80:\n        return \"B\"\n    return \"C\"",
      tests: [["grade(95)", "'A'"],
              ["grade(90)", "'A'"],
              ["grade(80)", "'B'"]],
      edge: [["grade(89)", "'B'"],
             ["grade(79)", "'C'"]],
      ex: "'이상' 은 그 값을 포함합니다. > 로 쓰면 딱 90점인 사람만 B가 되는데, 이런 버그는 한가운데 값으로만 확인하면 절대 안 보여요. 경계값을 먼저 넣어 봐야 합니다.",
    },
  ],
},
/* ── 실무 도구와 예외 심화 ────────────────────────────────── */
{
  unit: "실무 도구와 예외 심화",
  lesson: "직접 짜 보기 — 예외를 설계하기",
  th: {
    sum: "예외는 '터졌다' 가 아니라 **무엇이 왜 안 됐는지 알려 주는 값**이다.",
    body: [
      { h: "내 예외 타입을 만든다", t: "`KeyError` 를 그대로 흘려보내면, 부른 쪽은 그게 내 자료 조회 실패인지 안쪽 딕셔너리 사고인지 구분할 수 없다. `class NotFound(Exception)` 처럼 **내 이름의 예외**를 만들면 부른 쪽이 정확히 그것만 잡을 수 있다." },
      { h: "finally 는 어느 길로 나가도 지나간다", t: "`return` 으로 나가든 예외로 나가든 `finally` 블록은 반드시 실행된다. 그래서 뒷정리는 성공하는 길에 두지 말고 `finally` 에 둔다. 성공하는 길에만 두면 사고가 났을 때마다 자원이 열린 채 쌓인다." },
      { h: "하나 실패했다고 멈출 필요는 없다", t: "여러 건을 처리할 때 첫 실패에서 멈추면, 고치고 다시 돌리고를 반복하게 된다. 되는 것은 담고 안 되는 것은 따로 모아 **한 번에** 알려 주면 한 번에 고칠 수 있다." },
    ],
    code: { c: "class NotFound(Exception):\n    pass\n\ntry:\n    ...\nfinally:\n    res[\"closed\"] = True   # 어느 길로 나가도 실행된다", cap: "내 예외 + finally 뒷정리" },
    key: ["내 예외 타입을 만든다", "뒷정리는 `finally`", "실패를 모아 한 번에 알린다"],
  },
  q: [
    {
      k: "find · 내 이름의 예외로 알리기", cat: "internals",
      q: "키가 없으면 <code>NotFound</code> 를 던지세요. 어떤 키였는지 <code>key</code> 속성에 담아 주세요.",
      src: "class NotFound(Exception):\n    def __init__(self, key):\n        super().__init__(key)\n        self.key = key\n\n\ndef find(m, k):\n    return m[k]",
      sol: "class NotFound(Exception):\n    def __init__(self, key):\n        super().__init__(key)\n        self.key = key\n\n\ndef find(m, k):\n    if k not in m:\n        raise NotFound(k)\n    return m[k]",
      tests: [["find({'a': 1}, 'a')", "1"],
              ["__import__('unittest').TestCase().assertRaises(NotFound, find, {}, 'x') is None", "True"],
              ["issubclass(NotFound, Exception)", "True"]],
      edge: [["find({'a': 0}, 'a')", "0"]],
      ex: "m[k] 를 그대로 두면 KeyError 가 나갑니다. 부른 쪽은 그게 우리 조회 실패인지 안쪽 코드의 사고인지 구분할 수 없어요. 내 이름의 예외를 던지면 그것만 콕 집어 잡을 수 있습니다.",
    },
    {
      k: "use · 사고가 나도 닫기", cat: "internals",
      q: "<code>fail</code> 이 참이면 <code>ValueError</code> 를 던집니다. 어느 쪽이든 <code>res[\"closed\"]</code> 를 <b>반드시</b> <code>True</code> 로 만드세요.",
      src: "def use(res, fail):\n    if fail:\n        raise ValueError(\"실패\")\n    res[\"closed\"] = True\n    return \"ok\"",
      sol: "def use(res, fail):\n    try:\n        if fail:\n            raise ValueError(\"실패\")\n        return \"ok\"\n    finally:\n        res[\"closed\"] = True",
      tests: [["(lambda r: (use(r, False), r['closed'])[1])({})", "True"],
              ["(lambda r: (__import__('unittest').TestCase().assertRaises(ValueError, use, r, True), r.get('closed'))[1])({})", "True"],
              ["use({}, False)", "'ok'"]],
      edge: [["(lambda r: (__import__('unittest').TestCase().assertRaises(ValueError, use, r, True), len(r))[1])({})", "1"]],
      ex: "성공하는 길에만 뒷정리를 두면, 사고가 날 때마다 자원이 열린 채로 남습니다. finally 는 return 으로 나가든 예외로 나가든 반드시 지나가는 자리예요.",
    },
    {
      k: "parse_all · 되는 것과 안 되는 것을 나누기", cat: "internals",
      q: "글자 목록을 숫자로 바꿔 <code>(성공한 값들, 실패한 글자들)</code> 을 돌려주세요. 하나가 실패해도 <b>끝까지</b> 확인합니다.",
      src: "def parse_all(items):\n    out = []\n    for s in items:\n        out.append(int(s))\n    return out, []",
      sol: "def parse_all(items):\n    out = []\n    bad = []\n    for s in items:\n        try:\n            out.append(int(s))\n        except ValueError:\n            bad.append(s)\n    return out, bad",
      tests: [["parse_all(['1', '2'])", "([1, 2], [])"],
              ["parse_all(['1', 'x', '3'])", "([1, 3], ['x'])"],
              ["parse_all(['x', 'y'])", "([], ['x', 'y'])"]],
      edge: [["parse_all([])", "([], [])"]],
      ex: "첫 실패에서 멈추면 사용자는 하나 고치고 다시 올리기를 반복해야 합니다. 끝까지 보고 잘못된 것을 모아 알려 주면 한 번에 고칠 수 있어요.",
    },
  ],
},
/* ── 자료구조와 복잡도 ────────────────────────────────────── */
{
  unit: "자료구조와 복잡도",
  lesson: "직접 짜 보기 — 자료구조를 고르는 눈",
  th: {
    sum: "자료구조를 잘못 고르면 **코드는 맞는데 느리다.** 그리고 느린 코드는 자료가 커진 다음에야 티가 난다.",
    body: [
      { h: "'안에 있나' 는 집합에게", t: "리스트에 `x in xs` 를 하면 처음부터 하나씩 훑는다. 목록이 10배 커지면 10배 느려진다. 집합(`set`)은 몇 개가 들었든 거의 한 번에 답한다. 순서가 필요 없고 '있는지' 만 물을 거라면 집합이다." },
      { h: "묶어 담을 때는 리스트를 미리 만든다", t: "`d[k].append(v)` 는 `k` 가 처음 나오면 터진다. `d.setdefault(k, []).append(v)` 나 `defaultdict(list)` 를 쓰면 없을 때 알아서 만들어 준다. 이 한 줄 차이로 if 문이 사라진다." },
      { h: "나머지 연산이 경계를 지운다", t: "목록을 `k`칸 돌릴 때 `k` 가 길이보다 크면 그대로는 범위를 벗어난다. `k % len(xs)` 로 먼저 접어 두면 k가 얼마든 안전하다. 길이가 0일 때만 따로 챙기면 된다." },
    ],
    code: { c: "seen = set()          # '봤나' 는 집합에게\nd.setdefault(k, []).append(v)   # 없으면 만들어 준다\nk %= len(xs)          # 큰 k 를 접어 둔다", cap: "고르는 것만으로 코드가 짧아진다" },
    key: ["'있나' 는 집합", "묶기는 `setdefault`", "회전은 `% len`"],
  },
  q: [
    {
      k: "first_dup · 처음 두 번째로 나온 값", cat: "internals",
      q: "<b>처음으로</b> 두 번째 등장한 값을 돌려주세요. 겹치는 값이 없으면 <code>None</code> 입니다.",
      src: "def first_dup(xs):\n    found = None\n    seen = set()\n    for x in xs:\n        if x in seen:\n            found = x\n        seen.add(x)\n    return found",
      sol: "def first_dup(xs):\n    seen = set()\n    for x in xs:\n        if x in seen:\n            return x\n        seen.add(x)\n    return None",
      tests: [["first_dup([1, 2, 3, 2, 1])", "2"],
              ["first_dup([1, 2, 3])", "None"],
              ["first_dup(['가', '나', '가', '나'])", "'가'"]],
      edge: [["first_dup([])", "None"],
             ["first_dup([7, 7])", "7"]],
      ex: "끝까지 돌면서 계속 덮어쓰면 '마지막' 으로 겹친 값이 남습니다. 처음 것을 원하면 찾자마자 돌려줘야 하고, 그게 더 빠르기도 해요.",
    },
    {
      k: "group_by_len · 길이별로 묶기", cat: "internals",
      q: "낱말을 <b>길이별로</b> 묶어 딕셔너리로 돌려주세요. 값은 <b>들어온 순서</b>를 지킨 리스트입니다.",
      src: "def group_by_len(words):\n    d = {}\n    for w in words:\n        d[len(w)] = [w]\n    return d",
      sol: "def group_by_len(words):\n    d = {}\n    for w in words:\n        d.setdefault(len(w), []).append(w)\n    return d",
      tests: [["group_by_len(['가', '나다', '라'])", "{1: ['가', '라'], 2: ['나다']}"],
              ["group_by_len(['ab', 'cd'])", "{2: ['ab', 'cd']}"],
              ["group_by_len([])", "{}"]],
      edge: [["group_by_len([''])", "{0: ['']}"]],
      ex: "d[k] = [w] 는 이미 담아 둔 것을 통째로 버리고 새 리스트로 갈아 끼웁니다. setdefault 는 없을 때만 빈 리스트를 만들어 주고, 있으면 그대로 돌려줘서 뒤에 붙일 수 있어요.",
    },
    {
      k: "rotate · k가 길이보다 커도", cat: "internals",
      q: "리스트를 왼쪽으로 <code>k</code>칸 돌린 <b>새 리스트</b>를 돌려주세요. <code>k</code> 가 길이보다 커도 맞아야 합니다.",
      src: "def rotate(xs, k):\n    return xs[k:] + xs[:k]",
      sol: "def rotate(xs, k):\n    if not xs:\n        return []\n    k %= len(xs)\n    return xs[k:] + xs[:k]",
      tests: [["rotate([1, 2, 3], 1)", "[2, 3, 1]"],
              ["rotate([1, 2, 3], 5)", "[3, 1, 2]"],
              ["rotate([1, 2, 3], 3)", "[1, 2, 3]"]],
      edge: [["rotate([], 2)", "[]"],
             ["rotate([1, 2, 3], 0)", "[1, 2, 3]"]],
      ex: "슬라이스는 범위를 넘어가도 에러를 내지 않고 조용히 빈 리스트를 줍니다. 그래서 k가 크면 결과가 그냥 원본이 돼 버려요. % 로 한 바퀴 접어 두면 k가 얼마든 맞습니다.",
    },
  ],
},
/* ── 표준 라이브러리 실무 ─────────────────────────────────── */
{
  unit: "표준 라이브러리 실무",
  lesson: "직접 써 보기 — 이미 있는 것을 쓰기",
  th: {
    sum: "표준 라이브러리를 모르면 **이미 있는 것을 다시 만든다.** 대개 더 느리고 더 자주 틀린다.",
    body: [
      { h: "Counter 는 세는 일을 다 한다", t: "`Counter(words)` 는 한 번만 훑으며 개수를 센다. `most_common(n)` 은 많은 순으로 n개를 주는데, **같은 개수면 먼저 나온 것이 앞**이다. 직접 정렬하면 이 순서가 흔들려 결과가 들쭉날쭉해진다." },
      { h: "groupby 는 정렬을 먼저 요구한다", t: "`itertools.groupby` 는 **붙어 있는 같은 값**만 묶는다. 흩어져 있으면 같은 키가 여러 덩어리로 나뉜다. 그래서 같은 기준으로 **정렬한 뒤에** 넘겨야 한다 — 이걸 모르면 결과가 반쯤만 맞는다." },
      { h: "날짜는 문자열이 아니다", t: "`\"2024-03-01\"` 을 글자로 비교하면 형식이 조금만 달라져도 어긋난다. `datetime.strptime` 으로 날짜로 바꾸면 뺄셈이 되고, 뺀 결과의 `.days` 가 며칠인지 알려 준다." },
    ],
    code: { c: "from collections import Counter\nCounter(words).most_common(2)\n\nfrom datetime import datetime\n(datetime.strptime(b, \"%Y-%m-%d\") - datetime.strptime(a, \"%Y-%m-%d\")).days", cap: "세기와 날짜는 이미 만들어져 있다" },
    key: ["세기는 `Counter`", "`groupby` 전에 정렬", "날짜는 `strptime` 으로"],
  },
  q: [
    {
      k: "top_words · 많이 나온 낱말", cat: "internals",
      q: "문장에서 많이 나온 낱말 <code>n</code>개를 <code>[(낱말, 횟수)]</code> 로 돌려주세요. <b>대소문자는 같은 낱말</b>로 봅니다.",
      src: "from collections import Counter\n\n\ndef top_words(text, n):\n    return Counter(text.split()).most_common(n)",
      sol: "from collections import Counter\n\n\ndef top_words(text, n):\n    return Counter(text.lower().split()).most_common(n)",
      tests: [["top_words('a b A b b', 1)", "[('b', 3)]"],
              ["top_words('a b A', 2)", "[('a', 2), ('b', 1)]"],
              ["top_words('x', 3)", "[('x', 1)]"]],
      edge: [["top_words('', 2)", "[]"]],
      ex: "'A' 와 'a' 를 다른 낱말로 세면, 문장 첫머리에 온 낱말만 따로 세어져 순위가 어긋납니다. 세기 전에 기준을 하나로 맞춰 두는 것이 먼저예요.",
    },
    {
      k: "by_first · 첫 글자로 묶기", cat: "internals",
      q: "낱말을 <b>첫 글자별로</b> 묶어 <code>{첫 글자: [낱말들]}</code> 로 돌려주세요. 순서가 뒤섞여 들어와도 한 글자에 <b>한 덩어리</b>여야 합니다.",
      src: "from itertools import groupby\n\n\ndef by_first(words):\n    return {k: list(g) for k, g in groupby(words, key=lambda w: w[0])}",
      sol: "from itertools import groupby\n\n\ndef by_first(words):\n    ws = sorted(words, key=lambda w: w[0])\n    return {k: list(g) for k, g in groupby(ws, key=lambda w: w[0])}",
      tests: [["by_first(['ax', 'bx', 'ay'])", "{'a': ['ax', 'ay'], 'b': ['bx']}"],
              ["by_first(['ax', 'ay'])", "{'a': ['ax', 'ay']}"],
              ["len(by_first(['ax', 'bx', 'ay']))", "2"]],
      edge: [["by_first([])", "{}"]],
      ex: "groupby 는 나란히 붙어 있는 같은 값만 묶습니다. 'ax','bx','ay' 처럼 흩어져 있으면 a가 두 덩어리로 나뉘고, 딕셔너리로 만들 때 뒤엣것이 앞엣것을 덮어써요. 먼저 정렬해야 합니다.",
    },
    {
      k: "days_between · 며칠 차이인가", cat: "internals",
      q: "<code>\"YYYY-MM-DD\"</code> 두 개를 받아 <b>며칠 차이</b>인지 돌려주세요. 순서를 바꿔 넣어도 <b>같은 값</b>이어야 합니다.",
      src: "from datetime import datetime\n\n\ndef days_between(a, b):\n    fmt = \"%Y-%m-%d\"\n    return (datetime.strptime(b, fmt) - datetime.strptime(a, fmt)).days",
      sol: "from datetime import datetime\n\n\ndef days_between(a, b):\n    fmt = \"%Y-%m-%d\"\n    return abs((datetime.strptime(b, fmt) - datetime.strptime(a, fmt)).days)",
      tests: [["days_between('2024-03-01', '2024-03-05')", "4"],
              ["days_between('2024-03-05', '2024-03-01')", "4"],
              ["days_between('2024-02-28', '2024-03-01')", "2"]],
      edge: [["days_between('2024-03-01', '2024-03-01')", "0"]],
      ex: "뺄셈은 순서에 따라 음수가 나옵니다. '며칠 차이' 는 방향이 없는 값이니 abs 로 감싸야 해요. 그리고 2024년은 윤년이라 2월이 29일까지 있는데, 날짜로 바꿔 계산하면 이런 것을 신경 쓸 필요가 없습니다.",
    },
  ],
},
/* ── 로깅과 에러 처리 실무 ────────────────────────────────── */
{
  unit: "로깅과 에러 처리 실무",
  lesson: "직접 짜 보기 — 나중에 읽을 수 있는 기록 남기기",
  th: {
    sum: "기록은 **사고가 난 뒤에** 읽는다. 그때 읽을 수 없으면 남긴 의미가 없다.",
    body: [
      { h: "예외 이름을 빼면 못 찾는다", t: "`str(e)` 만 남기면 `division by zero` 같은 문장만 남는다. 어떤 종류의 사고였는지가 사라져서 검색도 분류도 안 된다. `type(e).__name__` 을 함께 남기면 `ZeroDivisionError: division by zero` 가 되어 한눈에 보인다." },
      { h: "잡을 것만 잡는다", t: "`except Exception` 은 내가 예상한 실패뿐 아니라 **오타로 생긴 사고까지** 삼킨다. 그러면 프로그램은 조용히 이상한 값을 내놓고 계속 간다. 예상한 것만 이름을 적어 잡고, 나머지는 위로 올려보내야 한다." },
      { h: "삼킨 예외는 사라진 단서다", t: "`except: pass` 는 그 순간 원인을 지워 버린다. 나중에 '왜 값이 비지' 를 거슬러 올라가는 시간이 처음부터 터뜨렸을 때보다 훨씬 오래 걸린다." },
    ],
    code: { c: "except ValueError as e:      # 예상한 것만\n    log(\"{}: {}\".format(type(e).__name__, e))\n\nexcept Exception:            # 오타까지 삼킨다\n    pass", cap: "이름을 남기고, 잡을 것만 잡는다" },
    key: ["예외 이름을 함께 남긴다", "`except Exception` 은 너무 넓다", "삼킨 예외는 단서가 사라진다"],
  },
  q: [
    {
      k: "describe · 어떤 사고였는지 남기기", cat: "internals",
      q: "예외 객체를 받아 <code>\"ValueError: 음수\"</code> 처럼 <b>종류와 내용</b>을 모두 담은 한 줄을 돌려주세요.",
      src: "def describe(e):\n    return str(e)",
      sol: "def describe(e):\n    return \"{}: {}\".format(type(e).__name__, e)",
      tests: [["describe(ValueError('음수'))", "'ValueError: 음수'"],
              ["describe(KeyError('a'))", "\"KeyError: 'a'\""],
              ["describe(TypeError(''))", "'TypeError: '"]],
      edge: [["describe(Exception('x'))", "'Exception: x'"]],
      ex: "내용만 남기면 'a' 같은 문장 하나가 덩그러니 남습니다. 종류를 함께 남겨야 같은 사고를 모아 세거나 검색할 수 있어요.",
    },
    {
      k: "safe_run · 실패해도 정보는 남기기", cat: "internals",
      q: "함수를 실행해 성공하면 <code>(True, 결과)</code>, 실패하면 <code>(False, 예외 이름)</code> 을 돌려주세요.",
      src: "def safe_run(fn):\n    try:\n        return True, fn()\n    except Exception:\n        return False, \"실패\"",
      sol: "def safe_run(fn):\n    try:\n        return True, fn()\n    except Exception as e:\n        return False, type(e).__name__",
      tests: [["safe_run(lambda: 1 + 1)", "(True, 2)"],
              ["safe_run(lambda: 1 / 0)", "(False, 'ZeroDivisionError')"],
              ["safe_run(lambda: int('x'))", "(False, 'ValueError')"]],
      edge: [["safe_run(lambda: None)", "(True, None)"]],
      ex: "'실패' 라고만 적으면 모든 사고가 똑같아 보입니다. 예외 이름만 남겨도 나눗셈 문제인지 형식 문제인지 바로 갈려요.",
    },
    {
      k: "parse · 예상한 것만 잡기", cat: "internals",
      q: "글자를 숫자로 바꾸되, <b>숫자가 아닌 글자</b>면 <code>None</code> 을 돌려주세요. 글자가 아닌 것(<code>None</code> 등)이 들어오면 <b>그대로 터지게</b> 두세요.",
      src: "def parse(s):\n    try:\n        return int(s)\n    except Exception:\n        return None",
      sol: "def parse(s):\n    try:\n        return int(s)\n    except ValueError:\n        return None",
      tests: [["parse('12')", "12"],
              ["parse('x')", "None"],
              ["__import__('unittest').TestCase().assertRaises(TypeError, parse, None) is None", "True"]],
      edge: [["parse('0')", "0"],
             ["parse(' 7 ')", "7"]],
      ex: "except Exception 은 형식이 아예 잘못된 것(TypeError)까지 삼켜 None 으로 만들어 버립니다. 그러면 부르는 쪽 버그가 조용히 묻혀요. 예상한 실패만 이름을 적어 잡아야 합니다.",
    },
  ],
},
/* ── 타입 힌트와 정적 검사 심화 ───────────────────────────── */
{
  unit: "타입 힌트와 정적 검사 심화",
  lesson: "직접 써 보기 — 타입으로 막을 수 있는 사고",
  th: {
    sum: "타입 힌트는 **주석이 아니라 약속**이다. 잘 쓰면 돌려 보기 전에 사고를 막는다.",
    body: [
      { h: "기본값에 빈 리스트를 두면 안 된다", t: "`def add(x, bag=[])` 의 리스트는 함수를 정의할 때 **딱 한 번** 만들어져 모든 호출이 나눠 쓴다. 두 번째 호출에 첫 번째 값이 남아 있다. 기본값은 `None` 으로 두고 안에서 새로 만든다 — 힌트로는 `Optional[list]` 다." },
      { h: "얼려 두면 못 바꾼다", t: "`@dataclass(frozen=True)` 는 만든 뒤 값을 바꾸려 하면 막는다. 좌표·설정처럼 '한 번 정해지면 끝' 인 것에 쓰면, 실수로 고치는 코드가 돌기 전에 걸린다. 덤으로 딕셔너리 키로도 쓸 수 있다." },
      { h: "Protocol 은 '모양' 으로 받는다", t: "상속을 요구하지 않고 **필요한 메서드가 있는지**만 본다. 남이 만든 클래스를 고치지 않고도 내 함수에 넘길 수 있다. `@runtime_checkable` 을 붙이면 `isinstance` 로도 확인할 수 있다." },
    ],
    code: { c: "def add(x, bag: list | None = None) -> list:\n    if bag is None:\n        bag = []\n    ...\n\n@dataclass(frozen=True)\nclass Point:\n    x: int", cap: "기본값은 None, 안 바뀔 것은 frozen" },
    key: ["가변 기본값은 공유된다", "`frozen=True` 로 잠근다", "`Protocol` 은 모양만 본다"],
  },
  q: [
    {
      k: "add_item · 기본값이 남아 있지 않게", cat: "internals",
      q: "값을 담아 목록을 돌려주세요. <code>bag</code> 을 안 넘기면 <b>매번 새 목록</b>에서 시작해야 합니다.",
      src: "def add_item(x, bag=[]):\n    bag.append(x)\n    return bag",
      sol: "def add_item(x, bag=None):\n    if bag is None:\n        bag = []\n    bag.append(x)\n    return bag",
      tests: [["add_item(1)", "[1]"],
              ["(lambda a, b: b)(add_item(1), add_item(2))", "[2]"],
              ["add_item(3, [9])", "[9, 3]"]],
      edge: [["(lambda a, b, c: c)(add_item('가'), add_item('나'), add_item('다'))", "['다']"]],
      ex: "기본값 리스트는 함수를 정의할 때 딱 한 번 만들어져 모든 호출이 같은 것을 씁니다. 그래서 두 번째 호출에 첫 번째 값이 남아 있어요. None 을 기본값으로 두고 안에서 만들면 매번 새것입니다.",
    },
    {
      k: "Point · 만든 뒤에는 못 바꾸게", cat: "internals",
      q: "<code>x</code>, <code>y</code> 를 담는 <code>Point</code> 를 데이터클래스로 만드세요. 만든 뒤에는 <b>값을 바꿀 수 없어야</b> 합니다.",
      src: "from dataclasses import dataclass\n\n\n@dataclass\nclass Point:\n    x: int\n    y: int",
      sol: "from dataclasses import dataclass\n\n\n@dataclass(frozen=True)\nclass Point:\n    x: int\n    y: int",
      tests: [["Point(1, 2).x", "1"],
              ["Point.__dataclass_params__.frozen", "True"],
              ["Point(1, 2) == Point(1, 2)", "True"]],
      edge: [["len({Point(1, 2), Point(1, 2)})", "1"]],
      ex: "frozen=True 를 붙이면 값을 바꾸려는 코드가 그 자리에서 막힙니다. 그리고 바뀌지 않는다는 보장이 생겨서 집합에 넣거나 딕셔너리 키로도 쓸 수 있어요.",
    },
    {
      k: "Named · 상속 없이 모양만 보기", cat: "internals",
      q: "<code>name</code> 속성을 가진 것이면 무엇이든 통과하는 <code>Named</code> 를 만드세요. <code>isinstance</code> 로 확인할 수 있어야 합니다.",
      src: "from typing import Protocol\n\n\nclass Named(Protocol):\n    name: str\n\n\nclass Dog:\n    def __init__(self, name):\n        self.name = name",
      sol: "from typing import Protocol, runtime_checkable\n\n\n@runtime_checkable\nclass Named(Protocol):\n    name: str\n\n\nclass Dog:\n    def __init__(self, name):\n        self.name = name",
      tests: [["isinstance(Dog('바둑'), Named)", "True"],
              ["isinstance(3, Named)", "False"],
              ["Dog('바둑').name", "'바둑'"]],
      /* issubclass 로는 확인하지 않는다 — 속성을 가진 Protocol 은 issubclass 를 아예 거부한다.
         '이 객체가 그 모양인가' 만 물을 수 있고, '이 클래스가 그 모양인가' 는 못 묻는다. */
      edge: [["isinstance(object(), Named)", "False"]],
      ex: "Protocol 은 원래 정적 검사기만 보는 약속이라, 그냥 두면 isinstance 가 거부합니다. @runtime_checkable 을 붙이면 돌아가는 중에도 '이 모양이 맞나' 를 물어볼 수 있어요.",
    },
  ],
},
];
