/* 파이썬 중급·심화 유닛 실습 (3차).
   1차 기초 8개, 2차 중급 8개를 채웠다. 여기서는 매직 메서드·프로퍼티·제너레이터·
   functools·정규식·데이터클래스·statistics·CSV 처럼 '라이브러리를 아는가' 가 갈리는 곳.

   전부 표준 라이브러리만 쓴다 — Pyodide 안에서 인터넷 없이 돈다.
   파일은 실제 파일 대신 io.StringIO 로 다룬다. 브라우저에는 진짜 파일 시스템이 없다. */
module.exports = [
{
  unit: "파이썬 중급",
  lesson: "직접 써 보기 — 풀어 담고 묶어 넘기기",
  th: {
    sum: "`*` 와 `**` 는 **묶을 때**와 **풀 때** 뜻이 반대다. 정의부에서는 모으고, 호출부에서는 흩뿌린다.",
    body: [
      { h: "모으기와 흩뿌리기", t: "`def f(*args)` 는 남는 위치 인자를 튜플로 **모은다.** `f(*xs)` 는 리스트를 인자 여러 개로 **푼다.** 같은 별표인데 자리가 다르면 반대로 동작한다 — 이걸 헷갈리면 인자가 하나로 뭉쳐 들어가거나 개수가 안 맞는다." },
      { h: "키워드 전용 인자", t: "`def f(a, *, verbose=False)` 처럼 별표를 홀로 두면 그 뒤는 **이름을 적어야만** 넘길 수 있다. 불리언 인자를 위치로 넘겨 `f(x, True)` 라고 쓰면 나중에 그 True 가 무슨 뜻인지 아무도 모른다 — 그걸 막는 장치다." },
    ],
    code: { c: "def f(*args, **kw): ...   # 모은다\nf(*xs, **opts)            # 푼다\n\ndef g(a, *, loud=False): ...\ng(1, loud=True)           # 이름 필수", cap: "정의부는 모으고 호출부는 푼다" },
    key: ["정의부의 `*` 는 모으기", "호출부의 `*` 는 풀기", "`*` 뒤 인자는 이름으로만"],
  },
  q: [
    {
      k: "call_with · 목록을 인자로 풀어 넘기기", cat: "internals",
      q: "인자 목록을 담은 리스트와 함수를 받아, <b>그 값들을 각각의 인자로</b> 넘겨 부른 결과를 돌려주세요.",
      src: "def call_with(fn, args):\n    return fn(args)",
      sol: "def call_with(fn, args):\n    return fn(*args)",
      tests: [["call_with(lambda a, b: a + b, [1, 2])", "3"],
              ["call_with(lambda a, b, c: a * b * c, [2, 3, 4])", "24"],
              ["call_with(lambda: 7, [])", "7"]],
      edge: [["call_with(lambda x: x, [5])", "5"]],
      ex: "fn(args) 는 리스트 하나를 통째로 넘깁니다. 인자 두 개를 받는 함수에 리스트 하나가 가서 개수가 안 맞아요. 별표를 붙여 풀어 줘야 합니다.",
    },
    {
      k: "tag · 키워드 전용 인자", cat: "internals",
      q: "글자를 감싸는 함수를 만드세요. <code>upper</code> 는 <b>이름으로만</b> 넘길 수 있어야 합니다 — 위치로는 넘길 수 없게 막으세요.",
      src: "def tag(text, name, upper=False):\n    inner = text.upper() if upper else text\n    return \"<\" + name + \">\" + inner + \"</\" + name + \">\"",
      sol: "def tag(text, name, *, upper=False):\n    inner = text.upper() if upper else text\n    return \"<\" + name + \">\" + inner + \"</\" + name + \">\"",
      tests: [["tag('hi', 'b')", "'<b>hi</b>'"],
              ["tag('hi', 'b', upper=True)", "'<b>HI</b>'"],
              ["__import__('inspect').signature(tag).parameters['upper'].kind.name", "'KEYWORD_ONLY'"]],
      edge: [["tag('', 'i')", "'<i></i>'"]],
      ex: "별표를 홀로 두면 그 뒤 인자는 이름으로만 받습니다. 이게 없으면 tag('hi','b',True) 가 통과하는데, 나중에 그 True 가 무슨 뜻인지 읽는 사람이 알 수 없어요.",
    },
  ],
},
{
  unit: "매직 메서드",
  lesson: "직접 써 보기 — 파이썬이 부르는 이름들",
  th: {
    sum: "매직 메서드는 파이썬이 **대신 불러 주는** 약속된 이름이다. `len(x)` 는 `x.__len__()` 을, `x == y` 는 `x.__eq__(y)` 를 부른다.",
    body: [
      { h: "eq 와 hash 는 짝", t: "`__eq__` 만 정의하면 그 객체는 **해시할 수 없게 된다.** 파이썬이 자동으로 `__hash__` 를 None 으로 만들기 때문이다. 집합이나 딕셔너리 열쇠로 쓰려면 `__hash__` 도 함께 정의한다 — 값이 같으면 해시도 같아야 한다." },
      { h: "repr 과 str", t: "`__repr__` 은 개발자가 보는 표현이고 `__str__` 은 사용자가 보는 표현이다. `__str__` 이 없으면 `__repr__` 이 대신 쓰인다. 그래서 하나만 만든다면 `__repr__` 쪽이다 — 목록 안에 담긴 객체를 찍을 때도 이쪽이 쓰인다." },
    ],
    code: { c: "class P:\n    def __eq__(self, o): return self.v == o.v\n    def __hash__(self): return hash(self.v)   # 짝을 맞춘다\n    def __repr__(self): return f\"P({self.v})\"", cap: "eq 를 만들면 hash 도 만든다" },
    key: ["`len(x)` 는 `__len__` 을 부른다", "`__eq__` 를 만들면 `__hash__` 도", "하나만 만든다면 `__repr__`"],
  },
  q: [
    {
      k: "Money · 집합에 담기는 값", cat: "internals",
      q: "금액을 담는 <code>Money</code> 를 완성하세요. 값이 같으면 <b>같은 것</b>으로 보고, <b>집합에 담아도</b> 중복이 걸러져야 합니다.",
      src: "class Money:\n    def __init__(self, won):\n        self.won = won\n\n    def __eq__(self, other):\n        return isinstance(other, Money) and self.won == other.won",
      sol: "class Money:\n    def __init__(self, won):\n        self.won = won\n\n    def __eq__(self, other):\n        return isinstance(other, Money) and self.won == other.won\n\n    def __hash__(self):\n        return hash(self.won)",
      tests: [["Money(100) == Money(100)", "True"], ["Money(100) == Money(200)", "False"],
              ["len({Money(100), Money(100), Money(200)})", "2"]],
      edge: [["Money(0) == Money(0)", "True"], ["{Money(5): 'x'}[Money(5)]", "'x'"]],
      ex: "__eq__ 만 정의하면 파이썬이 __hash__ 를 None 으로 만들어 버립니다. 집합에 넣는 순간 TypeError: unhashable 이 나요. 값이 같으면 해시도 같게 함께 정의해야 합니다.",
    },
    {
      k: "Bag · len 과 in 이 통하게", cat: "internals",
      q: "<code>Bag</code> 이 <code>len(bag)</code> 과 <code>x in bag</code> 에 반응하게 하세요. 담긴 항목 수와 포함 여부를 각각 돌려줍니다.",
      src: "class Bag:\n    def __init__(self, items):\n        self.items = list(items)\n\n    def size(self):\n        return len(self.items)\n\n    def has(self, x):\n        return x in self.items",
      sol: "class Bag:\n    def __init__(self, items):\n        self.items = list(items)\n\n    def __len__(self):\n        return len(self.items)\n\n    def __contains__(self, x):\n        return x in self.items",
      tests: [["len(Bag([1, 2, 3]))", "3"], ["2 in Bag([1, 2])", "True"], ["9 in Bag([1, 2])", "False"]],
      edge: [["len(Bag([]))", "0"], ["bool(Bag([]))", "False"], ["bool(Bag([1]))", "True"]],
      ex: "size() 와 has() 는 사람이 이름을 알아야 쓸 수 있습니다. __len__ 과 __contains__ 로 만들면 len() 과 in 이 그대로 통해요 — 게다가 __len__ 이 있으면 빈 객체가 자동으로 거짓이 됩니다.",
    },
  ],
},
{
  unit: "프로퍼티와 캡슐화",
  lesson: "직접 써 보기 — 속성처럼 보이는 함수",
  th: {
    sum: "`@property` 는 함수를 **속성처럼** 쓰게 한다. 괄호 없이 읽히지만 안에서는 계산이 돈다.",
    body: [
      { h: "언제 쓰나", t: "이미 `obj.width` 로 쓰이던 속성에 검사나 계산을 넣어야 할 때, 프로퍼티로 바꾸면 **부르는 쪽 코드를 고치지 않아도 된다.** 처음부터 게터·세터를 만들어 두는 것보다, 필요해질 때 바꾸는 편이 파이썬답다." },
      { h: "세터를 빠뜨리면", t: "`@property` 만 정의하면 읽기 전용이 된다. 값을 넣으려 하면 `AttributeError` 다. 쓰기가 필요하면 `@이름.setter` 를 함께 정의하고, 거기서 검사를 한다 — 잘못된 값이 들어오는 것을 만드는 순간 막는 자리다." },
    ],
    code: { c: "@property\ndef celsius(self): return self._c\n\n@celsius.setter\ndef celsius(self, v):\n    if v < -273.15: raise ValueError(\"절대영도 미만\")\n    self._c = v", cap: "검사는 세터에서" },
    key: ["`@property` 는 괄호 없이 읽힌다", "쓰기는 `@이름.setter`", "검사는 넣는 순간에 한다"],
  },
  q: [
    {
      k: "Temp · 잘못된 값을 막기", cat: "internals",
      q: "섭씨를 담는 <code>Temp</code> 를 완성하세요. <code>t.celsius</code> 로 <b>읽고 쓸 수</b> 있어야 합니다. 세터에서 <b>-273.15 미만이면 <code>ValueError</code></b> 를 던지세요.",
      src: "class Temp:\n    def __init__(self, c):\n        self._c = c\n\n    @property\n    def celsius(self):\n        return self._c",
      sol: "class Temp:\n    def __init__(self, c):\n        self.celsius = c\n\n    @property\n    def celsius(self):\n        return self._c\n\n    @celsius.setter\n    def celsius(self, v):\n        if v < -273.15:\n            raise ValueError(\"절대영도 미만\")\n        self._c = v",
      tests: [["Temp(20).celsius", "20"],
              ["(lambda t: (setattr(t, 'celsius', 30), t.celsius)[1])(Temp(0))", "30"],
              ["Temp.celsius.fset is not None", "True"]],
      edge: [["Temp(-273.15).celsius", "-273.15"],
             ["(lambda t: (setattr(t, 'celsius', -273.15), t.celsius)[1])(Temp(0))", "-273.15"]],
      ex: "@property 만 있으면 읽기 전용이라 값을 넣을 수 없습니다. 세터를 만들고 거기서 검사해야, 생성자든 나중이든 잘못된 값이 들어오는 순간 막을 수 있어요.",
    },
    {
      k: "Rect · 계산해서 보여 주기", cat: "internals",
      q: "<code>Rect</code> 에 <b>넓이</b>를 <code>r.area</code> 로(괄호 없이) 읽을 수 있게 하세요. 가로·세로를 바꾸면 넓이도 따라 바뀌어야 합니다.",
      src: "class Rect:\n    def __init__(self, w, h):\n        self.w = w\n        self.h = h\n        self.area = w * h",
      sol: "class Rect:\n    def __init__(self, w, h):\n        self.w = w\n        self.h = h\n\n    @property\n    def area(self):\n        return self.w * self.h",
      tests: [["Rect(3, 4).area", "12"],
              ["(lambda r: (setattr(r, 'w', 10), r.area)[1])(Rect(3, 4))", "40"],
              ["Rect(0, 5).area", "0"]],
      edge: [["(lambda r: (setattr(r, 'h', 0), r.area)[1])(Rect(2, 2))", "0"]],
      ex: "생성자에서 한 번 계산해 두면 그 뒤 가로를 바꿔도 넓이는 옛날 값 그대로입니다. 프로퍼티로 만들면 읽을 때마다 계산해서 항상 맞아요.",
    },
  ],
},
{
  unit: "이터레이터와 제너레이터 심화",
  lesson: "직접 써 보기 — 필요할 때 하나씩",
  th: {
    sum: "제너레이터는 값을 **미리 다 만들지 않는다.** 요청받을 때 하나씩 만들어 주고 그 자리에서 멈춰 기다린다.",
    body: [
      { h: "한 번 쓰면 끝", t: "제너레이터는 앞으로만 간다. 한 번 다 돌고 나면 다시 돌려도 아무것도 나오지 않는다 — 오류가 아니라 빈 결과라 더 헷갈린다. 두 번 써야 하면 리스트로 받아 두거나 다시 만든다." },
      { h: "yield from", t: "다른 이터러블의 값을 그대로 흘려보낼 때 `for x in it: yield x` 대신 `yield from it` 이라고 쓴다. 짧고, 중첩 제너레이터에서 값을 주고받는 통로까지 이어 준다." },
    ],
    code: { c: "def take(it, n):\n    for i, x in enumerate(it):\n        if i >= n: return\n        yield x\n\ndef flat(nested):\n    for it in nested:\n        yield from it", cap: "필요한 만큼만 만든다" },
    key: ["제너레이터는 한 번만 돈다", "미리 다 만들지 않는다", "`yield from` 으로 흘려보낸다"],
  },
  q: [
    {
      k: "take · 무한한 것에서 앞부분만", cat: "internals",
      q: "끝이 없을 수도 있는 이터러블에서 <b>앞의 n개</b>만 내보내는 <b>제너레이터</b>를 만드세요. 전체를 다 만들면 안 됩니다.",
      src: "def take(it, n):\n    return list(it)[:n]",
      sol: "def take(it, n):\n    for i, x in enumerate(it):\n        if i >= n:\n            return\n        yield x",
      tests: [["list(take(iter([1, 2, 3, 4]), 2))", "[1, 2]"],
              ["list(take(__import__('itertools').count(), 3))", "[0, 1, 2]"],
              ["list(take(iter([]), 3))", "[]"]],
      edge: [["list(take(iter([1]), 0))", "[]"],
             ["list(take(iter([1, 2]), 99))", "[1, 2]"]],
      ex: "list(it) 는 끝까지 다 만듭니다. 무한 수열이면 영영 끝나지 않아요. yield 로 하나씩 내보내고 n개를 채우면 return 으로 멈춰야 합니다.",
    },
    {
      k: "flatten · 한 겹 펴기", cat: "internals",
      q: "리스트의 리스트를 <b>한 겹 펴서</b> 값을 하나씩 내보내는 제너레이터를 만드세요. <code>yield from</code> 을 쓰세요.",
      src: "def flatten(nested):\n    out = []\n    for it in nested:\n        out.extend(it)\n    return out",
      sol: "def flatten(nested):\n    for it in nested:\n        yield from it",
      tests: [["list(flatten([[1, 2], [3]]))", "[1, 2, 3]"],
              ["list(flatten([]))", "[]"],
              ["list(flatten([[], [1]]))", "[1]"]],
      edge: [["hasattr(flatten([[1]]), '__next__')", "True"],
             ["list(flatten([(1, 2), 'ab']))", "[1, 2, 'a', 'b']"]],
      ex: "리스트를 만들어 돌려주면 제너레이터가 아닙니다. 전부 메모리에 올라가고, __next__ 도 없어요. yield from 을 쓰면 값을 하나씩 흘려보냅니다.",
    },
  ],
},
{
  unit: "functools와 itertools",
  lesson: "직접 써 보기 — 이미 만들어져 있는 것들",
  th: {
    sum: "반복문을 쓰기 전에, 표준 라이브러리에 이미 있는지 본다. 짧아지고 덜 틀린다.",
    body: [
      { h: "lru_cache", t: "`@lru_cache` 를 붙이면 같은 인자로 다시 부를 때 계산하지 않고 저장해 둔 값을 준다. 재귀 피보나치가 지수에서 선형으로 떨어진다. 다만 인자가 해시 가능해야 하고, 결과가 매번 달라야 하는 함수에는 쓰면 안 된다." },
      { h: "groupby 의 함정", t: "`itertools.groupby` 는 **연속된** 같은 값만 묶는다. 정렬하지 않고 쓰면 같은 열쇠가 여러 번 나온다. 정렬 후 쓰거나, 순서와 무관하게 묶으려면 딕셔너리를 쓴다 — SQL 의 GROUP BY 와 다르다." },
    ],
    code: { c: "from functools import lru_cache\n@lru_cache(maxsize=None)\ndef fib(n): ...\n\nfrom itertools import groupby\ngroupby(sorted(xs, key=k), key=k)   # 정렬 먼저", cap: "groupby 는 연속된 것만 묶는다" },
    key: ["`lru_cache` 는 같은 인자를 기억한다", "`groupby` 는 연속된 것만 묶는다", "쓰기 전에 정렬한다"],
  },
  q: [
    {
      k: "fib · 캐시로 지수를 선형으로", cat: "perf",
      q: "피보나치를 재귀로 구하되 <b>캐시</b>를 붙여 큰 입력도 빠르게 계산하세요. <code>fib(0)=0</code>, <code>fib(1)=1</code> 입니다.",
      src: "def fib(n):\n    if n < 2:\n        return n\n    return fib(n - 1) + fib(n - 2)",
      sol: "from functools import lru_cache\n\n@lru_cache(maxsize=None)\ndef fib(n):\n    if n < 2:\n        return n\n    return fib(n - 1) + fib(n - 2)",
      tests: [["fib(10)", "55"], ["fib(0)", "0"], ["fib(1)", "1"],
              ["(fib(25), fib.cache_info().currsize > 0)[1]", "True"]],
      edge: [["fib(2)", "1"], ["fib(25)", "75025"]],
      ex: "캐시가 없으면 같은 값을 몇 번이고 다시 계산합니다 — fib(40) 만 해도 호출이 수억 번이라 사실상 끝나지 않아요. @lru_cache 를 붙이면 각 n 을 한 번씩만 계산하고, cache_info() 로 몇 개가 저장됐는지도 볼 수 있습니다.",
    },
    {
      k: "group_by_first · 첫 글자로 묶기", cat: "debug",
      q: "단어들을 <b>첫 글자별로</b> 묶어 <code>{글자: [단어…]}</code> 로 돌려주세요. 입력 순서가 섞여 있어도 <b>같은 글자는 한 묶음</b>이어야 합니다.",
      src: "from itertools import groupby\n\ndef group_by_first(words):\n    out = {}\n    for k, g in groupby(words, key=lambda w: w[0]):\n        out[k] = list(g)\n    return out",
      sol: "def group_by_first(words):\n    out = {}\n    for w in words:\n        out.setdefault(w[0], []).append(w)\n    return out",
      tests: [["group_by_first(['apple', 'avocado', 'banana'])", "{'a': ['apple', 'avocado'], 'b': ['banana']}"],
              ["group_by_first(['ant', 'bee', 'ape'])", "{'a': ['ant', 'ape'], 'b': ['bee']}"],
              ["group_by_first([])", "{}"]],
      edge: [["group_by_first(['x'])", "{'x': ['x']}"]],
      ex: "groupby 는 연속된 같은 값만 묶습니다. ['ant','bee','ape'] 처럼 섞여 있으면 'a' 묶음이 두 번 생기고 뒤엣것이 앞엣것을 덮어써요. 정렬 후 쓰거나, 순서와 무관하게 묶으려면 딕셔너리가 낫습니다.",
    },
  ],
},
{
  unit: "정규표현식",
  lesson: "직접 써 보기 — 찾고 바꾸기",
  th: {
    sum: "`re.match` 는 **문자열 처음부터**만 본다. 가운데를 찾으려면 `re.search` 다.",
    body: [
      { h: "match 와 search", t: "`re.match('b', 'abc')` 는 `None` 이다. 처음이 'b' 가 아니기 때문이다. 어디에 있든 찾으려면 `re.search` 를 쓴다. 전체가 정확히 맞아야 하면 `re.fullmatch` 다 — 셋을 구분하지 않으면 '왜 안 찾아지지' 로 오래 헤맨다." },
      { h: "탐욕과 게으름", t: "`.*` 는 가능한 한 **많이** 먹는다. `<a><b>` 에서 `<.*>` 는 전체를 잡는다. 최소로 잡으려면 `<.*?>` 처럼 물음표를 붙인다. 태그나 따옴표를 다룰 때 결과가 통째로 달라지는 자리다." },
    ],
    code: { c: "re.match('b', 'abc')      # None — 처음만 본다\nre.search('b', 'abc')     # 찾는다\nre.findall(r'<.*?>', s)   # 최소로 잡기", cap: "match 는 처음부터만 본다" },
    key: ["`match` 는 처음부터, `search` 는 아무 데나", "`.*` 는 최대로 먹는다", "`.*?` 는 최소로"],
  },
  q: [
    {
      k: "find_number · 문장 속 숫자 찾기", cat: "debug",
      q: "문장 안에서 <b>처음 나오는 숫자</b>를 문자열로 돌려주세요. 없으면 <code>None</code> 입니다.",
      src: "import re\n\ndef find_number(s):\n    m = re.match(r'\\d+', s)\n    return m.group() if m else None",
      sol: "import re\n\ndef find_number(s):\n    m = re.search(r'\\d+', s)\n    return m.group() if m else None",
      tests: [["find_number('가격은 1200원')", "'1200'"], ["find_number('42개')", "'42'"],
              ["find_number('숫자 없음')", "None"]],
      edge: [["find_number('')", "None"], ["find_number('a1b22')", "'1'"]],
      ex: "re.match 는 문자열 맨 앞부터 맞는지만 봅니다. '가격은 1200원' 은 처음이 숫자가 아니라 None 이 나와요. 어디에 있든 찾으려면 re.search 입니다.",
    },
    {
      k: "strip_tags · 태그만 지우기", cat: "debug",
      q: "HTML 태그를 지우고 <b>안쪽 글자만</b> 남겨 주세요. <code>strip_tags('&lt;b&gt;안녕&lt;/b&gt;')</code> 은 <code>'안녕'</code> 입니다.",
      src: "import re\n\ndef strip_tags(s):\n    return re.sub(r'<.*>', '', s)",
      sol: "import re\n\ndef strip_tags(s):\n    return re.sub(r'<.*?>', '', s)",
      tests: [["strip_tags('<b>안녕</b>')", "'안녕'"],
              ["strip_tags('<p>가</p><p>나</p>')", "'가나'"],
              ["strip_tags('없음')", "'없음'"]],
      edge: [["strip_tags('')", "''"], ["strip_tags('<i>x</i>y')", "'xy'"]],
      ex: "<.*> 는 최대로 먹어서 첫 < 부터 마지막 > 까지 통째로 잡습니다. 안쪽 글자까지 함께 지워져요. 물음표를 붙여 최소로 잡으면 태그 하나씩만 지웁니다.",
    },
  ],
},
{
  unit: "타입힌트와 데이터클래스",
  lesson: "직접 써 보기 — 값 객체를 짧게",
  th: {
    sum: "`@dataclass` 는 `__init__`·`__repr__`·`__eq__` 를 자동으로 만들어 준다. 값을 담는 객체를 짧게 쓸 수 있다.",
    body: [
      { h: "가변 기본값은 field 로", t: "`items: list = []` 라고 쓰면 파이썬이 막아 준다(`ValueError`). 모든 인스턴스가 같은 리스트를 나눠 쓰게 되기 때문이다. `field(default_factory=list)` 로 **인스턴스마다 새로** 만든다 — 일반 함수의 기본값 함정과 같은 문제다." },
      { h: "frozen 과 해시", t: "`@dataclass(frozen=True)` 는 만든 뒤 값을 바꿀 수 없게 하고, 대신 `__hash__` 를 만들어 준다. 그래서 집합이나 딕셔너리 열쇠로 쓸 수 있다. 바뀌면 안 되는 값 객체에 알맞다." },
    ],
    code: { c: "@dataclass\nclass Cart:\n    items: list = field(default_factory=list)\n\n@dataclass(frozen=True)\nclass Point:\n    x: int\n    y: int          # 집합에 담을 수 있다", cap: "가변 기본값은 default_factory 로" },
    key: ["`@dataclass` 가 기본 메서드를 만든다", "가변 기본값은 `default_factory`", "`frozen=True` 면 해시 가능"],
  },
  q: [
    {
      k: "Cart · 인스턴스마다 새 목록", cat: "debug",
      q: "장바구니 <code>Cart</code> 를 데이터클래스로 만드세요. <b>새로 만들 때마다 빈 목록</b>이어야 하고, 하나에 담아도 다른 것에 영향이 없어야 합니다.",
      src: "from dataclasses import dataclass\n\n@dataclass\nclass Cart:\n    owner: str\n    items: list = None\n\n    def add(self, x):\n        if self.items is None:\n            self.items = []\n        self.items.append(x)",
      sol: "from dataclasses import dataclass, field\n\n@dataclass\nclass Cart:\n    owner: str\n    items: list = field(default_factory=list)\n\n    def add(self, x):\n        self.items.append(x)",
      tests: [["Cart('가영').items", "[]"],
              ["(lambda c: (c.add('사과'), c.items)[1])(Cart('가영'))", "['사과']"],
              ["(lambda a, b: (a.add('x'), b.items)[1])(Cart('a'), Cart('b'))", "[]"]],
      edge: [["Cart('a') == Cart('a')", "True"], ["Cart('a', ['x']).items", "['x']"]],
      ex: "기본값을 None 으로 두고 나중에 만들면, 만들자마자 items 를 읽는 코드가 None 을 봅니다. field(default_factory=list) 는 인스턴스마다 새 리스트를 만들어 줘요 — = [] 라고 쓰면 파이썬이 아예 막습니다.",
    },
    {
      k: "Point · 집합에 담기는 좌표", cat: "internals",
      q: "좌표 <code>Point</code> 를 데이터클래스로 만드세요. <b>값을 바꿀 수 없고</b>, <b>집합에 담을 수</b> 있어야 합니다.",
      src: "from dataclasses import dataclass\n\n@dataclass\nclass Point:\n    x: int\n    y: int",
      sol: "from dataclasses import dataclass\n\n@dataclass(frozen=True)\nclass Point:\n    x: int\n    y: int",
      tests: [["Point(1, 2) == Point(1, 2)", "True"],
              ["len({Point(1, 2), Point(1, 2), Point(3, 4)})", "2"],
              ["Point.__dataclass_params__.frozen", "True"]],
      edge: [["{Point(0, 0): 'origin'}[Point(0, 0)]", "'origin'"]],
      ex: "그냥 @dataclass 는 값을 바꿀 수 있고 해시할 수 없어 집합에 못 넣습니다. frozen=True 를 주면 못 바꾸는 대신 __hash__ 가 생겨요 — 바뀌면 안 되는 값 객체의 기본형입니다.",
    },
  ],
},
{
  unit: "statistics 모듈",
  lesson: "직접 써 보기 — 평균만으로는 모자라다",
  th: {
    sum: "평균은 **극단값 하나에 크게 흔들린다.** 중앙값은 그렇지 않다. 어느 쪽을 쓸지는 데이터 모양이 정한다.",
    body: [
      { h: "평균과 중앙값", t: "연봉처럼 몇몇이 아주 큰 데이터에서 평균은 대다수보다 높게 나온다. '보통 사람' 을 말하려면 중앙값(`median`)이 맞다. `statistics` 모듈은 둘 다 준다 — `mean`, `median`, `mode`." },
      { h: "빈 입력과 표본", t: "`mean([])` 은 `StatisticsError` 다. 계산 전에 비었는지 확인한다. 분산은 `pvariance`(모집단)와 `variance`(표본)가 다르다 — 표본은 n-1 로 나눠 값이 조금 크다. 어느 쪽인지 모르고 쓰면 결과가 미묘하게 틀린다." },
    ],
    code: { c: "import statistics as st\nst.mean([1, 2, 100])     # 34.33 — 하나에 끌려간다\nst.median([1, 2, 100])   # 2\nst.variance(xs)          # 표본 (n-1)", cap: "극단값이 있으면 중앙값" },
    key: ["평균은 극단값에 흔들린다", "`mean([])` 은 오류", "`variance` 는 표본, `pvariance` 는 모집단"],
  },
  q: [
    {
      k: "typical · 대표값 고르기", cat: "internals",
      q: "숫자 목록의 <b>대표값</b>을 돌려주세요. 값이 <b>10개 미만</b>이면 극단값에 흔들리지 않게 <b>중앙값</b>을, 그 이상이면 <b>평균</b>을 씁니다. 비어 있으면 <code>0.0</code> 입니다.",
      src: "import statistics as st\n\ndef typical(xs):\n    return st.mean(xs)",
      sol: "import statistics as st\n\ndef typical(xs):\n    if not xs:\n        return 0.0\n    if len(xs) < 10:\n        return st.median(xs)\n    return st.mean(xs)",
      tests: [["typical([1, 2, 100])", "2"], ["typical([])", "0.0"],
              ["typical(list(range(10)))", "4.5"]],
      edge: [["typical([5])", "5"], ["typical([1, 3])", "2.0"]],
      ex: "평균만 쓰면 [1, 2, 100] 의 대표값이 34.3 이 됩니다 — 셋 중 둘보다 훨씬 큰 값이에요. 그리고 빈 목록에서 mean 은 StatisticsError 를 던집니다.",
    },
    {
      k: "spread · 퍼진 정도", cat: "internals",
      q: "숫자 목록의 <b>표본 표준편차</b>를 돌려주세요. 값이 <b>2개 미만</b>이면 <code>0.0</code> 입니다.",
      src: "import statistics as st\n\ndef spread(xs):\n    return st.pstdev(xs)",
      sol: "import statistics as st\n\ndef spread(xs):\n    if len(xs) < 2:\n        return 0.0\n    return st.stdev(xs)",
      tests: [["round(spread([2, 4, 4, 4, 5, 5, 7, 9]), 4)", "2.1381"],
              ["spread([])", "0.0"], ["spread([5])", "0.0"]],
      edge: [["round(spread([1, 3]), 4)", "1.4142"]],
      ex: "pstdev 는 모집단 기준이라 n 으로 나눕니다. 표본이면 n-1 로 나누는 stdev 예요 — 값이 조금 더 큽니다. 그리고 stdev 는 값이 하나뿐이면 오류를 던지니 먼저 걸러야 합니다.",
    },
  ],
},
{
  unit: "CSV와 집계 패턴",
  lesson: "직접 써 보기 — 표를 읽어 묶기",
  th: {
    sum: "CSV 는 쉼표로 나누면 되는 것처럼 보이지만, **따옴표 안의 쉼표** 때문에 직접 나누면 깨진다.",
    body: [
      { h: "split 으로 나누지 않기", t: "`\"서울, 강남\",100` 을 `split(',')` 하면 세 조각이 된다. `csv` 모듈은 따옴표 규칙을 알고 있어 두 조각으로 정확히 나눈다. 직접 파서를 쓰는 순간 이스케이프·줄바꿈 규칙까지 다 떠안게 된다." },
      { h: "DictReader", t: "`csv.DictReader` 는 첫 줄을 열 이름으로 삼아 각 행을 딕셔너리로 준다. 열 순서가 바뀌어도 코드가 안 깨진다. 값은 **모두 문자열**이라 숫자로 쓰려면 직접 바꿔야 한다 — 이걸 빼먹으면 합계가 문자열 이어붙이기가 된다." },
    ],
    code: { c: "import csv, io\nfor row in csv.DictReader(io.StringIO(text)):\n    total += int(row[\"금액\"])   # 문자열이므로 변환", cap: "값은 전부 문자열로 들어온다" },
    key: ["`split(',')` 로 나누지 않는다", "`DictReader` 는 열 이름으로 읽는다", "값은 전부 문자열"],
  },
  q: [
    {
      k: "total_amount · 금액 합계", cat: "debug",
      q: "CSV 문자열에서 <code>금액</code> 열의 <b>합계</b>를 정수로 돌려주세요. 값에 <b>따옴표로 감싼 쉼표</b>가 있어도 깨지면 안 됩니다.",
      src: "def total_amount(text):\n    lines = text.strip().split(\"\\n\")\n    head = lines[0].split(\",\")\n    i = head.index(\"금액\")\n    total = 0\n    for line in lines[1:]:\n        total += int(line.split(\",\")[i])\n    return total",
      sol: "import csv\nimport io\n\ndef total_amount(text):\n    total = 0\n    for row in csv.DictReader(io.StringIO(text)):\n        total += int(row[\"금액\"])\n    return total",
      tests: [["total_amount('지역,금액\\n서울,100\\n부산,200\\n')", "300"],
              ["total_amount('지역,금액\\n\"서울, 강남\",100\\n부산,50\\n')", "150"],
              ["total_amount('지역,금액\\n')", "0"]],
      edge: [["total_amount('금액,지역\\n70,대구\\n')", "70"]],
      ex: "직접 split(',') 하면 따옴표 안의 쉼표까지 나눠 열이 밀립니다. '\"서울, 강남\",100' 이 세 조각이 되어 엉뚱한 값을 정수로 바꾸려다 터져요. csv 모듈은 이 규칙을 알고 있습니다.",
    },
    {
      k: "sum_by_region · 지역별 합계", cat: "internals",
      q: "CSV 에서 <b>지역별 금액 합계</b>를 <code>{지역: 합계}</code> 로 돌려주세요. 값은 <b>정수</b>여야 합니다.",
      src: "import csv\nimport io\n\ndef sum_by_region(text):\n    out = {}\n    for row in csv.DictReader(io.StringIO(text)):\n        r = row[\"지역\"]\n        out[r] = out.get(r, 0) + row[\"금액\"]\n    return out",
      sol: "import csv\nimport io\n\ndef sum_by_region(text):\n    out = {}\n    for row in csv.DictReader(io.StringIO(text)):\n        r = row[\"지역\"]\n        out[r] = out.get(r, 0) + int(row[\"금액\"])\n    return out",
      tests: [["sum_by_region('지역,금액\\n서울,100\\n부산,50\\n서울,20\\n')", "{'서울': 120, '부산': 50}"],
              ["sum_by_region('지역,금액\\n')", "{}"],
              ["sum_by_region('지역,금액\\n대구,7\\n')", "{'대구': 7}"]],
      edge: [["sum_by_region('지역,금액\\n서울,0\\n')", "{'서울': 0}"]],
      ex: "DictReader 가 주는 값은 전부 문자열입니다. 0 + '100' 은 TypeError 예요 — 숫자로 쓰려면 int() 로 바꿔야 합니다. 이걸 빼먹으면 합계가 아니라 글자 이어붙이기가 되는 경우도 있습니다.",
    },
  ],
},
{
  unit: "파일 입출력",
  lesson: "직접 써 보기 — 파일처럼 다루기",
  th: {
    sum: "파일을 여는 코드는 `with` 로 감싼다. 예외가 나도 반드시 닫히고, 닫는 것을 빠뜨릴 수 없다.",
    body: [
      { h: "왜 with 인가", t: "`f = open(...)` 뒤에 예외가 나면 `f.close()` 에 닿지 못한다. 열린 파일이 쌓이면 결국 열 수 없게 된다. `with open(...) as f:` 는 블록을 벗어나는 순간 — 예외든 return 이든 — 반드시 닫는다." },
      { h: "파일 같은 것", t: "함수가 파일 경로 대신 **파일 객체**를 받으면 테스트가 쉬워진다. `io.StringIO(\"...\")` 는 메모리 위의 파일처럼 동작해서 진짜 파일 없이 시험할 수 있다. 실무 코드에서는 열어 둔 파일을 그대로 넘긴다." },
    ],
    code: { c: "def count_lines(f):\n    return sum(1 for _ in f)\n\n# 테스트\ncount_lines(io.StringIO(\"a\\nb\\n\"))\n# 실무\nwith open(path) as f: count_lines(f)", cap: "경로 대신 파일 객체를 받는다" },
    key: ["열기는 `with` 로 감싼다", "경로 대신 파일 객체를 받으면 시험하기 쉽다", "`io.StringIO` 는 메모리 위의 파일"],
  },
  q: [
    {
      k: "read_nonempty · 빈 줄 빼고 읽기", cat: "internals",
      q: "파일 객체에서 <b>공백만 있는 줄을 빼고</b> 줄 목록을 돌려주세요. 각 줄의 <b>줄바꿈과 앞뒤 공백</b>은 없앱니다.",
      src: "def read_nonempty(f):\n    return [line for line in f if line != \"\"]",
      sol: "def read_nonempty(f):\n    out = []\n    for line in f:\n        s = line.strip()\n        if s:\n            out.append(s)\n    return out",
      tests: [["read_nonempty(__import__('io').StringIO('a\\n\\nb\\n'))", "['a', 'b']"],
              ["read_nonempty(__import__('io').StringIO('  x  \\n'))", "['x']"],
              ["read_nonempty(__import__('io').StringIO(''))", "[]"]],
      edge: [["read_nonempty(__import__('io').StringIO('\\n   \\n'))", "[]"]],
      ex: "파일에서 읽은 줄에는 줄바꿈이 붙어 있어서 빈 줄도 '\\n' 이라 != \"\" 가 참이 됩니다. 하나도 걸러지지 않아요. strip() 으로 다듬은 뒤 판단해야 합니다.",
    },
    {
      k: "word_count · 단어 세기", cat: "internals",
      q: "파일 객체 전체에서 <b>단어가 몇 번씩 나오는지</b> 세어 <code>{단어: 횟수}</code> 로 돌려주세요. 대소문자는 구별하지 않습니다.",
      src: "def word_count(f):\n    counts = {}\n    for line in f:\n        for w in line.split(\" \"):\n            counts[w] = counts.get(w, 0) + 1\n    return counts",
      sol: "def word_count(f):\n    counts = {}\n    for line in f:\n        for w in line.lower().split():\n            counts[w] = counts.get(w, 0) + 1\n    return counts",
      tests: [["word_count(__import__('io').StringIO('a b\\na\\n'))", "{'a': 2, 'b': 1}"],
              ["word_count(__import__('io').StringIO('Hi hi\\n'))", "{'hi': 2}"],
              ["word_count(__import__('io').StringIO(''))", "{}"]],
      edge: [["word_count(__import__('io').StringIO('  x   y  \\n'))", "{'x': 1, 'y': 1}"],
             ["word_count(__import__('io').StringIO('\\n'))", "{}"]],
      ex: "split(\" \") 는 공백이 여러 칸이면 빈 문자열을 만들고, 줄 끝의 줄바꿈도 단어에 붙입니다. 인자 없는 split() 은 공백을 알아서 처리하고 빈 조각도 만들지 않아요. 대소문자는 lower() 로 맞춥니다.",
    },
  ],
},
];
