/* 파이썬 중급 유닛 실습 — 기초 다음에 만나는, 역시 실습이 0이던 유닛들.
   문제는 문법 소개가 아니라 '여기서 조용히 틀린다' 로 골랐다. */
module.exports = [
{
  unit: "람다와 고차함수",
  lesson: "직접 써 보기 — 기준을 넘겨주기",
  th: {
    sum: "정렬이나 걸러내기의 '기준' 을 함수로 넘긴다. `key=` 가 그 자리다.",
    body: [
      { h: "key 는 '무엇으로 비교할지'", t: "`sorted(xs, key=len)` 은 길이로 비교한다. key 에 넘기는 것은 **비교 결과가 아니라 비교할 값을 뽑는 함수**다. `key=lambda x: -x` 처럼 부호를 뒤집으면 내림차순이 되지만, 뜻이 분명한 `reverse=True` 를 쓰는 편이 낫다." },
      { h: "정렬은 안정적이다", t: "파이썬의 정렬은 같은 값끼리 원래 순서를 지킨다(stable). 그래서 '점수 내림차순, 같으면 이름 오름차순' 은 이름으로 먼저 정렬한 뒤 점수로 다시 정렬하거나, `key=lambda p: (-p[1], p[0])` 처럼 튜플로 한 번에 준다." },
    ],
    code: { c: "people = [('가', 90), ('나', 90), ('다', 80)]\nsorted(people, key=lambda p: -p[1])          # 점수 내림차순\nsorted(people, key=lambda p: (-p[1], p[0]))  # 같으면 이름순", cap: "튜플을 key 로 주면 2차 기준까지 한 번에" },
    key: ["`key=` 는 비교할 값을 뽑는 함수", "정렬은 같은 값의 순서를 지킨다", "2차 기준은 튜플로 준다"],
  },
  q: [
    {
      k: "by_length · 길이순 정렬", cat: "internals",
      q: "문자열 리스트를 <b>길이가 짧은 것부터</b> 정렬해 돌려주세요. 길이가 같으면 <b>원래 순서</b>를 지킵니다.",
      src: "def by_length(xs):\n    return sorted(xs)",
      sol: "def by_length(xs):\n    return sorted(xs, key=len)",
      tests: [["by_length(['bbb','a','cc'])", "['a','cc','bbb']"], ["by_length(['dd','cc','a'])", "['a','dd','cc']"]],
      edge: [["by_length([])", "[]"], ["by_length(['x'])", "['x']"]],
      ex: "key 를 안 주면 글자 순서(사전순)로 정렬합니다. 길이로 비교하려면 key=len 을 줘야 해요.",
    },
    {
      k: "rank · 점수 내림차순, 동점은 이름순", cat: "internals",
      q: "<code>(이름, 점수)</code> 목록을 <b>점수 높은 순</b>으로, 점수가 같으면 <b>이름 오름차순</b>으로 정렬해 돌려주세요.",
      src: "def rank(ps):\n    return sorted(ps, key=lambda p: p[1], reverse=True)",
      sol: "def rank(ps):\n    return sorted(ps, key=lambda p: (-p[1], p[0]))",
      tests: [["rank([('na',90),('ga',90),('da',80)])", "[('ga',90),('na',90),('da',80)]"],
              ["rank([('b',10),('a',20)])", "[('a',20),('b',10)]"]],
      edge: [["rank([])", "[]"], ["rank([('z',1),('a',1)])", "[('a',1),('z',1)]"]],
      ex: "reverse=True 는 전체를 뒤집어서, 동점일 때 이름까지 내림차순이 돼 버립니다. 튜플 key 로 '점수는 뒤집고 이름은 그대로' 를 한 번에 표현해야 해요.",
    },
  ],
},
{
  unit: "컴프리헨션 심화",
  lesson: "직접 써 보기 — 한 줄로 만들기",
  th: {
    sum: "`[식 for x in 목록 if 조건]` — 걸러내면서 바꾸는 것을 한 줄로 쓴다.",
    body: [
      { h: "if 의 자리가 두 곳", t: "`for` 뒤의 `if` 는 **거르기**다. `for` 앞에 오는 `A if 조건 else B` 는 **고르기**다. 거를 때는 `else` 를 쓸 수 없고, 고를 때는 반드시 `else` 가 있어야 한다. 이 둘을 헷갈리면 문법 오류가 나거나 개수가 달라진다." },
      { h: "중첩의 순서", t: "`[x for a in A for b in B]` 는 바깥 루프를 **먼저** 적는다. 평소 for 문을 쓰는 순서와 같다. 반대로 적으면 이름을 아직 모른다는 오류가 난다." },
    ],
    code: { c: "[x*2 for x in xs if x > 0]          # 거르기 — else 없음\n[x if x > 0 else 0 for x in xs]     # 고르기 — else 필수\n[(a,b) for a in A for b in B]       # 바깥 루프를 먼저", cap: "거르기와 고르기는 if 의 자리가 다르다" },
    key: ["`for` 뒤 `if` 는 거르기 (개수가 준다)", "앞의 `A if 조건 else B` 는 고르기 (개수 유지)", "중첩은 바깥 루프를 먼저 적는다"],
  },
  q: [
    {
      k: "clamp_neg · 음수를 0으로", cat: "debug",
      q: "숫자 리스트에서 <b>음수만 0으로 바꾸고</b> 나머지는 그대로 둔 새 리스트를 돌려주세요. 개수는 그대로여야 합니다.",
      src: "def clamp_neg(xs):\n    return [x for x in xs if x > 0]",
      sol: "def clamp_neg(xs):\n    return [x if x > 0 else 0 for x in xs]",
      tests: [["clamp_neg([1,-2,3])", "[1,0,3]"], ["clamp_neg([-1,-1])", "[0,0]"]],
      edge: [["clamp_neg([])", "[]"], ["clamp_neg([0])", "[0]"]],
      ex: "for 뒤의 if 는 거르기라 음수가 사라져 개수가 줄어듭니다. 값을 바꾸려면 for 앞에 'A if 조건 else B' 를 써야 해요.",
    },
    {
      k: "pairs · 두 목록의 짝", cat: "internals",
      q: "두 리스트의 모든 짝을 <code>(a, b)</code> 튜플로 만든 리스트를 돌려주세요. <b>첫 번째 리스트를 바깥 루프</b>로 돌립니다.",
      src: "def pairs(A, B):\n    return [(a, b) for b in B for a in A]",
      sol: "def pairs(A, B):\n    return [(a, b) for a in A for b in B]",
      tests: [["pairs([1,2],['x','y'])", "[(1,'x'),(1,'y'),(2,'x'),(2,'y')]"],
              ["pairs([1],['a','b'])", "[(1,'a'),(1,'b')]"]],
      edge: [["pairs([],[1])", "[]"], ["pairs([1],[])", "[]"]],
      ex: "for 를 적은 순서대로 바깥·안쪽 루프가 정해집니다. 순서를 바꾸면 짝의 나열 순서가 달라져요.",
    },
  ],
},
{
  unit: "클로저·데코레이터·제너레이터",
  lesson: "직접 써 보기 — 감싸고, 기억하고, 미루기",
  th: {
    sum: "데코레이터는 함수를 감싸 원래 함수 대신 놓는 것이다. 제너레이터는 값을 한 번에 만들지 않고 필요할 때 하나씩 준다.",
    body: [
      { h: "감쌀 때 인자를 잃지 않기", t: "감싸는 함수는 어떤 함수든 받을 수 있어야 하므로 `def wrapper(*args, **kwargs)` 로 받아 `fn(*args, **kwargs)` 로 그대로 넘긴다. 그리고 **결과를 `return` 하는 것을 빠뜨리기 쉽다** — 빠뜨리면 감싼 순간 모든 함수가 None 을 돌려준다." },
      { h: "yield 가 있으면 제너레이터", t: "함수 안에 `yield` 가 하나라도 있으면 그 함수는 호출해도 몸통이 바로 돌지 않는다. `for` 로 돌리거나 `list()` 로 감쌀 때 비로소 한 걸음씩 실행된다. 그래서 무한한 수열도 만들 수 있다." },
    ],
    code: { c: "def 로그(fn):\n    def wrapper(*a, **k):\n        r = fn(*a, **k)\n        return r          # 이걸 빠뜨리면 전부 None\n    return wrapper", cap: "감싼 함수의 결과를 돌려주는 것을 빠뜨리지 않는다" },
    key: ["감쌀 때는 `*args, **kwargs` 로 그대로 넘긴다", "감싼 결과를 `return` 해야 한다", "`yield` 가 있으면 부를 때 바로 돌지 않는다"],
  },
  q: [
    {
      k: "double_result · 결과를 두 배로", cat: "debug",
      q: "함수를 감싸 <b>결과를 두 배로</b> 만들어 돌려주는 데코레이터를 완성하세요. 인자가 몇 개든 동작해야 합니다.",
      src: "def double_result(fn):\n    def wrapper(*args, **kwargs):\n        fn(*args, **kwargs) * 2\n    return wrapper",
      sol: "def double_result(fn):\n    def wrapper(*args, **kwargs):\n        return fn(*args, **kwargs) * 2\n    return wrapper",
      tests: [["double_result(lambda: 5)()", "10"], ["double_result(lambda a, b: a + b)(1, 2)", "6"]],
      edge: [["double_result(lambda s: s)('ab')", "'abab'"]],
      ex: "계산은 했는데 return 이 없어서 감싼 함수가 전부 None 을 돌려줍니다. 데코레이터에서 가장 자주 빠뜨리는 한 줄이에요.",
    },
    {
      k: "take · 앞에서 n개만", cat: "internals",
      q: "무한할 수도 있는 <b>이터러블</b>에서 앞의 n개만 리스트로 돌려주세요. 전체를 다 만들어 두면 안 됩니다.",
      src: "def take(it, n):\n    return list(it)[:n]",
      sol: "def take(it, n):\n    out = []\n    for x in it:\n        if len(out) >= n:\n            break\n        out.append(x)\n    return out",
      tests: [["take(iter([1,2,3,4]), 2)", "[1,2]"],
              ["take((i for i in range(100)), 3)", "[0,1,2]"],
              ["(lambda: (lambda g: take(g, 3))(__import__('itertools').count()))()", "[0,1,2]"]],
      edge: [["take(iter([]), 3)", "[]"], ["take(iter([1]), 0)", "[]"]],
      ex: "list(it) 는 끝까지 다 만들어 버립니다. 무한 수열이면 영영 끝나지 않아요. 필요한 개수만 채우고 멈춰야 합니다.",
    },
  ],
},
{
  unit: "문자열 포매팅",
  lesson: "직접 써 보기 — 보기 좋게 만들기",
  th: {
    sum: "f-문자열은 `f\"{값:형식}\"` 으로 값과 모양을 한 자리에 적는다.",
    body: [
      { h: "자주 쓰는 형식", t: "`{x:.2f}` 소수 둘째 자리까지, `{x:,}` 천 단위 쉼표, `{x:>8}` 오른쪽 정렬 8칸, `{x:05d}` 0으로 채운 5자리, `{x:.1%}` 백분율. 반올림해서 **보여줄 뿐** 값 자체는 바뀌지 않는다." },
      { h: "round 와는 다르다", t: "`round(2.675, 2)` 는 `2.67` 이 나온다 — 2.675 가 이진수로 정확히 표현되지 않아서다. 화면 표시는 f-문자열로, 돈 계산은 `decimal.Decimal` 로 하는 것이 정석이다." },
    ],
    code: { c: "x = 1234.5678\nf\"{x:,.2f}\"     # '1,234.57'\nf\"{7:03d}\"       # '007'\nf\"{0.256:.1%}\"   # '25.6%'", cap: "값과 모양을 한 자리에 적는다" },
    key: ["`{x:.2f}` 는 보여주기용 반올림", "`{x:,}` 천 단위 쉼표", "돈은 `Decimal`, 화면은 f-문자열"],
  },
  q: [
    {
      k: "money · 금액 표시", cat: "internals",
      q: "숫자를 <b>천 단위 쉼표와 소수 둘째 자리</b>로 만든 문자열을 돌려주세요. <code>money(1234.5)</code> 는 <code>\"1,234.50\"</code> 입니다.",
      src: "def money(x):\n    return f\"{x:.2f}\"",
      sol: "def money(x):\n    return f\"{x:,.2f}\"",
      tests: [["money(1234.5)", "'1,234.50'"], ["money(1000000)", "'1,000,000.00'"]],
      edge: [["money(0)", "'0.00'"], ["money(-1234.567)", "'-1,234.57'"]],
      ex: "쉼표를 넣으려면 형식에 , 를 함께 적어야 합니다 — {x:,.2f} 순서예요.",
    },
    {
      k: "pad_id · 자리수 맞추기", cat: "internals",
      q: "정수를 <b>0으로 채운 5자리</b> 문자열로 만들어 돌려주세요. <code>pad_id(42)</code> 는 <code>\"00042\"</code> 입니다.",
      src: "def pad_id(n):\n    return f\"{n:5d}\"",
      sol: "def pad_id(n):\n    return f\"{n:05d}\"",
      tests: [["pad_id(42)", "'00042'"], ["pad_id(0)", "'00000'"]],
      edge: [["pad_id(123456)", "'123456'"]],
      ex: "{n:5d} 는 공백으로 채웁니다. 0으로 채우려면 폭 앞에 0 을 적어 {n:05d} 여야 해요.",
    },
  ],
},
{
  unit: "collections 모듈",
  lesson: "직접 써 보기 — 세고 묶기",
  th: {
    sum: "`Counter` 는 세고, `defaultdict` 는 없는 열쇠를 자동으로 만들어 준다. 둘 다 반복문을 크게 줄인다.",
    body: [
      { h: "없는 열쇠", t: "보통 딕셔너리는 없는 열쇠를 꺼내면 `KeyError` 다. `defaultdict(list)` 는 꺼내는 순간 빈 리스트를 만들어 준다. 그래서 `d[k].append(v)` 를 조건문 없이 바로 쓸 수 있다." },
      { h: "동점의 순서", t: "`Counter.most_common(n)` 은 개수가 같으면 **처음 나온 순서**를 지킨다. 이 순서를 모르면 테스트가 왔다 갔다 하는 것처럼 보인다." },
    ],
    code: { c: "from collections import Counter, defaultdict\nCounter('aabc').most_common(2)   # [('a',2), ('b',1)]\n\nd = defaultdict(list)\nd['x'].append(1)                  # KeyError 없이 바로", cap: "세기와 묶기는 이미 만들어져 있다" },
    key: ["`Counter` 는 개수를 센다", "`defaultdict(list)` 는 빈 리스트를 자동으로 만든다", "`most_common` 은 동점이면 먼저 나온 것부터"],
  },
  q: [
    {
      k: "group_by_len · 길이로 묶기", cat: "internals",
      q: "문자열 리스트를 <b>길이별로 묶은</b> 딕셔너리를 돌려주세요. 값은 그 길이의 문자열 리스트이고, <b>원래 순서</b>를 지킵니다.",
      src: "def group_by_len(xs):\n    d = {}\n    for s in xs:\n        d[len(s)].append(s)\n    return d",
      sol: "def group_by_len(xs):\n    d = {}\n    for s in xs:\n        d.setdefault(len(s), []).append(s)\n    return d",
      tests: [["group_by_len(['a','bb','c'])", "{1:['a','c'], 2:['bb']}"],
              ["group_by_len(['xx'])", "{2:['xx']}"]],
      edge: [["group_by_len([])", "{}"]],
      ex: "없는 열쇠를 바로 꺼내면 KeyError 가 납니다. setdefault 나 defaultdict(list) 로 빈 리스트를 먼저 만들어야 해요.",
    },
    {
      k: "top_word · 가장 많이 나온 단어", cat: "internals",
      q: "공백으로 나뉜 문장에서 <b>가장 많이 나온 단어</b>를 돌려주세요. 같은 횟수면 <b>먼저 나온</b> 단어를 돌려줍니다. 빈 문장이면 빈 문자열입니다.",
      src: "def top_word(s):\n    words = s.split()\n    return max(words, key=words.count)",
      sol: "def top_word(s):\n    from collections import Counter\n    words = s.split()\n    if not words:\n        return \"\"\n    return Counter(words).most_common(1)[0][0]",
      tests: [["top_word('a b a')", "'a'"], ["top_word('')", "''"], ["top_word('x y')", "'x'"]],
      edge: [["top_word('   ')", "''"], ["top_word('z z y y')", "'z'"]],
      ex: "빈 문장에서 max() 는 ValueError 를 던집니다. 그리고 words.count 는 단어마다 전체를 다시 훑어 느려요 — Counter 는 한 번만 훑습니다.",
    },
  ],
},
{
  unit: "딕셔너리 심화",
  lesson: "직접 써 보기 — 안전하게 꺼내고 합치기",
  th: {
    sum: "딕셔너리는 '없을 때' 를 어떻게 다루느냐가 전부다.",
    body: [
      { h: "get 과 setdefault", t: "`d.get(k, 기본값)` 은 꺼내기만 하고 딕셔너리를 바꾸지 않는다. `d.setdefault(k, 기본값)` 은 없으면 **넣고** 그 값을 돌려준다. 읽기만 할 자리에 setdefault 를 쓰면 딕셔너리가 조용히 커진다." },
      { h: "합칠 때 누가 이기나", t: "`{**a, **b}` 는 겹치는 열쇠에서 **뒤에 있는 b 가 이긴다.** 순서를 헷갈리면 덮어쓰기 방향이 반대가 된다." },
    ],
    code: { c: "d = {'a': 1}\nd.get('b', 0)        # 0 — d 는 그대로\nd.setdefault('b', 0) # 0 — d 에 'b' 가 생긴다\n{**{'a':1}, **{'a':9}}  # {'a': 9} — 뒤가 이긴다", cap: "get 은 읽기만, setdefault 는 넣기도 한다" },
    key: ["`get` 은 딕셔너리를 바꾸지 않는다", "`setdefault` 는 없으면 넣는다", "`{**a, **b}` 는 뒤가 이긴다"],
  },
  q: [
    {
      k: "merge · 기본값 위에 덮어쓰기", cat: "internals",
      q: "기본 설정 위에 사용자 설정을 <b>덮어쓴</b> 새 딕셔너리를 돌려주세요. 원본 둘 다 그대로여야 합니다.",
      src: "def merge(base, user):\n    return {**user, **base}",
      sol: "def merge(base, user):\n    return {**base, **user}",
      tests: [["merge({'a':1,'b':2}, {'b':9})", "{'a':1,'b':9}"], ["merge({'x':1}, {})", "{'x':1}"]],
      edge: [["merge({}, {'y':2})", "{'y':2}"], ["merge({'a':1}, {'a':1})", "{'a':1}"]],
      ex: "뒤에 오는 것이 이깁니다. 순서를 바꾸면 사용자 설정이 기본값에 덮여 사라져요.",
    },
    {
      k: "count_safe · 세는 딕셔너리", cat: "debug",
      q: "값 목록에서 각 값이 몇 번 나왔는지 세는 딕셔너리를 돌려주세요. <b>세는 동안 원본 목록을 훑는 것 외에 다른 부작용이 없어야</b> 합니다.",
      src: "def count_safe(xs):\n    d = {}\n    for x in xs:\n        d[x] = d.get(x, 0)\n    return d",
      sol: "def count_safe(xs):\n    d = {}\n    for x in xs:\n        d[x] = d.get(x, 0) + 1\n    return d",
      tests: [["count_safe(['a','b','a'])", "{'a':2,'b':1}"], ["count_safe([1,1,1])", "{1:3}"]],
      edge: [["count_safe([])", "{}"], ["count_safe(['x'])", "{'x':1}"]],
      ex: "get 으로 꺼내기만 하고 1 을 더하지 않았습니다. 전부 0 이 나와요.",
    },
  ],
},
{
  unit: "슬라이싱과 시퀀스 심화",
  lesson: "직접 써 보기 — 잘라내기",
  th: {
    sum: "`xs[시작:끝:간격]` — 끝은 포함하지 않고, 범위를 넘겨도 오류가 나지 않는다.",
    body: [
      { h: "슬라이싱은 안전하다", t: "`xs[10]` 은 없는 자리면 오류지만 `xs[5:10]` 은 있는 만큼만 돌려준다. 그래서 '앞에서 n개' 는 길이를 확인하지 않고 `xs[:n]` 이라고 쓰면 된다." },
      { h: "음수와 뒤집기", t: "`xs[-1]` 은 마지막, `xs[:-1]` 은 마지막만 뺀 것이다. `xs[::-1]` 은 뒤집은 **새 리스트**를 만든다 — `reverse()` 는 원본을 바꾼다는 점이 다르다." },
    ],
    code: { c: "xs = [0,1,2,3,4]\nxs[1:3]     # [1, 2] — 끝은 포함 안 함\nxs[:-1]     # [0,1,2,3]\nxs[::-1]    # [4,3,2,1,0] — 새 리스트\nxs[10:20]   # [] — 오류가 아니다", cap: "끝은 포함하지 않고, 넘겨도 안전하다" },
    key: ["끝 번호는 포함하지 않는다", "범위를 넘겨도 오류가 아니다", "`xs[::-1]` 은 새 리스트, `reverse()` 는 원본을 바꾼다"],
  },
  q: [
    {
      k: "middle · 양끝을 뺀 가운데", cat: "internals",
      q: "리스트의 <b>처음과 마지막을 뺀</b> 가운데 부분을 돌려주세요. 원소가 2개 이하면 빈 리스트입니다.",
      src: "def middle(xs):\n    return xs[1:len(xs)]",
      sol: "def middle(xs):\n    return xs[1:-1]",
      tests: [["middle([1,2,3,4])", "[2,3]"], ["middle([1,2])", "[]"], ["middle([1,2,3])", "[2]"]],
      edge: [["middle([])", "[]"], ["middle([9])", "[]"]],
      ex: "xs[1:len(xs)] 은 마지막을 그대로 남깁니다. 마지막을 빼려면 끝을 -1 로 둬야 해요.",
    },
    {
      k: "last_n · 뒤에서 n개", cat: "internals",
      q: "리스트의 <b>뒤에서 n개</b>를 순서 그대로 돌려주세요. n이 0이면 빈 리스트이고, 개수보다 크면 전부 돌려줍니다.",
      src: "def last_n(xs, n):\n    return xs[-n:]",
      sol: "def last_n(xs, n):\n    if n <= 0:\n        return []\n    return xs[-n:]",
      tests: [["last_n([1,2,3], 2)", "[2,3]"], ["last_n([1,2,3], 0)", "[]"], ["last_n([1,2], 5)", "[1,2]"]],
      edge: [["last_n([], 2)", "[]"], ["last_n([1,2,3], 3)", "[1,2,3]"]],
      ex: "n 이 0 이면 xs[-0:] 이 되는데 -0 은 0 이라 전체가 나옵니다. 0 이하를 따로 걸러야 해요.",
    },
  ],
},
{
  unit: "재귀와 정렬",
  lesson: "직접 써 보기 — 스스로 부르기",
  th: {
    sum: "재귀는 '멈추는 조건' 을 먼저 쓰고, 그 다음에 '더 작은 문제로 넘기는' 줄을 쓴다.",
    body: [
      { h: "멈추는 조건이 먼저", t: "멈추는 조건(base case)이 없거나 닿지 않으면 파이썬은 약 1000번 만에 `RecursionError` 를 낸다. 넘기는 값이 **반드시 조건 쪽으로 가까워지는지** 확인한다 — `f(n)` 안에서 다시 `f(n)` 을 부르면 영원히 멈추지 않는다." },
      { h: "결과를 돌려받기", t: "재귀 호출의 결과를 `return` 하지 않고 그냥 부르기만 하면 값이 사라진다. `return f(n-1)` 처럼 돌려받아 이어 붙여야 한다." },
    ],
    code: { c: "def 팩토리얼(n):\n    if n <= 1:      # 멈추는 조건 먼저\n        return 1\n    return n * 팩토리얼(n - 1)   # 결과를 돌려받는다", cap: "멈추는 조건을 먼저, 결과는 돌려받는다" },
    key: ["멈추는 조건을 먼저 쓴다", "인자가 조건 쪽으로 가까워져야 한다", "재귀 결과를 `return` 으로 돌려받는다"],
  },
  q: [
    {
      k: "count_down · 거꾸로 세기", cat: "debug",
      q: "n부터 1까지 <b>거꾸로</b> 담은 리스트를 재귀로 만들어 돌려주세요. n이 0 이하면 빈 리스트입니다.",
      src: "def count_down(n):\n    if n <= 0:\n        return []\n    return [n] + count_down(n)",
      sol: "def count_down(n):\n    if n <= 0:\n        return []\n    return [n] + count_down(n - 1)",
      tests: [["count_down(3)", "[3,2,1]"], ["count_down(1)", "[1]"], ["count_down(0)", "[]"]],
      edge: [["count_down(-2)", "[]"]],
      ex: "count_down(n) 안에서 다시 count_down(n) 을 부르면 n 이 줄지 않아 멈추는 조건에 영영 닿지 않습니다. RecursionError 가 나요.",
    },
    {
      k: "flatten · 중첩 리스트 펴기", cat: "internals",
      q: "리스트 안에 리스트가 들어 있을 수 있습니다. 모든 값을 <b>순서대로 한 줄</b>로 편 리스트를 돌려주세요.",
      src: "def flatten(xs):\n    out = []\n    for x in xs:\n        if isinstance(x, list):\n            flatten(x)\n        else:\n            out.append(x)\n    return out",
      sol: "def flatten(xs):\n    out = []\n    for x in xs:\n        if isinstance(x, list):\n            out.extend(flatten(x))\n        else:\n            out.append(x)\n    return out",
      tests: [["flatten([1,[2,3],4])", "[1,2,3,4]"], ["flatten([[1,[2]],3])", "[1,2,3]"]],
      edge: [["flatten([])", "[]"], ["flatten([[]])", "[]"], ["flatten([1,2])", "[1,2]"]],
      ex: "재귀로 부르기만 하고 결과를 받지 않아서, 안쪽 리스트의 값이 통째로 사라집니다. out.extend(...) 로 돌려받아 이어 붙여야 해요.",
    },
  ],
},
];
