/* React 4차 — 실습이 하나도 없던 6개 유닛.

   채점기는 sucrase 로 JSX 를 바꾸고 진짜 react-dom 으로 그린다.
   컴포넌트 이름은 App 이어야 하고, 훅은 React.useState 꼴로 쓴다.
   검사식에서 쓸 수 있는 것: Q QA COUNT TXT ATTR CLICK CLICKN TYPE
   (CLICK 은 flushSync 로 감싸 있어 누른 뒤의 화면을 바로 볼 수 있다) */
module.exports = [
/* ── 렌더링과 재조정 ────────────────────────────────────── */
{
  unit: "렌더링과 재조정",
  lesson: "직접 짜 보기 — 리액트가 무엇을 다시 그리는가",
  th: {
    sum: "리액트는 **바뀐 것만 찾아 고친다**. 그 '찾는' 규칙을 알아야 예상대로 움직인다.",
    body: [
      { h: "같은 자리, 같은 타입이면 유지한다", t: "트리에서 같은 위치에 같은 종류의 요소가 있으면 상태를 그대로 둔 채 속성만 바꾼다. 타입이 달라지면 통째로 버리고 새로 만든다 — 그때 안에 있던 상태도 함께 사라진다." },
      { h: "key 는 '이것과 저것이 같은 것' 이라는 표시", t: "목록에서 key 가 같으면 같은 항목으로 보고 재사용한다. 인덱스를 key 로 쓰면 순서가 바뀔 때 '3번 자리' 는 그대로인데 내용만 바뀌어, 입력값이나 애니메이션이 엉뚱한 항목에 붙는다." },
      { h: "조건부 렌더링은 자리를 바꾼다", t: "`{cond && <A/>}` 로 A 가 사라지면 그 뒤 형제들의 자리가 밀린다. key 가 없으면 리액트는 밀린 자리를 '내용이 바뀐 것' 으로 읽는다." },
      { h: "다시 그린다고 DOM 이 바뀌는 건 아니다", t: "렌더는 '무엇을 그릴지 계산하는 일' 이고, 결과가 같으면 DOM 은 손대지 않는다. 그래서 렌더가 잦다고 곧바로 느린 것은 아니다 — 재 보고 판단한다." },
    ],
    code: { c: "{items.map(it => <Row key={it.id} />)}   // id 로\n{items.map((it, i) => <Row key={i} />)}  // 위험\n\n타입이 바뀌면 상태도 사라진다\n<div><Input/></div>  →  <span><Input/></span>", cap: "무엇을 같은 것으로 볼 것인가" },
    key: ["같은 자리·같은 타입이면 유지", "`key` 는 동일성 표시", "인덱스 key 는 순서가 바뀔 때 깨진다"],
  },
  q: [
    {
      k: "list · 무엇을 key 로 삼을까",
      qq: "목록을 그리되 <b>각 항목의 <code>id</code></b> 를 key 로 쓰고, <code>li</code> 에 <code>data-id</code> 속성으로도 넣어 주세요.",
      src: "function App() {\n  const items = [{ id: 'a', name: '가' }, { id: 'b', name: '나' }];\n  return (\n    <ul className=\"list\">\n      {items.map((it, i) => (\n        <li key={i} data-id={i} className=\"row\">{it.name}</li>\n      ))}\n    </ul>\n  );\n}\n",
      sol: "function App() {\n  const items = [{ id: 'a', name: '가' }, { id: 'b', name: '나' }];\n  return (\n    <ul className=\"list\">\n      {items.map(it => (\n        <li key={it.id} data-id={it.id} className=\"row\">{it.name}</li>\n      ))}\n    </ul>\n  );\n}\n",
      tests: [{ d: "항목이 둘이다", js: "COUNT('.row')===2" },
              { d: "첫 항목의 data-id 가 'a'", js: "ATTR('.row','data-id')==='a'" },
              { d: "둘째 항목의 data-id 가 'b'", js: "QA('.row')[1].getAttribute('data-id')==='b'" },
              { d: "이름이 보인다", js: "TXT('.row')==='가'" }],
      ex: "인덱스를 key 로 쓰면 '몇 번째 자리인가' 가 동일성이 됩니다 — 목록 앞에 항목을 하나 끼우면 모든 항목의 key 가 밀려, 리액트는 전부 내용이 바뀐 것으로 봐요. 입력 중이던 값이나 열려 있던 상태가 엉뚱한 줄에 붙습니다. 데이터에 있는 안정적인 id 를 쓰세요.",
    },
    {
      k: "toggleType · 타입이 바뀌면 상태가 사라진다",
      qq: "버튼을 누르면 숫자가 1 올라갑니다. <b>감싸는 태그를 바꾸지 말고</b> <code>className</code> 만 바꿔, 눌러도 값이 유지되게 하세요.",
      src: "function Counter() {\n  const [n, setN] = React.useState(0);\n  return <span className=\"n\">{n}</span>;\n}\n\nfunction App() {\n  const [on, setOn] = React.useState(false);\n  return (\n    <div>\n      <button className=\"go\" onClick={() => setOn(v => !v)}>바꾸기</button>\n      {on ? <section><Counter /></section> : <div><Counter /></div>}\n      <Bump />\n    </div>\n  );\n}\n\nfunction Bump() {\n  return null;\n}\n",
      sol: "function Counter({ onReady }) {\n  const [n, setN] = React.useState(0);\n  return <span className=\"n\" onClick={() => setN(v => v + 1)}>{n}</span>;\n}\n\nfunction App() {\n  const [on, setOn] = React.useState(false);\n  return (\n    <div>\n      <button className=\"go\" onClick={() => setOn(v => !v)}>바꾸기</button>\n      <div className={on ? 'b' : 'a'}><Counter /></div>\n    </div>\n  );\n}\n",
      tests: [{ d: "처음은 0", js: "TXT('.n')==='0'" },
              { d: "숫자를 누르면 올라간다", js: "(CLICK('.n'), TXT('.n')==='1')" },
              { d: "바꾸기를 눌러도 값이 유지된다", js: "(CLICK('.n'), CLICK('.go'), TXT('.n')==='2')" },
              { d: "클래스는 바뀐다", js: "(CLICK('.go'), COUNT('.b')===1 || COUNT('.a')===1)" }],
      ex: "감싸는 태그가 `div` 에서 `section` 으로 바뀌면 리액트는 그 자리를 통째로 버리고 새로 만듭니다 — 안에 있던 `Counter` 의 상태도 함께 사라져 0 으로 돌아가요. 같은 타입을 유지하고 속성만 바꾸면 상태가 살아남습니다.",
    },
    {
      k: "cond · 조건부로 사라져도 형제가 안 흔들리게",
      qq: "체크박스를 누르면 안내문이 <b>나타났다 사라집니다</b>. 그동안 아래 입력칸의 값은 <b>유지</b>되어야 합니다.",
      src: "function App() {\n  const [show, setShow] = React.useState(false);\n  return (\n    <div>\n      <button className=\"t\" onClick={() => setShow(v => !v)}>토글</button>\n      {show ? (\n        <div>\n          <p className=\"hint\">안내</p>\n          <input className=\"box\" defaultValue=\"\" />\n        </div>\n      ) : (\n        <div>\n          <input className=\"box\" defaultValue=\"\" />\n        </div>\n      )}\n    </div>\n  );\n}\n",
      sol: "function App() {\n  const [show, setShow] = React.useState(false);\n  return (\n    <div>\n      <button className=\"t\" onClick={() => setShow(v => !v)}>토글</button>\n      <div>\n        {show ? <p className=\"hint\">안내</p> : null}\n        <input className=\"box\" defaultValue=\"\" />\n      </div>\n    </div>\n  );\n}\n",
      tests: [{ d: "처음엔 안내가 없다", js: "COUNT('.hint')===0" },
              { d: "토글하면 안내가 뜬다", js: "(CLICK('.t'), COUNT('.hint')===1)" },
              { d: "입력값이 토글 뒤에도 남는다", js: "(TYPE('.box','안녕'), CLICK('.t'), Q('.box').value==='안녕')" },
              { d: "다시 토글해도 남는다", js: "(TYPE('.box','다시'), CLICK('.t'), CLICK('.t'), Q('.box').value==='다시')" }],
      ex: "두 갈래에 각각 입력칸을 두면, 겉보기에는 같은 칸이지만 리액트에게는 **다른 자리**입니다 — 토글할 때마다 새로 만들어져 입력한 값이 날아가요. 바뀌는 부분만 조건부로 두고 나머지는 한 번만 적으면, 자리가 그대로라 상태가 살아남습니다.",
    },
  ],
},
/* ── 훅 내부와 규칙 ─────────────────────────────────────── */
{
  unit: "훅 내부와 규칙",
  lesson: "직접 짜 보기 — 훅은 순서로 기억한다",
  th: {
    sum: "훅은 이름이 아니라 **부른 순서**로 값을 찾는다. 그래서 순서가 늘 같아야 한다.",
    body: [
      { h: "조건 안에서 부르면 순서가 어긋난다", t: "`if` 안에서 `useState` 를 부르면 어떤 렌더에서는 건너뛴다. 그러면 두 번째 훅이 첫 번째 자리에서 값을 찾아 엉뚱한 상태를 읽는다 — 그래서 훅은 언제나 맨 위에서, 조건 없이 부른다." },
      { h: "상태 갱신은 모아서 한 번에", t: "`setN(n + 1)` 을 두 번 부르면 둘 다 같은 `n` 을 읽어 1만 올라간다. `setN(v => v + 1)` 처럼 함수로 주면 앞의 결과 위에서 계산해 두 번 다 반영된다." },
      { h: "이전 값이 필요하면 함수형으로", t: "이벤트 핸들러나 타이머 안에서는 바깥의 `n` 이 그 시점에 붙잡힌 옛 값일 수 있다. 함수형 갱신은 리액트가 최신 값을 넘겨 주니 그 함정이 없다." },
      { h: "useRef 는 값을 들고 있되 다시 그리지 않는다", t: "`ref.current` 를 바꿔도 렌더가 일어나지 않는다. 화면에 안 보이는 값(타이머 id, 이전 값, DOM 참조)에 쓰고, 화면에 보여야 하는 값에는 쓰지 않는다." },
    ],
    code: { c: "// 나쁨\nif (cond) { const [a] = React.useState(0); }\n\n// 좋음: 맨 위에서 조건 없이\nconst [a, setA] = React.useState(0);\n\nsetN(v => v + 1);   // 앞의 결과 위에서", cap: "순서가 곧 이름이다" },
    key: ["훅은 조건 없이 맨 위에서", "연속 갱신은 함수형으로", "`useRef` 는 렌더를 일으키지 않는다"],
  },
  q: [
    {
      k: "twice · 두 번 누른 만큼 올라가게",
      qq: "버튼 한 번에 <b>2 씩</b> 올라가게 하세요. <code>set</code> 을 <b>두 번</b> 불러서 그렇게 되어야 합니다.",
      src: "function App() {\n  const [n, setN] = React.useState(0);\n  const go = () => { setN(n + 1); setN(n + 1); };\n  return (\n    <div>\n      <button className=\"go\" onClick={go}>더하기</button>\n      <span className=\"n\">{n}</span>\n    </div>\n  );\n}\n",
      sol: "function App() {\n  const [n, setN] = React.useState(0);\n  const go = () => { setN(v => v + 1); setN(v => v + 1); };\n  return (\n    <div>\n      <button className=\"go\" onClick={go}>더하기</button>\n      <span className=\"n\">{n}</span>\n    </div>\n  );\n}\n",
      tests: [{ d: "처음은 0", js: "TXT('.n')==='0'" },
              { d: "한 번 누르면 2", js: "(CLICK('.go'), TXT('.n')==='2')" },
              { d: "두 번 누르면 4", js: "(CLICKN('.go',2), TXT('.n')==='4')" },
              { d: "세 번 누르면 6", js: "(CLICKN('.go',3), TXT('.n')==='6')" }],
      ex: "`setN(n + 1)` 을 두 번 부르면 둘 다 그 렌더에 붙잡힌 같은 `n` 을 읽습니다 — 0 + 1 을 두 번 예약하는 셈이라 결과는 1 이에요. 함수형으로 주면 리액트가 앞의 결과를 넘겨 주니 두 번 다 반영됩니다.",
    },
    {
      k: "hookOrder · 조건 안에서 부르지 않기",
      qq: "체크 상태에 따라 <b>추가 카운터를 보여 줄지</b> 정합니다. 훅은 <b>언제나 같은 순서</b>로 불려야 합니다.",
      src: "function App() {\n  const [on, setOn] = React.useState(false);\n  if (on) {\n    const [extra, setExtra] = React.useState(7);\n    return (\n      <div>\n        <button className=\"t\" onClick={() => setOn(v => !v)}>토글</button>\n        <span className=\"x\">{extra}</span>\n      </div>\n    );\n  }\n  return (\n    <div>\n      <button className=\"t\" onClick={() => setOn(v => !v)}>토글</button>\n    </div>\n  );\n}\n",
      sol: "function App() {\n  const [on, setOn] = React.useState(false);\n  const [extra, setExtra] = React.useState(7);\n  return (\n    <div>\n      <button className=\"t\" onClick={() => setOn(v => !v)}>토글</button>\n      {on ? <span className=\"x\">{extra}</span> : null}\n    </div>\n  );\n}\n",
      tests: [{ d: "처음엔 안 보인다", js: "COUNT('.x')===0" },
              { d: "토글하면 보인다", js: "(CLICK('.t'), TXT('.x')==='7')" },
              { d: "껐다 켜도 값이 같다", js: "(CLICKN('.t',3), TXT('.x')==='7')" },
              { d: "끄면 다시 사라진다", js: "(CLICKN('.t',2), COUNT('.x')===0)" }],
      ex: "훅은 이름이 아니라 부른 **순서**로 값을 찾습니다. 조건 안에서 부르면 어떤 렌더에서는 건너뛰어, 그다음 훅이 앞자리 값을 읽게 돼요. 훅은 전부 맨 위에서 부르고, 보여 줄지 말지는 JSX 에서 정합니다.",
    },
    {
      k: "refCount · 렌더를 일으키지 않는 값",
      qq: "버튼을 누른 <b>횟수</b>는 화면에 보여 주고, <b>렌더 횟수</b>는 <code>useRef</code> 로 세어 화면에 함께 보여 주세요. ref 를 바꾸는 것만으로는 다시 그려지지 않습니다.",
      src: "function App() {\n  const [n, setN] = React.useState(0);\n  const [renders, setRenders] = React.useState(0);\n  setRenders(renders + 1);\n  return (\n    <div>\n      <button className=\"go\" onClick={() => setN(v => v + 1)}>누르기</button>\n      <span className=\"n\">{n}</span>\n      <span className=\"r\">{renders}</span>\n    </div>\n  );\n}\n",
      sol: "function App() {\n  const [n, setN] = React.useState(0);\n  const renders = React.useRef(0);\n  renders.current += 1;\n  return (\n    <div>\n      <button className=\"go\" onClick={() => setN(v => v + 1)}>누르기</button>\n      <span className=\"n\">{n}</span>\n      <span className=\"r\">{renders.current}</span>\n    </div>\n  );\n}\n",
      tests: [{ d: "처음 누른 횟수는 0", js: "TXT('.n')==='0'" },
              { d: "누르면 올라간다", js: "(CLICK('.go'), TXT('.n')==='1')" },
              { d: "렌더 횟수도 함께 는다", js: "(() => { const a = Number(TXT('.r')); CLICK('.go'); return Number(TXT('.r')) > a; })()" },
              { d: "여러 번 눌러도 멈추지 않는다", js: "(CLICKN('.go',5), TXT('.n')==='6')" }],
      ex: "렌더 중에 `setState` 를 부르면 다시 렌더되고, 또 부르고… 무한 반복이 됩니다. 화면에 보여 주긴 하되 그것 때문에 다시 그릴 필요는 없는 값이라면 `useRef` 예요 — `current` 를 바꿔도 렌더가 일어나지 않아, 이미 진행 중인 렌더에 얹어 보여 줄 수 있습니다.",
    },
  ],
},
/* ── 성능 최적화 ────────────────────────────────────────── */
{
  unit: "성능 최적화",
  lesson: "직접 짜 보기 — 안 바뀐 것은 다시 만들지 않기",
  th: {
    sum: "리액트 최적화의 대부분은 **매 렌더마다 새로 만들어지는 것을 줄이는 일**이다.",
    body: [
      { h: "객체와 함수는 렌더마다 새것", t: "JSX 안에서 만든 `{}` 나 화살표 함수는 매번 새 참조다. 자식이 `React.memo` 로 감싸져 있어도 참조가 달라 매번 다시 그린다 — 메모를 붙였는데 효과가 없는 흔한 이유다." },
      { h: "useMemo 는 값, useCallback 은 함수", t: "둘 다 의존성이 안 바뀌면 이전 것을 그대로 준다. 다만 공짜가 아니라 비교 비용이 있으니, 정말 비싼 계산이나 memo 자식에게 넘기는 것에만 쓴다." },
      { h: "의존성 배열을 속이지 않는다", t: "빈 배열로 두면 처음 값에 영원히 붙잡힌다. 린트가 알려 주는 의존성을 지우는 대신, 왜 그것이 자주 바뀌는지를 고친다." },
      { h: "먼저 재고 나서 고친다", t: "느껴지지 않는 렌더를 줄이는 데 시간을 쓰는 것보다, 느린 곳 하나를 찾는 편이 낫다. 프로파일러로 실제로 오래 걸리는 컴포넌트를 먼저 본다." },
    ],
    code: { c: "// 매 렌더마다 새 참조\n<Child style={{color:'red'}} onDone={() => f()} />\n\n// 유지\nconst style = React.useMemo(() => ({color:'red'}), []);\nconst onDone = React.useCallback(() => f(), []);", cap: "새로 만들지 않으면 다시 안 그린다" },
    key: ["객체·함수는 렌더마다 새것", "`useMemo`/`useCallback` 은 공짜가 아니다", "의존성을 속이지 않는다"],
  },
  q: [
    {
      k: "memoChild · 참조가 같아야 메모가 산다",
      qq: "<code>React.memo</code> 로 감싼 자식에게 <b>같은 참조</b>의 설정 객체를 넘겨, 부모가 다시 그려도 <b>자식은 다시 안 그려지게</b> 하세요.",
      src: "const Child = React.memo(function Child({ cfg }) {\n  const c = React.useRef(0);\n  c.current += 1;\n  return <span className=\"c\">{c.current}</span>;\n});\n\nfunction App() {\n  const [n, setN] = React.useState(0);\n  const cfg = { color: 'red' };\n  return (\n    <div>\n      <button className=\"go\" onClick={() => setN(v => v + 1)}>부모 갱신</button>\n      <span className=\"n\">{n}</span>\n      <Child cfg={cfg} />\n    </div>\n  );\n}\n",
      sol: "const Child = React.memo(function Child({ cfg }) {\n  const c = React.useRef(0);\n  c.current += 1;\n  return <span className=\"c\">{c.current}</span>;\n});\n\nfunction App() {\n  const [n, setN] = React.useState(0);\n  const cfg = React.useMemo(() => ({ color: 'red' }), []);\n  return (\n    <div>\n      <button className=\"go\" onClick={() => setN(v => v + 1)}>부모 갱신</button>\n      <span className=\"n\">{n}</span>\n      <Child cfg={cfg} />\n    </div>\n  );\n}\n",
      tests: [{ d: "부모는 갱신된다", js: "(CLICK('.go'), TXT('.n')==='1')" },
              { d: "자식은 다시 안 그려진다", js: "(() => { const a = TXT('.c'); CLICKN('.go',3); return TXT('.c')===a; })()" },
              { d: "자식이 한 번은 그려졌다", js: "Number(TXT('.c'))>=1" }],
      ex: "`{ color: 'red' }` 는 매 렌더마다 **새 객체**입니다. 값이 같아도 참조가 달라 `React.memo` 의 얕은 비교가 '바뀌었다' 고 판단해요 — memo 를 붙여 두고도 아무 효과가 없는 가장 흔한 이유입니다.",
    },
    {
      k: "stableCb · 함수도 매번 새것",
      qq: "메모된 자식에게 넘기는 <b>콜백의 참조</b>를 유지해, 부모가 갱신돼도 자식이 다시 안 그려지게 하세요.",
      src: "const Child = React.memo(function Child({ onPing }) {\n  const c = React.useRef(0);\n  c.current += 1;\n  return <span className=\"c\" onClick={onPing}>{c.current}</span>;\n});\n\nfunction App() {\n  const [n, setN] = React.useState(0);\n  const [pings, setPings] = React.useState(0);\n  const onPing = () => setPings(v => v + 1);\n  return (\n    <div>\n      <button className=\"go\" onClick={() => setN(v => v + 1)}>부모 갱신</button>\n      <span className=\"n\">{n}</span>\n      <span className=\"p\">{pings}</span>\n      <Child onPing={onPing} />\n    </div>\n  );\n}\n",
      sol: "const Child = React.memo(function Child({ onPing }) {\n  const c = React.useRef(0);\n  c.current += 1;\n  return <span className=\"c\" onClick={onPing}>{c.current}</span>;\n});\n\nfunction App() {\n  const [n, setN] = React.useState(0);\n  const [pings, setPings] = React.useState(0);\n  const onPing = React.useCallback(() => setPings(v => v + 1), []);\n  return (\n    <div>\n      <button className=\"go\" onClick={() => setN(v => v + 1)}>부모 갱신</button>\n      <span className=\"n\">{n}</span>\n      <span className=\"p\">{pings}</span>\n      <Child onPing={onPing} />\n    </div>\n  );\n}\n",
      tests: [{ d: "부모 갱신에도 자식은 그대로", js: "(() => { const a = TXT('.c'); CLICKN('.go',3); return TXT('.c')===a; })()" },
              { d: "콜백은 여전히 동작한다", js: "(CLICK('.c'), TXT('.p')==='1')" },
              { d: "부모 값도 오른다", js: "(CLICK('.go'), Number(TXT('.n'))>=1)" }],
      ex: "화살표 함수도 매 렌더마다 새로 만들어집니다 — 하는 일이 같아도 참조가 달라요. `useCallback` 에 빈 의존성을 준 것은 안에서 함수형 갱신만 쓰기 때문입니다. 바깥 값을 읽었다면 그것을 의존성에 적어야 하고요.",
    },
    {
      k: "heavyMemo · 비싼 계산은 한 번만",
      qq: "입력값이 바뀔 때만 다시 계산하고, <b>다른 상태가 바뀔 때는 계산하지 않게</b> 하세요. 계산 횟수도 함께 보여 줍니다.",
      src: "function App() {\n  const [n, setN] = React.useState(0);\n  const [text, setText] = React.useState('가');\n  const calc = React.useRef(0);\n  const upper = (() => { calc.current += 1; return text + '!'; })();\n  return (\n    <div>\n      <button className=\"go\" onClick={() => setN(v => v + 1)}>다른 상태</button>\n      <button className=\"ch\" onClick={() => setText(t => t + '나')}>글자 바꾸기</button>\n      <span className=\"n\">{n}</span>\n      <span className=\"u\">{upper}</span>\n      <span className=\"c\">{calc.current}</span>\n    </div>\n  );\n}\n",
      sol: "function App() {\n  const [n, setN] = React.useState(0);\n  const [text, setText] = React.useState('가');\n  const calc = React.useRef(0);\n  const upper = React.useMemo(() => { calc.current += 1; return text + '!'; }, [text]);\n  return (\n    <div>\n      <button className=\"go\" onClick={() => setN(v => v + 1)}>다른 상태</button>\n      <button className=\"ch\" onClick={() => setText(t => t + '나')}>글자 바꾸기</button>\n      <span className=\"n\">{n}</span>\n      <span className=\"u\">{upper}</span>\n      <span className=\"c\">{calc.current}</span>\n    </div>\n  );\n}\n",
      tests: [{ d: "처음 결과", js: "TXT('.u')==='가!'" },
              { d: "다른 상태가 바뀌어도 다시 계산하지 않는다", js: "(() => { const a = TXT('.c'); CLICKN('.go',3); return TXT('.c')===a; })()" },
              { d: "글자가 바뀌면 다시 계산한다", js: "(() => { const a = Number(TXT('.c')); CLICK('.ch'); return Number(TXT('.c')) > a; })()" },
              { d: "결과도 따라 바뀐다", js: "(CLICK('.ch'), TXT('.u').endsWith('!'))" }],
      ex: "렌더 본문에서 그냥 계산하면 어떤 상태가 바뀌든 매번 다시 합니다 — 관계없는 버튼을 눌러도 무거운 일이 도는 거예요. `useMemo` 의 의존성에 `text` 만 적어 두면, 그 값이 바뀔 때만 계산합니다.",
    },
  ],
},
/* ── 상태 관리 설계 ─────────────────────────────────────── */
{
  unit: "상태 관리 설계 심화: 로컬·전역·서버 상태 실무",
  lesson: "직접 짜 보기 — 어디에 둘 것인가",
  th: {
    sum: "상태 관리의 첫 질문은 라이브러리가 아니라 **이 값이 누구의 것인가**다.",
    body: [
      { h: "가능하면 가장 가까운 곳에", t: "한 컴포넌트만 쓰는 값은 그 안에 둔다. 전역으로 올리면 아무나 바꿀 수 있게 되고, 바뀔 때마다 관계없는 곳까지 다시 그린다." },
      { h: "파생된 값은 상태로 두지 않는다", t: "`items` 가 있으면 `count` 는 계산하면 된다. 둘 다 상태로 두면 언젠가 어긋나고, 그때 어느 쪽이 맞는지 알 수 없다 — 진실은 한 곳에만." },
      { h: "서버 상태는 다른 종류다", t: "서버에서 온 데이터는 '내 것' 이 아니라 사본이다. 낡을 수 있고, 다시 가져와야 하고, 여러 화면이 함께 본다 — 로컬 상태와 같은 도구로 다루면 캐시·재검증을 전부 손으로 짜게 된다." },
      { h: "올릴 때는 필요한 만큼만", t: "두 형제가 같은 값을 봐야 하면 공통 부모까지만 올린다. 앱 꼭대기까지 올리는 순간, 그 값을 안 쓰는 컴포넌트도 함께 다시 그려진다." },
    ],
    code: { c: "// 파생은 계산\nconst count = items.length;        // 상태로 두지 않는다\nconst done = items.filter(i => i.done);\n\n// 올리는 것은 공통 부모까지만", cap: "진실은 한 곳에만" },
    key: ["가장 가까운 곳에 둔다", "파생값은 계산한다", "서버 상태는 사본이다"],
  },
  q: [
    {
      k: "derived · 개수를 따로 들고 있지 않기",
      qq: "항목을 추가하면 <b>개수</b>가 따라 바뀝니다. 개수는 <b>상태로 두지 말고</b> 계산하세요.",
      src: "function App() {\n  const [items, setItems] = React.useState([]);\n  const [count, setCount] = React.useState(0);\n  const add = () => { setItems(v => [...v, v.length]); };\n  return (\n    <div>\n      <button className=\"go\" onClick={add}>추가</button>\n      <span className=\"c\">{count}</span>\n      <ul className=\"list\">{items.map(i => <li key={i} className=\"row\">{i}</li>)}</ul>\n    </div>\n  );\n}\n",
      sol: "function App() {\n  const [items, setItems] = React.useState([]);\n  const count = items.length;\n  const add = () => { setItems(v => [...v, v.length]); };\n  return (\n    <div>\n      <button className=\"go\" onClick={add}>추가</button>\n      <span className=\"c\">{count}</span>\n      <ul className=\"list\">{items.map(i => <li key={i} className=\"row\">{i}</li>)}</ul>\n    </div>\n  );\n}\n",
      tests: [{ d: "처음은 0", js: "TXT('.c')==='0'" },
              { d: "추가하면 개수가 따라간다", js: "(CLICK('.go'), TXT('.c')==='1')" },
              { d: "세 번 추가하면 3", js: "(CLICKN('.go',3), TXT('.c')==='3')" },
              { d: "실제 항목 수와 같다", js: "(CLICKN('.go',2), Number(TXT('.c'))===COUNT('.row'))" }],
      ex: "개수를 따로 상태로 두면 추가하는 자리마다 둘을 함께 고쳐야 하고, 언젠가 한 곳을 빠뜨립니다 — 목록에는 세 개인데 '2개' 라고 표시되는 거예요. 계산할 수 있는 값은 계산하면, 어긋날 자리가 아예 없습니다.",
    },
    {
      k: "liftUp · 필요한 만큼만 올리기",
      qq: "두 자식이 <b>같은 선택값</b>을 봅니다. 값을 <b>공통 부모</b>에 두고 양쪽에 내려 주세요.",
      src: "function Picker({ value, onPick }) {\n  const [own, setOwn] = React.useState('가');\n  return <button className=\"pick\" onClick={() => setOwn('나')}>{own}</button>;\n}\n\nfunction Label({ value }) {\n  return <span className=\"label\">{value}</span>;\n}\n\nfunction App() {\n  const [value, setValue] = React.useState('가');\n  return (\n    <div>\n      <Picker value={value} onPick={setValue} />\n      <Label value={value} />\n    </div>\n  );\n}\n",
      sol: "function Picker({ value, onPick }) {\n  return <button className=\"pick\" onClick={() => onPick('나')}>{value}</button>;\n}\n\nfunction Label({ value }) {\n  return <span className=\"label\">{value}</span>;\n}\n\nfunction App() {\n  const [value, setValue] = React.useState('가');\n  return (\n    <div>\n      <Picker value={value} onPick={setValue} />\n      <Label value={value} />\n    </div>\n  );\n}\n",
      tests: [{ d: "처음엔 둘 다 '가'", js: "TXT('.pick')==='가' && TXT('.label')==='가'" },
              { d: "고르면 둘 다 바뀐다", js: "(CLICK('.pick'), TXT('.label')==='나')" },
              { d: "버튼 글자도 따라간다", js: "(CLICK('.pick'), TXT('.pick')==='나')" }],
      ex: "자식이 자기 상태를 따로 들고 있으면, 버튼 글자는 바뀌는데 옆의 라벨은 그대로입니다 — 화면 안에서 같은 값이 서로 다르게 보여요. 둘이 함께 봐야 하는 값이면 공통 부모 한 곳에 두고 내려 줍니다.",
    },
    {
      k: "serverState · 낡았는지 표시하기",
      qq: "가져온 데이터와 <b>가져온 시각</b>을 받아, <code>ttl</code> 을 넘겼으면 <code>&lt;span class=\"stale\"&gt;</code> 를 함께 보여 주세요. 버튼을 누르면 시각이 <b>지금</b>으로 갱신됩니다.",
      src: "function App() {\n  const [now, setNow] = React.useState(1000);\n  const fetchedAt = 0;\n  const ttl = 100;\n  return (\n    <div>\n      <button className=\"go\" onClick={() => setNow(0)}>새로고침</button>\n      <span className=\"data\">값</span>\n    </div>\n  );\n}\n",
      sol: "function App() {\n  const [fetchedAt, setFetchedAt] = React.useState(0);\n  const now = 1000;\n  const ttl = 100;\n  const stale = now - fetchedAt > ttl;\n  return (\n    <div>\n      <button className=\"go\" onClick={() => setFetchedAt(now)}>새로고침</button>\n      <span className=\"data\">값</span>\n      {stale ? <span className=\"stale\">낡음</span> : null}\n    </div>\n  );\n}\n",
      tests: [{ d: "처음엔 낡았다고 표시된다", js: "COUNT('.stale')===1" },
              { d: "데이터는 그대로 보인다", js: "TXT('.data')==='값'" },
              { d: "새로고침하면 표시가 사라진다", js: "(CLICK('.go'), COUNT('.stale')===0)" },
              { d: "새로고침 뒤에도 데이터는 있다", js: "(CLICK('.go'), TXT('.data')==='값')" }],
      ex: "서버에서 온 값은 '내 상태' 가 아니라 **그 시점의 사본**입니다. 언제 가져왔는지를 함께 들고 있지 않으면 며칠 지난 값을 새것처럼 보여 주게 돼요 — 낡았음을 표시하되 값은 계속 보여 주는 것이, 화면을 비우는 것보다 대개 낫습니다.",
    },
  ],
},
/* ── 에러 경계와 Suspense ───────────────────────────────── */
{
  unit: "에러 경계와 Suspense — 선언적 로딩·에러 복구·코드 분할 (심화)",
  lesson: "직접 짜 보기 — 무너져도 화면은 남게",
  th: {
    sum: "에러 경계는 **한 부분이 무너져도 나머지 화면을 지키는 울타리**다.",
    body: [
      { h: "울타리가 없으면 전부 사라진다", t: "리액트 16 부터 렌더 중 예외가 잡히지 않으면 트리 전체를 걷어낸다. 흰 화면이 뜨는 이유다 — 경계를 두면 그 안쪽만 대체 화면으로 바뀐다." },
      { h: "경계는 렌더 오류만 잡는다", t: "이벤트 핸들러 안의 예외, 비동기 콜백, 서버 렌더링 오류는 못 잡는다. 그쪽은 `try/catch` 로 직접 다뤄야 한다 — 경계 하나로 다 된다고 믿으면 구멍이 남는다." },
      { h: "울타리를 어디에 칠지가 설계다", t: "앱 전체에 하나만 두면 결국 흰 화면과 비슷하다. 위젯·탭·목록 항목처럼 '이것만 없어도 나머지는 쓸 만한' 단위로 나눠 둔다." },
      { h: "다시 시도할 길을 준다", t: "대체 화면에 '다시 불러오기' 를 두고, 누르면 경계의 상태를 되돌린다. 사용자가 새로고침 말고 할 수 있는 일이 하나는 있어야 한다." },
    ],
    code: { c: "class Boundary extends React.Component {\n  state = { err: null };\n  static getDerivedStateFromError(e) { return { err: e }; }\n  render() {\n    if (this.state.err) return this.props.fallback;\n    return this.props.children;\n  }\n}", cap: "무너지는 범위를 좁힌다" },
    key: ["경계가 없으면 화면 전체가 사라진다", "렌더 오류만 잡는다", "울타리를 잘게 나눈다"],
  },
  q: [
    {
      k: "boundary · 옆 위젯은 살아남게",
      qq: "터지는 위젯을 <b>에러 경계</b>로 감싸, 옆의 정상 위젯은 <b>그대로 보이게</b> 하세요. 대체 화면은 <code>&lt;span class=\"fallback\"&gt;</code> 입니다.",
      src: "function Boom() {\n  throw new Error('의도된 실패');\n}\n\nfunction Ok() {\n  return <span className=\"ok\">정상</span>;\n}\n\nfunction App() {\n  return (\n    <div>\n      <Ok />\n      <Boom />\n    </div>\n  );\n}\n",
      sol: "class Boundary extends React.Component {\n  constructor(p) { super(p); this.state = { err: null }; }\n  static getDerivedStateFromError(e) { return { err: e }; }\n  render() {\n    if (this.state.err) return <span className=\"fallback\">문제가 생겼어요</span>;\n    return this.props.children;\n  }\n}\n\nfunction Boom() {\n  throw new Error('의도된 실패');\n}\n\nfunction Ok() {\n  return <span className=\"ok\">정상</span>;\n}\n\nfunction App() {\n  return (\n    <div>\n      <Ok />\n      <Boundary><Boom /></Boundary>\n    </div>\n  );\n}\n",
      tests: [{ d: "정상 위젯이 살아 있다", js: "TXT('.ok')==='정상'" },
              { d: "대체 화면이 보인다", js: "COUNT('.fallback')===1" },
              { d: "터진 위젯 자리에만 나온다", js: "COUNT('.ok')===1 && COUNT('.fallback')===1" }],
      ex: "경계가 없으면 위젯 하나의 예외가 트리 전체를 걷어냅니다 — 멀쩡한 부분까지 사라진 흰 화면이 되는 거예요. 울타리를 위젯 단위로 치면 그 자리만 대체 화면이 되고, 사용자는 나머지를 계속 쓸 수 있습니다.",
    },
    {
      k: "retry · 다시 해 볼 길을 준다",
      qq: "에러 경계의 대체 화면에 <b>다시 시도 버튼</b>을 두세요. 누르면 경계가 초기화되고, 두 번째에는 성공합니다.",
      src: "let attempts = 0;\n\nclass Boundary extends React.Component {\n  constructor(p) { super(p); this.state = { err: null }; }\n  static getDerivedStateFromError(e) { return { err: e }; }\n  render() {\n    if (this.state.err) return <span className=\"fallback\">실패</span>;\n    return this.props.children;\n  }\n}\n\nfunction Flaky() {\n  attempts += 1;\n  if (attempts === 1) throw new Error('의도된 실패');\n  return <span className=\"ok\">성공</span>;\n}\n\nfunction App() {\n  return <Boundary><Flaky /></Boundary>;\n}\n",
      sol: "let attempts = 0;\n\nclass Boundary extends React.Component {\n  constructor(p) { super(p); this.state = { err: null }; }\n  static getDerivedStateFromError(e) { return { err: e }; }\n  render() {\n    if (this.state.err) {\n      return (\n        <span className=\"fallback\">\n          실패\n          <button className=\"retry\" onClick={() => this.setState({ err: null })}>다시</button>\n        </span>\n      );\n    }\n    return this.props.children;\n  }\n}\n\nfunction Flaky() {\n  attempts += 1;\n  if (attempts === 1) throw new Error('의도된 실패');\n  return <span className=\"ok\">성공</span>;\n}\n\nfunction App() {\n  return <Boundary><Flaky /></Boundary>;\n}\n",
      tests: [{ d: "처음엔 실패 화면", js: "COUNT('.fallback')===1" },
              { d: "다시 시도 버튼이 있다", js: "COUNT('.retry')===1" },
              { d: "누르면 성공한다", js: "(CLICK('.retry'), TXT('.ok')==='성공')" },
              { d: "실패 화면은 사라진다", js: "(CLICK('.retry'), COUNT('.fallback')===0)" }],
      ex: "대체 화면에 '문제가 생겼어요' 만 있으면 사용자가 할 수 있는 일이 새로고침뿐입니다 — 그러면 다른 탭에서 하던 작업까지 날아가요. 경계의 상태를 되돌리는 버튼 하나면 그 자리만 다시 시도됩니다.",
    },
    {
      k: "scopeBoundary · 울타리를 잘게",
      qq: "목록의 <b>각 항목</b>을 따로 감싸, 한 항목이 터져도 <b>나머지 항목은 보이게</b> 하세요.",
      src: "class Boundary extends React.Component {\n  constructor(p) { super(p); this.state = { err: null }; }\n  static getDerivedStateFromError(e) { return { err: e }; }\n  render() {\n    if (this.state.err) return <li className=\"bad\">오류</li>;\n    return this.props.children;\n  }\n}\n\nfunction Row({ v }) {\n  if (v === 2) throw new Error('의도된 실패');\n  return <li className=\"row\">{v}</li>;\n}\n\nfunction App() {\n  return (\n    <ul>\n      <Boundary>\n        {[1, 2, 3].map(v => <Row key={v} v={v} />)}\n      </Boundary>\n    </ul>\n  );\n}\n",
      sol: "class Boundary extends React.Component {\n  constructor(p) { super(p); this.state = { err: null }; }\n  static getDerivedStateFromError(e) { return { err: e }; }\n  render() {\n    if (this.state.err) return <li className=\"bad\">오류</li>;\n    return this.props.children;\n  }\n}\n\nfunction Row({ v }) {\n  if (v === 2) throw new Error('의도된 실패');\n  return <li className=\"row\">{v}</li>;\n}\n\nfunction App() {\n  return (\n    <ul>\n      {[1, 2, 3].map(v => (\n        <Boundary key={v}><Row v={v} /></Boundary>\n      ))}\n    </ul>\n  );\n}\n",
      tests: [{ d: "멀쩡한 항목 둘이 남는다", js: "COUNT('.row')===2" },
              { d: "터진 자리 하나만 오류", js: "COUNT('.bad')===1" },
              { d: "첫 항목이 보인다", js: "TXT('.row')==='1'" },
              { d: "마지막 항목도 보인다", js: "QA('.row')[1].textContent==='3'" }],
      ex: "목록 전체를 하나로 감싸면 항목 하나의 오류에 목록이 통째로 사라집니다 — 100건 중 1건이 이상해서 99건을 못 보는 거예요. 울타리를 항목 단위로 내리면 잃는 것이 딱 그 한 줄입니다.",
    },
  ],
},
/* ── 코드 리뷰 ──────────────────────────────────────────── */
{
  unit: "코드 리뷰 — 결함 찾기",
  lesson: "직접 고쳐 보기 — 리액트 리뷰의 단골",
  th: {
    sum: "리액트 리뷰에서 걸리는 것은 대개 **상태를 제자리에서 바꾸거나, 정리를 안 하거나, key 를 잘못 쓴 것**이다.",
    body: [
      { h: "상태를 제자리에서 바꾸지 않는다", t: "`items.push(x)` 뒤에 `setItems(items)` 를 하면 같은 배열이라 리액트가 '안 바뀌었다' 고 본다. 화면이 그대로인 이유의 대부분이 이것이다." },
      { h: "정리 함수를 돌려준다", t: "`useEffect` 에서 만든 타이머·구독·리스너는 정리 함수에서 해제한다. 안 하면 컴포넌트가 사라진 뒤에도 돌아가며 없는 상태를 건드린다." },
      { h: "의존성 배열을 비워 두지 않는다", t: "빈 배열은 '처음 값에 영원히 붙잡힌다' 는 뜻이다. 타이머 안에서 옛 상태를 읽는 버그가 여기서 나온다 — 함수형 갱신을 쓰거나 의존성을 제대로 적는다." },
      { h: "controlled 와 uncontrolled 를 섞지 않는다", t: "`value` 를 주면서 `onChange` 를 안 주면 입력이 안 된다. 반대로 `defaultValue` 와 `value` 를 함께 주면 경고가 난다 — 둘 중 하나로 정한다." },
    ],
    code: { c: "// 나쁨\nitems.push(x); setItems(items);\n// 좋음\nsetItems([...items, x]);\n\nReact.useEffect(() => {\n  const id = setInterval(f, 100);\n  return () => clearInterval(id);   // 정리\n}, []);", cap: "새 값·정리·key" },
    key: ["제자리에서 바꾸지 않는다", "정리 함수를 돌려준다", "controlled 를 섞지 않는다"],
  },
  q: [
    {
      k: "immutableAdd · 새 배열을 넘겨야 다시 그린다",
      qq: "버튼을 누르면 항목이 하나 늘어납니다. <b>화면이 실제로 갱신되게</b> 고치세요.",
      src: "function App() {\n  const [items, setItems] = React.useState([]);\n  const add = () => { items.push(items.length); setItems(items); };\n  return (\n    <div>\n      <button className=\"go\" onClick={add}>추가</button>\n      <ul>{items.map(i => <li key={i} className=\"row\">{i}</li>)}</ul>\n    </div>\n  );\n}\n",
      sol: "function App() {\n  const [items, setItems] = React.useState([]);\n  const add = () => setItems(v => [...v, v.length]);\n  return (\n    <div>\n      <button className=\"go\" onClick={add}>추가</button>\n      <ul>{items.map(i => <li key={i} className=\"row\">{i}</li>)}</ul>\n    </div>\n  );\n}\n",
      tests: [{ d: "처음엔 비어 있다", js: "COUNT('.row')===0" },
              { d: "한 번 누르면 하나", js: "(CLICK('.go'), COUNT('.row')===1)" },
              { d: "세 번 누르면 셋", js: "(CLICKN('.go',3), COUNT('.row')===3)" },
              { d: "값이 순서대로다", js: "(CLICKN('.go',2), QA('.row')[1].textContent==='1')" }],
      ex: "`push` 는 같은 배열을 고칠 뿐이라, `setItems(items)` 로 넘겨도 리액트는 참조가 같으니 '안 바뀌었다' 고 판단합니다 — 데이터는 늘었는데 화면만 그대로인, 원인 찾기 어려운 버그예요. 새 배열을 만들어 넘기면 그 자리에서 해결됩니다.",
    },
    {
      k: "cleanup · 사라진 뒤에도 돌아가지 않게",
      qq: "타이머를 <code>useEffect</code> 로 걸고 <b>정리 함수</b>를 돌려주세요. 정리가 불린 횟수도 화면에 보여 줍니다.",
      src: "let cleaned = 0;\n\nfunction Ticker() {\n  const [n, setN] = React.useState(0);\n  React.useEffect(() => {\n    const id = setInterval(() => setN(v => v + 1), 10000);\n  }, []);\n  return <span className=\"n\">{n}</span>;\n}\n\nfunction App() {\n  const [on, setOn] = React.useState(true);\n  return (\n    <div>\n      <button className=\"t\" onClick={() => setOn(v => !v)}>토글</button>\n      {on ? <Ticker /> : null}\n      <span className=\"c\">{cleaned}</span>\n    </div>\n  );\n}\n",
      sol: "let cleaned = 0;\n\nfunction Ticker() {\n  const [n, setN] = React.useState(0);\n  React.useEffect(() => {\n    const id = setInterval(() => setN(v => v + 1), 10000);\n    return () => { clearInterval(id); cleaned += 1; };\n  }, []);\n  return <span className=\"n\">{n}</span>;\n}\n\nfunction App() {\n  const [on, setOn] = React.useState(true);\n  return (\n    <div>\n      <button className=\"t\" onClick={() => setOn(v => !v)}>토글</button>\n      {on ? <Ticker /> : null}\n      <span className=\"c\">{cleaned}</span>\n    </div>\n  );\n}\n",
      tests: [{ d: "처음엔 정리된 적이 없다", js: "TXT('.c')==='0'" },
              { d: "티커가 보인다", js: "TXT('.n')==='0'" },
              { d: "끄면 정리가 불린다", js: "(CLICK('.t'), Number(TXT('.c'))>=1)" },
              { d: "껐다 켜도 티커가 다시 뜬다", js: "(CLICKN('.t',2), TXT('.n')==='0')" }],
      ex: "정리 함수를 안 돌려주면 컴포넌트가 사라진 뒤에도 타이머가 계속 돕니다. 사라진 컴포넌트의 `setN` 을 부르고, 화면을 나갔다 들어올 때마다 타이머가 하나씩 늘어나요 — 몇 분 뒤에는 수십 개가 동시에 도는 상태가 됩니다.",
    },
    {
      k: "controlled · 값을 주면 바꾸는 길도 준다",
      qq: "입력칸을 <b>제어 컴포넌트</b>로 만들어, 타이핑한 값이 아래에 그대로 보이게 하세요.",
      src: "function App() {\n  const [text, setText] = React.useState('');\n  return (\n    <div>\n      <input className=\"box\" value={text} />\n      <span className=\"out\">{text}</span>\n    </div>\n  );\n}\n",
      sol: "function App() {\n  const [text, setText] = React.useState('');\n  return (\n    <div>\n      <input className=\"box\" value={text} onChange={e => setText(e.target.value)} />\n      <span className=\"out\">{text}</span>\n    </div>\n  );\n}\n",
      tests: [{ d: "처음엔 비어 있다", js: "TXT('.out')===''" },
              { d: "타이핑하면 따라 나온다", js: "(TYPE('.box','안녕'), TXT('.out')==='안녕')" },
              { d: "입력칸에도 남아 있다", js: "(TYPE('.box','값'), Q('.box').value==='값')" },
              { d: "다시 쓰면 바뀐다", js: "(TYPE('.box','하나'), TYPE('.box','둘'), TXT('.out')==='둘')" }],
      ex: "`value` 만 주고 `onChange` 를 안 주면 입력칸이 상태에 고정돼 아무것도 타이핑되지 않습니다 — 사용자에게는 '입력이 안 되는 칸' 으로 보여요. 값을 리액트가 정할 거면 바꾸는 길도 함께 열어 줘야 합니다.",
    },
  ],
},
];
