/* SQL 코드 리뷰 2차 — 잘못된 쿼리·스키마를 읽고 결함을 모두 골라낸다.
   리뷰는 실행 없이도 시니어 훈련이 되는 유형이라 SQL 트랙의 가장 싼 구멍 메우기다(36 → 66).

   각 문항에는 검증용 필드가 붙는다(주입하지 않는다):
     schema  검증기가 만들 테이블
     bad/fix 결함이 있는 쿼리와 고친 쿼리
     proof   'rows'  — 두 쿼리의 결과가 달라야 한다(결함이 결과를 바꾼다는 증거)
             'plan'  — EXPLAIN QUERY PLAN 이 bad 는 SCAN, fix 는 SEARCH 여야 한다
             'error' — bad 는 실행 자체가 실패해야 한다
             null    — 실행으로 증명할 수 없는 종류(설계·보안). 사람 판단으로 남긴다 */
module.exports = [
{ k:"깊은 페이지네이션", cat:"review",
  q:"이 코드의 결함을 모두 고르세요",
  code:"SELECT id, title, created_at\nFROM posts\nORDER BY created_at DESC\nLIMIT 20 OFFSET 100000;",
  items:[
    {txt:"OFFSET 100000 은 앞의 10만 행을 <b>읽고 버린</b> 뒤 20행을 낸다. 페이지가 깊어질수록 선형으로 느려지므로, 마지막 행의 정렬 키를 조건으로 쓰는 커서 방식(<code>WHERE created_at &lt; ?</code>)으로 바꿔야 한다.", bad:true},
    {txt:"<code>created_at</code> 에 동점이 있으면 정렬 순서가 결정적이지 않아 <b>페이지 사이에서 행이 중복되거나 누락</b>된다. <code>ORDER BY created_at DESC, id DESC</code> 처럼 유일한 키를 마지막 기준으로 넣어야 한다.", bad:true},
    {txt:"<code>ORDER BY</code> 에 <code>DESC</code> 를 쓰면 인덱스를 사용할 수 없으므로 <code>ASC</code> 로 바꾸고 애플리케이션에서 뒤집어야 한다.", bad:false},
    {txt:"<code>LIMIT</code> 과 <code>OFFSET</code> 을 함께 쓰면 문법 오류이므로 <code>FETCH FIRST</code> 구문을 써야 한다.", bad:false},
    {txt:"필요한 컬럼만 지정한 것은 적절하다 — <code>id, title, created_at</code> 만 읽으면 커버링 인덱스로 처리될 여지가 생긴다.", bad:false}],
  ex:"실제 결함 2가지. (1) <b>OFFSET 은 건너뛰는 게 아니라 읽고 버리는 것</b>이다 — 10만 번째 페이지는 10만 행을 읽는다. 커서(키셋) 페이지네이션으로 바꾸면 인덱스로 시작점을 바로 잡아 페이지 깊이와 무관하게 일정하다. (2) 정렬 키에 동점이 있으면 순서가 매 실행마다 달라질 수 있어, 다음 페이지에서 같은 행이 또 나오거나 빠진다 — <b>유일한 tie-break</b> 가 필요하다.\n디스트랙터: 인덱스는 <b>양방향 스캔</b>이 가능해 DESC 자체는 문제가 아니다. <code>LIMIT ... OFFSET</code> 은 표준은 아니지만 대부분의 DBMS 가 지원하는 정상 문법이다. 컬럼을 명시한 것은 오히려 잘한 부분이다.",
  schema:"CREATE TABLE posts(id INTEGER, title TEXT, created_at TEXT);\nINSERT INTO posts VALUES (1,'a','2024-01-01'),(2,'b','2024-01-01'),(3,'c','2024-01-02');",
  bad:"SELECT id FROM posts ORDER BY created_at DESC LIMIT 1 OFFSET 1;",
  fix:"SELECT id FROM posts ORDER BY created_at DESC, id DESC LIMIT 1 OFFSET 1;",
  proof:"rows" },

{ k:"NOT IN 과 NULL", cat:"review",
  q:"이 코드의 결함을 모두 고르세요",
  code:"SELECT c.id, c.name\nFROM customers c\nWHERE c.id NOT IN (\n  SELECT o.customer_id FROM orders o\n);",
  items:[
    {txt:"<code>orders.customer_id</code> 에 NULL 이 하나라도 있으면 <b>결과가 통째로 빈다</b>. <code>NOT IN</code> 은 <code>&lt;&gt; NULL</code> 비교를 포함하는데 그 결과가 UNKNOWN 이라 AND 로 묶이면 참이 될 수 없다.", bad:true},
    {txt:"<code>NOT EXISTS</code> 나 <code>LEFT JOIN ... WHERE o.customer_id IS NULL</code> 로 바꾸면 NULL 에 영향받지 않고 의도대로 동작한다.", bad:false},
    {txt:"서브쿼리가 <code>orders</code> 전체를 읽으므로 <code>customer_id</code> 에 인덱스가 없으면 고객 수만큼 반복 스캔한다 — 인덱스가 필요하다.", bad:true},
    {txt:"상관 서브쿼리가 아니므로 옵티마이저가 한 번만 평가할 수 있어 성능은 항상 문제되지 않는다.", bad:false},
    {txt:"<code>NOT IN</code> 대신 <code>!=</code> 를 여러 번 나열하면 같은 의미이면서 더 빠르다.", bad:false}],
  ex:"실제 결함 2가지. (1) <b>NOT IN + NULL = 빈 결과</b>. SQL 의 NULL 은 '없음' 이 아니라 '<b>알 수 없음</b>' 이고, 알 수 없는 값과 다른지는 알 수 없으므로 UNKNOWN 이다. AND 사슬에서 UNKNOWN 은 절대 참이 되지 않는다. (2) 조인 키 인덱스가 없으면 반복 스캔이 된다.\n디스트랙터: <code>NOT EXISTS</code> 로의 전환은 결함이 아니라 <b>해결책</b>이다. 옵티마이저가 서브쿼리를 한 번만 평가하더라도 그 결과와의 비교 비용은 남으므로 '항상 문제없다' 는 틀렸다. <code>!=</code> 나열은 목록이 동적일 때 불가능하고 NULL 문제도 그대로다.",
  schema:"CREATE TABLE customers(id INTEGER, name TEXT);\nINSERT INTO customers VALUES (1,'a'),(2,'b');\nCREATE TABLE orders(customer_id INTEGER);\nINSERT INTO orders VALUES (1),(NULL);",
  bad:"SELECT id FROM customers WHERE id NOT IN (SELECT customer_id FROM orders);",
  fix:"SELECT id FROM customers c WHERE NOT EXISTS (SELECT 1 FROM orders o WHERE o.customer_id=c.id);",
  proof:"rows" },

{ k:"조인 팬아웃과 합계", cat:"review",
  q:"이 코드의 결함을 모두 고르세요",
  code:"SELECT o.id, SUM(o.amount) AS total, COUNT(*) AS items\nFROM orders o\nJOIN order_items i ON i.order_id = o.id\nGROUP BY o.id;",
  items:[
    {txt:"주문에 항목이 여러 개면 <code>o.amount</code> 가 <b>항목 수만큼 복제</b>되어 <code>SUM</code> 이 배수로 부풀어 오른다. 금액은 주문 테이블에서 따로 집계하거나 항목 합계로 계산해야 한다.", bad:true},
    {txt:"<code>COUNT(*)</code> 는 조인된 행을 세므로 항목 수로는 맞지만, 항목이 없는 주문은 <code>JOIN</code> 때문에 <b>결과에서 통째로 사라진다</b>. <code>LEFT JOIN</code> 이 필요하다.", bad:true},
    {txt:"<code>GROUP BY o.id</code> 에 <code>o.amount</code> 가 없으므로 표준 SQL 에서는 오류가 나야 하지만, 집계 함수 안에서만 쓰였으므로 정상이다.", bad:false},
    {txt:"<code>COUNT(*)</code> 대신 <code>COUNT(i.id)</code> 를 쓰면 NULL 을 세지 않으므로 <code>LEFT JOIN</code> 과 함께 쓸 때 유용하다.", bad:false},
    {txt:"<code>SUM</code> 과 <code>COUNT</code> 를 한 쿼리에서 함께 쓰면 옵티마이저가 두 번 스캔하므로 나눠야 한다.", bad:false}],
  ex:"실제 결함 2가지. (1) <b>팬아웃</b> — 1:N 조인은 왼쪽 행을 오른쪽 짝의 수만큼 복제한다. 그 상태로 왼쪽 컬럼을 SUM 하면 금액이 항목 수만큼 곱해진다. 'JOIN 뒤에 SUM' 은 항상 의심할 신호다. (2) INNER JOIN 이라 항목이 없는 주문이 사라진다 — '모든 주문' 을 세는 보고서라면 치명적이다.\n디스트랙터: 집계 함수 안의 컬럼은 GROUP BY 에 없어도 정상이다. <code>COUNT(i.id)</code> 지적은 결함이 아니라 <b>올바른 보완</b>이다. 한 번의 스캔으로 여러 집계를 내는 것은 오히려 효율적이다.",
  schema:"CREATE TABLE orders(id INTEGER, amount INTEGER);\nINSERT INTO orders VALUES (1,1000),(2,2000);\nCREATE TABLE order_items(order_id INTEGER, id INTEGER);\nINSERT INTO order_items VALUES (1,10),(1,11);",
  bad:"SELECT o.id, SUM(o.amount) AS total FROM orders o JOIN order_items i ON i.order_id=o.id GROUP BY o.id;",
  fix:"SELECT o.id, o.amount AS total FROM orders o WHERE EXISTS (SELECT 1 FROM order_items i WHERE i.order_id=o.id);",
  proof:"rows" },

{ k:"복합 인덱스 좌측 접두사", cat:"review",
  q:"이 코드의 결함을 모두 고르세요",
  code:"CREATE INDEX idx_ev ON events (created_at, tenant_id, type);\n\nSELECT * FROM events\nWHERE tenant_id = 42\n  AND type = 'login'\nORDER BY created_at DESC\nLIMIT 50;",
  items:[
    {txt:"인덱스의 <b>첫 컬럼이 조건에 없어</b> 이 인덱스로는 시작점을 잡을 수 없다. 조건 컬럼을 앞에 둔 <code>(tenant_id, type, created_at)</code> 이 맞다.", bad:true},
    {txt:"컬럼 순서를 바꾸면 등치 조건 두 개로 범위를 좁힌 뒤 <code>created_at</code> 이 이미 정렬돼 있어 <b>정렬 작업 자체가 사라진다</b>.", bad:false},
    {txt:"<code>SELECT *</code> 라서 인덱스만으로 답할 수 없고 매 행마다 테이블을 다시 찾아간다 — 필요한 컬럼만 골라 커버링 인덱스로 만들 여지가 있다.", bad:true},
    {txt:"복합 인덱스는 컬럼이 3개를 넘으면 사용되지 않으므로 2개로 줄여야 한다.", bad:false},
    {txt:"<code>LIMIT 50</code> 이 있으면 인덱스와 무관하게 50행만 읽으므로 인덱스 설계는 성능에 영향을 주지 않는다.", bad:false}],
  ex:"실제 결함 2가지. (1) <b>좌측 접두사 규칙</b> — 복합 인덱스는 왼쪽부터 연속으로 쓰일 때만 범위를 좁힐 수 있다. 첫 컬럼이 조건에 없으면 인덱스 전체를 훑거나 아예 안 쓴다. 규칙은 '<b>등치 조건 → 정렬 → 범위</b>' 순으로 컬럼을 배치하는 것이다. (2) <code>SELECT *</code> 는 인덱스에 없는 컬럼 때문에 테이블 재방문(bookmark lookup)을 강제한다.\n디스트랙터: 순서를 바꾸면 정렬이 공짜가 되는 것은 <b>맞는 설명이자 해결책</b>이다. 컬럼 수 3개 제한 같은 규칙은 없다. LIMIT 이 있어도 <b>조건에 맞는 행을 찾기까지</b> 얼마나 읽는지는 인덱스가 정한다.",
  schema:"CREATE TABLE events(id INTEGER, created_at TEXT, tenant_id INTEGER, type TEXT);\nCREATE INDEX idx_bad ON events(created_at, tenant_id, type);\nCREATE INDEX idx_good ON events(tenant_id, type, created_at);\nINSERT INTO events VALUES (1,'2024-01-01',42,'login');",
  bad:"SELECT id FROM events INDEXED BY idx_bad WHERE tenant_id=42 AND type='login';",
  fix:"SELECT id FROM events INDEXED BY idx_good WHERE tenant_id=42 AND type='login';",
  proof:"plan" },

{ k:"함수로 감싼 조건", cat:"review",
  q:"이 코드의 결함을 모두 고르세요",
  code:"SELECT id, email\nFROM users\nWHERE LOWER(email) = 'kim@example.com'\n  AND strftime('%Y', created_at) = '2024';",
  items:[
    {txt:"<code>LOWER(email)</code> 처럼 컬럼을 함수로 감싸면 <b>인덱스를 쓸 수 없다</b>. 저장 시 소문자로 정규화하거나 표현식 인덱스를 만들어야 한다.", bad:true},
    {txt:"<code>strftime('%Y', created_at) = '2024'</code> 도 같은 이유로 인덱스를 무력화한다. <code>created_at &gt;= '2024-01-01' AND created_at &lt; '2025-01-01'</code> 범위 조건이 맞다.", bad:true},
    {txt:"우변의 리터럴에 함수를 쓰는 것은 인덱스에 영향을 주지 않는다 — 문제는 <b>컬럼 쪽</b>을 감쌌을 때다.", bad:false},
    {txt:"이메일 비교는 대소문자를 구분해야 하므로 <code>LOWER</code> 를 쓰는 것 자체가 논리적 오류다.", bad:false},
    {txt:"조건이 두 개 이상이면 AND 로 묶는 것보다 서브쿼리로 나누는 편이 항상 빠르다.", bad:false}],
  ex:"실제 결함 2가지 — 둘 다 <b>sargable 하지 않은 조건</b>이다. 인덱스는 컬럼의 <b>원래 값</b>으로 정렬돼 있으므로, 컬럼에 함수를 씌우면 그 정렬을 쓸 수 없어 전 행을 계산하며 훑게 된다. 해법은 두 가지 — 값을 <b>저장할 때 정규화</b>하거나(소문자 컬럼), 표현식 인덱스를 만드는 것이다. 날짜는 <b>반열린 범위</b>가 표준 해법이다.\n디스트랙터: 우변 함수는 상수로 한 번 계산되므로 무해하다 — 이 구분이 핵심이다. 이메일의 대소문자 무시는 도메인상 흔한 요구라 논리 오류가 아니다. AND 를 서브쿼리로 나누는 것이 항상 빠르다는 규칙은 없다.",
  schema:"CREATE TABLE users(id INTEGER, email TEXT, created_at TEXT);\nCREATE INDEX idx_email ON users(email);\nINSERT INTO users VALUES (1,'kim@example.com','2024-05-01');",
  bad:"SELECT id FROM users WHERE LOWER(email)='kim@example.com';",
  fix:"SELECT id FROM users WHERE email='kim@example.com';",
  proof:"plan" },

{ k:"읽고 고쳐 쓰기 경쟁", cat:"review",
  q:"이 코드의 결함을 모두 고르세요",
  code:"-- 재고 차감 (애플리케이션 코드에서 두 문장을 차례로 실행)\nSELECT stock FROM items WHERE id = 7;\n-- 애플리케이션에서 stock - 1 계산\nUPDATE items SET stock = 4 WHERE id = 7;",
  items:[
    {txt:"읽은 뒤 쓰는 사이에 다른 트랜잭션이 끼어들면 <b>갱신 손실</b>이 난다. <code>UPDATE items SET stock = stock - 1 WHERE id = 7 AND stock &gt; 0</code> 처럼 한 문장으로 계산하면 원자적으로 처리된다.", bad:true},
    {txt:"재고가 0인지 확인하는 조건이 없어 <b>음수 재고</b>가 될 수 있다. UPDATE 조건에 <code>stock &gt; 0</code> 을 넣고 영향 행 수로 성공 여부를 판단해야 한다.", bad:true},
    {txt:"두 문장이 하나의 트랜잭션으로 묶여 있지 않아, 중간에 실패하면 일부만 반영된 상태가 남는다.", bad:true},
    {txt:"<code>SELECT</code> 로 먼저 읽는 것은 항상 불필요하므로, 어떤 경우에도 읽기 없이 UPDATE 만 해야 한다.", bad:false},
    {txt:"<code>WHERE id = 7</code> 은 기본 키 조건이므로 인덱스를 타지 못해 전체 스캔이 된다.", bad:false}],
  ex:"실제 결함 3가지 — 전부 <b>동시성</b>에서 온다. (1) read-modify-write 사이의 틈이 갱신 손실을 만든다. 값을 애플리케이션이 계산하지 말고 <b>DB 가 한 문장에서</b> 계산하게 하면 그 틈이 사라진다. (2) 하한 검사가 조건에 없으면 동시 요청이 재고를 음수로 만든다. (3) 트랜잭션 경계가 없다.\n디스트랙터: 화면에 현재 재고를 보여 주려면 읽기가 필요하다 — '항상 불필요' 는 과하다. 기본 키 조건은 <b>가장 잘 인덱스를 타는</b> 형태다.",
  schema:"CREATE TABLE items(id INTEGER PRIMARY KEY, stock INTEGER);\nINSERT INTO items VALUES (7,0);",
  bad:"UPDATE items SET stock = stock - 1 WHERE id=7; SELECT stock FROM items WHERE id=7;",
  fix:"UPDATE items SET stock = stock - 1 WHERE id=7 AND stock > 0; SELECT stock FROM items WHERE id=7;",
  proof:"rows" },

{ k:"동적 SQL 조립", cat:"review",
  q:"이 코드의 결함을 모두 고르세요",
  code:"-- 애플리케이션에서 문자열을 이어 붙여 만든 쿼리\nquery = \"SELECT * FROM users WHERE name = '\" + userInput + \"'\"\n-- 실행되는 SQL 예시\nSELECT * FROM users WHERE name = 'kim';",
  items:[
    {txt:"사용자 입력을 문자열로 이어 붙이면 <b>SQL 인젝션</b>이 성립한다. 입력에 <code>' OR '1'='1</code> 이 들어오면 조건이 항상 참이 된다 — 바인드 파라미터를 써야 한다.", bad:true},
    {txt:"작은따옴표를 이스케이프하는 것만으로는 부족하다 — 숫자 컨텍스트나 식별자(컬럼·테이블 이름) 자리에서는 따옴표 없이도 주입되고, 문자 인코딩에 따라 이스케이프가 우회되기도 한다.", bad:true},
    {txt:"바인드 파라미터는 쿼리 계획을 재사용할 수 있어 <b>성능에도 유리하다</b> — 매번 다른 문자열이면 계획 캐시가 무의미해진다.", bad:false},
    {txt:"<code>SELECT *</code> 를 쓰면 인젝션 위험이 커지므로 컬럼을 명시하는 것만으로 이 문제가 해결된다.", bad:false},
    {txt:"입력 길이를 제한하면 인젝션을 원천 차단할 수 있으므로 파라미터화는 선택 사항이다.", bad:false}],
  ex:"실제 결함 2가지. (1) 문자열 조립은 <b>데이터와 코드의 경계를 지운다</b> — 바인드 파라미터는 값을 코드로 해석하지 않겠다는 계약이라 구조적으로 안전하다. (2) 이스케이프 기반 방어는 컨텍스트마다 규칙이 달라 빠짐없이 적용하기 어렵다.\n디스트랙터: 계획 캐시 재사용은 <b>파라미터화의 장점</b>이지 결함이 아니다. 컬럼 명시는 좋은 습관이지만 인젝션과 무관하다. 길이 제한은 <code>' OR 1=1--</code> 처럼 짧은 공격을 못 막는다 — 완화책일 뿐이다.",
  schema:"CREATE TABLE users(id INTEGER, name TEXT);\nINSERT INTO users VALUES (1,'kim'),(2,'lee');",
  bad:"SELECT id FROM users WHERE name = '' OR '1'='1';",
  fix:"SELECT id FROM users WHERE name = ''' OR ''1''=''1';",
  proof:"rows" },

{ k:"대용량 삭제", cat:"review",
  q:"이 코드의 결함을 모두 고르세요",
  code:"DELETE FROM audit_log\nWHERE created_at < '2023-01-01';\n-- 대상 행: 약 8,000만 건",
  items:[
    {txt:"8천만 행을 한 트랜잭션에서 지우면 <b>롤백 세그먼트·WAL 이 폭증</b>하고 락이 오래 유지돼 다른 작업이 밀린다. 배치로 나눠(<code>LIMIT</code> 반복) 지워야 한다.", bad:true},
    {txt:"<code>created_at</code> 에 인덱스가 없으면 전체 스캔이 되고, 있어도 삭제 대상이 대부분이면 옵티마이저가 스캔을 고른다 — 실행 계획을 먼저 확인해야 한다.", bad:true},
    {txt:"오래된 데이터를 주기적으로 지우는 요구라면 <b>파티셔닝</b> 후 파티션 단위로 떼어내는 것이 훨씬 싸다 — 삭제가 아니라 메타데이터 조작이 된다.", bad:false},
    {txt:"<code>DELETE</code> 대신 <code>TRUNCATE</code> 를 쓰면 조건부 삭제도 훨씬 빠르게 처리된다.", bad:false},
    {txt:"삭제된 공간은 즉시 OS 에 반환되므로 디스크 사용량은 바로 줄어든다.", bad:false}],
  ex:"실제 결함 2가지. (1) <b>한 방에 지우는 것</b>이 문제다 — 트랜잭션이 커질수록 언두/WAL 이 커지고, 락 유지 시간이 길어져 서비스가 멈춘다. 몇만 건씩 끊어 지우고 사이에 커밋하는 것이 정석이다. (2) 실행 계획 확인 없이 대량 DML 을 돌리는 것 자체가 위험하다.\n디스트랙터: 파티셔닝은 <b>더 나은 해법</b>이지 결함이 아니다. <code>TRUNCATE</code> 는 <b>조건을 받지 못한다</b> — 테이블 전체를 비우는 명령이다. 삭제된 공간은 대개 테이블 내부에서 재사용될 뿐 즉시 반환되지 않는다(VACUUM·OPTIMIZE 필요).",
  schema:"CREATE TABLE audit_log(id INTEGER, created_at TEXT);\nINSERT INTO audit_log VALUES (1,'2022-01-01'),(2,'2024-01-01');",
  bad:"DELETE FROM audit_log WHERE created_at < '2023-01-01'; SELECT COUNT(*) FROM audit_log;",
  fix:"DELETE FROM audit_log WHERE id IN (SELECT id FROM audit_log WHERE created_at < '2023-01-01' LIMIT 1); SELECT COUNT(*) FROM audit_log;",
  proof:null },

{ k:"UNION 과 정렬", cat:"review",
  q:"이 코드의 결함을 모두 고르세요",
  code:"SELECT user_id, day FROM web_log\nORDER BY day DESC\nUNION\nSELECT user_id, day FROM app_log\nORDER BY day DESC;",
  items:[
    {txt:"<code>UNION</code> 은 <b>중복을 제거</b>한다 — 웹과 앱에서 같은 날 접속한 사용자가 한 건으로 합쳐져 접속 건수가 줄어든다. 전부 남기려면 <code>UNION ALL</code> 이다.", bad:true},
    {txt:"<code>UNION</code> 의 각 갈래에 <code>ORDER BY</code> 를 붙일 수 없다 — 정렬은 전체 결과에 대해 <b>마지막에 한 번</b>만 쓸 수 있다.", bad:true},
    {txt:"<code>UNION</code> 은 중복 제거를 위해 정렬이나 해싱을 하므로 <code>UNION ALL</code> 보다 비싸다 — 중복 제거가 필요 없으면 성능 면에서도 <code>UNION ALL</code> 이 낫다.", bad:false},
    {txt:"두 갈래의 컬럼 개수와 타입이 같아야 하는데 여기서는 어긋나 있어 실행되지 않는다.", bad:false},
    {txt:"<code>UNION</code> 대신 <code>JOIN</code> 을 쓰면 같은 결과를 더 빠르게 얻을 수 있다.", bad:false}],
  ex:"실제 결함 2가지. (1) <b>UNION 은 중복을 지운다</b> — 로그 합치기처럼 건수가 의미인 경우 조용히 수를 줄인다. 기본 선택은 <code>UNION ALL</code> 이고, <code>UNION</code> 은 중복을 지워야 할 이유가 있을 때만 쓴다. (2) 갈래별 <code>ORDER BY</code> 는 표준상 허용되지 않는다 — 합집합에는 순서 개념이 없으므로 정렬은 전체에 한 번이다.\n디스트랙터: 성능 설명은 <b>맞는 이야기</b>다. 두 갈래의 컬럼은 <code>user_id, day</code> 로 동일하다. <code>JOIN</code> 은 행을 옆으로 붙이는 연산이라 세로로 이어 붙이는 <code>UNION</code> 을 대체할 수 없다.",
  schema:"CREATE TABLE web_log(user_id INTEGER, day TEXT);\nINSERT INTO web_log VALUES (1,'01-01');\nCREATE TABLE app_log(user_id INTEGER, day TEXT);\nINSERT INTO app_log VALUES (1,'01-01');",
  bad:"SELECT user_id, day FROM web_log UNION SELECT user_id, day FROM app_log;",
  fix:"SELECT user_id, day FROM web_log UNION ALL SELECT user_id, day FROM app_log;",
  proof:"rows" },

{ k:"스키마 설계 결함", cat:"review",
  q:"이 코드의 결함을 모두 고르세요",
  code:"CREATE TABLE orders (\n  id        TEXT,\n  user_id   TEXT,\n  amount    REAL,\n  status    TEXT,\n  created   TEXT\n);",
  items:[
    {txt:"기본 키가 없다 — 중복 행을 막을 수 없고, 복제·변경 추적·조인 최적화가 모두 어려워진다.", bad:true},
    {txt:"금액을 <code>REAL</code>(부동소수점)로 저장하면 <b>정확한 합계가 나오지 않는다</b>. 정수 최소 단위(원·센트)나 DECIMAL 이어야 한다.", bad:true},
    {txt:"<code>user_id</code> 에 외래 키 제약이 없어 존재하지 않는 사용자를 참조하는 행이 들어올 수 있다.", bad:true},
    {txt:"<code>status</code> 를 TEXT 로 둔 것은 결함이다 — 상태 값은 반드시 정수 코드로 저장해야 한다.", bad:false},
    {txt:"<code>created</code> 컬럼 이름이 예약어와 충돌해 대부분의 DBMS 에서 테이블 생성이 실패한다.", bad:false}],
  ex:"실제 결함 3가지. (1) <b>기본 키 부재</b> — 유일성을 보장할 방법이 사라진다. (2) <b>돈을 REAL 로</b> — 2진 부동소수점은 0.1 을 정확히 담지 못해 합계가 어긋난다. 회계에서는 1원 차이도 사고다. (3) <b>외래 키 부재</b> — 참조 무결성을 애플리케이션에만 맡기면 결국 고아 행이 쌓인다.\n디스트랙터: 상태를 문자열로 두는 것은 <b>가독성 면에서 오히려 권장</b>되기도 한다(제약이나 enum 으로 값을 묶으면 된다). <code>created</code> 는 예약어가 아니다 — <code>CREATE</code> 와 다른 단어다.",
  schema:"CREATE TABLE orders(id TEXT, user_id TEXT, amount REAL, status TEXT, created TEXT);\nINSERT INTO orders VALUES ('o1','u1',0.1,'new','2024-01-01'),('o2','u1',0.2,'new','2024-01-01');",
  bad:"SELECT SUM(amount)=0.3 AS exact FROM orders;",
  fix:"SELECT ROUND(SUM(amount),10)=0.3 AS exact FROM orders;",
  proof:"rows" },

{ k:"상관 서브쿼리 반복 평가", cat:"review",
  q:"이 코드의 결함을 모두 고르세요",
  code:"SELECT u.id, u.name,\n  (SELECT COUNT(*) FROM orders o WHERE o.user_id = u.id) AS order_count,\n  (SELECT MAX(created_at) FROM orders o WHERE o.user_id = u.id) AS last_order\nFROM users u;",
  items:[
    {txt:"같은 조건의 상관 서브쿼리를 <b>두 번</b> 돌린다 — 한 번의 <code>LEFT JOIN + GROUP BY</code> 로 두 값을 함께 구하면 <code>orders</code> 를 한 번만 읽는다.", bad:true},
    {txt:"<code>orders.user_id</code> 에 인덱스가 없으면 사용자 수 × 2 번의 전체 스캔이 되어 사용자가 늘수록 급격히 느려진다.", bad:true},
    {txt:"주문이 없는 사용자의 <code>order_count</code> 는 0, <code>last_order</code> 는 NULL 이 되어 의도대로 동작한다.", bad:false},
    {txt:"상관 서브쿼리는 표준 SQL 이 아니므로 <code>JOIN</code> 으로 반드시 바꿔야 한다.", bad:false},
    {txt:"<code>SELECT</code> 절에는 서브쿼리를 쓸 수 없어 구문 오류가 발생한다.", bad:false}],
  ex:"실제 결함 2가지. (1) <b>같은 테이블을 두 번 훑는다</b> — 하나의 조인·집계로 합치면 스캔이 절반이 된다. (2) 조인 키 인덱스가 없으면 이 구조는 N+1 쿼리와 같은 비용 곡선을 그린다.\n디스트랙터: 주문 없는 사용자의 결과(0 과 NULL)는 <b>정확한 동작</b>이다 — 오히려 LEFT JOIN 으로 바꿀 때 <code>COUNT(o.id)</code> 를 써야 같은 결과가 나온다는 점이 주의할 부분이다. 상관 서브쿼리는 표준이며, SELECT 절의 스칼라 서브쿼리도 표준이다.",
  schema:"CREATE TABLE users(id INTEGER, name TEXT);\nINSERT INTO users VALUES (1,'a'),(2,'b');\nCREATE TABLE orders(user_id INTEGER, created_at TEXT);\nINSERT INTO orders VALUES (1,'2024-01-01');",
  bad:"SELECT u.id, (SELECT COUNT(*) FROM orders o WHERE o.user_id=u.id) AS c FROM users u ORDER BY u.id;",
  fix:"SELECT u.id, COUNT(o.user_id) AS c FROM users u LEFT JOIN orders o ON o.user_id=u.id GROUP BY u.id ORDER BY u.id;",
  proof:null },

{ k:"트랜잭션 격리와 집계", cat:"review",
  q:"이 코드의 결함을 모두 고르세요",
  code:"BEGIN;\nSELECT SUM(balance) FROM accounts WHERE branch = 'seoul';\n-- (다른 작업 수행)\nSELECT SUM(balance) FROM accounts WHERE branch = 'seoul';\nCOMMIT;",
  items:[
    {txt:"READ COMMITTED 격리에서는 두 <code>SELECT</code> 사이에 커밋된 변경이 보여 <b>같은 트랜잭션 안에서 다른 합계</b>가 나온다(반복 불가능한 읽기).", bad:true},
    {txt:"다른 트랜잭션이 새 계좌를 <b>추가</b>하면 두 번째 집계에만 잡히는 팬텀 읽기가 생긴다 — 범위 조건 집계에서 특히 문제가 된다.", bad:true},
    {txt:"두 번의 집계 결과가 같아야 한다면 <code>REPEATABLE READ</code> 이상으로 올리거나 스냅숏을 한 번만 읽어 재사용해야 한다.", bad:false},
    {txt:"<code>BEGIN</code> 과 <code>COMMIT</code> 사이에 <code>SELECT</code> 만 있으면 트랜잭션을 열 필요가 없으므로 이 코드는 항상 불필요하다.", bad:false},
    {txt:"집계 함수는 트랜잭션 격리 수준의 영향을 받지 않는다.", bad:false}],
  ex:"실제 결함 2가지 — 둘 다 <b>격리 수준을 정하지 않은 채</b> 반복 읽기를 전제한 데서 온다. (1) 반복 불가능한 읽기: 기존 행의 값이 바뀐다. (2) 팬텀: 조건에 맞는 <b>행 자체가 늘어난다</b>. 보고서처럼 한 시점의 일관된 그림이 필요하면 격리 수준을 올려야 한다.\n디스트랙터: 격리 수준을 올리라는 지적은 <b>해결책</b>이다. 여러 읽기의 일관성이 필요하면 읽기 전용 트랜잭션도 의미가 있으므로 '항상 불필요' 는 틀렸다. 집계도 읽기이므로 당연히 격리의 영향을 받는다.",
  schema:"CREATE TABLE accounts(branch TEXT, balance INTEGER);\nINSERT INTO accounts VALUES ('seoul',100);",
  bad:"SELECT SUM(balance) FROM accounts WHERE branch='seoul';",
  fix:"SELECT SUM(balance) FROM accounts WHERE branch='seoul';",
  proof:null },

{ k:"CASE 와 NULL 처리", cat:"review",
  q:"이 코드의 결함을 모두 고르세요",
  code:"SELECT name,\n  CASE\n    WHEN grade = NULL THEN '미채점'\n    WHEN grade >= 90 THEN 'A'\n    WHEN grade >= 60 THEN 'B'\n  END AS result\nFROM exams;",
  items:[
    {txt:"<code>grade = NULL</code> 은 절대 참이 되지 않는다 — NULL 비교는 <code>IS NULL</code> 로 해야 한다. 지금은 미채점 분기가 죽어 있다.", bad:true},
    {txt:"<code>ELSE</code> 가 없어 60 미만이면 <b>조용히 NULL</b> 이 된다 — 어디에도 걸리지 않은 행이 빈 값으로 보인다.", bad:true},
    {txt:"조건을 좁은 것부터(90 → 60) 배치한 순서 자체는 올바르다 — CASE 는 위에서부터 처음 참인 가지에서 멈추기 때문이다.", bad:false},
    {txt:"<code>CASE</code> 안에서는 비교 연산자를 쓸 수 없고 <code>WHEN 값 THEN</code> 형태만 허용된다.", bad:false},
    {txt:"<code>grade</code> 가 NULL 인 행은 <code>WHERE</code> 절 없이도 결과에서 자동 제외된다.", bad:false}],
  ex:"실제 결함 2가지. (1) <b><code>= NULL</code> 은 UNKNOWN</b> — 참이 될 수 없으므로 그 분기는 죽은 코드다. <code>IS NULL</code> 이어야 한다. (2) <b><code>ELSE</code> 누락</b> — 어느 가지에도 걸리지 않으면 NULL 이 되어, '점수는 있는데 등급이 빈' 행이 생긴다.\n디스트랙터: 조건 순서는 <b>올바르다</b> — 넓은 조건을 위에 두면 아래가 죽는데, 여기서는 좁은 것부터 왔다. <code>CASE</code> 에는 검색형(<code>WHEN 조건</code>)과 단순형(<code>WHEN 값</code>) 두 가지가 있고 여기서는 검색형이다. NULL 행이 자동 제외되지는 않는다 — 결과 컬럼만 NULL 이 될 뿐이다.",
  schema:"CREATE TABLE exams(name TEXT, grade INTEGER);\nINSERT INTO exams VALUES ('a',NULL),('b',50);",
  bad:"SELECT name, CASE WHEN grade = NULL THEN '미채점' WHEN grade>=60 THEN 'B' END AS r FROM exams ORDER BY name;",
  fix:"SELECT name, CASE WHEN grade IS NULL THEN '미채점' WHEN grade>=60 THEN 'B' ELSE 'F' END AS r FROM exams ORDER BY name;",
  proof:"rows" },

{ k:"인덱스 과다", cat:"review",
  q:"이 코드의 결함을 모두 고르세요",
  code:"CREATE INDEX i1 ON logs (user_id);\nCREATE INDEX i2 ON logs (user_id, created_at);\nCREATE INDEX i3 ON logs (created_at);\nCREATE INDEX i4 ON logs (user_id, created_at, level);\n-- logs 는 초당 5,000행이 INSERT 되는 테이블",
  items:[
    {txt:"<code>i1</code> 은 <code>i2</code> 의 <b>좌측 접두사</b>이므로 중복이다 — <code>i2</code> 가 <code>user_id</code> 단독 조건도 처리한다. 같은 이유로 <code>i2</code> 도 <code>i4</code> 에 흡수된다.", bad:true},
    {txt:"쓰기가 초당 5,000행인데 인덱스가 4개면 <b>INSERT 마다 5번의 쓰기</b>가 발생한다 — 쓰기 위주 테이블에서 인덱스는 직접적인 비용이다.", bad:true},
    {txt:"<code>i3</code> 은 <code>created_at</code> 이 첫 컬럼이므로 다른 인덱스가 대신할 수 없다 — 시간 범위만으로 조회하는 쿼리가 있다면 필요하다.", bad:false},
    {txt:"인덱스는 조회 성능만 좌우하므로 개수가 많아도 쓰기 성능에는 영향이 없다.", bad:false},
    {txt:"복합 인덱스가 있으면 단일 컬럼 인덱스는 어떤 경우에도 만들면 안 된다.", bad:false}],
  ex:"실제 결함 2가지. (1) <b>접두사 중복</b> — <code>(a)</code>, <code>(a,b)</code>, <code>(a,b,c)</code> 를 모두 만들면 앞의 둘은 대개 낭비다. (2) 쓰기 비용 — 인덱스마다 갱신이 붙으므로 <b>쓰기가 많은 테이블일수록</b> 인덱스는 비싸다.\n디스트랙터: <code>i3</code> 은 첫 컬럼이 달라 <b>대체 불가</b>다 — 이 구분이 이 문항의 핵심이다. 인덱스가 쓰기에 영향이 없다는 것은 명백히 틀렸다. 단일 컬럼 인덱스가 항상 금지인 것도 아니다 — 첫 컬럼이 다르면 필요하다.",
  schema:"CREATE TABLE logs(user_id INTEGER, created_at TEXT, level TEXT);\nCREATE INDEX i2 ON logs(user_id, created_at);\nINSERT INTO logs VALUES (1,'2024-01-01','info');",
  bad:"SELECT user_id FROM logs WHERE user_id=1;",
  fix:"SELECT user_id FROM logs INDEXED BY i2 WHERE user_id=1;",
  proof:null },

{ k:"뷰와 필터 밀어넣기", cat:"review",
  q:"이 코드의 결함을 모두 고르세요",
  code:"CREATE VIEW v_orders AS\nSELECT o.*, u.name\nFROM orders o\nJOIN users u ON u.id = o.user_id\nORDER BY o.created_at DESC;\n\nSELECT * FROM v_orders WHERE user_id = 42;",
  items:[
    {txt:"뷰 정의 안의 <code>ORDER BY</code> 는 <b>의미가 없거나 불필요한 정렬을 강제</b>한다 — 바깥 쿼리가 다시 정렬하거나 순서를 보장하지 않으므로, 정렬은 뷰를 쓰는 쪽에서 지정해야 한다.", bad:true},
    {txt:"<code>SELECT o.*</code> 로 컬럼을 열어 두면 <code>orders</code> 에 컬럼이 추가될 때 뷰의 출력이 조용히 바뀌어 뷰를 쓰는 코드가 깨질 수 있다.", bad:true},
    {txt:"바깥의 <code>WHERE user_id = 42</code> 는 옵티마이저가 뷰 안으로 밀어넣을 수 있으므로 그 자체는 문제가 아니다.", bad:false},
    {txt:"뷰는 결과를 저장하므로 원본 테이블이 바뀌어도 갱신되지 않는다.", bad:false},
    {txt:"<code>JOIN</code> 이 들어간 뷰는 어떤 DBMS 에서도 인덱스를 사용할 수 없다.", bad:false}],
  ex:"실제 결함 2가지. (1) <b>뷰 안의 ORDER BY</b> — 집합에는 순서가 없으므로 바깥에서 다시 쓰면 낭비이고, 안 쓰면 순서가 보장되지도 않는다. 일부 DBMS 는 아예 무시하거나 오류를 낸다. (2) <code>o.*</code> 는 스키마 변경이 뷰 계약을 조용히 바꾸게 만든다 — <b>뷰는 인터페이스</b>이므로 컬럼을 명시하는 편이 안전하다.\n디스트랙터: 조건 밀어넣기(predicate pushdown)는 <b>옵티마이저의 정상 동작</b>이다. 일반 뷰는 결과를 저장하지 않는다(저장하는 것은 구체화 뷰). 뷰라고 인덱스를 못 쓰는 것도 아니다 — 실행 시점에 원본 테이블의 인덱스를 그대로 쓴다.",
  schema:"CREATE TABLE users(id INTEGER, name TEXT);\nINSERT INTO users VALUES (42,'kim');\nCREATE TABLE orders(id INTEGER, user_id INTEGER, created_at TEXT);\nINSERT INTO orders VALUES (1,42,'2024-01-01');",
  bad:"SELECT COUNT(*) FROM orders o JOIN users u ON u.id=o.user_id WHERE o.user_id=42;",
  fix:"SELECT COUNT(*) FROM orders o JOIN users u ON u.id=o.user_id WHERE o.user_id=42;",
  proof:null },
];
