/* code 트랙 코드 리뷰 — 매일 쓰는 기초 코드에 한 줄 지적을 단다. */
module.exports = [
{
  t: "review", k: "반복문 안의 타이머", cat: "review", d: 2, track: "code",
  q: "이 코드의 결함을 모두 고르세요",
  code: "function schedule(tasks) {\n  for (var i = 0; i < tasks.length; i++) {\n    setTimeout(function () {\n      console.log(i + \": \" + tasks[i].name);\n    }, 100);\n  }\n}",
  items: [
    { txt: "<code>var</code> 는 함수 스코프라 반복문이 끝난 뒤의 <code>i</code> 하나만 남는다. 타이머가 실행될 때는 이미 <code>i === tasks.length</code> 이므로 <code>tasks[i]</code> 가 <code>undefined</code> 가 되어 예외로 끝난다 — <code>let</code> 으로 바꾸면 반복마다 새 바인딩이 생겨 해결된다.", bad: true },
    { txt: "<code>setTimeout</code> 은 밀리초 단위 지연을 보장하지 않고 <b>최소 대기 시간</b>만 약속하므로, 정확한 시각에 실행해야 한다면 <code>Date.now()</code> 로 보정하는 스케줄러가 따로 필요하다. 다만 이 코드가 약속한 것은 '대략 100ms 뒤' 뿐이다.", bad: false },
    { txt: "모든 타이머를 같은 100ms 로 등록했으므로 한꺼번에 깨어나 실행 순서가 뒤섞이고, 작업이 많으면 그 순간 이벤트 루프가 한 번에 막힌다 — 등록 순서대로 흘리려면 지연을 <code>i * 100</code> 으로 늘려 잡아야 한다.", bad: false },
    { txt: "콘솔 출력을 함수 안에 직접 두면 자동 검사에서 무엇이 찍혔는지 붙잡기 어렵다 — 출력 대신 문자열을 돌려주고 호출자가 찍게 하면 같은 로직을 그대로 검증할 수 있다. 다만 이것은 설계 취향에 가깝지 이 코드의 동작 결함은 아니다.", bad: false },
    { txt: "화살표 함수 대신 <code>function</code> 을 썼기 때문에 콜백 안의 <code>this</code> 가 바깥과 달라지고, 그 때문에 <code>tasks</code> 를 참조하지 못해 <code>undefined</code> 를 읽게 되므로 화살표 함수로 바꿔야 한다.", bad: false },
  ],
  ex: "결함 1가지. <b><code>var</code> 는 반복마다 새 변수를 만들지 않는다</b> — 콜백은 전부 같은 <code>i</code> 를 보고, 타이머가 도는 시점에 그 값은 이미 배열 길이와 같다. <code>let</code> 으로 바꾸면 반복마다 별도의 바인딩이 생겨 각 콜백이 자기 값을 기억한다.\n디스트랙터: <code>setTimeout</code> 의 지연이 정확하지 않은 것은 사실이지만 이 코드가 약속한 범위 밖이다. 실행 순서는 같은 지연이면 등록 순서를 따르므로 문제되지 않는다. 콘솔 출력은 설계 취향이고, <code>this</code> 는 여기서 쓰이지 않으므로 화살표 함수 여부와 무관하다.",
},
{
  t: "review", k: "forEach 안에서 await", cat: "review", d: 2, track: "code",
  q: "이 코드의 결함을 모두 고르세요",
  code: "async function saveAll(rows) {\n  rows.forEach(async (r) => {\n    await save(r);\n  });\n  console.log(\"완료\");\n  return true;\n}",
  items: [
    { txt: "<code>rows</code> 가 비어 있으면 <code>forEach</code> 가 예외를 던지므로 <code>if (!rows.length) return true;</code> 를 앞에 두어 빈 입력을 먼저 걸러야 안전하다.", bad: false },
    { txt: "<code>forEach</code> 는 콜백이 돌려준 프라미스를 <b>기다리지 않는다</b>. 저장이 아직 진행 중인데 '완료' 가 찍히고 <code>true</code> 가 반환되므로, 호출자는 끝난 줄 알고 다음 단계로 넘어간다 — <code>for...of</code> 안에서 <code>await</code> 하거나 <code>Promise.all</code> 로 모아야 한다.", bad: true },
    { txt: "<code>Promise.all</code> 로 바꾸면 모든 저장이 한꺼번에 시작되어 상대 시스템의 커넥션 풀이나 속도 제한을 그대로 밀어붙이게 된다 — 동시 실행 수에 상한을 두는 편이 안전한 경우가 많지만, 그것은 다음 단계의 고민이지 지금 코드의 결함은 아니다.", bad: false },
    { txt: "<code>save</code> 가 실패해도 그 거절을 아무도 받지 않으므로 <b>잡히지 않은 거절</b>이 된다. 런타임에 따라 프로세스가 종료되고, 적어도 실패가 호출자에게 전달되지 않아 조용히 데이터가 빠진다.", bad: true },
    { txt: "함수에 <code>async</code> 를 붙였으므로 반환값이 자동으로 프라미스로 감싸지는데, 그 사실이 코드에 드러나지 않아 읽는 사람이 헷갈린다 — <code>true</code> 대신 <code>Promise.resolve(true)</code> 를 명시적으로 돌려주도록 바꿔야 한다.", bad: false },
  ],
  ex: "결함 2가지. (1) <b><code>forEach</code> 는 비동기를 모른다</b> — 콜백이 프라미스를 돌려줘도 그냥 버리므로 함수는 저장이 끝나기 전에 반환한다. (2) 그렇게 버려진 프라미스가 실패하면 <b>아무도 받지 않는 거절</b>이 되어 오류가 사라진다. 순서가 중요하면 <code>for...of</code> + <code>await</code>, 아니면 <code>await Promise.all(rows.map(save))</code> 다.\n디스트랙터: 빈 배열에서 <code>forEach</code> 는 아무 일도 하지 않고 예외도 없다. 동시 실행 상한은 다음 단계의 고민이다. <code>async</code> 함수의 반환값은 자동으로 프라미스가 되므로 감쌀 필요가 없다.",
},
{
  t: "review", k: "느슨한 비교로 값을 검사한다", cat: "review", d: 2, track: "code",
  q: "이 코드의 결함을 모두 고르세요",
  code: "function applyDiscount(order) {\n  if (!order.coupon) return order.total;\n  if (order.coupon.rate == \"0\") return order.total;\n  return order.total * (1 - order.coupon.rate);\n}",
  items: [
    { txt: "<code>!order.coupon</code> 는 쿠폰 객체의 유무만 보므로 적절하다 — 다만 쿠폰이 있는데 <code>rate</code> 가 없는 경우를 걸러 주지는 못하니, 값 자체를 검사하는 편이 안전하다.", bad: false },
    { txt: "부동소수 곱셈이므로 결과에 <code>0.1 * 3</code> 이 <code>0.30000000000000004</code> 가 되는 식의 오차가 남을 수 있다 — 돈을 다룬다면 최소 단위 정수로 계산하고 표시할 때만 나누는 편이 낫지만, 이 코드가 약속한 계산 자체는 맞다.", bad: false },
    { txt: "<code>rate == \"0\"</code> 은 느슨한 비교라 숫자 <code>0</code>, 문자열 <code>\"0\"</code>, 빈 배열까지 참이 된다. 의도가 '할인율 0' 이라면 <code>Number(rate) === 0</code> 처럼 <b>타입을 정한 뒤 비교</b>해야 하고, 그러지 않으면 엉뚱한 값에서 조기 반환한다.", bad: true },
    { txt: "할인율이 1 을 넘으면 총액이 음수가 되어 결제 단계로 이상한 값이 흘러가므로 <code>Math.max(0, ...)</code> 로 감싸야 한다 — 다만 쿠폰 값의 범위를 지키는 일은 이 함수가 아니라 쿠폰을 만들고 저장하는 쪽의 책임이다.", bad: false },
    { txt: "<code>rate</code> 가 문자열로 들어오면 <code>1 - \"0.1\"</code> 은 숫자 변환이 되지만 <code>1 - \"10%\"</code> 는 <code>NaN</code> 이 되어 총액이 통째로 <code>NaN</code> 이 된다. 계산 전에 숫자로 파싱하고 범위를 검사해야 한다.", bad: true },
  ],
  ex: "결함 2가지. (1) <b>느슨한 비교</b>는 타입을 넘나들며 참이 되어 의도하지 않은 값에서 분기한다 — 비교 전에 타입을 정하는 것이 규칙이다. (2) <b>문자열 계산</b>이 <code>NaN</code> 으로 번진다 — 산술 전에 파싱하고, 파싱에 실패하면 그 자리에서 실패해야 조용한 오염을 막는다.\n디스트랙터: 쿠폰 객체 유무 검사 자체는 문제가 없다. 부동소수 오차와 상한 검사는 옳은 지적이지만 이 함수의 계약 밖이거나 다른 계층의 책임이다.",
},
{
  t: "review", k: "순회하면서 지운다", cat: "review", d: 2, track: "code",
  q: "이 코드의 결함을 모두 고르세요",
  code: "function removeDone(tasks) {\n  for (let i = 0; i < tasks.length; i++) {\n    if (tasks[i].done) tasks.splice(i, 1);\n  }\n  return tasks;\n}",
  items: [
    { txt: "지운 자리로 뒤 원소가 <b>한 칸 당겨지는데 <code>i</code> 는 그대로 증가</b>하므로 바로 다음 원소를 건너뛴다. 완료된 항목이 연달아 있으면 하나 건너 하나만 지워져, 오류 없이 결과만 틀린다.", bad: true },
    { txt: "<code>tasks.length</code> 를 매 반복 읽으므로 성능이 나쁘다 — 길이를 변수에 담아 두어야 하지만, 배열을 줄이는 이 코드에서는 오히려 담아 두면 범위를 벗어난다.", bad: false },
    { txt: "<code>splice</code> 는 지운 원소를 새 배열로 돌려주는데 그 배열을 아무도 쓰지 않으므로, 반복마다 쓸모없는 배열이 하나씩 만들어져 가비지 컬렉터에 부담을 준다 — 사용하지 않는 반환값은 즉시 회수되므로 실제로는 문제가 되지 않는다.", bad: false },
    { txt: "인자로 받은 배열을 제자리에서 바꾸면서 그것을 다시 돌려주므로, 호출자는 새 배열을 받은 줄 알고 원본도 함께 바뀐 사실을 놓치기 쉽다 — <code>filter</code> 로 새 배열을 만들어 돌려주는 편이 예상을 지킨다.", bad: true },
    { txt: "완료 여부를 <code>tasks[i].done</code> 으로 직접 읽으므로 <code>done</code> 이 없는 항목에서는 <code>undefined</code> 가 되어 거짓으로 취급된다 — 이 함수의 계약상 자연스러운 동작이다.", bad: false },
  ],
  ex: "결함 2가지. (1) <b>순회 중 삭제</b>는 인덱스를 어긋나게 한다 — 뒤에서부터 훑거나 <code>filter</code> 로 새 배열을 만들어야 한다. (2) <b>제자리 변경과 반환을 함께</b> 하면 호출자가 원본이 그대로일 것이라 착각한다.\n디스트랙터: <code>tasks.length</code> 를 매번 읽는 것은 이 코드에서 <b>필요한</b> 동작이다 — 길이가 줄기 때문이다. <code>splice</code> 의 반환값은 쓰지 않으면 그대로 회수된다. <code>done</code> 이 없는 항목을 미완료로 보는 것은 합리적인 기본값이다.",
},
{
  t: "review", k: "오류를 삼키는 try/catch", cat: "review", d: 2, track: "code",
  q: "이 코드의 결함을 모두 고르세요",
  code: "function loadConfig(text) {\n  try {\n    return JSON.parse(text);\n  } catch (e) {\n    return {};\n  }\n}",
  items: [
    { txt: "<code>JSON.parse</code> 는 문법 오류에만 예외를 던지므로 값의 타입이 어긋나도 그대로 통과한다 — 파싱 뒤에 스키마 검증이 따로 필요하다는 지적은 옳지만, 그것은 이 함수가 약속한 범위 밖의 일이다.", bad: false },
    { txt: "파싱에 실패했다는 사실이 <b>어디에도 남지 않는다</b>. 호출자는 빈 설정을 정상으로 받아 기본값으로 돌아가고, 운영에서는 '설정을 바꿨는데 반영이 안 된다' 는 형태로 한참 뒤에 드러난다 — 최소한 로그를 남기고, 가능하면 실패를 돌려줘야 한다.", bad: true },
    { txt: "<code>catch (e)</code> 에서 변수를 한 번도 쓰지 않으므로 최신 문법인 <code>catch {}</code> 로 줄여야 하며, 그렇게 하지 않으면 사용하지 않는 변수 경고가 린트에서 오류로 승격되어 빌드를 막는다.", bad: false },
    { txt: "매 호출마다 새 빈 객체를 만들어 돌려주므로 상수 하나로 빼서 재사용해야 메모리를 아낄 수 있다 — 다만 그렇게 하면 호출자가 그 객체에 값을 하나만 넣어도 이후 모든 호출이 그것을 보게 되는 새 문제가 생긴다.", bad: false },
    { txt: "<code>{}</code> 를 돌려주면 '설정이 비어 있음' 과 '설정을 읽지 못함' 이 <b>구별되지 않는다</b>. 호출자가 두 경우를 다르게 다뤄야 한다면 <code>null</code> 이나 결과 객체로 나눠 돌려주는 편이 낫다.", bad: true },
  ],
  ex: "결함 2가지. (1) <b>실패를 조용히 없앤다</b> — 예외를 잡는 것 자체는 좋지만, 무엇이 왜 실패했는지 남기지 않으면 디버깅할 단서가 사라진다. (2) <b>성공과 실패가 같은 모양</b>으로 돌아온다 — 빈 설정과 읽기 실패를 호출자가 구별할 수 없다.\n디스트랙터: 스키마 검증은 다음 단계의 일이다. <code>catch {}</code> 는 문법 편의일 뿐 경고가 빌드를 막지는 않는다. 빈 객체를 상수로 빼는 것은 오히려 공유 변경 위험을 만든다.",
},
{
  t: "review", k: "월은 0부터 센다", cat: "review", d: 2, track: "code",
  q: "이 코드의 결함을 모두 고르세요",
  code: "function label(dateStr) {\n  const d = new Date(dateStr);\n  return d.getFullYear() + \"-\" + (d.getMonth()) + \"-\" + d.getDate();\n}",
  items: [
    { txt: "<code>getMonth()</code> 는 0 부터 세므로 8월이 <code>7</code> 로 찍힌다. <code>+ 1</code> 을 더하고 두 자리로 채워야 하며, 이 실수는 <b>테스트가 12월에만 통과</b>하는 식으로 늦게 발견되기 쉽다.", bad: true },
    { txt: "<code>new Date(dateStr)</code> 는 파싱에 실패하면 예외를 던지므로 <code>try/catch</code> 로 감싸야 하고, 그러지 않으면 잘못된 입력에서 함수가 중단된다.", bad: false },
    { txt: "<code>getMonth()</code>·<code>getDate()</code> 는 <b>실행 환경의 시간대</b>로 값을 돌려준다. 입력이 <code>\"2026-08-24\"</code> 처럼 날짜만 있으면 UTC 자정으로 해석되므로, UTC 서쪽 지역에서는 하루 전 날짜가 찍힌다.", bad: true },
    { txt: "월과 일을 두 자리로 채우지 않아 <code>2026-8-4</code> 처럼 정렬이 어긋나는 문자열이 나온다 — 형식을 맞추려면 <code>padStart(2, \"0\")</code> 이 필요하지만, 이 함수가 어떤 형식을 약속했는지는 이름만으로는 알 수 없다.", bad: false },
    { txt: "표준 형식이 필요하면 <code>toISOString().slice(0, 10)</code> 이 더 간단하다 — 다만 그것도 UTC 기준이므로 시간대 문제가 그대로 남는다.", bad: false },
  ],
  ex: "결함 2가지. (1) <b>월이 0부터</b>라 그대로 쓰면 한 달씩 어긋난다. (2) <b>지역 시간대로 읽는다</b> — 날짜만 있는 문자열은 UTC 자정으로 해석되므로, 지역 게터로 꺼내면 지역에 따라 하루가 밀린다. 달력상의 날짜를 다룬다면 문자열로 다루거나 시간대를 명시해야 한다.\n디스트랙터: <code>new Date</code> 는 파싱에 실패해도 예외 대신 <code>Invalid Date</code> 를 만든다. 자리 채움과 대안 API 는 형식을 어떻게 정하느냐의 문제다.",
},
{
  t: "review", k: "기본값으로 공유되는 객체", cat: "review", d: 3, track: "code",
  q: "이 코드의 결함을 모두 고르세요",
  code: "const DEFAULTS = { tags: [], retries: 3 };\n\nfunction makeJob(name, opts = DEFAULTS) {\n  opts.tags.push(name);\n  return { name, ...opts };\n}",
  items: [
    { txt: "<code>opts</code> 를 받아 그 자리에서 수정하는 것은 인자를 변경하는 것이라 예상 밖의 부작용이지만, 호출자가 매번 새 객체를 넘긴다면 실제 피해는 없다 — 그래도 규칙으로 금지해 두는 편이 안전하다.", bad: false },
    { txt: "기본값으로 준 <code>DEFAULTS</code> 는 <b>모듈에 하나뿐인 객체</b>다. 인자를 생략한 호출이 그 안의 <code>tags</code> 에 계속 밀어 넣으므로, 두 번째 작업부터 앞선 작업의 이름을 함께 갖게 된다.", bad: true },
    { txt: "자바스크립트의 기본 인자는 함수가 정의될 때 한 번 평가되므로, <code>opts = { tags: [] }</code> 로 바꿔도 같은 객체가 공유된다.", bad: false },
    { txt: "전개 연산자 <code>...opts</code> 는 <b>얕은 복사</b>라 <code>tags</code> 배열은 여전히 같은 참조다. 반환된 객체를 통해 배열을 수정하면 원본까지 바뀌므로, 깊은 복사나 새 배열 생성이 필요하다.", bad: true },
    { txt: "<code>retries</code> 를 3 으로 둔 것은 호출자가 값을 주지 않았을 때의 합리적인 기본값이다 — 숫자는 값 타입이라 전개로 복사되는 순간 완전히 독립하므로, 배열과 달리 공유로 인한 사고가 생기지 않는다.", bad: false },
  ],
  ex: "결함 2가지. (1) <b>공유 객체를 기본값으로</b> 썼다 — 그 안의 배열이 호출 사이에 누적된다. (2) <b>전개는 얕은 복사</b>라 중첩된 배열·객체는 여전히 공유된다. 둘 다 '기본값은 매번 새로 만들고, 복사는 깊이를 의식한다' 로 해결된다.\n디스트랙터: 인자를 수정하는 습관은 나쁘지만 그 자체로는 이 사고의 원인이 아니다. 자바스크립트의 기본 인자는 <b>호출할 때마다</b> 평가되므로 리터럴로 바꾸면 실제로 해결된다 — 정의 시점에 한 번인 것은 파이썬이다. 숫자 기본값은 문제가 없다.",
},
{
  t: "review", k: "빈 문자열과 0 을 함께 버린다", cat: "review", d: 2, track: "code",
  q: "이 코드의 결함을 모두 고르세요",
  code: "function buildQuery(filters) {\n  const parts = [];\n  for (const key in filters) {\n    if (!filters[key]) continue;\n    parts.push(key + \"=\" + filters[key]);\n  }\n  return parts.join(\"&\");\n}",
  items: [
    { txt: "<code>for...in</code> 은 프로토타입 체인의 열거 가능한 속성까지 훑으므로 <code>Object.hasOwn</code> 검사가 필요하다 — 리터럴 객체만 넘어온다면 실제로 문제되는 경우는 드물다.", bad: false },
    { txt: "<code>parts.join(\"&\")</code> 앞에 <code>?</code> 를 붙이지 않아 호출자가 URL 을 이어 붙일 때 빠뜨리기 쉽고, 결과가 비었을 때 <code>?</code> 만 남는 주소가 되기도 한다 — 다만 이 함수는 쿼리 부분만 만들기로 한 것이므로 계약대로다.", bad: false },
    { txt: "<code>!filters[key]</code> 는 <code>0</code>·빈 문자열·<code>false</code> 까지 버린다. <code>{ page: 0 }</code> 이나 <code>{ active: false }</code> 처럼 <b>의미 있는 거짓 값</b>이 조용히 사라지므로, <code>== null</code> 로 없는 값만 걸러야 한다.", bad: true },
    { txt: "값이 배열이면 문자열 변환이 일어나 <code>tag=a,b</code> 처럼 이어 붙는데, 서버가 <code>tag=a&amp;tag=b</code> 를 기대한다면 값이 통째로 어긋난다 — 배열을 어떻게 펼칠지는 API 계약에서 정할 일이다.", bad: false },
    { txt: "값을 그대로 이어 붙이므로 <code>&amp;</code> 나 <code>=</code> 가 들어간 값에서 쿼리 문자열이 깨진다. <code>encodeURIComponent</code> 로 <b>키와 값을 모두 인코딩</b>해야 하고, 그러지 않으면 읽는 쪽이 다른 파라미터로 잘못 나눈다.", bad: true },
  ],
  ex: "결함 2가지. (1) <b>거짓 같은 값</b>을 없는 값과 같이 취급한다 — <code>0</code> 과 빈 문자열은 대개 의미가 있으므로, 없는 값만 걸러야 한다. (2) <b>인코딩이 빠졌다</b> — 값에 구분자가 들어가면 쿼리가 통째로 어긋난다.\n디스트랙터: <code>for...in</code> 이 프로토타입 체인까지 훑는 것은 사실이지만, 리터럴 객체만 넘어오는 이 쓰임에서는 실제로 문제가 되지 않는다. <code>?</code> 를 붙일지, 배열 값을 어떤 형식으로 펼칠지는 이 함수가 아니라 <b>API 계약</b>에서 정할 일이다.",
},
];
