/* php 트랙 코드 리뷰 — PHP 를 가장 많이 오해하는 자리에 한 줄 지적을 단다. */
module.exports = [
{
  t: "review", k: "느슨한 비교로 토큰을 맞춘다", cat: "review", d: 3, track: "php",
  q: "이 코드의 결함을 모두 고르세요",
  code: "<?php\nfunction checkToken(string $given, string $stored): bool {\n    return md5($given) == $stored;\n}",
  items: [
    { txt: "<code>md5</code> 는 빠르고 솔트가 없어 무차별 대입과 레인보 테이블에 그대로 노출된다. 비밀번호라면 <code>password_hash</code>·<code>password_verify</code> 를, 단순 토큰이라도 최소한 느린 해시나 충분한 무작위 길이를 써야 한다.", bad: true },
    { txt: "<code>==</code> 는 두 값이 <code>0e</code> 로 시작하는 숫자꼴 문자열이면 <b>둘 다 0 으로 바꿔 비교</b>한다. 서로 다른 해시가 같다고 판정되는 경우가 실제로 있으므로, 문자열 비교에는 <code>===</code> 나 <code>hash_equals</code> 를 써야 한다.", bad: true },
    { txt: "비교가 앞에서부터 다른 글자를 만나면 즉시 끝나므로 응답 시간에 정보가 남는다 — <code>hash_equals</code> 는 길이가 같은 동안 <b>일정한 시간</b>으로 비교해 이 통로를 막아 준다.", bad: true },
    { txt: "반환 타입을 <code>bool</code> 로 선언했으므로 호출하는 쪽에서 <code>if</code> 에 그대로 쓸 수 있고, 실수로 문자열이나 <code>null</code> 이 새어 나가면 그 자리에서 TypeError 로 막힌다 — 이 부분은 오히려 잘 쓴 편이다.", bad: false },
    { txt: "인자 순서가 <code>(given, stored)</code> 라 헷갈리기 쉬우므로 배열이나 객체로 받아 이름을 붙여야 하며, 그러지 않으면 호출자가 뒤바꿔 넘겨도 아무도 눈치채지 못한다.", bad: false },
  ],
  ex: "결함 3가지. (1) <b>빠른 해시</b>는 비밀을 지키지 못한다. (2) <b><code>==</code> 의 형 변환</b>은 <code>\"0e123\"</code> 꼴 문자열을 숫자 0 으로 바꿔 서로 다른 해시를 같다고 만든다. (3) <b>이른 종료 비교</b>는 맞은 글자 수만큼 시간이 달라져 한 글자씩 알아낼 여지를 준다. 셋 다 <code>password_verify</code> 나 <code>hash_equals</code> 로 해결된다.\n디스트랙터: 반환 타입 선언은 오히려 잘한 부분이다. 인자 순서가 헷갈릴 수 있다는 지적은 취향에 가깝고, 두 인자 모두 문자열이라 타입으로도 막히지 않는 별개의 주제다.",
},
{
  t: "review", k: "in_array 를 느슨하게 쓴다", cat: "review", d: 2, track: "php",
  q: "이 코드의 결함을 모두 고르세요",
  code: "<?php\n$allowed = [1, 2, 3];\n\nfunction canUse($roleId, array $allowed): bool {\n    return in_array($roleId, $allowed);\n}",
  items: [
    { txt: "<code>$roleId</code> 에 타입 선언이 없어 문자열과 정수가 섞여 들어올 수 있다 — <code>int $roleId</code> 로 못박으면 느슨한 비교 문제의 절반은 호출 시점에 걸러진다. 다만 타입 선언만으로 전부 막히지는 않는다.", bad: false },
    { txt: "<code>in_array</code> 는 기본이 느슨한 비교라 <code>\"3abc\"</code> 나 <code>true</code> 같은 값이 통과할 수 있다. 권한 판정처럼 틀리면 위험한 자리에서는 세 번째 인자에 <code>true</code> 를 주어 <b>타입까지 견주게</b> 해야 한다.", bad: true },
    { txt: "목록이 세 개뿐이라면 <code>in_array</code> 대신 <code>match</code> 나 <code>switch</code> 로 쓰는 편이 읽기 쉽고, 값이 늘어날 때 어디를 고쳐야 하는지도 분명해진다 — 동작은 같으므로 취향의 영역이다.", bad: false },
    { txt: "허용 목록이 전역 변수로 밖에 있고 함수는 같은 이름의 인자를 받으므로, 호출자가 무엇을 넘겼는지에 따라 판정이 달라진다 — 상수나 열거형으로 <b>한 곳에 고정</b>하는 편이 안전하다.", bad: true },
    { txt: "배열을 값으로 받으므로 큰 목록에서는 복사 비용이 생긴다 — PHP 는 쓰기 전까지 복사를 미루므로 읽기만 하는 이 코드에서는 실제 비용이 발생하지 않는다.", bad: false },
  ],
  ex: "결함 2가지. (1) <b>느슨한 비교</b>가 기본값이라 의도하지 않은 값이 통과한다 — 권한 판정에서는 반드시 엄격 모드를 켠다. (2) <b>허용 목록의 출처가 둘</b>이다 — 전역과 인자가 같은 이름을 쓰면 어느 것이 쓰이는지 읽는 사람마다 다르게 짐작한다.\n디스트랙터: 타입 선언은 도움이 되지만 그것만으로 전부 막히지 않으므로 결함 목록의 답으로는 약하다. <code>match</code> 는 취향이고, 배열 복사는 PHP 의 쓰기 시 복사 덕분에 여기서는 비용이 없다.",
},
{
  t: "review", k: "참조로 순회한 뒤 남은 것", cat: "review", d: 4, track: "php",
  q: "이 코드의 결함을 모두 고르세요",
  code: "<?php\nforeach ($rows as &$row) {\n    $row['total'] = $row['price'] * $row['qty'];\n}\n\nforeach ($rows as $row) {\n    echo $row['total'], PHP_EOL;\n}",
  items: [
    { txt: "합계를 원본 배열에 끼워 넣는 대신 새 배열을 만들어 돌려주면 참조 자체가 필요 없어지고, <code>array_map</code> 으로 바꾸면 이 함정을 구조적으로 피할 수 있다 — 다만 제자리에서 채우는 방식이 반드시 틀린 것은 아니므로 결함이라기보다 대안이다.", bad: false },
    { txt: "<code>PHP_EOL</code> 대신 <code>\\n</code> 을 쓰면 운영체제에 따라 줄바꿈이 달라져 출력이 깨지므로, 웹 응답에서도 반드시 <code>PHP_EOL</code> 을 써야 한다.", bad: false },
    { txt: "첫 반복이 끝난 뒤에도 <code>$row</code> 가 <b>마지막 원소를 가리키는 참조로 남는다</b>. 이어지는 반복은 그 참조에 값을 대입하므로 끝의 원소가 앞 원소들로 계속 덮이고, 결국 바로 앞 원소의 값이 끝자리에 남는다.", bad: true },
    { txt: "<code>$row['price']</code> 나 <code>$row['qty']</code> 가 없으면 경고와 함께 <code>null</code> 로 계산되어 합계가 0 이 된다 — 입력 검증이 필요하다는 지적은 옳지만 이 조각의 초점은 아니다.", bad: false },
    { txt: "참조로 순회한 뒤에는 <code>unset($row);</code> 로 <b>끊어 주는 것이 규칙</b>이다. 이 한 줄이 없으면 같은 이름을 다시 쓰는 순간 조용히 값이 망가지고, 원인을 찾기 어려운 종류의 버그가 된다.", bad: true },
  ],
  ex: "결함 2가지. (1) <b>참조가 반복 뒤에도 살아 있다</b> — PHP 에서 가장 유명한 함정이고, 뒤이은 반복이 그 참조를 덮어써 끝의 원소가 망가진다. (2) 그래서 <b><code>unset</code> 이 규칙</b>이다 — 참조로 순회했으면 반드시 끊는다.\n디스트랙터: <code>array_map</code> 으로 바꾸는 것은 좋은 대안이지만 지금 방식이 틀린 것은 아니다. <code>PHP_EOL</code> 은 CLI 출력의 편의일 뿐 웹 응답에서 필수가 아니고, 키 검증은 이 조각의 초점이 아니다.",
},
{
  t: "review", k: "empty 로 값을 판정한다", cat: "review", d: 2, track: "php",
  q: "이 코드의 결함을 모두 고르세요",
  code: "<?php\nfunction pageOf(array $q): int {\n    if (empty($q['page'])) {\n        return 1;\n    }\n    return (int) $q['page'];\n}",
  items: [
    { txt: "<code>empty</code> 는 <code>\"0\"</code>·<code>0</code>·<code>\"\"</code>·<code>[]</code> 를 모두 참으로 본다. 페이지 번호가 0 인 요청이 조용히 1 로 바뀌므로, 값의 유무를 보려면 <code>isset</code> 이나 <code>array_key_exists</code> 로 <b>있고 없음만</b> 따져야 한다.", bad: true },
    { txt: "음수나 지나치게 큰 페이지 번호를 걸러 주지 않아 조회 계층에서 이상한 오프셋이 만들어질 수 있다 — 범위 검사는 필요하지만 어느 계층에서 할지는 설계에 따라 다르다.", bad: false },
    { txt: "반환 타입을 <code>int</code> 로 선언했으므로 호출자는 항상 정수를 받는다고 믿을 수 있다 — 기본값 1 을 함수 안에서 정한 것도 호출자마다 다른 기본값을 쓰는 것보다 낫다.", bad: false },
    { txt: "<code>(int)</code> 캐스팅은 <code>\"12abc\"</code> 를 12 로, <code>\"abc\"</code> 를 0 으로 바꾼다. 잘못된 입력이 예외 없이 그럴듯한 숫자가 되므로, <code>filter_var</code> 로 검증한 뒤 실패를 <b>값으로 돌려주는</b> 편이 안전하다.", bad: true },
    { txt: "배열을 타입 선언으로 받았으므로 <code>$q</code> 가 문자열이면 즉시 TypeError 가 난다 — 잘못된 호출을 빨리 실패시키는 좋은 습관이며 결함이 아니다.", bad: false },
  ],
  ex: "결함 2가지. (1) <b><code>empty</code> 는 '거짓 같은 값' 전부를 없는 것으로</b> 본다 — 0 이 의미를 갖는 자리에서 값이 조용히 사라진다. (2) <b>캐스팅은 실패하지 않는다</b> — 이상한 문자열도 숫자로 바뀌므로 검증 없이 쓰면 잘못된 입력이 그대로 흘러간다.\n디스트랙터: 범위 검사는 어느 계층의 책임인지 정할 문제다. 반환 타입 선언과 인자 타입 선언은 오히려 잘한 부분이다.",
},
{
  t: "review", k: "쿼리에 값을 이어 붙인다", cat: "review", d: 3, track: "php",
  q: "이 코드의 결함을 모두 고르세요",
  code: "<?php\n$sql = \"SELECT * FROM users WHERE email = '\" . $email . \"'\";\n$rows = $pdo->query($sql)->fetchAll();\nif (count($rows) === 0) {\n    echo \"없는 계정: \" . $email;\n}",
  items: [
    { txt: "<code>SELECT *</code> 는 필요 없는 열까지 읽어 오고 스키마가 바뀌면 조용히 동작이 달라진다 — 필요한 열만 적는 편이 낫지만, 이 코드의 위험은 그것이 아니다.", bad: false },
    { txt: "사용자 입력을 <b>따옴표 안에 그대로 이어 붙였다</b>. 값과 코드의 경계가 사라져 임의의 조건을 넣을 수 있으므로, 반드시 <code>prepare</code> 와 바인딩으로 값을 <b>구조 밖에서</b> 넘겨야 한다.", bad: true },
    { txt: "존재하지 않는 계정임을 그대로 알려 주면 이메일 목록을 대입해 가입 여부를 훑는 데 쓰일 수 있다 — 로그인 화면이라면 메시지를 뭉뚱그리는 편이 낫다는 지적이 맞지만, 여기서는 내부 조회 기능이라 맥락이 다르다.", bad: false },
    { txt: "<code>fetchAll</code> 은 결과를 모두 메모리에 올리므로 큰 결과에서는 위험하다 — 이메일로 한 건을 찾는 이 쿼리에서는 실질적인 문제가 되지 않는다.", bad: false },
    { txt: "입력을 그대로 출력하므로 브라우저에서 스크립트로 실행될 수 있다. 출력 맥락에 맞는 이스케이프(<code>htmlspecialchars</code>)를 거치지 않으면 <b>남의 화면에서 우리 도메인 권한</b>으로 코드가 돈다.", bad: true },
  ],
  ex: "결함 2가지. (1) <b>SQL 조립</b>은 값과 코드의 경계를 지운다 — 이스케이프로 막으려 하면 맥락마다 규칙이 달라 언젠가 새고, 바인딩이 구조적인 해법이다. (2) <b>입력을 그대로 출력</b>하면 저장·반사 경로로 스크립트가 실행된다 — 출력 맥락에 맞는 이스케이프가 필요하다.\n디스트랙터: <code>SELECT *</code> 와 <code>fetchAll</code> 은 개선 여지이지 이 코드의 위험이 아니다. 계정 존재 여부 노출은 인증 화면에서 중요한 논점이지만 여기서는 초점이 다르다.",
},
{
  t: "review", k: "정적 속성에 담아 둔 상태", cat: "review", d: 3, track: "php",
  q: "이 코드의 결함을 모두 고르세요",
  code: "<?php\nclass Cart {\n    private static array $items = [];\n\n    public function add(string $sku): void {\n        self::$items[] = $sku;\n    }\n    public function all(): array {\n        return self::$items;\n    }\n}",
  items: [
    { txt: "정적 속성은 <b>클래스에 하나뿐</b>이라 인스턴스를 새로 만들어도 같은 배열을 공유한다. 한 요청 안에서 여러 사용자의 장바구니를 다루면 내용이 뒤섞이고, 워커를 재사용하는 실행 모델에서는 요청 사이에도 남는다.", bad: true },
    { txt: "<code>self::</code> 대신 <code>static::</code> 를 쓰면 늦은 정적 바인딩이 적용되어 상속한 하위 클래스가 자기 저장소를 갖게 되고 공유 문제가 사라지므로, 지금 코드를 그렇게 바꿔야 한다.", bad: false },
    { txt: "인스턴스 메서드에서 정적 상태를 만지므로 이 클래스는 <b>테스트하기 어렵다</b>. 앞 테스트가 넣은 값이 다음 테스트로 넘어가 순서에 따라 결과가 달라지고, 정리하려면 리플렉션 같은 우회가 필요해진다.", bad: true },
    { txt: "타입 선언이 붙은 속성과 메서드 시그니처는 잘 갖춰져 있어 잘못된 값이 들어올 여지를 줄인다 — 문제는 타입이 아니라 값이 어디에 사는가이다.", bad: false },
    { txt: "장바구니에 같은 SKU 를 여러 번 넣을 수 있으므로 수량 개념이 필요하다 — 도메인 모델의 설계 주제이지 이 코드의 결함은 아니다.", bad: false },
  ],
  ex: "결함 2가지. (1) <b>정적 속성은 인스턴스마다 갖는 상태가 아니다</b> — 사용자별 데이터를 담으면 서로의 것이 섞인다. (2) 그래서 <b>테스트가 서로에게 영향을 준다</b> — 상태를 인스턴스 속성으로 옮기면 둘 다 사라진다.\n디스트랙터: <code>static::</code> 는 하위 클래스가 <b>따로 선언했을 때만</b> 저장소가 갈리므로 공유 문제의 해법이 아니다. 타입 선언은 잘 갖춰져 있고, 수량 모델링은 별개의 설계 주제다.",
},
{
  t: "review", k: "디코드 결과를 그대로 믿는다", cat: "review", d: 2, track: "php",
  q: "이 코드의 결함을 모두 고르세요",
  code: "<?php\nfunction readConfig(string $json): array {\n    $data = json_decode($json);\n    // 설정은 options 아래에만 들어 있다고 약속돼 있다\n    return $data->options;\n}\n\n$cfg = readConfig(file_get_contents('/etc/app/config.json'));",
  items: [
    { txt: "<code>options</code> 키가 없을 수 있으므로 <code>??</code> 로 기본값을 주는 편이 안전하다 — 옳은 지적이지만 앞의 두 문제를 고치면 자연스럽게 함께 다루게 되는 후속 작업이다.", bad: false },
    { txt: "<code>json_decode</code> 는 실패해도 예외 대신 <code>null</code> 을 돌려준다. 그 상태에서 속성을 읽으면 오류가 나므로, <code>JSON_THROW_ON_ERROR</code> 를 주거나 <code>json_last_error</code> 로 <b>실패를 확인</b>해야 한다.", bad: true },
    { txt: "큰 JSON 을 통째로 메모리에 올리므로 스트리밍 파서를 써야 한다 — 설정 파일 규모에서는 문제가 되지 않고, 오히려 코드만 복잡해진다.", bad: false },
    { txt: "두 번째 인자를 주지 않으면 객체로 디코드되는데 함수는 <code>array</code> 를 돌려주기로 선언했다. <code>options</code> 가 객체면 <b>반환 시점에 TypeError</b> 가 나고, 이 불일치는 선언과 구현을 함께 봐야 보인다.", bad: true },
    { txt: "함수 이름과 인자 타입이 무엇을 받는지 분명히 알려 주므로 호출자가 잘못 쓰기 어렵다 — 이름과 시그니처는 잘 지어진 편이다.", bad: false },
  ],
  ex: "결함 2가지. (1) <b>실패가 <code>null</code> 로 조용히 돌아온다</b> — 확인하지 않으면 엉뚱한 자리에서 터진다. (2) <b>선언한 반환 타입과 실제 값의 모양이 어긋난다</b> — 연관 배열이 필요하면 <code>json_decode($json, true)</code> 로 받아야 한다.\n디스트랙터: 키 부재 처리는 후속 작업이고, 스트리밍 파서는 설정 파일 규모에서 과하다. 이름과 시그니처는 잘 지어진 편이다.",
},
{
  t: "review", k: "출력 뒤에 헤더를 보낸다", cat: "review", d: 2, track: "php",
  q: "이 코드의 결함을 모두 고르세요",
  code: "<?php\necho \"처리 중...\";\n\nif ($user === null) {\n    header(\"Location: /login\");\n    exit;\n}\nsetcookie(\"seen\", \"1\");",
  items: [
    { txt: "리다이렉트 뒤 <code>exit</code> 를 부른 것은 옳다 — 그러지 않으면 응답 본문이 계속 만들어져 로그인하지 않은 사용자에게 내용이 새어 나갈 수 있다.", bad: false },
    { txt: "<code>Location</code> 헤더에는 절대 URL 을 써야 하며 상대 경로를 쓰면 일부 클라이언트가 해석하지 못하므로, 도메인을 포함한 주소로 바꿔야 한다.", bad: false },
    { txt: "본문을 먼저 <code>echo</code> 했으므로 헤더는 이미 전송된 뒤다. <code>header</code> 와 <code>setcookie</code> 는 <b>경고만 남기고 아무 일도 하지 않으므로</b>, 리다이렉트도 쿠키 설정도 조용히 실패한다.", bad: true },
    { txt: "출력 버퍼링을 켜면 이 순서로도 동작하지만, 그것은 증상을 가리는 것이지 구조를 고치는 것이 아니다 — 헤더는 본문보다 먼저 정하는 편이 언제나 낫다.", bad: false },
    { txt: "<code>setcookie</code> 에 <code>HttpOnly</code>·<code>Secure</code>·<code>SameSite</code> 를 지정하지 않아 스크립트에서 읽히고 평문으로도 오간다 — 옵션 배열로 <b>속성을 명시</b>하는 것이 지금의 기본이다.", bad: true },
  ],
  ex: "결함 2가지. (1) <b>본문이 나간 뒤에는 헤더를 보낼 수 없다</b> — 리다이렉트와 쿠키가 조용히 무시되고, 화면에는 '처리 중…' 만 남는다. (2) <b>쿠키 속성이 비어 있다</b> — 세션과 관련된 값이라면 최소한 <code>HttpOnly</code> 와 <code>Secure</code> 는 지정해야 한다.\n디스트랙터: 리다이렉트 뒤의 <code>exit</code> 는 오히려 필요한 처리다. 현대 클라이언트는 상대 경로 <code>Location</code> 을 잘 처리한다. 출력 버퍼링은 증상을 덮는 우회일 뿐 구조적 해법이 아니다.",
},
];
