/* fp 트랙 코드 리뷰 — 함수형으로 쓴 척하는 코드에 한 줄 지적을 단다. */
module.exports = [
{
  t: "review", k: "map 안에서 바깥을 바꾼다", cat: "review", d: 2, track: "fp",
  q: "이 코드의 결함을 모두 고르세요",
  code: "let total = 0;\n\nconst labels = items.map((it) => {\n  total += it.price;\n  return it.name + \" (\" + it.price + \")\";\n});",
  items: [
    { txt: "<code>map</code> 은 값을 변환해 새 배열을 만드는 자리인데 바깥 변수를 함께 바꾸고 있다. 이런 코드는 <b>순서와 실행 횟수에 의존</b>하게 되어, 나중에 결과만 재사용하거나 게으르게 평가하는 순간 합계가 어긋난다.", bad: true },
    { txt: "<code>map</code> 의 콜백에서 문자열을 이어 붙이는 대신 템플릿 리터럴을 쓰면 읽기 쉬워진다 — 취향의 문제이고 동작에는 아무 차이가 없으므로 리뷰에서 굳이 막을 이유는 없다.", bad: false },
    { txt: "합계와 라벨을 한 번에 만들려면 <code>reduce</code> 로 <b>두 값을 함께 접거나</b> 순회를 두 번 도는 편이 낫다. 배열이 아주 크지 않다면 두 번 도는 쪽이 읽기 쉽고, 각 단계가 무엇을 만드는지 이름으로 드러난다.", bad: true },
    { txt: "<code>let total</code> 을 모듈 최상위에 두었다면 이 코드를 두 번 실행할 때 앞의 합계 위에 계속 더해져 값이 부풀지만, 주어진 조각만으로는 함수 안인지 모듈 밖인지 알 수 없으므로 결함이라고 단정할 수 없다.", bad: false },
    { txt: "<code>items</code> 가 비어 있으면 <code>map</code> 이 <code>undefined</code> 를 돌려주므로 <code>labels</code> 를 쓰기 전에 존재 여부를 검사해야 한다.", bad: false },
  ],
  ex: "결함 2가지. (1) <b>변환 자리에서 부수효과</b>를 낸다 — <code>map</code> 은 '각 원소를 무엇으로 바꿀 것인가' 만 말해야 하고, 바깥을 바꾸면 그 약속이 깨진다. (2) 두 가지 결과를 한 순회에 섞어 <b>의도가 흐려진다</b> — <code>reduce</code> 로 명시적으로 접거나 순회를 나누면 각 단계가 무엇을 만드는지 드러난다.\n디스트랙터: 템플릿 리터럴은 취향이다. 최상위 <code>let</code> 은 걱정할 만하지만 이 조각만으로는 알 수 없다. 빈 배열에서 <code>map</code> 은 빈 배열을 돌려주지 <code>undefined</code> 가 아니다.",
},
{
  t: "review", k: "누산기를 그 자리에서 바꾼다", cat: "review", d: 3, track: "fp",
  q: "이 코드의 결함을 모두 고르세요",
  code: "const byUser = orders.reduce((acc, o) => {\n  acc[o.userId] = acc[o.userId] || [];\n  acc[o.userId].push(o);\n  return acc;\n}, {});",
  items: [
    { txt: "누산기를 제자리에서 바꾸는 것은 <code>reduce</code> 의 흔한 관용구이고, 초기값을 <b>이 호출에서 새로 만들었으므로</b> 밖으로 새지 않는다 — 성능 면에서도 매번 객체를 복사하는 것보다 낫다.", bad: false },
    { txt: "<code>o.userId</code> 가 <code>undefined</code> 면 <code>\"undefined\"</code> 라는 키에 모두 모인다. 키가 없을 수 있는 데이터라면 <b>그 자리에서 걸러 내거나</b> 별도 버킷으로 옮겨, 잘못된 묶음이 조용히 만들어지지 않게 해야 한다.", bad: true },
    { txt: "<code>Object.groupBy</code> 나 <code>Map</code> 을 쓰면 무엇을 묶는지가 이름으로 드러나고, 특히 <code>Map</code> 은 키 타입을 그대로 보존하며 프로토타입 오염 걱정도 없다 — 다만 지금 코드가 틀린 것은 아니므로 결함이라기보다 리팩터링 제안에 가깝다.", bad: false },
    { txt: "빈 객체를 초기값으로 쓰면 <code>__proto__</code> 같은 키가 들어올 때 프로토타입을 건드릴 수 있으므로, 사용자 입력에서 온 키를 그대로 쓴다면 <code>Object.create(null)</code> 로 시작해야 한다.", bad: true },
    { txt: "<code>reduce</code> 는 배열이 비어 있고 초기값이 없으면 예외를 던지므로, 초기값 <code>{}</code> 를 준 이 코드는 그 위험을 이미 피했다.", bad: false },
  ],
  ex: "결함 2가지. (1) <b>키가 없는 경우</b>를 다루지 않아 <code>\"undefined\"</code> 버킷이 조용히 생긴다 — 집계에서 가장 흔한 오염이다. (2) 사용자 입력에서 온 키를 평범한 객체에 넣으면 <code>__proto__</code> 같은 특수 키가 <b>프로토타입을 건드린다</b> — <code>Object.create(null)</code> 이나 <code>Map</code> 이 안전하다.\n디스트랙터: 이 호출에서 만든 초기값을 제자리에서 바꾸는 것은 밖으로 새지 않으므로 순수성을 해치지 않는다. <code>groupBy</code> 제안은 좋은 리팩터링이지 결함이 아니고, 초기값을 준 <code>reduce</code> 는 빈 배열에서도 안전하다.",
},
{
  t: "review", k: "얕게 복사하고 안심한다", cat: "review", d: 3, track: "fp",
  q: "이 코드의 결함을 모두 고르세요",
  code: "function withTag(state, tag) {\n  const next = { ...state };\n  next.filters.tags.push(tag);\n  return next;\n}",
  items: [
    { txt: "<code>structuredClone</code> 으로 통째로 깊은 복사를 하면 코드가 간단해지지만, 상태가 크면 매번 전부 복사하는 비용이 들고 함수·심볼처럼 복사되지 않는 값도 있다 — 바뀌는 경로만 새로 만드는 편이 보통 낫다.", bad: false },
    { txt: "함수 이름이 <code>withTag</code> 라 새 상태를 돌려준다는 의도는 잘 드러난다 — 이름이 계약을 설명하는 좋은 예이고, 이름 자체를 바꿀 이유는 없다.", bad: false },
    { txt: "전개는 <b>한 겹만</b> 복사한다. <code>next.filters</code> 는 여전히 원본과 같은 객체이므로 <code>tags</code> 에 밀어 넣는 순간 <b>원래 상태도 함께 바뀐다</b> — 새 객체를 돌려주니 안전해 보이는 것이 이 버그를 오래 살려 둔다.", bad: true },
    { txt: "<code>tag</code> 가 이미 목록에 있는지 검사하지 않아 같은 태그가 여러 번 들어갈 수 있다 — 중복 허용 여부는 이 함수가 아니라 태그 모델의 규칙에서 정할 일이다.", bad: false },
    { txt: "리액트 같은 곳에서는 참조가 같으면 다시 그리지 않는데, <code>filters</code> 참조가 그대로라 <b>화면이 갱신되지 않을 수도</b> 있다. 값은 바뀌었는데 화면은 그대로인, 가장 찾기 어려운 종류의 증상이 된다.", bad: true },
  ],
  ex: "결함 2가지. (1) <b>얕은 복사</b>라 중첩된 객체는 공유된다 — 겉으로는 불변처럼 보이는데 원본이 바뀌므로, 되돌리기·비교·캐시가 전부 어긋난다. (2) 참조 동일성으로 변경을 감지하는 도구에서는 <b>바뀐 것을 눈치채지 못한다</b>. 바뀌는 경로만 새로 만들어 <code>{ ...state, filters: { ...state.filters, tags: [...tags, tag] } }</code> 처럼 써야 한다.\n디스트랙터: 통째 깊은 복사는 대안 중 하나일 뿐 비용과 한계가 있다. 이름은 오히려 좋은 편이고, 중복 허용 여부는 모델의 규칙이다.",
},
{
  t: "review", k: "순수한 척하는 파이프라인", cat: "review", d: 2, track: "fp",
  q: "이 코드의 결함을 모두 고르세요",
  code: "const top3 = (rows) =>\n  rows\n    .sort((a, b) => b.score - a.score)\n    .slice(0, 3)\n    .map((r) => r.name);",
  items: [
    { txt: "<code>sort</code> 는 <b>원본 배열을 제자리에서</b> 정렬한다. 화살표 하나로 이어진 순수해 보이는 파이프라인이지만 호출자의 배열 순서를 바꿔 놓으므로, <code>rows.slice().sort(...)</code> 나 <code>toSorted</code> 로 복사본을 정렬해야 한다.", bad: true },
    { txt: "<code>slice(0, 3)</code> 은 <code>rows</code> 가 3개 미만이면 예외를 던지므로, 길이를 먼저 검사하고 부족하면 있는 만큼만 돌려주도록 감싸는 편이 안전하다.", bad: false },
    { txt: "전체를 정렬한 뒤 앞의 셋만 쓰므로 <code>O(n log n)</code> 이 든다 — 크기 3 의 최소 힙이나 한 번의 순회로 <code>O(n)</code> 에 끝낼 수 있지만, 이것은 정확성 문제가 아니고 목록이 작으면 차이를 느낄 수도 없다.", bad: false },
    { txt: "점수가 같을 때의 순서가 정해지지 않아 상위 3명이 실행마다 달라질 수 있다 — 동점 처리 규칙이 필요하다면 <code>id</code> 처럼 유일한 값을 두 번째 기준으로 넣어 <b>결과를 결정적으로</b> 만들어야 한다.", bad: true },
    { txt: "화살표 함수 본문을 여러 줄에 걸쳐 메서드 체인으로 쓰면 중간값에 이름이 없어 디버깅이 어렵다 — 읽기 취향의 문제이며, 단계마다 이름을 붙이는 스타일도 똑같이 정당하다.", bad: false },
  ],
  ex: "결함 2가지. (1) <b>제자리 정렬</b>이 파이프라인 한가운데 있다 — 함수형 스타일로 보이지만 입력을 바꾸므로, 같은 배열을 쓰는 다른 코드가 영향을 받는다. (2) <b>동점 순서가 결정적이지 않다</b> — 상위 k 를 뽑는 함수는 같은 입력에 같은 답을 줘야 신뢰할 수 있다.\n디스트랙터: <code>slice</code> 는 범위를 넘겨도 예외 없이 있는 만큼만 돌려준다. 정렬 비용과 체인 스타일은 결함이 아니다.",
},
{
  t: "review", k: "부수효과를 기억하는 메모이제이션", cat: "review", d: 3, track: "fp",
  q: "이 코드의 결함을 모두 고르세요",
  code: "const cache = new Map();\n\nfunction memo(fn) {\n  return (arg) => {\n    if (cache.has(arg)) return cache.get(arg);\n    const v = fn(arg);\n    cache.set(arg, v);\n    return v;\n  };\n}",
  items: [
    { txt: "인자가 객체면 참조로 키가 잡혀 내용이 같아도 캐시에 걸리지 않는다 — 값 기준으로 캐시하려면 키를 만들어야 하지만, 그것은 이 구현이 약속한 범위 밖의 이야기다.", bad: false },
    { txt: "캐시가 <b>모듈에 하나뿐</b>이라 <code>memo</code> 로 감싼 서로 다른 함수들이 같은 저장소를 나눠 쓴다. 인자가 같으면 다른 함수의 결과가 돌아오므로, 캐시는 <code>memo</code> 호출마다 새로 만들어야 한다.", bad: true },
    { txt: "<code>Map</code> 은 넣은 항목을 계속 붙잡으므로 인자의 종류가 많으면 메모리가 한없이 자란다 — 상한이나 만료가 필요하다는 지적은 옳지만, 값의 가짓수가 애초에 적은 캐시라면 필요 없을 수도 있다.", bad: false },
    { txt: "인자가 하나뿐인 함수만 감쌀 수 있으므로 <code>(...args)</code> 로 받아 <code>JSON.stringify</code> 를 키로 써야 하며, 그렇게 바꾸지 않으면 대부분의 함수에 쓸 수 없다.", bad: false },
    { txt: "메모이제이션은 <b>같은 입력에 같은 출력</b>이라는 성질에 기대는 최적화다. 시간·난수·입출력에 의존하는 함수를 감싸면 처음 한 번의 결과가 영원히 굳어 버리고, 그 뒤로는 무엇을 고쳐도 옛 값이 돌아오므로 감쌀 수 있는 함수인지 먼저 따져야 한다.", bad: true },
  ],
  ex: "결함 2가지. (1) <b>캐시를 공유한다</b> — <code>memo(f)</code> 와 <code>memo(g)</code> 가 같은 저장소를 쓰므로 결과가 뒤섞인다. 캐시는 반환하는 함수마다 새로 만들어야 한다. (2) <b>순수하지 않은 함수를 감싸면</b> 첫 결과가 영원히 굳는다 — 메모이제이션은 함수의 성질에 기대는 최적화다.\n디스트랙터: 객체 인자와 메모리 상한은 캐시 설계의 선택지이고, 인자 하나만 받는 것은 이 구현이 정한 계약이지 결함이 아니다.",
},
{
  t: "review", k: "예외로 흐름을 만든다", cat: "review", d: 2, track: "fp",
  q: "이 코드의 결함을 모두 고르세요",
  code: "function parseAge(s) {\n  const n = Number(s);\n  if (Number.isNaN(n)) throw new Error(\"bad\");\n  return n;\n}\n\nconst ages = inputs.map((s) => {\n  try { return parseAge(s); } catch { return null; }\n});",
  items: [
    { txt: "실패를 예외로 던지고 곧바로 잡아 <code>null</code> 로 바꾸는 것은 <b>제어 흐름으로 예외를 쓰는</b> 형태다. 실패가 값의 일부라면 <code>null</code> 이나 결과 타입을 <b>돌려주는</b> 편이 합성하기 쉽고 비용도 낮다.", bad: true },
    { txt: "<code>Number(\"\")</code> 는 <code>0</code> 이므로 빈 문자열이 나이 0 으로 통과한다 — 입력 검증에서 자주 놓치는 자리지만, 이 리뷰의 초점인 흐름 설계와는 다른 층위의 지적이다.", bad: false },
    { txt: "<code>Error(\"bad\")</code> 는 무엇이 왜 잘못됐는지 알려 주지 않는다. 잡는 쪽에서 구분할 수 없고 로그에도 남기지 않으므로, 최소한 어떤 입력이 실패했는지 메시지에 담아야 원인을 추적할 수 있다.", bad: true },
    { txt: "<code>catch</code> 에서 바인딩을 생략한 문법은 비교적 최신이라 오래된 실행 환경에서 문법 오류가 나므로, 반드시 <code>catch (e)</code> 로 되돌려야 한다.", bad: false },
    { txt: "결과 배열에 <code>null</code> 이 섞이므로 뒤에서 다시 걸러야 하는데, 그 시점에는 어떤 입력이 실패했는지가 이미 사라져 원인을 알려 줄 수 없다 — 입력과 짝을 이루어 돌려주면 낫지만 계약에 따라 다르다.", bad: false },
  ],
  ex: "결함 2가지. (1) <b>예외를 곧바로 잡아 값으로 바꾼다</b> — 그럴 것이라면 처음부터 값으로 돌려주는 편이 낫다. 예외는 '여기서는 다룰 수 없다' 는 신호일 때 쓰는 도구다. (2) <b>오류가 정보를 담지 않는다</b> — 잡는 쪽도 로그도 무엇이 실패했는지 알 수 없다.\n디스트랙터: <code>Number(\"\")</code> 문제는 별개의 검증 주제다. <code>catch</code> 바인딩 생략은 현대 환경에서 널리 지원된다. <code>null</code> 이 섞이는 것은 계약의 선택이다.",
},
{
  t: "review", k: "커링한 함수가 상태를 안고 있다", cat: "review", d: 3, track: "fp",
  q: "이 코드의 결함을 모두 고르세요",
  code: "const makeFormatter = (opts) => {\n  const parts = [];\n  return (row) => {\n    parts.push(row.id);\n    return opts.prefix + row.id + \" (\" + parts.length + \")\";\n  };\n};",
  items: [
    { txt: "<code>opts.prefix</code> 가 없으면 <code>\"undefined\"</code> 가 앞에 붙는다 — 기본값을 두거나 생성 시점에 검증하면 좋지만, 옵션 검증은 이 함수의 계약에 명시돼 있지 않다.", bad: false },
    { txt: "돌려주는 함수가 <b>클로저에 상태를 쌓는다</b>. 같은 입력에 다른 출력이 나오므로 <code>map</code> 같은 곳에 넘기면 순서에 따라 결과가 달라지고, 재시도나 병렬 처리에서 값이 어긋난다.", bad: true },
    { txt: "화살표 함수를 이중으로 쓰면 이름이 없어 스택 추적이 읽기 어렵다 — 이름 있는 함수 선언으로 바꾸면 디버깅이 편해지지만 동작은 같으므로 취향의 영역이다.", bad: false },
    { txt: "<code>parts</code> 는 커진 채로 계속 남는다 — 포매터를 오래 들고 있으면 처리한 행 수만큼 배열이 자라 메모리가 새고, 그 값이 실제로 쓰이는 곳은 길이뿐이라 더욱 아깝다.", bad: true },
    { txt: "클로저로 옵션을 붙잡는 것 자체는 부분 적용의 정석이다 — 문제는 옵션이 아니라 <b>호출마다 변하는 상태</b>를 함께 붙잡은 데 있다.", bad: false },
  ],
  ex: "결함 2가지. (1) <b>호출마다 결과가 달라진다</b> — 순번을 매기려는 의도라면 그것을 인자로 받거나 <code>map</code> 의 인덱스를 쓰는 편이 정직하다. (2) <b>쌓기만 하고 비우지 않는</b> 배열이 메모리에 남는다. 길이만 필요하다면 숫자 하나로 충분하고, 그마저도 바깥에서 세는 편이 낫다.\n디스트랙터: 옵션 기본값과 이름 있는 함수는 개선 제안이다. 클로저로 옵션을 붙잡는 것은 부분 적용의 정석이며, 문제는 변하는 상태를 함께 붙잡은 데 있다.",
},
{
  t: "review", k: "게으른 척하는 파이프라인", cat: "review", d: 3, track: "fp",
  q: "이 코드의 결함을 모두 고르세요",
  code: "const first = rows\n  .map((r) => expensive(r))\n  .filter((r) => r.ok)\n  .find((r) => r.score > 90);",
  items: [
    { txt: "<code>find</code> 는 조건을 만족하는 값이 없으면 <code>undefined</code> 를 돌려주므로 뒤에서 옵셔널 체이닝이나 기본값이 필요하다 — 이 코드 자체의 결함이 아니라 사용하는 쪽의 계약이다.", bad: false },
    { txt: "<code>expensive</code> 가 저장이나 전송 같은 부수효과를 낸다면 필요 없는 행에까지 그것이 실행되어 훨씬 큰 문제가 되지만, 이름만으로는 순수한 계산인지 알 수 없으므로 결함이라고 단정할 수 없다.", bad: false },
    { txt: "<code>map</code> 이 <b>모든 행에 대해 먼저 다 돈다</b>. 찾는 값이 앞쪽에 있어도 뒤쪽까지 비싼 계산을 전부 수행하므로, 조건을 만족하는 첫 값만 필요하다면 한 번의 순회에서 변환하고 판정하고 찾는 즉시 멈추는 형태로 바꿔야 한다.", bad: true },
    { txt: "메서드 체인 대신 <code>for</code> 문으로 쓰면 항상 더 빠르므로, 성능이 중요한 경로에서는 체인을 쓰지 않도록 규칙으로 금지해야 한다.", bad: false },
    { txt: "중간 배열이 두 개 만들어져 입력이 클수록 메모리를 크게 쓴다 — 자바스크립트의 배열 메서드는 게으르지 않으므로, 큰 데이터에서는 제너레이터나 순회 한 번으로 합치는 편이 낫다.", bad: true },
  ],
  ex: "결함 2가지. (1) <b>필요 없는 계산을 전부 한다</b> — 앞의 한 건만 필요한데 모든 행을 변환하므로, 데이터가 커질수록 낭비가 그대로 늘어난다. (2) <b>중간 배열</b>이 두 벌 생긴다. 둘 다 '한 번 돌면서 판정하고 찾으면 멈춘다' 로 바꾸면 함께 사라진다.\n디스트랙터: <code>find</code> 의 <code>undefined</code> 반환은 정상 계약이다. <code>expensive</code> 의 순수성은 이 조각만으로 알 수 없고, 체인을 <b>항상</b> 금지하는 규칙은 지나치다 — 대부분의 코드에서 읽기 쉬움이 더 값지다.",
},
];
