/* 보안 실습 2차 — 실습이 하나도 없던 6개 유닛을 연다.
   웹 보안 기초 · OWASP · 인증과 인가 · 암호화와 비밀 관리 · 접근 통제 · 운영 보안.

   보안은 '조심하자' 로 끝나기 쉽다. 하지만 실제로 뚫리는 자리는 대개 한 줄짜리
   판단이다 — 어디까지 escape 할지, 토큰을 어떻게 견줄지, 남의 자원인지 어떻게 볼지.
   그 판단을 직접 짜 보면 '왜 그렇게 해야 하는지' 가 손에 남는다.

   채점은 앱의 JS 하네스가 한다. */
module.exports = [
/* ── 웹 보안 기초 ─────────────────────────────────────────── */
{
  unit: "웹 보안 기초",
  lesson: "직접 짜 보기 — 남이 준 글자를 그대로 믿지 않기",
  th: {
    sum: "웹 취약점의 대부분은 **남이 준 글자를 그대로 쓴 것**에서 나온다.",
    body: [
      { h: "글자가 코드가 되는 순간", t: "사용자가 적은 글을 화면에 그대로 넣으면, `<script>` 를 적어 넣은 사람이 그 페이지에서 코드를 돌릴 수 있다. 글자를 글자로만 보이게 바꿔 주는 것(escape)이 첫 번째 방어다." },
      { h: "다섯 글자를 바꾼다", t: "`&`·`<`·`>`·`\"`·`'` 를 각각 이름 있는 표기로 바꾼다. `&` 를 **가장 먼저** 바꿔야 한다 — 나중에 바꾸면 앞서 만든 `&lt;` 의 `&` 까지 다시 바뀌어 글자가 깨진다." },
      { h: "어디에 넣는지에 따라 다르다", t: "HTML 본문·속성·자바스크립트 안·주소는 각각 위험한 글자가 다르다. 한 가지 방법으로 다 막으려 하면 어딘가는 새거나 멀쩡한 글자가 깨진다. 넣는 자리에 맞는 처리를 골라야 한다." },
      { h: "막는 목록보다 허용 목록", t: "'이런 건 안 돼' 를 나열하면 빠뜨린 것이 반드시 생긴다. '이것만 돼' 를 적으면 모르는 것은 기본적으로 막힌다. 새 공격 방식이 나와도 허용 목록은 그대로 버틴다." },
    ],
    code: { c: "s.replace(/&/g, '&amp;')   // & 를 먼저\n .replace(/</g, '&lt;')\n .replace(/>/g, '&gt;')", cap: "& 를 가장 먼저 바꾼다" },
    key: ["남의 글자를 그대로 넣지 않는다", "`&` 를 가장 먼저 바꾼다", "막는 목록보다 허용 목록"],
  },
  q: [
    {
      k: "escapeHtml · 순서까지 맞춰 바꾸기",
      qq: "HTML 에 넣어도 안전하도록 <code>&amp;</code>·<code>&lt;</code>·<code>&gt;</code>·<code>\"</code> 를 바꿔 주세요. <b>이미 바꾼 것이 다시 바뀌면 안 됩니다.</b>",
      src: "function escapeHtml(s) {\n  return String(s)\n    .replace(/</g, '&lt;')\n    .replace(/>/g, '&gt;')\n    .replace(/\"/g, '&quot;')\n    .replace(/&/g, '&amp;');\n}",
      sol: "function escapeHtml(s) {\n  return String(s)\n    .replace(/&/g, '&amp;')\n    .replace(/</g, '&lt;')\n    .replace(/>/g, '&gt;')\n    .replace(/\"/g, '&quot;');\n}",
      tests: [["escapeHtml('<b>')", "'&lt;b&gt;'"],
              ["escapeHtml('a & b')", "'a &amp; b'"],
              ["escapeHtml('\"x\"')", "'&quot;x&quot;'"]],
      edge: [["escapeHtml('')", "''"],
             ["escapeHtml('&amp;')", "'&amp;amp;'"]],
      ex: "& 를 마지막에 바꾸면, 앞에서 만든 &lt; 의 & 까지 다시 바뀌어 &amp;lt; 가 됩니다. 화면에는 '&lt;' 라는 글자가 그대로 보여요. 순서 하나로 결과가 달라집니다.",
    },
    {
      k: "safeUrl · 이상한 주소 막기",
      qq: "링크에 쓸 주소를 검사하세요. <code>http:</code>·<code>https:</code>·<code>/</code> 로 시작하는 것만 통과시키고, 나머지는 <code>'#'</code> 을 돌려줍니다.",
      src: "function safeUrl(u) {\n  return u.startsWith('javascript:') ? '#' : u;\n}",
      sol: "function safeUrl(u) {\n  const s = String(u).trim().toLowerCase();\n  if (s.startsWith('http://') || s.startsWith('https://') || s.startsWith('/')) return u;\n  return '#';\n}",
      tests: [["safeUrl('https://example.com')", "'https://example.com'"],
              ["safeUrl('javascript:alert(1)')", "'#'"],
              ["safeUrl('  JavaScript:alert(1)')", "'#'"]],
      edge: [["safeUrl('/about')", "'/about'"],
             ["safeUrl('data:text/html,<script>')", "'#'"]],
      ex: "'javascript:' 하나만 막으면 앞에 공백을 넣거나 대문자로 쓰거나 data: 를 쓰면 그대로 통과합니다. 막을 것을 나열하는 방식은 늘 빠뜨려요. 허용할 것만 적으면 모르는 것은 자동으로 막힙니다.",
    },
    {
      k: "allowedFields · 받을 항목만 받기",
      qq: "요청 본문에서 <b>허용된 항목만</b> 남긴 새 객체를 돌려주세요. 나머지는 버립니다.",
      src: "function allowedFields(body, allow) {\n  const out = Object.assign({}, body);\n  delete out.isAdmin;\n  return out;\n}",
      sol: "function allowedFields(body, allow) {\n  const out = {};\n  for (const k of allow) {\n    if (k in body) out[k] = body[k];\n  }\n  return out;\n}",
      tests: [["allowedFields({ name: '가', isAdmin: true }, ['name'])", "({ name: '가' })"],
              ["allowedFields({ name: '가', role: 'admin' }, ['name'])", "({ name: '가' })"],
              ["allowedFields({ name: '가' }, ['name', 'age'])", "({ name: '가' })"]],
      edge: [["allowedFields({}, ['name'])", "({})"],
             ["allowedFields({ a: 1 }, [])", "({})"]],
      ex: "위험한 항목을 하나씩 지우는 방식은, 나중에 누가 새 항목을 추가하면 그대로 뚫립니다. 받을 것만 골라 담으면 모르는 항목은 애초에 들어오지 못해요.",
    },
  ],
},
/* ── OWASP Top 10 실전 ────────────────────────────────────── */
{
  unit: "OWASP Top 10 실전",
  lesson: "직접 짜 보기 — 값과 명령을 섞지 않기",
  th: {
    sum: "인젝션은 **값이 명령으로 읽히는 것**이다. 둘을 섞어 문자열로 만드는 순간 생긴다.",
    body: [
      { h: "붙이지 말고 따로 넘긴다", t: "`\"... WHERE id = \" + input` 은 입력이 그대로 쿼리의 일부가 된다. 자리표시자를 두고 값을 따로 넘기면, 데이터베이스가 그것을 언제나 값으로만 다룬다. 이스케이프를 직접 하는 것보다 훨씬 안전하다." },
      { h: "정렬 기준 같은 것은 목록으로", t: "열 이름은 자리표시자로 넘길 수 없다. 이럴 때는 허용 목록에서 고르게 한다. 사용자가 준 글자를 그대로 열 이름에 넣으면 그 자리로 인젝션이 들어온다." },
      { h: "명령 실행은 인자 배열로", t: "셸에 문자열로 넘기면 `;` 하나로 다른 명령이 붙는다. 명령과 인자를 배열로 나눠 넘기면 셸을 거치지 않아 그 틈이 없다." },
      { h: "경로도 값이다", t: "파일 이름을 받아 그대로 이어 붙이면 `../` 로 위 폴더에 나갈 수 있다. 기준 폴더 안에 있는지 확인하고 벗어나면 거절한다." },
    ],
    code: { c: "db.query('SELECT * FROM u WHERE id = ?', [id]);\n\nconst col = ALLOWED.includes(sort) ? sort : 'id';", cap: "값은 값으로만 넘긴다" },
    key: ["문자열로 붙이지 않는다", "열 이름은 허용 목록에서", "경로는 벗어나는지 본다"],
  },
  q: [
    {
      k: "buildQuery · 값을 따로 넘기기",
      qq: "쿼리와 값을 <b>따로</b> 돌려주세요. 형식은 <code>{ sql, params }</code> 이고 자리표시자는 <code>?</code> 입니다.",
      src: "function buildQuery(id) {\n  return { sql: 'SELECT * FROM users WHERE id = ' + id, params: [] };\n}",
      sol: "function buildQuery(id) {\n  return { sql: 'SELECT * FROM users WHERE id = ?', params: [id] };\n}",
      tests: [["buildQuery(12).sql", "'SELECT * FROM users WHERE id = ?'"],
              ["buildQuery(12).params", "[12]"],
              ["buildQuery(\"1 OR 1=1\").sql.includes('OR')", "false"]],
      edge: [["buildQuery(0).params", "[0]"]],
      ex: "값을 문자열에 붙이면 '1 OR 1=1' 같은 입력이 쿼리의 일부가 되어 전체 행이 나옵니다. 자리표시자로 넘기면 데이터베이스가 그것을 언제나 값으로만 다뤄요.",
    },
    {
      k: "sortColumn · 열 이름은 목록에서 고르기",
      qq: "정렬 기준을 받아 <b>허용 목록에 있으면 그대로</b>, 없으면 <b>첫 번째 허용 값</b>을 돌려주세요.",
      src: "function sortColumn(input, allowed) {\n  return input;\n}",
      sol: "function sortColumn(input, allowed) {\n  return allowed.includes(input) ? input : allowed[0];\n}",
      tests: [["sortColumn('name', ['id', 'name'])", "'name'"],
              ["sortColumn('id; DROP TABLE u', ['id', 'name'])", "'id'"],
              ["sortColumn('', ['id', 'name'])", "'id'"]],
      edge: [["sortColumn(undefined, ['id'])", "'id'"]],
      ex: "열 이름은 자리표시자로 넘길 수 없어서, 여기가 인젝션이 남는 마지막 자리입니다. 허용 목록에서 고르게 하면 모르는 글자는 애초에 쿼리에 닿지 못해요.",
    },
    {
      k: "safeJoin · 폴더를 벗어나지 않기",
      qq: "기준 폴더와 파일 이름을 이어 붙이되, <code>..</code> 나 <code>/</code> 로 <b>위로 나가려 하면</b> <code>null</code> 을 돌려주세요.",
      src: "function safeJoin(base, name) {\n  return base + '/' + name;\n}",
      sol: "function safeJoin(base, name) {\n  const n = String(name);\n  if (n.includes('..') || n.includes('/') || n.includes('\\\\')) return null;\n  return base + '/' + n;\n}",
      tests: [["safeJoin('/data', 'a.txt')", "'/data/a.txt'"],
              ["safeJoin('/data', '../etc/passwd')", "null"],
              ["safeJoin('/data', 'sub/a.txt')", "null"]],
      edge: [["safeJoin('/data', '')", "'/data/'"],
             ["safeJoin('/data', '..')", "null"]],
      ex: "이름을 그대로 이어 붙이면 '../../etc/passwd' 로 어디든 갈 수 있습니다. 파일 서버에서 가장 흔한 사고예요. 위로 나가는 글자를 아예 거절하면 그 길이 막힙니다.",
    },
  ],
},
/* ── 인증과 인가 ──────────────────────────────────────────── */
{
  unit: "인증과 인가",
  lesson: "직접 짜 보기 — 누구인지와 무엇을 할 수 있는지",
  th: {
    sum: "**인증**은 누구인지 확인하는 것이고, **인가**는 그 사람이 이 일을 해도 되는지 보는 것이다.",
    body: [
      { h: "둘은 다른 질문이다", t: "로그인했다고 아무 자원이나 볼 수 있는 것은 아니다. 인증만 확인하고 인가를 빼먹으면, 로그인한 누구나 남의 자료를 볼 수 있게 된다 — 실제로 아주 흔한 사고다." },
      { h: "비밀번호는 되돌릴 수 없게 저장한다", t: "그대로 저장하면 저장소가 새는 순간 전부 털린다. 단방향으로 바꿔 저장하고, 사람마다 다른 소금값을 섞어 같은 비밀번호가 같은 값이 되지 않게 한다." },
      { h: "토큰 비교는 시간을 일정하게", t: "글자를 앞에서부터 비교하다 다르면 바로 멈추는 방식은, 몇 글자까지 맞았는지가 **걸린 시간으로 새어 나간다.** 길이와 상관없이 끝까지 비교해야 그 단서가 사라진다." },
      { h: "실패는 뭉뚱그려 알린다", t: "'그런 아이디 없음' 과 '비밀번호 틀림' 을 나눠 알려 주면, 어떤 아이디가 있는지 알아낼 수 있다. 겉으로는 하나로 말하고 기록에만 자세히 남긴다." },
    ],
    code: { c: "if (!user) return deny();          // 인증\nif (post.ownerId !== user.id) return deny();  // 인가", cap: "누구인지와 해도 되는지" },
    key: ["인증과 인가는 다른 질문", "비밀번호는 되돌릴 수 없게", "토큰 비교는 시간을 일정하게"],
  },
  q: [
    {
      k: "canEdit · 로그인만으로는 부족하다",
      qq: "사용자와 글을 받아 <b>수정할 수 있는지</b> 판단하세요. <b>글 주인이거나 관리자</b>일 때만 참입니다.",
      src: "function canEdit(user, post) {\n  return !!user;\n}",
      sol: "function canEdit(user, post) {\n  if (!user) return false;\n  return user.role === 'admin' || post.ownerId === user.id;\n}",
      tests: [["canEdit({ id: 1, role: 'user' }, { ownerId: 1 })", "true"],
              ["canEdit({ id: 2, role: 'user' }, { ownerId: 1 })", "false"],
              ["canEdit({ id: 2, role: 'admin' }, { ownerId: 1 })", "true"]],
      edge: [["canEdit(null, { ownerId: 1 })", "false"],
             ["canEdit({ id: 0, role: 'user' }, { ownerId: 0 })", "true"]],
      ex: "로그인 여부만 보면 로그인한 누구나 남의 글을 고칠 수 있습니다. 인증은 '누구인지', 인가는 '해도 되는지' 예요 — 둘은 다른 질문입니다.",
    },
    {
      k: "safeEqual · 걸린 시간으로 새지 않게",
      qq: "두 비밀 문자열이 같은지 판단하세요. <b>앞부분만 보지 말고 끝까지</b> 견주고, 길이가 다르면 거짓입니다. (끝까지 보는 것은 <b>걸린 시간으로 정보가 새지 않게</b> 하는 뜻도 있습니다.)",
      src: "function safeEqual(a, b) {\n  return a.slice(0, 8) === b.slice(0, 8);\n}",
      sol: "function safeEqual(a, b) {\n  if (a.length !== b.length) return false;\n  let diff = 0;\n  for (let i = 0; i < a.length; i++) {\n    diff |= a.charCodeAt(i) ^ b.charCodeAt(i);\n  }\n  return diff === 0;\n}",
      tests: [["safeEqual('abc', 'abc')", "true"],
              ["safeEqual('secret-token-1', 'secret-token-2')", "false"],
              ["safeEqual('abc', 'ab')", "false"]],
      edge: [["safeEqual('', '')", "true"],
             ["safeEqual('a', 'b')", "false"]],
      ex: "앞 여덟 글자만 보면 뒤가 다른 토큰이 전부 같은 것으로 통과합니다. 그리고 '다르면 바로 멈추는' 방식도 위험해요 — 앞 글자가 맞을수록 오래 걸려서, 공격자가 그 시간 차이로 한 글자씩 맞춰 나갈 수 있습니다. 끝까지 견주고 마지막에 판단하면 두 문제가 함께 사라져요.",
    },
    {
      k: "loginError · 있는 아이디를 알려 주지 않기",
      qq: "사용자 존재 여부와 비밀번호 일치 여부를 받아 <b>사용자에게 보여 줄 메시지</b>를 돌려주세요. 실패는 <b>모두 같은 문구</b>입니다.",
      src: "function loginError(exists, pwOk) {\n  if (!exists) return '없는 아이디입니다';\n  if (!pwOk) return '비밀번호가 틀렸습니다';\n  return null;\n}",
      sol: "function loginError(exists, pwOk) {\n  if (exists && pwOk) return null;\n  return '아이디 또는 비밀번호가 올바르지 않습니다';\n}",
      tests: [["loginError(false, false)", "'아이디 또는 비밀번호가 올바르지 않습니다'"],
              ["loginError(true, false)", "'아이디 또는 비밀번호가 올바르지 않습니다'"],
              ["loginError(true, true)", "null"]],
      edge: [["loginError(false, true)", "'아이디 또는 비밀번호가 올바르지 않습니다'"]],
      ex: "'없는 아이디' 라고 알려 주면, 아이디 목록을 하나씩 넣어 보며 어떤 계정이 있는지 알아낼 수 있습니다. 겉으로는 하나로 말하고, 자세한 이유는 기록에만 남겨요.",
    },
  ],
},
/* ── 암호화와 비밀 관리 ───────────────────────────────────── */
{
  unit: "암호화와 비밀 관리",
  lesson: "직접 짜 보기 — 감출 것과 확인할 것",
  th: {
    sum: "**되돌려 읽어야 하면 암호화**, **같은지만 확인하면 해시**다. 이 둘을 헷갈리면 설계가 무너진다.",
    body: [
      { h: "비밀번호는 되돌릴 필요가 없다", t: "우리가 알아야 할 것은 '입력한 것이 저장된 것과 같은가' 뿐이다. 그래서 되돌릴 수 없는 해시로 저장한다. 되돌릴 수 있게 저장했다면 그것은 언젠가 읽히기 위한 준비다." },
      { h: "소금을 섞는다", t: "같은 비밀번호가 같은 값으로 저장되면, 미리 계산해 둔 표 하나로 여러 계정이 한꺼번에 뚫린다. 사람마다 다른 값을 섞으면 그 표가 쓸모없어진다. 소금은 비밀이 아니라 같이 저장해도 된다." },
      { h: "카드번호는 되돌려야 한다", t: "결제할 때 원래 번호가 필요하면 해시로는 안 된다. 이때는 암호화하고 열쇠를 따로 보관한다. 열쇠를 자료 옆에 두면 암호화한 의미가 없다." },
      { h: "화면에는 일부만 보인다", t: "카드번호나 전화번호는 뒤 네 자리만 보여 주고 나머지는 가린다. 사용자는 자기 것인지 알아볼 수 있고, 화면을 훔쳐본 사람은 아무것도 얻지 못한다." },
    ],
    code: { c: "저장  : hash(salt + password)   // 되돌릴 필요 없다\n결제  : encrypt(cardNo, key)     // 되돌려야 한다\n화면  : ****-****-****-1234", cap: "되돌릴 필요가 있는가로 고른다" },
    key: ["확인만 하면 해시", "소금은 사람마다 다르게", "되돌려야 하면 암호화"],
  },
  q: [
    {
      k: "storageMode · 해시인가 암호화인가",
      qq: "자료 종류를 받아 저장 방식을 정하세요. <code>'password'</code>는 <code>'hash'</code>, <code>'card'</code>·<code>'ssn'</code>은 <code>'encrypt'</code>, 그 밖에는 <code>'plain'</code> 입니다.",
      src: "function storageMode(kind) {\n  return kind === 'password' ? 'hash' : 'plain';\n}",
      sol: "function storageMode(kind) {\n  if (kind === 'password') return 'hash';\n  if (kind === 'card' || kind === 'ssn') return 'encrypt';\n  return 'plain';\n}",
      tests: [["storageMode('password')", "'hash'"],
              ["storageMode('card')", "'encrypt'"],
              ["storageMode('nickname')", "'plain'"]],
      edge: [["storageMode('ssn')", "'encrypt'"],
             ["storageMode('')", "'plain'"]],
      ex: "카드번호를 그대로 저장하면 저장소가 새는 순간 전부 털립니다. 반대로 해시로 저장하면 결제할 때 되돌릴 수 없어요. '되돌릴 필요가 있는가' 가 방식을 정합니다.",
    },
    {
      k: "saltedKey · 사람마다 다른 값이 되게",
      qq: "소금과 비밀번호를 받아 저장할 열쇠를 만들어 주세요. 형식은 <code>소금 + ':' + 뒤집은 비밀번호</code> 입니다(진짜 해시 대신 흉내).",
      src: "function saltedKey(salt, pw) {\n  return pw.split('').reverse().join('');\n}",
      sol: "function saltedKey(salt, pw) {\n  return salt + ':' + pw.split('').reverse().join('');\n}",
      tests: [["saltedKey('s1', 'abc')", "'s1:cba'"],
              ["saltedKey('s2', 'abc')", "'s2:cba'"],
              ["saltedKey('s1', 'abc') === saltedKey('s2', 'abc')", "false"]],
      edge: [["saltedKey('s1', '')", "'s1:'"]],
      ex: "소금을 안 섞으면 같은 비밀번호가 같은 값으로 저장됩니다. 미리 계산해 둔 표 하나로 여러 계정이 한꺼번에 뚫려요. 사람마다 다른 값을 섞으면 그 표가 쓸모없어집니다.",
    },
    {
      k: "maskCard · 뒤 네 자리만 보이기",
      qq: "카드번호를 받아 <b>뒤 네 자리만</b> 남기고 나머지를 <code>*</code> 로 가려 주세요. 네 자리 이하면 <b>전부 가립니다</b>.",
      src: "function maskCard(no) {\n  return '****' + no.slice(-4);\n}",
      sol: "function maskCard(no) {\n  const s = String(no);\n  if (s.length <= 4) return '*'.repeat(s.length);\n  return '*'.repeat(s.length - 4) + s.slice(-4);\n}",
      tests: [["maskCard('1234567812345678')", "'************5678'"],
              ["maskCard('12345')", "'*2345'"],
              ["maskCard('1234')", "'****'"]],
      edge: [["maskCard('')", "''"],
             ["maskCard('12')", "'**'"]],
      ex: "별표를 네 개로 고정하면 16자리 번호가 8자리로 보여 자릿수 정보가 어긋납니다. 그리고 네 자리 이하일 때는 slice(-4) 가 전체를 돌려줘서 아무것도 가려지지 않아요.",
    },
  ],
},
/* ── 접근 통제 ────────────────────────────────────────────── */
{
  unit: "접근 통제 (중급) — IDOR·권한 상승·최소권한",
  lesson: "직접 짜 보기 — 남의 것을 못 보게",
  th: {
    sum: "주소에 적힌 번호만 바꿔 남의 자료를 보는 것이 **IDOR** 다. 막는 방법은 하나 — 매번 확인한다.",
    body: [
      { h: "번호를 감추는 것은 방어가 아니다", t: "번호를 어렵게 만들어도 언젠가 알려진다. 목록 화면에 안 보이게 하는 것도 마찬가지다. **볼 때마다 이 사람 것인지 확인하는 것** 말고는 방법이 없다." },
      { h: "확인은 서버에서 한다", t: "화면에서 버튼을 숨기는 것은 사용자를 위한 배려이지 방어가 아니다. 요청은 화면 없이도 보낼 수 있다. 서버가 매번 확인해야 실제로 막힌다." },
      { h: "권한은 필요한 만큼만", t: "'나중에 필요할지도' 로 권한을 넓게 주면, 그 계정이 뚫렸을 때 피해도 그만큼 넓어진다. 필요한 것만 주고 필요해질 때 더하는 편이 안전하다." },
      { h: "역할은 포함 관계로 정리한다", t: "관리자가 할 수 있는 일을 하나씩 나열하면 언젠가 빠뜨린다. '관리자는 편집자가 할 수 있는 모든 것을 할 수 있다' 처럼 포함 관계로 정하면 빠짐이 없다." },
    ],
    code: { c: "const doc = load(id);\nif (doc.ownerId !== user.id) return deny();   // 매번 확인", cap: "감추지 말고 확인한다" },
    key: ["번호를 감추는 것은 방어가 아니다", "확인은 서버에서 매번", "권한은 필요한 만큼만"],
  },
  q: [
    {
      k: "loadDoc · 남의 것이면 못 준다",
      qq: "문서를 찾아 돌려주되, <b>남의 것이면 <code>null</code></b> 을 돌려주세요. 없는 문서도 <code>null</code> 입니다.",
      src: "function loadDoc(docs, id, user) {\n  return docs.find(d => d.id === id) || null;\n}",
      sol: "function loadDoc(docs, id, user) {\n  const d = docs.find(x => x.id === id);\n  if (!d) return null;\n  return d.ownerId === user.id ? d : null;\n}",
      tests: [["loadDoc([{ id: 1, ownerId: 7 }], 1, { id: 7 }).id", "1"],
              ["loadDoc([{ id: 1, ownerId: 7 }], 1, { id: 8 })", "null"],
              ["loadDoc([{ id: 1, ownerId: 7 }], 2, { id: 7 })", "null"]],
      edge: [["loadDoc([], 1, { id: 7 })", "null"],
             ["loadDoc([{ id: 1, ownerId: 0 }], 1, { id: 0 }).id", "1"]],
      ex: "번호로 찾아 그대로 돌려주면, 주소의 숫자만 바꿔 남의 문서를 볼 수 있습니다. 목록에 안 보이게 해도 소용없어요 — 꺼내는 자리에서 매번 확인해야 합니다.",
    },
    {
      k: "roleAllows · 포함 관계로 정하기",
      qq: "역할과 필요한 권한을 받아 가능한지 판단하세요. <code>admin</code> 은 <code>editor</code> 가 할 수 있는 모든 것을, <code>editor</code> 는 <code>viewer</code> 의 모든 것을 할 수 있습니다.",
      src: "function roleAllows(role, need) {\n  return role === need;\n}",
      sol: "function roleAllows(role, need) {\n  const rank = { viewer: 1, editor: 2, admin: 3 };\n  return (rank[role] || 0) >= (rank[need] || 0);\n}",
      tests: [["roleAllows('admin', 'editor')", "true"],
              ["roleAllows('editor', 'admin')", "false"],
              ["roleAllows('editor', 'viewer')", "true"]],
      edge: [["roleAllows('viewer', 'viewer')", "true"],
             ["roleAllows('없음', 'viewer')", "false"]],
      ex: "역할이 정확히 같을 때만 허용하면, 관리자가 편집자의 일을 못 하게 됩니다. 그래서 권한을 하나씩 다 나열하게 되고, 그러다 언젠가 빠뜨려요. 포함 관계로 정하면 빠짐이 없습니다.",
    },
    {
      k: "grantScopes · 필요한 만큼만 주기",
      qq: "요청한 권한과 그 역할이 가질 수 있는 권한을 받아, <b>둘 다에 있는 것만</b> 돌려주세요. 순서는 요청한 순서입니다.",
      src: "function grantScopes(requested, allowed) {\n  return requested;\n}",
      sol: "function grantScopes(requested, allowed) {\n  return requested.filter(s => allowed.includes(s));\n}",
      tests: [["grantScopes(['read', 'write'], ['read'])", "['read']"],
              ["grantScopes(['read', 'admin'], ['read', 'write'])", "['read']"],
              ["grantScopes(['write', 'read'], ['read', 'write'])", "['write', 'read']"]],
      edge: [["grantScopes([], ['read'])", "[]"],
             ["grantScopes(['admin'], [])", "[]"]],
      ex: "요청한 대로 다 주면, 클라이언트가 admin 을 적어 보내는 것만으로 관리자가 됩니다. 줄 수 있는 것과 겹치는 부분만 주면, 요청이 무엇이든 넘어설 수 없어요.",
    },
  ],
},
/* ── 공격 대응과 운영 보안 ────────────────────────────────── */
{
  unit: "공격 대응과 운영 보안",
  lesson: "직접 짜 보기 — 새기 전에 막고, 샜으면 빨리 안다",
  th: {
    sum: "완벽한 방어는 없다. 그래서 **빨리 알아채고 빨리 되돌리는 것**이 나머지 절반이다.",
    body: [
      { h: "이상한 패턴을 세어 둔다", t: "한 계정에 짧은 시간 안에 실패가 몰리면 대입 공격일 수 있다. 세어 두고 기준을 넘으면 잠그거나 느리게 만든다. 세지 않으면 며칠이 지나도 모른다." },
      { h: "잠글 때는 풀 방법도 함께", t: "잠그기만 하고 푸는 방법을 안 만들면, 공격자가 남의 계정을 일부러 잠가 버리는 공격이 된다. 시간이 지나면 자동으로 풀리게 하는 것이 기본이다." },
      { h: "새어 나간 열쇠는 무효로 만든다", t: "기록에 한 번 들어간 열쇠는 지워도 이미 복제된 곳에 남는다. 지우는 것이 아니라 **무효로 만들고 새로 발급하는 것**이 정답이다." },
      { h: "무엇이 언제 바뀌었는지 남긴다", t: "누가 어떤 권한을 언제 바꿨는지 기록해 두면, 사고가 났을 때 되짚을 수 있다. 이 기록은 고칠 수 없게 두어야 의미가 있다 — 고칠 수 있으면 가장 먼저 고쳐질 기록이다." },
    ],
    code: { c: "if (fails >= 5 && sinceMs < 60000) lock(60000);\n\n// 새면: revoke(old) → issue(new)", cap: "빨리 알고 빨리 되돌린다" },
    key: ["이상한 패턴을 세어 둔다", "잠그면 푸는 방법도", "새면 무효로 만들고 새로 발급"],
  },
  q: [
    {
      k: "shouldLock · 몰린 실패를 알아채기",
      qq: "실패 시각 목록과 지금 시각을 받아, <b>최근 <code>windowMs</code> 안에 <code>limit</code>번 이상</b> 실패했으면 잠그세요.",
      src: "function shouldLock(fails, now, windowMs, limit) {\n  return fails.length >= limit;\n}",
      sol: "function shouldLock(fails, now, windowMs, limit) {\n  return fails.filter(t => now - t < windowMs).length >= limit;\n}",
      tests: [["shouldLock([0, 1, 2, 3, 4], 100000, 60000, 5)", "false"],
              ["shouldLock([95000, 96000, 97000, 98000, 99000], 100000, 60000, 5)", "true"],
              ["shouldLock([99000], 100000, 60000, 5)", "false"]],
      edge: [["shouldLock([], 100000, 60000, 1)", "false"],
             ["shouldLock([99999], 100000, 60000, 1)", "true"]],
      ex: "전체 실패 횟수를 세면 몇 달 전 오타 몇 번으로도 계정이 잠깁니다. 반대로 진짜 공격은 '최근에 몰렸다' 는 모양이라, 구간을 봐야 그 모양이 드러나요.",
    },
    {
      k: "lockLeft · 시간이 지나면 풀리게",
      qq: "잠근 시각·잠금 시간·지금 시각을 받아 <b>남은 잠금 시간</b>을 돌려주세요. 다 지났으면 <code>0</code> 입니다.",
      src: "function lockLeft(lockedAt, lockMs, now) {\n  return lockedAt + lockMs - now;\n}",
      sol: "function lockLeft(lockedAt, lockMs, now) {\n  return Math.max(0, lockedAt + lockMs - now);\n}",
      tests: [["lockLeft(0, 1000, 400)", "600"],
              ["lockLeft(0, 1000, 1000)", "0"],
              ["lockLeft(0, 1000, 5000)", "0"]],
      edge: [["lockLeft(0, 0, 0)", "0"],
             ["lockLeft(100, 1000, 100)", "1000"]],
      ex: "음수를 그대로 돌려주면 '남은 시간 -4초' 같은 값이 화면에 뜨고, 그 값을 참·거짓으로 보는 코드에서는 여전히 잠긴 것으로 읽힙니다. 0으로 잘라 두면 그런 일이 없어요.",
    },
    {
      k: "rotate · 새면 무효로 만들고 새로 발급",
      qq: "열쇠 목록에서 <b>새어 나간 것을 무효로</b> 표시하고 <b>새 열쇠를 하나 더한</b> 목록을 돌려주세요. 원본은 그대로 둡니다.",
      src: "function rotate(keys, leakedId, newKey) {\n  return keys.filter(k => k.id !== leakedId).concat([newKey]);\n}",
      sol: "function rotate(keys, leakedId, newKey) {\n  const out = keys.map(k => (k.id === leakedId ? Object.assign({}, k, { revoked: true }) : k));\n  return out.concat([newKey]);\n}",
      tests: [["rotate([{ id: 'a' }], 'a', { id: 'b' }).length", "2"],
              ["rotate([{ id: 'a' }], 'a', { id: 'b' })[0].revoked", "true"],
              ["rotate([{ id: 'a' }], 'a', { id: 'b' })[1].id", "'b'"]],
      edge: [["(() => { const ks = [{ id: 'a' }]; rotate(ks, 'a', { id: 'b' }); return ks[0].revoked; })()", "undefined"],
             ["rotate([{ id: 'a' }], '없음', { id: 'b' }).length", "2"]],
      ex: "목록에서 지우기만 하면 '그 열쇠가 언제 왜 무효가 됐는지' 가 사라집니다. 나중에 그 열쇠로 들어온 요청을 봐도 무슨 일인지 알 수 없어요. 무효 표시를 남겨 두면 추적이 됩니다.",
    },
  ],
},
];
