/* 시뮬레이션 문항 — 시스템 동작을 코드로 모델링하고 단계를 snap 으로 기록한다.
   하네스: snap(label, value, opt) → FRAMES · RESULT 에 결과 · 검사식은 둘을 읽는다.
   모델은 반드시 동기여야 한다(setTimeout·Promise 는 채점되지 않는다).
   난수도 쓰지 않는다 — 같은 코드가 매번 같은 결과를 내야 채점이 성립한다.

   ref 는 검증용 참조 구현이다(주입하지 않는다). 검증기가 확인하는 것:
     1. 시작 코드(src)로는 통과하지 못한다
     2. ref 로는 모든 검사가 통과한다 — 요건이 실제로 만족 가능하다 */
module.exports = [
/* ── 장애 대응 · 신뢰성 ── */
{ k:"서킷 브레이커", lv:3,
  q:"<b>서킷 브레이커</b>를 모델링하세요. 연속 실패가 <b>3회</b>면 <code>open</code> 으로 열리고, 열린 동안의 호출은 실제로 나가지 않습니다. <b>5틱</b>이 지나면 <code>half</code> 로 바뀌어 시험 호출을 한 번 보내고, 성공하면 <code>closed</code>, 실패하면 다시 <code>open</code> 입니다. 매 틱 <code>snap('t'+t, [나간 호출 수], {state})</code> 로 기록하고 <b>실제로 나간 호출 수</b>를 돌려주세요.",
  src:"/* 1 은 성공, 0 은 실패 — 20틱 분량의 외부 서비스 상태 */\nconst UP = [1,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1];\nconst FAIL_MAX = 3, COOLDOWN = 5;\n\nfunction run() {\n  let state = 'closed', fails = 0, openedAt = -1, sent = 0;\n  for (let t = 0; t < UP.length; t++) {\n    // TODO: 상태에 따라 호출을 내보내거나 건너뛰고, 전이를 처리하세요\n    snap('t' + t, [sent], { state });\n  }\n  return sent;\n}\n\nRESULT = run();",
  ref:"const UP = [1,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1];\nconst FAIL_MAX = 3, COOLDOWN = 5;\n\nfunction run() {\n  let state = 'closed', fails = 0, openedAt = -1, sent = 0;\n  for (let t = 0; t < UP.length; t++) {\n    if (state === 'open' && t - openedAt >= COOLDOWN) state = 'half';\n    if (state === 'open') { snap('t' + t, [sent], { state }); continue; }\n    sent++;\n    const ok = UP[t] === 1;\n    if (state === 'half') {\n      state = ok ? 'closed' : 'open';\n      fails = 0;\n      if (!ok) openedAt = t;\n    } else if (ok) { fails = 0; }\n    else { fails++; if (fails >= FAIL_MAX) { state = 'open'; openedAt = t; } }\n    snap('t' + t, [sent], { state });\n  }\n  return sent;\n}\n\nRESULT = run();",
  tests:[{d:"20틱을 모두 기록한다", js:"FRAMES.length===20"},
         {d:"닫힌 상태로 시작한다", js:"FRAMES[0].opt.state==='closed'"},
         {d:"연속 3회 실패 후 열린다", js:"FRAMES[3].opt.state==='open'"},
         {d:"열린 동안에는 호출이 나가지 않는다", js:"FRAMES[4].value[0]===FRAMES[3].value[0] && FRAMES[5].value[0]===FRAMES[3].value[0]"},
         {d:"쿨다운 뒤 시험 호출로 다시 닫힌다", js:"FRAMES.some((f,i)=>i>5 && f.opt.state==='closed')"},
         {d:"차단 덕분에 실제 호출이 20회보다 적다", js:"RESULT<20 && RESULT>0"}],
  ex:"🎯 서킷 브레이커는 <b>죽은 서비스를 계속 두들기지 않기 위한</b> 장치입니다. 장애 중인 의존성에 요청을 계속 보내면 스레드와 커넥션이 거기 묶여, 그 의존성을 안 쓰는 기능까지 함께 죽습니다.\n💡 <code>open</code> 에서 <b>즉시 실패</b>하는 것이 핵심입니다 — 기다리지 않고 바로 실패해야 호출자가 대체 경로(캐시된 값·기본값·부분 응답)로 넘어갈 수 있습니다.\n⚠️ <code>half</code> 상태가 없으면 한 번 열린 회로가 영영 안 닫히거나, 쿨다운마다 전체 트래픽이 한꺼번에 몰려 다시 무너집니다. <b>한 번만</b> 시험해 보는 것이 그래서 중요합니다.\n🔧 실무에서는 '연속 N회' 보다 '최근 창의 실패율' 로 판단합니다. 트래픽이 적을 때 우연한 실패 3회로 열리는 것을 막으려면 최소 호출 수 조건도 함께 둡니다." },

{ k:"재시도 폭풍과 지터", lv:3,
  q:"동시에 실패한 클라이언트 <b>60개</b>가 재시도합니다. (1) 지터 없이 <b>1초 뒤 일제히</b> 재시도할 때와 (2) 각자 <code>1 + id % 6</code> 초 뒤에 재시도할 때, <b>같은 초에 몰린 최대 요청 수</b>를 각각 구하세요. 초마다 <code>snap</code> 으로 요청 수를 기록하고 <code>[지터없음, 지터있음]</code> 을 돌려주세요.",
  src:"const N = 60, SPREAD = 6;\n\nfunction peak(delayOf) {\n  const at = {};\n  for (let id = 0; id < N; id++) {\n    const s = delayOf(id);\n    at[s] = (at[s] || 0) + 1;\n  }\n  // TODO: 초별 요청 수를 snap 으로 기록하고 최댓값을 돌려주세요\n  return 0;\n}\n\nRESULT = [peak(() => 1), peak((id) => 1 + (id % SPREAD))];",
  ref:"const N = 60, SPREAD = 6;\n\nfunction peak(delayOf) {\n  const at = {};\n  for (let id = 0; id < N; id++) {\n    const s = delayOf(id);\n    at[s] = (at[s] || 0) + 1;\n  }\n  const secs = Object.keys(at).map(Number).sort((a, b) => a - b);\n  let max = 0;\n  secs.forEach((s) => { max = Math.max(max, at[s]); snap('s' + s, [at[s]], { sec: s, n: at[s] }); });\n  return max;\n}\n\nRESULT = [peak(() => 1), peak((id) => 1 + (id % SPREAD))];",
  tests:[{d:"지터가 없으면 60개가 한 초에 몰린다", js:"RESULT[0]===60"},
         {d:"지터를 주면 최대 10개로 흩어진다", js:"RESULT[1]===10"},
         {d:"지터 없는 경우는 한 초만 기록된다", js:"FRAMES.filter(f=>f.opt.n===60).length===1"},
         {d:"지터를 주면 6개 초로 나뉜다", js:"FRAMES.filter(f=>f.opt.n===10).length===6"},
         {d:"두 경우 모두 총 60건이다", js:"FRAMES.reduce((s,f)=>s+f.opt.n,0)===120"}],
  ex:"🎯 지수 백오프만으로는 <b>몰림이 사라지지 않습니다</b>. 같은 시각에 실패한 클라이언트들은 같은 공식을 쓰므로 <b>같은 시각에 다시</b> 옵니다 — 간격만 벌어질 뿐 봉우리 높이는 그대로입니다.\n🔧 지터(무작위 흔들림)를 더해야 실제로 흩어집니다. 이 모델은 결정적이어야 해서 <code>id % 6</code> 으로 대신했지만, 실무에서는 <code>random(0, backoff)</code> 같은 <b>full jitter</b> 를 씁니다.\n⚠️ 재시도 폭풍(retry storm)은 장애를 <b>회복 불가능하게</b> 만듭니다. 서비스가 막 살아나려는 순간 밀린 재시도가 한꺼번에 들어와 다시 넘어뜨리고, 그게 반복됩니다.\n💡 그래서 재시도에는 백오프·지터·상한·서킷 브레이커가 <b>함께</b> 필요합니다. 하나만으로는 부족합니다." },

{ k:"타임아웃 예산 분배", lv:3,
  q:"사용자 요청의 전체 예산이 <b>1000ms</b> 입니다. 내부 호출 A(300ms)·B(400ms)·C(500ms)를 <b>순서대로</b> 부르는데, 각 호출 전에 <b>남은 예산</b>과 비교해 모자라면 <b>보내지 않고</b> 중단합니다. 각 단계를 <code>snap</code> 하고 <b>실제로 보낸 호출 수</b>를 돌려주세요.",
  src:"const BUDGET = 1000;\nconst CALLS = [{ name: 'A', ms: 300 }, { name: 'B', ms: 400 }, { name: 'C', ms: 500 }];\n\nfunction run() {\n  let left = BUDGET, done = 0;\n  // TODO: 남은 예산과 비교하고, 모자라면 보내지 않는다\n  return done;\n}\n\nRESULT = run();",
  ref:"const BUDGET = 1000;\nconst CALLS = [{ name: 'A', ms: 300 }, { name: 'B', ms: 400 }, { name: 'C', ms: 500 }];\n\nfunction run() {\n  let left = BUDGET, done = 0;\n  for (const c of CALLS) {\n    if (c.ms > left) { snap('skip ' + c.name, [left], { name: c.name, sent: false, left }); break; }\n    left -= c.ms;\n    done++;\n    snap('call ' + c.name, [left], { name: c.name, sent: true, left });\n  }\n  return done;\n}\n\nRESULT = run();",
  tests:[{d:"A 와 B 는 보낸다", js:"FRAMES.filter(f=>f.opt.sent).map(f=>f.opt.name).join(',')==='A,B'"},
         {d:"C 는 예산이 모자라 보내지 않는다", js:"FRAMES.some(f=>f.opt.name==='C'&&f.opt.sent===false)"},
         {d:"보낸 호출은 2개다", js:"RESULT===2"},
         {d:"남은 예산이 단조 감소한다", js:"FRAMES.every((f,i)=>i===0||f.opt.left<=FRAMES[i-1].opt.left)"},
         {d:"B 이후 남은 예산은 300ms 다", js:"FRAMES.find(f=>f.opt.name==='B').opt.left===300"}],
  ex:"🎯 각 호출에 <b>고정 타임아웃</b>을 주면 전체 예산이 지켜지지 않습니다. 300+400+500 = 1200ms 라 사용자는 이미 떠난 뒤에 응답이 나옵니다.\n🔧 예산을 <b>전파</b>하세요 — 상위에서 남은 시간을 계산해 하위 호출의 타임아웃으로 넘깁니다. gRPC 의 deadline, HTTP 의 컨텍스트 취소가 이 목적입니다.\n💡 남은 예산으로 끝낼 수 없는 호출은 <b>아예 보내지 않는</b> 것이 맞습니다. 어차피 버릴 응답을 위해 하위 서비스의 커넥션과 CPU 를 쓰는 것은 장애 상황에서 특히 해롭습니다.\n⚠️ 재시도를 넣을 때도 예산 안에서 해야 합니다. '3회 재시도 × 각 1초 타임아웃' 은 조용히 3초를 씁니다." },

{ k:"카나리 배포와 롤백 판단", lv:3,
  q:"카나리 트래픽을 <b>1% → 5% → 25% → 100%</b> 로 올립니다. 각 단계에서 카나리 오류율이 <b>기준(1%)의 3배를 넘으면 즉시 롤백</b>합니다. 단계마다 <code>snap</code> 하고 <b>최종 트래픽 비율</b>을 돌려주세요(롤백하면 0).",
  src:"const STEPS = [1, 5, 25, 100];\nconst BASE = 0.01;\n/* 각 단계에서 관측된 카나리 오류율 */\nconst OBS = [0.008, 0.012, 0.045, 0.01];\n\nfunction run() {\n  let at = 0;\n  // TODO: 단계마다 판정하고, 기준의 3배를 넘으면 롤백\n  return at;\n}\n\nRESULT = run();",
  ref:"const STEPS = [1, 5, 25, 100];\nconst BASE = 0.01;\nconst OBS = [0.008, 0.012, 0.045, 0.01];\n\nfunction run() {\n  let at = 0;\n  for (let i = 0; i < STEPS.length; i++) {\n    const bad = OBS[i] > BASE * 3;\n    snap('step ' + STEPS[i] + '%', [STEPS[i]], { pct: STEPS[i], rate: OBS[i], bad });\n    if (bad) { snap('rollback', [0], { pct: 0, rollback: true }); return 0; }\n    at = STEPS[i];\n  }\n  return at;\n}\n\nRESULT = run();",
  tests:[{d:"25% 단계에서 롤백한다", js:"RESULT===0"},
         {d:"롤백 프레임이 기록된다", js:"FRAMES.some(f=>f.opt.rollback===true)"},
         {d:"1%·5% 단계는 통과한다", js:"FRAMES.filter(f=>f.opt.bad===false).map(f=>f.opt.pct).join(',')==='1,5'"},
         {d:"롤백 후에는 더 진행하지 않는다", js:"!FRAMES.some(f=>f.opt.pct===100)"},
         {d:"롤백 시점 오류율은 기준의 3배를 넘는다", js:"FRAMES.find(f=>f.opt.bad===true).opt.rate>0.03"}],
  ex:"🎯 카나리의 목적은 <b>영향 범위를 좁힌 채 관측하는</b> 것입니다. 1% 에서 문제를 잡으면 99% 의 사용자는 아무것도 못 느낍니다.\n💡 판정 기준은 <b>절대값이 아니라 기준선 대비</b> 여야 합니다. '오류율 3% 이상' 같은 고정값은 서비스마다 다시 정해야 하지만, '기준의 3배' 는 그대로 쓸 수 있습니다.\n⚠️ 트래픽이 적은 단계에서는 <b>통계적으로 판단할 수 없습니다</b>. 1% 로 10건이 흘렀는데 1건 실패한 것을 '오류율 10%' 로 읽으면 멀쩡한 배포를 계속 되돌립니다 — 최소 표본 수 조건이 필요합니다.\n🔧 그리고 롤백은 <b>자동이어야</b> 의미가 있습니다. 사람이 그래프를 보고 판단하는 구조면 새벽 배포에서 아무도 못 잡습니다." },

/* ── DB · 락 ── */
{ k:"데드락 탐지", lv:3,
  q:"두 트랜잭션이 <b>반대 순서</b>로 락을 잡습니다. 대기 그래프를 만들어 <b>순환이 생기는 순간</b>을 찾으세요. 각 락 요청을 <code>snap</code> 하고 <b>데드락이 감지된 단계 번호</b>(0부터)를 돌려주세요. 없으면 -1 입니다.",
  src:"/* [트랜잭션, 원하는 자원] */\nconst REQ = [['T1','A'], ['T2','B'], ['T1','B'], ['T2','A']];\n\nfunction run() {\n  const owner = {};   // 자원 -> 소유 트랜잭션\n  const waits = {};   // 트랜잭션 -> 기다리는 대상 트랜잭션\n  // TODO: 대기 그래프에 순환이 생기면 그 단계 번호를 돌려주세요\n  return -1;\n}\n\nRESULT = run();",
  ref:"const REQ = [['T1','A'], ['T2','B'], ['T1','B'], ['T2','A']];\n\nfunction cycle(waits, from) {\n  const seen = {};\n  let cur = waits[from];\n  while (cur) {\n    if (cur === from) return true;\n    if (seen[cur]) return false;\n    seen[cur] = true;\n    cur = waits[cur];\n  }\n  return false;\n}\n\nfunction run() {\n  const owner = {}, waits = {};\n  for (let i = 0; i < REQ.length; i++) {\n    const tx = REQ[i][0], res = REQ[i][1];\n    if (!owner[res]) {\n      owner[res] = tx;\n      snap(tx + ' → ' + res, [i], { tx, res, got: true });\n    } else {\n      waits[tx] = owner[res];\n      const dead = cycle(waits, tx);\n      snap(tx + ' 대기 ' + res, [i], { tx, res, got: false, waitsFor: owner[res], deadlock: dead });\n      if (dead) return i;\n    }\n  }\n  return -1;\n}\n\nRESULT = run();",
  tests:[{d:"마지막 요청에서 데드락이 감지된다", js:"RESULT===3"},
         {d:"앞의 두 요청은 락을 얻는다", js:"FRAMES.slice(0,2).every(f=>f.opt.got===true)"},
         {d:"세 번째 요청은 T2 를 기다린다", js:"FRAMES[2].opt.got===false && FRAMES[2].opt.waitsFor==='T2'"},
         {d:"세 번째까지는 데드락이 아니다", js:"FRAMES.slice(0,3).every(f=>!f.opt.deadlock)"},
         {d:"네 번째에서 순환이 생긴다", js:"FRAMES[3].opt.deadlock===true"}],
  ex:"🎯 데드락은 <b>두 트랜잭션이 서로가 쥔 것을 기다릴 때</b> 생깁니다. 대기 그래프에 순환이 있으면 데드락이고, DB 는 이걸 감지해 한쪽을 희생시킵니다(victim).\n🔧 애플리케이션 쪽 예방책은 단순합니다 — <b>항상 같은 순서로</b> 락을 잡으면 순환이 만들어지지 않습니다. 계좌 이체에서 id 가 작은 쪽부터 잠그는 관용구가 그것입니다.\n💡 데드락은 재시도로 해결 가능한 오류입니다. 희생된 트랜잭션은 <b>처음부터 다시</b> 실행하면 대개 성공하므로, 트랜잭션 경계 밖에서 재시도할 수 있게 코드를 짜야 합니다.\n⚠️ 데드락이 잦다면 트랜잭션이 <b>너무 길거나 너무 많이 잠그고</b> 있다는 신호입니다. 외부 API 호출을 트랜잭션 안에 두는 것이 대표적인 원인입니다." },

{ k:"커넥션 풀 고갈", lv:3,
  q:"커넥션 풀 크기가 <b>4</b> 입니다. 매 틱 요청 <b>3개</b>가 도착하고 각 요청은 커넥션을 <b>3틱</b> 점유합니다. 10틱 동안 <b>반납 → 도착 → 배정</b> 순서로 진행하며 매 틱 <code>snap</code> 하고 <b>최대 대기열 길이</b>를 돌려주세요.",
  src:"const POOL = 4, ARRIVE = 3, HOLD = 3, TICKS = 10;\n\nfunction run() {\n  let busy = [];      // 각 원소는 남은 점유 틱\n  let queue = 0, maxQ = 0;\n  for (let t = 0; t < TICKS; t++) {\n    // TODO: 반납 → 도착 → 배정 순서로 처리하세요\n    snap('t' + t, [busy.length, queue], { t, busy: busy.length, queue });\n  }\n  return maxQ;\n}\n\nRESULT = run();",
  ref:"const POOL = 4, ARRIVE = 3, HOLD = 3, TICKS = 10;\n\nfunction run() {\n  let busy = [], queue = 0, maxQ = 0;\n  for (let t = 0; t < TICKS; t++) {\n    busy = busy.map((r) => r - 1).filter((r) => r > 0);\n    queue += ARRIVE;\n    while (busy.length < POOL && queue > 0) { busy.push(HOLD); queue--; }\n    maxQ = Math.max(maxQ, queue);\n    snap('t' + t, [busy.length, queue], { t, busy: busy.length, queue });\n  }\n  return maxQ;\n}\n\nRESULT = run();",
  tests:[{d:"10틱을 기록한다", js:"FRAMES.length===10"},
         {d:"사용중 커넥션이 풀 크기를 넘지 않는다", js:"FRAMES.every(f=>f.opt.busy<=4)"},
         {d:"첫 틱에는 대기가 없다", js:"FRAMES[0].opt.queue===0 && FRAMES[0].opt.busy===3"},
         {d:"대기열이 계속 늘어난다 (처리량 부족)", js:"FRAMES[9].opt.queue>FRAMES[2].opt.queue"},
         {d:"최대 대기열은 마지막 틱 값이다", js:"RESULT===FRAMES[9].opt.queue"}],
  ex:"🎯 커넥션 풀은 <b>동시 처리 수의 상한</b>입니다. 도착률이 처리율을 넘으면 대기열은 <b>끝없이 자랍니다</b> — 이 모델은 틱당 3개가 오는데 4개 풀로 3틱씩 잡으니 처리율이 약 1.33/틱 이라 못 따라갑니다.\n⚠️ 이때 나타나는 증상이 '<b>DB 는 한가한데 앱이 느리다</b>' 입니다. 병목이 DB 가 아니라 풀이므로 DB 지표만 보면 원인을 못 찾습니다. 풀 대기 시간을 반드시 지표로 남기세요.\n🔧 해법은 풀을 키우는 것만이 아닙니다. 점유 시간을 줄이는 쪽(쿼리 튜닝·트랜잭션 축소·커넥션 밖에서 외부 호출)이 대개 더 효과적입니다. 풀만 키우면 DB 쪽 커넥션 한계에 부딪힙니다.\n💡 대기열에는 <b>상한과 타임아웃</b>이 필요합니다. 무한 대기는 이미 떠난 사용자를 위해 자원을 계속 쓰는 것입니다." },

{ k:"낙관적 잠금 재시도", lv:2,
  q:"세 요청이 같은 행을 고칩니다. 셋 다 <b>같은 버전을 읽은</b> 상태에서 차례로 <code>WHERE version = ?</code> 갱신을 시도하는데, 버전이 다르면 <b>0행이 갱신되어</b> 다시 읽고 재시도합니다. 각 시도를 <code>snap</code> 하고 <b>총 시도 횟수</b>를 돌려주세요.",
  src:"const REQS = ['A', 'B', 'C'];\n\nfunction run() {\n  let version = 1, tries = 0;\n  const read = {};\n  REQS.forEach((r) => { read[r] = version; });   // 셋 다 같은 버전을 읽었다\n  // TODO: 차례로 갱신을 시도하고, 실패하면 다시 읽어 재시도하세요\n  return tries;\n}\n\nRESULT = run();",
  ref:"const REQS = ['A', 'B', 'C'];\n\nfunction run() {\n  let version = 1, tries = 0;\n  const read = {};\n  REQS.forEach((r) => { read[r] = version; });\n  const pending = REQS.slice();\n  while (pending.length) {\n    const r = pending.shift();\n    tries++;\n    const ok = read[r] === version;\n    snap(r + ' 시도', [tries], { who: r, saw: read[r], version, ok });\n    if (ok) version++;\n    else { read[r] = version; pending.push(r); }\n  }\n  return tries;\n}\n\nRESULT = run();",
  tests:[{d:"총 6번 시도한다", js:"RESULT===6"},
         {d:"첫 시도는 성공한다", js:"FRAMES[0].opt.ok===true"},
         {d:"두 번째와 세 번째는 버전 충돌로 실패한다", js:"FRAMES[1].opt.ok===false && FRAMES[2].opt.ok===false"},
         {d:"최종적으로 세 번 모두 성공한다", js:"FRAMES.filter(f=>f.opt.ok).length===3"},
         {d:"버전이 1에서 시작해 3까지 오른다", js:"FRAMES[0].opt.version===1 && FRAMES[FRAMES.length-1].opt.version===3"}],
  ex:"🎯 낙관적 잠금은 '<b>충돌은 드물다</b>' 고 보고 일단 진행한 뒤 검사합니다. 읽을 때 버전을 같이 읽고 쓸 때 <code>WHERE version = ?</code> 를 붙이면, 그 사이 누가 고쳤을 때 <b>0행이 갱신되어</b> 알 수 있습니다.\n💡 '0행 갱신' 을 <b>확인하지 않는 코드</b>가 이 방식의 가장 흔한 버그입니다. UPDATE 가 성공했다고 넘어가면 변경이 조용히 사라집니다 — 반환된 행 수를 반드시 검사하세요.\n⚠️ 충돌이 잦으면 재시도가 쌓여 오히려 느려집니다. 3개 요청에 6번 시도가 든 것처럼요 — 나중에 온 요청일수록 더 자주 밀립니다. 경합이 심하면 비관적 잠금(<code>SELECT ... FOR UPDATE</code>)이나 원자적 연산(<code>SET n = n - 1 WHERE n &gt;= 1</code>)이 낫습니다.\n🔧 재시도에는 상한이 필요합니다. 무한 재시도는 라이브락이 됩니다." },

/* ── SQL 튜닝 ── */
{ k:"인덱스가 바꾸는 비용", lv:2,
  q:"100만 행 테이블에서 조건에 맞는 <b>50행</b>을 찾습니다. (1) 인덱스가 없으면 <b>전체 스캔</b>(읽은 행 = 100만), (2) 인덱스가 있으면 <b>탐색 깊이 + 매칭 행</b>(= ceil(log2(100만)) + 50) 입니다. 두 계획을 <code>snap</code> 하고 <code>[전체스캔, 인덱스]</code> 읽은 행 수를 돌려주세요.",
  src:"const ROWS = 1000000, MATCH = 50;\n\nfunction run() {\n  // TODO: 두 방식의 읽은 행 수를 계산해 각각 snap 하세요\n  return [0, 0];\n}\n\nRESULT = run();",
  ref:"const ROWS = 1000000, MATCH = 50;\n\nfunction run() {\n  const full = ROWS;\n  const seek = Math.ceil(Math.log2(ROWS)) + MATCH;\n  snap('full scan', [full], { plan: 'full', read: full });\n  snap('index seek', [seek], { plan: 'index', read: seek });\n  return [full, seek];\n}\n\nRESULT = run();",
  tests:[{d:"전체 스캔은 100만 행을 읽는다", js:"RESULT[0]===1000000"},
         {d:"인덱스는 70행만 읽는다", js:"RESULT[1]===70"},
         {d:"두 계획을 순서대로 기록한다", js:"FRAMES.length===2 && FRAMES.map(f=>f.opt.plan).join(',')==='full,index'"},
         {d:"인덱스가 만 배 이상 적게 읽는다", js:"RESULT[0]/RESULT[1]>10000"},
         {d:"인덱스 비용은 탐색 깊이와 매칭 행의 합이다", js:"RESULT[1]===Math.ceil(Math.log2(1000000))+50"}],
  ex:"🎯 인덱스가 주는 것은 '빠름' 이 아니라 <b>읽지 않아도 되는 행</b>입니다. 100만 행 중 50행을 찾는데 100만 행을 훑는 것과 70행만 읽는 것의 차이입니다.\n💡 그래서 인덱스 효과는 <b>선택도</b>에 달려 있습니다. 조건에 맞는 행이 전체의 30% 라면 인덱스로 30만 번 랜덤 접근하는 것보다 전체 스캔이 <b>더 빠릅니다</b> — 옵티마이저가 인덱스를 무시하는 것은 대개 버그가 아니라 판단입니다.\n⚠️ 인덱스는 공짜가 아닙니다. INSERT·UPDATE 마다 함께 갱신되고 디스크를 더 씁니다. '일단 다 걸어 두기' 는 쓰기 성능을 갉아먹습니다.\n🔧 실제로는 EXPLAIN 으로 계획을 확인하세요. 추측이 아니라 <b>옵티마이저가 무엇을 고르는지</b> 봐야 합니다." },

{ k:"N+1 이 만드는 쿼리 수", lv:2,
  q:"주문 <b>200건</b>에 사용자 이름을 붙입니다. (1) 항목마다 조회하면 쿼리가 몇 개인지, (2) id 를 모아 <code>IN</code> 한 번으로 가져오면 몇 개인지 계산하세요(사용자는 중복 포함 <b>50명</b>). 두 방식을 <code>snap</code> 하고 <code>[N+1, 배치]</code> 를 돌려주세요.",
  src:"const ORDERS = 200, USERS = 50;\n\nfunction run() {\n  // TODO: 두 방식의 쿼리 수를 계산해 snap 하세요\n  return [0, 0];\n}\n\nRESULT = run();",
  ref:"const ORDERS = 200, USERS = 50;\n\nfunction run() {\n  const naive = 1 + ORDERS;\n  const batch = 1 + 1;\n  snap('N+1', [naive], { plan: 'n+1', queries: naive });\n  snap('batch IN', [batch], { plan: 'batch', queries: batch, distinct: USERS });\n  return [naive, batch];\n}\n\nRESULT = run();",
  tests:[{d:"N+1 은 쿼리 201개", js:"RESULT[0]===201"},
         {d:"배치는 쿼리 2개", js:"RESULT[1]===2"},
         {d:"두 방식을 모두 기록한다", js:"FRAMES.length===2"},
         {d:"배치가 백 배 이상 적다", js:"RESULT[0]/RESULT[1]>100"},
         {d:"중복 제거된 사용자 수를 알고 있다", js:"FRAMES[1].opt.distinct===50"}],
  ex:"🎯 N+1 의 무서움은 <b>개발 데이터에서 안 보인다</b>는 것입니다. 10건이면 쿼리 11개라 눈치채기 어렵고, 운영 200건이 되면 201개가 됩니다. 페이지 하나에 쿼리 수천 개가 나가는 일이 이렇게 생깁니다.\n🔧 고치는 방법은 <b>id 를 먼저 모아 한 번에</b> 가져오는 것입니다. 중복 id 는 Set 으로 걸러 조회량을 더 줄입니다.\n⚠️ ORM 의 지연 로딩이 이 문제를 <b>코드에서 보이지 않게</b> 만듭니다. <code>orders.map(o =&gt; o.user.name)</code> 한 줄이 쿼리 200개입니다 — eager loading·JOIN FETCH·DataLoader 로 명시해야 합니다.\n💡 발견하는 방법은 하나입니다. <b>요청당 쿼리 수를 세는</b> 것 — 개발 환경에서 임계를 넘으면 경고를 띄우는 팀이 많습니다." },

{ k:"커버링 인덱스", lv:3,
  q:"인덱스로 <b>1000행</b>을 찾은 뒤 각 행의 다른 컬럼을 읽어야 합니다. (1) 일반 인덱스는 <b>행마다 테이블을 한 번 더</b> 찾아갑니다. (2) 커버링 인덱스는 필요한 컬럼이 인덱스 안에 있어 <b>테이블 접근이 0</b> 입니다. 각각 <code>snap</code> 하고 <code>[일반, 커버링]</code> 의 테이블 접근 횟수를 돌려주세요.",
  src:"const MATCH = 1000;\n\nfunction run() {\n  // TODO: 두 경우의 테이블 접근 횟수를 snap 하고 돌려주세요\n  return [0, 0];\n}\n\nRESULT = run();",
  ref:"const MATCH = 1000;\n\nfunction run() {\n  snap('일반 인덱스', [MATCH], { plan: 'lookup', tableHits: MATCH, covering: false });\n  snap('커버링 인덱스', [0], { plan: 'covering', tableHits: 0, covering: true });\n  return [MATCH, 0];\n}\n\nRESULT = run();",
  tests:[{d:"일반 인덱스는 1000번 테이블을 찾아간다", js:"RESULT[0]===1000"},
         {d:"커버링 인덱스는 테이블 접근이 없다", js:"RESULT[1]===0"},
         {d:"두 계획을 모두 기록한다", js:"FRAMES.length===2"},
         {d:"커버링 여부를 표시한다", js:"FRAMES[0].opt.covering===false && FRAMES[1].opt.covering===true"},
         {d:"기록한 값이 테이블 접근 수와 일치한다", js:"FRAMES.every(f=>f.value[0]===f.opt.tableHits)"}],
  ex:"🎯 인덱스를 탔는데도 느린 가장 흔한 이유가 이것입니다. 인덱스는 '어디 있는지' 만 알려 주므로, <b>인덱스에 없는 컬럼</b>을 읽으려면 행마다 테이블로 되돌아가야 합니다(random I/O).\n🔧 <b>커버링 인덱스</b>는 조회에 필요한 컬럼을 인덱스에 함께 넣어 그 왕복을 없앱니다. PostgreSQL 의 <code>INCLUDE</code>, MySQL 은 복합 인덱스 뒤에 컬럼을 덧붙이는 식입니다.\n💡 EXPLAIN 에서 <code>Index Only Scan</code>(PostgreSQL)이나 <code>Using index</code>(MySQL)가 보이면 커버링이 된 것입니다 — <code>Using index condition</code> 과는 다릅니다.\n⚠️ 대가는 인덱스 크기입니다. 컬럼을 많이 넣을수록 인덱스가 커져 캐시 효율이 떨어지고 쓰기가 느려집니다. <b>자주 쓰는 조회 한둘</b>에만 적용하세요." },

/* ── 네트워크 ── */
{ k:"TCP 혼잡 제어", lv:3,
  q:"<b>슬로 스타트 → 혼잡 회피</b>를 모델링하세요. cwnd 는 1에서 시작해 라운드마다 <b>2배</b>가 되고, ssthresh(<b>16</b>) 이상이 되면 <b>1씩</b> 늘어납니다. <b>라운드 9</b>에서 손실이 나면 ssthresh 를 cwnd 의 절반으로 낮추고 cwnd 를 1로 되돌립니다. 12라운드를 <code>snap</code> 하고 <b>최대 cwnd</b> 를 돌려주세요.",
  src:"const ROUNDS = 12, LOSS_AT = 9;\n\nfunction run() {\n  let cwnd = 1, ssthresh = 16, max = 1;\n  for (let r = 0; r < ROUNDS; r++) {\n    // TODO: 손실·슬로스타트·혼잡회피를 처리하고 기록하세요\n    snap('r' + r, [cwnd], { r, cwnd, ssthresh });\n  }\n  return max;\n}\n\nRESULT = run();",
  ref:"const ROUNDS = 12, LOSS_AT = 9;\n\nfunction run() {\n  let cwnd = 1, ssthresh = 16, max = 1;\n  for (let r = 0; r < ROUNDS; r++) {\n    if (r === LOSS_AT) {\n      ssthresh = Math.max(Math.floor(cwnd / 2), 1);\n      cwnd = 1;\n      snap('r' + r + ' 손실', [cwnd], { r, cwnd, ssthresh, loss: true });\n      continue;\n    }\n    max = Math.max(max, cwnd);\n    snap('r' + r, [cwnd], { r, cwnd, ssthresh, phase: cwnd < ssthresh ? 'slow-start' : 'avoid' });\n    cwnd = cwnd < ssthresh ? cwnd * 2 : cwnd + 1;\n  }\n  return max;\n}\n\nRESULT = run();",
  tests:[{d:"12라운드를 기록한다", js:"FRAMES.length===12"},
         {d:"1에서 시작한다", js:"FRAMES[0].opt.cwnd===1"},
         {d:"슬로 스타트에서 2배씩 늘어난다", js:"FRAMES[1].opt.cwnd===2 && FRAMES[2].opt.cwnd===4 && FRAMES[3].opt.cwnd===8"},
         {d:"ssthresh 이후에는 1씩 늘어난다", js:"FRAMES[5].opt.cwnd===FRAMES[4].opt.cwnd+1"},
         {d:"손실 라운드에 cwnd 가 1로 떨어진다", js:"FRAMES[9].opt.loss===true && FRAMES[9].opt.cwnd===1"},
         {d:"손실 후 ssthresh 가 낮아진다", js:"FRAMES[9].opt.ssthresh<FRAMES[8].opt.ssthresh"}],
  ex:"🎯 TCP 는 <b>대역폭을 모르는 채로</b> 시작합니다. 그래서 조금씩 보내며 '어디까지 되는지' 를 탐색하고, 손실이 나면 그게 한계 신호라고 보고 물러섭니다.\n💡 슬로 스타트는 이름과 달리 <b>지수적으로 빠르게</b> 늘어납니다. '느린' 것은 시작점(1 세그먼트)이지 증가 속도가 아닙니다.\n⚠️ 이 동작 때문에 <b>짧은 연결은 대역폭을 못 씁니다</b>. 작은 HTTP 요청은 슬로 스타트 구간에서 끝나 버려 링크가 아무리 빨라도 소용이 없습니다 — 연결 재사용(keep-alive·HTTP/2)이 중요한 이유입니다.\n🔧 손실을 혼잡 신호로 읽는 이 방식은 <b>무선처럼 손실이 잦은 환경에서 오판</b>합니다. BBR 같은 최신 알고리즘이 손실 대신 지연과 대역폭을 직접 재는 이유입니다." },

{ k:"패킷 손실과 재전송 증폭", lv:2,
  q:"패킷 <b>100개</b>를 보냅니다. 손실률이 <b>10%</b> 라 매 라운드 <code>floor(보낸 수 / 10)</code> 개를 잃고, 잃은 것만 다시 보냅니다. 손실이 0이 될 때까지 반복하며 라운드마다 <code>snap</code> 하고 <b>총 전송 횟수</b>를 돌려주세요.",
  src:"const N = 100, EVERY = 10;\n\nfunction run() {\n  let left = N, sent = 0, round = 0;\n  // TODO: 남은 것을 보내고 손실분만 다시 보내기를 반복하세요\n  return sent;\n}\n\nRESULT = run();",
  ref:"const N = 100, EVERY = 10;\n\nfunction run() {\n  let left = N, sent = 0, round = 0;\n  while (left > 0 && round < 20) {\n    sent += left;\n    const lost = Math.floor(left / EVERY);\n    snap('round ' + round, [left, lost], { round, tried: left, lost, sent });\n    left = lost;\n    round++;\n  }\n  return sent;\n}\n\nRESULT = run();",
  tests:[{d:"총 전송은 111회다", js:"RESULT===111"},
         {d:"첫 라운드에 100개를 보내고 10개를 잃는다", js:"FRAMES[0].opt.tried===100 && FRAMES[0].opt.lost===10"},
         {d:"두 번째 라운드는 10개다", js:"FRAMES[1].opt.tried===10 && FRAMES[1].opt.lost===1"},
         {d:"세 번째 라운드에서 손실이 0이 된다", js:"FRAMES[2].opt.tried===1 && FRAMES[2].opt.lost===0"},
         {d:"세 라운드 만에 끝난다", js:"FRAMES.length===3"}],
  ex:"🎯 손실률 10% 는 '10% 더 보내면 된다' 가 아닙니다. 재전송분도 잃으므로 <b>총 전송이 111회</b>가 되고, 손실률이 높아질수록 이 증폭은 급격해집니다.\n⚠️ 진짜 비용은 전송량이 아니라 <b>지연</b>입니다. 각 재전송 라운드마다 최소 한 번의 왕복(RTT)이 더 들어가므로, 손실률 1% 만 되어도 대용량 전송의 완료 시간이 눈에 띄게 늘어납니다.\n💡 그래서 원거리 링크에서는 손실이 대역폭보다 중요합니다 — 1Gbps 회선이라도 손실 2% 면 실효 처리량이 수십 Mbps 로 떨어질 수 있습니다.\n🔧 대책은 재전송을 줄이는 쪽(FEC·패킷 페이싱)과 손실을 혼잡 신호로 오판하지 않는 쪽(BBR)입니다." },

{ k:"로드밸런싱 알고리즘 비교", lv:2,
  q:"요청 <b>9개</b>를 서버 <b>3대</b>에 나눕니다. 처리 비용이 <code>[1,1,5,1,1,5,1,1,5]</code> 로 들쭉날쭉합니다. (1) <b>라운드로빈</b>(<code>i % 3</code>)과 (2) <b>최소 부하</b>(가장 덜 바쁜 서버)로 각각 배정해 <b>최대 서버 부하</b>를 구하고 <code>[RR, LC]</code> 를 돌려주세요.",
  src:"const COST = [1,1,5,1,1,5,1,1,5];\nconst SERVERS = 3;\n\nfunction assign(pick) {\n  const load = new Array(SERVERS).fill(0);\n  COST.forEach((c, i) => {\n    const s = pick(load, i);\n    load[s] += c;\n    snap('req' + i, load.slice(), { req: i, to: s, cost: c });\n  });\n  return Math.max.apply(null, load);\n}\n\nfunction run() {\n  // TODO: 두 가지 배정 전략으로 각각 assign 을 부르세요\n  return [0, 0];\n}\n\nRESULT = run();",
  ref:"const COST = [1,1,5,1,1,5,1,1,5];\nconst SERVERS = 3;\n\nfunction assign(pick) {\n  const load = new Array(SERVERS).fill(0);\n  COST.forEach((c, i) => {\n    const s = pick(load, i);\n    load[s] += c;\n    snap('req' + i, load.slice(), { req: i, to: s, cost: c });\n  });\n  return Math.max.apply(null, load);\n}\n\nfunction run() {\n  const rr = assign(function (load, i) { return i % SERVERS; });\n  const lc = assign(function (load) { return load.indexOf(Math.min.apply(null, load)); });\n  return [rr, lc];\n}\n\nRESULT = run();",
  tests:[{d:"라운드로빈의 최대 부하는 15다", js:"RESULT[0]===15"},
         {d:"최소 부하 방식이 더 고르다", js:"RESULT[1]<RESULT[0]"},
         {d:"두 방식 모두 9개씩 배정한다", js:"FRAMES.length===18"},
         {d:"라운드로빈은 순서대로 돈다", js:"FRAMES.slice(0,3).map(f=>f.opt.to).join(',')==='0,1,2'"},
         {d:"총 비용은 두 방식이 같다 (각 21)", js:"FRAMES.slice(0,9).reduce((s,f)=>s+f.opt.cost,0)===21 && FRAMES.slice(9).reduce((s,f)=>s+f.opt.cost,0)===21"}],
  ex:"🎯 라운드로빈은 <b>요청 수</b>를 고르게 나눌 뿐 <b>부하</b>를 고르게 나누지 않습니다. 이 모델에서는 무거운 요청 3개가 전부 같은 서버로 가서 부하가 15까지 몰립니다.\n💡 최소 부하(least connections)는 지금 덜 바쁜 서버를 고르므로 처리 시간이 들쭉날쭉할 때 훨씬 낫습니다. 요청 비용이 <b>균일하다면</b> 라운드로빈으로 충분하고 더 싸고 예측 가능합니다.\n⚠️ 최소 연결에도 함정이 있습니다. <b>막 추가된 서버</b>는 연결이 0이라 트래픽이 한꺼번에 몰려 워밍업도 못 하고 죽습니다 — slow start 옵션이 그래서 있습니다.\n🔧 응답 시간을 반영하는 방식(EWMA·peak-EWMA)도 있습니다. 연결 수는 같아도 실제로 느린 서버를 피할 수 있습니다." },

/* ── 오케스트레이션 ── */
{ k:"HPA 오토스케일링", lv:3,
  q:"목표 CPU 가 <b>50%</b> 입니다. 매 틱 <code>ceil(현재 파드 × 관측CPU / 목표)</code> 를 원하는 값으로 삼되 <b>최소 2 · 최대 10</b> 이고, <b>확대는 즉시</b> 하지만 <b>축소는 2틱 연속</b> 낮을 때만 합니다. 8틱을 <code>snap</code> 하고 <b>최종 파드 수</b>를 돌려주세요.",
  src:"const TARGET = 50, MIN = 2, MAX = 10;\nconst CPU = [50, 90, 95, 80, 40, 30, 30, 30];\n\nfunction run() {\n  let pods = 2, lowStreak = 0;\n  for (let t = 0; t < CPU.length; t++) {\n    // TODO: 원하는 파드 수를 구하고 확대/축소 규칙을 적용하세요\n    snap('t' + t, [pods], { t, cpu: CPU[t], want: pods, pods });\n  }\n  return pods;\n}\n\nRESULT = run();",
  ref:"const TARGET = 50, MIN = 2, MAX = 10;\nconst CPU = [50, 90, 95, 80, 40, 30, 30, 30];\n\nfunction run() {\n  let pods = 2, lowStreak = 0;\n  for (let t = 0; t < CPU.length; t++) {\n    const want = Math.min(Math.max(Math.ceil((pods * CPU[t]) / TARGET), MIN), MAX);\n    if (want > pods) { pods = want; lowStreak = 0; }\n    else if (want < pods) {\n      lowStreak++;\n      if (lowStreak >= 2) { pods = want; lowStreak = 0; }\n    } else lowStreak = 0;\n    snap('t' + t, [pods], { t, cpu: CPU[t], want, pods });\n  }\n  return pods;\n}\n\nRESULT = run();",
  tests:[{d:"8틱을 기록한다", js:"FRAMES.length===8"},
         {d:"CPU 가 목표와 같으면 그대로다", js:"FRAMES[0].opt.pods===2"},
         {d:"과부하에서 즉시 늘어난다", js:"FRAMES[1].opt.pods>FRAMES[0].opt.pods"},
         {d:"파드 수가 상한 10을 넘지 않는다", js:"FRAMES.every(f=>f.opt.pods<=10)"},
         {d:"축소는 한 틱 만에 일어나지 않는다", js:"FRAMES[4].opt.want<FRAMES[4].opt.pods"},
         {d:"결국 줄어들고 최소치 이상을 유지한다", js:"RESULT<FRAMES[3].opt.pods && RESULT>=2"}],
  ex:"🎯 오토스케일링의 핵심은 <b>확대는 빠르게, 축소는 천천히</b> 입니다. 늦게 늘리면 사용자가 장애를 겪지만, 성급히 줄이면 다음 순간 다시 늘려야 해 진동(flapping)이 생깁니다.\n💡 그래서 쿠버네티스 HPA 에는 축소 안정화 창(<code>stabilizationWindowSeconds</code>, 기본 5분)이 있습니다. 이 모델의 '2틱 연속' 이 그 역할입니다.\n⚠️ CPU 기준 스케일링은 <b>CPU 가 병목일 때만</b> 맞습니다. 외부 API 를 기다리는 워크로드는 CPU 가 낮은 채로 응답이 느려지므로, 큐 길이나 동시 요청 수 같은 지표로 스케일해야 합니다.\n🔧 그리고 파드가 늘어나도 <b>DB 커넥션·외부 API 한도</b>는 그대로입니다. 앱만 늘리면 병목이 아래로 옮겨갈 뿐입니다." },

{ k:"노드 드레인과 PDB", lv:3,
  q:"파드 <b>5개</b>가 노드 3대에 <code>[2,2,1]</code> 로 떠 있습니다. 노드를 순서대로 비우는데 <b>PodDisruptionBudget</b> 이 '<b>최소 4개는 살아 있어야 한다</b>' 고 요구합니다(파드는 다시 뜨지 않는다고 가정). 노드마다 축출 가능 여부를 <code>snap</code> 하고 <b>실제로 비운 노드 수</b>를 돌려주세요.",
  src:"const NODES = [2, 2, 1];\nconst MIN_AVAILABLE = 4;\n\nfunction run() {\n  let alive = NODES.reduce((a, b) => a + b, 0);\n  let drained = 0;\n  // TODO: 노드마다 비운 뒤 남는 파드 수를 계산해 판정하세요\n  return drained;\n}\n\nRESULT = run();",
  ref:"const NODES = [2, 2, 1];\nconst MIN_AVAILABLE = 4;\n\nfunction run() {\n  let alive = NODES.reduce((a, b) => a + b, 0);\n  let drained = 0;\n  NODES.forEach(function (n, i) {\n    const after = alive - n;\n    const allowed = after >= MIN_AVAILABLE;\n    snap('node' + i, [alive, n], { node: i, pods: n, after, allowed });\n    if (allowed) { alive = after; drained++; }\n  });\n  return drained;\n}\n\nRESULT = run();",
  tests:[{d:"세 노드를 모두 시도한다", js:"FRAMES.length===3"},
         {d:"파드 2개짜리 노드는 비울 수 없다", js:"FRAMES[0].opt.allowed===false"},
         {d:"파드 1개짜리 노드는 비울 수 있다", js:"FRAMES[2].opt.allowed===true"},
         {d:"비운 노드는 1개다", js:"RESULT===1"},
         {d:"허용된 축출은 최소치를 지킨다", js:"FRAMES.every(f=>!f.opt.allowed||f.opt.after>=4)"}],
  ex:"🎯 PDB 는 '<b>자발적 중단</b>(노드 업그레이드·드레인) 중에도 이만큼은 살아 있어야 한다' 는 선언입니다. 이게 없으면 클러스터 업그레이드가 서비스 전체를 한꺼번에 내릴 수 있습니다.\n⚠️ 반대 함정도 있습니다. PDB 를 너무 빡빡하게 잡으면 <b>드레인이 영원히 막혀</b> 노드 업그레이드가 진행되지 않습니다. 이 모델에서 3개 노드 중 1개만 비울 수 있는 것처럼요.\n💡 그래서 파드를 노드에 <b>고르게 흩뿌리는</b> 것(<code>topologySpreadConstraints</code>)이 PDB 와 짝을 이룹니다. 한 노드에 몰려 있으면 그 노드를 못 비웁니다.\n🔧 PDB 는 자발적 중단만 막습니다 — 노드가 갑자기 죽는 <b>비자발적 중단</b>은 못 막습니다. 그건 복제 수와 여러 영역 분산으로 대비해야 합니다." },

{ k:"백프레셔와 큐 상한", lv:3,
  q:"큐 상한이 <b>20</b> 입니다. 매 틱 도착 <b>8건</b>, 워커 처리 <b>5건</b> 이고, 큐가 가득 차면 새 요청은 <b>즉시 거절</b>합니다. <b>처리 → 도착</b> 순서로 10틱을 <code>snap</code> 하고 <code>[처리 건수, 거절 건수]</code> 를 돌려주세요.",
  src:"const CAP = 20, ARRIVE = 8, RATE = 5, TICKS = 10;\n\nfunction run() {\n  let q = 0, done = 0, rejected = 0;\n  for (let t = 0; t < TICKS; t++) {\n    // TODO: 처리 → 도착(상한 초과분은 거절) 순서로 진행하세요\n    snap('t' + t, [q], { t, q, done, rejected });\n  }\n  return [done, rejected];\n}\n\nRESULT = run();",
  ref:"const CAP = 20, ARRIVE = 8, RATE = 5, TICKS = 10;\n\nfunction run() {\n  let q = 0, done = 0, rejected = 0;\n  for (let t = 0; t < TICKS; t++) {\n    const take = Math.min(q, RATE);\n    q -= take; done += take;\n    const room = CAP - q;\n    const accept = Math.min(ARRIVE, room);\n    q += accept; rejected += ARRIVE - accept;\n    snap('t' + t, [q], { t, q, done, rejected, accepted: accept });\n  }\n  return [done, rejected];\n}\n\nRESULT = run();",
  tests:[{d:"10틱을 기록한다", js:"FRAMES.length===10"},
         {d:"큐가 상한을 넘지 않는다", js:"FRAMES.every(f=>f.opt.q<=20)"},
         {d:"처음에는 거절이 없다", js:"FRAMES[0].opt.rejected===0"},
         {d:"결국 거절이 생긴다", js:"RESULT[1]>0"},
         {d:"누적 처리량이 틱당 5를 넘지 않는다", js:"FRAMES.every((f,i)=>f.opt.done<=(i+1)*5)"},
         {d:"처리 + 거절 + 큐 잔량이 도착 총량 80과 같다", js:"RESULT[0]+RESULT[1]+FRAMES[9].opt.q===80"}],
  ex:"🎯 도착률이 처리율을 넘으면 큐는 <b>끝없이 자랍니다</b>. 상한이 없으면 메모리를 다 쓰고 프로세스가 죽거나, 대기 시간이 몇 분으로 늘어 이미 떠난 사용자를 위해 계속 일하게 됩니다.\n🔧 백프레셔는 '<b>못 받겠다고 빨리 말하는</b>' 것입니다. 상한에서 즉시 429 를 주면 클라이언트가 백오프하거나 대체 경로로 갈 수 있습니다 — 받아 놓고 늦게 실패하는 것보다 훨씬 낫습니다.\n💡 거절이 생긴다는 것은 <b>용량이 부족하다는 사실</b>이 드러난 것입니다. 무한 큐는 그 사실을 지연 뒤로 숨길 뿐 해결하지 않습니다.\n⚠️ 큐 길이만 보고 워커를 늘리면 병목이 DB 로 옮겨갈 수 있습니다. 큐는 <b>순간적인 몰림</b>을 흡수하는 장치이지 만성적인 용량 부족의 해법이 아닙니다." },
];
