/* 시뮬레이션 2차 — 성능·데이터·보안의 '숫자로 봐야 납득되는' 현상들.
   하네스: snap(label, value, opt) → FRAMES · RESULT · 검사식은 둘을 읽는다.
   동기 실행만, 난수·시각 금지(같은 코드가 매번 같은 결과를 내야 채점이 성립한다).
   ref 는 검증용 참조 구현이며 주입하지 않는다. */
module.exports = [
/* ── 성능과 대기열 ── */
{ k:"큐 대기 시간과 이용률", lv:3,
  q:"단일 서버에 <b>10초 동안</b> 요청이 들어옵니다. 처리 시간은 1건당 <b>1초</b> 고정이고, 도착은 <code>ARR</code> 배열(초별 도착 건수)입니다. 매 초 <code>snap('t'+t, [대기열 길이], {t, queue, done})</code> 으로 기록하고 <b>[처리 완료 수, 최대 대기열 길이]</b> 를 돌려주세요. 서버는 초당 1건만 처리합니다.",
  src:"/* 초별 도착 건수 — 앞 5초는 과부하, 뒤 5초는 한산 */\nconst ARR = [3,3,3,0,0,0,0,0,0,0];\n\nfunction run() {\n  let queue = 0, done = 0, peak = 0;\n  for (let t = 0; t < ARR.length; t++) {\n    // TODO: 도착을 큐에 넣고, 초당 1건 처리하고, snap 으로 기록하세요\n  }\n  return [done, peak];\n}\n\nRESULT = run();",
  ref:"const ARR = [3,3,3,0,0,0,0,0,0,0];\n\nfunction run() {\n  let queue = 0, done = 0, peak = 0;\n  for (let t = 0; t < ARR.length; t++) {\n    queue += ARR[t];\n    if (queue > peak) peak = queue;\n    if (queue > 0) { queue--; done++; }\n    snap('t' + t, [queue], { t, queue, done });\n  }\n  return [done, peak];\n}\n\nRESULT = run();",
  tests:[{d:"10초를 모두 기록한다", js:"FRAMES.length===10"},
         {d:"도착 9건을 모두 처리한다", js:"RESULT[0]===9"},
         {d:"최대 대기열은 7이다", js:"RESULT[1]===7"},
         {d:"과부하 구간에서 대기열이 계속 자란다", js:"FRAMES[0].opt.queue<FRAMES[1].opt.queue && FRAMES[1].opt.queue<FRAMES[2].opt.queue"},
         {d:"한산해진 뒤 대기열이 줄어든다", js:"FRAMES[9].opt.queue<FRAMES[2].opt.queue"},
         {d:"마지막에 대기열이 비었다", js:"FRAMES[8].opt.queue===0"}],
  ex:"🎯 도착률이 처리율을 <b>잠깐만</b> 넘어도 대기열은 그 차이만큼 <b>쌓입니다</b>. 3초 동안 초당 2건씩 초과 도착한 것이 대기열 6~7건이 되고, 그만큼의 시간이 <b>모든 후속 요청의 지연</b>에 더해집니다.\n💡 대기행렬 이론의 핵심은 '<b>이용률이 100%에 가까워지면 대기 시간이 폭발한다</b>' 는 것입니다 — 70%에서는 견딜 만하다가 90%를 넘으면 급격히 나빠집니다. 평균 이용률이 낮아도 <b>버스트</b>가 있으면 같은 일이 벌어집니다.\n⚠️ 그래서 'CPU 사용률 50%인데 왜 느리냐' 는 질문이 성립합니다 — 평균은 낮아도 순간 도착이 몰리면 큐가 생깁니다. 지연을 볼 때는 평균이 아니라 <b>p99</b> 를 봐야 하는 이유입니다.\n🔧 해법은 셋 중 하나입니다 — <b>처리율을 올리거나</b>(최적화·수평 확장), <b>도착을 고르게 하거나</b>(레이트 리밋·큐잉), <b>넘치면 버립니다</b>(load shedding). 무한정 쌓이게 두는 것이 가장 나쁜 선택입니다." },

{ k:"캐시 적중률과 평균 지연", lv:3,
  q:"캐시 적중률에 따른 <b>평균 응답 시간</b>을 계산하세요. 적중은 <b>1ms</b>, 미스는 <b>50ms</b> 입니다. 적중률 <code>[0, 0.5, 0.8, 0.9, 0.95, 0.99]</code> 각각에 대해 <code>snap('h'+율, [평균ms], {hit, avg})</code> 로 기록하고, <b>[적중률 0.9의 평균, 0.99의 평균]</b> 을 돌려주세요.",
  src:"const HIT_MS = 1, MISS_MS = 50;\nconst RATES = [0, 0.5, 0.8, 0.9, 0.95, 0.99];\n\nfunction run() {\n  const got = {};\n  // TODO: 각 적중률의 평균 지연을 계산해 snap 으로 기록하세요\n  return [got[0.9], got[0.99]];\n}\n\nRESULT = run();",
  ref:"const HIT_MS = 1, MISS_MS = 50;\nconst RATES = [0, 0.5, 0.8, 0.9, 0.95, 0.99];\n\nfunction run() {\n  const got = {};\n  RATES.forEach((hit) => {\n    const avg = hit * HIT_MS + (1 - hit) * MISS_MS;\n    got[hit] = Math.round(avg * 100) / 100;\n    snap('h' + hit, [got[hit]], { hit, avg: got[hit] });\n  });\n  return [got[0.9], got[0.99]];\n}\n\nRESULT = run();",
  tests:[{d:"여섯 구간을 모두 기록한다", js:"FRAMES.length===6"},
         {d:"적중률 0 이면 미스 비용 그대로다", js:"FRAMES[0].opt.avg===50"},
         {d:"적중률 0.9 의 평균은 5.9ms 다", js:"RESULT[0]===5.9"},
         {d:"적중률 0.99 의 평균은 1.49ms 다", js:"RESULT[1]===1.49"},
         {d:"적중률이 오를수록 평균이 낮아진다", js:"FRAMES.every((f,i)=>i===0||f.opt.avg<FRAMES[i-1].opt.avg)"},
         {d:"0.9→0.95 개선폭이 0.5→0.8 개선폭보다 작다", js:"(FRAMES[3].opt.avg-FRAMES[4].opt.avg) < (FRAMES[1].opt.avg-FRAMES[2].opt.avg)"}],
  ex:"🎯 평균 지연은 <code>적중률×적중비용 + (1−적중률)×미스비용</code> 입니다. 미스가 50배 비싸면 <b>미스 쪽이 평균을 지배합니다</b> — 적중률 90%에서도 평균의 83%가 나머지 10% 미스에서 나옵니다.\n💡 그래서 캐시 개선은 <b>수익 체감</b>입니다. 50%→80%는 평균을 25.5ms 에서 10.8ms 로 크게 줄이지만, 90%→95%는 5.9ms 에서 3.45ms 로 줄일 뿐입니다. '적중률 1% 더' 를 위한 노력의 가치는 <b>현재 적중률에 달려</b> 있습니다.\n⚠️ 반대로 <b>미스 비용을 줄이는 것</b>이 더 효과적일 때가 많습니다. 미스가 50ms 가 아니라 10ms 라면 같은 90% 적중률에서 평균이 1.9ms 입니다 — 인덱스 하나가 캐시 튜닝보다 나은 경우입니다.\n🔧 이 계산은 <b>평균</b>일 뿐입니다. 사용자가 체감하는 것은 p99 이고, 거기서는 미스가 사실상 100%입니다 — 캐시는 평균을 개선하지만 <b>꼬리 지연은 미스 비용이 그대로</b> 결정합니다." },

{ k:"연결 풀 고갈", lv:3,
  q:"커넥션 풀 크기 <b>5</b>에 요청이 몰립니다. 각 요청은 커넥션을 <b>2틱</b> 점유합니다. 도착 배열 <code>ARR</code>(틱별 도착 수)을 처리하며 매 틱 <code>snap('t'+t, [사용중], {t, busy, waiting, rejected})</code> 로 기록하세요. 대기열이 <b>3을 넘으면 거절</b>합니다. <b>[총 처리, 총 거절]</b> 을 돌려주세요.",
  src:"const POOL = 5, HOLD = 2, MAX_WAIT = 3;\nconst ARR = [8,8,4,0,0,0,0,0];\n\nfunction run() {\n  const busyUntil = [];\n  let waiting = 0, served = 0, rejected = 0;\n  for (let t = 0; t < ARR.length; t++) {\n    // TODO: 반납 → (여유 있으면 즉시 배정, 아니면 대기, 대기도 꽉 차면 거절) → snap\n  }\n  return [served, rejected];\n}\n\nRESULT = run();",
  ref:"const POOL = 5, HOLD = 2, MAX_WAIT = 3;\nconst ARR = [8,8,4,0,0,0,0,0];\n\nfunction run() {\n  let busyUntil = [];\n  let waiting = 0, served = 0, rejected = 0;\n  for (let t = 0; t < ARR.length; t++) {\n    busyUntil = busyUntil.filter((u) => u > t);\n    while (waiting > 0 && busyUntil.length < POOL) { busyUntil.push(t + HOLD); waiting--; served++; }\n    for (let i = 0; i < ARR[t]; i++) {\n      if (busyUntil.length < POOL) { busyUntil.push(t + HOLD); served++; }\n      else if (waiting < MAX_WAIT) { waiting++; }\n      else { rejected++; }\n    }\n    snap('t' + t, [busyUntil.length], { t, busy: busyUntil.length, waiting, rejected });\n  }\n  return [served, rejected];\n}\n\nRESULT = run();",
  tests:[{d:"8틱을 모두 기록한다", js:"FRAMES.length===8"},
         {d:"사용 중 커넥션이 풀 크기를 넘지 않는다", js:"FRAMES.every(f=>f.opt.busy<=5)"},
         {d:"과부하 구간에서 풀이 가득 찬다", js:"FRAMES.some(f=>f.opt.busy===5)"},
         {d:"거절이 발생한다", js:"RESULT[1]>0"},
         {d:"거절은 한 번 늘면 줄지 않는다", js:"FRAMES.every((f,i)=>i===0||f.opt.rejected>=FRAMES[i-1].opt.rejected)"},
         {d:"한산해진 뒤 대기열이 비워진다", js:"FRAMES[7].opt.waiting===0"}],
  ex:"🎯 커넥션 풀은 <b>동시성의 상한</b>입니다 — 넘치는 요청은 기다리거나 거절됩니다. 이 모델에서 보이는 것은 '풀이 가득 찬 순간부터 <b>대기가 지연에 그대로 더해진다</b>' 는 사실입니다.\n💡 대기열에 <b>상한</b>을 두는 것이 중요합니다. 무한 대기열은 메모리를 먹고, 이미 떠난 사용자의 요청까지 처리하게 만듭니다 — <b>빠른 거절</b>이 느린 성공보다 나은 상황이 실제로 있습니다.\n⚠️ 풀을 무작정 키우는 것은 해법이 아닙니다 — 커넥션이 늘면 DB 쪽 컨텍스트 스위칭과 락 경합이 늘어 <b>전체 처리량이 오히려 떨어집니다</b>. HikariCP 문서가 '작은 풀이 빠르다' 를 강조하는 이유입니다.\n🔧 진짜 원인은 대개 <b>점유 시간</b>입니다. 쿼리를 100ms 에서 10ms 로 줄이면 같은 풀로 10배를 처리합니다 — 풀 크기보다 <b>커넥션을 얼마나 오래 잡는가</b>를 먼저 보세요." },

{ k:"N+1 쿼리의 비용", lv:2,
  q:"게시글 <b>20개</b>와 각 글의 작성자를 불러옵니다. (1) <b>N+1</b> 방식은 글 목록 1회 + 글마다 작성자 1회, (2) <b>일괄 조회</b>는 글 목록 1회 + 작성자 IN 절 1회입니다. 쿼리당 <b>5ms</b> 로 계산해 각 방식의 쿼리 수와 총 시간을 <code>snap</code> 하고 <b>[N+1 쿼리 수, 일괄 쿼리 수, 절약된 ms]</b> 를 돌려주세요.",
  src:"const POSTS = 20, MS = 5;\n\nfunction run() {\n  // TODO: 두 방식의 쿼리 수와 시간을 계산해 snap 으로 기록하세요\n  return [0, 0, 0];\n}\n\nRESULT = run();",
  ref:"const POSTS = 20, MS = 5;\n\nfunction run() {\n  const nPlus1 = 1 + POSTS;\n  const batched = 2;\n  snap('n+1', [nPlus1], { kind: 'n+1', queries: nPlus1, ms: nPlus1 * MS });\n  snap('batched', [batched], { kind: 'batched', queries: batched, ms: batched * MS });\n  return [nPlus1, batched, (nPlus1 - batched) * MS];\n}\n\nRESULT = run();",
  tests:[{d:"두 방식을 모두 기록한다", js:"FRAMES.length===2"},
         {d:"N+1 은 21회 쿼리한다", js:"RESULT[0]===21"},
         {d:"일괄 조회는 2회로 끝난다", js:"RESULT[1]===2"},
         {d:"95ms 를 아낀다", js:"RESULT[2]===95"},
         {d:"기록된 시간이 쿼리 수에 비례한다", js:"FRAMES.every(f=>f.opt.ms===f.opt.queries*5)"}],
  ex:"🎯 N+1 은 <b>코드에서는 안 보이는</b> 문제입니다. ORM 으로 <code>post.author.name</code> 을 쓰면 자연스러운 객체 접근처럼 보이지만, 뒤에서는 <b>글 하나마다 쿼리 한 번</b>이 나갑니다.\n💡 비용이 <b>글 개수에 비례</b>한다는 것이 핵심입니다 — 개발 환경의 20건에서는 100ms 라 눈치채지 못하고, 운영의 500건에서 2.5초가 됩니다. <b>데이터가 늘면서 나빠지는</b> 종류의 버그입니다.\n⚠️ 진짜 비용은 쿼리 실행 시간보다 <b>왕복 지연</b>입니다. DB 가 같은 랙에 있으면 1ms 지만 다른 리전이면 50ms — 같은 코드가 배포 환경에 따라 50배 차이 납니다.\n🔧 해법은 <b>미리 함께 가져오기</b>입니다(eager loading·JOIN·DataLoader 의 배치). 탐지는 쉽습니다 — 요청당 쿼리 수를 로그로 남기고 임계치를 넘으면 경고하세요. 개발 환경에서 쿼리 카운터를 켜 두는 것만으로 대부분 잡힙니다." },

/* ── 데이터 시스템 ── */
{ k:"인덱스가 있는 조회와 없는 조회", lv:2,
  q:"정렬된 <b>1,000,000</b> 행에서 값을 찾습니다. (1) 순차 스캔은 최악 <b>n</b> 번, (2) B-트리 인덱스는 <b>log₂n</b> 을 올림한 횟수만큼 비교합니다. 두 방식의 비교 횟수를 <code>snap</code> 하고 <b>[스캔 횟수, 인덱스 횟수, 배수(내림)]</b> 를 돌려주세요.",
  src:"const ROWS = 1000000;\n\nfunction run() {\n  // TODO: 두 방식의 비교 횟수를 계산해 snap 으로 기록하세요\n  return [0, 0, 0];\n}\n\nRESULT = run();",
  ref:"const ROWS = 1000000;\n\nfunction run() {\n  const scan = ROWS;\n  const idx = Math.ceil(Math.log2(ROWS));\n  snap('scan', [scan], { kind: 'scan', ops: scan });\n  snap('index', [idx], { kind: 'index', ops: idx });\n  return [scan, idx, Math.floor(scan / idx)];\n}\n\nRESULT = run();",
  tests:[{d:"두 방식을 모두 기록한다", js:"FRAMES.length===2"},
         {d:"순차 스캔은 100만 번이다", js:"RESULT[0]===1000000"},
         {d:"인덱스는 20번이면 충분하다", js:"RESULT[1]===20"},
         {d:"5만 배 차이가 난다", js:"RESULT[2]===50000"},
         {d:"인덱스 비용이 스캔보다 훨씬 작다", js:"FRAMES[1].opt.ops < FRAMES[0].opt.ops / 1000"}],
  ex:"🎯 <b>log₂(100만) ≈ 20</b> — 이 숫자가 인덱스의 전부입니다. 데이터가 100배 늘어도 비교는 7번 늘 뿐이라, 인덱스는 <b>규모가 커질수록 더 큰 차이</b>를 만듭니다.\n💡 그래서 개발 데이터 1,000행에서는 인덱스 유무가 안 보입니다(10 vs 1000). 운영에서 갑자기 느려지는 쿼리는 대개 '<b>원래 인덱스가 없었는데 티가 안 났던</b>' 것입니다.\n⚠️ 인덱스는 공짜가 아닙니다 — <b>쓰기마다 갱신</b>되고 저장 공간을 씁니다. 인덱스가 10개면 INSERT 하나가 11번의 쓰기입니다. '일단 다 걸자' 는 읽기를 위해 쓰기를 희생하는 결정임을 알고 해야 합니다.\n🔧 그리고 인덱스가 있어도 <b>쓰이지 않는</b> 경우가 많습니다 — 컬럼에 함수를 씌우거나(<code>DATE(ts)=</code>), 앞자리 와일드카드(<code>LIKE '%x'</code>), 타입 불일치가 대표적입니다. <code>EXPLAIN</code> 으로 실제 사용 여부를 확인하는 것이 유일한 확인법입니다." },

{ k:"복제 지연과 읽기 일관성", lv:3,
  q:"쓰기는 리더에, 읽기는 <b>2틱 지연</b>되는 팔로워에서 이뤄집니다. 사용자가 <b>t=0 에 쓰고 t=1 에 읽으면</b> 옛 값을 봅니다. 8틱 동안 <code>OPS</code>(<code>{t, kind, val}</code>)를 처리하며 <code>snap</code> 으로 리더·팔로워 값을 기록하고, <b>[읽기 중 옛 값을 본 횟수, 마지막 팔로워 값]</b> 을 돌려주세요.",
  src:"const LAG = 2;\nconst OPS = [{t:0,kind:'w',val:1},{t:1,kind:'r'},{t:2,kind:'w',val:2},{t:3,kind:'r'},{t:5,kind:'r'},{t:7,kind:'r'}];\n\nfunction run() {\n  const history = [{ at: -1, val: 0 }];\n  let stale = 0, follower = 0;\n  for (let t = 0; t < 8; t++) {\n    // TODO: 쓰기는 history 에, 읽기는 t-LAG 시점의 값으로\n  }\n  return [stale, follower];\n}\n\nRESULT = run();",
  ref:"const LAG = 2;\nconst OPS = [{t:0,kind:'w',val:1},{t:1,kind:'r'},{t:2,kind:'w',val:2},{t:3,kind:'r'},{t:5,kind:'r'},{t:7,kind:'r'}];\n\nfunction run() {\n  const history = [{ at: -1, val: 0 }];\n  let stale = 0, follower = 0, leader = 0;\n  for (let t = 0; t < 8; t++) {\n    const op = OPS.find((o) => o.t === t);\n    if (op && op.kind === 'w') { leader = op.val; history.push({ at: t, val: op.val }); }\n    const visible = history.filter((h) => h.at <= t - LAG).pop();\n    follower = visible ? visible.val : 0;\n    if (op && op.kind === 'r' && follower !== leader) stale++;\n    snap('t' + t, [leader, follower], { t, leader, follower, read: !!(op && op.kind === 'r') });\n  }\n  return [stale, follower];\n}\n\nRESULT = run();",
  tests:[{d:"8틱을 모두 기록한다", js:"FRAMES.length===8"},
         {d:"쓰기 직후 팔로워는 아직 옛 값이다", js:"FRAMES[0].opt.leader===1 && FRAMES[0].opt.follower===0"},
         {d:"지연이 지나면 팔로워가 따라잡는다", js:"FRAMES[2].opt.follower===1"},
         {d:"옛 값을 본 읽기가 2회 있다", js:"RESULT[0]===2"},
         {d:"마지막에는 두 값이 같아진다", js:"FRAMES[7].opt.leader===FRAMES[7].opt.follower"},
         {d:"팔로워 값은 되돌아가지 않는다", js:"FRAMES.every((f,i)=>i===0||f.opt.follower>=FRAMES[i-1].opt.follower)"}],
  ex:"🎯 읽기 부하를 팔로워로 분산하면 <b>복제 지연만큼 과거를 봅니다</b>. '방금 저장했는데 목록에 없다' 는 사용자 신고의 가장 흔한 원인이고, 코드에는 아무 문제가 없습니다.\n💡 이것이 <b>최종적 일관성</b>입니다 — 언젠가는 같아지지만 그 '언젠가' 동안 사용자는 자기 쓰기를 못 봅니다. 특히 <b>자기가 쓴 것을 자기가 읽을 때</b>(read-your-writes) 가장 이상하게 느껴집니다.\n⚠️ 해법은 상황마다 다릅니다 — 쓴 직후 일정 시간은 <b>리더에서 읽거나</b>, 세션에 마지막 쓰기 위치(LSN)를 담아 <b>그 이상 따라잡은 복제본</b>에서만 읽거나, UI 에서 낙관적으로 먼저 보여 줍니다.\n🔧 복제 지연은 평소 밀리초지만 <b>대량 쓰기·긴 트랜잭션·네트워크 문제</b>에서 초 단위로 튑니다. 지연을 지표로 감시하고 임계치를 넘으면 읽기를 리더로 되돌리는 자동 전환이 실전의 방어선입니다." },

{ k:"샤딩과 핫 파티션", lv:3,
  q:"4개 샤드에 <b>키 해시 % 4</b> 로 요청을 분배합니다. 그런데 인기 키 하나가 전체의 40%를 차지합니다. <code>KEYS</code>(키별 요청 수)를 분배해 샤드별 부하를 <code>snap</code> 하고, <b>[최대 샤드 부하, 최소 샤드 부하, 최대/평균 비율(소수 둘째)]</b> 을 돌려주세요.",
  src:"const SHARDS = 4;\n/* [키 해시, 요청 수] — 해시 8 과 4 가 같은 샤드로 떨어진다 */\nconst KEYS = [[8,400],[4,150],[1,150],[2,150],[3,150]];\n\nfunction run() {\n  const load = new Array(SHARDS).fill(0);\n  // TODO: 키를 샤드에 분배하고 샤드별 부하를 snap 으로 기록하세요\n  return [0, 0, 0];\n}\n\nRESULT = run();",
  ref:"const SHARDS = 4;\nconst KEYS = [[8,400],[4,150],[1,150],[2,150],[3,150]];\n\nfunction run() {\n  const load = new Array(SHARDS).fill(0);\n  KEYS.forEach(([h, n]) => { load[h % SHARDS] += n; });\n  load.forEach((v, i) => snap('shard' + i, [v], { shard: i, load: v }));\n  const total = load.reduce((a, b) => a + b, 0);\n  const avg = total / SHARDS;\n  const max = Math.max(...load), min = Math.min(...load);\n  return [max, min, Math.round((max / avg) * 100) / 100];\n}\n\nRESULT = run();",
  tests:[{d:"샤드 4개를 모두 기록한다", js:"FRAMES.length===4"},
         {d:"핫 파티션의 부하가 가장 크다", js:"RESULT[0]===550"},
         {d:"가장 한산한 샤드는 150 이다", js:"RESULT[1]===150"},
         {d:"최대 샤드가 평균의 2배가 넘는다", js:"RESULT[2]>2"},
         {d:"총 부하는 1000 이다", js:"FRAMES.reduce((s,f)=>s+f.opt.load,0)===1000"},
         {d:"샤드 0 이 핫 파티션이다", js:"FRAMES[0].opt.load===550"}],
  ex:"🎯 샤딩은 <b>부하가 고르게 퍼진다는 가정</b> 위에 섭니다. 그 가정이 깨지면 — 인기 상품·유명인 계정·특정 테넌트 — 샤드 하나가 <b>전체의 병목</b>이 되고, 나머지 샤드를 아무리 늘려도 소용없습니다.\n💡 '평균 부하' 는 이 문제를 <b>감춥니다</b>. 이 모델에서 평균은 250인데 최대는 550입니다 — 용량 계획을 평균으로 세우면 핫 샤드가 먼저 넘어집니다. <b>최대/평균 비율</b>을 지표로 보세요.\n⚠️ 해시를 바꾸는 것으로는 해결되지 않습니다 — 키 하나가 뜨거운 것이지 분포 함수가 나쁜 게 아니기 때문입니다. 해법은 <b>키를 쪼개거나</b>(user123#1..#10 같은 salt), <b>그 키만 따로 캐시하거나</b>, 전용 샤드를 주는 것입니다.\n🔧 실전에서 핫 파티션은 <b>갑자기</b> 생깁니다 — 이벤트·바이럴·봇 트래픽. 그래서 샤드별 부하를 상시 관측하고, 재분배(리샤딩)를 무중단으로 할 수 있는 구조인지가 설계의 핵심 질문이 됩니다." },

{ k:"블룸 필터의 거짓 양성", lv:3,
  q:"비트 배열 <b>32칸</b>, 해시 <b>2개</b>인 블룸 필터에 <code>ADDED</code> 를 넣고 <code>PROBE</code> 를 조회합니다. 해시는 <code>(k*7+i*13) % 32</code> 입니다. 각 조회를 <code>snap('q'+key, [있다고 답함], {key, said, real})</code> 로 기록하고 <b>[있다고 답한 수, 거짓 양성 수]</b> 를 돌려주세요.",
  src:"const BITS = 32, HASHES = 2;\nconst ADDED = [1,2,3,4,5,6,7,8];\nconst PROBE = [1,5,100,101,102,103];\n\nfunction run() {\n  const bits = new Array(BITS).fill(0);\n  // TODO: ADDED 를 넣고 PROBE 를 조회하세요\n  return [0, 0];\n}\n\nRESULT = run();",
  ref:"const BITS = 32, HASHES = 2;\nconst ADDED = [1,2,3,4,5,6,7,8];\nconst PROBE = [1,5,100,101,102,103];\n\nfunction run() {\n  const bits = new Array(BITS).fill(0);\n  const pos = (k) => { const out = []; for (let i = 0; i < HASHES; i++) out.push((k * 7 + i * 13) % BITS); return out; };\n  ADDED.forEach((k) => pos(k).forEach((p) => { bits[p] = 1; }));\n  let said = 0, fp = 0;\n  PROBE.forEach((k) => {\n    const hit = pos(k).every((p) => bits[p] === 1);\n    const real = ADDED.indexOf(k) >= 0;\n    if (hit) said++;\n    if (hit && !real) fp++;\n    snap('q' + k, [hit ? 1 : 0], { key: k, said: hit, real });\n  });\n  return [said, fp];\n}\n\nRESULT = run();",
  tests:[{d:"조회 6건을 모두 기록한다", js:"FRAMES.length===6"},
         {d:"넣은 키는 반드시 있다고 답한다", js:"FRAMES.filter(f=>f.opt.real).every(f=>f.opt.said===true)"},
         {d:"거짓 음성은 없다", js:"FRAMES.every(f=>!(f.opt.real&&!f.opt.said))"},
         {d:"거짓 양성이 발생한다", js:"RESULT[1]>0"},
         {d:"있다고 답한 수가 실제보다 많다", js:"RESULT[0]>FRAMES.filter(f=>f.opt.real).length"}],
  ex:"🎯 블룸 필터의 계약은 <b>비대칭</b>입니다 — '없다' 는 <b>확실히</b> 맞고, '있다' 는 <b>아닐 수도</b> 있습니다(거짓 양성). 거짓 음성이 절대 없다는 것이 쓸모의 근거입니다.\n💡 그래서 쓰임새가 정해집니다 — '<b>비싼 조회를 건너뛰기</b>' 입니다. 없다고 하면 디스크·네트워크를 안 타고 바로 끝내고, 있다고 하면 진짜인지 확인하러 갑니다. 확인 비용이 있으므로 거짓 양성은 <b>느려질 뿐 틀리지 않습니다</b>.\n⚠️ 비트가 채워질수록 거짓 양성률이 오릅니다 — 이 모델은 32비트에 8개를 넣어 절반 넘게 채웠습니다. 실전 크기는 <b>예상 원소 수와 목표 오류율</b>에서 계산하며, 넘치면 성능이 서서히 무너집니다.\n🔧 그리고 표준 블룸 필터는 <b>삭제할 수 없습니다</b> — 비트를 되돌리면 다른 키까지 지워집니다. 삭제가 필요하면 카운팅 블룸 필터를, 크기를 모르면 확장 가능 변형을 씁니다. LSM 트리의 SSTable 조회, CDN 의 '한 번 이상 요청된 것만 캐시' 판정이 대표적 사용처입니다." },

/* ── 보안 ── */
{ k:"비밀번호 크래킹 비용", lv:3,
  q:"공격자가 <b>초당 100억 회</b>(GPU 클러스터) 해시를 시도합니다. 문자 종류 <code>SETS</code> 와 길이 <code>LENS</code> 조합의 <b>전수 탐색 시간</b>을 초 단위로 계산해 <code>snap</code> 하고, <b>[숫자6자리 초, 소문자8자리 초(내림), 소문자+숫자14자리 년(내림)]</b> 을 돌려주세요. 1년은 31,536,000초입니다.",
  src:"const RATE = 1e10, YEAR = 31536000;\nconst CASES = [{name:'digit6',set:10,len:6},{name:'lower8',set:26,len:8},{name:'alnum14',set:36,len:14}];\n\nfunction run() {\n  // TODO: 경우의 수 / 초당 시도 = 시간(초)\n  return [0, 0, 0];\n}\n\nRESULT = run();",
  ref:"const RATE = 1e10, YEAR = 31536000;\nconst CASES = [{name:'digit6',set:10,len:6},{name:'lower8',set:26,len:8},{name:'alnum14',set:36,len:14}];\n\nfunction run() {\n  const secs = {};\n  CASES.forEach((c) => {\n    const space = Math.pow(c.set, c.len);\n    const s = space / RATE;\n    secs[c.name] = s;\n    snap(c.name, [s], { name: c.name, space, sec: s });\n  });\n  return [Math.floor(secs.digit6), Math.floor(secs.lower8), Math.floor(secs.alnum14 / YEAR)];\n}\n\nRESULT = run();",
  tests:[{d:"세 경우를 모두 기록한다", js:"FRAMES.length===3"},
         {d:"숫자 6자리는 1초도 안 걸린다", js:"RESULT[0]===0"},
         {d:"소문자 8자리는 20초쯤이다", js:"RESULT[1]>=20 && RESULT[1]<=21"},
         {d:"영숫자 14자리는 수만 년이 걸린다", js:"RESULT[2]>1000"},
         {d:"탐색 공간이 길이에 지수적으로 는다", js:"FRAMES[2].opt.space > FRAMES[1].opt.space * 1e6"}],
  ex:"🎯 탐색 공간은 <code>문자종류^길이</code> 라 <b>길이가 지수의 자리</b>에 있습니다. 문자 종류를 10에서 36으로 늘리는 것보다 <b>길이를 늘리는 쪽</b>이 압도적으로 강합니다 — '특수문자 필수' 정책보다 '길이 12자 이상' 이 나은 이유입니다.\n💡 그런데 이 계산은 <b>공격자가 해시를 가지고 있다</b>는 전제입니다(유출된 DB). 온라인 공격은 레이트 리밋으로 막지만, 유출 이후에는 오직 <b>해시의 강도와 비밀번호의 길이</b>만 남습니다.\n⚠️ 그래서 <b>느린 해시</b>가 필요합니다. SHA-256 은 초당 100억 회지만 bcrypt·argon2 는 <b>일부러 느리게</b>(초당 수만 회) 설계되어 같은 비밀번호의 크래킹 시간을 백만 배로 늘립니다 — 로그인 한 번에 100ms 를 쓰는 것이 그 대가입니다.\n🔧 소금(salt)은 <b>속도가 아니라 재사용을 막습니다</b> — 사용자마다 다른 소금이면 레인보우 테이블도, '한 번 깬 해시를 다른 계정에 재사용' 도 통하지 않습니다. 실전 조합은 '긴 비밀번호 + 느린 해시 + 사용자별 소금 + 2단계 인증' 입니다." },

{ k:"레이트 리밋으로 크리덴셜 스터핑 막기", lv:3,
  q:"유출된 계정 목록으로 <b>초당 1000회</b> 로그인을 시도합니다. IP 당 <b>분당 10회</b> 제한을 걸면 공격자가 <code>IPS</code> 개의 IP 를 쓸 때 <b>분당 실제로 시도되는 횟수</b>가 얼마나 되는지 계산하세요. IP 수 <code>[1, 10, 100, 6000]</code> 각각을 <code>snap</code> 하고 <b>[제한 없을 때 분당 시도, IP 100개일 때 분당 시도, 감소 배수(내림)]</b> 를 돌려주세요.",
  src:"const PER_SEC = 1000, LIMIT_PER_IP = 10;\nconst IPS = [1, 10, 100, 6000];\n\nfunction run() {\n  const unlimited = PER_SEC * 60;\n  // TODO: IP 수마다 min(공격 시도, IP수 × 제한) 을 계산해 snap 하세요\n  return [unlimited, 0, 0];\n}\n\nRESULT = run();",
  ref:"const PER_SEC = 1000, LIMIT_PER_IP = 10;\nconst IPS = [1, 10, 100, 6000];\n\nfunction run() {\n  const unlimited = PER_SEC * 60;\n  const got = {};\n  IPS.forEach((n) => {\n    const allowed = Math.min(unlimited, n * LIMIT_PER_IP);\n    got[n] = allowed;\n    snap('ip' + n, [allowed], { ips: n, allowed });\n  });\n  return [unlimited, got[100], Math.floor(unlimited / got[100])];\n}\n\nRESULT = run();",
  tests:[{d:"네 경우를 모두 기록한다", js:"FRAMES.length===4"},
         {d:"제한이 없으면 분당 6만 회다", js:"RESULT[0]===60000"},
         {d:"IP 100개면 분당 1000회로 줄어든다", js:"RESULT[1]===1000"},
         {d:"60배 줄어든다", js:"RESULT[2]===60"},
         {d:"IP 가 늘수록 통과량도 는다", js:"FRAMES.every((f,i)=>i===0||f.opt.allowed>=FRAMES[i-1].opt.allowed)"},
         {d:"IP 를 아주 많이 쓰면 제한이 무의미해진다", js:"FRAMES[3].opt.allowed===60000"}],
  ex:"🎯 IP 기반 레이트 리밋은 <b>공격 비용을 올릴 뿐</b> 막지 못합니다. IP 100개로 60배 줄지만, 봇넷이나 주거용 프록시로 IP 1000개를 쓰면 <b>제한이 사실상 사라집니다</b>(이 모델의 마지막 줄).\n💡 그래서 방어는 <b>층으로</b> 쌓습니다 — IP 리밋 + <b>계정별</b> 리밋(한 계정에 대한 시도 제한) + 실패율 기반 챌린지(CAPTCHA) + 유출 비밀번호 대조. 공격자가 IP 를 늘려도 계정별 리밋은 우회할 수 없습니다.\n⚠️ 계정별 리밋에는 부작용이 있습니다 — 공격자가 일부러 실패시켜 <b>정상 사용자를 잠그는</b> 서비스 거부입니다. 그래서 잠금 대신 <b>지연 증가</b>나 추가 인증 요구가 선호됩니다.\n🔧 크리덴셜 스터핑의 근본 원인은 <b>비밀번호 재사용</b>입니다 — 다른 사이트에서 유출된 조합이 그대로 통합니다. 그래서 최종 방어선은 언제나 <b>2단계 인증</b>이고, 유출 목록(HaveIBeenPwned) 대조로 가입·변경 시점에 미리 막는 것이 효과가 큽니다." },

{ k:"권한 상승 경로 추적", lv:3,
  q:"역할 상속 그래프에서 <b>권한 상승 경로</b>를 찾으세요. <code>GRANTS</code> 는 <code>{역할: [상속하는 역할들]}</code> 입니다. <code>viewer</code> 에서 시작해 <b>너비 우선</b>으로 도달 가능한 역할을 모두 찾고, 각 단계를 <code>snap('depth'+d, [해당 깊이 역할들], {depth, roles})</code> 로 기록하세요. <b>[도달 가능한 역할 수, admin 까지의 깊이(불가면 −1)]</b> 를 돌려주세요.",
  src:"const GRANTS = { viewer:['commenter'], commenter:['editor'], editor:['publisher'], publisher:['admin'], admin:[], billing:[] };\n\nfunction run() {\n  // TODO: viewer 에서 BFS 로 도달 가능한 역할을 찾으세요\n  return [0, -1];\n}\n\nRESULT = run();",
  ref:"const GRANTS = { viewer:['commenter'], commenter:['editor'], editor:['publisher'], publisher:['admin'], admin:[], billing:[] };\n\nfunction run() {\n  let frontier = ['viewer'];\n  const seen = new Set(frontier);\n  let depth = 0, adminAt = -1;\n  while (frontier.length) {\n    snap('depth' + depth, frontier.slice(), { depth, roles: frontier.slice() });\n    if (frontier.indexOf('admin') >= 0 && adminAt < 0) adminAt = depth;\n    const next = [];\n    frontier.forEach((r) => (GRANTS[r] || []).forEach((n) => {\n      if (!seen.has(n)) { seen.add(n); next.push(n); }\n    }));\n    frontier = next;\n    depth++;\n  }\n  return [seen.size, adminAt];\n}\n\nRESULT = run();",
  tests:[{d:"깊이별로 기록한다", js:"FRAMES.length===5"},
         {d:"viewer 에서 시작한다", js:"FRAMES[0].opt.roles.join()==='viewer'"},
         {d:"admin 까지 도달한다", js:"RESULT[1]===4"},
         {d:"5개 역할에 도달한다", js:"RESULT[0]===5"},
         {d:"billing 에는 도달하지 못한다", js:"FRAMES.every(f=>f.opt.roles.indexOf('billing')<0)"},
         {d:"각 깊이의 역할이 겹치지 않는다", js:"FRAMES.reduce((s,f)=>s+f.opt.roles.length,0)===RESULT[0]"}],
  ex:"🎯 역할 상속은 편리하지만 <b>전이적</b>입니다 — viewer 에게 준 권한이 네 단계를 거쳐 admin 까지 이어지면, 아무도 의도하지 않은 <b>권한 상승 경로</b>가 생깁니다. 각 단계는 다 합리적이었는데 합치면 그렇지 않습니다.\n💡 그래서 권한 감사는 <b>선언이 아니라 도달 가능성</b>으로 해야 합니다 — '이 역할에 무엇을 줬나' 가 아니라 '<b>이 역할로 결국 무엇을 할 수 있나</b>' 입니다. 이 BFS 가 정확히 그 계산입니다.\n⚠️ 실전에서는 그래프가 훨씬 복잡합니다 — 그룹 중첩, 서비스 계정의 위임, 리소스별 정책이 얽힙니다. 클라우드 IAM 사고의 대부분이 '한 단계씩 보면 문제없는데 <b>이어 보면 관리자</b>' 인 경로입니다.\n🔧 방어는 <b>도달 가능 집합을 CI 에서 검사</b>하는 것입니다 — '어떤 최소 권한 역할도 admin 에 도달하지 못한다' 를 테스트로 못 박으면, 나중에 누가 상속 한 줄을 추가할 때 빌드가 깨집니다. AWS 의 Access Analyzer 가 하는 일이 이 그래프 탐색입니다." },

{ k:"토큰 만료와 갱신 창", lv:2,
  q:"액세스 토큰은 <b>15분</b>, 리프레시 토큰은 <b>60분</b> 유효합니다. 사용자가 <code>USES</code> 시각(분)에 API 를 호출할 때, 액세스가 만료됐으면 리프레시로 <b>갱신</b>하고 리프레시도 만료면 <b>재로그인</b>입니다. 각 호출을 <code>snap</code> 하고 <b>[갱신 횟수, 재로그인 횟수]</b> 를 돌려주세요.",
  src:"const ACCESS = 15, REFRESH = 60;\nconst USES = [0, 10, 20, 40, 70, 100];\n\nfunction run() {\n  let accessAt = 0, refreshAt = 0, renew = 0, relogin = 0;\n  // TODO: 각 호출 시각에 만료를 판정하세요\n  return [renew, relogin];\n}\n\nRESULT = run();",
  ref:"const ACCESS = 15, REFRESH = 60;\nconst USES = [0, 10, 20, 40, 70, 100];\n\nfunction run() {\n  let accessAt = 0, refreshAt = 0, renew = 0, relogin = 0;\n  USES.forEach((t) => {\n    let action = 'ok';\n    if (t - accessAt >= ACCESS) {\n      if (t - refreshAt >= REFRESH) { accessAt = t; refreshAt = t; relogin++; action = 'relogin'; }\n      else { accessAt = t; renew++; action = 'renew'; }\n    }\n    snap('t' + t, [renew, relogin], { t, action, renew, relogin });\n  });\n  return [renew, relogin];\n}\n\nRESULT = run();",
  tests:[{d:"호출 6건을 모두 기록한다", js:"FRAMES.length===6"},
         {d:"첫 두 호출은 갱신이 필요 없다", js:"FRAMES[0].opt.action==='ok' && FRAMES[1].opt.action==='ok'"},
         {d:"20분 시점에 갱신한다", js:"FRAMES[2].opt.action==='renew'"},
         {d:"갱신은 3회다", js:"RESULT[0]===3"},
         {d:"재로그인은 1회다", js:"RESULT[1]===1"},
         {d:"재로그인은 리프레시 만료 이후에만 일어난다", js:"FRAMES.filter(f=>f.opt.action==='relogin').every(f=>f.opt.t>=60)"}],
  ex:"🎯 짧은 액세스 토큰 + 긴 리프레시 토큰은 <b>편의와 위험의 절충</b>입니다. 액세스가 유출돼도 15분이면 죽고, 사용자는 리프레시 덕분에 자주 로그인하지 않아도 됩니다.\n💡 액세스 토큰이 짧아야 하는 이유는 <b>취소가 어렵기</b> 때문입니다 — JWT 는 서명만 맞으면 유효하므로, 서버가 즉시 무효화하려면 별도의 블랙리스트가 필요합니다. 짧은 수명이 그 자체로 취소 메커니즘 역할을 합니다.\n⚠️ 리프레시 토큰은 반대로 <b>길고 강력해서</b> 훔치면 오래 쓸 수 있습니다. 그래서 <b>회전(rotation)</b> 이 표준입니다 — 쓸 때마다 새 리프레시를 발급하고 옛 것을 무효화해, 훔친 토큰이 재사용되면 <b>탈취를 탐지</b>할 수 있습니다.\n🔧 이 모델이 보여 주듯 <b>비활성 시간</b>이 리프레시 수명을 넘으면 재로그인입니다 — 그 값이 곧 '얼마나 오래 안 써도 로그인 상태를 유지할 것인가' 라는 제품 결정입니다. 은행 앱은 짧게, 스트리밍 앱은 길게 잡는 이유입니다." },

/* ── 프론트엔드·네트워크 ── */
{ k:"리렌더 전파", lv:2,
  q:"컴포넌트 트리에서 <b>상태 변경이 몇 개를 리렌더시키는지</b> 계산하세요. <code>TREE</code> 는 <code>{이름: [자식들]}</code> 이고, <code>memo</code> 로 감싼 컴포넌트는 <b>props 가 안 바뀌면 자신과 하위를 건너뜁니다</b>. <code>root</code> 상태 변경 시 (1) memo 없음, (2) <code>MEMOED</code> 가 memo 인 경우의 리렌더 수를 <code>snap</code> 하고 <b>[memo 없음, memo 있음]</b> 을 돌려주세요.",
  src:"const TREE = { root:['header','list','footer'], header:[], list:['item1','item2','item3'], item1:[], item2:[], item3:[], footer:[] };\nconst MEMOED = ['list'];\n\nfunction run() {\n  // TODO: 트리를 순회하며 리렌더 대상을 세세요\n  return [0, 0];\n}\n\nRESULT = run();",
  ref:"const TREE = { root:['header','list','footer'], header:[], list:['item1','item2','item3'], item1:[], item2:[], item3:[], footer:[] };\nconst MEMOED = ['list'];\n\nfunction run() {\n  const count = (memoed) => {\n    let n = 0;\n    const walk = (name, isRoot) => {\n      if (!isRoot && memoed.indexOf(name) >= 0) return;\n      n++;\n      (TREE[name] || []).forEach((c) => walk(c, false));\n    };\n    walk('root', true);\n    return n;\n  };\n  const plain = count([]);\n  const withMemo = count(MEMOED);\n  snap('plain', [plain], { kind: 'plain', rendered: plain });\n  snap('memo', [withMemo], { kind: 'memo', rendered: withMemo });\n  return [plain, withMemo];\n}\n\nRESULT = run();",
  tests:[{d:"두 경우를 모두 기록한다", js:"FRAMES.length===2"},
         {d:"memo 가 없으면 7개 전부 리렌더된다", js:"RESULT[0]===7"},
         {d:"list 를 memo 하면 3개만 리렌더된다", js:"RESULT[1]===3"},
         {d:"memo 가 리렌더를 줄인다", js:"FRAMES[1].opt.rendered < FRAMES[0].opt.rendered"},
         {d:"memo 는 자신과 하위를 함께 건너뛴다", js:"RESULT[0]-RESULT[1]===4"}],
  ex:"🎯 리액트의 기본 동작은 '<b>부모가 리렌더되면 자식도 전부</b>' 입니다. 실제 DOM 은 diff 로 최소 변경만 하지만, <b>렌더 함수 자체는 모두 실행</b>되므로 트리가 크면 그 비용이 쌓입니다.\n💡 <code>memo</code> 는 <b>자신과 하위 전체</b>를 잘라냅니다 — 이 모델에서 list 하나를 memo 하니 4개(자신 + 자식 3)가 빠졌습니다. 그래서 memo 는 <b>큰 서브트리의 루트</b>에 거는 것이 효과적입니다.\n⚠️ 그런데 memo 는 <b>props 가 실제로 안 바뀔 때만</b> 동작합니다. 부모가 매 렌더마다 새 객체·새 함수를 만들어 넘기면 참조가 달라져 memo 가 무력화됩니다 — <code>useCallback</code>·<code>useMemo</code> 가 함께 필요한 이유입니다.\n🔧 그리고 memo 자체도 <b>비교 비용</b>이 듭니다. 작은 컴포넌트에 전부 memo 를 거는 것은 대개 손해입니다 — 프로파일러로 <b>실제로 느린 서브트리</b>를 찾은 뒤 거기에만 거는 것이 정석입니다." },

{ k:"번들 크기와 코드 분할", lv:2,
  q:"페이지별 모듈 크기가 <code>MODULES</code>(KB)입니다. (1) <b>단일 번들</b>은 모든 모듈을 첫 로드에 받고, (2) <b>코드 분할</b>은 공통(<code>shared</code>)과 첫 페이지(<code>home</code>)만 받습니다. 각 경우의 첫 로드 크기를 <code>snap</code> 하고 <b>[단일 KB, 분할 KB, 절감률(%) 내림]</b> 을 돌려주세요.",
  src:"const MODULES = { shared:120, home:80, dashboard:300, settings:150, report:250 };\nconst FIRST = ['shared', 'home'];\n\nfunction run() {\n  // TODO: 두 경우의 첫 로드 크기를 계산해 snap 하세요\n  return [0, 0, 0];\n}\n\nRESULT = run();",
  ref:"const MODULES = { shared:120, home:80, dashboard:300, settings:150, report:250 };\nconst FIRST = ['shared', 'home'];\n\nfunction run() {\n  const names = Object.keys(MODULES);\n  const all = names.reduce((s, k) => s + MODULES[k], 0);\n  const split = FIRST.reduce((s, k) => s + MODULES[k], 0);\n  snap('single', [all], { kind: 'single', kb: all });\n  snap('split', [split], { kind: 'split', kb: split });\n  return [all, split, Math.floor((1 - split / all) * 100)];\n}\n\nRESULT = run();",
  tests:[{d:"두 경우를 모두 기록한다", js:"FRAMES.length===2"},
         {d:"단일 번들은 900KB 다", js:"RESULT[0]===900"},
         {d:"분할하면 200KB 만 받는다", js:"RESULT[1]===200"},
         {d:"77% 를 줄인다", js:"RESULT[2]===77"},
         {d:"분할이 항상 더 작다", js:"FRAMES[1].opt.kb < FRAMES[0].opt.kb"}],
  ex:"🎯 첫 로드에 <b>지금 안 쓰는 코드</b>가 섞여 있으면 그만큼 사용자가 기다립니다. 대시보드·설정·리포트는 방문한 사람만 필요한데, 단일 번들은 모두에게 보냅니다.\n💡 코드 분할의 기준은 <b>라우트</b>가 가장 자연스럽습니다 — 페이지 단위로 나누고 진입할 때 받습니다. 무거운 라이브러리(차트·에디터·PDF)를 <b>동적 import</b> 로 미루는 것도 효과가 큽니다.\n⚠️ 너무 잘게 쪼개면 <b>요청 수가 늘어</b> 오히려 느려집니다(HTTP/2 로 완화되지만 왕복 지연은 남습니다). 그리고 공통 모듈이 여러 청크에 <b>중복 포함</b>되면 총량이 늘 수 있어, 번들 분석기로 실제 구성을 확인해야 합니다.\n🔧 크기는 <b>전송(gzip/brotli) 기준</b>으로 봐야 의미가 있고, 실제 체감은 파싱·실행 시간까지 포함됩니다 — 저사양 기기에서는 <b>JS 파싱이 다운로드보다 오래</b> 걸리는 경우도 많습니다." },

{ k:"HTTP 왕복과 지연", lv:2,
  q:"RTT <b>100ms</b> 인 연결로 리소스를 받습니다. (1) HTTP/1.1 은 <b>연결당 1개씩 순차</b>(연결 6개), (2) HTTP/2 는 <b>한 연결에서 동시</b>입니다. 리소스 <b>18개</b>를 받을 때 각 방식의 왕복 수를 <code>snap</code> 하고 <b>[H1 왕복, H2 왕복, 시간 차이(ms)]</b> 를 돌려주세요.",
  src:"const RES = 18, CONNS = 6, RTT = 100;\n\nfunction run() {\n  // TODO: H1 은 연결당 순차, H2 는 한 번에\n  return [0, 0, 0];\n}\n\nRESULT = run();",
  ref:"const RES = 18, CONNS = 6, RTT = 100;\n\nfunction run() {\n  const h1 = Math.ceil(RES / CONNS);\n  const h2 = 1;\n  snap('h1', [h1], { kind: 'h1', rounds: h1, ms: h1 * RTT });\n  snap('h2', [h2], { kind: 'h2', rounds: h2, ms: h2 * RTT });\n  return [h1, h2, (h1 - h2) * RTT];\n}\n\nRESULT = run();",
  tests:[{d:"두 방식을 모두 기록한다", js:"FRAMES.length===2"},
         {d:"HTTP/1.1 은 3회 왕복이 필요하다", js:"RESULT[0]===3"},
         {d:"HTTP/2 는 1회로 끝난다", js:"RESULT[1]===1"},
         {d:"200ms 를 아낀다", js:"RESULT[2]===200"},
         {d:"기록된 시간이 왕복 수에 비례한다", js:"FRAMES.every(f=>f.opt.ms===f.opt.rounds*100)"}],
  ex:"🎯 HTTP/1.1 의 병목은 대역폭이 아니라 <b>연결당 하나씩</b>이라는 제약입니다. 브라우저가 도메인당 6개 연결을 열어 완화했지만, 리소스가 많으면 <b>왕복이 층층이 쌓입니다</b>.\n💡 그래서 HTTP/1 시대의 최적화는 '<b>요청 수 줄이기</b>' 였습니다 — 스프라이트 이미지, CSS/JS 번들링, 도메인 샤딩. HTTP/2 의 멀티플렉싱은 이 제약을 없애, <b>그 최적화들의 근거를 무너뜨렸습니다</b>.\n⚠️ 다만 HTTP/2 에도 한계가 있습니다 — TCP 수준의 <b>헤드 오브 라인 블로킹</b>은 남아서, 패킷 하나가 유실되면 그 연결의 모든 스트림이 멈춥니다. HTTP/3(QUIC)이 UDP 위에서 이것을 해결한 이유입니다.\n🔧 실제 체감은 왕복 수 × RTT 가 지배합니다 — 모바일 네트워크의 RTT 는 100~300ms 라, <b>요청 하나를 줄이는 것이 바이트를 줄이는 것보다 큰 효과</b>를 낼 때가 많습니다. CDN 이 빠른 첫 번째 이유도 대역폭이 아니라 <b>가까워서 RTT 가 짧기</b> 때문입니다." },

{ k:"이미지 최적화와 LCP", lv:2,
  q:"히어로 이미지의 <b>전송 시간</b>을 계산하세요. 대역폭은 <b>1.5Mbps</b>(초당 187.5KB)입니다. <code>VARIANTS</code>(KB)마다 전송 초를 <code>snap</code> 하고, <b>[원본 초(소수 둘째), webp 초(소수 둘째), LCP 2.5초 예산을 지키는 변형 수]</b> 를 돌려주세요.",
  src:"const KBPS = 187.5, BUDGET = 2.5;\nconst VARIANTS = [{name:'original',kb:1200},{name:'resized',kb:400},{name:'webp',kb:180},{name:'avif',kb:90}];\n\nfunction run() {\n  // TODO: 각 변형의 전송 시간을 계산해 snap 하세요\n  return [0, 0, 0];\n}\n\nRESULT = run();",
  ref:"const KBPS = 187.5, BUDGET = 2.5;\nconst VARIANTS = [{name:'original',kb:1200},{name:'resized',kb:400},{name:'webp',kb:180},{name:'avif',kb:90}];\n\nfunction run() {\n  const secs = {};\n  let ok = 0;\n  VARIANTS.forEach((v) => {\n    const s = Math.round((v.kb / KBPS) * 100) / 100;\n    secs[v.name] = s;\n    if (s <= BUDGET) ok++;\n    snap(v.name, [s], { name: v.name, kb: v.kb, sec: s, ok: s <= BUDGET });\n  });\n  return [secs.original, secs.webp, ok];\n}\n\nRESULT = run();",
  tests:[{d:"네 변형을 모두 기록한다", js:"FRAMES.length===4"},
         {d:"원본은 6.4초가 걸린다", js:"RESULT[0]===6.4"},
         {d:"webp 는 0.96초다", js:"RESULT[1]===0.96"},
         {d:"세 변형이 예산을 지킨다", js:"RESULT[2]===3"},
         {d:"원본만 예산을 넘는다", js:"FRAMES.filter(f=>!f.opt.ok).length===1"},
         {d:"크기가 작을수록 빠르다", js:"FRAMES.every((f,i)=>i===0||f.opt.sec<FRAMES[i-1].opt.sec)"}],
  ex:"🎯 LCP(가장 큰 콘텐츠 렌더 시간)의 범인은 대개 <b>히어로 이미지</b>입니다. 1.2MB 원본은 느린 회선에서 6.4초 — 사용자는 이미 떠났습니다. 좋은 점수 기준은 <b>2.5초 이하</b>입니다.\n💡 개선의 순서는 <b>크기 → 형식 → 지연 로딩</b> 입니다. 화면에 400px 로 보이는 이미지에 4000px 원본을 보내는 것이 가장 흔하고 가장 큰 낭비입니다 — <code>srcset</code> 으로 기기에 맞는 크기를 고르게 하세요.\n⚠️ 히어로 이미지에 <b>lazy loading 을 걸면 오히려 나빠집니다</b> — 화면 안에 있는데도 발견이 늦어져 LCP 가 밀립니다. 첫 화면 이미지는 <code>fetchpriority=\"high\"</code> 로 <b>먼저</b> 받아야 합니다.\n🔧 형식 전환(webp·avif)은 화질을 거의 유지하며 절반 이하로 줄입니다. <code>&lt;picture&gt;</code> 로 폴백을 두면 지원하지 않는 브라우저도 안전합니다 — 이 세 가지(크기·형식·우선순위)만 해도 대부분의 LCP 문제가 해결됩니다." },
];
