/* 시스템 설계 실습 2차 — 실습이 하나도 없던 6개 유닛을 연다.
   용량 추정 · 파티셔닝 · 로드밸런싱/가용성 · 피드 설계 · 일관성 · 캐시 전략.

   설계 문제는 '정답이 없다' 고들 하지만, 그 안에는 반드시 계산이 있다.
   초당 몇 건인지, 저장량이 몇 테라인지, 노드 하나가 죽으면 몇 퍼센트가 옮겨 가는지.
   그 계산을 못 하면 트레이드오프도 말로만 남는다. 여기서는 그 계산을 직접 짠다.

   채점은 앱의 JS 하네스가 한다. */
module.exports = [
/* ── 용량 추정과 기본 빌딩블록 ────────────────────────────── */
{
  unit: "용량 추정과 기본 빌딩블록",
  lesson: "직접 짜 보기 — 숫자로 크기를 잡기",
  th: {
    sum: "설계의 첫걸음은 **크기를 숫자로 잡는 것**이다. 초당 몇 건인지 모르면 무엇도 정할 수 없다.",
    body: [
      { h: "하루를 초로 바꾼다", t: "하루는 약 86,400초다. 하루 요청 수를 이 값으로 나누면 평균 초당 요청 수가 나온다. 이 한 번의 나눗셈이 '서버 몇 대' 의 출발점이다." },
      { h: "평균이 아니라 최대를 본다", t: "요청은 하루 내내 고르게 오지 않는다. 점심시간이나 퇴근길에 몰린다. 평균의 몇 배가 최대인지를 곱해 두지 않으면, 평소에는 멀쩡하다가 가장 중요한 시간에 무너진다." },
      { h: "저장량은 건수 × 크기 × 기간", t: "하루 100만 건을 1KB 씩 1년 보관하면 약 365GB 다. 여기에 복제본 수를 곱해야 실제 디스크가 나온다. 복제를 빼먹으면 세 배 차이가 난다." },
      { h: "어림수로 계산한다", t: "1KB 를 1000B 로, 하루를 10만 초로 놓고 계산해도 결론은 거의 같다. 설계 단계에서 필요한 것은 자릿수이지 소수점이 아니다 — 정확한 숫자를 붙들면 정작 결정을 못 한다." },
    ],
    code: { c: "qps  = daily / 86400\npeak = qps * peakFactor\nbytes = daily * sizeB * days * replicas", cap: "자릿수를 먼저 잡는다" },
    key: ["하루를 초로 바꾼다", "평균이 아니라 최대를 본다", "저장량에 복제본을 곱한다"],
  },
  q: [
    {
      k: "peakQps · 몰리는 시간을 기준으로",
      qq: "하루 요청 수와 <b>몰림 배수</b>를 받아 <b>최대 초당 요청 수</b>를 돌려주세요. 하루는 86400초이고, 올림합니다.",
      src: "function peakQps(daily, peakFactor) {\n  return Math.ceil(daily / 86400);\n}",
      sol: "function peakQps(daily, peakFactor) {\n  return Math.ceil((daily / 86400) * peakFactor);\n}",
      tests: [["peakQps(8640000, 1)", "100"],
              ["peakQps(8640000, 3)", "300"],
              ["peakQps(86400, 2)", "2"]],
      edge: [["peakQps(0, 3)", "0"],
             ["peakQps(1, 1)", "1"]],
      ex: "평균으로 서버를 잡으면 점심시간에 무너집니다. 요청은 하루 내내 고르게 오지 않아요. 평균의 몇 배가 최대인지를 곱해 두어야 가장 중요한 시간에 버팁니다.",
    },
    {
      k: "storageBytes · 복제본까지 세기",
      qq: "하루 건수·건당 바이트·보관 일수·복제본 수를 받아 <b>필요한 저장량</b>을 돌려주세요.",
      src: "function storageBytes(daily, sizeB, days, replicas) {\n  return daily * sizeB * days;\n}",
      sol: "function storageBytes(daily, sizeB, days, replicas) {\n  return daily * sizeB * days * replicas;\n}",
      tests: [["storageBytes(1000, 1000, 10, 1)", "10000000"],
              ["storageBytes(1000, 1000, 10, 3)", "30000000"],
              ["storageBytes(100, 500, 2, 2)", "200000"]],
      edge: [["storageBytes(0, 1000, 10, 3)", "0"],
             ["storageBytes(1000, 1000, 0, 3)", "0"]],
      ex: "복제본을 빼먹으면 실제 필요한 디스크의 3분의 1만 잡게 됩니다. 용량 산정에서 가장 흔하게 자릿수가 틀리는 자리예요.",
    },
    {
      k: "serversNeeded · 몇 대가 필요한가",
      qq: "최대 초당 요청 수와 서버 한 대가 감당하는 양, 그리고 <b>여유율</b>을 받아 필요한 대수를 돌려주세요. 올림하고 <b>최소 1대</b>입니다.",
      src: "function serversNeeded(peak, perServer, headroom) {\n  return Math.ceil(peak / perServer);\n}",
      sol: "function serversNeeded(peak, perServer, headroom) {\n  const need = Math.ceil(peak / (perServer * (1 - headroom)));\n  return Math.max(1, need);\n}",
      tests: [["serversNeeded(300, 100, 0)", "3"],
              ["serversNeeded(300, 100, 0.5)", "6"],
              ["serversNeeded(50, 100, 0)", "1"]],
      edge: [["serversNeeded(0, 100, 0.5)", "1"],
             ["serversNeeded(100, 100, 0.2)", "2"]],
      ex: "여유 없이 딱 맞춰 잡으면, 한 대만 죽어도 나머지가 즉시 한계를 넘습니다. 그러면 연쇄로 무너져요. 여유율은 낭비가 아니라 한 대가 빠질 자리를 미리 비워 두는 것입니다.",
    },
  ],
},
/* ── 데이터 파티셔닝·샤딩 ─────────────────────────────────── */
{
  unit: "데이터 파티셔닝·샤딩",
  lesson: "직접 짜 보기 — 어디에 둘지 정하는 규칙",
  th: {
    sum: "자료가 한 대에 안 들어가면 나눠 담는다. 문제는 **어느 것을 어디에 둘지** 정하는 규칙이다.",
    body: [
      { h: "나머지로 나누면 간단하지만", t: "`hash(key) % n` 은 쉽고 고르게 흩어진다. 그런데 노드를 하나 더하면 `n` 이 바뀌어 **거의 모든 열쇠의 자리가 바뀐다.** 자료를 통째로 옮겨야 하므로 실제 서비스에서는 쓰기 어렵다." },
      { h: "고리로 배치하면 조금만 옮긴다", t: "노드와 열쇠를 같은 고리 위에 올리고, 열쇠는 시계 방향으로 만나는 첫 노드가 맡는다. 노드를 하나 더해도 그 노드가 맡을 구간만 옮겨 간다 — 전체의 1/n 정도다." },
      { h: "한쪽으로 몰리는 열쇠", t: "인기 있는 계정 하나가 전체 트래픽의 절반이면, 그 열쇠가 있는 노드만 죽어난다. 이런 열쇠는 따로 떼어 내거나 뒤에 임의의 번호를 붙여 여러 칸으로 나눈다." },
      { h: "범위로 나누면 순서가 산다", t: "날짜처럼 순서가 있는 열쇠를 범위로 나누면 '최근 일주일' 같은 조회가 한두 노드로 끝난다. 대신 최신 자료가 한 노드에 몰려 그곳만 바빠진다 — 어느 쪽이 나은지는 조회 방식이 정한다." },
    ],
    code: { c: "// 나머지: 노드가 늘면 거의 전부 이동\nnode = hash(key) % n\n\n// 고리: 시계 방향 첫 노드가 맡는다", cap: "옮기는 양이 규칙을 가른다" },
    key: ["나머지는 쉽지만 재배치가 크다", "고리는 1/n 만 옮긴다", "몰리는 열쇠는 따로 뗀다"],
  },
  q: [
    {
      k: "moveRatio · 노드를 늘리면 얼마나 옮기나",
      qq: "열쇠 목록과 노드 수를 받아, <code>n</code>에서 <code>n+1</code>로 늘렸을 때 <b>자리가 바뀌는 열쇠의 비율</b>을 돌려주세요. 자리는 <code>key % n</code> 으로 정합니다.",
      src: "function moveRatio(keys, n) {\n  return 1 / (n + 1);\n}",
      sol: "function moveRatio(keys, n) {\n  if (!keys.length) return 0;\n  let moved = 0;\n  for (const k of keys) {\n    if (k % n !== k % (n + 1)) moved++;\n  }\n  return moved / keys.length;\n}",
      /* 2에서 3으로 늘리면 여섯 열쇠 중 넷이 옮겨 간다 — 나눗셈 결과가 딱 떨어지지
         않으므로 아주 작은 차이는 허용한다. */
      tests: [["moveRatio([0, 1, 2, 3], 1)", "0.5"],
              ["Math.abs(moveRatio([0, 1, 2, 3, 4, 5], 2) - 2 / 3) < 1e-9", "true"],
              ["moveRatio([], 3)", "0"]],
      edge: [["moveRatio([0], 1)", "0"],
             ["Math.abs(moveRatio([1, 3, 5], 2) - 2 / 3) < 1e-9", "true"]],
      ex: "'1/(n+1) 만 옮기면 된다' 는 고리 방식의 이야기입니다. 나머지 방식은 실제로 세어 보면 절반 넘게 움직여요 — 짐작하지 말고 세어 봐야 두 방식의 차이가 보입니다.",
    },
    {
      k: "ringNode · 시계 방향 첫 노드 찾기",
      qq: "고리 위 노드 위치들과 열쇠 위치를 받아 <b>시계 방향으로 만나는 첫 노드</b>를 돌려주세요. 끝을 넘으면 <b>맨 앞으로 돌아옵니다</b>.",
      src: "function ringNode(nodes, pos) {\n  const sorted = nodes.slice().sort((a, b) => a - b);\n  return sorted.find(n => n >= pos);\n}",
      sol: "function ringNode(nodes, pos) {\n  const sorted = nodes.slice().sort((a, b) => a - b);\n  const hit = sorted.find(n => n >= pos);\n  return hit === undefined ? sorted[0] : hit;\n}",
      tests: [["ringNode([10, 20, 30], 15)", "20"],
              ["ringNode([10, 20, 30], 35)", "10"],
              ["ringNode([10, 20, 30], 10)", "10"]],
      edge: [["ringNode([10], 99)", "10"],
             ["ringNode([30, 10, 20], 25)", "30"]],
      ex: "고리라는 것은 '끝에서 처음으로 이어진다' 는 뜻입니다. 그 되돌아오는 처리를 빼먹으면 마지막 노드 뒤쪽 열쇠들이 갈 곳을 잃어요 — undefined 가 그대로 흘러갑니다.",
    },
    {
      k: "hotKeys · 몰리는 열쇠 찾아내기",
      qq: "열쇠별 요청 수를 받아, <b>전체의 <code>pct</code> 이상</b>을 차지하는 열쇠 이름을 큰 순서로 돌려주세요.",
      src: "function hotKeys(counts, pct) {\n  return Object.keys(counts).filter(k => counts[k] >= pct);\n}",
      sol: "function hotKeys(counts, pct) {\n  const total = Object.values(counts).reduce((a, b) => a + b, 0);\n  if (!total) return [];\n  return Object.keys(counts)\n    .filter(k => counts[k] / total >= pct)\n    .sort((a, b) => counts[b] - counts[a]);\n}",
      tests: [["hotKeys({ a: 90, b: 10 }, 0.5)", "['a']"],
              ["hotKeys({ a: 50, b: 50 }, 0.5)", "['a', 'b']"],
              ["hotKeys({ a: 10, b: 10, c: 80 }, 0.5)", "['c']"]],
      edge: [["hotKeys({}, 0.5)", "[]"],
             ["hotKeys({ a: 1 }, 0.5)", "['a']"]],
      ex: "요청 수를 비율과 그대로 견주면 단위가 달라 아무 뜻이 없습니다. 전체로 나눠야 '얼마나 몰렸는가' 가 나와요. 몰린 열쇠를 못 찾으면 노드 하나만 계속 죽습니다.",
    },
  ],
},
/* ── 로드밸런싱·CDN·가용성 ────────────────────────────────── */
{
  unit: "로드밸런싱·CDN·가용성",
  lesson: "직접 짜 보기 — 나눠 보내고, 하나쯤 죽어도",
  th: {
    sum: "트래픽을 여러 대에 **고르게** 보내고, 그중 하나가 죽어도 서비스가 이어지게 만든다.",
    body: [
      { h: "고르게 나누는 가장 단순한 방법", t: "차례대로 돌아가며 보내는 방식(라운드 로빈)이 기본이다. 서버 성능이 다르면 좋은 서버에 더 많이 보내도록 가중치를 준다. 가중치를 안 주면 느린 서버가 전체 속도를 정한다." },
      { h: "죽은 서버는 목록에서 뺀다", t: "건강 검사에 실패한 서버를 계속 후보에 두면, 그 몫의 요청이 통째로 실패한다. 뺐다가 다시 살아나면 넣어야 하는데, 이때 한꺼번에 몰리지 않도록 조금씩 보내는 것이 좋다." },
      { h: "가용성은 곱셈이다", t: "각 99% 짜리 부품 세 개를 직렬로 이으면 전체는 약 97% 다. 부품을 늘릴수록 전체는 내려간다. 반대로 같은 역할을 병렬로 두면 둘 다 죽을 확률만 남아 크게 올라간다." },
      { h: "가까운 곳에서 준다", t: "CDN 은 사용자와 가까운 곳에 사본을 둔다. 거리 자체가 줄어드니 무엇보다 확실하게 빨라진다. 대신 원본이 바뀌었을 때 언제 갱신할지를 정해 둬야 한다 — 안 그러면 옛것이 오래 남는다." },
    ],
    code: { c: "// 직렬: 곱한다\n0.99 * 0.99 * 0.99 ≈ 0.970\n\n// 병렬(둘 중 하나만 살아도): 1 - (1-0.99)^2 ≈ 0.9999", cap: "직렬은 곱하고, 병렬은 올린다" },
    key: ["가중치를 안 주면 느린 쪽이 기준", "죽은 서버는 뺀다", "직렬 가용성은 곱셈"],
  },
  q: [
    {
      k: "pickServer · 살아 있는 것 중에서 돌아가며",
      qq: "서버 목록과 순번을 받아 <b>살아 있는 서버 중</b> 차례에 맞는 것을 돌려주세요. 살아 있는 것이 <b>없으면 <code>null</code></b> 입니다.",
      src: "function pickServer(servers, turn) {\n  return servers[turn % servers.length].name;\n}",
      sol: "function pickServer(servers, turn) {\n  const up = servers.filter(s => s.healthy);\n  if (!up.length) return null;\n  return up[turn % up.length].name;\n}",
      tests: [["pickServer([{ name: 'a', healthy: true }, { name: 'b', healthy: false }], 1)", "'a'"],
              ["pickServer([{ name: 'a', healthy: true }, { name: 'b', healthy: true }], 1)", "'b'"],
              ["pickServer([{ name: 'a', healthy: false }], 0)", "null"]],
      edge: [["pickServer([{ name: 'a', healthy: true }], 7)", "'a'"],
             ["pickServer([], 0)", "null"]],
      ex: "죽은 서버를 후보에 두면 그 차례의 요청이 통째로 실패합니다. 서버 두 대 중 하나가 죽으면 절반이 실패하는데, 그래프에는 '절반은 성공' 으로 보여 원인을 늦게 찾아요.",
    },
    {
      k: "weightedPick · 성능만큼 나눠 보내기",
      qq: "가중치가 있는 서버 목록과 순번을 받아, <b>가중치만큼 자주</b> 뽑히도록 이름을 돌려주세요. 순번은 0부터입니다.",
      src: "function weightedPick(servers, turn) {\n  return servers[turn % servers.length].name;\n}",
      sol: "function weightedPick(servers, turn) {\n  const slots = [];\n  servers.forEach(s => {\n    for (let i = 0; i < s.weight; i++) slots.push(s.name);\n  });\n  if (!slots.length) return null;\n  return slots[turn % slots.length];\n}",
      tests: [["weightedPick([{ name: 'big', weight: 2 }, { name: 'small', weight: 1 }], 0)", "'big'"],
              ["weightedPick([{ name: 'big', weight: 2 }, { name: 'small', weight: 1 }], 1)", "'big'"],
              ["weightedPick([{ name: 'big', weight: 2 }, { name: 'small', weight: 1 }], 2)", "'small'"]],
      edge: [["weightedPick([{ name: 'a', weight: 0 }], 0)", "null"],
             ["weightedPick([{ name: 'a', weight: 1 }], 5)", "'a'"]],
      ex: "가중치를 무시하면 성능이 절반인 서버에도 같은 양을 보냅니다. 그 서버가 먼저 한계에 닿아 응답이 느려지고, 결국 전체 속도가 느린 쪽에 맞춰져요.",
    },
    {
      k: "availability · 직렬로 이으면 내려간다",
      qq: "부품별 가용성 목록을 받아 <b>직렬로 이었을 때</b> 전체 가용성을 돌려주세요. 빈 목록이면 <code>1</code> 입니다.",
      src: "function availability(parts) {\n  if (!parts.length) return 1;\n  return Math.min.apply(null, parts);\n}",
      sol: "function availability(parts) {\n  return parts.reduce((a, b) => a * b, 1);\n}",
      tests: [["Math.abs(availability([0.99, 0.99]) - 0.9801) < 1e-9", "true"],
              ["availability([1, 1, 1])", "1"],
              ["availability([])", "1"]],
      edge: [["availability([0.5, 0.5])", "0.25"],
             ["availability([0])", "0"]],
      ex: "'가장 약한 고리만큼' 이라는 말은 직관적이지만 틀렸습니다. 99% 짜리 셋을 이으면 97% 로 내려가요. 부품을 늘릴수록 전체가 내려간다는 것이 직렬의 성질입니다.",
    },
  ],
},
/* ── 피드·타임라인 설계 ───────────────────────────────────── */
{
  unit: "피드·타임라인 설계",
  lesson: "직접 짜 보기 — 언제 만들어 둘 것인가",
  th: {
    sum: "피드는 **글을 쓸 때 미리 만들어 둘지**, **읽을 때 그때 모을지**로 갈린다.",
    body: [
      { h: "미리 만들어 두기", t: "글을 쓰면 팔로워들의 목록에 미리 넣어 둔다. 읽을 때는 자기 목록만 보면 되니 아주 빠르다. 대신 팔로워가 백만이면 쓰기 한 번에 백만 번을 써야 한다." },
      { h: "읽을 때 모으기", t: "읽는 순간 내가 팔로우한 사람들의 최근 글을 모아 합친다. 쓰기는 한 번으로 끝나지만, 읽을 때마다 여러 곳을 뒤져야 해서 느리다. 읽기가 훨씬 잦다는 점이 문제다." },
      { h: "섞어 쓴다", t: "팔로워가 아주 많은 계정만 '읽을 때 모으기' 로 두고 나머지는 미리 만들어 둔다. 대부분의 사용자는 빠른 길을 타고, 소수의 큰 계정 때문에 전체가 느려지지 않는다." },
      { h: "합칠 때는 순서를 지킨다", t: "여러 곳에서 모은 글을 시간순으로 합쳐야 한다. 각각 이미 정렬돼 있으니 앞에서부터 큰 것을 골라 담으면 전부 다시 정렬할 필요가 없다. 같은 시각이면 무엇을 앞에 둘지도 정해 둬야 결과가 흔들리지 않는다." },
    ],
    code: { c: "if (followers > 100000) 읽을 때 모으기\nelse                    미리 만들어 두기", cap: "쓰기 비용과 읽기 비용을 견준다" },
    key: ["미리 만들면 읽기가 빠르다", "팔로워가 많으면 쓰기가 폭발", "큰 계정만 따로 다룬다"],
  },
  q: [
    {
      k: "fanoutCost · 쓰기 비용 재기",
      qq: "글 수와 팔로워 수, 그리고 방식을 받아 <b>쓰기 횟수</b>를 돌려주세요. <code>'push'</code>는 글마다 팔로워 수만큼, <code>'pull'</code>은 글마다 한 번입니다.",
      src: "function fanoutCost(posts, followers, mode) {\n  return posts * followers;\n}",
      sol: "function fanoutCost(posts, followers, mode) {\n  return mode === 'push' ? posts * followers : posts;\n}",
      tests: [["fanoutCost(10, 100, 'push')", "1000"],
              ["fanoutCost(10, 100, 'pull')", "10"],
              ["fanoutCost(1, 1000000, 'push')", "1000000"]],
      edge: [["fanoutCost(0, 100, 'push')", "0"],
             ["fanoutCost(5, 0, 'push')", "0"]],
      ex: "두 방식의 비용을 같은 식으로 재면 비교 자체가 안 됩니다. 팔로워 백만인 계정이 글 하나를 쓸 때 백만 번을 쓰는지 한 번을 쓰는지가, 방식을 고르는 이유의 전부예요.",
    },
    {
      k: "feedMode · 큰 계정만 따로",
      qq: "팔로워 수와 기준을 받아 방식을 정하세요. 기준 <b>이상</b>이면 <code>'pull'</code>, 아니면 <code>'push'</code> 입니다.",
      src: "function feedMode(followers, threshold) {\n  return 'push';\n}",
      sol: "function feedMode(followers, threshold) {\n  return followers >= threshold ? 'pull' : 'push';\n}",
      tests: [["feedMode(100, 100000)", "'push'"],
              ["feedMode(1000000, 100000)", "'pull'"],
              ["feedMode(100000, 100000)", "'pull'"]],
      edge: [["feedMode(0, 100000)", "'push'"],
             ["feedMode(99999, 100000)", "'push'"]],
      ex: "전부 미리 만들어 두면 팔로워가 많은 계정 하나가 글을 쓸 때마다 시스템 전체가 멈칫합니다. 그런 계정만 읽을 때 모으게 하면, 대부분의 사용자는 빠른 길을 그대로 씁니다.",
    },
    {
      k: "mergeFeeds · 시간순으로 합치기",
      qq: "이미 <b>최신순으로 정렬된</b> 목록 여러 개를 받아 <b>상위 <code>n</code>개</b>를 최신순으로 합쳐 주세요. 시각이 같으면 <code>id</code> 가 작은 것이 앞입니다.",
      src: "function mergeFeeds(lists, n) {\n  return lists.flat().slice(0, n).map(x => x.id);\n}",
      sol: "function mergeFeeds(lists, n) {\n  return lists\n    .flat()\n    .sort((a, b) => b.at - a.at || a.id - b.id)\n    .slice(0, n)\n    .map(x => x.id);\n}",
      tests: [["mergeFeeds([[{ id: 1, at: 30 }], [{ id: 2, at: 40 }]], 2)", "[2, 1]"],
              ["mergeFeeds([[{ id: 1, at: 30 }, { id: 3, at: 10 }], [{ id: 2, at: 20 }]], 2)", "[1, 2]"],
              ["mergeFeeds([[{ id: 5, at: 10 }], [{ id: 2, at: 10 }]], 2)", "[2, 5]"]],
      edge: [["mergeFeeds([], 3)", "[]"],
             ["mergeFeeds([[{ id: 1, at: 1 }]], 5)", "[1]"]],
      ex: "그냥 이어 붙이면 첫 번째 목록의 옛 글이 두 번째 목록의 최신 글보다 앞에 옵니다. 각 목록은 정렬돼 있어도 합친 것은 아니에요. 그리고 같은 시각의 순서를 정해 두지 않으면 새로 고칠 때마다 순서가 흔들립니다.",
    },
  ],
},
/* ── 일관성과 신뢰성 ──────────────────────────────────────── */
{
  unit: "일관성과 신뢰성",
  lesson: "직접 짜 보기 — 몇 곳이 답해야 믿을 수 있나",
  th: {
    sum: "여러 곳에 복제해 두면, **몇 곳의 답을 들어야** 최신값이라고 할 수 있는지 정해야 한다.",
    body: [
      { h: "쓰기와 읽기의 수를 정한다", t: "복제본이 `N`개일 때 쓰기에 `W`곳, 읽기에 `R`곳의 답을 받는다. `W + R > N` 이면 쓴 곳과 읽는 곳이 반드시 한 곳은 겹쳐서, 최신값을 놓치지 않는다." },
      { h: "겹치지 않으면 옛것을 읽는다", t: "`W + R <= N` 이면 방금 쓴 값을 못 읽는 경우가 생긴다. 빠르지만 '방금 올린 글이 안 보인다' 는 문제가 따라온다. 어느 쪽이 나은지는 서비스가 정한다." },
      { h: "누가 최신인지 판단해야 한다", t: "두 곳의 값이 다르면 무엇이 최신인지 정해야 한다. 시각으로 정하면 시계가 어긋난 서버 때문에 뒤바뀔 수 있다. 그래서 버전 번호를 함께 올리는 방식이 안전하다." },
      { h: "재시도해도 한 번만 반영되게", t: "네트워크가 끊기면 같은 요청이 다시 온다. 요청마다 고유 번호를 붙이고 이미 처리한 번호는 건너뛰면, 두 번 와도 결과가 같다. 결제처럼 되돌리기 어려운 일에는 반드시 필요하다." },
    ],
    code: { c: "N = 3, W = 2, R = 2   →  W + R = 4 > 3  (겹친다)\nN = 3, W = 1, R = 1   →  2 <= 3      (겹치지 않는다)", cap: "겹쳐야 최신을 본다" },
    key: ["`W + R > N` 이면 겹친다", "겹치지 않으면 옛것을 읽는다", "최신 판단은 버전으로"],
  },
  q: [
    {
      k: "isStrong · 겹치는지 확인하기",
      qq: "복제본 수·쓰기 정족수·읽기 정족수를 받아, <b>최신값을 반드시 읽을 수 있는지</b> 판단하세요.",
      src: "function isStrong(n, w, r) {\n  return w + r >= n;\n}",
      sol: "function isStrong(n, w, r) {\n  return w + r > n;\n}",
      tests: [["isStrong(3, 2, 2)", "true"],
              ["isStrong(3, 1, 2)", "false"],
              ["isStrong(5, 3, 3)", "true"]],
      edge: [["isStrong(3, 3, 1)", "true"],
             ["isStrong(1, 1, 1)", "true"]],
      ex: "딱 같을 때(W + R = N)는 겹치지 않습니다. 쓴 곳과 읽는 곳이 서로 어긋날 수 있어요. 경계에서 한 칸 차이가 '방금 쓴 값을 읽을 수 있는가' 를 가릅니다.",
    },
    {
      k: "latest · 버전으로 최신 고르기",
      qq: "복제본들의 값을 받아 <b>버전이 가장 큰 것</b>의 값을 돌려주세요. 버전이 같으면 <b><code>node</code> 이름이 작은</b> 것을 고릅니다.",
      src: "function latest(replicas) {\n  return replicas.slice().sort((a, b) => b.at - a.at)[0].value;\n}",
      sol: "function latest(replicas) {\n  return replicas\n    .slice()\n    .sort((a, b) => b.version - a.version || (a.node < b.node ? -1 : 1))[0].value;\n}",
      tests: [["latest([{ node: 'a', version: 1, value: '옛' }, { node: 'b', version: 2, value: '새' }])", "'새'"],
              ["latest([{ node: 'b', version: 2, value: 'B' }, { node: 'a', version: 2, value: 'A' }])", "'A'"],
              ["latest([{ node: 'a', version: 5, value: 'x' }])", "'x'"]],
      edge: [["latest([{ node: 'a', version: 0, value: '' }, { node: 'b', version: 0, value: 'b' }])", "''"]],
      ex: "시각으로 최신을 정하면 시계가 조금 어긋난 서버 때문에 옛 값이 이기기도 합니다. 게다가 여기서는 at 이라는 항목 자체가 없어 전부 undefined 라 순서가 정해지지 않아요. 버전은 서버 시계와 무관합니다.",
    },
    {
      k: "applyOnce · 두 번 와도 한 번만",
      qq: "이미 처리한 요청 번호 집합과 새 요청을 받아, <b>처음이면 적용</b>하고 <b>이미 있으면 건너뛰게</b> 하세요. 돌려줄 값은 적용 후 잔액입니다.",
      src: "function applyOnce(seen, id, balance, amount) {\n  return balance + amount;\n}",
      sol: "function applyOnce(seen, id, balance, amount) {\n  if (seen.has(id)) return balance;\n  seen.add(id);\n  return balance + amount;\n}",
      tests: [["applyOnce(new Set(), 'r1', 100, 50)", "150"],
              ["applyOnce(new Set(['r1']), 'r1', 100, 50)", "100"],
              ["(() => { const s = new Set(); let b = applyOnce(s, 'r1', 100, 50); b = applyOnce(s, 'r1', b, 50); return b; })()", "150"]],
      edge: [["applyOnce(new Set(), 'r1', 0, 0)", "0"]],
      ex: "네트워크가 끊기면 같은 요청이 다시 옵니다. 번호를 안 보면 두 번 입금되거나 두 번 결제돼요. 요청마다 번호를 붙이고 이미 처리한 것을 건너뛰면, 몇 번 와도 결과가 같습니다.",
    },
  ],
},
/* ── 캐시 전략 ────────────────────────────────────────────── */
{
  unit: "캐시 전략",
  lesson: "직접 짜 보기 — 없을 때 무슨 일이 벌어지나",
  th: {
    sum: "캐시는 있을 때가 아니라 **없을 때** 무슨 일이 벌어지는지가 설계의 핵심이다.",
    body: [
      { h: "한꺼번에 만료되면 몰린다", t: "같은 시각에 만든 캐시가 같은 시각에 만료되면, 그 순간 모든 요청이 원본으로 몰린다. 유효 기간에 약간의 흔들림을 섞으면 만료 시점이 흩어져 이 몰림이 사라진다." },
      { h: "없는 값도 캐시한다", t: "없는 열쇠를 계속 물어보면 매번 원본까지 간다. 공격이 아니어도 오타 하나로 이런 일이 생긴다. '없음' 도 짧게 캐시해 두면 원본이 지켜진다." },
      { h: "만료 직전에 미리 갱신한다", t: "만료된 뒤에 만들면 그 사이 요청들이 전부 기다린다. 만료 전에 미리 새로 만들어 두면 사용자는 기다림을 겪지 않는다. 언제부터 미리 만들지를 비율로 정해 둔다." },
      { h: "적중률로 판단한다", t: "캐시가 도움이 되는지는 느낌이 아니라 적중률로 본다. 낮다면 열쇠가 잘못 만들어졌거나 유효 기간이 너무 짧은 것이다 — 캐시를 키우기 전에 이유를 먼저 본다." },
    ],
    code: { c: "ttl = base + random(0, jitter)     // 만료를 흩는다\nif (age > ttl * 0.9) refreshAhead()  // 미리 갱신", cap: "없을 때를 설계한다" },
    key: ["만료를 흩어 놓는다", "'없음' 도 캐시한다", "적중률로 판단한다"],
  },
  q: [
    {
      k: "ttlWithJitter · 만료 시점을 흩기",
      qq: "기본 유효 기간과 흔들림 폭, 그리고 <b>0~1 사이의 값</b>을 받아 실제 유효 기간을 돌려주세요. <code>base + jitter * r</code> 을 <b>내림</b>합니다.",
      src: "function ttlWithJitter(base, jitter, r) {\n  return base;\n}",
      sol: "function ttlWithJitter(base, jitter, r) {\n  return Math.floor(base + jitter * r);\n}",
      tests: [["ttlWithJitter(100, 50, 0)", "100"],
              ["ttlWithJitter(100, 50, 1)", "150"],
              ["ttlWithJitter(100, 50, 0.5)", "125"]],
      edge: [["ttlWithJitter(100, 0, 0.7)", "100"],
             ["ttlWithJitter(0, 10, 0.35)", "3"]],
      ex: "같은 시각에 만든 캐시가 같은 시각에 만료되면, 그 순간 모든 요청이 원본으로 한꺼번에 몰립니다. 유효 기간을 조금씩 다르게 하면 만료가 흩어져 이 몰림이 사라져요.",
    },
    {
      k: "getOrMiss · 없음도 캐시하기",
      qq: "캐시와 열쇠를 받아 값을 돌려주세요. 캐시에 <b>'없음'(<code>null</code>)이 저장돼 있으면</b> 원본을 보지 말고 그대로 <code>null</code> 을 돌려줍니다. 원본을 본 횟수는 <code>calls</code> 에 셉니다.",
      src: "function getOrMiss(cache, key, origin, calls) {\n  if (cache.get(key)) return cache.get(key);\n  calls.n++;\n  const v = origin(key);\n  cache.set(key, v);\n  return v;\n}",
      sol: "function getOrMiss(cache, key, origin, calls) {\n  if (cache.has(key)) return cache.get(key);\n  calls.n++;\n  const v = origin(key);\n  cache.set(key, v);\n  return v;\n}",
      tests: [["(() => { const c = new Map([['a', null]]); const n = { n: 0 }; const v = getOrMiss(c, 'a', () => 'x', n); return [v, n.n]; })()", "[null, 0]"],
              ["(() => { const c = new Map(); const n = { n: 0 }; getOrMiss(c, 'a', () => null, n); getOrMiss(c, 'a', () => null, n); return n.n; })()", "1"],
              ["(() => { const c = new Map([['a', 'v']]); const n = { n: 0 }; return [getOrMiss(c, 'a', () => 'x', n), n.n]; })()", "['v', 0]"]],
      edge: [["(() => { const c = new Map([['a', 0]]); const n = { n: 0 }; return [getOrMiss(c, 'a', () => 9, n), n.n]; })()", "[0, 0]"]],
      ex: "값이 있는지를 참·거짓으로 판단하면 null 과 0 과 빈 문자열이 전부 '없음' 이 됩니다. 그래서 그 열쇠는 매번 원본까지 가요 — 오타 하나가 원본을 계속 두드리는 상황이 이렇게 생깁니다.",
    },
    {
      k: "hitRate · 적중률로 판단하기",
      qq: "적중 수와 빗나감 수를 받아 <b>적중률</b>을 돌려주세요. 요청이 <b>하나도 없으면</b> <code>0</code> 입니다.",
      src: "function hitRate(hits, misses) {\n  return hits / (hits + misses);\n}",
      sol: "function hitRate(hits, misses) {\n  const total = hits + misses;\n  return total > 0 ? hits / total : 0;\n}",
      tests: [["hitRate(90, 10)", "0.9"],
              ["hitRate(0, 0)", "0"],
              ["hitRate(0, 10)", "0"]],
      edge: [["hitRate(5, 0)", "1"]],
      ex: "요청이 없을 때 나누면 NaN 이 나오고, 그 값은 어떤 비교에서도 거짓이라 경보가 조용히 안 울립니다. 새벽처럼 조용한 시간대에 딱 이 상태가 돼요.",
    },
  ],
},
];
