/* 테스팅 실행형 2 — 테스트를 굴리는 쪽의 계산을 직접 만들어 본다.
   단언과 매처, 데이터 준비와 정리, 비동기와 재시도, 회귀와 선별 실행.
   첫 실행형 유닛과 겹치지 않는 함수만 다룬다. */
module.exports = [

/* ───────────── 단언과 매처 ───────────── */
{ track: "test", k: "부분만 견준다 · matchSubset", cat: "impl",
  q: "기대 객체의 <b>열쇠들만</b> 실제 객체와 견주어 전부 같으면 <code>true</code> 를 돌려주세요. 실제 쪽에 열쇠가 더 있어도 괜찮습니다. 값 비교는 <code>===</code> 입니다.",
  src: "function matchSubset(actual, expected) {\n  // TODO: 기대 쪽 열쇠만 훑으세요\n  return false;\n}",
  sol: "function matchSubset(actual, expected) {\n  if (!actual || typeof actual !== \"object\") return false;\n  return Object.keys(expected).every((k) => actual[k] === expected[k]);\n}",
  tests: [['matchSubset({a:1,b:2}, {a:1})', 'true'],
    ['matchSubset({a:1}, {a:1,b:2})', 'false'],
    ['matchSubset({a:1}, {a:2})', 'false'],
    ['matchSubset({a:1}, {})', 'true']],
  edge: [['matchSubset(null, {a:1})', 'false'], ['matchSubset({}, {})', 'true']],
  ex: "<code>toMatchObject</code> 계열 매처가 하는 일입니다. 응답에 <b>확인하고 싶은 것만</b> 적고 나머지는 무시하므로, 필드가 하나 늘었다고 테스트가 깨지지 않습니다.\n이것이 장점이자 위험입니다. 없어야 할 필드가 생겨도 통과하므로, <b>없음을 확인해야 하는 것</b>에는 쓰면 안 됩니다. 비밀번호 해시가 응답에 섞여 나오는 사고가 이런 느슨한 단언 아래에서 오래 살아남습니다.\n<code>every</code> 는 빈 배열에 <code>true</code> 를 돌려줍니다. 그래서 기대 객체가 비면 언제나 통과하는데, 실수로 빈 객체를 넘긴 테스트는 <b>아무것도 확인하지 않으면서 초록불</b>이 됩니다.\n실제 매처는 중첩까지 재귀로 봅니다. 여기서는 한 층만 보지만, 깊이가 늘수록 '무엇을 확인하지 않고 있는가' 를 알기 어려워진다는 성질은 같습니다." },

{ track: "test", k: "오류를 견준다 · throwsWith", cat: "impl",
  q: "함수를 실행해 던져진 오류 메시지가 지정한 조각을 <b>포함하면</b> <code>\"pass\"</code>, 다른 메시지면 <code>\"wrong\"</code>, 아예 안 던지면 <code>\"none\"</code> 을 돌려주세요.",
  src: "function throwsWith(fn, part) {\n  // TODO: try 로 감싸고 메시지를 견주세요\n  return \"none\";\n}",
  sol: "function throwsWith(fn, part) {\n  try {\n    fn();\n  } catch (e) {\n    return String(e.message).indexOf(part) >= 0 ? \"pass\" : \"wrong\";\n  }\n  return \"none\";\n}",
  tests: [['throwsWith(function(){ throw new Error("bad input"); }, "input")', '"pass"'],
    ['throwsWith(function(){ throw new Error("oops"); }, "input")', '"wrong"'],
    ['throwsWith(function(){ return 1; }, "input")', '"none"'],
    ['throwsWith(function(){ throw new Error("x"); }, "")', '"pass"']],
  edge: [['throwsWith(function(){ throw new Error("abc"); }, "abc")', '"pass"'],
    ['throwsWith(function(){ throw new Error(""); }, "z")', '"wrong"']],
  ex: "'오류가 나는지' 를 확인하는 테스트에서 가장 흔한 실수는 <b>함수를 부른 결과를 넘기는 것</b>입니다. 그러면 단언에 닿기도 전에 테스트가 터져 버립니다. 그래서 매처는 언제나 <b>함수 자체</b>를 받습니다.\n메시지까지 견주는 이유는 <b>엉뚱한 오류로도 통과하기</b> 때문입니다. 오타로 생긴 <code>undefined is not a function</code> 도 오류이므로, 조각을 지정하지 않으면 깨진 코드가 초록불을 받습니다.\n안 던진 경우와 다른 메시지로 던진 경우를 나눈 것이 이 함수의 핵심입니다. 실패 메시지가 <b>둘 중 어느 쪽인지</b> 알려 주면 원인을 찾는 시간이 크게 줄어듭니다.\n조각이 빈 문자열이면 언제나 포함으로 잡힙니다. 실제 도구에서도 그렇게 동작하므로, <b>메시지를 안 적은 것</b>과 <b>아무 메시지나 좋다는 것</b>은 구분되지 않습니다." },

{ track: "test", k: "실패한 자리를 짚는다 · firstDiff", cat: "debug",
  q: "두 배열을 앞에서부터 견주어 <b>처음 다른 자리</b>의 첨자를 돌려주세요. 길이만 다르면 짧은 쪽의 길이를, 완전히 같으면 <code>-1</code> 을 돌려줍니다.",
  src: "function firstDiff(a, b) {\n  // TODO: 짧은 쪽까지 훑고 길이도 보세요\n  return -1;\n}",
  sol: "function firstDiff(a, b) {\n  const n = Math.min(a.length, b.length);\n  for (let i = 0; i < n; i++) if (a[i] !== b[i]) return i;\n  return a.length === b.length ? -1 : n;\n}",
  tests: [['firstDiff([1,2,3],[1,9,3])', '1'],
    ['firstDiff([1,2],[1,2,3])', '2'],
    ['firstDiff([1,2],[1,2])', '-1'],
    ['firstDiff([],[])', '-1']],
  edge: [['firstDiff([1],[])', '0'], ['firstDiff([5,5],[5,6])', '1']],
  ex: "실패 메시지의 질을 정하는 계산입니다. '기대와 다릅니다' 만 나오면 100개짜리 배열에서 <b>눈으로 찾아야</b> 하지만, 첨자를 알려 주면 곧바로 그 자리를 봅니다.\n길이가 다를 때 짧은 쪽 길이를 돌려주는 것이 자연스러운 답입니다. 그 자리에서 한쪽은 값이 있고 한쪽은 없으므로, <b>처음 어긋난 자리</b>라는 뜻이 그대로 유지됩니다.\n앞에서부터 보는 것에도 이유가 있습니다. 대부분의 어긋남은 <b>맨 앞이나 맨 뒤</b>에서 생기는데, 앞에서 찾으면 정렬이 밀렸는지 값 하나가 틀렸는지가 첫 결과에서 드러납니다.\n좋은 테스트 도구는 여기서 한 걸음 더 갑니다 — 어긋난 자리 <b>앞뒤 몇 개를 함께</b> 보여 줍니다. 문맥 없이 첨자만 있으면 여전히 스크롤해야 하기 때문입니다." },

{ track: "test", k: "가까우면 같다 · nearlyEqualPct", cat: "impl",
  q: "두 수의 차이가 <b>기대값의 몇 퍼센트</b> 이내면 <code>true</code> 를 돌려주세요. 기대값이 0이면 실제도 정확히 0일 때만 참입니다.",
  src: "function nearlyEqualPct(actual, expected, pct) {\n  // TODO: 상대 오차로 견주세요\n  return actual === expected;\n}",
  sol: "function nearlyEqualPct(actual, expected, pct) {\n  if (expected === 0) return actual === 0;\n  return Math.abs(actual - expected) / Math.abs(expected) <= pct / 100;\n}",
  tests: [['nearlyEqualPct(102, 100, 5)', 'true'],
    ['nearlyEqualPct(120, 100, 5)', 'false'],
    ['nearlyEqualPct(0, 0, 1)', 'true'],
    ['nearlyEqualPct(1, 0, 100)', 'false']],
  edge: [['nearlyEqualPct(95, 100, 5)', 'true'], ['nearlyEqualPct(-102, -100, 5)', 'true']],
  ex: "절대 오차가 아니라 <b>상대 오차</b>로 견주는 이유는 크기가 다른 값에 같은 기준을 쓸 수 있기 때문입니다. 응답 시간 100ms 에서 5ms 는 작지만 10ms 에서 5ms 는 큽니다.\n기대값이 0일 때를 따로 처리한 것은 <b>0으로 나눌 수 없어서</b>입니다. 이 자리를 빼먹으면 결과가 <code>Infinity</code> 나 <code>NaN</code> 이 되어, 비교가 언제나 거짓이 되거나 조용히 통과합니다.\n음수에서도 맞게 동작하려면 <b>양쪽 모두</b> 절댓값을 씌워야 합니다. 분모의 절댓값을 빼먹으면 음수 기대값에서 부등호가 뒤집힙니다.\n성능 테스트에 이런 매처를 쓸 때는 조심해야 합니다. 기계마다 속도가 달라 퍼센트로도 흔들리므로, <b>여러 번 재서 중앙값</b>을 쓰거나 아예 상대 비교(예전 대비)로 바꾸는 편이 낫습니다." },

{ track: "test", k: "실패를 사람 말로 · describeFail", cat: "impl",
  q: "<code>[이름, 통과여부]</code> 목록에서 <code>\"3 중 1 실패: b\"</code> 형태의 요약을 만들어 주세요. 전부 통과면 <code>\"3 전부 통과\"</code>, 실패가 여럿이면 이름을 <code>\", \"</code> 로 잇습니다.",
  src: "function describeFail(results) {\n  // TODO: 실패한 이름을 모아 문장을 만드세요\n  return \"\";\n}",
  sol: "function describeFail(results) {\n  const bad = results.filter((r) => !r[1]).map((r) => r[0]);\n  const n = results.length;\n  if (!bad.length) return n + \" 전부 통과\";\n  return n + \" 중 \" + bad.length + \" 실패: \" + bad.join(\", \");\n}",
  tests: [['describeFail([["a",true],["b",false],["c",true]])', '"3 중 1 실패: b"'],
    ['describeFail([["a",true],["b",true]])', '"2 전부 통과"'],
    ['describeFail([["a",false],["b",false]])', '"2 중 2 실패: a, b"'],
    ['describeFail([])', '"0 전부 통과"']],
  edge: [['describeFail([["only",false]])', '"1 중 1 실패: only"'], ['describeFail([["x",true]])', '"1 전부 통과"']],
  ex: "테스트 러너의 마지막 한 줄입니다. 사람이 실제로 읽는 것은 대개 이 줄뿐이라, <b>여기에 무엇을 담느냐</b>가 도구의 인상을 정합니다.\n전체 개수를 함께 적는 것이 중요합니다. '1 실패' 만 있으면 3개 중 1개인지 300개 중 1개인지 모르는데, <b>비율이 곧 심각도</b>입니다.\n실패한 이름을 나열하는 것에는 한계가 있습니다. 100개가 실패하면 한 줄이 감당하지 못하므로, 실제 도구는 <b>앞 몇 개만 보이고 나머지는 개수로</b> 줄입니다. 요약은 짧을 때만 요약입니다.\n빈 목록에 '0 전부 통과' 가 나오는 것은 논리적으로는 맞지만 <b>의심해야 할 신호</b>입니다. 테스트를 하나도 못 찾은 상태가 통과처럼 보이면, 설정이 깨진 채로 CI 가 계속 초록불이 됩니다." },

/* ───────────── 준비와 정리 ───────────── */
{ track: "test", k: "정리는 거꾸로 · teardownOrder", cat: "impl",
  q: "준비 단계 이름 목록을 받아, 정리해야 할 순서(<b>역순</b>)로 돌려주세요. 준비 중 지정한 단계에서 실패했다면 <b>그 단계까지 성공한 것만</b> 정리합니다.",
  src: "function teardownOrder(steps, failedAt) {\n  // TODO: 실패 전까지 자르고 뒤집으세요\n  return [];\n}",
  sol: "function teardownOrder(steps, failedAt) {\n  const at = steps.indexOf(failedAt);\n  const done = at < 0 ? steps.slice() : steps.slice(0, at);\n  return done.reverse();\n}",
  tests: [['teardownOrder(["db","cache","server"], null)', '["server","cache","db"]'],
    ['teardownOrder(["db","cache","server"], "server")', '["cache","db"]'],
    ['teardownOrder(["db","cache"], "db")', '[]'],
    ['teardownOrder([], null)', '[]']],
  edge: [['teardownOrder(["a"], null)', '["a"]'], ['teardownOrder(["a","b"], "b")', '["a"]']],
  ex: "준비의 역순으로 정리하는 것은 <b>의존 방향</b> 때문입니다. 서버가 DB 를 쓰고 있으므로 DB 를 먼저 닫으면 서버가 멈추다 오류를 냅니다.\n중간에 실패했을 때가 진짜 어려운 자리입니다. <b>성공한 것만 정리해야</b> 하는데, 이것을 못 하면 두 가지 중 하나가 일어납니다 — 아직 만들지 않은 것을 정리하려다 오류가 나거나, 이미 만든 것이 남아 다음 테스트를 오염시킵니다.\n그래서 준비를 <b>스택처럼</b> 쌓고 정리는 스택에서 빼는 방식이 널리 쓰입니다. 각 단계가 성공한 직후에 자기 정리 함수를 등록하면 이 계산이 저절로 맞습니다.\n정리 중에 오류가 나도 <b>나머지 정리는 계속해야</b> 합니다. 첫 오류에서 멈추면 그 아래 것들이 전부 남으므로, 오류를 모아 두었다가 마지막에 보고하는 방식이 안전합니다." },

{ track: "test", k: "남은 것을 찾는다 · leakedKeys", cat: "debug",
  q: "테스트 전후의 열쇠 목록을 받아 <b>뒤에만 있는</b> 열쇠를 정렬해 돌려주세요. 사라진 것은 세지 않습니다.",
  src: "function leakedKeys(before, after) {\n  // TODO: 앞에 없고 뒤에만 있는 것을 고르세요\n  return [];\n}",
  sol: "function leakedKeys(before, after) {\n  const had = new Set(before);\n  return after.filter((k) => !had.has(k)).sort();\n}",
  tests: [['leakedKeys(["a"], ["a","b"])', '["b"]'],
    ['leakedKeys(["a","b"], ["a"])', '[]'],
    ['leakedKeys([], ["z","y"])', '["y","z"]'],
    ['leakedKeys(["a"], ["a"])', '[]']],
  edge: [['leakedKeys([], [])', '[]'], ['leakedKeys(["x"], ["x","x"])', '[]']],
  ex: "테스트가 <b>흔적을 남기는지</b> 확인하는 검사입니다. 남은 행 하나, 남은 파일 하나가 다음 테스트를 통과시키거나 실패시키면 원인을 찾기가 아주 어렵습니다.\n사라진 것을 세지 않는 것은 선택입니다. 지우는 테스트라면 없어지는 것이 정상이므로, <b>늘어난 것만</b> 보는 편이 오탐이 적습니다. 다만 공용 데이터를 지우는 사고는 이 검사로 못 잡습니다.\n정렬해서 돌려주는 이유는 <b>실패 메시지가 매번 같아야</b> 하기 때문입니다. 순서가 흔들리면 같은 문제가 다른 메시지로 보여, 이미 아는 문제인지 새 문제인지 헷갈립니다.\n이 검사를 모든 테스트 뒤에 자동으로 붙여 두면 오염의 원인을 <b>만들어진 그 자리에서</b> 잡을 수 있습니다. 나중에 다른 테스트가 이상하게 실패한 뒤 거슬러 올라가는 것보다 훨씬 쌉니다." },

{ track: "test", k: "격리된 이름을 만든다 · isolatedName", cat: "impl",
  q: "기본 이름과 워커 번호, 실행 번호를 받아 <code>\"user_w2_r7\"</code> 형태의 이름을 돌려주세요. 워커 번호가 0이면 <code>\"user_r7\"</code> 처럼 워커 부분을 뺍니다.",
  src: "function isolatedName(base, worker, run) {\n  // TODO: 워커가 0이면 그 부분을 빼세요\n  return base;\n}",
  sol: "function isolatedName(base, worker, run) {\n  const mid = worker ? \"_w\" + worker : \"\";\n  return base + mid + \"_r\" + run;\n}",
  tests: [['isolatedName("user", 2, 7)', '"user_w2_r7"'],
    ['isolatedName("user", 0, 7)', '"user_r7"'],
    ['isolatedName("db", 1, 1)', '"db_w1_r1"'],
    ['isolatedName("x", 0, 0)', '"x_r0"']],
  edge: [['isolatedName("", 3, 4)', '"_w3_r4"'], ['isolatedName("t", 10, 100)', '"t_w10_r100"']],
  ex: "테스트를 병렬로 돌릴 때 가장 먼저 부딪히는 문제가 <b>이름 충돌</b>입니다. 두 워커가 같은 DB 이름이나 같은 임시 폴더를 쓰면 서로를 밟습니다.\n워커 번호와 실행 번호를 둘 다 넣는 이유가 다릅니다. 워커 번호는 <b>같은 시각의 충돌</b>을, 실행 번호는 <b>앞 실행이 남긴 것</b>과의 충돌을 막습니다. 하나만으로는 부족합니다.\n무작위 이름을 쓰는 방법도 있지만 단점이 큽니다 — 실패를 재현하기 어렵고, 정리에 실패하면 <b>이름을 모르는 쓰레기</b>가 쌓입니다. 규칙적인 이름이면 나중에 한 번에 걷어 낼 수 있습니다.\n워커 0에서 접미사를 빼는 것은 <b>단일 실행의 읽기 쉬움</b>을 위한 배려입니다. 혼자 돌릴 때까지 긴 이름을 보면 로그가 지저분해집니다." },

{ track: "test", k: "고정 시각을 정한다 · fixedNow", cat: "impl",
  q: "기준 시각(ms)과 앞으로 감을 시간 목록을 받아, 각 시점의 시각을 <b>누적해서</b> 배열로 돌려주세요. 음수는 무시합니다.",
  src: "function fixedNow(start, ticks) {\n  // TODO: 음수를 걸러 내며 누적하세요\n  return [];\n}",
  sol: "function fixedNow(start, ticks) {\n  const out = [];\n  let now = start;\n  ticks.forEach((t) => { if (t >= 0) { now += t; out.push(now); } });\n  return out;\n}",
  tests: [['fixedNow(1000, [10, 20])', '[1010,1030]'],
    ['fixedNow(0, [5])', '[5]'],
    ['fixedNow(100, [10, -5, 10])', '[110,120]'],
    ['fixedNow(50, [])', '[]']],
  edge: [['fixedNow(0, [0])', '[0]'], ['fixedNow(7, [-1,-2])', '[]']],
  ex: "시간을 쓰는 코드는 <b>고정하지 않으면 테스트할 수 없습니다.</b> 만료·타임아웃·요금 계산이 전부 '지금' 에 기대는데, 진짜 시계로는 같은 상황을 다시 만들 수 없습니다.\n가짜 시계의 핵심은 <b>앞으로만 간다</b>는 것입니다. 뒤로 가는 시계를 허용하면 실제로는 일어날 수 없는 상황을 시험하게 되어, 통과해도 뜻이 없거나 반대로 못 고칠 실패가 납니다.\n실제 시스템에서도 시계는 가끔 뒤로 갑니다. 시간 동기화가 보정할 때인데, 그래서 <b>경과 시간을 재는 자리</b>에는 벽시계 대신 단조 증가 시계를 씁니다.\n시각을 인자로 받거나 주입받게 만들어 두면 이런 가짜 시계가 필요 없어지기도 합니다. 테스트하기 쉬운 설계란 대개 <b>바깥 세계를 인자로 받는 설계</b>입니다." },

{ track: "test", k: "무엇을 다시 쓸까 · reuseVerdict", cat: "design",
  q: "준비 비용(ms)과 반복 횟수, 오염 위험 여부를 받아 <code>\"reuse\"</code> 또는 <code>\"fresh\"</code> 를 돌려주세요. 오염 위험이 있으면 언제나 새로 만들고, 아니면 <b>총 비용이 500ms 를 넘을 때</b> 다시 씁니다.",
  src: "function reuseVerdict(setupMs, times, dirty) {\n  // TODO: 위험을 먼저 보고 비용을 견주세요\n  return \"fresh\";\n}",
  sol: "function reuseVerdict(setupMs, times, dirty) {\n  if (dirty) return \"fresh\";\n  return setupMs * times > 500 ? \"reuse\" : \"fresh\";\n}",
  tests: [['reuseVerdict(100, 10, false)', '"reuse"'],
    ['reuseVerdict(100, 10, true)', '"fresh"'],
    ['reuseVerdict(10, 10, false)', '"fresh"'],
    ['reuseVerdict(600, 1, false)', '"reuse"']],
  edge: [['reuseVerdict(500, 1, false)', '"fresh"'], ['reuseVerdict(1, 1000, false)', '"reuse"']],
  ex: "테스트를 빠르게 만들려는 유혹은 대개 <b>준비를 재사용하자</b>로 나타납니다. 이 함수는 그 판단을 두 단계로 나눕니다 — 먼저 안전, 그 다음 비용입니다.\n순서가 뒤바뀌면 안 됩니다. 비용을 먼저 보면 '느리니까 재사용하자' 로 시작해 <b>오염을 나중에 감당하게</b> 되는데, 그때는 이미 테스트들이 서로 얽혀 있어 되돌리기 어렵습니다.\n오염 위험이란 <b>테스트가 상태를 바꾸는가</b>입니다. 읽기만 하는 테스트는 얼마든지 나눠 써도 되지만, 쓰는 테스트는 순서에 따라 결과가 달라집니다.\n중간 답도 있습니다 — 비싼 준비는 한 번 하되 <b>테스트마다 되돌리기</b>를 겁니다. DB 라면 트랜잭션을 열고 끝에 되돌리는 방식이 재사용의 속도와 격리의 안전을 함께 얻습니다." },

/* ───────────── 비동기와 흔들림 ───────────── */
{ track: "test", k: "기다릴 만큼만 · pollPlan", cat: "impl",
  q: "확인 간격과 제한 시간을 받아 <b>확인하는 시각</b>들을 배열로 돌려주세요. 제한 시각과 정확히 같은 시점까지 포함합니다. 간격이 0 이하면 빈 배열입니다.",
  src: "function pollPlan(everyMs, timeoutMs) {\n  // TODO: 간격만큼 늘려 가며 제한까지 쌓으세요\n  return [];\n}",
  sol: "function pollPlan(everyMs, timeoutMs) {\n  if (!(everyMs > 0)) return [];\n  const out = [];\n  for (let t = everyMs; t <= timeoutMs; t += everyMs) out.push(t);\n  return out;\n}",
  tests: [['pollPlan(100, 350)', '[100,200,300]'],
    ['pollPlan(100, 300)', '[100,200,300]'],
    ['pollPlan(500, 300)', '[]'],
    ['pollPlan(0, 100)', '[]']],
  edge: [['pollPlan(50, 50)', '[50]'], ['pollPlan(-1, 100)', '[]']],
  ex: "'조건이 만족될 때까지 기다린다' 를 구현하는 방법입니다. 고정 시간을 자는 대신 <b>짧게 여러 번 확인</b>하면 대개 훨씬 빨리 끝나고, 느린 기계에서도 안 깨집니다.\n<code>sleep(2000)</code> 이 나쁜 이유가 여기 있습니다 — 빠른 기계에서는 낭비고 느린 기계에서는 모자랍니다. 같은 코드가 <b>어떤 기계에서는 통과하고 어떤 기계에서는 실패</b>하는 전형적인 원인입니다.\n간격이 제한보다 크면 한 번도 확인하지 못합니다. 이 경우를 빈 배열로 정직하게 돌려주면, 부르는 쪽이 '기다렸는데 확인을 안 했다' 를 알아챌 수 있습니다.\n제일 좋은 것은 폴링조차 없애는 것입니다. 사건을 기다릴 수 있으면 즉시 반응하므로, <b>폴링은 사건을 받을 수 없을 때의 차선</b>입니다." },

{ track: "test", k: "몇 번 만에 성공했나 · retryUntil", cat: "impl",
  q: "각 시도의 성공 여부 목록과 최대 시도 횟수를 받아 <code>[성공여부, 시도횟수]</code> 를 돌려주세요. 목록이 모자라면 그 뒤는 실패로 봅니다.",
  src: "function retryUntil(results, maxTries) {\n  // TODO: 처음 성공한 자리를 찾으세요\n  return [false, 0];\n}",
  sol: "function retryUntil(results, maxTries) {\n  for (let i = 0; i < maxTries; i++) {\n    if (results[i]) return [true, i + 1];\n  }\n  return [false, maxTries];\n}",
  tests: [['retryUntil([false,true], 3)', '[true,2]'],
    ['retryUntil([true], 3)', '[true,1]'],
    ['retryUntil([false,false,false], 3)', '[false,3]'],
    ['retryUntil([], 2)', '[false,2]']],
  edge: [['retryUntil([false,true], 1)', '[false,1]'], ['retryUntil([true,true], 5)', '[true,1]']],
  ex: "재시도를 넣으면 흔들리는 테스트가 초록불이 됩니다. 그래서 편하지만, <b>흔들림 자체는 그대로 남습니다.</b>\n시도 횟수를 함께 돌려주는 것이 이 함수의 목적입니다. '통과' 만 기록하면 재시도로 겨우 붙은 것과 한 번에 붙은 것이 구분되지 않아, <b>망가지고 있다는 신호</b>를 놓칩니다.\n최대 횟수로 잘리는 자리도 정확해야 합니다. 목록에 성공이 있어도 최대 횟수 밖이면 실패인데, 이 경계를 틀리면 실제로는 실패할 상황에서 통과 판정이 납니다.\n재시도는 <b>진짜 불확실한 바깥 세계</b>에만 씁니다. 네트워크 호출은 그럴 만하지만, 순수한 계산에 재시도가 필요하다면 그 코드에 경합이 있다는 뜻이라 재시도로 덮을 문제가 아닙니다." },

{ track: "test", k: "흔들림을 재본다 · flakeRate", cat: "ops",
  q: "실행별 통과 여부 목록에서 <b>실패 비율을 백분율</b>(소수 첫째 자리 반올림)로 돌려주세요. 실행이 없으면 0 입니다.",
  src: "function flakeRate(runs) {\n  // TODO: 실패 수를 전체로 나누세요\n  return 0;\n}",
  sol: "function flakeRate(runs) {\n  if (!runs.length) return 0;\n  const bad = runs.filter((r) => !r).length;\n  return Math.round((bad / runs.length) * 1000) / 10;\n}",
  tests: [['flakeRate([true,true,false,true])', '25'],
    ['flakeRate([true,true])', '0'],
    ['flakeRate([false,false])', '100'],
    ['flakeRate([])', '0']],
  edge: [['flakeRate([true,true,true,false,false,false,true])', '42.9'], ['flakeRate([false])', '100']],
  ex: "흔들리는 테스트를 다룰 때 첫 단계는 <b>얼마나 흔들리는지 재는 것</b>입니다. 느낌으로는 '가끔' 인데 재 보면 30% 인 경우가 흔합니다.\n비율이 정해지면 판단이 쉬워집니다. 1% 라면 재시도로 넘기고 배경에 기록해 둘 수 있지만, 30% 라면 <b>그 테스트는 정보를 주지 않습니다</b> — 초록불도 빨간불도 믿을 수 없기 때문입니다.\n0% 와 100% 는 흔들림이 아닙니다. 언제나 실패하는 것은 <b>진짜 버그이거나 잘못 쓴 테스트</b>라, 흔들림 목록에서 빼고 곧바로 고쳐야 합니다.\n측정에는 반복이 필요합니다. 열 번 돌려 한 번 실패한 것과 백 번 돌려 열 번 실패한 것은 같은 10% 지만 <b>확신의 크기가 다릅니다.</b> 표본이 작으면 숫자를 너무 믿지 않습니다." },

{ track: "test", k: "순서에 기대는가 · orderDependent", cat: "debug",
  q: "정방향 실행 결과와 역방향 실행 결과 목록을 받아, <b>결과가 달라진</b> 테스트 이름을 정렬해 돌려주세요. 입력은 <code>[이름, 통과여부]</code> 목록입니다.",
  src: "function orderDependent(forward, backward) {\n  // TODO: 같은 이름끼리 결과를 견주세요\n  return [];\n}",
  sol: "function orderDependent(forward, backward) {\n  const b = new Map(backward);\n  return forward.filter((f) => b.has(f[0]) && b.get(f[0]) !== f[1])\n    .map((f) => f[0]).sort();\n}",
  tests: [['orderDependent([["a",true],["b",true]], [["a",true],["b",false]])', '["b"]'],
    ['orderDependent([["a",true]], [["a",true]])', '[]'],
    ['orderDependent([["a",false]], [["a",true]])', '["a"]'],
    ['orderDependent([["a",true]], [["z",true]])', '[]']],
  edge: [['orderDependent([], [])', '[]'], ['orderDependent([["y",true],["x",true]], [["y",false],["x",false]])', '["x","y"]']],
  ex: "순서를 뒤집어 돌려 보는 것은 <b>테스트 간 오염을 찾는 가장 싼 방법</b>입니다. 결과가 달라진 테스트가 있으면 앞선 무언가가 흔적을 남기고 있다는 뜻입니다.\n무작위 순서로 매번 돌리는 도구도 있습니다. 더 많은 조합을 시험하지만 <b>재현이 어렵다</b>는 단점이 있어, 대개 순서를 정하는 씨앗 값을 실패 메시지에 함께 적습니다.\n어느 쪽이 진짜인지는 이 결과만으로 알 수 없습니다. 정방향에서 통과하고 역방향에서 실패했다면, <b>앞선 테스트가 만들어 준 상태</b>에 기대고 있었을 가능성이 큽니다.\n한쪽에만 있는 이름은 견주지 않았습니다. 실행이 중간에 멈춰 목록 길이가 다를 수 있는데, 그것을 '달라졌다' 로 세면 <b>진짜 순서 의존</b>이 묻힙니다." },

{ track: "test", k: "먼저 알려 주는 순서 · failFastOrder", cat: "ops",
  q: "<code>[이름, 초, 최근실패여부]</code> 목록을 <b>최근 실패한 것 먼저</b>, 그 안에서는 <b>빠른 것 먼저</b> 정렬해 이름 배열로 돌려주세요.",
  src: "function failFastOrder(tests) {\n  // TODO: 최근 실패를 앞으로, 같으면 빠른 것 먼저\n  return [];\n}",
  sol: "function failFastOrder(tests) {\n  return tests.slice()\n    .sort((a, b) => (Number(b[2]) - Number(a[2])) || (a[1] - b[1]))\n    .map((t) => t[0]);\n}",
  tests: [['failFastOrder([["a",1,false],["b",5,true]])', '["b","a"]'],
    ['failFastOrder([["a",5,true],["b",1,true]])', '["b","a"]'],
    ['failFastOrder([["a",2,false],["b",1,false]])', '["b","a"]'],
    ['failFastOrder([])', '[]']],
  edge: [['failFastOrder([["only",9,false]])', '["only"]'], ['failFastOrder([["a",1,true],["b",1,false]])', '["a","b"]']],
  ex: "스위트가 길어지면 <b>실패를 언제 아느냐</b>가 개발 속도를 정합니다. 20분짜리 스위트라도 첫 30초에 알려 주면 그동안 다른 일을 할 수 있습니다.\n최근 실패한 것을 앞에 두는 이유는 <b>같은 것이 또 실패할 확률이 높기</b> 때문입니다. 고치는 중인 자리를 계속 건드리고 있으니 자연스러운 우선순위입니다.\n빠른 것을 먼저 두는 것도 같은 목적입니다. 같은 확률이라면 <b>답을 빨리 주는 쪽</b>이 낫습니다. 단위 테스트를 통합 테스트보다 먼저 돌리는 관행이 이 계산의 결과입니다.\n주의할 것은 <b>순서를 바꿔도 결과가 같아야 한다</b>는 전제입니다. 순서에 기대는 테스트가 남아 있으면 이런 최적화가 곧바로 거짓 실패를 만듭니다." },

/* ───────────── 회귀와 선별 ───────────── */
{ track: "test", k: "바뀐 것만 돌린다 · selectImpacted", cat: "ops",
  q: "테스트별 의존 파일 목록과 바뀐 파일 목록을 받아, <b>하나라도 겹치는</b> 테스트 이름을 정렬해 돌려주세요. 입력은 <code>[이름, 파일배열]</code> 목록입니다.",
  src: "function selectImpacted(tests, changed) {\n  // TODO: 겹치는 파일이 있는지 보세요\n  return [];\n}",
  sol: "function selectImpacted(tests, changed) {\n  const set = new Set(changed);\n  return tests.filter((t) => t[1].some((f) => set.has(f)))\n    .map((t) => t[0]).sort();\n}",
  tests: [['selectImpacted([["a",["x.js"]],["b",["y.js"]]], ["x.js"])', '["a"]'],
    ['selectImpacted([["a",["x.js","y.js"]]], ["y.js"])', '["a"]'],
    ['selectImpacted([["a",["x.js"]]], ["z.js"])', '[]'],
    ['selectImpacted([], ["x.js"])', '[]']],
  edge: [['selectImpacted([["a",[]]], ["x.js"])', '[]'], ['selectImpacted([["b",["x"]],["a",["x"]]], ["x"])', '["a","b"]']],
  ex: "큰 저장소에서 전체 스위트를 매번 돌릴 수 없을 때 쓰는 방법입니다. <b>바뀐 파일에 닿는 테스트만</b> 골라 돌리면 시간이 크게 줄어듭니다.\n위험도 분명합니다. 의존 목록이 <b>실제보다 좁으면</b> 돌려야 할 테스트를 빼먹습니다. 설정 파일, 환경 변수, 데이터 파일처럼 코드가 아닌 의존은 특히 놓치기 쉽습니다.\n그래서 실제로는 두 겹으로 씁니다 — 매 커밋에는 고른 것만 돌리고, <b>병합 전이나 밤에는 전부</b> 돌립니다. 빠른 되먹임과 안전망을 함께 가져가는 방식입니다.\n의존 목록은 손으로 적으면 곧 낡습니다. 실행 중 <b>실제로 읽은 파일</b>을 기록해 자동으로 만드는 것이 유지되는 유일한 방법입니다." },

{ track: "test", k: "예전과 달라졌다 · snapshotDiff", cat: "review",
  q: "예전 스냅샷 객체와 지금 값 객체를 받아 <code>[\"added\"|\"removed\"|\"changed\", 열쇠]</code> 쌍의 배열을 <b>열쇠 사전순</b>으로 돌려주세요. 같은 것은 담지 않습니다.",
  src: "function snapshotDiff(old, now) {\n  // TODO: 양쪽 열쇠를 모아 종류를 정하세요\n  return [];\n}",
  sol: "function snapshotDiff(old, now) {\n  const keys = [...new Set(Object.keys(old).concat(Object.keys(now)))].sort();\n  const out = [];\n  keys.forEach((k) => {\n    if (!(k in old)) out.push([\"added\", k]);\n    else if (!(k in now)) out.push([\"removed\", k]);\n    else if (old[k] !== now[k]) out.push([\"changed\", k]);\n  });\n  return out;\n}",
  tests: [['snapshotDiff({a:1}, {a:1,b:2})', '[["added","b"]]'],
    ['snapshotDiff({a:1,b:2}, {a:1})', '[["removed","b"]]'],
    ['snapshotDiff({a:1}, {a:9})', '[["changed","a"]]'],
    ['snapshotDiff({a:1}, {a:1})', '[]']],
  edge: [['snapshotDiff({}, {})', '[]'], ['snapshotDiff({b:1,a:1}, {a:2,c:3})', '[["changed","a"],["removed","b"],["added","c"]]']],
  ex: "스냅샷 테스트가 실패했을 때 사람이 보는 것이 이 목록입니다. <b>무엇이 늘고 줄고 바뀌었는지</b>가 한눈에 보이지 않으면 통째로 갱신해 버리게 됩니다.\n스냅샷의 가장 큰 위험이 그 <b>무심한 갱신</b>입니다. 실패할 때마다 갱신 명령을 누르면 스냅샷은 '현재 동작을 적어 둔 것' 이 되어 아무것도 지키지 않습니다.\n종류를 셋으로 나눈 데 뜻이 있습니다 — <b>추가</b>는 대개 안전하고, <b>변경</b>은 확인이 필요하며, <b>삭제</b>는 호환을 깨는 신호입니다. 같은 실패라도 심각도가 다릅니다.\n스냅샷은 <b>작고 뜻이 분명할수록</b> 쓸모 있습니다. 화면 전체를 담으면 사소한 변경에도 매번 실패해, 결국 아무도 내용을 읽지 않게 됩니다." },

{ track: "test", k: "얼마나 좁혔나 · narrowSteps", cat: "debug",
  q: "후보 개수를 받아 <b>절반씩 좁힐 때</b> 필요한 최대 시도 횟수를 돌려주세요. 후보가 1 이하면 0 입니다.",
  src: "function narrowSteps(n) {\n  // TODO: 절반씩 줄이며 세세요\n  return 0;\n}",
  sol: "function narrowSteps(n) {\n  let left = n, steps = 0;\n  while (left > 1) { left = Math.ceil(left / 2); steps++; }\n  return steps;\n}",
  tests: [['narrowSteps(8)', '3'],
    ['narrowSteps(1)', '0'],
    ['narrowSteps(100)', '7'],
    ['narrowSteps(0)', '0']],
  edge: [['narrowSteps(2)', '1'], ['narrowSteps(3)', '2']],
  ex: "실패의 원인을 찾을 때 <b>절반씩 지워 가며</b> 좁히는 방법의 비용입니다. 후보 100개를 7번이면 하나로 줄일 수 있다는 뜻이라, 손으로 하나씩 보는 것과 비교가 되지 않습니다.\n같은 계산이 여러 곳에 나옵니다 — 어느 커밋이 깨뜨렸는지, 어느 테스트가 오염시키는지, 어느 설정이 문제인지가 전부 반씩 자르는 문제입니다.\n<b>올림</b>이 중요합니다. 홀수를 반으로 나누면 큰 쪽이 남으므로, 내림으로 계산하면 실제보다 적게 나옵니다. 최악의 경우를 세는 것이 목적이니 큰 쪽을 따라가야 합니다.\n전제가 하나 있습니다 — <b>확인이 정확해야</b> 합니다. 흔들리는 테스트로 좁히면 잘못된 절반을 버리게 되어, 끝까지 가도 엉뚱한 답이 나옵니다." },

{ track: "test", k: "느려진 것을 잡는다 · slowdown", cat: "perf",
  q: "예전 시간과 지금 시간, 허용 배수를 받아 <code>[\"ok\"|\"slower\", 배수]</code> 를 돌려주세요. 배수는 소수 둘째 자리 반올림이고, 예전 시간이 0 이하면 <code>[\"ok\", 0]</code> 입니다.",
  src: "function slowdown(before, after, limit) {\n  // TODO: 비율을 구해 허용 배수와 견주세요\n  return [\"ok\", 0];\n}",
  sol: "function slowdown(before, after, limit) {\n  if (!(before > 0)) return [\"ok\", 0];\n  const r = Math.round((after / before) * 100) / 100;\n  return [r > limit ? \"slower\" : \"ok\", r];\n}",
  tests: [['slowdown(100, 250, 2)', '["slower",2.5]'],
    ['slowdown(100, 150, 2)', '["ok",1.5]'],
    ['slowdown(100, 200, 2)', '["ok",2]'],
    ['slowdown(0, 50, 2)', '["ok",0]']],
  edge: [['slowdown(100, 50, 2)', '["ok",0.5]'], ['slowdown(3, 10, 2)', '["slower",3.33]']],
  ex: "성능 회귀를 잡는 가장 실용적인 방법은 절대 시간이 아니라 <b>예전 대비 배수</b>를 보는 것입니다. 기계가 달라도 비율은 비교적 안정적입니다.\n허용 배수를 두는 이유는 측정이 흔들리기 때문입니다. 1.1배쯤은 늘 나므로 그것까지 실패로 잡으면 <b>아무도 안 보는 경고</b>가 됩니다.\n경계에서 통과시킨 것은 의도된 선택입니다. '두 배까지 허용' 이라 적어 두었으면 정확히 두 배는 허용해야, 문서와 동작이 어긋나지 않습니다.\n빨라진 경우도 <b>기록해 둘 값어치</b>가 있습니다. 예상치 못하게 빨라졌다면 최적화가 아니라 일을 덜 하고 있는 것일 수 있어, 성능 지표가 정확성 회귀를 먼저 알려 주기도 합니다." },

{ track: "test", k: "무엇을 먼저 고칠까 · triageOrder", cat: "review",
  q: "<code>[이름, 영향받는사용자, 우회가능]</code> 목록을 <b>우회 불가 먼저</b>, 그 안에서 <b>영향 큰 순</b>으로 정렬해 이름 배열로 돌려주세요.",
  src: "function triageOrder(bugs) {\n  // TODO: 우회 가능 여부를 먼저 보세요\n  return [];\n}",
  sol: "function triageOrder(bugs) {\n  return bugs.slice()\n    .sort((a, b) => (Number(a[2]) - Number(b[2])) || (b[1] - a[1]))\n    .map((x) => x[0]);\n}",
  tests: [['triageOrder([["a",100,true],["b",10,false]])', '["b","a"]'],
    ['triageOrder([["a",10,false],["b",100,false]])', '["b","a"]'],
    ['triageOrder([["a",5,true],["b",50,true]])', '["b","a"]'],
    ['triageOrder([])', '[]']],
  edge: [['triageOrder([["only",1,true]])', '["only"]'], ['triageOrder([["a",0,false],["b",0,true]])', '["a","b"]']],
  ex: "실패가 여럿일 때 <b>무엇부터 고칠지</b>를 규칙으로 만든 것입니다. 매번 감으로 정하면 목소리 큰 쪽이 이기고, 진짜 급한 것이 밀립니다.\n우회 가능 여부를 사람 수보다 먼저 본 데 이유가 있습니다. 우회할 수 있으면 <b>지금 당장 막히는 사람은 없으므로</b>, 아무리 많은 사람에게 영향을 줘도 조금 기다릴 수 있습니다.\n영향받는 사람 수는 <b>추정이지 사실이 아닙니다.</b> 그래서 이 순서는 출발점이지 결론이 아니고, 데이터로 시작해 사람이 조정하는 것이 현실적입니다.\n빠진 축이 하나 있습니다 — <b>고치는 비용</b>입니다. 5분이면 고칠 중간 문제를 며칠 걸릴 큰 문제 앞에 두는 것이 대개 합리적이라, 실제 분류에는 이 값도 함께 봅니다." },

];
