/* Testing 실행형 — 테스트 도구가 속으로 하는 계산을 직접 만들어 본다.
   비교(deep equal), 경계값 생성, 축소(shrink), 테스트 더블, 커버리지 집계,
   백분위와 회귀 판정, 샤드 분배, 플레이키 탐지.
   '프레임워크가 알아서 해 준다' 를 '내가 만들 수 있다' 로 바꾸는 것이 목적이다. */
module.exports = [

/* ───────────── 판정과 비교 ───────────── */
{ track: "test", k: "깊은 비교를 만든다 · deepEqual", cat: "internals",
  q: "두 값이 <b>구조까지 같은지</b> 판정해 주세요. 원시값은 <code>===</code>, 배열과 객체는 키·길이·각 값을 재귀로 비교합니다. 배열과 객체는 서로 같지 않습니다.",
  src: "function deepEqual(a, b) {\n  // TODO: 원시값 먼저, 그다음 구조를 재귀로 보세요\n  return a === b;\n}",
  sol: "function deepEqual(a, b) {\n  if (a === b) return true;\n  if (typeof a !== \"object\" || typeof b !== \"object\" || !a || !b) return false;\n  if (Array.isArray(a) !== Array.isArray(b)) return false;\n  const ka = Object.keys(a).sort();\n  const kb = Object.keys(b).sort();\n  if (ka.length !== kb.length) return false;\n  return ka.every((k, i) => k === kb[i] && deepEqual(a[k], b[k]));\n}",
  tests: [['deepEqual({a:1},{a:1})', 'true'],
    ['deepEqual([1,2],[1,2])', 'true'],
    ['deepEqual({a:1},{a:1,b:2})', 'false'],
    ['deepEqual([1,2],[2,1])', 'false']],
  edge: [['deepEqual(null,null)', 'true'], ['deepEqual({},[])', 'false']],
  ex: "<code>toEqual</code> 이 하는 일이 정확히 이것입니다. <code>===</code> 는 객체를 <b>같은 자리인가</b>로 비교하므로, 내용이 같아도 다른 객체면 거짓입니다. 테스트에서 필요한 것은 거의 언제나 <b>내용 비교</b>라 프레임워크가 이 함수를 따로 제공합니다.\n키를 정렬한 뒤 비교하는 것이 중요합니다. <code>{a:1,b:2}</code> 와 <code>{b:2,a:1}</code> 은 <b>같아야</b> 하는데, <code>JSON.stringify</code> 로 비교하면 키 순서가 달라 거짓이 나옵니다. 문자열 비교로 어설프게 때우면 정확히 이 지점에서 조용히 틀립니다.\n배열과 객체를 구분하는 줄도 빼놓을 수 없습니다. <code>Object.keys([])</code> 와 <code>Object.keys({})</code> 는 둘 다 빈 배열이라, 그 검사가 없으면 <code>[]</code> 와 <code>{}</code> 가 같다고 나옵니다.\n실제 프레임워크는 여기서 더 나아가 <code>Date</code>·<code>Map</code>·<code>Set</code>·순환 참조까지 다룹니다. 다만 뼈대는 이 여덟 줄이고, 나머지는 특수한 타입을 하나씩 더한 것뿐입니다." },

{ track: "test", k: "소수 비교의 허용 오차 · approxEqual", cat: "debug",
  q: "부동소수점 두 값이 <b>사실상 같은지</b> 판정해 주세요. 허용 오차는 <b>상대적</b>으로 봅니다 — 두 값 중 큰 절댓값(최소 1)에 <code>eps</code> 를 곱한 만큼까지 같다고 봅니다.",
  src: "function approxEqual(a, b, eps) {\n  // TODO: 차이를 값의 크기에 비례해 재세요\n  return a === b;\n}",
  sol: "function approxEqual(a, b, eps) {\n  if (a === b) return true;\n  const scale = Math.max(Math.abs(a), Math.abs(b), 1);\n  return Math.abs(a - b) <= eps * scale;\n}",
  tests: [['approxEqual(0.1+0.2, 0.3, 1e-9)', 'true'],
    ['approxEqual(1, 1.5, 0.1)', 'false'],
    ['approxEqual(1000000, 1000000.5, 1e-6)', 'true'],
    ['approxEqual(0, 1e-12, 1e-9)', 'true']],
  edge: [['approxEqual(0, 0, 0)', 'true'], ['approxEqual(1, 2, 0)', 'false']],
  ex: "<code>0.1 + 0.2 === 0.3</code> 이 거짓인 것은 자바스크립트의 결함이 아니라 <b>2진 부동소수점의 성질</b>입니다. 0.1 을 2진법으로 정확히 적을 수 없어서 아주 작은 오차가 남습니다. 그래서 소수를 다루는 테스트는 <code>toBe</code> 가 아니라 <code>toBeCloseTo</code> 를 씁니다.\n<b>절대 오차만 쓰면 큰 수에서 무너집니다.</b> '0.0001 이내' 라는 기준은 1 근처에서는 엄격하지만 1,000,000 근처에서는 표현 가능한 최소 간격보다도 작아 영영 만족되지 않습니다. 그래서 값의 크기에 비례하는 <b>상대 오차</b>를 함께 씁니다.\n<code>Math.max(..., 1)</code> 이 있는 이유는 0 근처 때문입니다. 순수한 상대 오차만 쓰면 <code>0</code> 과 <code>1e-12</code> 의 상대 차이가 무한대가 되어 절대 같다고 하지 못합니다. 두 방식을 섞는 것이 실무의 표준적인 답입니다.\n돈을 다룬다면 애초에 소수를 쓰지 않는 것이 정답입니다. 원 단위 정수나 십진 타입으로 저장하면 이 문제 자체가 사라집니다." },

{ track: "test", k: "실패 메시지를 만든다 · failMessage", cat: "impl",
  q: "테스트 이름과 기대값·실제값을 받아 <code>\"이름 — 기대 X, 실제 Y\"</code> 형태의 한 줄로 만들어 주세요. 값은 <code>JSON.stringify</code> 로 적습니다.",
  src: "function failMessage(name, want, got) {\n  // TODO: 값을 그대로 붙이지 말고 형태가 보이게 적으세요\n  return name;\n}",
  sol: "function failMessage(name, want, got) {\n  return name + \" — 기대 \" + JSON.stringify(want) +\n    \", 실제 \" + JSON.stringify(got);\n}",
  tests: [['failMessage("합계", 3, 4)', '"합계 — 기대 3, 실제 4"'],
    ['failMessage("목록", [1,2], [1])', '"목록 — 기대 [1,2], 실제 [1]"'],
    ['failMessage("빈 값", null, 0)', '"빈 값 — 기대 null, 실제 0"'],
    ['failMessage("플래그", true, false)', '"플래그 — 기대 true, 실제 false"']],
  edge: [['failMessage("없음", null, undefined)', '"없음 — 기대 null, 실제 undefined"'],
    ['failMessage("빈 배열", [], [])', '"빈 배열 — 기대 [], 실제 []"']],
  ex: "실패 메시지의 값어치는 <b>스택 트레이스를 열지 않고도 원인이 보이는가</b>로 정해집니다. '실패했습니다' 만 찍히는 테스트는 실패할 때마다 사람의 시간을 몇 분씩 먹습니다.\n<code>JSON.stringify</code> 를 쓰는 이유는 <b>형태가 보이기 때문</b>입니다. 문자열 연결로 그냥 붙이면 배열이 <code>1,2</code> 가 되어 <code>[1,2]</code> 인지 <code>[\"1,2\"]</code> 인지 구분되지 않고, 객체는 <code>[object Object]</code> 가 되어 아무것도 알려 주지 않습니다.\n마지막 엣지 케이스가 재미있는 지점입니다. <code>JSON.stringify(undefined)</code> 는 문자열이 아니라 <code>undefined</code> 를 돌려주는데, 문자열과 더해지면서 <code>\"undefined\"</code> 로 바뀝니다. 우연히 읽기 좋은 결과가 나오지만, 우연에 기대는 코드라는 점은 알고 있어야 합니다.\n좋은 프레임워크는 여기에 <b>차이 나는 지점만 강조</b>하는 기능을 더합니다. 긴 객체 두 개를 통째로 찍어 놓고 사람이 눈으로 찾게 하는 것은 불친절합니다." },

{ track: "test", k: "결과가 매번 같은가 · isDeterministic", cat: "debug",
  q: "같은 코드를 여러 번 돌린 결과 목록을 받아 <b>전부 같은지</b> 판정해 주세요. 값은 배열이나 객체일 수 있습니다. 빈 목록은 <code>true</code> 입니다.",
  src: "function isDeterministic(runs) {\n  // TODO: 첫 결과와 나머지를 구조까지 비교하세요\n  return true;\n}",
  sol: "function isDeterministic(runs) {\n  if (!runs.length) return true;\n  const first = JSON.stringify(runs[0]);\n  return runs.every((r) => JSON.stringify(r) === first);\n}",
  tests: [['isDeterministic([[1,2],[1,2],[1,2]])', 'true'],
    ['isDeterministic([[1,2],[2,1]])', 'false'],
    ['isDeterministic([])', 'true'],
    ['isDeterministic([5,5,5])', 'true']],
  edge: [['isDeterministic([null,null])', 'true'], ['isDeterministic([0,"0"])', 'false']],
  ex: "플레이키 테스트를 잡는 첫 도구가 이것입니다. <b>같은 입력에 같은 출력</b>이 아니면 그 테스트는 언젠가 반드시 빨간불이 됩니다.\n두 번째 테스트가 가장 흔한 원인을 보여 줍니다. <code>[1,2]</code> 와 <code>[2,1]</code> 은 <b>내용은 같고 순서만 다른데</b>, 정렬 없는 데이터베이스 조회나 <code>Object.keys</code> 순회, <code>Set</code> 순회에서 늘 나옵니다. 테스트에서 순서를 확인하고 싶지 않다면 비교 전에 정렬해야 하고, 순서가 계약이라면 코드 쪽에서 정렬을 보장해야 합니다.\n마지막 엣지 케이스는 <code>0</code> 과 <code>\"0\"</code> 이 다르다는 것을 확인합니다. <code>JSON.stringify</code> 로 비교하면 타입이 보존되어 <code>0</code> 과 <code>\"0\"</code> 이 구분됩니다 — <code>==</code> 로 비교했다면 놓쳤을 차이입니다.\n실무에서는 이 함수를 그대로 쓰기보다, 의심되는 테스트만 <b>같은 시드로 100번 돌려 보는</b> 스크립트를 만들어 씁니다. 한 번 통과했다고 결정적인 것은 아닙니다." },

{ track: "test", k: "응답 계약에서 빠진 것 · missingKeys", cat: "review",
  q: "기대하는 응답 형태와 실제 응답을 받아, <b>기대에는 있는데 실제에는 없는 키</b>를 사전순으로 돌려주세요. 값은 보지 않고 키의 존재만 봅니다.",
  src: "function missingKeys(want, got) {\n  // TODO: 키가 실제로 있는지만 확인하세요\n  return [];\n}",
  sol: "function missingKeys(want, got) {\n  return Object.keys(want).filter((k) => !(k in got)).sort();\n}",
  tests: [['missingKeys({a:1,b:2},{a:1})', '["b"]'],
    ['missingKeys({a:1},{a:1,b:2})', '[]'],
    ['missingKeys({id:1,name:"x"},{})', '["id","name"]'],
    ['missingKeys({},{a:1})', '[]']],
  edge: [['missingKeys({a:1},{a:undefined})', '[]'], ['missingKeys({b:1,a:1},{})', '["a","b"]']],
  ex: "계약 테스트의 뼈대입니다. 클라이언트가 <b>읽는 키가 그대로 있는가</b>가 API 의 약속이고, 그 약속이 깨졌는지는 이 비교로 대부분 잡힙니다.\n두 번째 테스트가 방향의 비대칭을 보여 줍니다. <b>키가 더 있는 것은 깨는 변경이 아닙니다.</b> 클라이언트는 모르는 키를 무시하기 때문입니다. 그래서 API 를 바꿀 때 '더하고 → 한동안 둘 다 주고 → 나중에 없앤다' 는 순서를 씁니다.\n엣지 케이스의 <code>{a:undefined}</code> 가 미묘한 지점입니다. <code>in</code> 연산자는 <b>키의 존재</b>를 보므로 값이 <code>undefined</code> 여도 있다고 답합니다. <code>got[k] === undefined</code> 로 검사했다면 없다고 판정했을 텐데, JSON 응답에서는 <code>null</code> 과 '키 자체가 없음' 이 서로 다른 의미인 경우가 많아 이 구분이 중요합니다.\n실무에서는 여기에 <b>타입 검사</b>를 더합니다. 키는 있는데 문자열이던 것이 숫자로 바뀌면 그것도 깨는 변경입니다." },

/* ───────────── 무엇을 넣어 볼 것인가 ───────────── */
{ track: "test", k: "경계값을 뽑아낸다 · boundaryValues", cat: "impl",
  q: "허용 범위 <code>min</code>~<code>max</code> 가 주어지면 확인할 <b>경계값</b>을 오름차순으로 돌려주세요. 각 경계의 <b>바로 아래·경계·바로 위</b>를 보되, 겹치는 값은 한 번만 담습니다.",
  src: "function boundaryValues(min, max) {\n  // TODO: 두 경계 주변 세 값씩을 모아 정리하세요\n  return [min, max];\n}",
  sol: "function boundaryValues(min, max) {\n  const raw = [min - 1, min, min + 1, max - 1, max, max + 1];\n  return raw.filter((v, i) => raw.indexOf(v) === i)\n    .sort((a, b) => a - b);\n}",
  tests: [['boundaryValues(1,10)', '[0,1,2,9,10,11]'],
    ['boundaryValues(0,1)', '[-1,0,1,2]'],
    ['boundaryValues(5,5)', '[4,5,6]'],
    ['boundaryValues(-2,2)', '[-3,-2,-1,1,2,3]']],
  edge: [['boundaryValues(1,2)', '[0,1,2,3]'], ['boundaryValues(0,0)', '[-1,0,1]']],
  ex: "버그는 <b>가운데가 아니라 가장자리</b>에 삽니다. <code>&lt;</code> 를 <code>&lt;=</code> 로 잘못 쓰는 실수는 범위 한가운데 값으로는 절대 드러나지 않고, 경계에서만 드러납니다.\n경계마다 세 값을 보는 것이 규칙입니다 — <b>바로 아래는 거부되어야</b> 하고, <b>경계는 허용되어야</b> 하고, <b>바로 위는 허용되어야</b> 합니다(하한 기준). 이 셋이면 부등호를 잘못 쓴 모든 경우가 걸립니다.\n<code>boundaryValues(5,5)</code> 처럼 상·하한이 같은 경우를 함수가 스스로 정리하게 만든 것이 이 문제의 핵심입니다. 중복 제거가 없으면 같은 값을 두 번 확인하는 테스트가 생기고, 그런 테스트는 늘어날수록 사람이 읽기를 포기합니다.\n실무에서는 이 목록에 <b>타입 경계</b>도 더합니다. 빈 문자열, <code>null</code>, 아주 큰 수, 소수점이 붙은 값 — 숫자 범위만 보고 통과한 코드가 이런 입력에서 무너지는 일이 흔합니다." },

{ track: "test", k: "입력을 등가 분할한다 · classifyAge", cat: "impl",
  q: "나이를 받아 등가 분할된 이름을 돌려주세요. 숫자가 아니거나 유한하지 않으면 <code>\"잘못된 값\"</code>, 음수는 <code>\"음수\"</code>, 14 미만 <code>\"어린이\"</code>, 19 미만 <code>\"청소년\"</code>, 65 미만 <code>\"성인\"</code>, 그 이상 <code>\"노인\"</code> 입니다.",
  src: "function classifyAge(n) {\n  // TODO: 잘못된 입력을 가장 먼저 걸러 내세요\n  return \"성인\";\n}",
  sol: "function classifyAge(n) {\n  if (typeof n !== \"number\" || !isFinite(n)) return \"잘못된 값\";\n  if (n < 0) return \"음수\";\n  if (n < 14) return \"어린이\";\n  if (n < 19) return \"청소년\";\n  if (n < 65) return \"성인\";\n  return \"노인\";\n}",
  tests: [['classifyAge(-1)', '"음수"'],
    ['classifyAge(14)', '"청소년"'],
    ['classifyAge(19)', '"성인"'],
    ['classifyAge(65)', '"노인"']],
  edge: [['classifyAge(NaN)', '"잘못된 값"'], ['classifyAge("20")', '"잘못된 값"']],
  ex: "<b>등가 분할</b>은 '같은 취급을 받는 입력끼리 묶고, 묶음마다 하나씩만 확인한다' 는 생각입니다. 20살과 30살과 40살을 각각 확인하는 것은 셋 다 같은 가지를 지나므로 새로 알게 되는 것이 없습니다.\n대신 <b>묶음의 경계</b>는 반드시 확인합니다. 그래서 테스트가 13·14·18·19·64·65 같은 값에 몰려 있는 것이 정상이고, 그 값들이 곧 요구사항의 문장입니다.\n<code>NaN</code> 이 특히 위험합니다. <code>NaN &lt; 14</code> 도 거짓이고 <code>NaN &gt;= 65</code> 도 거짓이라, 검사 순서를 잘못 두면 어느 가지에도 걸리지 않고 마지막 <code>return</code> 으로 흘러가 <b>조용히 '노인' 이 됩니다.</b> 잘못된 입력을 맨 앞에서 걷어 내는 이유입니다.\n<code>typeof</code> 검사가 문자열 <code>\"20\"</code> 을 막습니다. 자바스크립트는 <code>\"20\" &lt; 65</code> 를 참으로 만들어 주므로, 타입 검사 없이는 API 로 들어온 문자열이 그대로 통과합니다 — 실제 사고에서 아주 흔한 형태입니다." },

{ track: "test", k: "실패를 최소로 줄인다 · shrinkFailing", cat: "debug",
  q: "실패하는 입력 목록과 <b>실패 여부를 판정하는 함수</b>가 주어집니다. 원소를 하나씩 빼 봤을 때 여전히 실패하면 뺀 채로 두는 식으로, <b>더 줄일 수 없을 때까지</b> 줄인 목록을 돌려주세요.",
  src: "function shrinkFailing(list, fails) {\n  // TODO: 하나 빼 보고 여전히 실패하면 그대로 두세요\n  return list;\n}",
  sol: "function shrinkFailing(list, fails) {\n  let cur = list.slice();\n  let i = 0;\n  while (i < cur.length) {\n    const next = cur.slice(0, i).concat(cur.slice(i + 1));\n    if (fails(next)) cur = next;\n    else i++;\n  }\n  return cur;\n}",
  tests: [['shrinkFailing([1,2,3,4],(a)=>a.indexOf(3)>=0)', '[3]'],
    ['shrinkFailing([1,2,3],(a)=>a.length>=2)', '[2,3]'],
    ['shrinkFailing([5],(a)=>a.length>0)', '[5]'],
    ['shrinkFailing([1,2,3],(a)=>false)', '[1,2,3]']],
  edge: [['shrinkFailing([],(a)=>true)', '[]'],
    ['shrinkFailing([1,2,3,4],(a)=>a.length>=1)', '[4]']],
  ex: "속성 기반 테스트 도구가 실패를 찾은 뒤 하는 일이 <b>축소(shrink)</b> 입니다. 무작위로 만든 입력은 대개 크고 지저분한데, 그대로 보고하면 사람이 원인을 읽어 낼 수 없습니다.\n원리는 단순합니다 — <b>빼 보고 여전히 실패하면 그건 필요 없던 것</b>입니다. 필요 없는 것을 다 걷어 내면 남은 것이 원인의 최소 형태입니다. 100개짜리 배열이 <code>[3]</code> 하나로 줄어드는 순간 버그가 눈에 보입니다.\n<code>i</code> 를 언제 올리는지가 이 알고리즘의 전부입니다. <b>뺐을 때 성공했다면</b> 그 원소는 실패에 필요하므로 남기고 다음으로 넘어가고, <b>뺐을 때도 실패했다면</b> 지운 자리에 다음 원소가 밀려 왔으니 <code>i</code> 를 그대로 두고 다시 봅니다. 무심코 <code>i++</code> 를 무조건 하면 원소를 건너뛰게 됩니다.\n같은 생각을 사람이 손으로 하는 것이 버그 신고를 다듬는 과정이고, 코드에 적용한 것이 <code>git bisect</code> 입니다. 재현 조건을 줄이는 것은 언제나 원인을 찾는 것보다 먼저 할 일입니다." },

{ track: "test", k: "조건 조합 표를 만든다 · decisionRows", cat: "impl",
  q: "조건이 <code>n</code> 개일 때 가능한 참·거짓 조합을 <b>전부</b> 배열의 배열로 돌려주세요. 순서는 첫 조건을 가장 큰 자리로 본 이진수 오름차순입니다.",
  src: "function decisionRows(n) {\n  // TODO: 0부터 2ⁿ-1 까지의 이진 표현을 펼치세요\n  return [];\n}",
  sol: "function decisionRows(n) {\n  const out = [];\n  for (let i = 0; i < Math.pow(2, n); i++) {\n    const bits = [];\n    for (let b = n - 1; b >= 0; b--) bits.push(Boolean(i >> b & 1));\n    out.push(bits);\n  }\n  return out;\n}",
  tests: [['decisionRows(1)', '[[false],[true]]'],
    ['decisionRows(2)', '[[false,false],[false,true],[true,false],[true,true]]'],
    ['decisionRows(3).length', '8'],
    ['decisionRows(2)[3]', '[true,true]']],
  edge: [['decisionRows(0)', '[[]]'], ['decisionRows(3)[5]', '[true,false,true]']],
  ex: "<b>결정 표</b>는 조건이 여러 개 얽힌 규칙을 다룰 때 가장 값싼 도구입니다. 표를 만들어 놓고 각 줄의 결과를 적어 보면, 요구사항에 <b>정해지지 않은 조합</b>이 바로 눈에 띕니다.\n동시에 이 함수는 <b>왜 전수 확인이 불가능한지</b>도 보여 줍니다. 조건이 10개면 1,024줄, 20개면 100만 줄이 넘습니다. 그래서 실무에서는 표를 만든 뒤 <b>의미 있는 줄만 고릅니다</b> — 결과가 같은 줄들을 묶고, 대표 하나씩만 확인합니다.\n<code>decisionRows(0)</code> 이 <code>[[]]</code> 인 것이 헷갈리는 지점입니다. 조건이 하나도 없어도 <b>조합은 하나 있습니다</b> — '아무 조건도 없는 경우' 입니다. 빈 배열 <code>[]</code> 를 돌려주면 '경우가 아예 없다' 는 다른 뜻이 되어, 이 값을 순회하는 코드가 아무 일도 하지 않게 됩니다.\n비트 연산으로 만드는 이유는 <b>순서가 저절로 정해지기 때문</b>입니다. 재귀로 만들어도 되지만, 정수를 세는 방식은 어떤 줄이 몇 번째인지 언제든 되짚을 수 있습니다." },

{ track: "test", k: "덮이지 않은 규칙을 찾는다 · uncoveredRules", cat: "review",
  q: "요구사항 규칙 번호 목록과 테스트 이름 목록이 주어집니다. 규칙 번호가 <b>어느 테스트 이름에도 들어 있지 않으면</b> 덮이지 않은 것입니다. 원래 순서를 지켜 돌려주세요.",
  src: "function uncoveredRules(rules, names) {\n  // TODO: 규칙마다 그 번호를 담은 이름이 있는지 보세요\n  return rules;\n}",
  sol: "function uncoveredRules(rules, names) {\n  return rules.filter((r) =>\n    !names.some((nm) => String(nm).indexOf(r) >= 0));\n}",
  tests: [['uncoveredRules(["R1","R2","R3"],["R1 정상","R3 예외"])', '["R2"]'],
    ['uncoveredRules(["R1"],["R1"])', '[]'],
    ['uncoveredRules(["R1","R2"],[])', '["R1","R2"]'],
    ['uncoveredRules([],["R1"])', '[]']],
  edge: [['uncoveredRules(["R1","R10"],["R10 확인"])', '[]'],
    ['uncoveredRules(["r1"],["R1"])', '["r1"]']],
  ex: "커버리지 도구는 <b>코드의 어느 줄이 실행됐는지</b>만 알려 줄 뿐, <b>요구사항의 어느 규칙이 확인됐는지</b>는 알려 주지 못합니다. 규칙 번호를 테스트 이름에 적어 두면 그 빈칸을 기계가 셀 수 있게 됩니다.\n첫 엣지 케이스가 이 방식의 함정을 그대로 드러냅니다. <code>\"R1\"</code> 은 <code>\"R10 확인\"</code> 의 부분 문자열이라 <b>R1 이 덮인 것으로 잘못 판정됩니다.</b> 실무에서 규칙 번호를 <code>R-001</code> 처럼 자릿수를 맞춰 쓰거나 <code>[R1]</code> 처럼 구분자로 감싸는 이유가 이것입니다.\n두 번째 엣지 케이스는 <b>대소문자를 구분한다</b>는 사실을 못 박습니다. 이런 검사는 사람이 이름을 조금만 다르게 적어도 조용히 실패하므로, 규칙을 정했으면 도구로 강제해야 합니다.\n이 방식의 진짜 값어치는 숫자가 아니라 <b>대화</b>에 있습니다. '이 규칙은 왜 테스트가 없나요' 라는 질문이 리뷰에서 자동으로 나오게 만드는 것이 목적입니다." },

/* ───────────── 테스트 더블 ───────────── */
{ track: "test", k: "스파이 호출 기록 · spyReport", cat: "impl",
  q: "호출된 함수 이름의 기록을 받아 <code>[이름, 횟수]</code> 배열을 돌려주세요. <b>횟수 내림차순</b>, 같으면 <b>이름 사전순</b> 입니다.",
  src: "function spyReport(log) {\n  // TODO: 이름별로 세고 정렬 규칙을 두 단계로 두세요\n  return [];\n}",
  sol: "function spyReport(log) {\n  const seen = Object.create(null);\n  log.forEach((nm) => { seen[nm] = (seen[nm] || 0) + 1; });\n  return Object.keys(seen)\n    .sort((a, b) => seen[b] - seen[a] || (a < b ? -1 : a > b ? 1 : 0))\n    .map((nm) => [nm, seen[nm]]);\n}",
  tests: [['spyReport(["a","b","a"])', '[["a",2],["b",1]]'],
    ['spyReport([])', '[]'],
    ['spyReport(["z","y"])', '[["y",1],["z",1]]'],
    ['spyReport(["x","x","x"])', '[["x",3]]']],
  edge: [['spyReport(["b","a","b","a"])', '[["a",2],["b",2]]'],
    ['spyReport(["toString"])', '[["toString",1]]']],
  ex: "<b>스파이</b>는 진짜 동작은 그대로 두고 <b>호출 사실만 기록</b>하는 테스트 더블입니다. '알림이 정확히 한 번 갔는가' 처럼 결과값으로는 확인할 수 없는 것을 볼 때 씁니다.\n마지막 엣지 케이스가 이 문제의 진짜 함정입니다. <code>{}</code> 로 만든 객체에서 <code>seen[\"toString\"]</code> 은 <b>상속받은 함수</b>라 <code>||</code> 검사를 통과해 버리고, 거기에 1을 더하면 <code>NaN</code> 이 됩니다. <code>Object.create(null)</code> 로 <b>부모가 없는 객체</b>를 만들면 이 문제가 사라집니다(<code>Map</code> 을 써도 됩니다).\n동점 규칙을 정해 둔 것도 의도적입니다. 규칙이 없으면 같은 횟수인 항목의 순서가 환경에 따라 달라져, 이 함수를 쓰는 테스트가 <b>플레이키</b>가 됩니다. 정렬 비교 함수에서 <code>||</code> 로 2차 기준을 잇는 것은 자주 쓰는 관용구입니다.\n다만 스파이를 남용하면 '무엇을 하는가' 가 아니라 '어떻게 하는가' 를 못 박게 됩니다. 결과로 확인할 수 있으면 결과로 확인하는 편이 리팩터링에 강합니다." },

{ track: "test", k: "스텁 응답을 찾는다 · stubLookup", cat: "debug",
  q: "미리 정해 둔 응답표에서 키에 해당하는 값을 돌려주세요. <b>키가 표에 없을 때만</b> 기본값을 씁니다. 값이 <code>0</code>·<code>false</code>·<code>null</code> 이어도 그 값을 그대로 돌려줍니다.",
  src: "function stubLookup(table, key, fallback) {\n  // TODO: 값이 거짓 같은 값일 때를 조심하세요\n  return table[key] || fallback;\n}",
  sol: "function stubLookup(table, key, fallback) {\n  return Object.prototype.hasOwnProperty.call(table, key)\n    ? table[key]\n    : fallback;\n}",
  tests: [['stubLookup({a:1},"a",9)', '1'],
    ['stubLookup({a:0},"a",9)', '0'],
    ['stubLookup({},"a",9)', '9'],
    ['stubLookup({a:null},"a",9)', 'null']],
  edge: [['stubLookup({},"toString",9)', '9'], ['stubLookup({a:false},"a",true)', 'false']],
  ex: "시작 코드에 적힌 <code>table[key] || fallback</code> 이 <b>실무에서 가장 자주 나오는 버그</b> 중 하나입니다. <code>0</code>·<code>\"\"</code>·<code>false</code>·<code>null</code> 은 모두 거짓 같은 값이라, 멀쩡히 저장된 값이 기본값으로 바뀌어 버립니다.\n'할인율 0%' 가 기본값 10% 로 둔갑하거나, '알림 끔(false)' 이 켬으로 되돌아가는 사고가 정확히 이 형태입니다. 테스트에서 <code>0</code> 과 <code>false</code> 를 넣어 보지 않으면 영영 드러나지 않습니다.\n<code>hasOwnProperty</code> 를 <code>Object.prototype</code> 에서 꺼내 부르는 이유는 두 가지입니다. 표 자체에 <code>hasOwnProperty</code> 라는 키가 있을 수 있고, <code>Object.create(null)</code> 로 만든 표에는 그 메서드가 아예 없습니다. 엣지 케이스의 <code>\"toString\"</code> 은 <b>상속된 키를 자기 것으로 착각하지 않는지</b>를 확인합니다.\n요즘 코드라면 <code>??</code>(널 병합)로 <code>null</code>·<code>undefined</code> 만 걸러 내는 방법도 있습니다. 다만 '키가 없는 것' 과 '값이 <code>null</code> 인 것' 을 구분해야 한다면 이 문제처럼 존재 검사를 써야 합니다." },

{ track: "test", k: "가짜 시계를 돌린다 · fakeClock", cat: "impl",
  q: "시작 시각과 <b>앞으로 감을 간격 목록</b>을 받아, 감을 때마다의 시각을 순서대로 돌려주세요. 간격은 음수일 수도 있습니다.",
  src: "function fakeClock(start, ticks) {\n  // TODO: 현재 시각을 누적하며 매번 기록하세요\n  return ticks;\n}",
  sol: "function fakeClock(start, ticks) {\n  let now = start;\n  return ticks.map((d) => {\n    now += d;\n    return now;\n  });\n}",
  tests: [['fakeClock(0,[1,2,3])', '[1,3,6]'],
    ['fakeClock(100,[])', '[]'],
    ['fakeClock(10,[-5])', '[5]'],
    ['fakeClock(0,[0,0])', '[0,0]']],
  edge: [['fakeClock(1000,[1000])', '[2000]'], ['fakeClock(-5,[5])', '[0]']],
  ex: "'만료된 지 하루가 지나면 잠긴다' 같은 규칙을 진짜 시간으로 확인하면 <b>테스트가 하루 걸립니다.</b> 그래서 시간을 다루는 코드는 시계를 <b>바깥에서 넣을 수 있게</b> 만들고, 테스트에서는 가짜 시계를 넣어 원하는 만큼 감습니다.\n핵심은 코드가 <code>Date.now()</code> 를 직접 부르지 않는 것입니다. 직접 부르면 바꿔치기할 자리가 없어, 테스트를 위해 시스템 시간을 건드리는 지경까지 갑니다. <b>의존을 인자로 받는</b> 설계가 여기서 그대로 값어치를 냅니다.\n간격이 음수일 수 있게 한 것은 의도적입니다. 실제 시스템에서 시간은 <b>뒤로 갈 수 있습니다</b> — NTP 보정, 서머타임, 가상 머신의 시계 되돌림. '시간은 항상 앞으로 간다' 를 전제한 코드는 그때 이상하게 동작합니다.\n그래서 경과 시간을 재야 한다면 벽시계 대신 <b>단조 증가 시계</b>(<code>performance.now()</code>)를 씁니다. 벽시계는 '지금 몇 시인가' 를 답하고, 단조 시계는 '얼마나 지났는가' 를 답합니다." },

{ track: "test", k: "테스트 더블을 분류한다 · doubleKind", cat: "knowledge",
  q: "네 가지 성질을 받아 테스트 더블의 이름을 돌려주세요. 실제로 동작하는 간이 구현이면 <code>\"페이크\"</code>, 호출을 검증하면 <code>\"목\"</code>, 기록만 하면 <code>\"스파이\"</code>, 정해진 값만 돌려주면 <code>\"스텁\"</code>, 아무것도 안 하면 <code>\"더미\"</code> 입니다. 앞의 조건이 우선합니다.",
  src: "function doubleKind(canned, records, verifies, working) {\n  // TODO: 가장 강한 성질부터 차례로 보세요\n  return \"더미\";\n}",
  sol: "function doubleKind(canned, records, verifies, working) {\n  if (working) return \"페이크\";\n  if (verifies) return \"목\";\n  if (records) return \"스파이\";\n  if (canned) return \"스텁\";\n  return \"더미\";\n}",
  tests: [['doubleKind(false,false,false,false)', '"더미"'],
    ['doubleKind(true,false,false,false)', '"스텁"'],
    ['doubleKind(true,true,false,false)', '"스파이"'],
    ['doubleKind(true,true,true,false)', '"목"']],
  edge: [['doubleKind(false,false,false,true)', '"페이크"'],
    ['doubleKind(true,true,true,true)', '"페이크"']],
  ex: "다섯 이름이 흔히 뒤섞여 쓰이지만 구분은 분명합니다. <b>더미</b>는 자리만 채웁니다. <b>스텁</b>은 정해진 답을 돌려줍니다. <b>스파이</b>는 거기에 호출 기록을 더합니다. <b>목</b>은 '이렇게 불려야 한다' 는 기대를 미리 걸고 그것을 검증합니다. <b>페이크</b>는 실제로 동작하는 간이 구현입니다 — 메모리 저장소가 대표적입니다.\n실무에서 중요한 것은 이름이 아니라 <b>무엇에 결합되는가</b> 입니다. 스텁은 '무엇을 돌려줄까' 만 정하므로 결합이 약하고, 목은 '어떤 순서로 몇 번 불려야 하는가' 까지 못 박으므로 결합이 강합니다. 목이 많은 테스트가 리팩터링할 때 우수수 깨지는 이유입니다.\n<code>doubleKind(true,true,true,true)</code> 가 <code>\"페이크\"</code> 인 것은 <b>가장 강한 성질이 이긴다</b>는 규칙 때문입니다. 실제로 동작하는 구현이라면 굳이 기록이나 검증으로 부르지 않습니다.\n고르는 기준은 단순합니다. <b>결과로 확인할 수 있으면 스텁이나 페이크</b>를 쓰고, 결과에 드러나지 않는 부수 효과(메일 발송, 결제 요청)만 스파이나 목으로 확인합니다." },

{ track: "test", k: "호출 순서를 확인한다 · callOrder", cat: "impl",
  q: "실제 호출 기록과 기대하는 순서가 주어집니다. 기대한 이름들이 <b>그 순서대로</b> 기록에 나타나면 <code>true</code> 입니다. 사이에 다른 호출이 끼어도 괜찮습니다.",
  src: "function callOrder(log, want) {\n  // TODO: 기대 목록을 앞에서부터 하나씩 맞춰 나가세요\n  return false;\n}",
  sol: "function callOrder(log, want) {\n  let i = 0;\n  log.forEach((nm) => {\n    if (i < want.length && nm === want[i]) i++;\n  });\n  return i === want.length;\n}",
  tests: [['callOrder(["a","b","c"],["a","c"])', 'true'],
    ['callOrder(["a","b"],["b","a"])', 'false'],
    ['callOrder([],[])', 'true'],
    ['callOrder(["a"],["a","a"])', 'false']],
  edge: [['callOrder(["a","a"],["a","a"])', 'true'], ['callOrder(["x"],[])', 'true']],
  ex: "'트랜잭션을 열고 → 저장하고 → 커밋한다' 처럼 <b>순서 자체가 계약</b>인 경우가 있습니다. 이때는 호출 횟수만으로는 부족하고 순서를 봐야 합니다.\n'사이에 다른 호출이 끼어도 된다' 는 규칙이 중요합니다. 정확히 연속으로만 나타나야 한다고 하면, 관계없는 로그 호출 하나만 추가해도 테스트가 깨집니다. <b>부분 수열</b>로 보는 것이 필요한 만큼만 못 박는 방식입니다.\n마지막 테스트가 미묘합니다. <code>[\"a\"]</code> 안에서 <code>[\"a\",\"a\"]</code> 를 찾을 수는 없습니다 — <b>같은 이름도 개수만큼 따로 필요</b>합니다. 인덱스를 하나씩만 전진시키는 구현이 이 성질을 자연히 만족합니다.\n<code>callOrder([\"x\"],[])</code> 가 참인 것은 빈 기대는 언제나 만족된다는 뜻입니다. 논리적으로는 옳지만, 테스트에서 기대 목록이 실수로 비면 <b>아무것도 확인하지 않는 테스트</b>가 조용히 통과합니다. 그래서 실무 헬퍼는 빈 기대를 오류로 만들기도 합니다." },

/* ───────────── 층과 커버리지 ───────────── */
{ track: "test", k: "커버리지 비율 · coveragePct", cat: "impl",
  q: "전체 줄 수와 실행된 줄 수로 백분율을 <b>반올림</b>해 돌려주세요. 전체가 0이면 100 입니다.",
  src: "function coveragePct(total, covered) {\n  // TODO: 0으로 나누기를 먼저 막으세요\n  return covered / total * 100;\n}",
  sol: "function coveragePct(total, covered) {\n  if (!total) return 100;\n  return Math.round(covered / total * 100);\n}",
  tests: [['coveragePct(10,7)', '70'],
    ['coveragePct(3,1)', '33'],
    ['coveragePct(0,0)', '100'],
    ['coveragePct(8,8)', '100']],
  edge: [['coveragePct(3,2)', '67'], ['coveragePct(200,1)', '1']],
  ex: "커버리지는 <b>실행된 줄의 비율</b>일 뿐입니다. 이 함수가 그 사실을 그대로 보여 줍니다 — 어디에도 '확인했는가' 는 들어 있지 않습니다. 어서션이 하나도 없는 테스트도 커버리지는 올립니다.\n<code>coveragePct(0,0)</code> 을 100 으로 정한 것은 실용적인 선택입니다. 그대로 두면 <code>0/0</code> 이 <code>NaN</code> 이 되고, <code>NaN &lt; 80</code> 같은 비교가 <b>조용히 거짓</b>이 되어 게이트가 통과됩니다. 빈 파일이 커버리지를 떨어뜨려 사람들이 게이트를 꺼 버리는 일도 막습니다.\n<code>Math.round</code> 의 자리도 중요합니다. 79.6% 를 80% 로 반올림해 놓고 '기준 80% 달성' 이라고 말하는 것과, 소수점을 버려 79% 로 보고하는 것은 팀이 신뢰하는 숫자가 달라집니다. 어느 쪽이든 <b>정하고 문서에 적어 두는 것</b>이 중요합니다.\n숫자 자체보다 <b>추세</b>가 훨씬 유용합니다. '85% 유지' 보다 '이번 PR 에서 새로 추가된 줄의 커버리지' 를 보는 편이 실제 위험을 잘 반영합니다." },

{ track: "test", k: "안 덮인 줄 번호 · uncoveredLines", cat: "impl",
  q: "전체 줄 수와 실행된 줄 번호 목록을 받아, <b>실행되지 않은</b> 줄 번호를 오름차순으로 돌려주세요. 줄 번호는 1부터 셉니다.",
  src: "function uncoveredLines(total, hits) {\n  // TODO: 1부터 total 까지 돌며 없는 것만 모으세요\n  return [];\n}",
  sol: "function uncoveredLines(total, hits) {\n  const out = [];\n  for (let i = 1; i <= total; i++) {\n    if (hits.indexOf(i) < 0) out.push(i);\n  }\n  return out;\n}",
  tests: [['uncoveredLines(5,[1,2,5])', '[3,4]'],
    ['uncoveredLines(3,[])', '[1,2,3]'],
    ['uncoveredLines(2,[1,2])', '[]'],
    ['uncoveredLines(0,[])', '[]']],
  edge: [['uncoveredLines(4,[4,1])', '[2,3]'], ['uncoveredLines(3,[9])', '[1,2,3]']],
  ex: "커버리지 보고서에서 <b>실제로 봐야 할 것</b>은 퍼센트가 아니라 이 목록입니다. '3번과 4번 줄이 한 번도 실행되지 않았다' 는 정보가 '80%' 보다 훨씬 실행 가능합니다.\n<code>hits</code> 가 정렬돼 있지 않아도 동작하게 만든 것이 첫 엣지 케이스입니다. 커버리지 계측기는 실행 순서대로 기록하므로 줄 번호가 뒤죽박죽인 것이 정상입니다. 입력의 순서를 전제하는 함수는 언젠가 반드시 깨집니다.\n<code>uncoveredLines(3,[9])</code> 에서 범위 밖 번호를 <b>조용히 무시</b>하는 것도 의도된 동작입니다. 파일이 줄어들었는데 낡은 보고서가 남아 있으면 이런 입력이 실제로 들어옵니다.\n덮이지 않은 줄을 볼 때는 <b>줄이 아니라 이유</b>를 봐야 합니다. 예외 처리 구간이 비어 있다면 그것은 '실패했을 때 어떻게 되는지 아무도 모른다' 는 뜻이고, 대개 커버리지 숫자보다 훨씬 큰 위험입니다." },

{ track: "test", k: "피라미드 모양 판정 · pyramidVerdict", cat: "review",
  q: "단위·통합·E2E 테스트 개수를 받아 모양을 판정해 주세요. 합이 0이면 <code>\"테스트 없음\"</code>, E2E 가 단위보다 많으면 <code>\"아이스크림콘\"</code>, 통합이 전체의 5분의 1 미만이면 <code>\"모래시계\"</code>, 나머지는 <code>\"피라미드\"</code> 입니다.",
  src: "function pyramidVerdict(unit, integ, e2e) {\n  // TODO: 합이 0인 경우를 먼저 처리하세요\n  return \"피라미드\";\n}",
  sol: "function pyramidVerdict(unit, integ, e2e) {\n  const sum = unit + integ + e2e;\n  if (!sum) return \"테스트 없음\";\n  if (e2e > unit) return \"아이스크림콘\";\n  if (integ * 5 < sum) return \"모래시계\";\n  return \"피라미드\";\n}",
  tests: [['pyramidVerdict(70,20,10)', '"피라미드"'],
    ['pyramidVerdict(10,20,70)', '"아이스크림콘"'],
    ['pyramidVerdict(50,2,48)', '"모래시계"'],
    ['pyramidVerdict(0,0,0)', '"테스트 없음"']],
  edge: [['pyramidVerdict(0,0,1)', '"아이스크림콘"'], ['pyramidVerdict(1,0,1)', '"모래시계"']],
  ex: "<b>피라미드</b>는 빠르고 값싼 단위 테스트가 바닥에 넓게 깔린 모양입니다. 위로 갈수록 현실적이지만 느리고 잘 깨지므로 수를 줄입니다.\n<b>아이스크림콘</b>은 뒤집힌 모양입니다 — E2E 가 가장 많습니다. 화면부터 만들고 나중에 테스트를 붙인 프로젝트에서 흔히 나오는데, 스위트가 느리고 자주 흔들려 결국 아무도 믿지 않게 됩니다.\n<b>모래시계</b>는 단위와 E2E 는 많은데 <b>가운데가 비어 있는</b> 모양입니다. 조각들은 각각 확인되고 전체 흐름도 확인되는데, '조각들이 서로 맞는가' 를 보는 층이 없어 통합 지점의 버그가 E2E 에서야 발견됩니다. 그러면 원인 찾기가 몇 배로 어려워집니다.\n다만 이 비율은 <b>규칙이 아니라 출발점</b>입니다. 순수 로직이 많은 라이브러리와 화면 조립이 대부분인 앱은 답이 다릅니다. 우리 시스템에서 <b>실제로 어디서 사고가 났는지</b>가 언제나 더 강한 근거입니다." },

{ track: "test", k: "이름이 겹치는 테스트 · dupTestNames", cat: "review",
  q: "테스트 이름 목록에서 <b>두 번 이상 나온 이름</b>을 사전순으로 돌려주세요.",
  src: "function dupTestNames(names) {\n  // TODO: 이름별로 센 뒤 2 이상만 남기세요\n  return [];\n}",
  sol: "function dupTestNames(names) {\n  const seen = Object.create(null);\n  names.forEach((nm) => { seen[nm] = (seen[nm] || 0) + 1; });\n  return Object.keys(seen).filter((nm) => seen[nm] > 1).sort();\n}",
  tests: [['dupTestNames(["a","b","a"])', '["a"]'],
    ['dupTestNames(["a","b"])', '[]'],
    ['dupTestNames(["b","b","a","a"])', '["a","b"]'],
    ['dupTestNames([])', '[]']],
  edge: [['dupTestNames(["x","x","x"])', '["x"]'],
    ['dupTestNames(["constructor","constructor"])', '["constructor"]']],
  ex: "이름이 겹친 테스트는 대개 <b>복사해 붙인 뒤 이름을 안 고친</b> 흔적입니다. 실행은 되지만 보고서에서 어느 쪽이 실패했는지 구분되지 않아, 실패를 조사할 때 시간을 잡아먹습니다.\n더 나쁜 경우도 있습니다. 일부 프레임워크는 같은 이름의 테스트를 <b>덮어쓰거나 건너뜁니다.</b> 그러면 확인하고 있다고 믿는 것이 실제로는 한 번도 실행되지 않습니다.\n<code>Object.create(null)</code> 을 다시 쓴 이유가 마지막 엣지 케이스에 있습니다. 평범한 <code>{}</code> 에서는 <code>seen[\"constructor\"]</code> 가 <b>상속받은 생성자 함수</b>라 <code>|| 0</code> 을 통과해 버려, 숫자 대신 <code>NaN</code> 이 되고 결과에서 사라집니다. 사용자 입력이나 파일에서 온 문자열을 키로 쓸 때는 늘 이 위험이 있습니다.\n같은 이름을 <b>CI 에서 막는</b> 것이 실무의 답입니다. 사람이 리뷰에서 잡기에는 너무 사소하고, 기계는 1초 만에 잡습니다." },

{ track: "test", k: "어느 층에서 확인할까 · layerFor", cat: "review",
  q: "테스트가 필요로 하는 의존 목록을 받아 알맞은 층을 돌려주세요. <code>\"browser\"</code> 가 있으면 <code>\"e2e\"</code>, <code>\"db\"</code> 나 <code>\"http\"</code> 가 있으면 <code>\"integration\"</code>, 아무것도 없으면 <code>\"unit\"</code> 입니다.",
  src: "function layerFor(deps) {\n  // TODO: 가장 무거운 의존부터 확인하세요\n  return \"unit\";\n}",
  sol: "function layerFor(deps) {\n  if (deps.indexOf(\"browser\") >= 0) return \"e2e\";\n  if (deps.indexOf(\"db\") >= 0 || deps.indexOf(\"http\") >= 0) {\n    return \"integration\";\n  }\n  return \"unit\";\n}",
  tests: [['layerFor([])', '"unit"'],
    ['layerFor(["db"])', '"integration"'],
    ['layerFor(["browser","db"])', '"e2e"'],
    ['layerFor(["http"])', '"integration"']],
  edge: [['layerFor(["clock"])', '"unit"'], ['layerFor(["browser"])', '"e2e"']],
  ex: "층을 고르는 기준은 취향이 아니라 <b>무엇에 의존하는가</b> 입니다. 브라우저가 필요하면 그것은 이미 E2E 이고, 데이터베이스나 네트워크가 필요하면 통합입니다.\n그래서 '단위 테스트를 늘리자' 는 말은 실제로는 <b>의존을 줄이자</b>는 말입니다. 계산 로직을 데이터베이스 호출에서 떼어 내면 그 부분이 저절로 단위 테스트가 되고, 훨씬 빠르고 안정적으로 확인됩니다.\n<code>\"clock\"</code> 을 단위로 분류한 것이 힌트입니다. 시계는 <b>가짜로 바꿔치기할 수 있는</b> 의존이라 진짜 시간을 기다릴 필요가 없습니다. 같은 논리가 난수·파일 시스템·환경 변수에도 적용됩니다 — 인자로 받게 만들면 무거운 의존이 아니게 됩니다.\n무거운 것부터 검사하는 순서에도 이유가 있습니다. 브라우저를 쓰면서 데이터베이스도 쓰는 테스트는 결국 브라우저를 띄워야 하므로 <b>가장 비싼 의존이 층을 결정합니다.</b>" },

/* ───────────── 실행과 운영 ───────────── */
{ track: "test", k: "백분위를 계산한다 · percentile", cat: "impl",
  q: "응답 시간 목록에서 <code>p</code> 백분위 값을 돌려주세요. 정렬한 뒤 <code>ceil(p/100 × 개수) - 1</code> 번째를 고르되, 범위를 벗어나면 양 끝으로 맞춥니다. 목록이 비면 0 입니다.",
  src: "function percentile(nums, p) {\n  // TODO: 원본을 건드리지 말고 정렬하세요\n  return nums[0];\n}",
  sol: "function percentile(nums, p) {\n  if (!nums.length) return 0;\n  const sorted = nums.slice().sort((a, b) => a - b);\n  const idx = Math.ceil(p / 100 * sorted.length) - 1;\n  return sorted[Math.min(Math.max(idx, 0), sorted.length - 1)];\n}",
  tests: [['percentile([1,2,3,4,5,6,7,8,9,10],50)', '5'],
    ['percentile([1,2,3,4,5,6,7,8,9,10],95)', '10'],
    ['percentile([10,1,5],100)', '10'],
    ['percentile([],95)', '0']],
  edge: [['percentile([7],50)', '7'], ['percentile([1,2,3,4],0)', '1']],
  ex: "평균은 <b>꼬리를 감춥니다.</b> 응답이 대부분 100ms 인데 5%가 3초라면 평균은 245ms 로 멀쩡해 보이지만, 스무 명 중 한 명은 3초를 기다립니다. 그 한 명이 떠나는 사람입니다.\n<code>.slice()</code> 가 빠지면 <b>원본 배열이 정렬되어</b> 호출한 쪽의 데이터가 바뀝니다. 자바스크립트의 <code>sort</code> 는 제자리 정렬이라 이 실수가 자주 나오고, 부르는 순서에 따라 결과가 달라지는 고약한 버그가 됩니다.\n비교 함수 <code>(a,b)=&gt;a-b</code> 도 빼놓을 수 없습니다. 기본 정렬은 <b>문자열로 비교</b>하므로 <code>[10,9]</code> 가 <code>[10,9]</code> 그대로 남습니다 — <code>\"10\" &lt; \"9\"</code> 이기 때문입니다. 숫자 배열을 정렬할 때는 예외 없이 비교 함수를 줍니다.\n요청이 하루 1억 건이면 p99 밖의 1%도 <b>100만 건</b>입니다. '1%뿐' 이라는 말이 얼마나 위험한지 이 계산이 보여 줍니다. 그래서 실무 대시보드는 p50·p95·p99 를 나란히 놓습니다." },

{ track: "test", k: "성능 회귀를 판정한다 · regressionVerdict", cat: "debug",
  q: "기준선과 이번 측정값, 허용 변동 비율(%)을 받아 판정해 주세요. 기준선이 0이면 <code>\"기준선 없음\"</code>, 허용치보다 나빠지면 <code>\"악화\"</code>, 허용치보다 좋아지면 <code>\"개선\"</code>, 그 사이면 <code>\"변화 없음\"</code> 입니다.",
  src: "function regressionVerdict(base, now, pct) {\n  // TODO: 변화율을 먼저 구하고 양쪽 방향을 보세요\n  return \"변화 없음\";\n}",
  sol: "function regressionVerdict(base, now, pct) {\n  if (!base) return \"기준선 없음\";\n  const worse = (now - base) / base * 100;\n  if (worse > pct) return \"악화\";\n  if (worse < -pct) return \"개선\";\n  return \"변화 없음\";\n}",
  tests: [['regressionVerdict(100,130,20)', '"악화"'],
    ['regressionVerdict(100,70,20)', '"개선"'],
    ['regressionVerdict(100,105,20)', '"변화 없음"'],
    ['regressionVerdict(0,50,20)', '"기준선 없음"']],
  edge: [['regressionVerdict(100,120,20)', '"변화 없음"'],
    ['regressionVerdict(200,100,20)', '"개선"']],
  ex: "CI 기계는 <b>실행마다 성능이 다릅니다.</b> 붐비는 시간대에는 두 배 느려지기도 합니다. 그래서 '300ms 를 넘으면 실패' 같은 절대 기준으로 걸면 무더기로 빨간불이 뜨고, 사람들은 곧 그 검사를 끕니다.\n<b>기준선 대비 비율</b>로 보면 기계의 속도 차이가 대체로 상쇄됩니다. 같은 조건에서 잰 이전 값과 비교하므로, 코드가 실제로 느려졌을 때만 신호가 뜹니다.\n첫 엣지 케이스가 <b>경계의 방향</b>을 못 박습니다. 정확히 20% 나빠진 것은 '악화' 가 아닙니다 — <code>&gt;</code> 와 <code>&gt;=</code> 중 무엇을 쓸지는 사소해 보이지만, 이 한 글자 때문에 매일 아침 경보가 울리는 팀이 실제로 있습니다. 경계는 정하고 테스트로 못 박습니다.\n'개선' 도 함께 판정하는 이유는 <b>기준선을 갱신할 때</b>를 알기 위해서입니다. 좋아진 값을 기준선에 반영하지 않으면, 다음에 다시 나빠져도 옛 기준선과 비교되어 눈치채지 못합니다." },

{ track: "test", k: "테스트를 샤드에 나눈다 · shardBalance", cat: "impl",
  q: "각 테스트의 실행 시간 목록과 샤드 개수를 받아, <b>긴 것부터 가장 한가한 샤드에</b> 넣는 방식으로 나눈 뒤 샤드별 합계를 돌려주세요.",
  src: "function shardBalance(times, n) {\n  // TODO: 내림차순으로 정렬한 뒤 매번 최솟값 자리를 고르세요\n  return times;\n}",
  sol: "function shardBalance(times, n) {\n  const totals = new Array(n).fill(0);\n  times.slice().sort((a, b) => b - a).forEach((t) => {\n    let at = 0;\n    for (let i = 1; i < n; i++) {\n      if (totals[i] < totals[at]) at = i;\n    }\n    totals[at] += t;\n  });\n  return totals;\n}",
  tests: [['shardBalance([5,4,3,2],2)', '[7,7]'],
    ['shardBalance([10],2)', '[10,0]'],
    ['shardBalance([1,1,1],3)', '[1,1,1]'],
    ['shardBalance([],2)', '[0,0]']],
  edge: [['shardBalance([8,1,1],2)', '[8,2]'], ['shardBalance([3,3],1)', '[6]']],
  ex: "테스트가 느려지면 가장 먼저 하는 일이 <b>병렬로 쪼개는 것</b>입니다. 그런데 아무렇게나 나누면 한 샤드만 오래 걸려, 전체 시간은 그 샤드가 정합니다 — 나머지는 놀면서 기다립니다.\n<b>긴 것부터 넣는</b> 이 방법을 LPT(Longest Processing Time first)라고 합니다. 최적해를 보장하지는 않지만 아주 단순하면서도 최적의 4/3배 안에 든다는 것이 증명돼 있어, 실무에서 이보다 복잡한 방법을 쓸 이유가 거의 없습니다.\n짧은 것부터 넣으면 왜 나쁜지가 <code>[8,1,1]</code> 에서 보입니다. 1·1 을 먼저 각 샤드에 하나씩 넣으면 8이 어느 쪽에 가든 <code>[9,1]</code> 이 되어 전체가 9입니다. <b>큰 덩어리를 먼저 자리 잡게 해야</b> 작은 것들이 빈틈을 메울 수 있습니다.\n실제로 이 방식을 쓰려면 <b>각 테스트의 지난 실행 시간</b>이 필요합니다. 그래서 CI 는 실행 시간 보고서를 저장해 두었다가 다음 실행의 분배에 씁니다. 파일 이름 알파벳순으로 나누는 흔한 방식이 자주 불균형해지는 이유이기도 합니다." },

{ track: "test", k: "흔들리는 테스트를 찾는다 · flakyTests", cat: "debug",
  q: "테스트 이름 목록과 여러 번 실행한 결과(실행마다 이름 순서에 맞춘 성공 여부 배열)를 받아, <b>성공과 실패가 둘 다 있었던</b> 테스트 이름을 원래 순서로 돌려주세요.",
  src: "function flakyTests(names, results) {\n  // TODO: 이름마다 세로로(여러 실행에 걸쳐) 모아 보세요\n  return [];\n}",
  sol: "function flakyTests(names, results) {\n  return names.filter((nm, i) => {\n    const col = results.map((r) => r[i]);\n    return col.indexOf(true) >= 0 && col.indexOf(false) >= 0;\n  });\n}",
  tests: [['flakyTests(["a","b"],[[true,true],[false,true]])', '["a"]'],
    ['flakyTests(["a"],[[true],[true]])', '[]'],
    ['flakyTests(["a","b"],[[false,false],[true,true]])', '["a","b"]'],
    ['flakyTests([],[[]])', '[]']],
  edge: [['flakyTests(["a"],[[true]])', '[]'],
    ['flakyTests(["a","b"],[[true,false],[true,false]])', '[]']],
  ex: "<b>플레이키 테스트</b>는 같은 코드에서 어떤 때는 통과하고 어떤 때는 실패합니다. 진짜 실패보다 나쁩니다 — 사람들이 빨간불을 무시하기 시작하고, 그 순간 스위트 전체가 값어치를 잃기 때문입니다.\n찾는 방법은 단순합니다. <b>같은 커밋에서 여러 번 돌려 보고</b>, 결과가 섞이는 것을 고릅니다. 이 함수는 '세로로 본다' 는 그 생각을 그대로 옮긴 것입니다.\n마지막 엣지 케이스가 중요한 구분입니다. 매번 실패하는 테스트는 <b>플레이키가 아닙니다</b> — 그냥 실패하는 것이고, 진짜 버그거나 잘못 쓴 테스트입니다. 이 둘을 섞어 다루면 진짜 실패를 '또 흔들리네' 로 넘기는 사고가 납니다.\n찾은 뒤가 진짜 문제입니다. <b>재시도로 덮으면 원인이 사라지지 않고 숨습니다.</b> 원인은 대개 고정 시간 대기, 테스트 간 상태 공유, 시간·난수·순서 의존 넷 중 하나입니다. 당장 고칠 수 없다면 격리해서 표시하되, 기한과 담당자를 함께 정해 두어야 영원히 남지 않습니다." },
];
