const path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');let passed=0;function check(name,condition){assert.ok(condition,name);passed++;console.log('PASS '+name);}
(async()=>{const browser=await chromium.launch({channel:'msedge'});try{const p=await browser.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>{if(top===window)localStorage.setItem('coderun',JSON.stringify({onboarded:true,freeMode:true,recall:false}));});await p.goto('file:///'+path.resolve(__dirname,'../index.html').replace(/\\/g,'/'));await p.waitForFunction(()=>typeof CodeLiteracy!=='undefined');
check('AI와 만들면서 코드의 뜻을 배우는 목표를 안내한다',await p.locator('.study-welcome').innerText().then(t=>t.includes('AI가 만든 코드')&&t.includes('내 손으로 고칠')));
check('SQL 인덱스와 배열 위치의 뜻을 섞지 않는다',await p.evaluate(()=>{const list=CodeLiteracy.related({t:'sql',q:'인덱스로 조회를 빠르게 만들기'},null,'sql');return list.some(t=>t[0]==='DB 인덱스')&&!list.some(t=>t[0]==='인덱스 · 값의 위치');}));
const q={t:'code',run:'js',k:'literacy',q:'함수에서 숫자를 반환하세요.',src:'function value(){return 1;}',sol:'function value(){return 7;}',tests:[{in:'value()',out:'7'}],ex:'값을 반환해요.'};await p.evaluate(q=>{run={lang:'javascript',les:{title:'함수',q:[q],xp:10},i:0,total:1,correct:0,hearts:5,id:null,free:true,studyAnswers:[]};openRun();},q);
check('뜻 설명은 처음에 접혀 있어 문제 읽기를 막지 않는다',await p.locator('.study-literacy').evaluate(el=>!el.open));await p.locator('.study-literacy summary').click();check('함수와 return의 뜻을 쉬운 예시로 보여 준다',await p.locator('.study-literacy').innerText().then(t=>t.includes('다시 쓸 수 있게 묶은 코드')&&t.includes('호출한 곳으로 결과')));await p.waitForTimeout(100);check('개념의 도움을 받은 기록을 남긴다',await p.evaluate(()=>run.studyHinted));
await p.locator('#livecode').fill('function value(){return 2;}');await p.locator('#study-ai-prompt-open').click();const prompt=await p.locator('#study-ai-prompt').inputValue();check('질문은 현재 편집한 코드를 담고 기준 정답을 포함하지 않는다',prompt.includes('return 2;')&&!prompt.includes('return 7;'));check('AI에게 설명·한 가지 수정·테스트를 함께 요청한다',prompt.includes('입력 → 처리 → 결과')&&prompt.includes('정답 코드를 바로 완성하지')&&prompt.includes('잘못된 입력'));check('질문 만들기만으로 외부 요청이나 채점을 하지 않는다',await p.evaluate(()=>!run.answered&&run.correct===0));
await p.locator('#check').click();await p.waitForSelector('#study-retry');await p.locator('#study-retry').click();await p.locator('#livecode').fill(q.sol);await p.locator('#check').click();await p.waitForSelector('.study-explanation.correct');check('설명 도구와 코드 수정·재검사를 함께 쓸 수 있다',await p.evaluate(()=>run.correct===1));check('브라우저 실행 오류가 없다',errors.length===0);console.log(passed+' literacy checks passed');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
