const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const {chromium}=require('playwright');const root=path.resolve(__dirname,'..'),cases=[];
for(const name of fs.readdirSync(path.join(root,'data')).filter(n=>/^t-.*\.js$/.test(n))){let units;vm.runInNewContext(fs.readFileSync(path.join(root,'data',name),'utf8'),{__CR:(k,v)=>units=v});for(const u of units)for(const l of u.l)for(const q of l.q)if(q.sol&&['html','react'].includes(q.t))cases.push({name:name+':'+q.k,q});}
(async()=>{const browser=await chromium.launch(process.env.PLAYWRIGHT_CHROMIUM?{executablePath:process.env.PLAYWRIGHT_CHROMIUM}:{channel:'msedge'});try{const page=await browser.newPage();await page.addInitScript(()=>{if(top===window)localStorage.setItem('coderun',JSON.stringify({onboarded:true,goal:'free',freeMode:true,recall:false}));});await page.goto(process.env.CR_URL||'file:///'+path.join(root,'index.html').replace(/\\/g,'/'));await page.waitForFunction(()=>typeof DOMPractice!=='undefined');
 const semantic=await page.evaluate(()=>{const source="function strict(){'use strict';return this===undefined;}const make=()=>({n:3});let n=0;for(let i=0;i<3;i++)if(i<2)n++;else n+=2;do n--;while(n>3);[strict(),make().n,n]";return new Function('__crSafetyTick',DOMPractice.instrument(source).replace('[strict(),make().n,n]','return [strict(),make().n,n];'))(()=>{});});assert.deepEqual(semantic,[true,3,3]);console.log('PASS 안전 검사 추가 뒤 원래 코드 의미 유지');
 async function grade(q,source){return page.evaluate(async({q,source})=>{run={lang:'web',les:{title:'화면 검사',xp:10,q:[q]},i:0,correct:0,total:1,hearts:5,id:null,color:'#32664b',free:true,studyAnswers:[]};openRun();$('livecode').value=source;onCheck();const end=performance.now()+15000;while(!run.answered&&performance.now()<end)await new Promise(r=>setTimeout(r,80));return {answered:run.answered,correct:run.correct,result:liveTest,message:$('foot-msg').textContent,...(!run.answered?{srcdoc:$('liveview').srcdoc,editor:$('livecode').value}:{} )};},{q,source});}
 const basic={t:'html',k:'safety',q:'제목 만들기',tests:[{d:'제목',js:"TXT('h1')==='안녕'"}],ex:'제목을 넣어요.',src:'<h1>안녕</h1>'};
 const loop=await grade(basic,'<h1>안녕</h1><script>while(true){}</script>');if(!loop.answered)console.log('LOOP_FAIL '+JSON.stringify(loop));assert.equal(loop.answered,true);assert.equal(loop.correct,0);assert.match(loop.result.error,/1초/);console.log('PASS HTML 미리보기의 무한 반복을 끝내고 오류 표시');
 const recovery=await grade(basic,'<h1>안녕</h1>');assert.equal(recovery.correct,1);console.log('PASS 실행 제한 뒤 정상 HTML 검사 복구');
 await page.evaluate(()=>Promise.all([ensureSucrase(),ensureReactSrc()]));
 const reactLoop={t:'react',k:'react-safety',q:'컴포넌트',tests:[{d:'글자',js:"TXT('#root')==='안녕'"}],src:'function App(){return <p>안녕</p>}',ex:'컴포넌트를 반환해요.'};
 const blocked=await grade(reactLoop,'function App(){while(true){};return <p>안녕</p>}');assert.equal(blocked.answered,true);assert.equal(blocked.correct,0);console.log('PASS React 컴포넌트 안의 무한 반복도 종료');
 const syntax=await grade(reactLoop,'function App( {');assert.equal(syntax.answered,true);assert.equal(syntax.correct,0);assert.match(syntax.result.error,/문법/);console.log('PASS React 문법 오류는 기다리지 않고 표시');
 const asyncReact=await grade({...reactLoop,tests:[{d:'느린 검사',js:"new Promise(r=>setTimeout(()=>r(TXT('#root')==='안녕'),1200))"}]},reactLoop.src);assert.equal(asyncReact.correct,1);console.log('PASS 900ms보다 긴 React 검사도 결과를 기다려 판정');
 let passed=0;const failures=[];
 for(const c of cases){const r=await grade(c.q,c.q.sol);if(r.correct===1)passed++;else failures.push({name:c.name,result:r.result,message:r.message});if(passed%20===0)console.log(passed+' DOM reference checks');}
 console.log(JSON.stringify({passed,total:cases.length,failures}));assert.equal(failures.length,0,'HTML/React reference code must pass');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
