const assert=require('node:assert/strict'),path=require('node:path');
const {chromium}=require('playwright');let count=0;
function check(name,value){assert.ok(value,name);count++;console.log('PASS '+name);}
(async()=>{
 const browser=await chromium.launch(process.env.PLAYWRIGHT_CHROMIUM?{executablePath:process.env.PLAYWRIGHT_CHROMIUM}:{channel:'msedge'});
 try{
  const context=await browser.newContext({viewport:{width:1440,height:1100}}),page=await context.newPage(),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto(process.env.CR_URL||'file:///'+path.resolve(__dirname,'../index.html').replace(/\\/g,'/'));
  await page.locator('[data-experience=new]').click();await page.locator('#study-setup-start').click();
  await page.waitForFunction(()=>typeof VibeLab!=='undefined'&&trackLoaded(curLang));
  check('작은 앱이 홈의 기본 시작 버튼',await page.locator('#vibe-start').isVisible());
  await page.locator('#vibe-start').click();await page.waitForSelector('#vibe-preview');
  await page.waitForFunction(()=>$('vibe-preview-status').textContent==='입력하고 눌러 볼 수 있어요');
  check('홈은 입문 장바구니부터 추천',await page.locator('.vibe-mission-heading').innerText().then(t=>t.includes('장바구니')));
  check('대화창 밖 화면은 키보드 접근을 막음',await page.evaluate(()=>document.querySelector('.study-shell').inert&&$('vibe-lab').getAttribute('aria-modal')==='true'));
  const frame=page.frameLocator('#vibe-preview');await frame.locator('#qty').fill('3');
  check('오류를 실제 화면에서 확인할 수 있음',await frame.locator('#subtotal').innerText().then(t=>t.includes('10,000')));
  check('미리보기만 열어도 완료 처리되지 않음',await page.evaluate(()=>VibeLab.progress().done===0&&!S.vibeLab.cart.missions.quantity?.lastCheck));
  await page.locator('.vibe-common-terms summary').click();
  check('입력·처리·화면 흐름과 기초 문법 설명 제공',await page.locator('.vibe-code-flow li').count()===3&&await page.locator('.vibe-common-terms').innerText().then(t=>t.includes('querySelector')&&t.includes('const')));
  await page.locator('.vibe-common-terms summary').click();
  async function grade(source,id='cart',mission='quantity'){
   if(source!==undefined)await page.locator('#vibe-code').fill(source);
   await page.locator('#vibe-check').click();
   await page.waitForFunction(({id,mission})=>!!S.vibeLab[id].missions[mission]?.lastCheck,{id,mission},{timeout:18000});
   return page.evaluate(({id,mission})=>S.vibeLab[id].missions[mission].lastCheck,{id,mission});
  }
  await page.locator('#vibe-editor-full').click();
  let result=await grade();check('초안의 잘못된 계산은 검사에서 실패',!result.gate&&result.pass<result.total);
  const sources=await page.evaluate(()=>VibeLab.projects[0].missions.map(m=>m.reference));
  await page.locator('#vibe-code').fill(sources[0]);
  check('입력만 하면 실행하거나 채점하지 않음',await page.evaluate(()=>!S.vibeLab.cart.missions.quantity.lastCheck)&&await frame.locator('#subtotal').innerText().then(t=>t.includes('10,000')));
  result=await grade();check('올바른 계산과 경계값 검사 통과',result.gate&&result.pass===4);
  check('동작만 통과하면 뜻 확인 안내',await page.locator('.vibe-readiness').count()===1&&await page.locator('#vibe-next').count()===0);
  const answer=await page.evaluate(()=>VibeLab.projects[0].missions[0].quiz.answer);
  await page.locator('[data-vibe-answer="'+((answer+1)%3)+'"]').click();
  check('잘못 이해한 답은 완료 처리되지 않음',await page.evaluate(()=>VibeLab.progress().done===0));
  await page.locator('[data-vibe-answer="'+answer+'"]').click();
  check('동작과 뜻을 확인하면 한 단계 완료',await page.evaluate(()=>VibeLab.progress().done===1));
  await page.locator('#vibe-note').fill('수량을 계산에 넣지 않았기 때문에 곱하도록 고쳤다.');
  check('고친 이유를 기존 공부 노트에도 보관',await page.evaluate(()=>S.studyNotes['vibe:cart:quantity'].text.includes('수량')));
  await page.locator('#vibe-next').click();await page.waitForFunction(()=>$('vibe-preview-status').textContent==='입력하고 눌러 볼 수 있어요');
  check('다음 단계는 고친 코드를 이어서 사용',await page.locator('#vibe-code').inputValue().then(t=>t===sources[0]));
  await page.locator('#vibe-close').click();await page.reload();await page.waitForFunction(()=>typeof VibeLab!=='undefined');
  await page.locator('#vibe-start').click();await page.waitForSelector('#vibe-code');
  check('새로고침 뒤 코드·완료·다음 단계 복원',await page.evaluate(()=>S.vibeLab.cart.currentMission===1&&S.vibeLab.cart.missions.quantity.passed)&&await page.locator('#vibe-code').inputValue().then(t=>t===sources[0]));
  result=await grade(sources[1],'cart','delivery');check('배송비 기능 추가도 경계값 검사 통과',result.gate&&result.pass===4);
  await page.locator('[data-vibe-answer="'+await page.evaluate(()=>VibeLab.projects[0].missions[1].quiz.answer)+'"]').click();
  check('두 단계의 완료 기록을 따로 저장',await page.evaluate(()=>VibeLab.progress().done===2));
  await page.locator('.vibe-help summary').click();await page.locator('#vibe-prompt-open').click();
  check('AI 질문에 내 코드·요구사항·화면 뼈대 포함',await page.locator('#vibe-prompt').inputValue().then(t=>t.includes(sources[1])&&t.includes('index.html')&&t.includes('30,000')));
  await page.locator('#vibe-reference-open').click();check('예시 풀이 보기만으로 코드를 덮어쓰지 않음',await page.locator('#vibe-code').inputValue().then(t=>t===sources[1]));
  await page.locator('#vibe-reset').click();await page.waitForSelector('#confirm.on');
  check('초안 복원은 현재 코드를 보여 준 뒤 확인',await page.evaluate(()=>$('vibe-lab').inert&&$('confirm').getAttribute('aria-modal')==='true'));
  await page.locator('#confirm-no').click();check('복원 취소하면 코드 유지',await page.locator('#vibe-code').inputValue().then(t=>t===sources[1]));
  await page.locator('#vibe-reset').click();await page.locator('#confirm-yes').click();
  check('초안 복원해도 완료 기록과 정리 메모 보존',await page.evaluate(()=>S.vibeLab.cart.source===VibeLab.projects[0].source&&VibeLab.progress().done===2&&S.studyNotes['vibe:cart:quantity'].text.includes('수량')));
  await page.locator('#vibe-catalog').click();check('실습 모음에는 여섯 앱',await page.locator('[data-vibe-project]').count()===6);
  await page.locator('[data-vibe-project=form]').click();await page.waitForFunction(()=>$('vibe-preview-status').textContent==='입력하고 눌러 볼 수 있어요');
  await page.locator('#vibe-code').fill(await page.evaluate(()=>VibeLab.projects.find(p=>p.id==='form').missions[0].reference));await page.locator('#vibe-preview-run').click();
  await page.waitForFunction(()=>$('vibe-preview-status').textContent==='입력하고 눌러 볼 수 있어요');
  const form=page.frameLocator('#vibe-preview');await form.locator('#password').fill('abcdefgh');await form.locator('#submit').click();
  check('실제 폼 버튼으로 필수 입력 실패 이유 표시',await form.locator('#error').innerText().then(t=>t.includes('입력'))&&await form.locator('#success').isHidden());
  await form.locator('#email').fill('hello@example.com');await form.locator('#submit').click();check('실제 폼 버튼으로 정상 입력 확인',await form.locator('#success').isVisible());
  await page.locator('#vibe-catalog').click();
  await page.locator('[data-vibe-project=request]').click();await page.waitForFunction(()=>$('vibe-preview-status').textContent==='입력하고 눌러 볼 수 있어요');
  const apiSource=await page.evaluate(()=>VibeLab.projects.find(p=>p.id==='request').missions[0].reference);
  await page.locator('#vibe-code').fill(apiSource);await page.locator('#vibe-check').click();
  check('비동기 검사 중 코드·파일 변경을 잠금',await page.evaluate(()=>$('vibe-code').readOnly&&$('vibe-file-js').disabled&&$('vibe-file-html').disabled&&$('vibe-check').disabled));
  await page.locator('#vibe-catalog').click();await page.locator('[data-vibe-project=memo]').click();
  await page.waitForFunction(()=>$('vibe-preview-status').textContent==='입력하고 눌러 볼 수 있어요');
  check('검사 중 다른 앱을 열면 이전 검사는 완료 기록을 남기지 않음',await page.evaluate(()=>!S.vibeLab.request.missions.finish.lastCheck&&!S.vibeLab.memo.missions.text?.lastCheck));
  const memoSource=await page.locator('#vibe-code').inputValue();
  result=await grade('while (true) {}','memo','text');check('끝나지 않는 코드는 멈추고 이유를 표시',!result.gate&&/1초/.test(result.error));
  result=await grade('const = ;','memo','text');check('문법 오류는 통과시키지 않음',!result.gate&&/문법/.test(result.error));
  const memoFix=await page.evaluate(()=>VibeLab.projects.find(p=>p.id==='memo').missions[0].reference);
  result=await grade(memoFix,'memo','text');check('실행 오류 뒤 정상 코드로 복구',result.gate);
  await grade(memoFix+'\nsetTimeout(() => { throw new Error("나중에 오류"); }, 250);','memo','text');
  await page.waitForFunction(()=>S.vibeLab.memo.missions.text.lastCheck.error.includes('나중에 오류'));
  check('검사 뒤 발생한 실행 오류도 현재 통과 상태를 취소',await page.evaluate(()=>!S.vibeLab.memo.missions.text.lastCheck.gate)&&await page.locator('#vibe-next').count()===0);
  await grade(memoFix+'\nPromise.reject(new Error("요청 실패"));','memo','text');
  await page.waitForFunction(()=>S.vibeLab.memo.missions.text.lastCheck.error.includes('요청 실패'));
  check('처리하지 못한 비동기 오류도 이유를 표시',await page.evaluate(()=>!S.vibeLab.memo.missions.text.lastCheck.gate));
  await grade(memoFix,'memo','text');
  await page.locator('#vibe-file-html').click();check('HTML 뼈대는 읽기 전용',await page.evaluate(()=>$('vibe-code').readOnly));await page.locator('#vibe-file-js').click();
  check('파일 탭 전환으로 JavaScript 코드 보존',await page.locator('#vibe-code').inputValue().then(t=>t===memoFix));
  await page.keyboard.press('Escape');await page.waitForFunction(()=>!$('vibe-lab').classList.contains('on'));
  check('Escape로 닫고 홈 버튼으로 초점 복귀',await page.evaluate(()=>!document.querySelector('.study-shell').inert&&document.activeElement.id==='vibe-start'));
  check('편집하던 다른 앱을 홈에서 이어 하기',await page.evaluate(()=>VibeLab.recommend().project.id==='memo'));
  await page.setViewportSize({width:390,height:844});await page.locator('#vibe-start').click();await page.waitForSelector('#vibe-code',{state:'attached'});
  check('휴대폰은 실행 화면부터 보이고 코드 탭은 분리',await page.locator('[data-vibe-panel=preview]').isVisible()&&!await page.locator('[data-vibe-panel=editor]').isVisible());
  check('앱 높이에 맞춰 미리보기 높이를 조정',await page.locator('#vibe-preview').evaluate(e=>parseInt(e.style.height)>300));
  await page.locator('[data-vibe-pane=editor]').click();check('휴대폰에서 코드 탭으로 바꿀 수 있음',await page.locator('#vibe-code').isVisible());
  check('휴대폰 실습에 가로 넘침 없음',await page.evaluate(()=>$('vibe-body').scrollWidth<=$('vibe-body').clientWidth+1));
  await page.evaluate(()=>document.documentElement.dataset.theme='dark');check('야간 모드 코드 글자가 배경과 구분됨',await page.locator('#vibe-code').evaluate(e=>getComputedStyle(e).color!==getComputedStyle(e).backgroundColor));
  check('앱에서 처리하지 못한 브라우저 오류 없음',errors.length===0);
  console.log(JSON.stringify({checks:count,errors}));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
