const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs'),os=require('node:os'),{chromium}=require('playwright');
const base=require('../data/vibe-scenarios.js'),projects=[...base,...require('../data/vibe-challenges.js')(base),...require('../data/vibe-projects.js')],journey=require('../data/vibe-journey.js')(projects);let count=0;
function check(name,value){assert.ok(value,name);count++;console.log('PASS '+name);}
const state={vibeLab:{}};for(const p of base)state.vibeLab[p.id]={missions:Object.fromEntries(p.missions.map(m=>[m.id,{passed:true}]))};
check('기존 완료 기록 뒤에는 새 상황을 추천',journey.recommend(state,'2026-10-04',1).project.kind==='transfer');
const transfer=journey.transfer(state,'cart');journey.complete(state,transfer,{helpUsed:true},'2026-10-04');check('도움받은 성공은 독립 적용 수를 올리지 않음',journey.stats(state,'2026-10-04').independent===0);
const own={};journey.complete(state,journey.transfer(state,'cart'),own,'2026-10-04');journey.complete(state,transfer,own,'2026-10-04');check('같은 성공을 중복 기록하지 않음',journey.evidence(state,'cart').successes===1);check('첫 독립 적용은 다음 날 다시 떠올리기',journey.evidence(state,'cart').due==='2026-10-05');
check('복습할 때 다른 변형을 추천',journey.recommend(state,'2026-10-05',1).review&&journey.recommend(state,'2026-10-05',1).project.variant===2);
journey.complete(state,journey.transfer(state,'cart'),{},'2026-10-05');check('다시 독립 적용하면 복습 간격 3일',journey.evidence(state,'cart').due==='2026-10-08');
const runtimeState={},runtimeProject=projects.find(p=>p.id==='cart-transfer-0'),runtimeRecord={};journey.complete(runtimeState,runtimeProject,runtimeRecord,'2026-10-04');journey.invalidate(runtimeState,runtimeProject,runtimeRecord);check('늦은 실행 오류는 이번 독립 적용 기록도 취소',!journey.evidence(runtimeState,'cart').independent&&!runtimeRecord.passed);
check('날짜 경계 계산',journey.dates('2026-12-31',1)==='2027-01-01'&&journey.dates('2028-02-28',1)==='2028-02-29');
for(const family of journey.families)journey.evidence(state,family).independent=true;check('여섯 개념 적용 뒤 실제 앱 추천',journey.recommend(state,'2026-10-06',1).project.kind==='capstone');
const cap=projects.find(p=>p.kind==='capstone');state.vibeLab[cap.id]={missions:Object.fromEntries(cap.missions.map(m=>[m.id,{passed:true}]))};check('독서 앱 뒤에는 완성 프로젝트로 연결',journey.recommend(state,'2026-10-06',1).project.id==='expense-app');
for(const p of journey.collection)state.vibeLab[p.id]={missions:Object.fromEntries(p.missions.map(m=>[m.id,{passed:true}]))};check('모두 끝나면 첫 장바구니로 돌아가지 않음',journey.recommend(state,'2026-10-06',1).complete);
(async()=>{const browser=await chromium.launch(process.env.PLAYWRIGHT_CHROMIUM?{executablePath:process.env.PLAYWRIGHT_CHROMIUM}:process.platform==='win32'?{channel:'msedge'}:{}),temp=fs.mkdtempSync(path.join(os.tmpdir(),'coderun-journey-'));try{
 const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{if(top===window&&!localStorage.getItem('coderun'))localStorage.setItem('coderun',JSON.stringify({onboarded:true,goal:'free',freeMode:true,recall:false,theme:'light',learning:{experience:'new',minutes:10,configured:true,recent:[],trackLevels:{}}}));});
 await page.goto('file:///'+path.resolve(__dirname,'../index.html').replace(/\\/g,'/'));await page.waitForFunction(()=>typeof VibeLab!=='undefined');await page.locator('#vibe-start').click();
 check('처음에는 계산 한 줄만 편집',await page.locator('#vibe-code').inputValue().then(v=>v.trim()==='const subtotal = price;'));
 check('가격·수량의 뜻과 기대 결과가 코드 바로 옆에 있음',await page.locator('#vibe-inline-guide').innerText().then(v=>v.includes('한 권 가격')&&v.includes('20,000')));
 await page.locator('#vibe-code').fill('  const changed = price;');await page.locator('#vibe-code').press('End');await page.locator('#vibe-code').press('Space');
 check('줄 이름을 지워도 전체 화면 코드 보존',await page.evaluate(()=>S.vibeLab.cart.source.includes('function renderPrice')&&S.vibeLab.cart.source.includes('const changed = price; ')));
 await page.locator('#vibe-file-html').click();await page.locator('#vibe-file-js').click();
 check('찾을 줄이 없어지면 전체 코드로 안전하게 표시',await page.locator('#vibe-code').inputValue().then(v=>v.includes('function renderPrice')));
 await page.evaluate(()=>{S.vibeLab.cart.source=VibeLab.projects[0].source;S.vibeLab.cart.fullCode=false;VibeLab.select('cart',0);});
 await page.locator('#vibe-code').fill('  const subtotal = price * quantity;');
 async function grade(id,mission){await page.locator('#vibe-check').click();await page.waitForFunction(({id,mission})=>!!S.vibeLab[id]?.missions?.[mission]?.lastCheck,{id,mission},{timeout:20000});return page.evaluate(({id,mission})=>S.vibeLab[id].missions[mission].lastCheck,{id,mission});}
 check('한 줄 수정이 실제 전체 앱에서 검사됨',(await grade('cart','quantity')).gate);await page.locator('[data-vibe-answer="0"]').click();await page.locator('#vibe-next').click();
 await page.locator('#vibe-code').fill('  const shipping = subtotal === 0 || subtotal >= 30000 ? 0 : 3000;');check('다음 한 줄도 앞의 수정을 유지',(await grade('cart','delivery')).gate);await page.locator('[data-vibe-answer="1"]').click();await page.locator('#vibe-next').click();
 check('같은 앱의 두 단계 뒤 새 예약 상황으로 연결',await page.evaluate(()=>S.vibeLast.id==='cart-transfer-0'));
 check('혼자 적용할 때는 전체 코드를 제공',await page.locator('#vibe-code').inputValue().then(v=>v.includes('#seats')&&v.includes('8000')));
 await page.locator('.vibe-help summary').click();await page.locator('#vibe-reference-open').click();await page.locator('#vibe-close').click();await page.reload();await page.waitForFunction(()=>typeof VibeLab!=='undefined');await page.locator('#vibe-start').click();
 check('예시를 본 기록은 새로고침 뒤에도 유지',await page.evaluate(()=>S.vibeLab['cart-transfer-0'].missions.transfer.helpUsed));
  await page.locator('#vibe-catalog').click();await page.locator('[data-vibe-transfer=cart]').click();check('실습 모음으로 다시 열어도 도움 기록 유지',await page.evaluate(()=>S.vibeLab['cart-transfer-0'].missions.transfer.helpUsed));
 await page.locator('#vibe-code').fill(await page.evaluate(()=>VibeLab.projects.find(p=>p.id==='cart-transfer-0').missions[0].reference));check('새 상황의 실제 8개 검사 통과',(await grade('cart-transfer-0','transfer')).gate);await page.locator('[data-vibe-answer="1"]').click();
 check('도움받은 성공은 학습 완료로만 기록',await page.evaluate(()=>!VibeJourney.evidence(S,'cart').independent)&&await page.locator('#vibe-finish').innerText().then(v=>v.includes('도움받아')));
 await page.locator('#vibe-next').click();check('다시 풀기는 값과 이름이 바뀐 변형으로',await page.evaluate(()=>S.vibeLast.id==='cart-transfer-1')&&await page.locator('#vibe-code').inputValue().then(v=>v.includes('12000')));
 await page.locator('#vibe-code').fill(await page.evaluate(()=>VibeLab.projects.find(p=>p.id==='cart-transfer-1').missions[0].reference));await grade('cart-transfer-1','transfer');await page.locator('[data-vibe-answer="1"]').click();
 check('앱 도움을 열지 않은 적용과 복습 날짜를 따로 보관',await page.evaluate(()=>VibeJourney.evidence(S,'cart').independent&&VibeJourney.stats(S,today()).independent===1&&VibeJourney.evidence(S,'cart').due>today()));
 await page.evaluate(()=>VibeLab.select('bookshelf',0));
 for(const [index,id] of ['find','edit','save'].entries()){
  await page.locator('#vibe-code').fill(cap.missions[index].reference);check('내 앱 '+id+' 실제 검사',(await grade('bookshelf',id)).gate);await page.locator('[data-vibe-answer="'+cap.missions[index].quiz.answer+'"]').click();if(index<2)await page.locator('#vibe-next').click();
 }
 check('완성 앱을 실제 파일로 받을 수 있음',await page.locator('#vibe-export').isVisible());
 await page.locator('#vibe-preview-run').click();await page.waitForFunction(()=>$('vibe-preview-status').textContent==='입력하고 눌러 볼 수 있어요');const demo=page.frameLocator('#vibe-preview');await demo.locator('#book-title').fill('미리보기의 내 책');await demo.locator('#book-add').click();await page.waitForFunction(()=>S.vibeLab.bookshelf.previewBooks?.some(b=>b.title==='미리보기의 내 책'));await grade('bookshelf','save');check('채점용 저장 목록은 내 미리보기 데이터를 덮지 않음',await page.evaluate(()=>S.vibeLab.bookshelf.previewBooks.some(b=>b.title==='미리보기의 내 책')&&!S.vibeLab.bookshelf.previewBooks.some(b=>b.title==='저장된 책')));await page.locator('#vibe-preview-run').click();await page.waitForFunction(()=>$('vibe-preview-status').textContent==='입력하고 눌러 볼 수 있어요');check('미리보기도 다시 실행하면 내 목록 복원',await demo.locator('#book-list').innerText().then(v=>v.includes('미리보기의 내 책')));
 const downloadPromise=page.waitForEvent('download');await page.locator('#vibe-export').click();const download=await downloadPromise,file=path.join(temp,'my-bookshelf.html');await download.saveAs(file);check('내보낸 파일은 전체 앱과 저장 함수를 포함',fs.readFileSync(file,'utf8').includes('localStorage.setItem')&&fs.readFileSync(file,'utf8').includes('book-form'));
 const exported=await browser.newPage();exported.on('pageerror',e=>errors.push(e.message));await exported.goto('file:///'+file.replace(/\\/g,'/'));await exported.locator('#book-title').fill('<b>내가 추가한 책</b>');await exported.locator('#book-add').click();await exported.reload();check('내보낸 앱에서 추가한 책이 새로고침 뒤 복원',await exported.locator('#book-list').innerText().then(v=>v.includes('<b>내가 추가한 책</b>'))&&await exported.locator('#book-list b').count()===0);await exported.locator('[data-book-filter=unread]').click();await exported.locator('.task').filter({hasText:'내가 추가한 책'}).locator('input').click();await exported.reload();check('내보낸 앱에서 읽음 상태도 복원',await exported.locator('.task').filter({hasText:'내가 추가한 책'}).locator('input').isChecked());
 await page.locator('#vibe-next').click();check('완성 뒤 프로젝트·Git·장애·운영으로 연결',await page.locator('[data-vibe-route]').count()===7);await page.locator('[data-vibe-route=git]').click();check('Git 버튼이 실제 실습을 엶',await page.locator('#gitlab.on').count()===1);
 await page.locator('#gl-quit').click();await page.evaluate(()=>VibeLab.open('route'));await page.locator('[data-vibe-route=build]').click();await page.waitForFunction(()=>!!BL);check('다음 프로젝트는 실제 초급 빌드 워크스페이스로 연결',await page.evaluate(()=>BUILD_PROJECTS[BL.pi].lv<=3&&$('blab').classList.contains('on')));await page.locator('#bl-quit').click();
 await page.setViewportSize({width:360,height:800});check('휴대폰에서 네 가지 공부 메뉴 접근',await page.locator('#vibe-mobile-nav button:visible').count()===4);await page.locator('[data-mobile-nav=apps]').click();check('휴대폰 메뉴에서 앱 모음이 실제로 열림',await page.locator('[data-vibe-project]').count()===6);check('휴대폰 앱 모음과 성장 카드에 가로 넘침 없음',await page.evaluate(()=>$('vibe-body').scrollWidth<=$('vibe-body').clientWidth+1));await page.locator('#vibe-close').click();await page.locator('[data-mobile-nav=records]').click();check('내 기록에 도움과 독립 적용 근거가 표시',await page.locator('.vibe-coach-evidence').innerText().then(v=>v.includes('앱 도움 없이 적용 1/6')&&v.includes('다음 복습')));
 check('처리하지 못한 브라우저 오류 없음',errors.length===0);console.log(JSON.stringify({checks:count,errors}));
}finally{await browser.close();assert.ok(path.resolve(temp).startsWith(path.resolve(os.tmpdir())+path.sep)&&path.basename(temp).startsWith('coderun-journey-'));fs.rmSync(temp,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
